Repository PaddlePaddle/Paddle, pull requests merged in 2018-08, with the labels that each got.

#12618 fix UT for mkldnn 0.15
  paddle/fluid/operators/conv_mkldnn_op.cc
  paddle/fluid/platform/mkldnn_helper.h
  python/paddle/fluid/tests/unittests/test_conv2d_mkldnn_op.py
  python/paddle/fluid/tests/unittests/test_conv2d_op.py
Labels: Intel, MKL, enhancement, unitest

#12563 make inference_anakin_test SERIAL
  cmake/configure.cmake
  cmake/external/anakin.cmake
  cmake/inference_lib.cmake
  paddle/fluid/inference/api/CMakeLists.txt
Labels: Inference

#12669 Fuse Convolution and Eltwise Add into MKLDNN's Conv+Bias
  paddle/fluid/operators/conv_mkldnn_op.cc
  paddle/fluid/operators/conv_op.cc
  paddle/fluid/platform/mkldnn_helper.h
  python/paddle/fluid/transpiler/inference_transpiler.py
Labels: Intel

#12675 Update MKLDNN to 0.15, fix convolution integration
  cmake/external/mkldnn.cmake
  paddle/fluid/framework/tensor.cc
  paddle/fluid/framework/tensor.h
  paddle/fluid/framework/tensor_impl.h
  paddle/fluid/operators/conv_mkldnn_op.cc
Labels: Intel

#12515 Reusing primitives for forward Batch Norm operator
  paddle/fluid/operators/batch_norm_mkldnn_op.cc
Labels: Intel

#12982 Enforce requested size of tensor to be sufficiently large
  paddle/fluid/framework/tensor.cc
Labels: Intel, enhancement
