Repository PaddlePaddle/Paddle, pull requests merged in 2018-06, with the labels that each got.

#11090 add build and install document of fluid inference library
  doc/fluid/howto/index_cn.rst
  doc/fluid/howto/index_en.rst
  doc/fluid/howto/inference/build_and_install_lib_cn.rst
  doc/fluid/howto/inference/index_cn.rst
  doc/fluid/howto/inference/inference_support_in_fluid_cn.md
Labels: Inference

#11105 feature/simple inference demo
  paddle/contrib/inference/CMakeLists.txt
  paddle/contrib/inference/demo/CMakeLists.txt
  paddle/contrib/inference/demo/simple_on_word2vec.cc
  paddle/contrib/inference/paddle_inference_api_impl.cc
  paddle/contrib/inference/test_paddle_inference_api_impl.cc
Labels: Inference

#11147 rename Mkldnn to MKLDNN
  paddle/fluid/operators/activation_mkldnn_op.cc
Labels: Intel

#11162 enable infer api with multi-threads
  paddle/contrib/inference/demo/simple_on_word2vec.cc
  paddle/contrib/inference/paddle_inference_api.h
  paddle/contrib/inference/paddle_inference_api_impl.cc
  paddle/contrib/inference/paddle_inference_api_impl.h
Labels: Inference

#11211 add dfg graphviz pass
  paddle/fluid/inference/analysis/CMakeLists.txt
  paddle/fluid/inference/analysis/dfg_graphviz_draw_pass.h
  paddle/fluid/inference/analysis/dfg_graphviz_draw_pass_tester.cc
Labels: Inference

#11233 Fix abort issue in cpu multi-threads
  paddle/fluid/framework/scope.cc
  paddle/fluid/framework/scope.h
  paddle/fluid/inference/tests/book/test_inference_nlp.cc
Labels: Inference

#11222 rewrite unittest of trt_activation_op
  cmake/configure.cmake
  paddle/fluid/inference/tensorrt/convert/CMakeLists.txt
  paddle/fluid/inference/tensorrt/convert/activation_op.cc
  paddle/fluid/inference/tensorrt/convert/test_activation_op.cc
Labels: Inference

#11040 Mkldnn layout
  paddle/fluid/framework/data_layout.h
  paddle/fluid/framework/data_layout_transform.cc
  paddle/fluid/framework/data_layout_transform.h
  paddle/fluid/framework/data_transform.cc
  paddle/fluid/framework/op_kernel_type.h
  paddle/fluid/framework/op_registry.h
  paddle/fluid/framework/operator.cc
  paddle/fluid/framework/tensor.h
  paddle/fluid/framework/tensor_test.cc
  paddle/fluid/operators/activation_op.cc
  paddle/fluid/operators/batch_norm_op.cc
  paddle/fluid/operators/conv_op.cc
  paddle/fluid/operators/fc_op.cc
  paddle/fluid/operators/lrn_op.cc
  paddle/fluid/operators/pool_mkldnn_op.cc
  paddle/fluid/operators/pool_op.cc
  paddle/fluid/operators/softmax_op.cc
  paddle/fluid/platform/mkldnn_helper.h
Labels: Intel

#11247 Infer multi-threads API Demo and UT
  paddle/contrib/inference/demo/simple_on_word2vec.cc
  paddle/contrib/inference/test_paddle_inference_api_impl.cc
Labels: Inference

#11101 MKLDNN layout: Support for pool operator
  paddle/fluid/operators/pool_mkldnn_op.cc
Labels: Intel

#11098 MKLDNN layout: Support for batch norm operator
  paddle/fluid/operators/batch_norm_mkldnn_op.cc
  paddle/fluid/operators/batch_norm_op.cc
Labels: Intel

#11099 MKLDNN layout: Support for convolution operator
  paddle/fluid/operators/conv_mkldnn_op.cc
  paddle/fluid/operators/conv_op.cc
Labels: Intel

#10789 Add an interface to set the number of threads for math function, and set the default value to 1 for inference.
  cmake/external/openblas.cmake
  paddle/fluid/inference/io.cc
  paddle/fluid/operators/math/blas.h
  paddle/fluid/operators/math/math_function.h
  paddle/math/MathFunctions.h
Labels: Inference

#11354 Polish documentation
  paddle/fluid/operators/activation_op.cc
  paddle/fluid/operators/compare_op.cc
  paddle/fluid/operators/cumsum_op.cc
  paddle/fluid/operators/layer_norm_op.cc
  paddle/fluid/operators/multiplex_op.cc
  paddle/fluid/operators/reader/create_recordio_file_reader_op.cc
  paddle/fluid/operators/reader/reader_op_registry.cc
  paddle/fluid/operators/row_conv_op.cc
  paddle/fluid/operators/uniform_random_op.cc
  python/paddle/fluid/layers/control_flow.py
  python/paddle/fluid/layers/detection.py
  python/paddle/fluid/layers/io.py
  python/paddle/fluid/layers/nn.py
  python/paddle/fluid/layers/ops.py
  python/paddle/fluid/layers/tensor.py
Labels: PythonAPI, documentation

#11497 Doc update
  paddle/fluid/operators/activation_op.cc
  paddle/fluid/operators/mean_op.cc
  python/paddle/fluid/layers/control_flow.py
  python/paddle/fluid/layers/io.py
  python/paddle/fluid/layers/nn.py
  python/paddle/fluid/layers/tensor.py
Labels: PythonAPI, documentation

#11504 Polish inline math and duplicable/optional in auto generated doc
  python/paddle/fluid/layers/layer_function_generator.py
Labels: PythonAPI, documentation

#11488 add doc of sequence_softmax and parallelDo
  paddle/fluid/operators/elementwise_mul_op.cc
  python/paddle/fluid/layers/control_flow.py
  python/paddle/fluid/layers/nn.py
Labels: PythonAPI, documentation

#11491 Fix some problems in api reference
  doc/fluid/api/gen_doc.sh
  doc/fluid/api/initializer.rst
  doc/fluid/api/io.rst
  doc/fluid/api/layers.rst
  doc/fluid/api/optimizer.rst
  doc/fluid/api/profiler.rst
  paddle/fluid/operators/activation_op.cc
  paddle/fluid/operators/nce_op.cc
  python/paddle/fluid/layers/detection.py
  python/paddle/fluid/layers/metric.py
  python/paddle/fluid/layers/nn.py
  python/paddle/fluid/layers/tensor.py
Labels: PythonAPI, documentation

#11457 Add API reference
  paddle/fluid/operators/activation_op.cc
  paddle/fluid/operators/pool_op.cc
  python/paddle/fluid/layers/control_flow.py
  python/paddle/fluid/layers/io.py
  python/paddle/fluid/layers/learning_rate_scheduler.py
  python/paddle/fluid/layers/nn.py
  python/paddle/fluid/layers/tensor.py
Labels: PythonAPI, documentation

#11483 Fix doc of relu, log and zeros.
  python/paddle/fluid/layers/nn.py
  python/paddle/fluid/layers/ops.py
  python/paddle/fluid/layers/tensor.py
Labels: PythonAPI, documentation

#11492 [API Reference] fix some typo in layers
  paddle/fluid/operators/clip_by_norm_op.cc
  paddle/fluid/operators/uniform_random_batch_size_like_op.cc
  python/paddle/fluid/framework.py
  python/paddle/fluid/layers/control_flow.py
  python/paddle/fluid/layers/metric.py
  python/paddle/fluid/layers/nn.py
Labels: PythonAPI, documentation

#11489 Fix doc of warpctc, array_read, edit_distance and sequence_reshape.
  python/paddle/fluid/layers/control_flow.py
  python/paddle/fluid/layers/nn.py
Labels: PythonAPI, documentation

#11314 Fix api reference docs
  paddle/fluid/operators/chunk_eval_op.cc
  paddle/fluid/operators/conv_transpose_op.cc
  paddle/fluid/operators/cos_sim_op.cc
  paddle/fluid/operators/crf_decoding_op.cc
  paddle/fluid/operators/detection/iou_similarity_op.cc
  paddle/fluid/operators/linear_chain_crf_op.cc
  paddle/fluid/operators/lstm_op.cc
  paddle/fluid/operators/roi_pool_op.cc
  paddle/fluid/operators/scale_op.cc
  python/paddle/fluid/layers/io.py
  python/paddle/fluid/layers/layer_function_generator.py
  python/paddle/fluid/layers/nn.py
  python/paddle/fluid/layers/ops.py
Labels: PythonAPI, documentation

#11383 update split_lod_tensor, create_array and array_length doc
  paddle/fluid/operators/activation_op.cc
  paddle/fluid/operators/detection/polygon_box_transform_op.cc
  paddle/fluid/operators/shape_op.cc
  paddle/fluid/operators/sigmoid_cross_entropy_with_logits_op.cc
  python/paddle/fluid/layers/control_flow.py
  python/paddle/fluid/layers/detection.py
  python/paddle/fluid/layers/learning_rate_scheduler.py
  python/paddle/fluid/layers/nn.py
  python/paddle/fluid/layers/tensor.py
Labels: PythonAPI, documentation

#11124 MKLDNN layout: Support for activation operator
  paddle/fluid/operators/activation_mkldnn_op.cc
  paddle/fluid/operators/activation_op.cc
Labels: Intel

#11521 add doc for inference_transpiler
  python/paddle/fluid/transpiler/inference_transpiler.py
Labels: PythonAPI, documentation

#11525 refine the initial cpu memory flag for mkldnn
  paddle/fluid/platform/cpu_info.cc
  paddle/testing/paddle_gtest_main.cc
  python/paddle/fluid/__init__.py
Labels: Intel

#11563 Refine detection_map doc.
  paddle/fluid/operators/detection_map_op.cc
  python/paddle/fluid/layers/detection.py
Labels: PythonAPI, documentation

#11559 Polish profiler Python API.
  python/paddle/fluid/profiler.py
Labels: PythonAPI, documentation

#11532 Add none layers api doc
  python/paddle/fluid/clip.py
  python/paddle/fluid/inferencer.py
  python/paddle/fluid/initializer.py
  python/paddle/fluid/optimizer.py
  python/paddle/fluid/regularizer.py
Labels: PythonAPI, documentation

#11102 MKLDNN layout: Support for sum operator
  paddle/fluid/operators/parallel_do_op.cc
  paddle/fluid/operators/recurrent_op.cc
  paddle/fluid/operators/sum_mkldnn_op.cc
  paddle/fluid/operators/sum_op.cc
  paddle/fluid/operators/while_op.cc
  paddle/fluid/platform/mkldnn_helper.h
  python/paddle/fluid/backward.py
  python/paddle/fluid/layers/nn.py
  python/paddle/fluid/layers/tensor.py
  python/paddle/fluid/tests/unittests/test_sum_mkldnn_op.py
  python/paddle/fluid/tests/unittests/test_sum_op.py
  python/paddle/fluid/transpiler/distribute_transpiler.py
  python/paddle/reader/decorator.py
Labels: Intel

#11523 MKLDNN layout: Gaussian random layout
  paddle/fluid/operators/gaussian_random_mkldnn_op.cc
  paddle/fluid/operators/gaussian_random_op.cc
  python/paddle/fluid/tests/unittests/test_gaussian_random_mkldnn_op.py
  python/paddle/fluid/tests/unittests/test_gaussian_random_op.py
Labels: Intel

#11469 add beam search doc
  paddle/fluid/operators/activation_op.cc
  python/paddle/fluid/layers/control_flow.py
  python/paddle/fluid/layers/nn.py
Labels: PythonAPI, documentation

#11560 Doc of non layer api
  python/paddle/fluid/average.py
  python/paddle/fluid/backward.py
  python/paddle/fluid/io.py
Labels: PythonAPI, documentation

#11554 Refine ParallelExe Doc
  python/paddle/fluid/parallel_executor.py
Labels: PythonAPI, documentation

#11555 Refine fluid.net Doc
  python/paddle/fluid/nets.py
Labels: PythonAPI, documentation

#11580 Refine doc of data reader
  python/paddle/fluid/data_feeder.py
  python/paddle/fluid/executor.py
Labels: PythonAPI, documentation

#11508 Transpiler doc
  doc/fluid/api/gen_doc.sh
  doc/fluid/api/transpiler.rst
  python/paddle/fluid/transpiler/distribute_transpiler.py
  python/paddle/fluid/transpiler/ps_dispatcher.py
  tools/codestyle/docstring_checker.py
Labels: PythonAPI, documentation

#11531 Polish Non-Layer API
  python/paddle/fluid/__init__.py
  python/paddle/fluid/executor.py
  python/paddle/fluid/framework.py
  python/paddle/fluid/lod_tensor.py
  python/paddle/fluid/recordio_writer.py
  python/paddle/fluid/trainer.py
  python/paddle/fluid/transpiler/memory_optimization_transpiler.py
  python/paddle/fluid/unique_name.py
Labels: PythonAPI, documentation

#11640 added cycling the cifar and flowers datasets
  python/paddle/v2/dataset/cifar.py
  python/paddle/v2/dataset/flowers.py
Labels: Intel

#11519 MKLDNN: SoftmaxGrad Op
  cmake/external/mkldnn.cmake
  paddle/fluid/operators/softmax_mkldnn_op.cc
  paddle/fluid/operators/softmax_op.cc
  paddle/fluid/platform/mkldnn_helper.h
Labels: Intel

#11544 MKLDNN elementwis_add with default broadcast operations
  paddle/fluid/framework/data_layout_transform.cc
  paddle/fluid/framework/data_layout_transform.h
  paddle/fluid/framework/data_transform.cc
  paddle/fluid/operators/elementwise_add_mkldnn_op.cc
  paddle/fluid/operators/elementwise_op.h
  python/paddle/fluid/tests/unittests/test_elementwise_add_mkldnn_op.py
  python/paddle/fluid/tests/unittests/test_elementwise_add_op.py
Labels: Intel

#11434 bnorm+relu fuse for mkldnn (inference)
  benchmark/fluid/args.py
  benchmark/fluid/fluid_benchmark.py
  paddle/fluid/operators/batch_norm_mkldnn_op.cc
  paddle/fluid/operators/batch_norm_op.cc
  python/paddle/fluid/layers/nn.py
  python/paddle/fluid/tests/unittests/test_batch_norm_mkldnn_op.py
  python/paddle/fluid/tests/unittests/test_batch_norm_op.py
  python/paddle/fluid/transpiler/inference_transpiler.py
Labels: Intel

#11666 The mkldnn batch norm supports other data format
  paddle/fluid/framework/data_layout_transform.cc
  paddle/fluid/framework/data_layout_transform.h
  paddle/fluid/framework/data_transform.cc
  paddle/fluid/operators/batch_norm_mkldnn_op.cc
  paddle/fluid/platform/mkldnn_helper.h
Labels: Intel
