Repository PaddlePaddle/Paddle, pull requests merged in 2018-03, with the labels that each got.

#8680 Fix building error of missing end-group for Android.
  CMakeLists.txt
  cmake/external/zlib.cmake
  cmake/generic.cmake
Labels: Android

#8699 Try to add build_android task back to travis.
  .travis.yml
  CMakeLists.txt
  paddle/scripts/docker/build_android.sh
  paddle/scripts/travis/build_android.sh
Labels: Android

#8642 Enable is_test attr of batch norm and drop out op for test program
  paddle/fluid/framework/prune.cc
  python/paddle/fluid/framework.py
  python/paddle/fluid/tests/book/test_image_classification.py
  python/paddle/fluid/tests/book/test_recognize_digits.py
  python/paddle/fluid/tests/book/test_recommender_system.py
Labels: Inference

#8451 MKLDNN conv2d kernel added
  paddle/fluid/operators/CMakeLists.txt
  paddle/fluid/operators/conv_mkldnn_op.cc
  paddle/fluid/operators/conv_op.cc
  paddle/fluid/platform/cudnn_helper.h
  paddle/fluid/platform/device_context.cc
  paddle/fluid/platform/device_context.h
  paddle/fluid/platform/mkldnn_helper.h
  python/paddle/fluid/layers/nn.py
  python/paddle/fluid/nets.py
  python/paddle/fluid/tests/unittests/test_conv2d_op.py
Labels: Intel

#8682 refine operators/math/CMakeLists.txt
  paddle/fluid/operators/CMakeLists.txt
  paddle/fluid/operators/math/CMakeLists.txt
  paddle/fluid/operators/math/sequence2batch.cc
Labels: Inference

#7827 compile and install the static library of fluid inference
  cmake/external/openblas.cmake
  cmake/generic.cmake
  cmake/inference_lib.cmake
  paddle/fluid/inference/CMakeLists.txt
  paddle/scripts/docker/build.sh
Labels: Inference

#8695 Add float16 GEMM math function on GPU
  paddle/fluid/operators/math/math_function.cc
  paddle/fluid/operators/math/math_function.cu
  paddle/fluid/operators/math/math_function_test.cu
  paddle/fluid/platform/dynload/cublas.h
Labels: Inference

#8879 MKLDNN pool2d OP kernel added
  paddle/fluid/operators/conv_mkldnn_op.cc
  paddle/fluid/operators/pool_mkldnn_op.cc
  paddle/fluid/operators/pool_op.cc
  python/paddle/fluid/layers/nn.py
  python/paddle/fluid/nets.py
  python/paddle/fluid/tests/unittests/test_pool2d_op.py
Labels: Intel

#8946 Add GPU compute capability check for float16 math function test
  paddle/fluid/operators/math/math_function.cu
  paddle/fluid/operators/math/math_function_test.cu
  paddle/fluid/platform/device_context.cc
  paddle/fluid/platform/device_context.h
  paddle/fluid/platform/gpu_info.cc
  paddle/fluid/platform/gpu_info.h
Labels: Inference

#8910 Refine the profile codes for inference.
  paddle/fluid/framework/operator.cc
  paddle/fluid/inference/tests/test_helper.h
Labels: Inference

#9033 Fix the CPP Data Feeding design document
  doc/design/cpp_data_feeding.md
Labels: documentation

#9017 Add fp16 mul op support and bind paddle fp16 to numpy fp16
  paddle/fluid/operators/mul_op.cc
  paddle/fluid/operators/mul_op.cu.cc
  paddle/fluid/operators/mul_op.h
  paddle/fluid/pybind/pybind.cc
  paddle/fluid/pybind/tensor_py.h
  python/paddle/fluid/tests/unittests/test_mul_op.py
Labels: Inference

#9143 Add float16 support for cudnn conv2d
  paddle/fluid/operators/conv_cudnn_op.cu.cc
  paddle/fluid/operators/conv_op.cc
  paddle/fluid/platform/cudnn_helper.h
  python/paddle/fluid/tests/unittests/op_test.py
  python/paddle/fluid/tests/unittests/test_conv2d_op.py
Labels: Inference

#9148 Add float16 support for cast op
  paddle/fluid/operators/cast_op.cc
  paddle/fluid/operators/cast_op.cu
  python/paddle/fluid/tests/unittests/test_cast_op.py
Labels: Inference

#9167 Add float16 support for pool 2d operator
  paddle/fluid/operators/conv_cudnn_op.cu.cc
  paddle/fluid/operators/pool_cudnn_op.cu.cc
  paddle/fluid/operators/pool_op.cc
  python/paddle/fluid/tests/unittests/op_test.py
  python/paddle/fluid/tests/unittests/test_conv2d_op.py
  python/paddle/fluid/tests/unittests/test_pool2d_op.py
Labels: Inference

#9065 Limit the symbol table of fluid shared library.
  paddle/fluid/inference/CMakeLists.txt
  paddle/fluid/inference/paddle_fluid.map
Labels: Inference

#9223 Add float16 support to dropout operator
  paddle/fluid/operators/dropout_op.cc
  paddle/fluid/operators/dropout_op.cu
  paddle/fluid/operators/dropout_op.h
  paddle/fluid/platform/float16.h
  python/paddle/fluid/tests/unittests/test_dropout_op.py
Labels: Inference

#9242 Add an argument in Executor.Run to allow users to choose whether to create and destroy variables every time
  paddle/fluid/framework/executor.cc
  paddle/fluid/framework/executor.h
Labels: Inference

#9176 Add float16 support to batch norm operator
  paddle/fluid/operators/batch_norm_op.cc
  paddle/fluid/operators/batch_norm_op.cu.cc
  paddle/fluid/operators/math/math_function.cc
  paddle/fluid/operators/math/math_function.cu
  paddle/fluid/platform/cudnn_helper.h
  python/paddle/fluid/tests/unittests/test_batch_norm_op.py
Labels: Inference

#9214 Softmax MKLDNN FLUID operator
  paddle/fluid/operators/cross_entropy_op.h
  paddle/fluid/operators/softmax_mkldnn_op.cc
  paddle/fluid/operators/softmax_op.cc
  python/paddle/fluid/layer_helper.py
  python/paddle/fluid/layers/nn.py
  python/paddle/fluid/tests/unittests/test_softmax_op.py
Labels: Intel

#9267 Add float16 support to relu op
  paddle/fluid/operators/activation_op.cc
  paddle/fluid/operators/activation_op.cu
  paddle/fluid/operators/activation_op.h
  python/paddle/fluid/tests/unittests/test_activation_op.py
Labels: Inference

#9269 Add float16 support to cudnn softmax kernel
  paddle/fluid/operators/math/softmax.cu
  paddle/fluid/operators/softmax_cudnn_op.cu.cc
  paddle/fluid/operators/softmax_op.cc
  python/paddle/fluid/tests/unittests/test_softmax_op.py
Labels: Inference

#9165 Demostration of cmake refine for HIP support.
  CMakeLists.txt
  cmake/configure.cmake
  cmake/external/eigen.cmake
  cmake/generic.cmake
  cmake/hip.cmake
  paddle/fluid/operators/CMakeLists.txt
  paddle/fluid/operators/math/CMakeLists.txt
  paddle/fluid/operators/math/concat.hip.cu
  paddle/fluid/pybind/CMakeLists.txt
  paddle/scripts/docker/build.sh
Labels: AMD

#9123 Implementation of MKLDNN LRN
  paddle/fluid/operators/lrn_mkldnn_op.cc
  paddle/fluid/operators/lrn_op.cc
  python/paddle/fluid/tests/unittests/test_lrn_op.py
Labels: Intel

#9081 MKLDNN Relu Tanh Sqrt Abs activations added
  paddle/fluid/operators/CMakeLists.txt
  paddle/fluid/operators/activation_mkldnn_op.cc
  paddle/fluid/operators/activation_op.cc
  paddle/fluid/operators/activation_op.h
  paddle/fluid/operators/mkldnn_activation_op.h
  python/paddle/fluid/layer_helper.py
  python/paddle/fluid/tests/unittests/test_activation_op.py
Labels: Intel

#8887 add MKL for fluid static and shared library
  cmake/external/mklml.cmake
  cmake/inference_lib.cmake
  paddle/fluid/operators/math/math_function.h
  paddle/math/MathFunctions.cpp
  paddle/math/MathFunctions.h
Labels: Inference

#9329 Improvements for MKLDNN LRN
  paddle/fluid/operators/lrn_mkldnn_op.cc
  paddle/fluid/operators/lrn_op.cc
  python/paddle/fluid/tests/unittests/test_lrn_op.py
Labels: Intel

#9392 fix submit_local's paddle pip name issue
  paddle/scripts/submit_local.sh.in
Labels: Docker

#9384 remove vars when remove ops
  paddle/fluid/framework/block_desc.cc
  paddle/fluid/framework/block_desc.h
  python/paddle/fluid/tests/unittests/test_protobuf_descs.py
Labels: Inference
