Repository PaddlePaddle/Paddle, pull requests merged in 2018-05, with the labels that each got.

#10293 Update Intel AUTHORS.md
  AUTHORS.md
Labels: Intel

#10276 Fix more CPPLint issues in fluid/operators/math
  paddle/fluid/operators/concat_op.h
  paddle/fluid/operators/math/concat.cc
  paddle/fluid/operators/math/concat.cu
  paddle/fluid/operators/math/concat.h
  paddle/fluid/operators/math/detail/gru_cpu_kernel.h
  paddle/fluid/operators/math/detail/lstm_cpu_kernel.h
  paddle/fluid/operators/math/math_function_test.cu
  paddle/fluid/operators/math/selected_rows_functor_test.cu
Labels: Code Cleanup

#10272 Add float16 support to save op
  paddle/fluid/operators/save_load_op_test.cc
  paddle/fluid/operators/save_op.cc
Labels: Inference

#10317 Fix CPPLint issues with math/sequence_padding
  paddle/fluid/operators/math/sequence_padding.cc
  paddle/fluid/operators/math/sequence_padding.cu
  paddle/fluid/operators/math/sequence_padding.h
  paddle/fluid/operators/math/sequence_padding_test.cc
  paddle/fluid/operators/warpctc_op.h
Labels: Code Cleanup

#10345 Fix __shfl_down_sync_ of cross_entropy
  paddle/fluid/operators/elementwise_op_function.h
  paddle/fluid/operators/math/cross_entropy.cu
  paddle/fluid/operators/row_conv_op.cu
  paddle/fluid/platform/cuda_device_function.h
  paddle/fluid/platform/cuda_primitives.h
Labels: Code Cleanup

#9904 MKLDNN implementation of batch normalization
  paddle/fluid/operators/batch_norm_mkldnn_op.cc
  paddle/fluid/operators/batch_norm_op.cc
  python/paddle/fluid/layers/nn.py
  python/paddle/fluid/tests/unittests/test_batch_norm_mkldnn_op.py
  python/paddle/fluid/tests/unittests/test_batch_norm_op.py
Labels: Intel

#10280 Clean cross entropy
  paddle/fluid/operators/cross_entropy_op.cc
  paddle/fluid/operators/cross_entropy_op.cu
  paddle/fluid/operators/cross_entropy_op.h
Labels: Code Cleanup

#10268 Fix the bug when a input variable of op is dispensable.
  paddle/capi/Matrix.cpp
  paddle/fluid/framework/operator.cc
  paddle/fluid/framework/operator.h
  paddle/fluid/platform/profiler.h
Labels: Inference

#10327 Feature/clean blas
  paddle/fluid/operators/bilinear_tensor_product_op.h
  paddle/fluid/operators/gru_unit_op.h
  paddle/fluid/operators/math/blas_impl.cu.h
  paddle/fluid/operators/math/blas_impl.h
  paddle/fluid/operators/math/gru_compute.cc
  paddle/fluid/operators/math/gru_compute.cu
  paddle/fluid/operators/math/math_function.cc
  paddle/fluid/operators/math/math_function.cu
  paddle/fluid/operators/math/math_function.h
  paddle/fluid/operators/math/math_function_test.cc
  paddle/fluid/operators/math/math_function_test.cu
  paddle/fluid/operators/math/matmul.h
Labels: Code Cleanup

#10359 fix dead links in README.md
  README.md
Labels: documentation

#10331 Add float16 demo code and put float16 work in contrib/float16 folder
  contrib/float16/.gitignore
  contrib/float16/float16_benchmark.md
  contrib/float16/float16_inference_demo.py
  contrib/float16/float16_inference_report.md
  contrib/float16/float16_transpiler.py
  contrib/float16/run_float16_demo.sh
  paddle/fluid/inference/tests/book/test_inference_image_classification.cc
  python/paddle/fluid/inference_transpiler.py
  python/paddle/fluid/tests/book/test_image_classification.py
Labels: Inference

#10390 Fix CPPLint issues in /math/detail/gru_kernel.h
  paddle/fluid/operators/math/detail/gru_cpu_kernel.h
  paddle/fluid/operators/math/detail/gru_gpu_kernel.h
  paddle/fluid/operators/math/detail/gru_kernel.h
Labels: Code Cleanup

#10144 tensorrt convert init
  paddle/fluid/inference/tensorrt/CMakeLists.txt
  paddle/fluid/inference/tensorrt/convert/CMakeLists.txt
  paddle/fluid/inference/tensorrt/convert/activation_op.cc
  paddle/fluid/inference/tensorrt/convert/conv2d_op.cc
  paddle/fluid/inference/tensorrt/convert/mul_op.cc
  paddle/fluid/inference/tensorrt/convert/op_converter.h
  paddle/fluid/inference/tensorrt/convert/test_activation_op.cc
  paddle/fluid/inference/tensorrt/convert/test_op_converter.cc
  paddle/fluid/inference/tensorrt/engine.cc
  paddle/fluid/inference/tensorrt/engine.h
  paddle/fluid/inference/tensorrt/test_engine.cc
Labels: Inference

#10371 Polish MatMul, clean copy & paste code
  paddle/fluid/operators/bilinear_tensor_product_op.h
  paddle/fluid/operators/conv_op.h
  paddle/fluid/operators/conv_transpose_op.h
  paddle/fluid/operators/gru_unit_op.h
  paddle/fluid/operators/layer_norm_op.h
  paddle/fluid/operators/lstm_op.h
  paddle/fluid/operators/lstmp_op.h
  paddle/fluid/operators/math/CMakeLists.txt
  paddle/fluid/operators/math/blas.cc
  paddle/fluid/operators/math/blas.h
  paddle/fluid/operators/math/blas_impl.cu.h
  paddle/fluid/operators/math/blas_impl.h
  paddle/fluid/operators/math/context_project.h
  paddle/fluid/operators/math/gru_compute.cc
  paddle/fluid/operators/math/gru_compute.cu
  paddle/fluid/operators/math/math_function.cc
  paddle/fluid/operators/math/math_function.cu
  paddle/fluid/operators/math/math_function.h
  paddle/fluid/operators/math/math_function_test.cc
  paddle/fluid/operators/math/math_function_test.cu
  paddle/fluid/operators/math/matmul.h
  paddle/fluid/operators/mul_op.h
  paddle/fluid/operators/sequence_conv_op.h
Labels: Code Cleanup

#10414 Wrap shfl_x_sync
  paddle/fluid/operators/row_conv_op.cu
  paddle/fluid/operators/top_k_op.cu
  paddle/fluid/platform/cuda_device_function.h
Labels: Code Cleanup

#10394 Fix cpplint errors in lstm kernel
  paddle/fluid/operators/math/detail/lstm_cpu_kernel.h
  paddle/fluid/operators/math/detail/lstm_gpu_kernel.h
  paddle/fluid/operators/math/detail/lstm_kernel.h
Labels: Code Cleanup

#10403 Add the call of DropKids at the end of executor.Run to delete the local scopes created in operators
  paddle/fluid/framework/executor.cc
Labels: Inference

#10425 Add float16 support to conv3d op
  paddle/fluid/operators/conv_cudnn_op.cu.cc
  python/paddle/fluid/tests/unittests/test_conv3d_op.py
Labels: Inference

#10430 Add comment to explain how to run inference test
  paddle/fluid/inference/tests/book/CMakeLists.txt
Labels: Inference

#10461 refine io_convert and op_convert
  paddle/fluid/inference/tensorrt/CMakeLists.txt
  paddle/fluid/inference/tensorrt/convert/CMakeLists.txt
  paddle/fluid/inference/tensorrt/convert/io_converter.cc
  paddle/fluid/inference/tensorrt/convert/io_converter.h
  paddle/fluid/inference/tensorrt/convert/op_converter.h
  paddle/fluid/inference/tensorrt/convert/test_activation_op.cc
  paddle/fluid/inference/tensorrt/convert/test_io_converter.cc
  paddle/fluid/inference/tensorrt/convert/test_op_converter.cc
  paddle/fluid/inference/utils/singleton.h
Labels: Inference

#10478 Add classification_cost to v2 documentation
  doc/v2/api/config/layer.rst
Labels: PythonAPI, documentation

#10497 Feature/engine refactor
  paddle/fluid/inference/engine.h
  paddle/fluid/inference/tensorrt/CMakeLists.txt
  paddle/fluid/inference/tensorrt/convert/CMakeLists.txt
  paddle/fluid/inference/tensorrt/engine.cc
  paddle/fluid/inference/tensorrt/engine.h
Labels: Inference

#10501 Bump MKL-DNN version
  cmake/external/mkldnn.cmake
Labels: Intel

#10437 Add a multi-dim add layer test.
  paddle/fluid/inference/tensorrt/test_engine.cc
Labels: Inference

#10545 fix tensorrt_engine compiler error
  paddle/fluid/inference/CMakeLists.txt
  paddle/fluid/inference/tensorrt/CMakeLists.txt
Labels: Inference

#10449 Rewrite Matmul, make code cleaner
  paddle/fluid/operators/math/blas.cc
  paddle/fluid/operators/math/blas.h
  paddle/fluid/operators/math/blas_impl.h
  paddle/fluid/operators/math/matmul.h
  paddle/fluid/operators/matmul_op.cc
  paddle/fluid/operators/matmul_op.cu.cc
  paddle/fluid/operators/matmul_op.h
  python/paddle/fluid/tests/unittests/test_matmul_op.py
Labels: Code Cleanup

#10560 Update .copyright.hook
  .copyright.hook
Labels: Code Cleanup

#10576 Reusing of softmax mkldnn primitives
  paddle/fluid/operators/softmax_mkldnn_op.cc
Labels: Intel

#10616 Patch mkldnn for build on gcc 4.8.2
  cmake/external/mkldnn.cmake
  patches/mkldnn.hpp
Labels: Intel

#10527 Fix a bug related to dispensable inputs and refine the inference unittest
  paddle/fluid/framework/operator.h
  paddle/fluid/inference/tests/book/test_inference_image_classification.cc
  paddle/fluid/inference/tests/test_helper.h
  paddle/fluid/operators/math/sequence2batch.h
  paddle/fluid/operators/reshape_op.h
Labels: Inference

#10495 refine EngineIOConverter, and use io_convert in test_trt_activation_op
  paddle/fluid/inference/analysis/dot.h
  paddle/fluid/inference/engine.h
  paddle/fluid/inference/tensorrt/CMakeLists.txt
  paddle/fluid/inference/tensorrt/convert/CMakeLists.txt
  paddle/fluid/inference/tensorrt/convert/io_converter.cc
  paddle/fluid/inference/tensorrt/convert/io_converter.h
  paddle/fluid/inference/tensorrt/convert/test_activation_op.cc
  paddle/fluid/inference/tensorrt/convert/test_io_converter.cc
Labels: Inference

#10660 add boost to inference lib
  cmake/inference_lib.cmake
Labels: Inference

#10690 add pybind.h to inference lib for static link
  cmake/inference_lib.cmake
Labels: Inference

#10709 Fix hang when input is duplicated
  paddle/fluid/framework/details/op_handle_base.h
  paddle/fluid/framework/details/threaded_ssa_graph_executor.cc
Labels: Bug

#10705 add mkldnn to paddle lib
  cmake/inference_lib.cmake
Labels: Inference, Intel

#10736 refine mkldnn cmake with official commit id
  cmake/external/mkldnn.cmake
  patches/mkldnn.hpp
Labels: Intel

#10526 allow inference test to generate timeline
  paddle/fluid/inference/tests/test_helper.h
Labels: Inference

#10747 Reuse of pooling mkldnn primitives
  paddle/fluid/operators/pool_mkldnn_op.cc
  paddle/fluid/platform/mkldnn_helper.h
Labels: Intel

#10807 add version and cmakecache in inference_lib
  cmake/inference_lib.cmake
Labels: Inference

#10597 Update activations for MKL-DNN
  paddle/fluid/operators/activation_mkldnn_op.cc
  paddle/fluid/operators/activation_op.cc
  paddle/fluid/operators/mkldnn_activation_op.h
  paddle/fluid/platform/mkldnn_helper.h
Labels: Intel

#10701 enable MKLDNN inference test
  CMakeLists.txt
  paddle/fluid/inference/tests/book/test_inference_image_classification.cc
  paddle/fluid/inference/tests/test_helper.h
Labels: Inference

#10827 change CMAKE_INSTALL_PREFIX in inference_lib_dist to FLUID_INSTALL_DIR
  CMakeLists.txt
  cmake/inference_lib.cmake
  paddle/fluid/train/demo/README.md
  paddle/scripts/paddle_build.sh
Labels: Inference

#10913 Blas optimized elementwise_add forward and backward passes
  paddle/fluid/operators/elementwise_add_op.h
  paddle/fluid/operators/math/blas.h
  paddle/fluid/operators/math/blas_impl.h
Labels: Intel

#10934 speedup vInvSqrt vLogqp vTanh with mklml
  paddle/math/MathFunctions.cpp
Labels: Intel

#10988 fix inference_lib_dist deps
  cmake/inference_lib.cmake
Labels: Inference

#10941 Top K algorithm: parallel version
  paddle/fluid/operators/top_k_op.h
Labels: Intel

#10703 Withdraw MKLDNN Mul operator
  paddle/fluid/operators/mul_mkldnn_op.cc
  paddle/fluid/operators/mul_op.cc
  python/paddle/fluid/layers/nn.py
  python/paddle/fluid/tests/unittests/test_mul_mkldnn_op.py
  python/paddle/fluid/tests/unittests/test_mul_op.py
  python/paddle/fluid/tests/unittests/test_operator_desc.py
Labels: Intel
