Repository PaddlePaddle/Paddle, pull requests merged in 2018-12, with the labels that each got.

#14693 Fix for accuracy problem for inplace operators when MKL-DNN mode is enabled
  paddle/fluid/framework/operator.cc
Labels: Intel

#14441 Implementing ngraph engine
  cmake/external/ngraph.cmake
  cmake/inference_lib.cmake
  paddle/fluid/framework/CMakeLists.txt
  paddle/fluid/framework/ngraph_bridge.cc
  paddle/fluid/framework/ngraph_bridge.h
  paddle/fluid/framework/ngraph_operator.cc
  paddle/fluid/framework/ngraph_operator.h
  paddle/fluid/framework/operator.cc
  paddle/fluid/framework/operator.h
  paddle/fluid/inference/api/demo_ci/CMakeLists.txt
  python/setup.py.in
Labels: Intel, NGraph

#14707 Implement conv3d with mkldnn library
  paddle/fluid/operators/conv_mkldnn_op.cc
  paddle/fluid/operators/conv_op.cc
  paddle/fluid/platform/mkldnn_helper.h
  python/paddle/fluid/tests/unittests/test_conv3d_mkldnn_op.py
  python/paddle/fluid/tests/unittests/test_conv3d_op.py
Labels: Intel

#14709 Implement the fusion of convolution 3D and bias for mkldnn
  paddle/fluid/framework/ir/conv_bias_mkldnn_fuse_pass.cc
  paddle/fluid/framework/ir/conv_bias_mkldnn_fuse_pass.h
  paddle/fluid/framework/ir/graph_pattern_detector.cc
  paddle/fluid/framework/ir/graph_pattern_detector.h
  paddle/fluid/inference/api/paddle_pass_builder.h
  paddle/fluid/inference/tests/api/analyzer_dam_tester.cc
  paddle/fluid/operators/activation_mkldnn_op.cc
Labels: Intel

#14768 One possible solution to add flexibility for mkldnn placement pass
  paddle/fluid/framework/ir/mkldnn_placement_pass.cc
  paddle/fluid/inference/analysis/argument.h
  paddle/fluid/inference/analysis/ir_pass_manager.cc
  paddle/fluid/inference/api/analysis_config.cc
  paddle/fluid/inference/api/analysis_predictor.cc
  paddle/fluid/inference/api/paddle_analysis_config.h
  paddle/fluid/inference/tests/api/analyzer_dam_tester.cc
Labels: Intel

#14799 Fix/remove unnecessary mkldnn reorder
  paddle/fluid/framework/data_layout_transform.cc
Labels: Intel

#14851 Fix the issue to run on AVX2 machine
  paddle/fluid/operators/math/jit_kernel_layer_norm.cc
Labels: Intel

#14807 Follow ups on nGraph PR comments
  paddle/fluid/framework/CMakeLists.txt
  paddle/fluid/framework/executor.cc
  paddle/fluid/framework/ngraph_bridge.cc
  paddle/fluid/framework/ngraph_bridge.h
  paddle/fluid/framework/ngraph_operator.cc
  paddle/fluid/framework/ngraph_operator.h
Labels: Intel, NGraph

#14800 Enable ngraph tests for a ngraph engine
  python/paddle/fluid/tests/unittests/CMakeLists.txt
  python/paddle/fluid/tests/unittests/ngraph/CMakeLists.txt
  python/paddle/fluid/tests/unittests/ngraph/__init__.py
Labels: Intel, NGraph

#14801 Enable mul operator for a ngraph engine
  paddle/fluid/framework/ngraph_bridge.cc
  paddle/fluid/operators/ngraph/ngraph_ops.h
  paddle/fluid/operators/ngraph/ops/binary_unnary_op.h
  paddle/fluid/operators/ngraph/ops/mul_op.h
  paddle/fluid/platform/ngraph_helper.h
  python/paddle/fluid/tests/unittests/ngraph/test_activation_ngraph_op.py
  python/paddle/fluid/tests/unittests/ngraph/test_mul_ngraph_op.py
Labels: Intel, NGraph

#14874 MKLDNN residual connection fuse: fixing accuracy problem
  paddle/fluid/framework/ir/conv_elementwise_add_mkldnn_fuse_pass.cc
Labels: Intel

#14932 Fix the regression issue and add the group unitest for conv2d
  paddle/fluid/operators/conv_mkldnn_op.cc
  python/paddle/fluid/tests/unittests/test_conv2d_mkldnn_op.py
Labels: Intel

#14966 [MKL-DNN] Extending Transpose Op to reuse MKL-dNN primitives
  paddle/fluid/operators/transpose_mkldnn_op.cc
  paddle/fluid/platform/mkldnn_reuse.h
Labels: Intel, enhancement, inference, performance tuning

#14987 [MKL-DNN] Added transpose/transpose2 MKLDNN grad ops
  paddle/fluid/operators/transpose_mkldnn_op.cc
  paddle/fluid/operators/transpose_op.cc
  python/paddle/fluid/tests/unittests/test_transpose_mkldnn_op.py
  python/paddle/fluid/tests/unittests/test_transpose_op.py
Labels: Intel, enhancement

#14974 Add Quantize OP
  paddle/fluid/operators/quantize_mkldnn_op.cc
  paddle/fluid/operators/quantize_op.cc
  paddle/fluid/operators/quantize_op.h
  paddle/fluid/platform/mkldnn_reuse.h
  python/paddle/fluid/tests/unittests/test_quantize_mkldnn_op.py
Labels: Intel

#14973 Add Dequantize OP
  paddle/fluid/operators/dequantize_mkldnn_op.cc
  paddle/fluid/operators/dequantize_op.cc
  paddle/fluid/operators/dequantize_op.h
  python/paddle/fluid/tests/unittests/test_dequantize_mkldnn_op.py
Labels: Intel

#14804 Enable top_k operator for a ngraph engine
  paddle/fluid/framework/ngraph_bridge.cc
  paddle/fluid/operators/ngraph/ngraph_ops.h
  paddle/fluid/operators/ngraph/ops/top_k_op.h
  python/paddle/fluid/tests/unittests/ngraph/test_top_k_ngraph_op.py
Labels: Intel, NGraph

#14802 Enable fill_constant operator for a ngraph engine
  paddle/fluid/framework/ngraph_bridge.cc
  paddle/fluid/operators/ngraph/ngraph_ops.h
  paddle/fluid/operators/ngraph/ops/binary_unnary_op.h
  paddle/fluid/operators/ngraph/ops/fill_constant_op.h
  python/paddle/fluid/tests/unittests/ngraph/test_fill_constant_ngraph_op.py
Labels: Intel, NGraph

#15037 Fix/abnormal stack op time
  paddle/fluid/framework/operator.cc
Labels: Intel

#15085 en api improve format Dec 27
  python/paddle/fluid/data_feeder.py
  python/paddle/fluid/framework.py
  python/paddle/fluid/layers/control_flow.py
  python/paddle/fluid/layers/detection.py
  python/paddle/fluid/layers/io.py
  python/paddle/fluid/layers/nn.py
  python/paddle/fluid/layers/tensor.py
  python/paddle/fluid/metrics.py
  python/paddle/fluid/transpiler/distribute_transpiler.py
Labels: 文档
