Repository PaddlePaddle/Paddle, pull requests merged in 2019-04, with the labels that each got.

#16608 fix preprocess script with processbar, integrity check and logs
  paddle/fluid/inference/tests/api/full_ILSVRC2012_val_preprocess.py
Labels: Intel

#16559 fix dataset reading and add support for full dataset
  paddle/fluid/inference/api/helper.h
  paddle/fluid/inference/tests/api/CMakeLists.txt
  paddle/fluid/inference/tests/api/analyzer_bert_tester.cc
  paddle/fluid/inference/tests/api/analyzer_dam_tester.cc
  paddle/fluid/inference/tests/api/analyzer_int8_image_classification_tester.cc
  paddle/fluid/inference/tests/api/analyzer_lac_tester.cc
  paddle/fluid/inference/tests/api/analyzer_mm_dnn_tester.cc
  paddle/fluid/inference/tests/api/analyzer_ner_tester.cc
  paddle/fluid/inference/tests/api/analyzer_pyramid_dnn_tester.cc
  paddle/fluid/inference/tests/api/analyzer_resnet50_tester.cc
  paddle/fluid/inference/tests/api/analyzer_rnn1_tester.cc
  paddle/fluid/inference/tests/api/analyzer_rnn2_tester.cc
  paddle/fluid/inference/tests/api/analyzer_seq_conv1_tester.cc
  paddle/fluid/inference/tests/api/analyzer_seq_pool1_tester.cc
  paddle/fluid/inference/tests/api/analyzer_text_classification_tester.cc
  paddle/fluid/inference/tests/api/analyzer_transformer_tester.cc
  paddle/fluid/inference/tests/api/analyzer_vis_tester.cc
  paddle/fluid/inference/tests/api/tester_helper.h
  paddle/fluid/inference/tests/api/trt_models_tester.cc
Labels: Intel, int8

#16606 fix repeating passes
  paddle/fluid/inference/api/analysis_config.cc
  paddle/fluid/inference/api/paddle_pass_builder.cc
  paddle/fluid/inference/api/paddle_pass_builder.h
Labels: Intel

#16643 Cherry-pick of #16559, #16606 and #16608
  paddle/fluid/inference/api/analysis_config.cc
  paddle/fluid/inference/api/helper.h
  paddle/fluid/inference/api/paddle_pass_builder.cc
  paddle/fluid/inference/api/paddle_pass_builder.h
  paddle/fluid/inference/tests/api/CMakeLists.txt
  paddle/fluid/inference/tests/api/analyzer_bert_tester.cc
  paddle/fluid/inference/tests/api/analyzer_dam_tester.cc
  paddle/fluid/inference/tests/api/analyzer_int8_image_classification_tester.cc
  paddle/fluid/inference/tests/api/analyzer_lac_tester.cc
  paddle/fluid/inference/tests/api/analyzer_mm_dnn_tester.cc
  paddle/fluid/inference/tests/api/analyzer_ner_tester.cc
  paddle/fluid/inference/tests/api/analyzer_pyramid_dnn_tester.cc
  paddle/fluid/inference/tests/api/analyzer_resnet50_tester.cc
  paddle/fluid/inference/tests/api/analyzer_rnn1_tester.cc
  paddle/fluid/inference/tests/api/analyzer_rnn2_tester.cc
  paddle/fluid/inference/tests/api/analyzer_seq_conv1_tester.cc
  paddle/fluid/inference/tests/api/analyzer_seq_pool1_tester.cc
  paddle/fluid/inference/tests/api/analyzer_text_classification_tester.cc
  paddle/fluid/inference/tests/api/analyzer_transformer_tester.cc
  paddle/fluid/inference/tests/api/analyzer_vis_tester.cc
  paddle/fluid/inference/tests/api/full_ILSVRC2012_val_preprocess.py
  paddle/fluid/inference/tests/api/tester_helper.h
  paddle/fluid/inference/tests/api/trt_models_tester.cc
Labels: Intel, int8

#16515 MKLDNN INT8 v2 readme.md
  paddle/fluid/inference/tests/api/int8_mkldnn_quantization.md
Labels: Intel, int8

#16698 Fix training validation convergence - v1.4 bug fix
  paddle/fluid/operators/ngraph/ngraph_engine.cc
  paddle/fluid/operators/ngraph/ngraph_engine.h
Labels: Intel, NGraph

#16716 Fix training validation - cherry-pick to 1.4
  paddle/fluid/operators/ngraph/ngraph_engine.cc
  paddle/fluid/operators/ngraph/ngraph_engine.h
Labels: Intel, NGraph

#16756 Fix the order while sorting the operators
  paddle/fluid/framework/ir/graph_helper.cc
  paddle/fluid/framework/ir/graph_helper.h
  paddle/fluid/inference/tests/api/analyzer_transformer_tester.cc
Labels: Intel

#16747 Reduce test_calibration test time by using large batchsize
  python/paddle/fluid/contrib/tests/test_calibration.py
Labels: Intel, int8

#16667 [MKL-DNN] Added reusing of primitive descriptors (fp32)
  paddle/fluid/operators/mkldnn/batch_norm_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/conv_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/conv_transpose_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/softmax_mkldnn_op.cc
  paddle/fluid/platform/mkldnn_reuse.h
Labels: Intel, inference, performance tuning

#16875 Improve preprocessing script and read from tar
  paddle/fluid/inference/tests/api/full_ILSVRC2012_val_preprocess.py
Labels: Intel, int8

#16824 disable test_elementwise_mul_mkldnn_op case
  python/paddle/fluid/tests/unittests/mkldnn/test_elementwise_mul_mkldnn_op.py
Labels: Intel

#16977 Split test_calibration test to two tests
  python/paddle/fluid/contrib/tests/CMakeLists.txt
  python/paddle/fluid/contrib/tests/test_calibration_mobilenetv1.py
  python/paddle/fluid/contrib/tests/test_calibration_resnet50.py
Labels: Intel

#16994 resolve #16987
  python/paddle/fluid/tests/unittests/test_conv2d_op.py
Labels: Intel

#16995 resolve #16988
  python/paddle/fluid/tests/unittests/test_conv2d_op.py
Labels: Intel

#16990 update ngraph version
  cmake/external/ngraph.cmake
Labels: Intel, NGraph

#17058 Fix the bug of test_conv2d_int8_mkldnn case which raised by improper parameter passing
  python/paddle/fluid/tests/unittests/mkldnn/test_conv2d_int8_mkldnn_op.py
Labels: Intel

#17012 [cherry-pick]Detailed coordinate description for yolov3 loss
  paddle/fluid/API.spec
  paddle/fluid/operators/detection/yolov3_loss_op.cc
  python/paddle/fluid/layers/detection.py
Labels: 文档

#17148 fix assertion failure issue when test_analyzer_bert uses ngraph
  paddle/fluid/operators/ngraph/ops/softmax_op.h
Labels: Intel, NGraph

#17172 Update the folder name generation mechanism for saving the quantized model and weights during the test_calibration* execution phase.
  python/paddle/fluid/contrib/tests/test_calibration_mobilenetv1.py
  python/paddle/fluid/contrib/tests/test_calibration_resnet50.py
Labels: Intel, int8
