Repository PaddlePaddle/Paddle, pull requests merged in 2019-07, with the labels that each got.

#18186 Fix Pooling output scale
  paddle/fluid/framework/ir/mkldnn/cpu_quantize_pass.cc
  paddle/fluid/inference/api/mkldnn_quantizer.cc
Labels: Intel, int8

#18453 rename mkldnn set/get_cur_thread_id() to set/get_cur_mkldnn_session_id()
  paddle/fluid/operators/mkldnn/concat_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/pool_mkldnn_op.cc
  paddle/fluid/platform/device_context.cc
  paddle/fluid/platform/device_context.h
  paddle/fluid/platform/mkldnn_reuse.h
Labels: Intel

#18507 Fix command line bug in int8 mkldnn quantization readme
  paddle/fluid/inference/tests/api/int8_mkldnn_quantization.md
Labels: Intel, int8

#18428 use static variable to do cache instead of thread local in thread frequent switching case
  paddle/fluid/framework/transfer_scope_cache.cc
  paddle/fluid/inference/tests/api/analyzer_bert_tester.cc
Labels: Intel

#17834 Add mkldnn int8 mul-op kernel
  paddle/fluid/operators/mkldnn/mul_mkldnn_op.cc
  paddle/fluid/operators/mul_op.cc
  paddle/fluid/operators/mul_op.h
  paddle/fluid/platform/mkldnn_helper.h
  python/paddle/fluid/tests/unittests/mkldnn/test_mul_int8_mkldnn_op.py
  python/paddle/fluid/tests/unittests/test_operator_desc.py
Labels: Intel, int8

#18322 QAT int8 MKL-DNN transformation pass with MUL
  python/paddle/fluid/contrib/slim/quantization/quantization_mkldnn_pass.py
  python/paddle/fluid/contrib/slim/tests/test_quantization_mkldnn_pass.py
Labels: Intel, int8

#18191 [MKL-DNN] Activations MKLDNN ops refactoring
  paddle/fluid/operators/mkldnn/activation_mkldnn_op.cc
  paddle/fluid/platform/mkldnn_reuse.h
Labels: Intel

#18578 not use transferscope cache in cpu case
  paddle/fluid/framework/operator.cc
  paddle/fluid/framework/operator.h
Labels: Intel

#18585 [MKL-DNN] Reimplemented pool2d mkl-dnn to use Acquire API
  paddle/fluid/operators/mkldnn/pool_mkldnn_op.cc
  paddle/fluid/platform/mkldnn_reuse.h
Labels: Code Cleanup, Intel

#18568 Remove reshape2_grad infershape special handling
  paddle/fluid/operators/ngraph/ngraph_engine.cc
  paddle/fluid/operators/ngraph/ops/gather_op.h
  paddle/fluid/operators/ngraph/ops/reshape_op.h
  paddle/fluid/operators/ngraph/ops/transpose_op.h
Labels: Intel, NGraph

#18634 Fix the compiling issue with AVX512F macro
  paddle/fluid/operators/jit/more/intrinsic/crf_decoding.cc
Labels: Intel

#18656 Add LeakyRelu MKLDNN support
  paddle/fluid/operators/activation_op.cc
  paddle/fluid/operators/activation_op.h
  paddle/fluid/operators/mkldnn/activation_mkldnn_op.cc
  python/paddle/fluid/tests/unittests/mkldnn/test_activation_mkldnn_op.py
  python/paddle/fluid/tests/unittests/test_activation_op.py
Labels: Intel

#18370 [MKL-DNN]Bump up mkl-dnn to 0.20
  cmake/external/mkldnn.cmake
  paddle/fluid/platform/mkldnn_reuse.h
Labels: Intel, int8

#18675 [MKL-DNN] Extended LRN with reusing via Acquire API
  paddle/fluid/operators/mkldnn/lrn_mkldnn_op.cc
  paddle/fluid/platform/mkldnn_reuse.h
Labels: Code Cleanup, Intel, performance tuning

#18570 Extend Matmul to support matrix multiplication with multiple heads
  paddle/fluid/operators/math/blas.h
  paddle/fluid/operators/math/blas_impl.h
  paddle/fluid/operators/matmul_op.cc
  python/paddle/fluid/tests/unittests/CMakeLists.txt
  python/paddle/fluid/tests/unittests/test_matmul_op_with_head.py
Labels: Intel

#18756 change ComputeINT8 to template version to remove checking dst_datatype code
  paddle/fluid/operators/mkldnn/conv_mkldnn_op.cc
  paddle/fluid/platform/mkldnn_helper.h
  paddle/fluid/platform/mkldnn_reuse.h
Labels: Intel, int8

#18685 clarify INT8 Mul Op attributes
  paddle/fluid/operators/mkldnn/mul_mkldnn_op.cc
  paddle/fluid/operators/mul_op.cc
Labels: Intel, int8

#18816 fix mul_mkldnn_op build failure
  paddle/fluid/operators/mkldnn/mul_mkldnn_op.cc
Labels: Intel

#18791 remove unused TransposeINT8MKLDNNOpKernel for higher UT coverage
  paddle/fluid/operators/mkldnn/transpose_mkldnn_op.cc
Labels: Code Cleanup, Intel

#18762 Add LeakyReLU MKLDNN support
  paddle/fluid/operators/activation_op.cc
  paddle/fluid/operators/mkldnn/activation_mkldnn_op.cc
  python/paddle/fluid/tests/unittests/mkldnn/test_activation_mkldnn_op.py
  python/paddle/fluid/tests/unittests/test_activation_op.py
Labels: Intel, performance tuning

#18879 Revert "use static variable to do cache instead of thread local in thread frequent switching case
  paddle/fluid/framework/transfer_scope_cache.cc
  paddle/fluid/inference/tests/api/analyzer_bert_tester.cc
Labels: Intel

#18758 [MKL-DNN] Fix to int8 performance regression (#18698)
  paddle/fluid/operators/mkldnn/concat_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/conv_mkldnn_op.cc
  paddle/fluid/platform/mkldnn_reuse.h
Labels: Intel, inference, int8, performance tuning

#18853 upgrade ngraph version and simplify ngraph engine
  cmake/external/ngraph.cmake
  paddle/fluid/operators/ngraph/ngraph_engine.cc
  paddle/fluid/operators/ngraph/ngraph_engine.h
Labels: Intel, NGraph

#18099 use mkl to accelerate gelu_grad
  paddle/fluid/operators/activation_op.h
Labels: Intel
