Repository PaddlePaddle/Paddle, pull requests merged in 2019-02, with the labels that each got.

#15636 Fix ngraph compile WITH_DISTRIBUTE=ON
  paddle/fluid/framework/CMakeLists.txt
  paddle/fluid/operators/ngraph/ngraph_engine_op.h
  python/paddle/fluid/tests/unittests/ngraph/test_accuracy_ngraph_op.py
  python/paddle/fluid/tests/unittests/ngraph/test_conv2d_ngraph_op.py
  python/paddle/fluid/tests/unittests/ngraph/test_elementwise_add_ngraph_op.py
  python/paddle/fluid/tests/unittests/ngraph/test_mean_ngraph_op.py
  python/paddle/fluid/tests/unittests/ngraph/test_mul_ngraph_op.py
  python/paddle/fluid/tests/unittests/ngraph/test_pool2d_ngraph_op.py
  python/paddle/fluid/tests/unittests/ngraph/test_scale_ngraph_op.py
  python/paddle/fluid/tests/unittests/ngraph/test_top_k_ngraph_op.py
Labels: Intel, NGraph

#15628 Clang build fixes
  paddle/fluid/framework/details/computation_op_handle.h
  paddle/fluid/framework/details/parallel_ssa_graph_executor.cc
  paddle/fluid/framework/ir/graph.cc
  paddle/fluid/framework/operator.cc
  paddle/fluid/framework/operator.h
  paddle/fluid/inference/analysis/ir_pass_manager.cc
  paddle/fluid/inference/api/analysis_predictor.cc
  paddle/fluid/memory/allocation/allocator_facade.cc
  paddle/fluid/operators/jit/gen/act.h
  paddle/fluid/operators/jit/gen/blas.h
  paddle/fluid/operators/jit/gen/hopv.h
  paddle/fluid/operators/jit/gen/jitcode.h
  paddle/fluid/operators/jit/gen/matmul.h
  paddle/fluid/operators/jit/gen/seqpool.h
  paddle/fluid/pybind/inference_api.cc
Labels: Intel

#15375 Enable batch_norm operator for a ngraph engine
  paddle/fluid/operators/ngraph/ngraph_bridge.cc
  paddle/fluid/operators/ngraph/ngraph_ops.h
  paddle/fluid/operators/ngraph/ops/batch_norm_op.h
  paddle/fluid/platform/ngraph_helper.h
  python/paddle/fluid/tests/unittests/ngraph/test_batch_norm_ngraph_op.py
Labels: Intel, NGraph

#15659 Tests - add some missing to_string calls
  paddle/fluid/framework/details/fused_broadcast_op_handle_test.cc
  paddle/fluid/framework/ir/seqpool_concat_fuse_pass_tester.cc
Labels: Intel

#15626 fix aligned-new error in jitkernel
  paddle/fluid/operators/jit/gen_base.cc
  paddle/fluid/operators/jit/gen_base.h
Labels: Intel

#15642 Add ngraph sum, sigmoid, relu_grad and tanh_grad op
  paddle/fluid/operators/ngraph/ngraph_bridge.cc
  paddle/fluid/operators/ngraph/ngraph_ops.h
  paddle/fluid/operators/ngraph/ops/activation_op.h
  paddle/fluid/operators/ngraph/ops/sum_op.h
  python/paddle/fluid/tests/unittests/ngraph/test_activation_ngraph_op.py
  python/paddle/fluid/tests/unittests/ngraph/test_sum_ngraph_op.py
Labels: Intel, NGraph

#15701 Fix old FC backward weights descriptor creation
  paddle/fluid/operators/mkldnn/fc_mkldnn_op.cc
Labels: Intel

#15704 Fix old FC backward weights descriptor creation
  paddle/fluid/operators/mkldnn/fc_mkldnn_op.cc
Labels: Intel

#15739 resolve #15724
  python/paddle/fluid/contrib/int8_inference/README.md
  python/paddle/fluid/contrib/tests/CMakeLists.txt
  python/paddle/fluid/contrib/tests/test_calibration.py
Labels: Intel, int8

#15719 Removed duplicated code
  paddle/fluid/inference/analysis/ir_passes/subgraph_detector.cc
  paddle/fluid/inference/analysis/ir_passes/subgraph_detector.h
Labels: Intel

#15763 [cherry-pick] [V1.3] resolve #15724
  python/paddle/fluid/contrib/int8_inference/README.md
  python/paddle/fluid/contrib/tests/CMakeLists.txt
  python/paddle/fluid/contrib/tests/test_calibration.py
Labels: Intel, int8

#15768 Removed duplicated code
  paddle/fluid/inference/analysis/ir_passes/subgraph_detector.cc
  paddle/fluid/inference/analysis/ir_passes/subgraph_detector.h
Labels: Intel

#15699 Add JIT CRF_decoding and Layer_norm unit-test
  paddle/fluid/operators/jit/benchmark.cc
  paddle/fluid/operators/jit/test.cc
Labels: Intel

#15721 Add ngraph op coverage
  paddle/fluid/operators/ngraph/ops/fill_constant_op.h
  python/paddle/fluid/tests/unittests/ngraph/test_accuracy_ngraph_op.py
  python/paddle/fluid/tests/unittests/ngraph/test_batch_norm_ngraph_op.py
  python/paddle/fluid/tests/unittests/ngraph/test_conv2d_ngraph_op.py
  python/paddle/fluid/tests/unittests/ngraph/test_elementwise_add_ngraph_op.py
  python/paddle/fluid/tests/unittests/ngraph/test_fill_constant_ngraph_op.py
  python/paddle/fluid/tests/unittests/ngraph/test_mean_ngraph_op.py
  python/paddle/fluid/tests/unittests/ngraph/test_mul_ngraph_op.py
  python/paddle/fluid/tests/unittests/ngraph/test_pool2d_ngraph_op.py
  python/paddle/fluid/tests/unittests/ngraph/test_scale_ngraph_op.py
  python/paddle/fluid/tests/unittests/ngraph/test_softmax_ngraph_op.py
  python/paddle/fluid/tests/unittests/ngraph/test_top_k_ngraph_op.py
  python/paddle/fluid/tests/unittests/op_test.py
Labels: Intel, NGraph

#15674 Enable cross_entropy operator for a ngraph engine
  paddle/fluid/operators/ngraph/ngraph_bridge.cc
  paddle/fluid/operators/ngraph/ngraph_ops.h
  paddle/fluid/operators/ngraph/ops/batch_norm_op.h
  paddle/fluid/operators/ngraph/ops/cross_entropy_op.h
  python/paddle/fluid/tests/unittests/ngraph/test_cross_entropy_ngraph_op.py
Labels: Intel, NGraph

#15857 Fix few typos
  paddle/fluid/framework/op_proto_maker.h
  paddle/fluid/inference/api/analysis_config.cc
  paddle/fluid/inference/api/analysis_predictor.cc
  paddle/fluid/inference/api/analysis_predictor.h
  paddle/fluid/inference/api/analysis_predictor_tester.cc
  paddle/fluid/inference/api/api_impl.cc
  paddle/fluid/inference/api/paddle_analysis_config.h
  paddle/fluid/inference/api/paddle_api.h
Labels: Intel

#15854 update AUTHORS.md
  AUTHORS.md
Labels: Intel

#15856 MKL-DNN: Add UT to check whether primitives already exist in backward
  paddle/fluid/operators/mkldnn/activation_mkldnn_op.cc
  python/paddle/fluid/tests/unittests/mkldnn/test_activation_mkldnn_op.py
Labels: Intel

#15862 add override to ApplyImpl and precommit fixes
  paddle/fluid/framework/ir/attention_lstm_fuse_pass.h
  paddle/fluid/framework/ir/conv_affine_channel_fuse_pass.h
  paddle/fluid/framework/ir/conv_bn_fuse_pass.h
  paddle/fluid/framework/ir/conv_elementwise_add2_act_fuse_pass.h
  paddle/fluid/framework/ir/conv_elementwise_add_act_fuse_pass.h
  paddle/fluid/framework/ir/conv_elementwise_add_fuse_pass.h
  paddle/fluid/framework/ir/embedding_fc_lstm_fuse_pass.h
  paddle/fluid/framework/ir/fc_fuse_pass.h
  paddle/fluid/framework/ir/fc_gru_fuse_pass.h
  paddle/fluid/framework/ir/fc_lstm_fuse_pass.h
  paddle/fluid/framework/ir/fuse_elewise_add_act_pass.h
  paddle/fluid/framework/ir/fuse_relu_depthwise_conv_pass.h
  paddle/fluid/framework/ir/identity_scale_op_clean_pass.h
  paddle/fluid/framework/ir/lock_free_optimize_pass.h
  paddle/fluid/framework/ir/mkldnn/conv_bias_mkldnn_fuse_pass.h
  paddle/fluid/framework/ir/repeated_fc_relu_fuse_pass.h
  paddle/fluid/framework/ir/seq_concat_fc_fuse_pass.h
  paddle/fluid/framework/ir/seqconv_eltadd_relu_fuse_pass.h
  paddle/fluid/framework/ir/seqpool_concat_fuse_pass.h
  paddle/fluid/framework/ir/squared_mat_sub_fuse_pass.h
  paddle/fluid/framework/ir/transpose_flatten_concat_fuse_pass.h
Labels: Intel

#15402 The list of all oeprators is created to avoid any conflicts
  paddle/fluid/operators/ngraph/CMakeLists.txt
  paddle/fluid/operators/ngraph/ngraph_bridge.cc
  paddle/fluid/operators/ngraph/ngraph_bridge.h
  paddle/fluid/operators/ngraph/ngraph_engine.cc
  paddle/fluid/operators/ngraph/ngraph_ops.h
  paddle/fluid/operators/ngraph/ops/CMakeLists.txt
  paddle/fluid/operators/ngraph/ops/accuracy_op.h
  paddle/fluid/operators/ngraph/ops/activation_op.h
  paddle/fluid/operators/ngraph/ops/batch_norm_op.h
  paddle/fluid/operators/ngraph/ops/binary_unary_op.h
  paddle/fluid/operators/ngraph/ops/conv2d_op.h
  paddle/fluid/operators/ngraph/ops/cross_entropy_op.h
  paddle/fluid/operators/ngraph/ops/elementwise_add_op.h
  paddle/fluid/operators/ngraph/ops/fill_constant_op.h
  paddle/fluid/operators/ngraph/ops/mean_op.h
  paddle/fluid/operators/ngraph/ops/momentum_op.h
  paddle/fluid/operators/ngraph/ops/mul_op.h
  paddle/fluid/operators/ngraph/ops/op_bridge.h
  paddle/fluid/operators/ngraph/ops/pool2d_op.h
  paddle/fluid/operators/ngraph/ops/scale_op.h
  paddle/fluid/operators/ngraph/ops/softmax_op.h
  paddle/fluid/operators/ngraph/ops/top_k_op.h
Labels: Intel, NGraph

#15824 MKL-DNN: Add test for conv bias fuse pass
  paddle/fluid/framework/ir/CMakeLists.txt
  paddle/fluid/framework/ir/mkldnn/conv_bias_mkldnn_fuse_pass_tester.cc
Labels: Intel, unitest

#15770 Optimze Gelu with MKL Erf function
  cmake/external/mklml.cmake
  paddle/fluid/operators/activation_op.h
  paddle/fluid/operators/math/blas.h
  paddle/fluid/operators/math/blas_impl.h
  paddle/fluid/platform/dynload/mklml.h
Labels: Intel

#15882 Change *(smart_ptr.get()) -> *smart_ptr
  paddle/fluid/operators/beam_search_decode_op.h
  paddle/fluid/operators/mkldnn/activation_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/pool_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/softmax_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/sum_mkldnn_op.cc
  paddle/fluid/platform/device_context.cc
  paddle/fluid/platform/mkldnn_reuse.h
  paddle/fluid/train/demo/demo_trainer.cc
  paddle/fluid/train/test_train_recognize_digits.cc
Labels: Intel

#15429 [MKL-DNN] MKL-DNN specific Tensor modification
  paddle/fluid/framework/data_layout_transform.cc
  paddle/fluid/framework/data_transform.cc
  paddle/fluid/framework/tensor.h
  paddle/fluid/operators/mkldnn/conv_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/gaussian_random_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/transpose_mkldnn_op.cc
  paddle/fluid/platform/mkldnn_reuse.h
  paddle/fluid/platform/mkldnn_utils.h
Labels: Intel

#15901 cherry-pick pool/adaptive_pool/yolov3_loss doc fix
  paddle/fluid/operators/detection/yolov3_loss_op.cc
  paddle/fluid/operators/pool_op.cc
  python/paddle/fluid/layers/detection.py
  python/paddle/fluid/layers/nn.py
Labels: 文档

#15914 Refactor MKL-DNN Sum to use reference version on fallback
  paddle/fluid/operators/mkldnn/sum_mkldnn_op.cc
Labels: Intel

#15909 This PR improve performance of prior_box op about 1.25x faster on CPU.
  paddle/fluid/operators/detection/prior_box_op.h
Labels: Intel

#15923 Add Conv Residual Connection UT for Projection
  paddle/fluid/framework/ir/mkldnn/conv_elementwise_add_mkldnn_fuse_pass_tester.cc
Labels: Intel, unitest

#15922 MKL-DNN: Add Activations and Softmax UTs to check if primitives already exist in backward
  python/paddle/fluid/tests/unittests/mkldnn/mkldnn_op_test.py
  python/paddle/fluid/tests/unittests/mkldnn/test_activation_mkldnn_op.py
  python/paddle/fluid/tests/unittests/mkldnn/test_softmax_mkldnn_op.py
  python/paddle/fluid/tests/unittests/test_softmax_op.py
Labels: Intel

#15913 Enable function coverage for U8/S8 ConvMKLDNNOpKernel
  cmake/operators.cmake
  paddle/fluid/framework/op_registry.h
  paddle/fluid/operators/conv_op.cc
  paddle/fluid/operators/mkldnn/conv_mkldnn_op.cc
Labels: Intel, int8

#15917 [MKL-DNN] Adjusting ops to Tensor modifications
  paddle/fluid/operators/elementwise/mkldnn/elementwise_add_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/activation_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/batch_norm_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/concat_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/conv_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/conv_transpose_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/lrn_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/softmax_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/sum_mkldnn_op.cc
Labels: Intel

#15943 MKL-DNN: Add placement pass tester
  paddle/fluid/framework/ir/CMakeLists.txt
  paddle/fluid/framework/ir/mkldnn/mkldnn_placement_pass.cc
  paddle/fluid/framework/ir/mkldnn/mkldnn_placement_pass_tester.cc
Labels: Intel

#15883 INT8 Pool kernel Key Creation Optimization.
  paddle/fluid/operators/mkldnn/pool_mkldnn_op.cc
  paddle/fluid/platform/mkldnn_reuse.h
Labels: Intel, int8

#15924 Update ngraph version to v0.14
  cmake/external/ngraph.cmake
  paddle/fluid/operators/ngraph/ngraph_engine.cc
Labels: Intel, NGraph

#15946 added concat op for ngraph engine
  paddle/fluid/operators/ngraph/ops/concat_op.h
  python/paddle/fluid/tests/unittests/ngraph/test_concat_ngraph_op.py
Labels: Intel, NGraph

#15889 Enable the operator for the nGraph bridge
  paddle/fluid/operators/ngraph/ops/sum_op.h
Labels: Intel, NGraph

#15710 Add adam op for ngraph engine
  paddle/fluid/operators/ngraph/ops/adam_op.h
  python/paddle/fluid/tests/unittests/ngraph/test_adam_ngraph_op.py
Labels: NGraph

#15930 Optimize INT8 DeQuantize Op with primitive reuse.
  paddle/fluid/operators/mkldnn/dequantize_mkldnn_op.cc
Labels: Intel, int8

#15929 Optimize INT8 Quantize Op with primitive reuse.
  paddle/fluid/operators/mkldnn/quantize_mkldnn_op.cc
Labels: Intel, int8

#15931 Optimize gelu operation with mkl erf
  cmake/external/mklml.cmake
  paddle/fluid/operators/activation_op.h
  paddle/fluid/operators/math/blas.h
  paddle/fluid/operators/math/blas_impl.h
  paddle/fluid/platform/dynload/mklml.h
Labels: Intel

#15941 The flag of mkldnn engine is enabled iff it is necessary
  paddle/fluid/pybind/pybind.cc
  python/paddle/fluid/__init__.py
Labels: Intel
