Repository PaddlePaddle/Paddle, pull requests merged in 2019-08, with the labels that each got.

#18303 [PROPOSAL] Add support for dynamic code analysis (Sanitizers)
  CMakeLists.txt
  cmake/flags.cmake
Labels: Intel

#18911 [MKL-DNN] Removing transfering X from FWD to GRAD via device context
  paddle/fluid/operators/mkldnn/activation_mkldnn_op.cc
  paddle/fluid/platform/mkldnn_reuse.h
Labels: Code Cleanup, Intel, concurrency

#18622 Fix memory leak in test
  paddle/testing/paddle_gtest_main.cc
Labels: Intel

#18265 ngraph : fix for multithreading test_analyzer_image_classification
  paddle/fluid/operators/ngraph/ngraph_engine.cc
  paddle/fluid/operators/ngraph/ngraph_engine.h
Labels: Intel, NGraph

#19067 Add call stack info during compile time
  paddle/fluid/framework/CMakeLists.txt
  paddle/fluid/framework/op_call_stack.cc
  paddle/fluid/framework/op_call_stack.h
  paddle/fluid/framework/op_desc.cc
  paddle/fluid/framework/operator.cc
  python/paddle/fluid/tests/unittests/test_runtime_and_compiletime_exception.py
Labels: Error Message

#18765 optimize error message for "embedding" and "cross_entropy" OP
  paddle/fluid/operators/cross_entropy_op.h
  paddle/fluid/operators/lookup_table_op.cu
  paddle/fluid/operators/lookup_table_op.h
  paddle/fluid/platform/assert.h
Labels: Error Message

#18988 Replace Relu with bounded Relu in MobileNetV2 quantization mkldnn
  paddle/fluid/framework/ir/mkldnn/cpu_quantize_pass.cc
  paddle/fluid/operators/mkldnn/conv_mkldnn_op.cc
Labels: Intel, int8

#19011 UT coverage for guassian_mkldnn_op and batch_norm_mkldnn_op
  python/paddle/fluid/tests/unittests/mkldnn/mkldnn_op_test.py
  python/paddle/fluid/tests/unittests/mkldnn/test_batch_norm_mkldnn_op.py
  python/paddle/fluid/tests/unittests/mkldnn/test_gaussian_random_mkldnn_op.py
Labels: Intel

#18754 Add conv reqantize squash
  paddle/fluid/framework/ir/graph_pattern_detector.cc
  paddle/fluid/framework/ir/graph_pattern_detector.h
  paddle/fluid/framework/ir/mkldnn/cpu_quantize_squash_pass.cc
  paddle/fluid/framework/ir/mkldnn/cpu_quantize_squash_pass.h
  paddle/fluid/framework/ir/mkldnn/cpu_quantize_squash_pass_tester.cc
Labels: Intel, int8

#19070 Enhance the error message when GrapOpMaker is null.
  paddle/fluid/framework/op_info.h
Labels: Error Message

#19072 Add generalized Conv+Activation MKLDNN fuse pass creation Part1
  paddle/fluid/framework/ir/CMakeLists.txt
  paddle/fluid/framework/ir/graph_pattern_detector.cc
  paddle/fluid/framework/ir/graph_pattern_detector.h
  paddle/fluid/framework/ir/mkldnn/conv_activation_mkldnn_fuse_pass.cc
  paddle/fluid/framework/ir/mkldnn/conv_activation_mkldnn_fuse_pass.h
  paddle/fluid/framework/ir/mkldnn/conv_activation_mkldnn_fuse_pass_tester.cc
  paddle/fluid/framework/ir/mkldnn/conv_concat_relu_mkldnn_fuse_pass.cc
  paddle/fluid/framework/ir/mkldnn/conv_concat_relu_mkldnn_fuse_pass_tester.cc
  paddle/fluid/framework/ir/mkldnn/conv_elementwise_add_mkldnn_fuse_pass.cc
  paddle/fluid/inference/api/mkldnn_quantizer.cc
  paddle/fluid/inference/api/paddle_pass_builder.cc
  paddle/fluid/operators/conv_op.cc
  paddle/fluid/operators/conv_transpose_op.cc
  paddle/fluid/operators/mkldnn/conv_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/conv_transpose_mkldnn_op.cc
  paddle/fluid/platform/mkldnn_reuse.h
  python/paddle/fluid/tests/unittests/mkldnn/test_conv2d_int8_mkldnn_op.py
  python/paddle/fluid/tests/unittests/mkldnn/test_conv2d_mkldnn_op.py
  python/paddle/fluid/tests/unittests/mkldnn/test_conv2d_transpose_mkldnn_op.py
Labels: Intel

#18946 Fix mAP problem in unit test of int8 object detection test
  paddle/fluid/inference/tests/api/CMakeLists.txt
  paddle/fluid/inference/tests/api/analyzer_int8_object_detection_tester.cc
  paddle/fluid/inference/tests/api/tester_helper.h
Labels: Intel, int8

#19161 fix temporal_shift OP PADDLE_ENFORCE. test=develop
  paddle/fluid/operators/temporal_shift_op.cc
Labels: Error Message

#19064 Use sparse matrix to implement fused emb_seq_pool operator
  CMakeLists.txt
  cmake/external/mklml.cmake
  paddle/fluid/operators/fused/fused_embedding_seq_pool_op.h
  paddle/fluid/operators/math/blas.h
  paddle/fluid/operators/math/blas_impl.h
  paddle/fluid/platform/dynload/mklml.h
Labels: Intel

#19247 Modify PADDLE_ENFORCE to PADDLE_ENFORCE_CUDA_SUCCESS
  paddle/fluid/operators/math/blas_impl.cu.h
  paddle/fluid/platform/enforce.h
  paddle/fluid/platform/enforce_test.cc
Labels: Error Message

#19285 replace part of PADDLE_ASSERT to PADDLE_ENFORCE
  paddle/fluid/memory/detail/memory_block.cc
  paddle/fluid/memory/detail/meta_cache.cc
  paddle/fluid/memory/detail/system_allocator.cc
  paddle/fluid/memory/detail/system_allocator.h
  paddle/fluid/memory/detail/system_allocator_test.cc
  paddle/fluid/platform/float16_test.cc
  paddle/fluid/platform/float16_test.cu
Labels: Error Message

#19191 Add elementwise_mul_mkldnn UT with [conv + elt_mul + conv]
  python/paddle/fluid/tests/unittests/mkldnn/test_elementwise_mul_mkldnn_op.py
Labels: Intel

#19237 Add generalized Conv+Activation MKLDNN fuse pass creation Part2
  paddle/fluid/framework/ir/graph_pattern_detector.cc
  paddle/fluid/framework/ir/graph_pattern_detector.h
  paddle/fluid/framework/ir/mkldnn/conv_activation_mkldnn_fuse_pass.cc
  paddle/fluid/framework/ir/mkldnn/conv_activation_mkldnn_fuse_pass_tester.cc
  paddle/fluid/framework/ir/mkldnn/conv_brelu_mkldnn_fuse_pass.cc
  paddle/fluid/framework/ir/mkldnn/conv_brelu_mkldnn_fuse_pass.h
  paddle/fluid/framework/ir/mkldnn/conv_brelu_mkldnn_fuse_pass_tester.cc
  paddle/fluid/framework/ir/mkldnn/conv_elementwise_add_mkldnn_fuse_pass.cc
  paddle/fluid/framework/ir/mkldnn/conv_elementwise_add_mkldnn_fuse_pass.h
  paddle/fluid/framework/ir/mkldnn/conv_relu_mkldnn_fuse_pass.cc
  paddle/fluid/framework/ir/mkldnn/conv_relu_mkldnn_fuse_pass.h
  paddle/fluid/framework/ir/mkldnn/conv_relu_mkldnn_fuse_pass_tester.cc
  paddle/fluid/framework/ir/mkldnn/cpu_quantize_pass.cc
  paddle/fluid/framework/op_desc.h
  paddle/fluid/inference/api/mkldnn_quantizer.cc
  paddle/fluid/operators/mkldnn/conv_mkldnn_op.cc
Labels: Intel

#19303 stronger the error message of tensor's mutable_data
  paddle/fluid/framework/tensor.cc
Labels: Error Message

#19153 Use sparse matrix to implement FusedEmbeddingSeqPoolGradKernel
  paddle/fluid/operators/fused/fused_embedding_seq_pool_op.h
  python/paddle/fluid/tests/unittests/test_fused_emb_seq_pool_op.py
Labels: Intel

#19283 add local user data conversion into full_pascalvoc_test_preprocess.py
  paddle/fluid/inference/api/helper.h
  paddle/fluid/inference/tests/api/CMakeLists.txt
  paddle/fluid/inference/tests/api/analyzer_int8_object_detection_tester.cc
  paddle/fluid/inference/tests/api/full_pascalvoc_test_preprocess.py
  paddle/fluid/inference/tests/api/test_detection_dataset_preprocess.py
  paddle/fluid/inference/tests/api/tester_helper.h
Labels: Intel

#18905 Add conv dequant squash
  paddle/fluid/framework/ir/graph_pattern_detector.cc
  paddle/fluid/framework/ir/graph_pattern_detector.h
  paddle/fluid/framework/ir/mkldnn/cpu_quantize_squash_pass.cc
  paddle/fluid/framework/ir/mkldnn/cpu_quantize_squash_pass.h
  paddle/fluid/framework/ir/mkldnn/cpu_quantize_squash_pass_tester.cc
Labels: Intel, int8

#19155 Update ngraph engine for multiple threading
  paddle/fluid/operators/ngraph/ngraph_engine.cc
  paddle/fluid/operators/ngraph/ngraph_engine.h
Labels: Intel, NGraph

#19476 clean up intel labeled TODOs
  paddle/fluid/operators/mkldnn/concat_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/conv_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/conv_transpose_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/gaussian_random_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/quantize_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/requantize_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/sum_mkldnn_op.cc
  paddle/fluid/operators/ngraph/ops/reshape_op.h
  python/paddle/fluid/contrib/slim/quantization/mkldnn_post_training_strategy.py
  python/paddle/fluid/tests/unittests/mkldnn/test_elementwise_mul_mkldnn_op.py
Labels: Intel

#19529 remove unused assert.h
  paddle/fluid/framework/lod_tensor_test.cu
  paddle/fluid/memory/detail/buddy_allocator.h
  paddle/fluid/memory/detail/system_allocator.cc
  paddle/fluid/operators/argsort_op.cu
  paddle/fluid/operators/conv_transpose_cudnn_op.cu.cc
  paddle/fluid/operators/detection/target_assign_op.h
  paddle/fluid/operators/filter_by_instag_op.h
  paddle/fluid/operators/top_k_op.cu
Labels: Error Message

#19282 [MKL-DNN] Fix to face model on AVX512 platforms
  paddle/fluid/framework/data_layout_transform.cc
  paddle/fluid/framework/data_layout_transform.h
  paddle/fluid/operators/controlflow/fetch_op.cc
  paddle/fluid/operators/mkldnn/activation_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/batch_norm_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/mul_mkldnn_op.cc
  paddle/fluid/platform/mkldnn_helper.h
  paddle/fluid/platform/mkldnn_reuse.h
  python/paddle/fluid/tests/unittests/mkldnn/test_conv2d_int8_mkldnn_op.py
  python/paddle/fluid/tests/unittests/mkldnn/test_elementwise_mul_mkldnn_op.py
Labels: Intel, inference
