Repository PaddlePaddle/Paddle, pull requests merged in 2019-09, with the labels that each got.

#19312 [MKL-DNN] Refactoring Softmax
  paddle/fluid/operators/mkldnn/softmax_mkldnn_op.cc
  paddle/fluid/platform/mkldnn_reuse.h
Labels: Code Cleanup, Intel

#19586 replace PADDLE_ASSERT with PADDLE_ASSERT_MSG
  paddle/fluid/operators/bpr_loss_op.h
  paddle/fluid/operators/math/cross_entropy.cu
  paddle/fluid/operators/math/cross_entropy.h
  paddle/fluid/operators/math/unpooling.cu
  paddle/fluid/operators/modified_huber_loss_op.h
  paddle/fluid/operators/random_crop_op.h
  paddle/fluid/operators/sample_logits_op.h
  paddle/fluid/platform/assert.h
  python/paddle/fluid/tests/unittests/CMakeLists.txt
Labels: Error Message

#19515 Some ngraph op and unittest fix
  paddle/fluid/operators/ngraph/ngraph_bridge.cc
  paddle/fluid/operators/ngraph/ops/concat_op.h
  paddle/fluid/operators/ngraph/ops/conv2d_op.h
  paddle/fluid/operators/ngraph/ops/cross_entropy_op.h
  paddle/fluid/operators/ngraph/ops/dropout_op.h
  paddle/fluid/operators/ngraph/ops/lookup_table_op.h
  paddle/fluid/operators/ngraph/ops/slice_op.h
  python/paddle/fluid/tests/unittests/ngraph/test_assign_ngraph_op.py
  python/paddle/fluid/tests/unittests/ngraph/test_concat_ngraph_op.py
  python/paddle/fluid/tests/unittests/ngraph/test_lookup_table_ngraph_op.py
  python/paddle/fluid/tests/unittests/ngraph/test_reshape_ngraph_op.py
  python/paddle/fluid/tests/unittests/ngraph/test_slice_ngraph_op.py
  python/paddle/fluid/tests/unittests/op_test.py
Labels: Intel, NGraph

#19568 using MKLDNNMemoryFormat = mkldnn::memory::format changes
  paddle/fluid/framework/data_layout_transform.cc
  paddle/fluid/framework/data_layout_transform.h
  paddle/fluid/operators/elementwise/mkldnn/elementwise_add_mkldnn_op.cc
  paddle/fluid/operators/elementwise/mkldnn/elementwise_mul_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/activation_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/batch_norm_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/concat_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/conv_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/conv_transpose_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/dequantize_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/fc_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/mul_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/pool_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/requantize_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/softmax_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/sum_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/transpose_mkldnn_op.cc
  paddle/fluid/platform/mkldnn_helper.h
  paddle/fluid/platform/mkldnn_reuse.h
Labels: Intel

#19611 paddle::framework::vectorize() templatization
  paddle/fluid/framework/data_layout_transform.cc
  paddle/fluid/framework/ddim.cc
  paddle/fluid/framework/ddim.h
  paddle/fluid/framework/op_desc.cc
  paddle/fluid/operators/mkldnn/activation_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/batch_norm_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/concat_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/conv_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/conv_transpose_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/dequantize_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/fc_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/lrn_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/mul_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/pool_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/quantize_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/requantize_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/softmax_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/sum_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/transpose_mkldnn_op.cc
Labels: Code Cleanup, Intel

#19266 Enable ngraph through build_strategy
  paddle/fluid/framework/details/CMakeLists.txt
  paddle/fluid/framework/details/build_strategy.cc
  paddle/fluid/framework/executor.cc
  paddle/fluid/framework/ir/ngraph_subgraph_pass.cc
  paddle/fluid/inference/analysis/ir_passes/subgraph_detector.cc
  python/paddle/fluid/tests/unittests/ngraph/test_parallel_executor_ngraph.py
Labels: Intel, NGraph

#19605 Add user-friendly error message in optimizer ops to give a hint about the position sensitive problem of run(startup_program)
  paddle/fluid/operators/optimizers/adadelta_op.cc
  paddle/fluid/operators/optimizers/adagrad_op.cc
  paddle/fluid/operators/optimizers/adam_op.cc
  paddle/fluid/operators/optimizers/adamax_op.cc
  paddle/fluid/operators/optimizers/decayed_adagrad_op.cc
  paddle/fluid/operators/optimizers/ftrl_op.cc
  paddle/fluid/operators/optimizers/momentum_op.h
  paddle/fluid/operators/optimizers/sgd_op.cc
Labels: Error Message

#19631 unify PADDLE_ASSERT_MSG into PADDLE_ENFORCE(error_message)
  paddle/fluid/framework/dim.h
  paddle/fluid/inference/tensorrt/plugin/split_op_plugin.cu
  paddle/fluid/operators/center_loss_op.cu
  paddle/fluid/operators/cross_entropy_op.h
  paddle/fluid/operators/lookup_table_op.cu
  paddle/fluid/operators/math/CMakeLists.txt
  paddle/fluid/operators/math/cross_entropy.cu
  paddle/fluid/operators/math/cross_entropy.h
  paddle/fluid/operators/math/unpooling.cu
  paddle/fluid/operators/modified_huber_loss_op.h
  paddle/fluid/operators/random_crop_op.h
  paddle/fluid/operators/sample_logits_op.h
  paddle/fluid/platform/assert.h
  paddle/fluid/platform/enforce.h
Labels: Error Message

#19644 Code Cleanup: delete three useless raw variables in Conv2D
  paddle/fluid/operators/conv_cudnn_op_cache.h
  python/paddle/fluid/contrib/slim/tests/test_graph_wrapper.py
  python/paddle/fluid/dygraph/nn.py
  python/paddle/fluid/layers/nn.py
Labels: Code Cleanup

#19689 Upgrade ngraph to support mkldnn v1.0
  cmake/external/ngraph.cmake
Labels: Intel, NGraph

#19713 MKLDNN handler cleanup
  paddle/fluid/operators/elementwise/mkldnn/elementwise_add_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/concat_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/conv_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/dequantize_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/quantize_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/softmax_mkldnn_op.cc
  paddle/fluid/platform/mkldnn_helper.h
  paddle/fluid/platform/mkldnn_reuse.h
Labels: Code Cleanup, Intel

#19730 paddle::framework::vectorize() templatization [PART4]
  paddle/fluid/API.spec
  paddle/fluid/framework/ddim.cc
  paddle/fluid/framework/ddim.h
  paddle/fluid/operators/warpctc_cudnn_op.cu.cc
  paddle/fluid/operators/warpctc_op.cc
  python/paddle/fluid/layers/nn.py
  python/paddle/fluid/tests/unittests/test_warpctc_op.py
Labels: Code Cleanup

#19615 [MKL-DNN] Further refactoring of softmax
  paddle/fluid/operators/mkldnn/softmax_mkldnn_op.cc
Labels: Code Cleanup, Intel

#19748 [MKL-DNN] Refactoring activation mkldnn op
  paddle/fluid/operators/mkldnn/activation_mkldnn_op.cc
  paddle/fluid/platform/mkldnn_reuse.h
Labels: Code Cleanup, Intel

#19774 Fix the definition issue when used mkl_scsrmm and mkl_dcsrmm functions.
  paddle/fluid/platform/dynload/mklml.cc
Labels: Intel

#19767 Add common CreateKey for MKLDNN handlers
  paddle/fluid/framework/data_layout_transform.cc
  paddle/fluid/operators/elementwise/mkldnn/elementwise_add_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/activation_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/batch_norm_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/concat_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/conv_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/conv_transpose_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/dequantize_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/fc_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/lrn_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/mul_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/pool_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/quantize_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/softmax_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/transpose_mkldnn_op.cc
  paddle/fluid/platform/mkldnn_helper.h
  paddle/fluid/platform/mkldnn_reuse.h
Labels: Intel

#19770 Implement FusedEmbeddingSeqPoolGradKernel with cblas_saxpy
  paddle/fluid/operators/fused/fused_embedding_seq_pool_op.cc
  paddle/fluid/operators/fused/fused_embedding_seq_pool_op.h
  python/paddle/fluid/tests/unittests/test_fused_emb_seq_pool_op.py
Labels: Intel

#19801 Add MKLDNNhandler templatized class
  paddle/fluid/operators/mkldnn/softmax_mkldnn_op.cc
  paddle/fluid/platform/mkldnn_helper.h
  paddle/fluid/platform/mkldnn_reuse.h
Labels: Code Cleanup, Intel

#19714 Optimize amp for multi-gpu to enable FP16 gradients transfer across gpus
  paddle/fluid/API.spec
  python/paddle/fluid/contrib/mixed_precision/decorator.py
  python/paddle/fluid/contrib/mixed_precision/fp16_lists.py
  python/paddle/fluid/contrib/mixed_precision/fp16_utils.py
  python/paddle/fluid/contrib/tests/test_image_classification_fp16.py
Labels: AMP

#19867 Add template functions for Acquire primitive/primitive_desc
  paddle/fluid/operators/mkldnn/activation_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/softmax_mkldnn_op.cc
  paddle/fluid/platform/mkldnn_reuse.h
Labels: Code Cleanup, Intel

#19545 Fix conv2d+dequantize squash for residual fusion
  paddle/fluid/framework/ir/mkldnn/cpu_quantize_squash_pass.cc
Labels: Intel

#19574 Refactor conv computeINT8
  paddle/fluid/operators/mkldnn/conv_mkldnn_op.cc
  paddle/fluid/platform/mkldnn_reuse.h
Labels: Intel, int8

#19887 Refine executor bug info
  python/paddle/fluid/executor.py
Labels: Error Message

#19798 [MKL-DNN] LRN refactoring
  paddle/fluid/operators/mkldnn/lrn_mkldnn_op.cc
  paddle/fluid/platform/mkldnn_reuse.h
Labels: Code Cleanup, Intel

#19779 Refine err msg of out of gpu memory
  paddle/fluid/memory/detail/system_allocator.cc
Labels: Error Message

#19907 Add support for other axes in MKLDNN softmax op
  paddle/fluid/operators/mkldnn/softmax_mkldnn_op.cc
  paddle/fluid/operators/softmax_op.cc
  python/paddle/fluid/tests/unittests/mkldnn/test_softmax_mkldnn_op.py
  python/paddle/fluid/tests/unittests/test_softmax_op.py
Labels: Code Cleanup, Intel

#19840 Paddle split test fp32 int8
  paddle/fluid/inference/tests/api/tester_helper.h
Labels: Intel

#19872 optimize the error information when the input for while op has a wron…
  python/paddle/fluid/layers/control_flow.py
  python/paddle/fluid/tests/unittests/test_while_op.py
Labels: Error Message

#19911 [MKL-DNN] Pooling refactoring
  paddle/fluid/operators/mkldnn/pool_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/softmax_mkldnn_op.cc
  paddle/fluid/platform/mkldnn_reuse.h
Labels: Code Cleanup, Intel

#18970 Add support for new QAT models
  paddle/fluid/pybind/pybind.cc
  python/paddle/fluid/contrib/slim/quantization/quantization_mkldnn_pass.py
  python/paddle/fluid/contrib/slim/tests/CMakeLists.txt
  python/paddle/fluid/contrib/slim/tests/QAT_mkldnn_int8_readme.md
  python/paddle/fluid/contrib/slim/tests/qat_int8_comparison.py
  python/paddle/fluid/contrib/slim/tests/test_quantization_mkldnn_pass.py
  python/paddle/fluid/framework.py
Labels: Intel, int8

#19975 add input type and dtype check for softmax_op
  python/paddle/fluid/layers/nn.py
  python/paddle/fluid/tests/unittests/test_softmax_op.py
Labels: Error Message

#19708 add support of matmul with multiple head even different width and height
  paddle/fluid/operators/math/blas.h
  paddle/fluid/operators/math/blas_impl.h
  paddle/fluid/operators/matmul_op.cc
  python/paddle/fluid/tests/unittests/test_matmul_op_with_head.py
Labels: Intel

#19980 Add LoD empty check for all related sequence ops
  paddle/fluid/operators/sequence_ops/sequence_concat_op.h
  paddle/fluid/operators/sequence_ops/sequence_conv_op.h
  paddle/fluid/operators/sequence_ops/sequence_enumerate_op.h
  paddle/fluid/operators/sequence_ops/sequence_erase_op.h
  paddle/fluid/operators/sequence_ops/sequence_expand_as_op.h
  paddle/fluid/operators/sequence_ops/sequence_expand_op.h
  paddle/fluid/operators/sequence_ops/sequence_pad_op.h
  paddle/fluid/operators/sequence_ops/sequence_pool_op.h
  paddle/fluid/operators/sequence_ops/sequence_reshape_op.h
  paddle/fluid/operators/sequence_ops/sequence_reverse_op.h
  paddle/fluid/operators/sequence_ops/sequence_scatter_op.h
  paddle/fluid/operators/sequence_ops/sequence_slice_op.h
  paddle/fluid/operators/sequence_ops/sequence_softmax_op.h
  paddle/fluid/operators/sequence_ops/sequence_topk_avg_pooling_op.h
Labels: Error Message

#19998 enhance shape error message of mul_op
  paddle/fluid/operators/mul_op.cc
Labels: Error Message

#19974 refine the ifelse op error log info.
  paddle/fluid/operators/merge_lod_tensor_op.cc
  paddle/fluid/operators/split_lod_tensor_op.cc
Labels: Error Message

#19976 Fix test pool2d int8 mkldnn
  paddle/fluid/operators/mkldnn/pool_mkldnn_op.cc
  paddle/fluid/platform/mkldnn_reuse.h
  python/paddle/fluid/tests/unittests/mkldnn/test_pool2d_int8_mkldnn_op.py
  python/paddle/fluid/tests/unittests/test_pool2d_op.py
Labels: Intel, int8

#20012 MKLDNN BatchNorm operator refactor
  paddle/fluid/operators/mkldnn/batch_norm_mkldnn_op.cc
Labels: Code Cleanup, Intel

#20010 Updated AUTHORS from PP Poland
  AUTHORS.md
Labels: Intel

#19895 Paddle error message stack shaping and optimization
  paddle/fluid/framework/op_call_stack.cc
  paddle/fluid/framework/op_registry_test.cc
  paddle/fluid/framework/tensor_test.cc
  paddle/fluid/platform/enforce.h
  paddle/fluid/platform/enforce_test.cc
  python/paddle/fluid/executor.py
Labels: Error Message

#19881 Add fp16 support for pad and split
  paddle/fluid/operators/math/padding.h
  paddle/fluid/operators/pad_op.cu
  paddle/fluid/operators/pad_op.h
  paddle/fluid/operators/split_op.cc
  paddle/fluid/operators/split_op.cu.cc
  python/paddle/fluid/tests/unittests/test_concat_op.py
  python/paddle/fluid/tests/unittests/test_pad_op.py
  python/paddle/fluid/tests/unittests/test_split_op.py
Labels: AMP

#20041 Disable conv requant squash
  paddle/fluid/framework/ir/mkldnn/cpu_quantize_squash_pass.cc
  paddle/fluid/framework/ir/mkldnn/cpu_quantize_squash_pass_tester.cc
Labels: Intel, int8

#19979 Follow comment of Merged QAT PR 18970
  paddle/fluid/framework/ir/mkldnn/cpu_quantize_placement_pass.cc
  python/paddle/fluid/contrib/slim/quantization/quantization_mkldnn_pass.py
Labels: Intel, int8

#20055 Minor GetMKLDNNFormat changes
  paddle/fluid/operators/elementwise/mkldnn/elementwise_add_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/concat_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/fc_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/lrn_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/mul_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/pool_mkldnn_op.cc
Labels: Code Cleanup, Intel
