Repository PaddlePaddle/Paddle, pull requests merged in 2019-11, with the labels that each got.

#21008 Refine gpu allocator err msg
  paddle/fluid/memory/detail/system_allocator.cc
Labels: Error Message

#20334 add ending message
  paddle/scripts/paddle_build.sh
Labels: Intel

#21017 Polish error messages of pool_2d/3d and add Raises in English document
  paddle/fluid/operators/pool_op.cc
  paddle/fluid/operators/pool_op.h
  python/paddle/fluid/layers/nn.py
  python/paddle/fluid/tests/unittests/test_pool2d_op.py
  python/paddle/fluid/tests/unittests/test_pool3d_op.py
Labels: Error Message

#21028 Remove fuse_with_relu argument from batch_norm constructor
  python/paddle/fluid/dygraph/nn.py
  python/paddle/fluid/layers/nn.py
Labels: Intel

#21062 Add support for asymetric padding in MKLDNN pool, conv and conv_transpose
  paddle/fluid/operators/mkldnn/conv_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/conv_transpose_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/pool_mkldnn_op.cc
  paddle/fluid/platform/mkldnn_helper.h
  paddle/fluid/platform/mkldnn_reuse.h
  python/paddle/fluid/tests/unittests/mkldnn/test_conv2d_int8_mkldnn_op.py
  python/paddle/fluid/tests/unittests/mkldnn/test_conv2d_mkldnn_op.py
  python/paddle/fluid/tests/unittests/mkldnn/test_conv2d_transpose_mkldnn_op.py
  python/paddle/fluid/tests/unittests/mkldnn/test_conv3d_mkldnn_op.py
  python/paddle/fluid/tests/unittests/mkldnn/test_pool2d_mkldnn_op.py
Labels: Intel

#21072 [cherry-pick] Add support for asymetric padding in MKLDNN pool, conv and conv_transpose
  paddle/fluid/operators/mkldnn/conv_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/conv_transpose_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/pool_mkldnn_op.cc
  paddle/fluid/platform/mkldnn_helper.h
  paddle/fluid/platform/mkldnn_reuse.h
  python/paddle/fluid/tests/unittests/mkldnn/test_conv2d_int8_mkldnn_op.py
  python/paddle/fluid/tests/unittests/mkldnn/test_conv2d_mkldnn_op.py
  python/paddle/fluid/tests/unittests/mkldnn/test_conv2d_transpose_mkldnn_op.py
  python/paddle/fluid/tests/unittests/mkldnn/test_conv3d_mkldnn_op.py
  python/paddle/fluid/tests/unittests/mkldnn/test_pool2d_mkldnn_op.py
Labels: Intel

#21024 Enrich the type of error and declare the error type interfaces
  cmake/inference_lib.cmake
  paddle/fluid/framework/tensor_test.cc
  paddle/fluid/operators/mul_op.cc
  paddle/fluid/platform/CMakeLists.txt
  paddle/fluid/platform/enforce.h
  paddle/fluid/platform/enforce_test.cc
  paddle/fluid/platform/error_codes.proto
  paddle/fluid/platform/errors.cc
  paddle/fluid/platform/errors.h
  paddle/fluid/platform/errors_test.cc
Labels: Error Message

#21059 Fix dst memory allocation in elementwise_add
  paddle/fluid/operators/elementwise/mkldnn/elementwise_add_mkldnn_op.cc
Labels: Intel

#19424 Add transpose2 INT8 for mkl-dnn
  cmake/operators.cmake
  paddle/fluid/framework/ir/graph_pattern_detector.cc
  paddle/fluid/framework/ir/graph_pattern_detector.h
  paddle/fluid/framework/ir/mkldnn/cpu_quantize_pass.cc
  paddle/fluid/framework/ir/mkldnn/cpu_quantize_pass.h
  paddle/fluid/framework/ir/mkldnn/cpu_quantize_pass_tester.cc
  paddle/fluid/inference/api/mkldnn_quantizer_config.cc
  paddle/fluid/inference/tests/api/analyzer_int8_object_detection_tester.cc
  paddle/fluid/operators/mkldnn/dequantize_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/transpose_mkldnn_op.cc
  paddle/fluid/operators/transpose_op.cc
  paddle/fluid/operators/transpose_op.h
  paddle/fluid/platform/mkldnn_reuse.h
  python/paddle/fluid/tests/unittests/mkldnn/test_transpose_int8_mkldnn_op.py
Labels: Intel, int8

#21030 Split some APIs from nn.py to rnn.py and sequence_lod.py
  python/paddle/fluid/layers/__init__.py
  python/paddle/fluid/layers/nn.py
  python/paddle/fluid/layers/rnn.py
  python/paddle/fluid/layers/sequence_lod.py
Labels: Code Cleanup

#21060 Add Shallow clone to ExternalProjects
  cmake/external/brpc.cmake
  cmake/external/cares.cmake
  cmake/external/cub.cmake
  cmake/external/dlpack.cmake
  cmake/external/eigen.cmake
  cmake/external/gflags.cmake
  cmake/external/glog.cmake
  cmake/external/gtest.cmake
  cmake/external/leveldb.cmake
  cmake/external/libxsmm.cmake
  cmake/external/mkldnn.cmake
  cmake/external/ngraph.cmake
  cmake/external/openblas.cmake
  cmake/external/protobuf.cmake
  cmake/external/pybind11.cmake
  cmake/external/rocprim.cmake
  cmake/external/threadpool.cmake
  cmake/external/warpctc.cmake
  cmake/external/xbyak.cmake
  cmake/external/xxhash.cmake
  cmake/external/zlib.cmake
  cmake/third_party.cmake
Labels: Intel, enhancement

#20961 Add the check of lod_level between compile-time and runtime.
  paddle/fluid/framework/op_desc.cc
  paddle/fluid/framework/operator.cc
  paddle/fluid/framework/operator_test.cc
  paddle/fluid/framework/shape_inference.h
  paddle/fluid/operators/array_to_lod_tensor_op.cc
  paddle/fluid/operators/lod_tensor_to_array_op.cc
  paddle/fluid/operators/match_matrix_tensor_op.cc
  paddle/fluid/operators/sequence_ops/sequence_pad_op.cc
  paddle/fluid/operators/sequence_ops/sequence_pool_op.cc
  paddle/fluid/operators/sequence_ops/sequence_unpad_op.cc
  python/paddle/fluid/tests/unittests/op_test.py
  python/paddle/fluid/tests/unittests/test_match_matrix_tensor_op.py
  python/paddle/fluid/tests/unittests/test_sequence_pad_op.py
  python/paddle/fluid/tests/unittests/test_sequence_unpad_op.py
Labels: OpPorting

#21093 Further simplify the C++ error info stack
  paddle/fluid/platform/place.h
Labels: Error Message

#21140 Decorate badalloc exception and add examples for error msg specification - ResourceExhausted
  paddle/fluid/memory/allocation/cuda_allocator.cc
  paddle/fluid/memory/detail/system_allocator.cc
  paddle/fluid/platform/enforce.h
Labels: Error Message

#21153 Cherry pick 21059 Fix dst memory allocation in elementwise_add
  paddle/fluid/operators/elementwise/mkldnn/elementwise_add_mkldnn_op.cc
Labels: Intel

#21132 Add examples for error message writing specification - InvalidArgument
  paddle/fluid/framework/async_executor.cc
  paddle/fluid/framework/data_feed.cc
  paddle/fluid/framework/data_layout_transform.cc
  paddle/fluid/framework/details/eager_deletion_op_handle.cc
  paddle/fluid/framework/op_info.h
  paddle/fluid/framework/operator.cc
  paddle/fluid/framework/tensor_impl.h
  paddle/fluid/operators/reshape_op.cc
  paddle/fluid/operators/sequence_ops/sequence_pool_op.h
Labels: Error Message

#21137 Add examples for error message writing specification - PreconditionNotMet, Unimplemented, Unavailable
  paddle/fluid/framework/data_feed.cc
  paddle/fluid/framework/data_feed_test.cc
  paddle/fluid/framework/details/build_strategy.cc
  paddle/fluid/framework/details/fast_threaded_ssa_graph_executor.cc
  paddle/fluid/framework/executor_thread_worker.cc
  paddle/fluid/framework/ir/fusion_group/operation.h
  paddle/fluid/framework/ir/multi_devices_graph_pass/fuse_all_reduce_op_pass.cc
  paddle/fluid/inference/utils/benchmark.cc
  paddle/fluid/operators/mul_op.cc
Labels: Error Message

#21074 QAT int8 accuracy little improvement
  python/paddle/fluid/contrib/slim/quantization/quantization_mkldnn_pass.py
Labels: Intel

#21142 Refactor cuda enforce and add specify default error type - External
  paddle/fluid/memory/allocation/cuda_device_context_allocator.h
  paddle/fluid/platform/enforce.h
Labels: Error Message

#21161 add input type and dtype check template, and update some APIs check
  python/paddle/fluid/data_feeder.py
  python/paddle/fluid/input.py
  python/paddle/fluid/layers/layer_function_generator.py
  python/paddle/fluid/layers/loss.py
  python/paddle/fluid/layers/metric_op.py
  python/paddle/fluid/layers/nn.py
  python/paddle/fluid/layers/tensor.py
  python/paddle/fluid/tests/unittests/test_accuracy_op.py
  python/paddle/fluid/tests/unittests/test_zeros_op.py
Labels: Error Message

#21144 Add relative error measure when (value > 1)
  paddle/fluid/inference/tests/api/tester_helper.h
Labels: Intel

#21134 Add examples for error message writing specification - NotFound, OutOfRange, AlreadyExists, PermissionDenied
  paddle/fluid/framework/array.h
  paddle/fluid/framework/async_executor.cc
  paddle/fluid/framework/attribute.h
  paddle/fluid/framework/ir/fuse_optimizer_ops_pass/fuse_optimizer_op_pass.cc
  paddle/fluid/framework/ir/graph.h
  paddle/fluid/framework/ir/graph_pattern_detector.cc
  paddle/fluid/framework/ir/pass.h
  paddle/fluid/framework/ir/repeated_fc_relu_fuse_pass.cc
  paddle/fluid/framework/ir/seqpool_concat_fuse_pass.cc
  paddle/fluid/framework/naive_executor.cc
  paddle/fluid/framework/op_info.h
  paddle/fluid/framework/operator.cc
  paddle/fluid/operators/mul_op.cc
Labels: Error Message

#21178 Add PADDLE ENFORCE count script
  tools/count_invalid_enforce.sh
Labels: Error Message

#21180 [cherry-pick] fix error message in expand API, and fix two error unit-tests
  python/paddle/fluid/layers/nn.py
  python/paddle/fluid/tests/unittests/test_accuracy_op.py
  python/paddle/fluid/tests/unittests/test_zeros_op.py
Labels: Error Message

#21151 Fix jit tls issue
  paddle/fluid/operators/jit/helper.cc
  paddle/fluid/operators/jit/helper.h
  paddle/fluid/operators/jit/kernel_pool.cc
  paddle/fluid/operators/jit/kernel_pool.h
Labels: Intel

#21107 Add CI check for error message writing specification
  tools/check_api_approvals.sh
Labels: Error Message

#21002 modified error message and API doc for channel_last supported Op
  paddle/fluid/operators/conv_op.cc
  paddle/fluid/operators/conv_transpose_op.cc
  paddle/fluid/operators/group_norm_op.cc
  python/paddle/fluid/layers/nn.py
Labels: Error Message

#21204 Fix GELU grad error
  paddle/fluid/operators/activation_op.h
Labels: Intel

#21250 add input type and input data type check for Print_op test=develop
  python/paddle/fluid/layers/control_flow.py
  python/paddle/fluid/tests/unittests/test_print_op.py
Labels: Error Message

#21292 Avoid the string as the key of map to improve the jit performance
  paddle/fluid/operators/jit/helper.cc
  paddle/fluid/operators/jit/helper.h
  paddle/fluid/operators/jit/kernel_pool.cc
  paddle/fluid/operators/jit/kernel_pool.h
Labels: Intel

#21284 Fix the crash issue when scale or bias was null-pointer.
  paddle/fluid/operators/layer_norm_op.h
Labels: Intel

#21321 [Cherry-pick] Fix GELU grad error
  paddle/fluid/operators/activation_op.h
Labels: Intel

#21206 use prefetch to load next mem into cache
  paddle/fluid/operators/pyramid_hash_op.cc
Labels: Intel

#21061 Refactor MKL-DNN ElementwiseMul
  paddle/fluid/operators/elementwise/CMakeLists.txt
  paddle/fluid/operators/elementwise/elementwise_mul_op.cc
  paddle/fluid/operators/elementwise/elementwise_mul_op.h
  paddle/fluid/operators/elementwise/elementwise_op.h
  paddle/fluid/operators/elementwise/mkldnn/elementwise_mul_mkldnn_op.cc
  paddle/fluid/operators/elementwise/test_elementwise_mul_op_dim.cc
  python/paddle/fluid/tests/unittests/mkldnn/test_elementwise_mul_mkldnn_op.py
Labels: Intel

#21207 [MKL-DNN] Error throwing for NHWC layout for MKL-DNN ops
  paddle/fluid/operators/conv_op.cc
  paddle/fluid/operators/conv_transpose_op.cc
  paddle/fluid/operators/lrn_op.cc
  paddle/fluid/operators/pool_op.cc
  python/paddle/fluid/tests/unittests/mkldnn/test_lrn_mkldnn_op.py
  python/paddle/fluid/tests/unittests/mkldnn/test_pool2d_mkldnn_op.py
Labels: Error Message, Intel

#21361 [cherry-pick] Refactor mkldnn eletwise_mul and error message for NHWC in mkldnn
  paddle/fluid/operators/conv_op.cc
  paddle/fluid/operators/conv_transpose_op.cc
  paddle/fluid/operators/elementwise/CMakeLists.txt
  paddle/fluid/operators/elementwise/elementwise_mul_op.cc
  paddle/fluid/operators/elementwise/elementwise_mul_op.h
  paddle/fluid/operators/elementwise/elementwise_op.h
  paddle/fluid/operators/elementwise/mkldnn/elementwise_mul_mkldnn_op.cc
  paddle/fluid/operators/elementwise/test_elementwise_mul_op_dim.cc
  paddle/fluid/operators/lrn_op.cc
  paddle/fluid/operators/pool_op.cc
  python/paddle/fluid/tests/unittests/mkldnn/test_elementwise_mul_mkldnn_op.py
  python/paddle/fluid/tests/unittests/mkldnn/test_lrn_mkldnn_op.py
  python/paddle/fluid/tests/unittests/mkldnn/test_pool2d_mkldnn_op.py
Labels: Intel

#17641 INT8 Fully-connected
  cmake/operators.cmake
  paddle/fluid/framework/ir/graph_pattern_detector.cc
  paddle/fluid/framework/ir/graph_pattern_detector.h
  paddle/fluid/framework/ir/mkldnn/cpu_quantize_pass.cc
  paddle/fluid/framework/ir/mkldnn/cpu_quantize_pass.h
  paddle/fluid/framework/ir/mkldnn/cpu_quantize_pass_tester.cc
  paddle/fluid/framework/ir/mkldnn/fc_mkldnn_pass.cc
  paddle/fluid/inference/api/analysis_predictor_tester.cc
  paddle/fluid/inference/api/mkldnn_quantizer.cc
  paddle/fluid/inference/api/mkldnn_quantizer.h
  paddle/fluid/inference/api/mkldnn_quantizer_config.cc
  paddle/fluid/inference/api/paddle_mkldnn_quantizer_config.h
  paddle/fluid/operators/fc_op.cc
  paddle/fluid/operators/fc_op.h
  paddle/fluid/operators/mkldnn/dequantize_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/fc_mkldnn_op.cc
  python/paddle/fluid/tests/unittests/mkldnn/test_fc_mkldnn_op.py
Labels: Intel, int8

#21426 Add template version of UpdatePadding
  paddle/fluid/operators/conv_op.h
  paddle/fluid/operators/pool_op.h
Labels: Intel

#21375 [MKL-DNN] LRN and Pool2d (FWD) NHWC support
  paddle/fluid/framework/data_layout_transform.cc
  paddle/fluid/framework/data_layout_transform.h
  paddle/fluid/framework/data_transform.cc
  paddle/fluid/framework/executor.cc
  paddle/fluid/framework/operator.h
  paddle/fluid/operators/controlflow/fetch_op.cc
  paddle/fluid/operators/lrn_op.cc
  paddle/fluid/operators/mkldnn/dequantize_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/lrn_mkldnn_op.cc
  paddle/fluid/operators/pool_op.cc
  paddle/fluid/operators/pool_op.h
  paddle/fluid/platform/device_context.cc
  paddle/fluid/platform/device_context.h
  paddle/fluid/platform/mkldnn_reuse.h
  python/paddle/fluid/tests/unittests/mkldnn/test_lrn_mkldnn_op.py
  python/paddle/fluid/tests/unittests/mkldnn/test_pool2d_mkldnn_op.py
Labels: Intel

#21169 add unused input vars check for OpWithKernel, test=develop
  paddle/fluid/framework/CMakeLists.txt
  paddle/fluid/framework/operator.cc
  paddle/fluid/framework/operator.h
  paddle/fluid/framework/operator_test.cc
  paddle/fluid/framework/unused_var_check.cc
  paddle/fluid/framework/unused_var_check.h
  paddle/fluid/operators/batch_norm_op.cc
  paddle/fluid/operators/batch_norm_op.h
  paddle/fluid/operators/flatten_op.cc
  paddle/fluid/operators/instance_norm_op.h
  paddle/fluid/operators/lrn_op.cc
  paddle/fluid/operators/prelu_op.cc
  paddle/fluid/operators/prelu_op.cu
  paddle/fluid/operators/squeeze_op.cc
  paddle/scripts/paddle_build.sh
  python/paddle/fluid/__init__.py
  tools/check_api_approvals.sh
Labels: OpPorting

#21444 [cherry-pick]Fix the crash issue when scale or bias was null-pointer. (#21284)
  paddle/fluid/operators/layer_norm_op.h
Labels: Intel
