Repository PaddlePaddle/Paddle, pull requests merged in 2019-10, with the labels that each got.

#20075 Fill constant error message fix
  paddle/fluid/operators/fill_constant_op.cc
  python/paddle/fluid/data_feeder.py
  python/paddle/fluid/layers/tensor.py
  python/paddle/fluid/tests/unittests/test_fill_constant_op.py
Labels: Error Message

#20100 add input type and dtype check for squeeze
  paddle/fluid/operators/squeeze_op.cc
  paddle/fluid/operators/squeeze_op.h
  python/paddle/fluid/layers/nn.py
  python/paddle/fluid/tests/unittests/test_squeeze_op.py
Labels: Error Message

#20204 Refine Error Message for New Data API
  python/paddle/fluid/executor.py
  python/paddle/fluid/tests/unittests/test_feed_data_check_shape_type.py
Labels: Error Message

#20106 add input type and dtype check for elu_op
  python/paddle/fluid/layers/nn.py
  python/paddle/fluid/tests/unittests/test_activation_op.py
Labels: Error Message

#20273 fix softmax input error check on float16
  python/paddle/fluid/layers/nn.py
  python/paddle/fluid/tests/unittests/test_softmax_op.py
Labels: Error Message

#20238 enhance input check for roi_align, test=develop
  paddle/fluid/operators/roi_align_op.cu
  paddle/fluid/operators/roi_align_op.h
Labels: Error Message

#20172 enhance shape error message of fc API
  paddle/fluid/operators/sum_op.cc
  python/paddle/fluid/layers/nn.py
  python/paddle/fluid/tests/unittests/test_fc_op.py
Labels: Error Message

#20099 add input type, dtype and shape check for reshape op.
  paddle/fluid/operators/reshape_op.cc
  python/paddle/fluid/layers/nn.py
  python/paddle/fluid/tests/unittests/test_reshape_op.py
Labels: Error Message

#20349 [cherry-pick] Enhance shape error message of fc API (#20172)
  paddle/fluid/operators/sum_op.cc
  python/paddle/fluid/layers/nn.py
  python/paddle/fluid/tests/unittests/test_fc_op.py
Labels: Error Message

#20254 python api: add input type check for (sqrt, cos, round etc)
  python/paddle/fluid/layers/layer_function_generator.py
  python/paddle/fluid/tests/unittests/test_activation_op.py
Labels: Error Message

#20467 Fix fp16 in input.dtype check in layers.fc
  python/paddle/fluid/layers/nn.py
  python/paddle/fluid/tests/unittests/test_fc_op.py
Labels: Error Message

#20029 Update QAT MKL-DNN readme doc
  python/paddle/fluid/contrib/slim/tests/QAT_mkldnn_int8_readme.md
Labels: Intel, int8

#20520 [Release 1.6][Cherry-pick] Update QAT INT8 Readme
  python/paddle/fluid/contrib/slim/tests/QAT_mkldnn_int8_readme.md
Labels: Intel, design_doc, int8

#20500 [cherry-pick] Fix input.dtype fp16 of fc op
  python/paddle/fluid/layers/nn.py
  python/paddle/fluid/tests/unittests/test_fc_op.py
Labels: Error Message

#20101 add input type and dtype check, enhance shape error message for concat_op
  paddle/fluid/operators/concat_op.cc
  python/paddle/fluid/layers/tensor.py
  python/paddle/fluid/tests/unittests/test_concat_op.py
Labels: Error Message

#20508 Fix the error message of assign op
  python/paddle/fluid/layers/tensor.py
  python/paddle/fluid/tests/unittests/test_assign_op.py
Labels: Error Message

#20246 enhance embedding error message test=develop
  paddle/fluid/operators/lookup_table_op.cc
  paddle/fluid/operators/lookup_table_op.cu
  paddle/fluid/operators/lookup_table_op.h
  paddle/fluid/operators/lookup_table_v2_op.cc
  paddle/fluid/operators/lookup_table_v2_op.cu
  paddle/fluid/operators/lookup_table_v2_op.h
  python/paddle/fluid/input.py
  python/paddle/fluid/layers/nn.py
  python/paddle/fluid/tests/unittests/test_downpoursgd.py
  python/paddle/fluid/tests/unittests/test_lookup_table_op.py
  python/paddle/fluid/tests/unittests/test_lookup_table_v2_op.py
Labels: Error Message

#20519 [cherry-pick] Enhance embedding error message
  paddle/fluid/operators/lookup_table_op.cc
  paddle/fluid/operators/lookup_table_op.cu
  paddle/fluid/operators/lookup_table_op.h
  paddle/fluid/operators/lookup_table_v2_op.cc
  paddle/fluid/operators/lookup_table_v2_op.cu
  paddle/fluid/operators/lookup_table_v2_op.h
  python/paddle/fluid/input.py
  python/paddle/fluid/layers/nn.py
  python/paddle/fluid/tests/unittests/test_downpoursgd.py
  python/paddle/fluid/tests/unittests/test_lookup_table_op.py
  python/paddle/fluid/tests/unittests/test_lookup_table_v2_op.py
Labels: Error Message

#20417 [Cherry-pick][Release 1.6] Improve QAT accuracy
  python/paddle/fluid/contrib/slim/quantization/quantization_mkldnn_pass.py
Labels: Intel, int8

#20161 Add ConvTranspose + BatchNorm fuse pass
  paddle/fluid/framework/ir/CMakeLists.txt
  paddle/fluid/framework/ir/conv_bn_fuse_pass.cc
  paddle/fluid/framework/ir/conv_bn_fuse_pass.h
  paddle/fluid/framework/ir/conv_bn_fuse_pass_tester.cc
  paddle/fluid/framework/ir/graph_pattern_detector.cc
  paddle/fluid/framework/ir/graph_pattern_detector.h
  paddle/fluid/framework/ir/pass_tester_helper.h
  paddle/fluid/inference/api/paddle_pass_builder.cc
Labels: Intel, inference

#20551 [cherry-pick]fix reshape input(x) error check on float16.
  python/paddle/fluid/layers/nn.py
  python/paddle/fluid/tests/unittests/test_reshape_op.py
Labels: Error Message

#20476 Fix the error message of zeros op
  python/paddle/fluid/layers/tensor.py
  python/paddle/fluid/tests/unittests/test_zeros_op.py
Labels: Error Message

#20593 [cherry-pick] Fix the error message of zeros op (#20476)
  python/paddle/fluid/layers/tensor.py
  python/paddle/fluid/tests/unittests/test_zeros_op.py
Labels: Error Message

#20475 Modify the helper information in full_pascalvoc_test_preprocess.py
  paddle/fluid/inference/tests/api/full_pascalvoc_test_preprocess.py
Labels: Intel, int8

#20070 add input type and dtype check for cast_op
  python/paddle/fluid/data_feeder.py
  python/paddle/fluid/layers/tensor.py
  python/paddle/fluid/tests/unittests/test_cast_op.py
  python/paddle/fluid/tests/unittests/test_fill_constant_op.py
Labels: Error Message

#19771 Add fused_embedding_seq layer into fluid.contrib
  paddle/fluid/API.spec
  python/paddle/fluid/contrib/layers/nn.py
  python/paddle/fluid/tests/unittests/test_fused_emb_seq_pool_op.py
Labels: Intel

#20571 Add interface so user can get scaled loss when they use customized loss.
  paddle/fluid/API.spec
  python/paddle/fluid/contrib/mixed_precision/decorator.py
  python/paddle/fluid/contrib/tests/test_image_classification_fp16.py
Labels: AMP

#19970 refine error message of input TypeError in framework.py
  python/paddle/fluid/framework.py
  python/paddle/fluid/tests/unittests/test_compare_op.py
Labels: Error Message

#20636 Support fp16 in GPU impl of fused_elemwise_activation_op.
  paddle/fluid/operators/fused/fused_elemwise_activation_op.cu
  paddle/fluid/operators/math/functors.h
  python/paddle/fluid/tests/unittests/test_fused_elemwise_activation_op.py
Labels: AMP

#20044 Add IndicateVarDataType interface to block tensor is not initialized problem in OP GetExceptedKernelType
  paddle/fluid/framework/operator.cc
  paddle/fluid/framework/operator.h
  paddle/fluid/framework/operator_test.cc
  paddle/fluid/framework/variable.h
  paddle/fluid/operators/mul_op.cc
  paddle/fluid/operators/save_op.cc
Labels: Error Message

#19356 Add document for int8 object detection quantization
  paddle/fluid/inference/tests/api/int8_mkldnn_quantization.md
Labels: Intel, int8

#20669 [Cherry-Pick][1.6] INT8 Object Detection Quantization doc
  paddle/fluid/inference/tests/api/int8_mkldnn_quantization.md
Labels: Intel, int8

#20685 remove deprecated contrib/float16 directory
  paddle/contrib/float16/.gitignore
  paddle/contrib/float16/README.md
  paddle/contrib/float16/float16_benchmark.md
  paddle/contrib/float16/float16_inference_demo.py
  paddle/contrib/float16/float16_transpiler.py
  paddle/contrib/float16/run_float16_demo.sh
Labels: Code Cleanup

#20241 [MKL-DNN] Added mkl-dnn cache clearing when creating Executor instance
  paddle/fluid/framework/executor.cc
  paddle/fluid/framework/executor.h
  paddle/fluid/operators/elementwise/mkldnn/elementwise_add_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/batch_norm_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/concat_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/conv_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/conv_transpose_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/dequantize_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/fc_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/mul_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/softmax_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/transpose_mkldnn_op.cc
  paddle/fluid/platform/mkldnn_reuse.h
Labels: Code Cleanup, Intel

#20640 Revert "Refactor conv computeINT8"
  paddle/fluid/operators/mkldnn/conv_mkldnn_op.cc
  paddle/fluid/platform/mkldnn_reuse.h
Labels: Intel

#20693 [Release 1.6][Cherry-pick] Clear MKL-DNN Cache
  paddle/fluid/framework/executor.cc
  paddle/fluid/framework/executor.h
  paddle/fluid/operators/elementwise/mkldnn/elementwise_add_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/batch_norm_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/concat_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/conv_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/conv_transpose_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/dequantize_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/fc_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/mul_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/softmax_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/transpose_mkldnn_op.cc
  paddle/fluid/platform/mkldnn_reuse.h
Labels: Intel

#20753 Minor MKL-DNN conv int8 performance fixes
  paddle/fluid/operators/mkldnn/conv_mkldnn_op.cc
  paddle/fluid/platform/mkldnn_helper.h
Labels: Intel, int8

#20768 [Cherry-pick] Minor MKL-DNN conv int8 performance fixes
  paddle/fluid/operators/mkldnn/conv_mkldnn_op.cc
  paddle/fluid/platform/mkldnn_helper.h
Labels: Intel, int8

#20804 Refine error message of system_allocator.cc
  paddle/fluid/memory/detail/system_allocator.cc
Labels: Error Message

#20826 Make formatted ENFORCE stack adapt to more situations
  paddle/fluid/framework/op_call_stack.cc
  paddle/fluid/platform/enforce.h
Labels: Error Message

#20906 Add parameter init check add run_startup_progrom error message for fc(mul)
  paddle/fluid/operators/mul_op.cc
Labels: Error Message

#20895 Optimize the kernel implementation of layernorm with openmp
  paddle/fluid/operators/jit/more/intrinsic/layer_norm.cc
Labels: Intel
