Repository PaddlePaddle/Paddle, pull requests merged in 2020-12, with the labels that each got.

#29260 change import math.h to cmath
  paddle/fluid/memory/allocation/best_fit_allocator.cc
Labels: Intel

#29443 added internal and external reorders to profiler
  paddle/fluid/framework/data_layout_transform.cc
  paddle/fluid/operators/mkldnn/conv_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/fc_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/mul_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/quantize_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/requantize_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/sum_mkldnn_op.cc
  paddle/fluid/platform/mkldnn_helper.h
  paddle/fluid/platform/mkldnn_reuse.h
  paddle/fluid/platform/profiler_helper.h
Labels: Intel

#29493 [oneDNN] Fix flags use test for #29080, assert condition more general
  paddle/scripts/paddle_build.bat
  python/paddle/fluid/tests/unittests/mkldnn/test_flags_mkldnn_ops_on_off.py
  python/paddle/fluid/tests/unittests/mkldnn/test_flags_use_mkldnn.py
Labels: Intel

#29502 Fix bf16 activations test for softmax and gelu
  paddle/scripts/paddle_build.bat
  python/paddle/fluid/tests/unittests/mkldnn/test_activation_mkldnn_op.py
Labels: BF16, Intel

#29501 [oneDNN] Added Unit Test for Multiple instances prediction
  paddle/fluid/inference/tests/api/CMakeLists.txt
  paddle/fluid/inference/tests/api/analyzer_mmp_tester.cc
Labels: Intel

#29272 [oneDNN] Making ThreadID info in caching key optional
  paddle/fluid/framework/data_layout_transform.cc
  paddle/fluid/operators/fused/mkldnn/fusion_gru_mkldnn_op.cc
  paddle/fluid/operators/fused/mkldnn/multi_gru_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/batch_norm_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/concat_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/conv_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/conv_transpose_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/dequantize_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/fc_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/layer_norm_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/matmul_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/mul_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/pool_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/quantize_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/requantize_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/softmax_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/sum_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/transpose_mkldnn_op.cc
  paddle/fluid/platform/device_context.h
  paddle/fluid/platform/mkldnn_helper.h
  paddle/fluid/platform/mkldnn_reuse.h
Labels: Intel

#29378 Added verbose oneDNN lib version
  paddle/fluid/operators/mkldnn/concat_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/fc_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/matmul_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/mul_mkldnn_op.cc
  paddle/fluid/platform/device_context.cc
  paddle/fluid/platform/device_context.h
  paddle/fluid/platform/mkldnn_reuse.h
Labels: Intel

#29670 [oneDNN] Added missing format of oneDNN
  paddle/fluid/platform/mkldnn_helper.h
Labels: Intel

#29671 [oneDNN] Port to release/2.0 of Added verbose oneDNN lib version
  paddle/fluid/operators/mkldnn/concat_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/fc_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/matmul_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/mul_mkldnn_op.cc
  paddle/fluid/platform/device_context.cc
  paddle/fluid/platform/device_context.h
  paddle/fluid/platform/mkldnn_reuse.h
Labels: Intel

#28420 upgrade oneDNN with GRU INT8 optimizations
  cmake/external/mkldnn.cmake
  python/paddle/fluid/tests/unittests/mkldnn/test_flags_mkldnn_ops_on_off.py
Labels: Intel, int8

#29747 [oneDNN] Reimplemented elementwise_add grad
  paddle/fluid/operators/elementwise/mkldnn/elementwise_add_mkldnn_op.cc
  paddle/fluid/platform/mkldnn_reuse.h
Labels: Intel, dygraph

#29598 [oneDNN] Port to release/2.0 of Making ThreadID info in caching key optional (#29272)
  paddle/fluid/framework/data_layout_transform.cc
  paddle/fluid/operators/fused/mkldnn/fusion_gru_mkldnn_op.cc
  paddle/fluid/operators/fused/mkldnn/multi_gru_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/batch_norm_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/concat_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/conv_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/conv_transpose_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/dequantize_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/fc_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/layer_norm_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/matmul_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/mul_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/pool_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/quantize_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/requantize_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/softmax_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/sum_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/transpose_mkldnn_op.cc
  paddle/fluid/platform/device_context.h
  paddle/fluid/platform/mkldnn_helper.h
  paddle/fluid/platform/mkldnn_reuse.h
Labels: Intel

#29771 [oneDNN] Tensor copy fix to oneDNN tensors
  paddle/fluid/framework/tensor_util.cc
Labels: Intel, dygraph

#29606 [oneDNN] Unit test for checking oneDNN caching
  paddle/fluid/operators/CMakeLists.txt
  paddle/fluid/operators/mkldnn/caching_tests.cmake
  paddle/fluid/operators/mkldnn/test_mkldnn_caching.cc
  paddle/fluid/platform/device_context.cc
  paddle/fluid/platform/device_context.h
Labels: Intel

#29528 fix conv2d_int8 windows UT
  python/paddle/fluid/tests/unittests/mkldnn/test_conv2d_int8_mkldnn_op.py
  tools/windows/run_unittests.sh
Labels: Intel

#29772 Added fc + activation fuse pass (currently only gelu, sigmoid and tanh are supported)
  paddle/fluid/framework/ir/CMakeLists.txt
  paddle/fluid/framework/ir/graph_pattern_detector.cc
  paddle/fluid/framework/ir/graph_pattern_detector.h
  paddle/fluid/framework/ir/mkldnn/fc_act_mkldnn_fuse_pass.cc
  paddle/fluid/framework/ir/mkldnn/fc_act_mkldnn_fuse_pass.h
  paddle/fluid/framework/ir/mkldnn/fc_act_mkldnn_fuse_pass_tester.cc
  paddle/fluid/inference/api/paddle_pass_builder.cc
  paddle/fluid/inference/tests/api/analyzer_dam_tester.cc
  paddle/fluid/inference/tests/api/analyzer_image_classification_tester.cc
  paddle/fluid/inference/tests/api/analyzer_seq_pool1_tester_helper.h
  paddle/fluid/inference/tests/api/analyzer_transformer_compare_tester.cc
  paddle/fluid/inference/tests/api/analyzer_transformer_profile_tester.cc
  paddle/fluid/inference/tests/api/analyzer_vis_tester.cc
  paddle/fluid/operators/mkldnn/fc_mkldnn_op.cc
  python/paddle/fluid/tests/unittests/ir/inference/test_mkldnn_fc_act_fuse_pass.py
Labels: Intel
