Repository PaddlePaddle/Paddle, pull requests merged in 2020-03, with the labels that each got.

#22760 Add @skip_check_grad_ci to UT conv_mkldnn and int8_mul_mkldnn
  python/paddle/fluid/tests/unittests/mkldnn/test_conv2d_mkldnn_op.py
  python/paddle/fluid/tests/unittests/mkldnn/test_mul_int8_mkldnn_op.py
  python/paddle/fluid/tests/unittests/test_conv2d_op.py
Labels: Intel

#22773 upgrade fp32 to fp64, enlarge input shape for hsigmoid unittest
  python/paddle/fluid/tests/unittests/test_hsigmoid_op.py
  python/paddle/fluid/tests/unittests/white_list/check_shape_white_list.py
  python/paddle/fluid/tests/unittests/white_list/op_accuracy_white_list.py
Labels: OpPorting

#22788 Fix the big shape and precision op test, remove those from the white list
  python/paddle/fluid/tests/unittests/test_elementwise_div_op.py
  python/paddle/fluid/tests/unittests/test_elementwise_mul_op.py
  python/paddle/fluid/tests/unittests/test_mul_op.py
  python/paddle/fluid/tests/unittests/white_list/check_shape_white_list.py
  python/paddle/fluid/tests/unittests/white_list/op_accuracy_white_list.py
Labels: OpPorting

#22822 fixed save qat2 model resnet50 and ernie
  python/paddle/fluid/contrib/slim/tests/CMakeLists.txt
Labels: Intel

#22858 Added an option to use external FP32 model in QAT comparison test
  python/paddle/fluid/contrib/slim/tests/qat_int8_nlp_comparison.py
Labels: Intel, int8

#22692 fix concat_mkldnn op. test=develop
  paddle/fluid/operators/mkldnn/concat_mkldnn_op.cc
Labels: Intel

#22875 [cherry-pick]Changes QAT MKL-DNN documents about Ernie
  python/paddle/fluid/contrib/slim/tests/QAT_mkldnn_int8_readme.md
Labels: Intel

#22873 [Cherry-pick] Added an option to use external FP32 model in QAT comparison test
  python/paddle/fluid/contrib/slim/tests/qat_int8_nlp_comparison.py
Labels: Intel

#22840 Change QAT documents
  python/paddle/fluid/contrib/slim/tests/QAT_mkldnn_int8_readme.md
Labels: Intel

#22695 Change ShareDataWith() to TensorCopy() in conv_mkldnn
  paddle/fluid/framework/tensor_util.cc
  paddle/fluid/operators/mkldnn/conv_mkldnn_op.cc
Labels: Intel

#22985 Revert "Change ShareDataWith() to TensorCopy() in conv_mkldnn (#22695)"
  paddle/fluid/framework/tensor_util.cc
  paddle/fluid/operators/mkldnn/conv_mkldnn_op.cc
Labels: Intel

#23041 added mkldnn swish activation
  paddle/fluid/framework/ir/mkldnn/conv_activation_mkldnn_fuse_pass.cc
  paddle/fluid/framework/ir/mkldnn/conv_activation_mkldnn_fuse_pass.h
  paddle/fluid/framework/ir/mkldnn/conv_activation_mkldnn_fuse_pass_tester.cc
  paddle/fluid/inference/api/paddle_pass_builder.cc
  paddle/fluid/operators/activation_op.cc
  paddle/fluid/operators/mkldnn/activation_mkldnn_op.cc
  paddle/fluid/platform/mkldnn_reuse.h
  python/paddle/fluid/tests/unittests/mkldnn/test_activation_mkldnn_op.py
Labels: Intel

#23120 Improve SGD jit code to work with large data
  paddle/fluid/operators/jit/gen/sgd.cc
  paddle/fluid/operators/jit/gen/sgd.h
Labels: Intel

#23195 Add UT for SGD operator with large inputs
  python/paddle/fluid/tests/unittests/test_sgd_op.py
Labels: Intel

#23119 add check for scales and a message
  paddle/fluid/framework/ir/mkldnn/cpu_quantize_pass.cc
  paddle/fluid/framework/ir/mkldnn/cpu_quantize_pass.h
  paddle/fluid/framework/ir/mkldnn/cpu_quantize_pass_tester.cc
  python/paddle/fluid/contrib/slim/quantization/quantization_mkldnn_pass.py
Labels: Intel

#23284 separated QAT1 and QAT2
  python/paddle/fluid/contrib/slim/quantization/__init__.py
  python/paddle/fluid/contrib/slim/quantization/qat2_int8_mkldnn_pass.py
  python/paddle/fluid/contrib/slim/quantization/qat_int8_mkldnn_pass.py
Labels: Intel

#23197 [DNNL] Softmax mkldnn op inplace support
  paddle/fluid/operators/CMakeLists.txt
  paddle/fluid/operators/mkldnn/inplace_op_tests.cmake
  paddle/fluid/operators/mkldnn/softmax_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/test_mkldnn_op_inplace.cc
Labels: Intel
