Repository PaddlePaddle/Paddle, pull requests merged in 2020-09, with the labels that each got.

#26891 [oneDNN] Cosmetic fixes to align with PADDLE_ENFORCE guidelines
  paddle/fluid/operators/mkldnn/activation_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/batch_norm_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/concat_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/conv_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/conv_transpose_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/pool_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/softmax_mkldnn_op.cc
Labels: Intel

#26882 Restore "Add mkldnn bfloat16 option to C-API "
  go/paddle/config.go
  paddle/fluid/inference/api/analysis_config.cc
  paddle/fluid/inference/api/analysis_predictor_tester.cc
  paddle/fluid/inference/api/paddle_analysis_config.h
  paddle/fluid/inference/api/paddle_pass_builder.cc
  paddle/fluid/inference/api/paddle_pass_builder.h
  paddle/fluid/inference/capi/paddle_c_api.h
  paddle/fluid/inference/capi/pd_config.cc
  paddle/fluid/inference/tests/api/analyzer_capi_tester.cc
  paddle/fluid/pybind/inference_api.cc
Labels: BF16, Intel

#25402 Add bfloat16 data type
  paddle/fluid/framework/data_layout_transform.cc
  paddle/fluid/framework/data_layout_transform.h
  paddle/fluid/framework/data_layout_transform_test.cc
  paddle/fluid/framework/data_type.cc
  paddle/fluid/framework/data_type.h
  paddle/fluid/framework/data_type_test.cc
  paddle/fluid/framework/data_type_transform.cc
  paddle/fluid/framework/data_type_transform_test.cc
  paddle/fluid/framework/details/nan_inf_utils_detail.cc
  paddle/fluid/framework/dlpack_tensor.cc
  paddle/fluid/inference/analysis/passes/memory_optimize_pass.cc
  paddle/fluid/inference/lite/test_engine.cc
  paddle/fluid/operators/math/concat_and_split.h
  paddle/fluid/operators/math/math_function.cc
  paddle/fluid/platform/CMakeLists.txt
  paddle/fluid/platform/bfloat16.h
  paddle/fluid/platform/bfloat16_test.cc
  paddle/fluid/platform/mkldnn_helper.h
  paddle/fluid/pybind/tensor_py.h
Labels: BF16, Intel

#26938 Test for passing global env FLAGS_use_mkldnn
  python/paddle/fluid/tests/unittests/mkldnn/check_flags_use_mkldnn.py
  python/paddle/fluid/tests/unittests/mkldnn/test_flags_use_mkldnn.py
  python/paddle/fluid/tests/unittests/test_imperative_basic.py
Labels: Intel

#27006 [oneDNN] Fix to conv2d grad with groups
  paddle/fluid/operators/mkldnn/conv_mkldnn_op.cc
Labels: Intel, dygraph

#26776 fix dimensions error for mobilenetv1_KL_quant
  python/paddle/fluid/contrib/slim/quantization/quant2_int8_mkldnn_pass.py
  python/paddle/fluid/contrib/slim/tests/test_quant2_int8_mkldnn_pass.py
Labels: Intel

#27147 [oneDNN] Fix to conv2d grad with groups (#27006)
  paddle/fluid/operators/mkldnn/conv_mkldnn_op.cc
Labels: Intel, dygraph

#27137 [oneDNN]Introducing oneDNN 1.6
  cmake/external/mkldnn.cmake
  paddle/fluid/operators/elementwise/elementwise_mul_op.h
Labels: Intel

#27198 Fix GRU mkldnn kernel fail on look_table_v2
  paddle/fluid/inference/tests/api/CMakeLists.txt
  paddle/fluid/operators/fused/fusion_gru_op.cc
  paddle/fluid/operators/fused/mkldnn/fusion_gru_mkldnn_op.cc
Labels: Intel

#27220 Add int8 GRU kernel
  cmake/external/mkldnn.cmake
  paddle/fluid/operators/fused/fusion_gru_op.cc
  paddle/fluid/operators/fused/mkldnn/fusion_gru_mkldnn_op.cc
  python/paddle/fluid/tests/unittests/mkldnn/test_fusion_gru_int8_mkldnn_op.py
Labels: Intel, int8

#27274 - Fix to concat oneDNN overwritting data
  paddle/fluid/operators/mkldnn/concat_mkldnn_op.cc
Labels: Intel

#26999 Add bfloat16 passes
  paddle/fluid/framework/ir/CMakeLists.txt
  paddle/fluid/framework/ir/graph_pattern_detector.cc
  paddle/fluid/framework/ir/graph_pattern_detector.h
  paddle/fluid/framework/ir/mkldnn/cpu_bfloat16_pass.cc
  paddle/fluid/framework/ir/mkldnn/cpu_bfloat16_pass.h
  paddle/fluid/framework/ir/mkldnn/cpu_bfloat16_pass_tester.cc
  paddle/fluid/framework/ir/mkldnn/cpu_bfloat16_placement_pass.cc
  paddle/fluid/framework/ir/mkldnn/cpu_bfloat16_placement_pass.h
  paddle/fluid/framework/ir/mkldnn/cpu_bfloat16_placement_pass_tester.cc
  paddle/fluid/inference/api/paddle_pass_builder.cc
  paddle/fluid/operators/mkldnn/quantize_mkldnn_op.cc
  paddle/fluid/operators/quantize_op.cc
  paddle/fluid/platform/mkldnn_helper.h
  paddle/fluid/pybind/protobuf.cc
Labels: BF16, Intel

#27273 [oneDNN] Fix to concat oneDNN overwritting data
  paddle/fluid/operators/mkldnn/concat_mkldnn_op.cc
Labels: Intel

#27484 Refine error message of MatchMatrix and PyramidHash
  paddle/fluid/operators/match_matrix_tensor_op.cc
  paddle/fluid/operators/pyramid_hash_op.cc
Labels: Error Message

#27532 【ErrorMessage】Fix error message in operator/utils.h
  paddle/fluid/operators/utils.h
Labels: Error Message

#27325 Add conv2d bfloat16 support
  paddle/fluid/framework/ir/graph_pattern_detector.cc
  paddle/fluid/operators/conv_op.cc
  paddle/fluid/operators/mkldnn/conv_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/dequantize_mkldnn_op.cc
  paddle/fluid/pybind/tensor_py.h
  python/paddle/fluid/framework.py
  python/paddle/fluid/tests/unittests/mkldnn/test_conv2d_bf16_mkldnn_op.py
  python/paddle/fluid/tests/unittests/mkldnn/test_conv2d_int8_mkldnn_op.py
  python/paddle/fluid/tests/unittests/mkldnn/test_dequantize_mkldnn_op.py
  python/paddle/fluid/tests/unittests/op_test.py
Labels: BF16, Intel

#27482 Add support for mkldnn ops types selection with FLAGS in dygraph
  paddle/fluid/imperative/tracer.cc
  paddle/fluid/platform/flags.cc
  paddle/fluid/pybind/global_value_getter_setter.cc
  python/paddle/fluid/__init__.py
  python/paddle/fluid/tests/unittests/mkldnn/check_flags_mkldnn_ops_on_off.py
  python/paddle/fluid/tests/unittests/mkldnn/test_flags_mkldnn_ops_on_off.py
Labels: Intel

#27481 Add support for (de/re)quantization with shift
  paddle/fluid/operators/dequantize_op.cc
  paddle/fluid/operators/mkldnn/dequantize_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/quantize_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/requantize_mkldnn_op.cc
  paddle/fluid/operators/quantize_op.cc
  paddle/fluid/operators/requantize_op.cc
  python/paddle/fluid/tests/unittests/mkldnn/test_dequantize_mkldnn_op.py
  python/paddle/fluid/tests/unittests/mkldnn/test_quantize_mkldnn_op.py
  python/paddle/fluid/tests/unittests/mkldnn/test_requantize_mkldnn_op.py
Labels: Intel, int8

#27732 Add avx512 core instructions check
  paddle/fluid/platform/cpu_info.cc
  paddle/fluid/pybind/pybind.cc
  python/paddle/fluid/tests/unittests/mkldnn/test_conv2d_bf16_mkldnn_op.py
Labels: BF16, Intel
