Repository PaddlePaddle/Paddle, pull requests merged in 2020-07, with the labels that each got.

#25291 Update release/1.8 document
  python/paddle/fluid/contrib/slim/tests/QAT_mkldnn_int8_readme.md
Labels: Intel

#25256 [oneDNN] Fix to #25078
  paddle/fluid/framework/ir/mkldnn/mkldnn_inplace_pass.cc
Labels: Intel

#25297 fix PADDLE_ENFORCE
  paddle/fluid/platform/collective_helper.cc
  paddle/fluid/platform/collective_helper.h
  paddle/fluid/platform/device_context.h
  paddle/fluid/platform/device_memory_aligment.cc
  paddle/fluid/platform/device_tracer.cc
  paddle/fluid/platform/dynload/cudnn.cc
  paddle/fluid/platform/stream_callback_manager.cc
  paddle/fluid/platform/transform.h
Labels: Error Message

#25313 Quant2 updates and fixes
  paddle/fluid/framework/ir/mkldnn/cpu_quantize_pass.cc
  python/paddle/fluid/contrib/slim/quantization/quant2_int8_mkldnn_pass.py
  python/paddle/fluid/contrib/slim/tests/CMakeLists.txt
  python/paddle/fluid/contrib/slim/tests/quant2_int8_image_classification_comparison.py
  python/paddle/fluid/contrib/slim/tests/quant2_int8_nlp_comparison.py
  python/paddle/fluid/contrib/slim/tests/save_quant_model.py
Labels: Intel, int8

#25416 [oneDNN] LRN cleanup
  paddle/fluid/operators/mkldnn/lrn_mkldnn_op.cc
  python/paddle/fluid/tests/unittests/mkldnn/test_lrn_mkldnn_op.py
  python/paddle/fluid/tests/unittests/white_list/no_check_set_white_list.py
Labels: Intel

#25450 [oneDNN] Added missing oneDNN format
  paddle/fluid/platform/mkldnn_helper.h
Labels: Intel

#25390 Attempt to resolve the TLS problem
  cmake/external/mkldnn.cmake
  python/paddle/fluid/core.py
Labels: Intel

#25572 [Cherry-pick] Refactor of conv fp32 oneDNN operator
  paddle/fluid/operators/mkldnn/conv_mkldnn_op.cc
  paddle/fluid/platform/mkldnn_reuse.h
Labels: Intel

#25576 [oneDNN] cache cosmetics improvement
  paddle/fluid/operators/mkldnn/conv_mkldnn_op.cc
  paddle/fluid/platform/mkldnn_reuse.h
Labels: Intel

#25637 Add NOMINMAX define due to windows.h max/min macro conflict
  paddle/fluid/framework/io/shell.h
  paddle/fluid/memory/detail/system_allocator.cc
  paddle/fluid/operators/math/matrix_bit_code.h
  paddle/fluid/platform/cpu_info.cc
  paddle/fluid/platform/enforce.h
Labels: Intel, windows

#25687 Fix FC + GRU fuse pass
  paddle/fluid/framework/ir/fc_gru_fuse_pass.cc
  paddle/fluid/inference/tests/api/analyzer_vis_tester.cc
  paddle/fluid/operators/fused/fusion_gru_op.cc
Labels: Intel

#25625 add gradient Merge Optimizer
  python/paddle/fluid/optimizer.py
  python/paddle/fluid/tests/unittests/test_optimizer.py
Labels: PythonAPI, 内部提出

#25582 Add an option to choose inference targets in Quant tests
  python/paddle/fluid/contrib/slim/tests/quant2_int8_image_classification_comparison.py
  python/paddle/fluid/contrib/slim/tests/quant2_int8_nlp_comparison.py
Labels: Intel, int8

#25733 [Cherry-pick] Fix FC + GRU fuse pass
  paddle/fluid/framework/ir/fc_gru_fuse_pass.cc
  paddle/fluid/inference/tests/api/analyzer_vis_tester.cc
  paddle/fluid/operators/fused/fusion_gru_op.cc
Labels: Intel

#25624 Added DNNL cache management for DyGraph
  paddle/fluid/framework/executor.cc
  paddle/fluid/framework/ir/pass.cc
  paddle/fluid/framework/naive_executor.cc
  paddle/fluid/imperative/CMakeLists.txt
  paddle/fluid/imperative/layer.cc
  paddle/fluid/platform/CMakeLists.txt
  paddle/fluid/platform/flags.cc
  paddle/fluid/platform/mkldnn_helper.h
Labels: Intel, dygraph

#25745 add dnnl sigmoid (logistic) activation
  paddle/fluid/operators/mkldnn/activation_mkldnn_op.cc
  python/paddle/fluid/tests/unittests/mkldnn/test_activation_mkldnn_op.py
  python/paddle/fluid/tests/unittests/test_imperative_basic.py
Labels: Intel, dygraph

#25734 TracedLayer Error Message Enhancement
  python/paddle/fluid/dygraph/jit.py
  python/paddle/fluid/tests/unittests/test_imperative_ptb_rnn.py
  python/paddle/fluid/tests/unittests/test_imperative_transformer_sorted_gradient.py
  python/paddle/fluid/tests/unittests/test_traced_layer_err_msg.py
Labels: Error Message
