Repository PaddlePaddle/Paddle, pull requests merged in 2020-06, with the labels that each got.

#24798 Add isCached() mechanism for BatchNorm and LRN oneDNN operators
  paddle/fluid/operators/mkldnn/batch_norm_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/lrn_mkldnn_op.cc
  paddle/fluid/platform/mkldnn_reuse.h
Labels: Intel

#24689 add option to exclude ops by id from quantization
  paddle/fluid/framework/ir/mkldnn/cpu_quantize_pass.cc
  python/paddle/fluid/contrib/slim/quantization/qat2_int8_mkldnn_pass.py
  python/paddle/fluid/contrib/slim/tests/QAT_mkldnn_int8_readme.md
  python/paddle/fluid/contrib/slim/tests/qat2_int8_image_classification_comparison.py
  python/paddle/fluid/contrib/slim/tests/qat2_int8_nlp_comparison.py
  python/paddle/fluid/contrib/slim/tests/save_qat_model.py
Labels: Intel

#24853 Fix bug in ShareBufferWith causing non-fp32 inplace uts to fail
  paddle/fluid/framework/tensor.h
Labels: Intel, int8

#24855 Remove old mkldnn_elementwise_mul test
  paddle/fluid/operators/elementwise/CMakeLists.txt
  paddle/fluid/operators/elementwise/test_elementwise_mul_op_dim.cc
Labels: Intel

#24756 [oneDNN] Clearing mkldnn cache in naiveexecutor destructor
  paddle/fluid/framework/executor.cc
  paddle/fluid/framework/ir/CMakeLists.txt
  paddle/fluid/framework/ir/conv_bn_fuse_pass.cc
  paddle/fluid/framework/ir/mkldnn/mkldnn_conv_bn_fuse_pass_tester.cc
  paddle/fluid/framework/ir/pass.cc
  paddle/fluid/framework/naive_executor.cc
  paddle/fluid/framework/naive_executor.h
Labels: Intel

#24854 Fix OpTester from incorrectly converting uint8 data to utf-8 string
  python/paddle/fluid/tests/unittests/op_test.py
Labels: Intel, int8

#24929 fix WARNING: ThreadSanitizer: heap-use-after-free
  paddle/fluid/framework/ir/fc_elementwise_layernorm_fuse_pass.cc
Labels: Bug, Intel

#24970 Reshape transpose matmul coverage
  paddle/fluid/framework/ir/CMakeLists.txt
  paddle/fluid/framework/ir/mkldnn/reshape_transpose_matmul_mkldnn_fuse_pass_tester.cc
Labels: Intel

#24984 [oneDNN]elementwise_add and elementwise_mul int8 support
  paddle/fluid/framework/ir/graph_pattern_detector.cc
  paddle/fluid/operators/elementwise/elementwise_mul_op.h
  paddle/fluid/operators/elementwise/elementwise_op.h
  paddle/fluid/operators/elementwise/mkldnn/elementwise_add_mkldnn_op.cc
  paddle/fluid/operators/elementwise/mkldnn/elementwise_mkldnn_op.h
  paddle/fluid/operators/elementwise/mkldnn/elementwise_mul_mkldnn_op.cc
  paddle/fluid/platform/mkldnn_reuse.h
  python/paddle/fluid/layers/nn.py
  python/paddle/fluid/tests/unittests/mkldnn/test_elementwise_add_mkldnn_op.py
  python/paddle/fluid/tests/unittests/mkldnn/test_elementwise_mul_mkldnn_op.py
  python/paddle/tensor/math.py
Labels: Intel

#25137 Refactor of conv fp32 oneDNN operator
  paddle/fluid/operators/mkldnn/conv_mkldnn_op.cc
  paddle/fluid/platform/mkldnn_reuse.h
Labels: Intel

#25182 [cherry-pick 1.8] Fix to inplace pass (#24442)
  paddle/fluid/framework/ir/mkldnn/mkldnn_inplace_pass.cc
Labels: Intel

#25194 rename qat into quant in filenames only
  paddle/fluid/inference/tests/api/CMakeLists.txt
  paddle/fluid/inference/tests/api/analyzer_quant_image_classification_tester.cc
  python/paddle/fluid/contrib/slim/quantization/__init__.py
  python/paddle/fluid/contrib/slim/quantization/quant2_int8_mkldnn_pass.py
  python/paddle/fluid/contrib/slim/quantization/quant_int8_mkldnn_pass.py
  python/paddle/fluid/contrib/slim/tests/CMakeLists.txt
  python/paddle/fluid/contrib/slim/tests/README.md
  python/paddle/fluid/contrib/slim/tests/quant2_int8_image_classification_comparison.py
  python/paddle/fluid/contrib/slim/tests/quant2_int8_nlp_comparison.py
  python/paddle/fluid/contrib/slim/tests/quant_int8_image_classification_comparison.py
  python/paddle/fluid/contrib/slim/tests/save_quant_model.py
  python/paddle/fluid/contrib/slim/tests/test_quant2_int8_mkldnn_pass.py
Labels: Intel, int8

#25178 adding elementwiseadd quantization
  paddle/fluid/framework/ir/mkldnn/cpu_quantize_pass.cc
  paddle/fluid/framework/ir/mkldnn/cpu_quantize_pass.h
  paddle/fluid/framework/ir/mkldnn/cpu_quantize_pass_tester.cc
  paddle/fluid/inference/api/mkldnn_quantizer_config.cc
Labels: Intel

#24948 Rename QAT into Quant, update Quant2 INT8 options
  paddle/fluid/inference/tests/api/CMakeLists.txt
  paddle/fluid/inference/tests/api/analyzer_quant_image_classification_tester.cc
  python/paddle/fluid/contrib/slim/quantization/quant2_int8_mkldnn_pass.py
  python/paddle/fluid/contrib/slim/quantization/quant_int8_mkldnn_pass.py
  python/paddle/fluid/contrib/slim/tests/CMakeLists.txt
  python/paddle/fluid/contrib/slim/tests/README.md
  python/paddle/fluid/contrib/slim/tests/quant2_int8_image_classification_comparison.py
  python/paddle/fluid/contrib/slim/tests/quant2_int8_nlp_comparison.py
  python/paddle/fluid/contrib/slim/tests/quant_int8_image_classification_comparison.py
  python/paddle/fluid/contrib/slim/tests/save_quant_model.py
  python/paddle/fluid/contrib/slim/tests/test_quant2_int8_mkldnn_pass.py
  python/paddle/fluid/contrib/slim/tests/test_quantization_mkldnn_pass.py
Labels: Intel, int8
