Repository PaddlePaddle/Paddle, pull requests merged in 2020-08, with the labels that each got.

#25594 Add oneDNN fusion_gru kernel
  cmake/operators.cmake
  paddle/fluid/operators/fused/CMakeLists.txt
  paddle/fluid/operators/fused/fusion_gru_op.cc
  paddle/fluid/operators/fused/mkldnn/fusion_gru_mkldnn_op.cc
  paddle/fluid/platform/mkldnn_helper.h
  python/paddle/fluid/tests/unittests/mkldnn/test_fusion_gru_mkldnn_op.py
  python/paddle/fluid/tests/unittests/test_fusion_gru_op.py
Labels: Intel

#25779 enable check_dygraph for mkldnn activation tests
  python/paddle/fluid/tests/unittests/mkldnn/test_activation_mkldnn_op.py
Labels: Intel, dygraph

#25838 Change use_quantizer attribute name and data type
  paddle/fluid/framework/ir/mkldnn/cpu_quantize_pass.cc
  paddle/fluid/framework/ir/mkldnn/cpu_quantize_pass_tester.cc
  paddle/fluid/framework/ir/mkldnn/cpu_quantize_placement_pass.cc
  paddle/fluid/framework/ir/mkldnn/cpu_quantize_placement_pass_tester.cc
  paddle/fluid/inference/api/mkldnn_quantizer.cc
  paddle/fluid/operators/concat_op.cc
  paddle/fluid/operators/conv_op.cc
  paddle/fluid/operators/detection/prior_box_op.cc
  paddle/fluid/operators/elementwise/elementwise_op.h
  paddle/fluid/operators/fc_op.cc
  paddle/fluid/operators/matmul_op.cc
  paddle/fluid/operators/pool_op.cc
  paddle/fluid/operators/reshape_op.cc
  paddle/fluid/operators/transpose_op.cc
  paddle/fluid/platform/mkldnn_helper.h
  python/paddle/fluid/layers/nn.py
  python/paddle/tensor/math.py
Labels: Intel

#26037 Add oneDNN relu6 op
  paddle/fluid/operators/activation_op.cc
  paddle/fluid/operators/mkldnn/activation_mkldnn_op.cc
  python/paddle/fluid/layers/nn.py
  python/paddle/fluid/tests/unittests/mkldnn/test_activation_mkldnn_op.py
Labels: Intel, dygraph

#25202 - oneDNN update 1.3 -> 1.5
  cmake/external/mkldnn.cmake
  python/paddle/fluid/tests/unittests/mkldnn/test_matmul_mkldnn_op.py
Labels: Intel

#25534 GRU model xnli dataset C++ tester
  paddle/fluid/inference/tests/api/CMakeLists.txt
  paddle/fluid/inference/tests/api/analyzer_lexical_analysis_gru_tester.cc
Labels: Intel

#25778 Enable mkldnn layout conversion
  paddle/fluid/imperative/prepared_operator.cc
  paddle/fluid/imperative/tests/test_prepare_op.cc
  paddle/fluid/operators/conv_op.cc
  python/paddle/fluid/tests/unittests/mkldnn/test_activation_mkldnn_op.py
Labels: Intel, dygraph

#25773 add use_mkldnn attribute to ops in dygraph
  python/paddle/fluid/dygraph/layer_object_helper.py
  python/paddle/fluid/dygraph/nn.py
  python/paddle/fluid/dygraph_utils.py
  python/paddle/fluid/layers/nn.py
  python/paddle/fluid/tests/unittests/test_imperative_basic.py
Labels: Intel, dygraph

#26671 Small changes in conv2d mkldnn and in cpu_quantize_pass
  paddle/fluid/framework/ir/mkldnn/cpu_quantize_placement_pass.cc
  paddle/fluid/framework/ir/mkldnn/cpu_quantize_placement_pass_tester.cc
  paddle/fluid/operators/mkldnn/conv_mkldnn_op.cc
  paddle/fluid/platform/mkldnn_reuse.h
Labels: Intel

#26413 Update Paddle-Lite commit hash.
  cmake/external/lite.cmake
  paddle/fluid/framework/framework.proto
Labels: BF16, Intel

#26676 Add mkldnn bfloat16 option to C-API
  go/paddle/config.go
  paddle/fluid/inference/api/analysis_config.cc
  paddle/fluid/inference/api/analysis_predictor_tester.cc
  paddle/fluid/inference/api/paddle_analysis_config.h
  paddle/fluid/inference/api/paddle_pass_builder.cc
  paddle/fluid/inference/api/paddle_pass_builder.h
  paddle/fluid/inference/capi/paddle_c_api.h
  paddle/fluid/inference/capi/pd_config.cc
  paddle/fluid/inference/tests/api/analyzer_capi_gpu_tester.cc
  paddle/fluid/inference/tests/api/analyzer_capi_tester.cc
  paddle/fluid/pybind/inference_api.cc
Labels: BF16, Intel

#26715 Fix int8 performace drop cpu_quantize_placement_pass
  paddle/fluid/framework/ir/graph_pattern_detector.cc
  paddle/fluid/framework/ir/graph_pattern_detector.h
  paddle/fluid/framework/ir/mkldnn/cpu_quantize_placement_pass.cc
  paddle/fluid/framework/ir/mkldnn/cpu_quantize_placement_pass.h
  paddle/fluid/framework/ir/mkldnn/cpu_quantize_placement_pass_tester.cc
Labels: Intel, int8

#26708 Decouple weights and bias from fc primitive in MKLDNN cache
  paddle/fluid/operators/mkldnn/fc_mkldnn_op.cc
Labels: Intel

#26779 Upgrades to speedup oneDNN MASK-RCNN execution
  paddle/fluid/framework/ir/conv_affine_channel_fuse_pass.cc
  paddle/fluid/inference/api/paddle_pass_builder.cc
Labels: Intel

#26497 Add use of global flag 'use_mkldnn' to layer_helper
  paddle/fluid/imperative/tracer.cc
  paddle/fluid/pybind/global_value_getter_setter.cc
  python/paddle/fluid/tests/unittests/test_get_set_flags.py
  python/paddle/fluid/tests/unittests/test_global_var_getter_setter.py
  python/paddle/fluid/tests/unittests/test_imperative_basic.py
Labels: Intel, dygraph
