Repository PaddlePaddle/Paddle, pull requests merged in 2020-04, with the labels that each got.

#23204 Update DNNL version to 1.3
  cmake/external/mkldnn.cmake
Labels: Intel

#23315 [DNNL] Added MKL-DNN inplace pass for C-API inference
  paddle/fluid/framework/ir/CMakeLists.txt
  paddle/fluid/framework/ir/graph_pattern_detector.cc
  paddle/fluid/framework/ir/graph_pattern_detector.h
  paddle/fluid/framework/ir/mkldnn/mkldnn_inplace_pass.cc
  paddle/fluid/framework/ir/mkldnn/mkldnn_inplace_pass.h
  paddle/fluid/framework/ir/mkldnn/mkldnn_inplace_pass_tester.cc
  paddle/fluid/inference/api/paddle_pass_builder.cc
Labels: Intel, inference

#23202 handle conv2d activations in older QAT models
  python/paddle/fluid/contrib/slim/quantization/qat2_int8_mkldnn_pass.py
  python/paddle/fluid/contrib/slim/tests/test_qat2_int8_mkldnn_pass.py
Labels: Intel

#23318 Delete is_test attribute from activation operators
  paddle/fluid/operators/activation_op.cc
  paddle/fluid/operators/gelu_op.cc
  paddle/fluid/operators/mkldnn/activation_mkldnn_op.cc
  paddle/fluid/platform/mkldnn_reuse.h
Labels: Intel

#23042 Add default pass attributes
  paddle/fluid/framework/ir/mkldnn/cpu_quantize_placement_pass.cc
  paddle/fluid/framework/ir/mkldnn/cpu_quantize_placement_pass_tester.cc
  paddle/fluid/framework/ir/pass.h
  paddle/fluid/framework/ir/pass_test.cc
Labels: Intel

#23428 API (case) error message enhancement.
  python/paddle/fluid/layers/control_flow.py
  python/paddle/fluid/tests/unittests/test_case.py
Labels: Error Message

#23429 API (switch_case) error message enhancement.
  python/paddle/fluid/layers/control_flow.py
Labels: Error Message

#22997 Delete Ref & VectorRef and add GetDataSafely
  paddle/fluid/operators/activation_cudnn.cu.cc
  paddle/fluid/operators/activation_cudnn_op.cu.cc
  paddle/fluid/operators/activation_op.h
  paddle/fluid/operators/add_position_encoding_op.h
  paddle/fluid/operators/controlflow/get_places_op.cc
  paddle/fluid/operators/controlflow/tensor_array_read_write_op.cc
  paddle/fluid/operators/controlflow/while_op.cc
  paddle/fluid/operators/conv_op.h
  paddle/fluid/operators/cum_op.h
  paddle/fluid/operators/detail/safe_ref.h
  paddle/fluid/operators/detection/collect_fpn_proposals_op.h
  paddle/fluid/operators/detection/distribute_fpn_proposals_op.h
  paddle/fluid/operators/detection/generate_proposals_op.cc
  paddle/fluid/operators/detection/generate_proposals_op.cu
  paddle/fluid/operators/fill_op.h
  paddle/fluid/operators/fused/fused_elemwise_activation_op.h
  paddle/fluid/operators/fused/fused_embedding_eltwise_layernorm_op.cc
  paddle/fluid/operators/fused/fused_embedding_eltwise_layernorm_op.cu
  paddle/fluid/operators/fused/multihead_matmul_op.cc
  paddle/fluid/operators/fused/multihead_matmul_op.cu
  paddle/fluid/operators/hierarchical_sigmoid_op.h
  paddle/fluid/operators/lod_tensor_to_array_op.cc
  paddle/fluid/operators/matmul_op.cc
  paddle/fluid/operators/mkldnn/mkldnn_activation_op.h
  paddle/fluid/operators/optimizers/adam_op.cu
  paddle/fluid/operators/optimizers/adam_op.h
  paddle/fluid/operators/optimizers/lamb_op.h
  paddle/fluid/operators/random_crop_op.h
  paddle/fluid/operators/reader/create_custom_reader_op.cc
  paddle/fluid/operators/reader/read_op.cc
  paddle/fluid/operators/reorder_lod_tensor_by_rank_op.cc
  paddle/fluid/operators/scale_op.cc
  paddle/fluid/operators/sequence_ops/sequence_concat_op.h
  paddle/fluid/operators/sequence_ops/sequence_expand_as_op.h
  paddle/fluid/operators/sum_op.cc
  paddle/fluid/platform/enforce.h
  paddle/fluid/platform/enforce_test.cc
Labels: Error Message

#23454 Op (FusedEmbeddingSeqPool) error message enhancement.
  paddle/fluid/operators/fused/fused_embedding_seq_pool_op.cc
  paddle/fluid/operators/fused/fused_embedding_seq_pool_op.h
Labels: Error Message

#23498 Op (FusionSquaredMatSub) error message enhancement.
  paddle/fluid/operators/fused/fused_embedding_seq_pool_op.cc
  paddle/fluid/operators/fused/fusion_squared_mat_sub_op.cc
Labels: Error Message

#22426 Add MKL-DNN GELU activation
  paddle/fluid/operators/gelu_op.cc
  paddle/fluid/operators/mkldnn/activation_mkldnn_op.cc
  python/paddle/fluid/tests/unittests/mkldnn/test_activation_mkldnn_op.py
Labels: Intel

#23525 API(BatchNorm) error message enhancement
  python/paddle/fluid/dygraph/nn.py
  python/paddle/fluid/tests/unittests/test_batch_norm_op.py
Labels: Error Message

#23515 API(place-related) error message enhancement
  paddle/fluid/platform/place.h
Labels: Error Message

#23458 Op (Scope) error message enhancement
  paddle/fluid/framework/scope.cc
  paddle/fluid/framework/scope_pool.cc
  python/paddle/fluid/tests/unittests/test_scope.py
Labels: Error Message

#23481 OP (recurrent) error message enhancement
  paddle/fluid/operators/controlflow/recurrent_op_helper.cc
  paddle/fluid/operators/recurrent_op.h
Labels: Error Message

#23526 Op(feed) error message enhancement.
  paddle/fluid/operators/controlflow/feed_op.cc
Labels: Error Message

#23620 Refine batch_norm op converter error message
  paddle/fluid/inference/tensorrt/convert/activation_op.cc
  paddle/fluid/inference/tensorrt/convert/batch_norm_op.cc
Labels: Error Message

#23505 Add matmul-dequant squash
  paddle/fluid/framework/ir/graph_pattern_detector.cc
  paddle/fluid/framework/ir/graph_pattern_detector.h
  paddle/fluid/framework/ir/mkldnn/cpu_quantize_squash_pass.cc
  paddle/fluid/framework/ir/mkldnn/cpu_quantize_squash_pass.h
  paddle/fluid/framework/ir/mkldnn/cpu_quantize_squash_pass_tester.cc
Labels: Intel, int8

#23468 OP (tensor_array_read_write) error message enhancement.
  paddle/fluid/operators/array_operator.h
  paddle/fluid/operators/controlflow/tensor_array_read_write_op.cc
Labels: Error Message

#23459 API (Switch) error message enhancement. test=develop
  python/paddle/fluid/layers/control_flow.py
  python/paddle/fluid/layers/tensor.py
  python/paddle/fluid/tests/unittests/test_switch.py
Labels: Error Message

#23427 API (layers.data/fluid.data) error message enhancement
  python/paddle/fluid/data.py
  python/paddle/fluid/layers/io.py
  python/paddle/fluid/tests/unittests/test_data.py
Labels: Error Message

#23499 Op (lod_reset) error message enhancement
  paddle/fluid/operators/lod_reset_op.cc
  paddle/fluid/operators/lod_reset_op.h
  python/paddle/fluid/layers/nn.py
  python/paddle/fluid/tests/unittests/test_lod_reset_op.py
Labels: Error Message

#23519 API(Program) error message enhancement
  paddle/fluid/framework/block_desc.cc
  paddle/fluid/framework/program_desc.cc
  paddle/fluid/pybind/protobuf.cc
  python/paddle/fluid/framework.py
  python/paddle/fluid/tests/unittests/test_program.py
  python/paddle/fluid/tests/unittests/test_prune.py
Labels: Error Message

#23523 Op (concat) error message enhancement
  paddle/fluid/operators/concat_op.cc
  paddle/fluid/operators/concat_op.h
Labels: Error Message

#23534 API(LayerNorm) error message enhancement
  python/paddle/fluid/dygraph/nn.py
  python/paddle/fluid/tests/unittests/test_layer_norm_op.py
Labels: Error Message

#23560 fill op error message enhancement. test=develop
  paddle/fluid/operators/fill_op.cc
Labels: Error Message

#23562 repeated fc op error message enhancement.
  paddle/fluid/operators/fused/fusion_repeated_fc_relu_op.cc
Labels: Error Message

#23450 API(fluid.gridents) error message enhancement
  python/paddle/fluid/backward.py
  python/paddle/fluid/tests/unittests/test_backward.py
  python/paddle/fluid/tests/unittests/test_imperative_star_gan_with_gradient_penalty.py
Labels: Error Message

#23445 Api/Op (select_input/select_ouput) error message enhancement.
  paddle/fluid/operators/select_input_op.cc
  paddle/fluid/operators/select_op_helper.h
  paddle/fluid/operators/select_output_op.cc
  python/paddle/fluid/layers/control_flow.py
  python/paddle/fluid/tests/unittests/test_select_input_output_op.py
Labels: Error Message

#23638 box_clip error message enhance, test=develop
  paddle/fluid/operators/detection/box_clip_op.cc
  paddle/fluid/operators/detection/box_clip_op.cu
  paddle/fluid/operators/detection/box_clip_op.h
  python/paddle/fluid/layers/detection.py
Labels: Error Message

#23547 API(fluid.layers.array_length) error message enhancement
  paddle/fluid/operators/lod_array_length_op.cc
  python/paddle/fluid/layers/control_flow.py
  python/paddle/fluid/tests/unittests/test_lod_array_length_op.py
Labels: Error Message

#23556 OP(fake_dequantize) error message enhancement
  paddle/fluid/operators/fake_dequantize_op.cc
  paddle/fluid/operators/fake_dequantize_op.h
Labels: Error Message

#23550 OP(fake_quantize) error message enhancement
  paddle/fluid/operators/fake_quantize_op.cc
Labels: Error Message

#23542 Op(fetch) error message enhancement.
  paddle/fluid/operators/controlflow/fetch_op.cc
Labels: Error Message

#23480 API/OP (ConditionalBlock) error message enhancement
  paddle/fluid/operators/controlflow/conditional_block_infer_op.cc
  paddle/fluid/operators/controlflow/conditional_block_op.cc
  paddle/fluid/operators/controlflow/conditional_block_op.h
  paddle/fluid/operators/controlflow/conditional_block_op_helper.cc
  python/paddle/fluid/layers/control_flow.py
Labels: Error Message

#23621 OP(minus) error message enhancement. test=develop
  paddle/fluid/operators/minus_op.cc
Labels: Error Message

#23546 API (BuildStrategy) error message enhancement
  paddle/fluid/pybind/pybind.cc
Labels: Error Message

#23625 Refine transpose flatten concat error message
  paddle/fluid/operators/fused/fusion_transpose_flatten_concat_op.cc
  paddle/fluid/operators/fused/fusion_transpose_flatten_concat_op.cu.cc
Labels: Error Message

#23561 API/OP (Conv2D) error message enhancement
  python/paddle/fluid/dygraph/nn.py
  python/paddle/fluid/tests/unittests/test_layers.py
Labels: Error Message

#23452 API(program_guard) error message enhancement
  python/paddle/fluid/framework.py
Labels: Error Message

#23571 API(create_tensor) error message enhancement
  python/paddle/fluid/layers/tensor.py
Labels: Error Message

#23544 error message of NCE API enhancement
  python/paddle/fluid/dygraph/nn.py
  python/paddle/fluid/tests/unittests/test_nce.py
Labels: Error Message

#23649 enhance the error message of roi_align, test=develop
  paddle/fluid/operators/roi_align_op.cc
  paddle/fluid/operators/roi_align_op.cu
  paddle/fluid/operators/roi_align_op.h
  python/paddle/fluid/layers/nn.py
Labels: Error Message

#23462 API (BuildStrategy) error message enhancement.
  paddle/fluid/framework/details/build_strategy.cc
Labels: Error Message

#23510 Op(relu) error message enhancement
  python/paddle/fluid/layers/nn.py
  python/paddle/fluid/tests/unittests/test_activation_op.py
Labels: Error Message

#23565 error message enhancement for py_func op.
  paddle/fluid/operators/fused/fusion_repeated_fc_relu_op.cc
  paddle/fluid/operators/py_func_op.cc
  python/paddle/fluid/layers/nn.py
Labels: Error Message

#23563 error message enhancement for fusion_seqpool_concat_op.
  paddle/fluid/operators/fused/fusion_seqpool_concat_op.cc
Labels: Error Message

#23572 Enhance error msg of imperative code
  paddle/fluid/imperative/layer.cc
  paddle/fluid/imperative/prepared_operator.cc
  paddle/fluid/imperative/tests/test_prepare_op.cc
  paddle/fluid/pybind/imperative.cc
Labels: Error Message

#23516 error message of SpectralNorm API enhancement
  python/paddle/fluid/dygraph/nn.py
  python/paddle/fluid/tests/unittests/test_spectral_norm_op.py
Labels: Error Message

#23568 API(fluid.layers.array_read/array_write) error message enhancement
  python/paddle/fluid/layers/control_flow.py
  python/paddle/fluid/tests/unittests/test_array_read_write_op.py
Labels: Error Message

#23520 Refine shuffle channel trt op error message
  paddle/fluid/inference/tensorrt/convert/shuffle_channel_op.cc
Labels: Error Message

#23552 Op (reorder_lod_tensor_by_rank) error message enhancement
  paddle/fluid/operators/reorder_lod_tensor_by_rank_op.cc
  python/paddle/fluid/layers/control_flow.py
  python/paddle/fluid/tests/unittests/test_reorder_lod_tensor.py
Labels: Error Message

#23657 Enable matmul and cleanup in QAT2
  python/paddle/fluid/contrib/slim/quantization/qat2_int8_mkldnn_pass.py
  python/paddle/fluid/contrib/slim/tests/CMakeLists.txt
Labels: Intel

#23599 OP(fusion_lstm) error message enhancement. test=develop
  paddle/fluid/operators/fused/fusion_lstm_op.cc
Labels: Error Message

#23446 API(append_backward) error message enhancement
  python/paddle/fluid/backward.py
  python/paddle/fluid/tests/unittests/test_backward.py
Labels: Error Message

#23528 API(BilinearTensorProduct) error message enhancement
  python/paddle/fluid/dygraph/nn.py
  python/paddle/fluid/tests/unittests/test_bilinear_tensor_product_op.py
Labels: Error Message

#23533 API(Embedding) error message enhancement
  python/paddle/fluid/dygraph/nn.py
  python/paddle/fluid/tests/unittests/test_lookup_table_v2_op.py
Labels: Error Message

#23535 API(GRUUnit) error message enhancement
  python/paddle/fluid/dygraph/nn.py
  python/paddle/fluid/tests/unittests/test_gru_unit_op.py
Labels: Error Message

#23539 API(PRelu) error message enhancement
  python/paddle/fluid/dygraph/nn.py
  python/paddle/fluid/tests/unittests/test_prelu_op.py
Labels: Error Message

#23675 imporve error messages for conv, conv_transpose, cos_sim, group_norm
  paddle/fluid/operators/conv_op.cc
  paddle/fluid/operators/conv_transpose_op.cc
  paddle/fluid/operators/cos_sim_op.cc
  paddle/fluid/operators/group_norm_op.cc
Labels: Error Message

#23395 [DNNL][INT8][FP32] MatMul
  paddle/fluid/operators/matmul_op.cc
  paddle/fluid/operators/mkldnn/matmul_mkldnn_op.cc
  paddle/fluid/platform/mkldnn_helper.h
  python/paddle/fluid/tests/unittests/mkldnn/test_matmul_mkldnn_op.py
Labels: Intel, int8

#23665 Op-requant squash
  paddle/fluid/framework/ir/graph_pattern_detector.cc
  paddle/fluid/framework/ir/graph_pattern_detector.h
  paddle/fluid/framework/ir/mkldnn/cpu_quantize_squash_pass.cc
  paddle/fluid/framework/ir/mkldnn/cpu_quantize_squash_pass.h
  paddle/fluid/framework/ir/mkldnn/cpu_quantize_squash_pass_tester.cc
Labels: Intel, int8

#23605 refine act conv2d pool2d trt converter log
  paddle/fluid/inference/tensorrt/convert/activation_op.cc
  paddle/fluid/inference/tensorrt/convert/conv2d_op.cc
  paddle/fluid/inference/tensorrt/convert/fc_op.cc
  paddle/fluid/inference/tensorrt/convert/pool2d_op.cc
Labels: Error Message

#23361 [Doc update] Update for QAT INT8 MKL-DNN document
  python/paddle/fluid/contrib/slim/tests/QAT_mkldnn_int8_readme.md
Labels: Intel

#23726 OP(retinanet_detection_output, retinanet_target_assign, sigmoid_focal_loss, deformable_roi_pooling) error message enhancement
  paddle/fluid/operators/deformable_psroi_pooling_op.cc
  paddle/fluid/operators/deformable_psroi_pooling_op.cu
  paddle/fluid/operators/deformable_psroi_pooling_op.h
  paddle/fluid/operators/detection/retinanet_detection_output_op.cc
  paddle/fluid/operators/detection/rpn_target_assign_op.cc
  paddle/fluid/operators/detection/sigmoid_focal_loss_op.cc
  python/paddle/fluid/layers/detection.py
  python/paddle/fluid/layers/nn.py
  python/paddle/fluid/tests/unittests/test_deformable_psroi_pooling.py
  python/paddle/fluid/tests/unittests/test_layers.py
  python/paddle/fluid/tests/unittests/test_retinanet_detection_output.py
  python/paddle/fluid/tests/unittests/test_rpn_target_assign_op.py
  python/paddle/fluid/tests/unittests/test_sigmoid_focal_loss_op.py
Labels: Error Message

#23691 API/OP error message enhancement
  paddle/fluid/operators/batch_norm_op.cc
  paddle/fluid/operators/cos_sim_op.cc
  paddle/fluid/operators/dropout_op.cc
  paddle/fluid/operators/instance_norm_op.cc
  python/paddle/fluid/layers/loss.py
  python/paddle/fluid/layers/nn.py
  python/paddle/fluid/tests/unittests/test_cos_sim_op.py
  python/paddle/fluid/tests/unittests/test_instance_norm_op.py
  python/paddle/fluid/tests/unittests/test_npair_loss_op.py
Labels: Error Message

#23584 API/OP(fill_constant) error message enhancement
  paddle/fluid/framework/parallel_executor.cc
  paddle/fluid/operators/fill_constant_op.cc
  paddle/fluid/operators/fill_constant_op.h
  python/paddle/fluid/layers/tensor.py
  python/paddle/fluid/tests/unittests/test_fill_constant_op.py
Labels: Error Message

#23483 Error Message Enhancement
  paddle/fluid/framework/executor.cc
  paddle/fluid/framework/parallel_executor.cc
  paddle/fluid/operators/split_lod_tensor_op.cc
  python/paddle/fluid/layers/control_flow.py
  python/paddle/fluid/parallel_executor.py
  python/paddle/fluid/tests/test_if_else_op.py
  python/paddle/fluid/tests/unittests/test_cond.py
  python/paddle/fluid/tests/unittests/test_split_and_merge_lod_tensor_op.py
Labels: Error Message

#23603 API/OP (clip_by_norm/clip) error message enhancement
  paddle/fluid/operators/clip_by_norm_op.h
  paddle/fluid/operators/clip_op.cc
  python/paddle/fluid/layers/nn.py
Labels: Error Message

#23559 API (CompiledProgram) error message enhancement
  paddle/fluid/framework/ir/graph.cc
  paddle/fluid/framework/ir/graph.h
  python/paddle/fluid/compiler.py
  python/paddle/fluid/tests/unittests/test_compiled_program.py
Labels: Error Message

#23734 Add scale-matmul fuse pass
  paddle/fluid/framework/ir/CMakeLists.txt
  paddle/fluid/framework/ir/graph_pattern_detector.cc
  paddle/fluid/framework/ir/graph_pattern_detector.h
  paddle/fluid/framework/ir/mkldnn/scale_matmul_fuse_pass.cc
  paddle/fluid/framework/ir/mkldnn/scale_matmul_fuse_pass.h
  paddle/fluid/framework/ir/mkldnn/scale_matmul_fuse_pass_tester.cc
  paddle/fluid/inference/api/paddle_pass_builder.cc
  python/paddle/fluid/contrib/slim/quantization/qat2_int8_mkldnn_pass.py
Labels: Intel, int8

#23661 Refine error message of leaky_relu, tensorrt_engine, split, prelu op converter
  paddle/fluid/inference/tensorrt/convert/leaky_relu_op.cc
  paddle/fluid/inference/tensorrt/convert/prelu_op.cc
  paddle/fluid/inference/tensorrt/convert/split_op.cc
  paddle/fluid/inference/tensorrt/plugin/split_op_plugin.cu
  paddle/fluid/operators/tensorrt/tensorrt_engine_op.h
Labels: Error Message

#23684 API/OP error message enhancement
  paddle/fluid/operators/conv_shift_op.cc
  paddle/fluid/operators/l1_norm_op.cc
  paddle/fluid/operators/l1_norm_op.h
  paddle/fluid/operators/norm_op.cc
  paddle/fluid/operators/sample_logits_op.cc
  paddle/fluid/operators/sample_logits_op.h
  paddle/fluid/operators/squared_l2_distance_op.cc
  paddle/fluid/operators/squared_l2_norm_op.cc
  paddle/fluid/operators/squared_l2_norm_op.h
  python/paddle/fluid/tests/unittests/test_sample_logits_op.py
Labels: Error Message

#23646 enhance the error message, test=develop
  paddle/fluid/operators/detection/box_coder_op.cc
  paddle/fluid/operators/detection/box_coder_op.cu
  paddle/fluid/operators/detection/box_coder_op.h
  paddle/fluid/operators/detection/box_decoder_and_assign_op.cc
  paddle/fluid/operators/detection/box_decoder_and_assign_op.cu
  paddle/fluid/operators/detection/collect_fpn_proposals_op.cc
  paddle/fluid/operators/detection/collect_fpn_proposals_op.h
  paddle/fluid/operators/detection/distribute_fpn_proposals_op.cc
  paddle/fluid/operators/detection/distribute_fpn_proposals_op.cu
  paddle/fluid/operators/detection/distribute_fpn_proposals_op.h
  paddle/fluid/operators/detection/multiclass_nms_op.cc
  python/paddle/fluid/layers/detection.py
  python/paddle/fluid/tests/test_detection.py
Labels: Error Message

#23548 Variable error message enhancement.
  paddle/fluid/framework/variable.h
Labels: Error Message

#23558 fusion_seqexpand_concat_fc error message enhancement.
  paddle/fluid/operators/fused/fusion_seqexpand_concat_fc_op.cc
Labels: Error Message

#23623 API (create_parameter, create_global_var) error message enhancement
  python/paddle/fluid/layers/tensor.py
  python/paddle/fluid/tests/unittests/test_create_global_var.py
  python/paddle/fluid/tests/unittests/test_create_parameter.py
Labels: Error Message

#23521 API(Print) error message enhancement. test=develop
  paddle/fluid/operators/print_op.cc
Labels: Error Message

#23527 OP(fused_embedding_fc_lstm) error message enhancement. test=develop
  paddle/fluid/operators/fused/fused_embedding_fc_lstm_op.cc
Labels: Error Message

#23554 fusion_seqconv_eltadd_relu error message enhancement.
  paddle/fluid/operators/fused/fusion_seqconv_eltadd_relu_op.cc
Labels: Error Message

#23541 Api (lod_append) error message enhancement
  paddle/fluid/operators/concat_op.h
  paddle/fluid/operators/lod_reset_op.cc
  paddle/fluid/operators/lod_reset_op.h
  python/paddle/fluid/layers/nn.py
  python/paddle/fluid/tests/unittests/test_layers.py
  python/paddle/fluid/tests/unittests/test_lod_append_op.py
Labels: Error Message

#23692 Add user local data preprocess support
  paddle/fluid/inference/tests/api/CMakeLists.txt
  paddle/fluid/inference/tests/api/full_ILSVRC2012_val_preprocess.py
  paddle/fluid/inference/tests/api/full_pascalvoc_test_preprocess.py
Labels: Intel

#23596 Op(conv2d_fusion) error message enhancement.
  paddle/fluid/imperative/infer_shape_context.h
  paddle/fluid/operators/conv_op.cc
  paddle/fluid/operators/conv_op.h
  paddle/fluid/operators/fill_constant_op.cc
  paddle/fluid/operators/fused/conv_fusion_op.cc
  paddle/fluid/operators/fused/conv_fusion_op.cu
  python/paddle/fluid/tests/unittests/test_conv2d_fusion_op.py
Labels: Error Message

#23591 OP(fusion_gru) error message enhancement. test=develop
  paddle/fluid/operators/fused/fusion_gru_op.cc
Labels: Error Message

#24032 add boost dependency to cuda_stream, test=develop
  paddle/fluid/platform/stream/CMakeLists.txt
Labels: Multi-stream

#23477 [DNNL] Added elementwise_add mkl-dnn inplace
  paddle/fluid/framework/ir/CMakeLists.txt
  paddle/fluid/framework/ir/graph_pattern_detector.cc
  paddle/fluid/framework/ir/graph_pattern_detector.h
  paddle/fluid/framework/ir/mkldnn/mkldnn_inplace_pass.cc
  paddle/fluid/framework/ir/mkldnn/mkldnn_inplace_pass_tester.cc
  paddle/fluid/operators/elementwise/mkldnn/elementwise_add_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/inplace_op_tests.cmake
  paddle/fluid/operators/mkldnn/softmax_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/test_mkldnn_op_inplace.cc
  paddle/fluid/platform/mkldnn_helper.h
  paddle/fluid/platform/mkldnn_reuse.h
Labels: Intel, inference

#24075 [cherry-pick] [Beta2.0] Add user local data preprocess support (#23692)
  paddle/fluid/inference/tests/api/CMakeLists.txt
  paddle/fluid/inference/tests/api/full_ILSVRC2012_val_preprocess.py
  paddle/fluid/inference/tests/api/full_pascalvoc_test_preprocess.py
Labels: Intel

#24013 declare the stream::Priority as enum class, test=develop
  paddle/fluid/platform/device_context.cc
  paddle/fluid/platform/device_context.h
  paddle/fluid/platform/stream/cuda_stream.cc
  paddle/fluid/platform/stream/cuda_stream.h
Labels: Multi-stream

#23928 QAT: support for new models
  python/paddle/fluid/contrib/slim/quantization/qat2_int8_mkldnn_pass.py
  python/paddle/fluid/contrib/slim/tests/CMakeLists.txt
Labels: Intel

#24080 [cherry-pick] [DNNL] Added elementwise_add mkl-dnn inplace (#23477)
  paddle/fluid/framework/ir/CMakeLists.txt
  paddle/fluid/framework/ir/graph_pattern_detector.cc
  paddle/fluid/framework/ir/graph_pattern_detector.h
  paddle/fluid/framework/ir/mkldnn/mkldnn_inplace_pass.cc
  paddle/fluid/framework/ir/mkldnn/mkldnn_inplace_pass_tester.cc
  paddle/fluid/operators/elementwise/mkldnn/elementwise_add_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/inplace_op_tests.cmake
  paddle/fluid/operators/mkldnn/softmax_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/test_mkldnn_op_inplace.cc
  paddle/fluid/platform/mkldnn_helper.h
  paddle/fluid/platform/mkldnn_reuse.h
Labels: Intel

#24121 [cherry-pick] QAT: support for new models (#23928)
  python/paddle/fluid/contrib/slim/quantization/qat2_int8_mkldnn_pass.py
  python/paddle/fluid/contrib/slim/tests/CMakeLists.txt
Labels: Intel

#23866 added fusing matmul-transpose-reshape pass
  paddle/fluid/framework/ddim.cc
  paddle/fluid/framework/ddim.h
  paddle/fluid/framework/ir/CMakeLists.txt
  paddle/fluid/framework/ir/graph_pattern_detector.cc
  paddle/fluid/framework/ir/graph_pattern_detector.h
  paddle/fluid/framework/ir/mkldnn/matmul_transpose_reshape_fuse_pass.cc
  paddle/fluid/framework/ir/mkldnn/matmul_transpose_reshape_fuse_pass.h
  paddle/fluid/framework/ir/mkldnn/matmul_transpose_reshape_fuse_pass_tester.cc
  paddle/fluid/inference/api/paddle_pass_builder.cc
  paddle/fluid/operators/matmul_op.cc
  paddle/fluid/operators/mkldnn/matmul_mkldnn_op.cc
  python/paddle/fluid/contrib/slim/quantization/qat2_int8_mkldnn_pass.py
  python/paddle/fluid/tests/unittests/ir/inference/test_mkldnn_matmul_op_output_fuse_pass.py
  python/paddle/fluid/tests/unittests/mkldnn/test_matmul_mkldnn_op.py
Labels: Intel

#24123 [DNNL] activations Inplace support
  paddle/fluid/framework/ir/CMakeLists.txt
  paddle/fluid/framework/ir/graph_pattern_detector.cc
  paddle/fluid/framework/ir/mkldnn/mkldnn_inplace_pass.cc
  paddle/fluid/framework/ir/mkldnn/mkldnn_inplace_pass_tester.cc
  paddle/fluid/operators/mkldnn/activation_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/inplace_op_tests.cmake
  paddle/fluid/operators/mkldnn/test_mkldnn_op_inplace.cc
Labels: Intel

#24145 Fixes after PR#24123
  paddle/fluid/framework/ir/mkldnn/mkldnn_inplace_pass_tester.cc
Labels: Intel

#24140 [cherry-pick] [DNNL] Added mkldnn_matmul-transpose-reshape fuse pass (#23866)
  paddle/fluid/framework/ddim.cc
  paddle/fluid/framework/ddim.h
  paddle/fluid/framework/ir/CMakeLists.txt
  paddle/fluid/framework/ir/graph_pattern_detector.cc
  paddle/fluid/framework/ir/graph_pattern_detector.h
  paddle/fluid/framework/ir/mkldnn/matmul_transpose_reshape_fuse_pass.cc
  paddle/fluid/framework/ir/mkldnn/matmul_transpose_reshape_fuse_pass.h
  paddle/fluid/framework/ir/mkldnn/matmul_transpose_reshape_fuse_pass_tester.cc
  paddle/fluid/inference/api/paddle_pass_builder.cc
  paddle/fluid/operators/matmul_op.cc
  paddle/fluid/operators/mkldnn/matmul_mkldnn_op.cc
  python/paddle/fluid/contrib/slim/quantization/qat2_int8_mkldnn_pass.py
  python/paddle/fluid/tests/unittests/ir/inference/test_mkldnn_matmul_op_output_fuse_pass.py
  python/paddle/fluid/tests/unittests/mkldnn/test_matmul_mkldnn_op.py
Labels: Intel

#23754 added reshape transpose matmul fuse pass
  paddle/fluid/framework/ddim.cc
  paddle/fluid/framework/ir/CMakeLists.txt
  paddle/fluid/framework/ir/graph_pattern_detector.cc
  paddle/fluid/framework/ir/graph_pattern_detector.h
  paddle/fluid/framework/ir/mkldnn/reshape_transpose_matmul_mkldnn_fuse_pass.cc
  paddle/fluid/framework/ir/mkldnn/reshape_transpose_matmul_mkldnn_fuse_pass.h
  paddle/fluid/framework/ir/mkldnn/reshape_transpose_matmul_mkldnn_fuse_pass_tester.cc
  paddle/fluid/framework/ir/pass_tester_helper.h
  paddle/fluid/inference/api/paddle_pass_builder.cc
  paddle/fluid/operators/matmul_op.cc
  paddle/fluid/operators/mkldnn/matmul_mkldnn_op.cc
  paddle/fluid/platform/device_context.cc
  python/paddle/fluid/contrib/slim/quantization/qat2_int8_mkldnn_pass.py
  python/paddle/fluid/tests/unittests/mkldnn/test_matmul_mkldnn_op.py
Labels: Intel

#24127 Update QAT INT8 2.0 doc
  paddle/fluid/inference/tests/api/int8_mkldnn_quantization.md
  python/paddle/fluid/contrib/slim/tests/QAT_mkldnn_int8_readme.md
Labels: Intel

#24046 update the analysis predictor for multi-stream support, test=develop
  paddle/fluid/inference/api/analysis_config.cc
  paddle/fluid/inference/api/analysis_predictor.cc
  paddle/fluid/inference/api/demo_ci/utils.h
  paddle/fluid/inference/api/paddle_analysis_config.h
  paddle/fluid/inference/tests/api/lite_mul_model_test.cc
  paddle/fluid/inference/tests/api/tester_helper.h
  paddle/fluid/platform/init.cc
  paddle/fluid/platform/init.h
Labels: Multi-stream

#24143 [INT8] Add requant-op squash
  paddle/fluid/framework/ir/graph_pattern_detector.cc
  paddle/fluid/framework/ir/graph_pattern_detector.h
  paddle/fluid/framework/ir/mkldnn/cpu_quantize_squash_pass.cc
  paddle/fluid/framework/ir/mkldnn/cpu_quantize_squash_pass.h
  paddle/fluid/framework/ir/mkldnn/cpu_quantize_squash_pass_tester.cc
Labels: Intel

#24248 [cherry-pick]Update QAT INT8 1.8 doc (#24127)
  paddle/fluid/inference/tests/api/int8_mkldnn_quantization.md
  python/paddle/fluid/contrib/slim/tests/QAT_mkldnn_int8_readme.md
Labels: Intel
