Repository PaddlePaddle/Paddle, pull requests merged in 2020-11, with the labels that each got.

#28318 [oneDNN] sum op refactor
  paddle/fluid/operators/mkldnn/sum_mkldnn_op.cc
  paddle/fluid/platform/mkldnn_reuse.h
  python/paddle/fluid/tests/unittests/mkldnn/test_sum_mkldnn_op.py
Labels: Intel

#28278 Add conv_bias pass version python test
  paddle/fluid/framework/ir/mkldnn/conv_bias_mkldnn_fuse_pass.cc
  python/paddle/fluid/tests/unittests/ir/inference/test_conv_bias_mkldnn_fuse_pass.py
Labels: Intel

#28382 [oneDNN]Sum bf16 kernel
  paddle/fluid/framework/ir/graph_pattern_detector.cc
  paddle/fluid/framework/ir/mkldnn/cpu_bfloat16_placement_pass_tester.cc
  paddle/fluid/operators/mkldnn/sum_mkldnn_op.cc
  paddle/fluid/operators/sum_op.cc
  python/paddle/fluid/tests/unittests/mkldnn/test_sum_bf16_mkldnn_op.py
  tools/static_mode_white_list.py
Labels: BF16, Intel

#28394 Add bfloat16 softmax and gelu
  paddle/fluid/framework/ir/graph_pattern_detector.cc
  paddle/fluid/framework/ir/mkldnn/cpu_bfloat16_placement_pass_tester.cc
  paddle/fluid/inference/analysis/ir_pass_manager.cc
  paddle/fluid/operators/gelu_op.cc
  paddle/fluid/operators/mkldnn/activation_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/softmax_mkldnn_op.cc
  paddle/fluid/operators/softmax_op.cc
  python/paddle/fluid/tests/unittests/mkldnn/test_activation_mkldnn_op.py
  python/paddle/fluid/tests/unittests/mkldnn/test_softmax_bf16_mkldnn_op.py
  tools/static_mode_white_list.py
Labels: BF16, Intel

#28475 [Fix bug] If the pass name is not found, IsCompatible should return false
  paddle/fluid/framework/ir/mkldnn/conv_bias_mkldnn_fuse_pass.cc
  paddle/fluid/framework/ir/quant_conv2d_dequant_fuse_pass.cc
  paddle/fluid/framework/op_version_registry.h
  paddle/fluid/framework/op_version_registry_test.cc
  python/paddle/fluid/tests/unittests/ir/inference/test_mkldnn_conv_bias_fuse_pass.py
Labels: Intel

#28354 Op version python mkldnn_inplace test
  paddle/fluid/framework/ir/mkldnn/mkldnn_inplace_pass.cc
  python/paddle/fluid/tests/unittests/ir/inference/test_mkldnn_inplace_fuse_pass.py
  tools/static_mode_white_list.py
Labels: Intel

#28612 Add checkpoint to quantize
  paddle/fluid/framework/ir/mkldnn/cpu_bfloat16_pass.cc
  paddle/fluid/operators/quantize_op.cc
  python/paddle/fluid/tests/unittests/ir/inference/inference_pass_test.py
  python/paddle/fluid/tests/unittests/ir/inference/test_mkldnn_cpu_bfloat16_pass.py
Labels: Intel

#28619 [oneDNN] Layer norm bf16 kernel
  paddle/fluid/framework/ir/graph_pattern_detector.cc
  paddle/fluid/operators/layer_norm_op.cc
  paddle/fluid/operators/mkldnn/layer_norm_mkldnn_op.cc
  paddle/fluid/platform/mkldnn_reuse.h
  python/paddle/fluid/tests/unittests/mkldnn/test_layer_norm_bf16_mkldnn_op.py
  python/paddle/fluid/tests/unittests/mkldnn/test_layer_norm_mkldnn_op.py
  python/paddle/fluid/tests/unittests/mkldnn/test_sum_bf16_mkldnn_op.py
  python/paddle/fluid/tests/unittests/test_layer_norm_op.py
  tools/static_mode_white_list.py
Labels: BF16, Intel

#28591 Add multi_gru op and tests
  paddle/fluid/operators/fused/mkldnn/multi_gru_mkldnn_op.cc
  paddle/fluid/operators/fused/multi_gru_op.cc
  paddle/fluid/operators/fused/multi_gru_op.h
  python/paddle/fluid/tests/unittests/mkldnn/test_multi_gru_mkldnn_op.py
  tools/static_mode_white_list.py
Labels: Intel, int8

#28729 Add bf16 matmul, fc, elementwise add and mul
  paddle/fluid/framework/ir/graph_pattern_detector.cc
  paddle/fluid/framework/ir/mkldnn/cpu_bfloat16_placement_pass_tester.cc
  paddle/fluid/operators/elementwise/mkldnn/elementwise_add_mkldnn_op.cc
  paddle/fluid/operators/elementwise/mkldnn/elementwise_mul_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/fc_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/matmul_mkldnn_op.cc
  python/paddle/fluid/tests/unittests/ir/inference/test_mkldnn_cpu_bfloat16_pass.py
  python/paddle/fluid/tests/unittests/mkldnn/test_elementwise_add_bf16_mkldnn_op.py
  python/paddle/fluid/tests/unittests/mkldnn/test_elementwise_mul_bf16_mkldnn_op.py
  python/paddle/fluid/tests/unittests/mkldnn/test_fc_bf16_mkldnn_op.py
  python/paddle/fluid/tests/unittests/mkldnn/test_matmul_bf16_mkldnn_op.py
  tools/static_mode_white_list.py
Labels: BF16, Intel

#28758 [oneDNN] Fix to issue #28459
  paddle/fluid/framework/executor.cc
  paddle/fluid/framework/naive_executor.cc
  paddle/fluid/operators/mkldnn/concat_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/fc_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/matmul_mkldnn_op.cc
  paddle/fluid/platform/device_context.h
  paddle/fluid/platform/mkldnn_helper.h
  paddle/fluid/platform/mkldnn_reuse.h
Labels: Intel

#28604 Add multi_gru_seq_fuse_pass and tests
  paddle/fluid/framework/ir/CMakeLists.txt
  paddle/fluid/framework/ir/graph_pattern_detector.cc
  paddle/fluid/framework/ir/graph_pattern_detector.h
  paddle/fluid/framework/ir/mkldnn/multi_gru_seq_fuse_pass.cc
  paddle/fluid/framework/ir/mkldnn/multi_gru_seq_fuse_pass.h
  paddle/fluid/framework/ir/mkldnn/multi_gru_seq_fuse_pass_tester.cc
  tools/static_mode_white_list.py
Labels: Intel, int8

#29039 Add bf16 pool2d and unify bf16 unit tests
  paddle/fluid/framework/ir/graph_pattern_detector.cc
  paddle/fluid/framework/ir/mkldnn/cpu_bfloat16_placement_pass_tester.cc
  paddle/fluid/operators/mkldnn/pool_mkldnn_op.cc
  python/paddle/fluid/tests/unittests/mkldnn/test_concat_bf16_mkldnn_op.py
  python/paddle/fluid/tests/unittests/mkldnn/test_pool2d_bf16_mkldnn_op.py
  python/paddle/fluid/tests/unittests/mkldnn/test_reshape_bf16_op.py
  python/paddle/fluid/tests/unittests/mkldnn/test_softmax_bf16_mkldnn_op.py
  python/paddle/fluid/tests/unittests/mkldnn/test_transpose_bf16_mkldnn_op.py
  tools/static_mode_white_list.py
Labels: BF16, Intel

#28988 Fixes mkldnn dygraph learning rate scheduler crashes
  paddle/fluid/framework/operator.cc
  paddle/fluid/framework/operator.h
  paddle/fluid/operators/activation_op.cc
  paddle/fluid/operators/addmm_op.cc
  paddle/fluid/operators/batch_norm_op.cc
  paddle/fluid/operators/concat_op.cc
  paddle/fluid/operators/conv_op.cc
  paddle/fluid/operators/conv_transpose_op.cc
  paddle/fluid/operators/data_norm_op.cc
  paddle/fluid/operators/detection/prior_box_op.cc
  paddle/fluid/operators/elementwise/elementwise_div_op.h
  paddle/fluid/operators/elementwise/elementwise_mul_op.h
  paddle/fluid/operators/elementwise/elementwise_op.h
  paddle/fluid/operators/fused/fusion_gru_op.cc
  paddle/fluid/operators/gaussian_random_op.cc
  paddle/fluid/operators/gelu_op.cc
  paddle/fluid/operators/layer_norm_op.cc
  paddle/fluid/operators/lrn_op.cc
  paddle/fluid/operators/matmul_op.cc
  paddle/fluid/operators/mul_op.cc
  paddle/fluid/operators/pool_op.cc
  paddle/fluid/operators/softmax_op.cc
  paddle/fluid/operators/sum_op.cc
  paddle/fluid/operators/transpose_op.cc
  paddle/fluid/platform/mkldnn_helper.h
Labels: Intel, dygraph

#28615 Add quantization of multi_gru op and tests
  paddle/fluid/framework/ir/graph_pattern_detector.cc
  paddle/fluid/framework/ir/graph_pattern_detector.h
  paddle/fluid/framework/ir/mkldnn/cpu_quantize_pass.cc
  paddle/fluid/framework/ir/mkldnn/cpu_quantize_pass.h
  paddle/fluid/framework/ir/mkldnn/cpu_quantize_pass_tester.cc
  python/paddle/fluid/contrib/slim/quantization/quant2_int8_mkldnn_pass.py
  python/paddle/fluid/contrib/slim/tests/CMakeLists.txt
Labels: Intel, int8

#29155 Enable BF16 models test for googlenet, mobiletnetv1 and mobilenetv2
  paddle/fluid/inference/tests/api/CMakeLists.txt
  paddle/fluid/inference/tests/api/analyzer_bfloat16_image_classification_tester.cc
Labels: BF16, Intel

#29188 oneDNN conv2d kernel- optimize memory descriptors.
  paddle/fluid/operators/mkldnn/conv_mkldnn_op.cc
Labels: Intel
