Repository PaddlePaddle/Paddle, pull requests merged in 2020-10, with the labels that each got.

#27518 Added support for quantization of fusion_gru
  cmake/external/mkldnn.cmake
  paddle/fluid/framework/ir/graph_pattern_detector.cc
  paddle/fluid/framework/ir/graph_pattern_detector.h
  paddle/fluid/framework/ir/mkldnn/cpu_quantize_pass.cc
  paddle/fluid/framework/ir/mkldnn/cpu_quantize_pass.h
  paddle/fluid/framework/ir/mkldnn/cpu_quantize_pass_tester.cc
  paddle/fluid/framework/ir/mkldnn/cpu_quantize_squash_pass.cc
  paddle/fluid/operators/fused/mkldnn/fusion_gru_mkldnn_op.cc
  python/paddle/fluid/contrib/slim/quantization/quant2_int8_mkldnn_pass.py
  python/paddle/fluid/contrib/slim/tests/CMakeLists.txt
  python/paddle/fluid/tests/unittests/mkldnn/test_fusion_gru_int8_mkldnn_op.py
Labels: Intel, int8

#27546 Fix to issue #25537
  paddle/fluid/framework/data_layout_transform.cc
  paddle/fluid/operators/CMakeLists.txt
  paddle/fluid/operators/mkldnn/nhwc_op_tests.cmake
  paddle/fluid/operators/mkldnn/test_mkldnn_op_nhwc.cc
  paddle/fluid/operators/transpose_op.cc
  paddle/fluid/platform/mkldnn_helper.h
Labels: Intel

#27739 Add an option to set number of warmup iterations
  paddle/fluid/inference/tests/api/tester_helper.h
Labels: Intel

#27750 Add avx512 core instructions check 2
  python/paddle/fluid/tests/unittests/mkldnn/test_conv2d_bf16_mkldnn_op.py
Labels: BF16, Intel

#27731 [oneDNN] GRU BF16 kernel
  paddle/fluid/framework/ir/graph_pattern_detector.cc
  paddle/fluid/operators/fused/mkldnn/fusion_gru_mkldnn_op.cc
  python/paddle/fluid/tests/unittests/mkldnn/test_fusion_gru_bf16_mkldnn_op.py
Labels: BF16, Intel, inference

#27770 [oneDNN] Second fix to 27398
  paddle/fluid/framework/data_transform.cc
  paddle/fluid/framework/tensor_util.cc
Labels: Intel

#25132 use IndexList to improve performance of instance_norm op
  paddle/fluid/operators/instance_norm_op.cc
Labels: Eigen

#27747 [oneDNN] adaptive pool support
  paddle/fluid/operators/mkldnn/pool_mkldnn_op.cc
  paddle/fluid/platform/mkldnn_reuse.h
  python/paddle/fluid/tests/unittests/mkldnn/test_pool2d_mkldnn_op.py
Labels: Intel

#27954 Fix problem with flags fp32 and int8
  paddle/fluid/inference/tests/api/CMakeLists.txt
  paddle/fluid/inference/tests/api/tester_helper.h
Labels: Intel

#27914 [oneDNN] Conv dilation support
  paddle/fluid/framework/ir/mkldnn/conv_bias_mkldnn_fuse_pass.cc
  paddle/fluid/operators/mkldnn/conv_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/conv_transpose_mkldnn_op.cc
  paddle/fluid/platform/mkldnn_reuse.h
  python/paddle/fluid/tests/unittests/mkldnn/test_conv2d_bf16_mkldnn_op.py
  python/paddle/fluid/tests/unittests/mkldnn/test_conv2d_int8_mkldnn_op.py
  python/paddle/fluid/tests/unittests/mkldnn/test_conv2d_mkldnn_op.py
  python/paddle/fluid/tests/unittests/mkldnn/test_conv2d_transpose_mkldnn_op.py
Labels: Intel

#28028 [Cherry-pick] oneDNN Conv dilation support (#27914)
  paddle/fluid/framework/ir/mkldnn/conv_bias_mkldnn_fuse_pass.cc
  paddle/fluid/operators/mkldnn/conv_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/conv_transpose_mkldnn_op.cc
  paddle/fluid/platform/mkldnn_reuse.h
  python/paddle/fluid/tests/unittests/mkldnn/test_conv2d_bf16_mkldnn_op.py
  python/paddle/fluid/tests/unittests/mkldnn/test_conv2d_int8_mkldnn_op.py
  python/paddle/fluid/tests/unittests/mkldnn/test_conv2d_mkldnn_op.py
  python/paddle/fluid/tests/unittests/mkldnn/test_conv2d_transpose_mkldnn_op.py
Labels: Intel

#28087 Add AVX512 instruction check for C-API
  paddle/fluid/inference/api/analysis_config.cc
Labels: BF16, Intel

#28147 [Cherry-pick] Remove unnecessary attrs copy
  paddle/fluid/imperative/prepared_operator.cc
Labels: Intel

#28146 remove unnecessary attrs copy
  paddle/fluid/imperative/prepared_operator.cc
Labels: Intel

#27912 oneDNN BatchNorm + Act fusion pass.
  paddle/fluid/framework/ir/CMakeLists.txt
  paddle/fluid/framework/ir/graph_pattern_detector.cc
  paddle/fluid/framework/ir/graph_pattern_detector.h
  paddle/fluid/framework/ir/mkldnn/batch_norm_act_fuse_pass.cc
  paddle/fluid/framework/ir/mkldnn/batch_norm_act_fuse_pass.h
  paddle/fluid/framework/ir/mkldnn/batch_norm_act_fuse_pass_tester.cc
  paddle/fluid/inference/api/paddle_pass_builder.cc
  python/paddle/fluid/tests/unittests/ir/inference/test_mkldnn_batch_norm_act_fuse_pass.py
Labels: Intel

#27871 [oneDNN ] conv2d fwd&bwd optimization
  paddle/fluid/operators/mkldnn/conv_mkldnn_op.cc
  paddle/fluid/platform/mkldnn_helper.h
  paddle/fluid/platform/mkldnn_reuse.h
  python/paddle/fluid/tests/unittests/mkldnn/test_conv2d_bf16_mkldnn_op.py
  python/paddle/fluid/tests/unittests/mkldnn/test_conv2d_mkldnn_op.py
  python/paddle/fluid/tests/unittests/mkldnn/test_fusion_gru_bf16_mkldnn_op.py
  python/paddle/fluid/tests/unittests/op_test.py
Labels: Intel, dygraph

#28233 [oneDNN] sum primitive to respect diffrent memory formats of inputs
  paddle/fluid/operators/mkldnn/sum_mkldnn_op.cc
Labels: Intel, dygraph

#28288 fix conv mkldnn build error
  paddle/fluid/operators/mkldnn/conv_mkldnn_op.cc
Labels: Intel

#28195 Add bf16 transpose2, reshape2, concat ops
  paddle/fluid/framework/ir/graph_pattern_detector.cc
  paddle/fluid/framework/ir/mkldnn/cpu_bfloat16_placement_pass_tester.cc
  paddle/fluid/operators/mkldnn/concat_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/transpose_mkldnn_op.cc
  paddle/fluid/operators/reshape_op.cc
  python/paddle/fluid/tests/unittests/mkldnn/test_concat_bf16_mkldnn_op.py
  python/paddle/fluid/tests/unittests/mkldnn/test_reshape_bf16_op.py
  python/paddle/fluid/tests/unittests/mkldnn/test_transpose_bf16_mkldnn_op.py
Labels: BF16, Intel

#28313 Enable GRU infer model running CAPI
  paddle/fluid/inference/tests/api/analyzer_lexical_analysis_gru_tester.cc
Labels: Intel
