Repository PaddlePaddle/Paddle, pull requests merged in 2021-11, with the labels that each got.

#36711 Correct conv2d int8 mkldnn UT
  paddle/fluid/pybind/pybind.cc
  python/paddle/fluid/tests/unittests/mkldnn/test_conv2d_int8_mkldnn_op.py
Labels: Intel, int8

#36869 [Need review] Added conv + hard_sigmoid oneDNN fuse pass
  paddle/fluid/framework/ir/mkldnn/conv_activation_mkldnn_fuse_pass.cc
  paddle/fluid/framework/ir/mkldnn/conv_activation_mkldnn_fuse_pass.h
  paddle/fluid/framework/ir/mkldnn/conv_activation_mkldnn_fuse_pass_tester.cc
  paddle/fluid/inference/api/paddle_pass_builder.cc
  paddle/fluid/operators/compat/hard_sigmoid.pbtxt
  paddle/fluid/operators/mkldnn/conv_mkldnn_op.cc
  python/paddle/fluid/tests/unittests/ir/inference/test_mkldnn_conv_activation_fuse_pass.py
Labels: Intel

#36917 [Need review] Optimized and refactored oneDNN layer_norm kernel
  paddle/fluid/operators/mkldnn/layer_norm_mkldnn_op.cc
Labels: Intel

#36695 Disable pool&conv_transpose&quantize caching
  paddle/fluid/operators/fused/mkldnn/fusion_gru_mkldnn_op.cc
  paddle/fluid/operators/fused/mkldnn/fusion_lstm_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/conv_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/conv_transpose_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/pool_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/quantize_mkldnn_op.cc
  paddle/fluid/platform/mkldnn_reuse.h
  python/paddle/fluid/tests/unittests/mkldnn/test_conv3d_mkldnn_op.py
Labels: Intel

#36980 Added caching of scales for bias in conv2d int8
  paddle/fluid/operators/mkldnn/conv_mkldnn_op.cc
Labels: Intel

#37002 Added stack FP32 FWD oneDNN kernel
  paddle/fluid/operators/mkldnn/stack_mkldnn_op.cc
  paddle/fluid/operators/stack_op.cc
  paddle/fluid/platform/mkldnn_helper.h
  python/paddle/fluid/tests/unittests/mkldnn/test_stack_mkldnn_op.py
  python/paddle/fluid/tests/unittests/op_test.py
Labels: Intel

#37078 Enable FC int8
  paddle/fluid/inference/tests/api/analyzer_int8_image_classification_tester.cc
Labels: Intel, int8

#36657 Added softplus + activation oneDNN fuse pass
  paddle/fluid/framework/ir/CMakeLists.txt
  paddle/fluid/framework/ir/graph_pattern_detector.cc
  paddle/fluid/framework/ir/graph_pattern_detector.h
  paddle/fluid/framework/ir/mkldnn/softplus_activation_mkldnn_fuse_pass.cc
  paddle/fluid/framework/ir/mkldnn/softplus_activation_mkldnn_fuse_pass.h
  paddle/fluid/framework/ir/mkldnn/softplus_activation_mkldnn_fuse_pass_tester.cc
  paddle/fluid/inference/api/paddle_pass_builder.cc
  paddle/fluid/operators/activation_op.cc
  paddle/fluid/operators/mkldnn/softplus_mkldnn_op.h
  python/paddle/fluid/tests/unittests/ir/inference/test_mkldnn_softplus_activation_fuse_pass.py
Labels: Intel

#37104 Added BF16 to mean op
  paddle/fluid/operators/mean_op.cc
  paddle/pten/kernels/cpu/math.cc
  python/paddle/fluid/tests/book/test_fit_a_line.py
  python/paddle/fluid/tests/unittests/test_mean_op.py
Labels: Intel, BF16

#37149 Added ELU FP32 FWD/BWD oneDNN kernel
  paddle/fluid/operators/activation_op.cc
  paddle/fluid/operators/mkldnn/activation_mkldnn_op.cc
  python/paddle/fluid/tests/unittests/mkldnn/test_activation_mkldnn_op.py
Labels: Intel

#37081 Added BF16 Pool2d grad
  paddle/fluid/operators/mkldnn/pool_mkldnn_op.cc
  python/paddle/fluid/tests/unittests/mkldnn/test_pool2d_bf16_mkldnn_op.py
  python/paddle/fluid/tests/unittests/test_pool2d_op.py
Labels: Intel, BF16

#36226 Upgrade oneDNN to v2.4.4
  cmake/external/mkldnn.cmake
Labels: Intel

#37040 Changed first batch of deprecated mkldnn headers and function names to new oneDNN names
  paddle/fluid/framework/data_layout_transform.cc
  paddle/fluid/framework/data_layout_transform.h
  paddle/fluid/framework/data_layout_transform_test.cc
  paddle/fluid/framework/data_type_transform_test.cc
  paddle/fluid/operators/elementwise/mkldnn/elementwise_mkldnn_op.h
  paddle/fluid/operators/fused/mkldnn/fusion_lstm_mkldnn_op.cc
  paddle/fluid/operators/fused/mkldnn/fusion_rnn_mkldnn.h
  paddle/fluid/operators/mkldnn/axpy_handler.cc
  paddle/fluid/operators/mkldnn/dequantize_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/quantize_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/requantize_mkldnn_op.cc
  paddle/fluid/platform/mkldnn_helper.h
  paddle/fluid/platform/mkldnn_reuse.h
Labels: Intel

#37175 Replace custom IOHW -> OIHW reorder with build-in oneDNN reorder
  paddle/fluid/operators/mkldnn/conv_transpose_mkldnn_op.cc
Labels: Intel

#37310 Fix for wrong results in segmentation models
  paddle/fluid/platform/mkldnn_helper.h
Labels: Intel

#37352 Add corner case in PTQ scale calculation
  paddle/fluid/inference/api/mkldnn_quantizer.cc
Labels: Intel, int8

#37351 Changed second batch of deprecated mkldnn header and function names to new oneDNN names
  paddle/fluid/framework/tensor.h
  paddle/fluid/operators/mkldnn/activation_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/batch_norm_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/clip_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/concat_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/conv_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/conv_transpose_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/fc_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/lrn_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/matmul_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/mul_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/pool_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/scale_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/softmax_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/stack_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/sum_mkldnn_op.cc
  paddle/fluid/platform/device_context.cc
  paddle/fluid/platform/device_context.h
  paddle/fluid/platform/mkldnn_helper.h
Labels: Intel

#37622 refactoring matmul_v2 mkldnn hierarchy
  paddle/fluid/operators/mkldnn/matmul_v2_mkldnn_op.cc
Labels: Intel
