Repository PaddlePaddle/Paddle, pull requests merged in 2021-01, with the labels that each got.

#30191 Fix analysis predictor test
  paddle/fluid/inference/api/analysis_predictor_tester.cc
  tools/windows/run_unittests.sh
Labels: BF16, Intel

#30164 Disable mkldnn inplace pass on windows
  paddle/fluid/inference/api/paddle_pass_builder.cc
Labels: Intel

#30203 [oneDNN] Added UT for testing elementwise_mul caching
  paddle/fluid/operators/mkldnn/caching_tests.cmake
  paddle/fluid/operators/mkldnn/test_mkldnn_caching.cc
  paddle/fluid/platform/mkldnn_reuse.h
Labels: Intel

#30295 Wojtuss/upgrade one dnn 2.0
  cmake/external/mkldnn.cmake
  cmake/inference_lib.cmake
  python/paddle/fluid/tests/unittests/mkldnn/test_flags_mkldnn_ops_on_off.py
  python/setup.py.in
Labels: Intel

#30326 Change PADDLE_ENFORCE dimension size
  paddle/fluid/operators/mkldnn/activation_mkldnn_op.cc
Labels: Intel

#30128 Skip some conv2d_int8 tests in windows
  python/paddle/fluid/tests/unittests/mkldnn/test_conv2d_int8_mkldnn_op.py
  tools/windows/run_unittests.sh
Labels: Intel

#30433 [cherry-pick] correct the allowed dimension size (#30326)
  paddle/fluid/operators/mkldnn/activation_mkldnn_op.cc
Labels: Intel

#30404 fix cache key for inplaced elementwise ops
  paddle/fluid/operators/elementwise/mkldnn/elementwise_mkldnn_op.h
Labels: Intel

#30478 [cherry-pick] fix cache key for inplaced elementwise ops (#30404)
  paddle/fluid/operators/elementwise/mkldnn/elementwise_mkldnn_op.h
Labels: Intel

#30588 [oneDNN] Disabling oneDNN inplace pass
  paddle/fluid/inference/api/paddle_pass_builder.cc
  paddle/fluid/operators/mkldnn/activation_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/softmax_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/test_mkldnn_caching.cc
  paddle/fluid/platform/mkldnn_reuse.h
Labels: Intel

#30623 revert external gflags, test=develop
  cmake/external/gflags.cmake
  paddle/fluid/inference/check_symbol.sh
  paddle/fluid/inference/paddle_fluid.map
Labels: Google Flags

#30358 [oneDNN] Cache oneDNN stream not to recreate in each oneDNN op
  paddle/fluid/framework/data_layout_transform.cc
  paddle/fluid/operators/elementwise/mkldnn/elementwise_add_mkldnn_op.cc
  paddle/fluid/operators/elementwise/mkldnn/elementwise_mkldnn_op.h
  paddle/fluid/operators/fused/mkldnn/fusion_gru_mkldnn_op.cc
  paddle/fluid/operators/fused/mkldnn/multi_gru_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/activation_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/batch_norm_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/concat_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/conv_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/conv_transpose_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/dequantize_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/fc_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/interpolate_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/layer_norm_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/lrn_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/mul_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/pool_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/quantize_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/requantize_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/softmax_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/sum_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/transpose_mkldnn_op.cc
  paddle/fluid/platform/device_context.cc
  paddle/fluid/platform/device_context.h
  paddle/fluid/platform/mkldnn_helper.h
  paddle/fluid/platform/mkldnn_reuse.h
Labels: Intel

#29840 More precise mkldnn kernel rules in GetExpectedKernelType
  paddle/fluid/framework/operator.cc
  paddle/fluid/framework/operator.h
  paddle/fluid/operators/activation_op.cc
  paddle/fluid/operators/addmm_op.cc
  paddle/fluid/operators/batch_norm_op.cc
  paddle/fluid/operators/concat_op.cc
  paddle/fluid/operators/conv_op.cc
  paddle/fluid/operators/conv_transpose_op.cc
  paddle/fluid/operators/data_norm_op.cc
  paddle/fluid/operators/detection/prior_box_op.cc
  paddle/fluid/operators/elementwise/elementwise_div_op.h
  paddle/fluid/operators/elementwise/elementwise_mul_op.h
  paddle/fluid/operators/elementwise/elementwise_op.h
  paddle/fluid/operators/fused/fusion_gru_op.cc
  paddle/fluid/operators/gaussian_random_op.cc
  paddle/fluid/operators/gelu_op.cc
  paddle/fluid/operators/interpolate_op.cc
  paddle/fluid/operators/layer_norm_op.cc
  paddle/fluid/operators/lrn_op.cc
  paddle/fluid/operators/matmul_op.cc
  paddle/fluid/operators/mul_op.cc
  paddle/fluid/operators/pool_op.cc
  paddle/fluid/operators/softmax_op.cc
  paddle/fluid/operators/sum_op.cc
  paddle/fluid/operators/transpose_op.cc
Labels: Intel

#30708 Revert "Added vanilla LSTM and LSTM with peepholes oneDNN fp32 kernel"
  cmake/operators.cmake
  paddle/fluid/operators/fused/CMakeLists.txt
  paddle/fluid/operators/fused/fusion_lstm_op.cc
  paddle/fluid/operators/fused/mkldnn/fusion_gru_mkldnn_op.cc
  paddle/fluid/operators/fused/mkldnn/fusion_lstm_mkldnn_op.cc
  paddle/fluid/operators/fused/mkldnn/fusion_rnn_mkldnn.h
  python/paddle/fluid/tests/unittests/mkldnn/test_fusion_gru_mkldnn_op.py
  python/paddle/fluid/tests/unittests/mkldnn/test_fusion_lstm_mkldnn_op.py
  python/paddle/fluid/tests/unittests/test_fusion_gru_op.py
  python/paddle/fluid/tests/unittests/test_fusion_lstm_op.py
  python/paddle/fluid/tests/unittests/white_list/no_check_set_white_list.py
  tools/static_mode_white_list.py
Labels: Intel

#30698 Fix python3 incompatibility issues
  paddle/fluid/inference/tests/api/full_ILSVRC2012_val_preprocess.py
Labels: Intel

#30723 A fix for oneDNN matmul kernel. Fixes issue #30309
  paddle/fluid/operators/mkldnn/matmul_mkldnn_op.cc
  python/paddle/fluid/tests/unittests/mkldnn/test_matmul_mkldnn_op.py
Labels: Intel
