Repository PaddlePaddle/Paddle, pull requests merged in 2021-12, with the labels that each got.

#37618 dequantize matmul and matmul_v2 Y weights in quant2_int8
  python/paddle/fluid/contrib/slim/quantization/quant2_int8_mkldnn_pass.py
  python/paddle/fluid/contrib/slim/tests/test_quant2_int8_mkldnn_pass.py
Labels: Intel

#37630 Quantize slice op
  paddle/fluid/framework/ir/graph_pattern_detector.cc
  paddle/fluid/framework/ir/graph_pattern_detector.h
  paddle/fluid/framework/ir/mkldnn/cpu_quantize_pass.cc
  paddle/fluid/framework/ir/mkldnn/cpu_quantize_pass.h
  paddle/fluid/framework/ir/mkldnn/cpu_quantize_pass_tester.cc
  paddle/fluid/inference/api/mkldnn_quantizer.cc
  paddle/fluid/inference/api/mkldnn_quantizer_config.cc
  paddle/fluid/inference/tests/api/CMakeLists.txt
  paddle/fluid/inference/tests/api/analyzer_ernie_int8_tester.cc
  paddle/fluid/inference/tests/api/analyzer_ernie_tester.cc
  paddle/fluid/inference/tests/api/analyzer_ernie_tester.h
  paddle/fluid/operators/mkldnn/slice_mkldnn_op.cc
  paddle/fluid/operators/slice_op.cc
  python/paddle/fluid/contrib/slim/quantization/quant2_int8_mkldnn_pass.py
  python/paddle/fluid/contrib/slim/tests/CMakeLists.txt
Labels: Intel, int8

#38023 add map_matmul and fc_act_fuse passes to quant2_int8_mkldnn_pass
  paddle/fluid/operators/mkldnn/fc_mkldnn_op.cc
  python/paddle/fluid/contrib/slim/quantization/quant2_int8_mkldnn_pass.py
Labels: Intel

#37848 Faster implementation of CPU kernel for ROI Align operator
  paddle/fluid/operators/roi_align_op.cu
  paddle/fluid/operators/roi_align_op.h
Labels: Intel

#38225 fix use of implicitly deleted constructor
  paddle/fluid/operators/mkldnn/matmul_mkldnn_op.cc
Labels: Intel

#38176 Fix for elementwise_add_grad GetExpectedKernelType function
  paddle/fluid/operators/elementwise/elementwise_op.h
Labels: Intel

#37985 Add int8 nearest_interp and nearest_interp_v2
  paddle/fluid/operators/mkldnn/interpolate_mkldnn_op.cc
  python/paddle/fluid/tests/unittests/mkldnn/test_nearest_interp_mkldnn_op.py
  python/paddle/fluid/tests/unittests/mkldnn/test_nearest_interp_v2_mkldnn_op.py
Labels: Intel, int8

#38336 Make GetBlob assuming elements are cached
  paddle/fluid/framework/data_transform.cc
  paddle/fluid/operators/mkldnn/conv_mkldnn_op.cc
  paddle/fluid/platform/device_context.cc
Labels: Intel

#38507 Added Conv2D BF16 BWD oneDNN kernel
  paddle/fluid/operators/mkldnn/conv_mkldnn_op.cc
  python/paddle/fluid/tests/unittests/mkldnn/test_conv2d_bf16_mkldnn_op.py
Labels: Intel, BF16

#38019 Refactor cpu_quantize_pass_tester
  paddle/fluid/framework/ir/mkldnn/cpu_quantize_pass_tester.cc
Labels: Intel

#38553 Fix for undefined format for 6 dim tensor
  paddle/fluid/platform/mkldnn_helper.h
Labels: Intel

#38554 Fix for MKLDNNDeviceContext error in matmul_v2_transpose_reshape fuse pass when GLOG_v set
  paddle/fluid/inference/api/analysis_predictor.cc
Labels: Intel
