Repository PaddlePaddle/Paddle, pull requests merged in 2021-03, with the labels that each got.

#31348 [cherry-pick] Modify relu native implementation 2 (#30996)
  cmake/cuda.cmake
  paddle/fluid/operators/activation_op.cc
  paddle/fluid/operators/activation_op.cu
  paddle/fluid/operators/activation_op.h
  paddle/fluid/operators/fused/fused_bn_activation_op.cu
  paddle/fluid/operators/gru_unit_op.h
  paddle/fluid/operators/lstmp_op.h
  paddle/fluid/operators/rnn_op.h
Labels: Intel

#31234 Added LSTM BF16 and fixed GRU BF16
  paddle/fluid/operators/fused/fusion_lstm_op.cc
  paddle/fluid/operators/fused/mkldnn/fusion_gru_mkldnn_op.cc
  paddle/fluid/operators/fused/mkldnn/fusion_lstm_mkldnn_op.cc
  paddle/fluid/operators/fused/mkldnn/fusion_rnn_mkldnn.h
  python/paddle/fluid/tests/unittests/mkldnn/test_fusion_gru_bf16_mkldnn_op.py
  python/paddle/fluid/tests/unittests/mkldnn/test_fusion_gru_int8_mkldnn_op.py
  python/paddle/fluid/tests/unittests/mkldnn/test_fusion_lstm_bf16_mkldnn_op.py
  python/paddle/fluid/tests/unittests/op_test.py
  tools/static_mode_white_list.py
Labels: Intel

#31385 [oneDNN] elementwise add bf16 grad kernel with broadcasting
  paddle/fluid/operators/elementwise/elementwise_op.h
  paddle/fluid/operators/elementwise/mkldnn/elementwise_add_mkldnn_op.cc
  paddle/fluid/platform/mkldnn_reuse.h
  python/paddle/fluid/tests/unittests/mkldnn/test_elementwise_add_bf16_mkldnn_op.py
  python/paddle/fluid/tests/unittests/mkldnn/test_elementwise_add_mkldnn_op.py
  python/paddle/fluid/tests/unittests/mkldnn/test_reshape_bf16_op.py
  python/paddle/fluid/tests/unittests/op_test.py
Labels: BF16, Intel

#31482 [Bug fix] Different machine generate different binary file, remove md5 check
  paddle/fluid/inference/tests/api/full_ILSVRC2012_val_preprocess.py
Labels: Intel

#31270 cherry-pick #30295 and #31347: Upgrade oneDNN 2.2
  cmake/external/mkldnn.cmake
  cmake/inference_lib.cmake
  python/paddle/fluid/tests/unittests/mkldnn/test_flags_mkldnn_ops_on_off.py
  python/setup.py.in
Labels: Intel

#31558 [oneDNN] lookup_table op with support for BF16 data type.
  paddle/fluid/framework/ir/mkldnn/cpu_bfloat16_placement_pass.cc
  paddle/fluid/framework/ir/mkldnn/cpu_bfloat16_placement_pass.h
  paddle/fluid/operators/lookup_table_op.cc
  paddle/fluid/operators/lookup_table_op.h
  paddle/fluid/operators/math/blas_impl.h
  python/paddle/fluid/tests/unittests/op_test.py
  python/paddle/fluid/tests/unittests/test_lookup_table_bf16_op.py
  tools/static_mode_white_list.py
Labels: BF16, Intel

#31647 [oneDNN] Added Elementwise Mul grad fp32/bf16
  paddle/fluid/operators/elementwise/elementwise_op.h
  paddle/fluid/operators/elementwise/mkldnn/elementwise_add_mkldnn_op.cc
  paddle/fluid/operators/elementwise/mkldnn/elementwise_mkldnn_op.h
  paddle/fluid/operators/elementwise/mkldnn/elementwise_mul_mkldnn_op.cc
  paddle/fluid/platform/mkldnn_reuse.h
  python/paddle/fluid/tests/unittests/mkldnn/test_elementwise_mul_bf16_mkldnn_op.py
  python/paddle/fluid/tests/unittests/mkldnn/test_elementwise_mul_mkldnn_op.py
Labels: Intel

#31820 fix cache key in concat oneDNN kernel
  paddle/fluid/operators/mkldnn/concat_mkldnn_op.cc
Labels: Intel

#31810 [cherry-pick] update scale collection and propagation algorithm (#31783)
  python/paddle/fluid/contrib/slim/quantization/quant2_int8_mkldnn_pass.py
Labels: Intel

#31837 [cherry-pick] fix cache key in concat oneDNN kernel (#31820)
  paddle/fluid/operators/mkldnn/concat_mkldnn_op.cc
Labels: Intel

#31835 Delete cudnn6 code
  paddle/fluid/operators/conv_cudnn_op_cache.h
  paddle/fluid/operators/cudnn_lstm_cache.h
  paddle/fluid/operators/cudnn_rnn_cache.h
  paddle/fluid/platform/cudnn_helper.h
Labels: Code Cleanup

#31813 [Custom OP]Remove old custom OP and reduce whl package volume
  paddle/fluid/framework/CMakeLists.txt
  paddle/fluid/framework/c/c_api.cc
  paddle/fluid/framework/c/c_api.h
  paddle/fluid/framework/load_op_lib.h
  paddle/fluid/pybind/pybind.cc
  python/paddle/fluid/framework.py
  python/paddle/fluid/tests/CMakeLists.txt
  python/paddle/fluid/tests/custom_op/CMakeLists.txt
  python/paddle/fluid/tests/custom_op/relu_op.cc
  python/paddle/fluid/tests/custom_op/relu_op.cu
  python/paddle/fluid/tests/custom_op/relu_op3.cc
  python/paddle/fluid/tests/custom_op/relu_op3.cu
  python/paddle/fluid/tests/custom_op/setup_build.py
  python/paddle/fluid/tests/custom_op/setup_install.py
  python/paddle/fluid/tests/custom_op/test_custom_op.py
  python/paddle/fluid/tests/custom_op/test_jit_load.py
  python/paddle/fluid/tests/custom_op/test_setup_build.py
  python/paddle/fluid/tests/custom_op/test_setup_install.py
  python/paddle/incubate/__init__.py
  python/paddle/utils/__init__.py
  python/paddle/utils/cpp_extension/cpp_extension.py
  python/paddle/utils/cpp_extension/extension_utils.py
  python/setup.py.in
Labels: Code Cleanup

#31894 Added int8 kernel for oneDNN LSTM op
  paddle/fluid/operators/fused/fusion_lstm_op.cc
  paddle/fluid/operators/fused/mkldnn/fusion_lstm_mkldnn_op.cc
  python/paddle/fluid/tests/unittests/mkldnn/test_fusion_lstm_int8_mkldnn_op.py
  tools/static_mode_white_list.py
Labels: Intel, int8

#31870 OneDNN hardswish integration (#30211)
  paddle/fluid/framework/ir/mkldnn/conv_activation_mkldnn_fuse_pass.cc
  paddle/fluid/framework/ir/mkldnn/conv_activation_mkldnn_fuse_pass.h
  paddle/fluid/framework/ir/mkldnn/conv_activation_mkldnn_fuse_pass_tester.cc
  paddle/fluid/inference/api/paddle_pass_builder.cc
  paddle/fluid/operators/mkldnn/activation_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/conv_mkldnn_op.cc
  python/paddle/fluid/tests/unittests/ir/inference/test_mkldnn_conv_activation_fuse_pass.py
  python/paddle/fluid/tests/unittests/mkldnn/test_activation_mkldnn_op.py
  python/paddle/fluid/tests/unittests/test_activation_op.py
Labels: Intel

#31883 delete cuda9 code
  cmake/configure.cmake
  cmake/cuda.cmake
  paddle/fluid/operators/elementwise/elementwise_op_function.cu.h
  paddle/fluid/platform/cuda_device_function.h
  paddle/fluid/platform/cuda_helper.h
  paddle/fluid/platform/float16_test.cu
Labels: Code Cleanup

#31949 Delete legacy C++ training user-interface
  paddle/fluid/CMakeLists.txt
  paddle/fluid/train/CMakeLists.txt
  paddle/fluid/train/demo/CMakeLists.txt
  paddle/fluid/train/demo/README.md
  paddle/fluid/train/demo/clean.sh
  paddle/fluid/train/demo/demo_network.py
  paddle/fluid/train/demo/demo_trainer.cc
  paddle/fluid/train/demo/run.sh
  paddle/fluid/train/imdb_demo/CMakeLists.txt
  paddle/fluid/train/imdb_demo/README.md
  paddle/fluid/train/imdb_demo/demo_trainer.cc
  paddle/fluid/train/imdb_demo/generate_program.py
  paddle/fluid/train/imdb_demo/imdb_reader.py
  paddle/fluid/train/imdb_demo/include/save_model.h
  paddle/fluid/train/imdb_demo/nets.py
  paddle/fluid/train/imdb_demo/run.sh
  paddle/fluid/train/imdb_demo/save_model.cc
  paddle/fluid/train/imdb_demo/train.cfg
  paddle/fluid/train/imdb_demo/train_filelist.txt
  paddle/fluid/train/test_train_recognize_digits.cc
Labels: Code Cleanup
