Repository PaddlePaddle/Paddle, pull requests merged in 2021-09, with the labels that each got.

#34332 Added slice BF16/FP32 FWD/BWD kernels
  paddle/fluid/operators/mkldnn/slice_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/split_mkldnn_op.cc
  paddle/fluid/operators/slice_op.cc
  paddle/fluid/operators/split_op.cc
  paddle/fluid/platform/mkldnn_reuse.h
  python/paddle/fluid/tests/unittests/mkldnn/test_slice_mkldnn_op.py
  python/paddle/fluid/tests/unittests/test_static_save_load_bf16.py
Labels: Intel, BF16

#35334 Add fusion_lstm INT8 PTQ
  paddle/fluid/framework/ir/graph_pattern_detector.cc
  paddle/fluid/framework/ir/graph_pattern_detector.h
  paddle/fluid/framework/ir/mkldnn/cpu_quantize_pass.cc
  paddle/fluid/framework/ir/mkldnn/cpu_quantize_pass.h
  paddle/fluid/inference/api/mkldnn_quantizer.cc
  paddle/fluid/inference/api/mkldnn_quantizer.h
  paddle/fluid/inference/api/mkldnn_quantizer_config.cc
  paddle/fluid/inference/api/mkldnn_quantizer_tester.cc
  paddle/fluid/inference/api/paddle_pass_builder.cc
  paddle/fluid/operators/fused/mkldnn/fusion_lstm_mkldnn_op.cc
  python/paddle/fluid/contrib/slim/tests/CMakeLists.txt
  python/paddle/fluid/contrib/slim/tests/quant2_int8_lstm_model.py
Labels: Intel, int8

#35455 Fix for reshape2 oneDNN op
  paddle/fluid/operators/mkldnn/reshape_mkldnn_op.cc
  python/paddle/fluid/tests/unittests/mkldnn/test_reshape_mkldnn_op.py
Labels: Intel

#35331 [oneDNN] Disable cache matmul v1 & refactoring
  paddle/fluid/operators/mkldnn/matmul_mkldnn_op.cc
Labels: Intel

#35392 fix a pact quantization bug
  python/paddle/nn/quant/quant_layers.py
Labels: Bug

#35599 Update scales when variable is unsigned
  python/paddle/fluid/contrib/slim/quantization/quant2_int8_mkldnn_pass.py
  python/paddle/fluid/contrib/slim/tests/CMakeLists.txt
Labels: Intel, int8

#35601 Added clip BF16/FP32 FWD/BWD kernels
  paddle/fluid/operators/clip_op.cc
  paddle/fluid/operators/mkldnn/clip_mkldnn_op.cc
  paddle/fluid/platform/mkldnn_reuse.h
  python/paddle/fluid/tests/unittests/mkldnn/test_clip_mkldnn_op.py
Labels: Intel, BF16

#35382 Collect LSTM quant model scales and save LSTM int8
  paddle/fluid/framework/ir/fc_gru_fuse_pass.cc
  paddle/fluid/framework/ir/fc_lstm_fuse_pass.cc
  paddle/fluid/framework/ir/mkldnn/cpu_quantize_pass_tester.cc
  python/paddle/fluid/contrib/slim/quantization/quant2_int8_mkldnn_pass.py
  python/paddle/fluid/contrib/slim/tests/CMakeLists.txt
Labels: Intel

#35740 Fix for swin_transformer(matmul+transpose+reshape)
  paddle/fluid/operators/matmul_op.cc
  paddle/fluid/platform/mkldnn_helper.h
Labels: Intel

#35706 Fix for slice OneDNN kernel in solov2 and ppyolo models
  paddle/fluid/operators/mkldnn/slice_mkldnn_op.cc
  python/paddle/fluid/tests/unittests/mkldnn/test_slice_mkldnn_op.py
Labels: Intel

#35781 Disabled oneDNN reshape1/2 and squeeze1/2 kernels
  paddle/fluid/operators/reshape_op.cc
  paddle/fluid/operators/squeeze_op.cc
Labels: Intel

#35664 [oneDNN] Disable caching of Reorder operation
  log
  paddle/fluid/framework/data_layout_transform.cc
  paddle/fluid/operators/elementwise/mkldnn/elementwise_add_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/cast_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/conv_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/expand_v2_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/matmul_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/reshape_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/slice_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/split_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/sum_mkldnn_op.cc
  paddle/fluid/operators/reduce_ops/mkldnn/reduce_mkldnn_op.h
  paddle/fluid/platform/mkldnn_reuse.h
Labels: Intel

#35510 Reuse OneDNN handler for SGD and SUM for SelectedRows input tensors.
  paddle/fluid/operators/math/selected_rows_functor.cc
  paddle/fluid/operators/mkldnn/axpy_handler.cc
  paddle/fluid/operators/mkldnn/axpy_handler.h
  paddle/fluid/operators/optimizers/mkldnn/sgd_mkldnn_op.cc
  paddle/fluid/operators/optimizers/sgd_op.cc
  paddle/fluid/operators/optimizers/sgd_op.h
  python/paddle/fluid/contrib/mixed_precision/bf16/decorator.py
  python/paddle/fluid/optimizer.py
  python/paddle/fluid/tests/unittests/test_sgd_op_bf16.py
Labels: Intel, BF16

#35887 Add quant2 int8 lstm model test
  python/paddle/fluid/contrib/slim/quantization/quant2_int8_mkldnn_pass.py
  python/paddle/fluid/contrib/slim/tests/CMakeLists.txt
  python/paddle/fluid/contrib/slim/tests/quant2_int8_lstm_model.py
  python/paddle/fluid/contrib/slim/tests/save_quant_model.py
Labels: Intel, int8

#35885 Fix copy elision warning
  paddle/fluid/framework/fleet/gloo_wrapper.h
  paddle/fluid/framework/ir/fc_gru_fuse_pass_tester.h
  paddle/fluid/framework/ir/fc_lstm_fuse_pass_tester.h
  paddle/fluid/framework/new_executor/interpretercore_util.cc
  paddle/fluid/framework/new_executor/workqueue.cc
  paddle/fluid/inference/api/api_impl.cc
  paddle/fluid/memory/allocation/mmap_allocator.cc
  paddle/fluid/pybind/inference_api.cc
  paddle/fluid/string/string_helper.h
Labels: Intel

#35912 [cherry-pick] Add quant2 int8 lstm model test (#35887)
  python/paddle/fluid/contrib/slim/quantization/quant2_int8_mkldnn_pass.py
  python/paddle/fluid/contrib/slim/tests/CMakeLists.txt
  python/paddle/fluid/contrib/slim/tests/quant2_int8_lstm_model.py
  python/paddle/fluid/contrib/slim/tests/save_quant_model.py
Labels: Intel

#35884 [oneDNN] candidate fix to #34554
  paddle/fluid/operators/mkldnn/conv_mkldnn_op.cc
  paddle/fluid/platform/mkldnn_reuse.h
Labels: Intel

#35892 Added flatten and flatten2 BF16/FP32 FWD/BWD kernels
  paddle/fluid/operators/flatten_op.cc
  paddle/fluid/operators/mkldnn/reshape_mkldnn_op.cc
  paddle/fluid/operators/reshape_op.cc
  paddle/fluid/operators/squeeze_op.cc
  python/paddle/fluid/tests/unittests/mkldnn/test_flatten_mkldnn_op.py
Labels: Intel, BF16
