Repository PaddlePaddle/Paddle, pull requests merged in 2021-08, with the labels that each got.

#34623 [oneDNN] Fix to issue #34554
  paddle/fluid/operators/elementwise/mkldnn/elementwise_mkldnn_op.h
  paddle/fluid/operators/elementwise/mkldnn/elementwise_mul_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/activation_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/caching_tests.cmake
  paddle/fluid/operators/mkldnn/scale_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/softmax_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/test_mkldnn_caching.cc
  paddle/fluid/platform/mkldnn_reuse.h
Labels: Intel

#34859 [oneDNN] Fix to 34554 (same as previous PR but should build with GPU)
  paddle/fluid/operators/elementwise/mkldnn/elementwise_mkldnn_op.h
  paddle/fluid/operators/elementwise/mkldnn/elementwise_mul_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/activation_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/caching_tests.cmake
  paddle/fluid/operators/mkldnn/scale_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/softmax_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/test_mkldnn_caching.cc
  paddle/fluid/platform/mkldnn_reuse.h
Labels: Intel

#34820 Fix elementwise_add quantization
  paddle/fluid/framework/ir/graph_pattern_detector.cc
  paddle/fluid/framework/ir/mkldnn/cpu_quantize_pass.cc
  paddle/fluid/framework/ir/mkldnn/cpu_quantize_pass_tester.cc
  paddle/fluid/framework/ir/mkldnn/cpu_quantize_placement_pass_tester.cc
Labels: Intel, int8

#34830 [oneDNN ] disabling more ops caching
  paddle/fluid/operators/mkldnn/layer_norm_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/lrn_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/sum_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/transpose_mkldnn_op.cc
  paddle/fluid/platform/mkldnn_reuse.h
Labels: Intel

#35040 Upgrade oneDNN to v2.3.2
  cmake/external/mkldnn.cmake
Labels: Intel

#35030 [oneDNN] disable caching for interpolate and batch Norm
  paddle/fluid/operators/mkldnn/batch_norm_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/interpolate_mkldnn_op.cc
Labels: Intel

#35002 [oneDNN] Concat refactoring and disabling caching
  paddle/fluid/operators/mkldnn/concat_mkldnn_op.cc
  python/paddle/fluid/tests/unittests/mkldnn/test_concat_int8_mkldnn_op.py
  python/paddle/fluid/tests/unittests/mkldnn/test_concat_mkldnn_op.py
Labels: Intel

#34653 Update LearningRate for test fit a line BF16
  python/paddle/fluid/contrib/mixed_precision/bf16/amp_utils.py
  python/paddle/fluid/tests/book/test_fit_a_line.py
Labels: Intel, BF16

#34648 SGD BF16 functional test.
  python/paddle/fluid/layers/tensor.py
  python/paddle/fluid/tests/unittests/test_sgd_op_bf16.py
  python/paddle/tensor/stat.py
Labels: Intel, BF16

#35101 Fix for expand_v2 op
  paddle/fluid/inference/tests/infer_ut/test_ppyolo_mbv3.cc
  paddle/fluid/operators/mkldnn/expand_v2_mkldnn_op.cc
  python/paddle/fluid/tests/unittests/mkldnn/test_expand_v2_mkldnn_op.py
Labels: Intel

#35231 [oneDNN] Fix to #34492
  paddle/fluid/platform/mkldnn_helper.h
Labels: Intel
