Repository PaddlePaddle/Paddle, pull requests merged in 2022-12, with the labels that each got.

#48441 [Fluid Clean] remove pixel_shuffle, fsp_matrix, where, sign, unique, unique_with_counts
  python/paddle/fluid/layers/nn.py
  python/paddle/fluid/tests/unittests/mlu/test_where_index_op_mlu.py
  python/paddle/fluid/tests/unittests/npu/test_where_index_npu.py
  python/paddle/fluid/tests/unittests/test_fsp_op.py
  python/paddle/fluid/tests/unittests/test_layers.py
  python/paddle/fluid/tests/unittests/test_sign_op.py
  python/paddle/fluid/tests/unittests/test_unique.py
  python/paddle/fluid/tests/unittests/test_unique_with_counts.py
  python/paddle/fluid/tests/unittests/test_var_base.py
  python/paddle/fluid/tests/unittests/test_where_index.py
  python/paddle/fluid/tests/unittests/xpu/test_where_index_xpu.py
  python/paddle/fluid/variable_index.py
Labels: contributor, status: proposed

#48569 [Paddle Inference] remove conv_act_set from graph_pattern_detector.cc
  paddle/fluid/framework/ir/conv_elementwise_add2_act_fuse_pass.cc
  paddle/fluid/framework/ir/conv_elementwise_add_act_fuse_pass.cc
  paddle/fluid/framework/ir/graph_pattern_detector.cc
  paddle/fluid/framework/ir/graph_pattern_detector.h
Labels: contributor, status: proposed

#48434 fix boardcasting superlink
  paddle/fluid/operators/controlflow/bitwise_op.cc
  python/paddle/distribution/uniform.py
  python/paddle/tensor/creation.py
  python/paddle/tensor/logic.py
  python/paddle/tensor/math.py
  python/paddle/vision/image.py
  python/paddle/vision/transforms/functional.py
  python/paddle/vision/transforms/transforms.py
Labels: contributor, status: proposed

#48325 add silu, silu_grad, unfold and unfold_grad xpu kernels
  paddle/fluid/platform/device/xpu/xpu2_op_list.h
  paddle/phi/kernels/xpu/activation_grad_kernel.cc
  paddle/phi/kernels/xpu/activation_kernel.cc
  paddle/phi/kernels/xpu/conv_grad_kernel.cc
  paddle/phi/kernels/xpu/unfold_grad_kernel.cc
  paddle/phi/kernels/xpu/unfold_kernel.cc
  python/paddle/fluid/tests/unittests/xpu/test_activation_op_xpu.py
  python/paddle/fluid/tests/unittests/xpu/test_conv3d_op_xpu.py
  python/paddle/fluid/tests/unittests/xpu/test_unfold_op_xpu.py
Labels: contributor

#48269 [Fluid Clean] remove paddle.fluid.layers.nn.reduce_all,reduce_any
  python/paddle/fluid/contrib/mixed_precision/decorator.py
  python/paddle/fluid/layers/nn.py
  python/paddle/fluid/layers/rnn.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/transformer_dygraph_model.py
  python/paddle/fluid/tests/unittests/ipu/test_reduce_x_op_ipu.py
  python/paddle/fluid/tests/unittests/test_reduce_op.py
  python/paddle/jit/dy2static/convert_operators.py
Labels: contributor, status: proposed

#48592 add some compare and logical trt converter
  paddle/fluid/inference/api/analysis_predictor.cc
  paddle/fluid/inference/tensorrt/convert/elementwise_op.cc
  paddle/fluid/inference/tensorrt/op_teller.cc
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_compare_and_logical.py
Labels: contributor, status: proposed

#47805 Fix fuse_gemm_epilogue
  paddle/fluid/framework/ir/fuse_gemm_epilogue_pass.cc
  python/paddle/distributed/passes/cpp_pass.py
  python/paddle/fluid/tests/unittests/distributed_passes/CMakeLists.txt
  python/paddle/fluid/tests/unittests/distributed_passes/dist_pass_test_base.py
  python/paddle/fluid/tests/unittests/distributed_passes/test_dist_fuse_gemm_epilogue_pass.py
Labels: NVIDIA, contributor

#48456 [Fluid Clean] remove argsort, linspace, diag
  python/paddle/fluid/layers/tensor.py
  python/paddle/fluid/tests/unittests/ipu/test_argsort_op_ipu.py
  python/paddle/fluid/tests/unittests/test_argsort_op.py
  python/paddle/fluid/tests/unittests/test_diag.py
  python/paddle/fluid/tests/unittests/test_layers.py
  python/paddle/fluid/tests/unittests/test_linspace.py
Labels: contributor, status: proposed

#48299 Migrate mul_mkldnn_op to phi matmul_kernel
  paddle/fluid/operators/mkldnn/mul_mkldnn_op.cc
  paddle/phi/kernels/onednn/matmul_kernel.cc
Labels: Intel, contributor

#48611 [PHI] Migrate elementwise_sub kernel
  paddle/fluid/operators/elementwise/mkldnn/elementwise_sub_mkldnn_op.cc
  paddle/phi/kernels/elementwise_kernel.cc
  paddle/phi/kernels/onednn/elementwise_kernel.cc
Labels: Intel, contributor

#48639 [CodeStyle][py36] remove deprecated warnings for py36
  python/paddle/utils/deprecated.py
Labels: contributor, status: proposed

#48499 [PHI decoupling] migrate poly_util.h to phi
  paddle/phi/kernels/funcs/detection/nms_util.h
  paddle/phi/kernels/funcs/detection/poly_util.cc
  paddle/phi/kernels/funcs/detection/poly_util.h
Labels: contributor, status: proposed

#48289 [Fluid Clean] remove nn.topk, nn.ctc_greedy_decoder, nn.im2sequence, nn.multiplex, nn.smooth_l1
  paddle/phi/kernels/funcs/transpose_functor.cu.h
  python/paddle/fluid/layers/detection.py
  python/paddle/fluid/layers/nn.py
  python/paddle/fluid/tests/unittests/dist_transformer.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/seq2seq_dygraph_model.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/transformer_dygraph_model.py
  python/paddle/fluid/tests/unittests/ipu/test_topk_op_ipu.py
  python/paddle/fluid/tests/unittests/npu/test_smooth_l1_loss_op_npu.py
  python/paddle/fluid/tests/unittests/test_beam_search_op.py
  python/paddle/fluid/tests/unittests/test_ctc_align.py
  python/paddle/fluid/tests/unittests/test_layers.py
  python/paddle/fluid/tests/unittests/test_smooth_l1_loss_op.py
Labels: contributor, status: proposed

#48509 [Fluid Clean] remove fluid.layers.continuous_value_model
  python/paddle/fluid/layers/nn.py
  python/paddle/static/nn/__init__.py
Labels: contributor, status: proposed

#48659 fix bug in paddle/phi/api/yaml/generator
  paddle/fluid/operators/generator/cross_validate.py
  paddle/phi/api/yaml/generator/api_gen.py
  paddle/phi/api/yaml/generator/backward_api_gen.py
  paddle/phi/api/yaml/generator/intermediate_api_gen.py
  paddle/phi/api/yaml/generator/wrapped_infermeta_gen.py
Labels: contributor, status: proposed

#48694 [PHI decoupling] move device_memory_aligment from fluid to phi
  paddle/fluid/framework/details/CMakeLists.txt
  paddle/fluid/framework/details/fused_all_reduce_op_handle.cc
  paddle/fluid/operators/CMakeLists.txt
  paddle/fluid/operators/coalesce_tensor_op.cc
  paddle/fluid/platform/CMakeLists.txt
  paddle/fluid/platform/cpu_info.cc
  paddle/fluid/platform/cpu_info.h
  paddle/fluid/platform/device/gpu/gpu_info.cc
  paddle/fluid/platform/device/gpu/gpu_info.h
  paddle/fluid/platform/device/mlu/mlu_info.cc
  paddle/fluid/platform/device/mlu/mlu_info.h
  paddle/fluid/platform/device/npu/npu_info.cc
  paddle/fluid/platform/device/npu/npu_info.h
  paddle/fluid/platform/device_memory_aligment.h
  paddle/phi/backends/cpu/cpu_info.h
  paddle/phi/backends/device_memory_aligment.h
  paddle/phi/backends/gpu/gpu_info.h
  paddle/phi/backends/mlu/mlu_info.h
  paddle/phi/backends/npu/npu_info.h
  paddle/phi/kernels/CMakeLists.txt
  paddle/phi/kernels/check_memory_continue_kernel.cc
  paddle/phi/kernels/coalesce_tensor_kernel.cc
Labels: contributor, status: proposed

#47908 Add IntermediateLayerGetter
  python/paddle/fluid/tests/unittests/test_IntermediateLayerGetter.py
  python/paddle/vision/models/_utils.py
  python/paddle/vision/models/mobilenetv2.py
  python/paddle/vision/models/mobilenetv3.py
  python/paddle/vision/models/utils.py
Labels: contributor, status: proposed

#48625 [PHI] Migrate elementwise_(add/mul) kernels
  paddle/fluid/framework/ir/mkldnn/mkldnn_conv_bn_fuse_pass_tester.cc
  paddle/fluid/framework/ir/mkldnn/mkldnn_inplace_pass_tester.cc
  paddle/fluid/operators/elementwise/mkldnn/elementwise_add_mkldnn_op.cc
  paddle/fluid/operators/elementwise/mkldnn/elementwise_mkldnn_op.h
  paddle/fluid/operators/elementwise/mkldnn/elementwise_mul_mkldnn_op.cc
  paddle/fluid/operators/elementwise/unity_build_rule.cmake
  paddle/fluid/operators/mkldnn/test_mkldnn_caching.cc
  paddle/fluid/operators/mkldnn/test_mkldnn_op_inplace.cc
  paddle/phi/kernels/elementwise_kernel.cc
  paddle/phi/kernels/onednn/elementwise_kernel.cc
Labels: Intel, contributor

#48606 add xpu_support op function
  paddle/fluid/framework/operator.cc
  paddle/fluid/imperative/prepared_operator.cc
  paddle/fluid/platform/device/xpu/xpu1_op_list.h
  paddle/fluid/platform/device/xpu/xpu_op_list.cc
  paddle/fluid/platform/device/xpu/xpu_op_list.h
  paddle/fluid/pybind/place.cc
  paddle/phi/backends/xpu/CMakeLists.txt
  paddle/phi/backends/xpu/xpu1_op_list.cc
  paddle/phi/backends/xpu/xpu2_op_list.cc
  paddle/phi/backends/xpu/xpu_op_list.cc
  paddle/phi/backends/xpu/xpu_op_list.h
  paddle/phi/core/kernel_factory.cc
Labels: contributor, status: proposed

#48746 [CodeStyle][isort][Dy2St] sort imports in test_error
  pyproject.toml
  python/paddle/fluid/tests/unittests/dygraph_to_static/test_error.py
Labels: contributor, status: proposed

#48679 replace deprecated `load_module` with `exec_module`
  python/paddle/jit/dy2static/utils.py
  python/paddle/utils/cpp_extension/extension_utils.py
Labels: contributor, status: proposed

#48710 modify d2d copy to xpu::copy in xpu kernel, test=kunlun
  paddle/fluid/operators/reader/buffered_reader.cc
  paddle/phi/backends/xpu/xpu_info.cc
  paddle/phi/kernels/reshape_grad_kernel.cc
  paddle/phi/kernels/reshape_kernel.cc
  paddle/phi/kernels/xpu/gather_nd_kernel.cc
  paddle/phi/kernels/xpu/generate_proposals_kernel.cc
  paddle/phi/kernels/xpu/scatter_kernel.cc
  paddle/phi/kernels/xpu/tile_kernel.cc
  python/paddle/fluid/tests/unittests/xpu/get_test_cover_info.py
  python/paddle/fluid/tests/unittests/xpu/test_reshape2_op_xpu.py
Labels: contributor, status: proposed

#48692 [Paddle Inference] optimize transfer_layout kernel in fp16 model
  paddle/phi/kernels/funcs/math_function.cu
  paddle/phi/kernels/funcs/math_function.h
  paddle/phi/kernels/transfer_layout_kernel.cc
Labels: contributor, status: proposed

#48775 update kl1 op list and optimize matmul unitest for kunlun
  paddle/phi/backends/xpu/xpu1_op_list.cc
  paddle/phi/backends/xpu/xpu2_op_list.cc
  python/paddle/fluid/tests/unittests/xpu/test_matmul_v2_op_xpu.py
Labels: contributor, status: proposed

#48678 Remove reduntant numpy output in Example code (1/2), test=document_fix
  python/paddle/distributed/communication/stream/all_reduce.py
  python/paddle/fft.py
  python/paddle/incubate/nn/layer/fused_transformer.py
  python/paddle/nn/functional/activation.py
  python/paddle/nn/functional/conv.py
  python/paddle/nn/functional/distance.py
  python/paddle/nn/functional/extension.py
  python/paddle/nn/functional/loss.py
  python/paddle/nn/functional/vision.py
  python/paddle/nn/initializer/constant.py
  python/paddle/nn/layer/conv.py
  python/paddle/nn/layer/distance.py
  python/paddle/nn/layer/loss.py
  python/paddle/nn/layer/vision.py
  python/paddle/nn/quant/quant_layers.py
  python/paddle/tensor/manipulation.py
  python/paddle/text/datasets/conll05.py
  python/paddle/text/datasets/imdb.py
  python/paddle/text/datasets/imikolov.py
  python/paddle/text/datasets/movielens.py
Labels: contributor, status: proposed

#48634 [PHI] Migrate squeeze and squeeze_grad kernels
  paddle/fluid/operators/mkldnn/reshape_mkldnn_op.cc
  paddle/phi/kernels/onednn/squeeze_grad_kernel.cc
  paddle/phi/kernels/onednn/squeeze_kernel.cc
Labels: Intel, contributor

#48581 修复paddle.nn.functinal包和paddle.nn包下API文档
  python/paddle/nn/functional/conv.py
  python/paddle/nn/layer/conv.py
Labels: contributor, status: proposed

#48846 assign cve number to pdsa, test=document_fix
  security/advisory/pdsa-2022-001.md
  security/advisory/pdsa-2022-001_cn.md
  security/advisory/pdsa-2022-002.md
  security/advisory/pdsa-2022-002_cn.md
Labels: contributor, status: proposed

#48745 [CodeStyle][F811] fix some test cases shadowed by the same name
  .flake8
  python/paddle/fluid/tests/unittests/collective/fleet/test_dygraph_group_sharded_api_for_eager.py
  python/paddle/fluid/tests/unittests/fft/test_fft_with_static_graph.py
  python/paddle/fluid/tests/unittests/test_activation_nn_grad.py
  python/paddle/fluid/tests/unittests/test_lstm_cudnn_op.py
  python/paddle/fluid/tests/unittests/test_matmul_v2_op.py
  python/paddle/fluid/tests/unittests/test_rrelu_op.py
  setup.py
Labels: contributor, status: proposed

#48811 [PHI decoupling] remove gpu_info.h from phi dependencies
  paddle/phi/kernels/funcs/blas/blas_impl.cu.h
  paddle/phi/kernels/funcs/blas/blas_impl.hip.h
  paddle/phi/kernels/gpu/affine_grid_grad_kernel.cu
  paddle/phi/kernels/gpu/affine_grid_kernel.cu
  paddle/phi/kernels/gpu/one_hot_kernel.cu
  paddle/phi/kernels/gpu/pad3d_grad_kernel.cu
  paddle/phi/kernels/gpu/pad3d_kernel.cu
  paddle/phi/kernels/gpudnn/affine_grid_grad_kernel.cu
  paddle/phi/kernels/gpudnn/affine_grid_kernel.cu
  paddle/phi/kernels/gpudnn/conv_cudnn_v7.h
Labels: contributor, status: proposed

#48655 [Paddle Inference] Add add onehot trt converter
  paddle/fluid/inference/api/analysis_predictor.cc
  paddle/fluid/inference/tensorrt/convert/CMakeLists.txt
  paddle/fluid/inference/tensorrt/convert/one_hot_op.cc
  paddle/fluid/inference/tensorrt/op_teller.cc
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_one_hot.py
Labels: contributor, status: proposed

#48761 [PHI decoupling] remove bbox_util.h from phi dependencies
  paddle/phi/kernels/funcs/detection/bbox_util.h
  paddle/phi/kernels/gpu/distribute_fpn_proposals_kernel.cu
  paddle/phi/kernels/gpu/generate_proposals_kernel.cu
Labels: contributor, status: proposed

#47904 Optimize Paddle diagonal
  paddle/phi/kernels/cpu/diagonal_kernel.cc
  paddle/phi/kernels/funcs/diagonal.h
  paddle/phi/kernels/gpu/diagonal_grad_kernel.cu
  paddle/phi/kernels/gpu/diagonal_kernel.cu
  python/paddle/fluid/tests/unittests/test_diagonal_op.py
Labels: contributor, status: proposed

#48826 rm kunlun xpu2_op_list
  paddle/fluid/platform/device/xpu/xpu2_op_list.h
  python/paddle/fluid/tests/unittests/xpu/test_sampling_id_op_xpu.py
Labels: contributor, status: proposed

#48451 [Fluid Clean] remove unfold, deformable_roi_pooling, shard_index, hard_swish, mish, uniform_random, unbind
  python/paddle/distribution/uniform.py
  python/paddle/fluid/layers/nn.py
  python/paddle/fluid/tests/unittests/CMakeLists.txt
  python/paddle/fluid/tests/unittests/ir/inference/test_mkldnn_elt_act_fuse_pass.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_activation_pass.py
  python/paddle/fluid/tests/unittests/test_activation_op.py
  python/paddle/fluid/tests/unittests/test_cuda_random_seed.py
  python/paddle/fluid/tests/unittests/test_deformable_psroi_pooling.py
  python/paddle/fluid/tests/unittests/test_gradient_clip.py
  python/paddle/fluid/tests/unittests/test_layers.py
  python/paddle/fluid/tests/unittests/test_random_seed.py
  python/paddle/fluid/tests/unittests/test_regularizer.py
  python/paddle/fluid/tests/unittests/test_regularizer_api.py
  python/paddle/fluid/tests/unittests/test_static_shape_inferrence_for_shape_tensor.py
  python/paddle/fluid/tests/unittests/test_unbind_op.py
  python/paddle/fluid/tests/unittests/test_uniform_random_bf16_op.py
  python/paddle/fluid/tests/unittests/test_uniform_random_op.py
Labels: contributor, status: proposed

#48599 fix english docs typo errors
  python/paddle/vision/ops.py
Labels: contributor, status: proposed

#48860 [XPU] add load op into oplist.
  paddle/phi/backends/xpu/xpu2_op_list.cc
Labels: contributor, status: proposed

#48360 Reenabled ext_reorder recording
  paddle/phi/kernels/funcs/data_layout_transform.cc
Labels: Intel, contributor

#48845 add set_value and set_value_grad *test=kunlun
  paddle/phi/backends/xpu/xpu2_op_list.cc
  paddle/phi/kernels/xpu/set_value_grad_kernel.cc
  paddle/phi/kernels/xpu/set_value_kernel.cc
  python/paddle/fluid/tests/unittests/xpu/test_set_value_op_xpu.py
Labels: contributor, status: proposed

#48696 [PHI decoupling] move "flags.h" from fluid to phi
  paddle/fluid/distributed/store/tcp_store.cc
  paddle/fluid/eager/tests/performance_tests/benchmark_eager_cpu.cc
  paddle/fluid/eager/tests/performance_tests/benchmark_eager_cuda.cc
  paddle/fluid/framework/new_executor/executor_statistics.cc
  paddle/fluid/imperative/flags.cc
  paddle/fluid/imperative/profiler.cc
  paddle/fluid/inference/api/analysis_predictor.cc
  paddle/fluid/memory/allocation/auto_growth_best_fit_allocator.cc
  paddle/fluid/operators/controlflow/conditional_block_op.cc
  paddle/fluid/operators/conv_op.cc
  paddle/fluid/operators/conv_transpose_op.cc
  paddle/fluid/operators/fused/fusion_conv_inception_op.cc
  paddle/fluid/platform/CMakeLists.txt
  paddle/fluid/platform/cpu_info.cc
  paddle/fluid/platform/device/gpu/gpu_info.cc
  paddle/fluid/platform/enforce.h
  paddle/fluid/platform/profiler/host_tracer.cc
  paddle/fluid/pybind/global_value_getter_setter.cc
  paddle/phi/api/yaml/generator/ops_extra_info_gen.py
  paddle/phi/api/yaml/op_compat.yaml
  paddle/phi/backends/CMakeLists.txt
  paddle/phi/backends/gpu/CMakeLists.txt
  paddle/phi/backends/gpu/cuda/CMakeLists.txt
  paddle/phi/backends/gpu/cuda/cudnn_workspace_helper.cc
  paddle/phi/backends/gpu/cuda/cudnn_workspace_helper.h
  paddle/phi/backends/xpu/xpu_info.cc
  paddle/phi/core/CMakeLists.txt
  paddle/phi/core/flags.cc
  paddle/phi/core/flags.h
  paddle/phi/kernels/gpu/batch_norm_grad_kernel.cu
  paddle/phi/kernels/gpu/batch_norm_kernel.cu
  paddle/phi/kernels/gpu/gelu_funcs.h
  paddle/phi/kernels/gpudnn/conv_grad_kernel.cu
  paddle/phi/kernels/gpudnn/conv_kernel.cu
  paddle/phi/kernels/impl/conv_cudnn_impl.h
  paddle/testing/paddle_gtest_main.cc
Labels: contributor, status: proposed

#48838 [Paddle Inference]add cutlass act set in conv_elementwise_add_act_fuse_pass
  paddle/fluid/framework/ir/conv2d_fusion_layout_transfer_pass.cc
  paddle/fluid/framework/ir/conv_elementwise_add_act_fuse_pass.cc
Labels: contributor, status: proposed

#48942 temporally disable set_value *test=kunlun
  paddle/phi/backends/xpu/xpu2_op_list.cc
Labels: contributor, status: proposed

#48926 [PHI decoupling] move ops_extra_info_gen.py from phi to fluid
  paddle/fluid/operators/generator/CMakeLists.txt
  paddle/fluid/operators/generator/ops_extra_info_gen.py
Labels: contributor, status: proposed

#48886 对多个文档按照要求修改 对应中文的#5453
  python/paddle/nn/functional/activation.py
  python/paddle/nn/functional/common.py
  python/paddle/nn/layer/activation.py
  python/paddle/nn/layer/common.py
  python/paddle/nn/layer/loss.py
Labels: contributor, status: proposed

#48892 [CodeStyle] fix renamed files not being monitored by Codestyle Check
  tools/codestyle/pre_commit.sh
Labels: contributor, status: proposed

#45547 [Paddle-TRT] add cast between int64 tensor and Paddle-TRT
  paddle/fluid/inference/analysis/ir_passes/tensorrt_subgraph_pass.cc
  paddle/fluid/inference/tensorrt/engine.h
  paddle/fluid/operators/tensorrt/tensorrt_engine_op.h
  paddle/fluid/operators/tensorrt/tensorrt_engine_op_test.cc
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_int64.py
Labels: contributor, status: proposed

#48993 [Paddle-TRT]fix a bug in GetTrtWeight
  paddle/fluid/inference/tensorrt/engine.cc
Labels: contributor, status: proposed

#48930 [PHI decoupling] move norm_utils.cu.h from fluid to phi and remove norm_utils.h in fluid
  paddle/fluid/operators/batch_norm_op.cu
  paddle/fluid/operators/batch_norm_op.h
  paddle/fluid/operators/fused/fused_bn_activation_op.cu
  paddle/fluid/operators/fused/fused_bn_add_activation_op.cu
  paddle/fluid/operators/norm_utils.h
  paddle/fluid/operators/sync_batch_norm_op_mlu.cc
  paddle/fluid/operators/sync_batch_norm_op_npu.cc
  paddle/phi/kernels/funcs/norm_utils.cu.h
  paddle/phi/kernels/gpu/batch_norm_grad_kernel.cu
  paddle/phi/kernels/gpu/batch_norm_kernel.cu
Labels: contributor, status: proposed

#48763 [Paddle-TRT]forbid conv op whose weight is not a persistable weight into Paddle-TRT
  paddle/fluid/inference/tensorrt/op_teller.cc
Labels: contributor, status: proposed

#48539 [PHI] OneDNN version of Copy
  paddle/phi/core/tensor_utils.cc
  paddle/phi/kernels/onednn/transpose_grad_kernel.cc
  paddle/phi/kernels/onednn/transpose_kernel.cc
Labels: Intel, contributor

#48936 [CodeStyle][isort][F401] fix some regression issues
  python/paddle/distributed/auto_parallel/tuner/rule_based_tuner.py
  python/paddle/fluid/tests/unittests/test_device_guard.py
  python/paddle/fluid/tests/unittests/xpu/test_device_guard_xpu.py
  python/paddle/utils/inplace_utils.py
Labels: contributor

#48850 reshape onednn test reimplemented
  python/paddle/fluid/tests/unittests/mkldnn/test_reshape_mkldnn_op.py
  python/paddle/fluid/tests/unittests/test_reshape_op.py
Labels: Intel, contributor

#48221 [Inference]enable custom device save model on device memory
  paddle/fluid/inference/analysis/argument.h
  paddle/fluid/inference/analysis/passes/ir_params_sync_among_devices_pass.cc
  paddle/fluid/inference/analysis/passes/ir_params_sync_among_devices_pass.h
  paddle/fluid/inference/api/analysis_predictor.cc
Labels: contributor, status: proposed

#48961 Bugfix: bkcl_comm_num typo in fleet
  python/paddle/distributed/fleet/meta_optimizers/graph_execution_optimizer.py
Labels: contributor, status: proposed

#48627 [tools] Update summary env
  .github/ISSUE_TEMPLATE/3_build-installation-issue.yml
  tools/summary_env.py
Labels: contributor, status: proposed

#49024 [Dy2St] transforms.RandomVerticalFlip Support static mode
  python/paddle/tests/test_transforms_static.py
  python/paddle/vision/transforms/functional.py
  python/paddle/vision/transforms/functional_tensor.py
  python/paddle/vision/transforms/transforms.py
Labels: contributor, status: proposed

#48872 Correct quantization for multiple input and output ops
  paddle/fluid/framework/ir/mkldnn/cpu_quantize_pass.cc
  paddle/fluid/framework/ir/mkldnn/cpu_quantize_pass_tester.cc
  paddle/fluid/framework/ir/mkldnn/cpu_quantize_squash_pass.cc
Labels: Intel, int8, contributor

#48637 [CodeStyle][isort][Dy2St] sort imports for paddle.jit
  pyproject.toml
  python/paddle/jit/api.py
  python/paddle/jit/dy2static/assert_transformer.py
  python/paddle/jit/dy2static/ast_transformer.py
  python/paddle/jit/dy2static/base_transformer.py
  python/paddle/jit/dy2static/basic_api_transformer.py
  python/paddle/jit/dy2static/break_continue_transformer.py
  python/paddle/jit/dy2static/call_transformer.py
  python/paddle/jit/dy2static/cast_transformer.py
  python/paddle/jit/dy2static/convert_call_func.py
  python/paddle/jit/dy2static/convert_operators.py
  python/paddle/jit/dy2static/create_variable_transformer.py
  python/paddle/jit/dy2static/decorator_transformer.py
  python/paddle/jit/dy2static/early_return_transformer.py
  python/paddle/jit/dy2static/error.py
  python/paddle/jit/dy2static/function_spec.py
  python/paddle/jit/dy2static/ifelse_transformer.py
  python/paddle/jit/dy2static/logging_utils.py
  python/paddle/jit/dy2static/logical_transformer.py
  python/paddle/jit/dy2static/loop_transformer.py
  python/paddle/jit/dy2static/origin_info.py
  python/paddle/jit/dy2static/partial_program.py
  python/paddle/jit/dy2static/program_translator.py
  python/paddle/jit/dy2static/return_transformer.py
  python/paddle/jit/dy2static/static_analysis.py
  python/paddle/jit/dy2static/tensor_shape_transformer.py
  python/paddle/jit/dy2static/typehint_transformer.py
  python/paddle/jit/dy2static/utils.py
  python/paddle/jit/dy2static/variable_trans_func.py
Labels: contributor, status: proposed

#48969 Fixed the dead link bug in the API documentation
  python/paddle/distributed/launch/main.py
  python/paddle/fluid/dygraph/nn.py
  python/paddle/fluid/framework.py
  python/paddle/fluid/layers/rnn.py
Labels: contributor, status: proposed

#49043 nullptr bugfix for XPU pg mode
  paddle/fluid/distributed/collective/ProcessGroupBKCL.cc
  paddle/phi/backends/xpu/xpu2_op_list.cc
  paddle/phi/kernels/elementwise_kernel.cc
  paddle/phi/kernels/xpu/elementwise_multiply_kernel.cc
Labels: contributor, status: proposed

#48791 add condition of skipif
  python/paddle/fluid/tests/unittests/test_fused_gate_attention_op.py
Labels: contributor, status: proposed

#49017 [CodeStyle] fix c++17-extensions warning on macos
  cmake/flags.cmake
  paddle/phi/kernels/cpu/viterbi_decode_kernel.cc
  paddle/phi/kernels/strings/strings_lower_upper_kernel.h
Labels: contributor, status: proposed

#49066 Add custom CUDNN finding paths for 64bit Windows
  cmake/cudnn.cmake
Labels: contributor, status: proposed

#48997 Fix nullptr to TestFuseGemmEpilogueReluBWDFP*
  paddle/fluid/operators/fused/fused_gemm_epilogue_op.cc
  paddle/fluid/operators/fused/fused_gemm_epilogue_op.cu
Labels: NVIDIA, contributor

#48983 修复paddle.amp.decorate等API的文档
  python/paddle/amp/auto_cast.py
  python/paddle/fluid/framework.py
  python/paddle/fluid/optimizer.py
  python/paddle/incubate/operators/softmax_mask_fuse.py
  python/paddle/incubate/operators/softmax_mask_fuse_upper_triangle.py
  python/paddle/signal.py
  python/paddle/tensor/linalg.py
  python/paddle/tensor/random.py
Labels: contributor, status: proposed

#49014 按在线文档需求 61~70 更新了部分文档
  python/paddle/fluid/layers/control_flow.py
  python/paddle/fluid/layers/sequence_lod.py
  python/paddle/fluid/reader.py
  python/paddle/static/nn/common.py
  python/paddle/tensor/logic.py
  python/paddle/tensor/manipulation.py
Labels: contributor, status: proposed

#48906 Add a persistent ibuilder to speedup unit tests
  paddle/fluid/inference/tensorrt/engine.h
Labels: NVIDIA, contributor, status: not progressed

#48274 [Fluid Clean] remove paddle.fluid.layers.nn.split and paddle.fluid.layers.nn.l2_normalize
  python/paddle/fluid/contrib/layers/rnn_impl.py
  python/paddle/fluid/layers/nn.py
  python/paddle/fluid/nets.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/seq2seq_dygraph_model.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/test_partial_program.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/test_ptb_lm.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_subgraph_pass.py
  python/paddle/fluid/tests/unittests/npu/test_norm_op_npu.py
  python/paddle/fluid/tests/unittests/test_calc_gradient.py
  python/paddle/fluid/tests/unittests/test_eager_deletion_padding_rnn.py
  python/paddle/fluid/tests/unittests/test_imperative_auto_prune.py
  python/paddle/fluid/tests/unittests/test_imperative_ptb_rnn.py
  python/paddle/fluid/tests/unittests/test_imperative_save_load.py
  python/paddle/fluid/tests/unittests/test_imperative_save_load_v2.py
  python/paddle/fluid/tests/unittests/test_layers.py
  python/paddle/fluid/tests/unittests/test_norm_op.py
  python/paddle/fluid/tests/unittests/test_normalization_wrapper.py
  python/paddle/fluid/tests/unittests/test_sgd_op.py
  python/paddle/fluid/tests/unittests/test_split_op.py
  python/paddle/fluid/tests/unittests/test_static_save_load.py
  python/paddle/fluid/tests/unittests/xpu/test_sgd_op_xpu.py
  python/paddle/nn/utils/weight_norm_hook.py
Labels: contributor, status: proposed

#49055 修改了API文档的相关内容
  python/paddle/device/__init__.py
  python/paddle/device/cuda/__init__.py
  python/paddle/nn/utils/weight_norm_hook.py
  python/paddle/profiler/utils.py
  python/paddle/utils/dlpack.py
Labels: contributor, status: proposed

#48742 修复paddle.nn.ChannelShuffle等 API 的文档
  python/paddle/nn/functional/loss.py
  python/paddle/nn/functional/vision.py
  python/paddle/nn/layer/loss.py
  python/paddle/nn/layer/vision.py
Labels: contributor, status: proposed

#48990 fix english docs typo errors
  python/paddle/nn/functional/common.py
  python/paddle/nn/functional/loss.py
  python/paddle/nn/functional/vision.py
  python/paddle/nn/layer/common.py
  python/paddle/nn/layer/loss.py
  python/paddle/nn/layer/vision.py
Labels: contributor, status: proposed

#49057 [Dy2St] transforms.RandomCrop Support static mode
  python/paddle/tests/test_transforms_static.py
  python/paddle/vision/transforms/transforms.py
Labels: contributor

#49044 fix docstring
  python/paddle/fluid/dygraph/nn.py
  python/paddle/nn/decode.py
  python/paddle/nn/functional/loss.py
  python/paddle/nn/functional/norm.py
  python/paddle/nn/layer/loss.py
  python/paddle/nn/layer/norm.py
Labels: contributor, status: proposed

#47936 [Clean Fluid API]Remove API: unsqueeze, use paddle.unsqueeze to replace paddle.fluid.layers.unsqueeze
  python/paddle/fluid/layers/nn.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/seq2seq_dygraph_model.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/test_bmn.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/transformer_dygraph_model.py
  python/paddle/fluid/tests/unittests/ipu/test_unsqueeze_op_ipu.py
  python/paddle/fluid/tests/unittests/test_dynamic_rnn_stop_gradient.py
  python/paddle/fluid/tests/unittests/test_eager_deletion_while_op.py
  python/paddle/fluid/tests/unittests/test_layers.py
  python/paddle/fluid/tests/unittests/test_recurrent_op.py
Labels: contributor, status: proposed

#49131 [PHI Decoupling] move maxouting and matrix_bit_code from fluid to phi
  paddle/fluid/operators/math/CMakeLists.txt
  paddle/phi/kernels/cpu/hsigmoid_loss_grad.h
  paddle/phi/kernels/cpu/hsigmoid_loss_kernel.cc
  paddle/phi/kernels/funcs/CMakeLists.txt
  paddle/phi/kernels/funcs/matrix_bit_code.cc
  paddle/phi/kernels/funcs/matrix_bit_code.h
  paddle/phi/kernels/funcs/maxouting.cc
  paddle/phi/kernels/funcs/maxouting.cu
  paddle/phi/kernels/funcs/maxouting.h
  paddle/phi/kernels/impl/maxout_grad_kernel_impl.h
  paddle/phi/kernels/impl/maxout_kernel_impl.h
Labels: contributor, status: proposed

#49088 add diag_v2 op for xpu, test=kunlun
  cmake/external/xpu.cmake
  paddle/phi/backends/xpu/xpu2_op_list.cc
  paddle/phi/kernels/xpu/diag_kernel.cc
  python/paddle/fluid/tests/unittests/xpu/test_diag_v2_op_xpu.py
Labels: contributor, status: proposed

#49145 [Dy2St] 移除 declarative 接口
  python/paddle/fluid/data_feeder.py
  python/paddle/fluid/dygraph/base.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/bert_dygraph_model.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/seq2seq_dygraph_model.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/simnet_dygraph_model.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/test_assert.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/test_break_continue.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/test_cache_program.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/test_cast.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/test_cycle_gan.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/test_declarative.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/test_fetch_feed.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/test_ifelse.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/test_lac.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/test_lambda.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/test_len.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/test_list.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/test_loop.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/test_mobile_net.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/test_origin_info.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/test_partial_program.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/test_program_translator.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/test_ptb_lm.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/test_reinforcement_learning.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/test_save_inference_model.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/test_se_resnet.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/test_sentiment.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/test_tensor_shape.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/test_tsm.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/test_typehint.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/test_word2vec.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/yolov3.py
  python/paddle/fluid/tests/unittests/test_jit_save_load.py
  python/paddle/jit/__init__.py
  python/paddle/jit/api.py
  python/paddle/jit/dy2static/convert_call_func.py
  python/paddle/jit/dy2static/partial_program.py
Labels: contributor, status: proposed

#49132 [PHI decoupling] move gather_scatter_kernel from fluid to phi
  paddle/fluid/operators/CMakeLists.txt
  paddle/phi/kernels/CMakeLists.txt
  paddle/phi/kernels/cpu/put_along_axis_grad_kernel.cc
  paddle/phi/kernels/cpu/put_along_axis_kernel.cc
  paddle/phi/kernels/cpu/take_along_axis_grad_kernel.cc
  paddle/phi/kernels/cpu/take_along_axis_kernel.cc
  paddle/phi/kernels/funcs/CMakeLists.txt
  paddle/phi/kernels/funcs/gather_scatter_functor.cc
  paddle/phi/kernels/funcs/gather_scatter_functor.cu
  paddle/phi/kernels/funcs/gather_scatter_functor.h
  paddle/phi/kernels/gpu/put_along_axis_grad_kernel.cu
  paddle/phi/kernels/gpu/put_along_axis_kernel.cu
  paddle/phi/kernels/gpu/take_along_axis_grad_kernel.cu
  paddle/phi/kernels/gpu/take_along_axis_kernel.cu
Labels: contributor, status: not progressed

#49113 [Paddle Inference] Add add arg_min trt converter
  paddle/fluid/inference/api/analysis_predictor.cc
  paddle/fluid/inference/tensorrt/convert/CMakeLists.txt
  paddle/fluid/inference/tensorrt/convert/arg_min_op.cc
  paddle/fluid/inference/tensorrt/op_teller.cc
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_arg_min.py
Labels: contributor, status: proposed

#49139 [PHI decouple] move dropout_impl and cuda_graph_with_memory_pool from fluid to phi
  paddle/fluid/memory/allocation/allocator_facade.cc
  paddle/fluid/memory/allocation/stream_safe_cuda_allocator.cc
  paddle/fluid/memory/stream_safe_cuda_alloc_test.cu
  paddle/fluid/operators/cuda_graph_with_in_out.h
  paddle/fluid/operators/fused/fmha_ref.h
  paddle/fluid/operators/fused/fused_dropout_helper.h
  paddle/fluid/platform/cuda_graph_with_memory_pool.cc
  paddle/fluid/platform/cuda_graph_with_memory_pool.h
  paddle/fluid/platform/device/gpu/cuda/cuda_graph.h
  paddle/fluid/platform/device/gpu/gpu_info.cc
  paddle/fluid/pybind/pybind.cc
  paddle/phi/backends/gpu/cuda/cuda_graph.h
  paddle/phi/backends/gpu/cuda/cuda_graph_with_memory_pool.h
  paddle/phi/kernels/funcs/concat_and_split_functor.cu
  paddle/phi/kernels/funcs/dropout_impl.cu.h
  paddle/phi/kernels/funcs/dropout_impl_util.h
  paddle/phi/kernels/gpu/dropout_grad_kernel.cu
  paddle/phi/kernels/gpu/dropout_kernel.cu
  paddle/phi/kernels/gpudnn/conv_cudnn_v7.h
Labels: contributor, status: proposed

#49135 [CodeStyle][py2] cleanup some useless comments related to py2
  .pre-commit-config.yaml
  python/paddle/distributed/fleet/utils/http_server.py
  python/paddle/fluid/dataloader/dataloader_iter.py
  python/paddle/fluid/dataloader/worker.py
  python/paddle/fluid/dygraph/checkpoint.py
  python/paddle/fluid/framework.py
  python/paddle/fluid/incubate/fleet/utils/http_server.py
  python/paddle/fluid/multiprocess_utils.py
  python/paddle/fluid/reader.py
  tools/sampcd_processor.py
  tools/test_print_signatures.py
Labels: contributor, status: proposed

#49128 [Dy2St] transforms.RandomRotation Support static mode
  python/paddle/tests/test_transforms_static.py
  python/paddle/vision/transforms/functional_tensor.py
  python/paddle/vision/transforms/transforms.py
Labels: contributor

#49042 修复 paddle.static.load_from_file 等 API 英文文档
  python/paddle/static/input.py
  python/paddle/static/io.py
  python/paddle/static/nn/common.py
  python/paddle/sysconfig.py
Labels: contributor, status: proposed

#49153 disable set_value in kp *test=kunlun
  paddle/phi/kernels/xpu/set_value_grad_kernel.cc
  paddle/phi/kernels/xpu/set_value_kernel.cc
Labels: contributor, status: proposed

#49184 Add CMAKE_GENERATOR to protobuf
  cmake/external/protobuf.cmake
Labels: contributor, status: proposed

#49227 Enable identity_scale_op_clean_pass by default
  paddle/fluid/inference/api/paddle_pass_builder.cc
Labels: contributor, status: proposed

#49250 [XPU] fix exception in xpu executor
  paddle/fluid/framework/details/bind_threaded_ssa_graph_executor.cc
Labels: contributor

#48847 add sqaure_grad fp16 *test=kunlun
  paddle/phi/backends/xpu/xpu2_op_list.cc
  paddle/phi/kernels/xpu/activation_grad_kernel.cc
Labels: contributor, status: proposed

#49149 fix docstrings: paddle.nn.Conv3DTranspose, etc.
  python/paddle/nn/functional/common.py
  python/paddle/nn/functional/conv.py
  python/paddle/nn/functional/loss.py
  python/paddle/nn/layer/common.py
  python/paddle/nn/layer/conv.py
  python/paddle/nn/layer/loss.py
Labels: contributor, status: proposed

#49109 Fix docs(91-100)
  python/paddle/fluid/layers/sequence_lod.py
  python/paddle/static/nn/common.py
  python/paddle/static/nn/metric.py
  python/paddle/tensor/creation.py
  python/paddle/tensor/manipulation.py
Labels: contributor, status: proposed

#49069 support recompute for kunlun
  paddle/fluid/framework/details/bind_threaded_ssa_graph_executor.cc
  paddle/fluid/framework/generator.cc
  paddle/fluid/framework/generator.h
  paddle/fluid/platform/device_context.cc
  paddle/fluid/pybind/generator_py.cc
  paddle/phi/kernels/xpu/dropout_kernel.cc
  python/paddle/__init__.py
  python/paddle/distributed/fleet/recompute/recompute.py
  python/paddle/fluid/tests/unittests/collective/fleet/test_dygraph_recompute_for_eager.py
  python/paddle/fluid/tests/unittests/xpu/test_recompute_op_xpu.py
  python/paddle/framework/random.py
Labels: contributor, status: proposed

#49288 IdentityScaleOpCleanPass assert_var_not_persistable
  paddle/fluid/framework/ir/identity_scale_op_clean_pass.cc
Labels: contributor, status: proposed

#49171 fix dlrm qpsproblem
  paddle/phi/backends/xpu/xpu2_op_list.cc
  paddle/phi/kernels/xpu/embedding_grad_kernel.cc
  paddle/phi/kernels/xpu/log_softmax_grad_kernel.cc
  paddle/phi/kernels/xpu/log_softmax_kernel.cc
Labels: contributor, status: proposed

#49356 add unbind op for xpu
  paddle/phi/backends/xpu/xpu2_op_list.cc
  paddle/phi/kernels/xpu/unbind_kernel.cc
  python/paddle/fluid/tests/unittests/xpu/test_unbind_op_xpu.py
Labels: contributor, status: proposed

#48640 [CodeStyle][py36] update pypi doc
  python/paddle/README.md
  python/setup.py.in
  setup.py
Labels: contributor, status: proposed

#49336 xpu kernels support api int64 vector inputs, test=kunlun
  cmake/external/xpu.cmake
  paddle/phi/kernels/xpu/compare_kernel.cc
  paddle/phi/kernels/xpu/elementwise_add_kernel.cc
  paddle/phi/kernels/xpu/elementwise_divide_grad_kernel.cc
  paddle/phi/kernels/xpu/elementwise_divide_kernel.cc
  paddle/phi/kernels/xpu/elementwise_grad_kernel.cc
  paddle/phi/kernels/xpu/elementwise_kernel.cc
  paddle/phi/kernels/xpu/elementwise_multiply_grad_kernel.cc
  paddle/phi/kernels/xpu/elementwise_multiply_kernel.cc
  paddle/phi/kernels/xpu/elementwise_subtract_grad_kernel.cc
  paddle/phi/kernels/xpu/elementwise_subtract_kernel.cc
  paddle/phi/kernels/xpu/prod_kernel.cc
  paddle/phi/kernels/xpu/reduce_max_kernel.cc
  paddle/phi/kernels/xpu/reduce_mean_kernel.cc
  paddle/phi/kernels/xpu/reduce_min_kernel.cc
  paddle/phi/kernels/xpu/reduce_sum_kernel.cc
Labels: contributor

#48313 [MLU] cherry-pick from develop to release/2.4
  cmake/neuware.cmake
  paddle/fluid/imperative/prepared_operator.cc
  paddle/fluid/operators/collective/barrier_op_mlu.cc
  paddle/fluid/operators/collective/c_allgather_op_mlu.cc
  paddle/fluid/operators/detection/CMakeLists.txt
  paddle/fluid/operators/detection/prior_box_op_mlu.cc
  paddle/fluid/operators/detection/yolo_box_op_mlu.cc
  paddle/fluid/operators/dropout_op_mlu.cc
  paddle/fluid/operators/huber_loss_op_mlu.cc
  paddle/fluid/operators/mlu/mlu_baseop.cc
  paddle/fluid/operators/mlu/mlu_baseop.h
  paddle/fluid/operators/one_hot_v2_op_mlu.cc
  paddle/fluid/operators/optimizers/adam_op_mlu.cc
  paddle/fluid/operators/pool_op_mlu.cc
  paddle/fluid/operators/reduce_ops/reduce_max_op_mlu.cc
  paddle/fluid/operators/strided_slice_op_mlu.cc
  paddle/fluid/platform/device/mlu/device_context.cc
  paddle/fluid/platform/device/mlu/device_context.h
  paddle/fluid/platform/device/mlu/enforce.h
  paddle/fluid/platform/device/mlu/mlu_info.cc
  paddle/fluid/platform/device/mlu/mlu_info.h
  paddle/fluid/platform/profiler/profiler.cc
  python/paddle/fluid/tests/unittests/mlu/sync_batch_norm_op_mlu.py
  python/paddle/fluid/tests/unittests/mlu/test_collective_api_base_mlu.py
  python/paddle/fluid/tests/unittests/mlu/test_collective_base_mlu.py
  python/paddle/fluid/tests/unittests/mlu/test_dropout_op_mlu.py
  python/paddle/fluid/tests/unittests/mlu/test_grid_sampler_op_mlu.py
  python/paddle/fluid/tests/unittests/mlu/test_huber_loss_op_mlu.py
  python/paddle/fluid/tests/unittests/mlu/test_merged_adam_op_mlu.py
  python/paddle/fluid/tests/unittests/mlu/test_prior_box_op_mlu.py
  python/paddle/fluid/tests/unittests/mlu/test_reduce_sum_op_mlu.py
  python/paddle/fluid/tests/unittests/mlu/test_slice_op_mlu.py
  python/paddle/fluid/tests/unittests/mlu/test_softmax_with_cross_entropy_op_mlu.py
  python/paddle/fluid/tests/unittests/mlu/test_sync_batch_norm_base_mlu.py
  python/paddle/fluid/tests/unittests/mlu/test_sync_batch_norm_op_mlu_baseline.py
  python/paddle/fluid/tests/unittests/mlu/test_yolo_box_op_mlu.py
  tools/dockerfile/Dockerfile.mlu
Labels: contributor, status: proposed
