Repository PaddlePaddle/Paddle, pull requests merged in 2022-10, with the labels that each got.

#46608 Requantize to use Memory Desc in Tensors
  paddle/fluid/framework/data_layout_transform.cc
  paddle/fluid/framework/tensor_util.cc
  paddle/fluid/operators/mkldnn/requantize_mkldnn_op.cc
  paddle/fluid/operators/transfer_layout_op.h
  paddle/phi/kernels/funcs/data_layout_transform.cc
Labels: Intel, contributor

#46737 Update AUTHORS.md
  AUTHORS.md
Labels: contributor, status: proposed

#45488 fix some doc bug test=document_fix
  paddle/fluid/operators/activation_op.cc
  python/paddle/nn/functional/activation.py
  python/paddle/nn/functional/loss.py
  python/paddle/nn/layer/activation.py
  python/paddle/nn/layer/loss.py
Labels: contributor, status: proposed

#46585 [MLU] add mluops prior_box kernel
  paddle/fluid/operators/detection/CMakeLists.txt
  paddle/fluid/operators/detection/prior_box_op_mlu.cc
  paddle/fluid/operators/mlu/mlu_baseop.cc
  paddle/fluid/operators/mlu/mlu_baseop.h
  python/paddle/fluid/tests/unittests/mlu/test_prior_box_op_mlu.py
Labels: contributor, status: proposed

#46621 Enable hard_swish_grad unit test
  paddle/phi/kernels/onednn/activation_grad_kernel.cc
  python/paddle/fluid/tests/unittests/mkldnn/test_activation_mkldnn_op.py
Labels: Intel, contributor

#46747 [PHI] gaussian_random kernel fix accuracy drop
  paddle/phi/kernels/onednn/gaussian_random_kernel.cc
Labels: Intel, contributor

#46797 [MLU]fix unittest of sync_bn
  python/paddle/fluid/tests/unittests/mlu/sync_batch_norm_op_mlu.py
  python/paddle/fluid/tests/unittests/mlu/test_sync_batch_norm_base_mlu.py
Labels: contributor, status: proposed

#46765 fix numpy issue in codeblock examples for operators under python/padd…
  python/paddle/tensor/creation.py
  python/paddle/tensor/linalg.py
  python/paddle/tensor/logic.py
  python/paddle/tensor/manipulation.py
  python/paddle/tensor/math.py
  python/paddle/tensor/stat.py
Labels: contributor, status: proposed

#46111 【Hackathon No.56&38】deformable_conv_v1 算子实现 float16 数据类型支持&前向运行加速
  paddle/phi/kernels/cpu/deformable_conv_grad_kernel.cc
  paddle/phi/kernels/funcs/deformable_conv_functor.cc
  paddle/phi/kernels/funcs/deformable_conv_functor.cu
  paddle/phi/kernels/funcs/deformable_conv_functor.h
  paddle/phi/kernels/gpu/deformable_conv_grad_kernel.cu
  paddle/phi/kernels/gpu/deformable_conv_kernel.cu
  paddle/phi/kernels/impl/deformable_conv_grad_kernel_impl.h
  paddle/phi/kernels/impl/deformable_conv_kernel_impl.h
  python/paddle/fluid/tests/unittests/test_deformable_conv_v1_op.py
Labels: contributor, status: proposed

#45946 【Hackathon No.36】优化 lerp_grad op 在 GPU 上的计算性能
  paddle/phi/kernels/gpu/lerp_grad_kernel.cu
  paddle/phi/kernels/impl/broadcast_tensors_kernel_impl.h
  python/paddle/fluid/tests/unittests/test_lerp_op.py
Labels: contributor, status: proposed

#46139 [PHI] transpose2_grad op migration
  paddle/fluid/operators/mkldnn/transpose_mkldnn_op.cc
  paddle/phi/backends/onednn/onednn_reuse.h
  paddle/phi/kernels/onednn/transpose_grad_kernel.cc
  python/paddle/fluid/tests/unittests/test_transpose_op.py
Labels: Intel, contributor

#46422 [docs] add ipustrategy Hyperlink
  python/paddle/fluid/framework.py
  python/paddle/tensor/manipulation.py
Labels: contributor, status: proposed

#46426 【Hackathon No.10】新增 LogNormal API
  python/paddle/distribution/__init__.py
  python/paddle/distribution/kl.py
  python/paddle/distribution/lognormal.py
  python/paddle/distribution/normal.py
  python/paddle/distribution/transform.py
  python/paddle/distribution/transformed_distribution.py
  python/paddle/fluid/tests/unittests/distribution/test_distribution_lognormal.py
  python/paddle/fluid/tests/unittests/distribution/test_distribution_lognormal_static.py
  python/paddle/fluid/tests/unittests/distribution/test_distribution_multinomial_static.py
  python/paddle/fluid/tests/unittests/distribution/test_distribution_normal.py
  python/paddle/fluid/tests/unittests/distribution/test_distribution_transformed_distribution.py
Labels: PaddlePaddle Hackathon, contributor

#46725 [cherry-pick] [PHI] migrate softmax_grad kernel (#46257)
  paddle/fluid/operators/mkldnn/softmax_mkldnn_op.cc
  paddle/phi/backends/onednn/onednn_reuse.h
  paddle/phi/kernels/onednn/softmax_grad_kernel.cc
Labels: Intel, contributor

#46022 [Paddle-TRT] support new quant format from slim
  paddle/fluid/framework/ir/delete_quant_dequant_linear_op_pass.cc
  paddle/fluid/inference/api/paddle_pass_builder.cc
  paddle/fluid/inference/tensorrt/convert/matmul_v2_op.cc
  paddle/fluid/inference/tensorrt/op_teller.cc
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_matmul_v2.py
Labels: contributor

#46659 docs: fix typos in the docs
  README.md
Labels: contributor

#46738 [typo] correct typo errors in python\paddle\vision\datasets\cifar.py
  python/paddle/nn/functional/activation.py
  python/paddle/vision/datasets/cifar.py
  python/paddle/vision/transforms/transforms.py
Labels: contributor, status: proposed

#46739 [IPU] rm fp16 dtype_check in UTs
  python/paddle/fluid/tests/unittests/ipu/test_mixed_precision_inference_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_mixed_precision_training_ipu.py
Labels: contributor, status: proposed

#46726 [cherry-pick] [PHI] Migrate slice, slice_grad, split, pad and pad3d oneDNN kernels (#46101)
  paddle/fluid/operators/mkldnn/pad3d_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/slice_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/split_mkldnn_op.cc
  paddle/phi/backends/onednn/onednn_helper.h
  paddle/phi/backends/onednn/onednn_reuse.h
  paddle/phi/kernels/onednn/pad3d_kernel.cc
  paddle/phi/kernels/onednn/pad_kernel.cc
  paddle/phi/kernels/onednn/pad_kernel_impl.h
  paddle/phi/kernels/onednn/slice_grad_kernel.cc
  paddle/phi/kernels/onednn/slice_kernel.cc
  paddle/phi/kernels/onednn/split_kernel.cc
Labels: Intel, contributor

#46759 add function FindInputNameByVarName
  paddle/fluid/framework/ir/mkldnn/cpu_quantize_pass.cc
  paddle/fluid/framework/ir/mkldnn/cpu_quantize_squash_pass.cc
  paddle/fluid/framework/ir/mkldnn/scale_matmul_fuse_pass.cc
  paddle/fluid/platform/mkldnn_helper.h
Labels: Intel, contributor

#46827 remove comment
  paddle/phi/kernels/gpu/deformable_conv_grad_kernel.cu
Labels: contributor, status: proposed

#46757 Add fc residual pattern
  paddle/fluid/framework/ir/graph_pattern_detector.cc
  paddle/fluid/framework/ir/graph_pattern_detector.h
  paddle/fluid/framework/ir/mkldnn/cpu_quantize_pass.cc
  paddle/fluid/framework/ir/mkldnn/fc_elementwise_add_mkldnn_fuse_pass.cc
  paddle/fluid/framework/ir/mkldnn/fc_mkldnn_pass.cc
  paddle/fluid/framework/ir/mkldnn/fc_mkldnn_pass.h
Labels: Intel, contributor

#46706 [CodeStyle][F401] remove unused import in unittests/test_[u-z]
  python/paddle/fluid/tests/unittests/test_unbind_op.py
  python/paddle/fluid/tests/unittests/test_unfold_op.py
  python/paddle/fluid/tests/unittests/test_uniform_random_bf16_op.py
  python/paddle/fluid/tests/unittests/test_uniform_random_op.py
  python/paddle/fluid/tests/unittests/test_unique.py
  python/paddle/fluid/tests/unittests/test_unique_consecutive_op.py
  python/paddle/fluid/tests/unittests/test_unique_with_counts.py
  python/paddle/fluid/tests/unittests/test_unpool1d_op.py
  python/paddle/fluid/tests/unittests/test_unpool_op.py
  python/paddle/fluid/tests/unittests/test_var_info.py
  python/paddle/fluid/tests/unittests/test_variable.py
  python/paddle/fluid/tests/unittests/test_view_op_reuse_allocation.py
  python/paddle/fluid/tests/unittests/test_where_op.py
  python/paddle/fluid/tests/unittests/test_while_loop_op.py
  python/paddle/fluid/tests/unittests/test_while_op.py
  python/paddle/fluid/tests/unittests/test_yolo_box_op.py
  python/paddle/fluid/tests/unittests/test_zeros_like_op.py
  python/paddle/fluid/tests/unittests/test_zeros_op.py
Labels: contributor, status: proposed

#46793 [CodeStyle][F401] remove unused imports in unittests/distributed_passes,tokenizer,sequence
  python/paddle/fluid/tests/unittests/distributed_passes/auto_parallel_pass_test_base.py
  python/paddle/fluid/tests/unittests/distributed_passes/dist_pass_test_base.py
  python/paddle/fluid/tests/unittests/distributed_passes/pass_run_main.py
  python/paddle/fluid/tests/unittests/distributed_passes/ps_pass_test_base.py
  python/paddle/fluid/tests/unittests/distributed_passes/test_auto_parallel_amp_pass.py
  python/paddle/fluid/tests/unittests/distributed_passes/test_auto_parallel_data_parallel_optimization_pass.py
  python/paddle/fluid/tests/unittests/distributed_passes/test_auto_parallel_fp16_pass.py
  python/paddle/fluid/tests/unittests/distributed_passes/test_auto_parallel_gradient_merge_pass.py
  python/paddle/fluid/tests/unittests/distributed_passes/test_auto_parallel_recompute_pass.py
  python/paddle/fluid/tests/unittests/distributed_passes/test_auto_parallel_sharding_pass.py
  python/paddle/fluid/tests/unittests/distributed_passes/test_ps_server_pass.py
  python/paddle/fluid/tests/unittests/distributed_passes/test_ps_trainer_pass.py
  python/paddle/fluid/tests/unittests/sequence/test_sequence_first_step.py
  python/paddle/fluid/tests/unittests/sequence/test_sequence_last_step.py
  python/paddle/fluid/tests/unittests/sequence/test_sequence_mask.py
  python/paddle/fluid/tests/unittests/sequence/test_sequence_reshape.py
  python/paddle/fluid/tests/unittests/sequence/test_sequence_reverse.py
  python/paddle/fluid/tests/unittests/tokenizer/bert_tokenizer.py
  python/paddle/fluid/tests/unittests/tokenizer/tokenizer_utils.py
Labels: contributor, status: proposed

#46791 [CodeStyle][F401] remove unused imports in unittests/ipu
  python/paddle/fluid/tests/unittests/ipu/test_fill_constant_op_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_huber_loss_op_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_identity_loss_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_kldiv_loss_op_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_sigmoid_cross_entropy_with_logits_op_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_warpctc_op_ipu.py
Labels: contributor, status: proposed

#46717 [CodeStyle][F401] remove unused imports in fluid/tests/custom_*
  python/paddle/fluid/tests/custom_kernel/custom_kernel_dot_setup.py
  python/paddle/fluid/tests/custom_kernel/test_custom_kernel_dot.py
  python/paddle/fluid/tests/custom_op/custom_relu_setup.py
  python/paddle/fluid/tests/custom_op/test_check_abi.py
  python/paddle/fluid/tests/custom_op/test_custom_relu_op_jit.py
  python/paddle/fluid/tests/custom_op/test_custom_relu_op_setup.py
  python/paddle/fluid/tests/custom_op/test_custom_tanh_double_grad.py
  python/paddle/fluid/tests/custom_op/test_multi_out_jit.py
  python/paddle/fluid/tests/custom_op/utils.py
  python/paddle/fluid/tests/custom_runtime/custom_device_multi_process_collective.py
  python/paddle/fluid/tests/custom_runtime/process_group_xccl.py
  python/paddle/fluid/tests/custom_runtime/test_collective_process_group_xccl.py
  python/paddle/fluid/tests/custom_runtime/test_custom_cpu_plugin.py
  python/paddle/fluid/tests/custom_runtime/test_custom_cpu_profiler_plugin.py
  python/paddle/fluid/tests/custom_runtime/test_custom_cpu_to_static.py
Labels: contributor, status: proposed

#46716 [CodeStyle][F401] remove unused imports in fluid/tests/test_*, book
  python/paddle/fluid/tests/book/notest_understand_sentiment.py
  python/paddle/fluid/tests/book/test_image_classification.py
  python/paddle/fluid/tests/book/test_label_semantic_roles.py
  python/paddle/fluid/tests/book/test_recognize_digits.py
  python/paddle/fluid/tests/book/test_rnn_encoder_decoder.py
  python/paddle/fluid/tests/book/test_word2vec_book.py
  python/paddle/fluid/tests/test_beam_search_decoder.py
  python/paddle/fluid/tests/test_error_clip.py
Labels: contributor, status: proposed

#46718 [CodeStyle][F401] update flake8 F401 config (fluid/tests/)
  .flake8
Labels: contributor, status: proposed

#46707 [CodeStyle][F401] remove unused imports in unittests/fft_ps_rnn.
  python/paddle/fluid/tests/unittests/fft/spectral_op_np.py
  python/paddle/fluid/tests/unittests/fft/test_fft.py
  python/paddle/fluid/tests/unittests/fft/test_fft_with_static_graph.py
  python/paddle/fluid/tests/unittests/fft/test_spectral_op.py
  python/paddle/fluid/tests/unittests/ps/fl_ps_trainer.py
  python/paddle/fluid/tests/unittests/ps/ps_dnn_trainer.py
  python/paddle/fluid/tests/unittests/ps/test_fl_ps.py
  python/paddle/fluid/tests/unittests/ps/test_the_one_ps.py
  python/paddle/fluid/tests/unittests/rnn/convert.py
Labels: contributor, status: proposed

#46736 [CodeStyle] remove all future import.
  python/paddle/fluid/contrib/slim/tests/test_imperative_qat_lsq.py
  python/paddle/fluid/tests/unittests/mkldnn/test_fc_int8_mkldnn_op.py
  python/paddle/fluid/tests/unittests/mlu/test_huber_loss_op_mlu.py
  python/paddle/fluid/tests/unittests/mlu/test_yolo_box_op_mlu.py
  python/paddle/fluid/tests/unittests/xpu/test_index_select_op_xpu.py
  python/setup.py.in
Labels: contributor

#46754 [CodeStyle][F401] remove unused imports in python_paddle/proto_onnx_optimizer_hapi_autograd_framework.
  python/paddle/autograd/backward_mode.py
  python/paddle/framework/framework.py
  python/paddle/framework/io.py
  python/paddle/hapi/hub.py
  python/paddle/hapi/model.py
  python/paddle/hapi/static_flops.py
  python/paddle/optimizer/adadelta.py
  python/paddle/optimizer/adagrad.py
  python/paddle/optimizer/adam.py
  python/paddle/optimizer/adamax.py
  python/paddle/optimizer/lamb.py
  python/paddle/optimizer/momentum.py
  python/paddle/optimizer/optimizer.py
  python/paddle/optimizer/rmsprop.py
  python/paddle/optimizer/sgd.py
Labels: contributor, status: proposed

#46756 [CodeStyle][F401] update flake8 F401 config (python_paddle/proto,onnx,optimizer,hapi,autograd,framework,io,cost_model,geometric,vision,static).
  .flake8
Labels: contributor

#46698 [CodeStyle][F402] Change the loop variable name which is the same with an imported module
  python/paddle/fluid/tests/unittests/test_auto_parallel_partitioner.py
Labels: contributor, status: proposed

#46699 [CodeStyle][F402] Update flake8 F402 config
  .flake8
Labels: contributor, status: proposed

#46700 [CodeStyle][F541] Convert f-strings without curly braces to normal strings
  paddle/fluid/eager/auto_code_generator/generator/eager_gen.py
  python/paddle/distributed/fleet/elastic/manager.py
  python/paddle/distributed/fleet/utils/hybrid_parallel_inference.py
  python/paddle/fluid/tests/unittests/ipu/custom_ops/test_custom_ops_ipu.py
  python/paddle/fluid/tests/unittests/test_coalesce_tensor_op.py
  python/paddle/geometric/sampling/neighbors.py
  python/paddle/incubate/autograd/primx.py
  python/paddle/incubate/operators/graph_khop_sampler.py
  python/paddle/incubate/operators/graph_reindex.py
  python/paddle/incubate/operators/graph_sample_neighbors.py
  python/paddle/optimizer/optimizer.py
  python/paddle/tensor/einsum.py
  tools/gen_ut_cmakelists.py
Labels: contributor, status: proposed

#46702 [CodeStyle][W601] Replace .has_key() with 'in'
  tools/CrossStackProfiler/CspFileReader.py
  tools/CrossStackProfiler/ProfileFileReader.py
Labels: contributor, status: proposed

#46703 [CodeStyle][W601] Update flake8 config
  .flake8
Labels: contributor, status: proposed

#46719 [CodeStyle][F601] Remove repeated keys and only keep the last
  .cmake-format.py
  python/paddle/fluid/tests/unittests/ipu/test_ipu_strategy_ipu.py
  python/paddle/fluid/tests/unittests/xpu/test_pool2d_op_xpu.py
Labels: contributor, status: proposed

#46708 [CodeStyle][F632] Replace 'is' and 'is not' with == and != respectively
  python/paddle/distributed/parallel.py
  python/paddle/fluid/tests/custom_op/test_custom_relu_model.py
  python/paddle/fluid/tests/custom_op/test_custom_relu_op_setup.py
  python/paddle/fluid/tests/unittests/auto_parallel_gpt_model.py
  python/paddle/fluid/tests/unittests/test_auto_parallel_completion_gpt.py
  python/paddle/fluid/tests/unittests/test_auto_parallel_partitioner_gpt.py
  python/paddle/fluid/tests/unittests/test_lookup_table_bf16_op.py
  python/paddle/fluid/tests/unittests/test_max_min_amax_amin_op.py
  python/paddle/fluid/tests/unittests/test_parallel_executor_fetch_feed.py
  python/paddle/fluid/tests/unittests/test_real_imag_op.py
Labels: contributor, status: proposed

#46741 [CodeStyle][E714] Convert 'not ... is' to 'is not'
  tools/CrossStackProfiler/DCGMFileReader.py
  tools/CrossStackProfiler/NetFileReader.py
  tools/CrossStackProfiler/ProfileFileReader.py
Labels: contributor, status: proposed

#46734 [CodeStyle][E713] Convert 'not ... in ' into 'not in'
  python/paddle/distributed/fleet/launch_utils.py
  python/paddle/distributed/fleet/meta_optimizers/pipeline_optimizer.py
  python/paddle/distributed/fleet/utils/hybrid_parallel_inference.py
  python/paddle/distributed/ps/utils/public.py
  python/paddle/fluid/tests/unittests/mkldnn/test_clip_mkldnn_op.py
  python/paddle/fluid/tests/unittests/test_dropout_op.py
  python/paddle/fluid/tests/unittests/test_exponential_op.py
  python/paddle/fluid/tests/unittests/test_gaussian_random_op.py
  python/paddle/fluid/tests/unittests/test_multinomial_op.py
  python/paddle/fluid/tests/unittests/test_randint_op.py
  python/paddle/fluid/tests/unittests/test_uniform_random_op.py
  python/paddle/tensor/einsum.py
  tools/count_api_without_core_ops.py
  tools/infrt/get_compat_kernel_signature.py
  tools/infrt/print_kernel_pass_info.py
  tools/print_signatures.py
Labels: contributor, status: proposed

#46855 [CodeStyle][E713][E714] Remove E713,E714 code in .flake8 config
  .flake8
Labels: contributor, status: proposed

#46856 [CodeStyle][F631][F632] Remove F631,F632 in .flake8 config
  .flake8
Labels: contributor, status: proposed

#46745 [CodeStyle][F524] Add escape symbols to curly braces
  python/paddle/distributed/auto_parallel/tuner/recorder.py
Labels: contributor, status: proposed

#46696 代码退场，清除了与python2相关的一些条件分支
  python/paddle/fluid/layers/rnn.py
  python/paddle/fluid/param_attr.py
  python/paddle/fluid/tests/unittests/test_fs_interface.py
  python/paddle/fluid/tests/unittests/test_imperative_data_loader_exit_func.py
  python/paddle/fluid/tests/unittests/test_imperative_data_loader_process.py
  python/paddle/nn/layer/rnn.py
  python/paddle/tests/test_callback_visualdl.py
  python/setup.py.in
  tools/prune_for_jetson.py
  tools/remove_grad_op_and_kernel.py
Labels: contributor, status: proposed

#46865 [IPU] update to sdk3.0
  tools/dockerfile/Dockerfile.ipu
Labels: contributor, status: proposed

#46813 fix crop shape None error
  python/paddle/fluid/tests/unittests/test_crop_op.py
  python/paddle/tensor/manipulation.py
Labels: contributor, status: proposed

#46686 [CodeStyle] remove compat module (long_type, int_type, get_exception_message, floor_division)
  python/paddle/compat.py
  python/paddle/fluid/core.py
  python/paddle/fluid/tests/unittests/dist_transformer.py
  python/paddle/fluid/tests/unittests/test_compat.py
  python/paddle/fluid/tests/unittests/test_dataset.py
  python/paddle/fluid/tests/unittests/test_exception.py
  python/paddle/fluid/tests/unittests/test_imperative_data_loader_exception.py
  python/paddle/fluid/tests/unittests/test_imperative_data_loader_exit_func.py
  python/paddle/fluid/tests/unittests/test_imperative_double_grad.py
  python/paddle/fluid/tests/unittests/test_imperative_signal_handler.py
  python/paddle/fluid/tests/unittests/test_lookup_table_op.py
  python/paddle/fluid/tests/unittests/test_lookup_table_v2_op.py
  python/paddle/fluid/tests/unittests/test_operator_desc.py
  python/paddle/fluid/tests/unittests/test_optimizer.py
  python/paddle/fluid/tests/unittests/test_prune.py
  python/paddle/fluid/tests/unittests/test_zeros_op.py
  python/paddle/fluid/tests/unittests/xpu/test_lookup_table_v2_op_xpu.py
Labels: contributor, status: proposed

#46804 [MLU] add masterparam support for mlu adamw.
  paddle/fluid/operators/optimizers/adam_op_mlu.cc
Labels: contributor, status: proposed

#46830 [MLU] add int64 support for allgather.
  paddle/fluid/operators/collective/c_allgather_op_mlu.cc
Labels: contributor, status: proposed

#46898 add author
  AUTHORS.md
Labels: contributor, status: proposed

#46897 [CodeStyle][E306] remove error code E306 in flake8 config
  .flake8
Labels: contributor, status: proposed

#46760 add logging to fc residual fuse pass
  paddle/fluid/framework/ir/mkldnn/fc_elementwise_add_mkldnn_fuse_pass.cc
  paddle/fluid/framework/ir/mkldnn/fc_elementwise_add_mkldnn_fuse_pass_tester.cc
Labels: Intel, contributor

#46857 [cherry-pick] [PHI] Enable hard_swish_grad unit test (#46621)
  paddle/phi/kernels/onednn/activation_grad_kernel.cc
  python/paddle/fluid/tests/unittests/mkldnn/test_activation_mkldnn_op.py
Labels: Intel, contributor

#46858 [cherry-pick] [PHI] gaussian_random kernel fix accuracy drop (#46747)
  paddle/phi/kernels/onednn/gaussian_random_kernel.cc
Labels: Intel, contributor

#46709 [CodeStyle][F401] update flake8 F401 config (unittest/fft,ps,rnn,white_list).
  .flake8
Labels: contributor, status: proposed

#46792 [CodeStyle][F401] update flake8 F401 config (unittests/npu,xpu,mlu,ipu)
  .flake8
  .pre-commit-config.yaml
Labels: contributor, status: proposed

#46712 [CodeStyle][F401] remove unused imports in unittests/r_cmake_paddle_tools.
  cmake/make_resource.py
  paddle/fluid/eager/auto_code_generator/generator/codegen_utils.py
  paddle/fluid/eager/auto_code_generator/generator/eager_gen.py
  paddle/fluid/eager/auto_code_generator/generator/python_c_gen.py
  paddle/fluid/inference/api/demo_ci/untar_model.py
  paddle/fluid/inference/tests/api/full_ILSVRC2012_val_preprocess.py
  paddle/fluid/inference/tests/api/test_detection_dataset_preprocess.py
  paddle/infrt/tests/models/abs_model.py
  paddle/infrt/tests/models/efficientnet-b4/net/utils.py
  paddle/phi/api/yaml/generator/api_gen.py
  paddle/phi/api/yaml/generator/backward_api_gen.py
  paddle/phi/api/yaml/generator/filters.py
  paddle/phi/api/yaml/generator/generate_op.py
  paddle/phi/api/yaml/generator/intermediate_api_gen.py
  paddle/phi/api/yaml/generator/ops_extra_info_gen.py
  paddle/phi/api/yaml/generator/parse_api.py
  paddle/phi/api/yaml/generator/parse_utils.py
  paddle/phi/api/yaml/generator/sparse_api_gen.py
  paddle/phi/api/yaml/generator/sparse_bw_api_gen.py
  paddle/phi/api/yaml/generator/strings_api_gen.py
  paddle/phi/api/yaml/generator/wrapped_infermeta_gen.py
  paddle/scripts/conda_build.py
  r/example/mobilenet.py
  tools/CrossStackProfiler/CspChromeTraceFormatter.py
  tools/CrossStackProfiler/CspFileReader.py
  tools/CrossStackProfiler/CspReporter.py
  tools/CrossStackProfiler/DCGMFileReader.py
  tools/CrossStackProfiler/NetFileReader.py
  tools/CrossStackProfiler/ProfileFileReader.py
  tools/analysisPyXml.py
  tools/check_api_source_without_core_ops.py
  tools/check_ut.py
  tools/codestyle/docstring_checker.py
  tools/codestyle/test_docstring_checker.py
  tools/count_api_without_core_ops.py
  tools/diff_unittest.py
  tools/externalError/spider.py
  tools/final_ut_parallel_rule.py
  tools/get_pr_ut.py
  tools/get_single_test_cov.py
  tools/get_ut_file_map.py
  tools/handle_h_cu_file.py
  tools/infrt/fake_models/multi_fc.py
  tools/infrt/generate_phi_kernel_dialect.py
  tools/infrt/get_compat_kernel_signature.py
  tools/infrt/get_phi_kernel_info.py
  tools/infrt/print_kernel_pass_info.py
  tools/parallel_UT_rule.py
  tools/print_signatures.py
  tools/pyCov_multithreading.py
  tools/sampcd_processor.py
  tools/summary_env.py
  tools/test_check_api_compatible.py
  tools/test_sampcd_processor.py
  tools/timeline.py
  tools/windows/get_prec_ut_list.py
Labels: contributor, status: proposed

#46711 [CodeStyle][F401] update flake8 F401 config (r,cmake,paddle,tools).
  .flake8
Labels: contributor, status: proposed

#46762 [CodeStyle][F401] remove unused imports in python_paddle/inference_device_profiler_text_metric_incubate_quantization_libs_audio_amp_jit.
  python/paddle/device/cuda/streams.py
  python/paddle/incubate/autograd/functional.py
  python/paddle/incubate/autograd/primreg.py
  python/paddle/incubate/autograd/primrules.py
  python/paddle/incubate/distributed/models/moe/gate/gshard_gate.py
  python/paddle/incubate/distributed/models/moe/gate/naive_gate.py
  python/paddle/incubate/distributed/models/moe/gate/switch_gate.py
  python/paddle/incubate/distributed/models/moe/grad_clip.py
  python/paddle/incubate/distributed/models/moe/moe_layer.py
  python/paddle/incubate/multiprocessing/reductions.py
  python/paddle/incubate/nn/functional/fused_matmul_bias.py
  python/paddle/incubate/nn/functional/fused_transformer.py
  python/paddle/incubate/nn/layer/fused_transformer.py
  python/paddle/incubate/operators/graph_khop_sampler.py
  python/paddle/incubate/operators/graph_reindex.py
  python/paddle/incubate/operators/graph_sample_neighbors.py
  python/paddle/incubate/operators/graph_send_recv.py
  python/paddle/incubate/operators/resnet_unit.py
  python/paddle/incubate/operators/softmax_mask_fuse.py
  python/paddle/incubate/operators/softmax_mask_fuse_upper_triangle.py
  python/paddle/incubate/optimizer/distributed_fused_lamb.py
  python/paddle/incubate/optimizer/functional/utils.py
  python/paddle/incubate/optimizer/lookahead.py
  python/paddle/incubate/optimizer/modelaverage.py
  python/paddle/incubate/passes/fuse_resnet_unit_pass.py
  python/paddle/incubate/sparse/binary.py
  python/paddle/incubate/sparse/creation.py
  python/paddle/incubate/sparse/multiary.py
  python/paddle/incubate/sparse/nn/functional/activation.py
  python/paddle/incubate/sparse/nn/functional/conv.py
  python/paddle/incubate/sparse/nn/functional/pooling.py
  python/paddle/incubate/sparse/nn/functional/transformer.py
  python/paddle/incubate/sparse/unary.py
  python/paddle/incubate/xpu/resnet_block.py
  python/paddle/metric/metrics.py
  python/paddle/profiler/profiler.py
  python/paddle/profiler/statistic_helper.py
  python/paddle/profiler/timer.py
  python/paddle/text/datasets/conll05.py
  python/paddle/text/datasets/movielens.py
  python/paddle/text/datasets/wmt14.py
  python/paddle/text/viterbi_decode.py
Labels: contributor, status: proposed

#46763 [CodeStyle][F401] update flake8 F401 config (python_paddle/inference,device,profiler,text,metric,incubate,quantization,libs,audio,amp,jit).
  .flake8
Labels: contributor, status: proposed

#46905 [CodeStyle][F401] remove unused imports in unittests/mkldnn
  python/paddle/fluid/tests/unittests/mkldnn/test_activation_bf16_mkldnn_op.py
  python/paddle/fluid/tests/unittests/mkldnn/test_activation_mkldnn_op.py
  python/paddle/fluid/tests/unittests/mkldnn/test_batch_norm_mkldnn_op.py
  python/paddle/fluid/tests/unittests/mkldnn/test_bilinear_interp_mkldnn_op.py
  python/paddle/fluid/tests/unittests/mkldnn/test_bilinear_interp_v2_mkldnn_op.py
  python/paddle/fluid/tests/unittests/mkldnn/test_cast_mkldnn_op.py
  python/paddle/fluid/tests/unittests/mkldnn/test_clip_mkldnn_op.py
  python/paddle/fluid/tests/unittests/mkldnn/test_concat_bf16_mkldnn_op.py
  python/paddle/fluid/tests/unittests/mkldnn/test_concat_mkldnn_op.py
  python/paddle/fluid/tests/unittests/mkldnn/test_conv2d_bf16_mkldnn_op.py
  python/paddle/fluid/tests/unittests/mkldnn/test_conv2d_mkldnn_op.py
  python/paddle/fluid/tests/unittests/mkldnn/test_conv2d_transpose_mkldnn_op.py
  python/paddle/fluid/tests/unittests/mkldnn/test_conv3d_mkldnn_op.py
  python/paddle/fluid/tests/unittests/mkldnn/test_expand_v2_mkldnn_op.py
  python/paddle/fluid/tests/unittests/mkldnn/test_fusion_gru_bf16_mkldnn_op.py
  python/paddle/fluid/tests/unittests/mkldnn/test_fusion_gru_int8_mkldnn_op.py
  python/paddle/fluid/tests/unittests/mkldnn/test_fusion_gru_mkldnn_op.py
  python/paddle/fluid/tests/unittests/mkldnn/test_fusion_lstm_bf16_mkldnn_op.py
  python/paddle/fluid/tests/unittests/mkldnn/test_fusion_lstm_int8_mkldnn_op.py
  python/paddle/fluid/tests/unittests/mkldnn/test_fusion_lstm_mkldnn_op.py
  python/paddle/fluid/tests/unittests/mkldnn/test_layer_norm_bf16_mkldnn_op.py
  python/paddle/fluid/tests/unittests/mkldnn/test_lrn_mkldnn_op.py
  python/paddle/fluid/tests/unittests/mkldnn/test_matmul_bf16_mkldnn_op.py
  python/paddle/fluid/tests/unittests/mkldnn/test_matmul_v2_mkldnn_op.py
  python/paddle/fluid/tests/unittests/mkldnn/test_mul_mkldnn_op.py
  python/paddle/fluid/tests/unittests/mkldnn/test_multi_gru_mkldnn_op.py
  python/paddle/fluid/tests/unittests/mkldnn/test_onnx_format_quantization_mobilenetv1.py
  python/paddle/fluid/tests/unittests/mkldnn/test_pool2d_int8_mkldnn_op.py
  python/paddle/fluid/tests/unittests/mkldnn/test_reduce_bf16_mkldnn_op.py
  python/paddle/fluid/tests/unittests/mkldnn/test_reduce_mkldnn_op.py
  python/paddle/fluid/tests/unittests/mkldnn/test_reshape_bf16_op.py
  python/paddle/fluid/tests/unittests/mkldnn/test_scale_bf16_mkldnn_op.py
  python/paddle/fluid/tests/unittests/mkldnn/test_scale_mkldnn_op.py
  python/paddle/fluid/tests/unittests/mkldnn/test_shape_mkldnn_op.py
  python/paddle/fluid/tests/unittests/mkldnn/test_shuffle_channel_mkldnn_op.py
  python/paddle/fluid/tests/unittests/mkldnn/test_slice_mkldnn_op.py
  python/paddle/fluid/tests/unittests/mkldnn/test_softplus_mkldnn_op.py
  python/paddle/fluid/tests/unittests/mkldnn/test_split_bf16_mkldnn_op.py
  python/paddle/fluid/tests/unittests/mkldnn/test_split_mkldnn_op.py
  python/paddle/fluid/tests/unittests/mkldnn/test_stack_mkldnn_op.py
  python/paddle/fluid/tests/unittests/mkldnn/test_sum_bf16_mkldnn_op.py
  python/paddle/fluid/tests/unittests/test_cuda_random_seed.py
  python/paddle/fluid/tests/unittests/test_dataset.py
  python/paddle/fluid/tests/unittests/test_exception.py
  python/paddle/fluid/tests/unittests/test_fs_interface.py
  python/paddle/fluid/tests/unittests/test_generator.py
  python/paddle/fluid/tests/unittests/test_imperative_data_loader_exception.py
  python/paddle/fluid/tests/unittests/test_imperative_data_loader_exit_func.py
  python/paddle/fluid/tests/unittests/test_imperative_data_loader_process.py
  python/paddle/fluid/tests/unittests/test_imperative_double_grad.py
  python/paddle/fluid/tests/unittests/test_imperative_signal_handler.py
  python/paddle/fluid/tests/unittests/test_lookup_table_op.py
  python/paddle/fluid/tests/unittests/test_lookup_table_v2_op.py
  python/paddle/fluid/tests/unittests/test_operator_desc.py
  python/paddle/fluid/tests/unittests/test_optimizer.py
  python/paddle/fluid/tests/unittests/test_prune.py
  python/paddle/fluid/tests/unittests/test_random_seed.py
  python/paddle/fluid/tests/unittests/test_zeros_op.py
Labels: contributor, status: proposed

#46732 [CodeStyle][F401] update flake8 F401 config (python/paddle/)
  .flake8
Labels: contributor, status: proposed

#46927 Update README_cn.md
  README_cn.md
Labels: contributor, status: proposed

#46944 [CodeStyle][F401] revert an import in sampcd_processor
  tools/sampcd_processor.py
Labels: contributor, status: proposed

#46926 [CodeStyle][F401] fix incremental flake8 F401 and F541 issues
  python/paddle/distributed/communication/stream/reduce_scatter.py
  python/paddle/distributed/communication/stream/scatter.py
  python/paddle/fluid/tests/unittests/collective/communication_stream_alltoall_api_dygraph.py
  python/paddle/fluid/tests/unittests/collective/communication_stream_alltoall_single_api_dygraph.py
  python/paddle/fluid/tests/unittests/collective/test_communication_stream_alltoall_api.py
  python/paddle/fluid/tests/unittests/collective/test_communication_stream_alltoall_single_api.py
  python/paddle/fluid/tests/unittests/collective/test_communication_stream_broadcast_api.py
  python/paddle/fluid/tests/unittests/collective/test_communication_stream_reduce_api.py
  python/paddle/fluid/tests/unittests/collective/test_communication_stream_reduce_scatter_api.py
  python/paddle/fluid/tests/unittests/collective/test_communication_stream_scatter_api.py
  python/paddle/fluid/tests/unittests/xpu/test_lookup_table_v2_op_xpu.py
  python/paddle/nn/layer/rnn.py
  python/paddle/tests/test_callback_visualdl.py
  tools/prune_for_jetson.py
  tools/remove_grad_op_and_kernel.py
Labels: contributor, status: proposed

#46923 [CodeStyle][py2] remove compat module (round)
  python/paddle/compat.py
  python/paddle/fluid/tests/unittests/test_compat.py
  python/paddle/fluid/tests/unittests/test_roi_pool_op.py
Labels: contributor, status: proposed

#46873 [cherry-pick] [PHI] transpose2_grad op migration (#46139)
  paddle/fluid/operators/mkldnn/transpose_mkldnn_op.cc
  paddle/phi/backends/onednn/onednn_reuse.h
  paddle/phi/kernels/onednn/transpose_grad_kernel.cc
  python/paddle/fluid/tests/unittests/test_transpose_op.py
Labels: Intel, contributor

#45595 【Paddle Hackathon No.11】
  python/paddle/fluid/tests/unittests/test_multimarginloss.py
  python/paddle/nn/__init__.py
  python/paddle/nn/functional/__init__.py
  python/paddle/nn/functional/loss.py
  python/paddle/nn/layer/__init__.py
  python/paddle/nn/layer/loss.py
Labels: PaddlePaddle Hackathon, contributor

#46836 Tests for other dtypes corrected
  python/paddle/fluid/tests/unittests/mkldnn/test_nearest_interp_mkldnn_op.py
  python/paddle/fluid/tests/unittests/mkldnn/test_nearest_interp_v2_mkldnn_op.py
Labels: Intel, contributor

#45817 【PaddlePaddle Hackathon 3 No.47】为 Paddle 新增 logsumexp support fp16
  paddle/phi/kernels/gpu/logsumexp_grad_kernel.cu
  paddle/phi/kernels/gpu/logsumexp_kernel.cu
  paddle/phi/kernels/impl/logsumexp_grad_kernel_impl.h
  paddle/phi/kernels/impl/logsumexp_kernel_impl.h
  python/paddle/fluid/tests/unittests/test_logsumexp.py
Labels: PaddlePaddle Hackathon, contributor

#46531 Fix build strategy
  paddle/fluid/framework/distributed_strategy.proto
Labels: NVIDIA, contributor

#46979 [Paddle-TRT][Cherry-Pick] support new quant format from slim (#46022)
  paddle/fluid/framework/ir/delete_quant_dequant_linear_op_pass.cc
  paddle/fluid/inference/api/paddle_pass_builder.cc
  paddle/fluid/inference/tensorrt/convert/matmul_v2_op.cc
  paddle/fluid/inference/tensorrt/op_teller.cc
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_matmul_v2.py
Labels: contributor, status: proposed

#47001 Fix hAPI bug of not compatible with LayerHook
  python/paddle/hapi/model.py
Labels: contributor, status: proposed

#46997 speed_up for deformable conv
  paddle/phi/kernels/impl/deformable_conv_kernel_impl.h
Labels: contributor, status: proposed

#44386 [IR Pass] Add Common Subexpression Elimination Pass
  paddle/fluid/framework/ir/CMakeLists.txt
  paddle/fluid/framework/ir/common_subexpression_elimination_pass.cc
  paddle/fluid/framework/ir/common_subexpression_elimination_pass.h
  paddle/fluid/framework/ir/common_subexpression_elimination_pass_tester.cc
  paddle/fluid/inference/api/paddle_pass_builder.cc
Labels: contributor, status: proposed

#46866 [Cherry-pick] [IPU] rm fp16 dtype_check
  python/paddle/fluid/tests/unittests/ipu/test_mixed_precision_inference_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_mixed_precision_training_ipu.py
Labels: contributor, status: proposed

#46867 [Cherry-pick] [IPU] fix ut timeout 2
  python/paddle/fluid/tests/unittests/ipu/CMakeLists.txt
  python/paddle/fluid/tests/unittests/ipu/op_test_ipu.py
Labels: contributor, status: proposed

#46892 [Cherry-pick][IPU] update to sdk3.0
  tools/dockerfile/Dockerfile.ipu
Labels: contributor, status: proposed

#47004 Fix bugs in the new dynamic diagram mode of XPU. test=kunlun
  paddle/phi/kernels/xpu/reduce_sum_grad_kernel.cc
Labels: contributor

#47035 [CodeStyle][py2] remove `compat` module (to_bytes)
  python/paddle/dataset/wmt16.py
  python/paddle/fluid/backward.py
  python/paddle/fluid/dygraph/dygraph_to_static/partial_program.py
  python/paddle/fluid/dygraph/io.py
  python/paddle/fluid/executor.py
  python/paddle/fluid/framework.py
  python/paddle/fluid/ir.py
  python/paddle/fluid/layers/control_flow.py
  python/paddle/fluid/tests/unittests/ir/inference/program_config.py
  python/paddle/fluid/tests/unittests/npu/test_run_program_op_npu.py
  python/paddle/fluid/tests/unittests/test_eager_run_program.py
  python/paddle/fluid/tests/unittests/test_protobuf_descs.py
  python/paddle/fluid/tests/unittests/test_pybind_interface.py
  python/paddle/fluid/tests/unittests/test_run_program_op.py
  python/paddle/incubate/autograd/primx.py
  python/paddle/text/datasets/wmt16.py
  tools/infrt/generate_pd_op_dialect_from_paddle_op_maker.py
  tools/print_op_desc.py
Labels: contributor

#47037 Fix for conv_bias_mkldnn_pass
  paddle/fluid/framework/ir/graph_pattern_detector.cc
Labels: Intel, contributor

#46694 [Hackathon 3rd No.22 ] add paddle.incubate.sparse.reshape
  paddle/phi/api/yaml/sparse_backward.yaml
  paddle/phi/api/yaml/sparse_ops.yaml
  paddle/phi/kernels/sparse/cpu/reshape_grad_kernel.cc
  paddle/phi/kernels/sparse/cpu/reshape_kernel.cc
  paddle/phi/kernels/sparse/cpu/sparse_utils_kernel.cc
  paddle/phi/kernels/sparse/gpu/reshape_grad_kernel.cu
  paddle/phi/kernels/sparse/gpu/reshape_kernel.cu
  paddle/phi/kernels/sparse/gpu/sparse_utils_kernel.cu
  paddle/phi/kernels/sparse/unary_grad_kernel.h
  paddle/phi/kernels/sparse/unary_kernel.h
  python/paddle/fluid/tests/unittests/test_sparse_reshape_op.py
  python/paddle/incubate/sparse/__init__.py
  python/paddle/incubate/sparse/unary.py
Labels: contributor

#46255 【Hackathon No.8】 add gumbel distribution api
  python/paddle/distribution/__init__.py
  python/paddle/distribution/gumbel.py
  python/paddle/distribution/transformed_distribution.py
  python/paddle/distribution/uniform.py
  python/paddle/fluid/tests/unittests/distribution/test_distribution_gumbel.py
  python/paddle/fluid/tests/unittests/distribution/test_distribution_gumbel_static.py
Labels: contributor, status: not progressed

#47045 Fix warning message format error
  paddle/phi/backends/dynload/dynamic_loader.cc
Labels: contributor, status: proposed

#47017 [hidden trouble] Update test_sparse_transpose_op.py to get rid of a hidden trouble.
  python/paddle/fluid/tests/unittests/test_sparse_transpose_op.py
Labels: contributor, status: not progressed

#46844 delete maybe unused code in paddle\phi\infermeta\sparse\unary.h
  paddle/phi/infermeta/sparse/unary.h
Labels: contributor, status: not progressed

#47041 [XPU] update xpu cmake to 1016. test=kunlun
  cmake/external/xpu.cmake
  paddle/phi/kernels/xpu/transpose_kernel.cc
Labels: contributor, status: proposed

#47036 [CodeStyle][py2] remove `compat` module (to_text)
  python/paddle/dataset/conll05.py
  python/paddle/dataset/movielens.py
  python/paddle/dataset/wmt14.py
  python/paddle/dataset/wmt16.py
  python/paddle/distributed/passes/ps_trainer_pass.py
  python/paddle/fluid/backward.py
  python/paddle/fluid/compiler.py
  python/paddle/fluid/contrib/slim/quantization/quantization_pass.py
  python/paddle/fluid/dygraph/io.py
  python/paddle/fluid/framework.py
  python/paddle/fluid/incubate/fleet/parameter_server/ir/trainer_pass.py
  python/paddle/fluid/io.py
  python/paddle/fluid/layers/control_flow.py
  python/paddle/fluid/tests/unittests/dist_transformer.py
  python/paddle/text/datasets/conll05.py
  python/paddle/text/datasets/movielens.py
  python/paddle/text/datasets/wmt14.py
  python/paddle/text/datasets/wmt16.py
Labels: contributor, status: proposed

#47009 Construct exec and ctx only once in cond op to speed up
  paddle/fluid/operators/controlflow/conditional_block_infer_op.cc
Labels: Intel

#46890 [CodeStyle][py2] remove future import in docstring
  python/paddle/distributed/spawn.py
Labels: contributor, status: proposed

#47066 [Cherry-Pick][Paddle-TRT]support shape tensor is the input of trt-subgraph
  paddle/fluid/inference/analysis/ir_pass_manager.cc
  paddle/fluid/inference/analysis/ir_passes/tensorrt_subgraph_pass.cc
  paddle/fluid/inference/api/analysis_predictor.cc
  paddle/fluid/inference/api/analysis_predictor.h
  paddle/fluid/inference/tensorrt/engine.cc
  paddle/fluid/inference/tensorrt/engine.h
  paddle/fluid/inference/tensorrt/test_dynamic_engine.cc
  paddle/fluid/inference/utils/io_utils.cc
  paddle/fluid/inference/utils/io_utils.h
  paddle/fluid/inference/utils/io_utils_tester.cc
  paddle/fluid/inference/utils/shape_range_info.proto
  paddle/fluid/operators/tensorrt/tensorrt_engine_op.h
Labels: contributor, status: proposed

#45183 FC + activation fuse passes
  paddle/fluid/framework/ir/mkldnn/fc_act_mkldnn_fuse_pass.cc
  paddle/fluid/framework/ir/mkldnn/fc_act_mkldnn_fuse_pass.h
  paddle/fluid/framework/ir/mkldnn/fc_act_mkldnn_fuse_pass_tester.cc
  paddle/fluid/framework/ir/op_compat_sensible_pass.cc
  paddle/fluid/operators/mkldnn/fc_mkldnn_op.cc
  python/paddle/fluid/tests/unittests/ir/inference/CMakeLists.txt
  python/paddle/fluid/tests/unittests/ir/inference/test_mkldnn_fc_mish_fuse_pass.py
  python/paddle/fluid/tests/unittests/ir/inference/test_onednn_fc_activation_fuse_pass.py
Labels: Intel

#47097 [CodeStyle][py2] fix a decode error caused by 47036
  python/paddle/fluid/framework.py
  python/paddle/fluid/tests/unittests/test_block_rename_var.py
  tools/static_mode_white_list.py
Labels: contributor, status: proposed

#46644 fix build warning: [Wsign-compare] on linux
  paddle/fluid/distributed/ps/table/common_graph_table.cc
  paddle/fluid/distributed/ps/table/memory_dense_table.cc
  paddle/fluid/distributed/ps/table/memory_sparse_table.cc
  paddle/fluid/distributed/ps/table/sparse_sgd_rule.cc
Labels: contributor, status: proposed

#47098 Reduce squeeze2_matmul_fuse_pass, flattent tests time
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_flatten.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_squeeze2_matmul_fuse_pass.py
Labels: NVIDIA, contributor

#47100 Loose TRT half test tolerance to 1e-3 (1)
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_anchor_generator.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_fc.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_fill_constant.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_grid_sampler.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_inverse.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_matmul_v2.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_pad3d.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_roi_align.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_scatter_nd_add.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_shape.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_shuffle_channel.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_stack.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_sum.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_top_k.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_top_k_v2.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_transpose.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_unary.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_unfold.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_unsqueeze2.py
Labels: NVIDIA, contributor

#47106 Loose TRT half test tolerance to 1e-3 (3)
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_expand_v2.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_reduce_sum.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_reshape.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_roll.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_slice.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_split.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_squeeze2.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_tile.py
Labels: NVIDIA, contributor

#47116 [CodeStyle] add more information when codestyle check failed
  tools/codestyle/pre_commit.sh
Labels: contributor, status: proposed

#46946 [CodeStyle][F403] expand star import
  python/paddle/__init__.py
  python/paddle/distributed/__init__.py
  python/paddle/distributed/fleet/base/meta_optimizer_factory.py
  python/paddle/distributed/fleet/elastic/collective.py
  python/paddle/distributed/fleet/launch.py
  python/paddle/distributed/fleet/meta_optimizers/ps_optimizer.py
  python/paddle/distributed/passes/__init__.py
  python/paddle/distributed/passes/ps_server_pass.py
  python/paddle/distributed/passes/ps_trainer_pass.py
  python/paddle/distributed/ps/the_one_ps.py
  python/paddle/distributed/ps/utils/ps_factory.py
  python/paddle/distributed/ps/utils/ps_program_builder.py
  python/paddle/fluid/tests/test_beam_search_decoder.py
  python/paddle/fluid/tests/unittests/collective/fleet/test_recv_save_op.py
  python/paddle/fluid/tests/unittests/distribution/test_distribution.py
  python/paddle/fluid/tests/unittests/distribution/test_distribution_categorical.py
  python/paddle/fluid/tests/unittests/distribution/test_distribution_normal.py
  python/paddle/fluid/tests/unittests/distribution/test_distribution_uniform.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/test_ifelse.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/test_origin_info.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/test_tsm.py
  python/paddle/fluid/tests/unittests/ps/ps_dnn_trainer.py
  python/paddle/fluid/tests/unittests/ps/test_fl_ps.py
  python/paddle/fluid/tests/unittests/ps/test_the_one_ps.py
  python/paddle/fluid/tests/unittests/test_dataloader_dataset.py
  python/paddle/fluid/tests/unittests/test_default_scope_funcs.py
  python/paddle/fluid/tests/unittests/test_dist_train.py
  python/paddle/fluid/tests/unittests/test_distributions.py
  python/paddle/fluid/tests/unittests/test_dynrnn_gradient_check.py
  python/paddle/fluid/tests/unittests/test_imperative_load_static_param.py
  python/paddle/fluid/tests/unittests/test_lazy_init.py
  python/paddle/fluid/tests/unittests/test_listen_and_serv_op.py
  python/paddle/profiler/profiler_statistic.py
Labels: contributor, status: not progressed

#46947 [CodeStyle][F403] remove error code E403 in flake8 config
  .flake8
Labels: contributor, status: proposed

#47026 [WIP]fix rpc compile bug
  CMakeLists.txt
  cmake/configure.cmake
  cmake/third_party.cmake
  paddle/fluid/distributed/CMakeLists.txt
  paddle/fluid/distributed/rpc/CMakeLists.txt
  paddle/fluid/pybind/CMakeLists.txt
  paddle/fluid/pybind/pybind.cc
  python/paddle/fluid/tests/unittests/CMakeLists.txt
Labels: contributor, status: proposed

#47137 fix macos clang warnings of [-Wformat]
  paddle/fluid/framework/details/nan_inf_utils_detail.cc
  paddle/fluid/operators/math/bloomfilter.h
Labels: contributor, status: proposed

#47163 [Wsign-compare] Close Wno-error=sign_compare
  paddle/fluid/pybind/CMakeLists.txt
Labels: contributor, status: proposed

#45952 PaddlePaddle Hackathon 3 No.45 & 46】：为 Paddle cumsum和logcumsumexp 支持 float16 数据类型
  paddle/phi/kernels/gpu/cum_kernel.cu
  paddle/phi/kernels/gpu/logcumsumexp_grad_kernel.cu
  paddle/phi/kernels/impl/logcumsumexp_grad_impl.h
  python/paddle/fluid/tests/unittests/test_cumsum_op.py
  python/paddle/fluid/tests/unittests/test_logcumsumexp_op.py
  python/paddle/tensor/math.py
Labels: contributor

#46752 [CodeStyle][W605] Add escape symbols to some strings
  paddle/fluid/eager/auto_code_generator/generator/codegen_utils.py
  python/paddle/dataset/common.py
  python/paddle/distributed/fleet/meta_parallel/sharding/group_sharded_optimizer_stage2.py
  python/paddle/distribution/gumbel.py
  python/paddle/distribution/laplace.py
  python/paddle/fluid/tests/unittests/ir/inference/test_conv_act_mkldnn_fuse_pass.py
  python/paddle/fluid/tests/unittests/ir/inference/test_conv_bias_mkldnn_fuse_pass.py
  python/paddle/fluid/tests/unittests/ir/inference/test_conv_elementwise_add2_act_fuse_pass.py
  python/paddle/fluid/tests/unittests/ir/inference/test_conv_elementwise_add_act_fuse_pass.py
  python/paddle/fluid/tests/unittests/ir/inference/test_conv_eltwiseadd_bn_fuse_pass.py
  python/paddle/fluid/tests/unittests/ir/inference/test_conv_transpose_bn_fuse_pass.py
  python/paddle/fluid/tests/unittests/ir/inference/test_conv_transpose_eltwiseadd_bn_fuse_pass.py
  python/paddle/fluid/tests/unittests/ir/inference/test_emb_eltwise_layernorm_fuse_pass.py
  python/paddle/fluid/tests/unittests/ir/inference/test_fc_elementwise_layernorm_fuse_pass.py
  python/paddle/fluid/tests/unittests/ir/inference/test_fc_fuse_pass.py
  python/paddle/fluid/tests/unittests/ir/inference/test_flatten2_matmul_fuse_pass.py
  python/paddle/fluid/tests/unittests/ir/inference/test_layer_norm_fuse_pass.py
  python/paddle/fluid/tests/unittests/ir/inference/test_map_matmul_to_mul_pass.py
  python/paddle/fluid/tests/unittests/ir/inference/test_map_matmul_v2_to_matmul_pass.py
  python/paddle/fluid/tests/unittests/ir/inference/test_map_matmul_v2_to_mul_pass.py
  python/paddle/fluid/tests/unittests/ir/inference/test_matmul_scale_fuse_pass.py
  python/paddle/fluid/tests/unittests/ir/inference/test_matmul_v2_scale_fuse_pass.py
  python/paddle/fluid/tests/unittests/ir/inference/test_mkldnn_depthwise_conv_pass.py
  python/paddle/fluid/tests/unittests/ir/inference/test_reshape2_matmul_fuse_pass.py
  python/paddle/fluid/tests/unittests/ir/inference/test_squeeze2_matmul_fuse_pass.py
  python/paddle/fluid/tests/unittests/ir/inference/test_transpose_flatten_concat_fuse_pass.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_flatten2_matmul_fuse_pass.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_squeeze2_matmul_fuse_pass.py
  python/paddle/fluid/tests/unittests/ir/inference/test_unsqueeze2_eltwise_fuse_pass.py
  python/paddle/incubate/nn/layer/fused_linear.py
  python/paddle/incubate/nn/layer/fused_transformer.py
  python/paddle/incubate/sparse/nn/functional/activation.py
  python/paddle/incubate/sparse/nn/layer/activation.py
  python/paddle/incubate/sparse/unary.py
  python/paddle/nn/functional/pooling.py
  python/paddle/profiler/profiler_statistic.py
  python/paddle/tensor/random.py
  tools/analysisPyXml.py
  tools/get_pr_ut.py
  tools/get_ut_file_map.py
  tools/infrt/generate_pd_op_dialect_from_paddle_op_maker.py
  tools/infrt/generate_phi_kernel_dialect.py
  tools/infrt/get_compat_kernel_signature.py
  tools/jetson_infer_op.py
  tools/prune_for_jetson.py
  tools/remove_grad_op_and_kernel.py
Labels: contributor, status: proposed

#46753 [CodeStyle][W605] Update .flake8 config
  .flake8
Labels: contributor, status: proposed

#47153 [Paddle-TRT][Cherry-Pick]Rewrite strided_slice converter using shape tensor
  paddle/fluid/inference/tensorrt/convert/strided_slice_op.cc
  paddle/fluid/operators/tensorrt/tensorrt_engine_op.h
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_strided_slice.py
Labels: contributor, status: proposed

#47192 support compiling: with_distribute=on and with_pscore=off
  paddle/fluid/pybind/CMakeLists.txt
Labels: contributor, status: proposed

#47181 log only if > 0
  paddle/fluid/framework/ir/fc_gru_fuse_pass.cc
  paddle/fluid/framework/ir/layer_norm_fuse_pass.cc
  paddle/fluid/framework/ir/mkldnn/batch_norm_act_fuse_pass.cc
  paddle/fluid/framework/ir/mkldnn/conv_elementwise_add_mkldnn_fuse_pass.cc
  paddle/fluid/framework/ir/mkldnn/elt_act_mkldnn_fuse_pass.cc
  paddle/fluid/framework/ir/mkldnn/fc_elementwise_add_mkldnn_fuse_pass.cc
  paddle/fluid/framework/ir/mkldnn/matmul_activation_mkldnn_fuse_pass.cc
  paddle/fluid/framework/ir/mkldnn/matmul_elementwise_add_mkldnn_fuse_pass.cc
  paddle/fluid/framework/ir/mkldnn/scale_matmul_fuse_pass.cc
  paddle/fluid/framework/ir/mkldnn/softplus_activation_mkldnn_fuse_pass.cc
Labels: Intel, contributor

#47216 [CodeStyle] add -Werror=format for macos
  cmake/flags.cmake
Labels: contributor, status: proposed

#47228 add pdsa-2022-001, test=document_fix
  SECURITY.md
  SECURITY_cn.md
  security/README.md
  security/README_cn.md
  security/advisory/pdsa-2022-001.md
  security/advisory/pdsa-2022-001_cn.md
Labels: contributor, status: proposed

#47186 Fix the bug where the device memory address appears in abs_grad kernel fallback to CPU. test=kunlun
  paddle/phi/api/lib/api_custom_impl.cc
  paddle/phi/core/kernel_factory.cc
Labels: contributor

#47243 fix links, test=document_fix
  SECURITY.md
  SECURITY_cn.md
  security/README.md
  security/README_cn.md
  security/advisory/pdsa-2022-001.md
  security/advisory/pdsa-2022-001_cn.md
Labels: contributor, status: proposed

#47164 fix bug of abs_grad in eager mode for kunlun, test=kunlun
  paddle/phi/api/yaml/legacy_backward.yaml
  paddle/phi/kernels/cpu/abs_grad_kernel.cc
  paddle/phi/kernels/gpu/abs_grad_kernel.cu
  paddle/phi/kernels/xpu/abs_grad_kernel.cc
Labels: contributor

#47042 fix numpy issue in codeblock examples (test=document_fix)
  python/paddle/distributed/fleet/fleet.py
  python/paddle/regularizer.py
  python/paddle/tensor/manipulation.py
Labels: contributor, status: proposed

#47133 [IPU] fix runtime error
  paddle/fluid/framework/ir/ipu/infer_shape_pass.cc
  python/paddle/fluid/tests/unittests/ipu/op_test_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_transpose_op_ipu.py
Labels: contributor, status: proposed

#47034 [Paddle-TRT] fix conv2d
  paddle/fluid/inference/tensorrt/op_teller.cc
Labels: contributor, status: proposed

#47266 [CodeStyle][black] restore changes of PR-CI-Coverage in #46014
  paddle/scripts/paddle_build.sh
Labels: contributor, status: proposed

#47264 [CodeStyle] fix macos inconsistent-missing-override warnings and add -Werror
  cmake/flags.cmake
  paddle/fluid/eager/accumulation/accumulation_node.h
  paddle/fluid/eager/custom_operator/custom_operator_node.h
  paddle/fluid/framework/infershape_utils.h
  paddle/fluid/imperative/infer_var_type_context.h
  paddle/fluid/inference/api/analysis_predictor.h
  paddle/fluid/memory/allocation/auto_growth_best_fit_allocator_test.cc
  paddle/fluid/operators/cross_entropy_op.cc
  paddle/fluid/operators/decode_jpeg_op.cc
  paddle/fluid/operators/elementwise/elementwise_div_op.h
  paddle/fluid/operators/elementwise/elementwise_mul_op.h
  paddle/fluid/operators/elementwise/elementwise_op.h
  paddle/fluid/operators/inplace_abn_op.cc
  paddle/fluid/operators/optimizers/sgd_op.cc
  paddle/fluid/operators/pad2d_op.cc
Labels: contributor, status: proposed

#46743 [CodeStyle][F522] Remove unused arguments
  python/paddle/distributed/fleet/utils/fs.py
Labels: contributor, status: proposed

#47268 [CodeStyle][black] format dy2static unittests
  .pre-commit-config.yaml
  paddle/scripts/conda_build.py
  python/paddle/distributed/ps/utils/ps_program_builder.py
  python/paddle/fluid/tests/unittests/distributed_passes/test_build_cinn_pass_resnet.py
  python/paddle/fluid/tests/unittests/distributed_passes/test_build_cinn_pass_simple_net.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/test_build_strategy.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/test_error.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/test_origin_info.py
  python/paddle/fluid/tests/unittests/test_build_strategy_fusion_group_pass.py
  python/paddle/fluid/tests/unittests/test_pass_builder.py
  python/paddle/fluid/tests/unittests/test_signal.py
  tools/analysis_build_time.py
  tools/dockerfile/build_scripts/manylinux1-check.py
  tools/dockerfile/build_scripts/ssl-check.py
Labels: contributor, status: proposed

#47270 [CodeStyle][black] update flake8 config
  .flake8
Labels: contributor, status: proposed

#47283 Fix hAPI bug of not compatible with LayerHook (#47001)
  python/paddle/hapi/model.py
Labels: contributor, status: proposed

#47287 [CodeStyle][F522] Update .flake8 config
  .flake8
Labels: contributor, status: proposed

#47146 [CodeStyle] add black config to release2.4
  .pre-commit-config.yaml
  .style.yapf
  pyproject.toml
Labels: contributor, status: proposed

#47254 Fix compilation bug caused by incorrect log information
  paddle/fluid/framework/ir/fc_gru_fuse_pass.cc
  paddle/fluid/framework/ir/layer_norm_fuse_pass.cc
  paddle/fluid/framework/ir/mkldnn/batch_norm_act_fuse_pass.cc
  paddle/fluid/framework/ir/mkldnn/conv_elementwise_add_mkldnn_fuse_pass.cc
  paddle/fluid/framework/ir/mkldnn/elt_act_mkldnn_fuse_pass.cc
  paddle/fluid/framework/ir/mkldnn/fc_elementwise_add_mkldnn_fuse_pass.cc
  paddle/fluid/framework/ir/mkldnn/matmul_activation_mkldnn_fuse_pass.cc
  paddle/fluid/framework/ir/mkldnn/matmul_elementwise_add_mkldnn_fuse_pass.cc
  paddle/fluid/framework/ir/mkldnn/scale_matmul_fuse_pass.cc
  paddle/fluid/framework/ir/mkldnn/softplus_activation_mkldnn_fuse_pass.cc
Labels: status: not progressed

#47234 Fix for bias caching and scales computation optimization for oneDNN FC
  paddle/fluid/operators/mkldnn/fc_mkldnn_op.cc
Labels: Intel, contributor

#42469 【Hackathon No.6】implement nan_to_num
  python/paddle/__init__.py
  python/paddle/fluid/tests/unittests/test_nan_to_num_op.py
  python/paddle/tensor/__init__.py
  python/paddle/tensor/math.py
Labels: PaddlePaddle Hackathon, contributor

#47269 [CodeStyle][py2] remove `paddle.compat`
  python/paddle/__init__.py
  python/paddle/compat.py
  python/paddle/fluid/backward.py
  python/paddle/fluid/core.py
  python/paddle/fluid/dygraph/io.py
  python/paddle/fluid/framework.py
  python/paddle/fluid/layers/control_flow.py
  python/paddle/fluid/layers/detection.py
  python/paddle/fluid/optimizer.py
  python/paddle/fluid/tests/unittests/mlu/test_collective_api_base_mlu.py
  python/paddle/fluid/tests/unittests/mlu/test_collective_base_mlu.py
  python/paddle/fluid/tests/unittests/mlu/test_fill_constant_batch_size_like_op_mlu.py
  python/paddle/fluid/tests/unittests/mlu/test_sync_batch_norm_base_mlu.py
  python/paddle/fluid/tests/unittests/npu/test_collective_base_npu.py
  python/paddle/fluid/tests/unittests/npu/test_sync_batch_norm_base_npu.py
  python/paddle/fluid/tests/unittests/test_compat.py
Labels: contributor, status: proposed

#47309 [CodeStyle] fix braced-scalar-init warnings on macos
  cmake/flags.cmake
  paddle/fluid/eager/tests/task_tests/eager_utils_test.cc
  paddle/fluid/imperative/prepared_operator.h
  paddle/phi/ops/compat/concat_sig.cc
Labels: contributor

#47297 [CodeStyle][E231] remove unnecessary `,`
  python/paddle/fluid/tests/unittests/distributed_passes/ps_pass_test_base.py
  python/paddle/fluid/tests/unittests/test_layer_norm_op.py
  python/paddle/fluid/tests/unittests/test_set_value_op.py
Labels: contributor

#47298 [CodeStyle][E231] update flake8 config
  .flake8
Labels: contributor, status: proposed

#47314 Minor oneDNN split optimization
  paddle/phi/kernels/onednn/split_kernel.cc
Labels: Intel

#47208 export all symbols for phi_function_api
  paddle/fluid/inference/CMakeLists.txt
Labels: contributor, status: proposed

#47070 [Hackathon No.10] Add unit tests for Normal
  python/paddle/fluid/tests/unittests/distribution/test_distribution_normal.py
Labels: contributor, status: proposed

#47080 Added workaround for elementwise oneDNN kernel
  paddle/fluid/operators/elementwise/mkldnn/elementwise_mkldnn_op.h
  paddle/phi/backends/onednn/onednn_reuse.h
Labels: Intel, contributor

#47252 [Wsign-compare] Close Wno-error of sign-compare
  paddle/fluid/distributed/CMakeLists.txt
  paddle/fluid/distributed/ps/table/common_graph_table.cc
  paddle/fluid/distributed/rpc/CMakeLists.txt
  paddle/fluid/distributed/test/brpc_utils_test.cc
  paddle/fluid/distributed/test/graph_node_test.cc
Labels: contributor, status: proposed

#46918 Wandb callback
  python/paddle/callbacks.py
  python/paddle/hapi/callbacks.py
  python/paddle/tests/CMakeLists.txt
  python/paddle/tests/test_callback_wandb.py
  python/paddle/tests/test_utils_lazyimport.py
  python/paddle/utils/lazy_import.py
  python/unittest_py/requirements.txt
Labels: contributor, status: proposed

#47127 FC/matmul(v2) + scale fuse pass
  paddle/fluid/framework/ir/CMakeLists.txt
  paddle/fluid/framework/ir/mkldnn/operator_scale_onednn_fuse_pass.cc
  paddle/fluid/framework/ir/mkldnn/operator_scale_onednn_fuse_pass.h
  paddle/fluid/inference/api/paddle_pass_builder.cc
  paddle/fluid/operators/mkldnn/fc_mkldnn_op.cc
  paddle/fluid/platform/mkldnn_reuse.h
  python/paddle/fluid/tests/unittests/ir/inference/test_mkldnn_matmul_activation_fuse_pass.py
  python/paddle/fluid/tests/unittests/ir/inference/test_mkldnn_matmul_v2_activation_fuse_pass.py
  python/paddle/fluid/tests/unittests/ir/inference/test_onednn_fc_activation_fuse_pass.py
Labels: Intel, contributor

#47311 Update of PHI transpose_grad
  paddle/phi/backends/onednn/onednn_reuse.h
  paddle/phi/kernels/onednn/transpose_grad_kernel.cc
Labels: Intel, contributor, status: not progressed

#47285 Fix test_fused_dropout_act_bias failure on H100
  paddle/fluid/operators/fused/fused_dropout_act_bias.h
Labels: NVIDIA, contributor

#47399 [CodeStyle] fix pragma-pack warning on macos
  cmake/flags.cmake
  paddle/fluid/operators/math/bloomfilter.h
Labels: contributor, status: proposed

#47337 [Paddle-TRT] support multiclass_nms in int8 model
  paddle/fluid/inference/tensorrt/op_teller.cc
Labels: contributor, status: proposed

#47468 [CodeStyle] remove boost compiler flags in flags.cmake
  cmake/flags.cmake
  paddle/fluid/operators/dgc_op.h
  paddle/fluid/operators/mlu/mlu_baseop.cc
  paddle/fluid/operators/optimizers/dgc_momentum_op.h
  paddle/fluid/operators/reduce_ops/logsumexp_op_xpu.cc
  paddle/phi/kernels/cpu/layer_norm_kernel.cc
  paddle/phi/kernels/impl/logsumexp_grad_kernel_impl.h
  paddle/phi/kernels/impl/logsumexp_kernel_impl.h
Labels: contributor, status: proposed

#47477 fix typos for `True` and `False`
  paddle/fluid/framework/naive_executor.h
  paddle/fluid/memory/allocation/allocator_facade.cc
  paddle/fluid/operators/detection/yolo_box_op.cc
  paddle/fluid/operators/fused/fused_dropout_helper.h
  paddle/fluid/operators/select_op_helper.h
  paddle/fluid/operators/tensorrt/tensorrt_engine_op.h
  paddle/fluid/operators/unique_op.cc
  python/paddle/fluid/contrib/sparsity/asp.py
  python/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py
  python/paddle/fluid/dygraph/nn.py
  python/paddle/fluid/layers/control_flow.py
  python/paddle/fluid/layers/nn.py
  python/paddle/nn/layer/norm.py
  python/paddle/sparse/nn/layer/norm.py
  python/paddle/vision/ops.py
Labels: contributor, status: proposed

#47439 [MLU] fix compile error & add mlu blacklist function.
  paddle/fluid/imperative/prepared_operator.cc
  paddle/fluid/operators/strided_slice_op_mlu.cc
Labels: contributor, status: proposed
