Repository PaddlePaddle/Paddle, pull requests merged in 2022-06, with the labels that each got.

#42915 修复 paddle.ones 文档
  python/paddle/tensor/creation.py
Labels: contributor, status: proposed

#42912 修复 paddle.bernoulli 英文文档
  python/paddle/tensor/random.py
Labels: contributor, status: proposed

#43117 [MLU] add concat_grad mlu kernel.
  paddle/fluid/operators/concat_op_mlu.cc
Labels: contributor, status: proposed

#43094 [MLU] add mlu kernel for squeeze and squeeze2
  paddle/fluid/operators/squeeze_op_mlu.cc
  python/paddle/fluid/tests/unittests/mlu/test_squeeze2_op_mlu.py
  python/paddle/fluid/tests/unittests/mlu/test_squeeze_op_mlu.py
Labels: contributor, status: proposed

#43109 Fix for Bfloat16 placement pass.
  paddle/fluid/framework/ir/graph_pattern_detector.cc
Labels: Intel

#43201 delete duplicate code in set_state_dict in Paddle\python\paddle\optimizer\optimizer.py
  python/paddle/optimizer/optimizer.py
Labels: contributor, status: open review

#42942 修复 paddle.assign 等 API 的文档
  python/paddle/nn/functional/pooling.py
  python/paddle/nn/initializer/xavier.py
  python/paddle/nn/layer/pooling.py
  python/paddle/tensor/creation.py
  python/paddle/tensor/search.py
Labels: contributor, status: proposed

#43058 [MLU]support cast double type
  paddle/fluid/operators/cast_op_mlu.cc
  paddle/fluid/operators/mlu/mlu_baseop.h
  python/paddle/fluid/tests/unittests/mlu/test_cast_op_mlu.py
Labels: contributor, status: proposed

#43101 Allocate and use new memory for temp data in cumsum kernel
  paddle/phi/kernels/gpu/cumsum_kernel.cu
Labels: NVIDIA

#43184 Correct skip_quant condition
  paddle/fluid/framework/ir/mkldnn/compute_propagate_scales_mkldnn_pass.cc
  paddle/fluid/framework/ir/mkldnn/quant_dequant_mkldnn_pass.cc
  python/paddle/fluid/contrib/slim/quantization/quant2_int8_mkldnn_pass.py
Labels: Intel, int8

#43187 Optimized the performance of activation op in XPU2
  paddle/fluid/operators/optimizers/cast_with_ptr.h
  paddle/phi/kernels/funcs/elementwise_base.h
  paddle/phi/kernels/primitive/datamover_primitives.h
  paddle/phi/kernels/primitive/datamover_primitives_xpu2.h
Labels: contributor, status: proposed

#43198 Matmul post-ops for fuses
  paddle/fluid/operators/mkldnn/conv_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/conv_transpose_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/fc_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/matmul_mkldnn_op.cc
Labels: Intel, contributor

#43257 [cherry-pick] updated paddle_bfloat to v0.1.7
  python/requirements.txt
Labels: Intel, BF16

#43286 [MLU] add logical ops
  paddle/fluid/operators/controlflow/logical_op_mlu.cc
  paddle/fluid/operators/mlu/mlu_baseop.cc
  paddle/fluid/operators/mlu/mlu_baseop.h
  python/paddle/fluid/tests/unittests/mlu/test_logical_op_mlu.py
Labels: contributor, status: proposed

#41680 【Hackathon No.17】为 Paddle 新增 paddle.nn.CosineEmbeddingLoss 和 paddle.nn.functional.cosine_embedding_loss API
  python/paddle/fluid/tests/unittests/test_cosine_embedding_loss.py
  python/paddle/nn/__init__.py
  python/paddle/nn/functional/__init__.py
  python/paddle/nn/functional/loss.py
  python/paddle/nn/layer/loss.py
Labels: contributor, status: open review

#40698 【Hackathon No.13】为 Paddle 新增 CyclicLR 优化调度器
  python/paddle/fluid/tests/unittests/test_lr_scheduler.py
  python/paddle/optimizer/lr.py
Labels: contributor, status: open review

#43297 [Bug fix] Do not quantize weights Y when matmul X and Y both other ops outputs
  paddle/fluid/framework/ir/mkldnn/quant_dequant_mkldnn_pass.cc
Labels: Intel, contributor

#43344 add mlu gather_nd kernel
  paddle/fluid/operators/gather_nd_op_mlu.cc
  python/paddle/fluid/tests/unittests/mlu/test_gather_nd_op_mlu.py
Labels: contributor, status: proposed

#43271 [MLU] add mlu meshgrid kernel
  paddle/fluid/operators/meshgrid_op_mlu.cc
  python/paddle/fluid/tests/unittests/mlu/test_meshgrid_op_mlu.py
Labels: contributor, status: proposed

#43357 [MLU] add randperm kernel and reduce_prod kernel
  paddle/fluid/operators/randperm_op_mlu.cc
  paddle/fluid/operators/reduce_ops/reduce_prod_op_mlu.cc
  python/paddle/fluid/tests/unittests/mlu/test_randperm_op_mlu.py
  python/paddle/fluid/tests/unittests/mlu/test_reduce_prod_op_mlu.py
Labels: contributor, status: proposed

#42960 Re-implemented check_finite_and_unscale_op with newly added xdnn api
  paddle/fluid/operators/amp/check_finite_and_unscale_op_xpu.cc
  python/paddle/fluid/tests/unittests/xpu/test_amp_check_finite_and_scale_op_xpu.py
Labels: contributor, status: proposed

#43363 [IPU] add unary ops
  paddle/fluid/platform/device/ipu/popart_canonicalization/activation_ops.cc
  python/paddle/fluid/tests/unittests/ipu/test_activation_x_op_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_unary_ops_ipu.py
Labels: contributor, status: proposed

#43326 [MLU]add mlu kernel for sqrt op
  paddle/fluid/operators/activation_op_mlu.cc
  python/paddle/fluid/tests/unittests/mlu/test_sqrt_op_mlu.py
Labels: contributor, status: proposed

#42267 [Hackathon No.28] implement logcumsumexp
  paddle/fluid/operators/cum_op.cc
  paddle/phi/infermeta/unary.cc
  paddle/phi/infermeta/unary.h
  paddle/phi/kernels/cpu/cum_kernel.cc
  paddle/phi/kernels/cpu/cumsum_kernel.cc
  paddle/phi/kernels/cpu/logcumsumexp_grad_kernel.cc
  paddle/phi/kernels/cum_kernel.h
  paddle/phi/kernels/gpu/cum_kernel.cu
  paddle/phi/kernels/gpu/logcumsumexp_grad_kernel.cu
  paddle/phi/kernels/impl/logcumsumexp_grad_impl.h
  paddle/phi/kernels/logcumsumexp_grad_kernel.h
  paddle/phi/ops/compat/logcumsumexp_sig.cc
  python/paddle/__init__.py
  python/paddle/fluid/tests/unittests/CMakeLists.txt
  python/paddle/fluid/tests/unittests/test_logcumsumexp_op.py
  python/paddle/tensor/__init__.py
  python/paddle/tensor/math.py
  python/paddle/utils/code_gen/api.yaml
  python/paddle/utils/code_gen/backward.yaml
Labels: contributor, status: open review

#43292 [MLU]add mlu kernel for scatter op
  paddle/fluid/operators/scatter_op_mlu.cc
  python/paddle/fluid/tests/unittests/mlu/test_scatter_op_mlu.py
Labels: contributor, status: proposed

#43229 [MLU]add mlu kernel for clip
  paddle/fluid/operators/clip_op_mlu.cc
  paddle/fluid/operators/mlu/mlu_baseop.cc
  paddle/fluid/operators/mlu/mlu_baseop.h
  python/paddle/fluid/tests/unittests/mlu/test_clip_op_mlu.py
Labels: contributor, status: proposed

#40545 【Hachathon No.30】
  python/paddle/fluid/tests/unittests/test_triplet_margin_with_distance_loss.py
  python/paddle/nn/__init__.py
  python/paddle/nn/functional/__init__.py
  python/paddle/nn/functional/loss.py
  python/paddle/nn/layer/__init__.py
  python/paddle/nn/layer/loss.py
Labels: contributor, status: open review

#42916 Fix some en docs of paddle. and paddle.nn.initialize.
  python/paddle/fluid/initializer.py
  python/paddle/nn/initializer/constant.py
  python/paddle/nn/initializer/kaiming.py
  python/paddle/tensor/creation.py
  python/paddle/tensor/manipulation.py
  python/paddle/tensor/math.py
  python/paddle/tensor/random.py
  python/paddle/tensor/search.py
Labels: contributor, status: proposed

#43244 Enable bert model on CPU
  paddle/fluid/inference/tests/api/CMakeLists.txt
Labels: Intel, contributor

#43424 add split trt layer
  paddle/fluid/inference/tensorrt/convert/op_converter.h
  paddle/fluid/inference/tensorrt/convert/split_op.cc
  paddle/fluid/inference/tensorrt/engine.h
  paddle/fluid/inference/tensorrt/op_teller.cc
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_slice.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_split.py
Labels: contributor, status: proposed

#43366 [MLU]add lookup_table_v2 op and fix amp feature of bert with mlu device
  paddle/fluid/operators/amp/check_finite_and_unscale_op_mlu.cc
  paddle/fluid/operators/layer_norm_op_mlu.cc
  paddle/fluid/operators/lookup_table_v2_op_mlu.cc
  paddle/fluid/operators/mlu/mlu_baseop.cc
  paddle/fluid/operators/mlu/mlu_baseop.h
  paddle/fluid/operators/optimizers/adam_op_mlu.cc
  paddle/fluid/operators/softmax_op.cc
  python/paddle/fluid/tests/unittests/mlu/test_lookup_table_v2_op_mlu.py
Labels: contributor, status: proposed

#42929 Fix numpy 1.20+ deprecation warnings
  python/paddle/distributed/fleet/base/fleet_base.py
  python/paddle/distributed/fleet/meta_parallel/sharding/group_sharded_utils.py
  python/paddle/distributed/fleet/meta_parallel/sharding/sharding_utils.py
  python/paddle/fluid/data_feeder.py
  python/paddle/fluid/dygraph/amp/loss_scaler.py
  python/paddle/fluid/executor.py
  python/paddle/fluid/framework.py
  python/paddle/fluid/layers/nn.py
  python/paddle/fluid/reader.py
  python/paddle/fluid/tests/unittests/fft/test_fft.py
  python/paddle/fluid/tests/unittests/fft/test_fft_with_static_graph.py
  python/paddle/fluid/tests/unittests/ipu/test_assign_op_ipu.py
  python/paddle/fluid/tests/unittests/mkldnn/test_mul_int8_mkldnn_op.py
  python/paddle/fluid/tests/unittests/mkldnn/test_softmax_bf16_mkldnn_op.py
  python/paddle/fluid/tests/unittests/npu/test_box_coder_op_npu.py
  python/paddle/fluid/tests/unittests/npu/test_density_prior_box_op_npu.py
  python/paddle/fluid/tests/unittests/npu/test_fill_zeros_like_op_npu.py
  python/paddle/fluid/tests/unittests/npu/test_prior_box_op_npu.py
  python/paddle/fluid/tests/unittests/npu/test_reduce_max_op_npu.py
  python/paddle/fluid/tests/unittests/npu/test_reduce_min_op_npu.py
  python/paddle/fluid/tests/unittests/npu/test_reduce_prod_op_npu.py
  python/paddle/fluid/tests/unittests/npu/test_size_op_npu.py
  python/paddle/fluid/tests/unittests/npu/test_tril_triu_op_npu.py
  python/paddle/fluid/tests/unittests/npu/test_update_loss_scaling_min_op_npu.py
  python/paddle/fluid/tests/unittests/npu/test_update_loss_scaling_op_npu.py
  python/paddle/fluid/tests/unittests/op_test.py
  python/paddle/fluid/tests/unittests/test_assign_op.py
  python/paddle/fluid/tests/unittests/test_bipartite_match_op.py
  python/paddle/fluid/tests/unittests/test_box_coder_op.py
  python/paddle/fluid/tests/unittests/test_compare_op.py
  python/paddle/fluid/tests/unittests/test_density_prior_box_op.py
  python/paddle/fluid/tests/unittests/test_fuse_gemm_epilogue_pass.py
  python/paddle/fluid/tests/unittests/test_fused_multi_transformer_op.py
  python/paddle/fluid/tests/unittests/test_generate_mask_labels_op.py
  python/paddle/fluid/tests/unittests/test_kron_op.py
  python/paddle/fluid/tests/unittests/test_ones_like.py
  python/paddle/fluid/tests/unittests/test_prior_box_op.py
  python/paddle/fluid/tests/unittests/test_reduce_op.py
  python/paddle/fluid/tests/unittests/test_signal.py
  python/paddle/fluid/tests/unittests/test_update_loss_scaling_op.py
  python/paddle/fluid/tests/unittests/test_zeros_like_op.py
  python/paddle/fluid/tests/unittests/xpu/test_compare_op_xpu.py
  python/paddle/fluid/tests/unittests/xpu/test_prior_box_op_xpu.py
  python/paddle/fluid/tests/unittests/xpu/test_update_loss_scaling_op_xpu.py
  python/paddle/nn/layer/conv.py
  python/paddle/tensor/creation.py
  python/paddle/tensor/linalg.py
  python/paddle/tensor/logic.py
Labels: NVIDIA, contributor

#43311 [IPU]update paddle.distributed.launch
  python/paddle/distributed/launch/context/device.py
  python/paddle/distributed/launch/controllers/__init__.py
  python/paddle/distributed/launch/controllers/controller.py
  python/paddle/distributed/launch/controllers/ipu_controller.py
  python/paddle/distributed/launch/job/container.py
  python/paddle/distributed/launch/main.py
  python/paddle/distributed/launch/utils/process_context.py
  python/paddle/fluid/tests/unittests/ipu/distributed/run_dist_ipu.sh
  python/paddle/fluid/tests/unittests/ipu/distributed/test_dist_data_parallel_ipu.py
  python/paddle/fluid/tests/unittests/ipu/distributed/test_dist_pod128_sample.py
  python/paddle/fluid/tests/unittests/ipu/distributed/test_dist_sample.py
Labels: contributor, status: proposed

#43365 [MLU]: add elementwise_max mlu kernel
  paddle/fluid/operators/elementwise/elementwise_max_op_mlu.cc
  paddle/fluid/operators/elementwise/elementwise_mlu.h
  python/paddle/fluid/tests/unittests/mlu/test_elementwise_max_op_mlu.py
Labels: contributor, status: proposed

#43164 [IPU] Decoupling ipu sharding and modeling
  python/paddle/fluid/framework.py
  python/paddle/fluid/tests/unittests/ipu/test_set_ipu_shard_api.py
  python/paddle/static/__init__.py
Labels: contributor, status: proposed

#43435 [MLU] add bce kernel
  paddle/fluid/operators/mlu/mlu_baseop.cc
  paddle/fluid/operators/mlu/mlu_baseop.h
  paddle/fluid/operators/reduce_ops/reduce_sum_op_mlu.cc
  paddle/fluid/operators/sigmoid_cross_entropy_with_logits_op_mlu.cc
  python/paddle/fluid/tests/unittests/mlu/test_bce_with_logits_loss_mlu.py
  python/paddle/fluid/tests/unittests/mlu/test_sigmoid_cross_entropy_with_logits_op_mlu.py
Labels: contributor, status: proposed

#43467 [MLU] add bce_loss kernel for mlu
  paddle/fluid/operators/bce_loss_op_mlu.cc
  paddle/fluid/operators/mlu/mlu_baseop.cc
  paddle/fluid/operators/mlu/mlu_baseop.h
  python/paddle/fluid/tests/unittests/mlu/test_bce_loss_mlu.py
Labels: contributor, status: proposed

#43450 [MLU] add size kernel for mlu
  paddle/fluid/operators/size_op_mlu.cc
  python/paddle/fluid/tests/unittests/mlu/test_size_op_mlu.py
Labels: contributor, status: proposed

#43567 Fix for FC for quant model
  paddle/fluid/operators/mkldnn/fc_mkldnn_op.cc
Labels: Intel, int8, contributor

#43564 Revert md-in-tensor refactoring in Softmax Mkldnn Op
  paddle/fluid/operators/mkldnn/softmax_mkldnn_op.cc
Labels: Intel, contributor

#42782 [Inference] add squeeze2/unsqueeze2 trt layer
  paddle/fluid/inference/api/analysis_predictor.cc
  paddle/fluid/inference/tensorrt/convert/CMakeLists.txt
  paddle/fluid/inference/tensorrt/convert/squeeze2_op.cc
  paddle/fluid/inference/tensorrt/convert/unsqueeze2_op.cc
  paddle/fluid/inference/tensorrt/op_teller.cc
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_squeeze2.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_unsqueeze2.py
Labels: contributor, status: proposed

#43521 Unit test with tempfile to place the temporary files
  python/paddle/fluid/tests/custom_op/test_custom_relu_model.py
  python/paddle/fluid/tests/custom_op/test_custom_relu_op_setup.py
  python/paddle/fluid/tests/unittests/test_gpu_package_without_gpu_device.py
  python/paddle/fluid/tests/unittests/test_imperative_auto_mixed_precision.py
  python/paddle/fluid/tests/unittests/test_newprofiler.py
  python/paddle/fluid/tests/unittests/test_profiler.py
  python/paddle/fluid/tests/unittests/test_translated_layer.py
Labels: contributor, status: proposed

#43522 [cherry pick] Unit test with tempfile to place the temporary files
  python/paddle/fluid/tests/custom_op/test_custom_relu_model.py
  python/paddle/fluid/tests/custom_op/test_custom_relu_op_setup.py
  python/paddle/fluid/tests/unittests/test_gpu_package_without_gpu_device.py
  python/paddle/fluid/tests/unittests/test_imperative_auto_mixed_precision.py
  python/paddle/fluid/tests/unittests/test_newprofiler.py
  python/paddle/fluid/tests/unittests/test_profiler.py
  python/paddle/fluid/tests/unittests/test_translated_layer.py
Labels: contributor, status: proposed

#40487 [Hackathon No.26]
  python/paddle/fluid/tests/unittests/test_triplet_margin_loss.py
  python/paddle/nn/__init__.py
  python/paddle/nn/functional/__init__.py
  python/paddle/nn/functional/loss.py
  python/paddle/nn/layer/__init__.py
  python/paddle/nn/layer/loss.py
Labels: contributor, status: open review

#43537 fix paddle.Model en docs
  python/paddle/hapi/model.py
Labels: contributor, status: proposed

#43523 update ResNet en docs
  python/paddle/vision/models/resnet.py
Labels: contributor, status: not progressed

#43150 update api in creation.py and search.py; test=document_fix
  python/paddle/tensor/creation.py
  python/paddle/tensor/search.py
Labels: contributor, status: proposed

#41183 [PaddleHackathon No.14]
  python/paddle/fluid/tests/unittests/test_multi_label_soft_margin_loss.py
  python/paddle/nn/__init__.py
  python/paddle/nn/functional/__init__.py
  python/paddle/nn/functional/loss.py
  python/paddle/nn/layer/__init__.py
  python/paddle/nn/layer/loss.py
Labels: PaddlePaddle Hackathon, contributor, status: open review

#42380 fix en docs of paddle.vision.transforms.Normalize, paddle.vision.models.alexnet, paddle.vision.models.mobilenet, ops apis
  python/paddle/vision/models/alexnet.py
  python/paddle/vision/models/mobilenetv1.py
  python/paddle/vision/models/mobilenetv2.py
  python/paddle/vision/models/vgg.py
  python/paddle/vision/ops.py
  python/paddle/vision/transforms/transforms.py
Labels: contributor, status: proposed

#43347 [MLU]: add shape kernel
  paddle/fluid/operators/shape_op_mlu.cc
  python/paddle/fluid/tests/unittests/mlu/test_shape_op_mlu.py
Labels: contributor, status: proposed

#43491 [MLU]add elementwise_min op
  paddle/fluid/operators/elementwise/elementwise_min_op_mlu.cc
  paddle/fluid/operators/elementwise/elementwise_mlu.h
  paddle/fluid/platform/device/mlu/device_context.cc
  paddle/fluid/platform/device/mlu/device_context.h
  paddle/fluid/platform/device/mlu/mlu_info.cc
  paddle/fluid/platform/device/mlu/mlu_info.h
  python/paddle/fluid/tests/unittests/mlu/test_elementwise_min_op_mlu.py
Labels: contributor, status: proposed

#43503 [MLU] add mlu kernel for iou_similarity
  paddle/fluid/operators/detection/CMakeLists.txt
  paddle/fluid/operators/detection/iou_similarity_op_mlu.cc
  paddle/fluid/operators/mlu/mlu_baseop.cc
  paddle/fluid/operators/mlu/mlu_baseop.h
  python/paddle/fluid/tests/unittests/mlu/test_iou_similarity_op_mlu.py
Labels: contributor, status: proposed

#43353 [MLU]add mlu kernel for expand_v2 op
  paddle/fluid/operators/expand_v2_op.h
  paddle/fluid/operators/expand_v2_op_mlu.cc
  python/paddle/fluid/tests/unittests/mlu/test_expand_v2_op_mlu.py
Labels: contributor, status: proposed

#43389 [MLU]add mlu kernel for tile op
  paddle/fluid/operators/tile_op_functor.h
  paddle/fluid/operators/tile_op_mlu.cc
  python/paddle/fluid/tests/unittests/mlu/test_tile_op_mlu.py
Labels: contributor, status: proposed

#43441 [MLU]add mlu kernel for where op
  paddle/fluid/operators/mlu/mlu_baseop.cc
  paddle/fluid/operators/mlu/mlu_baseop.h
  paddle/fluid/operators/where_op_mlu.cc
  python/paddle/fluid/tests/unittests/mlu/test_where_op_mlu.py
Labels: contributor, status: proposed

#43575 [MLU] add truncated_gaussian_random kernel.
  paddle/fluid/operators/truncated_gaussian_random_op_mlu.cc
  python/paddle/fluid/tests/unittests/mlu/test_truncated_gaussian_random_op_mlu.py
Labels: contributor, status: proposed

#43632 Update CUDA and TensorRT
  paddle/fluid/inference/tests/infer_ut/run.sh
  tools/dockerfile/build_scripts/install_trt.sh
  tools/dockerfile/ci_dockerfile.sh
Labels: contributor, status: proposed

#43598 Revert "Revert md-in-tensor refactoring in Softmax Mkldnn Op "
  paddle/fluid/operators/mkldnn/softmax_mkldnn_op.cc
Labels: contributor, status: proposed

#43476 Fix for oneDNN layernorm for begin_norm_axis != last_dim
  paddle/fluid/operators/layer_norm_op.cc
  python/paddle/fluid/tests/unittests/mkldnn/test_layer_norm_mkldnn_op.py
Labels: Intel

#43588 [inference cherryy-pick] fix compile failing in cuda11.6
  paddle/fluid/inference/tensorrt/plugin/gather_nd_op_plugin.h
  paddle/fluid/inference/tensorrt/plugin/split_op_plugin.cu
  paddle/fluid/inference/tensorrt/plugin/split_op_plugin.h
Labels: contributor, status: proposed

#43608 [MLU] add mlu kernel for elementwise_max_grad
  paddle/fluid/operators/elementwise/elementwise_max_op_mlu.cc
  paddle/fluid/operators/elementwise/elementwise_min_op_mlu.cc
  paddle/fluid/operators/elementwise/elementwise_mlu.h
  python/paddle/fluid/tests/unittests/mlu/test_elementwise_max_op_mlu.py
Labels: contributor, status: proposed

#43630 [MLU] add deformable_conv kernel
  paddle/fluid/operators/deformable_conv_op_mlu.cc
  paddle/fluid/operators/mlu/mlu_baseop.cc
  paddle/fluid/operators/mlu/mlu_baseop.h
  python/paddle/fluid/tests/unittests/mlu/test_deformable_conv_op_mlu.py
Labels: contributor, status: proposed

#43693 Correct elementwise quantization
  paddle/fluid/framework/ir/graph_pattern_detector.cc
  paddle/fluid/framework/ir/graph_pattern_detector.h
  paddle/fluid/framework/ir/mkldnn/cpu_quantize_pass.cc
Labels: Intel, int8, contributor

#43382 Generalize conv+activation fuse pass
  paddle/fluid/framework/ir/mkldnn/conv_activation_mkldnn_fuse_pass.cc
  paddle/fluid/framework/ir/mkldnn/conv_activation_mkldnn_fuse_pass.h
  paddle/fluid/framework/ir/mkldnn/conv_activation_mkldnn_fuse_pass_tester.cc
  paddle/fluid/framework/ir/mkldnn/elt_act_mkldnn_fuse_pass.cc
  paddle/fluid/inference/api/paddle_pass_builder.cc
  paddle/fluid/inference/tests/api/analyzer_vit_ocr_tester.cc
  paddle/fluid/operators/elementwise/mkldnn/elementwise_mkldnn_op.h
  paddle/fluid/operators/mkldnn/conv_mkldnn_op.cc
  paddle/fluid/platform/mkldnn_reuse.h
  python/paddle/fluid/contrib/slim/quantization/quant2_int8_mkldnn_pass.py
  python/paddle/fluid/tests/unittests/ir/inference/test_conv_act_mkldnn_fuse_pass.py
  python/paddle/fluid/tests/unittests/ir/inference/test_mkldnn_conv_activation_fuse_pass.py
  python/paddle/fluid/tests/unittests/ir/inference/test_mkldnn_conv_gelu_fuse_pass.py
  python/paddle/fluid/tests/unittests/ir/inference/test_mkldnn_conv_hard_sigmoid_fuse_pass.py
  python/paddle/fluid/tests/unittests/ir/inference/test_mkldnn_conv_hard_swish_fuse_pass.py
  python/paddle/fluid/tests/unittests/ir/inference/test_mkldnn_conv_mish_fuse_pass.py
Labels: Intel, contributor

#43574 [MLU]: add argsort/argsort_grad kernel
  paddle/fluid/operators/argsort_op_mlu.cc
  paddle/fluid/operators/gather_op_mlu.cc
  paddle/fluid/operators/mlu/mlu_baseop.cc
  paddle/fluid/operators/mlu/mlu_baseop.h
  python/paddle/fluid/tests/unittests/mlu/test_argsort_op_mlu.py
Labels: contributor, status: proposed

#43393 add mlu expand_as_v2 kernel
  paddle/fluid/operators/expand_as_v2_op_mlu.cc
  python/paddle/fluid/tests/unittests/mlu/test_expand_as_v2_op_mlu.py
Labels: contributor, status: proposed

#43423 add mlu stack kernel
  paddle/fluid/operators/stack_op_mlu.cc
  python/paddle/fluid/tests/unittests/mlu/test_stack_op_mlu.py
Labels: contributor, status: proposed

#43624 add mlu arg_max kernel
  paddle/fluid/operators/arg_max_op_mlu.cc
  python/paddle/fluid/tests/unittests/mlu/test_arg_max_op_mlu.py
Labels: contributor, status: proposed

#43072 Fix cudnn error for BatchNorm1D kernel
  paddle/phi/kernels/gpu/batch_norm_grad_kernel.cu
  paddle/phi/kernels/gpu/batch_norm_kernel.cu
  python/paddle/fluid/tests/unittests/test_batch_norm_op_v2.py
Labels: contributor, status: proposed

#43642 [Cherry-pick] Update CUDA and TensorRT version for CI
  paddle/fluid/inference/tests/infer_ut/run.sh
  tools/dockerfile/build_scripts/install_trt.sh
  tools/dockerfile/ci_dockerfile.sh
Labels: contributor, status: proposed

#43648 [inference] add slice trt layer
  paddle/fluid/inference/tensorrt/convert/fc_op.cc
  paddle/fluid/inference/tensorrt/convert/multihead_matmul_op.cc
  paddle/fluid/inference/tensorrt/convert/op_converter.h
  paddle/fluid/inference/tensorrt/convert/slice_op.cc
  paddle/fluid/inference/tensorrt/engine.cc
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_slice.py
Labels: contributor, status: proposed

#42625 [external reviewing] Params to int8 pass
  paddle/fluid/framework/ir/CMakeLists.txt
  paddle/fluid/framework/ir/graph_pattern_detector.cc
  paddle/fluid/framework/ir/graph_pattern_detector.h
  paddle/fluid/framework/ir/mkldnn/params_quantization_mkldnn_pass.cc
  paddle/fluid/framework/ir/mkldnn/params_quantization_mkldnn_pass.h
  paddle/fluid/framework/ir/mkldnn/params_quantization_mkldnn_pass_tester.cc
  paddle/fluid/inference/api/mkldnn_quantizer.cc
  paddle/fluid/inference/tests/api/tester_helper.h
  paddle/fluid/operators/conv_op.cc
  paddle/fluid/operators/conv_op.h
  paddle/fluid/operators/mkldnn/conv_mkldnn_op.cc
  python/paddle/fluid/contrib/slim/quantization/quant2_int8_mkldnn_pass.py
  python/paddle/fluid/tests/unittests/ir/inference/auto_scan_test.py
Labels: Intel, int8, contributor

#43725 [cherry-pick] release/2.3 elementwise_mul and matmul mkldnn fix
  paddle/fluid/framework/ir/graph_pattern_detector.cc
  paddle/fluid/framework/ir/graph_pattern_detector.h
  paddle/fluid/framework/ir/mkldnn/cpu_quantize_pass.cc
  paddle/fluid/framework/ir/mkldnn/quant_dequant_mkldnn_pass.cc
Labels: Intel, contributor, status: proposed

#43670 Fix several unit tests and increase the unit tests stability
  paddle/fluid/platform/device_event_test.cc
  python/paddle/fluid/tests/unittests/CMakeLists.txt
  python/paddle/fluid/tests/unittests/test_collective_api_base.py
  python/paddle/fluid/tests/unittests/test_gather_op.py
Labels: NVIDIA, contributor, status: proposed

#43532 Fix 3 unittest errors
  paddle/fluid/operators/sparse_attention_op.cu
  python/paddle/fluid/tests/unittests/ir/test_fuse_resnet_unit.py
  python/paddle/fluid/tests/unittests/test_imperative_auto_mixed_precision.py
Labels: NVIDIA, contributor

#43659 Use fixed random seed
  python/paddle/fluid/tests/unittests/distribution/test_distribution_beta.py
Labels: NVIDIA, contributor

#43636 fix paddle.vision.models.* en
  python/paddle/vision/models/alexnet.py
  python/paddle/vision/models/densenet.py
  python/paddle/vision/models/googlenet.py
  python/paddle/vision/models/inceptionv3.py
  python/paddle/vision/models/lenet.py
  python/paddle/vision/models/mobilenetv1.py
  python/paddle/vision/models/mobilenetv2.py
  python/paddle/vision/models/mobilenetv3.py
  python/paddle/vision/models/resnet.py
  python/paddle/vision/models/shufflenetv2.py
  python/paddle/vision/models/squeezenet.py
  python/paddle/vision/models/vgg.py
Labels: contributor, status: proposed

#43649 fix paddle.vision.datasets.* en docs
  python/paddle/hapi/model.py
  python/paddle/vision/datasets/cifar.py
  python/paddle/vision/datasets/flowers.py
  python/paddle/vision/datasets/folder.py
  python/paddle/vision/datasets/mnist.py
  python/paddle/vision/datasets/voc2012.py
Labels: contributor, status: proposed

#43536 Fix elementwise_div UT by providing user defined gradients
  python/paddle/fluid/tests/unittests/test_elementwise_div_op.py
Labels: NVIDIA, contributor

#43750 [cherry-pick] Remove gpu_cpu_reshape2_matmul_fuse_pass in EnableMkldnn
  paddle/fluid/inference/api/paddle_pass_builder.cc
  paddle/fluid/inference/api/paddle_pass_builder.h
  python/paddle/fluid/contrib/slim/quantization/quant2_int8_mkldnn_pass.py
Labels: Intel, contributor

#43444 [MLU]add mlu kernel for tril_triu
  paddle/fluid/operators/mlu/mlu_baseop.cc
  paddle/fluid/operators/mlu/mlu_baseop.h
  paddle/fluid/operators/tril_triu_op_mlu.cc
  python/paddle/fluid/tests/unittests/mlu/test_tril_triu_op_mlu.py
Labels: contributor, status: proposed

#43615 [Inference] rewrite elementwise trt layer
  paddle/fluid/inference/tensorrt/convert/elementwise_op.cc
  paddle/fluid/inference/tensorrt/op_teller.cc
Labels: contributor, status: not progressed

#43743 add mlu label_smooth kernel
  paddle/fluid/operators/label_smooth_op_mlu.cc
  python/paddle/fluid/tests/unittests/mlu/test_label_smooth_op_mlu.py
Labels: contributor, status: proposed

#43687 [MLU]add mlu kernel for set_value op
  paddle/fluid/operators/set_value_op_mlu.cc
  python/paddle/fluid/tests/unittests/mlu/test_set_value_op_mlu.py
Labels: contributor, status: proposed

#43851 [Inference TRT] elementwise layer support
  paddle/fluid/inference/tensorrt/convert/elementwise_op.cc
  paddle/fluid/inference/tensorrt/convert/op_converter.h
  paddle/fluid/inference/tensorrt/engine.h
Labels: contributor, status: proposed

#43720 [MLU]add mlu kernel for where_index op
  paddle/fluid/operators/mlu/mlu_baseop.cc
  paddle/fluid/operators/mlu/mlu_baseop.h
  paddle/fluid/operators/where_index_op_mlu.cc
  python/paddle/fluid/tests/unittests/mlu/test_where_index_op_mlu.py
Labels: contributor, status: proposed

#43812 Apply IOU to test_parallel_executor_seresnext_base_gpu
  python/paddle/fluid/tests/unittests/parallel_executor_test_base.py
  python/paddle/fluid/tests/unittests/seresnext_test_base.py
  python/paddle/fluid/tests/unittests/test_fuse_all_reduce_pass.py
  python/paddle/fluid/tests/unittests/test_fuse_elewise_add_act_pass.py
  python/paddle/fluid/tests/unittests/test_fuse_optimizer_pass.py
  python/paddle/fluid/tests/unittests/test_fuse_relu_depthwise_conv_pass.py
  python/paddle/fluid/tests/unittests/test_ir_memory_optimize_pass.py
  python/paddle/fluid/tests/unittests/test_parallel_executor_mnist.py
  python/paddle/fluid/tests/unittests/test_parallel_executor_pg.py
  python/paddle/fluid/tests/unittests/test_parallel_executor_seresnext_base_gpu.py
  python/paddle/fluid/tests/unittests/test_parallel_executor_seresnext_with_reduce_cpu.py
Labels: NVIDIA, contributor

#43547 skip xpu conv2d fp16 unitest
  python/paddle/fluid/tests/unittests/xpu/test_conv2d_op_xpu.py
Labels: contributor, status: not progressed

#43894 [MLU] add rnn forward kernel.
  paddle/fluid/operators/mlu/mlu_baseop.cc
  paddle/fluid/operators/mlu/mlu_baseop.h
  paddle/fluid/operators/rnn_op_mlu.cc
  python/paddle/fluid/tests/unittests/mlu/test_rnn_op_mlu.py
Labels: contributor, status: proposed

#43852 [MLU] add exp and exp_grad kernel
  paddle/fluid/operators/activation_op_mlu.cc
  python/paddle/fluid/tests/unittests/mlu/test_exp_op_mlu.py
Labels: contributor, status: proposed

#43816 [MLU] add mlu kernel for masked_select
  paddle/fluid/operators/masked_select_op_mlu.cc
  paddle/fluid/operators/mlu/mlu_baseop.cc
  paddle/fluid/operators/mlu/mlu_baseop.h
  python/paddle/fluid/tests/unittests/mlu/test_masked_select_op_mlu.py
Labels: contributor, status: proposed

#43976 change email address in policy test=document_fix
  SECURITY.md
  SECURITY_cn.md
Labels: contributor, status: proposed
