Repository PaddlePaddle/Paddle, pull requests merged in 2022-07, with the labels that each got.

#43820 [MLU] add mlu kernel for fill_constant_batch_size_like
  paddle/fluid/operators/fill_constant_batch_size_like_op_mlu.cc
  python/paddle/fluid/tests/unittests/mlu/test_fill_constant_batch_size_like_op_mlu.py
Labels: contributor, status: proposed

#43460 Re-write the unit tests for compare xpu op
  python/paddle/fluid/tests/unittests/xpu/test_compare_op_xpu.py
Labels: contributor, status: proposed

#43931 Merge dimensions && OP performance optimization
  paddle/phi/kernels/gpu/cross_grad_kernel.cu
  paddle/phi/kernels/gpu/cross_kernel.cu
Labels: contributor, status: proposed

#44016 update paddle.distributed.launch en doc
  python/paddle/distributed/launch/main.py
Labels: contributor

#43973 Refactor quantization of immutable ops
  paddle/fluid/framework/ir/graph_pattern_detector.cc
  paddle/fluid/framework/ir/graph_pattern_detector.h
  paddle/fluid/framework/ir/mkldnn/cpu_quantize_pass.cc
  paddle/fluid/framework/ir/mkldnn/cpu_quantize_pass.h
  paddle/fluid/framework/ir/mkldnn/cpu_quantize_pass_tester.cc
Labels: Intel, int8

#43992 Fix for ernie3.0 int8
  paddle/fluid/operators/mkldnn/fc_mkldnn_op.cc
Labels: Intel, contributor, status: not progressed

#44078 Persuading more efficient memory format to be preferred
  paddle/fluid/platform/mkldnn_helper.h
  paddle/fluid/platform/mkldnn_utils.h
Labels: Intel, status: not progressed

#44045 [Paddle-TRT] fix stack_op_plugin bug
  paddle/fluid/inference/tensorrt/plugin/stack_op_plugin.cu
Labels: contributor, status: proposed

#44099 minor fix VLOG for xpu. test=kunlun.
  paddle/fluid/memory/allocation/naive_best_fit_allocator.cc
  paddle/phi/backends/xpu/xpu_context.cc
Labels: contributor, status: proposed

#44023 Set FC input data format to ANY
  paddle/fluid/operators/mkldnn/fc_mkldnn_op.cc
Labels: Intel, int8

#43803 Performance fix for recommender model
  paddle/fluid/operators/elementwise/mkldnn/elementwise_mkldnn_op.h
  paddle/fluid/operators/mkldnn/concat_mkldnn_op.cc
  paddle/fluid/operators/reduce_ops/reduce_op.h
  paddle/fluid/platform/mkldnn_reuse.h
  python/paddle/fluid/tests/unittests/mkldnn/test_elementwise_add_mkldnn_op.py
Labels: Intel, contributor

#44091 Optimized the performance of broadcast for kp XPU2
  paddle/phi/kernels/funcs/elementwise_base.h
  paddle/phi/kernels/primitive/datamover_primitives_xpu2.h
Labels: contributor, status: proposed

#44175 rmsprop for xpu. test=kunlun
  cmake/external/xpu.cmake
  paddle/fluid/operators/optimizers/rmsprop_op_xpu.cc
  paddle/fluid/platform/device/xpu/xpu2_op_list.h
  python/paddle/fluid/tests/unittests/white_list/no_check_set_white_list.py
  python/paddle/fluid/tests/unittests/xpu/test_rmsprop_op_xpu.py
Labels: contributor, status: proposed

#44185 Unify and generalize activation fuse passes
  paddle/fluid/framework/ir/graph_pattern_detector.cc
  paddle/fluid/framework/ir/graph_pattern_detector.h
  paddle/fluid/framework/ir/mkldnn/conv_activation_mkldnn_fuse_pass.cc
  paddle/fluid/framework/ir/mkldnn/conv_activation_mkldnn_fuse_pass.h
  paddle/fluid/framework/ir/mkldnn/elt_act_mkldnn_fuse_pass.cc
  paddle/fluid/framework/ir/mkldnn/elt_act_mkldnn_fuse_pass.h
  paddle/fluid/framework/ir/mkldnn/fc_act_mkldnn_fuse_pass.cc
  paddle/fluid/framework/ir/mkldnn/softplus_activation_mkldnn_fuse_pass.cc
  paddle/fluid/framework/ir/mkldnn/softplus_activation_mkldnn_fuse_pass.h
  paddle/fluid/operators/elementwise/mkldnn/elementwise_mkldnn_op.h
  paddle/fluid/operators/mkldnn/conv_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/softplus_mkldnn_op.h
  paddle/fluid/platform/mkldnn_reuse.h
  python/paddle/fluid/tests/unittests/ir/inference/test_mkldnn_softplus_activation_fuse_pass.py
Labels: Intel, contributor

#44124 Quantize shape operator
  paddle/fluid/framework/ir/graph_pattern_detector.h
  paddle/fluid/framework/ir/mkldnn/compute_propagate_scales_mkldnn_pass.cc
  paddle/fluid/framework/ir/mkldnn/cpu_quantize_pass.cc
  paddle/fluid/framework/ir/mkldnn/cpu_quantize_pass_tester.cc
  paddle/fluid/inference/api/mkldnn_quantizer.cc
  paddle/fluid/inference/api/mkldnn_quantizer_config.cc
  python/paddle/fluid/contrib/slim/quantization/quant2_int8_mkldnn_pass.py
Labels: Intel, int8

#44204 [IPU] support more ops 0/N
  paddle/fluid/framework/ir/ipu/optimizer_extract_pass.cc
  paddle/fluid/framework/ir/ipu/popart_canonicalization_pass.cc
  paddle/fluid/platform/device/ipu/ipu_compiler.cc
  paddle/fluid/platform/device/ipu/popart_canonicalization/canonicalization_utils.cc
  paddle/fluid/platform/device/ipu/popart_canonicalization/canonicalization_utils.h
  paddle/fluid/platform/device/ipu/popart_canonicalization/logic_ops.cc
  paddle/fluid/platform/device/ipu/popart_canonicalization/loss_ops.cc
  paddle/fluid/platform/device/ipu/popart_canonicalization/math_ops.cc
  paddle/fluid/platform/device/ipu/popart_canonicalization/op_builder.cc
  paddle/fluid/platform/device/ipu/popart_canonicalization/op_builder.h
  paddle/fluid/platform/device/ipu/popart_canonicalization/other_ops.cc
  paddle/fluid/platform/device/ipu/popart_canonicalization/reduce_ops.cc
  paddle/fluid/platform/device/ipu/supported_ops_autogen.h
Labels: contributor, status: proposed

#44205 [IPU] support more ops 1/N
  paddle/fluid/platform/device/ipu/popart_canonicalization/nn_ops.cc
  paddle/fluid/platform/device/ipu/popart_canonicalization/tensor_ops.cc
Labels: contributor, status: proposed

#44219 [MLU]: set numpy random seed for test_hard_sigmoid_op_mlu.py and test…
  python/paddle/fluid/tests/unittests/mlu/test_hard_sigmoid_op_mlu.py
  python/paddle/fluid/tests/unittests/mlu/test_hard_swish_op_mlu.py
Labels: contributor, status: proposed

#44230 [MLU] fix mlu ctest for bilinear, relu6 and squared_l2_norm
  python/paddle/fluid/tests/unittests/mlu/test_bilinear_interp_v2_op_mlu.py
  python/paddle/fluid/tests/unittests/mlu/test_relu6_op_mlu.py
  python/paddle/fluid/tests/unittests/mlu/test_squared_l2_norm_op_mlu.py
Labels: contributor, status: proposed

#44215 [MLU]add elementwise_pow op
  paddle/fluid/operators/elementwise/elementwise_mlu.h
  paddle/fluid/operators/elementwise/elementwise_pow_op_mlu.cc
  python/paddle/fluid/tests/unittests/mlu/test_elementwise_pow_op_mlu.py
Labels: contributor, status: proposed

#44176 [MLU]add sync_batch_norm op 1/2
  paddle/fluid/operators/CMakeLists.txt
  paddle/fluid/operators/mlu/mlu_baseop.cc
  paddle/fluid/operators/mlu/mlu_baseop.h
  paddle/fluid/operators/sync_batch_norm_op_mlu.cc
  python/paddle/fluid/tests/unittests/mlu/CMakeLists.txt
  python/paddle/fluid/tests/unittests/mlu/sync_batch_norm_op_mlu.py
Labels: contributor, status: proposed

#44178 [MLU]add sync_batch_norm op 2/2
  paddle/fluid/operators/scale_op_mlu.cc
  paddle/fluid/platform/device/mlu/device_context.cc
  python/paddle/fluid/tests/unittests/mlu/test_sync_batch_norm_base_mlu.py
  python/paddle/fluid/tests/unittests/mlu/test_sync_batch_norm_op_mlu_baseline.py
  python/paddle/fluid/tests/unittests/mlu/test_sync_batch_norm_op_mlu_extra.py
Labels: contributor, status: proposed

#44220 [MLU] fix expand_v2 scatter tile where ctest bugs
  python/paddle/fluid/tests/unittests/mlu/test_expand_v2_op_mlu.py
  python/paddle/fluid/tests/unittests/mlu/test_scatter_op_mlu.py
  python/paddle/fluid/tests/unittests/mlu/test_tile_op_mlu.py
  python/paddle/fluid/tests/unittests/mlu/test_where_op_mlu.py
Labels: contributor, status: proposed

#44227 add grid_sampler and update relu op for xpu.
  cmake/external/xpu.cmake
  paddle/fluid/operators/activation_op_xpu.cc
  paddle/fluid/operators/grid_sampler_op_xpu.cc
  paddle/fluid/platform/device/xpu/xpu2_op_list.h
  python/paddle/fluid/tests/unittests/xpu/test_grid_sampler_op_xpu.py
Labels: contributor, status: proposed

#43855 [MLU]add mlu kernel for reciprocal and reciprocal grad op
  paddle/fluid/operators/activation_op_mlu.cc
  python/paddle/fluid/tests/unittests/mlu/test_reciprocal_op_mlu.py
Labels: contributor, status: proposed

#44260 fix cpu lars_momentum bug & add xpu grad_add/log_softmax/log_softmax_…
  paddle/fluid/operators/optimizers/lars_momentum_op.h
  paddle/fluid/platform/device/xpu/xpu2_op_list.h
  paddle/phi/kernels/xpu/elementwise_add_kernel.cc
  paddle/phi/kernels/xpu/log_softmax_grad_kernel.cc
  paddle/phi/kernels/xpu/log_softmax_kernel.cc
  python/paddle/fluid/tests/unittests/xpu/get_test_cover_info.py
  python/paddle/fluid/tests/unittests/xpu/test_log_softmax_op_xpu.py
Labels: contributor, status: proposed

#44274 Zhusonghe
  paddle/fluid/operators/activation_op_xpu.cc
  paddle/fluid/platform/device/xpu/xpu2_op_list.h
Labels: contributor, status: proposed

#44306 添加账户及id MoYan 至 api approval 检查列表
  tools/check_api_approvals.sh
Labels: contributor, status: proposed

#44285 [IPU] clean unittest.skipIf 0/N
  python/paddle/fluid/tests/unittests/ipu/op_test_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_activation_ops_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_affine_channel_op_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_arg_max_op_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_arg_min_op_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_argsort_op_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_assign_op_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_avg_shard_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_batch_norm_op_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_binary_cross_entropy_op_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_bmm_op_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_cast_op_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_clip_op_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_concat_op_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_conv2d_transpose_op_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_conv_op_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_dy2static_fp16_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_dy2static_ipu.py
Labels: contributor, status: proposed

#44286 [IPU] clean unittest.skipIf 1/N
  python/paddle/fluid/tests/unittests/ipu/test_cross_entropy2_op_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_cumsum_op_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_data_norm_op_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_dist_op_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_dot_op_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_dropout_op_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_elemetwise_x_op_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_equal_op_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_eval_model_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_expand_as_v2_op_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_expand_op_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_expand_v2_op_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_fill_any_like_op_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_fill_constant_op_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_flatten_contiguous_range_op_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_flatten_op_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_flip_op_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_fp16_support_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_gather_op_ipu.py
Labels: contributor, status: proposed

#44287 [IPU] clean unittest.skipIf 2/N
  python/paddle/fluid/tests/unittests/ipu/test_gelu_op_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_gradient_clip_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_greater_op_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_groupnorm_op_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_huber_loss_op_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_inference_model_io_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_instancenorm_op_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_interpolate_ops_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_ipu_shard_api_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_ipu_strategy_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_kldiv_loss_op_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_layernorm_op_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_logical_not_op_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_logical_x_op_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_lookuptable_op_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_lookuptable_v2_op_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_lr_sheduler_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_matmul_op_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_matmul_serilize_ipu.py
Labels: contributor, status: proposed

#44290 [IPU] clean unittest.skipIf 3/N
  python/paddle/fluid/tests/unittests/ipu/test_matmul_v2_op_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_mean_op_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_meshgrid_op_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_mixed_precision_inference_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_mixed_precision_training_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_model_parallel_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_model_pipeline_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_mul_op_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_not_equal_op_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_one_hot_op_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_one_hot_v2_op_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_optimizer_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_p_norm_op_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_pad_op_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_pool_avg_op_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_pool_max_op_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_pow_op_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_prelu_op_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_print_op_ipu.py
Labels: contributor, status: proposed

#44289 [IPU] clean unittest.skipIf 4/N
  python/paddle/fluid/tests/unittests/ipu/test_reduce_x_op_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_reshape_inplace_op_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_reshape_op_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_save_load_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_scale_op_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_scaled_optimizer_state_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_set_batch_size_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_set_ipu_shard_api.py
  python/paddle/fluid/tests/unittests/ipu/test_slice_op_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_softmax_op_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_softmax_with_cross_entropy_op_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_split_op_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_squeeze_op_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_stack_op_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_sum_op_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_topk_op_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_transpose_op_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_unary_ops_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_unsqueeze_op_ipu.py
Labels: contributor, status: proposed

#44288 [IPU] clean unittest.skipIf 5/N
  python/paddle/fluid/tests/unittests/ipu/test_varname_inplace_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_warpctc_op_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_weight_decay_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_weight_sharing_ipu.py
Labels: contributor, status: proposed

#43530 Optimize batchnorm1d using 2D kernel
  paddle/phi/kernels/gpu/batch_norm_grad_kernel.cu
  paddle/phi/kernels/gpu/batch_norm_kernel.cu
  python/paddle/fluid/tests/unittests/test_batch_norm_op_v2.py
Labels: contributor, status: proposed

#44135 Fix random seed for several unit tests
  python/paddle/fluid/tests/unittests/autograd/test_autograd_functional_dynamic.py
  python/paddle/fluid/tests/unittests/test_functional_conv2d_transpose.py
  python/paddle/fluid/tests/unittests/test_lu_unpack_op.py
  python/paddle/fluid/tests/unittests/test_variable.py
Labels: NVIDIA

#44328 [IPU] add custom-op UTs 0/N
  python/paddle/fluid/tests/unittests/ipu/CMakeLists.txt
  python/paddle/fluid/tests/unittests/ipu/custom_ops/CMakeLists.txt
  python/paddle/fluid/tests/unittests/ipu/custom_ops/custom_checkpointoutput.cc
  python/paddle/fluid/tests/unittests/ipu/custom_ops/custom_detach.cc
  python/paddle/fluid/tests/unittests/ipu/custom_ops/custom_identity.cc
  python/paddle/fluid/tests/unittests/ipu/custom_ops/custom_nll.cc
  python/paddle/fluid/tests/unittests/ipu/custom_ops/deprecated/CMakeLists.txt
  python/paddle/fluid/tests/unittests/ipu/custom_ops/deprecated/custom_nllloss.cc
  python/paddle/fluid/tests/unittests/ipu/custom_ops/deprecated/test_custom_nllloss_ipu.py
  python/paddle/fluid/tests/unittests/ipu/custom_ops/test_checkpointoutput_ipu.py
  python/paddle/fluid/tests/unittests/ipu/custom_ops/test_custom_ops_ipu.py
Labels: contributor, status: proposed

#44314 [Paddle-TRT] reshape fill_constant
  paddle/fluid/inference/api/analysis_predictor.cc
  paddle/fluid/inference/tensorrt/convert/CMakeLists.txt
  paddle/fluid/inference/tensorrt/convert/fill_constant_op.cc
  paddle/fluid/inference/tensorrt/convert/reshape_op.cc
  paddle/fluid/inference/tensorrt/op_teller.cc
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_fill_constant.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_reshape.py
Labels: contributor, status: proposed

#44382 [Paddle-TRT] remove useless code in fc
  paddle/fluid/inference/tensorrt/convert/fc_op.cc
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_fc.py
Labels: contributor, status: proposed

#44312 [Paddle-TRT] Fix cast
  paddle/fluid/inference/tensorrt/op_teller.cc
Labels: contributor, status: proposed

#44297 add xpu resnet_unit
  cmake/external/xpu.cmake
  paddle/fluid/operators/fused/CMakeLists.txt
  paddle/fluid/operators/fused/resnet_unit_op.cc
  paddle/fluid/operators/fused/resnet_unit_op_xpu.cc
  paddle/fluid/platform/device/xpu/xpu2_op_list.h
  python/paddle/fluid/tests/unittests/xpu/get_test_cover_info.py
  python/paddle/incubate/operators/resnet_unit.py
Labels: contributor, status: proposed

#44404 [MLU] fix mlu ctest final.
  python/paddle/fluid/tests/unittests/mlu/test_c_comm_init_op_mlu.sh
  python/paddle/fluid/tests/unittests/mlu/test_hard_swish_op_mlu.py
  python/paddle/fluid/tests/unittests/mlu/test_spawn_mlu.py
Labels: contributor, status: proposed

#44394 [Paddle-TRT] Shape sum fix scale
  paddle/fluid/inference/api/analysis_predictor.cc
  paddle/fluid/inference/tensorrt/convert/CMakeLists.txt
  paddle/fluid/inference/tensorrt/convert/shape_op.cc
  paddle/fluid/inference/tensorrt/convert/sum_op.cc
  paddle/fluid/inference/tensorrt/op_teller.cc
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_shape.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_sum.py
Labels: contributor, status: proposed

#44279 add labels for infer ut
  paddle/fluid/inference/analysis/CMakeLists.txt
  python/paddle/fluid/tests/unittests/ir/CMakeLists.txt
  python/paddle/fluid/tests/unittests/ir/inference/CMakeLists.txt
Labels: contributor, status: not progressed

#43990 Added pad3d and pad2d FP32 FWD oneDNN kernels
  paddle/fluid/operators/mkldnn/pad3d_mkldnn_op.cc
  paddle/fluid/operators/pad2d_op.cc
  paddle/fluid/operators/pad3d_op.cc
  python/paddle/fluid/tests/unittests/ir/inference/test_mkldnn_pad2d_op.py
  python/paddle/fluid/tests/unittests/ir/inference/test_mkldnn_pad3d_op.py
Labels: Intel

#44414 [IPU] Add more Ops
  paddle/fluid/platform/device/ipu/popart_canonicalization/detection_ops.cc
  paddle/fluid/platform/device/ipu/popart_canonicalization/nn_ops.cc
  paddle/fluid/platform/device/ipu/popart_canonicalization/op_builder.cc
  paddle/fluid/platform/device/ipu/popart_canonicalization/op_builder.h
  paddle/fluid/platform/device/ipu/popart_canonicalization/tensor_ops.cc
Labels: contributor, status: proposed

#44367 [XPU][NPU] (1) add device_guard. (2) add support for LoDTensorArray of sum op.
  paddle/fluid/framework/new_executor/interpretercore_util.cc
  paddle/fluid/framework/operator.cc
  paddle/fluid/framework/operator.h
  paddle/fluid/operators/controlflow/while_op_helper.cc
  paddle/fluid/operators/sum_op_xpu.cc
  python/paddle/fluid/framework.py
  python/paddle/fluid/tests/unittests/xpu/test_device_guard_xpu.py
  python/paddle/fluid/tests/unittests/xpu/test_while_op_xpu.py
Labels: contributor, status: proposed

#44415 [IPU] add Op uts
  python/paddle/fluid/tests/unittests/ipu/test_pad_op_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_share_data_op_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_strided_slice_op_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_tile_op_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_unstack_op_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_where_op_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_yolo_box_op_ipu.py
Labels: contributor, status: proposed

#44478 Fix the bug of ModuleNotFound when compiling,test=document_fix
  paddle/scripts/paddle_build.sh
Labels: contributor, status: proposed

#44481 [Paddle-TRT] fix_fill_constant
  paddle/fluid/inference/tensorrt/convert/fill_constant_op.cc
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_fill_constant.py
Labels: contributor, status: proposed

#44475 [MLU] transpose avg_pool2d to NHWC for better performance.
  paddle/fluid/operators/pool_op_mlu.cc
Labels: contributor, status: proposed

#44521 fix arg_max to select first index
  paddle/fluid/operators/arg_max_op_mlu.cc
  python/paddle/fluid/tests/unittests/mlu/test_arg_max_op_mlu.py
Labels: contributor, status: proposed

#44498 [MLU] add floor kernel and grid_sampler kernel
  paddle/fluid/operators/activation_op_mlu.cc
  paddle/fluid/operators/grid_sampler_op_mlu.cc
  paddle/fluid/operators/mlu/mlu_baseop.cc
  paddle/fluid/operators/mlu/mlu_baseop.h
  paddle/fluid/platform/device/mlu/mlu_info.h
  python/paddle/fluid/tests/unittests/mlu/test_floor_op_mlu.py
  python/paddle/fluid/tests/unittests/mlu/test_grid_sampler_op_mlu.py
  tools/dockerfile/Dockerfile.mlu
Labels: contributor, status: proposed

#44448 add xpu lars_momentum/pow2_decay
  cmake/external/xpu.cmake
  paddle/fluid/operators/optimizers/lars_momentum_op_xpu.cc
  paddle/fluid/operators/optimizers/pow2_decay_with_linear_warmup_op_xpu.cc
  paddle/fluid/platform/device/xpu/xpu2_op_list.h
  python/paddle/fluid/tests/unittests/xpu/get_test_cover_info.py
  python/paddle/fluid/tests/unittests/xpu/test_coalesce_tensor_op_xpu.py
  python/paddle/fluid/tests/unittests/xpu/test_pow2_decay_with_linear_warmup_op_xpu.py
Labels: contributor, status: proposed

#42364 【Hackathon No.21】为 Paddle 新增 SoftMarginLoss
  python/paddle/fluid/tests/unittests/test_soft_margin_loss.py
  python/paddle/nn/__init__.py
  python/paddle/nn/functional/__init__.py
  python/paddle/nn/functional/loss.py
  python/paddle/nn/layer/__init__.py
  python/paddle/nn/layer/loss.py
Labels: contributor, status: proposed

#44552 [MLU]transpose convbpf output to HWCN for better performance
  paddle/fluid/operators/conv_op_mlu.cc
Labels: contributor, status: proposed

#44647 [IPU] fix ci on physical ipu
  python/paddle/fluid/tests/unittests/ipu/op_test_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_cast_op_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_groupnorm_op_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_interpolate_ops_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_meshgrid_op_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_mixed_precision_training_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_save_load_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_scaled_optimizer_state_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_weight_decay_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_yolo_box_op_ipu.py
Labels: contributor, status: proposed

#44646 [IPU] add more loss ops
  paddle/fluid/platform/device/ipu/popart_canonicalization/loss_ops.cc
  python/paddle/fluid/tests/unittests/ipu/test_dy2static_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_margin_rank_loss_op_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_rank_loss_op_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_sigmoid_cross_entropy_with_logits_op_ipu.py
Labels: contributor, status: proposed

#44648 [IPU] add g_ipuplace_pytype
  paddle/fluid/pybind/place.cc
Labels: contributor, status: proposed

#44656 [XPU] add top_k op
  cmake/external/xpu.cmake
  paddle/fluid/operators/top_k_op_xpu.cc
  paddle/fluid/platform/device/xpu/xpu2_op_list.h
  python/paddle/fluid/tests/unittests/xpu/test_top_k_op_xpu.py
Labels: contributor, status: proposed

#44355 Move api(lgamma) from legacy_api.yaml to api.yaml
  paddle/fluid/operators/lgamma_op.cc
  paddle/phi/api/yaml/api.yaml
  paddle/phi/api/yaml/api_compat.yaml
  paddle/phi/api/yaml/backward.yaml
  paddle/phi/api/yaml/legacy_api.yaml
  paddle/phi/api/yaml/legacy_backward.yaml
  paddle/phi/ops/compat/lgamma_sig.cc
  python/paddle/fluid/layers/ops.py
  python/paddle/fluid/tests/unittests/test_lgamma_op.py
  python/paddle/tensor/math.py
  python/paddle/tensor/ops.py
Labels: contributor, status: not progressed

#44669 [MLU] fix log_softmax mode selection.
  paddle/fluid/operators/softmax_op_mlu.cc
  python/paddle/fluid/tests/unittests/mlu/test_log_softmax_op_mlu.py
Labels: contributor, status: proposed

#44704 [XPU] add sampling_id op, add top_k op, update xdnn api
  cmake/external/xpu.cmake
  paddle/fluid/framework/tensor_util.h
  paddle/fluid/operators/detection/generate_proposals_v2_op_xpu.cc
  paddle/fluid/operators/one_hot_op_xpu.cc
  paddle/fluid/operators/sampling_id_op_xpu.cc
  paddle/fluid/platform/device/xpu/xpu2_op_list.h
  python/paddle/fluid/tests/unittests/xpu/test_one_hot_op_xpu.py
  python/paddle/fluid/tests/unittests/xpu/test_sampling_id_op_xpu.py
Labels: contributor, status: proposed

#44523 [MLU] add pytest for mlu strided_slice kernel
  python/paddle/fluid/tests/unittests/mlu/test_strided_slice_op_mlu.py
Labels: contributor, status: proposed

#44673 [IPU] update to sdk2.6.0
  paddle/fluid/platform/device/ipu/ipu_compiler.cc
  paddle/fluid/platform/device/ipu/ipu_executor.cc
  paddle/fluid/platform/device/ipu/ipu_executor.h
  paddle/fluid/platform/device/ipu/ipu_strategy.cc
  paddle/fluid/platform/device/ipu/supported_ops_autogen.h
  python/paddle/fluid/tests/unittests/ipu/custom_ops/leaky_relu_ipu.cc
  tools/dockerfile/Dockerfile.ipu
Labels: status: not progressed

#44640 [WIP] Matmul v1 & v2 unification -- part 1
  paddle/fluid/operators/mkldnn/matmul_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/matmul_v2_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/mul_mkldnn_op.cc
  paddle/fluid/platform/mkldnn_reuse.h
Labels: Intel

#44672 add some fp16 op for kunlun resnet50 model
  paddle/fluid/operators/fused/resnet_unit_op_xpu.cc
  paddle/fluid/operators/optimizers/lars_momentum_op_xpu.cc
  paddle/fluid/platform/device/xpu/xpu2_op_list.h
  paddle/phi/kernels/xpu/elementwise_add_kernel.cc
  paddle/phi/kernels/xpu/log_softmax_grad_kernel.cc
  paddle/phi/kernels/xpu/log_softmax_kernel.cc
  python/paddle/fluid/tests/unittests/xpu/test_update_loss_scaling_op_xpu.py
Labels: contributor, status: proposed

#44161 【PaddlePaddle Hackathon 3 No.12】为 Paddle 新增 pairwise_distance
  python/paddle/fluid/tests/unittests/test_pairwise_distance.py
  python/paddle/nn/functional/__init__.py
  python/paddle/nn/functional/distance.py
  python/paddle/nn/layer/distance.py
Labels: contributor, status: proposed
