Repository PaddlePaddle/Paddle, pull requests merged in 2022-04, with the labels that each got.

#41151 support multi_layer of bilstm,*test=kunlun
  cmake/external/xpu.cmake
  paddle/fluid/operators/rnn_op_xpu.cc
  paddle/fluid/platform/device/xpu/xpu2_op_list.h
  python/paddle/fluid/tests/unittests/xpu/test_rnn_op_xpu.py
Labels: contributor, status: proposed

#41235 Enabled FC of oneDNN for bert tester
  paddle/fluid/inference/tests/api/analyzer_bert_tester.cc
Labels: Intel, contributor, status: proposed

#41120 xpu add dropout&cast unitest test=kunlun
  paddle/fluid/operators/dropout_op_xpu.cc
  python/paddle/fluid/tests/unittests/op_test_xpu.py
  python/paddle/fluid/tests/unittests/xpu/test_cast_op_xpu.py
  python/paddle/fluid/tests/unittests/xpu/test_dropout_op_xpu.py
Labels: contributor, status: not progressed

#41286 conv + elementwise_add refactor
  paddle/fluid/framework/ir/graph_pattern_detector.cc
  paddle/fluid/framework/ir/graph_pattern_detector.h
  paddle/fluid/framework/ir/graph_traits.cc
  paddle/fluid/framework/ir/graph_traits.h
  paddle/fluid/framework/ir/mkldnn/conv_elementwise_add_mkldnn_fuse_pass.cc
  paddle/fluid/framework/ir/mkldnn/conv_elementwise_add_mkldnn_fuse_pass.h
  python/paddle/fluid/tests/unittests/ir/inference/test_mkldnn_conv_elementwise_add_fuse_pass.py
Labels: Intel, contributor

#40472 【PaddlePaddle Hackathon 2】8、为 Paddle 新增 nanmean API
  python/paddle/__init__.py
  python/paddle/fluid/tests/unittests/test_nanmean_api.py
  python/paddle/tensor/__init__.py
  python/paddle/tensor/math.py
Labels: contributor, status: revision

#41307 [IPU] remove paddle_ipu shared library
  cmake/inference_lib.cmake
  paddle/fluid/framework/ir/CMakeLists.txt
  paddle/fluid/inference/CMakeLists.txt
  paddle/fluid/inference/api/analysis_predictor.cc
  paddle/fluid/platform/device/ipu/CMakeLists.txt
  paddle/fluid/platform/device/ipu/popart_canonicalization/activation_ops.cc
  paddle/fluid/platform/device/ipu/popart_canonicalization/canonicalization_utils.h
  paddle/fluid/platform/device/ipu/popart_canonicalization/elementwise_ops.cc
  paddle/fluid/platform/device/ipu/popart_canonicalization/logic_ops.cc
  paddle/fluid/platform/device/ipu/popart_canonicalization/math_ops.cc
  paddle/fluid/platform/device/ipu/popart_canonicalization/nn_ops.cc
  paddle/fluid/platform/device/ipu/popart_canonicalization/other_ops.cc
  paddle/fluid/platform/device/ipu/popart_canonicalization/reduce_ops.cc
  paddle/fluid/platform/device/ipu/popart_canonicalization/search_ops.cc
  paddle/fluid/platform/device/ipu/popart_canonicalization/tensor_ops.cc
  paddle/fluid/pybind/CMakeLists.txt
  python/setup.py.in
Labels: contributor, status: proposed

#41186 add matmul & adamw unittest test=kunlun
  python/paddle/fluid/tests/unittests/xpu/test_adamw_op_xpu.py
  python/paddle/fluid/tests/unittests/xpu/test_matmul_op_xpu.py
  python/paddle/fluid/tests/unittests/xpu/test_matmul_v2_op_xpu.py
Labels: contributor, status: proposed

#41323 add rewrite pattern form paddle op tp trt op
  paddle/infrt/dialect/tensorrt/convert.h
  paddle/infrt/dialect/tensorrt/pd_lower_to_trt.td
  paddle/infrt/dialect/tensorrt/trt_op_converter_pass.cc
  paddle/infrt/dialect/tensorrt/trt_ops.td
  paddle/infrt/kernel/tensorrt/trt_kernels.cc
  paddle/infrt/kernel/tensorrt/trt_layers.h
Labels: contributor, status: proposed

#41325 momentum support l2decay for xpu. test=kunlun
  cmake/external/xpu.cmake
  paddle/fluid/framework/CMakeLists.txt
  paddle/fluid/operators/optimizers/momentum_op_xpu.cc
  python/paddle/fluid/tests/unittests/xpu/test_momentum_op_xpu.py
Labels: contributor, status: proposed

#41342 ignore some failed test for KL2
  paddle/fluid/operators/fill_constant_op_xpu.cc
  paddle/fluid/platform/device/xpu/xpu2_op_list.h
  python/paddle/fluid/tests/unittests/CMakeLists.txt
  python/paddle/fluid/tests/unittests/xpu/test_assign_op_xpu.py
  python/paddle/fluid/tests/unittests/xpu/test_bilinear_interp_op_xpu.py
  python/paddle/fluid/tests/unittests/xpu/test_lamb_op_xpu.py
  python/paddle/fluid/tests/unittests/xpu/test_nearest_interp_op_xpu.py
  python/paddle/fluid/tests/unittests/xpu/test_one_hot_op_xpu.py
  python/paddle/fluid/tests/unittests/xpu/test_reduce_max_op_xpu.py
  python/paddle/fluid/tests/unittests/xpu/test_rmsprop_op_xpu.py
  tools/check_file_diff_approvals.sh
Labels: contributor, status: proposed

#41445 Fix dygraph record event position
  paddle/fluid/imperative/partial_grad_engine.cc
  paddle/fluid/imperative/tracer.cc
  paddle/fluid/platform/profiler/chrometracing_logger.cc
Labels: contributor, status: proposed

#41420 Fix problem with py3.6 and test for quant2_int8_lstm
  python/paddle/distributed/parallel.py
  python/paddle/fluid/contrib/slim/tests/save_quant_model.py
Labels: Intel, contributor

#41140 xpu mul unittest test=kunlun
  paddle/fluid/operators/mul_op_xpu.cc
  paddle/fluid/platform/device/xpu/xpu2_op_list.h
  python/paddle/fluid/tests/unittests/xpu/test_mul_op_xpu.py
Labels: contributor, status: not progressed

#41524 Refine statistic table
  python/paddle/fluid/tests/unittests/test_profiler_statistic.py
  python/paddle/profiler/profiler_statistic.py
Labels: contributor, status: proposed

#41534 modify unittest of lstm forward, *test=kunlun
  cmake/external/xpu.cmake
  paddle/fluid/operators/rnn_op_xpu.cc
  python/paddle/fluid/tests/unittests/xpu/test_rnn_op_xpu.py
Labels: contributor, status: proposed

#41481 [IPU] fix running error for ipu
  paddle/phi/common/backend.h
  paddle/phi/core/compat/convert_utils.cc
Labels: contributor, status: proposed

#41532 Add get profiler from config
  python/paddle/fluid/tests/unittests/test_newprofiler.py
  python/paddle/profiler/profiler.py
  python/paddle/profiler/profiler_statistic.py
Labels: contributor, status: proposed

#41522 fix arg_max for int type, *test=kunlun
  paddle/fluid/operators/arg_max_op_xpu.cc
Labels: contributor, status: proposed

#41572 Fix for gaussian random kernel
  paddle/fluid/operators/mkldnn/gaussian_random_mkldnn_op.cc
Labels: Intel

#41421 [IPU] support more ops
  cmake/external/poplar.cmake
  cmake/inference_lib.cmake
  paddle/fluid/platform/device/ipu/ipu_compiler.cc
  paddle/fluid/platform/device/ipu/ipu_strategy.cc
  paddle/fluid/platform/device/ipu/ipu_strategy.h
  paddle/fluid/platform/device/ipu/popart_canonicalization/math_ops.cc
  paddle/fluid/platform/device/ipu/popart_canonicalization/nn_ops.cc
  paddle/fluid/platform/device/ipu/popart_canonicalization/tensor_ops.cc
Labels: contributor, status: proposed

#41533 [IPU] [cherry-pick] fix running error for ipu
  paddle/phi/common/backend.h
  paddle/phi/core/compat/convert_utils.cc
Labels: contributor, status: proposed

#41581 [cherry-pick] Refine statistic table and bug fix
  python/paddle/fluid/tests/unittests/test_newprofiler.py
  python/paddle/fluid/tests/unittests/test_profiler_statistic.py
  python/paddle/profiler/profiler.py
  python/paddle/profiler/profiler_statistic.py
Labels: contributor, status: proposed

#41608 [cherry-pick] Fix old dygraph record event
  paddle/fluid/imperative/partial_grad_engine.cc
  paddle/fluid/imperative/tracer.cc
  paddle/fluid/platform/profiler/chrometracing_logger.cc
Labels: contributor, status: proposed

#41562 Add possibility to test native config in Mkldnn tests
  paddle/fluid/inference/tests/api/analyzer_bfloat16_image_classification_tester.cc
  paddle/fluid/inference/tests/api/analyzer_int8_image_classification_tester.cc
  paddle/fluid/inference/tests/api/analyzer_int8_object_detection_tester.cc
  paddle/fluid/inference/tests/api/analyzer_quant_image_classification_tester.cc
Labels: Intel

#41657 update kunlun xdnn
  cmake/external/xpu.cmake
Labels: contributor, status: proposed

#41679 update kunlun xdnn (#41657)
  cmake/external/xpu.cmake
Labels: contributor, status: proposed

#41226 【Hackathon No.27】为 Paddle 新增 frac 数学计算API
  python/paddle/__init__.py
  python/paddle/fluid/tests/unittests/test_frac_api.py
  python/paddle/tensor/__init__.py
  python/paddle/tensor/math.py
Labels: contributor, status: proposed

#41685 Update sign op xpu
  cmake/external/xpu.cmake
  paddle/fluid/operators/sign_op_xpu.cc
  paddle/fluid/platform/device/xpu/xpu2_op_list.h
  python/paddle/fluid/tests/unittests/xpu/test_sign_op_xpu.py
Labels: contributor, status: proposed

#41610 support bce_loss and bce_loss_grad in XPU, test=kunlun
  paddle/fluid/operators/bce_loss_op_xpu.cc
  paddle/fluid/platform/device/xpu/xpu2_op_list.h
  python/paddle/fluid/tests/unittests/xpu/test_bce_loss_op_xpu.py
Labels: contributor, status: proposed

#41631 concat and relu sopport FP16 in XPU, test=kunlun
  paddle/fluid/operators/activation_op_xpu.cc
  paddle/fluid/operators/concat_op_xpu.cc
  paddle/fluid/platform/device/xpu/xpu2_op_list.h
Labels: contributor, status: proposed

#41671 use bilstm_train for rnn forward, * test=kunlun
  paddle/fluid/operators/rnn_op_xpu.cc
Labels: contributor, status: proposed

#41715 fix new dygraph record event
  paddle/fluid/eager/auto_code_generator/eager_generator.cc
  paddle/fluid/eager/auto_code_generator/final_state_generator/codegen_utils.py
  paddle/fluid/eager/auto_code_generator/final_state_generator/eager_gen.py
  paddle/fluid/eager/backward.cc
  python/paddle/utils/code_gen/api_base.py
Labels: contributor, status: proposed

#39756 Added shuffle_channel BF16/FP32 FWD oneDNN kernel
  paddle/fluid/framework/ir/CMakeLists.txt
  paddle/fluid/framework/ir/mkldnn/shuffle_channel_mkldnn_detect_pass.cc
  paddle/fluid/framework/ir/mkldnn/shuffle_channel_mkldnn_detect_pass.h
  paddle/fluid/inference/api/paddle_pass_builder.cc
  paddle/fluid/operators/mkldnn/shuffle_channel_mkldnn_op.cc
  paddle/fluid/operators/shuffle_channel_op.cc
  python/paddle/fluid/tests/unittests/ir/inference/test_mkldnn_shuffle_channel_op.py
  python/paddle/fluid/tests/unittests/mkldnn/test_shuffle_channel_mkldnn_op.py
Labels: Intel, BF16

#41771 [cherry-pick] fix new dygraph record event (#41715)
  paddle/fluid/eager/auto_code_generator/eager_generator.cc
  paddle/fluid/eager/auto_code_generator/final_state_generator/codegen_utils.py
  paddle/fluid/eager/auto_code_generator/final_state_generator/eager_gen.py
  paddle/fluid/eager/backward.cc
  python/paddle/utils/code_gen/api_base.py
Labels: contributor, status: proposed

#41749 add security policy
  SECURITY.md
  SECURITY_cn.md
  security/README.md
  security/README_cn.md
Labels: contributor, status: proposed

#41796 Fix links in security policy
  SECURITY.md
  SECURITY_cn.md
  security/README.md
  security/README_cn.md
Labels: contributor, status: proposed

#41776 FC+elementwise_add (residual connection)
  paddle/fluid/framework/ir/CMakeLists.txt
  paddle/fluid/framework/ir/mkldnn/fc_elementwise_add_mkldnn_fuse_pass.cc
  paddle/fluid/framework/ir/mkldnn/fc_elementwise_add_mkldnn_fuse_pass.h
  paddle/fluid/framework/ir/mkldnn/fc_elementwise_add_mkldnn_fuse_pass_tester.cc
  paddle/fluid/inference/api/paddle_pass_builder.cc
  paddle/fluid/inference/api/paddle_pass_builder.h
  paddle/fluid/inference/tests/api/CMakeLists.txt
  paddle/fluid/inference/tests/api/analyzer_bert_tester.cc
  paddle/fluid/inference/tests/api/analyzer_vit_ocr_tester.cc
  paddle/fluid/operators/mkldnn/fc_mkldnn_op.cc
  python/paddle/fluid/tests/unittests/ir/inference/CMakeLists.txt
  python/paddle/fluid/tests/unittests/ir/inference/test_mkldnn_fc_elementwise_add_fuse_pass.py
Labels: Intel, contributor

#41026 Fix to #38693 (minimal UT)
  paddle/fluid/framework/data_layout_transform.h
  paddle/fluid/framework/data_transform.cc
  paddle/fluid/inference/api/details/zero_copy_tensor.cc
  paddle/fluid/platform/mkldnn_helper.h
  paddle/phi/common/layout.h
  python/paddle/fluid/tests/unittests/ir/inference/CMakeLists.txt
  python/paddle/fluid/tests/unittests/ir/inference/test_mkldnn_conv3d_op.py
Labels: Intel, contributor, status: proposed

#41494 [KP] Add registry for elementwise_add/max/min/sub/div/mul/floordiv on XPU2 with KP lib
  paddle/fluid/framework/new_executor/standalone_executor_test.cc
  paddle/fluid/operators/elementwise/elementwise_add_op.kps
  paddle/fluid/platform/device/xpu/xpu_op_kpfirst_list.h
  paddle/phi/kernels/funcs/elementwise_functor.h
  paddle/phi/kernels/impl/elementwise_kernel_impl.h
  paddle/phi/kernels/kps/elementwise_kernel.cu
Labels: contributor, status: not progressed

#41786 fix xpu cmake lib name. test=kunlun
  cmake/external/xpu.cmake
Labels: contributor, status: proposed

#41794 fix divide zero error when cpu only
  python/paddle/profiler/profiler_statistic.py
Labels: contributor, status: proposed

#41138 [MLU] add mlu new profiler
  paddle/fluid/platform/device/mlu/mlu_info.h
  paddle/fluid/platform/profiler/CMakeLists.txt
  paddle/fluid/platform/profiler/chrometracing_logger.cc
  paddle/fluid/platform/profiler/mlu/CMakeLists.txt
  paddle/fluid/platform/profiler/mlu/cnpapi_data_process.cc
  paddle/fluid/platform/profiler/mlu/cnpapi_data_process.h
  paddle/fluid/platform/profiler/mlu/mlu_tracer.cc
  paddle/fluid/platform/profiler/mlu/mlu_tracer.h
  paddle/fluid/platform/profiler/profiler.cc
  paddle/fluid/platform/profiler/profiler.h
  paddle/fluid/platform/profiler/trace_event.h
  paddle/fluid/platform/profiler/trace_event_collector.h
  paddle/fluid/pybind/pybind.cc
  python/paddle/profiler/profiler.py
Labels: contributor, status: proposed

#41751 [MLU] add mlu activation kernels
  paddle/fluid/operators/activation_op_mlu.cc
  paddle/fluid/operators/fill_constant_op_mlu.cc
  paddle/fluid/operators/mean_op_mlu.cc
  paddle/fluid/operators/metrics/accuracy_op_mlu.cc
  paddle/fluid/operators/mlu/mlu_baseop.cc
  paddle/fluid/operators/mlu/mlu_baseop.h
  paddle/fluid/operators/optimizers/merged_momentum_op_mlu.cc
  paddle/fluid/operators/optimizers/momentum_op_mlu.cc
  paddle/fluid/operators/reduce_ops/reduce_mean_op_mlu.cc
  paddle/fluid/operators/scale_op_mlu.cc
  python/paddle/fluid/tests/unittests/mlu/test_gelu_op_mlu.py
  python/paddle/fluid/tests/unittests/mlu/test_leaky_relu_op_mlu.py
  python/paddle/fluid/tests/unittests/mlu/test_relu6_op_mlu.py
  python/paddle/fluid/tests/unittests/mlu/test_sigmoid_op_mlu.py
  python/paddle/fluid/tests/unittests/mlu/test_tanh_op_mlu.py
Labels: contributor, status: proposed

#41543 refactor KL unittest, *test=kunlun
  python/paddle/fluid/tests/unittests/xpu/test_squeeze2_op_xpu.py
  python/paddle/fluid/tests/unittests/xpu/test_unsqueeze2_op_xpu.py
Labels: contributor, status: proposed

#41343 【Hackathon No.25】为 Paddle 新增 nanquantile 数学计算API
  python/paddle/__init__.py
  python/paddle/fluid/tests/unittests/test_quantile.py
  python/paddle/fluid/tests/unittests/test_quantile_and_nanquantile.py
  python/paddle/tensor/__init__.py
  python/paddle/tensor/stat.py
Labels: contributor, status: open review

#41731 [IPU][cherry-pick] support more ops
  cmake/external/poplar.cmake
  cmake/inference_lib.cmake
  paddle/fluid/platform/device/ipu/ipu_compiler.cc
  paddle/fluid/platform/device/ipu/ipu_strategy.cc
  paddle/fluid/platform/device/ipu/ipu_strategy.h
  paddle/fluid/platform/device/ipu/popart_canonicalization/math_ops.cc
  paddle/fluid/platform/device/ipu/popart_canonicalization/nn_ops.cc
  paddle/fluid/platform/device/ipu/popart_canonicalization/tensor_ops.cc
Labels: contributor, status: proposed

#41733 [IPU] add mixed-precission support for ipu
  paddle/fluid/framework/ir/ipu/optimizer_extract_pass.cc
  python/paddle/fluid/contrib/mixed_precision/fp16_utils.py
  python/paddle/fluid/tests/unittests/ipu/op_test_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_mixed_precision_inference_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_mixed_precision_training_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_model_parallel_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_weight_decay_ipu.py
Labels: contributor, status: proposed

#41816 [MLU] add mlu softmax kernel
  paddle/fluid/operators/mlu/mlu_baseop.cc
  paddle/fluid/operators/mlu/mlu_baseop.h
  paddle/fluid/operators/softmax_op_mlu.cc
  python/paddle/fluid/tests/unittests/mlu/test_softmax_op_mlu.py
Labels: contributor, status: proposed

#41215 add fp16 for masked_select on kunlun
  paddle/fluid/operators/masked_select_op_xpu.cc
  paddle/fluid/platform/device/xpu/xpu2_op_list.h
Labels: contributor, status: proposed

#41832 modify xpu.cmake,*test=kunlun
  cmake/external/xpu.cmake
Labels: contributor, status: not progressed

#41877 support tril_triu_grad for KL2, *test=kunlun
  paddle/fluid/operators/tril_triu_op_xpu.cc
  paddle/fluid/platform/device/xpu/xpu2_op_list.h
  python/paddle/fluid/tests/unittests/xpu/test_tril_triu_op_xpu.py
Labels: contributor, status: proposed

#41905 [cherry-pick] modify xpu.cmake,*test=kunlun (#41832)
  cmake/external/xpu.cmake
Labels: contributor, status: not progressed

#40664 Add float16 to fake quantize/dequantize OP
  paddle/fluid/operators/fake_dequantize_op.cu
  paddle/fluid/operators/fake_quantize_op.cu
  paddle/fluid/operators/fake_quantize_op.cu.h
  python/paddle/fluid/tests/unittests/test_fake_dequantize_op.py
  python/paddle/fluid/tests/unittests/test_fake_quantize_op.py
Labels: NVIDIA

#41959 Revert "[cherry-pick] modify xpu.cmake,*test=kunlun (#41832)"
  cmake/external/xpu.cmake
Labels: contributor, status: proposed

#41791 [MLU]add op: cumsum, fill_any_like, unsqueeze
  paddle/fluid/operators/cumsum_op_mlu.cc
  paddle/fluid/operators/fill_any_like_op_mlu.cc
  paddle/fluid/operators/unsqueeze_op_mlu.cc
  python/paddle/fluid/tests/unittests/mlu/test_cumsum_op_mlu.py
  python/paddle/fluid/tests/unittests/mlu/test_fill_any_like_op_mlu.py
  python/paddle/fluid/tests/unittests/mlu/test_unsqueeze2_op_mlu.py
  python/paddle/fluid/tests/unittests/mlu/test_unsqueeze_op_mlu.py
Labels: contributor, status: proposed

#41850 fix bug for MultiplicativeDecay
  python/paddle/optimizer/lr.py
Labels: contributor, PFCC

#41935 support bmm&bmm_grad for KL2, *test=kunlun
  paddle/fluid/operators/bmm_op_xpu.cc
  paddle/fluid/platform/device/xpu/xpu2_op_list.h
  python/paddle/fluid/tests/unittests/xpu/test_bmm_op_xpu.py
Labels: contributor, status: not progressed

#41939 Rebase for profiler statistic ratio
  python/paddle/fluid/tests/unittests/test_profiler_statistic.py
  python/paddle/profiler/profiler_statistic.py
Labels: contributor, status: proposed

#41303 OneDNN md-in-tensor refactoring part 1: Added main changes for md-in-tensor
  paddle/fluid/framework/data_layout_transform.cc
  paddle/fluid/framework/data_transform.cc
  paddle/fluid/framework/tensor_util.cc
  paddle/fluid/operators/mkldnn/cast_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/expand_v2_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/slice_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/split_mkldnn_op.cc
  paddle/fluid/operators/reduce_ops/mkldnn/reduce_mkldnn_op.h
  paddle/fluid/operators/split_op.cc
  paddle/fluid/platform/mkldnn_reuse.h
  paddle/fluid/platform/mkldnn_utils.h
  paddle/phi/core/CMakeLists.txt
  paddle/phi/core/compat/convert_utils.cc
  paddle/phi/core/compat/convert_utils.h
  paddle/phi/core/dense_tensor.cc
  paddle/phi/core/dense_tensor.h
  paddle/phi/core/dense_tensor.inl
  paddle/phi/core/dense_tensor_impl.cc
  python/paddle/fluid/tests/unittests/ir/inference/test_mkldnn_shape_op.py
Labels: Intel, contributor

#41822 reduce performance influence by RecordEvent in Python
  python/paddle/fluid/tests/unittests/test_newprofiler.py
  python/paddle/profiler/profiler.py
  python/paddle/profiler/utils.py
Labels: contributor, status: proposed

#41969 [MLU] add gather mlu kernel
  cmake/neuware.cmake
  paddle/fluid/operators/gather_op_mlu.cc
  paddle/fluid/operators/mlu/mlu_baseop.cc
  paddle/fluid/operators/optimizers/merged_momentum_op_mlu.cc
  paddle/fluid/operators/optimizers/momentum_op_mlu.cc
  paddle/fluid/platform/profiler_helper.h
  python/paddle/fluid/tests/unittests/mlu/test_gather_op_mlu.py
  python/paddle/tensor/creation.py
Labels: contributor, status: proposed

#41989 [cherry-pick] Refine user experience for profiler
  python/paddle/fluid/tests/unittests/test_newprofiler.py
  python/paddle/fluid/tests/unittests/test_profiler_statistic.py
  python/paddle/profiler/profiler.py
  python/paddle/profiler/profiler_statistic.py
  python/paddle/profiler/utils.py
Labels: contributor, status: proposed

#41261 【PaddlePaddle Hackathon 2】9、为 Paddle 新增 logspace API
  paddle/fluid/operators/logspace_op.cc
  paddle/phi/infermeta/multiary.cc
  paddle/phi/infermeta/multiary.h
  paddle/phi/kernels/cpu/logspace_kernel.cc
  paddle/phi/kernels/gpu/logspace_kernel.cu
  paddle/phi/kernels/logspace_kernel.h
  python/paddle/__init__.py
  python/paddle/fluid/tests/unittests/test_logspace.py
  python/paddle/tensor/creation.py
  tools/static_mode_white_list.py
Labels: contributor, status: revision

#42058 fix api math equation dispaly issue; test=document_fix
  python/paddle/tensor/math.py
Labels: contributor, status: proposed

#41976 modify batch_norm and batch_norm_grad. *test=kunlun
  paddle/fluid/operators/batch_norm_op_xpu.cc
Labels: contributor, status: proposed

#41997 OneDNN md-in-tensor refactoring part 2: Second batch of changes for md-in-tensor
  paddle/fluid/operators/mkldnn/activation_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/batch_norm_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/clip_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/concat_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/expand_v2_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/gaussian_random_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/interpolate_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/layer_norm_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/log_softmax_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/lrn_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/pool_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/prelu_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/scale_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/shape_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/shuffle_channel_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/softmax_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/softplus_mkldnn_op.h
  python/paddle/fluid/tests/unittests/mkldnn/test_expand_v2_mkldnn_op.py
Labels: Intel, contributor, status: proposed

#40910 【PaddlePaddle Hackathon 2】23、为 Paddle 新增 Softmax2D 组网API
  python/paddle/fluid/tests/unittests/test_softmax2d.py
  python/paddle/nn/__init__.py
  python/paddle/nn/layer/__init__.py
  python/paddle/nn/layer/activation.py
Labels: contributor, status: open review

#41810 [MLU]:add elementwise_div op
  paddle/fluid/operators/elementwise/elementwise_div_op_mlu.cc
  python/paddle/fluid/tests/unittests/mlu/test_elementwise_div_op_mlu.py
Labels: contributor, status: proposed

#41906 [IPU] [Cherry-pick] add mixed-precission support for ipu (#41733)
  paddle/fluid/framework/ir/ipu/optimizer_extract_pass.cc
  python/paddle/fluid/contrib/mixed_precision/fp16_utils.py
  python/paddle/fluid/tests/unittests/ipu/op_test_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_mixed_precision_inference_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_mixed_precision_training_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_model_parallel_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_weight_decay_ipu.py
Labels: contributor, status: proposed

#42055 [cherry-pick 2.3] Back port of "Fix to #38693 (minimal UT) "
  paddle/fluid/framework/data_layout_transform.h
  paddle/fluid/framework/data_transform.cc
  paddle/fluid/inference/api/details/zero_copy_tensor.cc
  paddle/fluid/platform/mkldnn_helper.h
  paddle/phi/common/layout.h
  python/paddle/fluid/tests/unittests/ir/inference/CMakeLists.txt
  python/paddle/fluid/tests/unittests/ir/inference/test_mkldnn_conv3d_op.py
Labels: Intel, contributor, status: proposed

#41010 [WIP] Algorithm Cache of cuBlasLt Epilogue
  paddle/fluid/operators/fused/fused_gemm_epilogue_op.cu
  paddle/fluid/operators/fused/fused_gemm_epilogue_op.h
  paddle/fluid/platform/dynload/cublasLt.h
  paddle/fluid/platform/flags.cc
  paddle/phi/backends/dynload/cublasLt.h
  python/paddle/fluid/tests/unittests/CMakeLists.txt
  python/paddle/fluid/tests/unittests/test_fuse_gemm_epilogue_pass.py
Labels: NVIDIA, contributor

#41045 fix incorrect usages of std::move and other compile errors
  paddle/fluid/distributed/test/ctr_accessor_test.cc
  paddle/fluid/framework/ir/fusion_group/code_generator_tester.cc
  paddle/fluid/framework/ir/fusion_group/fusion_group_pass_tester.cc
  paddle/fluid/framework/new_executor/interpretercore_util.cc
  paddle/fluid/framework/var_desc.h
  paddle/fluid/inference/utils/table_printer.cc
  paddle/fluid/platform/profiler.cc
  paddle/phi/api/lib/api_gen_utils.cc
  paddle/phi/api/lib/data_transform.cc
  paddle/phi/core/compat/arg_map_context.h
  paddle/phi/core/utils/type_registry.h
  paddle/utils/array_ref.h
Labels: contributor, status: open review

#40743 【PaddlePaddle Hackathon 2】24、为 Paddle 新增 nn.ChannelShuffle 组网 API
  paddle/fluid/operators/channel_shuffle_op.cc
  paddle/phi/infermeta/backward.cc
  paddle/phi/infermeta/backward.h
  paddle/phi/infermeta/unary.cc
  paddle/phi/infermeta/unary.h
  paddle/phi/kernels/channel_shuffle_grad_kernel.h
  paddle/phi/kernels/channel_shuffle_kernel.h
  paddle/phi/kernels/cpu/channel_shuffle_grad_kernel.cc
  paddle/phi/kernels/cpu/channel_shuffle_kernel.cc
  paddle/phi/kernels/gpu/channel_shuffle_grad_kernel.cu
  paddle/phi/kernels/gpu/channel_shuffle_kernel.cu
  paddle/phi/kernels/impl/channel_shuffle_grad_kernel_impl.h
  paddle/phi/kernels/impl/channel_shuffle_kernel_impl.h
  paddle/phi/ops/compat/channel_shuffle_sig.cc
  python/paddle/fluid/tests/unittests/test_channel_shuffle.py
  python/paddle/nn/__init__.py
  python/paddle/nn/functional/__init__.py
  python/paddle/nn/functional/vision.py
  python/paddle/nn/layer/__init__.py
  python/paddle/nn/layer/vision.py
  tools/static_mode_white_list.py
Labels: contributor, status: open review

#42041 Downloading data for test_analyzer_vit_ocr
  paddle/fluid/inference/tests/api/CMakeLists.txt
Labels: Intel, contributor

#41604 fix en docs of some Apis (gradients, scope_guard, cuda_places, name_scope, device_guard, load_program_state, scale, ParamAttr and WeightNormParamAttr)
  python/paddle/fluid/backward.py
  python/paddle/fluid/executor.py
  python/paddle/fluid/framework.py
  python/paddle/fluid/io.py
  python/paddle/fluid/layers/nn.py
  python/paddle/fluid/param_attr.py
Labels: contributor, status: proposed

#42230 Increase test_export_deploy_model tolerance for broadwell CPU
  python/paddle/tests/test_model.py
Labels: NVIDIA, contributor, status: proposed

#42200 align the API parameter “name” annotation in math.py; test=document_fix
  python/paddle/tensor/math.py
Labels: contributor, status: proposed

#42252 [cherry-pick] refactor vision models
  python/paddle/vision/__init__.py
  python/paddle/vision/models/__init__.py
  python/paddle/vision/models/inceptionv3.py
  python/paddle/vision/models/mobilenetv1.py
  python/paddle/vision/models/mobilenetv2.py
  python/paddle/vision/models/resnet.py
  python/paddle/vision/models/resnext.py
  python/paddle/vision/models/shufflenetv2.py
  python/paddle/vision/ops.py
Labels: contributor, status: proposed

#40728 【PaddlePaddle Hackathon 2】29、为 Paddle 新增 PixelUnshuffle 组网 API
  paddle/fluid/operators/pixel_unshuffle_op.cc
  paddle/phi/infermeta/backward.cc
  paddle/phi/infermeta/backward.h
  paddle/phi/infermeta/unary.cc
  paddle/phi/infermeta/unary.h
  paddle/phi/kernels/cpu/pixel_unshuffle_grad_kernel.cc
  paddle/phi/kernels/cpu/pixel_unshuffle_kernel.cc
  paddle/phi/kernels/gpu/pixel_unshuffle_grad_kernel.cu
  paddle/phi/kernels/gpu/pixel_unshuffle_kernel.cu
  paddle/phi/kernels/impl/pixel_unshuffle_grad_kernel_impl.h
  paddle/phi/kernels/impl/pixel_unshuffle_kernel_impl.h
  paddle/phi/kernels/pixel_unshuffle_grad_kernel.h
  paddle/phi/kernels/pixel_unshuffle_kernel.h
  paddle/phi/ops/compat/pixel_unshuffle_sig.cc
  python/paddle/fluid/tests/unittests/test_pixel_unshuffle.py
  python/paddle/nn/__init__.py
  python/paddle/nn/functional/__init__.py
  python/paddle/nn/functional/vision.py
  python/paddle/nn/layer/__init__.py
  python/paddle/nn/layer/vision.py
  tools/static_mode_white_list.py
Labels: contributor, status: open review

#42195 support nhwc format for kunlun conv/batch_norm
  cmake/external/xpu.cmake
  paddle/fluid/operators/batch_norm_op_xpu.cc
  paddle/fluid/operators/conv_op_xpu.cc
Labels: contributor, status: proposed

#42274 [MLU]add dropout op
  paddle/fluid/operators/dropout_op_mlu.cc
  paddle/fluid/operators/mlu/mlu_baseop.cc
  paddle/fluid/operators/mlu/mlu_baseop.h
  python/paddle/fluid/tests/unittests/mlu/test_dropout_op_mlu.py
Labels: contributor, status: proposed

#42271 fix sparse csr constructing
  paddle/phi/api/lib/api_gen_utils.cc
  paddle/phi/core/sparse_csr_tensor.cc
Labels: contributor, status: proposed

#42205 Fix the race condition in cumsum operator
  paddle/phi/kernels/gpu/cumsum_kernel.cu
Labels: NVIDIA, contributor, status: proposed

#42001 Added missing test for shuffle_channel_mkldnn_detect_pass
  paddle/fluid/framework/ir/CMakeLists.txt
  paddle/fluid/framework/ir/mkldnn/shuffle_channel_mkldnn_detect_pass_tester.cc
  python/paddle/fluid/tests/unittests/ir/inference/test_mkldnn_shuffle_channel_detect_pass.py
Labels: Intel, contributor

#42238 Bfloat16 refactor
  paddle/fluid/framework/ir/graph_pattern_detector.cc
  paddle/fluid/framework/ir/graph_pattern_detector.h
  paddle/fluid/framework/ir/mkldnn/cpu_bfloat16_pass.cc
  paddle/fluid/framework/ir/mkldnn/cpu_bfloat16_pass.h
  paddle/fluid/framework/ir/mkldnn/cpu_bfloat16_placement_pass.cc
  paddle/fluid/framework/ir/mkldnn/cpu_bfloat16_placement_pass.h
Labels: Intel, BF16, contributor
