Repository PaddlePaddle/Paddle, pull requests merged in 2022-11, with the labels that each got.

#47513 [CodeStyle] remove unused-local-typedefs warning on linux
  cmake/flags.cmake
  paddle/fluid/operators/collective/c_comm_init_op.cc
  paddle/fluid/operators/elementwise/mkldnn/elementwise_mkldnn_op.h
  paddle/phi/kernels/xpu/rnn_kernel.cc
Labels: contributor, status: proposed

#47486 add pdsa-2022-002, test=document_fix
  security/README.md
  security/README_cn.md
  security/advisory/pdsa-2022-002.md
  security/advisory/pdsa-2022-002_cn.md
Labels: contributor, status: proposed

#47334 [CodeStyle][py2] remove `six` package (part2)
  paddle/scripts/conda_build.py
  python/paddle/distributed/fleet/elastic/manager.py
  python/paddle/distributed/launch/controllers/master.py
  python/paddle/fluid/contrib/slim/quantization/imperative/ptq_quantizer.py
  python/paddle/fluid/dataloader/dataloader_iter.py
  python/paddle/fluid/dataloader/worker.py
  python/paddle/fluid/dygraph/dygraph_to_static/convert_call_func.py
  python/paddle/fluid/executor.py
  python/paddle/fluid/framework.py
  python/paddle/fluid/incubate/fleet/parameter_server/ir/public.py
  python/paddle/fluid/layers/io.py
  python/paddle/fluid/layers/nn.py
  python/paddle/fluid/layers/utils.py
  python/paddle/fluid/reader.py
  python/paddle/fluid/tests/unittests/npu/test_save_load_npu.py
  python/paddle/fluid/tests/unittests/test_fleet_elastic_manager.py
  python/paddle/reader/decorator.py
  python/requirements.txt
Labels: contributor, status: proposed

#47526 add pdsa-2022-002 (#47486)
  security/README.md
  security/README_cn.md
  security/advisory/pdsa-2022-002.md
  security/advisory/pdsa-2022-002_cn.md
Labels: contributor, status: proposed

#47465 [CodeStyle][E711][E712] update flake8 config
  .flake8
Labels: contributor, status: proposed

#47524 Add build option for CUDNN Frontend API
  CMakeLists.txt
  cmake/configure.cmake
  cmake/external/cudnn-frontend.cmake
  cmake/flags.cmake
  cmake/third_party.cmake
  paddle/fluid/platform/flags.cc
  paddle/phi/backends/dynload/CMakeLists.txt
  paddle/phi/backends/dynload/cudnn.cc
  paddle/phi/backends/dynload/cudnn.h
  paddle/phi/backends/dynload/cudnn_frontend.h
  paddle/phi/backends/dynload/cudnn_frontend_test.cc
  patches/cudnn-frontend/0001-patch-for-paddle.patch
Labels: NVIDIA, contributor, status: proposed

#47409 [XPU] add int64 support for slice and subtract. test=kunlun
  paddle/fluid/platform/device/xpu/xpu2_op_list.h
  paddle/phi/kernels/elementwise_kernel.cc
  paddle/phi/kernels/xpu/elementwise_subtract_kernel.cc
  paddle/phi/kernels/xpu/slice_kernel.cc
Labels: contributor, status: proposed

#47483 Remove redundant numpy import in Docs(test=document_fix)
  python/paddle/incubate/nn/functional/fused_transformer.py
  python/paddle/nn/layer/pooling.py
  python/paddle/optimizer/adagrad.py
  python/paddle/regularizer.py
Labels: contributor, status: proposed

#47488 Fix TRT UT failures
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_elementwise.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_group_norm.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_pool2d.py
Labels: NVIDIA, contributor

#47053 Close popen pipe after used
  python/paddle/fluid/core.py
Labels: NVIDIA, contributor

#47558 [CodeStyle] remove unused-variable warning in linux
  cmake/flags.cmake
  paddle/fluid/distributed/CMakeLists.txt
  paddle/fluid/distributed/ps/service/communicator/communicator.cc
  paddle/fluid/distributed/ps/table/common_graph_table.cc
  paddle/fluid/distributed/ps/table/memory_dense_table.cc
  paddle/fluid/distributed/ps/table/memory_sparse_table.cc
  paddle/fluid/distributed/rpc/CMakeLists.txt
Labels: contributor, status: proposed

#47339 [PHI] Migrate softmax kernel
  paddle/fluid/framework/ir/mkldnn/mkldnn_inplace_pass_tester.cc
  paddle/fluid/operators/mkldnn/softmax_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/test_mkldnn_caching.cc
  paddle/fluid/operators/mkldnn/test_mkldnn_op_inplace.cc
  paddle/phi/backends/onednn/onednn_reuse.h
  paddle/phi/kernels/onednn/softmax_kernel.cc
Labels: Intel, contributor

#47555 Remove reduntant numpy input in Example code （test=document_fix）
  python/paddle/incubate/optimizer/lookahead.py
  python/paddle/incubate/optimizer/modelaverage.py
  python/paddle/nn/functional/activation.py
  python/paddle/nn/functional/common.py
  python/paddle/nn/functional/conv.py
  python/paddle/nn/functional/loss.py
  python/paddle/nn/functional/norm.py
  python/paddle/nn/functional/pooling.py
  python/paddle/nn/functional/sparse_attention.py
  python/paddle/nn/layer/activation.py
  python/paddle/nn/layer/common.py
  python/paddle/nn/layer/conv.py
  python/paddle/nn/layer/loss.py
  python/paddle/nn/layer/norm.py
  python/paddle/nn/layer/pooling.py
  python/paddle/onnx/export.py
  python/paddle/optimizer/adadelta.py
  python/paddle/optimizer/adamax.py
  python/paddle/optimizer/momentum.py
  python/paddle/optimizer/optimizer.py
  python/paddle/static/input.py
  python/paddle/tensor/linalg.py
  python/paddle/vision/ops.py
Labels: contributor, status: proposed

#47612 Test CUDNN Frontend Build
  paddle/scripts/paddle_build.sh
Labels: NVIDIA, contributor

#47237 Fix oneDNN elementwise_sub dnnl_error in unit test
  paddle/fluid/operators/elementwise/mkldnn/elementwise_mkldnn_op.h
  python/paddle/fluid/tests/unittests/mkldnn/test_elementwise_sub_mkldnn_op.py
Labels: Intel, contributor

#47420 [cherry-pick] FC/matmul(v2) + scale fuse pass (#47127)
  paddle/fluid/framework/ir/CMakeLists.txt
  paddle/fluid/framework/ir/mkldnn/operator_scale_onednn_fuse_pass.cc
  paddle/fluid/framework/ir/mkldnn/operator_scale_onednn_fuse_pass.h
  paddle/fluid/inference/api/paddle_pass_builder.cc
  paddle/fluid/operators/mkldnn/fc_mkldnn_op.cc
  paddle/fluid/platform/mkldnn_reuse.h
  python/paddle/fluid/tests/unittests/ir/inference/test_mkldnn_matmul_activation_fuse_pass.py
  python/paddle/fluid/tests/unittests/ir/inference/test_mkldnn_matmul_v2_activation_fuse_pass.py
Labels: Intel, contributor

#47370 matmul_v2 support new case and fix masked_select bug for xpu, test=kunlun
  paddle/phi/kernels/xpu/masked_select_kernel.cc
  paddle/phi/kernels/xpu/matmul_grad_kernel.cc
  paddle/phi/kernels/xpu/xpu_api_wrapper.h
  python/paddle/fluid/tests/unittests/xpu/test_matmul_v2_op_xpu.py
Labels: contributor

#47391 Optimized oneDNN FC and added operator+unsqueeze2 and operator+reshape2 oneDNN fuse passes
  paddle/fluid/framework/ir/CMakeLists.txt
  paddle/fluid/framework/ir/graph_pattern_detector.cc
  paddle/fluid/framework/ir/graph_pattern_detector.h
  paddle/fluid/framework/ir/mkldnn/operator_reshape2_onednn_fuse_pass.cc
  paddle/fluid/framework/ir/mkldnn/operator_reshape2_onednn_fuse_pass.h
  paddle/fluid/framework/ir/mkldnn/operator_unsqueeze2_onednn_fuse_pass.cc
  paddle/fluid/framework/ir/mkldnn/operator_unsqueeze2_onednn_fuse_pass.h
  paddle/fluid/inference/api/paddle_pass_builder.cc
  paddle/fluid/operators/elementwise/mkldnn/elementwise_mkldnn_op.h
  paddle/fluid/operators/mkldnn/fc_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/transpose_mkldnn_op.cc
  paddle/fluid/platform/mkldnn_reuse.h
Labels: Intel, contributor

#47365 fix deepfm bug, add embedding_sparse_grad kernel, test=kunlun
  paddle/fluid/imperative/gradient_accumulator.cc
  paddle/fluid/platform/device/xpu/xpu2_op_list.h
  paddle/phi/kernels/selected_rows/xpu/adam_kernel.cc
  paddle/phi/kernels/xpu/embedding_grad_kernel.cc
Labels: contributor, status: proposed

#47406 [PHI] Migrate softplus kernel
  paddle/fluid/operators/mkldnn/activation_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/softplus_mkldnn_op.h
  paddle/phi/kernels/onednn/softplus_kernel.cc
Labels: Intel, contributor

#47423 [PHI] Migrate pool2d and pool2d_grad kernels
  paddle/fluid/operators/mkldnn/pool_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/test_mkldnn_op_nhwc.cc
  paddle/phi/backends/onednn/onednn_reuse.h
  paddle/phi/kernels/onednn/pool_grad_kernel.cc
  paddle/phi/kernels/onednn/pool_kernel.cc
Labels: Intel, contributor

#47658 [PHI] Migrate depthwise_conv2d and conv3d kernels
  paddle/fluid/operators/mkldnn/conv_mkldnn_op.cc
  paddle/phi/kernels/onednn/conv_kernel.cc
Labels: Intel

#47585 [XPU] add cumsum op. test=kunlun
  cmake/external/xpu.cmake
  paddle/fluid/platform/device/xpu/xpu2_op_list.h
  paddle/phi/kernels/xpu/cum_kernel.cc
  python/paddle/fluid/tests/unittests/xpu/test_cumsum_op_xpu.py
  python/setup.py.in
Labels: contributor, status: proposed

#47617 slice & mul & requantize tensors to use mem_desc
  paddle/fluid/operators/mkldnn/mul_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/requantize_mkldnn_op.cc
  paddle/fluid/operators/slice_op.cc
Labels: Intel, contributor, status: proposed

#47686 [PHI] Migrate depthwise_conv2d_grad and conv3d_grad kernels
  paddle/fluid/operators/mkldnn/conv_mkldnn_op.cc
  paddle/phi/kernels/onednn/conv_grad_kernel.cc
Labels: Intel, contributor

#47652 [PHI] Migrate batch_norm
  paddle/fluid/framework/ir/mkldnn/mkldnn_conv_bn_fuse_pass_tester.cc
  paddle/fluid/operators/mkldnn/batch_norm_mkldnn_op.cc
  paddle/phi/backends/onednn/onednn_reuse.h
  paddle/phi/kernels/onednn/batch_norm_kernel.cc
Labels: Intel, contributor

#47687 [CodeStyle][E262][E265] make comments start with `# `
  .flake8
  python/paddle/distributed/fleet/launch_utils.py
  python/paddle/distributed/fleet/meta_optimizers/ascend/ascend_parser.py
  python/paddle/distributed/fleet/meta_optimizers/parameter_server_optimizer.py
  python/paddle/distributed/passes/auto_parallel_grad_clip.py
  python/paddle/distributed/passes/ps_trainer_pass.py
  python/paddle/fluid/tests/unittests/dist_fleet_ctr.py
  python/paddle/fluid/tests/unittests/ps/ps_dnn_trainer.py
  python/paddle/fluid/tests/unittests/test_cross_entropy_loss.py
  python/paddle/fluid/tests/unittests/test_fused_feedforward_op.py
  python/paddle/fluid/tests/unittests/test_get_inputs_outputs_in_block.py
  python/paddle/fluid/tests/unittests/test_multi_dot_op.py
  python/paddle/fluid/tests/unittests/test_slice_op.py
  python/paddle/fluid/tests/unittests/test_strided_slice_op.py
  python/paddle/fluid/tests/unittests/white_list/check_op_sequence_instance_0_input_white_list.py
  python/paddle/framework/__init__.py
  tools/parallel_UT_rule.py
  tools/sampcd_processor.py
Labels: contributor, status: proposed

#47693 [CodeStyle] refine pre-commit-config.yaml
  .pre-commit-config.yaml
Labels: contributor, status: proposed

#47368 add roll and roll_grad kernels and strided_slice and strided_slice_grad kernels, test=kunlun
  paddle/fluid/platform/device/xpu/xpu2_op_list.h
  paddle/phi/kernels/strided_slice_grad_kernel.cc
  paddle/phi/kernels/strided_slice_kernel.cc
  paddle/phi/kernels/xpu/roll_grad_kernel.cc
  paddle/phi/kernels/xpu/roll_kernel.cc
  paddle/phi/kernels/xpu/stride_slice_grad_kernel.cc
  paddle/phi/kernels/xpu/stride_slice_kernel.cc
  python/paddle/fluid/tests/unittests/xpu/test_roll_op_xpu.py
  python/paddle/fluid/tests/unittests/xpu/test_strided_slice_op_xpu.py
Labels: contributor, status: proposed

#47706 [CodeStyle] remove hardcoded -Wunused-variable compiler flags
  paddle/fluid/eager/api/manual/eager_manual/forwards/add_n_fwd_func.cc
  paddle/fluid/eager/api/manual/eager_manual/forwards/conv2d_fwd_function.cc
  paddle/fluid/eager/api/manual/fluid_manual/forwards/fused_attention_fwd_func.cc
  paddle/fluid/eager/api/manual/fluid_manual/forwards/fused_feedforward_fwd_func.cc
  paddle/fluid/eager/api/manual/fluid_manual/forwards/fused_gate_attention_fwd_func.cc
  paddle/fluid/eager/api/manual/fluid_manual/forwards/fused_gemm_epilogue_fwd_func.cc
  paddle/fluid/eager/auto_code_generator/eager_generator.cc
  paddle/fluid/operators/dlnne/CMakeLists.txt
  paddle/fluid/pybind/CMakeLists.txt
Labels: contributor, status: proposed

#47421 Fix undefined symbol: shm_open
  paddle/fluid/memory/allocation/CMakeLists.txt
Labels: Intel, contributor

#47739 [phi] remove <fluid/eager/api/utils/global_utils.h> from phi
  paddle/phi/api/yaml/generator/backward_api_gen.py
Labels: contributor, status: proposed

#46289 [Paddle-TRT]Fix cast converter bug , use setOutputType() instaead
  paddle/fluid/inference/tensorrt/convert/cast_op.cc
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_cast.py
Labels: contributor, status: not progressed

#47449 Split quant
  paddle/fluid/framework/ir/graph_pattern_detector.h
  paddle/fluid/framework/ir/mkldnn/compute_propagate_scales_mkldnn_pass.cc
  paddle/fluid/framework/ir/mkldnn/cpu_quantize_pass.cc
  paddle/fluid/framework/ir/mkldnn/cpu_quantize_pass.h
  paddle/fluid/framework/ir/mkldnn/cpu_quantize_pass_tester.cc
  paddle/fluid/framework/ir/mkldnn/cpu_quantize_placement_pass.cc
  paddle/fluid/inference/api/mkldnn_quantizer.cc
  paddle/fluid/inference/api/mkldnn_quantizer_config.cc
  paddle/fluid/inference/api/paddle_analysis_config.h
  paddle/fluid/operators/split_op.cc
  paddle/phi/kernels/onednn/split_kernel.cc
  python/paddle/fluid/contrib/slim/quantization/quant2_int8_mkldnn_pass.py
  python/paddle/fluid/tests/unittests/mkldnn/test_split_mkldnn_op.py
Labels: Intel, contributor

#47682 update AUTHOR. test=kunlun
  AUTHORS.md
Labels: contributor, status: proposed

#47551 [Paddle Inference] allow fold fill_constant && allow nms3 into trt in int8 model
  paddle/fluid/framework/ir/constant_folding_pass.cc
  paddle/fluid/inference/tensorrt/op_teller.cc
  paddle/fluid/inference/tests/api/analyzer_seq_pool1_fuse_statis_tester.cc
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_expand_v2.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_fill_constant.py
Labels: contributor, status: proposed

#47741 Set default gpu arch for cuda 11 on jetson
  cmake/cuda.cmake
Labels: contributor, status: proposed

#47742 Set default gpu arch for cuda 11 on jetson
  cmake/cuda.cmake
Labels: contributor, status: proposed

#47728 [CodeStyle][py2] remove the `next` method for python2 compatibility (PEP 3114)
  python/paddle/fluid/dataloader/dataloader_iter.py
  python/paddle/fluid/reader.py
Labels: contributor, status: proposed

#47722 Fix bug of abs_double_grad in eager mode for kunlun, test=kunlun
  paddle/phi/api/yaml/legacy_backward.yaml
  paddle/phi/kernels/cpu/abs_grad_kernel.cc
  paddle/phi/kernels/gpu/abs_grad_kernel.cu
Labels: contributor, status: proposed

#47701 argsort support n > 16384 and add argsort_grad op for xpu, test=kunlun
  paddle/fluid/platform/device/xpu/xpu2_op_list.h
  paddle/phi/kernels/xpu/argsort_grad_kernel.cc
  paddle/phi/kernels/xpu/argsort_kernel.cc
  python/paddle/fluid/tests/unittests/xpu/test_argsort_op_xpu.py
Labels: contributor, status: proposed

#47661 add adadelta op for xpu, test=kunlun
  paddle/fluid/platform/device/xpu/xpu2_op_list.h
  paddle/phi/kernels/xpu/adadelta_kernel.cc
  python/paddle/fluid/tests/unittests/xpu/test_adadelta_op_xpu.py
  python/paddle/fluid/tests/unittests/xpu/test_clip_by_norm_op_xpu.py
Labels: contributor

#47727 [CodeStyle][py2] remove unnecessary u-prefix in string literal
  python/paddle/fluid/contrib/slim/tests/test_moving_average_abs_max_scale_op.py
  python/paddle/fluid/data_feeder.py
  python/paddle/fluid/tests/unittests/test_backward.py
  python/paddle/fluid/tests/unittests/test_dist_transpiler.py
  python/paddle/fluid/tests/unittests/test_feed_data_check_shape_type.py
  python/paddle/fluid/tests/unittests/test_print_op.py
  python/paddle/framework/framework.py
  python/paddle/tensor/math.py
  tools/prune_for_jetson.py
  tools/remove_grad_op_and_kernel.py
Labels: contributor, status: proposed

#47730 [CodeStyle][py2] use new syntax for metaclass declaration (PEP 3115)
  python/paddle/fluid/incubate/fleet/base/fleet_base.py
Labels: contributor, status: proposed

#47256 fix The first round of evaluation
  python/paddle/framework/io.py
  python/paddle/tensor/creation.py
  python/paddle/tensor/linalg.py
  python/paddle/tensor/search.py
  python/paddle/tensor/stat.py
Labels: contributor, status: proposed

#47770 [phi] rm #include "paddle/fluid/framework/data_layout.h" in phi
  paddle/phi/common/layout.h
  paddle/phi/kernels/gpu/batch_norm_grad_kernel.cu
  paddle/phi/kernels/gpu/batch_norm_kernel.cu
Labels: contributor, status: proposed

#47778 [PHI decoupling] remove "paddle/fluid/platform/dynload/cublas.h" in phi
  paddle/phi/kernels/funcs/blas/blas_impl.cu.h
Labels: contributor

#46768 Final changes to introduce mem_desc to be hold in Tensor
  paddle/fluid/framework/tensor_util.cc
  paddle/fluid/operators/fused/mkldnn/fusion_rnn_mkldnn.h
  paddle/fluid/operators/fused/mkldnn/multi_gru_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/dequantize_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/fc_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/interpolate_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/matmul_v2_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/prelu_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/quantize_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/reshape_mkldnn_op.cc
  paddle/fluid/platform/mkldnn_helper.h
  paddle/fluid/platform/mkldnn_utils.h
  paddle/phi/backends/onednn/onednn_reuse.h
  paddle/phi/core/dense_tensor.cc
  paddle/phi/core/dense_tensor.h
  paddle/phi/core/dense_tensor.inl
  paddle/phi/core/dense_tensor_impl.cc
  paddle/phi/kernels/onednn/split_kernel.cc
Labels: Intel

#47762 matmul(v1) code clean up
  paddle/fluid/operators/mkldnn/matmul_v2_mkldnn_op.cc
Labels: Intel, contributor

#47777 Fix for missing oneDNN reorders in profiling
  paddle/fluid/operators/elementwise/mkldnn/elementwise_mkldnn_op.h
  paddle/fluid/operators/mkldnn/conv_transpose_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/fc_mkldnn_op.cc
  paddle/phi/backends/onednn/onednn_reuse.h
  paddle/phi/kernels/onednn/conv_grad_kernel.cc
Labels: Intel, contributor

#47772 [CodeStyle][E266] remove multiple '#' in comments
  paddle/fluid/eager/auto_code_generator/generator/codegen_utils.py
  paddle/fluid/eager/auto_code_generator/generator/eager_gen.py
  paddle/fluid/eager/auto_code_generator/generator/python_c_gen.py
  python/paddle/distributed/fleet/meta_optimizers/ascend/ascend_parser.py
  python/paddle/distributed/launch/controllers/collective.py
  python/paddle/distributed/passes/ps_trainer_pass.py
  python/paddle/distributed/ps/utils/public.py
  python/paddle/fluid/tests/unittests/autograd/test_jvp_and_transpose.py
  python/paddle/fluid/tests/unittests/autograd/test_orig2prim.py
  python/paddle/fluid/tests/unittests/autograd/test_prim2orig.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/transformer_dygraph_model.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_reduce_mean.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_reduce_sum.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_top_k.py
  python/paddle/fluid/tests/unittests/standalone_executor/test_standalone_custom_stream.py
  python/paddle/fluid/tests/unittests/test_batch_norm_op_v2.py
  python/paddle/fluid/tests/unittests/test_bitwise_op.py
  python/paddle/fluid/tests/unittests/test_fold_op.py
  python/paddle/fluid/tests/unittests/test_fusion_seqpool_concat_op.py
  python/paddle/fluid/tests/unittests/test_fusion_seqpool_cvm_concat_op.py
  python/paddle/fluid/tests/unittests/test_math_op_patch_var_base.py
  python/paddle/fluid/tests/unittests/test_nansum_api.py
  python/paddle/fluid/tests/unittests/test_rot90_op.py
  python/paddle/fluid/tests/unittests/test_sparse_unary_op.py
  python/paddle/fluid/tests/unittests/test_tensor_scalar_type_promotion_dynamic.py
  python/paddle/fluid/tests/unittests/test_tril_triu_op.py
  python/paddle/fluid/tests/unittests/test_unfold_op.py
  python/paddle/fluid/tests/unittests/xpu/test_batch_norm_op_xpu.py
  python/paddle/fluid/tests/unittests/xpu/test_bitwise_op_xpu.py
  python/paddle/fluid/tests/unittests/xpu/test_depthwise_conv2d_op_xpu.py
  python/paddle/fluid/tests/unittests/xpu/test_logical_op_xpu.py
  python/paddle/incubate/autograd/primrules.py
  python/paddle/incubate/optimizer/functional/bfgs.py
  python/paddle/incubate/optimizer/functional/lbfgs.py
  python/paddle/nn/layer/norm.py
  python/paddle/profiler/profiler_statistic.py
  python/paddle/utils/cpp_extension/extension_utils.py
Labels: contributor, status: proposed

#47773 [CodeStyle][E266] update .flake8 config
  .flake8
Labels: contributor, status: proposed

#45704 Enable fc passes
  paddle/fluid/inference/api/analysis_config.cc
  paddle/fluid/inference/api/analysis_predictor_tester.cc
  paddle/fluid/inference/api/paddle_analysis_config.h
  paddle/fluid/inference/api/paddle_pass_builder.cc
  paddle/fluid/inference/api/paddle_pass_builder.h
  paddle/fluid/inference/tests/api/analyzer_bert_tester.cc
  paddle/fluid/inference/tests/api/analyzer_dam_tester.cc
  paddle/fluid/inference/tests/api/analyzer_ernie_int8_tester.cc
  paddle/fluid/inference/tests/api/analyzer_ernie_tester.cc
  paddle/fluid/inference/tests/api/analyzer_image_classification_tester.cc
  paddle/fluid/inference/tests/api/analyzer_lexical_analysis_gru_tester.cc
  paddle/fluid/inference/tests/api/analyzer_seq_pool1_tester_helper.h
  paddle/fluid/inference/tests/api/analyzer_transformer_compare_tester.cc
  paddle/fluid/inference/tests/api/analyzer_transformer_profile_tester.cc
  paddle/fluid/inference/tests/api/analyzer_vis_tester.cc
  paddle/fluid/inference/tests/api/analyzer_vit_ocr_tester.cc
  paddle/fluid/pybind/inference_api.cc
  python/paddle/fluid/contrib/slim/tests/quant2_int8_lstm_model.py
  python/paddle/fluid/tests/unittests/ir/inference/test_mkldnn_matmul_op_output_fuse_pass.py
Labels: Intel, contributor

#47776 [PHI decoupling] remove framework/data_type.h from phi
  paddle/phi/core/utils/data_type.h
  paddle/phi/kernels/cpu/arg_min_max_kernel.cc
  paddle/phi/kernels/cpu/cumprod_grad_kernel.cc
  paddle/phi/kernels/cpu/unique_consecutive_kernel.cc
  paddle/phi/kernels/funcs/math_function.cc
  paddle/phi/kernels/funcs/math_function.cu
  paddle/phi/kernels/funcs/math_function_impl.h
  paddle/phi/kernels/gpu/arg_min_max_kernel.cu
  paddle/phi/kernels/gpu/cumprod_grad_kernel.cu
  paddle/phi/kernels/gpu/unique_consecutive_kernel.cu
  paddle/phi/kernels/impl/isclose_kernel_impl.h
  paddle/phi/kernels/xpu/arg_min_max_kernel.cc
Labels: contributor, status: proposed

#47780 Move dropout removing pass at the beginning of the INT8 process
  paddle/fluid/inference/api/paddle_pass_builder.cc
Labels: Intel, int8, contributor

#47787 [PHI decoupling] remove "paddle/fluid/platform/dynload/xxx.h" in phi
  paddle/phi/kernels/funcs/blas/blas.h
  paddle/phi/kernels/funcs/blas/blas_impl.h
  paddle/phi/kernels/funcs/blas/blas_impl.hip.h
  paddle/phi/kernels/funcs/cpu_vec.h
  paddle/phi/kernels/funcs/math_function.cc
  paddle/phi/kernels/gpu/rnn_functor.h
  paddle/phi/kernels/gpu/sync_batch_norm_utils.h
  paddle/phi/kernels/gpudnn/softmax_gpudnn.h
  paddle/phi/kernels/impl/conv_cudnn_impl.h
Labels: contributor, status: proposed

#47756 [CodeStyle][F821] fix test_exception in test_unpool3d_op and test_unpool_op
  python/paddle/fluid/tests/unittests/test_unpool3d_op.py
  python/paddle/fluid/tests/unittests/test_unpool_op.py
Labels: contributor, status: proposed

#47445 XPU multi-card support eager mode
  paddle/fluid/distributed/collective/BKCLTools.cc
  paddle/fluid/distributed/collective/BKCLTools.h
  paddle/fluid/distributed/collective/CMakeLists.txt
  paddle/fluid/distributed/collective/Common.cc
  paddle/fluid/distributed/collective/Common.h
  paddle/fluid/distributed/collective/ProcessGroupBKCL.cc
  paddle/fluid/distributed/collective/ProcessGroupBKCL.h
  paddle/fluid/distributed/collective/reducer.cc
  paddle/fluid/operators/math/concat_and_split.cc
  paddle/fluid/platform/collective_helper.cc
  paddle/fluid/platform/device/xpu/xpu2_op_list.h
  paddle/fluid/pybind/CMakeLists.txt
  paddle/fluid/pybind/distributed_py.cc
  paddle/fluid/pybind/pybind.cc
  paddle/fluid/pybind/xpu_streams_py.cc
  paddle/fluid/pybind/xpu_streams_py.h
  paddle/phi/backends/xpu/xpu_context.cc
  paddle/phi/backends/xpu/xpu_context.h
  paddle/phi/kernels/funcs/concat_and_split_functor.h
  paddle/phi/kernels/funcs/math_function.cc
  paddle/phi/kernels/xpu/concat_and_split.cc
  paddle/phi/kernels/xpu/split_kernel.cc
  python/paddle/device/__init__.py
  python/paddle/device/xpu/__init__.py
  python/paddle/distributed/collective.py
  python/paddle/fluid/core.py
  python/paddle/fluid/tests/unittests/xpu/parallel_dygraph_dataparallel_with_pylayer.py
  python/paddle/fluid/tests/unittests/xpu/parallel_dygraph_gradient_check.py
  python/paddle/fluid/tests/unittests/xpu/parallel_dygraph_gradient_check_in_eager_mode.py
  python/paddle/fluid/tests/unittests/xpu/process_group_bkcl.py
  python/paddle/fluid/tests/unittests/xpu/test_collective_process_group.py
  python/paddle/fluid/tests/unittests/xpu/test_parallel_dygraph_dataparallel.py
  python/paddle/fluid/tests/unittests/xpu/test_xpu_stream_event.py
  python/setup.py.in
Labels: contributor, status: proposed

#47823 [PHI Decoupling] remove "paddle/fluid/platform/place.h" in phi.
  paddle/phi/common/scalar.cc
  paddle/phi/kernels/cpu/put_along_axis_grad_kernel.cc
  paddle/phi/kernels/cpu/put_along_axis_kernel.cc
  paddle/phi/kernels/cpu/take_along_axis_grad_kernel.cc
  paddle/phi/kernels/cpu/take_along_axis_kernel.cc
  paddle/phi/kernels/gpu/put_along_axis_grad_kernel.cu
  paddle/phi/kernels/gpu/put_along_axis_kernel.cu
  paddle/phi/kernels/gpu/take_along_axis_grad_kernel.cu
  paddle/phi/kernels/gpu/take_along_axis_kernel.cu
Labels: contributor, status: proposed

#47815 [PHI Decoupling] remove dependency on "paddle/fluid/platform/errors.h" and "paddle/fluid/platform/fast_divmod.h" in phi.
  paddle/phi/backends/dynload/tensorrt.cc
  paddle/phi/core/selected_rows_impl.cc
  paddle/phi/kernels/autotune/auto_tune_base.h
  paddle/phi/kernels/funcs/concat_funcs.h
  paddle/phi/kernels/funcs/interpolate_function.h
  paddle/phi/kernels/funcs/pooling.cu
  paddle/phi/kernels/gpu/interpolate_grad_kernel.cu
  paddle/phi/kernels/gpu/interpolate_kernel.cu
  paddle/phi/kernels/impl/broadcast_tensors_kernel_impl.h
  paddle/phi/tests/api/scale_api.h
  paddle/phi/tests/kernels/test_math_function.cc
  paddle/phi/tests/kernels/test_math_function.cu
Labels: contributor, status: proposed

#47817 [PHI Decoupling] remove "paddle/fluid/platform/float16.h" and "paddle/fluid/platform/for_range.h" in phi.
  paddle/phi/kernels/cpu/fill_grad_kernel.cc
  paddle/phi/kernels/cpu/fill_kernel.cc
  paddle/phi/kernels/funcs/math_function.cc
  paddle/phi/kernels/funcs/math_function.cu
  paddle/phi/kernels/gpu/bmm_grad_kernel.cu
  paddle/phi/kernels/gpu/bmm_kernel.cu
  paddle/phi/kernels/gpu/cholesky_kernel.cu
  paddle/phi/kernels/gpu/fill_grad_kernel.cu
  paddle/phi/kernels/gpu/fill_kernel.cu
  paddle/phi/kernels/gpu/overlap_add_grad_kernel.cu
  paddle/phi/kernels/gpu/overlap_add_kernel.cu
  paddle/phi/kernels/gpu/set_value_kernel.cu
  paddle/phi/kernels/gpudnn/conv_grad_kernel.cu
  paddle/phi/kernels/impl/atan2_grad_kernel_impl.h
  paddle/phi/kernels/impl/atan2_kernel_impl.h
  paddle/phi/kernels/impl/cholesky_grad_kernel_impl.h
  paddle/phi/kernels/impl/conv_cudnn_impl.h
  paddle/phi/kernels/impl/eye_kernel_impl.h
  paddle/phi/kernels/impl/selu_grad_kernel_impl.h
  paddle/phi/kernels/impl/selu_kernel_impl.h
  paddle/phi/kernels/xpu/bmm_grad_kernel.cc
  paddle/phi/kernels/xpu/bmm_kernel.cc
  paddle/phi/kernels/xpu/xpu_api_wrapper.h
Labels: contributor, status: proposed

#47808 [PHI decoupling] remove "paddle/fluid/platform/device/gpu/gpu_launch_config.h" in phi
  paddle/phi/kernels/funcs/elementwise_grad_base.h
  paddle/phi/kernels/funcs/gather.cu.h
  paddle/phi/kernels/funcs/reduce_function.h
  paddle/phi/kernels/funcs/scatter.cu.h
  paddle/phi/kernels/gpu/histogram_kernel.cu
  paddle/phi/kernels/gpu/index_add_grad_kernel.cu
  paddle/phi/kernels/gpu/index_add_kernel.cu
  paddle/phi/kernels/gpu/index_sample_grad_kernel.cu
  paddle/phi/kernels/gpu/index_sample_kernel.cu
  paddle/phi/kernels/gpu/index_select_grad_kernel.cu
  paddle/phi/kernels/gpu/index_select_impl.h
  paddle/phi/kernels/gpu/index_select_kernel.cu
  paddle/phi/kernels/gpu/nanmedian_grad_kernel.cu
  paddle/phi/kernels/gpu/nanmedian_kernel.cu
  paddle/phi/kernels/gpu/top_k_kernel.cu
Labels: contributor, status: proposed

#47822 [PHI decoupling] remove fluid/framework/generator.h from phi
  paddle/phi/kernels/cpu/class_center_sample_kernel.cc
  paddle/phi/kernels/cpu/dropout_kernel.cc
  paddle/phi/kernels/cpu/gaussian_kernel.cc
  paddle/phi/kernels/cpu/rnn_functor.h
  paddle/phi/kernels/cpu/rrelu_kernel.cc
  paddle/phi/kernels/gpu/gaussian_kernel.cu
  paddle/phi/kernels/gpu/gumbel_softmax_kernel.cu
  paddle/phi/kernels/gpu/rnn_kernel.cu.cc
  paddle/phi/kernels/xpu/gaussian_kernel.cc
Labels: contributor, status: proposed

#47831 [PHI decoupling] remove #include "paddle/fluid/platform/bfloat16.h" in phi
  paddle/phi/kernels/cpu/concat_kernel.cc
  paddle/phi/kernels/cpu/fill_grad_kernel.cc
  paddle/phi/kernels/cpu/fill_kernel.cc
  paddle/phi/kernels/funcs/math_function.cc
  paddle/phi/kernels/funcs/math_function.cu
  paddle/phi/kernels/gpu/concat_kernel.cu
  paddle/phi/kernels/gpu/fill_grad_kernel.cu
  paddle/phi/kernels/gpu/fill_kernel.cu
Labels: contributor, status: proposed

#47842 [PHI decoupling] remove dependency on 2 header files in fluid from phi
  paddle/phi/kernels/cpu/scale_kernel.cc
  paddle/phi/kernels/funcs/reduce_grad_functions.h
  paddle/phi/kernels/gpu/dot_kernel.cu
  paddle/phi/kernels/impl/dot_grad_kernel_impl.h
  paddle/phi/kernels/impl/sign_kernel_impl.h
Labels: contributor, status: proposed

#47840 [PHI decoupling] remove fluid/framework/lod_tensor.h from phi
  paddle/phi/api/lib/utils/tensor_utils.h
  paddle/phi/kernels/funcs/sequence2batch.h
Labels: contributor, status: proposed

#47868 [PHI decoupling] remove "paddle/fluid/framework/op_registry.h" from phi
  paddle/phi/kernels/funcs/batch_norm_utils.h
  paddle/phi/kernels/gpudnn/affine_grid_grad_kernel.cu
  paddle/phi/kernels/gpudnn/affine_grid_kernel.cu
Labels: contributor, status: proposed

#47838 bugfix in XPU legacy_dygraph distributed training:
  paddle/fluid/platform/collective_helper.cc
Labels: contributor

#47363 [IPU]: add model_runtime backend support in IPU
  paddle/fluid/framework/data_type_transform.cc
  paddle/fluid/framework/ir/node.cc
  paddle/fluid/framework/ir/node.h
  paddle/fluid/platform/device/ipu/CMakeLists.txt
  paddle/fluid/platform/device/ipu/ipu_backend.cc
  paddle/fluid/platform/device/ipu/ipu_executor.cc
  paddle/fluid/platform/device/ipu/ipu_executor.h
  paddle/fluid/platform/device/ipu/ipu_strategy.cc
  paddle/fluid/platform/device/ipu/ipu_strategy.h
  paddle/fluid/platform/device/ipu/ipu_utils.cc
  paddle/fluid/platform/device/ipu/ipu_utils.h
  python/paddle/fluid/tests/unittests/ipu/test_modelruntime_ipu.py
Labels: contributor

#47893 fix coverage bug,test=document_fix
  tools/coverage/paddle_coverage.sh
Labels: contributor, status: proposed

#47869 [CodeStyle][F821] refactor unittests utility function `parameterized` related code
  python/paddle/fluid/tests/unittests/distribution/parameterize.py
  python/paddle/fluid/tests/unittests/fft/test_fft_with_static_graph.py
Labels: contributor, status: proposed

#47112 Inference lite opencl
  paddle/fluid/inference/analysis/argument.h
  paddle/fluid/inference/analysis/ir_pass_manager.cc
  paddle/fluid/inference/analysis/ir_passes/lite_subgraph_pass.cc
  paddle/fluid/inference/api/analysis_config.cc
  paddle/fluid/inference/api/analysis_predictor.cc
  paddle/fluid/inference/api/paddle_analysis_config.h
  paddle/fluid/inference/lite/engine.cc
  paddle/fluid/inference/lite/engine.h
  paddle/fluid/pybind/inference_api.cc
Labels: contributor, heco

#47899 [CodeStyle][F821] fix undefined variables due to missing imports, misspelled variable names
  python/paddle/audio/functional/window.py
  python/paddle/distributed/auto_parallel/cost/base_cost.py
  python/paddle/distributed/auto_parallel/operators/dist_reshape.py
  python/paddle/distributed/auto_parallel/planner.py
  python/paddle/distributed/fleet/base/orthogonal_strategy.py
  python/paddle/distributed/fleet/data_generator/data_generator.py
  python/paddle/distributed/fleet/layers/mpu/mp_ops.py
  python/paddle/distributed/fleet/runtime/the_one_ps.py
  python/paddle/distributed/fleet/utils/fs.py
  python/paddle/distributed/launch/job/pod.py
  python/paddle/distributed/launch/utils/kv_client.py
  python/paddle/distributed/passes/auto_parallel_data_parallel_optimization.py
  python/paddle/distributed/ps/utils/public.py
  python/paddle/distribution/variable.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_equal.py
  python/paddle/fluid/tests/unittests/test_dropout_nd_op.py
  python/paddle/fluid/tests/unittests/test_mean_op.py
Labels: contributor, status: proposed

#47844 Modified mem_desc() to return reference to Tensor::memory::desc to avoid copying
  paddle/phi/core/dense_tensor.inl
  paddle/phi/core/dense_tensor_impl.cc
Labels: Intel, contributor

#47870 [PHI decoupling] remove dependency on "paddle/fluid/operators/elementwise/xxx.h" in phi
  paddle/phi/kernels/gpu/label_smooth_grad_kernel.cu
  paddle/phi/kernels/gpu/label_smooth_kernel.cu
  paddle/phi/kernels/gpu/p_norm_kernel.cu
  paddle/phi/kernels/gpu/viterbi_decode_kernel.cu
Labels: contributor, status: proposed

#47926 [PHI decoupling] remove "paddle/fluid/platform/complex.h" in phi
  paddle/phi/backends/dynload/lapack.h
  paddle/phi/kernels/cpu/concat_kernel.cc
  paddle/phi/kernels/gpu/concat_kernel.cu
  paddle/phi/kernels/gpu/pad_kernel.cu
Labels: contributor, status: proposed

#47968 [CodeStyle][F821] fix remaining F821 issues
  .flake8
  python/paddle/distributed/auto_parallel/completion.py
  python/paddle/distributed/auto_parallel/cost/tensor_cost.py
  python/paddle/distributed/auto_parallel/operators/dist_reduce_sum_p.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/test_closure_analysis.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/yolov3.py
  python/paddle/fluid/tests/unittests/gradient_checker.py
  python/paddle/fluid/tests/unittests/test_auto_parallel_reshard_serial.py
  python/paddle/fluid/tests/unittests/test_reorder_lod_tensor.py
  python/paddle/fluid/tests/unittests/test_weight_normalization.py
Labels: contributor, status: proposed

#47782 Added optimization pass for oneDNN layernorm kernel
  paddle/fluid/framework/ir/CMakeLists.txt
  paddle/fluid/framework/ir/graph_pattern_detector.cc
  paddle/fluid/framework/ir/graph_pattern_detector.h
  paddle/fluid/framework/ir/mkldnn/layer_norm_onednn_optimization_pass.cc
  paddle/fluid/framework/ir/mkldnn/layer_norm_onednn_optimization_pass.h
  paddle/fluid/inference/api/paddle_pass_builder.cc
  paddle/fluid/operators/mkldnn/layer_norm_mkldnn_op.cc
Labels: Intel, contributor

#47963 更改了引用格式
  python/paddle/fluid/dataloader/batch_sampler.py
  python/paddle/fluid/dataloader/dataset.py
  python/paddle/fluid/dataloader/sampler.py
Labels: contributor, status: proposed

#48005 fix coverage ci bug, test=document_fix
  tools/coverage/paddle_coverage.sh
Labels: contributor, status: proposed

#46770 Add bf16 data type support to oneDNN bilinear_interp kernel
  paddle/fluid/framework/ir/graph_pattern_detector.cc
  paddle/fluid/framework/ir/mkldnn/cpu_bfloat16_placement_pass.cc
  paddle/fluid/inference/api/paddle_pass_builder.cc
  paddle/phi/kernels/onednn/interpolate_kernel.cc
  python/paddle/fluid/tests/unittests/mkldnn/test_bilinear_interp_v2_mkldnn_op.py
Labels: Intel

#48020 [PHI decoupling] remove "paddle/fluid/framework/gpu_utils.h" in phi
  paddle/phi/kernels/gpu/transpose_kernel.cu
Labels: contributor, status: proposed

#48031 xpu.cmake: use baidu-kunlun-product. update to 1116.
  cmake/external/xpu.cmake
Labels: contributor, status: proposed

#48062 [PHI decoupling] move "paddle/fluid/operators/math.h" to phi
  paddle/fluid/operators/cross_entropy_op.h
  paddle/fluid/operators/dequantize_log_op.cu
  paddle/fluid/operators/detection/sigmoid_focal_loss_op.cu
  paddle/fluid/operators/math/cross_entropy.cu
  paddle/fluid/operators/sequence_ops/sequence_softmax_op.cu
  paddle/phi/kernels/cpu/bce_loss_kernel.cc
  paddle/phi/kernels/cpu/nll_loss_grad_kernel.cc
  paddle/phi/kernels/funcs/functors.h
  paddle/phi/kernels/funcs/math.h
  paddle/phi/kernels/gpu/nll_loss.h
  paddle/phi/kernels/gpu/sigmoid_cross_entropy_with_logits.h
  paddle/phi/kernels/gpu/sigmoid_cross_entropy_with_logits_grad_kernel.cu
  paddle/phi/kernels/gpu/sigmoid_cross_entropy_with_logits_kernel.cu
  paddle/phi/kernels/impl/selu_kernel_impl.h
Labels: contributor, status: proposed

#48057 rm "paddle/phi/kernels/gpu/batch_norm_utils.h" in phi
  paddle/phi/kernels/cpu/batch_norm_grad_kernel.cc
  paddle/phi/kernels/gpu/batch_norm_grad_kernel.cu
  paddle/phi/kernels/gpu/batch_norm_kernel.cu
  paddle/phi/kernels/gpu/batch_norm_utils.h
Labels: contributor, status: proposed

#47916 Remove reduntant numpy input in Example code
  python/paddle/distributed/utils/moe_utils.py
  python/paddle/fft.py
  python/paddle/sparse/nn/functional/activation.py
  python/paddle/sparse/nn/layer/activation.py
Labels: contributor, status: proposed

#48065 [PHI decoupling] move "function_traits.h" from fluid to phi
  paddle/phi/kernels/funcs/broadcast_function.h
  paddle/phi/kernels/funcs/elementwise_base.h
  paddle/phi/kernels/funcs/function_traits.h
Labels: contributor

#46658 add ffn & attention test=kunlun
  paddle/fluid/operators/fused/CMakeLists.txt
  paddle/fluid/operators/fused/fused_attention_op_xpu.cc
  paddle/fluid/operators/fused/fused_feedforward_op_xpu.cc
  paddle/fluid/operators/fused/xpu_fused_common_function.h
  paddle/fluid/platform/device/xpu/xpu2_op_list.h
  paddle/phi/kernels/xpu/xpu_api_wrapper.h
  python/paddle/fluid/tests/unittests/xpu/test_fused_attention_op_xpu.py
  python/paddle/fluid/tests/unittests/xpu/test_fused_feedforward_op_xpu.py
Labels: contributor

#48066 optimizing a bit tensor_array initialization checking
  paddle/phi/core/tensor_array.cc
Labels: contributor, status: proposed

#48001 [PHI decoupling] remove "paddle/fluid/framework/convert_utils.h" in phi
  paddle/fluid/framework/convert_utils.cc
  paddle/fluid/framework/convert_utils.h
  paddle/fluid/operators/prune_gate_by_capacity_op.cu
  paddle/phi/core/utils/data_type.h
  paddle/phi/infermeta/unary.cc
  paddle/phi/kernels/cpu/index_sample_grad_kernel.cc
  paddle/phi/kernels/cpu/index_sample_kernel.cc
  paddle/phi/kernels/cpu/put_along_axis_grad_kernel.cc
  paddle/phi/kernels/cpu/put_along_axis_kernel.cc
  paddle/phi/kernels/cpu/take_along_axis_kernel.cc
  paddle/phi/kernels/funcs/math_function.h
  paddle/phi/kernels/funcs/unique_functor.h
  paddle/phi/kernels/gpu/fill_diagonal_kernel.cu
  paddle/phi/kernels/gpu/index_sample_grad_kernel.cu
  paddle/phi/kernels/gpu/index_sample_kernel.cu
  paddle/phi/kernels/gpu/put_along_axis_grad_kernel.cu
  paddle/phi/kernels/gpu/put_along_axis_kernel.cu
  paddle/phi/kernels/gpu/sync_batch_norm_utils.h
  paddle/phi/kernels/gpu/take_along_axis_grad_kernel.cu
  paddle/phi/kernels/gpu/take_along_axis_kernel.cu
Labels: contributor, status: proposed

#48051 [PHI decoupling] remove "paddle/fluid/operators/amp/fp16_type_traits.h" in phi
  paddle/fluid/operators/group_norm_op.cu
  paddle/fluid/operators/uniform_random_op.h
  paddle/phi/kernels/funcs/functors.h
  paddle/phi/kernels/gpu/norm_grad_kernel.cu
  paddle/phi/kernels/gpu/norm_kernel.cu
  paddle/phi/kernels/gpu/sgd_kernel.cu
  paddle/phi/kernels/primitive/functor_primitives.h
Labels: contributor, status: proposed

#48064 fix onednn prelu lincense header
  paddle/phi/kernels/onednn/prelu_kernel.cc
Labels: Intel, contributor

#47800 cast and gradient_accumulator support double for xpu, test=kunlun
  paddle/fluid/imperative/gradient_accumulator.cc
  paddle/fluid/platform/device/xpu/xpu2_op_list.h
  paddle/phi/kernels/xpu/cast_kernel.cc
  python/paddle/fluid/tests/unittests/xpu/test_adadelta_op_xpu.py
  python/paddle/fluid/tests/unittests/xpu/test_cast_op_xpu.py
Labels: contributor

#48032 Allow to specify train_bs and eval_bs separately in hapi.fit()
  python/paddle/hapi/model.py
  python/paddle/tests/test_model.py
Labels: contributor, status: proposed

#47454 CUDNN v8 Implementation of Convolution Kernels
  paddle/fluid/platform/device/gpu/cuda/cudnn_desc.h
  paddle/fluid/platform/flags.cc
  paddle/phi/kernels/CMakeLists.txt
  paddle/phi/kernels/autotune/CMakeLists.txt
  paddle/phi/kernels/autotune/cache.cc
  paddle/phi/kernels/autotune/cache.h
  paddle/phi/kernels/autotune/cache_cudnn_frontend.h
  paddle/phi/kernels/gpudnn/conv_cudnn_frontend.h
  paddle/phi/kernels/gpudnn/conv_cudnn_v7.h
  paddle/phi/kernels/gpudnn/conv_gpudnn_base.h
  paddle/phi/kernels/gpudnn/conv_grad_kernel.cu
  paddle/phi/kernels/gpudnn/conv_kernel.cu
Labels: NVIDIA, contributor

#48076 fix device id issue for xpu eager mode
  paddle/fluid/distributed/collective/ProcessGroupBKCL.cc
  paddle/fluid/eager/auto_code_generator/generator/python_c_gen.py
  paddle/fluid/pybind/distributed_py.cc
Labels: contributor, status: proposed

#48074 Add description to `nn.functional.celu`
  python/paddle/nn/functional/activation.py
Labels: contributor, status: proposed

#47882 correct sync behavior for XPU distributed training
  paddle/fluid/distributed/collective/BKCLTools.h
  paddle/fluid/distributed/collective/ProcessGroupBKCL.cc
  paddle/phi/backends/xpu/xpu_context.cc
  paddle/phi/kernels/xpu/concat_and_split_functor.cc
Labels: contributor, status: proposed

#48097 [PHI decoupling] move "gpu_device_function.h" from fluid to phi
  paddle/phi/backends/gpu/cuda/cuda_device_function.h
  paddle/phi/backends/gpu/gpu_device_function.h
  paddle/phi/backends/gpu/rocm/rocm_device_function.h
  paddle/phi/kernels/funcs/elementwise_grad_base.h
  paddle/phi/kernels/funcs/reduce_function.h
  paddle/phi/kernels/gpu/activation_grad_kernel.cu
  paddle/phi/kernels/gpu/activation_kernel.cu
  paddle/phi/kernels/gpu/affine_grid_grad_kernel.cu
  paddle/phi/kernels/gpu/affine_grid_kernel.cu
  paddle/phi/kernels/gpu/cross_entropy_grad_kernel.cu
  paddle/phi/kernels/gpu/cross_entropy_kernel.cu
  paddle/phi/kernels/gpu/depthwise_conv.h
  paddle/phi/kernels/gpu/grid_sample_grad_kernel.cu
  paddle/phi/kernels/gpu/group_norm_utils.h
  paddle/phi/kernels/gpu/interpolate_kernel.cu
  paddle/phi/kernels/gpudnn/affine_grid_grad_kernel.cu
  paddle/phi/kernels/gpudnn/affine_grid_kernel.cu
  paddle/phi/kernels/gpudnn/softmax_gpudnn.h
  paddle/phi/kernels/primitive/compute_primitives.h
Labels: contributor, status: proposed

#48119 [PHI] Migrate conv_transpose kernel
  paddle/fluid/framework/ir/mkldnn/conv_bias_mkldnn_fuse_pass.cc
  paddle/fluid/framework/ir/mkldnn/mkldnn_conv_bn_fuse_pass_tester.cc
  paddle/fluid/operators/mkldnn/conv_transpose_mkldnn_op.cc
  paddle/fluid/operators/ops_extra_info.h
  paddle/phi/kernels/onednn/conv_transpose_kernel.cc
Labels: Intel, contributor

#47949 Remove API: pad_constant_like
  python/paddle/fluid/layers/nn.py
  python/paddle/fluid/tests/unittests/test_pad_constant_like.py
Labels: contributor, status: proposed

#48023 [PHI] Migrate matmul_grad kernel
  paddle/fluid/operators/mkldnn/matmul_v2_mkldnn_op.cc
  paddle/phi/backends/onednn/onednn_reuse.h
  paddle/phi/kernels/onednn/matmul_grad_kernel.cc
Labels: Intel, contributor

#48069 [PHI decoupling] move "macros.h" from fluid to phi
  paddle/fluid/platform/macros.h
  paddle/phi/core/macros.h
  paddle/phi/kernels/funcs/pooling.h
Labels: contributor, status: proposed

#48160 [PHI decoupling] move cross_entropy from fluid to phi
  paddle/fluid/operators/collective/c_softmax_with_cross_entropy_op.cu
  paddle/fluid/operators/collective/c_softmax_with_cross_entropy_op.h
  paddle/fluid/operators/cross_entropy_op.h
  paddle/fluid/operators/math/CMakeLists.txt
  paddle/fluid/operators/softmax_with_cross_entropy_op_npu.cc
  paddle/phi/kernels/cpu/cross_entropy_kernel.cc
  paddle/phi/kernels/funcs/CMakeLists.txt
  paddle/phi/kernels/funcs/cross_entropy.cc
  paddle/phi/kernels/funcs/cross_entropy.cu
  paddle/phi/kernels/funcs/cross_entropy.h
  paddle/phi/kernels/gpu/cross_entropy_grad_kernel.cu
  paddle/phi/kernels/gpu/cross_entropy_kernel.cu
Labels: contributor, status: proposed

#48177 add author
  AUTHORS.md
Labels: contributor, status: proposed

#47954 [Clean Fluid API]Remove API: gather
  python/paddle/fluid/layers/detection.py
  python/paddle/fluid/layers/nn.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/bert_dygraph_model.py
  python/paddle/fluid/tests/unittests/ipu/test_fp16_support_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_gather_op_ipu.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_gather_op.py
  python/paddle/fluid/tests/unittests/mlu/test_gather_nd_op_mlu.py
  python/paddle/fluid/tests/unittests/mlu/test_gather_op_mlu.py
  python/paddle/fluid/tests/unittests/npu/test_gather_nd_op_npu.py
  python/paddle/fluid/tests/unittests/npu/test_gather_op_npu.py
  python/paddle/fluid/tests/unittests/test_gather_nd_op.py
  python/paddle/fluid/tests/unittests/test_gather_op.py
  python/paddle/fluid/tests/unittests/test_imperative_deepcf.py
Labels: contributor, status: proposed

#47969 [Clean Fluid API]Remove API: selu
  python/paddle/fluid/layers/nn.py
  python/paddle/fluid/tests/unittests/test_selu_op.py
Labels: contributor, status: proposed

#48154 add check_xpu_dependence.sh script.
  cmake/external/xpu.cmake
Labels: contributor, status: proposed

#48114 add adamw suppor xpu, test=kunlun
  paddle/fluid/platform/device/xpu/xpu2_op_list.h
  paddle/phi/kernels/xpu/adamw_kernel.cc
  python/paddle/fluid/tests/unittests/xpu/test_adamw_op_xpu.py
Labels: contributor, status: proposed

#48075 [PHI decoupling] move "thread pool" from fluid to phi
  paddle/fluid/framework/CMakeLists.txt
  paddle/fluid/framework/scope.cc
  paddle/fluid/framework/threadpool.h
  paddle/fluid/framework/threadpool_test.cc
  paddle/phi/core/CMakeLists.txt
  paddle/phi/core/threadpool.cc
  paddle/phi/core/threadpool.h
  paddle/phi/kernels/selected_rows/cpu/adam_kernel.cc
Labels: contributor, status: proposed

#47972 [Clean Fluid API]Remove API: crop
  python/paddle/fluid/layers/nn.py
  python/paddle/fluid/tests/unittests/test_layers.py
Labels: contributor, status: proposed

#47945 [Clean Fluid API]Remove API: lrn (remove directly)
  python/paddle/fluid/layers/nn.py
  python/paddle/fluid/tests/unittests/test_layers.py
  python/paddle/fluid/tests/unittests/test_lrn_op.py
Labels: contributor, status: proposed

#47960 [Clean Fluid API]Remove API: scatter_nd scatter_nd_add
  python/paddle/fluid/layers/nn.py
  python/paddle/fluid/tests/unittests/test_scatter_nd_op.py
Labels: contributor, status: proposed

#48061 [PHI] Migrate mul_grad kernel
  paddle/fluid/operators/mkldnn/mul_mkldnn_op.cc
  paddle/phi/backends/onednn/onednn_reuse.h
  paddle/phi/kernels/onednn/matmul_grad_kernel.cc
Labels: Intel, contributor

#46917 add fc-residual quantization
  paddle/fluid/framework/ir/graph_pattern_detector.cc
  paddle/fluid/framework/ir/mkldnn/cpu_bfloat16_pass.cc
  paddle/fluid/framework/ir/mkldnn/cpu_quantize_pass.cc
  paddle/fluid/framework/ir/mkldnn/cpu_quantize_pass.h
  paddle/fluid/framework/ir/mkldnn/cpu_quantize_squash_pass.cc
  paddle/fluid/framework/ir/mkldnn/fc_elementwise_add_mkldnn_fuse_pass.cc
  paddle/fluid/framework/ir/mkldnn/fc_mkldnn_pass.cc
  paddle/fluid/framework/ir/mkldnn/fc_mkldnn_pass.h
  paddle/fluid/inference/api/paddle_pass_builder.cc
  paddle/fluid/operators/mkldnn/fc_mkldnn_op.cc
Labels: Intel, int8, contributor

#48218 [CodeStyle][py2][py311] replace deprecated `inspect.getargspec` with `inspect.getfullargspec`
  python/paddle/distributed/auto_parallel/dist_tensor.py
  python/paddle/fluid/dygraph/dygraph_to_static/utils.py
  python/paddle/fluid/layers/nn.py
  python/paddle/hapi/model.py
Labels: contributor, status: proposed

#48117 [PHI decoupling] remove "gpu_device_function.h" in fluid.
  paddle/fluid/operators/activation_op.kps
  paddle/fluid/operators/elementwise/elementwise_op_function.h
  paddle/fluid/operators/fused/fused_attention_op.cu
  paddle/fluid/operators/fused/fused_bias_dropout_residual_layer_norm_op.cu
  paddle/fluid/operators/fused/fused_dropout_common.h
  paddle/fluid/operators/fused/fused_fc_elementwise_layernorm_op.cu
  paddle/fluid/operators/fused/fused_gate_attention_op.cu
  paddle/fluid/operators/fused/fused_multi_transformer_op.cu.h
  paddle/fluid/operators/group_norm_op.cu
  paddle/fluid/operators/layer_norm_kernel.cu.h
  paddle/fluid/operators/math/beam_search.cu
  paddle/fluid/operators/row_conv_op.cu
  paddle/fluid/operators/top_k_function_cuda.h
  paddle/fluid/platform/device/gpu/cuda/cuda_device_function.h
  paddle/fluid/platform/device/gpu/cuda_helper_test.cu
  paddle/fluid/platform/device/gpu/gpu_device_function.h
  paddle/fluid/platform/device/gpu/rocm/rocm_device_function.h
Labels: contributor

#48113 Delete caching from requantize_mkldnn_op and changed to Acquire API
  paddle/fluid/operators/mkldnn/requantize_mkldnn_op.cc
Labels: Intel, contributor

#48118 Some residualdata fixes
  paddle/fluid/framework/ir/mkldnn/cpu_bfloat16_pass.cc
  paddle/fluid/framework/ir/mkldnn/matmul_elementwise_add_mkldnn_fuse_pass.cc
  paddle/fluid/operators/ops_extra_info.h
Labels: Intel, BF16, contributor

#47643 [CodeStyle][py2][U008] remove unnecessary args in `super()` for some example code
  python/paddle/distributed/spawn.py
  python/paddle/fluid/dygraph/jit.py
Labels: contributor, status: proposed

#48203 CudnnNormConvolution is no longer supported on NVIDIA Hopper GPUs
  paddle/fluid/operators/fused/cudnn_norm_conv.cu.h
  paddle/fluid/operators/fused/cudnn_norm_conv_test.cc
  python/paddle/fluid/tests/unittests/ir/test_fuse_resnet_unit.py
Labels: NVIDIA, contributor

#48175 [PHI decoupling] move vol2col from fluid to phi
  paddle/fluid/operators/conv_op.h
  paddle/fluid/operators/math/CMakeLists.txt
  paddle/fluid/operators/math/vol2col_test.cc
  paddle/phi/kernels/funcs/CMakeLists.txt
  paddle/phi/kernels/funcs/vol2col.cc
  paddle/phi/kernels/funcs/vol2col.cu
  paddle/phi/kernels/funcs/vol2col.h
  paddle/phi/kernels/impl/conv_grad_kernel_impl.h
  paddle/phi/kernels/impl/conv_kernel_impl.h
  paddle/phi/kernels/impl/conv_transpose_grad_kernel_impl.h
  paddle/phi/kernels/impl/conv_transpose_kernel_impl.h
Labels: contributor, status: proposed

#48210 [PHI] Migrate elementwise_div + all elementwise grad kernels
  paddle/fluid/operators/elementwise/mkldnn/elementwise_add_mkldnn_op.cc
  paddle/fluid/operators/elementwise/mkldnn/elementwise_div_mkldnn_op.cc
  paddle/fluid/operators/elementwise/mkldnn/elementwise_mul_mkldnn_op.cc
  paddle/fluid/operators/elementwise/mkldnn/elementwise_sub_mkldnn_op.cc
  paddle/phi/kernels/elementwise_kernel.cc
  paddle/phi/kernels/onednn/elementwise_grad_kernel.cc
  paddle/phi/kernels/onednn/elementwise_kernel.cc
Labels: Intel, contributor

#48134 add warpctc kernel and change cast_v2 to cast for xpu, test=kunlun
  cmake/external/xpu.cmake
  paddle/fluid/framework/data_type_transform.cc
  paddle/fluid/imperative/tests/test_gradient_accmulator.cc
  paddle/fluid/operators/metrics/accuracy_op_xpu.cc
  paddle/fluid/operators/top_k_op_xpu.cc
  paddle/fluid/platform/device/xpu/xpu2_op_list.h
  paddle/phi/kernels/xpu/amp_kernel.cc
  paddle/phi/kernels/xpu/cast_kernel.cc
  paddle/phi/kernels/xpu/cross_entropy_grad_kernel.cc
  paddle/phi/kernels/xpu/cross_entropy_kernel.cc
  paddle/phi/kernels/xpu/gather_grad_kernel.cc
  paddle/phi/kernels/xpu/sgd_kernel.cc
  paddle/phi/kernels/xpu/top_k_kernel.cc
  paddle/phi/kernels/xpu/warpctc_grad_kernel.cc
  paddle/phi/kernels/xpu/warpctc_kernel.cc
  python/paddle/fluid/tests/unittests/xpu/test_warpctc_op_xpu.py
Labels: contributor

#47933 [Clean Fluid API]Remove API: remove dice_loss from paddle.fluid.layers
  python/paddle/fluid/layers/nn.py
  python/paddle/fluid/tests/unittests/test_layers.py
  python/paddle/fluid/tests/unittests/test_nn_dice_loss.py
Labels: contributor, status: not progressed

#47952 [Clean Fluid API]Remove API: label_smooth
  python/paddle/fluid/layers/nn.py
  python/paddle/fluid/tests/unittests/collective/fleet/parallel_dygraph_transformer.py
  python/paddle/fluid/tests/unittests/dist_transformer.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/transformer_dygraph_model.py
  python/paddle/fluid/tests/unittests/test_imperative_transformer_sorted_gradient.py
  python/paddle/fluid/tests/unittests/test_label_smooth_functional.py
  python/paddle/fluid/tests/unittests/test_layers.py
Labels: contributor, status: proposed

#48137 add masked_select_grad kernel
  paddle/fluid/platform/device/xpu/xpu2_op_list.h
  paddle/phi/kernels/xpu/concat_kernel.cc
  paddle/phi/kernels/xpu/conv_kernel.cc
  paddle/phi/kernels/xpu/masked_select_grad_kernel.cc
  paddle/phi/kernels/xpu/sgd_kernel.cc
  python/paddle/fluid/tests/unittests/xpu/test_conv3d_op_xpu.py
  python/paddle/fluid/tests/unittests/xpu/test_masked_select_op_xpu.py
  python/paddle/fluid/tests/unittests/xpu/test_sgd_op_xpu.py
Labels: contributor

#47971 [Clean Fluid API]Remove API: mean_iou (remove directly)
  python/paddle/fluid/layers/nn.py
  python/paddle/fluid/tests/unittests/test_layers.py
  python/paddle/fluid/tests/unittests/test_mean_iou.py
Labels: contributor, status: proposed

#48236 [Fluid Clean] remove paddle.fluid.layers.nn.reduce_max/min
  python/paddle/fluid/layers/distributions.py
  python/paddle/fluid/layers/nn.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/test_sentiment.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/test_tsm.py
  python/paddle/fluid/tests/unittests/ipu/test_reduce_x_op_ipu.py
  python/paddle/fluid/tests/unittests/test_assert_op.py
Labels: contributor, status: proposed

#48174 [PHI decoupling] move im2col from fluid to phi
  paddle/fluid/operators/conv_op.h
  paddle/fluid/operators/im2sequence_op.h
  paddle/fluid/operators/math/CMakeLists.txt
  paddle/fluid/operators/math/context_project.h
  paddle/fluid/operators/math/im2col_test.cc
  paddle/phi/kernels/funcs/CMakeLists.txt
  paddle/phi/kernels/funcs/im2col.cc
  paddle/phi/kernels/funcs/im2col.cu
  paddle/phi/kernels/funcs/im2col.h
  paddle/phi/kernels/funcs/im2col_cfo_cpu.h
  paddle/phi/kernels/impl/conv_grad_kernel_impl.h
  paddle/phi/kernels/impl/conv_kernel_impl.h
  paddle/phi/kernels/impl/conv_transpose_grad_kernel_impl.h
  paddle/phi/kernels/impl/conv_transpose_kernel_impl.h
  paddle/phi/kernels/impl/fold_grad_kernel_impl.h
  paddle/phi/kernels/impl/fold_kernel_impl.h
  paddle/phi/kernels/impl/unfold_grad_kernel_impl.h
  paddle/phi/kernels/impl/unfold_kernel_impl.h
Labels: contributor, status: proposed

#47958 [Clean Fluid API]Remove API: scatter
  python/paddle/fluid/layers/nn.py
  python/paddle/fluid/tests/unittests/test_layers.py
Labels: contributor, status: proposed

#48232 processgroup bkcl support reduce
  paddle/fluid/distributed/collective/ProcessGroupBKCL.cc
  paddle/fluid/distributed/collective/ProcessGroupBKCL.h
  python/paddle/fluid/tests/unittests/xpu/process_group_bkcl.py
Labels: contributor

#48288 [PHI] Migrate batch_norm_grad kernel
  paddle/fluid/operators/batch_norm_op.cc
  paddle/fluid/operators/inplace_abn_op.cc
  paddle/fluid/operators/mkldnn/batch_norm_mkldnn_op.cc
  paddle/fluid/operators/unity_build_rule.cmake
  paddle/phi/backends/onednn/onednn_reuse.h
  paddle/phi/kernels/cpu/batch_norm_grad_kernel.cc
  paddle/phi/kernels/onednn/batch_norm_grad_kernel.cc
Labels: Intel, contributor

#48298 [Dy2St] drop `Executor` and `ParallelExecutor` support for JITLayer
  paddle/fluid/jit/CMakeLists.txt
  paddle/fluid/jit/engine/CMakeLists.txt
  paddle/fluid/jit/engine/executor_engine.cc
  paddle/fluid/jit/engine/executor_engine.h
  paddle/fluid/jit/engine/pe_engine.cc
  paddle/fluid/jit/engine/pe_engine.h
  paddle/fluid/jit/serializer.cc
Labels: contributor, status: proposed

#48049 [PHI decoupling] remove "paddle/fluid/platform/enforce.h" in phi
  paddle/fluid/inference/check_symbol.sh
  paddle/fluid/platform/CMakeLists.txt
  paddle/fluid/platform/enforce.h
  paddle/phi/backends/callback_manager.cc
  paddle/phi/backends/dynload/cudnn.cc
  paddle/phi/backends/dynload/cufft.cc
  paddle/phi/backends/dynload/dynamic_loader.cc
  paddle/phi/backends/dynload/miopen.cc
  paddle/phi/backends/dynload/tensorrt.h
  paddle/phi/backends/gpu/cuda/cuda_info.cc
  paddle/phi/backends/gpu/gpu_context.cc
  paddle/phi/backends/gpu/gpu_resources.cc
  paddle/phi/backends/gpu/rocm/rocm_info.cc
  paddle/phi/backends/xpu/enforce_xpu.h
  paddle/phi/backends/xpu/xpu_header.h
  paddle/phi/core/CMakeLists.txt
  paddle/phi/core/cuda_stream.h
  paddle/phi/core/enforce.h
  paddle/phi/core/external_error.proto
  paddle/phi/kernels/autotune/CMakeLists.txt
  paddle/phi/kernels/funcs/concat_funcs.h
  paddle/phi/kernels/funcs/cpu_vec.h
  paddle/phi/kernels/funcs/cufft_util.h
  paddle/phi/kernels/funcs/gru_compute.h
  paddle/phi/kernels/funcs/hipfft_util.h
  paddle/phi/kernels/funcs/lstm_compute.h
  paddle/phi/kernels/funcs/math_function.h
  paddle/phi/kernels/gpu/batch_norm_grad_kernel.cu
  paddle/phi/kernels/gpu/batch_norm_kernel.cu
  paddle/phi/kernels/gpu/cholesky_solve_kernel.cu
  paddle/phi/kernels/gpu/class_center_sample_kernel.cu
  tools/externalError/start.sh
Labels: contributor, status: proposed

#48168 [PHI decoupling] simplify "convert_utils.h" in fluid
  paddle/fluid/distributed/ps/service/brpc_utils.cc
  paddle/fluid/distributed/ps/service/heter_client.cc
  paddle/fluid/eager/amp_auto_cast.h
  paddle/fluid/eager/eager_amp_auto_cast.h
  paddle/fluid/eager/grad_node_info.cc
  paddle/fluid/framework/CMakeLists.txt
  paddle/fluid/framework/convert_utils.cc
  paddle/fluid/framework/convert_utils.h
  paddle/fluid/framework/heter_section_worker.cc
  paddle/fluid/framework/tensor_util.cc
  paddle/fluid/inference/lite/tensor_utils.cc
  paddle/fluid/operators/amp/update_loss_scaling_op_npu.cc
  paddle/fluid/operators/collective/c_embedding_op.h
  paddle/fluid/operators/collective/c_embedding_op_npu.cc
  paddle/fluid/operators/detection/bbox_util.h
  paddle/fluid/operators/ipu/ipu_runtime_op.cc
  paddle/fluid/operators/pscore/send_and_recv_op_gpu_test.cc
  paddle/fluid/operators/reader/buffered_reader.cc
  paddle/fluid/platform/device/gpu/cuda/cudnn_desc.h
  paddle/fluid/platform/device/gpu/rocm/miopen_desc.h
  paddle/fluid/pybind/eager_functions.cc
  paddle/fluid/pybind/eager_method.cc
  paddle/fluid/pybind/imperative.cc
  paddle/phi/common/data_type.h
  paddle/phi/core/compat/CMakeLists.txt
  paddle/phi/core/utils/data_type.h
  paddle/phi/infermeta/unary.cc
  paddle/phi/kernels/cpu/arg_min_max_kernel.cc
  paddle/phi/kernels/cpu/index_sample_grad_kernel.cc
  paddle/phi/kernels/cpu/index_sample_kernel.cc
  paddle/phi/kernels/cpu/unique_consecutive_kernel.cc
  paddle/phi/kernels/funcs/unique_functor.h
  paddle/phi/kernels/gpu/arg_min_max_kernel.cu
  paddle/phi/kernels/gpu/index_sample_grad_kernel.cu
  paddle/phi/kernels/gpu/index_sample_kernel.cu
  paddle/phi/kernels/gpu/unique_consecutive_kernel.cu
  paddle/phi/kernels/gpudnn/conv_cudnn_frontend.h
Labels: contributor

#48345 fix xpu compile on phi::enforce.
  paddle/fluid/platform/device/xpu/tests/enforce_xpu_test.cc
Labels: contributor, status: proposed

#48354 [Dy2St] clean `FLAGS_jit_engine_type` related comments
  paddle/fluid/platform/flags.cc
Labels: contributor, status: proposed

#47962 [Clean Fluid API]Remove API: random_crop
  python/paddle/fluid/layers/nn.py
  python/paddle/fluid/tests/unittests/test_random_crop_op.py
Labels: contributor, status: proposed

#48379 fix loopup_table plugin deserialize size error
  paddle/fluid/inference/tensorrt/plugin/lookup_table.cu
Labels: contributor, status: proposed

#48230 add reciprocal trt converter
  paddle/fluid/inference/tensorrt/convert/unary_op.cc
  paddle/fluid/inference/tensorrt/op_teller.cc
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_unary.py
Labels: contributor, status: proposed

#48416 Remove LoDTensor and Tensor in fluid except operators folder
  paddle/fluid/distributed/ps/service/communicator/communicator.cc
  paddle/fluid/distributed/ps/wrapper/fleet.cc
  paddle/fluid/distributed/ps/wrapper/fleet.h
  paddle/fluid/distributed/ps/wrapper/ps_wrapper.h
  paddle/fluid/inference/api/mkldnn_quantizer.cc
  paddle/fluid/inference/tensorrt/convert/io_converter.h
  paddle/fluid/platform/device/ipu/ipu_utils.h
  paddle/fluid/platform/device/npu/npu_op_runner.h
Labels: contributor, status: proposed

#48420 [Phi decouple] remove dependece to "paddle/fluid/platform/device/xpu/xxx.h" in phi
  paddle/fluid/platform/device/xpu/CMakeLists.txt
  paddle/fluid/platform/device/xpu/xpu_op_list.cc
  paddle/fluid/platform/device/xpu/xpu_op_list.h
  paddle/phi/backends/CMakeLists.txt
  paddle/phi/backends/xpu/CMakeLists.txt
  paddle/phi/backends/xpu/xpu_op_list.cc
  paddle/phi/backends/xpu/xpu_op_list.h
  paddle/phi/core/CMakeLists.txt
  paddle/phi/core/kernel_factory.cc
  paddle/phi/kernels/xpu/cast_kernel.cc
  paddle/phi/kernels/xpu/nonzero_kernel.cc
Labels: contributor, status: proposed

#48404 [CodeStyle][isort] introduce isort (part5)
  python/paddle/common_ops_import.py
  python/paddle/tensor/array.py
  python/paddle/tensor/attribute.py
  python/paddle/tensor/creation.py
  python/paddle/tensor/einsum.py
  python/paddle/tensor/layer_function_generator.py
  python/paddle/tensor/linalg.py
  python/paddle/tensor/logic.py
  python/paddle/tensor/manipulation.py
  python/paddle/tensor/math.py
  python/paddle/tensor/ops.py
  python/paddle/tensor/random.py
  python/paddle/tensor/search.py
  python/paddle/tensor/stat.py
  python/paddle/tensor/to_string.py
Labels: contributor

#48403 [PHI decoupling] add "cpu_info.h" to phi
  paddle/fluid/platform/cpu_info.h
  paddle/phi/backends/cpu/cpu_info.h
  paddle/phi/kernels/funcs/cpu_vec.h
  paddle/phi/kernels/funcs/detail/activation_functions.h
  paddle/phi/kernels/funcs/detail/avx_mathfun.h
  paddle/phi/kernels/sparse/cpu/softmax_grad_kernel.cc
  paddle/phi/kernels/sparse/cpu/softmax_kernel.cc
  paddle/phi/tests/kernels/test_cpu_vec.cc
Labels: contributor, status: proposed

#48251 [PHI decoupling]migrate top_k_function_cuda.h from fluid to phi
  paddle/fluid/operators/top_k_op.cu
  paddle/phi/kernels/funcs/top_k_function_cuda.h
  paddle/phi/kernels/gpu/kthvalue_grad_kernel.cu
  paddle/phi/kernels/gpu/kthvalue_kernel.cu
  paddle/phi/kernels/gpu/top_k_grad_kernel.cu
  paddle/phi/kernels/gpu/top_k_kernel.cu
Labels: contributor, status: proposed

#48263 Cherrypick NV fixes to release/2.4
  paddle/fluid/framework/distributed_strategy.proto
  paddle/fluid/operators/fused/cudnn_norm_conv.cu.h
  paddle/fluid/operators/fused/cudnn_norm_conv_test.cc
  paddle/fluid/operators/fused/fused_dropout_act_bias.h
  python/paddle/fluid/core.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_activation.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_anchor_generator.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_arg_max.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_bmm.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_clip.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_concat.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_conv2d_transpose.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_dropout.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_elementwise.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_equal.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_fc.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_fill_constant.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_flatten.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_gather.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_gather_nd.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_gelu.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_grid_sampler.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_group_norm.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_hard_sigmoid.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_hard_swish.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_inverse.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_leaky_relu.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_matmul.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_matmul_v2.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_multihead_matmul.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_pad3d.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_pool2d.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_reduce_sum.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_reshape.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_roi_align.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_roll.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_scatter_nd_add.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_shape.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_shuffle_channel.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_slice.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_split.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_squeeze2.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_stack.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_sum.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_tile.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_top_k.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_top_k_v2.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_transpose.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_unary.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_unfold.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_unsqueeze2.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_squeeze2_matmul_fuse_pass.py
  python/paddle/fluid/tests/unittests/ir/test_fuse_resnet_unit.py
Labels: NVIDIA, contributor

#48415 [PHI decoupling] move several header files from fluid to phi
  paddle/fluid/operators/cuda_graph_with_in_out.h
  paddle/fluid/operators/fused/cudnn_bn_stats_finalize.cu.h
  paddle/fluid/operators/fused/cudnn_norm_conv.cu.h
  paddle/fluid/operators/fused/cudnn_scale_bias_add_relu.cu.h
  paddle/fluid/platform/device/gpu/cuda/cudnn_helper_test.cc
  paddle/fluid/platform/device/gpu/cudnn_desc_test.cc
  paddle/fluid/platform/device/gpu/gpu_dnn.h
  paddle/fluid/platform/device/gpu/rocm/miopen_helper_test.cc
  paddle/phi/backends/gpu/cuda/cudnn_desc.h
  paddle/phi/backends/gpu/cuda/cudnn_helper.h
  paddle/phi/backends/gpu/gpu_dnn.h
  paddle/phi/backends/gpu/rocm/miopen_desc.h
  paddle/phi/backends/gpu/rocm/miopen_helper.h
  paddle/phi/kernels/funcs/cross_entropy.cu
  paddle/phi/kernels/gpu/batch_norm_grad_kernel.cu
  paddle/phi/kernels/gpu/batch_norm_kernel.cu
  paddle/phi/kernels/gpu/cross_entropy_grad_kernel.cu
  paddle/phi/kernels/gpu/cross_entropy_kernel.cu
  paddle/phi/kernels/gpu/instance_norm_utils.h
  paddle/phi/kernels/gpu/rnn_functor.h
  paddle/phi/kernels/gpu/sync_batch_norm_utils.h
  paddle/phi/kernels/gpudnn/affine_grid_grad_kernel.cu
  paddle/phi/kernels/gpudnn/affine_grid_kernel.cu
  paddle/phi/kernels/gpudnn/conv_cudnn_frontend.h
  paddle/phi/kernels/gpudnn/conv_cudnn_v7.h
  paddle/phi/kernels/gpudnn/conv_gpudnn_base.h
  paddle/phi/kernels/gpudnn/conv_gpudnn_info.h
  paddle/phi/kernels/gpudnn/conv_grad_kernel.cu
  paddle/phi/kernels/gpudnn/conv_kernel.cu
  paddle/phi/kernels/gpudnn/conv_transpose_grad_kernel.cu
  paddle/phi/kernels/gpudnn/conv_transpose_kernel.cu
  paddle/phi/kernels/gpudnn/pool_gpudnn.h
  paddle/phi/kernels/gpudnn/pool_grad_kernel.cu
  paddle/phi/kernels/gpudnn/pool_kernel.cu
  paddle/phi/kernels/gpudnn/softmax_gpudnn.h
Labels: contributor

#47983 [Clean Fluid API]Remove API: crop_tensor
  python/paddle/fluid/layers/nn.py
  python/paddle/fluid/tests/unittests/test_device_guard.py
  python/paddle/fluid/tests/unittests/test_layers.py
  python/paddle/fluid/tests/unittests/xpu/test_device_guard_xpu.py
Labels: contributor, status: proposed

#47938 [Clean Fluid API]Remove squeeze: use paddle.squeeze to replace paddle.fluid.layers.squeeze
  python/paddle/fluid/layers/nn.py
  python/paddle/fluid/layers/rnn.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/seq2seq_dygraph_model.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/test_bmn.py
  python/paddle/fluid/tests/unittests/ipu/test_squeeze_op_ipu.py
  python/paddle/fluid/tests/unittests/test_layers.py
  python/paddle/fluid/tests/unittests/test_recurrent_op.py
  python/paddle/fluid/tests/unittests/test_rnn_decode_api.py
  python/paddle/fluid/tests/unittests/test_squeeze2_op.py
Labels: contributor, status: proposed
