Repository PaddlePaddle/Paddle, pull requests merged in 2022-09, with the labels that each got.

#45557 add support of cast kernel from fp32 to uint8 *test=kunlun
  paddle/phi/kernels/xpu/cast_kernel.cc
  python/paddle/fluid/tests/unittests/xpu/test_cast_op_xpu.py
Labels: contributor, status: proposed

#45617 [XPU] add c_embedding_op_xpu.
  cmake/external/xpu.cmake
  paddle/fluid/operators/collective/c_embedding_op_xpu.cc
  paddle/fluid/platform/device/xpu/xpu2_op_list.h
  python/paddle/fluid/tests/unittests/c_embedding_op_base.py
  python/paddle/fluid/tests/unittests/xpu/test_c_embedding_op_xpu.py
Labels: contributor, status: proposed

#44946 【PaddlePaddle Hackathon 3 No.31】为 Paddle 优化 dist op 在 GPU 上的计算性能
  paddle/phi/kernels/dist_kernel.cc
  paddle/phi/kernels/gpu/dist_kernel.cu
Labels: PaddlePaddle Hackathon, contributor

#45630 add coverage dir for xpu
  tools/coverage/paddle_coverage.sh
Labels: contributor, status: proposed

#37896 fix error in the doc: batchnorm weight is initialized with one s by default, not Xavier
  python/paddle/nn/layer/norm.py
Labels: 文档, contributor

#44680 add int8 scale calculation and conv weights quantization pass to paddle_pass_builder
  paddle/fluid/inference/api/paddle_pass_builder.cc
Labels: Intel, int8, contributor

#45481 [PHI] Migrate gaussian_random kernel
  paddle/fluid/operators/mkldnn/gaussian_random_mkldnn_op.cc
  paddle/phi/backends/onednn/onednn_helper.h
  paddle/phi/backends/onednn/onednn_reuse.h
  paddle/phi/core/compat/convert_utils.cc
  paddle/phi/core/compat/convert_utils.h
  paddle/phi/core/dense_tensor_impl.cc
  paddle/phi/kernels/funcs/data_layout_transform.cc
  paddle/phi/kernels/funcs/data_layout_transform.h
  paddle/phi/kernels/onednn/activation_grad_kernel.cc
  paddle/phi/kernels/onednn/activation_kernel.cc
  paddle/phi/kernels/onednn/gaussian_random_kernel.cc
  paddle/phi/kernels/transfer_layout_kernel.cc
Labels: Intel, contributor

#45625 move one_hot_v2, p_norm, p_norm_grad to phi
  paddle/fluid/operators/one_hot_v2_op_xpu.cc
  paddle/fluid/operators/p_norm_op_xpu.cc
  paddle/phi/kernels/one_hot_kernel.cc
  paddle/phi/kernels/xpu/one_hot_kernel.cc
  paddle/phi/kernels/xpu/p_norm_grad_kernel.cc
  paddle/phi/kernels/xpu/p_norm_kernel.cc
Labels: contributor, status: proposed

#45692 Fix jetson compile error
  paddle/fluid/platform/device/gpu/gpu_launch_config.h
Labels: contributor, status: proposed

#45027 Update DlNNE engine
  paddle/fluid/inference/analysis/argument.h
  paddle/fluid/inference/analysis/ir_pass_manager.cc
  paddle/fluid/inference/analysis/ir_passes/dlnne_reg_py.h
  paddle/fluid/inference/analysis/ir_passes/dlnne_subgraph_pass.cc
  paddle/fluid/inference/analysis/ir_passes/dlnne_subgraph_pass.h
  paddle/fluid/inference/api/analysis_config.cc
  paddle/fluid/inference/api/analysis_predictor.cc
  paddle/fluid/inference/api/paddle_analysis_config.h
  paddle/fluid/inference/capi/pd_config.cc
  paddle/fluid/operators/dlnne/CMakeLists.txt
  paddle/fluid/operators/dlnne/dlnne_engine_op.cc
  paddle/fluid/operators/dlnne/dlnne_engine_op.h
  paddle/fluid/pybind/inference_api.cc
Labels: contributor, status: proposed

#45416 New format quant model support for MKLDNN
  paddle/fluid/framework/ir/mkldnn/quant_dequant_mkldnn_pass.cc
  paddle/fluid/framework/ir/mkldnn/quant_dequant_mkldnn_pass.h
  paddle/fluid/inference/analysis/argument.h
  paddle/fluid/inference/analysis/passes/ir_analysis_pass.cc
  paddle/fluid/inference/analysis/passes/ir_analysis_pass.h
  paddle/fluid/inference/api/analysis_config.cc
  paddle/fluid/inference/api/analysis_predictor.cc
  paddle/fluid/inference/api/paddle_analysis_config.h
  paddle/fluid/pybind/inference_api.cc
  python/paddle/fluid/contrib/slim/tests/CMakeLists.txt
  python/paddle/fluid/tests/unittests/mkldnn/CMakeLists.txt
  python/paddle/fluid/tests/unittests/mkldnn/test_onnx_format_quantization_mobilenetv1.py
Labels: Intel, int8

#45626 [PHI] Move oneDNN helper classes to new location
  paddle/fluid/framework/new_executor/data_transfer.cc
  paddle/fluid/framework/phi_utils_test.cc
  paddle/fluid/platform/mkldnn_reuse.h
  paddle/phi/api/lib/kernel_dispatch.cc
  paddle/phi/backends/onednn/onednn_helper.h
  paddle/phi/backends/onednn/onednn_reuse.h
  paddle/phi/common/backend.h
  paddle/phi/common/layout.h
  paddle/phi/kernels/onednn/log_softmax_kernel.cc
  paddle/phi/kernels/transfer_layout_kernel.cc
  paddle/phi/tests/common/test_data_layout.cc
  paddle/phi/tests/kernels/test_transfer_layout_dev_api.cc
Labels: Intel, contributor

#45734 [XPU] rmsprop to phi.
  paddle/fluid/operators/optimizers/rmsprop_op_xpu.cc
  paddle/phi/kernels/xpu/rmsprop_kernel.cc
Labels: contributor, status: proposed

#45773 add a wrap_decorator decorator to keep the __doc__ attr
  python/paddle/fluid/dygraph/jit.py
Labels: contributor, status: proposed

#45496 【PaddlePaddle Hackathon 3 No.48】为 Paddle 新增 elementwise op support fp16
  paddle/phi/kernels/elementwise_kernel.cc
  paddle/phi/kernels/funcs/elementwise_functor.h
  paddle/phi/kernels/gpu/elementwise_grad_kernel.cu
  paddle/phi/kernels/impl/elementwise_grad_kernel_impl.h
  paddle/phi/kernels/kps/elementwise_kernel.cu
  python/paddle/fluid/tests/unittests/test_elementwise_heaviside_op.py
  python/paddle/fluid/tests/unittests/test_elementwise_mod_op.py
  python/paddle/fluid/tests/unittests/test_elementwise_pow_op.py
  python/paddle/fluid/tests/unittests/test_fmax_op.py
  python/paddle/fluid/tests/unittests/test_fmin_op.py
  python/paddle/tensor/math.py
Labels: PaddlePaddle Hackathon, contributor

#45720 [just for my self-learning] take some notes about sparse API
  paddle/fluid/pybind/eager_functions.cc
  paddle/fluid/pybind/eager_utils.cc
  paddle/phi/api/include/tensor.h
  paddle/phi/core/dense_tensor.h
  paddle/phi/core/tensor_base.h
Labels: contributor, status: proposed

#45719 [Paddle Inference] fix bugs in quant_conv2d_dequant_fuse_pass when weight is shared between ops
  paddle/fluid/framework/ir/quant_conv2d_dequant_fuse_pass.cc
Labels: contributor, status: proposed

#45091 Added concat workaround for vivo model
  paddle/fluid/operators/mkldnn/concat_mkldnn_op.cc
Labels: Intel, contributor, status: not progressed

#45537 [PHI] Migrate scale kernel
  paddle/fluid/operators/mkldnn/scale_mkldnn_op.cc
  paddle/phi/kernels/onednn/scale_kernel.cc
Labels: Intel, contributor

#45707 [MLU] fix sync_bn of mlu and add unittests
  paddle/fluid/operators/sync_batch_norm_op_mlu.cc
  python/paddle/fluid/framework.py
  python/paddle/fluid/tests/unittests/mlu/parallel_dygraph_sync_batch_norm.py
  python/paddle/fluid/tests/unittests/mlu/test_parallel_dygraph_sync_batch_norm_mlu.py
  python/paddle/fluid/tests/unittests/mlu/test_sync_batch_norm_base_mlu.py
  python/paddle/fluid/tests/unittests/mlu/test_sync_batch_norm_op_mlu.sh
  python/paddle/fluid/tests/unittests/test_dist_base.py
Labels: contributor

#45822 [XPU] move rnn op to phi.
  paddle/fluid/operators/rnn_op_xpu.cc
  paddle/fluid/platform/device/npu/CMakeLists.txt
  paddle/phi/kernels/funcs/math_function.cc
  paddle/phi/kernels/xpu/rnn_grad_kernel.cc
  paddle/phi/kernels/xpu/rnn_kernel.cc
  paddle/phi/kernels/xpu/rnn_util.h
Labels: contributor, status: proposed

#45536 [PHI] Migrate reduce sum+grad, mean+grad, min and max oneDNN kernels
  paddle/fluid/operators/reduce_ops/mkldnn/reduce_max_mkldnn_op.cc
  paddle/fluid/operators/reduce_ops/mkldnn/reduce_mean_mkldnn_op.cc
  paddle/fluid/operators/reduce_ops/mkldnn/reduce_min_mkldnn_op.cc
  paddle/fluid/operators/reduce_ops/mkldnn/reduce_mkldnn_op.h
  paddle/fluid/operators/reduce_ops/mkldnn/reduce_sum_mkldnn_op.cc
  paddle/phi/kernels/onednn/reduce_kernel_impl.h
  paddle/phi/kernels/onednn/reduce_max_kernel.cc
  paddle/phi/kernels/onednn/reduce_mean_grad_kernel.cc
  paddle/phi/kernels/onednn/reduce_mean_kernel.cc
  paddle/phi/kernels/onednn/reduce_min_kernel.cc
  paddle/phi/kernels/onednn/reduce_sum_grad_kernel.cc
  paddle/phi/kernels/onednn/reduce_sum_kernel.cc
  paddle/phi/kernels/reduce_max_kernel.cc
  paddle/phi/kernels/reduce_mean_kernel.cc
  paddle/phi/kernels/reduce_min_kernel.cc
  paddle/phi/kernels/reduce_sum_kernel.cc
Labels: Intel, contributor, status: proposed

#45777 [XPU] update xdnn to 0907.
  cmake/external/xpu.cmake
  paddle/phi/kernels/xpu/rnn_grad_kernel.cc
  paddle/phi/kernels/xpu/rnn_kernel.cc
  paddle/phi/kernels/xpu/rnn_util.h
  python/paddle/fluid/tests/unittests/xpu/get_test_cover_info.py
Labels: contributor, status: proposed

#45843 update security policy test=document_fix
  SECURITY.md
  SECURITY_cn.md
Labels: contributor, status: proposed

#45819 Increase the threshold of softmax and imperative qat UT
  python/paddle/fluid/contrib/slim/tests/test_imperative_qat.py
  python/paddle/fluid/contrib/slim/tests/test_imperative_qat_channelwise.py
  python/paddle/fluid/contrib/slim/tests/test_imperative_qat_fuse.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_softmax.py
Labels: NVIDIA, contributor

#45321 [ Hackathon 3rd No.2 ] add paddle.iinfo
  paddle/fluid/eager/grad_node_info.h
  paddle/fluid/pybind/pybind.cc
  python/paddle/__init__.py
  python/paddle/fluid/tests/unittests/test_iinfo_and_finfo.py
  python/paddle/framework/dtype.py
Labels: contributor, status: not progressed

#45775 [PHI] Migrate cast, clip+grad and pool+grad oneDNN kernels
  paddle/fluid/operators/mkldnn/cast_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/clip_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/pool_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/test_mkldnn_op_nhwc.cc
  paddle/phi/backends/onednn/onednn_reuse.h
  paddle/phi/kernels/onednn/cast_kernel.cc
  paddle/phi/kernels/onednn/clip_grad_kernel.cc
  paddle/phi/kernels/onednn/clip_kernel.cc
  paddle/phi/kernels/onednn/pool_grad_kernel.cc
  paddle/phi/kernels/onednn/pool_kernel.cc
Labels: Intel, contributor

#45886 [MLU] fix mluinfo compile error.
  paddle/fluid/platform/device/mlu/CMakeLists.txt
Labels: contributor, status: proposed

#45820 optimization of max_pool3d forward
  paddle/phi/kernels/funcs/pooling.cu
Labels: contributor, status: proposed

#45086 【PaddlePaddle Hackathon 3 No.23】为 Paddle 新增 paddle.incubate.sparse.is_same_shape 稀疏 API
  paddle/fluid/pybind/eager_method.cc
  python/paddle/fluid/tests/unittests/test_sparse_is_same_shape.py
  python/paddle/incubate/sparse/__init__.py
  python/paddle/incubate/sparse/binary.py
Labels: PaddlePaddle Hackathon, contributor

#44853 【PaddlePaddle Hackathon 3 No.20】为 Paddle 新增 vsplit API
  python/paddle/__init__.py
  python/paddle/fluid/tests/unittests/test_splits_api.py
  python/paddle/tensor/__init__.py
  python/paddle/tensor/manipulation.py
Labels: PaddlePaddle Hackathon, contributor

#45925 Fix namespace error
  paddle/phi/kernels/gpu/group_norm_grad_kernel.cu
Labels: contributor

#45923 [MLU] fix compute error of dropout op
  paddle/fluid/operators/dropout_op_mlu.cc
  paddle/fluid/operators/pool_op_mlu.cc
  python/paddle/fluid/tests/unittests/mlu/test_dropout_op_mlu.py
Labels: contributor, status: proposed

#45965 [MLU] add mergedAdam kernel.
  paddle/fluid/operators/optimizers/adam_op_mlu.cc
  python/paddle/fluid/tests/unittests/mlu/test_merged_adam_op_mlu.py
Labels: contributor

#45996 fix compile
  paddle/fluid/inference/tensorrt/plugin/layernorm_shift_partition_op.cu
Labels: contributor

#44043 update comments about fleet.init()
  python/paddle/distributed/fleet/fleet.py
Labels: contributor

#46029 [chery-pick]Fix namespace error (#45925)
  paddle/phi/kernels/gpu/group_norm_grad_kernel.cu
Labels: contributor, status: proposed

#45824 delay tensorrt registry
  paddle/fluid/inference/analysis/ir_passes/tensorrt_subgraph_pass.cc
  paddle/fluid/inference/tensorrt/plugin/trt_plugin.h
  paddle/fluid/inference/tensorrt/test_dynamic_engine.cc
  paddle/fluid/platform/dynload/tensorrt.cc
  paddle/phi/backends/dynload/tensorrt.cc
Labels: contributor

#45958 cherry pick delay tensorrt log
  paddle/fluid/inference/analysis/ir_passes/tensorrt_subgraph_pass.cc
  paddle/fluid/inference/tensorrt/plugin/trt_plugin.h
  paddle/fluid/inference/tensorrt/test_dynamic_engine.cc
  paddle/fluid/platform/dynload/tensorrt.cc
  paddle/phi/backends/dynload/tensorrt.cc
Labels: contributor

#46008 Support inference compilation in training package
  CMakeLists.txt
  cmake/third_party.cmake
  paddle/fluid/framework/new_executor/new_executor_defs.cc
  paddle/fluid/framework/new_executor/new_executor_defs.h
  paddle/fluid/framework/scope.cc
  paddle/fluid/framework/scope.h
  paddle/fluid/platform/flags.cc
  paddle/fluid/pybind/CMakeLists.txt
  paddle/fluid/pybind/pybind.cc
  python/paddle/fluid/tests/unittests/CMakeLists.txt
  python/paddle/fluid/tests/unittests/dygraph_to_static/CMakeLists.txt
Labels: contributor, status: proposed

#46013 Support inference compilation in training package
  CMakeLists.txt
  cmake/third_party.cmake
  paddle/fluid/framework/new_executor/new_executor_defs.cc
  paddle/fluid/framework/new_executor/new_executor_defs.h
  paddle/fluid/framework/scope.cc
  paddle/fluid/framework/scope.h
  paddle/fluid/platform/flags.cc
  paddle/fluid/pybind/CMakeLists.txt
  paddle/fluid/pybind/pybind.cc
  python/paddle/fluid/tests/unittests/CMakeLists.txt
  python/paddle/fluid/tests/unittests/dygraph_to_static/CMakeLists.txt
Labels: contributor

#45355 General plugin mechanism
  paddle/fluid/inference/api/analysis_predictor.cc
  paddle/fluid/inference/tensorrt/CMakeLists.txt
  paddle/fluid/inference/tensorrt/convert/CMakeLists.txt
  paddle/fluid/inference/tensorrt/convert/generic_and_custom_plugin_creater.cc
  paddle/fluid/inference/tensorrt/convert/op_converter.h
  paddle/fluid/inference/tensorrt/convert/test_custom_op_plugin.h
  paddle/fluid/inference/tensorrt/convert/test_custom_plugin_creater.cc
  paddle/fluid/inference/tensorrt/convert/test_op_converter.cc
  paddle/fluid/inference/tensorrt/dynamic_shape_infermeta.cc
  paddle/fluid/inference/tensorrt/dynamic_shape_infermeta_factory.h
  paddle/fluid/inference/tensorrt/dynamic_shape_infermeta_registry.h
  paddle/fluid/inference/tensorrt/op_teller.cc
  paddle/fluid/inference/tensorrt/op_teller.h
  paddle/fluid/inference/tensorrt/plugin/CMakeLists.txt
  paddle/fluid/inference/tensorrt/plugin/generic_plugin.cu
  paddle/fluid/inference/tensorrt/plugin/generic_plugin.h
  paddle/fluid/inference/tensorrt/plugin/mish_op_plugin.h
  paddle/fluid/inference/tensorrt/plugin_arg_mapping_context.cc
  paddle/fluid/inference/tensorrt/plugin_arg_mapping_context.h
  paddle/fluid/inference/tensorrt/test_arg_mapping_context.cc
  paddle/fluid/operators/tensorrt/tensorrt_engine_op_test.cc
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_gather_nd.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_yolo_box.py
Labels: contributor

#46067 [CodeStyle] trailing whitespace hook for doc and cpp related files
  .pre-commit-config.yaml
Labels: contributor

#45624 updating mul and matmul with set_mem_desc
  paddle/fluid/operators/mkldnn/matmul_v2_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/mul_mkldnn_op.cc
  paddle/fluid/platform/mkldnn_reuse.h
  paddle/phi/kernels/transfer_layout_kernel.cc
Labels: Intel, contributor

#45901 [jit] skip forward save
  python/paddle/fluid/dygraph/jit.py
  python/paddle/fluid/tests/unittests/test_jit_save_load.py
Labels: contributor

#45936 Correct order of passes in QAT
  python/paddle/fluid/contrib/slim/quantization/quant2_int8_mkldnn_pass.py
Labels: Intel, int8, contributor

#46035 fix bug for TransformedDistribution
  python/paddle/distribution/transformed_distribution.py
Labels: PaddlePaddle Hackathon, contributor, status: proposed

#46045 Fix bug of reduce_sum op.
  paddle/phi/kernels/kps/reduce_sum_kernel.cu
Labels: contributor

#46157 [Cherry-pick] fix bug for TransformedDistribution
  python/paddle/distribution/transformed_distribution.py
Labels: contributor, status: proposed

#46081 [CodeStyle] trailing whitespace hook for .hook and .yaml
  .pre-commit-config.yaml
Labels: contributor, status: proposed

#46136 [CodeStyle] fix cpplint hook not working on CI
  .pre-commit-config.yaml
  tools/codestyle/cpplint_pre_commit.hook
Labels: contributor, status: proposed

#46178 [Inference] fix preln_residual_bias_fuse_pass bug in TNT_small model
  paddle/fluid/framework/ir/preln_residual_bias_fuse_pass.cc
Labels: contributor, status: proposed

#46246 [XPU] update xdnn activations.
  cmake/external/xpu.cmake
  paddle/phi/kernels/xpu/activation_kernel.cc
Labels: contributor

#46260 [Inference][Cherry-pick] fix preln_residual_bias_fuse_pass bug in TNT_small model …
  paddle/fluid/framework/ir/preln_residual_bias_fuse_pass.cc
Labels: contributor, status: proposed

#46155 [CodeStyle] remove crlf in python files
  python/paddle/fluid/tests/unittests/asp/test_asp_utils.py
  python/paddle/fluid/tests/unittests/mkldnn/test_elementwise_sub_mkldnn_op.py
  python/paddle/fluid/tests/unittests/mkldnn/test_fill_constant_mkldnn_op.py
  python/paddle/fluid/tests/unittests/sequence/test_sequence_first_step.py
  python/paddle/fluid/tests/unittests/sequence/test_sequence_last_step.py
  python/paddle/fluid/tests/unittests/test_lstm_cudnn_op.py
  python/paddle/fluid/tests/unittests/test_rnn_op.py
  python/paddle/fluid/transpiler/memory_optimization_transpiler.py
Labels: contributor, status: proposed

#46156 [CodeStyle] remove crlf in cpp files
  paddle/fluid/inference/analysis/analysis_pass.h
  paddle/fluid/operators/collective/c_allgather_op_npu_test.cc
  paddle/fluid/operators/collective/c_allreduce_max_op_npu_test.cc
  paddle/fluid/operators/collective/c_allreduce_sum_op_npu_test.cc
  paddle/fluid/operators/collective/c_broadcast_op_npu_test.cc
  paddle/fluid/operators/collective/c_reduce_sum_op_npu_test.cc
  paddle/fluid/operators/collective/c_reducescatter_op_npu_test.cc
  paddle/fluid/operators/mkldnn/fill_constant_mkldnn_op.cc
  paddle/fluid/operators/unbind_op.cc
  paddle/fluid/operators/unbind_op.h
Labels: contributor, status: proposed

#46154 [CodeStyle] fix remove-crlf hook config
  .pre-commit-config.yaml
Labels: contributor, status: proposed

#46259 Fix python link order error on cc_test test_egr_performance_benchmark_eager_cpu
  cmake/generic.cmake
Labels: contributor, status: proposed

#45545 [Paddle-TRT] Full support for ops with persistable input
  paddle/fluid/inference/tensorrt/convert/generic_and_custom_plugin_creater.cc
  paddle/fluid/inference/tensorrt/convert/op_converter.h
  paddle/fluid/inference/tensorrt/engine.cc
  paddle/fluid/inference/tensorrt/engine.h
Labels: contributor, status: not progressed

#44918 [Paddle-TRT] matmul_v2 support
  paddle/fluid/inference/api/analysis_predictor.cc
  paddle/fluid/inference/tensorrt/convert/CMakeLists.txt
  paddle/fluid/inference/tensorrt/convert/matmul_v2_op.cc
  paddle/fluid/inference/tensorrt/op_teller.cc
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_matmul_v2.py
Labels: contributor, status: proposed

#46177 [Paddle-TRT] Support matmul_v2 in Paddle-TensorRT
  paddle/fluid/inference/api/analysis_predictor.cc
  paddle/fluid/inference/tensorrt/convert/CMakeLists.txt
  paddle/fluid/inference/tensorrt/convert/matmul_v2_op.cc
  paddle/fluid/inference/tensorrt/op_teller.cc
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_matmul_v2.py
Labels: contributor, status: proposed

#46254 Reverted changes for concat workaround
  paddle/fluid/operators/mkldnn/concat_mkldnn_op.cc
Labels: Intel, contributor

#46101 [PHI] Migrate slice, slice_grad, split, pad and pad3d oneDNN kernels
  paddle/fluid/operators/mkldnn/pad3d_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/slice_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/split_mkldnn_op.cc
  paddle/phi/backends/onednn/onednn_helper.h
  paddle/phi/backends/onednn/onednn_reuse.h
  paddle/phi/kernels/onednn/pad3d_kernel.cc
  paddle/phi/kernels/onednn/pad_kernel.cc
  paddle/phi/kernels/onednn/pad_kernel_impl.h
  paddle/phi/kernels/onednn/slice_grad_kernel.cc
  paddle/phi/kernels/onednn/slice_kernel.cc
  paddle/phi/kernels/onednn/split_kernel.cc
Labels: Intel, contributor

#46257 [PHI] migrate softmax_grad kernel
  paddle/fluid/operators/mkldnn/softmax_mkldnn_op.cc
  paddle/phi/backends/onednn/onednn_reuse.h
  paddle/phi/kernels/onednn/softmax_grad_kernel.cc
Labels: Intel, contributor

#46271 [XPU] update xpu cmake.
  cmake/external/xpu.cmake
Labels: contributor, status: proposed

#46280 [Paddle-TRT][Cherry-pick] Full support for ops with persistable input (#45545)
  paddle/fluid/inference/tensorrt/convert/generic_and_custom_plugin_creater.cc
  paddle/fluid/inference/tensorrt/convert/op_converter.h
  paddle/fluid/inference/tensorrt/engine.cc
  paddle/fluid/inference/tensorrt/engine.h
Labels: contributor, status: proposed

#46282 [cherry-pick][xpu] update xdnn activations
  cmake/external/xpu.cmake
  paddle/phi/kernels/xpu/activation_kernel.cc
Labels: contributor, status: proposed

#45959 【PFCC算子性能优化】为Paddle优化adaptive_pooling_op性能
  paddle/phi/kernels/funcs/pooling.cu
  paddle/phi/kernels/funcs/pooling.h
Labels: contributor

#46236 [CodeStyle] remove tabs in cpp files
  paddle/fluid/operators/dequeue_op.cc
  paddle/fluid/operators/enqueue_op.cc
  paddle/fluid/operators/pixel_shuffle_op.cc
  paddle/fluid/operators/pixel_unshuffle_op.cc
  paddle/fluid/operators/reader/create_ctr_reader_op.cc
  paddle/fluid/operators/shuffle_channel_op.cc
Labels: contributor, status: proposed

#46232 [CodeStyle] add pre-commit hook `remove-tabs` for cpp files
  .pre-commit-config.yaml
Labels: contributor, status: proposed

#46090 [Paddle-TRT] remove trt_reshape2_matmul_fuse_pass
  paddle/fluid/inference/api/paddle_pass_builder.cc
  python/paddle/fluid/tests/unittests/ir/inference/CMakeLists.txt
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_reshape2_matmul_fuse_pass.py
Labels: contributor, status: proposed

#45943 [CodeStyle] init flake8 configs
  .editorconfig
  .flake8
  .pre-commit-config.yaml
Labels: contributor, status: proposed

#46306 [CodeStyle]update for ranking_loss #46302
  python/paddle/nn/functional/loss.py
Labels: contributor, status: not progressed

#46332 optimization of depthwise_conv2d grad
  paddle/phi/kernels/gpu/depthwise_conv.h
Labels: contributor, status: proposed

#46318 migrate add_n kernel to phi
  paddle/fluid/operators/sum_op_xpu.cc
  paddle/phi/kernels/xpu/add_n_kernel.cc
Labels: contributor, status: proposed

#46312 fix error: control reaches end of non-void function
  paddle/fluid/eager/backward.cc
Labels: contributor, status: proposed

#45989 [PHI] Revert pool and pool_grad oneDNN kernel conversion
  paddle/fluid/operators/mkldnn/pool_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/test_mkldnn_op_nhwc.cc
  paddle/phi/backends/onednn/onednn_reuse.h
  paddle/phi/kernels/onednn/pool_grad_kernel.cc
  paddle/phi/kernels/onednn/pool_kernel.cc
Labels: Intel, contributor

#46313 [MLU] add int64 support for mlu one_hot_v2
  paddle/fluid/operators/one_hot_v2_op_mlu.cc
Labels: contributor, status: proposed

#45752 [docs] fix some format issue
  python/paddle/distribution/kl.py
  python/paddle/distribution/normal.py
  python/paddle/distribution/transform.py
  python/paddle/distribution/uniform.py
  python/paddle/nn/functional/activation.py
  python/paddle/nn/functional/common.py
  python/paddle/nn/functional/loss.py
  python/paddle/nn/functional/norm.py
  python/paddle/nn/functional/vision.py
  python/paddle/profiler/profiler.py
  python/paddle/profiler/utils.py
  python/paddle/tensor/math.py
  python/paddle/utils/cpp_extension/cpp_extension.py
Labels: contributor, status: proposed

#46334 [Paddle-TRT]fix bug in fill_constant_batch_size_like op
  paddle/fluid/inference/tensorrt/convert/fill_constant_batch_size_like_op.cc
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_rnn.py
Labels: contributor, status: proposed

#46309 [CodeStyle][W191][E101] remove tabs in python NPU unittest files
  python/paddle/fluid/tests/unittests/npu/test_eye_op_npu.py
Labels: contributor, status: proposed

#46374 [PHI] Migrate sgd and stack oneDNN kernels
  paddle/fluid/operators/mkldnn/stack_mkldnn_op.cc
  paddle/fluid/operators/optimizers/mkldnn/sgd_mkldnn_op.cc
  paddle/phi/backends/CMakeLists.txt
  paddle/phi/backends/onednn/axpy_handler.cc
  paddle/phi/backends/onednn/axpy_handler.h
  paddle/phi/kernels/onednn/sgd_kernel.cc
  paddle/phi/kernels/onednn/stack_kernel.cc
Labels: Intel, contributor

#46239 [PHI] Sum op migration
  paddle/fluid/operators/mkldnn/sum_mkldnn_op.cc
  paddle/phi/kernels/onednn/add_n_kernel.cc
Labels: Intel, contributor

#46357 [CodeStyle][W191][E101] remove tabs in python fluid unittests
  python/paddle/fluid/tests/unittests/test_eye_op.py
  python/paddle/fluid/tests/unittests/test_generate_proposal_labels_op.py
  python/paddle/fluid/tests/unittests/test_generate_proposals_op.py
  python/paddle/fluid/tests/unittests/test_optimizer.py
  python/paddle/fluid/tests/unittests/test_recurrent_op.py
  python/paddle/fluid/tests/unittests/xpu/test_generate_proposals_v2_op_xpu.py
Labels: contributor

#46165 Fix the En docs (delete some expression like 'This OP')
  python/paddle/autograd/py_layer.py
  python/paddle/device/cuda/__init__.py
  python/paddle/distributed/collective.py
  python/paddle/distributed/fleet/base/private_helper_function.py
  python/paddle/distributed/parallel.py
  python/paddle/distributed/sharding/group_sharded.py
  python/paddle/distribution/distribution.py
  python/paddle/framework/io.py
  python/paddle/incubate/autograd/primapi.py
  python/paddle/incubate/autograd/primx.py
  python/paddle/incubate/autograd/utils.py
  python/paddle/incubate/sparse/creation.py
  python/paddle/nn/functional/activation.py
  python/paddle/nn/functional/conv.py
  python/paddle/nn/functional/extension.py
  python/paddle/nn/functional/loss.py
  python/paddle/nn/functional/norm.py
  python/paddle/nn/functional/pooling.py
  python/paddle/nn/layer/activation.py
  python/paddle/nn/layer/common.py
  python/paddle/nn/layer/conv.py
  python/paddle/nn/layer/loss.py
  python/paddle/nn/layer/norm.py
  python/paddle/nn/layer/pooling.py
  python/paddle/nn/utils/spectral_norm_hook.py
  python/paddle/nn/utils/weight_norm_hook.py
  python/paddle/optimizer/lr.py
  python/paddle/optimizer/rmsprop.py
  python/paddle/reader/decorator.py
  python/paddle/static/io.py
  python/paddle/static/nn/common.py
  python/paddle/tensor/linalg.py
  python/paddle/tensor/logic.py
  python/paddle/tensor/manipulation.py
  python/paddle/tensor/math.py
  python/paddle/utils/cpp_extension/cpp_extension.py
  python/paddle/vision/ops.py
Labels: contributor, status: proposed

#46208 [MLU] fix profiler compile failure
  paddle/fluid/platform/profiler/profiler.cc
Labels: contributor, status: proposed

#45233 [IPU] fix ut timeout 2
  python/paddle/fluid/tests/unittests/ipu/CMakeLists.txt
  python/paddle/fluid/tests/unittests/ipu/op_test_ipu.py
Labels: contributor, status: proposed

#46417 [MLU] add barrier_op kernel.
  paddle/fluid/operators/collective/barrier_op_mlu.cc
Labels: contributor, status: proposed

#44913 【PaddlePaddle Hackathon 3 No.9】为 Paddle 新增 Laplace API
  python/paddle/distribution/__init__.py
  python/paddle/distribution/kl.py
  python/paddle/distribution/laplace.py
  python/paddle/fluid/tests/unittests/distribution/test_distribution_laplace.py
  python/paddle/fluid/tests/unittests/distribution/test_distribution_laplace_static.py
Labels: PaddlePaddle Hackathon, contributor

#46241 add phi reduce_sum test=kunlun
  paddle/fluid/operators/reduce_ops/reduce_sum_op_xpu.cc
  paddle/phi/kernels/reduce_sum_kernel.cc
  paddle/phi/kernels/xpu/reduce_sum_grad_kernel.cc
  paddle/phi/kernels/xpu/reduce_sum_kernel.cc
  python/paddle/fluid/tests/unittests/xpu/test_reduce_max_op_xpu.py
  python/paddle/fluid/tests/unittests/xpu/test_reduce_sum_op_xpu.py
Labels: contributor

#46288 [CodeStyle][W191][E101] remove tabs in python files
  python/paddle/distributed/fleet/dataset/dataset.py
  python/paddle/incubate/nn/layer/fused_transformer.py
  python/paddle/incubate/sparse/unary.py
  python/paddle/nn/functional/common.py
  python/paddle/nn/functional/loss.py
  python/paddle/nn/layer/loss.py
  python/paddle/nn/layer/norm.py
  python/paddle/optimizer/adagrad.py
  python/paddle/optimizer/adam.py
  python/paddle/optimizer/adamax.py
  python/paddle/optimizer/adamw.py
  python/paddle/tensor/attribute.py
  python/paddle/tensor/manipulation.py
  python/paddle/text/datasets/conll05.py
Labels: contributor, status: not progressed

#46410 [CodeStyle] remove some `yapf: disable`
  python/paddle/fluid/tests/unittests/fft/test_fft.py
  python/paddle/fluid/tests/unittests/fft/test_fft_with_static_graph.py
  python/paddle/fluid/tests/unittests/test_signal.py
  python/paddle/tensor/math.py
Labels: contributor, status: proposed

#46429 [MLU] fluid: add mluop
  cmake/neuware.cmake
  paddle/fluid/operators/mlu/mlu_baseop.cc
  paddle/fluid/operators/mlu/mlu_baseop.h
  paddle/fluid/platform/device/mlu/device_context.cc
  paddle/fluid/platform/device/mlu/device_context.h
  paddle/fluid/platform/device/mlu/enforce.h
  paddle/fluid/platform/device/mlu/mlu_info.cc
  paddle/fluid/platform/device/mlu/mlu_info.h
  python/paddle/fluid/tests/unittests/mlu/test_grid_sampler_op_mlu.py
  python/paddle/fluid/tests/unittests/mlu/test_reduce_sum_op_mlu.py
  tools/dockerfile/Dockerfile.mlu
Labels: contributor, status: proposed

#46459 Conv grad to use set_mem_desc()
  paddle/fluid/operators/mkldnn/conv_mkldnn_op.cc
Labels: Intel, contributor, status: proposed

#46290 [CodeStyle] add pre-commit hook `remove-tabs` for python files
  .flake8
  .pre-commit-config.yaml
Labels: contributor

#46466 [CodeStyle] add CI script to prevent future import
  tools/check_file_diff_approvals.sh
Labels: contributor

#46463 [CodeStyle] format some dy2static unittests
  .pre-commit-config.yaml
  python/paddle/fluid/tests/unittests/dygraph_to_static/test_error.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/test_origin_info.py
Labels: contributor, status: proposed

#46507 [CodeStyle][F401] initial F401 config
  .flake8
Labels: contributor, status: proposed

#46501 [PHI] relu6_grad kernel
  paddle/fluid/operators/mkldnn/activation_mkldnn_op.cc
  paddle/fluid/platform/mkldnn_reuse.h
  paddle/phi/kernels/onednn/activation_grad_kernel.cc
  paddle/phi/kernels/onednn/activation_kernel.cc
Labels: Intel, contributor

#46372 Replacing set_format with set_mem_desc in FC onednn kernel
  paddle/fluid/operators/mkldnn/fc_mkldnn_op.cc
  python/paddle/fluid/tests/unittests/mkldnn/test_fc_int8_mkldnn_op.py
  python/paddle/fluid/tests/unittests/mkldnn/test_fc_mkldnn_op.py
Labels: Intel, contributor

#46363 [Paddle-TRT][Cherry-Pick] remove trt_reshape2_matmul_fuse_pass
  paddle/fluid/inference/api/paddle_pass_builder.cc
  python/paddle/fluid/tests/unittests/ir/inference/CMakeLists.txt
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_reshape2_matmul_fuse_pass.py
Labels: contributor, status: proposed

#46437 [XPU] update xpu cmake to 0928.
  cmake/external/xpu.cmake
  paddle/phi/kernels/xpu/activation_kernel.cc
Labels: contributor, status: proposed

#46376 [CodeStyle][F401] remove unused imports in unittest/asp, autograd, interpreter
  python/paddle/fluid/tests/unittests/asp/asp_pruning_base.py
  python/paddle/fluid/tests/unittests/asp/test_asp_optimize_dynamic.py
  python/paddle/fluid/tests/unittests/asp/test_asp_optimize_static.py
  python/paddle/fluid/tests/unittests/asp/test_asp_pruning_static.py
  python/paddle/fluid/tests/unittests/asp/test_fleet_with_asp_dynamic.py
  python/paddle/fluid/tests/unittests/asp/test_fleet_with_asp_sharding.py
  python/paddle/fluid/tests/unittests/asp/test_fleet_with_asp_static.py
  python/paddle/fluid/tests/unittests/autograd/test_autograd_functional_dynamic.py
  python/paddle/fluid/tests/unittests/autograd/test_autograd_functional_prim.py
  python/paddle/fluid/tests/unittests/autograd/test_autograd_functional_static.py
  python/paddle/fluid/tests/unittests/autograd/test_jvp_and_transpose.py
  python/paddle/fluid/tests/unittests/autograd/test_orig2prim.py
  python/paddle/fluid/tests/unittests/autograd/test_prim2orig.py
  python/paddle/fluid/tests/unittests/autograd/test_primops.py
  python/paddle/fluid/tests/unittests/autograd/test_transform.py
  python/paddle/fluid/tests/unittests/autograd/utils.py
  python/paddle/fluid/tests/unittests/interpreter/test_standalone_controlflow.py
  python/paddle/fluid/tests/unittests/interpreter/test_standalone_multiply_write.py
Labels: contributor, status: proposed

#45651 [MLU] add mlu kernel for reduce_max_grad
  paddle/fluid/operators/reduce_ops/reduce_max_op_mlu.cc
Labels: contributor

#46616 [CodeStyle][F401] update flake8 F401 config (unittest/asp,interpreter,autograd,collective)
  .flake8
Labels: contributor, status: proposed

#46557 Add index_select, index_select_grad, reduce_min kernel for kunlun. test=kunlun.
  paddle/fluid/platform/device/xpu/xpu2_op_list.h
  paddle/phi/kernels/reduce_min_kernel.cc
  paddle/phi/kernels/xpu/index_select_kernel.cc
  paddle/phi/kernels/xpu/reduce_min_kernel.cc
  python/paddle/fluid/tests/unittests/xpu/test_index_select_op_xpu.py
Labels: contributor

#46401 [Hackathon No.18] 为 Paddle 新增 frexp API
  python/paddle/__init__.py
  python/paddle/fluid/tests/unittests/test_frexp_api.py
  python/paddle/tensor/__init__.py
  python/paddle/tensor/math.py
Labels: PaddlePaddle Hackathon, contributor

#44607 update docs for ResNetBasicBlock, test=kunlun
  python/paddle/incubate/xpu/resnet_block.py
Labels: contributor

#46601 fix mpi include bug
  paddle/fluid/distributed/collective/ProcessGroupMPI.cc
Labels: contributor, status: proposed

#45849 【Hackathon No.21】为 Paddle 新增 paddle.incubate.sparse.transpose 稀疏 API
  paddle/phi/api/yaml/sparse_backward.yaml
  paddle/phi/api/yaml/sparse_ops.yaml
  paddle/phi/core/sparse_coo_tensor.h
  paddle/phi/core/sparse_csr_tensor.h
  paddle/phi/infermeta/sparse/unary.h
  paddle/phi/kernels/sparse/cpu/transpose_grad_kernel.cc
  paddle/phi/kernels/sparse/cpu/transpose_kernel.cc
  paddle/phi/kernels/sparse/gpu/transpose_grad_kernel.cu
  paddle/phi/kernels/sparse/gpu/transpose_kernel.cu
  paddle/phi/kernels/sparse/unary_grad_kernel.h
  paddle/phi/kernels/sparse/unary_kernel.h
  paddle/phi/tests/kernels/CMakeLists.txt
  paddle/phi/tests/kernels/test_sparse_transpose_dev_api.cc
  python/paddle/fluid/tests/unittests/test_sparse_transpose_op.py
  python/paddle/incubate/sparse/__init__.py
  python/paddle/incubate/sparse/unary.py
Labels: contributor, status: proposed

#46634 add ipu related authors
  AUTHORS.md
Labels: contributor, status: proposed

#46540 fix bugs of tipc, test=kunlun
  paddle/fluid/framework/tensor_util.h
  paddle/fluid/platform/device/xpu/xpu2_op_list.h
  paddle/phi/kernels/assign_kernel.cc
  paddle/phi/kernels/batch_norm_kernel.cc
  paddle/phi/kernels/empty_kernel.cc
  paddle/phi/kernels/xpu/stack_grad_kernel.cc
  paddle/phi/kernels/xpu/top_k_kernel.cc
Labels: contributor

#46573 [MLU] add_fluid_mluop_yolo_box
  paddle/fluid/operators/detection/CMakeLists.txt
  paddle/fluid/operators/detection/yolo_box_op_mlu.cc
  paddle/fluid/operators/mlu/mlu_baseop.cc
  paddle/fluid/operators/mlu/mlu_baseop.h
  python/paddle/fluid/tests/unittests/mlu/test_yolo_box_op_mlu.py
Labels: contributor, status: proposed

#46649 [MLU] fix phi::Tensor compile error of mlu.
  paddle/fluid/operators/collective/barrier_op_mlu.cc
  paddle/fluid/operators/huber_loss_op_mlu.cc
  python/paddle/fluid/tests/unittests/mlu/test_collective_api_base_mlu.py
  python/paddle/fluid/tests/unittests/mlu/test_collective_base_mlu.py
  python/paddle/fluid/tests/unittests/mlu/test_slice_op_mlu.py
  python/paddle/fluid/tests/unittests/mlu/test_sync_batch_norm_base_mlu.py
Labels: contributor, status: proposed

#45235 [IPU] paddle-inference support custom-ops
  paddle/fluid/framework/ir/ipu/infer_shape_pass.cc
  paddle/fluid/framework/ir/ipu/inference_dtype_transfer_pass.cc
  paddle/fluid/framework/ir/ipu/inference_process_pass.cc
  paddle/fluid/inference/analysis/argument.h
  paddle/fluid/inference/analysis/passes/ir_graph_build_pass.cc
  paddle/fluid/inference/api/analysis_config.cc
  paddle/fluid/inference/api/analysis_predictor.cc
  paddle/fluid/inference/api/paddle_analysis_config.h
  paddle/fluid/platform/device/ipu/ipu_backend.cc
  paddle/fluid/pybind/inference_api.cc
Labels: contributor, status: proposed
