Repository PaddlePaddle/Paddle, pull requests merged in 2022-08, with the labels that each got.

#42413 update document of quantile and nanquantile; test=document_fix
  python/paddle/tensor/stat.py
Labels: contributor, status: proposed

#44210 support build with Ninja on Linux
  cmake/external/dgc.cmake
  cmake/external/gflags.cmake
  cmake/external/mkldnn.cmake
  cmake/external/openblas.cmake
  cmake/external/rocksdb.cmake
  cmake/third_party.cmake
Labels: contributor, status: proposed

#44744 Fix to CI
  paddle/fluid/operators/mkldnn/matmul_v2_mkldnn_op.cc
Labels: Intel

#44347 Update linalg.py (just two typos)
  python/paddle/tensor/linalg.py
Labels: contributor, status: proposed

#44191 update manipulation.py paddle.moveaxis test=document_fix
  python/paddle/tensor/manipulation.py
Labels: contributor, status: proposed

#44035 Modify the output result annotation under the lerp function
  python/paddle/tensor/math.py
Labels: contributor

#44720 support beam_search operator on xpu. test=kunlun
  paddle/fluid/operators/beam_search_op_xpu.cc
  paddle/fluid/operators/math/CMakeLists.txt
  paddle/fluid/operators/math/beam_search_xpu.cc
  paddle/fluid/platform/device/xpu/xpu2_op_list.h
Labels: contributor, status: proposed

#44038 Update manipulation.py paddle.rot90()补上漏掉的"k的绝对值"。
  python/paddle/tensor/manipulation.py
Labels: contributor

#44787 fix get_pr_ut error
  tools/get_pr_ut.py
Labels: contributor, status: proposed

#44756 [Paddle-TRT] remove stack plugin
  paddle/fluid/inference/tensorrt/convert/stack_op.cc
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_stack.py
Labels: contributor, status: proposed

#44460 [MLU] add strided_slice mlu kernel
  paddle/fluid/memory/memcpy.cc
  paddle/fluid/operators/strided_slice_op_mlu.cc
  paddle/fluid/operators/utils.h
Labels: contributor, status: proposed

#44807 训练进程异常退出，但是分布式lanch进程是正常退出状态的问题修复 #44583
  python/paddle/distributed/fleet/launch_utils.py
Labels: contributor, status: proposed

#44195 【PaddlePaddle Hackathon 3 No.5】为 Paddle 新增 bucketize
  python/paddle/__init__.py
  python/paddle/fluid/tests/unittests/test_bucketize_api.py
  python/paddle/tensor/__init__.py
  python/paddle/tensor/search.py
Labels: contributor, status: proposed

#44854 [XPU] fleet dist_model support xpu
  paddle/fluid/distributed/fleet_executor/dist_model.cc
  python/paddle/fluid/tests/unittests/xpu/test_fleet_exe_dist_model_run_xpu.py
Labels: contributor, status: proposed

#44757 [Paddle-TRT][cherry pick] Slice to 2.3
  paddle/fluid/inference/tensorrt/convert/fc_op.cc
  paddle/fluid/inference/tensorrt/convert/multihead_matmul_op.cc
  paddle/fluid/inference/tensorrt/convert/slice_op.cc
  paddle/fluid/inference/tensorrt/engine.cc
  paddle/fluid/inference/tensorrt/op_teller.cc
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_slice.py
Labels: contributor, status: proposed

#44677 OneDNN md-in-tensor refactoring part 6: Memory descriptor enabled for conv and conv_transpose
  paddle/fluid/operators/mkldnn/conv_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/conv_transpose_mkldnn_op.cc
Labels: Intel, contributor

#44678 [Paddle-TRT] add Rnn
  paddle/fluid/inference/api/analysis_predictor.cc
  paddle/fluid/inference/tensorrt/convert/CMakeLists.txt
  paddle/fluid/inference/tensorrt/convert/fill_constant_batch_size_like_op.cc
  paddle/fluid/inference/tensorrt/convert/rnn_op.cc
  paddle/fluid/inference/tensorrt/op_teller.cc
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_rnn.py
Labels: contributor, status: proposed

#44679 [Docs][en] adjust code example format
  python/paddle/distribution/transform.py
  python/paddle/fluid/dataloader/dataset.py
  python/paddle/fluid/dygraph/base.py
  python/paddle/fluid/dygraph/layers.py
  python/paddle/fluid/executor.py
  python/paddle/fluid/initializer.py
  python/paddle/incubate/autotune.py
  python/paddle/nn/functional/activation.py
  python/paddle/nn/functional/loss.py
  python/paddle/nn/functional/pooling.py
  python/paddle/nn/functional/vision.py
  python/paddle/nn/initializer/constant.py
  python/paddle/nn/initializer/normal.py
  python/paddle/nn/initializer/uniform.py
  python/paddle/nn/initializer/xavier.py
  python/paddle/nn/layer/activation.py
  python/paddle/nn/layer/loss.py
  python/paddle/nn/layer/pooling.py
  python/paddle/nn/layer/vision.py
  python/paddle/profiler/profiler.py
  python/paddle/profiler/utils.py
  python/paddle/static/io.py
  python/paddle/tensor/creation.py
  python/paddle/tensor/linalg.py
  python/paddle/tensor/manipulation.py
  python/paddle/tensor/math.py
  python/paddle/tensor/random.py
  python/paddle/tensor/search.py
  python/paddle/tensor/stat.py
  python/paddle/vision/ops.py
Labels: contributor, status: proposed

#44655 Matmuls with activation and elementwise_add fuses
  paddle/fluid/framework/ir/CMakeLists.txt
  paddle/fluid/framework/ir/graph_pattern_detector.cc
  paddle/fluid/framework/ir/graph_pattern_detector.h
  paddle/fluid/framework/ir/mkldnn/cpu_bfloat16_pass.cc
  paddle/fluid/framework/ir/mkldnn/matmul_activation_mkldnn_fuse_pass.cc
  paddle/fluid/framework/ir/mkldnn/matmul_elementwise_add_mkldnn_fuse_pass.cc
  paddle/fluid/framework/ir/mkldnn/matmul_elementwise_add_mkldnn_fuse_pass.h
  paddle/fluid/inference/api/paddle_pass_builder.cc
  paddle/fluid/operators/mkldnn/matmul_v2_mkldnn_op.cc
  paddle/fluid/platform/mkldnn_reuse.h
  python/paddle/fluid/tests/unittests/ir/inference/test_mkldnn_matmul_elementwise_add_activation_fuse_pass.py
  python/paddle/fluid/tests/unittests/ir/inference/test_mkldnn_matmul_elementwise_add_fuse_pass.py
  python/paddle/fluid/tests/unittests/ir/inference/test_mkldnn_matmul_v2_activation_fuse_pass.py
  python/paddle/fluid/tests/unittests/ir/inference/test_mkldnn_matmul_v2_elementwise_add_fuse_pass.py
Labels: Intel, contributor

#44909 [IPU] restore dockerfile to gcc8.2
  tools/dockerfile/Dockerfile.ipu
Labels: contributor, status: proposed

#44908 Register matmul int8 with MatMulV2MKLDNNKernel
  paddle/fluid/operators/mkldnn/matmul_v2_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/mul_mkldnn_op.cc
  paddle/fluid/platform/mkldnn_reuse.h
Labels: Intel, int8, contributor

#44883 modify pybind.cc (maybe a typo)
  paddle/fluid/pybind/pybind.cc
Labels: contributor, status: proposed

#44870 Merge matmul_v1 and matmul_v2 fuse passes
  paddle/fluid/framework/ir/CMakeLists.txt
  paddle/fluid/framework/ir/mkldnn/matmul_transpose_reshape_fuse_pass.h
  paddle/fluid/framework/ir/mkldnn/matmul_transpose_reshape_mkldnn_fuse_pass.cc
  paddle/fluid/framework/ir/mkldnn/matmul_transpose_reshape_mkldnn_fuse_pass.h
  paddle/fluid/framework/ir/mkldnn/matmul_transpose_reshape_mkldnn_fuse_pass_tester.cc
  paddle/fluid/framework/ir/mkldnn/matmul_v2_transpose_reshape_fuse_pass.cc
  paddle/fluid/framework/ir/mkldnn/reshape_transpose_matmul_mkldnn_fuse_pass.cc
  paddle/fluid/framework/ir/mkldnn/reshape_transpose_matmul_mkldnn_fuse_pass.h
  paddle/fluid/framework/ir/mkldnn/reshape_transpose_matmul_mkldnn_fuse_pass_tester.cc
  paddle/fluid/framework/ir/mkldnn/reshape_transpose_matmul_v2_mkldnn_fuse_pass.cc
  paddle/fluid/framework/ir/mkldnn/reshape_transpose_matmul_v2_mkldnn_fuse_pass.h
  paddle/fluid/inference/api/paddle_pass_builder.cc
  python/paddle/fluid/contrib/slim/quantization/quant2_int8_mkldnn_pass.py
  python/paddle/fluid/tests/unittests/ir/inference/test_mkldnn_matmul_transpose_reshape_fuse_pass.py
  python/paddle/fluid/tests/unittests/ir/inference/test_mkldnn_matmul_v2_transpose_reshape_fuse_pass.py
  python/paddle/fluid/tests/unittests/ir/inference/test_mkldnn_reshape_transpose_matmul_v2_fuse_pass.py
Labels: Intel, contributor

#44919 [MLU] fix bn_grad and hard_sigmoid_grad error
  paddle/fluid/operators/activation_op_mlu.cc
  paddle/fluid/operators/batch_norm_op_mlu.cc
  paddle/fluid/operators/conv_transpose_op_mlu.cc
  paddle/phi/kernels/funcs/activation_functor.h
Labels: contributor, status: proposed

#43996 【Fix en docs】 Fix document formatting*test=document_fix
  python/paddle/fluid/io.py
  python/paddle/fluid/layers/loss.py
  python/paddle/fluid/layers/nn.py
  python/paddle/fluid/layers/sequence_lod.py
  python/paddle/fluid/metrics.py
  python/paddle/nn/functional/common.py
  python/paddle/nn/functional/extension.py
  python/paddle/nn/functional/loss.py
  python/paddle/nn/layer/loss.py
  python/paddle/static/io.py
  python/paddle/tensor/creation.py
  python/paddle/tensor/manipulation.py
  python/paddle/utils/cpp_extension/cpp_extension.py
Labels: contributor

#44936 modified gcda_clean to make it more robust
  tools/coverage/gcda_clean.py
Labels: contributor, status: proposed

#44972 fix format for paddle/phi/api/lib/tensor.cc
  paddle/fluid/inference/tests/api/analyzer_rnn1_tester.cc
  paddle/fluid/operators/fused/fused_softmax_mask.cu.h
  paddle/fluid/pybind/pybind.cc
  paddle/infrt/common/type.h
  paddle/phi/api/lib/data_transform.cc
  paddle/phi/api/lib/tensor.cc
  paddle/phi/api/lib/tensor_method.cc
Labels: contributor, PFCC

#45003 Fix random seed for test_distribution_* UTs
  python/paddle/fluid/tests/unittests/distribution/test_distribution_beta_static.py
  python/paddle/fluid/tests/unittests/distribution/test_distribution_categorical.py
  python/paddle/fluid/tests/unittests/distribution/test_distribution_constraint.py
  python/paddle/fluid/tests/unittests/distribution/test_distribution_dirichlet.py
  python/paddle/fluid/tests/unittests/distribution/test_distribution_dirichlet_static.py
  python/paddle/fluid/tests/unittests/distribution/test_distribution_expfamily.py
  python/paddle/fluid/tests/unittests/distribution/test_distribution_expfamily_static.py
  python/paddle/fluid/tests/unittests/distribution/test_distribution_independent.py
  python/paddle/fluid/tests/unittests/distribution/test_distribution_independent_static.py
  python/paddle/fluid/tests/unittests/distribution/test_distribution_normal.py
  python/paddle/fluid/tests/unittests/distribution/test_distribution_transform.py
  python/paddle/fluid/tests/unittests/distribution/test_distribution_transform_static.py
  python/paddle/fluid/tests/unittests/distribution/test_distribution_uniform.py
  python/paddle/fluid/tests/unittests/distribution/test_distribution_variable.py
  python/paddle/fluid/tests/unittests/distribution/test_kl.py
  python/paddle/fluid/tests/unittests/distribution/test_kl_static.py
Labels: NVIDIA, contributor

#45023 [Paddle-TRT] fix conv2d/int64
  paddle/fluid/inference/tensorrt/op_teller.cc
Labels: contributor, status: proposed

#44568 【PaddlePaddle Hackathon 3 No.17】为 Paddle 新增 sgn
  python/paddle/__init__.py
  python/paddle/fluid/tests/unittests/test_sgn.py
  python/paddle/tensor/__init__.py
  python/paddle/tensor/math.py
Labels: PaddlePaddle Hackathon, contributor

#45081 [XPU] fix typo in unit tests.
  python/paddle/fluid/tests/unittests/xpu/get_test_cover_info.py
  python/paddle/fluid/tests/unittests/xpu/test_conv2d_op_xpu.py
  python/paddle/fluid/tests/unittests/xpu/test_fused_resnet_basic_block_op_xpu.py
  python/paddle/fluid/tests/unittests/xpu/test_generate_proposals_v2_op_xpu.py
  python/paddle/fluid/tests/unittests/xpu/test_refactor_op_xpu.py
  python/paddle/fluid/tests/unittests/xpu/test_rnn_op_xpu.py
Labels: contributor, status: proposed

#45087 [IPU] fix compilation
  paddle/fluid/platform/device/ipu/ipu_compiler.cc
Labels: contributor, status: proposed

#44941 Offload calculations from matmul op to fuse pass
  paddle/fluid/framework/ir/mkldnn/matmul_transpose_reshape_mkldnn_fuse_pass.cc
  paddle/fluid/framework/ir/mkldnn/reshape_transpose_matmul_mkldnn_fuse_pass.cc
  paddle/fluid/operators/matmul_op.cc
  paddle/fluid/operators/matmul_v2_op.cc
  paddle/fluid/operators/mkldnn/matmul_v2_mkldnn_op.cc
  paddle/phi/core/ddim.cc
  python/paddle/fluid/tests/unittests/ir/inference/test_mkldnn_matmul_activation_fuse_pass.py
  python/paddle/fluid/tests/unittests/ir/inference/test_mkldnn_matmul_v2_activation_fuse_pass.py
Labels: Intel, contributor

#45049 [XPU] add some collective ops.
  cmake/external/xpu.cmake
  paddle/fluid/distributed/fleet_executor/dist_model.cc
  paddle/fluid/operators/collective/c_allgather_op_xpu.cc
  paddle/fluid/operators/collective/c_allreduce_sum_op_xpu.cc
  paddle/fluid/operators/collective/c_identity_op_xpu.cc
  paddle/fluid/operators/collective/c_sync_comm_stream_op_xpu.cc
  paddle/fluid/platform/device/xpu/bkcl_helper.h
  paddle/fluid/platform/device/xpu/xpu2_op_list.h
  python/paddle/fluid/tests/unittests/xpu/collective_allgather_op_xpu.py
  python/paddle/fluid/tests/unittests/xpu/collective_allreduce_op_xpu.py
  python/paddle/fluid/tests/unittests/xpu/collective_identity_op_xpu.py
  python/paddle/fluid/tests/unittests/xpu/test_collective_allgather_xpu.py
  python/paddle/fluid/tests/unittests/xpu/test_collective_allreduce_xpu.py
  python/paddle/fluid/tests/unittests/xpu/test_collective_base_xpu.py
  python/paddle/fluid/tests/unittests/xpu/test_collective_identity_xpu.py
Labels: contributor, status: proposed

#45102 Refine TRT unit test
  paddle/fluid/inference/tests/api/trt_dynamic_shape_ernie_test.cc
  python/paddle/fluid/tests/unittests/ir/inference/auto_scan_test.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_affine_channel.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_batch_norm.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_conv2d.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_conv2d_fusion.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_conv2d_transpose.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_depthwise_conv2d.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_depthwise_conv2d_transpose.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_elementwise.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_flatten.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_flatten_contiguous_range.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_hard_swish.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_mish.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_pool2d.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_prelu.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_scale.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_skip_layernorm.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_swish.py
Labels: NVIDIA

#45152 [XPU] add truncated_gaussian_random op.
  paddle/fluid/platform/device/xpu/xpu2_op_list.h
  python/paddle/fluid/tests/unittests/xpu/test_truncated_gaussian_random_op_xpu.py
Labels: contributor, status: proposed

#45126 [CodeStyle] Add CI for self.assertTrue(np.allclose(...))
  tools/check_file_diff_approvals.sh
Labels: contributor, status: proposed

#45194 [MLU] fix copy error
  paddle/fluid/operators/gaussian_random_op_mlu.cc
  paddle/fluid/operators/optimizers/adam_op_mlu.cc
  paddle/fluid/pybind/tensor_py.h
Labels: contributor, status: proposed

#45201 [MLU] fix celoss to use valid_label.
  python/paddle/nn/functional/loss.py
Labels: contributor, status: proposed

#45239 seem to be a typo
  paddle/fluid/pybind/pybind.cc
Labels: contributor, status: proposed

#45213 [CodeStyle] use np.testing.assert_allclose instead of self.assertTrue(np.allclose(...)) (part 2)
  python/paddle/fluid/tests/unittests/dygraph_to_static/test_build_strategy.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/test_mnist.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/test_mobile_net.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/test_resnet.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/test_resnet_amp.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/test_resnet_pure_fp16.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/test_resnet_v2.py
  python/paddle/fluid/tests/unittests/test_activation_op.py
  python/paddle/fluid/tests/unittests/test_auc_op.py
  python/paddle/fluid/tests/unittests/test_bce_loss.py
  python/paddle/fluid/tests/unittests/test_bce_with_logits_loss.py
  python/paddle/fluid/tests/unittests/test_cond.py
  python/paddle/fluid/tests/unittests/test_dygraph_weight_norm.py
  python/paddle/fluid/tests/unittests/test_einsum.py
  python/paddle/fluid/tests/unittests/test_einsum_v2.py
  python/paddle/fluid/tests/unittests/test_elementwise_heaviside_op.py
  python/paddle/fluid/tests/unittests/test_frac_api.py
  python/paddle/fluid/tests/unittests/test_gather_nd_op.py
  python/paddle/fluid/tests/unittests/test_graph_send_ue_recv_op.py
  python/paddle/fluid/tests/unittests/test_graph_send_uv_op.py
  python/paddle/fluid/tests/unittests/test_imperative_double_grad.py
  python/paddle/fluid/tests/unittests/test_masked_select_op.py
  python/paddle/fluid/tests/unittests/test_math_op_patch.py
  python/paddle/fluid/tests/unittests/test_mse_loss.py
  python/paddle/fluid/tests/unittests/test_multi_dot_op.py
  python/paddle/fluid/tests/unittests/test_multi_label_soft_margin_loss.py
  python/paddle/fluid/tests/unittests/test_nll_loss.py
  python/paddle/fluid/tests/unittests/test_normal.py
  python/paddle/fluid/tests/unittests/test_normalization_wrapper.py
  python/paddle/fluid/tests/unittests/test_pass_builder.py
  python/paddle/fluid/tests/unittests/test_prelu_op.py
  python/paddle/fluid/tests/unittests/test_psroi_pool_op.py
  python/paddle/fluid/tests/unittests/test_queue.py
  python/paddle/fluid/tests/unittests/test_reorder_lod_tensor.py
  python/paddle/fluid/tests/unittests/test_rrelu_op.py
  python/paddle/fluid/tests/unittests/test_searchsorted_op.py
  python/paddle/fluid/tests/unittests/test_sgn.py
  python/paddle/fluid/tests/unittests/test_sigmoid_focal_loss.py
  python/paddle/fluid/tests/unittests/test_smooth_l1_loss.py
  python/paddle/fluid/tests/unittests/test_soft_margin_loss.py
  python/paddle/fluid/tests/unittests/test_softmax2d.py
  python/paddle/fluid/tests/unittests/test_square_error_cost.py
  python/paddle/fluid/tests/unittests/test_tril_indices_op.py
  python/paddle/fluid/tests/unittests/test_unsqueeze_op.py
Labels: contributor, status: proposed

#45229 add case where the HOME directory does not have write permissions
  python/paddle/dataset/common.py
Labels: contributor, status: proposed

#45251 [WIP][CodeStyle] use np.testing.assert_allclose instead of self.assertTrue(np.allclose(...)) (part 3)
  python/paddle/fluid/tests/unittests/test_dropout_op.py
Labels: contributor, status: proposed

#45241 add merged_momentum unittest and change momentum
  paddle/fluid/operators/optimizers/merged_momentum_op_xpu.cc
  paddle/fluid/operators/optimizers/momentum_op_xpu.cc
  paddle/fluid/platform/device/xpu/xpu2_op_list.h
  python/paddle/fluid/tests/unittests/xpu/test_merged_momentum_op_xpu.py
  python/paddle/fluid/tests/unittests/xpu/test_merged_momentum_op_xpu_base.py
  python/paddle/fluid/tests/unittests/xpu/test_momentum_op_xpu.py
Labels: contributor, status: proposed

#45264 Make up beam_search_decode operator test cases on xpu and cpu environment
  paddle/fluid/operators/beam_search_decode_op_test.cc
  paddle/fluid/operators/beam_search_decode_op_xpu_test.cc
Labels: contributor, status: proposed

#45248 [XPU] c_allreduce support int. update bkcl to 1.0.5.
  cmake/external/xpu.cmake
  paddle/fluid/operators/collective/c_allreduce_sum_op_xpu.cc
  paddle/fluid/platform/device/xpu/xpu2_op_list.h
Labels: contributor, status: proposed

#45089 Extend conv_concat_relu to support all activations
  paddle/fluid/framework/ir/CMakeLists.txt
  paddle/fluid/framework/ir/graph_pattern_detector.cc
  paddle/fluid/framework/ir/graph_pattern_detector.h
  paddle/fluid/framework/ir/mkldnn/conv_activation_mkldnn_fuse_pass.cc
  paddle/fluid/framework/ir/mkldnn/conv_activation_mkldnn_fuse_pass.h
  paddle/fluid/framework/ir/mkldnn/conv_concat_relu_mkldnn_fuse_pass.cc
  paddle/fluid/framework/ir/mkldnn/conv_concat_relu_mkldnn_fuse_pass.h
  paddle/fluid/framework/ir/mkldnn/conv_concat_relu_mkldnn_fuse_pass_tester.cc
  paddle/fluid/inference/api/paddle_pass_builder.cc
  python/paddle/fluid/contrib/slim/quantization/quant2_int8_mkldnn_pass.py
  python/paddle/fluid/tests/unittests/ir/inference/test_mkldnn_conv_concat_relu_mkldnn_fuse_pass.py
Labels: Intel

#45077 Add int8 support for matmul+elementwise_add fuse pass
  paddle/fluid/framework/ir/graph_pattern_detector.cc
  paddle/fluid/framework/ir/graph_pattern_detector.h
  paddle/fluid/framework/ir/mkldnn/cpu_quantize_pass.cc
  paddle/fluid/framework/ir/mkldnn/cpu_quantize_pass.h
  paddle/fluid/framework/ir/mkldnn/cpu_quantize_pass_tester.cc
  paddle/fluid/inference/api/paddle_pass_builder.cc
  paddle/fluid/platform/mkldnn_reuse.h
  python/paddle/fluid/contrib/slim/quantization/quant2_int8_mkldnn_pass.py
Labels: Intel, int8

#45273 modify something unimportant when I read source code
  paddle/fluid/framework/scope.h
  paddle/fluid/framework/var_desc.cc
  paddle/phi/core/dense_tensor.inl
Labels: contributor, status: proposed

#45057 【PaddlePaddle Hackathon 3 No.33】为 Paddle 优化 erfinv op 在 GPU 上的计算性能
  paddle/phi/kernels/gpu/erfinv_kernel.cu
Labels: PaddlePaddle Hackathon, contributor, status: proposed

#45270 modify scope.h (delete maybe unnecessary class declaration)
  paddle/fluid/framework/scope.h
Labels: contributor, status: proposed

#45068 update loss.py in nn.functional and nn.layer module;test=document_fix
  python/paddle/nn/functional/common.py
  python/paddle/nn/functional/loss.py
  python/paddle/nn/layer/common.py
  python/paddle/nn/layer/loss.py
Labels: contributor, status: proposed

#45287 fix a syntax error in CspFileReader
  tools/CrossStackProfiler/CspFileReader.py
Labels: contributor, status: proposed

#45238 [MLU]: compile prior box CPU kernel when WITH_MLU is ON for SSD
  paddle/fluid/operators/detection/CMakeLists.txt
Labels: contributor, status: proposed

#45292 Support fp16 of adam operator in xpu environment
  paddle/fluid/operators/optimizers/adam_op_xpu.cc
  paddle/fluid/platform/device/xpu/xpu2_op_list.h
  python/paddle/fluid/tests/unittests/xpu/test_adam_op_xpu.py
Labels: contributor, status: not progressed

#45160 【Hackathon No.34】优化 poisson op
  paddle/phi/backends/gpu/gpu_launch_config.h
  paddle/phi/kernels/gpu/poisson_kernel.cu
Labels: PaddlePaddle Hackathon, contributor

#45386 [Paddle-TRT] add PADDLE_ENFORCE in reshape2
  paddle/fluid/inference/tensorrt/convert/reshape_op.cc
Labels: contributor, status: proposed

#45300 add temporal shift and grad *test=kunlun
  paddle/fluid/platform/device/xpu/xpu2_op_list.h
  paddle/phi/kernels/xpu/temporal_shift_grad_kernel.cc
  paddle/phi/kernels/xpu/temporal_shift_kernel.cc
  python/paddle/fluid/tests/unittests/xpu/test_temporal_shift_op_xpu.py
Labels: contributor, status: proposed

#45168 [triu_indices] add triu_indices_op
  paddle/fluid/operators/triu_indices_op.cc
  paddle/phi/api/yaml/legacy_api.yaml
  paddle/phi/infermeta/nullary.cc
  paddle/phi/infermeta/nullary.h
  paddle/phi/kernels/cpu/triu_indices_kernel.cc
  paddle/phi/kernels/gpu/triu_indices_kernel.cu
  paddle/phi/kernels/triu_indices_kernel.h
  python/paddle/__init__.py
  python/paddle/fluid/tests/unittests/test_triu_indices_op.py
  python/paddle/tensor/creation.py
Labels: PaddlePaddle Hackathon, contributor

#45249 Enable OMP multithreading in lookup_table_v2
  paddle/phi/kernels/cpu/embedding_kernel.cc
Labels: Intel, contributor

#45401 fix reduce mean grad bug *test=kunlun
  paddle/fluid/operators/reduce_ops/reduce_mean_op_xpu.cc
Labels: contributor, status: proposed

#45436 [XPU] add load_combine_op_xpu
  paddle/fluid/operators/load_combine_op_xpu.cc
  paddle/fluid/platform/device/xpu/xpu2_op_list.h
Labels: contributor, status: proposed

#44948 fix en docs in fft and io.dataset
  python/paddle/fft.py
  python/paddle/fluid/dataloader/dataset.py
  python/paddle/nn/functional/common.py
  python/paddle/nn/functional/input.py
  python/paddle/nn/functional/pooling.py
  python/paddle/nn/layer/activation.py
  python/paddle/nn/layer/common.py
  python/paddle/nn/layer/pooling.py
Labels: contributor, status: proposed

#45441 [IPU] fix compile for IPU
  paddle/fluid/platform/device/ipu/ipu_compiler.cc
Labels: contributor, status: proposed

#45234 [IPU] support depthwise_conv2d ops
  paddle/fluid/platform/device/ipu/popart_canonicalization/activation_ops.cc
  paddle/fluid/platform/device/ipu/popart_canonicalization/nn_ops.cc
  python/paddle/fluid/tests/unittests/ipu/test_conv2d_transpose_op_ipu.py
  python/paddle/fluid/tests/unittests/ipu/test_conv_op_ipu.py
Labels: contributor, status: proposed

#45336 [MLU] optimize matmul_grad_v2 dy (B,M,K)*(K,N) for better performance
  paddle/fluid/operators/matmul_v2_op_mlu.cc
  python/paddle/fluid/tests/unittests/mlu/test_matmul_v2_op_mlu.py
Labels: contributor, status: proposed

#45423 update PixelShuffle and PRelu api in vision.py and activation.py；test=document_fix
  python/paddle/nn/functional/activation.py
  python/paddle/nn/functional/vision.py
  python/paddle/nn/layer/activation.py
  python/paddle/nn/layer/vision.py
Labels: contributor, status: proposed

#45397 [PHI] Migrate relu6 and abs kernels
  paddle/fluid/operators/mkldnn/activation_mkldnn_op.cc
  paddle/fluid/platform/mkldnn_reuse.h
  paddle/phi/kernels/funcs/data_layout_transform.cc
  paddle/phi/kernels/funcs/onednn/onednn_helper.h
  paddle/phi/kernels/funcs/onednn/onednn_reuse.h
  paddle/phi/kernels/onednn/activation_grad_kernel.cc
  paddle/phi/kernels/onednn/activation_kernel.cc
  paddle/phi/kernels/transfer_layout_kernel.cc
Labels: Intel, contributor

#45494 [Paddle-TRT] constant-folding
  paddle/fluid/framework/ir/CMakeLists.txt
  paddle/fluid/framework/ir/constant_folding_pass.cc
  paddle/fluid/framework/ir/constant_folding_pass.h
  paddle/fluid/inference/api/paddle_pass_builder.cc
  paddle/fluid/inference/tests/api/analyzer_dam_tester.cc
  paddle/fluid/inference/tests/api/analyzer_ernie_int8_tester.cc
  paddle/fluid/inference/tests/api/analyzer_ernie_tester.cc
  paddle/fluid/inference/tests/api/analyzer_save_model_tester.cc
  paddle/fluid/inference/tests/api/analyzer_seq_pool1_fuse_statis_tester.cc
Labels: contributor, status: proposed

#44741 【PaddlePaddle Hackathon 3 No.16】为 Paddle 新增 API paddle.take
  python/paddle/__init__.py
  python/paddle/fluid/tests/unittests/test_take.py
  python/paddle/tensor/__init__.py
  python/paddle/tensor/math.py
Labels: PaddlePaddle Hackathon, contributor

#45266 【PaddlePaddle Hackathon 3 No.14】为 Paddle 新增 remainder_ API
  paddle/fluid/operators/elementwise/elementwise_mod_op.cc
  python/paddle/__init__.py
  python/paddle/fluid/tests/unittests/test_elementwise_mod_op.py
  python/paddle/fluid/tests/unittests/test_inplace.py
  python/paddle/tensor/__init__.py
  python/paddle/tensor/math.py
Labels: PaddlePaddle Hackathon, contributor

#45099 Fix UT failures
  paddle/fluid/framework/selected_rows_utils.cc
  python/paddle/fluid/contrib/slim/tests/CMakeLists.txt
  python/paddle/fluid/contrib/slim/tests/test_post_training_quantization_mobilenetv1.py
  python/paddle/fluid/tests/unittests/ir/inference/inference_pass_test.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_conv2d.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_instance_norm.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_reduce_sum.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_flatten2_matmul_fuse_pass.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_pool3d_op.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_pool_op.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_reduce_mean_op.py
  python/paddle/fluid/tests/unittests/test_einsum_v2.py
Labels: NVIDIA, contributor
