Repository PaddlePaddle/Paddle, pull requests merged in 2023-01, with the labels that each got.

#49431 memorty_optimize remove inplace op
  paddle/fluid/inference/analysis/passes/memory_optimize_pass.cc
Labels: contributor, status: proposed

#49105 Rewrite scale matmul mkldnn fuse pass tester
  paddle/fluid/framework/ir/CMakeLists.txt
  paddle/fluid/framework/ir/mkldnn/scale_matmul_fuse_pass_tester.cc
  python/paddle/fluid/tests/unittests/ir/inference/test_mkldnn_scale_matmul_fuse_pass.py
Labels: Intel, contributor

#49393 Add not_equal trt converter
  paddle/fluid/inference/api/analysis_predictor.cc
  paddle/fluid/inference/tensorrt/convert/equal_op.cc
  paddle/fluid/inference/tensorrt/op_teller.cc
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_equal.py
Labels: contributor, status: proposed

#49378 [Paddle-TRT] Forbid ops who have 1D intermediate tensor entering Paddle-TRT
  paddle/fluid/inference/tensorrt/op_teller.cc
Labels: contributor, status: proposed

#47989 [Paddle Inference] Implement conv2d_fusion NHWC format using cutlass
  paddle/fluid/framework/ir/CMakeLists.txt
  paddle/fluid/framework/ir/conv2d_fusion_layout_transfer_pass.cc
  paddle/fluid/framework/ir/conv_elementwise_add_act_fuse_pass.cc
  paddle/fluid/framework/ir/silu_fuse_pass.cc
  paddle/fluid/framework/ir/silu_fuse_pass.h
  paddle/fluid/inference/analysis/argument.h
  paddle/fluid/inference/analysis/ir_pass_manager.cc
  paddle/fluid/inference/api/analysis_config.cc
  paddle/fluid/inference/api/analysis_predictor.cc
  paddle/fluid/inference/api/paddle_analysis_config.h
  paddle/fluid/inference/api/paddle_pass_builder.cc
  paddle/fluid/operators/fused/conv_fusion_op.cc
  paddle/fluid/pybind/inference_api.cc
  paddle/phi/kernels/CMakeLists.txt
  paddle/phi/kernels/fusion/cutlass/conv2d/conv2d_bias.cu
  paddle/phi/kernels/fusion/cutlass/conv2d/conv2d_bias_add_relu.cu
  paddle/phi/kernels/fusion/cutlass/conv2d/conv2d_bias_leaky_relu.cu
  paddle/phi/kernels/fusion/cutlass/conv2d/conv2d_bias_relu.cu
  paddle/phi/kernels/fusion/cutlass/conv2d/conv2d_bias_relu_few_channels.cu
  paddle/phi/kernels/fusion/cutlass/conv2d/conv2d_bias_silu.cu
  paddle/phi/kernels/fusion/cutlass/conv2d/conv2d_decl.h
  paddle/phi/kernels/fusion/cutlass/conv2d/conv2d_util.cu
  paddle/phi/kernels/fusion/cutlass/conv2d/conv2d_util.h
  paddle/phi/kernels/fusion/cutlass/conv2d_fusion.cu
  paddle/phi/ops/compat/conv2d_sig.cc
  python/paddle/fluid/tests/unittests/ir/inference/CMakeLists.txt
  python/paddle/fluid/tests/unittests/ir/inference/auto_scan_test.py
  python/paddle/fluid/tests/unittests/ir/inference/test_cutlass_conv2d_fusion_op.py
Labels: contributor, status: proposed

#48685 [CodeStyle][py2] remove python2 installation from `Dockerfile.ubuntu`
  tools/dockerfile/Dockerfile.ubuntu
Labels: contributor, status: proposed

#49108 Replace matmul with matmul_v2 during oneDNN fuse passes
  paddle/fluid/framework/ir/mkldnn/matmul_activation_mkldnn_fuse_pass.cc
  paddle/fluid/framework/ir/mkldnn/matmul_elementwise_add_mkldnn_fuse_pass.cc
  paddle/fluid/framework/ir/mkldnn/matmul_transpose_reshape_mkldnn_fuse_pass.cc
  paddle/fluid/framework/ir/mkldnn/operator_scale_onednn_fuse_pass.cc
  paddle/fluid/framework/ir/mkldnn/reshape_transpose_matmul_mkldnn_fuse_pass.cc
  paddle/fluid/framework/ir/mkldnn/reshape_transpose_matmul_mkldnn_fuse_pass_tester.cc
  paddle/fluid/operators/matmul_op.cc
  paddle/fluid/operators/mkldnn/matmul_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/matmul_v2_mkldnn_op.cc
  paddle/fluid/operators/ops_extra_info.h
  python/paddle/fluid/tests/unittests/ir/inference/test_mkldnn_matmul_activation_fuse_pass.py
  python/paddle/fluid/tests/unittests/ir/inference/test_mkldnn_matmul_elementwise_add_activation_fuse_pass.py
  python/paddle/fluid/tests/unittests/ir/inference/test_mkldnn_matmul_elementwise_add_fuse_pass.py
  python/paddle/fluid/tests/unittests/ir/inference/test_mkldnn_matmul_transpose_reshape_fuse_pass.py
  python/paddle/fluid/tests/unittests/ir/inference/test_mkldnn_matmul_v2_transpose_reshape_fuse_pass.py
  python/paddle/fluid/tests/unittests/ir/inference/test_mkldnn_reshape_transpose_matmul_fuse_pass.py
  python/paddle/fluid/tests/unittests/mkldnn/test_matmul_mkldnn_op.py
Labels: Intel, contributor

#49407 [Cherry-pick] add condition of skipif
  python/paddle/fluid/tests/unittests/test_fused_gate_attention_op.py
Labels: contributor, status: proposed

#49506 [CodeStyle][UP019] update deprecated type annotation in `python/paddle/jit/api.py`
  python/paddle/jit/api.py
Labels: contributor, status: proposed

#49521 Add for-else
  python/paddle/fluid/layers/math_op_patch.py
  python/paddle/fluid/tests/unittests/test_imperative_auto_prune.py
Labels: contributor, status: proposed

#49524 [CI FIX] Revert "Replace matmul with matmul_v2 during oneDNN fuse passes"
  paddle/fluid/framework/ir/mkldnn/matmul_activation_mkldnn_fuse_pass.cc
  paddle/fluid/framework/ir/mkldnn/matmul_elementwise_add_mkldnn_fuse_pass.cc
  paddle/fluid/framework/ir/mkldnn/matmul_transpose_reshape_mkldnn_fuse_pass.cc
  paddle/fluid/framework/ir/mkldnn/operator_scale_onednn_fuse_pass.cc
  paddle/fluid/framework/ir/mkldnn/reshape_transpose_matmul_mkldnn_fuse_pass.cc
  paddle/fluid/framework/ir/mkldnn/reshape_transpose_matmul_mkldnn_fuse_pass_tester.cc
  paddle/fluid/operators/matmul_op.cc
  paddle/fluid/operators/mkldnn/matmul_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/matmul_v2_mkldnn_op.cc
  paddle/fluid/operators/ops_extra_info.h
  python/paddle/fluid/tests/unittests/ir/inference/test_mkldnn_matmul_activation_fuse_pass.py
  python/paddle/fluid/tests/unittests/ir/inference/test_mkldnn_matmul_elementwise_add_activation_fuse_pass.py
  python/paddle/fluid/tests/unittests/ir/inference/test_mkldnn_matmul_elementwise_add_fuse_pass.py
  python/paddle/fluid/tests/unittests/ir/inference/test_mkldnn_matmul_transpose_reshape_fuse_pass.py
  python/paddle/fluid/tests/unittests/ir/inference/test_mkldnn_matmul_v2_transpose_reshape_fuse_pass.py
  python/paddle/fluid/tests/unittests/ir/inference/test_mkldnn_reshape_transpose_matmul_fuse_pass.py
  python/paddle/fluid/tests/unittests/mkldnn/test_matmul_mkldnn_op.py
Labels: Intel, contributor

#49516 [CodeStyle][py36] update requirements.txt and setup.py.in
  python/setup.py.in
  python/unittest_py/requirements.txt
  setup.py
Labels: contributor, status: proposed

#49513 Fix some en docs
  python/paddle/tensor/manipulation.py
  python/paddle/tensor/search.py
Labels: contributor, status: proposed

#49535 [XPU] fix clip op unit test.
  python/paddle/fluid/tests/unittests/xpu/test_clip_op_xpu.py
Labels: contributor, status: proposed

#49402 Add to_hash func and paddle2arg map for cinn
  paddle/fluid/framework/paddle2cinn/cinn_cache_key.cc
  paddle/fluid/operators/cinn/cinn_launch_context.cc
  paddle/fluid/operators/cinn/cinn_launch_context.h
  paddle/phi/core/ddim.cc
  paddle/phi/core/ddim.h
  paddle/phi/tests/core/test_ddim.cc
Labels: contributor, status: proposed

#39750 Fix throw exception typo in paddle/nn/functional/loss.py
  python/paddle/distributed/fleet/layers/mpu/mp_ops.py
  python/paddle/nn/functional/loss.py
Labels: contributor, PR is welcome

#49532 refix 40644 in english docs
  python/paddle/nn/layer/common.py
Labels: contributor, status: proposed

#49551 Expansions of some unmaintained pr
  paddle/fluid/platform/dynload/tensorrt.cc
  paddle/phi/backends/dynload/tensorrt.cc
  python/paddle/tensor/manipulation.py
Labels: contributor, status: proposed

#49522 [CodeStyle][UP005] replace deprecated unittest aliases
  python/paddle/fluid/tests/custom_op/test_check_abi.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/test_declarative.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/test_program_translator.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/test_spec_names.py
  python/paddle/fluid/tests/unittests/ir_memory_optimize_net_base.py
  python/paddle/fluid/tests/unittests/mlu/test_tril_triu_op_mlu.py
  python/paddle/fluid/tests/unittests/npu/test_tril_triu_op_npu.py
  python/paddle/fluid/tests/unittests/seresnext_test_base.py
  python/paddle/fluid/tests/unittests/test_base_layer.py
  python/paddle/fluid/tests/unittests/test_crypto.py
  python/paddle/fluid/tests/unittests/test_cyclic_cifar_dataset.py
  python/paddle/fluid/tests/unittests/test_dataset_dataloader.py
  python/paddle/fluid/tests/unittests/test_deprecated_memory_optimize_interfaces.py
  python/paddle/fluid/tests/unittests/test_detach.py
  python/paddle/fluid/tests/unittests/test_dist_tree_index.py
  python/paddle/fluid/tests/unittests/test_egr_python_api.py
  python/paddle/fluid/tests/unittests/test_fuse_all_reduce_pass.py
  python/paddle/fluid/tests/unittests/test_fuse_elewise_add_act_pass.py
  python/paddle/fluid/tests/unittests/test_fuse_optimizer_pass.py
  python/paddle/fluid/tests/unittests/test_fuse_relu_depthwise_conv_pass.py
  python/paddle/fluid/tests/unittests/test_global_var_getter_setter.py
  python/paddle/fluid/tests/unittests/test_imperative_data_loader_exception.py
  python/paddle/fluid/tests/unittests/test_inplace.py
  python/paddle/fluid/tests/unittests/test_io_save_load.py
  python/paddle/fluid/tests/unittests/test_optimizer_grad.py
  python/paddle/fluid/tests/unittests/test_parallel_executor_mnist.py
  python/paddle/fluid/tests/unittests/test_parallel_executor_pg.py
  python/paddle/fluid/tests/unittests/test_parallel_executor_seresnext_with_reduce_cpu.py
  python/paddle/fluid/tests/unittests/test_pylayer_op.py
  python/paddle/fluid/tests/unittests/test_scope.py
  python/paddle/fluid/tests/unittests/test_set_value_op.py
  python/paddle/fluid/tests/unittests/test_tril_triu_op.py
  python/paddle/fluid/tests/unittests/test_view_op_reuse_allocation.py
Labels: contributor, status: proposed

#49591 Dev
  paddle/phi/backends/xpu/xpu2_op_list.cc
  paddle/phi/kernels/xpu/bitwise.cc
Labels: contributor

#49619 [Dy2St] transforms.RandomResizedCrop Support static mode
  python/paddle/tests/test_transforms_static.py
  python/paddle/vision/transforms/transforms.py
Labels: contributor, status: proposed

#49590 [Dy2St] RandomHorizontalFlip
  python/paddle/tests/test_transforms_static.py
  python/paddle/vision/transforms/transforms.py
Labels: contributor, status: proposed

#49568 Unify the pass of the map class
  paddle/fluid/framework/ir/CMakeLists.txt
  paddle/fluid/framework/ir/inplace_op_var_pass.cc
  paddle/fluid/framework/ir/inplace_op_var_pass.h
  paddle/fluid/framework/ir/map_op_to_another_pass.cc
  paddle/fluid/framework/ir/map_op_to_another_pass.h
  paddle/fluid/inference/api/paddle_pass_builder.cc
Labels: contributor, status: proposed

#49465 add einsum fill diagonal and diagonal kernels
  paddle/phi/backends/xpu/xpu2_op_list.cc
  paddle/phi/kernels/xpu/diagonal_kernel.cc
  paddle/phi/kernels/xpu/einsum_grad_kernel.cc
  paddle/phi/kernels/xpu/einsum_kernel.cc
  paddle/phi/kernels/xpu/fill_diagonal_tensor_kernel.cc
  python/paddle/fluid/tests/unittests/xpu/test_diagonal_op_xpu.py
  python/paddle/fluid/tests/unittests/xpu/test_einsum_op_xpu.py
  python/paddle/fluid/tests/unittests/xpu/test_fill_diagonal_tensor_op_xpu.py
Labels: contributor

#49645 add fill/fill_any for kunlun
  paddle/phi/backends/xpu/xpu2_op_list.cc
  paddle/phi/kernels/xpu/fill_kernel.cc
  python/paddle/fluid/tests/unittests/xpu/test_fill_any_op_xpu.py
  python/paddle/fluid/tests/unittests/xpu/test_fill_op_xpu.py
Labels: contributor, status: proposed

#49617 [Dy2St] transforms.RandomErasing Support static mode
  python/paddle/tests/test_transforms_static.py
  python/paddle/vision/transforms/transforms.py
Labels: contributor, status: proposed

#49277 Rewrite batch norm act fuse pass tester
  paddle/fluid/framework/ir/CMakeLists.txt
  paddle/fluid/framework/ir/mkldnn/batch_norm_act_fuse_pass_tester.cc
  python/paddle/fluid/tests/unittests/ir/inference/CMakeLists.txt
  python/paddle/fluid/tests/unittests/ir/inference/test_onednn_batch_norm_act_fuse_pass.py
Labels: Intel, contributor

#49650 Update tensorrt version
  tools/dockerfile/ci_dockerfile.sh
Labels: contributor, status: proposed

#49543 [Infer UT] Fix unary operator expected error
  paddle/fluid/inference/tests/infer_ut/run.sh
Labels: contributor

#49240 Add mkldnn build option for inference CI
  paddle/scripts/paddle_build.sh
Labels: contributor, status: proposed

#49615 Add reduce_min prod trt converter
  paddle/fluid/inference/api/analysis_predictor.cc
  paddle/fluid/inference/tensorrt/convert/reduce_op.cc
  paddle/fluid/inference/tensorrt/op_teller.cc
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_reduce.py
Labels: contributor, status: proposed

#49624 fix repeat judgment conditions
  paddle/fluid/inference/analysis/passes/ir_params_sync_among_devices_pass.cc
Labels: contributor, status: proposed

#49668 [PHI Decoupling] move sequence_scale from fluid to phi
  paddle/fluid/operators/math/CMakeLists.txt
  paddle/phi/kernels/funcs/CMakeLists.txt
  paddle/phi/kernels/funcs/sequence_scale.cc
  paddle/phi/kernels/funcs/sequence_scale.cu
  paddle/phi/kernels/funcs/sequence_scale.h
  paddle/phi/kernels/impl/warpctc_grad_kernel_impl.h
  paddle/phi/kernels/impl/warpctc_kernel_impl.h
Labels: contributor, status: proposed

#49485 [Dy2St] Add ignore_module API
  python/paddle/fluid/tests/unittests/dygraph_to_static/test_ignore_module.py
  python/paddle/jit/__init__.py
  python/paddle/jit/api.py
  python/paddle/jit/dy2static/convert_call_func.py
Labels: contributor, status: proposed

#49681 [XPU] update xpu.cmake to 20230110
  cmake/external/xpu.cmake
Labels: contributor, status: proposed

#49628 [Dy2St] 移除 ProgramTranslator
  python/paddle/fluid/framework.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/test_assert.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/test_bert.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/test_bmn.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/test_break_continue.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/test_build_strategy.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/test_cache_program.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/test_convert_call.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/test_cycle_gan.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/test_declarative.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/test_dict.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/test_error.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/test_fetch_feed.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/test_for_enumerate.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/test_full_name_usage.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/test_grad.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/test_grid_generator.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/test_ifelse.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/test_isinstance.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/test_lac.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/test_logical.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/test_lstm.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/test_mobile_net.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/test_param_guard.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/test_partial_program.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/test_print.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/test_program_translator.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/test_ptb_lm.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/test_ptb_lm_v2.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/test_reinforcement_learning.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/test_resnet.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/test_resnet_amp.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/test_resnet_pure_fp16.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/test_resnet_v2.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/test_return.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/test_save_inference_model.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/test_save_load.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/test_se_resnet.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/test_sentiment.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/test_seq2seq.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/test_simnet.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/test_simnet_v2.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/test_slice.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/test_tensor_methods.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/test_tsm.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/test_word2vec.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/test_yolov3.py
  python/paddle/fluid/tests/unittests/test_base_layer.py
  python/paddle/fluid/tests/unittests/test_directory_migration.py
  python/paddle/fluid/tests/unittests/test_jit_layer.py
  python/paddle/jit/__init__.py
  python/paddle/jit/api.py
  python/paddle/jit/dy2static/__init__.py
  python/paddle/jit/dy2static/program_translator.py
  python/paddle/tests/test_model.py
Labels: contributor, status: proposed

#49720 fix paddle_infer_contrib inclue
  paddle/fluid/inference/api/paddle_infer_contrib.h
Labels: contributor, status: proposed

#49747 remove Travis CI build status badge from README
  README.md
  README_cn.md
  python/paddle/README.md
Labels: contributor, status: proposed

#49750 Fix the bugs of set_value and set_value_grad ops. test=kunlun
  paddle/phi/backends/xpu/xpu2_op_list.cc
  paddle/phi/kernels/xpu/set_value_grad_kernel.cc
  paddle/phi/kernels/xpu/set_value_kernel.cc
Labels: contributor

#49707 conv2d_fusion(cudnn or cutlass)
  paddle/fluid/framework/ir/conv2d_fusion_layout_transfer_pass.cc
Labels: contributor, status: proposed

#49749 Fix reduce func bug in process_group_bkcl
  paddle/fluid/distributed/collective/process_group_bkcl.cc
  paddle/fluid/pybind/process_group_utils.h
  python/paddle/fluid/tests/unittests/xpu/process_group_bkcl.py
Labels: contributor

#49672 add prelu & prelu_grad op for xpu
  paddle/phi/backends/xpu/xpu2_op_list.cc
  paddle/phi/kernels/xpu/prelu_grad_kernel.cc
  paddle/phi/kernels/xpu/prelu_kernel.cc
  python/paddle/fluid/tests/unittests/xpu/test_prelu_op_xpu.py
Labels: contributor, status: proposed

#49773 Add unitest for set_value, set_value_grad. test=kunlun
  paddle/phi/kernels/xpu/set_value_grad_kernel.cc
  paddle/phi/kernels/xpu/set_value_kernel.cc
  python/paddle/fluid/tests/unittests/xpu/test_set_value_op_xpu.py
Labels: contributor, status: proposed

#49760 fix xpu unittest issue
  paddle/phi/backends/xpu/xpu2_op_list.cc
  python/paddle/fluid/tests/unittests/xpu/test_zero_dim_tensor_xpu.py
Labels: contributor, status: proposed

#49757 kunlun add support for c_concat and c_split
  paddle/fluid/operators/collective/c_concat_op_xpu.cc
  paddle/fluid/operators/collective/c_split_op_xpu.cc
  paddle/phi/backends/xpu/xpu2_op_list.cc
  python/paddle/fluid/tests/unittests/xpu/collective_concat_op.py
  python/paddle/fluid/tests/unittests/xpu/collective_split_op.py
  python/paddle/fluid/tests/unittests/xpu/test_c_concat.py
  python/paddle/fluid/tests/unittests/xpu/test_c_split.py
Labels: contributor

#49816 add prod for kunlun
  paddle/phi/backends/xpu/xpu2_op_list.cc
  python/paddle/fluid/tests/unittests/xpu/test_prod_op_xpu.py
Labels: contributor, status: proposed

#49539 CUDA12.0 integration
  cmake/external/warpctc.cmake
  paddle/fluid/platform/device/gpu/cuda/cuda_profiler.cc
  paddle/phi/kernels/funcs/sparse/sparse_blas_impl.cu.h
  paddle/phi/kernels/gpu/send_u_recv_kernel.cu
  paddle/phi/kernels/gpu/send_ue_recv_kernel.cu
  paddle/phi/kernels/gpu/unique_kernel.cu
  paddle/phi/kernels/sparse/gpu/coalesce_kernel.cu
Labels: NVIDIA, contributor

#48227 Update README.md
  README.md
Labels: contributor, status: proposed

#49580 Rewrite mat reshape transpose testers
  paddle/fluid/framework/ir/CMakeLists.txt
  paddle/fluid/framework/ir/mkldnn/matmul_transpose_reshape_mkldnn_fuse_pass_tester.cc
  paddle/fluid/framework/ir/mkldnn/reshape_transpose_matmul_mkldnn_fuse_pass_tester.cc
  python/paddle/fluid/tests/unittests/ir/inference/CMakeLists.txt
  python/paddle/fluid/tests/unittests/ir/inference/test_onednn_matmul_transpose_reshape_fuse_pass.py
  python/paddle/fluid/tests/unittests/ir/inference/test_onednn_reshape_transpose_matmul_fuse_pass.py
Labels: Intel, contributor

#49806 use default XPU stream for computing
  paddle/fluid/distributed/collective/process_group_bkcl.cc
  paddle/fluid/platform/device_context.h
  paddle/phi/backends/xpu/xpu_context.cc
  paddle/phi/backends/xpu/xpu_context.h
Labels: contributor

#49896 kunlun support p2p send/recv
  paddle/fluid/distributed/collective/process_group_bkcl.cc
  paddle/fluid/distributed/collective/process_group_bkcl.h
  python/paddle/fluid/tests/unittests/xpu/process_group_bkcl.py
Labels: contributor

#49911 [XPU] add logical_not op.
  paddle/phi/backends/xpu/xpu2_op_list.cc
  paddle/phi/kernels/xpu/logical_kernel.cc
  python/paddle/fluid/tests/unittests/xpu/get_test_cover_info.py
  python/paddle/fluid/tests/unittests/xpu/test_logical_op_xpu.py
Labels: contributor, status: proposed

#49824 Handle repetitive code in oneDNN activation fuse passes
  paddle/fluid/framework/ir/mkldnn/activation_onednn_fuse_pass.h
  paddle/fluid/framework/ir/mkldnn/conv_activation_mkldnn_fuse_pass.cc
  paddle/fluid/framework/ir/mkldnn/elt_act_mkldnn_fuse_pass.cc
  paddle/fluid/framework/ir/mkldnn/fc_act_mkldnn_fuse_pass.cc
  paddle/fluid/framework/ir/mkldnn/matmul_activation_mkldnn_fuse_pass.cc
  paddle/fluid/framework/ir/mkldnn/softplus_activation_mkldnn_fuse_pass.cc
  paddle/phi/backends/onednn/onednn_reuse.h
Labels: Intel, contributor, status: not progressed

#49505 [KUNLUN] add op: maxpool_with_index
  paddle/fluid/imperative/amp_auto_cast.cc
  paddle/phi/backends/xpu/xpu2_op_list.cc
  paddle/phi/kernels/xpu/pool_grad_kernel.cc
  paddle/phi/kernels/xpu/pool_kernel.cc
  python/paddle/amp/auto_cast.py
  python/paddle/fluid/tests/unittests/xpu/test_pool_max_op.py
Labels: contributor

#49941 [KUNLUN] update xccl lib & use native Reduce in dygraph
  cmake/external/xpu.cmake
  paddle/fluid/distributed/collective/process_group_bkcl.cc
Labels: contributor

#48593 Fix for bad_alloc in oneDNN matmul_grad kernel
  paddle/phi/kernels/onednn/matmul_grad_kernel.cc
Labels: Intel, contributor, status: not progressed

#49960 [XPU] add xpu version info into version.show()
  cmake/external/xpu.cmake
  python/setup.py.in
  setup.py
Labels: contributor, status: proposed

#50058 depthwise_conv 映射成 conv的逻辑中添加下cudnn版本的判断
  paddle/fluid/framework/ir/map_op_to_another_pass.cc
Labels: contributor, status: proposed

#49961 [Fix deprecation warning in test] bool => bool_
  python/paddle/fluid/tests/unittests/ipu/test_flip_op_ipu.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_compare_and_logical.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_fill_any_like.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_one_hot.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_unary.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_where.py
  python/paddle/fluid/tests/unittests/npu/test_assign_value_op_npu.py
  python/paddle/fluid/tests/unittests/test_assign_value_op.py
  python/paddle/fluid/tests/unittests/test_fused_multi_transformer_int8_op.py
  python/paddle/fluid/tests/unittests/test_fused_multi_transformer_op.py
  python/paddle/fluid/tests/unittests/test_update_loss_scaling_op.py
  python/paddle/fluid/tests/unittests/xpu/test_assign_value_op_xpu.py
  python/paddle/fluid/tests/unittests/xpu/test_bitwise_op_xpu.py
  python/paddle/fluid/tests/unittests/xpu/test_logical_op_xpu.py
Labels: contributor, status: proposed

#49885 [PHI]add phi tensor vector array api from fluid
  paddle/fluid/framework/tensor_util.h
  paddle/phi/core/tensor_utils.cc
  paddle/phi/core/tensor_utils.h
  paddle/phi/kernels/assign_kernel.cc
  paddle/phi/kernels/cpu/adam_kernel.cc
  paddle/phi/kernels/cpu/adamw_kernel.cc
  paddle/phi/kernels/cpu/cross_grad_kernel.cc
  paddle/phi/kernels/cpu/cross_kernel.cc
  paddle/phi/kernels/cpu/index_sample_grad_kernel.cc
  paddle/phi/kernels/cpu/index_sample_kernel.cc
  paddle/phi/kernels/cpu/repeat_interleave_grad_kernel.cc
  paddle/phi/kernels/cpu/roll_grad_kernel.cc
  paddle/phi/kernels/cpu/roll_kernel.cc
  paddle/phi/kernels/cpu/unique_consecutive_functor.h
  paddle/phi/kernels/funcs/repeat_tensor2index_tensor.h
  paddle/phi/kernels/funcs/unique_functor.h
  paddle/phi/kernels/gpu/adam_kernel.cu
  paddle/phi/kernels/gpu/adamw_kernel.cu
  paddle/phi/kernels/gpu/class_center_sample_kernel.cu
  paddle/phi/kernels/gpu/diagonal_grad_kernel.cu
  paddle/phi/kernels/gpu/diagonal_kernel.cu
  paddle/phi/kernels/gpu/margin_cross_entropy_grad_kernel.cu
  paddle/phi/kernels/gpu/margin_cross_entropy_kernel.cu
  paddle/phi/kernels/gpu/prior_box_kernel.cu
  paddle/phi/kernels/gpu/unique_consecutive_functor.h
  paddle/phi/kernels/gpu/unique_kernel.cu
  paddle/phi/kernels/impl/determinant_kernel_impl.h
  paddle/phi/kernels/impl/repeat_interleave_grad_kernel_impl.h
  paddle/phi/kernels/impl/repeat_interleave_kernel_impl.h
  paddle/phi/kernels/impl/set_value_kernel_impl.h
  paddle/phi/kernels/impl/slogdeterminant_kernel_impl.h
  paddle/phi/kernels/selected_rows/cpu/adam_kernel.cc
  paddle/phi/kernels/selected_rows/cpu/adamw_kernel.cc
  paddle/phi/kernels/selected_rows/gpu/adam_kernel.cu
  paddle/phi/kernels/selected_rows/gpu/adamw_kernel.cu
  paddle/phi/kernels/selected_rows/xpu/adam_kernel.cc
  paddle/phi/kernels/xpu/adam_kernel.cc
  paddle/phi/kernels/xpu/adamw_kernel.cc
  paddle/phi/kernels/xpu/set_value_kernel.cc
Labels: contributor, status: proposed

#49951 [Divide by 0 Error] add pinv check
  paddle/phi/kernels/cpu/svd_kernel.cc
  paddle/phi/kernels/gpu/svd_kernel.cu
  python/paddle/fluid/tests/unittests/test_linalg_pinv_op.py
Labels: contributor, status: proposed

#49943 [Fix IndexError] add unstack axis check
  python/paddle/fluid/tests/unittests/test_unstack_op.py
  python/paddle/tensor/manipulation.py
Labels: contributor, status: proposed

#49962 fix the div 0 error of deform_conv2d
  python/paddle/fluid/tests/unittests/test_deformable_conv_op.py
  python/paddle/static/nn/common.py
Labels: contributor, status: proposed

#49976 Fix 空指针 (Null pointer) of case 2 paddle.linalg.lu_unpack
  paddle/phi/kernels/impl/lu_kernel_impl.h
  paddle/phi/kernels/impl/lu_unpack_kernel_impl.h
  python/paddle/fluid/tests/unittests/test_lu_unpack_op.py
Labels: contributor, status: proposed

#49988 Fix Python IndexError of case7: paddle.static.nn.spectral_norm
  python/paddle/fluid/tests/unittests/test_spectral_norm_op.py
  python/paddle/static/nn/common.py
Labels: contributor, status: proposed

#49975 [Fix deprecation warning in test]np.unicode_ => np.str_
  python/paddle/fluid/tests/unittests/test_egr_string_tensor_api.py
Labels: contributor

#49967 modify np.int with np.int64
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_one_hot.py
Labels: contributor, status: proposed

#49993 Fix UFA非法地址访问(UFA illegal address access) of case1: paddle.vision.ops.nms
  paddle/phi/kernels/cpu/nms_kernel.cc
  paddle/phi/kernels/gpu/nms_kernel.cu
Labels: contributor, status: proposed

#49996 fix the div 0 error of pixel_shuffle
  paddle/phi/infermeta/unary.cc
  python/paddle/fluid/tests/unittests/test_pixel_shuffle.py
Labels: contributor, status: proposed

#49982 Fix 堆栈溢出 (stack overflow) of case9: paddle.repeat_interleave
  paddle/phi/infermeta/unary.cc
  python/paddle/fluid/tests/unittests/test_repeat_interleave_op.py
Labels: contributor, status: proposed

#49942 Fix the div 0 error of matrix_power
  paddle/phi/infermeta/unary.cc
  python/paddle/fluid/tests/unittests/test_matrix_power_op.py
Labels: contributor, status: proposed

#49965 fix the div 0 errors in psroi_pool
  python/paddle/fluid/tests/unittests/test_psroi_pool_op.py
  python/paddle/vision/ops.py
Labels: contributor, status: proposed

#49973 Fix 空指针 (Null pointer) of case 14 paddle.atan2
  paddle/phi/infermeta/binary.cc
  paddle/phi/kernels/impl/atan2_kernel_impl.h
  python/paddle/fluid/tests/unittests/test_atan2_op.py
Labels: contributor, status: proposed

#49981 Fix 堆栈溢出 (stack overflow) of case10: paddle.unique
  paddle/phi/infermeta/unary.cc
  python/paddle/fluid/tests/unittests/test_unique.py
Labels: contributor, status: proposed

#49992 Fix Python IndexError of case17: paddle.nn.functional.interpolate
  python/paddle/fluid/tests/unittests/test_bicubic_interp_op.py
  python/paddle/fluid/tests/unittests/test_bicubic_interp_v2_op.py
  python/paddle/nn/functional/common.py
Labels: contributor, status: proposed

#50000 fix div 0 error in conv1_transpose
  paddle/phi/kernels/funcs/concat_and_split_functor.cc
  python/paddle/fluid/tests/unittests/test_functional_conv1d_transpose.py
Labels: contributor, status: proposed

#50005 fix the indexerror of conv2d_transpose
  python/paddle/fluid/tests/unittests/test_conv2d_transpose_op.py
  python/paddle/static/nn/common.py
Labels: contributor, status: proposed

#50011 Fix Python IndexError of case13: paddle.static.nn.batch_norm
  python/paddle/fluid/tests/unittests/test_batch_norm_op.py
  python/paddle/fluid/tests/unittests/test_fold_op.py
  python/paddle/static/nn/common.py
Labels: contributor

#50017 fix the NullPointerError of median
  python/paddle/fluid/tests/unittests/test_median.py
  python/paddle/tensor/stat.py
Labels: contributor, status: proposed

#49970 [Fix deprecation warning in test] np.float => np.float64
  python/paddle/optimizer/lr.py
Labels: contributor, status: proposed

#50049 Add unitest for set_value_grad. test=kunlun
  python/paddle/fluid/tests/unittests/xpu/test_set_value_op_xpu.py
Labels: contributor

#49997 fix div 0 error in floormod
  paddle/phi/kernels/funcs/elementwise_functor.h
  python/paddle/fluid/tests/unittests/test_elementwise_floormod_op.py
Labels: contributor, status: proposed

#49980 Fix 空指针 (Null pointer) of case15: paddle.broadcast_tensors
  paddle/phi/infermeta/multiary.cc
  python/paddle/fluid/tests/unittests/test_broadcast_tensors_op.py
Labels: contributor

#49945 [KUNLUN] rename test_pool_max_op.py
  cmake/external/xpu.cmake
  python/paddle/fluid/tests/unittests/xpu/test_pool_max_op_xpu.py
Labels: contributor

#49953 fix div 0 error of NoamDecay
  python/paddle/fluid/tests/unittests/test_noamdecay_op.py
  python/paddle/optimizer/lr.py
Labels: contributor, status: proposed

#50002 [Numpy] Add FP16 dtype for CastNumpy2Scalar
  paddle/fluid/pybind/eager_utils.cc
  paddle/fluid/pybind/op_function_common.cc
  paddle/fluid/pybind/op_function_common.h
  python/paddle/fluid/tests/unittests/test_elementwise_add_op.py
  python/paddle/fluid/transpiler/collective.py
Labels: contributor, status: proposed

#50090 bind pixel_shuffle & pixel_shuffle_grad op for xpu
  paddle/phi/backends/xpu/xpu2_op_list.cc
  paddle/phi/kernels/xpu/pixel_shuffle_grad_kernel.cc
  paddle/phi/kernels/xpu/pixel_shuffle_kernel.cc
  python/paddle/fluid/tests/unittests/xpu/test_pixel_shuffle_op_xpu.py
Labels: contributor, status: proposed
