Repository PaddlePaddle/Paddle, pull requests merged in 2023-10, with the labels that each got.

#57834 [tests] fix `test_egr_performance_benchmark_eager_cuda` build error
  test/cpp/eager/performance_tests/CMakeLists.txt
Labels: contributor

#57860 [CodeStyle] clean some `#noqa: F401` step: 1
  python/paddle/amp/__init__.py
  python/paddle/audio/backends/__init__.py
  python/paddle/audio/features/__init__.py
  python/paddle/audio/functional/__init__.py
  python/paddle/autograd/__init__.py
  python/paddle/base/reader.py
  python/paddle/callbacks.py
  python/paddle/cost_model/__init__.py
  python/paddle/dataset/__init__.py
  python/paddle/decomposition/primitives.py
  python/paddle/device/__init__.py
  python/paddle/device/cuda/__init__.py
  python/paddle/distributed/__init__.py
  python/paddle/distributed/auto_parallel/static/dist_attribute.py
  python/paddle/distributed/auto_parallel/static/reshard.py
  python/paddle/distributed/collective.py
  python/paddle/distributed/fleet/__init__.py
  python/paddle/distributed/parallel.py
  python/paddle/hub.py
  python/paddle/linalg.py
Labels: contributor, HappyOpenSource

#57658 [Docathon] Fix NO.13-NO.18 API label
  python/paddle/base/dygraph/base.py
  python/paddle/base/framework.py
  python/paddle/distributed/fleet/fleet.py
  python/paddle/incubate/optimizer/lookahead.py
  python/paddle/incubate/optimizer/modelaverage.py
  python/paddle/nn/clip.py
  python/paddle/optimizer/optimizer.py
Labels: contributor, HappyOpenSource

#57839 [CodeStyle][task 39] enable isort in `python/paddle/base/framework.py`(part3)
  pyproject.toml
  python/paddle/__init__.py
  python/paddle/base/__init__.py
  python/paddle/base/framework.py
  python/paddle/pir/__init__.py
  test/dygraph_to_static/test_origin_info.py
Labels: contributor, HappyOpenSource

#57864 [CodeStyle][task 8] enable Ruff C408 rule in python/paddle/base
  pyproject.toml
  python/paddle/base/backward.py
  python/paddle/base/default_scope_funcs.py
  python/paddle/base/executor.py
  python/paddle/base/framework.py
  python/paddle/base/layers/layer_function_generator.py
Labels: contributor, HappyOpenSource

#57876 [CodeStyle][task 33] enable Ruff PLC0414 rule in `python/paddle/base`
  pyproject.toml
  python/paddle/base/backward.py
Labels: contributor, HappyOpenSource

#57941 [codestyle][ruff] enable `PGH004`
  pyproject.toml
  python/paddle/distributed/fleet/utils/__init__.py
  python/paddle/distribution/__init__.py
  python/paddle/distribution/transform.py
  python/paddle/incubate/asp/__init__.py
  python/paddle/incubate/autograd/__init__.py
  python/paddle/incubate/nn/__init__.py
  python/paddle/inference/__init__.py
  python/paddle/io/__init__.py
  python/paddle/jit/__init__.py
  python/paddle/metric/__init__.py
  python/paddle/nn/__init__.py
  python/paddle/nn/functional/__init__.py
  python/paddle/nn/initializer/__init__.py
  python/paddle/nn/layer/layers.py
  python/paddle/nn/utils/__init__.py
  python/paddle/optimizer/__init__.py
  python/paddle/optimizer/lr.py
  python/paddle/static/__init__.py
  python/paddle/static/nn/__init__.py
  python/paddle/tensor/__init__.py
  python/paddle/text/__init__.py
  python/paddle/utils/__init__.py
  python/paddle/utils/cpp_extension/__init__.py
  python/paddle/utils/unique_name.py
  python/paddle/vision/__init__.py
  python/paddle/vision/datasets/__init__.py
  python/paddle/vision/models/__init__.py
  python/paddle/vision/ops.py
  python/paddle/vision/transforms/__init__.py
  test/autograd/test_autograd_functional_dynamic.py
Labels: contributor

#57819 Fix 55358
  python/paddle/base/data_feeder.py
  python/paddle/base/executor.py
  python/paddle/incubate/autograd/primapi.py
Labels: NVIDIA, contributor

#57806 [Fix] fix float patch as string beginning
  tools/sampcd_processor.py
  tools/test_sampcd_processor.py
Labels: contributor

#57868 [clang-tidy] clang-tidy script to repeat
  tools/codestyle/clang-tidy.py
Labels: contributor, HappyOpenSource Pro

#57591 [xdoctest][task 232-235] reformat example code with google style in `python/paddle/distributed/*`
  python/paddle/distributed/rpc/rpc.py
  python/paddle/distributed/sharding/group_sharded.py
  python/paddle/distributed/spawn.py
  python/paddle/distributed/transpiler/distribute_transpiler.py
Labels: contributor, HappyOpenSource Pro

#57865 【Hackathon 5th No.102】 move fused_embedding_eltwise_layernorm/fusion_transpose_flatten_concat/fused_fc_elementwise_layernorm to phi
  paddle/fluid/operators/fused/CMakeLists.txt
  paddle/fluid/operators/fused/fused_embedding_eltwise_layernorm_op.cc
  paddle/fluid/operators/fused/fused_embedding_eltwise_layernorm_op.cu
  paddle/fluid/operators/fused/fused_fc_elementwise_layernorm_op.cc
  paddle/fluid/operators/fused/fusion_transpose_flatten_concat_op.cc
  paddle/fluid/operators/fused/fusion_transpose_flatten_concat_op.cu.cc
  paddle/fluid/operators/fused/fusion_transpose_flatten_concat_op.h
  paddle/fluid/operators/math/bert_encoder_functor.cu
  paddle/fluid/operators/math/bert_encoder_functor.h
  paddle/phi/api/yaml/fused_ops.yaml
  paddle/phi/api/yaml/op_compat.yaml
  paddle/phi/infermeta/fusion.cc
  paddle/phi/infermeta/fusion.h
  paddle/phi/kernels/funcs/common_shape.h
  paddle/phi/kernels/funcs/emb_eltwise_layer_norm_functor.cu
  paddle/phi/kernels/funcs/emb_eltwise_layer_norm_functor.h
  paddle/phi/kernels/fusion/gpu/fused_embedding_eltwise_layernorm_kernel.cu
  paddle/phi/kernels/fusion/gpu/fused_fc_elementwise_layernorm_kernel.cu
  paddle/phi/kernels/fusion/gpu/fusion_transpose_flatten_concat_kernel.cu
  test/legacy_test/test_fusion_transpose_flatten_concat_op.py
Labels: PaddlePaddle Hackathon, contributor

#57857 [Hackathon 5th No.49] add opResult Tensor Methods - Part 1
  python/paddle/__init__.py
  python/paddle/pir/__init__.py
  python/paddle/pir/math_op_patch.py
  test/legacy_test/test_math_op_patch_pir.py
  test/legacy_test/test_math_op_patch_var_base.py
Labels: PaddlePaddle Hackathon, contributor

#57982 [CodeStyle][ruff] format `python/paddle/framework/__init__.py`
  python/paddle/framework/__init__.py
Labels: contributor, HappyOpenSource

#57984 [Change] xdoctest version
  python/unittest_py/requirements.txt
Labels: contributor

#57990 [PIR] Migrate paddle.dot into pir
  python/paddle/tensor/linalg.py
  test/legacy_test/test_dot_op.py
Labels: contributor

#57985 [pir] rename opResult Tensor Methods test
  test/legacy_test/test_math_op_patch_pir.py
Labels: contributor

#57970 [CodeStyle][ruff] clean some `F401` step: 2
  python/paddle/base/layers/__init__.py
  python/paddle/distributed/fleet/dataset/__init__.py
  python/paddle/distributed/fleet/meta_parallel/__init__.py
  python/paddle/distributed/fleet/meta_parallel/parallel_layers/__init__.py
  python/paddle/distributed/fleet/meta_parallel/parallel_layers/mp_layers.py
  python/paddle/distributed/fleet/meta_parallel/parallel_layers/random.py
  python/paddle/distributed/fleet/metrics/__init__.py
  python/paddle/distributed/fleet/utils/__init__.py
  python/paddle/distributed/metric/__init__.py
  python/paddle/distributed/sharding/__init__.py
  python/paddle/geometric/__init__.py
  python/paddle/geometric/message_passing/__init__.py
  python/paddle/geometric/sampling/__init__.py
  python/paddle/hapi/__init__.py
  python/paddle/incubate/__init__.py
  python/paddle/incubate/asp/__init__.py
  python/paddle/incubate/autograd/primitives.py
  python/paddle/incubate/distributed/fleet/parameter_server/pslib/__init__.py
  python/paddle/incubate/multiprocessing/__init__.py
  python/paddle/incubate/nn/__init__.py
  python/paddle/incubate/operators/__init__.py
  python/paddle/incubate/optimizer/__init__.py
  python/paddle/incubate/optimizer/functional/__init__.py
  python/paddle/io/__init__.py
  python/paddle/jit/dy2static/__init__.py
  python/paddle/jit/dy2static/utils.py
  python/paddle/jit/dy2static/utils_helper.py
  python/paddle/metric/__init__.py
Labels: contributor, HappyOpenSource

#57859 [fix] fix ambiguity of k in Geometric distribution
  python/paddle/distribution/geometric.py
  test/distribution/test_distribution_geometric.py
  test/distribution/test_distribution_geometric_static.py
Labels: contributor

#57989 [fix ]fix sample code in `paddle.utils.require_version`
  python/paddle/base/framework.py
Labels: contributor, HappyOpenSource

#57861 [clang-tidy] NO.9 enable `bugprone-narrowing-conversions`
  .clang-tidy
  paddle/fluid/distributed/auto_parallel/spmd_rules/cross_entropy_with_softmax_spmd_rule.cc
  paddle/fluid/eager/custom_operator/custom_operator_node.cc
  paddle/fluid/framework/new_executor/interpreter/interpreter_util.cc
  paddle/fluid/framework/new_executor/new_ir_interpreter.cc
  paddle/fluid/inference/utils/io_utils.cc
  paddle/fluid/inference/utils/table_printer.cc
  paddle/fluid/ir_adaptor/translator/program_translator.cc
  paddle/fluid/operators/controlflow/pylayer_op_helper.cc
  paddle/fluid/pir/dialect/operator/ir/op_attribute.cc
  paddle/fluid/pir/dialect/operator/ir/op_dialect.cc
  paddle/fluid/pir/transforms/pd_op_to_kernel_pass.cc
  paddle/fluid/pybind/auto_parallel_py.cc
  paddle/phi/core/distributed/auto_parallel/nd_mesh_reshard_function.cc
  paddle/phi/core/distributed/auto_parallel/s_to_s_reshard_function.cc
  paddle/phi/infermeta/fusion.cc
  paddle/pir/core/parser/ir_parser.cc
  paddle/pir/core/parser/lexer.cc
  paddle/pir/dialect/shape/utils/shape_utils.cc
  test/cpp/pir/core/ir_parser_test.cc
Labels: contributor, HappyOpenSource Pro

#57565 [xdoctest] reformat example code with google style in No.324, 333, 336, 353
  paddle/fluid/pybind/eager_method.cc
  paddle/fluid/pybind/parallel_executor.cc
  python/paddle/base/dygraph/base.py
  python/paddle/base/executor.py
Labels: contributor, HappyOpenSource Pro

#57809 [clang-tidy] NO.17 performance-for-range-copy
  .clang-tidy
  paddle/fluid/distributed/auto_parallel/dist_attr.cc
  paddle/fluid/distributed/fleet_executor/carrier.cc
  paddle/fluid/distributed/fleet_executor/compute_interceptor.cc
  paddle/fluid/distributed/fleet_executor/dist_model.cc
  paddle/fluid/distributed/fleet_executor/fleet_executor.cc
  paddle/fluid/eager/auto_code_generator/eager_generator.cc
  paddle/fluid/eager/backward.cc
  paddle/fluid/eager/custom_operator/custom_operator_node.cc
  paddle/fluid/framework/data_set.cc
  paddle/fluid/framework/downpour_worker.cc
  paddle/fluid/framework/downpour_worker_opt.cc
  paddle/fluid/framework/hogwild_worker.cc
  paddle/fluid/framework/ir/add_support_int8_pass.cc
  paddle/fluid/framework/ir/coalesce_grad_tensor_pass.cc
  paddle/fluid/framework/ir/constant_folding_pass.cc
  paddle/fluid/framework/ir/delete_cast_op_pass.cc
  paddle/fluid/framework/ir/delete_repeated_ops_pass.cc
  paddle/fluid/framework/ir/fuse_gemm_epilogue_pass.cc
  paddle/fluid/framework/ir/fuse_optimizer_ops_pass/fuse_optimizer_op_pass.cc
  paddle/fluid/framework/ir/fusion_group/code_generator.cc
  paddle/fluid/framework/ir/fusion_group/operation.cc
  paddle/fluid/framework/ir/generate_pass.cc
  paddle/fluid/framework/ir/graph_helper.cc
  paddle/fluid/framework/ir/inplace_op_var_pass.cc
  paddle/fluid/framework/ir/memory_optimize_pass/eager_deletion_pass.cc
  paddle/fluid/framework/ir/mkldnn/compute_propagate_scales_mkldnn_pass.cc
  paddle/fluid/framework/ir/mkldnn/cpu_quantize_pass.cc
  paddle/fluid/framework/ir/mkldnn/cpu_quantize_squash_pass.cc
  paddle/fluid/framework/ir/mkldnn/fc_act_mkldnn_fuse_pass.cc
  paddle/fluid/framework/ir/mkldnn/quant_dequant_mkldnn_pass.cc
  paddle/fluid/framework/ir/multi_batch_merge_pass.cc
  paddle/fluid/framework/ir/multi_devices_graph_pass/fuse_all_reduce_op_pass.cc
  paddle/fluid/framework/ir/multi_devices_graph_pass/multi_devices_graph_pass.cc
  paddle/fluid/framework/ir/squared_mat_sub_fuse_pass.cc
  paddle/fluid/framework/new_executor/interpreter/dependency_builder.cc
  paddle/fluid/framework/program_utils.cc
  paddle/fluid/framework/pull_dense_worker.cc
  paddle/fluid/inference/api/analysis_config.cc
  paddle/fluid/inference/api/analysis_predictor.cc
  paddle/fluid/inference/api/mkldnn_quantizer.cc
  paddle/fluid/ir_adaptor/translator/op_translator.cc
  paddle/fluid/jit/property.cc
  paddle/fluid/memory/allocation/mmap_allocator.cc
  paddle/fluid/operators/fused/fused_elemwise_activation_op.cc
  paddle/fluid/operators/prim_ops/split_p_op.cc
  paddle/fluid/platform/gen_comm_id_helper.cc
  paddle/fluid/platform/profiler/custom_device/custom_tracer.cc
  paddle/fluid/pybind/inference_api.cc
  paddle/fluid/pybind/pybind.cc
  paddle/phi/backends/device_manager.cc
  paddle/phi/backends/dynload/dynamic_loader.cc
  paddle/phi/backends/gpu/gpu_info.cc
  paddle/phi/core/kernel_factory.cc
  paddle/phi/core/tensor_array.cc
  paddle/phi/kernels/funcs/jit/benchmark.cc
  paddle/phi/kernels/funcs/tensor_formatter.cc
  paddle/pir/core/ir_context.cc
Labels: contributor, HappyOpenSource Pro

#57973 [fix] add `name` for `example_code` in ` paddle/incubate/amp/amp.py`
  python/paddle/incubate/asp/asp.py
Labels: contributor, HappyOpenSource

#58028 [clang-tidy] No.24 fix some `performance-inefficient-vector-operation` part:1
  paddle/fluid/distributed/collective/reducer.cc
  paddle/fluid/distributed/fleet_executor/carrier.cc
  paddle/fluid/framework/details/parallel_ssa_graph_executor.cc
  paddle/fluid/framework/ir/delete_cast_op_pass_test.cc
  paddle/fluid/framework/ir/fuse_adamw_op_pass.cc
  paddle/fluid/framework/ir/fuse_gemm_epilogue_pass.cc
  paddle/fluid/framework/ir/fuse_optimizer_ops_pass/fuse_optimizer_op_pass.cc
  paddle/fluid/framework/ir/graph_helper.cc
  paddle/fluid/framework/ir/memory_optimize_pass/test_reference_count_pass_last_lived_ops.cc
  paddle/fluid/framework/ir/multi_batch_merge_pass.cc
  paddle/fluid/framework/ir/multi_devices_graph_pass/multi_devices_graph_pass.cc
  paddle/fluid/framework/ir/subgraph_detector.cc
  paddle/fluid/framework/ir/transfer_layout_elim_pass.cc
  paddle/fluid/framework/ir/transpose_flatten_concat_fuse_pass.cc
  paddle/fluid/framework/ir/trt_delete_weight_dequant_linear_op_pass.cc
Labels: contributor, HappyOpenSource Pro

#57787 [xdoctest][task 226-230] reformat example code with google style in `python/paddle/distributed/fleet/*`
  python/paddle/distributed/fleet/recompute/recompute.py
  python/paddle/distributed/fleet/utils/__init__.py
  python/paddle/distributed/fleet/utils/fs.py
  python/paddle/distributed/fleet/utils/hybrid_parallel_inference.py
  python/paddle/distributed/parallel.py
Labels: contributor, HappyOpenSource Pro

#57683 add xpu3_op_list
  paddle/fluid/platform/device/xpu/xpu_op_list.cc
  paddle/fluid/pybind/place.cc
  paddle/phi/backends/CMakeLists.txt
  paddle/phi/backends/xpu/xpu3_op_list.cc
  paddle/phi/backends/xpu/xpu_info.cc
  paddle/phi/backends/xpu/xpu_info.h
  paddle/phi/backends/xpu/xpu_op_list.h
Labels: contributor

#57627 [clang-tidy] NO.19 performance-move-const-arg
  .clang-tidy
  paddle/fluid/distributed/collective/reducer.cc
  paddle/fluid/eager/backward.cc
  paddle/fluid/framework/custom_operator.cc
  paddle/fluid/framework/data_feed.cc
  paddle/fluid/framework/data_set.cc
  paddle/fluid/framework/details/async_ssa_graph_executor.cc
  paddle/fluid/framework/details/fetch_op_handle.cc
  paddle/fluid/framework/details/parallel_ssa_graph_executor.cc
  paddle/fluid/framework/details/scope_buffered_ssa_graph_executor.cc
  paddle/fluid/framework/infershape_utils.cc
  paddle/fluid/framework/ir/fuse_bn_act_pass.cc
  paddle/fluid/framework/ir/fuse_bn_add_act_pass.cc
  paddle/fluid/framework/ir/fuse_elewise_add_act_pass.cc
  paddle/fluid/framework/ir/memory_optimize_pass/eager_deletion_pass.cc
  paddle/fluid/framework/new_executor/interpreter/interpreter_util.cc
  paddle/fluid/framework/new_executor/program_interpreter.cc
  paddle/fluid/framework/op_desc.cc
  paddle/fluid/framework/operator.cc
  paddle/fluid/imperative/basic_engine.cc
  paddle/fluid/imperative/jit/program_desc_tracer.cc
  paddle/fluid/imperative/layer.cc
  paddle/fluid/imperative/partial_grad_engine.cc
  paddle/fluid/imperative/reducer.cc
  paddle/fluid/imperative/tracer.cc
  paddle/fluid/inference/api/mkldnn_quantizer.cc
  paddle/fluid/memory/allocation/stream_safe_cuda_allocator.cc
  paddle/fluid/operators/split_op.cc
  paddle/fluid/operators/string/faster_tokenizer_op.cc
  paddle/fluid/prim/api/manual_prim/utils/static_utils.cc
  paddle/fluid/pybind/bind_fleet_executor.cc
  paddle/fluid/pybind/data_set_py.cc
  paddle/fluid/pybind/eager_functions.cc
  paddle/fluid/pybind/eager_utils.cc
  paddle/fluid/pybind/imperative.cc
  paddle/fluid/pybind/inference_api.cc
  paddle/phi/api/lib/op_meta_info.cc
  paddle/phi/api/lib/tensor.cc
  paddle/phi/backends/gpu/gpu_context.cc
  paddle/phi/core/infermeta_utils.cc
  paddle/phi/infermeta/binary.cc
  paddle/pir/core/ir_context.cc
Labels: contributor, HappyOpenSource Pro

#57540 [complex] No.31 add complex support for softplus
  paddle/phi/kernels/cpu/activation_grad_kernel.cc
  paddle/phi/kernels/cpu/activation_kernel.cc
  paddle/phi/kernels/funcs/activation_functor.h
  paddle/phi/kernels/gpu/activation_grad_kernel.cu
  paddle/phi/kernels/gpu/activation_kernel.cu
  python/paddle/nn/functional/activation.py
  test/legacy_test/test_activation_op.py
Labels: contributor, HappyOpenSource Pro

#57826 fix_dpsgd_test
  paddle/fluid/pir/dialect/op_generator/ops_api_gen.py
  paddle/fluid/pir/dialect/operator/ir/ops.yaml
  paddle/fluid/pir/dialect/operator/utils/utils.cc
  paddle/phi/api/yaml/op_compat.yaml
  paddle/phi/infermeta/ternary.cc
  paddle/phi/infermeta/ternary.h
  test/white_list/new_ir_op_test_white_list
Labels: contributor

#58046 [fix] fix name for example_code in paddle/incubate/asp/asp.py
  python/paddle/incubate/asp/asp.py
Labels: contributor, HappyOpenSource

#57724 【Hackathon 5 No.21】Add LinearLR to Paddle
  python/paddle/optimizer/lr.py
  test/legacy_test/test_lr_scheduler.py
Labels: PaddlePaddle Hackathon, contributor

#58058 complete the xpu3_op_list
  paddle/phi/backends/xpu/xpu3_op_list.cc
Labels: contributor

#57969 fix parser
  paddle/pir/core/parser/ir_parser.cc
  paddle/pir/core/parser/lexer.cc
  test/cpp/pir/core/TestParserText.txt
Labels: contributor

#58083 [fix]try to fix copyfrom problem in `paddle.incubate.asp`
  python/paddle/incubate/asp/asp.py
Labels: contributor

#58051 [SOT][ci] add check file run
  paddle/scripts/paddle_build.sh
Labels: contributor

#58056 [CodeStyle][task 21] enable ruff C405 rule in `python/paddle/base`
  pyproject.toml
  python/paddle/base/backward.py
  python/paddle/base/dygraph/base.py
  python/paddle/base/multiprocess_utils.py
Labels: contributor, HappyOpenSource

#57835 【PaddlePaddle Hackathon 5 No.48】ContiguousKernel、StridedCopyKernel算子CPU、GPU性能优化
  paddle/phi/kernels/gpu/contiguous_kernel.cu
Labels: PaddlePaddle Hackathon, contributor

#58033 【PaddlePaddle Hackathon 5 No.48】StridedCopyKernel算子GPU性能优化
  paddle/phi/kernels/gpu/strided_copy_kernel.cu
Labels: PaddlePaddle Hackathon, contributor

#57972 Stage1 support main grad
  python/paddle/distributed/fleet/scaler.py
  python/paddle/distributed/fleet/utils/mix_precision_utils.py
  test/collective/fleet/CMakeLists.txt
  test/collective/fleet/dygraph_group_sharded_stage1_fp16.py
  test/collective/fleet/test_dygraph_sharding_stage1_fp16.py
  test/collective/fleet/testslist.csv
  tools/gpups_test.sh
Labels: contributor

#58093 [PIR] Migrate paddle.floor into pir
  python/paddle/tensor/ops.py
  test/legacy_test/test_activation_op.py
Labels: contributor

#58005 [PIR] Migrate paddle.round into pir
  python/paddle/tensor/ops.py
  test/legacy_test/test_activation_op.py
  test/mkldnn/test_activation_mkldnn_op.py
Labels: contributor

#58095 modify evaluate and predict funtion to fit with new Datalaoder
  python/paddle/distributed/auto_parallel/static/engine.py
Labels: contributor

#58042 [Hackathon 5th No.49][pir] add some method property - Part 2
  python/paddle/base/dygraph/math_op_patch.py
  python/paddle/base/layers/math_op_patch.py
  python/paddle/pir/math_op_patch.py
  test/legacy_test/test_math_op_patch_pir.py
Labels: PaddlePaddle Hackathon, contributor

#58081 [PIR] add all paddle.dot pir test
  test/legacy_test/test_dot_op.py
Labels: contributor

#58094 [PIR] Migrate paddle.sin into pir
  python/paddle/tensor/ops.py
  test/legacy_test/test_activation_op.py
Labels: contributor

#56761 No.12 Modify paddle.nn.utils.parameters_to_vector's stop_gradient to False
  python/paddle/nn/utils/transform_parameters.py
Labels: contributor, HappyOpenSource

#57875 【Hackathon 5th No.51】 为 Paddle 新增 flatten 的 spmd 切分推导规则
  paddle/phi/infermeta/spmd_rules/flatten.cc
  paddle/phi/infermeta/spmd_rules/flatten.h
  paddle/phi/infermeta/spmd_rules/rules.h
  test/auto_parallel/spmd_rules/CMakeLists.txt
  test/auto_parallel/spmd_rules/test_flatten_rule.py
Labels: PaddlePaddle Hackathon, contributor

#58162 [CodeStyle][task 9] enable Ruff UP030 rule in python/paddle/base
  pyproject.toml
  python/paddle/base/layers/layer_function_generator.py
Labels: contributor, HappyOpenSource

#58168 [xdoctest] reformat example code with google style in No. 261-263
  python/paddle/distributed/fleet/fleet.py
  python/paddle/incubate/nn/functional/fused_rms_norm.py
  python/paddle/incubate/nn/functional/fused_transformer.py
  python/paddle/incubate/nn/layer/fused_dropout_nd.py
Labels: contributor, HappyOpenSource

#57776 Release 2.5 sharding
  paddle/phi/infermeta/multiary.cc
  python/paddle/amp/auto_cast.py
  python/paddle/distributed/fleet/base/topology.py
  python/paddle/distributed/fleet/meta_optimizers/dygraph_optimizer/dygraph_sharding_optimizer.py
  python/paddle/distributed/fleet/meta_optimizers/dygraph_optimizer/hybrid_parallel_optimizer.py
  python/paddle/distributed/fleet/meta_parallel/pipeline_parallel.py
  python/paddle/distributed/fleet/meta_parallel/sharding_parallel.py
  python/paddle/distributed/fleet/model.py
  python/paddle/distributed/fleet/utils/hybrid_parallel_util.py
  python/paddle/distributed/fleet/utils/mix_precision_utils.py
  python/paddle/optimizer/optimizer.py
  test/collective/fleet/hybrid_parallel_sharding_model.py
  test/collective/fleet/hybrid_parallel_sharding_state_dict.py
  test/collective/fleet/test_parallel_dygraph_sharding_parallel.py
Labels: NVIDIA

#58173 [xdoctest][task 376~381] reformat example code with google style
  python/paddle/distribution/bernoulli.py
  python/paddle/distribution/categorical.py
  python/paddle/hapi/dynamic_flops.py
  python/paddle/hapi/model.py
  python/paddle/hapi/model_summary.py
Labels: contributor, HappyOpenSource

#57295 【Hackathon No.8】add api hypot & hypot_
  python/paddle/__init__.py
  python/paddle/tensor/__init__.py
  python/paddle/tensor/math.py
  test/legacy_test/test_hypot.py
  test/legacy_test/test_inplace.py
Labels: PaddlePaddle Hackathon, contributor

#58133 Adapt test_collective_global_gather with Numpy >= 1.25.2
  test/legacy_test/test_collective_api_base.py
Labels: NVIDIA, contributor

#58186 [CodeStyle][task 29,31,32] enable ruff B019, C416 and F821 rule in `python/paddle/base`
  pyproject.toml
  python/paddle/base/executor.py
  python/paddle/base/variable_index.py
Labels: contributor, HappyOpenSource

#58142 Integrate the new cuDNN version
  paddle/phi/backends/gpu/cuda/cudnn_helper.h
  paddle/phi/backends/gpu/gpu_resources.cc
  paddle/phi/backends/gpu/rocm/miopen_helper.h
Labels: NVIDIA, contributor

#58175 [CodeStyle][task 1] enable Ruff UP032 rule with some comments
  python/paddle/distributed/fleet/elastic/manager.py
  python/paddle/distributed/passes/auto_parallel_amp.py
  python/paddle/tensor/to_string.py
  test/legacy_test/test_inplace.py
Labels: contributor, HappyOpenSource

#58255 【Hackathon 5th No.13】【关联 PR】Added int support for sign -Part
  paddle/phi/kernels/cpu/sign_kernel.cc
  paddle/phi/kernels/funcs/eigen/sign.cc
  paddle/phi/kernels/funcs/eigen/sign.cu
  paddle/phi/kernels/gpu/sign_kernel.cu.cc
  python/paddle/tensor/math.py
  test/legacy_test/test_sign_op.py
Labels: contributor

#58253 [cmake] Standardize the use of git addresses
  cmake/cinn/external/absl.cmake
  cmake/cinn/external/jitify.cmake
  cmake/external/brpc.cmake
  cmake/external/cudnn-frontend.cmake
  cmake/external/dirent.cmake
  cmake/external/jemalloc.cmake
  cmake/external/libxsmm.cmake
  cmake/external/onnxruntime.cmake
  cmake/external/openblas.cmake
  cmake/external/paddle2onnx.cmake
  cmake/external/protobuf.cmake
Labels: contributor

#58308 [CodeStyle][ruff][F401] Clean up unnecessary imports
  python/paddle/distributed/fleet/utils/__init__.py
  python/paddle/incubate/multiprocessing/__init__.py
Labels: contributor

#58219 [Hackathon 5th No.49][pir] add some operation - Part 3
  python/paddle/pir/math_op_patch.py
  python/paddle/tensor/math.py
  test/legacy_test/test_math_op_patch_pir.py
Labels: PaddlePaddle Hackathon, contributor

#58185 [CodeStyle][task 10] enable ruff B017 rule in python/paddle/base
  pyproject.toml
  test/auto_parallel/spmd_rules/test_reshape_rule.py
  test/dygraph_to_static/test_assert.py
  test/legacy_test/test_cuda_max_memory_allocated.py
  test/legacy_test/test_cuda_max_memory_reserved.py
  test/legacy_test/test_cuda_memory_allocated.py
  test/legacy_test/test_cuda_memory_reserved.py
  test/legacy_test/test_eigvals_op.py
  test/legacy_test/test_tensordot.py
  test/legacy_test/test_top_k_v2_op.py
Labels: contributor, HappyOpenSource

#57741 【PIR】add memcpy in PIR
  paddle/fluid/pir/dialect/op_generator/ops_api_gen.py
  paddle/fluid/pir/dialect/operator/ir/ops.yaml
  paddle/fluid/pir/transforms/pd_op_to_kernel_pass.cc
  paddle/phi/api/yaml/op_compat.yaml
  test/dygraph_to_static/test_tensor_memcpy_on_cpu.py
  test/dygraph_to_static/test_tensor_memcpy_on_gpu.py
  test/white_list/new_ir_op_test_white_list
Labels: contributor

#58287 [PIR] Migrate some ops into pir
  python/paddle/tensor/attribute.py
  python/paddle/tensor/logic.py
  python/paddle/tensor/manipulation.py
  python/paddle/tensor/math.py
  python/paddle/tensor/search.py
  test/legacy_test/test_compare_reduce_op.py
  test/legacy_test/test_expand_as_v2_op.py
  test/legacy_test/test_flip.py
  test/legacy_test/test_full_op.py
  test/legacy_test/test_logical_op.py
  test/legacy_test/test_logit_op.py
  test/legacy_test/test_nonzero_api.py
  test/legacy_test/test_real_imag_op.py
Labels: contributor

#58352 [PIR] Migrate paddle.nn.MSELoss into pir
  test/legacy_test/test_mse_loss.py
Labels: contributor

#58340 [PIR] Migrate paddle.nn.LeakyReLU into pir
  python/paddle/nn/functional/activation.py
  test/legacy_test/test_activation_op.py
Labels: contributor

#58363 [PIR] Migrate paddle.Tensor.log10 into pir
  python/paddle/tensor/math.py
  test/legacy_test/test_activation_op.py
Labels: contributor

#58206 [xdoctest] reformat example code with google style in No.386-389
  python/paddle/nn/functional/flash_attention.py
  python/paddle/quantization/config.py
  python/paddle/quantization/factory.py
  python/paddle/tensor/linalg.py
Labels: contributor, HappyOpenSource

#58355 [PIR]modify vjp interface gen for control_flow
  paddle/fluid/pir/dialect/op_generator/op_interface_gen.py
  paddle/fluid/pir/dialect/operator/ir/manual_op_vjp.cc
  python/paddle/autograd/ir_backward.py
  test/cpp/prim/test_vjp.cc
  test/prim/pir_prim/test_vjp_prim.py
Labels: contributor

#58374 fix jemalloc download problem
  cmake/external/jemalloc.cmake
Labels: contributor

#58327 [tests] move `paddle/fluid/framework/*_test*` -> `test/cpp/fluid/framework/`
  cmake/generic.cmake
  paddle/fluid/framework/CMakeLists.txt
  test/cpp/fluid/CMakeLists.txt
  test/cpp/fluid/framework/CMakeLists.txt
  test/cpp/fluid/framework/attribute_test.cc
  test/cpp/fluid/framework/convert_utils_test.cc
  test/cpp/fluid/framework/copy_same_tensor_test.cc
  test/cpp/fluid/framework/data_device_transform_test.cu
  test/cpp/fluid/framework/data_feed_test.cc
  test/cpp/fluid/framework/data_layout_transform_test.cc
  test/cpp/fluid/framework/data_type_test.cc
  test/cpp/fluid/framework/data_type_transform_test.cc
  test/cpp/fluid/framework/data_type_transform_test.cu
  test/cpp/fluid/framework/details/cow_ptr_test.cc
  test/cpp/fluid/framework/device_worker_test.cc
  test/cpp/fluid/framework/dist_multi_trainer_test.cc
  test/cpp/fluid/framework/dlpack_tensor_test.cc
  test/cpp/fluid/framework/eigen_test.cc
  test/cpp/fluid/framework/heter_pipeline_trainer_test.cc
  test/cpp/fluid/framework/infershape_utils_test.cc
  test/cpp/fluid/framework/inlined_vector_test.cc
  test/cpp/fluid/framework/lod_tensor_test.cc
  test/cpp/fluid/framework/lod_tensor_test.cu
  test/cpp/fluid/framework/naive_executor_test.cc
  test/cpp/fluid/framework/no_need_buffer_vars_inference_test.cc
  test/cpp/fluid/framework/op_call_stack_test.cc
  test/cpp/fluid/framework/op_compatible_info_test.cc
  test/cpp/fluid/framework/op_desc_test.cc
  test/cpp/fluid/framework/op_kernel_type_test.cc
  test/cpp/fluid/framework/op_proto_maker_test.cc
  test/cpp/fluid/framework/op_registry_test.cc
  test/cpp/fluid/framework/op_version_registry_test.cc
  test/cpp/fluid/framework/operator_exception_test.cc
  test/cpp/fluid/framework/operator_test.cc
  test/cpp/fluid/framework/phi_utils_test.cc
  test/cpp/fluid/framework/program_desc_test.cc
  test/cpp/fluid/framework/program_utils_test.cc
  test/cpp/fluid/framework/prune_test.cc
  test/cpp/fluid/framework/reader_test.cc
  test/cpp/fluid/framework/scope_guard_test.cc
  test/cpp/fluid/framework/scope_test.cc
  test/cpp/fluid/framework/selected_rows_utils_test.cc
  test/cpp/fluid/framework/tensor_test.cc
  test/cpp/fluid/framework/tensor_util_test.cc
  test/cpp/fluid/framework/tensor_util_test.cu
  test/cpp/fluid/framework/threadpool_test.cc
  test/cpp/fluid/framework/trainer_test.cc
  test/cpp/fluid/framework/tuple_test.cc
  test/cpp/fluid/framework/var_type_inference_test.cc
  test/cpp/fluid/framework/var_type_traits_test.cc
  test/cpp/fluid/framework/variable_test.cc
  test/cpp/fluid/framework/version_test.cc
Labels: contributor

#58354 [PIR]Migrate Conv1D into pir
  python/paddle/nn/functional/conv.py
  python/paddle/tensor/math.py
  test/legacy_test/test_conv1d_layer.py
Labels: contributor

#58324 Improve send recv overlap
  python/paddle/distributed/auto_parallel/static/parallelizer_v2.py
  python/paddle/distributed/passes/pass_utils.py
  python/paddle/distributed/passes/pipeline_scheduler_pass.py
Labels: contributor

#58369 [AutoParallel] Support disttensor for Tensor.copy_
  paddle/phi/api/lib/tensor_method.cc
  test/auto_parallel/semi_auto_parallel_recompute.py
  test/auto_parallel/semi_auto_parallel_simple_net.py
  test/auto_parallel/test_semi_auto_parallel_single_strategy.py
Labels: contributor

#58380 [AutoParallel] check nan or inf add disttensor
  paddle/fluid/eager/nan_inf_utils.cc
Labels: contributor

#58388 [PIR] fix c_sync_comm_stream
  paddle/fluid/pir/transforms/pd_op_to_kernel_pass.cc
  paddle/phi/api/yaml/legacy_ops.yaml
Labels: contributor

#58341 【PIR API adaptor No.37、38】 Migrate paddle.cholesky/cholesky_solve into pir
  python/paddle/tensor/linalg.py
  test/legacy_test/test_cholesky_op.py
  test/legacy_test/test_cholesky_solve_op.py
Labels: contributor

#58333 【PIR API adaptor No.10、11】Migrate paddle.as_real/as_complex into pir
  python/paddle/tensor/manipulation.py
  test/legacy_test/test_complex_view_op.py
Labels: contributor

#58390 [PIR] translate newir in python
  paddle/fluid/framework/new_executor/standalone_executor.cc
  paddle/fluid/ir_adaptor/translator/translate.cc
  python/paddle/base/executor.py
Labels: contributor

#58382 [PIR]Perfect unittest for exp / full_like / gather_nd / gather / rms_norm / softmax / transpose
  python/paddle/incubate/nn/functional/fused_rms_norm.py
  python/paddle/tensor/linalg.py
  python/paddle/tensor/manipulation.py
  test/legacy_test/test_activation_op.py
  test/legacy_test/test_full_like_op.py
  test/legacy_test/test_gather_nd_op.py
  test/legacy_test/test_gather_op.py
  test/legacy_test/test_rms_norm_op.py
  test/legacy_test/test_softmax_op.py
  test/legacy_test/test_transpose_op.py
Labels: contributor

#58283 [PIR] Fix bug when build scope
  paddle/fluid/framework/new_executor/pir_adaptor/pir_adaptor_util.cc
  paddle/fluid/framework/new_executor/pir_adaptor/pir_adaptor_util.h
  paddle/fluid/framework/new_executor/pir_interpreter.cc
  paddle/fluid/pir/transforms/pd_op_to_kernel_pass.cc
  python/paddle/jit/dy2static/partial_program.py
  test/cpp/new_executor/standalone_executor_new_ir_test.cc
  test/cpp/prim/test_vjp.cc
  test/dygraph_to_static/test_typehint.py
Labels: contributor

#58402 fix shard2 global norm
  python/paddle/distributed/fleet/meta_optimizers/dygraph_optimizer/dygraph_sharding_optimizer.py
Labels: contributor

#58392 [Inference] upgrade inference profiler
  paddle/fluid/framework/naive_executor.cc
  paddle/fluid/framework/new_executor/program_interpreter.cc
  paddle/fluid/inference/api/analysis_predictor.cc
Labels: contributor

#58364 Add XPU bf16 support for split kernel and update XPU basedate.
  cmake/external/xpu.cmake
  paddle/phi/backends/xpu/xpu2_op_list.cc
  paddle/phi/backends/xpu/xpu3_op_list.cc
  paddle/phi/kernels/xpu/split_kernel.cc
Labels: contributor

#58029 fix exponential op
  paddle/phi/api/yaml/op_compat.yaml
  test/legacy_test/CMakeLists.txt
  test/legacy_test/op_test.py
  test/white_list/new_ir_op_test_no_check_list
  test/white_list/new_ir_op_test_white_list
Labels: contributor

#58403 [AutoParallel] refine tensor methon code
  paddle/phi/api/lib/tensor_method.cc
Labels: contributor

#58361 [OneDNN] Pooling calculation issue fix
  paddle/phi/backends/onednn/onednn_reuse.h
  test/cpp/fluid/mkldnn/CMakeLists.txt
  test/cpp/fluid/mkldnn/test_mkldnn_pool_adaptive_op.cc
Labels: Intel, contributor

#58401 【pir】add fused_linear_param_grad_add_pass
  paddle/fluid/pir/transforms/fusion/fused_dropout_add_pass.cc
  paddle/fluid/pir/transforms/fusion/fused_gemm_epilogue_pass.cc
  paddle/fluid/pir/transforms/fusion/fused_linear_param_grad_add_pass.cc
  paddle/fluid/pir/transforms/fusion/fused_linear_param_grad_add_pass.h
  paddle/fluid/pybind/pir.cc
  test/cpp/pir/pattern_rewrite/CMakeLists.txt
  test/cpp/pir/pattern_rewrite/drr_fuse_linear_param_grad_add_test.cc
  test/ir/new_ir/fused_pass/CMakeLists.txt
  test/ir/new_ir/fused_pass/test_fused_dropout_add_pass.py
Labels: contributor

#58383 [Distributed]Add unbalance batch for virtual pp
  python/paddle/distributed/fleet/meta_parallel/__init__.py
  python/paddle/distributed/fleet/meta_parallel/pipeline_parallel.py
  python/paddle/distributed/fleet/meta_parallel/pp_utils/p2p_communication.py
  python/paddle/distributed/fleet/model.py
Labels: contributor

#58408 fix inference build error
  paddle/phi/core/distributed/nccl_tools.cc
Labels: contributor

#58424 [SOT][3.11] Increase ref of func to avoid segmentation fault
  paddle/fluid/pybind/eval_frame.c
Labels: contributor

#58414 [PIR] Solve conflict
  paddle/fluid/pir/transforms/pd_op_to_kernel_pass.cc
Labels: contributor

#58419 sqrt, transpose, transpose_grad support bf16 type for XPU
  paddle/phi/backends/xpu/xpu2_op_list.cc
  paddle/phi/backends/xpu/xpu3_op_list.cc
  paddle/phi/kernels/xpu/activation_kernel.cc
  paddle/phi/kernels/xpu/transpose_grad_kernel.cc
  paddle/phi/kernels/xpu/transpose_kernel.cc
Labels: contributor

#58412 [AutoParallel] Verify optimizer in test case
  paddle/phi/api/yaml/generator/dist_api_gen.py
  test/auto_parallel/semi_auto_parallel_simple_net.py
  test/auto_parallel/semi_auto_parallel_simple_net_hybrid.py
Labels: contributor

#58409 [AutoParallel] Gradient hook check
  test/auto_parallel/semi_auto_parallel_simple_net_gradient_hook.py
  test/auto_parallel/test_semi_auto_parallel_single_strategy.py
Labels: contributor

#58428 [DCU] fix compile error on DCU, test=develop
  cmake/hip.cmake
  paddle/fluid/distributed/collective/process_group_nccl.cc
  paddle/phi/backends/dynload/rccl.h
  paddle/phi/core/distributed/nccl_comm_task.cc
  paddle/phi/core/distributed/nccl_comm_task.h
  paddle/phi/core/distributed/nccl_tools.h
  paddle/phi/kernels/fusion/gpu/fused_bn_add_activation_grad_kernel.cu
  paddle/phi/kernels/fusion/gpu/fused_bn_add_activation_kernel.cu
  paddle/phi/kernels/fusion/gpu/fusion_transpose_flatten_concat_kernel.cu
  paddle/phi/kernels/gpu/contiguous_kernel.cu
Labels: contributor

#58437 [AutoParallel] clear gradient support auto parallel
  paddle/fluid/pybind/eager_method.cc
  test/auto_parallel/semi_auto_parallel_clear_gradient.py
  test/auto_parallel/test_semi_auto_parallel_single_strategy.py
Labels: contributor

#58420 【pir】Modify comment of #58401
  paddle/fluid/pir/transforms/fusion/fused_linear_param_grad_add_pass.cc
Labels: contributor

#58349 [CINN] add README.md
  paddle/cinn/README.md
Labels: contributor

#57866 【Hackathon 5th No.50】 为 Paddle 新增 slice 的 spmd 切分推导规则
  paddle/phi/infermeta/spmd_rules/rules.h
  paddle/phi/infermeta/spmd_rules/slice.cc
  paddle/phi/infermeta/spmd_rules/slice.h
  test/auto_parallel/spmd_rules/CMakeLists.txt
  test/auto_parallel/spmd_rules/test_slice_rule.py
Labels: PaddlePaddle Hackathon, contributor

#57881 【Hackathon 5th No.105】move fusion_gru/fusion_seqconv_eltadd_relu/fusion_seqexpand_concat_fc to phi
  paddle/fluid/operators/fused/CMakeLists.txt
  paddle/fluid/operators/fused/fusion_gru_op.cc
  paddle/fluid/operators/fused/fusion_gru_op.h
  paddle/fluid/operators/fused/fusion_seqconv_eltadd_relu_op.cc
  paddle/fluid/operators/fused/fusion_seqconv_eltadd_relu_op.h
  paddle/fluid/operators/fused/fusion_seqexpand_concat_fc_op.cc
  paddle/fluid/operators/fused/fusion_seqexpand_concat_fc_op.h
  paddle/fluid/operators/fused/mkldnn/fusion_gru_mkldnn_op.cc
  paddle/fluid/pir/dialect/op_generator/ops_api_gen.py
  paddle/phi/api/yaml/fused_ops.yaml
  paddle/phi/api/yaml/op_compat.yaml
  paddle/phi/infermeta/fusion.cc
  paddle/phi/infermeta/fusion.h
  paddle/phi/kernels/fusion/cpu/fusion_gru_kernel.cc
  paddle/phi/kernels/fusion/cpu/fusion_seqconv_eltadd_relu_kernel.cc
  paddle/phi/kernels/fusion/cpu/fusion_seqexpand_concat_fc_kernel.cc
  paddle/phi/kernels/fusion/onednn/fusion_gru_kernel.cc
  test/legacy_test/test_fusion_seqconv_eltadd_relu_op.py
Labels: PaddlePaddle Hackathon, contributor

#58314 [AutoTuner]Improve ETCD fault tolerance
  python/paddle/distributed/auto_tuner/prune.py
  python/paddle/distributed/auto_tuner/recorder.py
  python/paddle/distributed/launch/controllers/master.py
  python/paddle/distributed/launch/controllers/watcher.py
  python/paddle/distributed/launch/main.py
  python/paddle/distributed/launch/utils/etcd_client.py
  python/paddle/distributed/launch/utils/nvsmi.py
Labels: contributor

#58389 [Dy2St] Refactor dy2st unittest decorators name - Part 1
  test/dygraph_to_static/test_basic_api_transformation.py
  test/dygraph_to_static/test_bert.py
  test/dygraph_to_static/test_bmn.py
  test/dygraph_to_static/test_break_continue.py
  test/dygraph_to_static/test_build_strategy.py
  test/dygraph_to_static/test_cache_program.py
  test/dygraph_to_static/test_cinn.py
  test/dygraph_to_static/test_cinn_prim.py
  test/dygraph_to_static/test_cinn_prim_gelu.py
  test/dygraph_to_static/test_cinn_prim_layer_norm.py
  test/dygraph_to_static/test_cinn_prim_mean.py
  test/dygraph_to_static/test_convert_call.py
  test/dygraph_to_static/test_convert_call_generator.py
  test/dygraph_to_static/test_convert_operators.py
  test/dygraph_to_static/test_cpu_cuda_to_tensor.py
  test/dygraph_to_static/test_cycle_gan.py
  test/dygraph_to_static/test_dict.py
  test/dygraph_to_static/test_drop_path.py
  test/dygraph_to_static/test_duplicate_output.py
Labels: contributor

#58441 [incubate/new_frl] Support release_grads in Pipeline Parallel while using comm overlap
  paddle/fluid/framework/distributed_strategy.proto
  python/paddle/distributed/fleet/meta_parallel/pipeline_parallel.py
  python/paddle/distributed/fleet/utils/tensor_fusion_helper.py
Labels: contributor

#58458 [Dy2St] Refactor dy2st unittest decorators name - Part 2
  test/dygraph_to_static/dygraph_to_static_utils_new.py
  test/dygraph_to_static/test_fallback.py
  test/dygraph_to_static/test_fetch_feed.py
  test/dygraph_to_static/test_for_enumerate.py
  test/dygraph_to_static/test_full_name_usage.py
  test/dygraph_to_static/test_grad.py
  test/dygraph_to_static/test_gradient_aggregation.py
  test/dygraph_to_static/test_gradname_parse.py
  test/dygraph_to_static/test_ifelse.py
  test/dygraph_to_static/test_isinstance.py
  test/dygraph_to_static/test_jit_property_save.py
  test/dygraph_to_static/test_jit_setitem.py
  test/dygraph_to_static/test_lambda.py
  test/dygraph_to_static/test_layer_hook.py
  test/dygraph_to_static/test_len.py
  test/dygraph_to_static/test_list.py
Labels: contributor

#58464 [Dy2St] Refactor dy2st unittest decorators name - Part 3
  test/dygraph_to_static/dygraph_to_static_utils_new.py
  test/dygraph_to_static/test_ifelse.py
  test/dygraph_to_static/test_inplace_assign.py
  test/dygraph_to_static/test_logical.py
  test/dygraph_to_static/test_loop.py
  test/dygraph_to_static/test_lstm.py
  test/dygraph_to_static/test_mnist.py
  test/dygraph_to_static/test_mnist_amp.py
  test/dygraph_to_static/test_mnist_pure_fp16.py
  test/dygraph_to_static/test_mobile_net.py
  test/dygraph_to_static/test_multi_forward.py
  test/dygraph_to_static/test_new_ir_selectedrows.py
  test/dygraph_to_static/test_op_attr.py
  test/dygraph_to_static/test_origin_info.py
  test/dygraph_to_static/test_param_guard.py
  test/dygraph_to_static/test_params_no_grad.py
Labels: contributor

#58465 [Dy2St] Refactor dy2st unittest decorators name - Part 4
  test/dygraph_to_static/test_partial_program_hook.py
  test/dygraph_to_static/test_place.py
  test/dygraph_to_static/test_print.py
  test/dygraph_to_static/test_program_translator.py
  test/dygraph_to_static/test_ptb_lm.py
  test/dygraph_to_static/test_ptb_lm_v2.py
  test/dygraph_to_static/test_pylayer.py
  test/dygraph_to_static/test_reinforcement_learning.py
  test/dygraph_to_static/test_resnet.py
  test/dygraph_to_static/test_resnet_amp.py
  test/dygraph_to_static/test_resnet_pure_fp16.py
  test/dygraph_to_static/test_resnet_v2.py
  test/dygraph_to_static/test_return.py
  test/dygraph_to_static/test_rollback.py
  test/dygraph_to_static/test_save_inference_model.py
Labels: contributor

#58447 [AutoParallel] Checker for tensor manipulation in hook
  test/auto_parallel/semi_auto_parallel_simple_net_gradient_hook.py
Labels: contributor

#58360 [auto parallel] enable spmd rules for maximum
  paddle/phi/api/yaml/legacy_backward.yaml
  paddle/phi/api/yaml/legacy_ops.yaml
  paddle/phi/infermeta/spmd_rules/elementwise.h
  test/auto_parallel/semi_auto_parallel_for_elementwise.py
Labels: contributor

#58448 [pir] delete pm.EnablePassTiming() avoid build error
  test/cpp/pir/pattern_rewrite/drr_fuse_linear_param_grad_add_test.cc
Labels: contributor

#58406 fix dtype bug in layer norm custom vjp rule
  paddle/fluid/primitive/rule/vjp/details.h
Labels: contributor

#58351 [PIR]Add cinn broadcast op when x_shape not equal y_shape in elementwise op
  paddle/cinn/hlir/dialect/operator/transforms/CMakeLists.txt
  paddle/cinn/hlir/dialect/operator/transforms/add_broadcast_to_elementwise_pass.cc
  paddle/cinn/hlir/dialect/operator/transforms/add_broadcast_to_elementwise_pass.h
  paddle/cinn/hlir/dialect/operator/transforms/pd_to_cinn_pass.cc
  test/cpp/pir/cinn/CMakeLists.txt
  test/cpp/pir/cinn/add_broadcast_to_elementwise_test.cc
Labels: contributor

#58451 [Debug][Prim][PIR]Codegen for decomp interface implementation
  paddle/fluid/pir/dialect/op_generator/decomp_interface_gen_op_list.py
  paddle/fluid/pir/dialect/op_generator/op_gen.py
  paddle/fluid/pir/dialect/operator/ir/CMakeLists.txt
  paddle/fluid/pir/dialect/operator/ir/manual_op_decomp.cc
  paddle/fluid/primitive/codegen/CMakeLists.txt
  paddle/fluid/primitive/codegen/decomp_gen.py
  paddle/fluid/primitive/codegen/templates/decomp/generated_decomp.j2
Labels: contributor

#58445 【PIR API adaptor No.178、169、137、34、129】 Migrate ReLU6/PReLU/LogSigmoid/CELU/LogSoftmax into pir
  python/paddle/nn/functional/activation.py
  test/legacy_test/test_activation_op.py
  test/legacy_test/test_log_softmax.py
  test/legacy_test/test_prelu_op.py
Labels: contributor

#58456 [XPU] add bfloat16 support for CastKernel
  paddle/phi/backends/xpu/xpu2_op_list.cc
  paddle/phi/backends/xpu/xpu3_op_list.cc
  paddle/phi/kernels/xpu/cast_kernel.cc
  test/xpu/test_cast_op_xpu.py
Labels: contributor

#58459 [PIR][AutoParallel] Support 1F1B/FThenB with PIR
  paddle/fluid/framework/new_executor/feed_fetch_utils.cc
  paddle/fluid/framework/new_executor/feed_fetch_utils.h
  paddle/fluid/framework/new_executor/standalone_executor.cc
  paddle/fluid/framework/new_executor/standalone_executor.h
  python/paddle/base/executor.py
  python/paddle/distributed/passes/auto_parallel_gradient_merge.py
  python/paddle/distributed/passes/pass_utils.py
  python/paddle/distributed/passes/pipeline_pass_base.py
  python/paddle/distributed/passes/pipeline_scheduler_pass.py
  test/auto_parallel/gpt_with_newir.py
  test/standalone_executor/test_standalone_custom_event.py
  test/standalone_executor/test_standalone_executor_1f1b_plan.py
  test/standalone_executor/test_standalone_executor_fthenb_plan.py
  test/standalone_executor/test_standalone_executor_multi_micro_batch.py
Labels: contributor

#58435 [OneDNN] v3.2 pp_liteseg_stdc1 regression issue
  paddle/phi/kernels/onednn/conv_handler.h
  test/cpp/fluid/mkldnn/test_conv_mkldnn_nhwc.cc
Labels: Intel, contributor

#58436 [AutoParallel] PHI copy support auto parallel
  paddle/phi/api/lib/tensor_copy.cc
  test/auto_parallel/CMakeLists.txt
  test/auto_parallel/test_semi_auto_parallel_functional_in_single_card.py
Labels: contributor

#58367 [NVIDIA] Fix CUDNNv8 build
  paddle/phi/kernels/fusion/gpu/fused_scale_bias_relu_conv_bnstats_kernel.cu
Labels: NVIDIA, contributor

#58370 【PIR API adaptor No.231、232】 Migrate paddle.tril_indices/triu_indices into pir
  python/paddle/tensor/creation.py
  test/legacy_test/test_tril_indices_op.py
Labels: contributor

#58434 [AutoParallel] Addn support AutoParallel
  paddle/phi/api/lib/api_custom_impl.cc
  paddle/phi/api/lib/api_gen_utils.cc
  paddle/phi/api/lib/api_gen_utils.h
  paddle/phi/api/lib/data_transform.cc
  paddle/phi/api/lib/data_transform.h
  paddle/phi/infermeta/spmd_rules/utils.h
  test/auto_parallel/semi_auto_parallel_for_add_n.py
  test/auto_parallel/test_semi_auto_parallel_basic.py
Labels: contributor

#58418 [PIR]Migrate Conv3D into pir
  test/legacy_test/test_conv3d_layer.py
  test/legacy_test/test_conv3d_op.py
Labels: contributor

#58317 【PIR API adaptor No.2】 Migrate paddle.acos into pir
  python/paddle/tensor/ops.py
  test/legacy_test/test_activation_op.py
Labels: contributor

#58450 【PIR API adaptor No.3】 Migrate paddle.acosh into pir
  python/paddle/tensor/ops.py
  test/legacy_test/test_activation_op.py
Labels: contributor

#58239 [PIR]Migrate isclose into pir
  paddle/fluid/operators/generator/generate_op.py
  paddle/fluid/operators/generator/type_mapping.py
  paddle/fluid/pir/dialect/op_generator/op_gen.py
  paddle/phi/api/yaml/generator/api_base.py
  paddle/phi/api/yaml/ops.yaml
  python/paddle/tensor/logic.py
  test/legacy_test/test_isclose_op.py
Labels: contributor

#58377 【PIR API adaptor No.206、207】 Migrate paddle.sign/sinh into pir
  python/paddle/tensor/math.py
  python/paddle/tensor/ops.py
  test/legacy_test/test_activation_op.py
  test/legacy_test/test_sign_op.py
Labels: contributor

#58462 Support release_grads in DygraphShardingOptimizerV2
  python/paddle/distributed/fleet/meta_optimizers/dygraph_optimizer/dygraph_sharding_optimizer.py
  python/paddle/distributed/fleet/utils/tensor_fusion_helper.py
Labels: contributor

#56550 解决废弃算子mul op 在新 IR 下的translator问题
  paddle/fluid/ir_adaptor/translator/op_translator.cc
  paddle/fluid/operators/mul_op.cc
  paddle/phi/api/yaml/op_compat.yaml
  test/white_list/new_ir_op_test_white_list
Labels: contributor

#58372 [PIR] Add pir test for test_while_loop_op
  paddle/fluid/framework/executor_cache.cc
  paddle/fluid/framework/new_executor/instruction/instruction_util.cc
  paddle/fluid/framework/new_executor/instruction/instruction_util.h
  paddle/fluid/framework/new_executor/instruction/while_instruction.cc
  paddle/fluid/framework/new_executor/standalone_executor.cc
  paddle/fluid/pir/transforms/pd_op_to_kernel_pass.cc
  paddle/phi/core/flags.cc
  test/legacy_test/op_test.py
  test/legacy_test/test_while_loop_op.py
Labels: contributor

#58490 [Dy2St] Refactor dy2st unittest decorators name - Part 5
  test/dygraph_to_static/test_save_load.py
  test/dygraph_to_static/test_se_resnet.py
  test/dygraph_to_static/test_seq2seq.py
  test/dygraph_to_static/test_simnet.py
  test/dygraph_to_static/test_simnet_v2.py
  test/dygraph_to_static/test_slice.py
  test/dygraph_to_static/test_tensor_hook.py
  test/dygraph_to_static/test_tensor_memcpy_on_cpu.py
  test/dygraph_to_static/test_tensor_memcpy_on_gpu.py
  test/dygraph_to_static/test_tensor_methods.py
  test/dygraph_to_static/test_to_tensor.py
  test/dygraph_to_static/test_train_step.py
  test/dygraph_to_static/test_transformer.py
  test/dygraph_to_static/test_tsm.py
  test/dygraph_to_static/test_typehint.py
Labels: contributor

#58472 [Paddle Inference] Support GQA Decoder
  paddle/phi/infermeta/multiary.cc
  paddle/phi/kernels/fusion/gpu/masked_multihead_attention.cu
Labels: contributor

#58394 【PIR API adaptor No.221】 Migrate paddle.nn.Swish/LeakyReLU into pir
  python/paddle/nn/functional/activation.py
  test/legacy_test/test_activation_op.py
Labels: contributor

#58473 【PIR API adaptor No.16、18】 Migrate paddle.atan, paddle.atanh into pir
  python/paddle/tensor/ops.py
  test/legacy_test/test_activation_op.py
Labels: contributor

#58332 [SOT] add CMakeLists to sot unittests
  paddle/scripts/paddle_build.sh
  test/CMakeLists.txt
  test/dygraph_to_static/CMakeLists.txt
  test/sot/CMakeLists.txt
  test/sot/extract_errors.py
  test/sot/test_12_for_loop.py
  test/sot/test_builtin_map.py
  test/sot/test_builtin_range.py
  test/sot/test_sot_cost_model.py
  test/sot/test_sot_exception.py
  test/sot/test_sot_resnet.py
  test/sot/test_sot_resnet50_backward.py
Labels: contributor

#58498 [PIR]Migrate gather into pir
  paddle/phi/infermeta/binary.cc
  test/legacy_test/test_gather_op.py
Labels: contributor

#58492 [Inference] jit.save() remove useless renaming process
  python/paddle/static/io.py
  test/legacy_test/test_static_save_load.py
Labels: contributor

#58381 [PIR]Support generate op that is used for pir only
  paddle/fluid/ir_adaptor/translator/op_translator.cc
  paddle/fluid/operators/generator/parse_utils.py
  paddle/fluid/pir/dialect/op_generator/api_gen.py
  paddle/fluid/pir/dialect/op_generator/op_creator_drr_gen.py
  paddle/fluid/pir/dialect/op_generator/op_gen.py
  paddle/fluid/pir/dialect/operator/ir/CMakeLists.txt
  paddle/fluid/pir/dialect/operator/ir/update_ops.yaml
  paddle/fluid/pir/drr/CMakeLists.txt
  paddle/fluid/primitive/codegen/CMakeLists.txt
  paddle/fluid/primitive/codegen/gen.py
  paddle/phi/api/yaml/legacy_ops.yaml
  paddle/phi/api/yaml/static_ops.yaml
  paddle/phi/infermeta/nullary.cc
  paddle/phi/infermeta/nullary.h
  paddle/phi/infermeta/ternary.cc
  paddle/phi/infermeta/ternary.h
  paddle/phi/kernels/arange_kernel.h
  paddle/phi/kernels/cpu/arange_kernel.cc
  paddle/phi/kernels/gpu/arange_kernel.cu
  paddle/phi/kernels/xpu/arange_kernel.cc
  python/paddle/tensor/creation.py
  test/legacy_test/test_arange.py
Labels: contributor

#57852 add quant_linear
  paddle/phi/api/yaml/static_ops.yaml
  paddle/phi/infermeta/ternary.cc
  paddle/phi/infermeta/ternary.h
  paddle/phi/kernels/funcs/fc_functor.cu
  paddle/phi/kernels/funcs/fc_functor.h
  paddle/phi/kernels/funcs/quant_dequant.h
  paddle/phi/kernels/gpu/quant_linear_kernel.cu
  paddle/phi/kernels/impl/matmul_kernel_impl.h
  paddle/phi/kernels/impl/quant_linear_kernel_impl.h
  python/paddle/static/nn/__init__.py
  python/paddle/static/nn/common.py
  test/legacy_test/test_quant_linear_op.py
Labels: contributor

#58479 [AutoParallel] refine copy to
  paddle/phi/api/lib/tensor_method.cc
  test/auto_parallel/test_semi_auto_parallel_functional_in_single_card.py
Labels: contributor

#58442 [AutoParallel] eager method support autoparallel 1
  paddle/fluid/pybind/eager_method.cc
  test/auto_parallel/semi_auto_parallel_simple_net_zero_grads.py
  test/auto_parallel/test_semi_auto_parallel_functional_in_single_card.py
  test/auto_parallel/test_semi_auto_parallel_single_strategy.py
Labels: contributor

#58487 [AutoParallel] eager_function.cc support autoparallel
  paddle/fluid/pybind/eager_functions.cc
  test/auto_parallel/semi_auto_parallel_simple_net_grad_api.py
Labels: contributor

#58391 [PIR]Migrate SGD into pir
  test/legacy_test/op_test.py
  test/legacy_test/test_sgd_op.py
Labels: contributor

#58503 [Docathon][Fix System Message No.1、26]
  python/paddle/static/nn/common.py
Labels: contributor, HappyOpenSource

#58501 [PIR]Migrate einsum_v2 into pir
  python/paddle/tensor/einsum.py
  test/legacy_test/test_einsum_v2.py
Labels: contributor

#58476 [AutoParallel] Eager method support autoparallel3
  paddle/fluid/pybind/eager_method.cc
  paddle/phi/api/lib/tensor.cc
  python/paddle/distributed/auto_parallel/api.py
  test/auto_parallel/test_semi_auto_parallel_functional_in_single_card.py
Labels: contributor

#58421 【AutoParallelism】Add refined recompute support
  python/paddle/distributed/auto_parallel/__init__.py
  python/paddle/distributed/auto_parallel/interface.py
  python/paddle/distributed/auto_parallel/static/utils.py
  python/paddle/distributed/passes/auto_parallel_recompute.py
  test/legacy_test/auto_parallel_gpt_model.py
Labels: contributor

#58379 fix_repeat_interleave_op
  paddle/fluid/ir_adaptor/translator/op_translator.cc
  paddle/phi/api/yaml/legacy_ops.yaml
  paddle/phi/api/yaml/op_compat.yaml
  test/legacy_test/test_repeat_interleave_op.py
  test/white_list/new_ir_op_test_white_list
Labels: contributor

#58439 不开 sharding, 不创建通信组
  python/paddle/distributed/fleet/base/topology.py
Labels: contributor

#58466 【PIR API adaptor No.50、57、67】Migrate some ops into pir
  python/paddle/tensor/math.py
  test/legacy_test/test_cumprod_op.py
  test/legacy_test/test_digamma_op.py
  test/legacy_test/test_erfinv_op.py
Labels: contributor

#58474 [auto parallel] complete elementwise ops spmd rules of LLaMa2 for eager semi auto parallel
  paddle/phi/api/yaml/backward.yaml
  paddle/phi/api/yaml/legacy_backward.yaml
  paddle/phi/api/yaml/legacy_ops.yaml
  paddle/phi/api/yaml/ops.yaml
  paddle/phi/core/distributed/auto_parallel/reshard_utils.h
  paddle/phi/core/visit_type.h
  paddle/phi/infermeta/spmd_rules/elementwise.cc
  paddle/phi/infermeta/spmd_rules/elementwise.h
  paddle/phi/kernels/cpu/elementwise_divide_grad_kernel.cc
  paddle/phi/kernels/cpu/elementwise_divide_kernel.cc
  paddle/phi/kernels/gpu/elementwise_grad_kernel.cu
  paddle/phi/kernels/kps/elementwise_kernel.cu
  paddle/phi/kernels/legacy/cpu/elementwise_divide_kernel.cc
  paddle/phi/kernels/legacy/kps/elementwise_kernel.cu
  test/auto_parallel/CMakeLists.txt
  test/auto_parallel/semi_auto_parallel_for_bitwise.py
  test/auto_parallel/semi_auto_parallel_for_compare.py
  test/auto_parallel/semi_auto_parallel_for_elementwise.py
  test/auto_parallel/test_semi_auto_parallel_basic.py
Labels: contributor
