Repository PaddlePaddle/Paddle, pull requests merged in 2023-08, with the labels that each got.

#55657 [IR Operation] ⚔Elden chapter 1.3⚔
  paddle/fluid/pybind/ir.cc
  paddle/ir/core/operation.cc
  paddle/ir/core/operation.h
Labels: contributor, HappyOpenSource

#55784 print dialect name before type
  paddle/fluid/ir/dialect/pd_dialect.cc
Labels: contributor, status: proposed

#55804 [xdoctest] reformat example code with google style in No.1-No.5
  python/paddle/batch.py
  python/paddle/dataset/image.py
  python/paddle/fft.py
  python/paddle/metric/metrics.py
  python/paddle/onnx/export.py
Labels: contributor, HappyOpenSource

#55815 [clang-tidy] NO.45 enable `bugprone-unused-raii` check
  .clang-tidy
  paddle/fluid/framework/io/crypto/aes_cipher.cc
  paddle/fluid/pybind/generator_py.cc
Labels: contributor, HappyOpenSource

#55849 [xdoctest] reformat example code with google style in No.21-30
  python/paddle/autograd/py_layer.py
  python/paddle/autograd/saved_tensors_hooks.py
  python/paddle/framework/dtype.py
  python/paddle/framework/framework.py
  python/paddle/framework/io.py
  python/paddle/framework/io_utils.py
  python/paddle/framework/random.py
  python/paddle/nn/initializer/Bilinear.py
  python/paddle/nn/initializer/assign.py
  python/paddle/nn/initializer/constant.py
Labels: contributor, HappyOpenSource

#55287 Add FP16 & BF16 for erfinv
  paddle/phi/kernels/gpu/erfinv_grad_kernel.cu
  paddle/phi/kernels/gpu/erfinv_kernel.cu
  paddle/phi/kernels/impl/erfinv_grad_kernel_impl.h
  python/paddle/tensor/math.py
  test/legacy_test/test_erfinv_op.py
Labels: contributor, HappyOpenSource

#55824 Modify the documentation description of poisson
  python/paddle/tensor/random.py
Labels: contributor, HappyOpenSource

#55774 [clang-tidy] NO.6 enable `modernize-avoid-c-arrays` check
  paddle/ir/core/builtin_op.cc
  paddle/ir/core/ir_printer.cc
  paddle/ir/core/op_info_impl.cc
  paddle/phi/backends/cpu/cpu_info.cc
  paddle/phi/backends/dynload/dynamic_loader.cc
  paddle/phi/backends/dynload/port.cc
  paddle/phi/backends/gpu/cuda/cuda_graph.cc
  paddle/phi/core/distributed/store/socket.cpp
  paddle/phi/core/enforce.cc
  paddle/phi/core/flags.cc
  paddle/phi/core/flags.h
  paddle/phi/kernels/funcs/gpc.cc
  paddle/phi/kernels/funcs/jit/gen/act.cc
  paddle/phi/kernels/funcs/jit/kernel_key.cc
  paddle/utils/string/pretty_log.cc
Labels: contributor, HappyOpenSource

#55897 Fix random seed of test_eig_op
  test/legacy_test/test_eig_op.py
Labels: NVIDIA, contributor

#55806 [xdoctest] reformat example code with google style No.80-85
  python/paddle/nn/functional/pooling.py
  python/paddle/nn/functional/sparse_attention.py
  python/paddle/nn/layer/activation.py
  python/paddle/nn/layer/common.py
  python/paddle/nn/layer/layers.py
Labels: contributor, HappyOpenSource

#55812 [xdoctest] reformat example code with google style in No.86-90
  python/paddle/nn/layer/norm.py
  python/paddle/nn/layer/pooling.py
  python/paddle/nn/layer/rnn.py
  python/paddle/nn/layer/transformer.py
  python/paddle/nn/layer/vision.py
Labels: contributor, HappyOpenSource

#55834 [xdoctest] reformat example code with google style in No.95-99
  python/paddle/nn/quant/quant_layers.py
  python/paddle/nn/quant/stub.py
  python/paddle/nn/utils/clip_grad_norm_.py
  python/paddle/nn/utils/clip_grad_value_.py
  python/paddle/nn/utils/spectral_norm_hook.py
Labels: contributor, HappyOpenSource

#55912 [Change] change global_exec
  tools/sampcd_processor_xdoctest.py
  tools/test_sampcd_processor_xdoctest.py
Labels: contributor, status: proposed

#55919 [xdoctest][task 60-64] reformat example code with google style in `geometric/*` ,`hapi/callbacks.py`
  python/paddle/geometric/math.py
  python/paddle/geometric/message_passing/send_recv.py
  python/paddle/geometric/reindex.py
  python/paddle/geometric/sampling/neighbors.py
  python/paddle/hapi/callbacks.py
Labels: contributor, HappyOpenSource

#55925 [xdoctest] reformat example code with google style in No.11
  python/paddle/audio/backends/backend.py
Labels: contributor, HappyOpenSource

#55895 [clang-tidy][task 46] enable `modernize-avoid-bind`
  .clang-tidy
  paddle/fluid/framework/dist_multi_trainer.cc
  paddle/fluid/framework/multi_trainer.cc
  paddle/fluid/framework/op_desc.cc
  paddle/fluid/framework/operator.cc
  paddle/phi/core/threadpool.cc
Labels: contributor, HappyOpenSource

#55894 [clang-tidy] update pre-commit clang-tidy hook
  tools/codestyle/clang-tidy.py
Labels: contributor, HappyOpenSource

#55948 [FLUID]: move limit_by_capacity to PHI
  paddle/fluid/operators/limit_by_capacity_op.cc
  paddle/fluid/operators/limit_by_capacity_op.cu
  paddle/fluid/operators/limit_by_capacity_op.h
  paddle/phi/kernels/cpu/limit_by_capacity_kernel.cc
  paddle/phi/kernels/gpu/limit_by_capacity_kernel.cu
  paddle/phi/kernels/limit_by_capacity_kernel.h
  paddle/phi/ops/compat/limit_by_capacity_sig.cc
Labels: contributor, HappyOpenSource

#55832 [xdoctest] reformat example code with google style in No.91-94
  python/paddle/nn/decode.py
  python/paddle/nn/layer/loss.py
  python/paddle/nn/quant/format.py
Labels: contributor, HappyOpenSource

#51321 【PaddlePaddle Hackathon 4】No.63 : add embedding fp16 test
  test/legacy_test/test_lookup_table_v2_op.py
Labels: PaddlePaddle Hackathon, contributor

#55800 [clang-tidy] NO.12 enable `modernize-use-nullptr` check
  .clang-tidy
  paddle/fluid/framework/data_feed.cc
  paddle/fluid/framework/io/crypto/aes_cipher.cc
  paddle/fluid/framework/io/fs.cc
  paddle/fluid/framework/io/shell.cc
  paddle/fluid/framework/ir/multi_devices_graph_pass/fuse_all_reduce_op_pass.cc
  paddle/fluid/inference/capi_exp/pd_config.cc
  paddle/fluid/inference/capi_exp/pd_predictor.cc
  paddle/fluid/inference/capi_exp/pd_utils.cc
  paddle/fluid/memory/allocation/best_fit_allocator_test.cc
  paddle/fluid/memory/allocation/mmap_allocator.cc
  paddle/fluid/operators/pyramid_hash_op.cc
  paddle/fluid/platform/gen_comm_id_helper.cc
  paddle/fluid/platform/init.cc
  paddle/fluid/platform/timer.cc
  paddle/fluid/pybind/eager.cc
  paddle/fluid/pybind/eager_functions.cc
  paddle/fluid/pybind/eager_math_op_patch.cc
  paddle/fluid/pybind/eager_method.cc
  paddle/fluid/pybind/eager_py_layer.cc
  paddle/fluid/pybind/exception.cc
  paddle/fluid/pybind/jit.cc
  paddle/phi/kernels/cpu/eigvals_kernel.cc
  paddle/phi/kernels/funcs/fc_functor.cc
  paddle/phi/kernels/funcs/gpc.cc
  paddle/phi/kernels/funcs/jit/gen/sgd.cc
  paddle/phi/kernels/onednn/matmul_kernel.cc
  paddle/utils/string/string_helper.cc
  test/cpp/fluid/gather_test.cc
  test/cpp/fluid/math/im2col_test.cc
  test/cpp/imperative/test_layer.cc
  test/cpp/phi/kernels/test_cpu_vec.cc
Labels: contributor, HappyOpenSource

#55799 [clang-tidy] enable modernize-use-emplace
  .clang-tidy
  paddle/fluid/distributed/auto_parallel/spmd_rules/common.cc
  paddle/fluid/distributed/collective/reducer.cc
  paddle/fluid/distributed/ps/table/graph/graph_node.cc
  paddle/fluid/distributed/ps/table/ssd_sparse_table.cc
  paddle/fluid/framework/attribute_test.cc
  paddle/fluid/framework/data_feed.cc
  paddle/fluid/framework/data_set.cc
  paddle/fluid/framework/dist_multi_trainer.cc
  paddle/fluid/framework/downpour_worker.cc
  paddle/fluid/framework/downpour_worker_opt.cc
  paddle/fluid/framework/io/fs.cc
  paddle/fluid/framework/ir/embedding_eltwise_layernorm_fuse_pass.cc
  paddle/fluid/framework/multi_trainer.cc
  paddle/fluid/framework/new_executor/executor_statistics.cc
  paddle/fluid/framework/new_executor/interpreter/data_transfer.cc
  paddle/fluid/framework/op_def_api.cc
  paddle/fluid/framework/op_desc_test.cc
  paddle/fluid/framework/pipeline_trainer.cc
  paddle/fluid/imperative/reducer.cc
  paddle/fluid/inference/api/analysis_predictor.cc
  paddle/fluid/inference/api/api_impl.cc
  paddle/fluid/inference/api/paddle_pass_builder.cc
  paddle/fluid/inference/tensorrt/dynamic_shape_infermeta.cc
  paddle/fluid/inference/utils/table_printer.cc
  paddle/fluid/ir/transforms/pd_op_to_kernel_pass.cc
  paddle/fluid/ir_adaptor/translator/op_translator.cc
  paddle/fluid/memory/allocation/virtual_memory_auto_growth_best_fit_allocator.cc
  paddle/fluid/memory/malloc_test.cu
  paddle/fluid/memory/stream_safe_cuda_alloc_test.cu
  paddle/fluid/operators/fused/mkldnn/multi_gru_mkldnn_op.cc
  paddle/fluid/operators/math/tree2col.cc
  paddle/fluid/platform/profiler/dump/test_serialization_logger.cc
  paddle/fluid/platform/profiler/test_event_node.cc
  paddle/ir/core/ir_printer.cc
  paddle/phi/api/lib/op_meta_info.cc
  paddle/utils/string/string_helper_test.cc
  test/cpp/fluid/reader/reader_blocking_queue_test.cc
  test/cpp/phi/kernels/test_fused_adam_kernel.cc
Labels: contributor, HappyOpenSource

#55935 [CINN] Dump more compilation result and optimize parallel compiler flags
  paddle/cinn/auto_schedule/tests/performance_comparison_test.cc
  paddle/cinn/backends/compiler.cc
  paddle/cinn/backends/compiler.h
  paddle/cinn/hlir/framework/graph.cc
  paddle/cinn/hlir/framework/graph.h
  paddle/cinn/hlir/framework/graph_compiler.cc
  paddle/cinn/hlir/framework/instruction.cc
  paddle/cinn/hlir/framework/instruction.h
  paddle/cinn/hlir/framework/parallel_compiler.cc
  paddle/cinn/hlir/framework/parallel_compiler.h
  paddle/cinn/hlir/framework/visualize_helper.cc
  paddle/cinn/hlir/framework/visualize_helper.h
  paddle/cinn/runtime/flags.cc
Labels: contributor, status: proposed

#55757 repacle embedding in fluid with 2.0 version
  python/paddle/fluid/layers/nn.py
  python/paddle/incubate/distributed/fleet/parameter_server/distribute_transpiler/__init__.py
  python/paddle/incubate/distributed/fleet/parameter_server/pslib/__init__.py
  test/auto_parallel/test_dist_embedding.py
  test/book/notest_understand_sentiment.py
  test/book/test_recommender_system.py
  test/book/test_word2vec_book.py
  test/ipu/distributed/test_dist_pod128_sample.py
  test/ipu/distributed/test_dist_sample.py
  test/ipu/test_lookuptable_op_ipu.py
  test/ipu/test_weight_sharing_ipu.py
  test/ir/test_ir_embedding_eltwise_layernorm_fuse_pass.py
  test/legacy_test/dist_ctr.py
  test/legacy_test/dist_fleet_ctr.py
  test/legacy_test/dist_fleet_heter_pipeline_ctr.py
  test/legacy_test/dist_text_classification.py
  test/legacy_test/dist_word2vec.py
  test/legacy_test/fleet_heter_ps_training.py
  test/legacy_test/nets.py
  test/legacy_test/simple_nets.py
  test/legacy_test/test_communicator_geo.py
  test/legacy_test/test_dist_fleet_a_sync_optimizer_auto_async.py
  test/legacy_test/test_dist_fleet_a_sync_optimizer_auto_geo.py
  test/legacy_test/test_dist_fleet_heter_program.py
  test/legacy_test/test_dist_fleet_ps.py
  test/legacy_test/test_dist_fleet_ps3.py
  test/legacy_test/test_dist_fleet_ps5.py
  test/legacy_test/test_dist_sparse_load_ps0.py
  test/legacy_test/test_dist_sparse_tensor_load_sgd.py
  test/legacy_test/test_dist_transpiler.py
  test/legacy_test/test_downpoursgd.py
  test/legacy_test/test_eager_deletion_padding_rnn.py
  test/legacy_test/test_entry_attr2.py
  test/legacy_test/test_fleet.py
  test/legacy_test/test_fleet_base_2.py
  test/legacy_test/test_fleet_nocvm_1.py
  test/legacy_test/test_fleet_unitaccessor.py
  test/legacy_test/test_gradient_clip.py
  test/legacy_test/test_hsigmoid_op.py
  test/legacy_test/test_layers.py
  test/legacy_test/test_lookup_table_bf16_op.py
  test/legacy_test/test_lookup_table_op.py
  test/legacy_test/test_monitor.py
  test/legacy_test/test_regularizer.py
  test/legacy_test/test_regularizer_api.py
  test/legacy_test/test_sgd_op_bf16.py
  test/legacy_test/test_weight_decay.py
  test/legacy_test/transformer_model.py
Labels: contributor, status: proposed

#56006 Fix typos in dy2st unittests
  test/dygraph_to_static/ifelse_simple_func.py
  test/dygraph_to_static/seq2seq_dygraph_model.py
  test/dygraph_to_static/test_ifelse.py
  test/dygraph_to_static/test_jit_property_save.py
  test/dygraph_to_static/test_jit_setitem.py
  test/dygraph_to_static/test_origin_info.py
  test/dygraph_to_static/test_program_translator.py
  test/dygraph_to_static/test_resnet_amp.py
  test/dygraph_to_static/test_seq2seq.py
  test/dygraph_to_static/test_tensor_shape.py
Labels: contributor, status: proposed

#56005 Fix typos, test=document_fix
  test/amp/amp_base_models.py
  test/amp/test_amp_master_grad_static.py
  test/amp/test_model_cast_to_bf16.py
  test/amp/test_tensor_checker.py
  test/legacy_test/test_nan_inf.py
Labels: contributor, status: proposed

#56001 Update profiler.py
  python/paddle/profiler/profiler.py
Labels: contributor, status: proposed

#55999 fix cholesky_solve document bug
  python/paddle/tensor/linalg.py
Labels: contributor, status: proposed

#56008 Fix typos
  test/collective/fleet/hybrid_parallel_mp_amp.py
  test/collective/fleet/hybrid_parallel_mp_bf16.py
  test/collective/fleet/hybrid_parallel_mp_broadcast_obj.py
  test/collective/fleet/hybrid_parallel_mp_clip_grad.py
  test/collective/fleet/hybrid_parallel_mp_fp16.py
  test/collective/fleet/hybrid_parallel_mp_layers.py
  test/collective/fleet/hybrid_parallel_mp_model.py
  test/collective/fleet/hybrid_parallel_mp_model_with_sequence_parallel.py
  test/collective/fleet/hybrid_parallel_mp_random.py
  test/collective/fleet/hybrid_parallel_pp_amp.py
  test/collective/fleet/hybrid_parallel_pp_bf16.py
  test/collective/fleet/hybrid_parallel_pp_clip_grad.py
  test/collective/fleet/hybrid_parallel_pp_embedding.py
  test/collective/fleet/hybrid_parallel_pp_fp16.py
  test/collective/fleet/hybrid_parallel_pp_recompute.py
  test/collective/fleet/hybrid_parallel_pp_save_load.py
  test/collective/fleet/hybrid_parallel_pp_save_load_with_virtual_stage.py
  test/collective/fleet/hybrid_parallel_pp_transformer.py
  test/collective/fleet/hybrid_parallel_pp_transformer_save.py
  test/collective/fleet/hybrid_parallel_pp_transformer_save_with_virtual_stage.py
  test/collective/fleet/hybrid_parallel_pp_transformer_unbalanced_data.py
  test/collective/fleet/hybrid_parallel_pp_transformer_with_virtual_stage.py
  test/collective/fleet/hybrid_parallel_qat.py
  test/collective/fleet/hybrid_parallel_sharding_model.py
  test/collective/fleet/hybrid_parallel_shared_weight.py
  test/collective/fleet/parallel_dygraph_no_sync_gradient_check.py
  test/collective/fleet/test_fleet_static_mp_layers.py
  test/legacy_test/auto_parallel_gpt_model.py
  test/legacy_test/benchmark_sum_op.py
  test/legacy_test/dist_fleet_ctr.py
  test/legacy_test/dist_hapi_mnist_dynamic.py
  test/legacy_test/dist_hapi_mnist_static.py
  test/legacy_test/dist_hapi_pure_fp16_static.py
  test/legacy_test/gradient_checker.py
  test/legacy_test/hybrid_parallel_pp_alexnet.py
  test/legacy_test/parallel_dygraph_dataparallel_with_pylayer.py
  test/legacy_test/parallel_dygraph_gradient_check.py
  test/legacy_test/parallel_dygraph_gradient_check_in_eager_mode.py
  test/xpu/parallel_dygraph_dataparallel_with_pylayer.py
  test/xpu/parallel_dygraph_gradient_check.py
  test/xpu/parallel_dygraph_gradient_check_in_eager_mode.py
Labels: contributor, status: proposed

#55813 [xdoctest] No.44-47 and No.50-59 doc style
  python/paddle/distribution/cauchy.py
  python/paddle/distribution/independent.py
  python/paddle/distribution/kl.py
  python/paddle/distribution/laplace.py
  python/paddle/distribution/lognormal.py
  python/paddle/distribution/multinomial.py
  python/paddle/distribution/normal.py
  python/paddle/distribution/transform.py
  python/paddle/distribution/transformed_distribution.py
Labels: contributor, HappyOpenSource Pro

#55959 [XPU] Fix linspace op do data transform error on xpu1 device when execute fall back to cpu
  paddle/phi/api/yaml/static_ops.yaml
Labels: contributor, status: not progressed

#54451 [cmake] add xpu and paddle2onnx third_party cache
  cmake/external/paddle2onnx.cmake
  cmake/external/xpu.cmake
Labels: contributor, HappyOpenSource

#55903 Provide opoperands(), opresults() methods for the Operation module
  paddle/fluid/pybind/ir.cc
  paddle/ir/core/operation.cc
  paddle/ir/core/operation.h
  test/ir/new_ir/test_ir_pybind.py
Labels: contributor, HappyOpenSource

#55896 Fix random seed of test_lu_op
  test/legacy_test/test_lu_op.py
Labels: NVIDIA, contributor

#56016 Open FLAGS_new_executor_static_build in auto_parallel
  python/paddle/distributed/auto_parallel/static/engine.py
Labels: contributor, status: proposed

#56054 [XPU] update ut threshold for depthwise_conv2d.
  cmake/external/xpu.cmake
  test/xpu/test_depthwise_conv2d_op_xpu.py
Labels: contributor, status: proposed

#55884 Fatal bug fix for hapi.eval
  python/paddle/hapi/model.py
Labels: contributor, status: proposed

#56073 Fix error in docstring for flatten function
  python/paddle/tensor/manipulation.py
Labels: contributor, status: not progressed

#56064 [XPU] register multiclass_nms3 and norm xpu kernel to optimize model …
  paddle/phi/backends/xpu/xpu2_op_list.cc
  paddle/phi/kernels/xpu/multiclass_nms3_kernel.cc
  paddle/phi/kernels/xpu/norm_kernel.cc
  test/xpu/test_multiclass_nms3_op_xpu.py
  test/xpu/test_norm_op_xpu.py
Labels: contributor, status: proposed

#56003 move dgc kernel to phi
  paddle/fluid/framework/operator.cc
  paddle/fluid/operators/dgc_op.cc
  paddle/fluid/operators/dgc_op.cu
  paddle/fluid/operators/dgc_op.h
  paddle/phi/CMakeLists.txt
  paddle/phi/kernels/CMakeLists.txt
  paddle/phi/kernels/dgc_kernel.h
  paddle/phi/kernels/gpu/dgc_kernel.cu
Labels: contributor, HappyOpenSource Pro

#55995 move `decayed_adagrad_op` to phi
  paddle/fluid/operators/optimizers/decayed_adagrad_op.cc
  paddle/fluid/operators/optimizers/decayed_adagrad_op.cu
  paddle/fluid/operators/optimizers/decayed_adagrad_op.h
  paddle/phi/infermeta/multiary.cc
  paddle/phi/infermeta/multiary.h
  paddle/phi/kernels/cpu/decayed_adagrad_kernel.cc
  paddle/phi/kernels/decayed_adagrad_kernel.h
  paddle/phi/kernels/gpu/decayed_adagrad_kernel.cu
  paddle/phi/kernels/impl/decayed_adagrad_kernel_impl.h
  paddle/phi/ops/compat/decayed_adagrad_sig.cc
  test/legacy_test/test_decayed_adagrad_op.py
Labels: contributor, HappyOpenSource Pro

#55966 [xdoctest] reformat example code with google style in 78
  python/paddle/nn/functional/input.py
Labels: contributor, HappyOpenSource Pro

#56069 Reduce the workspace for TRT index_select UT
  test/ir/inference/test_trt_convert_index_select.py
Labels: NVIDIA, contributor

#56068 fix: support str_value of Scalar is bool dtype
  paddle/phi/common/scalar.h
Labels: contributor, status: proposed

#55001 [XPU] add pos_weight for sigmoid_cross_entropy_with_logits.
  paddle/phi/kernels/xpu/sigmoid_cross_entropy_with_logits_grad_kernel.cc
  paddle/phi/kernels/xpu/sigmoid_cross_entropy_with_logits_kernel.cc
  test/xpu/test_sigmoid_cross_entropy_with_logits_op_xpu.py
Labels: contributor, status: proposed

#55914 [XPU] add fused_softmax_mask and fused_softmax_mask_grad.
  paddle/phi/backends/xpu/xpu2_op_list.cc
  paddle/phi/kernels/fusion/xpu/fused_softmax_mask_grad_kernel.cc
  paddle/phi/kernels/fusion/xpu/fused_softmax_mask_kernel.cc
  test/xpu/test_fused_softmax_mask_op_xpu.py
Labels: contributor, status: proposed

#56051 [xdoctest] reformat example code with google style in No.31-35
  python/paddle/nn/initializer/dirac.py
  python/paddle/nn/initializer/initializer.py
  python/paddle/nn/initializer/kaiming.py
  python/paddle/nn/initializer/normal.py
  python/paddle/nn/initializer/orthogonal.py
Labels: contributor, HappyOpenSource Pro

#56056 Add FP16 & BF16 for nanmedian
  paddle/phi/kernels/gpu/nanmedian_grad_kernel.cu
  paddle/phi/kernels/gpu/nanmedian_kernel.cu
  python/paddle/tensor/stat.py
  test/legacy_test/test_nanmedian.py
Labels: contributor, HappyOpenSource

#55950 [XPU kernel] fix warpctc issue
  paddle/phi/kernels/xpu/warpctc_kernel.cc
Labels: contributor, status: proposed

#56093 feat(hihg-performance): use std::move to instead of copy-ctor
  paddle/phi/core/enforce.h
Labels: contributor

#56123 Refine interface of hlir::framework::Instruction
  paddle/cinn/hlir/framework/instruction.cc
  paddle/cinn/hlir/framework/instruction.h
  paddle/cinn/hlir/framework/program.cc
Labels: contributor, status: proposed

#55549 [cmake] add absl third_party cache
  cmake/cinn.cmake
  cmake/cinn/external/absl.cmake
Labels: contributor, HappyOpenSource

#56152 [NewIR]Remove framework_proto DEPS in pd_dialect
  paddle/fluid/ir/dialect/CMakeLists.txt
Labels: contributor, status: proposed

#55986 move some fluid apis
  python/paddle/__init__.py
  python/paddle/distributed/fleet/meta_optimizers/localsgd_optimizer.py
  python/paddle/distributed/passes/ps_server_pass.py
  python/paddle/fluid/initializer.py
  python/paddle/fluid/layers/__init__.py
  python/paddle/fluid/layers/learning_rate_scheduler.py
  python/paddle/fluid/layers/nn.py
  python/paddle/incubate/distributed/fleet/parameter_server/ir/public.py
  python/paddle/nn/initializer/initializer.py
  python/paddle/nn/initializer/lazy_init.py
  python/paddle/optimizer/lr.py
  python/paddle/static/__init__.py
  python/paddle/static/nn/common.py
  test/collective/fleet/parallel_dygraph_se_resnext.py
  test/legacy_test/dist_se_resnext.py
  test/legacy_test/test_dist_transpiler.py
  test/legacy_test/test_imperative_ocr_attention_model.py
  test/legacy_test/test_imperative_resnet.py
  test/legacy_test/test_imperative_resnet_sorted_gradient.py
  test/legacy_test/test_imperative_transformer_sorted_gradient.py
  test/legacy_test/test_learning_rate_scheduler.py
Labels: contributor, status: proposed

#55345 repacle fluid.io.load_inference_model, fluid.io.save_inference_model in fluid with 2.0 version
  python/paddle/distributed/fleet/runtime/parameter_server_runtime.py
  python/paddle/fluid/io.py
  python/paddle/hapi/model.py
  python/paddle/incubate/distributed/fleet/collective.py
  python/paddle/incubate/distributed/fleet/fleet_util.py
  python/paddle/incubate/distributed/fleet/utils.py
  python/paddle/jit/api.py
  python/paddle/static/io.py
  test/book/notest_understand_sentiment.py
  test/book/test_image_classification.py
  test/book/test_recognize_digits.py
  test/book/test_recommender_system.py
  test/book/test_word2vec_book.py
  test/cinn/fake_model/resnet_model.py
  test/cinn/test_paddle_model_convertor.py
  test/contrib/test_image_classification_fp16.py
  test/dygraph_to_static/test_bert.py
  test/dygraph_to_static/test_bmn.py
  test/dygraph_to_static/test_lac.py
  test/dygraph_to_static/test_mnist.py
  test/dygraph_to_static/test_mobile_net.py
  test/dygraph_to_static/test_resnet.py
  test/dygraph_to_static/test_save_inference_model.py
  test/dygraph_to_static/test_se_resnet.py
  test/ir/inference/inference_pass_test.py
  test/ir/inference/program_config.py
  test/ir/inference/quant_dequant_test.py
  test/legacy_test/test_dist_base.py
  test/legacy_test/test_dist_mnist_fleet_save.py
  test/legacy_test/test_eager_deletion_padding_rnn.py
  test/legacy_test/test_executor_and_use_program_cache.py
  test/legacy_test/test_inference_model_io.py
  test/legacy_test/test_io_save_load.py
  test/legacy_test/test_load_state_dict_from_old_format.py
  test/legacy_test/test_save_model_without_var.py
  test/quantization/convert_model2dot.py
  test/quantization/quant2_int8_image_classification_comparison.py
  test/quantization/quant_int8_image_classification_comparison.py
  tools/cinn/paddle_benchmark/paddle_save_model.py
  tools/cinn/paddle_benchmark/test_paddle_ops.py
Labels: contributor, status: proposed

#56167 [xdoctest][task 105]reformat example code with google style in python/paddle/optimizer/adamax.py
  python/paddle/optimizer/adamax.py
Labels: contributor, HappyOpenSource Pro

#56099 remove the optimizer base and learning rate base
  python/paddle/amp/auto_cast.py
  python/paddle/distributed/auto_parallel/static/engine.py
  python/paddle/distributed/fleet/meta_optimizers/dgc_optimizer.py
  python/paddle/fluid/__init__.py
  python/paddle/fluid/dygraph/__init__.py
  python/paddle/fluid/dygraph/learning_rate_scheduler.py
  python/paddle/fluid/optimizer.py
  python/paddle/incubate/distributed/fleet/base.py
  python/paddle/incubate/distributed/fleet/parameter_server/distribute_transpiler/__init__.py
  python/paddle/incubate/optimizer/distributed_fused_lamb.py
  python/paddle/incubate/optimizer/pipeline.py
  python/paddle/optimizer/optimizer.py
  python/paddle/static/__init__.py
  python/paddle/static/amp/decorator.py
  test/legacy_test/test_dist_transpiler.py
  test/legacy_test/test_imperative_save_load_v2.py
Labels: contributor, status: proposed

#56168 [cmake] add boost third_party cache
  cmake/cinn/external/boost.cmake
Labels: contributor, HappyOpenSource

#56211 [xdoctest] reformat example code with google style in No. 212
  python/paddle/distributed/communicator.py
Labels: contributor

#56212 [xdoctest] reformat example code with google style in No. 214
  python/paddle/distributed/fleet/base/private_helper_function.py
Labels: contributor

#55968 [xdoctest] reformat example code with google style in No 101
  python/paddle/nn/utils/weight_norm_hook.py
Labels: contributor, HappyOpenSource Pro

#55769 [Fluid] Move fused_softmax_mask_upper_triangle to phi
  paddle/fluid/operators/fused_softmax_mask_upper_triangle_op.cc
  paddle/fluid/operators/fused_softmax_mask_upper_triangle_op.cu
  paddle/fluid/operators/fused_softmax_mask_upper_triangle_op.h
  paddle/phi/kernels/fused_softmax_mask_upper_triangle_kernel.h
  paddle/phi/kernels/fusion/cpu/fused_softmax_mask_upper_triangle_kernel.cc
  paddle/phi/kernels/fusion/gpu/fused_softmax_mask_upper_triangle_grad_kernel.cu
  paddle/phi/kernels/fusion/gpu/fused_softmax_mask_upper_triangle_kernel.cu
  paddle/phi/kernels/fusion/gpu/fused_softmax_mask_upper_triangle_utils.h
  paddle/phi/ops/compat/fused_softmax_mask_upper_triangle_sig.cc
  test/legacy_test/test_softmax_mask_fuse_upper_triangle_op.py
Labels: contributor, HappyOpenSource Pro

#56228 [xdoctest][task 112] Reformat example code with google style in python/paddle/optimizer/sgd.py
  python/paddle/optimizer/sgd.py
Labels: contributor, HappyOpenSource Pro

#56227 [xdoctest][task 111] Reformat example code with google style in python/paddle/optimizer/rmsprop.py
  python/paddle/optimizer/rmsprop.py
Labels: contributor, HappyOpenSource Pro

#56226 [xdoctest][task 110] Reformat example code with google style in python/paddle/optimizer/momentum.py
  python/paddle/optimizer/momentum.py
Labels: contributor, HappyOpenSource Pro

#56222 [xdoctest][task 106] Reformat example code with google style in python/paddle/optimizer/adamw.py
  python/paddle/optimizer/adamw.py
Labels: contributor, HappyOpenSource Pro

#56053 [AMP][Custom Device] add fp16 op detection for custom device
  paddle/fluid/imperative/amp_auto_cast.cc
  python/paddle/static/amp/fp16_lists.py
Labels: contributor, status: proposed

#56234 [xdoctest][task 123] Reformat example code with google style in python/paddle/quantization/quanters/abs_max.py
  python/paddle/quantization/quanters/abs_max.py
Labels: contributor, HappyOpenSource Pro

#56213 [xdoctest] reformat example code with google style in No. 231
  python/paddle/distributed/parallel_with_gloo.py
Labels: contributor, HappyOpenSource Pro

#56171 [xdoctest] reformat example code with google style in 202
  python/paddle/distributed/communication/all_gather.py
  python/paddle/distributed/communication/stream/all_gather.py
Labels: contributor, HappyOpenSource Pro

#56191 把p_norm_kernel.cu和p_norm_grad_kernel.cu的公共函数写入到 p_norm_utils.h中
  paddle/phi/kernels/funcs/p_norm_utils.h
  paddle/phi/kernels/gpu/p_norm_kernel.cu
Labels: contributor, status: proposed

#56246 [clang-tidy] NO.66 enable `bugprone-integer-division`
  .clang-tidy
  paddle/fluid/framework/details/scope_buffered_monitor.cc
Labels: contributor, HappyOpenSource Pro

#56219 [clang-tidy] No.51 enable bugprone-copy-constructor-init
  .clang-tidy
  paddle/phi/core/dense_tensor.cc
  paddle/phi/core/sparse_coo_tensor.cc
  paddle/phi/core/sparse_csr_tensor.cc
  paddle/phi/core/string_tensor.cc
Labels: contributor, HappyOpenSource Pro

#56217 [clang-tidy] No.52 enable bugprone-argument-comment
  .clang-tidy
  paddle/fluid/framework/executor_cache.cc
  paddle/fluid/framework/new_executor/interpreter/stream_analyzer.cc
  paddle/fluid/framework/parallel_executor.cc
Labels: contributor, HappyOpenSource Pro

#56216 [clang-tidy] No.31 enable modernize-use-bool-literals
  .clang-tidy
  paddle/fluid/framework/hogwild_worker.cc
  paddle/fluid/framework/io/shell.cc
  paddle/fluid/framework/ir/transfer_layout_elim_pass.cc
  paddle/fluid/framework/trainer.cc
  paddle/fluid/inference/analysis/ir_pass_manager.cc
  paddle/fluid/inference/api/analysis_predictor.cc
  paddle/fluid/inference/api/onnxruntime_predictor.cc
  paddle/fluid/memory/allocation/buddy_allocator.cc
  paddle/fluid/operators/fused/fused_embedding_eltwise_layernorm_op.cc
  paddle/fluid/operators/fused/fused_seqpool_cvm_op.cc
  paddle/fluid/operators/generator/get_expected_kernel_func.cc
  paddle/fluid/operators/partial_concat_op.cc
  paddle/fluid/operators/partial_sum_op.cc
  paddle/phi/api/profiler/device_tracer.cc
  paddle/phi/kernels/funcs/gpc.cc
Labels: contributor, HappyOpenSource Pro

#56208 [clang-tidy] NO.7 enable `cppcoreguidelines-avoid-c-arrays`
  .clang-tidy
  paddle/fluid/operators/controlflow/conditional_block_op.cc
  paddle/fluid/operators/recurrent_op.cc
  paddle/fluid/pybind/eager.cc
  paddle/fluid/pybind/eager_functions.cc
  paddle/fluid/pybind/eager_math_op_patch.cc
  paddle/fluid/pybind/eager_method.cc
  paddle/fluid/pybind/eager_properties.cc
  paddle/fluid/pybind/ops_api.cc
  paddle/phi/backends/cpu/cpu_info.cc
  paddle/phi/kernels/funcs/strided_reshape_utils.cc
  test/cpp/phi/api/test_strings_lower_upper_api.cc
  test/cpp/phi/kernels/test_strings_lower_upper_dev_api.cc
Labels: contributor, HappyOpenSource Pro

#56134 [clang-tidy] skip check when not find compilation db
  tools/codestyle/clang-tidy.py
Labels: contributor, HappyOpenSource Pro

#56113 Add WITH_MKLDNN check into target test_save_optimized_model_pass
  test/ir/inference/CMakeLists.txt
Labels: NVIDIA, contributor

#56118 [xdoctest] reformat example code with google style No.116-119
  python/paddle/optimizer/optimizer.py
  python/paddle/quantization/config.py
  python/paddle/quantization/factory.py
  python/paddle/quantization/imperative/qat.py
Labels: contributor, HappyOpenSource Pro

#56210 [xdoctest] reformat example code with google style in No.12-No.15
  python/paddle/audio/backends/init_backend.py
  python/paddle/audio/backends/wave_backend.py
  python/paddle/audio/datasets/esc50.py
  python/paddle/audio/datasets/tess.py
Labels: contributor, HappyOpenSource Pro

#56253 [clang-tidy] NO.62,63 enable `clang-analyzer-security.insecureAPI.vfork`、`clang-analyzer-unix.Vfork`
  .clang-tidy
  paddle/fluid/framework/io/shell.cc
Labels: contributor, HappyOpenSource Pro

#56184 [dtype] add fp16 support for dist_kernel
  paddle/phi/kernels/dist_grad_kernel.cc
  paddle/phi/kernels/gpu/dist_kernel.cu
  python/paddle/tensor/linalg.py
  test/legacy_test/test_dist_op.py
Labels: contributor, HappyOpenSource

#56239 [xdoctest][task 142] Reformat example code with google style in quantization/quant_int8_mkldnn_pass.py
  python/paddle/static/quantization/quant_int8_mkldnn_pass.py
Labels: contributor, HappyOpenSource Pro

#56260 Update README.md
  README.md
  README_cn.md
  README_ja.md
Labels: contributor, status: proposed

#56231 [xdoctest][task 120] Reformat example code with google style in python/paddle/quantization/observers/abs_max.py
  python/paddle/quantization/observers/abs_max.py
Labels: contributor, HappyOpenSource Pro

#56224 [xdoctest][task 108] Reformat example code with google style in python/paddle/optimizer/lbfgs.py
  python/paddle/optimizer/lbfgs.py
Labels: contributor, HappyOpenSource Pro

#56124 [xdoctest] reformat example code with google style No.102-104
  python/paddle/optimizer/adadelta.py
  python/paddle/optimizer/adagrad.py
  python/paddle/optimizer/adam.py
Labels: contributor, HappyOpenSource Pro

#55953 [xdoctest] reformat example code with google style in No.65-68
  python/paddle/hapi/dynamic_flops.py
  python/paddle/hapi/hub.py
  python/paddle/hapi/model.py
  python/paddle/hapi/model_summary.py
  python/paddle/tensor/math.py
Labels: contributor, HappyOpenSource Pro

#56129 [Fluid] NO.1 Migrate c_embedding to PHI
  paddle/fluid/operators/collective/c_embedding_op.cc
  paddle/fluid/operators/collective/c_embedding_op.cu
  paddle/fluid/operators/collective/c_embedding_op.h
  paddle/fluid/operators/collective/c_embedding_op_xpu.cc
  paddle/phi/kernels/c_embedding_grad_kernel.h
  paddle/phi/kernels/c_embedding_kernel.h
  paddle/phi/kernels/cpu/c_embedding_grad_kernel.cc
  paddle/phi/kernels/cpu/c_embedding_kernel.cc
  paddle/phi/kernels/gpu/c_embedding_grad_kernel.cu
  paddle/phi/kernels/gpu/c_embedding_kernel.cu
  paddle/phi/kernels/xpu/c_embedding_kernel.cc
  paddle/phi/kernels/xpu/c_embedding_kernel_grad.cc
  paddle/phi/ops/compat/c_embedding_sig.cc
  test/legacy_test/c_embedding_op_base.py
Labels: contributor, HappyOpenSource Pro

#55794 [Fluid] move assign_pos to phi
  paddle/fluid/operators/assign_pos_op.cc
  paddle/fluid/operators/assign_pos_op.cu
  paddle/fluid/operators/assign_pos_op.h
  paddle/phi/kernels/assign_pos_kernel.h
  paddle/phi/kernels/cpu/assign_pos_kernel.cc
  paddle/phi/kernels/gpu/assign_pos_kernel.cu
  paddle/phi/ops/compat/assign_pos_sig.cc
  test/legacy_test/test_assign_pos_op.py
Labels: contributor, HappyOpenSource Pro

#55507 [ROCM]:Delete the special target and fix compiler options
  paddle/fluid/framework/ir/fusion_group/cuda_resources.h
  paddle/phi/backends/device_code.cc
Labels: contributor, status: proposed

#56158 move dgc_momentum kernel to phi
  paddle/fluid/operators/optimizers/dgc_momentum_op.cc
  paddle/fluid/operators/optimizers/dgc_momentum_op.h
  paddle/phi/kernels/cpu/dgc_momentum_kernel.cc
  paddle/phi/kernels/dgc_momentum_kernel.h
  paddle/phi/kernels/gpu/dgc_momentum_kernel.cu
  paddle/phi/kernels/impl/dgc_momentum_kernel_impl.h
  paddle/phi/ops/compat/dgc_momentum_sig.cc
Labels: contributor, HappyOpenSource Pro

#56185 Support control flow for static build [Step 1: support subgraph]
  paddle/fluid/framework/new_executor/interpreter/static_build.cc
  paddle/fluid/framework/new_executor/program_interpreter.cc
  test/legacy_test/CMakeLists.txt
Labels: contributor, status: proposed

#56178 [xdoctest] reformat example code with google style in No.150-160
  python/paddle/text/datasets/wmt16.py
  python/paddle/text/viterbi_decode.py
  python/paddle/vision/models/_utils.py
  python/paddle/vision/models/alexnet.py
  python/paddle/vision/models/densenet.py
  python/paddle/vision/models/googlenet.py
  python/paddle/vision/models/inceptionv3.py
  python/paddle/vision/models/lenet.py
  python/paddle/vision/models/mobilenetv1.py
  python/paddle/vision/models/mobilenetv2.py
  python/paddle/vision/models/mobilenetv3.py
Labels: contributor, HappyOpenSource Pro

#56349 【complex op】 No.34 add complex support for dot
  python/paddle/tensor/linalg.py
  test/legacy_test/test_dot_op.py
Labels: contributor, HappyOpenSource

#56379 Update docstrings in `paddle.vision.transforms.functional` to reflect functions accepting Tensors.
  python/paddle/vision/transforms/functional.py
Labels: contributor, status: proposed

#56296 [xdoctest] reformat example code with google style in No.16-No.20
  python/paddle/audio/features/layers.py
  python/paddle/audio/functional/functional.py
  python/paddle/audio/functional/window.py
  python/paddle/autograd/autograd.py
  python/paddle/autograd/backward_mode.py
Labels: contributor, HappyOpenSource Pro

#56340 fix fft bug in DCU
  paddle/phi/backends/dynload/dynamic_loader.cc
Labels: contributor, status: proposed

#56186 [xdoctest][task 198-199] reformat example code with google style in `tensor/*`
  python/paddle/tensor/array.py
  python/paddle/tensor/attribute.py
Labels: contributor, HappyOpenSource Pro

#56358 move dgc_momentum InferShape to phi
  paddle/fluid/operators/optimizers/dgc_momentum_op.cc
  paddle/phi/infermeta/multiary.cc
  paddle/phi/infermeta/multiary.h
Labels: contributor, HappyOpenSource Pro

#56422 [xdoctest] No.161-162 update models docstring for doc xdoctest
  python/paddle/vision/models/resnet.py
  python/paddle/vision/models/shufflenetv2.py
Labels: contributor, HappyOpenSource Pro

#56240 [xdoctest][task 143] Reformat example code with google style in quantization/quantization_pass.py
  python/paddle/quantization/config.py
  python/paddle/quantization/factory.py
  python/paddle/static/quantization/quant_int8_mkldnn_pass.py
  python/paddle/static/quantization/quantization_pass.py
Labels: contributor, HappyOpenSource Pro

#56232 [xdoctest][task 121] Reformat example code with google style in python/paddle/quantization/ptq.py
  python/paddle/quantization/ptq.py
Labels: contributor, HappyOpenSource Pro

#56225 [xdoctest][task 109] Reformat example code with google style in python/paddle/optimizer/lr.py
  python/paddle/optimizer/lr.py
Labels: contributor, HappyOpenSource Pro

#56233 [xdoctest][task 122] Reformat example code with google style in python/paddle/quantization/qat.py
  python/paddle/quantization/qat.py
Labels: contributor, HappyOpenSource Pro

#56235 [xdoctest][task 124] Reformat example code with google style in python/paddle/quantization/quantize.py
  python/paddle/quantization/quantize.py
Labels: contributor, HappyOpenSource Pro

#56230 [xdoctest][task 114] Reformat example code with google style in python/paddle/nn/functional/vision.py
  python/paddle/nn/functional/vision.py
Labels: contributor, HappyOpenSource Pro

#56229 [xdoctest][task 113] Reformat example code with google style in python/paddle/nn/layer/container.py
  python/paddle/nn/layer/container.py
Labels: contributor, HappyOpenSource Pro

#56412 【Complex op】add complex support for numel
  paddle/phi/kernels/cpu/numel_kernel.cc
  paddle/phi/kernels/gpu/numel_kernel.cu
  paddle/phi/kernels/xpu/numel_kernel.cc
  python/paddle/tensor/stat.py
  test/legacy_test/test_numel_op.py
Labels: contributor, HappyOpenSource

#56108 [GLCC]Part-1: Add pylayer op to Support @to_static
  paddle/fluid/operators/controlflow/conditional_block_op.cc
  paddle/fluid/operators/controlflow/control_flow_op_helper.h
  paddle/fluid/operators/controlflow/pylayer_op.cc
  paddle/fluid/operators/controlflow/pylayer_op.h
  paddle/phi/api/yaml/op_compat.yaml
  python/paddle/fluid/framework.py
  python/paddle/static/nn/__init__.py
  python/paddle/static/nn/static_pylayer.py
  test/ir/inference/program_config.py
  test/legacy_test/test_static_pylayer.py
  test/legacy_test/test_static_pylayer_block.py
Labels: contributor, status: proposed

#55590 [CINN] Optimize parallel compiler and support dumping more compilation information
  paddle/cinn/auto_schedule/auto_tuner_test.cc
  paddle/cinn/auto_schedule/measure/measurer_test.cc
  paddle/cinn/auto_schedule/measure/simple_builder.cc
  paddle/cinn/auto_schedule/measure/simple_builder.h
  paddle/cinn/auto_schedule/measure/simple_runner_test.cc
  paddle/cinn/auto_schedule/tests/performance_comparison_test.cc
  paddle/cinn/backends/compiler.h
  paddle/cinn/frontend/computation.cc
  paddle/cinn/frontend/computation.h
  paddle/cinn/frontend/decomposer/activation_test.cc
  paddle/cinn/frontend/decomposer/batch_norm_test.cc
  paddle/cinn/frontend/decomposer/test_helper.h
  paddle/cinn/frontend/decomposer/top_k_test.cc
  paddle/cinn/frontend/interpreter.cc
  paddle/cinn/frontend/net_builder_test.cc
  paddle/cinn/frontend/paddle_model_convertor_test.cc
  paddle/cinn/frontend/pass/decomposer_test.cc
  paddle/cinn/frontend/pass/expand_zero_dim_pass_test.cc
  paddle/cinn/frontend/pass/fill_constant_folding_test.cc
  paddle/cinn/frontend/pass/pass_test_helper.h
  paddle/cinn/frontend/pass/program_topoerror_test.cc
  paddle/cinn/frontend/pass/test_helper.h
  paddle/cinn/frontend/pass/transpose_collapsing_test.cc
  paddle/cinn/frontend/pass/transpose_folding_input_test.cc
  paddle/cinn/frontend/syntax_test.cc
  paddle/cinn/hlir/framework/CMakeLists.txt
  paddle/cinn/hlir/framework/graph_compiler.cc
  paddle/cinn/hlir/framework/graph_compiler.h
  paddle/cinn/hlir/framework/graph_compiler_test.cc
  paddle/cinn/hlir/framework/graph_compiler_util.cc
  paddle/cinn/hlir/framework/graph_compiler_util.h
  paddle/cinn/hlir/framework/parallel_compiler.cc
  paddle/cinn/hlir/framework/parallel_compiler.h
  paddle/cinn/hlir/framework/parallel_compiler_test.cc
  paddle/cinn/hlir/pass/alterlayout_test.cc
  paddle/cinn/hlir/pass/check_fusion_accuracy_pass_test.cc
  paddle/cinn/hlir/pass/common_subexpression_elimination_test.cc
  paddle/cinn/hlir/pass/const_propagate_test.cc
  paddle/cinn/hlir/pass/constant_folding_pass_test.cc
  paddle/cinn/hlir/pass/dense_merge_pass_test.cc
  paddle/cinn/hlir/pass/dot_merger_test.cc
  paddle/cinn/hlir/pass/opfusion_test.cc
  paddle/cinn/hlir/pass/reduce_split_pass_test.cc
  paddle/cinn/hlir/pass/test_primitive_ops.cc
  paddle/cinn/pybind/frontend.cc
  paddle/fluid/framework/paddle2cinn/cinn_compiler.cc
  test/cinn/ops/test_constant_op.py
Labels: contributor, status: proposed

#56438 [xdoctest][task 272-273，282-283] reformat example code with google style in`utils/*`, `tensor/*`
  python/paddle/tensor/stat.py
  python/paddle/tensor/to_string.py
  python/paddle/utils/download.py
  python/paddle/utils/install_check.py
Labels: contributor, HappyOpenSource Pro

#56435 Bugfix, read-write race at fast_ln_fwd_kernel
  paddle/phi/kernels/funcs/layer_norm_impl.cu.h
  paddle/phi/kernels/gpu/layer_norm_kernel.cu
Labels: NVIDIA, contributor

#56303 [OneDNN] cpu_quantize_pass fix
  paddle/fluid/framework/ir/mkldnn/cpu_quantize_pass.cc
  test/cpp/fluid/mkldnn/CMakeLists.txt
  test/cpp/fluid/mkldnn/test_mkldnn_cpu_quantize_pass.cc
Labels: Intel, contributor

#56455 bug fix of operator "interp_linear"
  paddle/phi/kernels/gpu/interpolate_kernel.cu
Labels: contributor, status: proposed

#56327 [Fluid] NO.4 Migrate c_split to PHI
  paddle/fluid/operators/collective/c_split_op.cc
  paddle/fluid/operators/collective/c_split_op.cu
  paddle/fluid/operators/collective/c_split_op.h
  paddle/fluid/operators/collective/c_split_op_xpu.cc
  paddle/phi/kernels/c_split_kernel.h
  paddle/phi/kernels/cpu/c_split_kernel.cc
  paddle/phi/kernels/gpu/c_split_kernel.cu
  paddle/phi/kernels/xpu/c_split_kernel.cc
  paddle/phi/ops/compat/c_split_sig.cc
Labels: contributor, HappyOpenSource Pro

#56476 [xdoctest] reformat example code with google style in No. 270 275-280
  python/paddle/distributed/communication/group.py
  python/paddle/distributed/communication/recv.py
  python/paddle/distributed/communication/reduce.py
  python/paddle/distributed/communication/reduce_scatter.py
  python/paddle/distributed/communication/scatter.py
  python/paddle/distributed/communication/send.py
  python/paddle/utils/cpp_extension/extension_utils.py
Labels: contributor, HappyOpenSource Pro

#56166 [xdoctest] reformat example code with google style No.186-190
  python/paddle/distributed/auto_parallel/static/engine.py
  python/paddle/distributed/auto_parallel/static/process_mesh_v2.py
  python/paddle/distributed/auto_parallel/static/utils.py
  python/paddle/distributed/auto_parallel/strategy.py
  python/paddle/distributed/collective.py
Labels: contributor, HappyOpenSource Pro

#56475 [xdoctest] reformat example code with google style in No. 246 and 247
  python/paddle/incubate/autotune.py
  python/paddle/incubate/distributed/fleet/base.py
Labels: contributor, HappyOpenSource Pro

#56159 [xdoctest][task 171-180] reformat example code with google style in audio/*
  python/paddle/amp/auto_cast.py
  python/paddle/amp/debugging.py
  python/paddle/amp/grad_scaler.py
  python/paddle/device/__init__.py
  python/paddle/device/cuda/__init__.py
  python/paddle/device/xpu/__init__.py
  python/paddle/profiler/profiler.py
  python/paddle/profiler/utils.py
  python/paddle/sparse/binary.py
  python/paddle/sparse/creation.py
Labels: contributor, HappyOpenSource Pro

#55967 [xdoctest] reformat example code with google style in No. 100
  python/paddle/nn/utils/transform_parameters.py
Labels: contributor, HappyOpenSource Pro

#56400 [Change] 利用multiprocessing对xdoctester进行环境隔离
  python/unittest_py/requirements.txt
  tools/sampcd_processor_utils.py
  tools/sampcd_processor_xdoctest.py
  tools/test_sampcd_processor_xdoctest.py
Labels: contributor

#56517 [ROCM]fix bfloat16 to float error!
  paddle/phi/common/bfloat16.h
Labels: contributor, status: proposed

#54803 Integrate TRT qdq layers
  paddle/fluid/inference/analysis/argument.h
  paddle/fluid/inference/api/analysis_config.cc
  paddle/fluid/inference/api/analysis_predictor.cc
  paddle/fluid/inference/api/paddle_analysis_config.h
  paddle/fluid/inference/tensorrt/convert/CMakeLists.txt
  paddle/fluid/inference/tensorrt/convert/dequantize_linear_op.cc
  paddle/fluid/inference/tensorrt/convert/quantize_linear_op.cc
  paddle/fluid/inference/tensorrt/op_teller.cc
  paddle/fluid/pybind/inference_api.cc
  test/ir/inference/CMakeLists.txt
  test/ir/inference/auto_scan_test.py
  test/ir/inference/test_trt_convert_quantize_dequantize_linear.py
Labels: NVIDIA, contributor

#56487 update xpu xdnn time
  cmake/external/xpu.cmake
Labels: contributor, status: proposed

#56473 [xdoctest] reformat example code with google style in No. 203 - 211
  python/paddle/distributed/communication/stream/all_reduce.py
  python/paddle/distributed/communication/stream/all_to_all.py
  python/paddle/distributed/communication/stream/broadcast.py
  python/paddle/distributed/communication/stream/gather.py
  python/paddle/distributed/communication/stream/recv.py
  python/paddle/distributed/communication/stream/reduce.py
  python/paddle/distributed/communication/stream/reduce_scatter.py
  python/paddle/distributed/communication/stream/scatter.py
  python/paddle/distributed/communication/stream/send.py
Labels: contributor, HappyOpenSource Pro

#56530 [CINN] Dump compilation info by fusion group while compiling
  paddle/cinn/backends/compiler.cc
  paddle/cinn/backends/compiler.h
  paddle/cinn/hlir/framework/graph_compiler.cc
  paddle/cinn/hlir/framework/parallel_compiler.cc
  paddle/cinn/hlir/framework/parallel_compiler.h
Labels: contributor, status: proposed

#56574 update xdnn date
  cmake/external/xpu.cmake
Labels: contributor

#56469 Fixed a mismatch between Chinese and English documents for the CrossEntropyLoss #50424
  python/paddle/nn/layer/loss.py
Labels: contributor

#56559 Fix typo
  paddle/fluid/framework/ir/xpu/matmul_weight_trans_pass.h
Labels: contributor

#56645 [Tools]Refine check_api_approve.sh and modify into Github Name to improve readability
  tools/check_api_approvals.sh
Labels: contributor

#56483 Fix TensorRT multiclass_nms Test
  test/ir/inference/test_trt_convert_multiclass_nms.py
Labels: NVIDIA, contributor, status: proposed

#56359 [xdoctest] reformat example code with google style No.241-245
  python/paddle/incubate/autograd/functional.py
  python/paddle/incubate/autograd/primapi.py
  python/paddle/incubate/autograd/primreg.py
  python/paddle/incubate/autograd/primx.py
  python/paddle/incubate/autograd/utils.py
Labels: contributor, HappyOpenSource Pro

#55926 [xdoctest] reformat example code with google style in 192-197
  python/paddle/distributed/communication/all_gather.py
  python/paddle/distributed/communication/all_reduce.py
  python/paddle/distributed/communication/all_to_all.py
  python/paddle/distributed/communication/batch_isend_irecv.py
  python/paddle/distributed/communication/broadcast.py
  python/paddle/distributed/communication/gather.py
Labels: contributor, HappyOpenSource Pro

#56600 [xdoctest] reformat example code with google style in No. 305
  python/paddle/incubate/xpu/resnet_block.py
Labels: contributor, HappyOpenSource Pro

#56579 [xdoctest][task 144-149] reformat example code with google style in `text/datasets/*`
  python/paddle/text/datasets/conll05.py
  python/paddle/text/datasets/imdb.py
  python/paddle/text/datasets/imikolov.py
  python/paddle/text/datasets/movielens.py
  python/paddle/text/datasets/uci_housing.py
  python/paddle/text/datasets/wmt14.py
Labels: contributor, HappyOpenSource Pro

#56458 [xdoctest][task 293-296] reformat example code with google style in `vision`
  python/paddle/vision/datasets/folder.py
  python/paddle/vision/datasets/mnist.py
  python/paddle/vision/datasets/voc2012.py
  python/paddle/vision/image.py
Labels: contributor, HappyOpenSource Pro

#56121 [xdoctest][task 125-137] reformat example code with google style in static/*
  python/paddle/static/amp/bf16/amp_lists.py
  python/paddle/static/amp/bf16/amp_utils.py
  python/paddle/static/amp/bf16/decorator.py
  python/paddle/static/amp/debugging.py
  python/paddle/static/amp/decorator.py
  python/paddle/static/amp/fp16_utils.py
  python/paddle/static/input.py
  python/paddle/static/io.py
  python/paddle/static/log_helper.py
  python/paddle/static/nn/loss.py
  python/paddle/static/nn/metric.py
Labels: contributor, HappyOpenSource Pro

#56573 [Change] 不再兼容旧格式示例代码
  paddle/scripts/paddle_build.sh
  tools/sampcd_processor.py
  tools/sampcd_processor_utils.py
  tools/sampcd_processor_xdoctest.py
  tools/test_sampcd_processor.py
  tools/test_sampcd_processor_xdoctest.py
Labels: contributor

#56687 [Fix] 修改logger名称避免冲突
  tools/sampcd_processor_utils.py
Labels: contributor

#56547 [Phi] move shuffle_batch to phi
  paddle/fluid/operators/shuffle_batch_op.cc
  paddle/fluid/operators/shuffle_batch_op.cu
  paddle/fluid/operators/shuffle_batch_op.h
  paddle/phi/kernels/cpu/shuffle_batch_grad_kernel.cc
  paddle/phi/kernels/cpu/shuffle_batch_kernel.cc
  paddle/phi/kernels/gpu/shuffle_batch_grad_kernel.cu
  paddle/phi/kernels/gpu/shuffle_batch_kernel.cu
  paddle/phi/kernels/gpu/shuffle_batch_utils.h
  paddle/phi/kernels/shuffle_batch_grad_kernel.h
  paddle/phi/kernels/shuffle_batch_kernel.h
  paddle/phi/ops/compat/shuffle_batch_sig.cc
  test/legacy_test/CMakeLists.txt
  test/legacy_test/test_shuffle_batch_op.py
Labels: contributor

#56675 [Tools]Refine check_file_diff_approvals.sh and modify into Github Name
  tools/check_file_diff_approvals.sh
Labels: contributor

#56466 Add Japanese docs
  SECURITY_ja.md
  security/README_ja.md
Labels: contributor, status: proposed

#56681 [API Enhancement] No.1 support the any number of times in paddle.diff [used AI Studio]
  python/paddle/tensor/math.py
  test/legacy_test/test_diff_op.py
Labels: contributor

#56651 [xdoctest][task 213,215-217] reformat example code with google style in `python/paddle/distributed/fleet/base`
  python/paddle/distributed/fleet/base/orthogonal_strategy.py
  python/paddle/distributed/fleet/base/strategy_group.py
  python/paddle/distributed/fleet/base/topology.py
  python/paddle/distributed/fleet/base/util_factory.py
Labels: contributor, HappyOpenSource Pro

#56693 [clang-tidy] NO.65 enable `clang-analyzer-cplusplus.InnerPointer` check
  .clang-tidy
  paddle/phi/kernels/funcs/math_function.cc
Labels: contributor, HappyOpenSource Pro

#56692 [clang-tidy] NO.38 enable `bugprone-exception-escape`
  .clang-tidy
  paddle/fluid/distributed/auto_parallel/spmd_rules/dim_trans.cc
  paddle/fluid/eager/auto_code_generator/eager_generator.cc
  paddle/fluid/eager/pylayer/py_layer_node.cc
  paddle/fluid/framework/custom_operator.cc
  paddle/fluid/framework/new_executor/interpreter/interpreter_util.cc
  paddle/fluid/framework/scope.cc
  paddle/fluid/inference/api/analysis_predictor.cc
  paddle/fluid/memory/allocation/mmap_allocator.cc
  paddle/fluid/platform/profiler.cc
  paddle/fluid/platform/profiler/chrometracing_logger.cc
  paddle/fluid/platform/profiler/dump/deserialization_reader.cc
  paddle/fluid/platform/profiler/dump/serialization_logger.cc
  paddle/fluid/pybind/eager_functions.cc
  paddle/fluid/pybind/eager_legacy_op_function_generator.cc
  paddle/fluid/pybind/eager_utils.cc
  paddle/fluid/pybind/imperative.cc
  paddle/fluid/pybind/kernel_signature_generator.cc
  paddle/ir/core/storage_manager.cc
  paddle/phi/core/distributed/store/tcp_store.cc
  paddle/phi/core/sparse_coo_tensor.cc
  paddle/phi/core/string_tensor.cc
  paddle/phi/core/tensor_meta.cc
  paddle/testing/paddle_gtest_main.cc
Labels: contributor, HappyOpenSource Pro

#56686 Update loss.py --refactored fluid_softmax_with_cross_entropy
  python/paddle/nn/functional/loss.py
Labels: contributor

#56470 [API Enhancement] No.6 support single `int` input in UpsamplingNearest2D and UpsamplingBilinear2D
  python/paddle/nn/layer/common.py
  test/legacy_test/test_imperative_layers.py
Labels: contributor, HappyOpenSource

#56637 [clang-tidy] NO.42 enable `clang-analyzer-core.uninitialized.Assign`
  .clang-tidy
  paddle/phi/kernels/funcs/activation_functor.h
  paddle/phi/kernels/funcs/gpc.cc
Labels: contributor, HappyOpenSource Pro
