Repository PaddlePaddle/Paddle, pull requests merged in 2023-03, with the labels that each got.

#51013 [PHI Decoupling]fix custom plugin include headers error
  paddle/phi/core/tensor_utils.cc
  paddle/phi/core/tensor_utils.h
Labels: contributor, status: proposed

#50945 [fp16] suppot fp16 in diagflat
  python/paddle/fluid/tests/unittests/test_diagflat.py
  python/paddle/tensor/creation.py
Labels: contributor, status: proposed

#51034 fix zero bug of case18: paddle.logsumexp
  paddle/phi/kernels/impl/logsumexp_kernel_impl.h
  python/paddle/fluid/tests/unittests/test_logsumexp.py
Labels: contributor, status: proposed

#51052 [xpu] fix bugs of split/embedding_with_wltwise_add/beam_search_decode kernel
  paddle/fluid/operators/beam_search_decode_op_xpu.cc
  paddle/phi/kernels/fusion/xpu/embedding_with_eltwise_add_xpu_kernel.cc
  paddle/phi/kernels/xpu/split_kernel.cc
Labels: contributor, status: proposed

#50936 [fp16] suppot fp16 in std
  python/paddle/fluid/tests/unittests/test_std_layer.py
  python/paddle/tensor/stat.py
Labels: contributor, status: proposed

#51053 [XPU] add smallest mode for top_k
  paddle/phi/kernels/xpu/top_k_kernel.cc
  python/paddle/fluid/tests/unittests/xpu/test_top_k_v2_op_xpu.py
Labels: contributor, status: proposed

#50626 Fluid clean parallel
  python/paddle/__init__.py
  python/paddle/distributed/__init__.py
  python/paddle/distributed/fleet/fleet.py
  python/paddle/distributed/fleet/utils/hybrid_parallel_util.py
  python/paddle/distributed/parallel.py
  python/paddle/distributed/parallel_helper.py
  python/paddle/fluid/dygraph/__init__.py
  python/paddle/fluid/dygraph/layers.py
  python/paddle/fluid/dygraph/parallel.py
  python/paddle/fluid/dygraph/varbase_patch_methods.py
  python/paddle/fluid/tests/unittests/test_dist_base.py
  python/paddle/fluid/tests/unittests/test_imperative_data_parallel.py
  python/paddle/fluid/tests/unittests/test_imperative_parallel_coalesce_split.py
  python/paddle/fluid/tests/unittests/test_spawn_and_init_parallel_env.py
  python/paddle/framework/__init__.py
  python/paddle/hapi/model.py
Labels: contributor, status: not progressed

#51088 Fix divide zero bug for paddle.all
  paddle/phi/kernels/reduce_all_kernel.cc
  python/paddle/fluid/tests/unittests/test_reduce_op.py
Labels: contributor, status: proposed

#51091 fix zero bug of case21: paddle.mode
  paddle/phi/kernels/cpu/mode_kernel.cc
  paddle/phi/kernels/gpu/mode_kernel.cu
  python/paddle/fluid/tests/unittests/test_mode_op.py
Labels: contributor

#50743 oneDNN kernels code cleanup
  paddle/fluid/operators/mkldnn/fc_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/matmul_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/transpose_mkldnn_op.cc
  paddle/phi/backends/CMakeLists.txt
  paddle/phi/backends/onednn/matmul_utils.cc
  paddle/phi/backends/onednn/matmul_utils.h
  paddle/phi/backends/onednn/onednn_reuse.h
  paddle/phi/kernels/fusion/onednn/fused_matmul_kernel.cc
  paddle/phi/kernels/onednn/elementwise_kernel.cc
  paddle/phi/kernels/onednn/matmul_grad_kernel.cc
  paddle/phi/kernels/onednn/matmul_kernel.cc
  paddle/phi/kernels/onednn/transpose_kernel.cc
  python/paddle/fluid/tests/unittests/ir/inference/CMakeLists.txt
  python/paddle/fluid/tests/unittests/ir/inference/test_onednn_operator_unsqueeze2_fuse_pass.py
Labels: Intel, contributor

#51139 add float16 to pixel_shuffle
  python/paddle/fluid/tests/unittests/test_pixel_shuffle_op.py
  python/paddle/nn/functional/vision.py
Labels: contributor, status: proposed

#51145 Add float16 to less than
  python/paddle/fluid/tests/unittests/test_less_than_op.py
  python/paddle/tensor/logic.py
Labels: contributor, status: proposed

#51090 add float16 to greater_than
  python/paddle/fluid/tests/unittests/test_compare_op.py
  python/paddle/tensor/logic.py
Labels: contributor

#51098 greater_equal API for fp16
  python/paddle/fluid/tests/unittests/test_greater_equal_op.py
  python/paddle/tensor/logic.py
Labels: contributor, status: proposed

#51094 add float16 to less_equal
  python/paddle/fluid/tests/unittests/test_less_equal_op.py
  python/paddle/tensor/logic.py
Labels: contributor, status: proposed

#51082 [xpu] support paddle compile with XFT
  CMakeLists.txt
  cmake/external/xpu.cmake
  python/env_dict.py.in
  python/setup.py.in
  setup.py
Labels: contributor, status: proposed

#50974 [Hackathon NO.76] 为 Paddle-TRT 添加elementwise_mod 算子
  paddle/fluid/inference/api/analysis_predictor.cc
  paddle/fluid/inference/tensorrt/convert/elementwise_op.cc
  paddle/fluid/inference/tensorrt/convert/op_converter.h
  paddle/fluid/inference/tensorrt/op_teller.cc
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_elementwise.py
Labels: contributor, status: proposed

#51174 Remove TODOs from code
  paddle/fluid/framework/ir/embedding_fc_lstm_fuse_pass.cc
  paddle/fluid/framework/ir/fc_gru_fuse_pass.cc
  paddle/fluid/framework/ir/graph_pattern_detector.h
  paddle/fluid/framework/ir/mkldnn/cpu_quantize_pass.cc
  paddle/fluid/framework/ir/mkldnn/cpu_quantize_squash_pass.cc
  paddle/fluid/inference/tests/api/CMakeLists.txt
  paddle/fluid/operators/controlflow/conditional_block_op.cc
  paddle/fluid/operators/controlflow/while_op.cc
  paddle/fluid/operators/conv_op.cc
  paddle/fluid/operators/elementwise/elementwise_op.h
  paddle/fluid/operators/fused/mkldnn/fusion_rnn_mkldnn.h
  paddle/fluid/operators/fused/mkldnn/multi_gru_mkldnn_op.cc
  paddle/fluid/operators/matmul_op.cc
  paddle/fluid/operators/mkldnn/layer_norm_mkldnn_op.cc
  paddle/fluid/operators/pool_op.cc
  paddle/fluid/operators/sequence_ops/sequence_pool_op.h
  paddle/phi/backends/onednn/axpy_handler.h
  python/paddle/fluid/tests/unittests/mkldnn/test_elementwise_div_mkldnn_op.py
  python/paddle/fluid/tests/unittests/mkldnn/test_split_bf16_mkldnn_op.py
Labels: Intel, contributor

#50882 [Fix Typo] Fix the quotation mark format problem
  python/paddle/nn/functional/vision.py
Labels: contributor, status: proposed

#51203 Fix the "unknown-pragmas" compiler warning in Linux
  paddle/fluid/distributed/CMakeLists.txt
  paddle/fluid/distributed/ps/service/brpc_ps_client.cc
  paddle/fluid/distributed/rpc/CMakeLists.txt
  paddle/fluid/pybind/CMakeLists.txt
Labels: contributor, status: proposed

#51092 Fix npairloss bug
  python/paddle/fluid/tests/unittests/test_npair_loss_op.py
  python/paddle/nn/functional/loss.py
Labels: contributor, status: proposed

#50094 Rewrite multi_gru_fuse_pass_tester & multi_gru_seq_fuse_pass_tester
  paddle/fluid/framework/ir/CMakeLists.txt
  paddle/fluid/framework/ir/mkldnn/multi_gru_fuse_pass.cc
  paddle/fluid/framework/ir/mkldnn/multi_gru_fuse_pass.h
  paddle/fluid/framework/ir/mkldnn/multi_gru_fuse_pass_tester.cc
  paddle/fluid/framework/ir/mkldnn/multi_gru_seq_fuse_pass.cc
  paddle/fluid/framework/ir/mkldnn/multi_gru_seq_fuse_pass.h
  paddle/fluid/framework/ir/mkldnn/multi_gru_seq_fuse_pass_tester.cc
  python/paddle/fluid/tests/unittests/ir/inference/CMakeLists.txt
  python/paddle/fluid/tests/unittests/ir/inference/program_config.py
  python/paddle/fluid/tests/unittests/ir/inference/test_onednn_multi_gru_fuse_pass.py
  python/paddle/fluid/tests/unittests/ir/inference/test_onednn_multi_gru_seq_fuse_pass.py
Labels: Intel, contributor

#50987 【PaddlePaddle Hackathon 第四期】No1：为 Paddle 新增 finfo API
  paddle/fluid/pybind/pybind.cc
  paddle/phi/common/bfloat16.h
  paddle/phi/common/float16.h
  python/paddle/__init__.py
  python/paddle/fluid/tests/unittests/test_iinfo_and_finfo.py
  python/paddle/framework/dtype.py
Labels: contributor, status: not progressed

#51216 add float16 to log log1p logsumexp
  python/paddle/fluid/tests/unittests/test_activation_op.py
  python/paddle/tensor/math.py
Labels: contributor, status: not progressed

#51040 Fix doc 175-185
  python/paddle/autograd/py_layer.py
  python/paddle/nn/initializer/Bilinear.py
  python/paddle/tensor/logic.py
  python/paddle/tensor/manipulation.py
  python/paddle/tensor/math.py
Labels: contributor, status: proposed

#51178 Update weight_norm_hook.py
  python/paddle/nn/utils/weight_norm_hook.py
Labels: contributor, status: proposed

#50677 【Hackathon No.89】 Remove circle import Part1
  python/paddle/jit/api.py
Labels: contributor, status: proposed

#51338 Fix typos
  paddle/fluid/distributed/collective/process_group_nccl.cc
  paddle/fluid/distributed/collective/reducer.cc
  paddle/fluid/distributed/fleet_executor/compute_interceptor.cc
  paddle/fluid/distributed/index_dataset/index_wrapper.cc
  paddle/fluid/distributed/ps.proto
  paddle/fluid/distributed/ps/service/communicator/communicator.cc
  paddle/fluid/distributed/ps/service/communicator/communicator.h
Labels: contributor, status: proposed

#51315 [phi] add register of argmax/min
  paddle/fluid/framework/new_executor/interpreter/interpreter_util.cc
  paddle/phi/kernels/cpu/arg_min_max_kernel.cc
  paddle/phi/kernels/gpu/arg_min_max_kernel.cu
  paddle/phi/kernels/xpu/arg_min_max_kernel.cc
Labels: contributor, status: proposed

#51320 [PHI] add register of ROI_POOL
  paddle/fluid/framework/new_executor/interpreter/interpreter_util.cc
Labels: contributor, status: proposed

#51330 remove entry_attr.py and evaluatory.py in fluid
  python/paddle/fluid/__init__.py
  python/paddle/fluid/entry_attr.py
  python/paddle/fluid/evaluator.py
  python/paddle/fluid/io.py
Labels: contributor

#51325 add output defs for nonzero and nms
  paddle/fluid/framework/new_executor/interpreter/interpreter_util.cc
  paddle/phi/kernels/cpu/nms_kernel.cc
  paddle/phi/kernels/cpu/nonzero_kernel.cc
  paddle/phi/kernels/gpu/nms_kernel.cu
  paddle/phi/kernels/gpu/nonzero_kernel.cu
  paddle/phi/kernels/xpu/nonzero_kernel.cc
Labels: contributor, status: proposed

#51114 [AMP OP&Test] Mean fp/bf 16 support
  paddle/phi/kernels/gpu/reduce_mean_grad_kernel.cu
  paddle/phi/kernels/kps/reduce_mean_kernel.cu
  paddle/phi/kernels/reduce_mean_kernel.cc
  python/paddle/fluid/tests/unittests/test_mean_op.py
Labels: contributor, status: proposed

#51322 [phi] add register of is_finite
  paddle/fluid/framework/new_executor/interpreter/interpreter_util.cc
  paddle/phi/kernels/cpu/isfinite_kernel.cc
  paddle/phi/kernels/gpu/isfinite_kernel.cu
  paddle/phi/kernels/xpu/isfinite_kernel.cc
Labels: contributor, status: proposed

#51311 add output defs for qr kernel
  paddle/fluid/framework/new_executor/interpreter/interpreter_util.cc
Labels: contributor, status: proposed

#51264 Delete axis of fmax kernel
  paddle/phi/api/yaml/legacy_backward.yaml
  paddle/phi/kernels/cpu/elementwise_kernel.cc
  paddle/phi/kernels/elementwise_grad_kernel.h
  paddle/phi/kernels/elementwise_kernel.cc
  paddle/phi/kernels/elementwise_kernel.h
  paddle/phi/kernels/impl/elementwise_grad_kernel_impl.h
  paddle/phi/kernels/impl/elementwise_kernel_impl.h
  paddle/phi/kernels/kps/elementwise_kernel.cu
  paddle/phi/ops/compat/elementwise_sig.cc
Labels: contributor, status: not progressed

#50624 【Hackathon No.67】remove reference to operator.h in phi [part 1]
  paddle/fluid/framework/data_layout_transform.cc
  paddle/fluid/imperative/tests/test_group.cc
  paddle/fluid/operators/detection/anchor_generator_op.h
  paddle/fluid/operators/detection/prior_box_op.h
  paddle/fluid/operators/index_select_op.h
  paddle/fluid/operators/interpolate_op.h
  paddle/fluid/operators/math/prelu.h
  paddle/fluid/operators/math/sequence_pooling.cc
  paddle/fluid/operators/math/tree2col.cu
  paddle/fluid/operators/reduce_ops/check_reduce_rank_test.cu
  paddle/fluid/operators/sequence_ops/sequence_expand_op.h
  paddle/phi/core/utils/visit_place.h
  paddle/phi/kernels/cpu/repeat_interleave_grad_kernel.cc
  paddle/phi/kernels/cpu/sparse_weight_embedding_kernel.cc
  paddle/phi/kernels/cpu/take_along_axis_grad_kernel.cc
  paddle/phi/kernels/cpu/unique_consecutive_kernel.cc
  paddle/phi/kernels/cpu/unique_kernel.cc
  paddle/phi/kernels/funcs/math_function.cc
  paddle/phi/kernels/funcs/math_function.h
  paddle/phi/kernels/funcs/math_function_impl.h
  paddle/phi/kernels/funcs/segment_pooling.cu
  paddle/phi/kernels/funcs/unique_functor.h
  paddle/phi/kernels/gpu/bincount_kernel.cu
  paddle/phi/kernels/gpu/class_center_sample_kernel.cu
  paddle/phi/kernels/gpu/edit_distance_kernel.cu
  paddle/phi/kernels/gpu/margin_cross_entropy_grad_kernel.cu
  paddle/phi/kernels/gpu/margin_cross_entropy_kernel.cu
  paddle/phi/kernels/gpu/sync_batch_norm_kernel.cu
  paddle/phi/kernels/impl/repeat_interleave_kernel_impl.h
  paddle/phi/kernels/impl/set_value_grad_kernel_impl.h
  paddle/phi/kernels/xpu/distribute_fpn_proposals_kernel.cc
  paddle/phi/kernels/xpu/set_value_grad_kernel.cc
Labels: contributor, status: proposed

#51313 [phi] add register of asreal
  paddle/fluid/framework/new_executor/interpreter/interpreter_util.cc
  paddle/phi/infermeta/unary.cc
  paddle/phi/kernels/cpu/as_real_kernel.cc
  paddle/phi/kernels/gpu/as_real_kernel.cu
Labels: contributor, status: proposed

#51336 fix maybe-uninitialized compiler warning in Linux
  cmake/flags.cmake
  paddle/fluid/framework/ir/delete_weight_dequant_linear_op_pass.cc
  paddle/fluid/inference/tensorrt/convert/op_converter.h
  paddle/fluid/inference/tensorrt/convert/unary_op.cc
  paddle/fluid/operators/fused/fused_gemm_epilogue_op_xpu.cc
  paddle/phi/kernels/xpu/pad3d_grad_kernel.cc
Labels: contributor, status: proposed

#51308 [phi] add register of accuracy
  paddle/fluid/framework/new_executor/interpreter/interpreter_util.cc
  paddle/phi/kernels/cpu/accuracy_kernel.cc
  paddle/phi/kernels/gpu/accuracy_kernel.cu
Labels: contributor, status: proposed

#51393 add output defs for eigvals kernel
  paddle/fluid/framework/new_executor/interpreter/interpreter_util.cc
  paddle/phi/kernels/cpu/eigvals_kernel.cc
Labels: contributor

#51324 Add output defs for edit_distance kernel
  paddle/fluid/framework/new_executor/interpreter/interpreter_util.cc
  paddle/phi/kernels/cpu/edit_distance_kernel.cc
  paddle/phi/kernels/gpu/edit_distance_kernel.cu
Labels: contributor, status: proposed

#51332 Add output defs for sgd kernel
  paddle/fluid/framework/new_executor/interpreter/interpreter_util.cc
  paddle/phi/infermeta/multiary.cc
  paddle/phi/kernels/gpu/sgd_kernel.cu
Labels: contributor

#51323 Add output defs for fused_adam kernel
  paddle/fluid/framework/new_executor/interpreter/interpreter_util.cc
  paddle/phi/kernels/cpu/fused_adam_kernel.cc
  paddle/phi/kernels/gpu/fused_adam_kernel.cu
Labels: contributor, status: proposed

#51271 Xpu ernie3: support fp16 for xpu kernels: full_like/stack/where
  paddle/phi/backends/xpu/xpu2_op_list.cc
  paddle/phi/kernels/xpu/full_kernel.cc
  paddle/phi/kernels/xpu/stack_kernel.cc
  paddle/phi/kernels/xpu/where_kernel.cc
Labels: contributor, status: not progressed

#50989 【Hackathon No.67】remove operator.h in blas.h
  paddle/fluid/operators/attention_lstm_op.cc
  paddle/fluid/operators/center_loss_op.h
  paddle/fluid/operators/fsp_op.h
  paddle/fluid/operators/fused/fused_embedding_fc_lstm_op.cc
  paddle/fluid/operators/fused/fused_embedding_seq_pool_op.h
  paddle/fluid/operators/fused/fusion_gru_op.cc
  paddle/fluid/operators/fused/fusion_lstm_op.cc
  paddle/fluid/operators/fused/fusion_seqexpand_concat_fc_op.cc
  paddle/fluid/operators/gru_unit_op.h
  paddle/fluid/operators/index_select_op.h
  paddle/fluid/operators/lookup_table_op.h
  paddle/fluid/operators/lookup_table_v2_op.h
  paddle/fluid/operators/lrn_op.cc
  paddle/fluid/operators/match_matrix_tensor_op.cc
  paddle/fluid/operators/matmul_op.cc
  paddle/fluid/operators/search_compute.h
  paddle/fluid/operators/svd_helper.h
  paddle/fluid/operators/var_conv_2d_op.cc
  paddle/phi/kernels/funcs/blas/blas.h
  paddle/phi/kernels/funcs/math_function.cu
Labels: contributor, status: not progressed

#49013 [Framework]Support deliver stop_gradient in static mode
  paddle/fluid/operators/recurrent_op.cc
  paddle/fluid/operators/select_output_op.cc
  python/paddle/fluid/framework.py
  python/paddle/fluid/tests/unittests/ir/test_ir_fusion_group_pass.py
  python/paddle/fluid/tests/unittests/test_cond.py
  python/paddle/fluid/tests/unittests/test_desc_clone.py
  python/paddle/fluid/tests/unittests/test_eager_deletion_while_op.py
  python/paddle/fluid/tests/unittests/test_imperative_recurrent_usage.py
  python/paddle/fluid/tests/unittests/test_nn_grad.py
  python/paddle/fluid/tests/unittests/test_optimizer.py
  python/paddle/fluid/tests/unittests/test_pass_stop_gradient.py
  python/paddle/fluid/tests/unittests/test_set_value_op.py
  python/paddle/fluid/tests/unittests/test_where_op.py
  python/paddle/fluid/tests/unittests/test_while_loop_op.py
  python/paddle/fluid/tests/unittests/test_zero_dim_tensor.py
Labels: framework

#51168 No.54：为 Paddle allclose、isclose 算子实现 float16 数据类型支持
  paddle/phi/kernels/gpu/allclose_kernel.cu
  paddle/phi/kernels/gpu/isclose_kernel.cu
  paddle/phi/kernels/impl/isclose_kernel_impl.h
  python/paddle/fluid/tests/unittests/test_allclose_op.py
  python/paddle/fluid/tests/unittests/test_isclose_op.py
  python/paddle/tensor/logic.py
Labels: contributor, status: proposed

#51314 [phi] add register of angle
  paddle/fluid/framework/new_executor/interpreter/interpreter_util.cc
  paddle/phi/kernels/cpu/angle_kernel.cc
  paddle/phi/kernels/gpu/angle_kernel.cu
Labels: contributor, status: proposed

#51316 [phi] Add register of yolo_loss
  paddle/fluid/framework/new_executor/interpreter/interpreter_util.cc
  paddle/phi/kernels/cpu/yolo_loss_kernel.cc
Labels: contributor, status: proposed

#51368 fix-debug-mode-exception
  python/paddle/dataset/image.py
Labels: contributor

#51197 【Hackathon No58】-fix set_value
  paddle/phi/kernels/gpu/set_value_grad_kernel.cu
  paddle/phi/kernels/gpu/set_value_kernel.cu
  paddle/phi/kernels/set_value_grad_kernel.h
  paddle/phi/kernels/set_value_kernel.h
  python/paddle/fluid/tests/unittests/test_set_value_op.py
Labels: contributor, status: proposed

#51501 add output defs for send_u_recv
  paddle/fluid/framework/new_executor/interpreter/interpreter_util.cc
  paddle/phi/kernels/cpu/send_u_recv_kernel.cc
  paddle/phi/kernels/gpu/send_u_recv_kernel.cu
Labels: contributor, status: proposed

#51410 Add output defs for all_close all_raw kernel
  paddle/fluid/framework/new_executor/interpreter/interpreter_util.cc
  paddle/phi/kernels/cpu/reduce_all_kernel.cc
  paddle/phi/kernels/kps/reduce_all_kernel.cu
Labels: contributor, status: proposed

#51522 add output defs for send_ue_recv kernel
  paddle/fluid/framework/new_executor/interpreter/interpreter_util.cc
  paddle/phi/kernels/cpu/send_ue_recv_kernel.cc
  paddle/phi/kernels/gpu/send_ue_recv_kernel.cu
Labels: contributor, status: proposed

#51484 add register of is_empty
  paddle/fluid/framework/new_executor/interpreter/interpreter_util.cc
  paddle/phi/kernels/is_empty_kernel.cc
Labels: contributor, status: proposed

#51508 add register of bincount
  paddle/fluid/framework/new_executor/interpreter/interpreter_util.cc
  paddle/phi/kernels/cpu/bincount_kernel.cc
  paddle/phi/kernels/gpu/bincount_kernel.cu
Labels: contributor, status: proposed

#51199 【Hackathon No.89】 Remove circle import Part2
  python/paddle/jit/dy2static/call_transformer.py
  python/paddle/jit/dy2static/convert_call_func.py
  python/paddle/jit/dy2static/convert_operators.py
  python/paddle/jit/dy2static/ifelse_transformer.py
  python/paddle/jit/dy2static/loop_transformer.py
  python/paddle/jit/dy2static/partial_program.py
  python/paddle/jit/dy2static/program_translator.py
  python/paddle/jit/dy2static/return_transformer.py
  python/paddle/jit/dy2static/utils.py
Labels: contributor, status: not progressed

#51523 remove_viterbi_devode
  paddle/fluid/framework/new_executor/interpreter/interpreter_util.cc
Labels: contributor, status: proposed

#51451 add register of auc
  paddle/fluid/framework/new_executor/interpreter/interpreter_util.cc
  paddle/phi/kernels/cpu/auc_kernel.cc
  paddle/phi/kernels/gpu/auc_kernel.cu
Labels: contributor, status: not progressed

#50603 [Paddle Inference ]use python to generate cutlass code
  .gitignore
  paddle/fluid/framework/ir/conv2d_fusion_layout_transfer_pass.cc
  paddle/phi/kernels/CMakeLists.txt
  paddle/phi/kernels/fusion/cutlass/conv2d/conv2d_bias.cu
  paddle/phi/kernels/fusion/cutlass/conv2d/conv2d_bias_act.py
  paddle/phi/kernels/fusion/cutlass/conv2d/conv2d_bias_add_relu.cu
  paddle/phi/kernels/fusion/cutlass/conv2d/conv2d_bias_leaky_relu.cu
  paddle/phi/kernels/fusion/cutlass/conv2d/conv2d_bias_relu.cu
  paddle/phi/kernels/fusion/cutlass/conv2d/conv2d_bias_residual.py
  paddle/phi/kernels/fusion/cutlass/conv2d/conv2d_bias_silu.cu
  paddle/phi/kernels/fusion/cutlass/conv2d/conv2d_common.py
  paddle/phi/kernels/fusion/cutlass/conv2d/conv2d_decl.h
  paddle/phi/kernels/fusion/cutlass/conv2d/conv2d_util.cu
  paddle/phi/kernels/fusion/cutlass/conv2d/conv2d_util.h
  paddle/phi/kernels/fusion/cutlass/conv2d_fusion.cu
  paddle/phi/kernels/fusion/cutlass/util.py
  python/paddle/fluid/tests/unittests/ir/inference/test_cutlass_conv2d_fusion_op.py
Labels: contributor, status: proposed

#51534 add register of kthvalue
  paddle/fluid/framework/new_executor/interpreter/interpreter_util.cc
  paddle/phi/kernels/cpu/kthvalue_kernel.cc
  paddle/phi/kernels/gpu/kthvalue_kernel.cu
Labels: contributor, status: proposed

#51516 Add output defs for conv3d_coo distribute_fpn_proposals kernel
  paddle/fluid/framework/new_executor/interpreter/interpreter_util.cc
  paddle/phi/kernels/cpu/distribute_fpn_proposals_kernel.cc
  paddle/phi/kernels/gpu/distribute_fpn_proposals_kernel.cu
  paddle/phi/kernels/sparse/cpu/conv_kernel.cc
  paddle/phi/kernels/sparse/gpu/conv_kernel.cu
  paddle/phi/kernels/xpu/distribute_fpn_proposals_kernel.cc
Labels: contributor, status: proposed

#51492 fix paddle::Tensor symbol missing
  paddle/fluid/inference/paddle_inference.map
Labels: contributor, status: proposed

#51326 Add output defs for fused_matmul kernel
  paddle/fluid/framework/new_executor/interpreter/interpreter_util.cc
  paddle/fluid/operators/fused/fused_matmul_op.cc
  paddle/phi/infermeta/binary.cc
  paddle/phi/infermeta/binary.h
  paddle/phi/kernels/fusion/onednn/fused_matmul_kernel.cc
Labels: contributor, status: proposed

#51363 Add output defs for mode kernel
  paddle/fluid/framework/new_executor/interpreter/interpreter_util.cc
  paddle/phi/kernels/cpu/mode_kernel.cc
  paddle/phi/kernels/gpu/mode_kernel.cu
Labels: contributor, status: proposed

#51470 [PHI] Replace paddle::experimental::DataType as phi::DataType
  paddle/phi/backends/c_comm_lib.h
  paddle/phi/core/dense_tensor_impl.cc
  paddle/phi/core/kernel_factory.cc
  paddle/phi/kernels/cpu/amp_kernel.cc
  paddle/phi/kernels/cpu/as_real_kernel.cc
  paddle/phi/kernels/cpu/cast_grad_kernel.cc
  paddle/phi/kernels/cpu/cast_kernel.cc
  paddle/phi/kernels/cpu/compare_kernel.cc
  paddle/phi/kernels/cpu/dropout_kernel.cc
  paddle/phi/kernels/cpu/eigvals_kernel.cc
  paddle/phi/kernels/cpu/nms_kernel.cc
  paddle/phi/kernels/cpu/nonzero_kernel.cc
  paddle/phi/kernels/cpu/one_hot_kernel.cc
  paddle/phi/kernels/cpu/reduce_sum_kernel.cc
  paddle/phi/kernels/cpu/top_k_kernel.cc
  paddle/phi/kernels/cpu/viterbi_decode_kernel.cc
  paddle/phi/kernels/gpu/amp_kernel.cu
  paddle/phi/kernels/gpu/as_real_kernel.cu
  paddle/phi/kernels/gpu/cast_grad_kernel.cu
  paddle/phi/kernels/gpu/cast_kernel.cu
  paddle/phi/kernels/gpu/dropout_kernel.cu
  paddle/phi/kernels/gpu/nms_kernel.cu
  paddle/phi/kernels/gpu/nonzero_kernel.cu
  paddle/phi/kernels/gpu/one_hot_kernel.cu
  paddle/phi/kernels/gpu/top_k_kernel.cu
  paddle/phi/kernels/gpu/viterbi_decode_kernel.cu
  paddle/phi/kernels/kps/compare_kernel.cu
  paddle/phi/kernels/kps/reduce_sum_kernel.cu
  paddle/phi/kernels/one_hot_kernel.cc
  paddle/phi/kernels/reduce_sum_kernel.cc
  paddle/phi/kernels/shape_kernel.cc
  paddle/phi/kernels/xpu/amp_kernel.cc
  paddle/phi/kernels/xpu/cast_kernel.cc
  paddle/phi/kernels/xpu/compare_kernel.cc
  paddle/phi/kernels/xpu/nonzero_kernel.cc
  paddle/phi/kernels/xpu/one_hot_kernel.cc
  paddle/phi/kernels/xpu/top_k_kernel.cc
Labels: contributor, status: proposed

#51527 Add Unsqueeze op composite rule
  python/paddle/fluid/tests/unittests/CMakeLists.txt
  python/paddle/fluid/tests/unittests/test_unsqueeze2_op.py
  python/paddle/incubate/autograd/composite_rules.py
Labels: contributor, status: proposed

#51506 Fix docs 修复第七轮第一组文档问题
  python/paddle/nn/clip.py
  python/paddle/nn/functional/common.py
  python/paddle/nn/layer/rnn.py
Labels: contributor, status: proposed

#51478 add register of complex
  paddle/fluid/framework/new_executor/interpreter/interpreter_util.cc
Labels: contributor, status: not progressed

#51493 【hackathon 4 No53】label_smooth add fp16 support
  paddle/phi/kernels/gpu/label_smooth_grad_kernel.cu
  paddle/phi/kernels/gpu/label_smooth_kernel.cu
  python/paddle/fluid/tests/unittests/test_label_smooth_op.py
  python/paddle/nn/functional/common.py
Labels: contributor, status: proposed

#50924 【Hackathon No.47】为 Paddle cross 算子实现 float16 数据类型支持
  paddle/phi/kernels/gpu/cross_grad_kernel.cu
  paddle/phi/kernels/gpu/cross_kernel.cu
  python/paddle/fluid/tests/unittests/test_cross_op.py
  python/paddle/tensor/linalg.py
Labels: contributor, status: proposed

#51207 [Hackathon NO.73] 为 Paddle-TRT 添加 temporal_shift 算子
  paddle/fluid/framework/ir/trt_support_nhwc_pass.cc
  paddle/fluid/inference/api/analysis_predictor.cc
  paddle/fluid/inference/tensorrt/convert/CMakeLists.txt
  paddle/fluid/inference/tensorrt/convert/temporal_shift_op.cc
  paddle/fluid/inference/tensorrt/op_teller.cc
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_temporal_shift.py
Labels: contributor, status: proposed

#51377 update empty api to support complex dtype at static mode
  python/paddle/tensor/creation.py
Labels: contributor, status: proposed

#51595 add register of select
  paddle/fluid/framework/new_executor/interpreter/interpreter_util.cc
Labels: contributor, status: proposed

#51317 add output defs for histogram kernel
  paddle/fluid/framework/new_executor/interpreter/interpreter_util.cc
  paddle/phi/infermeta/unary.cc
  paddle/phi/kernels/cpu/histogram_kernel.cc
  paddle/phi/kernels/gpu/histogram_kernel.cu
Labels: contributor, status: proposed

#51583 [Divide by 0 Error] add DataNormKernel check
  paddle/fluid/operators/data_norm_op.cc
  paddle/fluid/operators/data_norm_op.cu
  python/paddle/fluid/tests/unittests/test_data_norm_op.py
Labels: contributor, status: proposed

#51553 add symbol InitDevices InitMemoryMethod
  paddle/fluid/inference/paddle_inference.map
Labels: contributor, status: proposed

#51379 Fix typos
  paddle/fluid/eager/pylayer/py_layer_node.cc
  paddle/fluid/framework/details/all_reduce_op_handle.cc
  paddle/fluid/framework/details/bind_threaded_ssa_graph_executor.cc
  paddle/fluid/framework/details/eager_deletion_op_handle.cc
  paddle/fluid/framework/details/fetch_async_op_handle.cc
  paddle/fluid/framework/details/multi_devices_helper.h
  paddle/fluid/framework/details/op_handle_base.h
Labels: contributor, status: proposed

#51608 [Werror]修复maybe-uninitialized编译致命警告
  paddle/fluid/operators/detection/multiclass_nms_op.cc
  paddle/fluid/operators/fused/fusion_repeated_fc_relu_op.cc
  paddle/fluid/pybind/tensor_py.h
  paddle/phi/kernels/cpu/matrix_nms_kernel.cc
  paddle/phi/kernels/cpu/multiclass_nms3_kernel.cc
  paddle/phi/kernels/sparse/cpu/sparse_utils_kernel.cc
Labels: contributor, status: proposed

#51634 Delete hardswish_raw op
  paddle/phi/api/yaml/legacy_backward.yaml
  paddle/phi/kernels/activation_grad_kernel.h
  paddle/phi/kernels/activation_kernel.cc
  paddle/phi/kernels/activation_kernel.h
  paddle/phi/kernels/cpu/activation_grad_kernel.cc
  paddle/phi/kernels/cpu/activation_kernel.cc
  paddle/phi/kernels/gpu/activation_grad_kernel.cu
  paddle/phi/kernels/gpu/activation_kernel.cu
  paddle/phi/kernels/onednn/activation_grad_kernel.cc
  paddle/phi/kernels/onednn/activation_kernel.cc
  paddle/phi/kernels/xpu/activation_grad_kernel.cc
  paddle/phi/kernels/xpu/activation_kernel.cc
  paddle/phi/ops/compat/activation_sig.cc
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_hard_swish.py
Labels: contributor, status: proposed

#51622 support to_static for SpectralNorm
  python/paddle/nn/utils/spectral_norm_hook.py
Labels: contributor, status: proposed

#51600 support auto generate for nonzero
  paddle/fluid/operators/where_index_op.cc
  paddle/phi/api/yaml/legacy_ops.yaml
  paddle/phi/api/yaml/ops.yaml
  paddle/phi/ops/compat/where_index_sig.cc
Labels: contributor, status: proposed

#51631 Delete randperm raw op
  paddle/phi/backends/xpu/xpu2_op_list.cc
  paddle/phi/kernels/cpu/randperm_kernel.cc
  paddle/phi/kernels/gpu/randperm_kernel.cu
  paddle/phi/kernels/randperm_kernel.h
  paddle/phi/kernels/xpu/randperm_kernel.cc
  paddle/phi/ops/compat/randperm_sig.cc
Labels: contributor, status: proposed

#51472 [PHI] remove operator.h in blas.h (rebase to latest codebase)
  paddle/fluid/framework/ir/mkldnn/layer_norm_onednn_optimization_pass.cc
  paddle/fluid/operators/attention_lstm_op.cc
  paddle/fluid/operators/center_loss_op.h
  paddle/fluid/operators/fsp_op.h
  paddle/fluid/operators/fused/fused_embedding_fc_lstm_op.cc
  paddle/fluid/operators/fused/fused_embedding_seq_pool_op.h
  paddle/fluid/operators/fused/fusion_gru_op.cc
  paddle/fluid/operators/fused/fusion_lstm_op.cc
  paddle/fluid/operators/fused/fusion_seqexpand_concat_fc_op.cc
  paddle/fluid/operators/gru_unit_op.h
  paddle/fluid/operators/index_select_op.h
  paddle/fluid/operators/lookup_table_op.h
  paddle/fluid/operators/lookup_table_v2_op.h
  paddle/fluid/operators/lrn_op.cc
  paddle/fluid/operators/match_matrix_tensor_op.cc
  paddle/fluid/operators/math/selected_rows_functor_test.cu.cc
  paddle/fluid/operators/matmul_op.cc
  paddle/fluid/operators/search_compute.h
  paddle/fluid/operators/svd_helper.h
  paddle/fluid/operators/var_conv_2d_op.cc
  paddle/phi/backends/gpu/cuda/cuda_helper.h
  paddle/phi/core/kernel_factory.cc
  paddle/phi/core/kernel_factory.h
  paddle/phi/infermeta/unary.cc
  paddle/phi/kernels/cpu/index_sample_grad_kernel.cc
  paddle/phi/kernels/cpu/index_sample_kernel.cc
  paddle/phi/kernels/cpu/matrix_nms_kernel.cc
  paddle/phi/kernels/cpu/repeat_interleave_grad_kernel.cc
  paddle/phi/kernels/funcs/blas/blas.h
  paddle/phi/kernels/funcs/selected_rows_functor.cc
  paddle/phi/kernels/funcs/selected_rows_functor.h
  paddle/phi/kernels/funcs/unique_functor.h
  paddle/phi/kernels/gpu/index_sample_grad_kernel.cu
  paddle/phi/kernels/gpu/index_sample_kernel.cu
  paddle/phi/kernels/impl/lamb_kernel_impl.h
  paddle/phi/kernels/impl/multi_dot_kernel_impl.h
  paddle/phi/kernels/impl/repeat_interleave_grad_kernel_impl.h
  paddle/phi/kernels/impl/repeat_interleave_kernel_impl.h
  paddle/phi/kernels/selected_rows/cpu/adam_kernel.cc
  paddle/phi/kernels/selected_rows/hsigmoid_loss_grad_kernel.cc
  paddle/phi/kernels/selected_rows/impl/lamb_kernel_impl.h
  paddle/phi/kernels/xpu/index_sample_kernel.cc
  paddle/phi/tests/kernels/test_math_function.cc
  paddle/phi/tests/kernels/test_math_function.cu
Labels: contributor, status: proposed

#51131 【PaddlePaddle Hackathon 4 No.35】为 Paddle 优化 prelu op 在 GPU 上的计算性能
  paddle/phi/kernels/funcs/index_impl.cu.h
  paddle/phi/kernels/gpu/prelu_funcs.h
  paddle/phi/kernels/gpu/prelu_kernel.cu
Labels: contributor

#51319 add output defs for eig kernel
  paddle/fluid/framework/new_executor/interpreter/interpreter_util.cc
  paddle/phi/infermeta/unary.cc
  paddle/phi/kernels/cpu/eig_kernel.cc
Labels: contributor, status: proposed

#51390 Fix nccl_test_op failure on hopper
  paddle/fluid/operators/nccl/nccl_op_test.cu.cc
Labels: NVIDIA, contributor, status: proposed

#51576 Add output defs for generate_proposals,instance_norm kernel
  paddle/fluid/framework/new_executor/interpreter/interpreter_util.cc
  paddle/phi/kernels/cpu/generate_proposals_kernel.cc
  paddle/phi/kernels/gpu/generate_proposals_kernel.cu
  paddle/phi/kernels/xpu/generate_proposals_kernel.cc
Labels: contributor, status: proposed

#51419 文档修复
  python/paddle/nn/functional/common.py
  python/paddle/nn/layer/rnn.py
Labels: contributor, status: proposed

#51433 【Hackathon No.89】 Remove circle import Part3
  python/paddle/jit/dy2static/ast_utils.py
  python/paddle/jit/dy2static/logging_utils.py
  python/paddle/jit/dy2static/static_analysis.py
  python/paddle/jit/dy2static/utils.py
  python/paddle/jit/dy2static/utils_helper.py
Labels: contributor, status: proposed

#51312 add output defs for atan2 kernel
  paddle/fluid/framework/new_executor/interpreter/interpreter_util.cc
  paddle/phi/infermeta/binary.cc
  paddle/phi/kernels/cpu/atan2_kernel.cc
  paddle/phi/kernels/gpu/atan2_kernel.cu
Labels: contributor

#51360 [PHI] Add rnn and searchsorted output defs
  paddle/fluid/framework/new_executor/interpreter/interpreter_util.cc
  paddle/phi/kernels/cpu/rnn_kernel.cc
  paddle/phi/kernels/cpu/searchsorted_kernel.cc
  paddle/phi/kernels/gpu/rnn_kernel.cu.cc
  paddle/phi/kernels/gpu/searchsorted_kernel.cu
  paddle/phi/kernels/xpu/rnn_kernel.cc
Labels: contributor, status: proposed

#50901 【Hackathon 4 No.14】Add Polar to paddle
  python/paddle/__init__.py
  python/paddle/fluid/tests/unittests/test_polar.py
  python/paddle/tensor/__init__.py
  python/paddle/tensor/creation.py
Labels: contributor, API

#51446 [phi][jit] clean paddle/phi/kernels/jit Unused methods
  AUTHORS.md
  paddle/phi/kernels/cpu/layer_norm_grad_kernel.cc
  paddle/phi/kernels/funcs/jit/benchmark.cc
  paddle/phi/kernels/funcs/jit/gen/CMakeLists.txt
  paddle/phi/kernels/funcs/jit/gen/blas.cc
  paddle/phi/kernels/funcs/jit/gen/blas.h
  paddle/phi/kernels/funcs/jit/gen/hopv.cc
  paddle/phi/kernels/funcs/jit/gen/hopv.h
  paddle/phi/kernels/funcs/jit/helper.cc
  paddle/phi/kernels/funcs/jit/kernel_base.h
  paddle/phi/kernels/funcs/jit/more/mix/CMakeLists.txt
  paddle/phi/kernels/funcs/jit/more/mix/mix.cc
  paddle/phi/kernels/funcs/jit/more/mix/mix.h
  paddle/phi/kernels/funcs/jit/more/mkl/CMakeLists.txt
  paddle/phi/kernels/funcs/jit/more/mkl/mkl.cc
  paddle/phi/kernels/funcs/jit/more/mkl/mkl.h
  paddle/phi/kernels/funcs/jit/refer/CMakeLists.txt
  paddle/phi/kernels/funcs/jit/refer/refer.cc
  paddle/phi/kernels/funcs/jit/refer/refer.h
  paddle/phi/kernels/funcs/jit/test.cc
Labels: contributor, status: proposed

#51714 【Hackathon No.31】 除0问题修复 Case17:paddle.incubate.graph_reindex
  paddle/phi/kernels/cpu/graph_reindex_kernel.cc
  paddle/phi/kernels/gpu/graph_reindex_kernel.cu
  python/paddle/fluid/tests/unittests/test_graph_reindex.py
Labels: contributor, status: proposed

#51357 [PHI] Add multinomial output defs
  paddle/fluid/framework/new_executor/interpreter/interpreter_util.cc
  paddle/phi/kernels/cpu/multinomial_kernel.cc
  paddle/phi/kernels/gpu/multinomial_kernel.cu
Labels: contributor, status: proposed

#51185 【Hackathon No58】-fix atan2
  paddle/phi/kernels/gpu/atan2_grad_kernel.cu
  paddle/phi/kernels/gpu/atan2_kernel.cu
  paddle/phi/kernels/impl/atan2_kernel_impl.h
  python/paddle/fluid/tests/unittests/test_atan2_op.py
Labels: contributor, status: proposed

#50923 【Hackathon No.46】为 Paddle gumbel_softmax 算子实现 float16 数据类型支持
  paddle/phi/kernels/gpu/gumbel_softmax_grad_kernel.cu
  paddle/phi/kernels/gpu/gumbel_softmax_kernel.cu
  python/paddle/fluid/tests/unittests/test_gumbel_softmax_op.py
  python/paddle/nn/functional/activation.py
Labels: contributor, status: proposed

#51736 [bug fix] fix fp16 dtype checking for diff op
  python/paddle/fluid/tests/unittests/test_diff_op.py
  python/paddle/tensor/math.py
Labels: contributor

#51407 [phi] Add output defs for argsort kernel
  paddle/fluid/framework/new_executor/interpreter/interpreter_util.cc
  paddle/phi/kernels/cpu/argsort_kernel.cc
  paddle/phi/kernels/gpu/argsort_kernel.cu
  paddle/phi/kernels/xpu/argsort_kernel.cc
Labels: contributor, status: proposed

#51563 resgister for ftt_r2c, ftt_c2_r
  paddle/fluid/framework/new_executor/interpreter/interpreter_util.cc
  paddle/phi/kernels/cpu/fft_kernel.cc
  paddle/phi/kernels/gpu/fft_kernel.cu
Labels: contributor, status: proposed

#51770 【Hackathon No.89】 Remove circle import Part4
  python/paddle/jit/dy2static/partial_program.py
Labels: contributor

#50986 [Hackathon NO.71] 为 Paddle-TRT 添加 pad3d 算子
  paddle/fluid/framework/op_desc.cc
  paddle/fluid/framework/op_desc.h
  paddle/fluid/inference/api/analysis_predictor.cc
  paddle/fluid/inference/tensorrt/convert/CMakeLists.txt
  paddle/fluid/inference/tensorrt/convert/pad3d_op.cc
  paddle/fluid/inference/tensorrt/op_teller.cc
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_pad3d.py
Labels: contributor, status: proposed

#51571 [xpu] fused_MT xpu kernel support
  cmake/external/xpu.cmake
  paddle/fluid/framework/ir/CMakeLists.txt
  paddle/fluid/framework/ir/fuse_multi_transformer_layer_pass_tester.cc
  paddle/fluid/framework/ir/node.h
  paddle/fluid/framework/ir/pass.cc
  paddle/fluid/framework/ir/pass_tester_helper.h
  paddle/fluid/framework/ir/xpu/fused_multi_transformer_xpu_quant_pass.cc
  paddle/fluid/framework/ir/xpu/fused_multi_transformer_xpu_quant_pass_tester.cc
  paddle/fluid/inference/api/paddle_pass_builder.cc
  paddle/phi/api/yaml/static_ops.yaml
  paddle/phi/backends/xpu/xpu2_op_list.cc
  paddle/phi/infermeta/fusion.cc
  paddle/phi/infermeta/fusion.h
  paddle/phi/kernels/fusion/xpu/fused_multi_transformer_xpu_kernel.cc
Labels: contributor, status: proposed

#51771 [CodeStyle][UP004] remove useless object inheritance
  paddle/fluid/imperative/README.md
  pyproject.toml
  python/paddle/device/__init__.py
  python/paddle/distributed/fleet/base/runtime_factory.py
  python/paddle/distributed/passes/auto_parallel_bf16.py
  python/paddle/distributed/passes/auto_parallel_sharding.py
  python/paddle/fluid/tests/unittests/prim/model/bert.py
  python/paddle/fluid/tests/unittests/ps/static_gpubox_trainer.py
  python/paddle/fluid/tests/unittests/xpu/test_warpctc_op_xpu.py
  python/paddle/jit/dy2static/program_translator.py
  python/paddle/quantization/config.py
  python/paddle/quantization/quantize.py
  tools/parse_kernel_info.py
Labels: contributor

#51109 add LoongArch support
  CMakeLists.txt
  cmake/external/openblas.cmake
  cmake/flags.cmake
  paddle/fluid/operators/search_compute.h
  paddle/fluid/platform/denormal.cc
  paddle/phi/backends/cpu/cpu_info.cc
  paddle/phi/backends/cpu/cpu_info.h
Labels: contributor, heco

#51801 Fix fc_xpu_fuse_pass Attribute (beta) is not set correctly error
  paddle/fluid/framework/ir/xpu/fc_xpu_fuse_pass.cc
Labels: contributor

#51775 Fix typos
  paddle/phi/README.md
  paddle/phi/core/compat/get_kerneltype_forvar_utils.cc
  paddle/phi/core/compat/op_utils.h
  paddle/phi/core/distributed/store/tcp_store.cc
  paddle/phi/core/distributed/store/tcp_utils.cc
Labels: contributor

#51850 fix softmaxce null point in shape test
  paddle/fluid/operators/softmax_with_cross_entropy_op.cc
Labels: contributor

#51784 【Hackathon No.31】 Fix Null pointer bug for Case4:paddle.incubate.graph_khop_sampler
  paddle/fluid/operators/graph_khop_sampler_op.cu
  paddle/fluid/operators/graph_khop_sampler_op.h
  python/paddle/fluid/tests/unittests/test_graph_khop_sampler.py
Labels: contributor

#51834 [CodeStyle][UP005] remove deprecated unittest alias
  pyproject.toml
  python/paddle/fluid/tests/unittests/dygraph_to_static/test_ignore_module.py
  python/paddle/fluid/tests/unittests/prim/test_comp_get_grad_op_desc_prim_disabled.py
  python/paddle/fluid/tests/unittests/prim/test_comp_get_grad_op_desc_prim_enabled.py
  python/paddle/fluid/tests/unittests/prim/test_comp_skip_op_set.py
  python/paddle/fluid/tests/unittests/test_dot_op.py
Labels: contributor

#51839 [CodeStyle][C400] replace unnecessary generator list
  python/paddle/distributed/auto_parallel/operators/dist_pnorm.py
  python/paddle/distributed/auto_parallel/reshard.py
  python/paddle/distributed/auto_parallel/tuner/recorder.py
  python/paddle/distributed/fleet/recompute/recompute.py
  python/paddle/fluid/tests/unittests/autograd/utils.py
  python/paddle/fluid/tests/unittests/test_conv2d_layer.py
  python/paddle/nn/layer/conv.py
  python/paddle/tensor/manipulation.py
  python/paddle/tensor/math.py
Labels: contributor

#51710 fix Tensor::mutable_data lack custom place & fix gtest not load custom device
  paddle/fluid/inference/api/analysis_predictor.cc
  paddle/fluid/inference/api/details/zero_copy_tensor.cc
  paddle/fluid/inference/api/paddle_tensor.h
Labels: contributor, status: proposed

#51845 [CodeStyle][C401&C402] replace unnecessary generator set and dict
  python/paddle/distributed/auto_parallel/tuner/tunable_space.py
  python/paddle/distributed/auto_parallel/tuner/tunable_variable.py
  python/paddle/distributed/fleet/meta_parallel/parallel_layers/pp_layers.py
  python/paddle/distributed/ps/utils/public.py
  python/paddle/incubate/distributed/fleet/parameter_server/distribute_transpiler/distributed_strategy.py
  python/paddle/static/quantization/tests/quant2_int8_image_classification_comparison.py
  python/paddle/static/quantization/tests/quant2_int8_nlp_comparison.py
Labels: contributor

#51598 remove duplicate mkldnn_data_type
  paddle/fluid/framework/ir/op_compat_sensible_pass.cc
  paddle/phi/api/yaml/op_compat.yaml
Labels: contributor, status: proposed

#51935 [CodeStyple][B011] replace assert false with raise AssertionError
  paddle/fluid/eager/auto_code_generator/generator/eager_gen.py
  paddle/fluid/eager/auto_code_generator/generator/python_c_gen.py
  pyproject.toml
  python/paddle/dataset/imikolov.py
  python/paddle/distributed/auto_parallel/cost/base_cost.py
  python/paddle/distributed/auto_parallel/dist_context.py
  python/paddle/distributed/auto_parallel/operators/common.py
  python/paddle/distributed/auto_parallel/process_group.py
  python/paddle/distributed/auto_parallel/utils.py
  python/paddle/distributed/collective.py
  python/paddle/distributed/fleet/fleet.py
  python/paddle/distributed/fleet/launch_utils.py
  python/paddle/distributed/fleet/meta_optimizers/ascend/ascend_optimizer.py
  python/paddle/distributed/fleet/meta_optimizers/ascend/ascend_parser.py
  python/paddle/distributed/fleet/meta_optimizers/dgc_optimizer.py
  python/paddle/fluid/tests/unittests/check_nan_inf_base.py
  python/paddle/fluid/tests/unittests/check_nan_inf_base_dygraph.py
  python/paddle/fluid/tests/unittests/ir/inference/auto_scan_test.py
  python/paddle/fluid/tests/unittests/test_matmul_op_with_head.py
  python/paddle/fluid/tests/unittests/test_nan_inf.py
  python/paddle/incubate/distributed/fleet/collective.py
  python/paddle/incubate/distributed/models/moe/moe_layer.py
  python/paddle/jit/dy2static/convert_operators.py
  python/paddle/nn/layer/transformer.py
  python/paddle/text/datasets/imikolov.py
Labels: contributor

#51847 【Hackathon 4 No.31】Case7:paddle.distribution.Beta
  paddle/phi/kernels/cpu/stack_kernel.cc
  paddle/phi/kernels/funcs/stack_and_unstack.h
  python/paddle/fluid/tests/unittests/distribution/test_distribution_beta.py
Labels: contributor

#51941 [Test Mv] legacy_test
  python/paddle/tests/CMakeLists.txt
  test/legacy_test/CMakeLists.txt
  test/legacy_test/dist_hapi_mnist_dynamic.py
  test/legacy_test/dist_hapi_mnist_static.py
  test/legacy_test/dist_hapi_pure_fp16_static.py
  test/legacy_test/hapi_mnist_bf16_static.py
  test/legacy_test/hubconf.py
  test/legacy_test/test_async_read_write.py
  test/legacy_test/test_audio_backend.py
  test/legacy_test/test_audio_datasets.py
  test/legacy_test/test_audio_functions.py
  test/legacy_test/test_audio_logmel_feature.py
  test/legacy_test/test_audio_mel_feature.py
  test/legacy_test/test_callback_early_stop.py
  test/legacy_test/test_callback_reduce_lr_on_plateau.py
  test/legacy_test/test_callback_visualdl.py
  test/legacy_test/test_callback_wandb.py
  test/legacy_test/test_callbacks.py
  test/legacy_test/test_dataset_cifar.py
  test/legacy_test/test_dataset_conll05.py
  test/legacy_test/test_dataset_imdb.py
  test/legacy_test/test_dataset_imikolov.py
  test/legacy_test/test_dataset_movielens.py
  test/legacy_test/test_dataset_uci_housing.py
  test/legacy_test/test_dataset_voc.py
  test/legacy_test/test_dataset_wmt.py
  test/legacy_test/test_datasets.py
  test/legacy_test/test_dist_hapi_model.py
  test/legacy_test/test_dlpack.py
  test/legacy_test/test_download.py
  test/legacy_test/test_hapi_amp.py
  test/legacy_test/test_hapi_hub.py
  test/legacy_test/test_hapi_hub_model.py
  test/legacy_test/test_logger.py
  test/legacy_test/test_metrics.py
  test/legacy_test/test_model.py
  test/legacy_test/test_ops_roi_align.py
  test/legacy_test/test_ops_roi_pool.py
  test/legacy_test/test_pretrained_model.py
  test/legacy_test/test_progressbar.py
  test/legacy_test/test_read_file.py
  test/legacy_test/test_transforms.py
  test/legacy_test/test_transforms_static.py
  test/legacy_test/test_utils_lazyimport.py
  test/legacy_test/test_vision_models.py
Labels: contributor

#51922 [CodeStyle][UP018] remove unnecessary call to `str`
  pyproject.toml
  python/paddle/distributed/auto_parallel/operators/common.py
  python/paddle/distributed/auto_parallel/operators/dist_check_finite_and_unscale.py
  python/paddle/distributed/passes/auto_parallel_grad_clip.py
  python/paddle/distributed/passes/auto_parallel_sharding.py
  python/paddle/fluid/tests/unittests/check_nan_inf_base.py
  python/paddle/fluid/tests/unittests/check_nan_inf_base_dygraph.py
  python/paddle/fluid/tests/unittests/collective/test_gen_nccl_id_op.py
  python/paddle/fluid/tests/unittests/mkldnn/check_flags_mkldnn_ops_on_off.py
  python/paddle/fluid/tests/unittests/mkldnn/check_flags_use_mkldnn.py
  python/paddle/fluid/tests/unittests/mkldnn/test_flags_mkldnn_ops_on_off.py
  python/paddle/fluid/tests/unittests/mkldnn/test_flags_use_mkldnn.py
  python/paddle/fluid/tests/unittests/test_nan_inf.py
  python/paddle/fluid/tests/unittests/xpu/test_gen_bkcl_id_op.py
  python/paddle/incubate/passes/ir.py
  python/paddle/static/io.py
Labels: contributor

#51601 support auto generate for dirichlet
  paddle/fluid/operators/dirichlet_op.cc
  paddle/phi/api/yaml/legacy_ops.yaml
  paddle/phi/api/yaml/op_compat.yaml
  paddle/phi/api/yaml/ops.yaml
Labels: contributor, status: proposed

#51590 support auto generate for p_norm
  paddle/fluid/operators/p_norm_op.cc
  paddle/phi/api/yaml/backward.yaml
  paddle/phi/api/yaml/legacy_backward.yaml
  paddle/phi/api/yaml/legacy_ops.yaml
  paddle/phi/api/yaml/op_compat.yaml
  paddle/phi/api/yaml/op_version.yaml
  paddle/phi/api/yaml/ops.yaml
  paddle/phi/ops/compat/p_norm_sig.cc
Labels: contributor, status: proposed

#51887 add autogen code support for index_add op
  paddle/fluid/operators/index_add_op.cc
  paddle/phi/api/yaml/backward.yaml
  paddle/phi/api/yaml/legacy_backward.yaml
  paddle/phi/api/yaml/legacy_ops.yaml
  paddle/phi/api/yaml/op_compat.yaml
  paddle/phi/api/yaml/ops.yaml
  paddle/phi/ops/compat/index_add_sig.cc
Labels: contributor

#51869 remove net_drawer.py, memory_analysis.py
  python/paddle/fluid/memory_analysis.py
  python/paddle/fluid/net_drawer.py
  python/paddle/fluid/tests/unittests/test_memory_analysis.py
Labels: contributor

#50021 Extract fused_transpose op dedicated for oneDNN fuse passes
  paddle/fluid/framework/ir/graph_pattern_detector.cc
  paddle/fluid/framework/ir/graph_pattern_detector.h
  paddle/fluid/framework/ir/mkldnn/compute_propagate_scales_mkldnn_pass.cc
  paddle/fluid/framework/ir/mkldnn/cpu_quantize_pass.cc
  paddle/fluid/framework/ir/mkldnn/cpu_quantize_pass_tester.cc
  paddle/fluid/framework/ir/mkldnn/cpu_quantize_placement_pass.cc
  paddle/fluid/framework/ir/mkldnn/mkldnn_pass_util.h
  paddle/fluid/framework/ir/mkldnn/operator_reshape2_onednn_fuse_pass.cc
  paddle/fluid/framework/ir/mkldnn/operator_unsqueeze2_onednn_fuse_pass.cc
  paddle/fluid/framework/ir/mkldnn/quant_transpose2_dequant_onednn_fuse_pass.cc
  paddle/fluid/framework/ir/mkldnn/quant_transpose2_dequant_onednn_fuse_pass.h
  paddle/fluid/framework/ir/mkldnn/squeeze2_transpose2_onednn_fuse_pass.cc
  paddle/fluid/inference/api/mkldnn_quantizer.cc
  paddle/fluid/inference/api/mkldnn_quantizer_config.cc
  paddle/fluid/inference/tests/api/analyzer_int8_object_detection_tester.cc
  paddle/fluid/operators/compat/fused_transpose.pbtxt
  paddle/fluid/operators/compat/transpose.pbtxt
  paddle/fluid/operators/compat/transpose2.pbtxt
  paddle/fluid/operators/fused/fused_transpose_op.cc
  paddle/fluid/operators/mkldnn/nhwc_op_tests.cmake
  paddle/fluid/operators/mkldnn/test_mkldnn_op_nhwc.cc
  paddle/fluid/operators/mkldnn/transpose_mkldnn_op.cc
  paddle/fluid/operators/ops_extra_info.h
  paddle/fluid/operators/transpose_op.cc
  paddle/fluid/operators/transpose_op.h
  paddle/phi/api/yaml/op_compat.yaml
  paddle/phi/backends/onednn/onednn_reuse.h
  paddle/phi/kernels/fusion/onednn/fused_transpose_kernel.cc
  paddle/phi/kernels/onednn/transpose_kernel.cc
  paddle/phi/ops/compat/fused_transpose_sig.cc
  python/paddle/fluid/tests/unittests/ir/inference/test_onednn_operator_reshape2_fuse_pass.py
  python/paddle/fluid/tests/unittests/ir/inference/test_onednn_operator_unsqueeze2_fuse_pass.py
  python/paddle/fluid/tests/unittests/ir/inference/test_onednn_quant_transpose_dequant_fuse_pass.py
  python/paddle/fluid/tests/unittests/ir/inference/test_onednn_squeeze2_transpose2_fuse_pass.py
Labels: Intel, contributor

#51687 [Zero-Dim] Support 0-D tensor for some oneDNN unary kernels
  paddle/fluid/framework/data_transform.cc
  paddle/phi/backends/onednn/onednn_helper.h
  paddle/phi/backends/onednn/onednn_reuse.h
  paddle/phi/kernels/funcs/data_layout_transform.cc
  paddle/phi/kernels/funcs/data_layout_transform.h
  paddle/phi/kernels/onednn/log_softmax_kernel.cc
  paddle/phi/kernels/transfer_layout_kernel.cc
  python/paddle/fluid/tests/unittests/mkldnn/test_activation_mkldnn_op.py
  python/paddle/fluid/tests/unittests/mkldnn/test_cast_mkldnn_op.py
  python/paddle/fluid/tests/unittests/mkldnn/test_clip_mkldnn_op.py
  python/paddle/fluid/tests/unittests/mkldnn/test_log_softmax_mkldnn_op.py
  python/paddle/fluid/tests/unittests/mkldnn/test_scale_mkldnn_op.py
  python/paddle/fluid/tests/unittests/mkldnn/test_softmax_mkldnn_op.py
  python/paddle/fluid/tests/unittests/test_softmax_op.py
Labels: Intel, contributor, status: proposed

#51994 [CodeStyle][UP012] Unnecessary call to `encode` as UTF-8
  pyproject.toml
  python/paddle/fluid/tests/unittests/test_nan_inf.py
  tools/test_print_signatures.py
Labels: contributor, status: proposed

#51969 [CodeStyle][C404] Unnecessary list comprehension (rewrite as a dict comprehension)
  python/paddle/distributed/passes/auto_parallel_sharding.py
  python/paddle/fluid/tests/unittests/distributed_fused_lamb_test_base.py
Labels: contributor

#50926 【Hackathon No.45】为 Paddle logical 算子实现 float16 数据类型支持
  paddle/phi/kernels/kps/logical_kernel.cu
  python/paddle/fluid/tests/unittests/test_logical_op.py
  python/paddle/tensor/logic.py
Labels: contributor, status: proposed

#51968 [CodeStyle][C403] Unnecessary list comprehension (rewrite as a set comprehension)
  python/paddle/distributed/fleet/base/role_maker.py
  python/paddle/distributed/fleet/meta_optimizers/dygraph_optimizer/dygraph_sharding_optimizer.py
  python/paddle/distributed/fleet/meta_optimizers/sharding/fp16_helper.py
  python/paddle/distributed/fleet/meta_optimizers/sharding/gradient_clip_helper.py
  python/paddle/distributed/fleet/meta_optimizers/sharding/shard.py
  python/paddle/distributed/fleet/meta_optimizers/sharding_optimizer.py
  python/paddle/distributed/launch/plugins/__init__.py
  python/paddle/distributed/parallel.py
  python/paddle/distributed/passes/auto_parallel_data_parallel_optimization.py
  python/paddle/distributed/passes/auto_parallel_sharding.py
  python/paddle/distributed/transpiler/collective.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/test_save_inference_model.py
  python/paddle/fluid/tests/unittests/test_backward.py
  python/paddle/fluid/tests/unittests/test_target_assign_op.py
  python/paddle/incubate/autograd/composite_rules.py
  python/paddle/optimizer/optimizer.py
  python/paddle/static/io.py
  python/paddle/utils/cpp_extension/extension_utils.py
  tools/diff_use_default_grad_op_maker.py
Labels: contributor

#51358 [PHI] Add nanmedian output defs
  paddle/fluid/framework/new_executor/interpreter/interpreter_util.cc
  paddle/phi/kernels/cpu/nanmedian_kernel.cc
  paddle/phi/kernels/gpu/nanmedian_kernel.cu
Labels: contributor, status: proposed

#51532 【PaddlePaddle Hackathon 4】No.63 fix temporal_shift and conj
  paddle/phi/kernels/gpu/complex_kernel.cu
  paddle/phi/kernels/gpu/temporal_shift_grad_kernel.cu
  paddle/phi/kernels/gpu/temporal_shift_kernel.cu
  python/paddle/fluid/tests/unittests/test_conj_op.py
  python/paddle/fluid/tests/unittests/test_temporal_shift_op.py
Labels: contributor, status: proposed

#51943 [Test Mv] reader to legacy_test
  python/CMakeLists.txt
  python/paddle/reader/tests/CMakeLists.txt
  python/paddle/reader/tests/__init__.py
  test/CMakeLists.txt
  test/legacy_test/CMakeLists.txt
  test/legacy_test/test_decorator.py
Labels: contributor

#51956 [Bug fixes] fix distributed graph engine
  paddle/fluid/distributed/ps/service/graph_brpc_client.cc
  paddle/fluid/distributed/ps/service/graph_brpc_server.cc
Labels: contributor

#51891 support auto generate for nms
  paddle/fluid/operators/detection/CMakeLists.txt
  paddle/fluid/operators/detection/nms_op.cc
  paddle/phi/api/yaml/legacy_ops.yaml
  paddle/phi/api/yaml/op_compat.yaml
  paddle/phi/api/yaml/ops.yaml
Labels: contributor

#51967 let op <lod_reset> support xpu
  paddle/fluid/operators/lod_reset_op.cc
  paddle/fluid/operators/lod_reset_op.h
  paddle/phi/backends/xpu/xpu2_op_list.cc
Labels: contributor

#51993 Add output defs for clip_by_norm kernel
  paddle/fluid/framework/new_executor/interpreter/interpreter_util.cc
Labels: contributor, status: proposed

#51945 [Test Mv] python/paddle/fluid/tests/book to test/book
  python/paddle/fluid/tests/CMakeLists.txt
  python/paddle/fluid/tests/book/__init__.py
  test/CMakeLists.txt
  test/book/.gitignore
  test/book/CMakeLists.txt
  test/book/notest_understand_sentiment.py
  test/book/test_fit_a_line.py
  test/book/test_image_classification.py
  test/book/test_recognize_digits.py
  test/book/test_recommender_system.py
  test/book/test_word2vec_book.py
Labels: contributor

#51944 [Test Mv] python/paddle/fluid/tests to test/legacy_test
  test/legacy_test/test_detection.py
  test/legacy_test/test_sequential.py
Labels: contributor

#51835 【PaddlePaddle Hackathon 4 No.40】为 Paddle 优化 kthvalue op 在 GPU 上的计算性能
  paddle/phi/kernels/funcs/top_k_function_cuda.h
  paddle/phi/kernels/gpu/kthvalue_grad_kernel.cu
  paddle/phi/kernels/gpu/kthvalue_kernel.cu
Labels: contributor

#51353 [PHI]fix momentum dtype infer
  paddle/phi/infermeta/multiary.cc
  paddle/phi/kernels/gpu/momentum_kernel.cu
  paddle/phi/kernels/xpu/momentum_kernel.cc
Labels: contributor, status: proposed

#51946 [Test Mv] python/paddle/fluid/tests/custom_kernel/*.py to test/custom_kernel
  python/paddle/fluid/tests/CMakeLists.txt
  test/CMakeLists.txt
  test/custom_kernel/CMakeLists.txt
  test/custom_kernel/__init__.py
  test/custom_kernel/custom_kernel_dot_c_setup.py
  test/custom_kernel/custom_kernel_dot_setup.py
  test/custom_kernel/test_custom_kernel_dot.py
  test/custom_kernel/test_custom_kernel_load.py
Labels: contributor

#52064 [Test Mv] remove mlu
  python/paddle/fluid/tests/unittests/CMakeLists.txt
  python/paddle/fluid/tests/unittests/mlu/CMakeLists.txt
  python/paddle/fluid/tests/unittests/mlu/c_comm_init_op_mlu.py
  python/paddle/fluid/tests/unittests/mlu/collective_allgather_api.py
  python/paddle/fluid/tests/unittests/mlu/collective_allgather_op.py
  python/paddle/fluid/tests/unittests/mlu/collective_allreduce_api.py
  python/paddle/fluid/tests/unittests/mlu/collective_allreduce_op.py
  python/paddle/fluid/tests/unittests/mlu/collective_broadcast_api.py
  python/paddle/fluid/tests/unittests/mlu/collective_broadcast_op.py
  python/paddle/fluid/tests/unittests/mlu/collective_reduce_api.py
  python/paddle/fluid/tests/unittests/mlu/collective_reduce_op.py
  python/paddle/fluid/tests/unittests/mlu/multi_process_mlu.py
  python/paddle/fluid/tests/unittests/mlu/nproc_process_mlu.py
  python/paddle/fluid/tests/unittests/mlu/parallel_dygraph_sync_batch_norm.py
  python/paddle/fluid/tests/unittests/mlu/test_c_comm_init_op_mlu.sh
  python/paddle/fluid/tests/unittests/mlu/test_collective_allgather.py
  python/paddle/fluid/tests/unittests/mlu/test_collective_allgather_api_mlu.py
  python/paddle/fluid/tests/unittests/mlu/test_collective_allreduce_api_mlu.py
  python/paddle/fluid/tests/unittests/mlu/test_collective_allreduce_max.py
  python/paddle/fluid/tests/unittests/mlu/test_collective_allreduce_min.py
  python/paddle/fluid/tests/unittests/mlu/test_collective_allreduce_prod.py
  python/paddle/fluid/tests/unittests/mlu/test_collective_allreduce_sum.py
  python/paddle/fluid/tests/unittests/mlu/test_collective_api_base_mlu.py
  python/paddle/fluid/tests/unittests/mlu/test_collective_base_mlu.py
  python/paddle/fluid/tests/unittests/mlu/test_collective_broadcast.py
  python/paddle/fluid/tests/unittests/mlu/test_collective_broadcast_api_mlu.py
  python/paddle/fluid/tests/unittests/mlu/test_collective_reduce_api_mlu.py
  python/paddle/fluid/tests/unittests/mlu/test_collective_reduce_max.py
  python/paddle/fluid/tests/unittests/mlu/test_collective_reduce_min.py
  python/paddle/fluid/tests/unittests/mlu/test_collective_reduce_prod.py
  python/paddle/fluid/tests/unittests/mlu/test_collective_reduce_sum.py
  python/paddle/fluid/tests/unittests/mlu/test_launch_async_mlu.sh
  python/paddle/fluid/tests/unittests/mlu/test_launch_cloud_mlu.sh
  python/paddle/fluid/tests/unittests/mlu/test_launch_nproc_mlu.sh
  python/paddle/fluid/tests/unittests/mlu/test_merged_adam_op_mlu.py
  python/paddle/fluid/tests/unittests/mlu/test_merged_momentum_op_mlu.py
  python/paddle/fluid/tests/unittests/mlu/test_parallel_dygraph_sync_batch_norm_mlu.py
  python/paddle/fluid/tests/unittests/mlu/test_spawn_mlu.py
  python/paddle/fluid/tests/unittests/mlu/test_sync_batch_norm_op_mlu.sh
Labels: contributor, status: proposed

#52050 [CodeStyle][UP009] mv unnecessary utf8 declaration
  pyproject.toml
  python/paddle/fluid/tests/unittests/dygraph_to_static/seq2seq_dygraph_model.py
  python/paddle/fluid/tests/unittests/dygraph_to_static/seq2seq_utils.py
  python/paddle/fluid/tests/unittests/test_multimarginloss.py
  python/paddle/fluid/tests/unittests/test_tdm_sampler_op.py
  python/paddle/nn/functional/loss.py
  python/paddle/nn/layer/loss.py
  python/paddle/static/nn/loss.py
  tools/coverage/coverage_diff.py
  tools/coverage/coverage_diff_list.py
  tools/coverage/coverage_lines.py
  tools/coverage/cuda_clean.py
  tools/coverage/gcda_clean.py
  tools/coverage/pull_request.py
  tools/coverage/python_coverage.py
  tools/final_ut_parallel_rule.py
  tools/get_ut_mem_map.py
Labels: contributor, status: proposed

#52059 [CodeStyle][UP028] using yield from
  pyproject.toml
  python/paddle/dataset/imdb.py
  python/paddle/distributed/fleet/data_generator/data_generator.py
  python/paddle/fluid/tests/unittests/dist_text_classification.py
  python/paddle/fluid/tests/unittests/feed_data_reader.py
  python/paddle/fluid/tests/unittests/test_imperative_decorator.py
  python/paddle/fluid/tests/unittests/test_parallel_executor_transformer.py
  python/paddle/nn/layer/layers.py
  python/paddle/reader/decorator.py
  python/paddle/utils/layers_utils.py
Labels: contributor, status: proposed

#52025 [CodeStyle][UP027] Replace unpacked list comprehension with a generator expression
  paddle/fluid/operators/generator/parse_utils.py
  pyproject.toml
  python/paddle/fluid/tests/unittests/dygraph_to_static/test_lac.py
  python/paddle/fluid/tests/unittests/test_imperative_deepcf.py
  python/paddle/fluid/tests/unittests/test_sample_logits_op.py
  python/paddle/fluid/tests/unittests/test_transformer_api.py
  python/paddle/tensor/einsum.py
Labels: contributor, status: proposed

#52118 [CodeStyle][B016] Cannot raise a literal. Did you intend to return it or raise an Exception?
  pyproject.toml
  python/paddle/distributed/launch/plugins/__init__.py
Labels: contributor, status: proposed

#52057 [CodeStyle][C411] replace list() with []
  pyproject.toml
  python/paddle/distributed/auto_parallel/reshard.py
Labels: contributor, status: proposed

#52002 [Fix Bug] get_new_shape and get_new_data_from_tensor support fallback to CPU on Custom Device
  paddle/phi/kernels/funcs/interpolate_function.h
Labels: contributor, status: proposed

#51942 [Test Mv] quantization
  python/CMakeLists.txt
  python/paddle/tests/CMakeLists.txt
  test/CMakeLists.txt
  test/quantization/CMakeLists.txt
  test/quantization/test_customized_quanter.py
  test/quantization/test_ptq.py
  test/quantization/test_qat.py
  test/quantization/test_quant.py
  test/quantization/test_stub.py
  test/quantization/test_trace_quanter.py
Labels: contributor
