Repository PaddlePaddle/Paddle, pull requests merged in 2023-04, with the labels that each got.

#52353 [Test Mv] quantization
  python/CMakeLists.txt
  python/paddle/static/quantization/tests/CMakeLists.txt
  test/quantization/CMakeLists.txt
  test/quantization/README.md
  test/quantization/__init__.py
  test/quantization/convert_model2dot.py
  test/quantization/imperative_test_utils.py
  test/quantization/quant2_int8_image_classification_comparison.py
  test/quantization/quant2_int8_lstm_model.py
  test/quantization/quant2_int8_nlp_comparison.py
  test/quantization/quant_int8_image_classification_comparison.py
  test/quantization/test_graph.py
  test/quantization/test_imperative_out_scale.py
  test/quantization/test_imperative_ptq.py
  test/quantization/test_imperative_qat.py
  test/quantization/test_imperative_qat_amp.py
  test/quantization/test_imperative_qat_channelwise.py
  test/quantization/test_imperative_qat_fuse.py
  test/quantization/test_imperative_qat_lsq.py
  test/quantization/test_imperative_qat_matmul.py
  test/quantization/test_imperative_qat_user_defined.py
  test/quantization/test_imperative_skip_op.py
  test/quantization/test_moving_average_abs_max_scale_op.py
  test/quantization/test_post_training_quantization_lstm_model.py
  test/quantization/test_post_training_quantization_mnist.py
  test/quantization/test_post_training_quantization_mobilenetv1.py
  test/quantization/test_post_training_quantization_program_resnet50.py
  test/quantization/test_post_training_quantization_resnet50.py
  test/quantization/test_post_training_quantization_while.py
  test/quantization/test_quant2_int8_mkldnn_pass.py
  test/quantization/test_quantization_mkldnn_pass.py
  test/quantization/test_quantization_pass.py
  test/quantization/test_quantization_scale_pass.py
  test/quantization/test_user_defined_quantization.py
  test/quantization/test_weight_quantization_mobilenetv1.py
Labels: contributor, status: not progressed

#52372 rename_batch_norm_grad_grad
  paddle/phi/api/yaml/legacy_backward.yaml
  paddle/phi/kernels/cpu/batch_norm_grad_kernel.cc
  paddle/phi/kernels/gpu/batch_norm_grad_kernel.cu
  paddle/phi/ops/compat/batch_norm_sig.cc
Labels: contributor, status: proposed

#51649 【PaddlePaddle Hackathon 4】No.56 : add fp16 test and bf16 test for diag, diagonal, fill and fill_diagonal_tensor
  paddle/fluid/operators/fill_op.cu.cc
  paddle/phi/kernels/gpu/diag_grad_kernel.cu
  paddle/phi/kernels/gpu/diag_kernel.cu
  python/paddle/fluid/tests/unittests/test_diag_v2.py
  python/paddle/fluid/tests/unittests/test_diagonal_op.py
  python/paddle/fluid/tests/unittests/test_fill_diagonal_tensor_op.py
  python/paddle/fluid/tests/unittests/test_fill_op.py
Labels: contributor, status: proposed

#52437 add autogen code support for auc_op
  paddle/fluid/operators/metrics/auc_op.cc
  paddle/phi/api/yaml/legacy_ops.yaml
  paddle/phi/api/yaml/op_compat.yaml
  paddle/phi/api/yaml/op_version.yaml
  paddle/phi/api/yaml/ops.yaml
  paddle/phi/ops/compat/auc_sig.cc
Labels: contributor, status: proposed

#51513 【Hackathon 4th No.24】为 Paddle 新增 paddle.sparse.is_nan 稀疏 API
  paddle/phi/api/yaml/sparse_ops.yaml
  paddle/phi/kernels/sparse/cpu/mask_kernel.cc
  paddle/phi/kernels/sparse/cpu/sparse_utils_kernel.cc
  paddle/phi/kernels/sparse/cpu/unary_kernel.cc
  paddle/phi/kernels/sparse/gpu/mask_kernel.cu
  paddle/phi/kernels/sparse/gpu/sparse_utils_kernel.cu
  paddle/phi/kernels/sparse/gpu/unary_kernel.cu
  paddle/phi/kernels/sparse/impl/unary_kernel_impl.h
  paddle/phi/kernels/sparse/sparse_utils_grad_kernel.cc
  paddle/phi/kernels/sparse/unary_kernel.h
  python/paddle/fluid/tests/unittests/test_sparse_isnan_op.py
  python/paddle/sparse/__init__.py
  python/paddle/sparse/unary.py
Labels: contributor, API

#52424 add autogen code support for accuracy
  paddle/fluid/operators/metrics/accuracy_op.cc
  paddle/phi/api/yaml/legacy_ops.yaml
  paddle/phi/api/yaml/op_compat.yaml
  paddle/phi/api/yaml/ops.yaml
Labels: contributor, status: proposed

#52079 Kernel registrar
  cmake/phi.cmake
  paddle/phi/core/kernel_registry.h
  paddle/phi/kernels/reshape_kernel.cc
Labels: contributor, status: proposed

#52378 rem is_compiled_with_mlu
  .flake8
  .pre-commit-config.yaml
  paddle/fluid/pybind/pybind.cc
  pyproject.toml
  python/CMakeLists.txt
  python/paddle/__init__.py
  python/paddle/amp/auto_cast.py
  python/paddle/amp/grad_scaler.py
  python/paddle/device/__init__.py
  python/paddle/distributed/collective.py
  python/paddle/distributed/fleet/launch.py
  python/paddle/distributed/fleet/launch_utils.py
  python/paddle/distributed/launch/context/device.py
  python/paddle/distributed/parallel.py
  python/paddle/distributed/spawn.py
  python/paddle/fluid/dygraph/varbase_patch_methods.py
  python/paddle/fluid/executor.py
  python/paddle/fluid/framework.py
  python/paddle/fluid/tests/unittests/eager_op_test.py
  python/paddle/fluid/tests/unittests/test_dist_base.py
  python/paddle/static/__init__.py
  python/paddle/static/amp/fp16_lists.py
  python/paddle/static/io.py
  tools/get_quick_disable_lt.py
Labels: contributor, status: proposed

#52422 support auto generate static for gaussian (gaussian_random)
  paddle/fluid/operators/gaussian_random_batch_size_like_op.cc
  paddle/fluid/operators/gaussian_random_batch_size_like_op.cu
  paddle/fluid/operators/gaussian_random_op.cc
  paddle/fluid/operators/unity_build_rule.cmake
  paddle/phi/api/yaml/op_compat.yaml
  paddle/phi/api/yaml/op_version.yaml
  paddle/phi/api/yaml/static_ops.yaml
Labels: contributor, status: proposed

#52413 【Hackathon No.64】增加 kron 算子FP16/BF16单测，unbind 算子FP16单测
  paddle/phi/kernels/gpu/kron_grad_kernel.cu
  paddle/phi/kernels/gpu/kron_kernel.cu
  python/paddle/fluid/tests/unittests/test_kron_op.py
  python/paddle/fluid/tests/unittests/test_unbind_op.py
Labels: contributor, status: proposed

#50925 【Hackathon No.50】为 Paddle lerp 算子实现 float16 数据类型支持
  paddle/phi/kernels/gpu/lerp_grad_kernel.cu
  paddle/phi/kernels/gpu/lerp_kernel.cu
  paddle/phi/kernels/impl/lerp_kernel_impl.h
  python/paddle/fluid/tests/unittests/test_lerp_op.py
  python/paddle/tensor/math.py
Labels: contributor, status: proposed

#52369 【Hackathon No.62】增加margin_cross_entropy BF16算子单测，transfer_layout，dropout_nd 算子FP16/BF16单测
  paddle/fluid/operators/margin_cross_entropy_op.cu
  paddle/phi/kernels/primitive/functor_primitives.h
  python/paddle/fluid/tests/unittests/test_dropout_nd_op.py
  python/paddle/fluid/tests/unittests/test_margin_cross_entropy_op.py
  python/paddle/fluid/tests/unittests/test_transfer_layout_op.py
Labels: contributor

#52375 rename_bilinear_tensor_product
  paddle/fluid/operators/bilinear_tensor_product_op.cc
  paddle/phi/api/yaml/legacy_backward.yaml
  paddle/phi/api/yaml/legacy_ops.yaml
  paddle/phi/infermeta/multiary.cc
  paddle/phi/infermeta/multiary.h
  paddle/phi/kernels/bilinear_grad_kernel.h
  paddle/phi/kernels/bilinear_kernel.h
  paddle/phi/kernels/cpu/bilinear_grad_kernel.cc
  paddle/phi/kernels/cpu/bilinear_kernel.cc
  paddle/phi/kernels/gpu/bilinear_grad_kernel.cu
  paddle/phi/kernels/gpu/bilinear_kernel.cu
  paddle/phi/kernels/impl/bilinear_grad_kernel_impl.h
  paddle/phi/kernels/impl/bilinear_kernel_impl.h
  paddle/phi/ops/compat/bilinear_tensor_product_sig.cc
Labels: contributor, status: proposed

#52248 remove op.py in fluid
  python/paddle/fluid/tests/unittests/benchmark.py
  python/paddle/fluid/tests/unittests/collective/fleet/test_dgc_momentum_op.py
  python/paddle/fluid/tests/unittests/collective/fleet/test_dgc_op.py
  python/paddle/fluid/tests/unittests/collective/fleet/test_recv_save_op.py
  python/paddle/fluid/tests/unittests/eager_op_test.py
  python/paddle/fluid/tests/unittests/op.py
  python/paddle/fluid/tests/unittests/test_activation_sparse_op.py
  python/paddle/fluid/tests/unittests/test_adagrad_op.py
  python/paddle/fluid/tests/unittests/test_adam_op.py
  python/paddle/fluid/tests/unittests/test_batch_norm_op.py
  python/paddle/fluid/tests/unittests/test_beam_search_decode_op.py
  python/paddle/fluid/tests/unittests/test_beam_search_op.py
  python/paddle/fluid/tests/unittests/test_clip_by_norm_op.py
  python/paddle/fluid/tests/unittests/test_data_norm_op.py
  python/paddle/fluid/tests/unittests/test_fake_init_op.py
  python/paddle/fluid/tests/unittests/test_fill_constant_op.py
  python/paddle/fluid/tests/unittests/test_fill_op.py
  python/paddle/fluid/tests/unittests/test_ftrl_op.py
  python/paddle/fluid/tests/unittests/test_get_tensor_from_selected_rows_op.py
  python/paddle/fluid/tests/unittests/test_lamb_op.py
  python/paddle/fluid/tests/unittests/test_lookup_table_bf16_op.py
  python/paddle/fluid/tests/unittests/test_lookup_table_op.py
  python/paddle/fluid/tests/unittests/test_lookup_table_v2_op.py
  python/paddle/fluid/tests/unittests/test_merge_selectedrows_op.py
  python/paddle/fluid/tests/unittests/test_momentum_op.py
  python/paddle/fluid/tests/unittests/test_operator.py
  python/paddle/fluid/tests/unittests/test_rmsprop_op.py
  python/paddle/fluid/tests/unittests/test_scalar.py
  python/paddle/fluid/tests/unittests/test_scale_op.py
  python/paddle/fluid/tests/unittests/test_sgd_op.py
  python/paddle/fluid/tests/unittests/test_sgd_op_bf16.py
  python/paddle/fluid/tests/unittests/test_shape_op.py
  python/paddle/fluid/tests/unittests/test_share_data_op.py
  python/paddle/fluid/tests/unittests/test_sum_op.py
  python/paddle/fluid/tests/unittests/test_uniform_random_bf16_op.py
  python/paddle/fluid/tests/unittests/test_uniform_random_op.py
  python/paddle/fluid/tests/unittests/testsuite.py
  python/paddle/fluid/tests/unittests/xpu/test_adam_op_xpu.py
  python/paddle/fluid/tests/unittests/xpu/test_fill_op_xpu.py
  python/paddle/fluid/tests/unittests/xpu/test_rmsprop_op_xpu.py
  python/paddle/fluid/tests/unittests/xpu/test_sgd_op_xpu.py
  python/paddle/fluid/tests/unittests/xpu/test_shape_op_xpu.py
  test/mkldnn/test_sum_mkldnn_op.py
Labels: contributor, status: proposed

#52231 support auto generate for bce_loss
  paddle/fluid/operators/bce_loss_op.cc
  paddle/phi/api/yaml/backward.yaml
  paddle/phi/api/yaml/legacy_backward.yaml
  paddle/phi/api/yaml/legacy_ops.yaml
  paddle/phi/api/yaml/op_compat.yaml
  paddle/phi/api/yaml/ops.yaml
  paddle/phi/ops/compat/bce_loss_sig.cc
Labels: contributor, status: proposed

#52474 rem useless mlu nup dockerfile
  tools/dockerfile/Dockerfile.mlu
  tools/dockerfile/Dockerfile.npu_aarch64
  tools/dockerfile/Dockerfile.npu_x86_64
  tools/dockerfile/Dockerfile.paddle-mlu-build
  tools/dockerfile/Dockerfile.paddle-npu-build
Labels: contributor, status: proposed

#52476 [Change]修改python unittest_py中scipy的版本信息
  python/unittest_py/requirements.txt
Labels: contributor, status: proposed

#52048 relocate debugger.py
  python/paddle/distributed/fleet/base/graphviz.py
  python/paddle/distributed/fleet/base/util_factory.py
  python/paddle/fluid/debugger.py
  python/paddle/fluid/tests/unittests/test_debugger.py
  python/paddle/incubate/distributed/fleet/utils.py
Labels: contributor, status: proposed

#51837 【Hackathon No.62】增加pool3d算子BF16及单测，lgamma, masked_select FP16/BF16算子单测
  paddle/phi/kernels/funcs/pooling.cu
  paddle/phi/kernels/funcs/select_impl.cu.h
  paddle/phi/kernels/gpu/lgamma_grad_kernel.cu
  paddle/phi/kernels/gpu/lgamma_kernel.cu
  paddle/phi/kernels/gpu/masked_select_grad_kernel.cu
  paddle/phi/kernels/gpu/masked_select_kernel.cu
  paddle/phi/kernels/gpu/pool_grad_kernel.cu
  paddle/phi/kernels/gpu/pool_kernel.cu
  paddle/phi/kernels/impl/lgamma_grad_kernel_impl.h
  python/paddle/fluid/tests/unittests/test_lgamma_op.py
  python/paddle/fluid/tests/unittests/test_masked_select_op.py
  python/paddle/fluid/tests/unittests/test_pool3d_api.py
  python/paddle/fluid/tests/unittests/test_pool3d_op.py
  python/paddle/nn/functional/pooling.py
  python/paddle/tensor/math.py
  python/paddle/tensor/search.py
Labels: contributor

#51995 Rewrite quant2_int8_nlp_comparison test
  test/quantization/CMakeLists.txt
  test/quantization/quant2_int8_nlp_comparison.py
Labels: Intel, int8, contributor

#52539 [CodeStyle][PLR0206] Cannot have defined parameters for properties
  pyproject.toml
  test/dygraph_to_static/simnet_dygraph_model.py
  test/dygraph_to_static/simnet_dygraph_model_v2.py
Labels: contributor, status: proposed

#52522 support auto generate static for uniform (uniform_random)
  paddle/fluid/operators/uniform_random_batch_size_like_op.cc
  paddle/fluid/operators/uniform_random_batch_size_like_op.cu
  paddle/fluid/operators/uniform_random_op.cc
  paddle/fluid/operators/unity_build_rule.cmake
  paddle/phi/api/yaml/op_compat.yaml
  paddle/phi/api/yaml/static_ops.yaml
Labels: contributor, status: proposed

#52529 support auto generate static for randint
  paddle/fluid/operators/randint_op.cc
  paddle/fluid/operators/unity_build_rule.cmake
  paddle/phi/api/yaml/op_compat.yaml
  paddle/phi/api/yaml/static_ops.yaml
Labels: contributor, status: proposed

#52524 support auto generate static for empty
  paddle/fluid/operators/empty_op.cc
  paddle/fluid/operators/unity_build_rule.cmake
  paddle/phi/api/yaml/op_compat.yaml
  paddle/phi/api/yaml/static_ops.yaml
  paddle/phi/ops/compat/empty_sig.cc
Labels: contributor, status: proposed

#51819 【PaddlePaddle Hackathon 4】No.63 add fp16 and bf16 for eye and frame
  paddle/phi/kernels/gpu/eye_kernel.cu
  paddle/phi/kernels/gpu/frame_grad_kernel.cu
  paddle/phi/kernels/gpu/frame_kernel.cu
  python/paddle/fluid/tests/unittests/test_eye_op.py
  python/paddle/fluid/tests/unittests/test_frame_op.py
Labels: contributor

#52462 [oneDNN]disable interpolate operators by default
  paddle/fluid/framework/ir/mkldnn/mkldnn_placement_pass.cc
  paddle/fluid/inference/api/paddle_pass_builder.cc
Labels: Intel, contributor

#52385 rem is_compiled_with_npu
  .flake8
  .pre-commit-config.yaml
  paddle/fluid/pybind/pybind.cc
  pyproject.toml
  python/paddle/__init__.py
  python/paddle/amp/auto_cast.py
  python/paddle/amp/grad_scaler.py
  python/paddle/device/__init__.py
  python/paddle/distributed/collective.py
  python/paddle/distributed/fleet/ascend_utils.py
  python/paddle/distributed/fleet/launch.py
  python/paddle/distributed/fleet/launch_utils.py
  python/paddle/distributed/fleet/layers/mpu/mp_ops.py
  python/paddle/distributed/fleet/meta_optimizers/common.py
  python/paddle/distributed/fleet/meta_optimizers/sharding/offload_helper.py
  python/paddle/distributed/fleet/meta_optimizers/sharding_optimizer.py
  python/paddle/distributed/fleet/meta_parallel/sharding/group_sharded_storage.py
  python/paddle/distributed/fleet/meta_parallel/sharding/group_sharded_utils.py
  python/paddle/distributed/fleet/utils/hybrid_parallel_inference.py
  python/paddle/distributed/launch/context/device.py
  python/paddle/distributed/parallel.py
  python/paddle/distributed/ps/utils/collective_transpiler.py
  python/paddle/distributed/transpiler/collective.py
  python/paddle/fluid/__init__.py
  python/paddle/fluid/device_worker.py
  python/paddle/fluid/dygraph/varbase_patch_methods.py
  python/paddle/fluid/executor.py
  python/paddle/fluid/framework.py
  python/paddle/fluid/optimizer.py
  python/paddle/fluid/tests/unittests/ascend_multi_process_collective.py
  python/paddle/fluid/tests/unittests/c_embedding_op_base.py
  python/paddle/fluid/tests/unittests/eager_op_test.py
  python/paddle/fluid/tests/unittests/test_cuda_max_memory_allocated.py
  python/paddle/fluid/tests/unittests/test_cuda_max_memory_reserved.py
  python/paddle/fluid/tests/unittests/test_cuda_memory_allocated.py
  python/paddle/fluid/tests/unittests/test_cuda_memory_reserved.py
  python/paddle/fluid/tests/unittests/test_device.py
  python/paddle/fluid/tests/unittests/test_dist_base.py
  python/paddle/fluid/tests/unittests/test_fleet_ascend_utils.py
  python/paddle/fluid/tests/unittests/test_npu_identity_op.py
  python/paddle/fluid/tests/unittests/test_var_base.py
  python/paddle/hapi/model.py
  python/paddle/nn/functional/conv.py
  python/paddle/static/__init__.py
  python/paddle/static/amp/amp_nn.py
  python/paddle/static/amp/decorator.py
  python/paddle/static/amp/fp16_lists.py
  python/paddle/static/io.py
  python/paddle/static/nn/common.py
  python/paddle/tensor/creation.py
  python/paddle/utils/install_check.py
  test/custom_kernel/custom_kernel_dot_c_setup.py
  test/custom_kernel/custom_kernel_dot_setup.py
  tools/get_quick_disable_lt.py
Labels: contributor

#52371 Rename conv2d transpose grad grad
  paddle/phi/api/yaml/legacy_backward.yaml
  paddle/phi/kernels/gpu/conv_transpose_grad_kernel.cu
  paddle/phi/kernels/gpudnn/conv_transpose_grad_kernel.cu
  paddle/phi/ops/compat/conv_transpose_sig.cc
Labels: contributor, status: proposed

#52534 support auto generate static for assign_value
  paddle/fluid/operators/assign_value_op.cc
  paddle/phi/api/yaml/op_compat.yaml
  paddle/phi/api/yaml/static_ops.yaml
Labels: contributor, status: proposed

#51743 Move fused_attention op to phi [迁移前向 GPU OpKernel]
  paddle/fluid/operators/fused/fused_attention_op.cu
  paddle/fluid/operators/fused/fused_attention_utils.h
  paddle/phi/kernels/funcs/blas/blaslt_impl.cu.h
  paddle/phi/kernels/funcs/layer_norm_impl.cu.h
  paddle/phi/kernels/funcs/reduce_function.h
  paddle/phi/kernels/fusion/gpu/attention_layer.norm.h
  paddle/phi/kernels/fusion/gpu/attn_gemm.h
  paddle/phi/kernels/fusion/gpu/fmha_ref.h
  paddle/phi/kernels/fusion/gpu/fused_dropout_act_bias.h
  paddle/phi/kernels/fusion/gpu/fused_dropout_common.h
  paddle/phi/kernels/fusion/gpu/fused_dropout_helper.h
  paddle/phi/kernels/fusion/gpu/fused_layernorm_residual_dropout_bias.h
  paddle/phi/kernels/fusion/gpu/fused_residual_dropout_bias.h
  paddle/phi/kernels/fusion/gpu/fused_softmax_mask_utils.h
  paddle/phi/ops/compat/fused_attention_sig.cc
  python/paddle/fluid/tests/unittests/test_fused_multi_transformer_op.py
Labels: contributor

#49444 Remove oneDNN-specific attributes from matmul
  paddle/fluid/framework/ir/fuse_gemm_epilogue_pass.cc
  paddle/fluid/framework/ir/fuse_gemm_epilogue_pass.h
  paddle/fluid/operators/compat/matmul.pbtxt
  paddle/fluid/operators/feed_forward_test.cu
  paddle/fluid/operators/matmul_op.cc
  paddle/fluid/operators/mkldnn/matmul_mkldnn_op.cc
  paddle/phi/api/yaml/op_compat.yaml
  paddle/phi/backends/onednn/matmul_utils.h
  paddle/phi/kernels/onednn/matmul_kernel.cc
  python/paddle/fluid/tests/unittests/ir/inference/test_flatten2_matmul_fuse_pass.py
  python/paddle/fluid/tests/unittests/ir/inference/test_map_matmul_to_mul_pass.py
  python/paddle/fluid/tests/unittests/ir/inference/test_matmul_scale_fuse_pass.py
  python/paddle/fluid/tests/unittests/ir/inference/test_mkldnn_scale_matmul_fuse_pass.py
  python/paddle/fluid/tests/unittests/ir/inference/test_multihead_matmul_fuse_pass_v3.py
  python/paddle/fluid/tests/unittests/ir/inference/test_multihead_matmul_roformer_fuse_pass.py
  python/paddle/fluid/tests/unittests/ir/inference/test_onednn_matmul_transpose_reshape_fuse_pass.py
  python/paddle/fluid/tests/unittests/ir/inference/test_onednn_reshape_transpose_matmul_fuse_pass.py
  python/paddle/fluid/tests/unittests/ir/inference/test_reshape2_matmul_fuse_pass.py
  python/paddle/fluid/tests/unittests/ir/inference/test_squared_mat_sub_fuse_pass.py
  python/paddle/fluid/tests/unittests/ir/inference/test_squeeze2_matmul_fuse_pass.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_matmul.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_multihead_matmul.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_multihead_matmul_roformer.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_flatten2_matmul_fuse_pass.py
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_squeeze2_matmul_fuse_pass.py
  test/mkldnn/test_matmul_mkldnn_op.py
  test/mkldnn/test_matmul_v2_mkldnn_op.py
Labels: Intel, contributor

#52562 [框架静态图算子自动生成]add argmax argmin to ops
  paddle/fluid/operators/arg_max_op.cc
  paddle/fluid/operators/arg_max_op_npu.cc
  paddle/fluid/operators/arg_min_max_op_base.h
  paddle/fluid/operators/arg_min_op.cc
  paddle/fluid/operators/arg_min_op_npu.cc
  paddle/phi/api/yaml/legacy_ops.yaml
  paddle/phi/api/yaml/op_compat.yaml
  paddle/phi/api/yaml/ops.yaml
  paddle/phi/ops/compat/arg_min_max_sig.cc
Labels: contributor, status: proposed

#52520 [Test MV] standalone_executor
  python/paddle/fluid/tests/unittests/CMakeLists.txt
  test/CMakeLists.txt
  test/standalone_executor/CMakeLists.txt
  test/standalone_executor/test_standalone_controlflow.py
  test/standalone_executor/test_standalone_cross_step_overlap.py
  test/standalone_executor/test_standalone_cuda_graph_multi_stream.py
  test/standalone_executor/test_standalone_custom_stream.py
  test/standalone_executor/test_standalone_executor.py
  test/standalone_executor/test_standalone_executor_aot_choose_kernel.py
  test/standalone_executor/test_standalone_multiply_write.py
  test/standalone_executor/test_standalone_op_priority.py
Labels: contributor, status: proposed

#52568 [CustomDevice] Add enable custom device C Api
  paddle/fluid/inference/capi_exp/pd_common.h
  paddle/fluid/inference/capi_exp/pd_config.cc
  paddle/fluid/inference/capi_exp/pd_config.h
  paddle/fluid/inference/capi_exp/pd_utils.cc
Labels: contributor, status: proposed

#52537 support auto generate static for tril_indices and triu_indices
  paddle/fluid/operators/tril_indices_op.cc
  paddle/fluid/operators/triu_indices_op.cc
  paddle/phi/api/yaml/static_ops.yaml
Labels: contributor, status: proposed

#52610 add autogen code support for warpctc op
  paddle/fluid/operators/CMakeLists.txt
  paddle/fluid/operators/warpctc_op.cc
  paddle/phi/api/yaml/backward.yaml
  paddle/phi/api/yaml/legacy_backward.yaml
  paddle/phi/api/yaml/legacy_ops.yaml
  paddle/phi/api/yaml/op_compat.yaml
  paddle/phi/api/yaml/ops.yaml
  paddle/phi/ops/compat/warpctc_sig.cc
Labels: contributor, status: proposed

#52589 [API] Expose capi in MacOS to enable GPU computing as custom device
  paddle/phi/capi/all.h
  paddle/phi/capi/capi.h
  paddle/phi/capi/include/c_data_type.h
  paddle/phi/capi/include/c_device_context.h
  paddle/phi/capi/include/c_int_array.h
  paddle/phi/capi/include/c_kernel_context.h
  paddle/phi/capi/include/c_kernel_factory.h
  paddle/phi/capi/include/c_kernel_registry.h
  paddle/phi/capi/include/c_place.h
  paddle/phi/capi/include/c_scalar.h
  paddle/phi/capi/include/c_tensor.h
  paddle/phi/capi/include/common.h
  paddle/phi/capi/include/data_type.h
  paddle/phi/capi/include/kernel_registry.h
  paddle/phi/capi/include/kernel_utils.h
  paddle/phi/capi/include/type_utils.h
  paddle/phi/capi/include/wrapper_base.h
Labels: contributor, status: proposed

#52388 【Hackathon4】No58. empty
  python/paddle/fluid/tests/unittests/test_empty_op.py
Labels: contributor, status: proposed

#52540 support auto generate static for truncated_gaussian_random
  paddle/fluid/operators/truncated_gaussian_random_op.cc
  paddle/fluid/operators/unity_build_rule.cmake
  paddle/phi/api/yaml/op_compat.yaml
  paddle/phi/api/yaml/static_ops.yaml
  paddle/phi/ops/compat/truncated_gaussian_random_sig.cc
Labels: contributor, status: proposed

#52612 昇腾和寒武纪相关代码退场 WITH_ASCEND_CL
  paddle/fluid/distributed/fleet_executor/test/CMakeLists.txt
  paddle/fluid/imperative/CMakeLists.txt
  paddle/fluid/inference/tests/api/CMakeLists.txt
  paddle/fluid/operators/CMakeLists.txt
  paddle/fluid/operators/amp/CMakeLists.txt
  paddle/fluid/operators/collective/CMakeLists.txt
  paddle/fluid/operators/elementwise/CMakeLists.txt
  paddle/fluid/operators/math/CMakeLists.txt
  paddle/fluid/operators/reduce_ops/CMakeLists.txt
  paddle/fluid/platform/CMakeLists.txt
  paddle/fluid/platform/dynload/CMakeLists.txt
  paddle/fluid/pybind/CMakeLists.txt
  python/CMakeLists.txt
  python/paddle/fluid/tests/unittests/CMakeLists.txt
  python/paddle/fluid/tests/unittests/collective/CMakeLists.txt
  python/paddle/fluid/tests/unittests/collective/fleet/CMakeLists.txt
  python/paddle/fluid/tests/unittests/distributed_passes/CMakeLists.txt
  test/asp/CMakeLists.txt
  tools/coverage/paddle_coverage.sh
  tools/coverage/paddle_coverage_new.sh
Labels: contributor, status: proposed

#52479 add autogen code support for matrix_nms.
  paddle/fluid/operators/detection/CMakeLists.txt
  paddle/fluid/operators/detection/matrix_nms_op.cc
  paddle/fluid/operators/generator/get_expected_kernel_func.cc
  paddle/fluid/operators/generator/get_expected_kernel_func.h
  paddle/phi/api/yaml/legacy_ops.yaml
  paddle/phi/api/yaml/op_compat.yaml
  paddle/phi/api/yaml/op_version.yaml
  paddle/phi/api/yaml/ops.yaml
  paddle/phi/ops/compat/matrix_nms_sig.cc
Labels: contributor, status: proposed

#52669 Remove WITH_ASCEND
  CMakeLists.txt
  cmake/configure.cmake
  cmake/external/protobuf.cmake
  paddle/fluid/distributed/fleet_executor/test/CMakeLists.txt
  paddle/fluid/inference/tests/api/CMakeLists.txt
  paddle/fluid/operators/CMakeLists.txt
  paddle/fluid/pybind/CMakeLists.txt
  python/paddle/fluid/tests/unittests/CMakeLists.txt
  python/paddle/fluid/tests/unittests/collective/CMakeLists.txt
  python/paddle/fluid/tests/unittests/collective/fleet/CMakeLists.txt
  python/paddle/fluid/tests/unittests/distributed_passes/CMakeLists.txt
  test/asp/CMakeLists.txt
Labels: contributor, status: proposed

#52675 delete paddle/fluid/operators/elementwise/*_npu.*
  paddle/fluid/operators/elementwise/elementwise_add_op_npu.cc
  paddle/fluid/operators/elementwise/elementwise_div_op_npu.cc
  paddle/fluid/operators/elementwise/elementwise_floordiv_op_npu.cc
  paddle/fluid/operators/elementwise/elementwise_max_op_npu.cc
  paddle/fluid/operators/elementwise/elementwise_min_op_npu.cc
  paddle/fluid/operators/elementwise/elementwise_mod_op_npu.cc
  paddle/fluid/operators/elementwise/elementwise_mul_op_npu.cc
  paddle/fluid/operators/elementwise/elementwise_npu.h
  paddle/fluid/operators/elementwise/elementwise_op_npu_test.cc
  paddle/fluid/operators/elementwise/elementwise_pow_op_npu.cc
  paddle/fluid/operators/elementwise/elementwise_sub_op_npu.cc
Labels: contributor, status: proposed

#52676 delete paddle/fluid/operators/controlflow/*_npu.*
  paddle/fluid/operators/controlflow/compare_op_npu.cc
  paddle/fluid/operators/controlflow/logical_op_npu.cc
Labels: contributor, status: proposed

#52677 delete paddle/fluid/operators/collective/*_npu.*
  paddle/fluid/operators/collective/c_allgather_op_npu.cc
  paddle/fluid/operators/collective/c_allgather_op_npu_test.cc
  paddle/fluid/operators/collective/c_allreduce_max_op_npu.cc
  paddle/fluid/operators/collective/c_allreduce_max_op_npu_test.cc
  paddle/fluid/operators/collective/c_allreduce_min_op_npu.cc
  paddle/fluid/operators/collective/c_allreduce_prod_op_npu.cc
  paddle/fluid/operators/collective/c_allreduce_sum_op_npu.cc
  paddle/fluid/operators/collective/c_allreduce_sum_op_npu_test.cc
  paddle/fluid/operators/collective/c_broadcast_op_npu.cc
  paddle/fluid/operators/collective/c_broadcast_op_npu_test.cc
  paddle/fluid/operators/collective/c_embedding_op_npu.cc
  paddle/fluid/operators/collective/c_identity_op_npu.cc
  paddle/fluid/operators/collective/c_reduce_max_op_npu.cc
  paddle/fluid/operators/collective/c_reduce_min_op_npu.cc
  paddle/fluid/operators/collective/c_reduce_prod_op_npu.cc
  paddle/fluid/operators/collective/c_reduce_sum_op_npu.cc
  paddle/fluid/operators/collective/c_reduce_sum_op_npu_test.cc
  paddle/fluid/operators/collective/c_reducescatter_op_npu.cc
  paddle/fluid/operators/collective/c_reducescatter_op_npu_test.cc
  paddle/fluid/operators/collective/c_sync_calc_stream_op_npu_test.cc
  paddle/fluid/operators/collective/c_sync_comm_stream_op_npu_test.cc
  paddle/fluid/operators/collective/checknumeric_npu_test.cc
  paddle/fluid/operators/collective/mp_allreduce_sum_op_npu.cc
  paddle/fluid/operators/collective/partial_allgather_op_npu.cc
  paddle/fluid/operators/collective/partial_recv_op_npu.cc
  paddle/fluid/operators/collective/partial_send_op_npu.cc
  paddle/fluid/operators/collective/recv_v2_op_npu.cc
  paddle/fluid/operators/collective/recv_v2_op_npu_test.cc
  paddle/fluid/operators/collective/send_v2_op_npu.cc
  paddle/fluid/operators/collective/send_v2_op_npu_test.cc
Labels: contributor, status: proposed

#52674 delete paddle/fluid/operators/math,metrics,optimizers,reduce_ops/*_npu.*
  paddle/fluid/operators/math/beam_search_npu.cc
  paddle/fluid/operators/metrics/accuracy_op_npu.cc
  paddle/fluid/operators/optimizers/adam_op_npu.cc
  paddle/fluid/operators/optimizers/merged_momentum_op_npu.cc
  paddle/fluid/operators/optimizers/momentum_op_npu.cc
  paddle/fluid/operators/optimizers/rmsprop_op_npu.cc
  paddle/fluid/operators/optimizers/sgd_op_npu.cc
  paddle/fluid/operators/reduce_ops/reduce_any_op_npu.cc
  paddle/fluid/operators/reduce_ops/reduce_any_op_npu_test.cc
  paddle/fluid/operators/reduce_ops/reduce_max_op_npu.cc
  paddle/fluid/operators/reduce_ops/reduce_mean_op_npu.cc
  paddle/fluid/operators/reduce_ops/reduce_min_op_npu.cc
  paddle/fluid/operators/reduce_ops/reduce_prod_op_npu.cc
  paddle/fluid/operators/reduce_ops/reduce_sum_op_npu.cc
  paddle/fluid/operators/sequence_ops/sequence_mask_op_npu.cc
Labels: contributor, status: proposed

#52679 change cmake/operators.cmake & remove *_npu*
  cmake/operators.cmake
Labels: contributor, status: proposed

#52560 add autogen code support for affine_grid op
  paddle/fluid/operators/affine_grid_op.cc
  paddle/phi/api/yaml/backward.yaml
  paddle/phi/api/yaml/legacy_backward.yaml
  paddle/phi/api/yaml/legacy_ops.yaml
  paddle/phi/api/yaml/op_compat.yaml
  paddle/phi/api/yaml/op_version.yaml
  paddle/phi/api/yaml/ops.yaml
  paddle/phi/infermeta/backward.cc
  paddle/phi/infermeta/unary.cc
  paddle/phi/ops/compat/affine_grid_sig.cc
Labels: contributor, status: proposed

#52620 [Custom Device] Enable linkage to custom device plugin's dynamic library on MacOS.
  paddle/fluid/distributed/collective/custom_ccl_tools.h
  paddle/phi/backends/device_ext.h
  paddle/phi/backends/device_manager.cc
Labels: contributor, status: proposed

#52509 【PaddlePaddle Hackathon 4 No.44】为 Paddle 优化 logsumexp op 在 GPU 上的计算性能
  paddle/phi/kernels/gpu/logsumexp_kernel.cu
Labels: contributor, status: proposed

#52687 support auto generate for eigvalsh
  paddle/fluid/operators/eigvalsh_op.cc
  paddle/phi/api/yaml/backward.yaml
  paddle/phi/api/yaml/legacy_backward.yaml
  paddle/phi/api/yaml/legacy_ops.yaml
  paddle/phi/api/yaml/op_compat.yaml
  paddle/phi/api/yaml/ops.yaml
  paddle/phi/kernels/cpu/eigvalsh_grad_kernel.cc
  paddle/phi/kernels/gpu/eigvalsh_grad_kernel.cu
  paddle/phi/kernels/gpu/eigvalsh_kernel.cu
  paddle/phi/ops/compat/eigvalsh_sig.cc
Labels: contributor, status: proposed

#52482 【PaddlePaddle Hackathon 4 No.36】为 Paddle 优化 tile op 在 GPU 上的计算性能
  paddle/phi/kernels/gpu/tile_kernel.cu
Labels: contributor, status: not progressed

#52672 remove infrt V1.1
  .gitignore
  CMakeLists.txt
  cmake/external/llvm.cmake
  cmake/infrt_lib.cmake
  cmake/third_party.cmake
  paddle/phi/README.md
  tools/get_pr_ut.py
Labels: contributor, status: proposed

#52682 add autogen code support for logcumsumexp op
  paddle/fluid/operators/cum_op.cc
  paddle/phi/api/yaml/backward.yaml
  paddle/phi/api/yaml/legacy_backward.yaml
  paddle/phi/api/yaml/legacy_ops.yaml
  paddle/phi/api/yaml/op_compat.yaml
  paddle/phi/api/yaml/ops.yaml
  paddle/phi/ops/compat/logcumsumexp_sig.cc
Labels: contributor, status: proposed

#50318 Fix gcc12 check cuda version
  cmake/experiments/cuda_module_loading_lazy.cmake
Labels: contributor, status: proposed

#51300 【Hackathon4 No58】fix exponential and pad
  paddle/phi/kernels/cpu/exponential_kernel.cc
  paddle/phi/kernels/exponential_kernel.h
  paddle/phi/kernels/gpu/exponential_kernel.cu
  paddle/phi/kernels/gpu/pad_grad_kernel.cu
  paddle/phi/kernels/gpu/pad_kernel.cu
  paddle/phi/kernels/pad_grad_kernel.h
  paddle/phi/kernels/pad_kernel.h
  python/paddle/fluid/tests/unittests/test_exponential_op.py
  python/paddle/fluid/tests/unittests/test_pad_op.py
  python/paddle/tensor/random.py
Labels: contributor, status: proposed

#52690 Autogen code bilinear_tensor_product
  paddle/fluid/operators/bilinear_tensor_product_op.cc
  paddle/phi/api/yaml/backward.yaml
  paddle/phi/api/yaml/legacy_backward.yaml
  paddle/phi/api/yaml/legacy_ops.yaml
  paddle/phi/api/yaml/op_compat.yaml
  paddle/phi/api/yaml/ops.yaml
  paddle/phi/ops/compat/bilinear_tensor_product_sig.cc
Labels: contributor, status: proposed

#51117 【Hackathon No.16】add PoissonNLLLoss API
  python/paddle/fluid/tests/unittests/test_poisson_nll_loss.py
  python/paddle/nn/__init__.py
  python/paddle/nn/functional/__init__.py
  python/paddle/nn/functional/loss.py
  python/paddle/nn/layer/__init__.py
  python/paddle/nn/layer/loss.py
  python/paddle/tensor/math.py
  python/paddle/tensor/ops.py
Labels: contributor, API

#52673 delete paddle/fluid/operators/amp/*_npu.*
  .gitignore
  paddle/fluid/operators/amp/alloc_float_status_op_npu.cc
  paddle/fluid/operators/amp/check_finite_and_unscale_op_npu.cc
  paddle/fluid/operators/amp/check_finite_and_unscale_op_npu_test.cc
  paddle/fluid/operators/amp/clear_float_status_op_npu.cc
  paddle/fluid/operators/amp/get_float_status_op_npu.cc
  paddle/fluid/operators/amp/update_loss_scaling_op_npu.cc
Labels: contributor, status: proposed

#52380 【Hackathon No57】 add fp16 & bf16 for flip, fp16 for gaussian
  paddle/phi/kernels/gpu/flip_kernel.cu
  python/paddle/fluid/tests/unittests/test_flip.py
  python/paddle/fluid/tests/unittests/test_gaussian_random_op.py
Labels: contributor, status: proposed

#52719 remove paddle/infrt/
  .gitignore
  paddle/infrt/tests/models/efficientnet-b4/net/utils.py
Labels: contributor, status: proposed

#52611 support auto generate for op momentum optimizer
  paddle/fluid/operators/optimizers/dgc_momentum_op.cc
  paddle/fluid/operators/optimizers/dgc_momentum_op.h
  paddle/fluid/operators/optimizers/momentum_op.cc
  paddle/fluid/operators/optimizers/momentum_op.h
  paddle/fluid/operators/optimizers/unity_build_rule.cmake
  paddle/phi/api/yaml/legacy_ops.yaml
  paddle/phi/api/yaml/op_compat.yaml
  paddle/phi/api/yaml/op_version.yaml
  paddle/phi/api/yaml/ops.yaml
  paddle/phi/ops/compat/momentum_sig.cc
Labels: contributor, status: proposed

#52695 support auto generate for op adagrad optimizer
  paddle/fluid/operators/optimizers/adagrad_op.cc
  paddle/fluid/operators/optimizers/unity_build_rule.cmake
  paddle/phi/api/yaml/legacy_ops.yaml
  paddle/phi/api/yaml/op_compat.yaml
  paddle/phi/api/yaml/ops.yaml
  paddle/phi/ops/compat/adagrad_sig.cc
Labels: contributor, status: proposed

#52701 add autogen code support for reverse op
  paddle/fluid/operators/reverse_op.cc
  paddle/phi/api/yaml/backward.yaml
  paddle/phi/api/yaml/legacy_backward.yaml
  paddle/phi/api/yaml/legacy_ops.yaml
  paddle/phi/api/yaml/op_compat.yaml
  paddle/phi/api/yaml/ops.yaml
Labels: contributor, status: proposed

#52718 Delete the keyword WITH_ASCEND_INT64 in configure.cmake and CMakeList
  CMakeLists.txt
  cmake/configure.cmake
Labels: contributor, status: proposed

#51362 Add output defs for eigh kernel
  paddle/phi/infermeta/unary.cc
  paddle/phi/kernels/cpu/eigh_kernel.cc
  paddle/phi/kernels/gpu/eigh_kernel.cu
Labels: contributor, status: not progressed

#52512 support auto generate for flatten (flatten_contiguous_range)
  paddle/fluid/operators/flatten_op.cc
  paddle/phi/api/yaml/backward.yaml
  paddle/phi/api/yaml/legacy_backward.yaml
  paddle/phi/api/yaml/legacy_ops.yaml
  paddle/phi/api/yaml/op_compat.yaml
  paddle/phi/api/yaml/ops.yaml
  paddle/phi/ops/compat/flatten_sig.cc
Labels: contributor, status: proposed

#52708 support auto generate for op merged_momentum optimizer
  paddle/fluid/operators/generator/type_mapping.py
  paddle/fluid/operators/optimizers/merged_momentum_op.cc
  paddle/phi/api/yaml/legacy_ops.yaml
  paddle/phi/api/yaml/op_compat.yaml
  paddle/phi/api/yaml/ops.yaml
  paddle/phi/ops/compat/merged_momentum_sig.cc
Labels: contributor, status: proposed

#52668 【Hackathon4 No58】empty_like fp16&bf16 API test
  python/paddle/fluid/tests/unittests/test_empty_like_op.py
  python/paddle/tensor/attribute.py
  python/paddle/tensor/creation.py
Labels: contributor, status: proposed

#50999 [AMP OP&Test]stack & unstack ops fp16 bf16 support
  python/paddle/fluid/tests/unittests/test_stack_op.py
  python/paddle/fluid/tests/unittests/test_unstack_op.py
Labels: contributor, status: proposed

#52748 delete remote_prefetch
  paddle/fluid/operators/hierarchical_sigmoid_op.cc
  paddle/phi/api/yaml/legacy_backward.yaml
  paddle/phi/api/yaml/legacy_ops.yaml
  paddle/phi/infermeta/multiary.cc
  paddle/phi/infermeta/multiary.h
  paddle/phi/kernels/cpu/hsigmoid_loss_grad.h
  paddle/phi/kernels/cpu/hsigmoid_loss_grad_kernel.cc
  paddle/phi/kernels/cpu/hsigmoid_loss_kernel.cc
  paddle/phi/kernels/hsigmoid_loss_grad_kernel.h
  paddle/phi/kernels/hsigmoid_loss_kernel.h
  paddle/phi/kernels/selected_rows/hsigmoid_loss_grad_kernel.cc
  paddle/phi/kernels/selected_rows/hsigmoid_loss_grad_kernel.h
  paddle/phi/ops/compat/hierarchical_sigmoid_sig.cc
  python/paddle/fluid/tests/unittests/test_hsigmoid_op.py
  python/paddle/nn/functional/loss.py
Labels: contributor, status: proposed

#52531 support auto generate static for randperm
  paddle/fluid/operators/randperm_op.cc
  paddle/fluid/operators/unity_build_rule.cmake
  paddle/phi/api/yaml/op_compat.yaml
  paddle/phi/api/yaml/static_ops.yaml
  paddle/phi/ops/compat/randperm_sig.cc
Labels: contributor, status: proposed

#52704 support auto generate for op average_accumulates
  paddle/fluid/operators/average_accumulates_op.cc
  paddle/fluid/operators/unity_build_rule.cmake
  paddle/phi/api/yaml/legacy_ops.yaml
  paddle/phi/api/yaml/ops.yaml
  paddle/phi/ops/compat/average_accumulates_sig.cc
Labels: contributor, status: proposed

#52244 【Hackathon 4th No.13】为 Paddle 新增 Bernoulli API
  python/paddle/distribution/__init__.py
  python/paddle/distribution/bernoulli.py
  python/paddle/distribution/kl.py
  python/paddle/fluid/tests/unittests/distribution/test_distribution_bernoulli.py
  python/paddle/fluid/tests/unittests/distribution/test_distribution_bernoulli_static.py
Labels: contributor, API

#52723 add a new python script topology.py and its corresponding unittest fo…
  python/paddle/distributed/auto_parallel/topology.py
  python/paddle/fluid/tests/unittests/auto_parallel/test_topology.py
Labels: contributor, status: proposed

#52798 remove *hccl*.cc
  paddle/fluid/operators/collective/CMakeLists.txt
  paddle/fluid/operators/collective/c_comm_init_hccl_op.cc
  paddle/fluid/operators/collective/c_gen_hccl_id_op.cc
  paddle/fluid/operators/collective/gen_hccl_id_op.cc
  paddle/fluid/operators/collective/gen_hccl_id_op_helper.cc
  paddle/fluid/operators/collective/gen_hccl_id_op_helper.h
  python/paddle/distributed/fleet/meta_optimizers/common.py
  python/paddle/fluid/framework.py
  python/paddle/fluid/tests/unittests/ir/inference/program_config.py
Labels: contributor, status: proposed

#52780 fix CMakeLists.txt error of incorrect default value
  CMakeLists.txt
Labels: contributor, status: proposed

#52662 add autogen code support for squared_l2_norm_op
  paddle/fluid/operators/squared_l2_norm_op.cc
  paddle/phi/api/yaml/backward.yaml
  paddle/phi/api/yaml/legacy_backward.yaml
  paddle/phi/api/yaml/legacy_ops.yaml
  paddle/phi/api/yaml/op_compat.yaml
  paddle/phi/api/yaml/ops.yaml
  paddle/phi/ops/compat/squared_l2_norm_sig.cc
Labels: contributor, status: proposed

#52782 [phi] mv sequence_pool to phi - Step 1 : sequence_pooling_test
  paddle/fluid/operators/math/CMakeLists.txt
  test/cpp/phi/kernels/CMakeLists.txt
  test/cpp/phi/kernels/sequence_pooling_test.cc
Labels: contributor, status: proposed

#52702 support auto generate for op adamax optimizer
  paddle/fluid/operators/optimizers/adamax_op.cc
  paddle/fluid/operators/optimizers/unity_build_rule.cmake
  paddle/phi/api/yaml/legacy_ops.yaml
  paddle/phi/api/yaml/op_compat.yaml
  paddle/phi/api/yaml/ops.yaml
  paddle/phi/ops/compat/adamax_sig.cc
Labels: contributor, status: proposed

#52811 rem cncl in ut & build sh
  paddle/scripts/paddle_build.sh
  python/paddle/fluid/tests/unittests/test_dist_base.py
  test/cpp/imperative/CMakeLists.txt
  test/cpp/imperative/test_group.cc
Labels: contributor, status: proposed

#52745 Rename bilinear_tensor op
  paddle/phi/api/yaml/backward.yaml
  paddle/phi/api/yaml/op_compat.yaml
  paddle/phi/api/yaml/ops.yaml
  paddle/phi/infermeta/backward.cc
  paddle/phi/infermeta/backward.h
  paddle/phi/kernels/cpu/slice_grad_kernel.cc
  paddle/phi/kernels/gpu/slice_grad_kernel.cu.cc
  paddle/phi/kernels/impl/slice_grad_kernel_impl.h
  paddle/phi/kernels/onednn/slice_grad_kernel.cc
  paddle/phi/kernels/slice_grad_kernel.h
  paddle/phi/kernels/xpu/slice_grad_kernel.cc
  python/paddle/nn/functional/common.py
Labels: contributor, status: proposed

#52714 Support static graph code-gen for yolo_box
  paddle/fluid/operators/detection/CMakeLists.txt
  paddle/fluid/operators/detection/yolo_box_op.cc
  paddle/phi/api/yaml/legacy_ops.yaml
  paddle/phi/api/yaml/op_compat.yaml
  paddle/phi/api/yaml/op_version.yaml
  paddle/phi/api/yaml/ops.yaml
  paddle/phi/ops/compat/yolo_box_sig.cc
Labels: contributor, status: proposed

#52797 add autogen code support for expand_as op
  paddle/fluid/operators/expand_as_v2_op.cc
  paddle/phi/api/yaml/backward.yaml
  paddle/phi/api/yaml/legacy_backward.yaml
  paddle/phi/api/yaml/legacy_ops.yaml
  paddle/phi/api/yaml/op_compat.yaml
  paddle/phi/api/yaml/op_version.yaml
  paddle/phi/api/yaml/ops.yaml
  paddle/phi/ops/compat/expand_as_sig.cc
Labels: contributor, status: proposed

#52759 rename PD_REGISTER_GENERAL_KERNEL
  cmake/operators.cmake
  cmake/phi.cmake
  paddle/fluid/operators/controlflow/feed_op.cc
  paddle/phi/core/kernel_registry.h
  paddle/phi/kernels/assign_kernel.cc
  paddle/phi/kernels/memcpy_kernel.cc
  paddle/phi/kernels/reshape_grad_kernel.cc
  paddle/phi/kernels/selected_rows/assign_kernel.cc
  paddle/phi/kernels/share_buffer_kernel.cc
  paddle/phi/kernels/strings/cpu/strings_copy_kernel.cc
  paddle/phi/kernels/strings/cpu/strings_lower_upper_kernel.cc
  paddle/phi/kernels/strings/gpu/strings_copy_kernel.cu
  paddle/phi/kernels/strings/gpu/strings_lower_upper_kernel.cu
  paddle/phi/kernels/strings/strings_empty_kernel.cc
  paddle/phi/kernels/transfer_layout_kernel.cc
Labels: contributor, status: proposed

#52686 Support static graph code-gen for temporal_shift
  paddle/fluid/operators/temporal_shift_op.cc
  paddle/phi/api/yaml/backward.yaml
  paddle/phi/api/yaml/legacy_backward.yaml
  paddle/phi/api/yaml/legacy_ops.yaml
  paddle/phi/api/yaml/op_compat.yaml
  paddle/phi/api/yaml/ops.yaml
  paddle/phi/ops/compat/temporal_shift_sig.cc
  python/paddle/nn/functional/extension.py
Labels: contributor, status: proposed

#52709 support auto generate for op rmsprop optimizer
  paddle/fluid/operators/optimizers/rmsprop_op.cc
  paddle/fluid/operators/optimizers/unity_build_rule.cmake
  paddle/phi/api/yaml/legacy_ops.yaml
  paddle/phi/api/yaml/op_compat.yaml
  paddle/phi/api/yaml/ops.yaml
  paddle/phi/ops/compat/rmsprop_sig.cc
Labels: contributor, status: proposed

#50843 Add GaussianNLLLoss API.
  python/paddle/fluid/tests/unittests/test_gaussian_nll_loss.py
  python/paddle/nn/__init__.py
  python/paddle/nn/functional/__init__.py
  python/paddle/nn/functional/loss.py
  python/paddle/nn/layer/__init__.py
  python/paddle/nn/layer/loss.py
Labels: contributor, API

#52582 【Hackathon No.55】pixel_shuffle, pixel_unshuffle算子FP16/BF16单测完善
  paddle/phi/kernels/gpu/pixel_unshuffle_grad_kernel.cu
  paddle/phi/kernels/gpu/pixel_unshuffle_kernel.cu
  python/paddle/fluid/tests/unittests/test_pixel_shuffle_op.py
  python/paddle/fluid/tests/unittests/test_pixel_unshuffle.py
  python/paddle/nn/functional/vision.py
Labels: contributor, status: proposed

#52426 【Hackathon No57】add_fp16_bf16_for_dot & bf16_for_cross
  paddle/phi/kernels/gpu/cross_grad_kernel.cu
  paddle/phi/kernels/gpu/cross_kernel.cu
  paddle/phi/kernels/gpu/dot_grad_kernel.cu
  paddle/phi/kernels/gpu/dot_kernel.cu
  python/paddle/fluid/tests/unittests/test_cross_op.py
  python/paddle/fluid/tests/unittests/test_dot_op.py
Labels: contributor, status: proposed

#52830 remove code with PADDLE_WITH_ASCEND
  cmake/configure.cmake
  cmake/external/ascend.cmake
  paddle/CMakeLists.txt
Labels: contributor, status: proposed

#52434 rem cncl
  CMakeLists.txt
  paddle/fluid/framework/var_type_traits.h
  paddle/fluid/imperative/CMakeLists.txt
  paddle/fluid/imperative/cncl_context.cc
  paddle/fluid/imperative/cncl_context.h
  paddle/fluid/imperative/reducer.cc
  paddle/fluid/imperative/reducer.h
  paddle/fluid/operators/collective/CMakeLists.txt
  paddle/fluid/operators/collective/c_allreduce_op.h
  paddle/fluid/operators/collective/c_comm_init_op.cc
  paddle/fluid/operators/collective/c_gen_cncl_id_op.cc
  paddle/fluid/operators/collective/c_reduce_op.h
  paddle/fluid/operators/collective/c_sync_calc_stream_op.h
  paddle/fluid/operators/collective/c_sync_comm_stream_op.h
  paddle/fluid/platform/CMakeLists.txt
  paddle/fluid/platform/collective_helper.h
  paddle/fluid/platform/gen_comm_id_helper.cc
  paddle/fluid/platform/gen_comm_id_helper.h
  paddle/fluid/pybind/CMakeLists.txt
  paddle/fluid/pybind/imperative.cc
  python/paddle/fluid/framework.py
Labels: contributor, status: proposed

#51909 Move fused_attention op to phi [迁移反向 GPU OpKernel]
  paddle/fluid/operators/fused/fused_attention_op.cu
  paddle/phi/ops/compat/fused_attention_sig.cc
Labels: contributor

#52185 [Zero-Dim] support 0-D tensor for reduce/reshape/stack/prelu/expand_v2/gaussion onednn kernels
  paddle/fluid/operators/mkldnn/reshape_mkldnn_op.cc
  paddle/phi/backends/onednn/onednn_reuse.h
  paddle/phi/kernels/onednn/expand_grad_kernel.cc
  paddle/phi/kernels/onednn/gaussian_kernel.cc
  paddle/phi/kernels/onednn/reduce_kernel_impl.h
  paddle/phi/kernels/onednn/reshape_kernel.cc
  test/mkldnn/test_expand_v2_mkldnn_op.py
  test/mkldnn/test_gaussian_random_mkldnn_op.py
  test/mkldnn/test_prelu_mkldnn_op.py
  test/mkldnn/test_reduce_mkldnn_op.py
  test/mkldnn/test_reshape_mkldnn_op.py
  test/mkldnn/test_stack_mkldnn_op.py
Labels: Intel, contributor

#52630 【Hackathon No.59】 angle, bmm算子FP16/BF16单测完善
  paddle/phi/kernels/gpu/angle_grad_kernel.cu
  paddle/phi/kernels/gpu/angle_kernel.cu
  paddle/phi/kernels/gpu/bmm_grad_kernel.cu
  paddle/phi/kernels/gpu/bmm_kernel.cu
  python/paddle/fluid/tests/unittests/test_angle_op.py
  python/paddle/fluid/tests/unittests/test_bmm_op.py
  python/paddle/tensor/math.py
Labels: contributor, status: proposed

#52604 【Hackathon No.62】digamma, dirichlet算子FP16/BF16单测完善
  paddle/phi/kernels/gpu/digamma_grad_kernel.cu
  paddle/phi/kernels/gpu/digamma_kernel.cu
  paddle/phi/kernels/gpu/dirichlet_kernel.cu
  paddle/phi/kernels/impl/digamma_grad_kernel_impl.h
  paddle/phi/kernels/impl/digamma_kernel_impl.h
  paddle/phi/kernels/impl/dirichlet_kernel_impl.h
  python/paddle/distribution/dirichlet.py
  python/paddle/fluid/tests/unittests/distribution/test_dirichlet_op.py
  python/paddle/fluid/tests/unittests/test_digamma_op.py
  python/paddle/tensor/math.py
Labels: contributor, status: proposed

#51615 【Hackathon4 No58】kthvalue
  paddle/phi/kernels/gpu/kthvalue_grad_kernel.cu
  paddle/phi/kernels/gpu/kthvalue_kernel.cu
  python/paddle/fluid/tests/unittests/test_kthvalue_op.py
Labels: contributor, status: proposed

#51275 【Hackathon4 No58】logcumsum logsum
  paddle/phi/kernels/gpu/cum_kernel.cu
  paddle/phi/kernels/gpu/logcumsumexp_grad_kernel.cu
  paddle/phi/kernels/gpu/logsumexp_grad_kernel.cu
  paddle/phi/kernels/gpu/logsumexp_kernel.cu
  paddle/phi/kernels/logcumsumexp_grad_kernel.h
  paddle/phi/kernels/logsumexp_grad_kernel.h
  paddle/phi/kernels/logsumexp_kernel.h
  python/paddle/fluid/tests/unittests/test_logcumsumexp_op.py
  python/paddle/fluid/tests/unittests/test_logsumexp.py
  python/paddle/tensor/math.py
Labels: contributor, status: proposed

#52937 Fix typos, test=document_fix
  paddle/phi/common/data_type.h
  paddle/phi/common/thread_data_registry.h
  paddle/phi/common/transform.h
Labels: contributor, status: proposed

#52941 Add output defs for some kernelsPhi register
  paddle/fluid/framework/new_executor/interpreter/static_build.cc
  paddle/fluid/operators/sync_batch_norm_op.cu
  paddle/phi/infermeta/multiary.cc
  paddle/phi/infermeta/unary.cc
  paddle/phi/kernels/cpu/amp_kernel.cc
  paddle/phi/kernels/cpu/eig_grad_kernel.cc
  paddle/phi/kernels/cpu/eig_kernel.cc
  paddle/phi/kernels/cpu/eigh_kernel.cc
  paddle/phi/kernels/cpu/unique_consecutive_kernel.cc
  paddle/phi/kernels/cpu/unique_kernel.cc
  paddle/phi/kernels/gpu/adagrad_kernel.cu
  paddle/phi/kernels/gpu/amp_kernel.cu
  paddle/phi/kernels/gpu/eigh_kernel.cu
  paddle/phi/kernels/gpu/lamb_kernel.cu
  paddle/phi/kernels/gpu/unique_consecutive_kernel.cu
  paddle/phi/kernels/gpu/unique_kernel.cu
  paddle/phi/kernels/xpu/lamb_kernel.cc
  python/paddle/fluid/tests/unittests/CMakeLists.txt
  tools/check_file_diff_approvals.sh
  tools/windows/run_unittests.sh
Labels: contributor

#52934 remove hccl in .py files
  python/paddle/distributed/collective.py
  python/paddle/distributed/fleet/launch.py
  python/paddle/distributed/fleet/launch_utils.py
  python/paddle/distributed/fleet/meta_optimizers/ascend/__init__.py
  python/paddle/distributed/fleet/meta_optimizers/ascend/ascend_optimizer.py
  python/paddle/distributed/fleet/meta_optimizers/ascend/ascend_parser.py
  python/paddle/distributed/fleet/meta_optimizers/sharding_optimizer.py
  python/paddle/fluid/tests/unittests/ascend_group.py
  python/paddle/fluid/tests/unittests/hccl_tools.py
  python/paddle/fluid/tests/unittests/test_dist_base.py
  python/setup.py.in
  setup.py
Labels: contributor, status: proposed

#52942 remove hccl in some .cc files
  paddle/fluid/imperative/hccl_context.cc
  paddle/fluid/imperative/hccl_context.h
  paddle/fluid/pybind/imperative.cc
  paddle/phi/backends/dynload/dynamic_loader.cc
  python/paddle/fluid/tests/unittests/test_ascend_group.sh
Labels: contributor, status: proposed

#52863 rename_SliceKernel
  paddle/phi/kernels/accuracy_kernel.h
  paddle/phi/kernels/cpu/accuracy_kernel.cc
  paddle/phi/kernels/cpu/slice_kernel.cc
  paddle/phi/kernels/gpu/accuracy_kernel.cu
  paddle/phi/kernels/gpu/qr_kernel.cu
  paddle/phi/kernels/gpu/slice_kernel.cu.cc
  paddle/phi/kernels/impl/qr_grad_kernel_impl.h
  paddle/phi/kernels/impl/slice_kernel_impl.h
  paddle/phi/kernels/impl/svd_grad_kernel_impl.h
  paddle/phi/kernels/onednn/slice_kernel.cc
  paddle/phi/kernels/slice_kernel.h
  paddle/phi/kernels/xpu/slice_kernel.cc
Labels: contributor, status: proposed

#52939 Kim/rem cncl in py
  python/paddle/distributed/fleet/launch.py
  python/paddle/distributed/fleet/launch_utils.py
  python/paddle/distributed/parallel.py
  python/paddle/distributed/spawn.py
  python/paddle/distributed/utils/launch_utils.py
Labels: contributor, status: proposed

#52700 【Hackathon No.32】为 Paddle 优化 expand_as 前向&反向 op 在 GPU 上的计算性能
  paddle/phi/kernels/gpu/expand_as_grad_kernel.cu
  paddle/phi/kernels/gpu/expand_as_kernel.cu
Labels: contributor, status: proposed

#50930 【PaddlePaddle Hackathon 4 No.49】：为 Paddle bce_loss 支持 float16 数据类型
  paddle/phi/kernels/gpu/bce_loss_grad_kernel.cu
  paddle/phi/kernels/gpu/bce_loss_kernel.cu
  python/paddle/fluid/tests/unittests/test_bce_loss.py
  python/paddle/nn/functional/loss.py
  python/paddle/nn/layer/loss.py
Labels: contributor, status: proposed

#52955 add autogen code support for uniform_inplace
  paddle/fluid/operators/uniform_random_inplace_op.cc
  paddle/phi/api/yaml/backward.yaml
  paddle/phi/api/yaml/legacy_backward.yaml
  paddle/phi/api/yaml/legacy_ops.yaml
  paddle/phi/api/yaml/op_compat.yaml
  paddle/phi/api/yaml/ops.yaml
  paddle/phi/ops/compat/uniform_random_inplace_sig.cc
Labels: contributor, status: proposed

#52967 [Test Mv] remove rnn
  python/paddle/fluid/tests/unittests/CMakeLists.txt
  python/paddle/fluid/tests/unittests/test_gru_rnn_op.py
  python/paddle/fluid/tests/unittests/test_rnn_cell_api.py
  python/paddle/fluid/tests/unittests/test_rnn_op.py
  python/paddle/fluid/tests/unittests/test_simple_rnn_op.py
  test/CMakeLists.txt
  test/rnn/CMakeLists.txt
  test/rnn/__init__.py
  test/rnn/convert.py
  test/rnn/rnn_numpy.py
  test/rnn/test_rnn_api.py
  test/rnn/test_rnn_cells.py
  test/rnn/test_rnn_cells_static.py
  test/rnn/test_rnn_cudnn_params_packing.py
  test/rnn/test_rnn_nets.py
  test/rnn/test_rnn_nets_static.py
  test/rnn/test_wrappers.py
Labels: contributor, status: proposed

#52659 Support static graph code-gen for matrix_rank
  paddle/fluid/operators/matrix_rank_op.cc
  paddle/phi/api/yaml/op_compat.yaml
  paddle/phi/api/yaml/static_ops.yaml
  paddle/phi/infermeta/binary.cc
  paddle/phi/infermeta/binary.h
  paddle/phi/ops/compat/matrix_rank_sig.cc
Labels: contributor, status: proposed

#52749 reorder_prior_box
  paddle/phi/api/yaml/legacy_ops.yaml
  paddle/phi/infermeta/binary.cc
  paddle/phi/infermeta/binary.h
  paddle/phi/kernels/cpu/prior_box_kernel.cc
  paddle/phi/kernels/gpu/prior_box_kernel.cu
  paddle/phi/kernels/prior_box_kernel.h
  paddle/phi/kernels/xpu/prior_box_kernel.cc
  paddle/phi/ops/compat/prior_box_sig.cc
  python/paddle/fluid/tests/unittests/test_prior_box_op.py
  python/paddle/vision/ops.py
Labels: contributor, status: proposed

#52799 add autogen code support for rnn op
  paddle/fluid/operators/rnn_op.cc
  paddle/phi/api/yaml/op_compat.yaml
  paddle/phi/api/yaml/static_backward.yaml
  paddle/phi/api/yaml/static_ops.yaml
  paddle/phi/ops/compat/rnn_sig.cc
Labels: contributor, status: proposed

#53007 remove mlu
  cmake/operators.cmake
  paddle/fluid/eager/amp_auto_cast.h
  paddle/fluid/eager/amp_utils.h
  paddle/fluid/eager/eager_amp_auto_cast.h
  paddle/fluid/framework/library_type.h
  paddle/fluid/framework/tensor_util.cc
  paddle/fluid/imperative/CMakeLists.txt
  paddle/fluid/imperative/amp_auto_cast.cc
  paddle/fluid/imperative/reducer.cc
  paddle/fluid/operators/collective/c_comm_init_op.cc
  paddle/fluid/operators/generator/get_expected_kernel_func.cc
  paddle/fluid/operators/interpolate_op.h
  paddle/fluid/operators/reader/buffered_reader.cc
  paddle/fluid/operators/reader/buffered_reader.h
  paddle/fluid/operators/reduce_ops/reduce_op.h
  paddle/fluid/operators/softmax_op.cc
  paddle/fluid/operators/tile_op_functor.h
  paddle/fluid/platform/CMakeLists.txt
  paddle/fluid/platform/device_context.cc
  paddle/fluid/platform/device_context.h
  paddle/fluid/platform/monitor.cc
  paddle/fluid/platform/monitor.h
  paddle/fluid/platform/place.cc
  paddle/fluid/platform/place.h
  paddle/fluid/platform/profiler/chrometracing_logger.cc
  paddle/fluid/platform/profiler/profiler.h
  paddle/fluid/platform/profiler/utils.cc
  paddle/fluid/pybind/place.cc
  paddle/fluid/pybind/tensor.cc
  paddle/fluid/pybind/tensor_py.h
  paddle/phi/common/backend.h
  paddle/phi/common/place.cc
  paddle/phi/core/compat/convert_utils.cc
  python/paddle/distributed/spawn.py
  python/paddle/nn/functional/loss.py
  python/paddle/profiler/profiler.py
  tools/get_pr_ut.py
Labels: contributor, status: proposed

#52572 【Hackathon No.59】index_add, index_sample, put_along_axis, take_along_axis算子FP16/BF16单测完善
  paddle/phi/kernels/funcs/gather_scatter_functor.h
  paddle/phi/kernels/gpu/index_add_grad_kernel.cu
  paddle/phi/kernels/gpu/index_add_kernel.cu
  paddle/phi/kernels/gpu/put_along_axis_grad_kernel.cu
  paddle/phi/kernels/gpu/put_along_axis_kernel.cu
  paddle/phi/kernels/gpu/take_along_axis_grad_kernel.cu
  paddle/phi/kernels/gpu/take_along_axis_kernel.cu
  python/paddle/fluid/tests/unittests/test_index_add_op.py
  python/paddle/fluid/tests/unittests/test_index_sample_op.py
  python/paddle/fluid/tests/unittests/test_put_along_axis_op.py
  python/paddle/fluid/tests/unittests/test_take_along_axis_op.py
  python/paddle/tensor/manipulation.py
Labels: contributor, status: proposed

#52683 【Hackathon No.60】randperm, split, split_with_num 算子FP16/BF16单测完善
  paddle/phi/kernels/gpu/randperm_kernel.cu
  python/paddle/fluid/tests/unittests/test_randperm_op.py
  python/paddle/fluid/tests/unittests/test_split_op.py
  python/paddle/tensor/manipulation.py
Labels: contributor, status: proposed

#52956 【Hackathon No.64】logspace 算子FP16/BF16单测完善
  paddle/phi/kernels/gpu/logspace_kernel.cu
  python/paddle/fluid/tests/unittests/test_logspace.py
Labels: contributor, status: proposed

#52925 reorder MatrixRank
  paddle/phi/api/yaml/legacy_ops.yaml
  paddle/phi/api/yaml/static_ops.yaml
  paddle/phi/infermeta/binary.cc
  paddle/phi/infermeta/unary.cc
  paddle/phi/infermeta/unary.h
  paddle/phi/kernels/cpu/matrix_rank_kernel.cc
  paddle/phi/kernels/gpu/matrix_rank_kernel.cu
  paddle/phi/kernels/matrix_rank_kernel.h
  paddle/phi/ops/compat/matrix_rank_sig.cc
  python/paddle/fluid/tests/unittests/test_matrix_rank_op.py
  python/paddle/tensor/linalg.py
Labels: contributor, status: proposed

#52666 【Hackathon No.60】prelu, clip_by_norm, multi_dot 算子FP16/BF16单测完善
  paddle/fluid/operators/math/prelu.cu
  paddle/phi/kernels/gpu/clip_by_norm_kernel.cu
  paddle/phi/kernels/gpu/multi_dot_grad_kernel.cu
  paddle/phi/kernels/gpu/multi_dot_kernel.cu
  paddle/phi/kernels/gpu/prelu_grad_kernel.cu
  paddle/phi/kernels/gpu/prelu_kernel.cu
  python/paddle/fluid/tests/unittests/test_clip_by_norm_op.py
  python/paddle/fluid/tests/unittests/test_multi_dot_op.py
  python/paddle/fluid/tests/unittests/test_prelu_op.py
  python/paddle/nn/clip.py
  python/paddle/nn/functional/activation.py
  python/paddle/tensor/linalg.py
Labels: contributor, status: proposed

#52930 fix graph_reindex
  paddle/fluid/operators/graph_reindex_op.cc
  paddle/phi/api/yaml/op_compat.yaml
  paddle/phi/api/yaml/ops.yaml
  paddle/phi/infermeta/multiary.cc
  paddle/phi/infermeta/multiary.h
  paddle/phi/kernels/cpu/graph_reindex_kernel.cc
  paddle/phi/kernels/gpu/graph_reindex_kernel.cu
  paddle/phi/kernels/graph_reindex_kernel.h
  paddle/phi/ops/compat/graph_reindex_sig.cc
  python/paddle/geometric/reindex.py
  python/paddle/incubate/operators/graph_reindex.py
Labels: contributor, status: proposed

#52855 add autogen code support for mean_all op
  paddle/fluid/operators/mean_op.cc
  paddle/phi/api/yaml/backward.yaml
  paddle/phi/api/yaml/legacy_backward.yaml
  paddle/phi/api/yaml/legacy_ops.yaml
  paddle/phi/api/yaml/op_compat.yaml
  paddle/phi/api/yaml/ops.yaml
  paddle/phi/infermeta/unary.cc
  paddle/phi/infermeta/unary.h
  paddle/phi/ops/compat/mean_sig.cc
Labels: contributor, status: proposed

#53011 Move fused_attention op to phi [迁移XPU OpKernel] [ test=kunlun ]
  paddle/fluid/framework/new_executor/interpreter/static_build.cc
  paddle/fluid/operators/fused/fused_attention_op_xpu.cc
  paddle/phi/kernels/fused_attention_grad_kernel.h
  paddle/phi/kernels/fused_attention_kernel.h
  paddle/phi/kernels/xpu/fused_attention_grad_kernel.cc
  paddle/phi/kernels/xpu/fused_attention_kernel.cc
  paddle/phi/kernels/xpu/xpu_fused_common_function.h
  python/paddle/fluid/tests/unittests/CMakeLists.txt
Labels: contributor, status: proposed

#53099 Fix typos, test=document_fix
  paddle/phi/kernels/digamma_kernel.h
  python/paddle/fluid/__init__.py
  python/paddle/fluid/backward.py
  python/paddle/fluid/compiler.py
  python/paddle/fluid/core.py
Labels: contributor, status: proposed

#53019 Fix open missing mode on jetson
  paddle/fluid/inference/analysis/ir_passes/tensorrt_subgraph_pass.cc
Labels: contributor, status: proposed

#53082 Fix a code sample bug for function 'mode()'
  python/paddle/tensor/search.py
Labels: contributor, status: proposed

#53046 remove ASCEND* keyword
  paddle/fluid/operators/ascend_trigger_op.cc
  paddle/fluid/operators/ascend_trigger_op.h
  paddle/fluid/operators/collective/c_allreduce_op.h
  paddle/fluid/operators/collective/c_reduce_op.h
  paddle/fluid/operators/unity_build_rule.cmake
  paddle/fluid/platform/monitor.cc
  paddle/phi/backends/device_memory_aligment.h
  paddle/phi/core/flags.cc
  paddle/phi/kernels/npu_identity_kernel.cc
  python/paddle/distributed/fleet/meta_optimizers/sharding_optimizer.py
  python/paddle/distributed/transpiler/ascend_transpiler.py
  python/paddle/fluid/dygraph/varbase_patch_methods.py
  python/paddle/fluid/tests/unittests/test_ascend_trigger.py
  python/paddle/fluid/tests/unittests/test_fleet_launch_ascend.sh
  python/paddle/incubate/__init__.py
  python/paddle/incubate/tensor/__init__.py
  python/paddle/incubate/tensor/manipulation.py
  python/paddle/nn/functional/conv.py
  python/paddle/nn/layer/norm.py
  tools/gen_ut_cmakelists.py
  tools/parallel_UT_rule.py
Labels: contributor, status: proposed

#53058 rem hccl keywords
  paddle/fluid/distributed/collective/custom_ccl_tools.cc
  paddle/fluid/distributed/collective/process_group_custom.cc
  paddle/fluid/imperative/reducer.cc
Labels: contributor, status: proposed

#53069 [cherry-pick] Fix open missing mode on jetson
  paddle/fluid/inference/analysis/ir_passes/tensorrt_subgraph_pass.cc
Labels: contributor, status: proposed

#53010 move_elementwise_raw
  paddle/phi/kernels/CMakeLists.txt
  paddle/phi/kernels/cpu/elementwise_kernel.cc
  paddle/phi/kernels/elementwise_kernel.cc
  paddle/phi/kernels/elementwise_kernel.h
  paddle/phi/kernels/kps/elementwise_kernel.cu
  paddle/phi/kernels/legacy/cpu/elementwise_kernel.cc
  paddle/phi/kernels/legacy/elementwise_kernel.h
  paddle/phi/kernels/legacy/kps/elementwise_kernel.cu
  paddle/phi/kernels/xpu/elementwise_kernel.cc
Labels: contributor, status: not progressed

#53150 rm _init_npu_pipeline_comm
  python/paddle/distributed/fleet/meta_optimizers/sharding_optimizer.py
Labels: contributor, status: proposed

#52711 support auto generate for op adam, adamw and merged_adam optimizer
  paddle/fluid/operators/optimizers/adam_op.cc
  paddle/fluid/operators/optimizers/adam_op.h
  paddle/fluid/operators/optimizers/adam_op_functor.h
  paddle/fluid/operators/optimizers/adamw_op.cc
  paddle/fluid/operators/optimizers/merged_adam_op.cc
  paddle/fluid/operators/optimizers/unity_build_rule.cmake
  paddle/phi/api/yaml/legacy_ops.yaml
  paddle/phi/api/yaml/op_compat.yaml
  paddle/phi/api/yaml/op_version.yaml
  paddle/phi/api/yaml/ops.yaml
  paddle/phi/ops/compat/adamw_sig.cc
  paddle/phi/ops/compat/merged_adam_sig.cc
Labels: contributor, status: proposed

#52963 【Hackathon No.61】增加 unfold 算子FP16/BF16单测
  paddle/phi/kernels/funcs/im2col.cu
  paddle/phi/kernels/gpu/unfold_grad_kernel.cu
  paddle/phi/kernels/gpu/unfold_kernel.cu
  python/paddle/fluid/tests/unittests/test_unfold_op.py
Labels: contributor, status: proposed

#52954 【Hackathon No.64】trace 算子FP16/BF16单测完善
  paddle/phi/kernels/gpu/trace_grad_kernel.cu
  paddle/phi/kernels/gpu/trace_kernel.cu
  python/paddle/fluid/tests/unittests/test_trace_op.py
Labels: contributor, status: proposed

#52444 【Hackathon No.61】增加 update_loss_scaling 算子FP16/BF16单测
  python/paddle/fluid/tests/unittests/test_update_loss_scaling_op.py
Labels: contributor, status: proposed

#50494 add deterministic embedding grad kernel
  paddle/phi/core/flags.cc
  paddle/phi/kernels/gpu/embedding_grad_kernel.cu
Labels: NVIDIA, contributor

#53138 optimize memory allocation of optimizer
  python/paddle/optimizer/optimizer.py
Labels: contributor, status: not progressed

#53097 optimize memory allocation of optimizer
  python/paddle/optimizer/optimizer.py
Labels: contributor, status: proposed

#52820 relocate paddle/fluid/contrib/layers
  paddle/fluid/operators/tdm_child_op.h
  python/paddle/fluid/contrib/__init__.py
  python/paddle/fluid/contrib/layers/metric_op.py
  python/paddle/fluid/layers/nn.py
  python/paddle/fluid/tests/unittests/dist_fleet_sparse_embedding_ctr.py
  python/paddle/fluid/tests/unittests/test_bilateral_slice_op.py
  python/paddle/fluid/tests/unittests/test_boxps.py
  python/paddle/fluid/tests/unittests/test_dist_fleet_minimize.py
  python/paddle/fluid/tests/unittests/test_dist_fleet_ps11.py
  python/paddle/fluid/tests/unittests/test_dist_fleet_ps12.py
  python/paddle/fluid/tests/unittests/test_dist_fleet_ps13.py
  python/paddle/fluid/tests/unittests/test_dist_fleet_ps2.py
  python/paddle/fluid/tests/unittests/test_dist_fleet_ps4.py
  python/paddle/fluid/tests/unittests/test_dist_fleet_ps6.py
  python/paddle/fluid/tests/unittests/test_dist_fleet_sparse_embedding_ctr.py
  python/paddle/fluid/tests/unittests/test_dist_fleet_spmt.py
  python/paddle/fluid/tests/unittests/test_fleet_pyramid_hash.py
  python/paddle/fluid/tests/unittests/test_fuse_bn_add_act_pass.py
  python/paddle/fluid/tests/unittests/test_fused_emb_seq_pool_op.py
  python/paddle/fluid/tests/unittests/test_layers.py
  python/paddle/fluid/tests/unittests/test_pow2_decay_with_linear_warmup_op.py
  python/paddle/fluid/tests/unittests/test_pull_gpups_sparse_op.py
  python/paddle/fluid/tests/unittests/test_pyramid_hash_op.py
  python/paddle/fluid/tests/unittests/test_tdm_child_op.py
  python/paddle/fluid/tests/unittests/test_tdm_sampler_op.py
  python/paddle/fluid/tests/unittests/test_while_op.py
  python/paddle/incubate/__init__.py
  python/paddle/incubate/distributed/fleet/fleet_util.py
  python/paddle/incubate/layers/__init__.py
  python/paddle/incubate/layers/nn.py
  python/paddle/static/__init__.py
  python/paddle/static/nn/__init__.py
  python/paddle/static/nn/common.py
  python/paddle/static/nn/metric.py
  python/setup.py.in
  setup.py
  test/contrib/test_correlation.py
  test/legacy_test/test_detection.py
  test/ps/ps_dnn_model.py
  test/xpu/test_pow2_decay_with_linear_warmup_op_xpu.py
Labels: contributor, status: proposed

#53202 delete axis from elementwise_grad
  paddle/fluid/operators/elementwise/elementwise_max_op.cc
  paddle/fluid/operators/elementwise/elementwise_pow_op.cc
  paddle/fluid/prim/api/composite_backward/composite_backward_api.h
  paddle/phi/api/yaml/legacy_backward.yaml
  paddle/phi/kernels/cpu/elementwise_grad_kernel.cc
  paddle/phi/kernels/elementwise_grad_kernel.h
  paddle/phi/kernels/gpu/elementwise_grad_kernel.cu
  paddle/phi/kernels/impl/elementwise_grad_kernel_impl.h
  paddle/phi/kernels/xpu/elementwise_grad_kernel.cc
  paddle/phi/ops/compat/elementwise_sig.cc
Labels: contributor, status: proposed

#52707 delete overwrite from gather_grad
  paddle/fluid/operators/gather_op.cc
  paddle/fluid/prim/api/composite_backward/composite_backward_api.h
  paddle/phi/api/yaml/legacy_backward.yaml
  paddle/phi/api/yaml/op_compat.yaml
  paddle/phi/kernels/cpu/gather_grad_kernel.cc
  paddle/phi/kernels/gather_grad_kernel.h
  paddle/phi/kernels/gpu/gather_grad_kernel.cu
  paddle/phi/kernels/xpu/gather_grad_kernel.cc
  paddle/phi/ops/compat/gather_sig.cc
Labels: contributor, status: proposed

#53038 [Sparse]fix bug in paddle.sparse.transpose and paddle.sparse.reshape
  paddle/phi/kernels/sparse/cpu/transpose_kernel.cc
  paddle/phi/kernels/sparse/gpu/reshape_kernel.cu
  paddle/phi/kernels/sparse/gpu/transpose_kernel.cu
Labels: contributor, status: proposed

#52940 support the 'generate_proposals' for generating static graph ops
  paddle/fluid/operators/detection/CMakeLists.txt
  paddle/fluid/operators/detection/generate_proposals_v2_op.cc
  paddle/phi/api/yaml/legacy_ops.yaml
  paddle/phi/api/yaml/op_compat.yaml
  paddle/phi/api/yaml/op_version.yaml
  paddle/phi/api/yaml/ops.yaml
  paddle/phi/ops/compat/generate_proposals_sig.cc
Labels: contributor, status: proposed

#53196 Move fused feedforward xpu
  paddle/fluid/operators/fused/fused_feedforward_op_xpu.cc
  paddle/phi/kernels/fused_feedforward_grad_kernel.h
  paddle/phi/kernels/fused_feedforward_kernel.h
  paddle/phi/kernels/fusion/xpu/fused_feedforward_grad_xpu_kernel.cc
  paddle/phi/kernels/fusion/xpu/fused_feedforward_xpu_kernel.cc
  paddle/phi/ops/compat/fused_feedforward_sig.cc
Labels: contributor, status: proposed

#53194 rm mlu
  paddle/fluid/imperative/amp_auto_cast.cc
  paddle/fluid/operators/collective/c_comm_init_op.cc
  paddle/fluid/operators/generator/get_expected_kernel_func.cc
  paddle/fluid/operators/reduce_ops/reduce_op.h
  paddle/fluid/operators/softmax_op.cc
  paddle/fluid/platform/device_context.h
  paddle/fluid/platform/profiler/dump/nodetree.proto
  paddle/fluid/platform/profiler/profiler.h
  paddle/fluid/pybind/imperative.cc
  paddle/phi/api/profiler/trace_event.h
  paddle/phi/common/backend.h
  paddle/phi/common/place.h
  python/paddle/amp/auto_cast.py
  python/paddle/amp/grad_scaler.py
  python/paddle/distributed/launch/main.py
  python/paddle/distributed/spawn.py
  python/paddle/profiler/profiler.py
Labels: contributor, status: proposed

#53164 Update sharding_optimizer.py
  python/paddle/distributed/fleet/meta_optimizers/sharding_optimizer.py
Labels: contributor, status: proposed

#53132 remove ASCEND* keyword in doc and cmakelists
  python/paddle/fluid/tests/unittests/CMakeLists.txt
  python/paddle/fluid/tests/unittests/collective/CMakeLists.txt
  python/paddle/fluid/tests/unittests/collective/README.md
  python/paddle/fluid/tests/unittests/collective/fleet/testslist.csv
  python/paddle/fluid/tests/unittests/collective/testslist.csv
Labels: contributor, status: proposed

#53193 Reduce inference library size and compile time
  cmake/phi.cmake
  paddle/phi/kernels/CMakeLists.txt
  tools/reduce_lib_size_util.py
  tools/remove_grad_op_and_kernel.py
Labels: contributor, status: proposed

#53252 Change gpu_time_diff default value in tools/check_op_benchmark_result.py
  tools/check_op_benchmark_result.py
Labels: contributor, status: proposed

#52314 【Hackathon No57】add fp16 & bf16 for max_pool2d_with_index, max_pool3d_with_index
  paddle/phi/kernels/funcs/pooling.cu
  paddle/phi/kernels/gpu/pool_grad_kernel.cu
  paddle/phi/kernels/gpu/pool_kernel.cu
  python/paddle/fluid/tests/unittests/test_pool_max_op.py
Labels: contributor, status: not progressed

#52887 【Hackathon No.61】min 算子FP16/BF16单测完善
  paddle/phi/kernels/gpu/reduce_min_grad_kernel.cu
  paddle/phi/kernels/kps/reduce_min_kernel.cu
  paddle/phi/kernels/reduce_min_kernel.cc
  python/paddle/fluid/tests/unittests/test_reduce_op.py
  python/paddle/tensor/math.py
Labels: contributor, status: proposed

#52195 【Hackathon No57】add_bf16_fp16 unittest for conv3d & conv3d_transpose
  python/paddle/fluid/tests/unittests/test_conv3d_op.py
  python/paddle/fluid/tests/unittests/test_conv3d_transpose_op.py
  python/paddle/fluid/tests/unittests/test_conv3d_transpose_part2_op.py
Labels: contributor, status: proposed

#53145 Fix some problems in Paddle english instruction doc files.
  python/paddle/fluid/framework.py
  python/paddle/tensor/math.py
Labels: contributor, status: proposed
