Repository PaddlePaddle/Paddle, pull requests merged in 2023-02, with the labels that each got.

#49985 Fix Python IndexError of case1: paddle.linalg.lstsq
  python/paddle/fluid/tests/unittests/test_linalg_lstsq_op.py
  python/paddle/tensor/linalg.py
Labels: contributor, status: proposed

#49995 Fix UFA非法地址访问(UFA illegal address access) of case4: paddle.unbind
  paddle/phi/infermeta/unary.cc
  python/paddle/fluid/tests/unittests/test_unbind_op.py
  python/paddle/tensor/manipulation.py
Labels: contributor, status: proposed

#50033 add dynamic shape support for running paddle-trt in calib_mode
  paddle/fluid/operators/tensorrt/tensorrt_engine_op.h
Labels: contributor, status: proposed

#49966 [Divide by 0 Error] add norm check
  paddle/phi/kernels/cpu/p_norm_kernel.cc
  paddle/phi/kernels/gpu/p_norm_kernel.cu
  paddle/phi/kernels/xpu/p_norm_kernel.cc
  python/paddle/fluid/tests/unittests/test_norm_all.py
Labels: contributor, status: proposed

#49971 [Divide by 0 Error] add eig check
  paddle/phi/kernels/cpu/eig_kernel.cc
  python/paddle/fluid/tests/unittests/test_linalg_eig_op.py
  python/paddle/tensor/linalg.py
Labels: contributor, status: proposed

#49974 [Divide by 0 Error] add lu check
  paddle/phi/kernels/impl/lu_kernel_impl.h
  python/paddle/fluid/tests/unittests/test_lu_op.py
Labels: contributor

#49857 support grid_sampler_grad op for XPU
  paddle/phi/backends/xpu/xpu2_op_list.cc
  paddle/phi/kernels/xpu/grid_sample_grad_kernel.cc
  python/paddle/fluid/tests/unittests/op_test_xpu.py
  python/paddle/fluid/tests/unittests/xpu/test_grid_sampler_op_xpu.py
Labels: contributor, status: proposed

#49990 Fix Python IndexError of case9: paddle.static.nn.deform_conv2d
  python/paddle/fluid/tests/unittests/test_deform_conv2d.py
  python/paddle/static/nn/common.py
Labels: contributor, status: proposed

#50015 fix the NullPointerError of matrix_power
  python/paddle/fluid/tests/unittests/test_matrix_power_op.py
Labels: contributor, status: proposed

#49948 fix the div 0 error of sparse_embedding
  python/paddle/fluid/contrib/layers/nn.py
  python/paddle/fluid/tests/unittests/test_sparse_embedding_op.py
Labels: contributor, status: proposed

#50018 [Numpy]Fix NumpyScaler2Tensor dtype error
  python/paddle/fluid/tests/unittests/test_npscaler_to_tensor.py
  python/paddle/tensor/creation.py
Labels: contributor, status: proposed

#48535 run infer ut in A10, test=allcase
  paddle/scripts/paddle_build.sh
  tools/coverage/paddle_coverage_new.sh
  tools/dockerfile/build_scripts/install_trt.sh
  tools/dockerfile/ci_dockerfile.sh
Labels: contributor, status: proposed

#50010 Fix div 0 error of case11: paddle.nn.functional.max_pool1d/max_pool2d/max_pool3d
  paddle/fluid/operators/pool_with_index_op.cc
  paddle/phi/kernels/funcs/pooling.h
  python/paddle/fluid/tests/unittests/test_pool1d_api.py
  python/paddle/fluid/tests/unittests/test_pool2d_api.py
  python/paddle/fluid/tests/unittests/test_pool3d_api.py
Labels: contributor

#49979 Fix 空指针 (Null pointer) of case8: paddle.slice
  paddle/phi/infermeta/unary.cc
  python/paddle/fluid/tests/unittests/test_slice_op.py
Labels: contributor

#49986 Fix Python IndexError of case2-3
  python/paddle/fluid/tests/unittests/test_fused_attention_no_dropout.py
  python/paddle/fluid/tests/unittests/test_fused_multi_transformer_op.py
  python/paddle/incubate/nn/functional/fused_transformer.py
Labels: contributor, status: proposed

#49994 Fix UFA非法地址访问(UFA illegal address access) of case3: paddle.crop
  paddle/phi/kernels/impl/crop_kernel_impl.h
  python/paddle/fluid/tests/unittests/test_crop_op.py
Labels: contributor, status: proposed

#49991 Fix Python IndexError of case16: paddle.nn.functional.max_unpool2d/max_unpool3d
  python/paddle/fluid/tests/unittests/test_unpool3d_op.py
  python/paddle/fluid/tests/unittests/test_unpool_op.py
  python/paddle/nn/functional/pooling.py
Labels: contributor, status: not progressed

#49989 Fix Python IndexError of case8: paddle.static.nn.nce
  python/paddle/fluid/tests/unittests/test_nce.py
  python/paddle/static/nn/loss.py
Labels: contributor, status: proposed

#50012 Fix div 0 error of case10: paddle.nn.functional.max_pool2d/max_pool3d
  paddle/phi/kernels/funcs/pooling.h
  python/paddle/fluid/tests/unittests/test_pool1d_api.py
  python/paddle/fluid/tests/unittests/test_pool2d_api.py
  python/paddle/fluid/tests/unittests/test_pool3d_api.py
Labels: contributor, status: not progressed

#50001 Fix Python IndexError of case18: paddle.nn.functional.conv3d_transpose
  python/paddle/fluid/tests/unittests/test_conv3d_transpose_op.py
  python/paddle/nn/functional/conv.py
Labels: contributor, status: proposed

#50006 Fix Python IndexError of case19: paddle.nn.functional.conv2d_transpose
  python/paddle/fluid/tests/unittests/test_conv2d_transpose_op.py
  python/paddle/nn/functional/conv.py
Labels: contributor, status: proposed

#49987 Fix Python IndexError of case4: paddle.optimizer.lr.PiecewiseDecay
  python/paddle/fluid/tests/unittests/test_lr_scheduler.py
  python/paddle/optimizer/lr.py
  python/paddle/tests/test_callback_reduce_lr_on_plateau.py
Labels: contributor, status: proposed

#49977 [Divide by 0 Error] add normalize check
  python/paddle/fluid/tests/unittests/test_normalize.py
  python/paddle/nn/functional/norm.py
Labels: contributor, status: proposed

#49968 [Divide by 0 Error] add svd check
  python/paddle/fluid/tests/unittests/test_svd_op.py
  python/paddle/tensor/linalg.py
Labels: contributor, status: proposed

#49984 Fix 堆栈溢出 (stack overflow) of case3: paddle.metric.accuracy
  paddle/phi/kernels/cpu/accuracy_kernel.cc
  paddle/phi/kernels/gpu/accuracy_kernel.cu
  python/paddle/fluid/tests/unittests/test_accuracy_op.py
Labels: contributor, status: proposed

#50013 Fix div 0 error of case20: paddle.min
  paddle/fluid/operators/reduce_ops/reduce_op.h
  paddle/phi/kernels/funcs/reduce_function.h
  paddle/phi/kernels/funcs/reduce_grad_functions.h
  paddle/phi/kernels/reduce_min_kernel.cc
  python/paddle/fluid/tests/unittests/test_min_op.py
Labels: contributor, status: proposed

#49582 Rewrite conv testers from cpp to python
  paddle/fluid/framework/ir/CMakeLists.txt
  paddle/fluid/framework/ir/mkldnn/conv_bias_mkldnn_fuse_pass_tester.cc
  paddle/fluid/framework/ir/mkldnn/conv_concat_relu_mkldnn_fuse_pass_tester.cc
  paddle/fluid/framework/ir/mkldnn/conv_elementwise_add_mkldnn_fuse_pass_tester.cc
  python/paddle/fluid/tests/unittests/ir/inference/CMakeLists.txt
  python/paddle/fluid/tests/unittests/ir/inference/test_mkldnn_conv_bias_fuse_pass.py
  python/paddle/fluid/tests/unittests/ir/inference/test_onednn_conv_bias_fuse_pass.py
  python/paddle/fluid/tests/unittests/ir/inference/test_onednn_conv_concat_activation_fuse_pass.py
  python/paddle/fluid/tests/unittests/ir/inference/test_onednn_conv_elementwise_add_fuse_pass.py
Labels: Intel, contributor

#49515 Replace matmul(v2) with fused_matmul during oneDNN fuse passes
  paddle/fluid/framework/ir/mkldnn/matmul_activation_mkldnn_fuse_pass.cc
  paddle/fluid/framework/ir/mkldnn/matmul_elementwise_add_mkldnn_fuse_pass.cc
  paddle/fluid/framework/ir/mkldnn/matmul_transpose_reshape_mkldnn_fuse_pass.cc
  paddle/fluid/framework/ir/mkldnn/operator_scale_onednn_fuse_pass.cc
  paddle/fluid/framework/ir/mkldnn/reshape_transpose_matmul_mkldnn_fuse_pass.cc
  paddle/fluid/operators/compat/fused_matmul.pbtxt
  paddle/fluid/operators/compat/matmul_v2.pbtxt
  paddle/fluid/operators/fused/fused_matmul_op.cc
  paddle/fluid/operators/matmul_v2_op.cc
  paddle/fluid/operators/matmul_v2_op.h
  paddle/fluid/operators/ops_extra_info.h
  paddle/phi/backends/onednn/onednn_reuse.h
  paddle/phi/kernels/fusion/onednn/fused_matmul_kernel.cc
  paddle/phi/kernels/onednn/matmul_kernel.cc
  paddle/phi/ops/compat/fused_matmul_sig.cc
  python/paddle/fluid/tests/unittests/ir/inference/test_map_matmul_v2_to_matmul_pass.py
  python/paddle/fluid/tests/unittests/ir/inference/test_map_matmul_v2_to_mul_pass.py
  python/paddle/fluid/tests/unittests/ir/inference/test_matmul_v2_scale_fuse_pass.py
  python/paddle/fluid/tests/unittests/ir/inference/test_mkldnn_matmul_activation_fuse_pass.py
  python/paddle/fluid/tests/unittests/ir/inference/test_mkldnn_matmul_elementwise_add_activation_fuse_pass.py
  python/paddle/fluid/tests/unittests/ir/inference/test_mkldnn_matmul_elementwise_add_fuse_pass.py
  python/paddle/fluid/tests/unittests/ir/inference/test_mkldnn_matmul_v2_activation_fuse_pass.py
  python/paddle/fluid/tests/unittests/ir/inference/test_mkldnn_matmul_v2_elementwise_add_fuse_pass.py
  python/paddle/fluid/tests/unittests/ir/inference/test_mkldnn_matmul_v2_transpose_reshape_fuse_pass.py
  python/paddle/fluid/tests/unittests/ir/inference/test_mkldnn_matmulv2_op.py
  python/paddle/fluid/tests/unittests/ir/inference/test_onednn_matmul_transpose_reshape_fuse_pass.py
  python/paddle/fluid/tests/unittests/ir/inference/test_onednn_reshape_transpose_matmul_fuse_pass.py
Labels: Intel, contributor

#49983 Fix 堆栈溢出 (stack overflow) of case8: paddle.unique_consecutive
  paddle/phi/kernels/cpu/unique_consecutive_kernel.cc
  paddle/phi/kernels/gpu/unique_consecutive_kernel.cu
  python/paddle/fluid/tests/unittests/test_unique_consecutive_op.py
Labels: contributor, status: proposed

#49752 优化 PartialProgramLayer hash逻辑
  python/paddle/fluid/layers/utils.py
Labels: contributor, status: proposed

#50218 [NPU] fix cross_entropy
  python/paddle/nn/functional/loss.py
Labels: contributor, status: proposed

#50139 [PHI]move ReshapeToMatrix & GetValue
  paddle/fluid/framework/tensor_test.cc
  paddle/fluid/framework/tensor_util.h
  paddle/fluid/operators/bpr_loss_op.h
  paddle/fluid/operators/cross_entropy_op.h
  paddle/fluid/operators/fused/multihead_matmul_op.cu
  paddle/fluid/operators/isfinite_op.h
  paddle/phi/core/tensor_utils.cc
  paddle/phi/core/tensor_utils.h
  paddle/phi/kernels/fusion/onednn/fused_matmul_kernel.cc
  paddle/phi/kernels/gpu/arange_kernel.cu
  paddle/phi/kernels/gpu/linspace_kernel.cu
  paddle/phi/kernels/impl/matmul_grad_kernel_impl.h
  paddle/phi/kernels/impl/matmul_kernel_impl.h
  paddle/phi/kernels/onednn/matmul_grad_kernel.cc
  paddle/phi/kernels/onednn/matmul_kernel.cc
  paddle/phi/kernels/xpu/arange_kernel.cc
  paddle/phi/kernels/xpu/matmul_grad_kernel.cc
  paddle/phi/kernels/xpu/matmul_kernel.cc
Labels: contributor, status: proposed

#50213 [Zero-Dim] unique_consecutive support 0d input
  paddle/phi/infermeta/unary.cc
  python/paddle/fluid/tests/unittests/test_zero_dim_tensor.py
Labels: contributor, status: proposed

#50200 [XPU] add int type for concat and split functor
  paddle/fluid/pybind/process_group_utils.h
  paddle/phi/kernels/xpu/concat_and_split_functor.cc
Labels: contributor, status: not progressed

#50028 Fix 空指针 (Null pointer) of case 17 paddle.flip
  paddle/fluid/pybind/op_function_common.cc
  python/paddle/fluid/tests/unittests/test_flip.py
Labels: contributor, status: proposed

#50097 Fix Python IndexError of case11: paddle.static.nn.data_norm
  python/paddle/fluid/tests/unittests/test_data_norm_op.py
  python/paddle/static/nn/common.py
Labels: contributor, status: proposed

#49958 fix div 0 error of split
  paddle/phi/infermeta/unary.cc
  python/paddle/fluid/tests/unittests/test_split_op.py
Labels: contributor, status: proposed

#49955 fix div 0 error of fft.rfftfreq
  python/paddle/fft.py
  python/paddle/fluid/tests/unittests/fft/test_fft.py
Labels: contributor, status: proposed

#50008 Fix Python IndexError of Case12: paddle.static.nn.bilinear_tensor_product
  python/paddle/fluid/tests/unittests/test_bilinear_tensor_product_op.py
  python/paddle/static/nn/common.py
Labels: contributor, status: proposed

#50106 Support build with gcc12 for CUDA less than 12.0
  cmake/experiments/cuda_module_loading_lazy.cmake
  cmake/external/gloo.cmake
  cmake/external/protobuf.cmake
  cmake/external/warpctc.cmake
  paddle/fluid/framework/fleet/heter_ps/gpu_graph_utils.h
  paddle/fluid/operators/jit/CMakeLists.txt
  paddle/phi/tools/CMakeLists.txt
  patches/gloo/device.cc.patch
  patches/warpctc/CMakeLists.txt.patch
Labels: contributor, status: proposed

#49963 fix the div 0 error of sequence_concat
  paddle/fluid/operators/sequence_ops/sequence_concat_op.cc
  python/paddle/fluid/tests/unittests/sequence/test_sequence_concat.py
Labels: contributor, status: proposed

#49998 fix div 0 error of chunk
  python/paddle/fluid/tests/unittests/test_chunk_op.py
Labels: contributor, status: proposed

#49999 fix div 0 error in conv1/2/3
  paddle/phi/infermeta/binary.cc
  python/paddle/fluid/tests/unittests/test_functional_conv1d.py
  python/paddle/fluid/tests/unittests/test_functional_conv2d.py
  python/paddle/fluid/tests/unittests/test_functional_conv3d.py
Labels: contributor, status: proposed

#50181 [Paddle-TRT] remove engine info from RumImpl process
  paddle/fluid/inference/tensorrt/engine.cc
  paddle/fluid/operators/tensorrt/tensorrt_engine_op.h
Labels: contributor, status: not progressed

#50254 Add bf16 support for fused matmul
  paddle/fluid/framework/ir/graph_pattern_detector.cc
  paddle/fluid/framework/ir/mkldnn/matmul_activation_mkldnn_fuse_pass.cc
  paddle/fluid/framework/ir/mkldnn/matmul_elementwise_add_mkldnn_fuse_pass.cc
  paddle/fluid/framework/ir/mkldnn/matmul_transpose_reshape_mkldnn_fuse_pass.cc
  paddle/fluid/framework/ir/mkldnn/reshape_transpose_matmul_mkldnn_fuse_pass.cc
Labels: Intel, contributor

#49509 fuse quantize+transpose and transpose+dequantize
  paddle/fluid/framework/ir/CMakeLists.txt
  paddle/fluid/framework/ir/graph_pattern_detector.cc
  paddle/fluid/framework/ir/graph_pattern_detector.h
  paddle/fluid/framework/ir/mkldnn/quant_transpose2_dequant_onednn_fuse_pass.cc
  paddle/fluid/framework/ir/mkldnn/quant_transpose2_dequant_onednn_fuse_pass.h
  paddle/fluid/inference/api/paddle_pass_builder.cc
  paddle/fluid/operators/ops_extra_info.h
  paddle/phi/kernels/onednn/transpose_kernel.cc
  python/paddle/fluid/tests/unittests/ir/inference/program_config.py
  python/paddle/fluid/tests/unittests/ir/inference/test_onednn_quant_transpose_dequant_fuse_pass.py
Labels: Intel, contributor

#50228 add logical_and, logical_or and logical_xor for xpu
  paddle/phi/backends/xpu/xpu2_op_list.cc
  paddle/phi/kernels/xpu/logical_kernel.cc
Labels: contributor

#50146 [Paddle-TRT] GroupNorm int8 nchw32 fake kernel
  paddle/fluid/inference/tensorrt/convert/group_norm_op.cc
  paddle/fluid/inference/tensorrt/engine.h
  paddle/fluid/inference/tensorrt/plugin/common/groupNormPluginCommon.h
  paddle/fluid/inference/tensorrt/plugin/group_norm_op_plugin.cu
  paddle/fluid/inference/tensorrt/plugin/group_norm_op_plugin.h
  paddle/fluid/inference/tensorrt/test_dynamic_engine.cc
Labels: contributor, status: proposed

#49899 Adjust mkldnn_placement_pass to check library type and data type
  paddle/fluid/framework/executor.cc
  paddle/fluid/framework/ir/cudnn_placement_pass.cc
  paddle/fluid/framework/ir/cudnn_placement_pass.h
  paddle/fluid/framework/ir/mkldnn/mkldnn_fc_rnn_fuse_pass_tester.cc
  paddle/fluid/framework/ir/mkldnn/mkldnn_placement_pass.cc
  paddle/fluid/framework/ir/mkldnn/mkldnn_placement_pass.h
  paddle/fluid/framework/ir/mkldnn/mkldnn_placement_pass_tester.cc
  paddle/fluid/framework/ir/pass_tester_helper.h
  paddle/fluid/framework/ir/placement_pass_base.cc
  paddle/fluid/framework/ir/placement_pass_base.h
  paddle/fluid/inference/api/CMakeLists.txt
  paddle/fluid/inference/api/api_impl_tester.cc
  paddle/fluid/platform/mkldnn_helper.h
Labels: Intel, contributor

#50209 Modify full kernel for xpu. test=kunlun
  paddle/phi/backends/xpu/xpu2_op_list.cc
  paddle/phi/kernels/selected_rows/full_kernel.cc
  paddle/phi/kernels/xpu/full_kernel.cc
Labels: contributor, status: proposed

#50373 [XPU] bind op: atan & deformable_conv_v1
  paddle/phi/backends/xpu/xpu2_op_list.cc
  paddle/phi/kernels/xpu/atan_grad_kernel.cc
  paddle/phi/kernels/xpu/atan_kernel.cc
  python/paddle/fluid/tests/unittests/xpu/test_atan_op_xpu.py
Labels: contributor, status: proposed

#50016 Fix Python IndexError of Case14: paddle.nn.functional.glu
  python/paddle/fluid/tests/unittests/test_glu.py
  python/paddle/nn/functional/activation.py
Labels: contributor, status: proposed

#50025 Fix UFA非法地址访问(UFA illegal address access) of case2: paddle.scatter
  paddle/phi/kernels/funcs/scatter.cu.h
  paddle/phi/kernels/funcs/scatter.h
  python/paddle/fluid/tests/unittests/test_scatter_op.py
Labels: contributor, status: proposed

#50243 fix stackoverflow case13 gather
  paddle/phi/infermeta/binary.cc
  python/paddle/fluid/tests/unittests/test_gather_op.py
Labels: contributor, status: proposed

#50384 add xpu batch norm ncdhw layout, test=kunlun
  paddle/phi/kernels/xpu/batch_norm_grad_kernel.cc
  paddle/phi/kernels/xpu/batch_norm_kernel.cc
  paddle/phi/kernels/xpu/conv_grad_kernel.cc
  paddle/phi/kernels/xpu/conv_kernel.cc
Labels: contributor, status: proposed

#50394 Fix bugs and add unit tests in instance_norm_grad_kernel when d_scale and d_bias are nullptr. Modify the code style of full_kernel.cc. Add new data type for concat, elementwise_add, gather, scale, scatter ops. test=kunlun
  paddle/phi/backends/xpu/xpu2_op_list.cc
  paddle/phi/kernels/selected_rows/full_kernel.cc
  paddle/phi/kernels/xpu/concat_kernel.cc
  paddle/phi/kernels/xpu/elementwise_add_kernel.cc
  paddle/phi/kernels/xpu/full_kernel.cc
  paddle/phi/kernels/xpu/gather_kernel.cc
  paddle/phi/kernels/xpu/instance_norm_grad_kernel.cc
  paddle/phi/kernels/xpu/scale_kernel.cc
  paddle/phi/kernels/xpu/scatter_kernel.cc
  python/paddle/fluid/tests/custom_op/test_custom_relu_op_xpu_setup.py
  python/paddle/fluid/tests/unittests/xpu/test_instance_norm_op_xpu.py
Labels: contributor, status: proposed

#50291 [Cherry-pick] Support build with gcc12 for CUDA less than 12.0
  cmake/experiments/cuda_module_loading_lazy.cmake
  cmake/external/gloo.cmake
  cmake/external/protobuf.cmake
  cmake/external/warpctc.cmake
  paddle/fluid/operators/jit/CMakeLists.txt
  paddle/phi/tools/CMakeLists.txt
  patches/gloo/device.cc.patch
  patches/warpctc/CMakeLists.txt.patch
Labels: contributor, status: proposed

#50014 Fix div 0 error of case25: paddle.dot
  paddle/phi/kernels/cpu/dot_kernel.cc
  paddle/phi/kernels/impl/dot_grad_kernel_impl.h
  python/paddle/fluid/tests/unittests/test_dot_op.py
Labels: contributor, status: proposed

#50233 add xpu pool3d kernels
  paddle/fluid/operators/reduce_ops/reduce_op.h
  paddle/phi/backends/xpu/xpu2_op_list.cc
  paddle/phi/kernels/reduce_sum_kernel.cc
  paddle/phi/kernels/xpu/activation_grad_kernel.cc
  paddle/phi/kernels/xpu/adam_kernel.cc
  paddle/phi/kernels/xpu/pool_grad_kernel.cc
  paddle/phi/kernels/xpu/pool_kernel.cc
  paddle/phi/kernels/xpu/prod_kernel.cc
  paddle/phi/kernels/xpu/reduce.h
  paddle/phi/kernels/xpu/reduce_max_kernel.cc
  paddle/phi/kernels/xpu/reduce_mean_kernel.cc
  paddle/phi/kernels/xpu/reduce_min_kernel.cc
  paddle/phi/kernels/xpu/reduce_sum_kernel.cc
  python/paddle/fluid/tests/unittests/xpu/test_pool3d_op_xpu.py
  python/paddle/fluid/tests/unittests/xpu/test_reduce_sum_op_xpu.py
Labels: contributor

#50156 Comment: float32 => float16
  python/paddle/amp/auto_cast.py
Labels: contributor, status: proposed

#50393 update class docstring in PiecewiseDecay
  python/paddle/optimizer/lr.py
Labels: contributor, status: proposed

#50415 add tensor numel check for float
  paddle/fluid/pybind/op_function_common.cc
Labels: contributor, status: proposed

#50416 fix: Correct text error
  python/paddle/fluid/tests/unittests/npu/test_take_along_axis_op_npu.py
Labels: contributor, status: proposed

#50458 [CodeStyle] update flake8 config
  .flake8
  .pre-commit-config.yaml
  pyproject.toml
Labels: contributor, status: proposed

#50264 [PHI decoupling]decouple tensor_utils of TensorCopy
  paddle/phi/api/lib/data_transform.cc
  paddle/phi/backends/CMakeLists.txt
  paddle/phi/common/CMakeLists.txt
  paddle/phi/common/int_array.cc
  paddle/phi/common/scalar.cc
  paddle/phi/core/tensor_utils.cc
  paddle/phi/kernels/cpu/amp_kernel.cc
  paddle/phi/kernels/cpu/batch_norm_grad_kernel.cc
  paddle/phi/kernels/cpu/batch_norm_kernel.cc
  paddle/phi/kernels/cpu/broadcast_tensors_grad_kernel.cc
  paddle/phi/kernels/cpu/cross_kernel.cc
  paddle/phi/kernels/cpu/interpolate_kernel.cc
  paddle/phi/kernels/funcs/adam_functors.h
  paddle/phi/kernels/funcs/interpolate_function.h
  paddle/phi/kernels/funcs/math_function.h
  paddle/phi/kernels/gpu/amp_kernel.cu
  paddle/phi/kernels/gpu/broadcast_tensors_grad_kernel.cu
  paddle/phi/kernels/gpu/class_center_sample_kernel.cu
  paddle/phi/kernels/gpu/gumbel_softmax_kernel.cu
  paddle/phi/kernels/gpu/interpolate_kernel.cu
  paddle/phi/kernels/impl/meshgrid_kernel_impl.h
  paddle/phi/kernels/selected_rows/gpu/adamw_kernel.cu
Labels: contributor, status: proposed

#50391 [Paddle-TRT]Fix roll
  paddle/fluid/inference/tensorrt/convert/roll_op.cc
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_roll.py
Labels: contributor, status: proposed

#50187 [Paddle-TRT]fix slice, bilinear_interp_v2 in trt 7011
  paddle/fluid/inference/tensorrt/convert/slice_op.cc
  paddle/fluid/inference/tensorrt/engine.cc
  paddle/fluid/inference/tensorrt/op_teller.cc
  python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_bilinear_interp_v2.py
Labels: contributor, status: proposed

#50409 [CUSTOM]custom device add black_list
  paddle/fluid/framework/phi_utils.cc
  paddle/fluid/framework/phi_utils.h
  paddle/phi/backends/CMakeLists.txt
  paddle/phi/backends/custom/custom_device_op_list.cc
  paddle/phi/backends/custom/custom_device_op_list.h
  paddle/phi/core/kernel_factory.cc
Labels: contributor, status: proposed

#50450 remove duplicated op in xpu2_op_list
  paddle/phi/backends/xpu/xpu2_op_list.cc
Labels: contributor, status: proposed

#50454 add gather_nd_grad op for xpu
  paddle/phi/backends/xpu/xpu2_op_list.cc
  paddle/phi/kernels/xpu/gather_nd_grad_kernel.cc
  paddle/phi/kernels/xpu/where_grad_kernel.cc
  python/paddle/fluid/tests/unittests/xpu/test_gather_nd_op_xpu.py
Labels: contributor, status: proposed

#49278 Rewrite conv activation mkldnn fuse pass tester
  paddle/fluid/framework/ir/CMakeLists.txt
  paddle/fluid/framework/ir/mkldnn/conv_activation_mkldnn_fuse_pass.cc
  paddle/fluid/framework/ir/mkldnn/conv_activation_mkldnn_fuse_pass_tester.cc
  python/paddle/fluid/tests/unittests/ir/inference/CMakeLists.txt
  python/paddle/fluid/tests/unittests/ir/inference/test_conv_act_mkldnn_fuse_pass.py
  python/paddle/fluid/tests/unittests/ir/inference/test_conv_act_onednn_fuse_pass.py
  python/paddle/fluid/tests/unittests/ir/inference/test_mkldnn_conv_activation_fuse_pass.py
  python/paddle/fluid/tests/unittests/ir/inference/test_onednn_conv_concat_activation_fuse_pass.py
Labels: Intel, contributor

#50247 [XPU] update xccl to 1.0.8 and xdnn to 20230215
  cmake/external/xpu.cmake
  paddle/fluid/platform/device/xpu/bkcl_helper.h
  paddle/fluid/pybind/process_group_utils.h
  paddle/phi/backends/xpu/enforce_xpu.h
  paddle/phi/kernels/xpu/concat_and_split_functor.cc
Labels: contributor, status: proposed

#50530 Update trt version to 8.5.3.1
  tools/dockerfile/build_scripts/install_trt.sh
  tools/dockerfile/ci_dockerfile.sh
Labels: contributor, status: proposed

#50031 Export paddle_proto symbols
  paddle/fluid/inference/paddle_inference.map
  paddle/fluid/inference/paddle_inference_custom_device.map
Labels: Intel, contributor

#50539 add cinn_git_tag param
  paddle/scripts/paddle_build.sh
  setup.py
Labels: contributor, status: proposed

#49577 [note]-MSELoss- API英文文档中包含报错信息的问题修复
  python/paddle/nn/layer/loss.py
Labels: contributor, status: proposed

#49493 fix englishdocs typo error in 8th2s
  python/paddle/nn/functional/activation.py
  python/paddle/nn/layer/activation.py
Labels: contributor, status: proposed

#49428 修改docs对应的英文注释synchronize函数等
  python/paddle/device/cuda/__init__.py
  python/paddle/fft.py
Labels: contributor, status: proposed

#49626 delete numpy,test=document_fix,test=docs_preview
  python/paddle/nn/layer/common.py
Labels: contributor, status: proposed

#50599 [XPU] add fp16 support for cumsum and log
  paddle/phi/backends/xpu/xpu2_op_list.cc
  paddle/phi/kernels/xpu/activation_kernel.cc
  paddle/phi/kernels/xpu/cum_kernel.cc
  python/paddle/fluid/tests/unittests/xpu/test_cumsum_op_xpu.py
Labels: contributor, status: proposed

#46301 upgrade oneDNN to 2.7.3
  cmake/external/mkldnn.cmake
  paddle/fluid/framework/ir/mkldnn/softplus_activation_mkldnn_fuse_pass.cc
  paddle/fluid/operators/mkldnn/fc_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/matmul_v2_mkldnn_op.cc
  paddle/phi/backends/onednn/onednn_reuse.h
  python/paddle/fluid/tests/unittests/ir/inference/test_onednn_softplus_activation_fuse_pass.py
Labels: Intel, contributor, status: proposed

#50627 add missing newline to some ci message
  tools/check_file_diff_approvals.sh
Labels: contributor, status: proposed

#50644 Update image.py
  python/paddle/dataset/image.py
Labels: contributor, status: proposed

#50650 Update CspFileReader.py
  tools/CrossStackProfiler/CspFileReader.py
Labels: contributor, status: proposed

#50651 Update CspReporter.py
  tools/CrossStackProfiler/CspReporter.py
Labels: contributor, status: proposed

#50475 [PHI decoupling] remove reference to fluid/framework/tensor.h in phi
  paddle/phi/backends/custom/custom_device_test.cc
  paddle/phi/kernels/funcs/math_function.h
  paddle/phi/kernels/funcs/sequence2batch.h
  paddle/phi/kernels/gpu/depthwise_conv.h
  paddle/phi/tests/core/test_custom_kernel.cc
Labels: contributor, status: proposed

#50614 [XPU] add fp16 support for top_k_v2, squeeze2 and argsort.
  paddle/phi/backends/xpu/xpu2_op_list.cc
  paddle/phi/kernels/xpu/argsort_kernel.cc
  paddle/phi/kernels/xpu/top_k_kernel.cc
  python/paddle/fluid/tests/unittests/xpu/test_argsort_op_xpu.py
  python/paddle/fluid/tests/unittests/xpu/test_top_k_v2_op_xpu.py
Labels: contributor, status: not progressed

#49594 [note]Linear API 英文文档的shape缺少对数据类型的描述
  python/paddle/nn/layer/common.py
Labels: contributor, status: proposed

#50652 Update DCGMFileReader.py
  tools/CrossStackProfiler/DCGMFileReader.py
Labels: contributor, status: proposed

#50655 [XPU] add fp16 support for tril_triu. add index_sample op.
  cmake/external/xpu.cmake
  paddle/phi/backends/xpu/xpu2_op_list.cc
  paddle/phi/kernels/xpu/index_sample_kernel.cc
  paddle/phi/kernels/xpu/tril_triu_grad_kernel.cc
  paddle/phi/kernels/xpu/tril_triu_kernel.cc
  python/paddle/fluid/tests/unittests/xpu/test_cumsum_op_xpu.py
  python/paddle/fluid/tests/unittests/xpu/test_index_sample_op_xpu.py
Labels: contributor, status: proposed

#50653 pad3d support fp16 for xpu
  paddle/phi/backends/xpu/xpu2_op_list.cc
  paddle/phi/kernels/xpu/pad3d_kernel.cc
  python/paddle/fluid/tests/unittests/xpu/test_pad3d_op_xpu.py
Labels: contributor

#50606 add c_reduce_sum for kunlun
  paddle/fluid/operators/collective/c_allreduce_max_op_xpu.cc
  paddle/fluid/operators/collective/c_reduce_sum_op_xpu.cc
  paddle/phi/backends/xpu/xpu2_op_list.cc
  paddle/phi/kernels/xpu/unstack_grad_kernel.cc
  paddle/phi/kernels/xpu/unstack_kernel.cc
  python/paddle/fluid/tests/unittests/xpu/test_unstack_op_xpu.py
Labels: contributor, status: proposed

#50702 [XPU] add fp16 support for assign. update xccl to 1.0.9.
  cmake/external/xpu.cmake
  paddle/phi/backends/xpu/xpu2_op_list.cc
  paddle/phi/kernels/assign_kernel.cc
  python/paddle/fluid/tests/unittests/xpu/test_assign_op_xpu.py
Labels: contributor, status: proposed

#50544 fix coverage combine bug
  tools/coverage/paddle_coverage_new.sh
Labels: contributor, status: proposed

#50429 Fix some typos.
  paddle/CMakeLists.txt
  paddle/fluid/framework/data_set.h
  paddle/fluid/framework/op_desc.h
  paddle/fluid/framework/operator.cc
  paddle/fluid/framework/var_desc.h
  paddle/fluid/inference/tensorrt/convert/c_allreduce_op.cc
  paddle/fluid/operators/cinn/cinn_launch_context.cc
  paddle/fluid/operators/dlnne/dlnne_engine_op.h
  paddle/fluid/operators/fused/attn_gemm_int8.h
  paddle/fluid/operators/fused/fused_gate_attention.h
  paddle/fluid/operators/fused/fused_gate_attention_op.cu
  paddle/fluid/operators/kldiv_loss_op.cc
  paddle/fluid/operators/linear_chain_crf_op.cc
  paddle/phi/infermeta/binary.cc
  paddle/phi/infermeta/nullary.cc
  paddle/phi/kernels/cpu/gather_tree_kernel.cc
  paddle/phi/kernels/funcs/broadcast_function.h
  paddle/phi/kernels/gpu/gather_tree_kernel.cu
  paddle/scripts/README.md
  python/paddle/distributed/auto_parallel/interface.py
  python/paddle/fluid/dygraph/layers.py
  python/paddle/fluid/tests/unittests/ir/inference/auto_scan_test.py
  python/paddle/fluid/tests/unittests/test_fused_gate_attention_op.py
  python/paddle/incubate/autograd/primreg.py
  python/paddle/incubate/nn/layer/fused_transformer.py
  python/paddle/optimizer/lr.py
  python/paddle/static/nn/common.py
  tools/get_single_test_cov.py
Labels: contributor, status: proposed

#50753 update device value error formatting
  python/paddle/fluid/framework.py
Labels: contributor, status: proposed

#49934 kunlun support c_softmax_with_cross_entropy
  paddle/fluid/operators/collective/c_softmax_with_cross_entropy_op_xpu.cc
  paddle/phi/backends/xpu/xpu2_op_list.cc
  python/paddle/fluid/tests/unittests/xpu/collective_softmax_with_cross_entropy_op_xpu.py
  python/paddle/fluid/tests/unittests/xpu/test_collective_softmax_with_cross_entropy_xpu.py
Labels: contributor

#50763 Fix cutlass build error for cuda greater than 11 and with_python=off
  cmake/external/cutlass.cmake
Labels: contributor

#50625 [Paddle C++ API] Remapping input and output tensors after XPU op has fallen back to CPU op
  paddle/phi/api/yaml/generator/api_base.py
  paddle/phi/api/yaml/generator/api_gen.py
Labels: contributor, status: proposed

#50307 Remove tests with save_quant_model.py
  python/paddle/static/quantization/tests/CMakeLists.txt
  python/paddle/static/quantization/tests/quant2_int8_lstm_model.py
  python/paddle/static/quantization/tests/save_quant_model.py
Labels: Intel, contributor

#50715 [Paddle-TRT] Fix QkvToContextPluginDynamic bug
  paddle/fluid/inference/tensorrt/plugin/qkv_to_context_plugin.cu
Labels: contributor, status: proposed

#50800 fix setup.py
  setup.py
Labels: contributor

#50751 Fused ops converter
  paddle/fluid/framework/ir/conv_bn_fuse_pass.cc
  paddle/fluid/framework/ir/mkldnn/activation_onednn_fuse_pass.h
  paddle/fluid/framework/ir/mkldnn/conv_activation_mkldnn_fuse_pass.cc
  paddle/fluid/framework/ir/mkldnn/conv_elementwise_add_mkldnn_fuse_pass.cc
  paddle/fluid/framework/ir/mkldnn/cpu_quantize_pass.cc
  paddle/fluid/framework/ir/mkldnn/cpu_quantize_placement_pass.cc
  paddle/fluid/framework/ir/mkldnn/cpu_quantize_squash_pass.cc
  paddle/fluid/framework/ir/mkldnn/int8_scale_calculation_mkldnn_pass.cc
  paddle/fluid/framework/ir/mkldnn/matmul_activation_mkldnn_fuse_pass.cc
  paddle/fluid/framework/ir/mkldnn/matmul_elementwise_add_mkldnn_fuse_pass.cc
  paddle/fluid/framework/ir/mkldnn/matmul_transpose_reshape_mkldnn_fuse_pass.cc
  paddle/fluid/framework/ir/mkldnn/mkldnn_pass_util.h
  paddle/fluid/framework/ir/mkldnn/operator_scale_onednn_fuse_pass.cc
  paddle/fluid/framework/ir/mkldnn/reshape_transpose_matmul_mkldnn_fuse_pass.cc
Labels: Intel, contributor

#50554 [Paddle-TRT] allow plugin fall back to fp16 when int8
  paddle/fluid/inference/tensorrt/engine.h
Labels: contributor, status: proposed

#50852 Fix typos
  python/paddle/signal.py
  tools/count_api_without_core_ops.py
  tools/infrt/generate_pd_op_dialect_from_paddle_op_maker.py
  tools/infrt/generate_phi_kernel_dialect.py
  tools/infrt/get_phi_kernel_info.py
  tools/infrt/print_kernel_pass_info.py
Labels: contributor, status: proposed

#50546 [Paddle-TRT-fix]fix solov2 infer error
  paddle/fluid/inference/tensorrt/engine.h
Labels: contributor, status: proposed

#50847 [fp16] suppot fp16 input in nansum
  python/paddle/fluid/tests/unittests/test_nansum_api.py
  python/paddle/tensor/math.py
  python/paddle/tensor/search.py
Labels: contributor, status: proposed

#50848 fix fp16 dtype checking for paddle.diag API
  python/paddle/fluid/tests/unittests/test_diag.py
  python/paddle/tensor/creation.py
Labels: contributor, status: proposed

#50849 [fp16] fix fp16 support for nn.PairwiseDistance
  python/paddle/fluid/tests/unittests/test_pairwise_distance.py
  python/paddle/nn/functional/distance.py
  python/paddle/nn/layer/distance.py
Labels: contributor

#50868 fix fp16 dtype checking for conj op
  python/paddle/fluid/tests/unittests/test_conj_op.py
  python/paddle/tensor/math.py
Labels: contributor, status: proposed

#50878 fix fp16 dtype checking for clip op
  python/paddle/fluid/tests/unittests/test_clip_op.py
  python/paddle/tensor/math.py
Labels: contributor, status: proposed

#50905 [fp16] suppot fp16 in broadcast
  python/paddle/fluid/tests/unittests/test_broadcast_to_op.py
  python/paddle/tensor/manipulation.py
Labels: contributor, status: proposed

#50906 [fp16] suppot fp16 in flatten
  python/paddle/fluid/tests/unittests/test_flatten_op.py
  python/paddle/tensor/manipulation.py
Labels: contributor, status: proposed

#50909 [fp16] suppot fp16 in gather_nd
  python/paddle/fluid/tests/unittests/test_gather_nd_op.py
  python/paddle/tensor/manipulation.py
Labels: contributor, status: proposed

#50916 [fp16] support fp16 on unbind
  python/paddle/fluid/tests/unittests/test_unbind_op.py
  python/paddle/tensor/manipulation.py
Labels: contributor, status: proposed

#50917 [fp16] support fp16 on AlphaDropout
  python/paddle/fluid/tests/unittests/test_dropout_op.py
  python/paddle/nn/functional/common.py
Labels: contributor, status: proposed

#50920 [fp16] support fp16 on AvgPool3D
  python/paddle/fluid/tests/unittests/test_pool3d_api.py
  python/paddle/nn/functional/pooling.py
Labels: contributor, status: proposed

#50919 [fp16] support fp16 on temporal_shift
  python/paddle/fluid/tests/unittests/test_temporal_shift_op.py
  python/paddle/nn/functional/extension.py
Labels: contributor

#50929 [Bug fix] Fix fp16 dtype checking for AvgPool1D op
  python/paddle/fluid/tests/unittests/test_pool1d_api.py
  python/paddle/nn/functional/pooling.py
Labels: contributor, status: proposed

#50894 Fix typos
  python/paddle/audio/backends/backend.py
  python/paddle/audio/datasets/esc50.py
  python/paddle/audio/datasets/tess.py
  python/paddle/autograd/backward_mode.py
  python/paddle/autograd/saved_tensors_hooks.py
  python/paddle/dataset/conll05.py
  python/paddle/dataset/flowers.py
  python/paddle/dataset/image.py
  python/paddle/dataset/imikolov.py
  python/paddle/distributed/auto_parallel/cluster_v2.py
  python/paddle/distributed/auto_parallel/completion.py
  python/paddle/distributed/auto_parallel/dist_context.py
  python/paddle/distributed/auto_parallel/dist_loader.py
  python/paddle/distributed/auto_parallel/dist_op.py
  python/paddle/distributed/auto_parallel/engine.py
  python/paddle/distributed/auto_parallel/interface.py
  python/paddle/distributed/auto_parallel/operators/common.py
  python/paddle/distributed/auto_parallel/operators/dist_embedding.py
  python/paddle/distributed/auto_parallel/operators/dist_fill_constant_batch_size_like.py
  python/paddle/distributed/auto_parallel/operators/dist_matmul.py
  python/paddle/distributed/auto_parallel/operators/dist_pnorm.py
  python/paddle/distributed/auto_parallel/operators/dist_update_loss_scaling.py
  python/paddle/distributed/auto_parallel/parallelizer.py
  python/paddle/distributed/auto_parallel/partitioner.py
  python/paddle/distributed/auto_parallel/planner_v2.py
  python/paddle/distributed/auto_parallel/process_group.py
  python/paddle/distributed/auto_parallel/process_mesh_v2.py
  python/paddle/distributed/auto_parallel/strategy.py
  python/paddle/distributed/auto_parallel/tuner/algorithms.py
  python/paddle/distributed/auto_parallel/tuner/optimization_tuner.py
  python/paddle/distributed/auto_parallel/tuner/parallel_tuner.py
  python/paddle/distributed/auto_parallel/tuner/profiler.py
  python/paddle/distributed/auto_parallel/tuner/rule_based_tuner.py
  python/paddle/distributed/auto_parallel/tuner/trial.py
  python/paddle/distributed/auto_parallel/tuner/tunable_space.py
  python/paddle/distributed/auto_parallel/utils.py
Labels: contributor, status: proposed

#50833 【Hackathon No.68】Remove utils in phi
  paddle/fluid/operators/concat_op_mlu.cc
  paddle/fluid/operators/cudnn_lstm_op.cu.cc
  paddle/fluid/operators/interpolate_v2_op_mlu.cc
  paddle/fluid/operators/one_hot_v2_op_mlu.cc
  paddle/fluid/operators/reshape_op_mlu.cc
  paddle/fluid/operators/reshape_op_npu.cc
  paddle/fluid/operators/rnn_op_mlu.cc
  paddle/fluid/operators/slice_op_mlu.cc
  paddle/fluid/operators/slice_op_npu.cc
  paddle/fluid/operators/split_op_mlu.cc
  paddle/fluid/operators/strided_slice_op_mlu.cc
  paddle/fluid/operators/strided_slice_op_npu.cc
  paddle/fluid/operators/unsqueeze_op.h
  paddle/fluid/operators/utils.h
  paddle/phi/core/tensor_utils.h
  paddle/phi/kernels/cpu/rnn_functor.h
  paddle/phi/kernels/gpu/rnn_grad_kernel.cu.cc
  paddle/phi/kernels/gpu/rnn_kernel.cu.cc
  paddle/phi/kernels/xpu/rnn_grad_kernel.cc
  paddle/phi/kernels/xpu/rnn_kernel.cc
Labels: contributor, status: proposed

#50939 [bug fix] fix fp16 dtype checking for argsort op
  python/paddle/fluid/tests/unittests/test_argsort_op.py
  python/paddle/tensor/search.py
Labels: contributor, status: proposed

#50859 [Fix Typo] Unify the digital presentation of rrelu's Docs
  python/paddle/nn/functional/activation.py
Labels: contributor, status: proposed

#50973 [bug fix] fix fp16 dtype checking for cumsum op
  python/paddle/fluid/tests/unittests/test_cumsum_op.py
  python/paddle/tensor/math.py
Labels: contributor, status: proposed

#50975 Add author
  AUTHORS.md
Labels: contributor, status: proposed

#50904 [fp16] suppot fp16 on nn.Dropout2D
  paddle/fluid/operators/temporal_shift_op.cc
  python/paddle/fluid/tests/unittests/test_dropout_op.py
  python/paddle/nn/functional/common.py
Labels: contributor, status: proposed

#50913 fix fp16 for tile op
  python/paddle/fluid/tests/unittests/test_tile_op.py
  python/paddle/tensor/manipulation.py
Labels: contributor, status: proposed

#50918 [fp16] support fp16 on LocalResponseNorm
  python/paddle/fluid/tests/unittests/test_lrn_op.py
  python/paddle/nn/functional/norm.py
  python/paddle/nn/layer/pooling.py
Labels: contributor

#50938 [fp16] suppot fp16 in tensordot
  python/paddle/fluid/tests/unittests/test_tensordot.py
  python/paddle/tensor/manipulation.py
Labels: contributor, status: proposed

#50858 [fp16] suppot fp16 in argmin
  python/paddle/fluid/tests/unittests/test_arg_min_max_v2_op.py
  python/paddle/tensor/search.py
Labels: contributor, status: not progressed

#50265 Rewrite mkldnn fc rnn fuse pass tester
  paddle/fluid/framework/ir/CMakeLists.txt
  paddle/fluid/framework/ir/fc_lstm_fuse_pass.cc
  paddle/fluid/framework/ir/mkldnn/mkldnn_fc_rnn_fuse_pass_tester.cc
  paddle/fluid/framework/ir/mkldnn/mkldnn_placement_pass.cc
  python/paddle/fluid/tests/unittests/ir/inference/test_onednn_fc_gru_fuse_pass.py
  python/paddle/fluid/tests/unittests/ir/inference/test_onednn_fc_lstm_fuse_pass.py
Labels: contributor, status: proposed

#50914 Fix some typos
  paddle/fluid/operators/conv_op.h
  paddle/fluid/operators/jit/README.en.md
  paddle/fluid/pybind/communicator_py.cc
  paddle/fluid/pybind/fleet_py.cc
  paddle/scripts/musl_build/README.md
  python/CMakeLists.txt
  python/paddle/distributed/fleet/base/role_maker.py
  python/paddle/fluid/device_worker.py
  python/paddle/fluid/trainer_desc.py
  python/paddle/fluid/trainer_factory.py
  python/paddle/incubate/autograd/composite_rules.py
  python/paddle/incubate/autograd/primx.py
  python/paddle/incubate/distributed/fleet/parameter_server/pslib/__init__.py
  python/paddle/incubate/distributed/fleet/parameter_server/pslib/node.py
  python/paddle/incubate/distributed/fleet/parameter_server/pslib/optimizer_factory.py
  python/paddle/incubate/distributed/fleet/role_maker.py
  python/paddle/tensor/linalg.py
  tools/document_preview.sh
Labels: contributor, status: proposed

#50867 force use np.uint8 for cv2 lut
  python/paddle/vision/transforms/functional.py
Labels: contributor, status: proposed

#50749 【Hackathon No.69】[PHI decoupling] move device_wrapper from fluid to phi
  paddle/phi/backends/callback_manager.cc
  paddle/phi/backends/event.cc
  paddle/phi/backends/stream.cc
  paddle/phi/kernels/funcs/selected_rows_functor.cc
Labels: contributor, status: proposed

#50846 Add gru qat int8 test
  paddle/fluid/inference/tests/api/CMakeLists.txt
  paddle/fluid/inference/tests/api/analyzer_int8_image_classification_tester.cc
  paddle/fluid/inference/tests/api/analyzer_lexical_analysis_gru_tester.cc
  paddle/fluid/inference/tests/api/analyzer_quant_image_classification_tester.cc
  paddle/fluid/inference/tests/api/tester_helper.h
  python/paddle/static/quantization/tests/CMakeLists.txt
Labels: Intel, int8, contributor
