Repository PaddlePaddle/Paddle, pull requests merged in 2023-09, with the labels that each got.

#56261 [clang-tidy] No.34,36 enable performance-noexcept-move-constructor,modernize-use-transparent-functors
  .clang-tidy
  paddle/fluid/distributed/fleet_executor/dist_model_tensor_wrapper.cc
  paddle/fluid/distributed/fleet_executor/dist_model_tensor_wrapper.h
  paddle/fluid/framework/ir/memory_optimize_pass/eager_deletion_pass.cc
  paddle/fluid/framework/ir/memory_optimize_pass/memory_reuse_pass.cc
  paddle/fluid/framework/ir/mkldnn/conv_bias_mkldnn_fuse_pass.cc
  paddle/fluid/framework/ir/mkldnn/shuffle_channel_mkldnn_detect_pass.cc
  paddle/fluid/framework/ir/shuffle_channel_detect_pass.cc
  paddle/fluid/inference/analysis/passes/memory_optimize_pass.cc
  paddle/fluid/inference/api/api.cc
  paddle/fluid/inference/api/paddle_api.h
  paddle/fluid/operators/fused/resnet_unit_op.cc
  paddle/ir/core/op_base.cc
  paddle/ir/core/op_base.h
  paddle/phi/api/include/tensor.h
  paddle/phi/api/lib/tensor.cc
  paddle/phi/backends/cpu/cpu_context.cc
  paddle/phi/backends/gpu/gpu_context.cc
  paddle/phi/core/dense_tensor.cc
  paddle/phi/core/dense_tensor.h
  paddle/phi/core/device_context.cc
  paddle/phi/core/device_context.h
  paddle/phi/core/sparse_coo_tensor.cc
  paddle/phi/core/sparse_coo_tensor.h
  paddle/phi/core/string_tensor.cc
  paddle/phi/core/string_tensor.h
  paddle/phi/kernels/cpu/class_center_sample_kernel.cc
  paddle/phi/kernels/cpu/weighted_sample_neighbors_kernel.cc
Labels: contributor, HappyOpenSource Pro

#56631 【NewIR】enable dy2st new IR test
  test/dygraph_to_static/dygraph_to_static_util.py
  test/dygraph_to_static/test_assert.py
  test/dygraph_to_static/test_ast_util.py
  test/dygraph_to_static/test_backward_without_params.py
  test/dygraph_to_static/test_basic_api_transformation.py
  test/dygraph_to_static/test_cinn.py
  test/dygraph_to_static/test_cinn_prim.py
  test/dygraph_to_static/test_closure_analysis.py
  test/dygraph_to_static/test_convert_call_generator.py
  test/dygraph_to_static/test_cpu_cuda_to_tensor.py
Labels: contributor

#56527 [Doctest]fix No.163,164,166, test=docs_preview
  python/paddle/vision/models/squeezenet.py
  python/paddle/vision/models/vgg.py
  python/paddle/vision/transforms/functional.py
Labels: contributor, HappyOpenSource Pro

#56826 [xdoctest][task 291] reformat example code with google style in `python/paddle/incubate/operators/unzip.py`
  python/paddle/incubate/operators/unzip.py
Labels: contributor, HappyOpenSource Pro

#56747 [clang-tidy] NO.35 enable `bugprone-incorrect-roundings`
  .clang-tidy
  paddle/fluid/operators/detection/mask_util.cc
  paddle/phi/kernels/cpu/interpolate_grad_kernel.cc
  paddle/phi/kernels/cpu/interpolate_kernel.cc
  paddle/phi/kernels/cpu/roi_align_grad_kernel.cc
  paddle/phi/kernels/cpu/roi_align_kernel.cc
Labels: contributor, HappyOpenSource Pro

#56457 【Complex op】add complex support for index_select and index_sample
  paddle/fluid/eager/grad_node_info.cc
  paddle/phi/api/yaml/backward.yaml
  paddle/phi/api/yaml/generator/api_base.py
  paddle/phi/api/yaml/ops.yaml
  paddle/phi/kernels/cpu/index_sample_grad_kernel.cc
  paddle/phi/kernels/cpu/index_sample_kernel.cc
  paddle/phi/kernels/cpu/index_select_grad_kernel.cc
  paddle/phi/kernels/cpu/index_select_kernel.cc
  paddle/phi/kernels/gpu/index_sample_grad_kernel.cu
  paddle/phi/kernels/gpu/index_sample_kernel.cu
  paddle/phi/kernels/gpu/index_select_grad_kernel.cu
  paddle/phi/kernels/gpu/index_select_kernel.cu
  python/paddle/tensor/search.py
  test/legacy_test/test_index_sample_op.py
  test/legacy_test/test_index_select_op.py
Labels: contributor

#56848 export flags defined in phi on windows
  paddle/phi/core/flags.h
Labels: contributor

#56766 [Custom Device]fix symbol redefined
  paddle/fluid/distributed/collective/process_group_custom.cc
Labels: contributor

#56913 fix paddle namespace conflict when using paddle_flags
  paddle/fluid/distributed/ps/service/heter_client.cc
  paddle/phi/core/flags.h
  paddle/utils/flags_native.h
Labels: contributor

#56915 fix compile errors when using shared phi on windows
  paddle/fluid/framework/new_executor/interpreter_base_impl.h
  paddle/fluid/framework/op_kernel_type.h
  paddle/fluid/imperative/tracer.cc
  paddle/fluid/imperative/tracer.h
  paddle/fluid/pybind/eager_method.cc
  paddle/phi/api/lib/api_gen_utils.cc
  paddle/phi/api/lib/data_transform.cc
  paddle/phi/core/kernel_factory.cc
Labels: contributor

#56779 Remove has_structed_kerenl and has_fluid_kernel
  paddle/fluid/framework/new_executor/interpreter/static_build.cc
  test/legacy_test/CMakeLists.txt
Labels: contributor

#56676 [clang-tidy] No. 59,60 bugprone-unused-return-value, bugprone-suspicious-missing-comma
  .clang-tidy
  paddle/fluid/distributed/fleet_executor/fleet_executor.cc
  paddle/fluid/framework/ir/mkldnn/compute_propagate_scales_mkldnn_pass.cc
  paddle/fluid/framework/operator.cc
  paddle/fluid/pybind/eager_legacy_op_function_generator.cc
Labels: contributor, HappyOpenSource Pro

#56649 [clang-tidy] No. 57,58 enable cppcoreguidelines-explicit-virtual-functions clang-analyzer-core.NonNullParamChecker
  .clang-tidy
  paddle/fluid/memory/allocation/naive_best_fit_allocator.cc
  paddle/phi/kernels/cpu/rnn_functor.h
  paddle/phi/kernels/cpu/rnn_kernel.cc
Labels: contributor, HappyOpenSource Pro

#56815 [xdoctest][task 224-225] reformat example code with google style in `python/paddle/distributed/fleet`
  python/paddle/distributed/fleet/model.py
  python/paddle/distributed/fleet/optimizer.py
Labels: contributor, HappyOpenSource Pro

#56599 [xdoctest] reformat example code with google style in No. 301
  python/paddle/incubate/optimizer/modelaverage.py
Labels: contributor, HappyOpenSource Pro

#56677 [xdoctest][task 125-137] reformat example code with google style in static/*
  python/paddle/static/nn/common.py
  python/paddle/static/nn/control_flow.py
Labels: contributor, HappyOpenSource Pro

#56907 [xdoctest] reformat example code with google style in No. 264-265
  python/paddle/incubate/nn/layer/fused_dropout_add.py
  python/paddle/incubate/nn/layer/fused_dropout_nd.py
Labels: contributor, HappyOpenSource Pro

#56666 [xdoctest][task 184-185] reformat example code with google style in `distributed/auto_parallel/static/*`
  python/paddle/distributed/auto_parallel/static/cluster_v2.py
  python/paddle/distributed/auto_parallel/static/converter.py
Labels: contributor, HappyOpenSource Pro

#56751 [Fluid] move lars_momentum_xpu to phi
  paddle/fluid/operators/optimizers/lars_momentum_op_xpu.cc
  paddle/phi/kernels/xpu/lars_momentum_kernel.cc
Labels: contributor, HappyOpenSource Pro

#56749 [Fluid] move lars_momentum_op InferShape to phi
  paddle/fluid/operators/optimizers/lars_momentum_op.cc
  paddle/phi/infermeta/multiary.cc
  paddle/phi/infermeta/multiary.h
Labels: contributor, HappyOpenSource Pro

#56541 [xdoctest] reformat example code with google style in No. 250-260
  python/paddle/incubate/distributed/fleet/parameter_server/pslib/__init__.py
  python/paddle/incubate/distributed/models/moe/grad_clip.py
  python/paddle/incubate/distributed/models/moe/moe_layer.py
  python/paddle/incubate/layers/nn.py
  python/paddle/incubate/nn/functional/fused_dropout_add.py
  python/paddle/incubate/nn/functional/fused_ec_moe.py
  python/paddle/incubate/nn/functional/fused_gate_attention.py
  python/paddle/incubate/nn/functional/fused_matmul_bias.py
  python/paddle/incubate/nn/functional/fused_rotary_position_embedding.py
  python/paddle/tensor/linalg.py
  python/paddle/tensor/logic.py
Labels: contributor, HappyOpenSource Pro

#56901 [xdoctest][task 79] reformat example code with google style in `python/paddle/nn/functional/loss.py`
  python/paddle/nn/functional/loss.py
Labels: contributor, HappyOpenSource Pro

#56965 [xdoctest][task 268] reformat example code with google style in `/incubate/nn/layer/fused_transformer.py`
  python/paddle/incubate/nn/layer/fused_transformer.py
Labels: contributor, HappyOpenSource Pro

#56861 [xdoctest] reformat example code with google style in No.297、298、302
  python/paddle/incubate/optimizer/functional/bfgs.py
  python/paddle/incubate/optimizer/functional/lbfgs.py
  python/paddle/incubate/passes/ir.py
Labels: contributor, HappyOpenSource Pro

#56992 make loss cond. on label while using Stirling approximation
  python/paddle/nn/functional/loss.py
  test/legacy_test/test_poisson_nll_loss.py
Labels: contributor

#56993 fix compile errors with gflags
  cmake/configure.cmake
  cmake/external/gflags.cmake
  paddle/utils/flags.h
Labels: contributor

#56384 [ONEDNN] fix LSTM FP32 model acc drop issue, and add fc_…
  paddle/fluid/operators/mkldnn/fc_mkldnn_op.cc
  paddle/phi/backends/onednn/onednn_helper.h
Labels: Intel, contributor

#56773 [XPU] add squeeze_excitation_block_xpu op&pass to optimize ppocr_v3_det model
  paddle/fluid/framework/ir/CMakeLists.txt
  paddle/fluid/framework/ir/xpu/squeeze_excitation_fuse_pass.cc
  paddle/fluid/framework/ir/xpu/squeeze_excitation_fuse_pass.h
  paddle/fluid/framework/ir/xpu/squeeze_excitation_fuse_pass_test.cc
  paddle/fluid/inference/api/paddle_pass_builder.cc
  paddle/phi/api/yaml/fused_ops.yaml
  paddle/phi/backends/xpu/xpu2_op_list.cc
  paddle/phi/infermeta/fusion.cc
  paddle/phi/infermeta/fusion.h
  paddle/phi/kernels/fusion/xpu/squeeze_excitation_block_xpu_kernel.cc
  test/ir/inference/test_xpu_squeeze_excitation_fuse_pass.py
Labels: contributor

#56772 [xdoctest][task 248-249,266-267,269] reformat example code with google style in `incubate/distributed/fleet/*`,`incubate/nn/layer/*`
  python/paddle/incubate/distributed/fleet/fleet_util.py
  python/paddle/incubate/distributed/fleet/parameter_server/ir/ps_dispatcher.py
  python/paddle/incubate/nn/layer/fused_ec_moe.py
  python/paddle/incubate/nn/layer/fused_linear.py
  python/paddle/incubate/nn/layer/io.py
Labels: contributor, HappyOpenSource Pro

#56797 [xdoctest] reformat example code with google style in No.286-290
  python/paddle/incubate/operators/graph_reindex.py
  python/paddle/incubate/operators/graph_sample_neighbors.py
  python/paddle/incubate/operators/graph_send_recv.py
  python/paddle/incubate/operators/softmax_mask_fuse.py
  python/paddle/incubate/operators/softmax_mask_fuse_upper_triangle.py
Labels: contributor, HappyOpenSource Pro

#56852 【Complex OP】No.28 LogSigmoid
  paddle/phi/common/complex.h
  paddle/phi/kernels/cpu/activation_grad_kernel.cc
  paddle/phi/kernels/cpu/activation_kernel.cc
  paddle/phi/kernels/funcs/activation_functor.h
  paddle/phi/kernels/gpu/activation_grad_kernel.cu
  paddle/phi/kernels/gpu/activation_kernel.cu
  python/paddle/nn/functional/activation.py
  test/legacy_test/test_activation_op.py
Labels: contributor, HappyOpenSource Pro

#56903 【complex op】No.18 add complex support for silu
  paddle/phi/common/complex.h
  paddle/phi/kernels/cpu/activation_grad_kernel.cc
  paddle/phi/kernels/cpu/activation_kernel.cc
  paddle/phi/kernels/funcs/activation_functor.h
  paddle/phi/kernels/gpu/activation_grad_kernel.cu
  paddle/phi/kernels/gpu/activation_kernel.cu
  python/paddle/nn/functional/activation.py
  test/legacy_test/test_activation_op.py
Labels: contributor, HappyOpenSource Pro

#57018 fix doc typo and format
  python/paddle/nn/layer/container.py
  python/paddle/nn/layer/norm.py
  python/paddle/tensor/creation.py
Labels: contributor, HappyOpenSource

#57058 【complex op】No.18 add complex support for silu
  paddle/phi/common/complex.h
Labels: contributor

#56994 [clang-tidy] NO.25 modernize-deprecated-headers
  .clang-tidy
  paddle/fluid/framework/data_feed_factory.cc
  paddle/fluid/framework/device_worker_factory.cc
  paddle/fluid/framework/ir/mkldnn/compute_propagate_scales_mkldnn_pass.cc
  paddle/fluid/framework/lod_tensor.cc
  paddle/fluid/framework/pull_dense_worker.cc
  paddle/fluid/framework/section_worker.cc
  paddle/fluid/framework/trainer_factory.cc
  paddle/fluid/imperative/data_loader.cc
  paddle/fluid/memory/allocation/cpu_allocator.cc
  paddle/fluid/memory/allocation/cuda_ipc_allocator.cc
  paddle/fluid/memory/allocation/mmap_allocator.cc
  paddle/fluid/operators/detection/generate_mask_labels_op.cc
  paddle/fluid/operators/detection/mask_util.cc
  paddle/fluid/operators/save_op.cc
  paddle/fluid/platform/gen_comm_id_helper.cc
  paddle/fluid/platform/profiler/event_node.cc
  paddle/fluid/prim/api/manual_prim/static_prim_api.cc
  paddle/phi/kernels/cpu/lstsq_kernel.cc
  paddle/phi/kernels/cpu/trunc_kernel.cc
  paddle/phi/kernels/funcs/jit/gen/adam.cc
  paddle/phi/kernels/funcs/jit/gen/adamw.cc
  paddle/phi/kernels/funcs/jit/gen/embseqpool.cc
  paddle/phi/kernels/funcs/jit/gen/gru.cc
  paddle/phi/kernels/funcs/jit/gen/lstm.cc
  paddle/phi/kernels/funcs/jit/gen/matmul.cc
  paddle/phi/kernels/funcs/jit/gen/sgd.cc
Labels: contributor, HappyOpenSource Pro

#56744 [clang-tidy] NO.33,64 enable `bugprone-signed-char-misuse`,`clang-analyzer-optin.portability.UnixAPI` check
  .clang-tidy
  paddle/fluid/framework/details/all_reduce_op_handle.cc
  paddle/fluid/framework/details/broadcast_op_handle.cc
  paddle/fluid/framework/details/op_handle_base.cc
  paddle/fluid/framework/details/parallel_ssa_graph_executor.cc
  paddle/fluid/framework/details/reduce_op_handle.cc
  paddle/fluid/framework/dlpack_tensor.cc
  paddle/fluid/imperative/nccl_context.cc
  paddle/fluid/imperative/xccl_context.cc
  paddle/fluid/memory/allocation/cuda_managed_allocator.cc
  paddle/fluid/memory/allocation/cuda_virtual_mem_allocator.cc
  paddle/fluid/operators/reader/buffered_reader.cc
  paddle/fluid/platform/device_event_custom_device.cc
  paddle/fluid/platform/device_event_gpu.cc
  paddle/fluid/pybind/pybind.cc
  paddle/phi/backends/custom/custom_device.cc
  paddle/phi/kernels/cpu/cross_entropy_grad_kernel.cc
  paddle/phi/kernels/cpu/multiclass_nms3_kernel.cc
  paddle/phi/kernels/funcs/cross_entropy.cc
Labels: contributor, HappyOpenSource Pro

#56954 [clang-tidy] NO.20 clang-analyzer-core.CallAndMessage
  .clang-tidy
  paddle/fluid/eager/grad_node_info.cc
  paddle/fluid/framework/ir/delete_cast_op_pass.cc
  paddle/fluid/framework/ir/embedding_fc_lstm_fuse_pass.cc
  paddle/fluid/framework/ir/fuse_adamw_op_pass.cc
  paddle/fluid/framework/ir/graph_pattern_detector.cc
  paddle/fluid/framework/ir/transfer_layout_elim_pass.cc
  paddle/fluid/framework/new_executor/program_interpreter.cc
  paddle/fluid/framework/op_desc.cc
  paddle/fluid/imperative/layer.cc
  paddle/fluid/operators/gru_op.cc
  paddle/fluid/operators/gru_op.cu.cc
  paddle/fluid/operators/mkldnn/matmul_mkldnn_op.cc
  paddle/fluid/operators/sequence_ops/sequence_softmax_cudnn_op.cu.cc
  paddle/phi/kernels/cpu/rnn_functor.h
  paddle/phi/kernels/cpu/rnn_grad_kernel.cc
  paddle/phi/kernels/cpu/send_u_recv_grad_kernel.cc
  paddle/phi/kernels/funcs/activation_functor.h
  paddle/phi/kernels/funcs/gpc.cc
  paddle/phi/kernels/gpu/rnn_functor.h
  paddle/phi/kernels/sparse/cpu/elementwise_grad_kernel.cc
Labels: contributor, HappyOpenSource Pro

#57060 [xdoctest][task 238] reformat example code with google style in `python/paddle/distributed/fleet/launch_utils.py`
  python/paddle/distributed/fleet/launch_utils.py
Labels: contributor, HappyOpenSource Pro

#56906 [xdoctest][task 167-170] reformat example code with google style in /paddle/vision/datasets/*; test=docs_preview
  python/paddle/amp/__init__.py
  python/paddle/vision/datasets/cifar.py
  python/paddle/vision/datasets/flowers.py
  python/paddle/vision/transforms/transforms.py
Labels: contributor, HappyOpenSource Pro

#56782 [OneDNN] Fix v3.2 conv dst layout cause regression case performance declined issue
  paddle/phi/kernels/onednn/conv_handler.h
  test/cpp/fluid/mkldnn/CMakeLists.txt
  test/cpp/fluid/mkldnn/test_conv_mkldnn_nhwc.cc
Labels: Intel, contributor

#57088 refine paddle_flags error message about flag multiple definition
  paddle/utils/flags_native.cc
Labels: contributor

#55695 [NewIR] Add parser to deserialize
  paddle/fluid/ir/dialect/paddle_dialect/ir/pd_attribute.cc
  paddle/fluid/ir/dialect/paddle_dialect/ir/pd_attribute.h
  paddle/fluid/ir/dialect/paddle_dialect/ir/pd_dialect.cc
  paddle/fluid/ir/dialect/paddle_dialect/ir/pd_dialect.h
  paddle/ir/core/CMakeLists.txt
  paddle/ir/core/attribute.h
  paddle/ir/core/dialect.h
  paddle/ir/core/ir_parser.h
  paddle/ir/core/ir_printer.cc
  paddle/ir/core/parser/ir_parser.cc
  paddle/ir/core/parser/lexer.cc
  paddle/ir/core/parser/lexer.h
  paddle/ir/core/parser/token.h
  paddle/ir/core/program.h
  paddle/ir/core/type.h
  test/cpp/ir/core/CMakeLists.txt
  test/cpp/ir/core/TestParserText.txt
  test/cpp/ir/core/add_dialect_parser_test.cc
  test/cpp/ir/core/ir_parser_test.cc
  test/cpp/ir/core/program_translator_test.cc
Labels: contributor

#56871 [Change] use log_exit for end of the check
  paddle/scripts/paddle_build.sh
  tools/sampcd_processor.py
  tools/sampcd_processor_utils.py
Labels: contributor

#56991 Bincount op fix
  paddle/phi/kernels/gpu/bincount_kernel.cu
  test/legacy_test/test_bincount_op.py
Labels: contributor, HappyOpenSource

#56914 【complex op】No.25 add complex support for fold
  paddle/phi/kernels/cpu/fold_grad_kernel.cc
  paddle/phi/kernels/cpu/fold_kernel.cc
  paddle/phi/kernels/funcs/im2col.cc
  paddle/phi/kernels/funcs/im2col.cu
  paddle/phi/kernels/gpu/fold_grad_kernel.cu
  paddle/phi/kernels/gpu/fold_kernel.cu
  python/paddle/nn/functional/common.py
  test/legacy_test/test_fold_op.py
Labels: contributor, HappyOpenSource Pro

#56748 [xdoctest][task 318-322] reformat example code with google style in `paddle/fluid/*` and `python/paddle/sparse/unary`
  paddle/fluid/operators/fused/fused_elemwise_activation_op.cc
  paddle/fluid/pybind/cuda_streams_py.cc
  paddle/fluid/pybind/custom_device_py.cc
  paddle/fluid/pybind/inference_api.cc
  python/paddle/sparse/unary.py
Labels: contributor, HappyOpenSource Pro

#57128 [xdoctest][task 310] reformat example code with google style in python/paddle/sparse/nn/functional/activation.py
  python/paddle/sparse/nn/functional/activation.py
Labels: contributor, HappyOpenSource Pro

#57129 [xdoctest][task 311] reformat example code with google style in python/paddle/sparse/nn/functional/conv.py
  python/paddle/sparse/nn/functional/conv.py
Labels: contributor, HappyOpenSource Pro

#57130 [xdoctest][task 312] reformat example code with google style in python/paddle/sparse/nn/functional/pooling.py
  python/paddle/sparse/nn/functional/pooling.py
Labels: contributor, HappyOpenSource Pro

#57132 [xdoctest][task 314] reformat example code with google style in python/paddle/sparse/nn/layer/activation.py
  python/paddle/sparse/nn/layer/activation.py
Labels: contributor, HappyOpenSource Pro

#57133 [xdoctest][task 315] reformat example code with google style in python/paddle/sparse/nn/layer/conv.py
  python/paddle/sparse/nn/layer/conv.py
Labels: contributor, HappyOpenSource Pro

#57135 [xdoctest][task 316] reformat example code with google style in python/paddle/sparse/nn/layer/norm.py
  python/paddle/sparse/nn/layer/norm.py
Labels: contributor, HappyOpenSource Pro

#57136 [xdoctest][task 317] reformat example code with google style in python/paddle/sparse/nn/layer/pooling.py
  python/paddle/sparse/nn/layer/pooling.py
Labels: contributor, HappyOpenSource Pro

#57134 [xdoctest] reformat example code with google style in No.344-No.352
  python/paddle/base/lod_tensor.py
  python/paddle/base/log_helper.py
  python/paddle/base/param_attr.py
  python/paddle/base/reader.py
  python/paddle/base/unique_name.py
  python/paddle/nn/initializer/lazy_init.py
Labels: contributor, HappyOpenSource Pro

#57140 [xdoctest][task 338] reformat example code with google style in python/paddle/base/initializer.py
  python/paddle/base/initializer.py
Labels: contributor, HappyOpenSource Pro

#57141 [xdoctest][task 334] reformat example code with google style in python/paddle/base/dygraph/math_op_patch.py
  python/paddle/base/dygraph/math_op_patch.py
Labels: contributor, HappyOpenSource Pro

#57143 [xdoctest][task 332] reformat example code with google style in python/paddle/base/dataset.py
  python/paddle/base/dataset.py
Labels: contributor, HappyOpenSource Pro

#57144 [xdoctest][task 335] reformat example code with google style in python/paddle/base/dygraph/tensor_patch_methods.py
  python/paddle/base/dygraph/tensor_patch_methods.py
Labels: contributor, HappyOpenSource Pro

#57127 [xdoctest][task 304] reformat example code with google style in python/paddle/incubate/tensor/math.py
  python/paddle/incubate/tensor/math.py
Labels: contributor, HappyOpenSource Pro

#57146 [xdoctest][task 274] reformat example code with google style in `python/paddle/static/nn/sequence_lod.py`
  python/paddle/static/nn/sequence_lod.py
Labels: contributor, HappyOpenSource Pro

#57151 [xdoctest][task 337] reformat example code with google style in `python/paddle/base/framework.py`
  python/paddle/base/framework.py
Labels: contributor, HappyOpenSource Pro

#57087 [xdoctest] reformat example code with google style in No.339-No.343
  python/paddle/base/layer_helper_base.py
  python/paddle/base/layers/math_op_patch.py
Labels: contributor, HappyOpenSource Pro

#57108 [xdoctest][task 165] reformat example code with google style in python/paddle/vision/ops.py
  python/paddle/vision/ops.py
Labels: contributor, HappyOpenSource Pro

#56531 [GLCC]Part-2: @to_static support for PyLayer
  paddle/fluid/framework/CMakeLists.txt
  paddle/fluid/framework/executor_gc_helper.cc
  paddle/fluid/framework/ir/graph_helper.cc
  paddle/fluid/framework/ir/memory_optimize_pass/CMakeLists.txt
  paddle/fluid/framework/ir/memory_optimize_pass/eager_deletion_pass.cc
  paddle/fluid/framework/ir/memory_optimize_pass/pylayer_op_eager_deletion_pass.cc
  paddle/fluid/framework/new_executor/interpreter/interpreter_util.cc
  paddle/fluid/operators/controlflow/CMakeLists.txt
  paddle/fluid/operators/controlflow/pylayer_op.cc
  paddle/fluid/operators/controlflow/pylayer_op.h
  paddle/fluid/operators/controlflow/pylayer_op_helper.cc
  paddle/fluid/operators/controlflow/pylayer_op_helper.h
  python/paddle/jit/dy2static/convert_operators.py
  python/paddle/jit/dy2static/py_layer.py
  python/paddle/static/nn/static_pylayer.py
  test/dygraph_to_static/test_pylayer.py
  test/legacy_test/test_static_pylayer.py
Labels: contributor

#57116 No.10 add complex support for exp/expm1
  paddle/phi/kernels/cpu/activation_grad_kernel.cc
  paddle/phi/kernels/cpu/activation_kernel.cc
  paddle/phi/kernels/funcs/activation_functor.h
  paddle/phi/kernels/gpu/activation_grad_kernel.cu
  paddle/phi/kernels/gpu/activation_kernel.cu
  python/paddle/tensor/ops.py
  test/legacy_test/test_activation_op.py
Labels: contributor, HappyOpenSource Pro

#57110 [ROCM] fix GetNCCLVersion ON rocm emv
  paddle/fluid/pybind/pybind.cc
Labels: contributor

#56446 fix(fill kernel): fill kernel not enforce nan
  paddle/phi/kernels/impl/fill_kernel_impl.h
  test/legacy_test/test_fill_op.py
Labels: contributor, HappyOpenSource

#57163 fix pyyaml dependency check script
  paddle/fluid/operators/generator/CMakeLists.txt
Labels: contributor

#56909 Refine self_attention_fuse pass with removing the size restriction
  paddle/fluid/operators/fused/scaled_dp_attention.h
  paddle/fluid/operators/fused/self_dp_attention_op.cc
  test/mkldnn/test_fused_vit_attention.py
Labels: Intel, contributor

#56207 Add label_smoothing function into CrossEntropyLoss
  python/paddle/nn/functional/loss.py
  python/paddle/nn/layer/loss.py
  test/legacy_test/test_cross_entropy_loss.py
Labels: contributor

#57155 [xdoctest][task 326-329] reformat example code with google style in paddle/fluid/pybind/*
  paddle/fluid/pybind/pybind.cc
  paddle/fluid/pybind/tensor.cc
  python/paddle/base/backward.py
  python/paddle/base/compiler.py
Labels: contributor, HappyOpenSource Pro

#57203 [xdoctest][task 236] reformat example code with google style in `python/paddle/distributed/utils/launch_utils.py`
  python/paddle/distributed/utils/launch_utils.py
Labels: contributor, HappyOpenSource Pro

#57202 [xdoctest][task 237] reformat example code with google style in `python/paddle/distributed/utils/moe_utils.py`
  python/paddle/distributed/utils/moe_utils.py
Labels: contributor, HappyOpenSource Pro

#57137 [xdoctest][task 330] reformat example code with google style in python/paddle/base/data_feed_desc.py
  python/paddle/base/data_feed_desc.py
Labels: contributor, HappyOpenSource Pro

#57201 [NewIR] Modify xx_new_ir_mode into xx_pir_mode
  python/paddle/base/framework.py
  python/paddle/framework/__init__.py
  python/paddle/nn/functional/activation.py
  python/paddle/nn/functional/common.py
  python/paddle/nn/initializer/constant.py
  python/paddle/nn/initializer/xavier.py
  python/paddle/nn/layer/loss.py
  python/paddle/optimizer/optimizer.py
  python/paddle/optimizer/sgd.py
  python/paddle/static/input.py
  python/paddle/tensor/creation.py
  python/paddle/tensor/manipulation.py
  python/paddle/tensor/math.py
  python/paddle/tensor/stat.py
  test/legacy_test/test_fill_any_like_op.py
  test/legacy_test/test_full_like_op.py
Labels: contributor

#57229 modified version.cmake to use the '+' in PADDLE_VERSION
  cmake/version.cmake
Labels: contributor

#57153 [NewComm] No.1 compatiable upgrade for `class_center_sample` op
  paddle/fluid/operators/class_center_sample_op.cu
  test/legacy_test/test_class_center_sample_op.py
Labels: contributor, HappyOpenSource

#57161 [NewComm] No.3 compatiable upgrade for global_scatter op
  paddle/fluid/operators/collective/global_scatter_op.cu.cc
  test/collective/collective_global_scatter.py
  test/collective/test_collective_global_scatter.py
Labels: contributor, HappyOpenSource

#56884 修复 paddle.expand 等 API 的文档
  python/paddle/nn/layer/common.py
Labels: contributor

#56048 【Complex Op】Add complex support for trigonometric and hyperbolic functions
  paddle/phi/common/complex.h
  paddle/phi/kernels/cpu/activation_grad_kernel.cc
  paddle/phi/kernels/cpu/activation_kernel.cc
  paddle/phi/kernels/funcs/activation_functor.h
  paddle/phi/kernels/gpu/activation_grad_kernel.cu
  paddle/phi/kernels/gpu/activation_kernel.cu
  python/paddle/tensor/ops.py
  test/legacy_test/test_activation_op.py
Labels: contributor

#57252 [NewComm] No.4 compatiable upgrade for partial_allgather op
  paddle/fluid/operators/collective/partial_allgather_op.cu.cc
Labels: contributor, HappyOpenSource

#57166 [NewIR] No.12 Migrate paddle.add into pir
  python/paddle/tensor/math.py
  test/legacy_test/test_elementwise_add_op.py
Labels: contributor, HappyOpenSource

#57171 fix cc_test_old
  paddle/pir/core/parser/ir_parser.cc
  paddle/pir/core/parser/ir_parser.h
  test/cpp/pir/core/CMakeLists.txt
  test/cpp/pir/core/ir_parser_test.cc
Labels: contributor

#57251 [NewComm] No.6 compatiable upgrade for partial_send op
  paddle/fluid/operators/collective/partial_send_op.cu.cc
Labels: contributor, HappyOpenSource

#57208 [NewComm] No.5 compatiable upgrade for c_softmax_with_cross_entropy op
  paddle/fluid/operators/collective/c_softmax_with_cross_entropy_op.cu
  test/legacy_test/test_c_softmax_with_cross_entropy_op.py
Labels: contributor, HappyOpenSource

#57157 [NewIR] No.10 Migrate silu into pir
  paddle/fluid/pir/dialect/op_generator/vjp_interface_gen_op_list.py
  python/paddle/nn/functional/activation.py
  test/legacy_test/op_test.py
  test/legacy_test/test_activation_op.py
Labels: contributor, HappyOpenSource

#57159 [NewIR] No.11 Migrate cast into pir
  test/legacy_test/test_cast_op.py
Labels: contributor, HappyOpenSource

#57175 [NewIR] No.13 Migrate paddle.multiply into pir
  python/paddle/tensor/math.py
  test/legacy_test/test_elementwise_mul_op.py
Labels: contributor, HappyOpenSource

#56827 extend matmul_int8 and support matmul_with_flatten_int8
  paddle/fluid/operators/matmul_op.cc
  paddle/phi/api/yaml/legacy_ops.yaml
  paddle/phi/backends/gpu/cuda/cuda_helper.h
  paddle/phi/infermeta/binary.cc
  paddle/phi/infermeta/binary.h
  paddle/phi/kernels/autotune/auto_tune_base.h
  paddle/phi/kernels/funcs/blas/blaslt_impl.cu.h
  paddle/phi/kernels/gpu/matmul_kernel.cu
  paddle/phi/kernels/impl/matmul_kernel_impl.h
  python/paddle/tensor/linalg.py
  test/legacy_test/test_inner.py
  test/legacy_test/test_matmul_int8_op.py
  test/legacy_test/test_mul_op.py
  test/legacy_test/test_outer.py
Labels: contributor

#57123 [NewIR] No.19 Migrate paddle.reduce_max into pir
  python/paddle/tensor/math.py
  test/legacy_test/test_reduce_op.py
Labels: contributor, HappyOpenSource

#57145 [CodeStyle][ruff] update ruff v0.0.289 and black 23.9.1
  .flake8
  .pre-commit-config.yaml
  pyproject.toml
  python/paddle/distributed/auto_parallel/static/planner_v2.py
  python/paddle/distributed/auto_parallel/static/tuner/rule_based_tuner.py
  setup.py
  test/legacy_test/test_math_op_patch.py
  test/legacy_test/test_rnn_cell_api.py
Labels: contributor

#57305 [NewComm]No.7 compatiable upgrade for global_gather_op.
  paddle/fluid/operators/collective/global_gather_op.cu.cc
  test/collective/collective_global_gather.py
  test/collective/test_collective_global_gather.py
Labels: contributor, HappyOpenSource

#57215 FollowUp: Fix unnecessary synchronized memcpy in hybrid parallel training
  python/paddle/distributed/fleet/meta_optimizers/dygraph_optimizer/hybrid_parallel_optimizer.py
  python/paddle/distributed/fleet/utils/hybrid_parallel_util.py
  python/paddle/nn/clip.py
Labels: NVIDIA, contributor

#56897 【NewIR】enable dy2st new IR test 2
  test/dygraph_to_static/dygraph_to_static_util.py
  test/dygraph_to_static/test_convert_operators.py
  test/dygraph_to_static/test_declarative.py
  test/dygraph_to_static/test_decorator_transform.py
  test/dygraph_to_static/test_deepcopy.py
  test/dygraph_to_static/test_dict.py
  test/dygraph_to_static/test_drop_path.py
  test/dygraph_to_static/test_duplicate_output.py
  test/dygraph_to_static/test_fetch_feed.py
  test/dygraph_to_static/test_gradient_aggregation.py
  test/dygraph_to_static/test_grid_generator.py
  test/dygraph_to_static/test_isinstance.py
  test/dygraph_to_static/test_layer_hook.py
  test/dygraph_to_static/test_load_transformer.py
  test/dygraph_to_static/test_multi_forward.py
  test/dygraph_to_static/test_param_guard.py
Labels: contributor

#57330 [NewIR] No.33, 34 Migrate paddle.shape, paddle.numel into pir
  python/paddle/tensor/attribute.py
  python/paddle/tensor/stat.py
  test/legacy_test/test_numel_op.py
  test/legacy_test/test_shape_op.py
Labels: contributor, HappyOpenSource

#57341 [NewIR] No.35 Migrate paddle.slice into pir
  python/paddle/tensor/manipulation.py
  test/legacy_test/test_slice_op.py
Labels: contributor, HappyOpenSource

#57212 【NewIR】add share_data_op
  paddle/fluid/pir/dialect/operator/ir/ops.yaml
  paddle/fluid/pir/dialect/operator/utils/utils.cc
  paddle/phi/api/yaml/op_compat.yaml
Labels: contributor

#57359 Fix typo(unitest, unnitest->unittest)
  paddle/fluid/operators/nce_op.h
  paddle/phi/infermeta/spmd_rules/rules.h
  paddle/scripts/paddle_build.sh
  test/ir/inference/CMakeLists.txt
  test/legacy_test/test_run.py
  test/quantization/CMakeLists.txt
  tools/check_added_ut.sh
  tools/check_sequence_op.sh
Labels: contributor

#57378 [CodeStyle] rollback black to 23.3.0
  .pre-commit-config.yaml
Labels: contributor

#57277 [NewIR] No.30 Migrate paddle.matmul into pir
  python/paddle/tensor/linalg.py
  test/legacy_test/test_matmul_v2_op.py
Labels: contributor, HappyOpenSource

#57398 [CodeStyle][task 17] enable Ruff F811 rule in `python/paddle/base`
  pyproject.toml
  python/paddle/base/dygraph/base.py
  python/paddle/base/io.py
  python/paddle/base/reader.py
Labels: contributor

#57271 [PIR] op.name() == "XX" 优化为 op.isa<XXOp>()
  paddle/fluid/framework/new_executor/standalone_executor.cc
  paddle/fluid/pir/dialect/operator/ir/CMakeLists.txt
  paddle/fluid/pir/phi_kernel_adaptor/phi_kernel_util.cc
  paddle/fluid/pir/transforms/CMakeLists.txt
  paddle/fluid/pir/transforms/constant_folding_pass.cc
  paddle/fluid/pir/transforms/inplace_pass.cc
  paddle/fluid/pir/transforms/pd_op_to_kernel_pass.cc
  paddle/fluid/pybind/ir.cc
  paddle/pir/transforms/dead_code_elimination_pass.cc
  test/cpp/pir/pass/pass_manager_test.cc
  test/cpp/pir/pattern_rewrite/pattern_rewrite_test.cc
Labels: contributor

#57248 [NewIR] No.40-41 Migrate paddle.tanh and paddle.transpose into pir
  python/paddle/tensor/linalg.py
  python/paddle/tensor/math.py
  test/legacy_test/test_activation_op.py
  test/legacy_test/test_transpose_op.py
Labels: contributor, HappyOpenSource

#57400 [CodeStyle][task 15] enable Ruff PLW3301 rule
  pyproject.toml
  python/paddle/distributed/passes/ps_trainer_pass.py
  python/paddle/tensor/manipulation.py
Labels: contributor

#56238 [xdoctest][task 141] Reformat example code with google style in quantization/post_training_quantization.py
  python/paddle/static/quantization/post_training_quantization.py
Labels: contributor, HappyOpenSource Pro

#57297 [NewIR] No.14 Migrate paddle.pow into pir
  python/paddle/tensor/math.py
  test/legacy_test/test_activation_op.py
  test/legacy_test/test_elementwise_pow_op.py
Labels: contributor, HappyOpenSource

#57131 [xdoctest][task 313] reformat example code with google style in python/paddle/sparse/nn/functional/transformer.py
  python/paddle/sparse/nn/functional/transformer.py
Labels: contributor, HappyOpenSource Pro

#57138 [xdoctest][task 331] reformat example code with google style in python/paddle/base/data_feeder.py
  python/paddle/base/data_feeder.py
Labels: contributor, HappyOpenSource Pro

#57111 [xdoctest][task 171-180] reformat example code with google style in audio/*
  python/paddle/amp/auto_cast.py
  python/paddle/amp/debugging.py
  python/paddle/amp/grad_scaler.py
  python/paddle/device/__init__.py
  python/paddle/device/cuda/__init__.py
  python/paddle/profiler/profiler.py
  python/paddle/profiler/utils.py
  python/paddle/sparse/binary.py
  python/paddle/sparse/creation.py
Labels: contributor, HappyOpenSource Pro

#57376 [CodeStyle][task 20] enable ruff B011 rule in `python/paddle/base`
  pyproject.toml
  python/paddle/base/incubate/checkpoint/auto_checkpoint.py
Labels: contributor, HappyOpenSource

#57388 [CodeStyle][task 2] enable Ruff F401 rule in `python/paddle/base`
  pyproject.toml
  python/paddle/base/compiler.py
  python/paddle/base/core.py
  python/paddle/base/data_feeder.py
  python/paddle/base/device_worker.py
  python/paddle/base/dygraph/math_op_patch.py
  python/paddle/base/dygraph/tensor_patch_methods.py
  python/paddle/base/dygraph/tracer.py
  python/paddle/base/executor.py
  python/paddle/base/framework.py
  python/paddle/base/incubate/checkpoint/auto_checkpoint.py
  python/paddle/base/initializer.py
  python/paddle/base/io.py
  python/paddle/base/layer_helper.py
  python/paddle/base/layers/layer_function_generator.py
  python/paddle/base/reader.py
  python/paddle/base/trainer_desc.py
  python/paddle/base/trainer_factory.py
  python/paddle/base/variable_index.py
  python/paddle/io/reader.py
Labels: contributor, HappyOpenSource

#57244 【complex op】No.33 add complex support for sigmoid
  paddle/phi/kernels/cpu/activation_grad_kernel.cc
  paddle/phi/kernels/cpu/activation_kernel.cc
  paddle/phi/kernels/funcs/activation_functor.h
  paddle/phi/kernels/gpu/activation_grad_kernel.cu
  paddle/phi/kernels/gpu/activation_kernel.cu
  python/paddle/tensor/ops.py
  test/legacy_test/test_activation_op.py
Labels: contributor, HappyOpenSource Pro

#57405 [CodeStyle][task 12] enable Ruff UP028 rule in `python/paddle/base`
  pyproject.toml
  python/paddle/base/dygraph/base.py
  python/paddle/base/framework.py
  python/paddle/base/incubate/checkpoint/auto_checkpoint.py
  python/paddle/base/layer_helper.py
  python/paddle/dataset/cifar.py
  python/paddle/dataset/common.py
  python/paddle/io/dataloader/dataset.py
  python/paddle/nn/layer/layers.py
  python/paddle/utils/layers_utils.py
  test/legacy_test/test_lstm_cudnn_op.py
  test/rnn/rnn_numpy.py
Labels: contributor, HappyOpenSource

#57402 [CodeStyle][task 13] enable Ruff F522 rule in `python/paddle/base`
  pyproject.toml
  python/paddle/base/framework.py
Labels: contributor, HappyOpenSource

#57391 [CodeStyle][task 5] Enable Ruff PLR1701 rule in `python/paddle/` and `test/`
  pyproject.toml
  python/paddle/base/compiler.py
  python/paddle/base/executor.py
  python/paddle/base/framework.py
  python/paddle/base/layer_helper.py
  python/paddle/base/layers/layer_function_generator.py
  python/paddle/base/param_attr.py
  python/paddle/incubate/optimizer/recompute.py
  python/paddle/io/dataloader/dataloader_iter.py
  python/paddle/tensor/manipulation.py
  test/ir/inference/auto_scan_test.py
  test/legacy_test/nets.py
  test/legacy_test/test_bicubic_interp_v2_op.py
  test/legacy_test/test_bilinear_interp_v2_op.py
  test/legacy_test/test_linear_interp_v2_op.py
  test/legacy_test/test_nearest_interp_v2_op.py
  test/legacy_test/test_trilinear_interp_v2_op.py
  test/legacy_test/test_unflatten.py
Labels: contributor, HappyOpenSource

#57343 [clang-tidy] NO.29 enable `cppcoreguidelines-no-malloc`
  .clang-tidy
  paddle/fluid/framework/data_feed.cc
  paddle/fluid/framework/new_executor/workqueue/workqueue.cc
  paddle/fluid/framework/new_executor/workqueue/workqueue_utils.cc
  paddle/fluid/framework/string_array.cc
  paddle/fluid/inference/capi_exp/pd_config.cc
  paddle/fluid/memory/allocation/auto_growth_best_fit_allocator_test.cc
  paddle/fluid/memory/allocation/cpu_allocator.cc
  paddle/fluid/memory/allocation/system_allocator.cc
  paddle/fluid/operators/detection/mask_util.cc
  paddle/phi/core/enforce.cc
  paddle/phi/kernels/cpu/multiclass_nms3_kernel.cc
  paddle/phi/kernels/funcs/jit/gen_base.cc
  paddle/pir/core/op_info_impl.cc
  paddle/pir/core/utils.cc
  paddle/testing/paddle_gtest_main.cc
Labels: contributor, HappyOpenSource Pro

#57397 [CodeStyle][task 18] enable Ruff C403 rule in `python/paddle/base`
  pyproject.toml
  python/paddle/base/backward.py
Labels: contributor, HappyOpenSource

#57399 [CodeStyle][task 16] enable Ruff B010 rule in python/paddle/base
  pyproject.toml
  python/paddle/base/compiler.py
  python/paddle/base/dygraph/tensor_patch_methods.py
  python/paddle/base/framework.py
Labels: contributor, HappyOpenSource

#57395 [CodeStyle][task 19] enable Ruff UP034 rule in `python/paddle/base`
  pyproject.toml
  python/paddle/base/framework.py
Labels: contributor, HappyOpenSource

#57428 [CodeStyle][task 4] enable ruff NPY003 rule in `python/paddle/base`
  pyproject.toml
  python/paddle/hapi/dynamic_flops.py
  python/paddle/hapi/static_flops.py
  test/autograd/utils.py
  test/dygraph_to_static/test_cast.py
  test/legacy_test/gradient_checker.py
  test/legacy_test/test_fake_quantize_op.py
  test/legacy_test/test_isfinite_v2_op.py
  test/legacy_test/test_lu_op.py
  test/legacy_test/test_lu_unpack_op.py
  test/legacy_test/test_nn_functional_hot_op.py
  test/legacy_test/test_one_hot_v2_op.py
  test/legacy_test/test_overlap_add_op.py
  test/legacy_test/test_signal.py
  test/legacy_test/test_tensor.py
  test/legacy_test/test_var_base.py
  test/quantization/imperative_test_utils.py
  test/quantization/test_imperative_qat_user_defined.py
  test/xpu/test_one_hot_op_xpu.py
  test/xpu/test_one_hot_v2_op_xpu.py
Labels: contributor, HappyOpenSource

#57436 [CodeStyle][task 6] enable ruff UP018 rule in `python/paddle/base`
  pyproject.toml
  python/paddle/distributed/fleet/meta_optimizers/localsgd_optimizer.py
  python/paddle/distributed/fleet/meta_optimizers/sharding/utils.py
  python/paddle/distributed/fleet/meta_optimizers/sharding_optimizer.py
  python/paddle/distributed/fleet/utils/pp_parallel_adaptor.py
  python/paddle/distributed/passes/auto_parallel_gradient_merge.py
  python/paddle/hapi/dynamic_flops.py
  python/paddle/incubate/autograd/utils.py
  python/paddle/incubate/optimizer/gradient_merge.py
  python/paddle/incubate/optimizer/pipeline.py
  python/paddle/nn/functional/loss.py
  python/paddle/static/nn/metric.py
  test/cinn/ops/test_fill_constant_op.py
  test/collective/fleet/parallel_dygraph_transformer.py
  test/collective/fleet/test_dgc_op.py
  test/dygraph_to_static/transformer_dygraph_model.py
  test/legacy_test/fleet_heter_ps_training.py
  test/legacy_test/test_fake_quantize_op.py
  test/legacy_test/test_generate_mask_labels_op.py
  test/legacy_test/test_imperative_transformer_sorted_gradient.py
  test/legacy_test/test_progressbar.py
  test/legacy_test/test_tensor_fill_.py
Labels: contributor, HappyOpenSource

#57421 [Add] bad statement check
  tools/sampcd_processor.py
  tools/sampcd_processor_utils.py
  tools/test_sampcd_processor.py
Labels: contributor

#57437 [xdoctest] reformat example code with google style in No.356
  python/paddle/ir/core.py
Labels: contributor, HappyOpenSource Pro

#57120 【NewIR】enable dy2stat newIR_test 3
  test/dygraph_to_static/test_inplace_assign.py
  test/dygraph_to_static/test_mnist.py
  test/dygraph_to_static/test_partial_program.py
  test/dygraph_to_static/test_print.py
  test/dygraph_to_static/test_ptb_lm.py
  test/dygraph_to_static/test_reinforcement_learning.py
  test/dygraph_to_static/test_rollback.py
  test/dygraph_to_static/test_save_inference_model.py
  test/dygraph_to_static/test_save_load.py
  test/dygraph_to_static/test_sentiment.py
  test/dygraph_to_static/test_spec_names.py
  test/dygraph_to_static/test_tensor_methods.py
  test/dygraph_to_static/test_tensor_shape.py
  test/dygraph_to_static/test_transformer.py
  test/dygraph_to_static/test_typehint.py
  test/dygraph_to_static/test_typing.py
  test/dygraph_to_static/test_unuseful_inputs.py
Labels: contributor

#57442 fix example code in celoss (complement pr 56207)
  python/paddle/nn/functional/loss.py
  python/paddle/nn/layer/loss.py
Labels: contributor

#57113 [XPU] Add fast_layternorm + leaky_relu fusion
  paddle/fluid/framework/ir/CMakeLists.txt
  paddle/fluid/framework/ir/xpu/layer_norm_act_xpu_fuse_pass.cc
  paddle/fluid/inference/api/paddle_pass_builder.cc
  paddle/phi/api/yaml/fused_ops.yaml
  paddle/phi/backends/xpu/xpu2_op_list.cc
  paddle/phi/infermeta/fusion.cc
  paddle/phi/infermeta/fusion.h
  paddle/phi/kernels/fusion/xpu/layer_norm_act_xpu_kernel.cc
  paddle/phi/kernels/xpu/plugin/include/xpu/plugin.h
  paddle/phi/kernels/xpu/plugin/src/kernel/kunlun2cpp/layer_norm_act_fusion.xpu
  paddle/phi/kernels/xpu/plugin/src/wrapper/layer_norm_act_fusion.cpp
  test/ir/inference/test_xpu_layer_norm_act_fuse_pass.py
Labels: contributor

#56926 修复 paddle.argmax 等 API 的文档
  python/paddle/device/__init__.py
  python/paddle/hapi/callbacks.py
  python/paddle/nn/layer/container.py
  python/paddle/nn/layer/transformer.py
  python/paddle/tensor/creation.py
Labels: contributor, HappyOpenSource

#57441 【newIR】delete share_buffer op in newIR
  paddle/fluid/pir/dialect/operator/ir/ops.yaml
Labels: contributor

#57460 [xdoctest] reformat example code with google style in No.92
  python/paddle/nn/clip.py
Labels: contributor, HappyOpenSource Pro

#57440 [xdoctest] reformat example code with google style No.354
  python/setup.py.in
  setup.py
Labels: contributor, HappyOpenSource Pro

#57379 [CodeStyle][task 11] enable Ruff F403 rule in `python/paddle/base/layers/__init__.py`
  pyproject.toml
  python/paddle/base/__init__.py
  python/paddle/base/dygraph/__init__.py
  python/paddle/base/layers/__init__.py
  python/paddle/nn/functional/pooling.py
Labels: contributor, HappyOpenSource

#57031 Add a config to set TensorRT optimization level
  paddle/fluid/inference/analysis/argument.h
  paddle/fluid/inference/analysis/ir_pass_manager.cc
  paddle/fluid/inference/analysis/ir_passes/tensorrt_subgraph_pass.cc
  paddle/fluid/inference/api/analysis_config.cc
  paddle/fluid/inference/api/analysis_predictor.cc
  paddle/fluid/inference/api/paddle_analysis_config.h
  paddle/fluid/inference/tensorrt/engine.cc
  paddle/fluid/inference/tensorrt/engine.h
  paddle/fluid/pybind/inference_api.cc
  test/ir/inference/CMakeLists.txt
  test/ir/inference/test_trt_optimization_level.py
Labels: NVIDIA, contributor

#57401 [CodeStyle][task 14] enable Ruff PLR1722 rule in `python/paddle/base`
  pyproject.toml
  python/paddle/base/device_worker.py
Labels: contributor, HappyOpenSource

#57483 [clang-tidy] NO.32 clang-analyzer-deadcode.DeadStores
  .clang-tidy
  paddle/fluid/distributed/collective/reducer.cc
  paddle/fluid/framework/data_set.cc
  paddle/fluid/framework/ir/fuse_adamw_op_pass.cc
  paddle/fluid/framework/ir/fuse_bn_act_pass.cc
  paddle/fluid/framework/ir/fuse_bn_add_act_pass.cc
  paddle/fluid/framework/ir/fuse_gemm_epilogue_pass.cc
  paddle/fluid/framework/ir/fuse_relu_depthwise_conv_pass.cc
  paddle/fluid/framework/ir/fused_attention_pass.cc
  paddle/fluid/framework/ir/transfer_layout_elim_pass.cc
  paddle/fluid/framework/parallel_executor.cc
  paddle/fluid/imperative/layout_autotune.cc
  paddle/fluid/memory/allocation/buddy_allocator.cc
  paddle/fluid/platform/gen_comm_id_helper.cc
  paddle/phi/api/lib/tensor_method.cc
  paddle/phi/core/distributed/store/tcp_store.cc
  paddle/phi/kernels/funcs/gpc.cc
  paddle/pir/core/utils.cc
Labels: contributor, HappyOpenSource Pro

#57512 [Docathon] Fix NO.6 API Label
  python/paddle/incubate/optimizer/lars_momentum.py
  python/paddle/incubate/optimizer/lbfgs.py
  python/paddle/nn/layer/rnn.py
  python/paddle/optimizer/adadelta.py
  python/paddle/optimizer/adam.py
  python/paddle/optimizer/adamax.py
  python/paddle/optimizer/lbfgs.py
  python/paddle/optimizer/momentum.py
  python/paddle/optimizer/optimizer.py
  python/paddle/optimizer/rmsprop.py
  python/paddle/optimizer/sgd.py
  python/paddle/static/nn/common.py
  python/paddle/static/nn/loss.py
  python/paddle/static/nn/sequence_lod.py
Labels: contributor, HappyOpenSource

#56837 赛题八：paddleviz能力扩展——Tensor信息展示
  paddle/fluid/eager/accumulation/accumulation_node.cc
  paddle/fluid/eager/api/manual/eager_manual/nodes/add_n_node.cc
  paddle/fluid/eager/api/manual/eager_manual/nodes/conv2d_nodes.cc
  paddle/fluid/eager/api/manual/eager_manual/nodes/multiply_node.cc
  paddle/fluid/eager/api/manual/eager_manual/nodes/sync_batch_norm_node.cc
  paddle/fluid/eager/auto_code_generator/generator/eager_gen.py
  paddle/fluid/eager/grad_node_info.cc
  paddle/fluid/eager/grad_node_info.h
  paddle/fluid/eager/utils.h
  paddle/fluid/pybind/eager_utils.h
  paddle/fluid/pybind/pybind.cc
Labels: contributor

#57314 fix parse string
  paddle/pir/core/ir_printer.cc
  paddle/pir/core/parser/ir_parser.cc
  paddle/pir/core/parser/ir_parser.h
  paddle/pir/core/parser/lexer.cc
  paddle/pir/core/parser/lexer.h
  paddle/pir/core/parser/token.h
  test/cpp/pir/core/TestParserText.txt
  test/cpp/pir/core/add_dialect_parser_test.cc
  test/cpp/pir/core/ir_parser_test.cc
Labels: contributor

#56696 Support control flow for static build [Step 2: support conditional_block]
  paddle/fluid/framework/new_executor/interpreter/interpreter_util.cc
  paddle/fluid/framework/new_executor/interpreter/static_build.cc
  paddle/fluid/framework/new_executor/interpreter/static_build.h
  paddle/fluid/framework/new_executor/interpreter_base_impl.h
  paddle/fluid/framework/new_executor/interpretercore.cc
  paddle/fluid/framework/new_executor/interpretercore.h
  paddle/fluid/framework/new_executor/new_ir_interpreter.cc
  paddle/fluid/framework/new_executor/new_ir_interpreter.h
  paddle/fluid/framework/new_executor/program_interpreter.cc
  paddle/fluid/framework/new_executor/program_interpreter.h
  paddle/phi/kernels/gpu/lamb_kernel.cu
  test/legacy_test/CMakeLists.txt
  test/white_list/new_ir_op_test_white_list
Labels: contributor

#57424 [NewComm] No.10 compatiable upgrade for distributed_fused_lamb op
  paddle/fluid/operators/optimizers/distributed_fused_lamb_op.cu
  paddle/phi/core/distributed/nccl_comm_context.cc
  paddle/phi/core/distributed/nccl_comm_context.h
  test/legacy_test/CMakeLists.txt
  test/legacy_test/distributed_fused_lamb_test_base.py
  test/legacy_test/test_distributed_fused_lamb_op_with_clip.py
  test/legacy_test/test_distributed_fused_lamb_op_with_gradient_merge.py
Labels: contributor, HappyOpenSource

#57548 [NewComm] No.2 compatiable upgrade for partial_recv op
  paddle/fluid/operators/collective/partial_recv_op.cu.cc
Labels: contributor, HappyOpenSource

#57413 [CodeStyle][task 39] enable isort in `python/paddle/base` (part1)
  pyproject.toml
  python/paddle/base/backward.py
  python/paddle/base/compiler.py
  python/paddle/base/data_feed_desc.py
  python/paddle/base/data_feeder.py
  python/paddle/base/dataset.py
  python/paddle/base/default_scope_funcs.py
  python/paddle/base/dygraph/base.py
  python/paddle/base/dygraph/math_op_patch.py
  python/paddle/base/dygraph/tensor_patch_methods.py
  python/paddle/base/dygraph/tracer.py
  python/paddle/base/dygraph_utils.py
  python/paddle/base/executor.py
  python/paddle/base/incubate/checkpoint/auto_checkpoint.py
  python/paddle/base/initializer.py
  python/paddle/base/io.py
  python/paddle/base/layer_helper.py
  python/paddle/base/layer_helper_base.py
  python/paddle/base/layers/io.py
  python/paddle/base/layers/layer_function_generator.py
  python/paddle/base/layers/math_op_patch.py
  python/paddle/base/lod_tensor.py
  python/paddle/base/multiprocess_utils.py
  python/paddle/base/param_attr.py
  python/paddle/base/reader.py
  python/paddle/base/trainer_desc.py
  python/paddle/base/trainer_factory.py
  python/paddle/base/unique_name.py
  python/paddle/base/variable_index.py
  python/paddle/base/wrapped_decorator.py
Labels: contributor, HappyOpenSource

#57560 [NewComm] No.9 compatiable upgrade for fused_attention op
  paddle/fluid/operators/fused/fused_attention_utils.h
  test/legacy_test/test_fused_attention_op.py
Labels: contributor, HappyOpenSource

#57501 [CodeStyle][task 11] enable Ruff F403 rule in `python/paddle/base/__init__.py`
  pyproject.toml
  python/paddle/base/__init__.py
  python/paddle/base/core.py
  python/paddle/base/dygraph/__init__.py
  python/paddle/base/io.py
Labels: contributor, HappyOpenSource

#57544 [Custom Device] change the dlopen flag of custom device dylibs
  paddle/fluid/platform/init.cc
Labels: contributor

#57522 [clang-tidy] NO.23 bugprone-branch-clone
  .clang-tidy
  paddle/fluid/distributed/collective/processgroup_comm_utils.cc
  paddle/fluid/framework/details/fetch_op_handle.cc
  paddle/fluid/framework/downpour_worker.cc
  paddle/fluid/framework/executor_cache.cc
  paddle/fluid/framework/io/fs.cc
  paddle/fluid/framework/ir/constant_folding_pass.cc
  paddle/fluid/framework/ir/mkldnn/quant_dequant_mkldnn_pass.cc
  paddle/fluid/framework/new_executor/garbage_collector/event_garbage_collector.cc
  paddle/fluid/framework/new_executor/garbage_collector/fast_garbage_collector.cc
  paddle/fluid/framework/new_executor/interpreter/static_build.cc
  paddle/fluid/framework/new_executor/new_ir_interpreter.cc
  paddle/fluid/framework/new_executor/program_interpreter.cc
  paddle/fluid/framework/operator.cc
  paddle/fluid/framework/parallel_executor.cc
  paddle/fluid/framework/tensor_util.cc
  paddle/fluid/framework/var_desc.cc
  paddle/fluid/inference/api/analysis_predictor.cc
  paddle/fluid/memory/memcpy.cc
  paddle/fluid/operators/batch_norm_op.cc
  paddle/fluid/operators/data_norm_op.cc
  paddle/fluid/operators/detection/multiclass_nms_op.cc
  paddle/fluid/operators/fused/fused_bn_activation_op.cc
  paddle/fluid/operators/fused/fused_bn_add_activation_op.cc
  paddle/fluid/operators/fused/mkldnn/fusion_gru_mkldnn_op.cc
  paddle/fluid/operators/fused/mkldnn/fusion_lstm_mkldnn_op.cc
  paddle/fluid/operators/fused/mkldnn/multi_gru_mkldnn_op.cc
  paddle/fluid/operators/inplace_abn_op.cc
  paddle/fluid/operators/mkldnn/fc_mkldnn_op.cc
  paddle/fluid/operators/mkldnn/reshape_mkldnn_op.cc
  paddle/fluid/operators/reader/buffered_reader.cc
  paddle/fluid/operators/sum_op.cc
  paddle/fluid/pir/phi_kernel_adaptor/phi_kernel_util.cc
  paddle/fluid/platform/place.cc
  paddle/fluid/prim/api/manual_prim/static_prim_api.cc
  paddle/fluid/pybind/eager_method.cc
  paddle/fluid/pybind/eager_properties.cc
  paddle/fluid/pybind/eager_utils.cc
  paddle/fluid/pybind/inference_api.cc
  paddle/fluid/pybind/op_function_common.cc
  paddle/phi/core/compat/convert_utils.cc
  paddle/phi/core/kernel_factory.cc
  paddle/phi/infermeta/unary.cc
  paddle/phi/kernels/cpu/diagonal_grad_kernel.cc
  paddle/phi/kernels/cpu/generate_proposals_kernel.cc
  paddle/phi/kernels/cpu/send_ue_recv_grad_kernel.cc
  paddle/phi/kernels/funcs/vol2col.cc
Labels: contributor, HappyOpenSource Pro

#57562 [PIR] No.28 Migrate paddle.gather_nd into pir
  python/paddle/tensor/manipulation.py
  test/legacy_test/test_gather_nd_op.py
Labels: contributor

#57607 [CodeStyle][task 23] enable Ruff PLR0402 rule in `python/paddle/base`
  pyproject.toml
  python/paddle/base/dygraph/tensor_patch_methods.py
Labels: contributor, HappyOpenSource

#57301 [xdoctest] reformat example code with google style in 211,281,308,323
  paddle/fluid/pybind/imperative.cc
  python/paddle/distributed/communication/stream/send.py
  python/paddle/distributed/io.py
  python/paddle/tensor/random.py
Labels: contributor, HappyOpenSource Pro

#57066 [GLCC]Part-3: Support jit.save and jit.load for pylayer op
  paddle/fluid/framework/prune.cc
  python/paddle/jit/dy2static/py_layer.py
  python/paddle/static/io.py
  python/paddle/static/nn/static_pylayer.py
  test/dygraph_to_static/test_pylayer.py
  test/legacy_test/test_jit_save_load.py
  test/legacy_test/test_program_prune_backward.py
  test/legacy_test/test_prune.py
  test/legacy_test/test_static_pylayer.py
Labels: contributor

#57564 [NewComm] No.8 compatiable upgrade for fused_multi_transformer op
  paddle/fluid/operators/fused/fused_multi_transformer_op.cu.h
  test/legacy_test/test_fused_multi_transformer_op.py
Labels: contributor, HappyOpenSource
