Repository PaddlePaddle/Paddle, pull requests merged in 2024-08, with the labels that each got.

#66774 【Error Message BUAA】add error description for few files
  paddle/cinn/ir/schedule/schedule_desc.cc
  test/cpp/phi/api/test_phi_tensor.cc
  test/cpp/phi/core/test_dense_tensor.cc
Labels: contributor, HappyOpenSource Pro

#66816 [Fix PIR Unittest] fix pir ut (`test_sequence_conv_op_xpu,test_while_op_xpu`)
  test/xpu/test_sequence_conv_op_xpu.py
  test/xpu/test_while_op_xpu.py
Labels: contributor

#66771 [Typing][C-52] Add type annotations for `python/paddle/distributed/fleet/utils/__init__.py`
  python/paddle/distributed/fleet/utils/__init__.py
Labels: PaddlePaddle Hackathon, contributor

#66609 【Infer Symbolic Shape BUAA No.76】Add mean_all op
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/unary_infer_sym.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/unary_infer_sym.h
  paddle/phi/ops/yaml/ops.yaml
  test/legacy_test/test_mean_op.py
Labels: contributor, HappyOpenSource Pro

#66838 【Infer Symbolic Shape BUAA No.6】Add row_conv op
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/same_operands_result.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/same_operands_result.h
  paddle/phi/ops/yaml/legacy/static_ops.yaml
Labels: contributor, HappyOpenSource Pro

#66762 【Infer Symbolic Shape BUAA No.55,56,57,58】Add i0, i0e, i1, i1e op
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/same_operands_result.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/same_operands_result.h
  paddle/phi/ops/yaml/ops.yaml
Labels: contributor, HappyOpenSource Pro

#66551 【Error Message BUAA】fix error in 5 files.
  paddle/cinn/hlir/framework/pir/op_lowering_impl.cc
  paddle/cinn/operator_fusion/utils.h
  paddle/fluid/framework/fleet/fleet_wrapper.cc
  paddle/fluid/framework/fleet/heter_ps/heter_comm_kernel.cu
  paddle/fluid/framework/ir/trt_remove_amp_strategy_op_pass.cc
Labels: contributor, HappyOpenSource Pro

#66615 【Error Message No.35 BUAA】Update error massage of test\cpp\inference\api\xpu_runtime_config_resnet50_test.cc & test\cpp\inference\test_helper.h & test\deprecated\cpp\inference\api\analyzer_vis_tester.cc
  test/cpp/inference/api/xpu_runtime_config_resnet50_test.cc
  test/cpp/inference/test_helper.h
  test/deprecated/cpp/inference/api/analyzer_vis_tester.cc
Labels: contributor, HappyOpenSource Pro

#66775 【Error Message No. 35 BUAA】broadcast.cc and sort.cc
  paddle/cinn/hlir/op/broadcast.cc
  paddle/cinn/hlir/op/contrib/sort.cc
Labels: contributor, HappyOpenSource Pro

#66830 【Error Message No. 35 BUAA】lowered_func.cc & ir_operators.cc&vectorize_loops.cc
  paddle/cinn/ir/lowered_func.cc
  paddle/cinn/ir/op/ir_operators.cc
  paddle/cinn/optim/vectorize_loops.cc
Labels: contributor, HappyOpenSource Pro

#66753 【Error Message No. 333,334,335,336,337 BUAA】解决了报错信息优化任务中的 333-337
  paddle/cinn/optim/cast_bool_to_int8.cc
  paddle/cinn/optim/fold_cinn_call_arguments.cc
  paddle/cinn/optim/insert_debug_log_callee.cc
  paddle/cinn/optim/optimize.cc
  paddle/cinn/optim/replace_call_with_expr.cc
Labels: contributor, HappyOpenSource Pro

#66872 【Error Message No.363 BUAA】Update error massage of paddle\fluid\framework\fleet\fleet_wrapper.h and other 3 files
  paddle/fluid/framework/fleet/fleet_wrapper.h
  paddle/fluid/framework/fleet/heter_ps/heter_comm.h
  paddle/fluid/framework/fleet/heter_ps/heter_resource.cc
  paddle/fluid/framework/io/fs.cc
Labels: contributor, HappyOpenSource Pro

#66832 【Error Message No.349 BUAA】Update error massage of paddle\fluid\distributed\common\chunk_allocator.h and other 3 files
  paddle/fluid/distributed/common/chunk_allocator.h
  paddle/fluid/distributed/ps/service/brpc_ps_client.cc
  paddle/fluid/distributed/ps/service/brpc_ps_client.h
  paddle/fluid/distributed/ps/service/ps_service/service.cc
Labels: contributor, HappyOpenSource Pro

#66084 Fused MoE Support
  paddle/phi/infermeta/multiary.cc
  paddle/phi/infermeta/multiary.h
  paddle/phi/kernels/CMakeLists.txt
  paddle/phi/kernels/fusion/cutlass/cutlass_extensions/ft_gemm_configs.h
  paddle/phi/kernels/fusion/cutlass/cutlass_extensions/gemm/kernel/gemm_moe_problem_visitor.h
  paddle/phi/kernels/fusion/cutlass/cutlass_extensions/gemm/kernel/moe_problem_visitor.h
  paddle/phi/kernels/fusion/cutlass/cutlass_kernels/moe_gemm/fused_moe_cutlass_kernel.h
  paddle/phi/kernels/fusion/cutlass/cutlass_kernels/moe_gemm/fused_moe_gemm_kernels.cu
  paddle/phi/kernels/fusion/cutlass/cutlass_kernels/moe_gemm/fused_moe_gemm_kernels.h
  paddle/phi/kernels/fusion/cutlass/cutlass_kernels/moe_gemm/fused_moe_gemm_kernels_template.h
  paddle/phi/kernels/fusion/cutlass/fused_moe_kernel.cu
  paddle/phi/kernels/fusion/cutlass/gemm_epilogue/gemm_epilogue_util.h
  paddle/phi/kernels/fusion/cutlass/moe/fused_moe_helper.h
  paddle/phi/kernels/fusion/cutlass/moe/fused_moe_imp_op.h
  paddle/phi/kernels/fusion/cutlass/moe/fused_moe_op.h
  paddle/phi/kernels/fusion/cutlass/moe/moe_cutlass_kernel.h
  paddle/phi/kernels/fusion/cutlass/moe_kernel.cu
  paddle/phi/kernels/fusion/gpu/fused_multi_transformer_helper.cu.h
  paddle/phi/kernels/fusion/gpu/mmha_util.cu.h
  paddle/phi/ops/yaml/fused_ops.yaml
  python/paddle/incubate/nn/functional/__init__.py
  python/paddle/incubate/nn/functional/fused_ec_moe.py
  python/paddle/incubate/nn/functional/fused_moe.py
  test/legacy_test/test_fused_moe_op.py
Labels: contributor

#66580 【Infer Symbolic Shape BUAA No.37】Add FakeChannelWiseDequantizeMaxAbs operator for CINN compiler
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/multiary_infer_sym.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/multiary_infer_sym.h
  paddle/phi/ops/yaml/ops.yaml
Labels: contributor, HappyOpenSource Pro

#66612 【Infer Symbolic Shape BUAA No.38】Add FakeChannelWiseQuantizeAbsMax operator support for CINN compiler
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/unary_infer_sym.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/unary_infer_sym.h
  paddle/phi/ops/yaml/ops.yaml
Labels: contributor, HappyOpenSource Pro

#66856 [Docathon][Add API Legend No.58 BUAA] 给 hstack 函数补充了英文版图例介绍，此前对应的中文版本已成功合入
  python/paddle/tensor/manipulation.py
Labels: contributor, HappyOpenSource Pro

#66719 【Error Message BUAA No. 32】 channel.h,archive.h,fleet/heter_ps/heter_comm_inl.h
  paddle/fluid/framework/archive.h
  paddle/fluid/framework/channel.h
  paddle/fluid/framework/fleet/heter_ps/heter_comm_inl.h
Labels: contributor, HappyOpenSource Pro

#66702 【Error Message BUAA No. 87， 102】
  paddle/cinn/hlir/op/contrib/triangular_solve.cc
  test/cpp/eager/task_tests/tensor_utils_test.cc
Labels: contributor, HappyOpenSource Pro

#66548 【Error Message BUAA No. 58】 paddle\fluid\inference\tensorrt\plugin\generic_plugin.cu
  paddle/fluid/inference/tensorrt/plugin/generic_plugin.cu
Labels: contributor, HappyOpenSource Pro

#66780 【Error Message No. 371,372,373,374,375 BUAA】解决了报错信息优化任务中的 371-375
  paddle/fluid/inference/tensorrt/convert/op_converter.h
  paddle/fluid/inference/tensorrt/convert/pool2d_op.cc
  paddle/fluid/inference/tensorrt/convert/pool3d_op.cc
  paddle/fluid/memory/malloc.h
Labels: contributor, HappyOpenSource Pro

#66709 [Fix PIR Unittest] fix pir ut in test/legacy_test/(`test_nadam_op,test_asgd_op`).py
  test/legacy_test/test_asgd_op.py
  test/legacy_test/test_nadam_op.py
Labels: contributor

#66857 【Error Message No. 35 BUAA】gather_nd.cc & one_hot.cc & dot_lang.cc
  paddle/cinn/hlir/op/contrib/gather_nd.cc
  paddle/cinn/hlir/op/contrib/one_hot.cc
  paddle/cinn/utils/dot_lang.cc
Labels: contributor, HappyOpenSource Pro

#66515 Migrate collective_helper [fluid_ops]
  paddle/fluid/platform/collective_helper.cc
  paddle/fluid/platform/collective_helper.h
  paddle/fluid/platform/device/gpu/gpu_resource_pool.cc
  paddle/fluid/platform/device/gpu/gpu_resource_pool.h
  paddle/fluid/platform/device/gpu/nccl_helper.h
  paddle/phi/core/CMakeLists.txt
  paddle/phi/core/platform/CMakeLists.txt
  paddle/phi/core/platform/collective_helper.cc
  paddle/phi/core/platform/collective_helper.h
  paddle/phi/core/platform/device/gpu/gpu_resource_pool.cc
  paddle/phi/core/platform/device/gpu/gpu_resource_pool.h
Labels: contributor, HappyOpenSource

#66467 【Fix PIR Unittest No.8 BUAA】Fix some test case in PIR
  python/paddle/base/reader.py
  python/paddle/distributed/fleet/dataset/dataset.py
  python/paddle/nn/functional/loss.py
  test/deprecated/legacy_test/CMakeLists.txt
  test/deprecated/legacy_test/test_dataset_dataloader_deprecated.py
Labels: contributor, HappyOpenSource Pro

#66625 【Infer Symbolic Shape BUAA No.34/69/88/99/104】Add 5 Ops.
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/same_operands_result.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/same_operands_result.h
  paddle/phi/ops/yaml/ops.yaml
Labels: contributor, HappyOpenSource Pro

#66792 [Typing][C-116,C-117] Add type annotations for "paddle/geometric/*"
  python/paddle/geometric/reindex.py
  python/paddle/geometric/sampling/neighbors.py
Labels: contributor, HappyOpenSource

#66876 【Error Message No.354 BUAA】Update error massage of paddle/fluid/distributed/ps/table/ctr_accessor.cc and other 3 files
  paddle/fluid/distributed/ps/table/ctr_accessor.cc
  paddle/fluid/distributed/ps/table/ctr_double_accessor.cc
  paddle/fluid/distributed/ps/table/ctr_dymf_accessor.cc
  paddle/fluid/distributed/ps/table/sparse_accessor.cc
Labels: contributor, HappyOpenSource Pro

#66738 [PIR] Refactor pir `GetNameMap` and assert `value` unique
  paddle/fluid/eager/to_static/run_program_op_node.h
  paddle/fluid/pir/utils/name_analysis.h
  paddle/fluid/pybind/pir.cc
  python/paddle/jit/dy2static/pir_partial_program.py
Labels: contributor

#66804 【Error Message No. 27 No. 28 No.11 BUAA】rewrite error message
  paddle/cinn/adt/igroup.h
  paddle/cinn/adt/naive_bidirection_equation_generator.cc
  paddle/cinn/lang/lower_impl.h
  paddle/cinn/operator_fusion/backend/pattern_fuser.cc
  paddle/cinn/optim/check_tensor_buffer_map.cc
  paddle/cinn/optim/lower_intrin.cc
Labels: contributor, HappyOpenSource Pro

#66862 [Typing][B-52] Add type annotations for `python/paddle/onnx/export.py`
  python/paddle/jit/api.py
  python/paddle/onnx/export.py
Labels: contributor, HappyOpenSource

#66884 [Typing] 修复标注类型 `ReduceOp` to `_ReduceOp`
  python/paddle/distributed/communication/all_reduce.py
Labels: PaddlePaddle Hackathon, contributor

#66651 [Inference] cublaslt gemm algo search code optimization When the shape exceeds the maximum in cache file
  paddle/phi/kernels/funcs/blas/blaslt_gemm_search.h
Labels: contributor

#66675 【Error Message BUAA No. 16,17】 将报错信息修改为 PADDLE_ENFORCE_EQ 的形式
  test/cpp/eager/task_tests/eager_utils_test.cc
  test/cpp/pir/cinn/build_cinn_pass_test.cc
Labels: contributor, HappyOpenSource Pro

#66844 【Error Message No. 22,23,25-27,67 BUAA】 change CHECK_ into PADDLE_ENFORCE_
  paddle/fluid/framework/barrier.h
  paddle/fluid/framework/dist_multi_trainer.cc
  paddle/fluid/framework/fleet/ps_gpu_wrapper.cc
  paddle/fluid/framework/ir/auto_mixed_precision_pass.cc
  paddle/fluid/framework/ir/identity_op_clean_pass.cc
  paddle/fluid/framework/ir/trt_support_nhwc_pass.cc
  test/deprecated/cpp/inference/api/analysis_predictor_tester.cc
Labels: contributor, HappyOpenSource Pro

#66794 【Error Message BUAA】add error description for few files
  paddle/cinn/common/cinn_value.cc
  paddle/cinn/common/common.h
  paddle/cinn/ir/schedule_block_graph.cc
  paddle/cinn/ir/utils/ir_copy.cc
  paddle/cinn/ir/utils/ir_nodes_collector.cc
  paddle/cinn/ir/utils/ir_replace.cc
Labels: contributor, HappyOpenSource Pro

#66869 【Error Message BUAA No.35】fix error message
  paddle/cinn/backends/llvm/llvm_util.cc
  paddle/cinn/backends/llvm/llvm_util.h
  paddle/cinn/common/cas.h
  paddle/cinn/ir/schedule/factorize_reduction.h
  paddle/cinn/lang/builtin.cc
  paddle/cinn/lang/builtin.h
  paddle/cinn/lang/compute.cc
  paddle/cinn/lang/compute.h
  paddle/cinn/operator_fusion/policy/relative_judge_policy.cc
  paddle/cinn/optim/lower_function_call_bind_vars.cc
  paddle/cinn/optim/lower_function_call_bind_vars.h
  paddle/cinn/optim/map_extern_call.cc
  paddle/cinn/optim/map_extern_call.h
  paddle/cinn/optim/remove_schedule_block.cc
  paddle/cinn/optim/remove_schedule_block.h
  paddle/cinn/optim/resize_buffer.cc
  paddle/cinn/optim/resize_buffer.h
  paddle/cinn/pybind/ir/ir_context.h
  paddle/fluid/distributed/ps/table/memory_dense_table.cc
  paddle/fluid/distributed/ps/table/memory_dense_table.h
Labels: contributor, HappyOpenSource Pro

#66860 【Error Message BUAA No.35】fix error message
  paddle/cinn/common/broadcast_tree.cc
  paddle/cinn/ir/schedule/impl/compute_location.cc
  paddle/cinn/runtime/cpu/host_intrinsics.cc
  paddle/fluid/distributed/ps/service/ps_graph_client.cc
Labels: contributor, HappyOpenSource Pro

#66788 【Error Message No. 11 No. 23 No.28 BUAA】rewrite error message
  paddle/cinn/adt/generate_map_expr.cc
  paddle/cinn/adt/inline_translator.h
  paddle/cinn/hlir/op/contrib/argmax.cc
  paddle/cinn/hlir/op/contrib/argmin.cc
  paddle/cinn/hlir/op/contrib/lookup_table.cc
  paddle/cinn/hlir/op/reduction.cc
  paddle/cinn/optim/eliminate_common_global_memory_read.cc
Labels: contributor, HappyOpenSource Pro

#66909 Replace phi::errors [fluid_ops] part19
  paddle/fluid/pir/drr/src/attr_type_uilts.h
  paddle/fluid/pir/drr/src/ir_operation_factory.cc
  paddle/fluid/pir/drr/src/ir_operation_factory.h
  paddle/fluid/pir/drr/src/match_context_impl.h
  paddle/fluid/pir/drr/src/pattern_graph.cc
  paddle/fluid/pir/drr/src/rewrite_pattern.cc
  paddle/fluid/pir/serialize_deserialize/include/deserialize_utils.h
  paddle/fluid/pir/serialize_deserialize/include/serialize_utils.h
  paddle/fluid/pir/serialize_deserialize/src/patch_util.cc
  paddle/fluid/pir/serialize_deserialize/src/save_load_parameters.cc
  paddle/fluid/pir/serialize_deserialize/src/schema.cc
  paddle/fluid/pir/transforms/general/auto_mixed_precision_pass.cc
  paddle/fluid/pir/transforms/general/constant_folding_pass.cc
  paddle/fluid/pir/transforms/general/delete_quant_dequant_linear_op_pass.cc
  paddle/fluid/pir/transforms/general/delete_weight_dequant_linear_op_pass.cc
  paddle/fluid/pir/transforms/general/inplace_pass.cc
  paddle/fluid/pir/transforms/general/params_sync_among_devices_pass.cc
  paddle/fluid/pir/transforms/general/remove_shadow_feed_pass.cc
  paddle/fluid/pir/transforms/onednn/elementwise_act_onednn_fuse_pass.cc
  paddle/fluid/pir/transforms/pd_op_to_kernel_pass.cc
  paddle/fluid/pir/transforms/sub_graph_detector.cc
  paddle/fluid/pir/transforms/sub_graph_extract_pass.cc
  paddle/fluid/pir/utils/general_functions.cc
Labels: contributor, HappyOpenSource

#66643 【Infer Symbolic Shape BUAA No.33】Add empty_like op
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/same_operands_result.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/same_operands_result.h
  paddle/phi/ops/yaml/ops.yaml
Labels: contributor, HappyOpenSource Pro

#66802 【Error Message No. 27 No. 28 No.11 No.15 BUAA】rewrite error message
  paddle/cinn/adt/get_sub_reshape_dim_ranges.cc
  paddle/cinn/adt/naive_op_equation_context.cc
  paddle/cinn/common/cuda_test_helper.cc
  paddle/cinn/common/dim_expr_converter.cc
  paddle/cinn/lang/lower_tensor_group.cc
  paddle/cinn/optim/trans_buffer_with_dynamic_shape.cc
Labels: contributor, HappyOpenSource Pro

#66908 Replace phi::errors [fluid_ops] part18
  paddle/fluid/imperative/all_reduce.cc
  paddle/fluid/imperative/amp_auto_cast.cc
  paddle/fluid/imperative/basic_engine.cc
  paddle/fluid/imperative/bkcl_context.cc
  paddle/fluid/imperative/data_loader.cc
  paddle/fluid/imperative/dygraph_grad_maker.h
  paddle/fluid/imperative/execution_context.h
  paddle/fluid/imperative/gloo_context.cc
  paddle/fluid/imperative/gradient_accumulator.cc
  paddle/fluid/imperative/gradient_accumulator.h
  paddle/fluid/imperative/heter_ccl_context.cc
  paddle/fluid/imperative/infer_shape_context.h
  paddle/fluid/imperative/infer_var_type_context.h
  paddle/fluid/imperative/layer.cc
  paddle/fluid/imperative/layer.h
  paddle/fluid/imperative/layout_autotune.cc
  paddle/fluid/imperative/nccl_context.cc
  paddle/fluid/imperative/op_base.h
  paddle/fluid/imperative/partial_grad_engine.cc
  paddle/fluid/imperative/prepared_operator.cc
  paddle/fluid/imperative/prepared_operator.h
  paddle/fluid/imperative/reducer.cc
  paddle/fluid/imperative/reducer.cu
  paddle/fluid/imperative/tracer.cc
  paddle/fluid/imperative/var_helper.cc
  paddle/fluid/imperative/variable_wrapper.h
  paddle/fluid/imperative/xccl_context.cc
Labels: contributor, HappyOpenSource

#66898 Replace phi::errors in fluid/pir/dialect [fluid_ops] part20
  paddle/fluid/pir/dialect/distributed/ir/dist_attribute.cc
  paddle/fluid/pir/dialect/distributed/ir/dist_op.cc
  paddle/fluid/pir/dialect/distributed/transforms/dist_to_dense_pass.cc
  paddle/fluid/pir/dialect/kernel/ir/kernel_op.cc
  paddle/fluid/pir/dialect/op_generator/api_gen.py
  paddle/fluid/pir/dialect/op_generator/op_build_gen.py
  paddle/fluid/pir/dialect/op_generator/op_infermeta_func_gen.py
  paddle/fluid/pir/dialect/op_generator/op_interface_gen.py
  paddle/fluid/pir/dialect/op_generator/op_verify_gen.py
  paddle/fluid/pir/dialect/op_generator/ops_api_gen.py
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/binary_infer_sym.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/infer_sym_slice_utils.h
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/infer_sym_utils.h
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/multiary_infer_sym.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/nullary_infer_sym.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/unary_infer_sym.cc
  paddle/fluid/pir/dialect/operator/interface/layout_transformation.cc
  paddle/fluid/pir/dialect/operator/ir/api_builder.cc
  paddle/fluid/pir/dialect/operator/ir/control_flow_op.cc
  paddle/fluid/pir/dialect/operator/ir/ir_meta_tensor.cc
  paddle/fluid/pir/dialect/operator/ir/manual_api.cc
  paddle/fluid/pir/dialect/operator/ir/manual_onednn_op.cc
  paddle/fluid/pir/dialect/operator/ir/manual_op.cc
  paddle/fluid/pir/dialect/operator/ir/manual_op_decomp_vjp.cc
  paddle/fluid/pir/dialect/operator/ir/manual_op_vjp.cc
  paddle/fluid/pir/dialect/operator/ir/op_attribute.cc
  paddle/fluid/pir/dialect/operator/ir/op_dialect.cc
  paddle/fluid/pir/dialect/operator/ir/tensorrt_op.cc
  paddle/fluid/pir/dialect/operator/utils/op_yaml_info_parser.cc
  paddle/fluid/pir/dialect/operator/utils/utils.cc
  paddle/fluid/pir/dialect/operator/utils/utils.h
Labels: contributor, HappyOpenSource

#66915 Replace framework::LoDTensorArray part4
  paddle/phi/core/compat/arg_map_context.h
  paddle/phi/infermeta/unary.cc
  paddle/phi/kernels/funcs/strided_slice.h
  paddle/phi/kernels/reverse_kernel.cc
  test/cpp/fluid/assign_op_test.cc
  test/cpp/fluid/beam_search_decode_op_test.cc
  test/cpp/fluid/controlflow/conditional_block_op_test.cc
  test/cpp/fluid/framework/operator_test.cc
  test/cpp/fluid/framework/reader_test.cc
  test/cpp/fluid/framework/var_type_traits_test.cc
  test/cpp/imperative/test_layer.cc
  test/cpp/inference/test_helper.h
  test/xpu/cpp/beam_search_decode_op_xpu_test.cc
Labels: contributor, HappyOpenSource

#66907 Replace phi::errors [fluid_ops] part17
  paddle/fluid/eager/accumulation/accumulation_node.cc
  paddle/fluid/eager/api/generated/eager_generated/backwards/scale_node.cc
  paddle/fluid/eager/api/manual/eager_manual/forwards/reshard_fwd_func.cc
  paddle/fluid/eager/api/manual/eager_manual/nodes/multiply_node.cc
  paddle/fluid/eager/api/manual/eager_manual/nodes/reshard_node.cc
  paddle/fluid/eager/api/manual/eager_manual/nodes/sync_batch_norm_node.cc
  paddle/fluid/eager/api/manual/fluid_manual/nodes/nodes.h
  paddle/fluid/eager/api/utils/hook_utils.cc
  paddle/fluid/eager/auto_code_generator/eager_generator.cc
  paddle/fluid/eager/auto_code_generator/generator/eager_gen.py
  paddle/fluid/eager/auto_code_generator/generator/python_c_gen.py
  paddle/fluid/eager/autograd_meta.h
  paddle/fluid/eager/backward.cc
  paddle/fluid/eager/custom_operator/custom_operator_node.cc
  paddle/fluid/eager/custom_operator/custom_operator_utils.cc
  paddle/fluid/eager/eager_tensor.h
  paddle/fluid/eager/general_grad.h
  paddle/fluid/eager/grad_node_info.cc
  paddle/fluid/eager/grad_node_info.h
  paddle/fluid/eager/grad_tensor_holder.cc
  paddle/fluid/eager/hooks.h
  paddle/fluid/eager/nan_inf_utils.cc
  paddle/fluid/eager/pylayer/py_layer_node.cc
  paddle/fluid/eager/tensor_wrapper.h
  paddle/fluid/eager/to_static/run_program_op_node.h
  paddle/fluid/eager/utils.cc
Labels: contributor, HappyOpenSource

#66927 Replace platform/collective_helper.h in fluid/operators [fluid_ops]
  paddle/fluid/operators/collective/alltoall_op.cu.cc
  paddle/fluid/operators/collective/barrier_op.cu.cc
  paddle/fluid/operators/collective/c_allgather_op.cu.cc
  paddle/fluid/operators/collective/c_allgather_op_xpu.cc
  paddle/fluid/operators/collective/c_allreduce_op.h
  paddle/fluid/operators/collective/c_broadcast_op.cu.cc
  paddle/fluid/operators/collective/c_broadcast_op_xpu.cc
  paddle/fluid/operators/collective/c_comm_init_all_op.h
  paddle/fluid/operators/collective/c_comm_init_multitrainer_op.cc
  paddle/fluid/operators/collective/c_comm_init_op.cc
  paddle/fluid/operators/collective/c_concat_op.cu.cc
  paddle/fluid/operators/collective/c_concat_op_xpu.cc
  paddle/fluid/operators/collective/c_reduce_op.h
  paddle/fluid/operators/collective/c_reducescatter_op.cu.cc
  paddle/fluid/operators/collective/c_scatter_op.cu.cc
  paddle/fluid/operators/collective/c_softmax_with_cross_entropy_op.cu
  paddle/fluid/operators/collective/c_softmax_with_cross_entropy_op_xpu.cc
  paddle/fluid/operators/collective/c_sync_comm_stream_op.h
  paddle/fluid/operators/collective/c_wait_comm_op.cc
  paddle/fluid/operators/collective/c_wait_compute_op.cc
  paddle/fluid/operators/collective/global_gather_op.cu.cc
  paddle/fluid/operators/collective/global_scatter_op.cu.cc
  paddle/fluid/operators/collective/partial_allgather_op.cu.cc
  paddle/fluid/operators/collective/partial_recv_op.cu.cc
  paddle/fluid/operators/collective/partial_send_op.cu.cc
  paddle/fluid/operators/collective/recv_v2_op.cu.cc
  paddle/fluid/operators/collective/send_v2_op.cu.cc
  paddle/fluid/operators/custom_device_common_op_registry.cc
  paddle/fluid/operators/data_norm_op.cu
  paddle/fluid/operators/fused/fused_attention_utils.h
  paddle/fluid/operators/margin_cross_entropy_op.cu
Labels: contributor, HappyOpenSource

#66906 Replace phi::errors [fluid_ops] part16
  paddle/fluid/distributed/auto_parallel/dist_attr.cc
  paddle/fluid/distributed/collective/async_load.cc
  paddle/fluid/distributed/collective/bkcl_tools.cc
  paddle/fluid/distributed/collective/bkcl_tools.h
  paddle/fluid/distributed/collective/custom_ccl_tools.cc
  paddle/fluid/distributed/collective/mpi_tools.cc
  paddle/fluid/distributed/collective/mpi_tools.h
  paddle/fluid/distributed/collective/process_group.h
  paddle/fluid/distributed/collective/process_group_bkcl.cc
  paddle/fluid/distributed/collective/process_group_custom.cc
  paddle/fluid/distributed/collective/process_group_gloo.cc
  paddle/fluid/distributed/collective/process_group_gloo.h
  paddle/fluid/distributed/collective/process_group_mpi.cc
  paddle/fluid/distributed/collective/process_group_mpi.h
  paddle/fluid/distributed/collective/process_group_nccl.cc
  paddle/fluid/distributed/collective/process_group_with_stream.h
  paddle/fluid/distributed/collective/process_group_without_stream.h
  paddle/fluid/distributed/collective/reducer.cc
  paddle/fluid/distributed/common/chunk_allocator.h
  paddle/fluid/distributed/fleet_executor/carrier.cc
  paddle/fluid/distributed/fleet_executor/compute_interceptor.cc
  paddle/fluid/distributed/fleet_executor/cond_interceptor.cc
  paddle/fluid/distributed/fleet_executor/dist_model.cc
  paddle/fluid/distributed/fleet_executor/dist_model_tensor_wrapper.cc
  paddle/fluid/distributed/fleet_executor/fleet_executor.cc
  paddle/fluid/distributed/fleet_executor/global.h
  paddle/fluid/distributed/fleet_executor/interceptor.cc
  paddle/fluid/distributed/fleet_executor/message_bus.cc
  paddle/fluid/distributed/fleet_executor/start_interceptor.cc
  paddle/fluid/distributed/fleet_executor/task_loop.cc
  paddle/fluid/distributed/fleet_executor/task_loop_thread.cc
  paddle/fluid/distributed/fleet_executor/task_loop_thread_pool.cc
  paddle/fluid/distributed/fleet_executor/task_node.cc
  paddle/fluid/distributed/index_dataset/index_sampler.h
  paddle/fluid/distributed/index_dataset/index_wrapper.cc
  paddle/fluid/distributed/index_dataset/index_wrapper.h
  paddle/fluid/distributed/ps/service/brpc_ps_client.cc
  paddle/fluid/distributed/ps/service/brpc_ps_server.cc
  paddle/fluid/distributed/ps/service/brpc_utils.cc
  paddle/fluid/distributed/ps/service/communicator/communicator.cc
  paddle/fluid/distributed/ps/service/communicator/communicator.h
  paddle/fluid/distributed/ps/service/heter_client.cc
  paddle/fluid/distributed/ps/service/heter_server.h
  paddle/fluid/distributed/ps/service/ps_local_client.cc
  paddle/fluid/distributed/ps/service/server.h
  paddle/fluid/distributed/ps/service/simple_rpc/baidu_rpc_server.cc
  paddle/fluid/distributed/ps/service/simple_rpc/rpc_server.cc
  paddle/fluid/distributed/ps/table/common_graph_table.cc
  paddle/fluid/distributed/ps/table/graph/graph_node.h
  paddle/fluid/distributed/ps/table/memory_dense_table.cc
  paddle/fluid/distributed/ps/table/ssd_sparse_table.cc
  paddle/fluid/distributed/ps/wrapper/fleet.cc
  paddle/fluid/distributed/rpc/future_wrapper.h
  paddle/fluid/distributed/rpc/rpc_agent.cc
Labels: contributor, HappyOpenSource

#66555 Replace phi::errors [fluid_ops] part4
  paddle/fluid/ir_adaptor/translator/attribute_translator.cc
  paddle/fluid/ir_adaptor/translator/op_translator.cc
  paddle/fluid/ir_adaptor/translator/program_translator.cc
  paddle/fluid/ir_adaptor/translator/type_translator.h
  paddle/fluid/ir_adaptor/translator/utils.h
  paddle/fluid/jit/compilation_unit.cc
  paddle/fluid/jit/engine/interpreter_engine.cc
  paddle/fluid/jit/function.cc
  paddle/fluid/jit/function_utils.cc
  paddle/fluid/jit/layer.cc
  paddle/fluid/jit/property.cc
  paddle/fluid/prim/api/composite_backward/composite_backward_api.h
  paddle/fluid/prim/api/manual_prim/static_prim_api.cc
  paddle/fluid/prim/api/manual_prim/utils/utils.h
  paddle/fluid/prim/utils/static/composite_grad_desc_maker.h
  paddle/fluid/primitive/base/decomp_trans.cc
  paddle/fluid/primitive/codegen/templates/decomp/generated_decomp.j2
  paddle/fluid/primitive/codegen/templates/decomp/generated_decomp_vjp.j2
  paddle/fluid/primitive/composite/composite.h
  paddle/fluid/primitive/rule/vjp/details.h
  paddle/fluid/primitive/utils/utils.h
  paddle/fluid/sub_graph/sub_graph_checker.cc
Labels: contributor, HappyOpenSource

#66912 Replace framework::LoDTensorArray part1
  paddle/fluid/eager/api/manual/eager_manual/forwards/add_n_fwd_func.cc
  paddle/fluid/eager/api/manual/eager_manual/forwards/conv2d_fwd_function.cc
  paddle/fluid/eager/api/manual/eager_manual/forwards/multiply_fwd_func.cc
  paddle/fluid/eager/api/manual/eager_manual/forwards/reshard_fwd_func.cc
  paddle/fluid/eager/api/manual/eager_manual/forwards/sync_batch_norm_fwd_func.cc
  paddle/fluid/eager/api/manual/eager_manual/nodes/add_n_node.cc
  paddle/fluid/eager/api/manual/eager_manual/nodes/conv2d_nodes.cc
  paddle/fluid/eager/api/manual/eager_manual/nodes/multiply_node.cc
  paddle/fluid/eager/api/manual/eager_manual/nodes/reshard_node.cc
  paddle/fluid/eager/api/manual/eager_manual/nodes/sync_batch_norm_node.cc
  paddle/fluid/eager/api/manual/fluid_manual/forwards/fused_attention_fwd_func.cc
  paddle/fluid/eager/api/manual/fluid_manual/forwards/fused_bias_dropout_residual_layer_norm_fwd_func.cc
  paddle/fluid/eager/api/manual/fluid_manual/forwards/fused_feedforward_fwd_func.cc
  paddle/fluid/eager/api/manual/fluid_manual/forwards/fused_gate_attention_fwd_func.cc
  paddle/fluid/eager/api/manual/fluid_manual/forwards/fused_gemm_epilogue_fwd_func.cc
  paddle/fluid/eager/auto_code_generator/eager_generator.cc
  paddle/fluid/eager/auto_code_generator/generator/eager_gen.py
  paddle/fluid/eager/auto_code_generator/generator/python_c_gen.py
  paddle/fluid/eager/backward.cc
  paddle/fluid/eager/custom_operator/custom_operator_node.cc
  paddle/fluid/eager/to_static/run_program_op_node.h
Labels: contributor, HappyOpenSource

#66641 [Auto Parallel] Support gradient_merge pass for PIR
  paddle/fluid/pybind/pir.cc
  python/paddle/distributed/auto_parallel/static/engine.py
  python/paddle/distributed/auto_parallel/static/pir_pass.py
  python/paddle/distributed/passes/auto_parallel_gradient_merge.py
  python/paddle/distributed/passes/auto_parallel_master_grad.py
  python/paddle/distributed/passes/pass_utils.py
  test/auto_parallel/pir/mlp_demo.py
Labels: contributor

#66933 【Error Message BUAA No.35】fix error message
  paddle/cinn/adt/schedule_dim.cc
  paddle/cinn/adt/schedule_dim.h
  paddle/cinn/backends/codegen_c_x86.cc
  paddle/cinn/backends/codegen_c_x86.h
  paddle/cinn/backends/codegen_cuda_generate_test.cc
  paddle/cinn/backends/codegen_debug_test.cc
  paddle/cinn/backends/codegen_device_util.cc
  paddle/cinn/backends/extern_func_jit_register.cc
  paddle/cinn/backends/extern_func_jit_register.h
  paddle/cinn/common/axis.cc
  paddle/cinn/common/axis.h
  paddle/cinn/common/scc_walker.h
  paddle/cinn/common/test_helper.h
  paddle/cinn/common/type.h
Labels: contributor, HappyOpenSource Pro

#66939 【Error Message BUAA No.35】fix error message
  paddle/cinn/hlir/op/contrib/randint.cc
  paddle/cinn/hlir/op/contrib/triangular_solve.cc
  paddle/cinn/hlir/op/contrib/uniform_random.cc
  paddle/cinn/hlir/pe/elementwise.cc
  paddle/cinn/hlir/pe/elementwise.h
  paddle/cinn/ir/group_schedule/config/file_database.cc
  paddle/cinn/ir/group_schedule/tactic/tile_tactic.cc
  paddle/cinn/ir/intrinsic_ops.cc
  paddle/cinn/ir/ir_visitor.h
  paddle/cinn/ir/module.cc
  paddle/cinn/ir/registry.cc
  paddle/cinn/ir/schedule/impl/for_type.cc
  paddle/cinn/ir/schedule/impl/reduction.cc
  paddle/cinn/poly/domain.cc
  paddle/cinn/poly/map.cc
  paddle/cinn/poly/naive_scheduler.cc
  paddle/cinn/poly/schedule.h
Labels: contributor, HappyOpenSource Pro

#66867 [Typing][C-91, C-92] Add annotations for ```python/paddle/incubate/operators/{softmax_mask_fuse, softmax_mask_fuse_upper_triangle}.py```
  python/paddle/incubate/operators/softmax_mask_fuse.py
  python/paddle/incubate/operators/softmax_mask_fuse_upper_triangle.py
Labels: contributor, HappyOpenSource

#66914 Replace framework::LoDTensorArray part3 [fluid_ops]
  paddle/fluid/operators/assign_op.h
  paddle/fluid/operators/beam_search_decode_op.h
  paddle/fluid/operators/beam_search_decode_op_def.h
  paddle/fluid/operators/beam_search_decode_op_xpu.h
  paddle/fluid/operators/collective/recv_v2_op.cu.cc
  paddle/fluid/operators/collective/send_v2_op.cc
  paddle/fluid/operators/collective/send_v2_op.cu.cc
  paddle/fluid/operators/controlflow/control_flow_op_helper.h
  paddle/fluid/operators/controlflow/fetch_op.cc
  paddle/fluid/operators/controlflow/fetch_v2_op.cc
  paddle/fluid/operators/controlflow/tensor_array_read_write_op.cc
  paddle/fluid/operators/controlflow/while_op.cc
  paddle/fluid/operators/generator/get_expected_kernel_func.cc
  paddle/fluid/operators/lod_array_length_op.cc
  paddle/fluid/operators/memcpy_d2h_op.h
  paddle/fluid/operators/reader/buffered_reader.cc
  paddle/fluid/operators/reader/buffered_reader.h
  paddle/fluid/operators/reader/lod_tensor_blocking_queue.h
  paddle/fluid/operators/reader/py_reader.cc
  paddle/fluid/operators/reader/py_reader.h
  paddle/fluid/operators/reader/read_op.cc
  paddle/fluid/operators/slice_op.cc
  paddle/fluid/operators/sum_op.cc
  paddle/fluid/operators/tensor_array_to_tensor_op.cc
Labels: contributor, HappyOpenSource

#66795 [Prim][PIR] Forward decomp the heaviside op
  paddle/fluid/pir/dialect/op_generator/decomp_interface_gen_op_list.py
  paddle/fluid/primitive/composite/composite.h
  test/legacy_test/test_elementwise_heaviside_op.py
  test/prim/pir_prim/test_prim_sub_graph_dynamic_shape.py
Labels: contributor

#66886 Replace platform/enforce.h in fluid/memory [fluid_ops]
  paddle/fluid/memory/allocation/aligned_allocator.cc
  paddle/fluid/memory/allocation/allocator.h
  paddle/fluid/memory/allocation/allocator_facade.cc
  paddle/fluid/memory/allocation/allocator_strategy.cc
  paddle/fluid/memory/allocation/best_fit_allocator.cc
  paddle/fluid/memory/allocation/cpu_allocator.cc
  paddle/fluid/memory/allocation/cuda_allocator.cc
  paddle/fluid/memory/allocation/cuda_ipc_allocator.cc
  paddle/fluid/memory/allocation/cuda_ipc_allocator.h
  paddle/fluid/memory/allocation/cuda_malloc_async_allocator.cc
  paddle/fluid/memory/allocation/cuda_managed_allocator.cc
  paddle/fluid/memory/allocation/cuda_virtual_mem_allocator.cc
  paddle/fluid/memory/allocation/custom_allocator.cc
  paddle/fluid/memory/allocation/memory_block.cc
  paddle/fluid/memory/allocation/meta_cache.cc
  paddle/fluid/memory/allocation/mmap_allocator.cc
  paddle/fluid/memory/allocation/naive_best_fit_allocator.cc
  paddle/fluid/memory/allocation/retry_allocator.h
  paddle/fluid/memory/allocation/system_allocator.cc
  paddle/fluid/memory/allocation/xpu_allocator.cc
  paddle/fluid/memory/stats.h
Labels: contributor, HappyOpenSource

#66684 [Typing][C-119] Add type annotations for `python/paddle/quantization/config.py`
  python/paddle/quantization/config.py
Labels: contributor, HappyOpenSource

#66922 【Hackathon 6th Fundable Projects 3 No.248-251】Remove fluid operators ncclAllReduce etc
  paddle/fluid/operators/nccl/CMakeLists.txt
  paddle/fluid/operators/nccl/nccl_op.cc
  paddle/fluid/operators/nccl/nccl_op.cu.cc
  test/cpp/fluid/CMakeLists.txt
  test/cpp/fluid/nccl/CMakeLists.txt
  test/cpp/fluid/nccl/nccl_op_test.cu.cc
Labels: PaddlePaddle Hackathon, contributor

#66942 Replace platform::ToBKCLDataType in operators/collective [fluid_ops]
  paddle/fluid/operators/collective/c_allgather_op_xpu.cc
  paddle/fluid/operators/collective/c_allreduce_op.h
  paddle/fluid/operators/collective/c_broadcast_op_xpu.cc
  paddle/fluid/operators/collective/c_concat_op_xpu.cc
  paddle/fluid/operators/collective/c_reduce_op.h
  paddle/fluid/operators/collective/c_softmax_with_cross_entropy_op_xpu.cc
Labels: contributor, HappyOpenSource

#66965 [Typing][PEP585 Upgrade][1] Use stardand collections for type hints in `paddle/fluid/ir_adaptor/translator/op_compat_gen.py`
  paddle/fluid/ir_adaptor/translator/op_compat_gen.py
Labels: contributor, HappyOpenSource

#66966 [Typing][C-93] Add type annotation for `python/paddle/incubate/operators/unzip.py`
  python/paddle/incubate/operators/unzip.py
Labels: contributor, HappyOpenSource

#66793 [Typing][C-90] Add type annotation for `python/paddle/incubate/operators/resnet_unit.py`
  python/paddle/incubate/operators/resnet_unit.py
Labels: contributor, HappyOpenSource

#66987 [Typing][C-79] Add type annotations for `python/paddle/incubate/nn/functional/swiglu.py`
  python/paddle/incubate/nn/functional/swiglu.py
Labels: contributor

#66985 [Typing][C-5, C-6] Add type annotations for `python/paddle/distributed/auto_parallel/{process_mesh, random}.py`
  python/paddle/distributed/auto_parallel/process_mesh.py
  python/paddle/distributed/auto_parallel/random.py
Labels: contributor

#66639 [Typing][B-49] Add type annotations for `python/paddle/base/layer_helper.py`
  python/paddle/base/layer_helper.py
  python/paddle/base/param_attr.py
Labels: contributor, HappyOpenSource

#66986 [Typing][C-10, C-11] Add type annotations for `python/paddle/distributed/checkpoint/{load_state_dict, save_state_dict}.py`
  python/paddle/distributed/checkpoint/load_state_dict.py
  python/paddle/distributed/checkpoint/save_state_dict.py
Labels: contributor

#66993 [Typing][C-27,C-28,C-29,C-30,C-31,C-32,C-33] Add type annotations for `python/paddle/distributed/communication/stream/*.py`
  python/paddle/distributed/communication/stream/broadcast.py
  python/paddle/distributed/communication/stream/gather.py
  python/paddle/distributed/communication/stream/recv.py
  python/paddle/distributed/communication/stream/reduce.py
  python/paddle/distributed/communication/stream/reduce_scatter.py
  python/paddle/distributed/communication/stream/scatter.py
  python/paddle/distributed/communication/stream/send.py
Labels: contributor

#66958 【Error Message No. 4 No.33 BUAA】rewrite error message
  paddle/fluid/inference/capi/c_api.cc
  paddle/fluid/inference/tensorrt/plugin/generic_plugin.cu
  paddle/fluid/pir/transforms/sub_graph_detector.cc
Labels: contributor, HappyOpenSource Pro

#66835 [Prim][PIR] Surport dynamic shape for matmul_grad
  paddle/fluid/primitive/rule/vjp/details.h
  python/paddle/autograd/backward_utils.py
  test/prim/pir_prim/test_prim_sub_graph_backward_dynamic_shape.py
Labels: contributor

#66837 【Infer Symbolic Shape BUAA No.70】Add lerp op
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/multiary_infer_sym.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/multiary_infer_sym.h
  paddle/phi/ops/yaml/ops.yaml
Labels: contributor, HappyOpenSource Pro

#66913 Replace framework::LoDTensorArray part2 [fluid_ops]
  paddle/fluid/framework/attribute.cc
  paddle/fluid/framework/attribute.h
  paddle/fluid/framework/data_type.cc
  paddle/fluid/framework/details/eager_deletion_op_handle.cc
  paddle/fluid/framework/dlpack_tensor.cc
  paddle/fluid/framework/executor.cc
  paddle/fluid/framework/executor_gc_helper.cc
  paddle/fluid/framework/feed_fetch_type.h
  paddle/fluid/framework/infershape_utils.cc
  paddle/fluid/framework/ir/graph.h
  paddle/fluid/framework/ir/memory_optimize_pass/eager_deletion_pass.cc
  paddle/fluid/framework/new_executor/garbage_collector/event_garbage_collector.cc
  paddle/fluid/framework/new_executor/garbage_collector/fast_garbage_collector.cc
  paddle/fluid/framework/new_executor/garbage_collector/no_event_garbage_collector.cc
  paddle/fluid/framework/new_executor/instruction/instruction_base.cc
  paddle/fluid/framework/new_executor/instruction/phi_kernel_instruction.cc
  paddle/fluid/framework/new_executor/interpreter/data_transfer.cc
  paddle/fluid/framework/new_executor/interpreter/interpreter_util.cc
  paddle/fluid/framework/new_executor/interpreter/static_build.cc
  paddle/fluid/framework/new_executor/new_executor_defs.cc
  paddle/fluid/framework/new_executor/pir_interpreter.cc
  paddle/fluid/framework/new_executor/program_interpreter.cc
  paddle/fluid/framework/new_executor/standalone_executor.cc
  paddle/fluid/framework/new_executor/workqueue/nonblocking_threadpool.h
  paddle/fluid/framework/new_executor/workqueue/workqueue.cc
  paddle/fluid/framework/op_desc.cc
  paddle/fluid/framework/operator.cc
  paddle/fluid/framework/operator.h
  paddle/fluid/framework/reader.cc
  paddle/fluid/framework/reader.h
  paddle/fluid/framework/var_type.h
  paddle/fluid/framework/var_type_traits.h
  paddle/fluid/framework/variable.h
  paddle/fluid/framework/variable_helper.cc
Labels: contributor, HappyOpenSource

#66968 [Typing][PEP585 Upgrade][2-3] Use stardand collections for type hints in `paddle/fluid/operators/generator/*`
  paddle/fluid/operators/generator/filters.py
  paddle/fluid/operators/generator/parse_utils.py
Labels: contributor, HappyOpenSource

#66785 [PIR Unittest] fix pir ut (`test_while_op,test_norm_nn_grad`)
  paddle/fluid/pir/dialect/op_generator/ops_api_gen.py
  paddle/phi/infermeta/binary.cc
  python/paddle/incubate/layers/nn.py
  test/legacy_test/test_norm_nn_grad.py
  test/legacy_test/test_shuffle_batch_op.py
  test/legacy_test/test_while_op.py
Labels: contributor

#66952 【Infer Symbolic Shape BUAA】add clipbynorm, ctcalign, identityloss
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/binary_infer_sym.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/binary_infer_sym.h
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/unary_infer_sym.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/unary_infer_sym.h
  paddle/phi/ops/yaml/ops.yaml
Labels: contributor, HappyOpenSource Pro

#66724 【Hackathon 6th Fundable Projects 3 No.225】 [fluid_ops] margin_cross_entropy
  paddle/fluid/operators/margin_cross_entropy_op.cc
  paddle/fluid/operators/margin_cross_entropy_op.cu
  paddle/phi/kernels/gpu/margin_cross_entropy_grad_kernel.cu
  paddle/phi/kernels/gpu/margin_cross_entropy_kernel.cu
  paddle/phi/kernels/impl/margin_cross_entropy.cu.h
  test/collective/fleet/test_parallel_margin_cross_entropy.py
  test/legacy_test/test_margin_cross_entropy_op.py
Labels: PaddlePaddle Hackathon, contributor

#66974 [Doc] Fix embedding doc; test=document_fix
  python/paddle/nn/functional/input.py
  python/paddle/nn/layer/common.py
Labels: PaddlePaddle Hackathon, contributor

#66946 【Infer Symbolic Shape BUAA No.12】Add channelshuffle op
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/unary_infer_sym.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/unary_infer_sym.h
  paddle/phi/ops/yaml/ops.yaml
Labels: contributor, HappyOpenSource Pro

#66925 [auto_parallel] Layered Implementation of load_state_dict
  python/paddle/distributed/checkpoint/load_state_dict.py
  test/auto_parallel/test_dist_checkpoint_utils.py
Labels: contributor

#66983 【BUAA】【Error Message No.45,81,143】Update error message
  paddle/cinn/backends/extern_func_emitter_builtin.cc
  paddle/cinn/optim/transform_gpu_forloop.cc
  paddle/fluid/framework/hetercpu_worker.cc
Labels: contributor, HappyOpenSource Pro

#66734 [Fix PIR Unittest] fix pir ut in test/contrib/`test_multi_precision_fp16_train`.py
  python/paddle/incubate/optimizer/lars_momentum.py
  test/contrib/test_multi_precision_fp16_train.py
Labels: contributor

#66959 [PIR Unittest] fix pir ut in (`test_quant_linear_op`)
  test/legacy_test/test_quant_linear_op.py
  test/xpu/test_while_op_xpu.py
Labels: contributor

#66570 【Infer Symbolic Shape BUAA No.21】dequantize_abs_max
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/same_operands_result.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/same_operands_result.h
  paddle/phi/ops/yaml/ops.yaml
Labels: contributor, HappyOpenSource Pro

#66888 【Infer Symbolic Shape BUAA No.35】Add equal_all op
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/binary_infer_sym.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/binary_infer_sym.h
  paddle/phi/ops/yaml/ops.yaml
Labels: contributor, HappyOpenSource Pro

#66847 【Error Message No. 35 【BUAA】 】reciprocal.cc & ast_gen.cc& poly_scheduler.cc
  paddle/cinn/hlir/op/contrib/reciprocal.cc
  paddle/cinn/poly/ast_gen.cc
  paddle/cinn/poly/poly_scheduler.cc
Labels: contributor, HappyOpenSource Pro

#66975 [Typing][PEP585 Upgrade][BUAA][202-206] Use stardand collections for type hints for 5 uts in `test/ir/inference/`
  test/ir/inference/test_trt_convert_one_hot.py
  test/ir/inference/test_trt_convert_p_norm.py
  test/ir/inference/test_trt_convert_pad.py
  test/ir/inference/test_trt_convert_pad3d.py
  test/ir/inference/test_trt_convert_pool2d.py
Labels: contributor, HappyOpenSource Pro

#66967 【Infer Symbolic Shape No.96-98 BUAA】Add softplus, softshrink and softsign op
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/same_operands_result.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/same_operands_result.h
  paddle/phi/ops/yaml/ops.yaml
Labels: contributor, HappyOpenSource Pro

#66961 【Infer Symbolic Shape BUAA No.51 BUAA】gelu
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/same_operands_result.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/same_operands_result.h
  paddle/phi/ops/yaml/ops.yaml
Labels: contributor, HappyOpenSource Pro

#66972 [Typing][PEP585 Upgrade][BUAA][201] Use stardand collections for type hints in `test/ir/inference/test_trt_convert_nearest_interp_v2.py`
  test/ir/inference/test_trt_convert_nearest_interp_v2.py
Labels: contributor, HappyOpenSource Pro

#67028 [Typing][PEP585 Upgrade][BUAA][226-235] Use standard collections for type hints for 10 uts in `test/ir/inference/`
  test/ir/inference/test_trt_convert_softmax.py
  test/ir/inference/test_trt_convert_solve.py
  test/ir/inference/test_trt_convert_split.py
  test/ir/inference/test_trt_convert_square.py
  test/ir/inference/test_trt_convert_squeeze2.py
  test/ir/inference/test_trt_convert_stack.py
  test/ir/inference/test_trt_convert_strided_slice.py
  test/ir/inference/test_trt_convert_sum.py
  test/ir/inference/test_trt_convert_swish.py
  test/ir/inference/test_trt_convert_take_along_axis.py
Labels: contributor, HappyOpenSource Pro

#67024 [Typing][PEP585 Upgrade][BUAA][216-225] Use standard collections for type hints for 10 uts in `test/ir/inference/`
  test/ir/inference/test_trt_convert_roi_align.py
  test/ir/inference/test_trt_convert_roll.py
  test/ir/inference/test_trt_convert_scale.py
  test/ir/inference/test_trt_convert_scatter.py
  test/ir/inference/test_trt_convert_scatter_nd_add.py
  test/ir/inference/test_trt_convert_shape.py
  test/ir/inference/test_trt_convert_share_data.py
  test/ir/inference/test_trt_convert_shuffle_channel.py
  test/ir/inference/test_trt_convert_size.py
  test/ir/inference/test_trt_convert_slice.py
Labels: contributor, HappyOpenSource Pro

#66899 【Error Message No.362】【BUAA】Update error massage of paddle\fluid\distributed\ps\wrapper\fleet.h and other 3 files
  paddle/fluid/distributed/ps/wrapper/fleet.h
  paddle/fluid/inference/capi/pd_predictor.cc
  paddle/fluid/inference/tensorrt/convert/leaky_relu_op.cc
Labels: contributor, HappyOpenSource Pro

#66864 [Typing][C-21,C-22,C-23,C-24] Add type annotations for `python/paddle/distributed/communication/{reduce_scatter.py, scatter.py, send.py, all_gather.py}`
  python/paddle/distributed/communication/reduce_scatter.py
  python/paddle/distributed/communication/scatter.py
  python/paddle/distributed/communication/send.py
  python/paddle/distributed/communication/stream/all_gather.py
Labels: contributor, HappyOpenSource Pro

#67018 【BUAA】【Infer Symbolic Shape BUAA No.70】Add lerp op
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/multiary_infer_sym.cc
Labels: contributor

#66848 【Hackathon 6th Fundable Projects 3 No.49】 [fluid_ops] c_scatter
  paddle/fluid/operators/collective/c_scatter_op.cc
  paddle/fluid/operators/collective/c_scatter_op.cu.cc
  paddle/fluid/operators/collective/c_scatter_op.h
  paddle/phi/infermeta/unary.cc
  paddle/phi/infermeta/unary.h
  paddle/phi/kernels/cpu/c_scatter_kernel.cc
  paddle/phi/kernels/gpu/c_scatter_kernel.cu
  paddle/phi/ops/yaml/inconsistent/static_ops.yaml
  paddle/phi/ops/yaml/ops.yaml
Labels: PaddlePaddle Hackathon, contributor

#66818 Replace framework::LoDTensorArray part5 [fluid_ops]
  paddle/fluid/distributed/fleet_executor/compute_interceptor.cc
  paddle/fluid/distributed/ps/service/brpc_ps_server.cc
  paddle/fluid/distributed/ps/service/communicator/communicator.cc
  paddle/fluid/distributed/ps/service/heter_client.cc
  paddle/fluid/distributed/ps/service/heter_server.h
  paddle/fluid/imperative/all_reduce.cc
  paddle/fluid/imperative/basic_engine.cc
  paddle/fluid/imperative/bkcl_context.cc
  paddle/fluid/imperative/gloo_context.cc
  paddle/fluid/imperative/layer.cc
  paddle/fluid/imperative/partial_grad_engine.cc
  paddle/fluid/imperative/prepared_operator.cc
  paddle/fluid/imperative/prepared_operator.h
  paddle/fluid/imperative/tracer.cc
  paddle/fluid/imperative/var_helper.cc
  paddle/fluid/imperative/xccl_context.cc
  paddle/fluid/inference/api/details/reset_tensor_array.cc
  paddle/fluid/inference/api/details/reset_tensor_array.h
  paddle/fluid/platform/profiler/profiler_test.cc
  paddle/fluid/platform/resource_pool.h
  paddle/fluid/pybind/compiled_program.cc
  paddle/fluid/pybind/eager_math_op_patch.cc
  paddle/fluid/pybind/eager_utils.cc
  paddle/fluid/pybind/place.cc
  paddle/fluid/pybind/pybind.cc
  paddle/fluid/pybind/reader_py.cc
  paddle/fluid/pybind/tensor.cc
  paddle/phi/core/memory/allocation/auto_growth_best_fit_allocator.cc
  paddle/phi/core/memory/allocation/auto_growth_best_fit_allocator_v2.cc
  paddle/phi/core/memory/allocation/stream_safe_cuda_allocator.cc
  paddle/phi/core/memory/allocation/stream_safe_custom_device_allocator.cc
  paddle/phi/core/memory/allocation/stream_safe_xpu_allocator.cc
  paddle/phi/core/memory/memcpy.cc
Labels: contributor, HappyOpenSource

#67040 [Typing][PEP585 Upgrade][BUAA][246-255] Use standard collections for type hints for 10 uts in `test/ir/inference/`
  test/ir/inference/test_trt_convert_where.py
  test/ir/inference/test_trt_convert_yolo_box.py
  test/ir/inference/test_trt_convert_yolo_box_head.py
  test/ir/inference/test_trt_float64.py
  test/ir/inference/test_trt_int64.py
  test/ir/inference/test_trt_ops_fp32_mix_precision.py
  test/ir/pir/cinn/llama_test_model.py
  test/legacy_test/auto_parallel_op_test.py
  test/legacy_test/test_memory_efficient_attention.py
Labels: contributor, HappyOpenSource Pro

#67044 [Typing][PEP585 Upgrade][BUAA][256-260] Use standard collections for type hints for 5 uts in `test/`
  test/legacy_test/utils.py
  test/prim/model/bert.py
  test/quantization/test_customized_quanter.py
  test/sot/test_builtin_map.py
  tools/cinn/gen_c++_tutorial.py
Labels: contributor, HappyOpenSource Pro

#66620 [CINN][New Hardware Update] add CodeGenGPU_Dev
  paddle/cinn/backends/CMakeLists.txt
  paddle/cinn/backends/codegen_cuda_dev.cc
  paddle/cinn/backends/codegen_cuda_dev.h
  paddle/cinn/backends/codegen_cuda_generate_test.cc
  paddle/cinn/backends/codegen_cuda_host.cc
  paddle/cinn/backends/codegen_cuda_host.h
  paddle/cinn/backends/codegen_debug_test.cc
  paddle/cinn/backends/codegen_device_util.h
  paddle/cinn/backends/codegen_gpu_dev.cc
  paddle/cinn/backends/codegen_gpu_dev.h
  paddle/cinn/backends/compiler.cc
  paddle/cinn/backends/llvm/execution_engine.cc
  paddle/cinn/backends/llvm/simple_jit.cc
  paddle/cinn/common/cuda_test_helper.cc
Labels: contributor

#66971 【Error Message No.282 】[BUAA]将CHECK宏进行替换
  paddle/phi/api/ext/spmd_infer.h
Labels: contributor, HappyOpenSource Pro

#67049 【Infer Symbolic Shape】【BUAA】Add placeholders
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/binary_infer_sym.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/binary_infer_sym.h
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/multiary_infer_sym.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/multiary_infer_sym.h
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/nullary_infer_sym.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/nullary_infer_sym.h
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/same_operands_result.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/same_operands_result.h
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/unary_infer_sym.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/unary_infer_sym.h
  paddle/phi/ops/yaml/ops.yaml
Labels: contributor, HappyOpenSource Pro

#66889 【Infer Symbolic Shape BUAA No.20 No.24 No.32 No.68 No.77】Add mish label_smooth elu disable_check_model_nan_inf depend op
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/same_operands_result.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/same_operands_result.h
  paddle/phi/ops/yaml/ops.yaml
Labels: contributor, HappyOpenSource Pro

#67031 [Typing][C-132,C-133,C-134] Add type annotations for `python/paddle/nn/{clip,decode,initializer/lazy_init}.py`
  python/paddle/nn/clip.py
  python/paddle/nn/decode.py
  python/paddle/nn/initializer/lazy_init.py
Labels: contributor, HappyOpenSource

#67085 [OneDNN] Fix Prelu kernel failed in bf16 since data type error
  paddle/phi/backends/onednn/onednn_reuse.h
Labels: Intel, contributor

#67029 [Typing][PEP585 Upgrade][BUAA][4-10] Use standard collections for type hints in `paddle/`
  paddle/fluid/pir/dialect/op_generator/ops_onednn_extra_parser.py
  paddle/phi/api/generator/api_base.py
  paddle/phi/kernels/fusion/cutlass/memory_efficient_attention/generate_kernels.py
  paddle/phi/kernels/fusion/cutlass/memory_efficient_attention/generate_variable_forward_kernels.py
  python/paddle/amp/debugging.py
Labels: contributor, HappyOpenSource Pro

#66757 [PIR Unittest] fix pir ut (`test_custom_relu_op_setup,test_weight_decay,test_sync_batch_norm_op`
  test/custom_op/test_custom_relu_op_setup.py
  test/legacy_test/dist_fleet_sync_batch_norm.py
  test/legacy_test/test_sync_batch_norm_op.py
  test/legacy_test/test_weight_decay.py
Labels: contributor

#67096 [Typing][PEP585 Upgrade][BUAA][11-20] Use standard collections for type hints for 8 files in `python/paddle/`
  python/paddle/audio/datasets/dataset.py
  python/paddle/audio/datasets/esc50.py
  python/paddle/audio/datasets/tess.py
  python/paddle/audio/functional/window.py
  python/paddle/autograd/autograd.py
  python/paddle/autograd/backward_mode.py
  python/paddle/autograd/py_layer.py
  python/paddle/base/dygraph/base.py
Labels: contributor, HappyOpenSource Pro

#66956 【BUAA】【Infer Symbolic Shape】add mv, shadow_feed, share_data_
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/binary_infer_sym.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/binary_infer_sym.h
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/same_operands_result.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/same_operands_result.h
  paddle/phi/ops/yaml/inconsistent/static_ops.yaml
  paddle/phi/ops/yaml/ops.yaml
Labels: contributor, HappyOpenSource Pro

#66633 【Infer Symbolic Shape BUAA No.64】Add inverse op
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/unary_infer_sym.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/unary_infer_sym.h
  paddle/phi/ops/yaml/ops.yaml
Labels: contributor, HappyOpenSource Pro

#66735 【Infer Symbolic Shape BUAA No.63】Add index_select_strided op
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/binary_infer_sym.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/binary_infer_sym.h
  paddle/phi/ops/yaml/ops.yaml
Labels: contributor, HappyOpenSource Pro

#67058 [XPU] Support int31 weight dynamic quantization for fc and conv2d (#59981)
  paddle/fluid/framework/ir/xpu/conv2d_xpu_fuse_pass.cc
  paddle/fluid/framework/ir/xpu/fc_xpu_fuse_pass.cc
  paddle/fluid/framework/ir/xpu/pass_utils.cc
  paddle/fluid/framework/ir/xpu/quant_utils.cc
  paddle/phi/kernels/fusion/xpu/conv2d_xpu_kernel.cc
  paddle/phi/kernels/fusion/xpu/fc_xpu_kernel.cc
Labels: contributor

#67099 [BUAA][Error Message No.90/293/294/304] 优化了 4 个文件的报错信息
  paddle/cinn/adt/m_ir.cc
  paddle/cinn/adt/map_expr_ctx.h
  paddle/cinn/common/float16_bfloat16_cuda_test.cu
  paddle/cinn/hlir/op/contrib/gaussian_random.cc
Labels: contributor, HappyOpenSource Pro

#66953 【Error Message No. 55,94,96,97,134,135,174,175,177BUAA】将CHECK宏进行替换
  paddle/phi/kernels/fusion/xpu/block_multi_head_attention_kernel.cc
  paddle/phi/kernels/fusion/xpu/fused_bias_act_kernel.cc
  paddle/pir/src/dialect/shape/utils/dim_expr_util.cc
  test/cpp/eager/data_structure_tests/autograd_meta_test.cc
  test/cpp/phi/core/test_intrusive_ptr.cc
  test/cpp/phi/core/test_sparse_coo_tensor.cc
  test/cpp/phi/core/test_sparse_csr_tensor.cc
  test/cpp/utils/span_test.cc
Labels: contributor, HappyOpenSource Pro

#66777 【BUAA】【Error Message No.21】Update error massage of paddle\cinn\hlir\dialect\operator\ir\generate_shape_util.cc and other 4 files
  paddle/cinn/hlir/dialect/operator/ir/generate_shape_util.cc
  paddle/cinn/hlir/dialect/operator/transforms/group_merge/convert_static_dim_to_dynamic_pass.cc
  paddle/cinn/hlir/dialect/operator/transforms/group_merge/generate_shape_util.cc
  paddle/cinn/hlir/dialect/operator/transforms/pd_to_cinn_pass.cc
  paddle/cinn/hlir/dialect/operator/transforms/split_generate_shape_into_shape_ops_pass.cc
Labels: contributor, HappyOpenSource Pro

#67015 [Typing][PEP585 Upgrade][BUAA][151-160] Use standard collections for type hints for 10 uts in `test/ir/inference/`
  test/ir/inference/test_trt_convert_bitwise_or.py
  test/ir/inference/test_trt_convert_bmm.py
  test/ir/inference/test_trt_convert_cast.py
  test/ir/inference/test_trt_convert_clip.py
  test/ir/inference/test_trt_convert_compare_and_logical.py
  test/ir/inference/test_trt_convert_concat.py
  test/ir/inference/test_trt_convert_conv2d.py
  test/ir/inference/test_trt_convert_conv2d_transpose.py
  test/ir/inference/test_trt_convert_conv3d_transpose.py
  test/ir/inference/test_trt_convert_cross_multihead_matmul.py
Labels: contributor, HappyOpenSource Pro

#66935 【Infer Symbolic Shape 2 BUAA No.4】Add get_tensor_from_selected_rows op
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/same_operands_result.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/same_operands_result.h
  paddle/phi/ops/yaml/inconsistent/static_ops.yaml
Labels: contributor, HappyOpenSource Pro

#67078 【BUAA】【Error Message No.10,15】Update error message
  paddle/cinn/poly/stage.cc
  paddle/fluid/framework/data_feed.cc
Labels: contributor, HappyOpenSource Pro

#67109 【Error Message No. 27 BUAA】rewrite error message
  paddle/cinn/backends/codegen_c.cc
Labels: contributor, HappyOpenSource Pro

#67074 [BUAA][Error Message No.226/232/233/234/235]优化了5个文件的报错信息
  paddle/cinn/adt/equation_util.h
  paddle/cinn/hlir/dialect/operator/transforms/dynamic_reshape_pass.cc
  paddle/cinn/hlir/dialect/operator/transforms/fuse_shape_ops_into_generate_shape_op_pass.cc
  paddle/cinn/hlir/framework/op.h
  paddle/cinn/hlir/framework/pir/op_lowering_impl.cc
Labels: contributor, HappyOpenSource Pro

#66977 [PIR] Fix layout transformation
  paddle/fluid/framework/new_executor/instruction/onednn/onednn_instruction.cc
  paddle/phi/infermeta/binary.cc
  paddle/phi/infermeta/binary.h
  test/ir/pir/fused_pass/onednn/test_onednn_placement.py
Labels: contributor

#67008 【Infer Symbolic Shape [BUAA] No.93 & 98 & 105 】sqrt & silu & view_dtype
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/same_operands_result.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/same_operands_result.h
  paddle/phi/ops/yaml/ops.yaml
Labels: contributor, HappyOpenSource Pro

#66799 【BUAA】【Error Message No.22,23】Update error massage of paddle\cinn\hlir\framework\op_strategy.cc, paddle\cinn\hlir\op\contrib\assert_true.cc and other 3 files
  paddle/cinn/hlir/framework/op_strategy.cc
  paddle/cinn/hlir/framework/schedule.h
  paddle/cinn/hlir/framework/visualize_helper.h
  paddle/cinn/hlir/op/contrib/assert_true.cc
  paddle/cinn/hlir/op/contrib/cholesky.cc
Labels: contributor, HappyOpenSource Pro

#66796 【Hackathon 6th Fundable Projects 3 No.52】[fluid_ops] c_sync_calc_stream
  paddle/fluid/operators/collective/c_sync_calc_stream_op.cc
  paddle/fluid/operators/collective/c_sync_calc_stream_op.cu.cc
  paddle/fluid/operators/collective/c_sync_calc_stream_op.h
  paddle/fluid/operators/collective/c_sync_calc_stream_op.kps
  paddle/fluid/operators/collective/c_sync_calc_stream_op_xpu.cc
  paddle/fluid/pir/dialect/operator/utils/utils.cc
  paddle/phi/kernels/gpu/sync_calc_stream_kernel.cu
  paddle/phi/kernels/impl/sync_calc_stream_kernel_impl.h
  paddle/phi/kernels/kps/sync_calc_stream_kernel.kps
  paddle/phi/kernels/xpu/sync_calc_stream_kernel.cc
  paddle/phi/ops/yaml/op_compat.yaml
  paddle/phi/ops/yaml/ops.yaml
Labels: PaddlePaddle Hackathon, contributor

#67100 [Docathon][Add API Legend No.5] [BUAA] Sync the legend of the concat API to the English documentation
  python/paddle/tensor/manipulation.py
Labels: contributor, HappyOpenSource Pro

#67119 [Typing][PEP585 Upgrade][BUAA][21-30] Use standard collections for type hints for 9 files in `python/paddle/`
  python/paddle/base/framework.py
  python/paddle/batch.py
  python/paddle/decomposition/recompute.py
  python/paddle/distributed/auto_parallel/api.py
  python/paddle/distributed/auto_parallel/interface.py
  python/paddle/distributed/auto_tuner/recorder.py
  python/paddle/distributed/auto_tuner/utils.py
  python/paddle/distributed/checkpoint/metadata.py
  python/paddle/distributed/checkpoint/utils.py
Labels: contributor, HappyOpenSource Pro

#67089 [Typing][C-135,C-136,C-137] Add type annotations for `python/paddle/distributed/fleet/{layers/mpu/mp_ops,recompute/{recompute,recompute_hybrid}}.py`
  python/paddle/distributed/fleet/layers/mpu/mp_ops.py
  python/paddle/distributed/fleet/recompute/recompute.py
  python/paddle/distributed/fleet/recompute/recompute_hybrid.py
Labels: PaddlePaddle Hackathon, contributor

#67125 [CodeStyle][Ruff][BUAA][C-[21-30]] Fix Ruff `RSE102` diagnostic for 10 files in `python/paddle/` and `test/`
  python/paddle/utils/environments.py
  test/book/notest_understand_sentiment.py
  test/deprecated/book/test_recognize_digits_deprecated.py
  test/deprecated/book/test_word2vec_book_deprecated.py
  test/deprecated/legacy_test/test_multiprocess_reader_exception.py
  test/distributed_passes/auto_parallel_pass_test_base.py
  test/distributed_passes/dist_pass_test_base.py
  test/ir/inference/auto_scan_test.py
  test/ir/inference/test_trt_convert_prelu.py
  test/legacy_test/check_nan_inf_base.py
Labels: contributor

#67111 [PIR] Migrate Sparse API unary op No.6
  python/paddle/sparse/unary.py
  test/legacy_test/test_sparse_unary_op.py
Labels: contributor

#67110 [PIR] Migrate Sparse API max_pool3d No.5
  python/paddle/sparse/nn/functional/pooling.py
  test/legacy_test/test_sparse_pooling_op.py
Labels: contributor

#67069 [Typing][PEP585 Upgrade][BUAA][51-60] Use standard collections for type hints for 10 files in `python/paddle/`
  python/paddle/distribution/uniform.py
  python/paddle/distribution/variable.py
  python/paddle/fft.py
  python/paddle/framework/random.py
  python/paddle/hapi/callbacks.py
  python/paddle/hapi/hub.py
  python/paddle/hapi/model_summary.py
  python/paddle/incubate/asp/asp.py
  python/paddle/incubate/autograd/functional.py
Labels: contributor, HappyOpenSource Pro

#67145 [CodeStyle][Ruff][BUAA][G-[191-200]] Fix Ruff `RUF005` diagnostic for 10 files in `test/legacy_test/`
  test/legacy_test/test_asgd_op.py
  test/legacy_test/test_attn_bias.py
  test/legacy_test/test_cholesky_op.py
  test/legacy_test/test_conv1d_layer.py
  test/legacy_test/test_conv1d_transpose_layer.py
  test/legacy_test/test_conv2d_layer.py
  test/legacy_test/test_conv2d_transpose_layer.py
  test/legacy_test/test_conv3d_layer.py
  test/legacy_test/test_conv3d_transpose_layer.py
  test/legacy_test/test_conv_transpose_nn_grad.py
Labels: contributor

#67122 [CodeStyle][Ruff][BUAA][G-[201-208]] Fix ruff `RUF005` diagnostic for 8 files in `python/test/legacy_test/`
  test/legacy_test/test_crf_decoding_op.py
  test/legacy_test/test_cross_entropy_op.py
  test/legacy_test/test_dataset_consistency_inspection.py
  test/legacy_test/test_deform_conv2d.py
  test/legacy_test/test_detection.py
  test/legacy_test/test_distribute_fpn_proposals_op.py
  test/legacy_test/test_dygraph_spectral_norm.py
  test/legacy_test/test_dygraph_weight_norm.py
Labels: contributor

#67137 [CodeStyle][Ruff][BUAA][G-[257-262]] Fix Ruff `RUF005` diagnostic for 6 files in `test/xpu/` and `tools/`
  test/xpu/test_repeat_interleave_op_xpu.py
  test/xpu/test_scatter_nd_add_op_xpu.py
  test/xpu/test_sequence_conv_op_xpu.py
  test/xpu/test_sigmoid_cross_entropy_with_logits_op_xpu.py
  test/xpu/test_swiglu_op_xpu.py
  tools/count_api_without_core_ops.py
Labels: contributor

#67126 [CodeStyle][Ruff][BUAA][C-[31-37]] Fix Ruff `RSE102` diagnostic for 7 files in `test/legacy_test/`
  test/legacy_test/check_nan_inf_base_dygraph.py
  test/legacy_test/distributed_fused_lamb_test_base.py
  test/legacy_test/fleet_meta_optimizer_base.py
  test/legacy_test/test_imperative_optimizer.py
  test/legacy_test/test_imperative_optimizer_v2.py
  test/legacy_test/test_logcumsumexp_op.py
  test/legacy_test/test_nan_inf.py
Labels: contributor

#67066 【Hackathon 6th Fundable Projects 3 No.267】 [fluid_ops] partial_send
  paddle/fluid/operators/collective/partial_send_op.cc
  paddle/fluid/operators/collective/partial_send_op.cu.cc
  paddle/fluid/operators/collective/partial_send_op.h
  paddle/fluid/pir/dialect/operator/utils/utils.cc
  paddle/phi/kernels/cpu/partial_send_kernel.cc
  paddle/phi/kernels/gpu/partial_send_kernel.cu
Labels: contributor

#67012 【Hackathon 6th Fundable Projects 3 No.264】 [fluid_ops] partial_allgather
  paddle/fluid/operators/collective/partial_allgather_op.cc
  paddle/fluid/operators/collective/partial_allgather_op.cu.cc
  paddle/fluid/operators/collective/partial_allgather_op.h
  paddle/phi/kernels/cpu/partial_allgather_kernel.cc
  paddle/phi/kernels/gpu/partial_allgather_kernel.cu
Labels: PaddlePaddle Hackathon, contributor

#67135 [Typing][PEP585 Upgrade][BUAA][31-40] Use standard collections for type hints for 10 files in `python/paddle/distributed` and `python/paddle/distribution`
  python/paddle/distributed/fleet/meta_parallel/pipeline_parallel.py
  python/paddle/distributed/parallel.py
  python/paddle/distributed/passes/auto_parallel_gradient_merge.py
  python/paddle/distributed/passes/auto_parallel_master_grad.py
  python/paddle/distribution/bernoulli.py
  python/paddle/distribution/beta.py
  python/paddle/distribution/categorical.py
  python/paddle/distribution/cauchy.py
  python/paddle/distribution/dirichlet.py
  python/paddle/distribution/distribution.py
Labels: contributor, HappyOpenSource Pro

#67050 【Error Message No. 5, 6】【BUAA】
  paddle/cinn/hlir/op/elementwise.cc
  paddle/cinn/hlir/op/transform.cc
Labels: contributor, HappyOpenSource Pro

#66963 【Error Message No. 221,225,286,288, BUAA】将CHECK宏进行替换
  test/auto_parallel/custom_op/custom_relu_op.cu
  test/cpp_extension/custom_relu_forward.cu
  test/custom_op/custom_inplace.cu
  test/custom_op/custom_relu_op.cu
Labels: contributor, HappyOpenSource Pro

#67016 [Typing][PEP585 Upgrade][BUAA][161-170] Use standard collections for type hints for 10 uts in `test/ir/inference/`
  test/ir/inference/test_trt_convert_cumsum.py
  test/ir/inference/test_trt_convert_deformable_conv.py
  test/ir/inference/test_trt_convert_depthwise_conv2d.py
  test/ir/inference/test_trt_convert_depthwise_conv2d_transpose.py
  test/ir/inference/test_trt_convert_dropout.py
  test/ir/inference/test_trt_convert_einsum.py
  test/ir/inference/test_trt_convert_elementwise.py
  test/ir/inference/test_trt_convert_elementwiseadd_transpose.py
  test/ir/inference/test_trt_convert_emb_eltwise_layernorm.py
  test/ir/inference/test_trt_convert_equal.py
Labels: contributor, HappyOpenSource Pro

#66855 Replace phi::errors to ::common::errors in cinn [fluid_ops]
  paddle/cinn/adt/generate_map_expr.cc
  paddle/cinn/adt/get_sub_reshape_dim_ranges.cc
  paddle/cinn/adt/igroup.cc
  paddle/cinn/adt/igroup.h
  paddle/cinn/adt/inline_translator.h
  paddle/cinn/adt/naive_bidirection_equation_generator.cc
  paddle/cinn/adt/naive_op_equation_context.cc
  paddle/cinn/adt/schedule_mesh.cc
  paddle/cinn/backends/function_prototype.cc
  paddle/cinn/backends/llvm/codegen_llvm.h
  paddle/cinn/backends/llvm/codegen_x86.cc
  paddle/cinn/backends/llvm/llvm_intrin_rule.h
  paddle/cinn/backends/llvm/llvm_util.cc
  paddle/cinn/backends/llvm/simple_jit.cc
  paddle/cinn/backends/nvrtc/nvrtc_util.cc
  paddle/cinn/common/broadcast_tree.cc
  paddle/cinn/common/cas.h
  paddle/cinn/common/cuda_test_helper.cc
  paddle/cinn/common/dim_expr_converter.cc
  paddle/cinn/common/graph_utils.cc
  paddle/cinn/common/graph_utils.h
  paddle/cinn/common/target.cc
  paddle/cinn/lang/builtin.cc
  paddle/cinn/lang/compute.cc
  paddle/cinn/lang/lower_impl.h
  paddle/cinn/lang/lower_tensor_group.cc
  paddle/cinn/optim/cast_bool_to_int8.cc
  paddle/cinn/optim/check_tensor_buffer_map.cc
  paddle/cinn/optim/eliminate_common_factor_of_local_index.cc
  paddle/cinn/optim/eliminate_common_global_memory_read.cc
  paddle/cinn/optim/fold_cinn_call_arguments.cc
  paddle/cinn/optim/insert_debug_log_callee.cc
  paddle/cinn/optim/ir_simplify.cc
  paddle/cinn/optim/lower_function_call_bind_vars.cc
  paddle/cinn/optim/lower_intrin.cc
  paddle/cinn/optim/map_extern_call.cc
  paddle/cinn/optim/optimize.cc
  paddle/cinn/optim/remove_schedule_block.cc
  paddle/cinn/optim/replace_call_with_expr.cc
  paddle/cinn/optim/replace_cross_thread_reduction.cc
  paddle/cinn/optim/resize_buffer.cc
  paddle/cinn/optim/schedule_block_dce.cc
  paddle/cinn/optim/trans_buffer_with_dynamic_shape.cc
  paddle/cinn/optim/transform_polyfor_to_for.cc
  paddle/cinn/optim/var_mod_simplify.cc
  paddle/cinn/optim/vectorize_loops.cc
  paddle/cinn/poly/ast_gen.cc
  paddle/cinn/poly/isl_utils.cc
  paddle/cinn/poly/poly_scheduler.cc
  paddle/cinn/poly/schedule.cc
  paddle/cinn/pybind/ir/ir_context.cc
  paddle/cinn/pybind/ir/ir_context.h
  paddle/cinn/runtime/cpu/host_intrinsics.cc
  paddle/cinn/utils/dot_lang.cc
Labels: contributor, HappyOpenSource

#67128 [CodeStyle][Ruff][BUAA][G-6,G-7,G-8,G-9,G-10] Fix ruff `RUF005` diagnostic for 5 files in `python/paddle/`
  python/paddle/__init__.py
  python/paddle/audio/functional/window.py
  python/paddle/base/backward.py
  python/paddle/base/lod_tensor.py
  python/paddle/dataset/imikolov.py
Labels: contributor, HappyOpenSource Pro

#66810 [auto parallel] Support 1F1B for PIR
  python/paddle/distributed/auto_parallel/constants.py
  python/paddle/distributed/auto_parallel/static/engine.py
  python/paddle/distributed/auto_parallel/static/pir_pass.py
  python/paddle/distributed/auto_parallel/static/utils.py
  python/paddle/distributed/passes/auto_parallel_gradient_merge.py
  python/paddle/distributed/passes/pipeline_scheduler_pass/pipeline_1f1b.py
  test/auto_parallel/pir/1F1B_pass_unittest_pir.py
  test/auto_parallel/pir/CMakeLists.txt
  test/auto_parallel/pir/test_pipeline_scheduler_1f1b_pir.py
  test/auto_parallel/pir/test_pir_1f1b_plan.py
Labels: contributor

#66930 【Infer Symbolic Shape BUAA No.42-44】Add ops
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/multiary_infer_sym.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/multiary_infer_sym.h
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/unary_infer_sym.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/unary_infer_sym.h
  paddle/phi/ops/yaml/ops.yaml
Labels: contributor, HappyOpenSource Pro

#67048 【Error Message No. 95,133,220,223,225,240,279,290-291,386,388,398-400,402,411,412】[BUAA]将CHECK宏进行替换
  paddle/cinn/ir/buffer.h
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/infer_sym_slice_utils.h
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/unary_infer_sym.cc
  paddle/fluid/pir/dialect/operator/ir/op_dialect.cc
  paddle/phi/kernels/fusion/xpu/blha_get_max_len_kernel.cc
  paddle/phi/kernels/fusion/xpu/weight_only_linear_kernel_xpu.cc
  paddle/phi/kernels/gpu/shuffle_batch_utils.h
  paddle/pir/src/dialect/shape/transforms/shape_optimization_pass.cc
  test/auto_parallel/custom_op/custom_relu_op.cc
  test/cpp/eager/data_structure_tests/grad_node_info_test.cc
  test/cpp/eager/data_structure_tests/tensor_wrapper_test.cc
  test/cpp_extension/mix_relu_and_extension.cc
  test/deprecated/cpp/inference/analysis/analyzer_tester.cc
  test/deprecated/cpp/inference/api/analyzer_dam_tester.cc
  test/deprecated/cpp/inference/api/analyzer_rnn2_tester.cc
  test/deprecated/cpp/inference/api/analyzer_text_classification_tester.cc
  test/ipu/custom_ops/leaky_relu_cpu.cc
Labels: contributor, HappyOpenSource Pro

#67153 [CodeStyle][Ruff][BUAA][G-[225-232]] Fix ruff `RUF005` diagnostic for 8 files in `python/test/legacy_test/`
  test/legacy_test/test_imperative_named_members.py
  test/legacy_test/test_imperative_ocr_attention_model.py
  test/legacy_test/test_index_add_op.py
  test/legacy_test/test_index_select_op.py
  test/legacy_test/test_layers.py
  test/legacy_test/test_lu_op.py
  test/legacy_test/test_lu_unpack_op.py
  test/legacy_test/test_matmul_op_with_head.py
Labels: contributor, HappyOpenSource Pro

#67143 [Typing][C-83] Add type annotations for `python/paddle/incubate/nn/layer/fused_ec_moe.py`
  python/paddle/incubate/nn/layer/fused_ec_moe.py
Labels: contributor, HappyOpenSource

#67127 [CodeStyle][Ruff][BUAA][G-1,G-2,G-3,G-4,G-5] Fix ruff `RUF005` diagnostic for 5 files in `python/paddle/`
  paddle/fluid/pir/dialect/op_generator/op_gen.py
  paddle/fluid/primitive/codegen/gen.py
  paddle/phi/api/generator/tensor_operants_gen.py
Labels: contributor, HappyOpenSource Pro

#67130 [CodeStyle][Ruff][BUAA][G-[209-216]] Fix ruff `RUF005` diagnostic for 8 files in `python/test/legacy_test/`
  test/legacy_test/test_eigh_op.py
  test/legacy_test/test_eigvalsh_op.py
  test/legacy_test/test_embedding_deterministic.py
  test/legacy_test/test_fake_quantize_op.py
  test/legacy_test/test_flash_attention.py
  test/legacy_test/test_fleet_executor.py
  test/legacy_test/test_fleet_executor_origin_scheduler.py
  test/legacy_test/test_fleet_executor_with_task_nodes.py
Labels: contributor, HappyOpenSource Pro

#67139 [CodeStyle][Ruff][BUAA][G-[217-224]] Fix ruff `RUF005` diagnostic for 8 files in `python/test/legacy_test/`
  test/legacy_test/test_frame_op.py
  test/legacy_test/test_functional_conv2d.py
  test/legacy_test/test_functional_conv3d.py
  test/legacy_test/test_functional_conv3d_transpose.py
  test/legacy_test/test_fused_attention_no_dropout.py
  test/legacy_test/test_graph_send_ue_recv_op.py
  test/legacy_test/test_group_norm_op.py
  test/legacy_test/test_householder_product.py
Labels: contributor, HappyOpenSource Pro
