Repository PaddlePaddle/Paddle, pull requests merged in 2024-04, with the labels that each got.

#63139 Fix Symetric Symmetric
  python/paddle/incubate/distributed/fleet/parameter_server/distribute_transpiler/__init__.py
  python/paddle/incubate/distributed/fleet/parameter_server/pslib/__init__.py
  python/paddle/incubate/distributed/fleet/role_maker.py
  test/legacy_test/test_fleet_rolemaker.py
  test/legacy_test/test_fleet_rolemaker_2.py
Labels: contributor, HappyOpenSource

#63133 [HACKATHON 6th] Fix clang-12 support
  cmake/flags.cmake
  paddle/fluid/framework/ir/generate_pass_tester.cc
  paddle/fluid/framework/ir/mkldnn/cpu_quantize_squash_pass_tester.cc
  paddle/fluid/framework/ir/mkldnn/params_quantization_mkldnn_pass_tester.cc
  paddle/fluid/inference/api/analysis_predictor.cc
  paddle/fluid/inference/api/details/zero_copy_tensor_test.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/unary_infer_sym.cc
  paddle/fluid/pir/dialect/operator/ir/op_dialect.cc
  test/cpp/fluid/framework/new_executor/workqueue_test.cc
  test/cpp/inference/api/analyzer_bert_tester.cc
  test/cpp/inference/api/analyzer_mmp_tester.cc
  test/cpp/inference/api/lite_mul_model_test.cc
  test/cpp/inference/api/mkldnn_quantizer_tester.cc
  test/cpp/new_executor/standalone_executor_test.cc
  test/cpp/pir/core/ir_parser_test.cc
  test/cpp/prim/test_static_prim.cc
Labels: contributor

#62533 improve the performence of divide_double_grad
  paddle/fluid/operators/elementwise/elementwise_div_op.cc
  paddle/fluid/operators/ops_signature/elementwise_sig.cc
  paddle/fluid/pir/dialect/operator/ir/ops_backward.yaml
  paddle/phi/api/yaml/legacy_backward.yaml
  paddle/phi/kernels/elementwise_divide_grad_kernel.h
  paddle/phi/kernels/funcs/common_shape.h
  paddle/phi/kernels/impl/elementwise_grad_kernel_impl.h
  test/cpp/fluid/elementwise/test_elementwise_div_grad_grad.cc
  test/cpp/fluid/elementwise/test_elementwise_op_grad_grad.h
Labels: contributor

#63128 修复Sequential英文文档
  python/paddle/nn/layer/container.py
Labels: contributor, HappyOpenSource

#63121 paddle.summary 英文文档修改
  python/paddle/hapi/model_summary.py
Labels: contributor, HappyOpenSource

#62958 [PIR] support `matrix_norm` and fix backward redundant cast
  python/paddle/tensor/linalg.py
  test/legacy_test/test_zero_dim_sundry_static_api_part1.py
  test/legacy_test/test_zero_dim_sundry_static_api_part4.py
Labels: contributor

#63144 [common] fix #63106 Incorrect segmentation
  paddle/common/enforce.cc
  test/legacy_test/test_cpp_error_msg.py
Labels: contributor

#62292 feat(custom device): enable memory event and stat record for custom device using FLAGS_custom_device_mem_record.
  paddle/common/flags.cc
  paddle/fluid/memory/allocation/custom_allocator.cc
  paddle/fluid/memory/allocation/system_allocator.cc
Labels: contributor, heco

#63092 Fix spece spec, etc
  python/cinn/auto_schedule/cost_model/xgb_cost_model.py
  python/paddle/distributed/auto_parallel/static/operators/dist_eltwise.py
  python/paddle/distributed/auto_parallel/static/operators/dist_matmul.py
  python/paddle/distributed/auto_parallel/static/operators/dist_reduce_sum_p.py
  python/paddle/distributed/fleet/fleet.py
  python/paddle/distributed/fleet/fleet_executor_utils.py
  python/paddle/distributed/fleet/launch_utils.py
  test/legacy_test/test_merged_momentum_op.py
  test/legacy_test/test_momentum_op.py
  test/legacy_test/test_mul_op.py
  test/legacy_test/test_multi_label_soft_margin_loss.py
  test/legacy_test/test_multinomial_op.py
  test/legacy_test/test_multiprocess_dataloader_dataset.py
  test/legacy_test/test_multiprocess_dataloader_exception.py
  test/legacy_test/test_nan_inf.py
  test/mkldnn/test_elementwise_sub_onednn_op.py
  test/mkldnn/test_lrn_mkldnn_op.py
  test/mkldnn/test_matmul_v2_mkldnn_op.py
  test/white_list/check_op_sequence_instance_0_input_white_list.py
  test/white_list/compile_vs_runtime_white_list.py
  test/xpu/test_adamw_op_xpu.py
  test/xpu/test_merged_momentum_op_xpu_base.py
  test/xpu/test_reduce_min_op_xpu.py
Labels: contributor, HappyOpenSource

#63147 Fix unity_build_rule.cmake files
  paddle/fluid/operators/amp/unity_build_rule.cmake
  paddle/fluid/operators/controlflow/unity_build_rule.cmake
  paddle/fluid/operators/fused/unity_build_rule.cmake
  paddle/fluid/operators/metrics/unity_build_rule.cmake
  paddle/fluid/operators/prim_ops/unity_build_rule.cmake
  paddle/fluid/operators/reduce_ops/unity_build_rule.cmake
Labels: contributor, HappyOpenSource

#63162 Rename operators/mkldnn operators/onednn
  cmake/operators.cmake
  paddle/fluid/operators/fused/onednn/fusion_lstm_onednn_op.cc
  paddle/fluid/operators/fused/onednn/fusion_rnn_onednn.h
  paddle/fluid/operators/fused/onednn/multi_gru_onednn_op.cc
  paddle/fluid/operators/onednn/interpolate_onednn_op.cc
  paddle/fluid/operators/onednn/lrn_onednn_op.cc
  paddle/fluid/operators/onednn/matmul_onednn_op.cc
  paddle/fluid/operators/onednn/quantize_onednn_op.cc
  paddle/fluid/operators/onednn/requantize_onednn_op.cc
  paddle/fluid/operators/onednn/reshape_onednn_op.cc
  paddle/fluid/operators/onednn/shuffle_channel_onednn_op.cc
  paddle/fluid/operators/onednn/transpose_onednn_op.cc
  paddle/fluid/operators/unity_build_rule.cmake
  tools/enforce/count_enforce_by_dir.sh
Labels: PaddlePaddle Hackathon, contributor

#62951 [CINN] optimize symbol shape dim expr substitute in lower_cinn_fusion…
  paddle/cinn/hlir/dialect/operator/transforms/lowering_pass/collect_sym_expr.cc
Labels: contributor

#63163 【Hackathon 6th Fundable Projects No.3】part Remove fluid/operators/amp -part
  paddle/fluid/operators/CMakeLists.txt
  paddle/fluid/operators/amp/CMakeLists.txt
  paddle/fluid/operators/amp/alloc_float_status_op.cc
  paddle/fluid/operators/amp/clear_float_status_op.cc
  paddle/fluid/operators/amp/get_float_status_op.cc
  paddle/fluid/operators/amp/unity_build_rule.cmake
Labels: PaddlePaddle Hackathon, contributor

#63134 API improvement for nn.initializer.XavierNormal and nn.initializer.XavierUniform 易用性提升
  python/paddle/nn/initializer/xavier.py
  test/legacy_test/test_initializer.py
Labels: contributor

#63193 【Error Message No. 30】paddle/cinn/pybind/*
  paddle/cinn/pybind/framework.cc
  paddle/cinn/pybind/frontend.cc
  paddle/cinn/pybind/ir/ir.cc
Labels: contributor, HappyOpenSource

#63199 Rename mkldnn onednn in paddle/cinn
  paddle/cinn/hlir/op/nn.cc
  paddle/cinn/hlir/pe/nn.cc
  paddle/cinn/hlir/pe/nn.h
  paddle/cinn/runtime/cpu/CMakeLists.txt
  paddle/cinn/runtime/cpu/onednn_math.cc
  paddle/cinn/runtime/cpu/onednn_math.h
  paddle/cinn/runtime/cpu/onednn_math_test.cc
  paddle/cinn/runtime/cpu/use_extern_funcs.h
Labels: PaddlePaddle Hackathon, contributor

#63202 Update CMakeLists.txt
  test/quantization/CMakeLists.txt
Labels: contributor, HappyOpenSource

#63200 Update build.sh
  tools/cinn/build.sh
Labels: PaddlePaddle Hackathon, contributor

#62876 API improvement for paddle.linalg.svd_lowrank
  python/paddle/linalg.py
  python/paddle/tensor/__init__.py
  python/paddle/tensor/linalg.py
  test/legacy_test/test_svd_lowrank.py
Labels: contributor

#63185 [PIR] reopen `TestReduceAPI.test_static_reduce` UT
  python/paddle/autograd/backward_utils.py
  test/legacy_test/test_zero_dim_reduce_api.py
Labels: contributor

#63257 Replace fluid/operators/eigen/eigen_function.h
  paddle/fluid/operators/crop_op.h
  paddle/fluid/operators/expand_as_v2_op.h
  paddle/fluid/operators/expand_op.h
  paddle/fluid/operators/expand_v2_op.h
  paddle/fluid/operators/l1_norm_op.h
  paddle/fluid/operators/minus_op.h
  paddle/fluid/operators/set_value_op.h
  paddle/fluid/operators/svd_helper.h
  paddle/fluid/pybind/tensor_py.h
Labels: contributor

#63222 【Hackthon 6th No. 10】Upgrade isinf to support int8 int16 uint8 -part
  paddle/phi/kernels/cpu/isfinite_kernel.cc
  paddle/phi/kernels/gpu/isfinite_kernel.cu
  python/paddle/tensor/math.py
  test/legacy_test/test_isfinite_v2_op.py
Labels: PaddlePaddle Hackathon, contributor

#63204 【Hackthon 6th No.10】Upgrade signbit -part
  python/paddle/tensor/math.py
  test/legacy_test/test_signbit.py
Labels: PaddlePaddle Hackathon, contributor

#63266 Remove fluid xpu_api_wrapper.h
  paddle/fluid/operators/matmul_op_xpu.cc
  paddle/fluid/operators/xpu_api_wrapper.h
Labels: contributor, HappyOpenSource

#62689 add group_norm_silu_xpu_fuse
  paddle/fluid/framework/ir/CMakeLists.txt
  paddle/fluid/framework/ir/pass.cc
  paddle/fluid/framework/ir/xpu/group_norm_silu_xpu_fuse_pass.cc
  paddle/fluid/inference/api/paddle_pass_builder.cc
  paddle/phi/api/yaml/fused_ops.yaml
  paddle/phi/backends/xpu/xpu1_op_list.cc
  paddle/phi/backends/xpu/xpu2_op_list.cc
  paddle/phi/backends/xpu/xpu3_op_list.cc
  paddle/phi/infermeta/fusion.cc
  paddle/phi/infermeta/fusion.h
  paddle/phi/kernels/fusion/xpu/group_norm_silu_xpu_kernel.cc
  test/ir/inference/test_xpu_group_norm_silu_pass.py
Labels: contributor

#63214 add WITH_NIGHTLY_BUILD option for windows build task
  paddle/scripts/paddle_build.bat
Labels: contributor

#62863 【PIR OpTest Fix No.30】 test_assign_pos_op
  paddle/fluid/pir/dialect/op_generator/ops_api_gen.py
  paddle/fluid/pir/dialect/operator/ir/ops.yaml
  paddle/phi/api/yaml/op_compat.yaml
  paddle/phi/infermeta/ternary.cc
  paddle/phi/infermeta/ternary.h
  test/white_list/pir_op_test_no_check_list
  test/white_list/pir_op_test_white_list
Labels: contributor, HappyOpenSource

#63013 【PIR Dist Op Reg No.11】 reg dgc_momentum
  paddle/fluid/pir/dialect/op_generator/ops_api_gen.py
  paddle/fluid/pir/dialect/operator/ir/ops.yaml
  paddle/phi/api/yaml/op_compat.yaml
  test/ir/pir/translator/CMakeLists.txt
  test/ir/pir/translator/test_dgc_momentum_translator.py
Labels: contributor, HappyOpenSource

#63242 Remove fluid TrilTriu
  paddle/fluid/operators/svd_helper.h
Labels: PaddlePaddle Hackathon, contributor

#63276 [Prim][Pir] Fix the bug in test_sub_graph73 when open prim setting
  paddle/phi/infermeta/ternary.cc
  test/ir/pir/cinn/sub_graphs/test_sub_graph_73.py
Labels: contributor

#63201 Rename tracer_mkldnn_ops_on tracer_onednn_ops_on
  paddle/common/flags.cc
  paddle/fluid/imperative/tracer.cc
  test/mkldnn/check_flags_mkldnn_ops_on_off.py
  test/mkldnn/test_flags_mkldnn_ops_on_off.py
Labels: contributor, HappyOpenSource

#63267 Replace include fluid utils.h
  paddle/fluid/operators/partial_concat_op.h
  paddle/fluid/operators/set_value_op.h
  paddle/fluid/operators/split_op.h
  paddle/fluid/operators/unbind_op.h
  paddle/fluid/pybind/eager_utils.cc
  paddle/fluid/pybind/imperative.cc
  paddle/fluid/pybind/uva_utils.h
Labels: contributor, HappyOpenSource

#63221 fix nanmedian cpu kernel crash 易用性提升
  paddle/phi/kernels/cpu/nanmedian_kernel.cc
  test/legacy_test/test_nanmedian.py
Labels: contributor

#63141 [OneDNN][PIR] squeeze_transpose pass
  paddle/fluid/inference/api/paddle_pass_builder.cc
  paddle/fluid/pir/transforms/onednn/squeeze_transpose_onednn_fuse_pass.cc
  paddle/fluid/pir/transforms/onednn/squeeze_transpose_onednn_fuse_pass.h
  paddle/fluid/pir/transforms/passes.h
  test/ir/pir/fused_pass/onednn/test_squeeze_transpose_onednn_pass.py
Labels: Intel, contributor

#63264 Replace IR_ENFORCE - part
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/unary_infer_sym.cc
  paddle/fluid/pir/dialect/operator/ir/api_builder.cc
  paddle/fluid/pir/dialect/operator/ir/control_flow_op.cc
  paddle/fluid/pir/dialect/operator/ir/manual_onednn_op.cc
  paddle/fluid/pir/dialect/operator/ir/manual_op.cc
  paddle/pir/src/core/block.cc
  paddle/pir/src/core/ir_printer.cc
  paddle/pir/src/core/operation.cc
  paddle/pir/src/core/parser/ir_parser.cc
  paddle/pir/src/core/region.cc
  paddle/pir/src/dialect/control_flow/ir/cf_interface.cc
  paddle/pir/src/dialect/control_flow/ir/cf_op.cc
  paddle/pir/src/dialect/shape/utils/dim_expr_builder.cc
  paddle/pir/src/dialect/shape/utils/shape_analysis.cc
  paddle/pir/src/pass/pass.cc
  paddle/pir/src/pass/print_statistics.cc
  paddle/pir/src/pattern_rewrite/pattern_match.cc
  test/cpp/pir/core/add_dialect_parser_test.cc
  test/cpp/pir/pass/pass_manager_test.cc
  test/cpp/pir/pattern_rewrite/pattern_rewrite_test.cc
Labels: contributor, HappyOpenSource

#63207 【complex op No.25】add complex support for cross
  paddle/phi/kernels/cpu/cross_grad_kernel.cc
  paddle/phi/kernels/cpu/cross_kernel.cc
  paddle/phi/kernels/gpu/cross_grad_kernel.cu
  paddle/phi/kernels/gpu/cross_kernel.cu
  python/paddle/tensor/linalg.py
  test/legacy_test/test_cross_op.py
Labels: contributor

#63051 [OneDNN][PIR] Add depthwise_conv_onednn_pass
  paddle/fluid/inference/api/paddle_pass_builder.cc
  paddle/fluid/pir/transforms/onednn/depthwise_conv_onednn_pass.cc
  paddle/fluid/pir/transforms/onednn/depthwise_conv_onednn_pass.h
  paddle/fluid/pir/transforms/passes.h
  test/ir/pir/fused_pass/onednn/test_pir_depthwise_conv_onednn_pass.py
Labels: Intel, contributor

#61293 【PIR Dist Op Reg No.27】 reg distributed_fused_lamb
  paddle/fluid/pir/dialect/op_generator/ops_api_gen.py
  paddle/fluid/pir/dialect/operator/ir/ops.yaml
  paddle/phi/api/yaml/op_compat.yaml
  test/ir/pir/translator/CMakeLists.txt
  test/ir/pir/translator/test_distributed_fused_lamb.py
Labels: contributor, HappyOpenSource

#63234 Fix shedule schedule, etc
  paddle/cinn/ir/schedule/ir_schedule.h
  paddle/common/flags.cc
  paddle/fluid/eager/auto_code_generator/generator/eager_gen.py
  paddle/fluid/framework/new_executor/workqueue/event_count.h
  paddle/fluid/primitive/codegen/decomp_gen.py
  paddle/phi/kernels/gpu/cross_entropy_kernel.cu
  paddle/pir/include/pass/analysis_manager.h
  paddle/pir/include/pattern_rewrite/pattern_match.h
  python/paddle/incubate/autograd/composite_rules.py
  python/paddle/incubate/autograd/functional.py
  python/paddle/incubate/autograd/primapi.py
  python/paddle/incubate/autograd/primrules.py
  python/paddle/incubate/autograd/primx.py
  python/paddle/incubate/distributed/utils/io/dist_save.py
  python/paddle/incubate/nn/functional/block_multihead_attention.py
  python/paddle/incubate/optimizer/pipeline.py
  python/paddle/static/quantization/quant2_int8_onednn_pass.py
  test/cpp/fluid/framework/tensor_test.cc
  test/cpp/fluid/math/selected_rows_functor_test.cc
  test/cpp/fluid/memory/buddy_allocator_test.cc
  test/cpp/fluid/memory/mmap_allocator_test.cc
  test/cpp/fluid/platform/device/custom/custom_device_test.cc
  test/legacy_test/test_fleet_rolemaker.py
  test/legacy_test/test_fleet_rolemaker_init.py
Labels: contributor, HappyOpenSource

#62988 [PIR-3][33-35] Adapt `weight` api
  python/paddle/nn/quant/quantized_linear.py
  test/quantization/test_weight_only_linear.py
Labels: contributor

#62781 【PIR Dist Op Reg No.28】 reg dgc
  paddle/fluid/pir/dialect/op_generator/ops_api_gen.py
  paddle/fluid/pir/dialect/operator/ir/ops.yaml
  paddle/phi/api/yaml/op_compat.yaml
  test/ir/pir/translator/CMakeLists.txt
  test/ir/pir/translator/test_dgc_translator.py
Labels: contributor, HappyOpenSource

#63345 [eager][utils] fix `GRAD_SLOT_META_TEMPLATE` fmt error
  paddle/fluid/eager/utils.cc
Labels: contributor

#63292 add expand op merge pass and integrate with reshape
  paddle/cinn/hlir/dialect/operator/transforms/add_cinn_pass.cc
  paddle/cinn/hlir/dialect/operator/transforms/fold_manipulation_ops_pass.cc
  paddle/cinn/hlir/dialect/operator/transforms/fold_manipulation_ops_pass.h
  test/ir/pir/cinn/symbolic/test_cinn_merge_expand.py
Labels: contributor

#63233 Replace WITH_MKLDNN WITH_ONEDNN
  cmake/cinn.cmake
  cmake/external/lite.cmake
  cmake/generic.cmake
  cmake/inference_lib.cmake
  cmake/operators.cmake
  cmake/third_party.cmake
  cmake/version.cmake
  paddle/cinn/runtime/cpu/CMakeLists.txt
  paddle/fluid/distributed/index_dataset/CMakeLists.txt
  paddle/fluid/eager/auto_code_generator/CMakeLists.txt
  paddle/fluid/framework/CMakeLists.txt
  paddle/fluid/framework/details/CMakeLists.txt
  paddle/fluid/framework/executor.cc
  paddle/fluid/framework/io/CMakeLists.txt
  paddle/fluid/framework/ir/CMakeLists.txt
  paddle/fluid/framework/new_executor/CMakeLists.txt
  paddle/fluid/framework/paddle2cinn/CMakeLists.txt
  paddle/fluid/inference/api/CMakeLists.txt
  paddle/fluid/memory/CMakeLists.txt
  paddle/fluid/pir/dialect/CMakeLists.txt
  paddle/fluid/pir/drr/CMakeLists.txt
  paddle/fluid/pir/transforms/CMakeLists.txt
  paddle/fluid/platform/CMakeLists.txt
  paddle/fluid/pybind/CMakeLists.txt
  paddle/phi/CMakeLists.txt
  paddle/phi/backends/CMakeLists.txt
  paddle/phi/config.h.in
  paddle/phi/kernels/CMakeLists.txt
  paddle/scripts/paddle_build.sh
  paddle/scripts/submit_local.sh.in
  paddle/testing/CMakeLists.txt
  python/env_dict.py.in
  python/setup.py.in
  python/setup_cinn.py.in
  setup.py
  test/CMakeLists.txt
  test/auto_parallel/custom_op/CMakeLists.txt
  test/auto_parallel/custom_op/utils.py
  test/cpp/fluid/CMakeLists.txt
  test/cpp/inference/api/CMakeLists.txt
  test/cpp/inference/api/int8_mkldnn_quantization.md
  test/ir/inference/CMakeLists.txt
  test/ir/pir/fused_pass/CMakeLists.txt
  test/mkldnn/CMakeLists.txt
  test/quantization/CMakeLists.txt
Labels: contributor, HappyOpenSource

#63251 [Prim] Fix the bug in test_sub_graph_78 when open prim setting
  paddle/fluid/primitive/utils/utils.h
  test/ir/pir/cinn/sub_graphs/test_sub_graph_78.py
Labels: contributor

#63339 [Prim][PIR] support rsqrt op backward in prim pir
  paddle/fluid/prim/api/composite_backward/composite_backward_api.h
  paddle/fluid/primitive/codegen/gen.py
  paddle/fluid/primitive/rule/vjp/details.h
  paddle/phi/api/yaml/backward.yaml
  python/paddle/incubate/autograd/composite_rules.py
  test/legacy_test/test_activation_op.py
Labels: contributor

#62966 【Hackathon 6th No. 27】为 paddle.io.RandomSampler/random_split /Layer.clear_gradients 进行功能增强 -part
  python/paddle/io/dataloader/dataset.py
  python/paddle/io/dataloader/sampler.py
  python/paddle/nn/layer/layers.py
  test/legacy_test/test_batch_sampler.py
  test/legacy_test/test_dataloader_dataset.py
  test/legacy_test/test_layers.py
Labels: PaddlePaddle Hackathon, contributor

#63335 Replace IR_ENFORCE PADDLE_ENFORCE
  paddle/cinn/hlir/dialect/operator/ir/manual_op.cc
  paddle/common/enforce.h
  paddle/fluid/ir_adaptor/translator/utils.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/infer_sym_slice_utils.h
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/unary_infer_sym.cc
  paddle/fluid/pir/dialect/operator/ir/control_flow_op.cc
  paddle/fluid/pir/dialect/operator/ir/manual_onednn_op.cc
  paddle/fluid/pir/dialect/operator/ir/manual_op.cc
  paddle/fluid/pir/dialect/operator/ir/op_dialect.cc
  paddle/pir/src/core/block.cc
  paddle/pir/src/core/block_argument.cc
  paddle/pir/src/core/block_operand.cc
  paddle/pir/src/core/builtin_op.cc
  paddle/pir/src/core/ir_context.cc
  paddle/pir/src/core/op_info_impl.cc
  paddle/pir/src/core/op_operand.cc
  paddle/pir/src/core/op_result.cc
  paddle/pir/src/core/op_trait.cc
  paddle/pir/src/core/operation.cc
  paddle/pir/src/core/parser/ir_parser.cc
  paddle/pir/src/core/region.cc
  paddle/pir/src/core/value.cc
  paddle/pir/src/dialect/shape/utils/dim_expr_builder.cc
  paddle/pir/src/dialect/shape/utils/shape_analysis.cc
  paddle/pir/src/pattern_rewrite/pattern_match.cc
  test/cpp/pir/core/ir_op_test.cc
  test/cpp/pir/tools/test_op.cc
  test/cpp/pir/tools/test_trait.cc
Labels: contributor, HappyOpenSource

#63301 【Error Message No. 12】paddle/cinn/ast_gen_ius/*
  paddle/cinn/ast_gen_ius/ast_gen.cc
Labels: contributor, HappyOpenSource

#63273 【Error Message No. 21】paddle/cinn/dialect/*
  paddle/cinn/hlir/dialect/operator/transforms/group_merge/convert_dynamic_to_static_dim_pass.cc
  paddle/cinn/hlir/dialect/operator/transforms/group_merge/convert_static_dim_to_dynamic_pass.cc
  paddle/cinn/hlir/dialect/operator/transforms/group_merge/group_with_group_merge_pass.cc
  paddle/cinn/hlir/dialect/operator/transforms/lowering_pass/broadcast_with_cf.cc
  paddle/cinn/hlir/dialect/operator/transforms/split_generate_shape_into_shape_ops_pass.cc
Labels: contributor, HappyOpenSource

#63374 Fix brodacast_set broadcast_set, etc
  paddle/cinn/ir/schedule/schedule_base.cc
  paddle/cinn/pybind/frontend.cc
  paddle/fluid/distributed/fleet_executor/compute_interceptor.cc
  paddle/fluid/distributed/fleet_executor/compute_interceptor.h
  paddle/fluid/eager/auto_code_generator/CMakeLists.txt
  paddle/fluid/eager/auto_code_generator/generator/eager_gen.py
  paddle/fluid/operators/controlflow/depend_op.cc
  paddle/fluid/pir/dialect/operator/ir/ops.yaml
  paddle/phi/api/profiler/device_tracer.cc
  paddle/phi/api/profiler/device_tracer.h
  paddle/phi/api/profiler/profiler_helper.h
  paddle/pir/src/dialect/shape/utils/dim_expr_util.cc
  python/paddle/incubate/distributed/fleet/parameter_server/distribute_transpiler/__init__.py
  python/paddle/incubate/distributed/utils/io/dist_save.py
  python/paddle/incubate/optimizer/pipeline.py
Labels: contributor, HappyOpenSource

#63145 [OneDNN][PIR] MKLDNN Conv activation fusion pass
  paddle/fluid/inference/api/paddle_pass_builder.cc
  paddle/fluid/pir/transforms/onednn/conv_activation_onednn_fuse_pass.cc
  paddle/fluid/pir/transforms/onednn/conv_activation_onednn_fuse_pass.h
  paddle/fluid/pir/transforms/passes.h
  test/ir/pir/fused_pass/onednn/test_conv_activation_onednn_fuse_pass.py
Labels: Intel, contributor

#63397 [PIR] fix `FullWithTensor` set backend error
  paddle/phi/kernels/cpu/full_kernel.cc
  paddle/phi/kernels/gpu/full_kernel.cu
  paddle/phi/kernels/selected_rows/full_kernel.cc
  paddle/phi/kernels/xpu/full_kernel.cc
Labels: contributor

#63236 【Hackathon 6th Fundable Projects 3 No.18】Remove fluid operator bernoulli_p - part
  paddle/fluid/operators/prim_ops/bernoulli_p_op.cc
  python/paddle/incubate/autograd/primops.py
  python/paddle/incubate/autograd/primrules.py
  test/autograd/test_orig2prim.py
  test/autograd/test_prim2orig.py
Labels: PaddlePaddle Hackathon, contributor

#63382 [HACKATHON 6th] Specify nvcc host compiler when using clang
  cmake/flags.cmake
Labels: contributor

#62993 [OneDNN][PIR] conv_concat_activation_mkldnn_fuse_pass
  paddle/fluid/inference/api/paddle_pass_builder.cc
  paddle/fluid/pir/transforms/onednn/conv_concat_activation_onednn_fuse_pass.cc
  paddle/fluid/pir/transforms/onednn/conv_concat_activation_onednn_fuse_pass.h
  paddle/fluid/pir/transforms/passes.h
  test/ir/pir/fused_pass/onednn/test_conv_concat_activation_onednn_fuse_pass.py
Labels: Intel, contributor

#62892 Spatial transformer resblock
  paddle/fluid/framework/ir/CMakeLists.txt
  paddle/fluid/framework/ir/pass.cc
  paddle/fluid/framework/ir/xpu/spatial_transformer_resblock_xpu_fuse_pass.cc
  paddle/fluid/inference/api/paddle_pass_builder.cc
  paddle/phi/api/yaml/fused_ops.yaml
  paddle/phi/backends/xpu/xpu2_op_list.cc
  paddle/phi/infermeta/fusion.cc
  paddle/phi/infermeta/fusion.h
  paddle/phi/kernels/fusion/xpu/spatial_transformer_resblock_xpu_kernel.cc
Labels: contributor

#63132 [WIP] remove parallel executor in pybind
  python/paddle/base/__init__.py
  python/paddle/distributed/fleet/base/distributed_strategy.py
  python/paddle/incubate/distributed/fleet/collective.py
  python/paddle/incubate/distributed/fleet/parameter_server/distribute_transpiler/distributed_strategy.py
  python/paddle/static/__init__.py
  python/paddle/static/quantization/adaround.py
  test/collective/fleet/test_distributed_strategy.py
  test/collective/fleet/test_fleet_distributed_strategy.py
  test/legacy_test/parallel_executor_test_base.py
  test/legacy_test/test_directory_migration.py
  test/legacy_test/test_dist_base.py
  test/legacy_test/test_dist_mnist_fleetapi.py
  test/legacy_test/test_eager_deletion_padding_rnn.py
  test/legacy_test/test_weight_decay.py
Labels: PaddlePaddle Hackathon, contributor

#63377 Update static_backward.yaml
  paddle/phi/api/yaml/static_backward.yaml
Labels: contributor, HappyOpenSource

#63217 [DCU] fix bugs and surpport some fused ops
  paddle/fluid/platform/device/gpu/gpu_info.cc
  paddle/phi/core/visit_type.h
  paddle/phi/kernels/CMakeLists.txt
  paddle/phi/kernels/funcs/dropout_impl.cu.h
  paddle/phi/kernels/funcs/layer_norm_impl.cu.h
  paddle/phi/kernels/fusion/gpu/fused_bias_dropout_residual_layer_norm_grad_kernel.cu
  paddle/phi/kernels/fusion/gpu/fused_bias_dropout_residual_layer_norm_kernel.cu
  paddle/phi/kernels/fusion/gpu/fused_dropout_act_bias.h
  paddle/phi/kernels/fusion/gpu/fused_dropout_add_grad_kernel.cu
  paddle/phi/kernels/fusion/gpu/fused_dropout_add_kernel.cu
  paddle/phi/kernels/fusion/gpu/fused_dropout_common.h
  paddle/phi/kernels/fusion/gpu/fused_layernorm_kernel.cu
  paddle/phi/kernels/fusion/gpu/fused_layernorm_residual_dropout_bias.h
  paddle/phi/kernels/fusion/gpu/fused_residual_dropout_bias.h
  paddle/phi/kernels/gpu/rms_norm_funcs.h
  paddle/phi/kernels/gpu/rms_norm_grad_kernel.cu
  paddle/phi/kernels/gpu/rms_norm_kernel.cu
  paddle/phi/kernels/gpudnn/conv_grad_kernel.cu
  python/paddle/device/cuda/graphs.py
  test/legacy_test/test_fused_layernorm_op.py
  test/legacy_test/test_rms_norm_op.py
Labels: contributor

#63429 Fix Registe Register, etc
  paddle/phi/api/yaml/fused_ops.yaml
  paddle/phi/api/yaml/op_version.yaml
  paddle/phi/api/yaml/ops.yaml
  test/auto_parallel/hybrid_strategy/semi_auto_parallel_global_input.py
  test/auto_parallel/hybrid_strategy/semi_auto_parallel_multi_inputs.py
  test/cpp/fluid/framework/details/broadcast_op_handle_test.h
  test/cpp/fluid/framework/details/reduce_op_handle_test.cc
  test/cpp/fluid/framework/io/cipher_utils_test.cc
  test/cpp/fluid/framework/selected_rows_utils_test.cc
  test/cpp/imperative/test_gradient_accmulator.cc
  test/cpp/imperative/test_hooks.cc
  test/cpp/inference/api/analyzer_capi_exp_xpu_tester.cc
  test/legacy_test/test_dropout_op.py
  test/legacy_test/test_fractional_max_pool2d_op.py
  test/legacy_test/test_fractional_max_pool3d_op.py
  test/legacy_test/test_function_hook.py
  test/legacy_test/test_fused_dconv_drelu_dbn_op.py
  test/legacy_test/test_fused_elemwise_activation_op.py
  test/legacy_test/test_fused_feedforward_pass.py
Labels: contributor, HappyOpenSource

#62645 [AutoParallel] Reconstruct pipeline_scheduler_pass
  python/paddle/distributed/passes/pipeline_scheduler_pass/__init__.py
  python/paddle/distributed/passes/pipeline_scheduler_pass/pipeline_1f1b.py
  python/paddle/distributed/passes/pipeline_scheduler_pass/pipeline_eager_1f1b.py
  python/paddle/distributed/passes/pipeline_scheduler_pass/pipeline_fthenb.py
  python/paddle/distributed/passes/pipeline_scheduler_pass/pipeline_pass_base.py
  python/paddle/distributed/passes/pipeline_scheduler_pass/pipeline_vpp.py
  python/setup.py.in
  setup.py
Labels: contributor

#63449 Switch the parameter order of "Scale" and "Bias".
  paddle/fluid/pir/transforms/xpu/group_norm_silu_fuse_pass.cc
  paddle/phi/api/yaml/fused_ops.yaml
Labels: contributor

#63476 【Hackathon 6th Fundable Projects 3 No.69】Remove fluid operator conv2d_inception_fusion
  paddle/fluid/operators/fused/CMakeLists.txt
  paddle/fluid/operators/fused/fusion_conv_inception_op.cc
  paddle/fluid/operators/fused/fusion_conv_inception_op.cu
Labels: PaddlePaddle Hackathon, contributor

#63504 【Hackathon 6th Fundable Projects 3 No.263】Remove fluid operator pad2d
  paddle/fluid/operators/pad2d_op.cc
Labels: PaddlePaddle Hackathon, contributor

#63515 【Hackathon 6th Fundable Projects 3 No.181】Remove fluid operator get_places
  paddle/fluid/operators/controlflow/get_places_op.cc
Labels: PaddlePaddle Hackathon, contributor

#63250 fix CINN prim decomp error
  paddle/fluid/primitive/base/decomp_trans.cc
  paddle/fluid/primitive/base/decomp_trans.h
  test/ir/pir/cinn/sub_graphs/test_sub_graph_46.py
Labels: contributor

#63262 【Hackathon 6th Fundable Projects 3 No.236】Remove fluid operator mine_hard_examples
  paddle/fluid/operators/detection/CMakeLists.txt
  paddle/fluid/operators/detection/mine_hard_examples_op.cc
  test/legacy_test/test_mine_hard_examples_op.py
  test/white_list/compile_vs_runtime_white_list.py
  tools/parallel_UT_rule.py
  tools/static_mode_white_list.py
Labels: PaddlePaddle Hackathon, contributor

#63248 【Hackathon 6th Fundable Projects 3 No.195】Remove fluid operator iou_similarity
  paddle/fluid/operators/detection/CMakeLists.txt
  paddle/fluid/operators/detection/iou_similarity_op.cc
  paddle/fluid/operators/detection/iou_similarity_op.cu
  paddle/fluid/operators/detection/iou_similarity_op.h
  paddle/fluid/operators/detection/iou_similarity_op_xpu.cc
  paddle/phi/backends/xpu/xpu1_op_list.cc
  paddle/phi/backends/xpu/xpu2_op_list.cc
  test/legacy_test/test_iou_similarity_op.py
  test/xpu/test_iou_similarity_op_xpu.py
  tools/parallel_UT_rule.py
  tools/static_mode_white_list.py
Labels: PaddlePaddle Hackathon, contributor

#63241 【Hackathon 6th Fundable Projects 3 No.234、364】Remove fluid operator merge_lod_tensor
  paddle/fluid/operators/merge_lod_tensor_op.cc
  paddle/fluid/operators/split_lod_tensor_op.cc
  paddle/fluid/operators/unity_build_rule.cmake
Labels: PaddlePaddle Hackathon, contributor

#63252 【Hackathon 6th Fundable Projects 3 No.209】Remove fluid operator locality_aware_nms
  paddle/fluid/operators/detection/CMakeLists.txt
  paddle/fluid/operators/detection/locality_aware_nms_op.cc
  test/legacy_test/test_locality_aware_nms_op.py
  test/white_list/compile_vs_runtime_white_list.py
  tools/parallel_UT_rule.py
  tools/static_mode_white_list.py
Labels: PaddlePaddle Hackathon, contributor

#63258 【Hackathon 6th Fundable Projects 3 No.296】Remove fluid operator rank_loss
  paddle/fluid/operators/rank_loss_op.cc
  paddle/fluid/operators/rank_loss_op.h
  test/legacy_test/test_rank_loss_op.py
  test/white_list/no_grad_set_white_list.py
  test/white_list/op_accuracy_white_list.py
  tools/parallel_UT_rule.py
  tools/static_mode_white_list.py
Labels: PaddlePaddle Hackathon, contributor

#63372 [Prim][PIR] support reciprocal op forward in prim pir
  paddle/fluid/pir/dialect/op_generator/decomp_interface_gen_op_list.py
  paddle/fluid/primitive/composite/composite.h
  test/legacy_test/test_activation_op.py
Labels: contributor

#63167 【Hackathon 6th No.33】支持动态图流水并行设定多个损失函数，并返回多个 loss
  python/paddle/distributed/fleet/meta_parallel/parallel_layers/pp_layers.py
  python/paddle/distributed/fleet/meta_parallel/pipeline_parallel.py
  test/collective/fleet/hybrid_parallel_pp_multiple_losses.py
  test/collective/fleet/hybrid_parallel_pp_multiple_losses_alignment.py
  test/collective/fleet/hybrid_parallel_pp_multiple_losses_with_virtual_stage.py
Labels: PaddlePaddle Hackathon, contributor

#63477 【Hackathon 6th Fundable Projects 3 No.88】Remove fluid operator delete_var
  paddle/fluid/operators/delete_var_op.cc
Labels: PaddlePaddle Hackathon, contributor

#63484 【Hackathon 6th Fundable Projects 3 No.277】Remove fluid operator pull_box_extended_sparse
  paddle/fluid/operators/pull_box_extended_sparse_op.cc
  paddle/fluid/operators/pull_box_extended_sparse_op.cu
  paddle/fluid/operators/pull_box_extended_sparse_op.h
  python/paddle/incubate/layers/__init__.py
  python/paddle/incubate/layers/nn.py
Labels: PaddlePaddle Hackathon, contributor

#63337 【Hackathon 6th No.35】support kwargs for recompute when use_reentrant == True
  python/paddle/distributed/fleet/recompute/recompute.py
  test/collective/fleet/test_dygraph_recompute_for_eager.py
Labels: PaddlePaddle Hackathon, contributor

#63235 【Hackathon 6th Fundable Projects 3 No.334】Remove fluid operator sequence_concat
  paddle/fluid/operators/sequence_ops/sequence_concat_op.cc
  paddle/fluid/operators/sequence_ops/sequence_concat_op.cu.cc
  paddle/fluid/operators/sequence_ops/sequence_concat_op.h
  paddle/fluid/operators/sequence_ops/unity_build_rule.cmake
  python/paddle/static/nn/__init__.py
  python/paddle/static/nn/sequence_lod.py
  test/sequence/CMakeLists.txt
  test/sequence/test_sequence_concat.py
  test/white_list/check_op_sequence_batch_1_input_white_list.py
  test/white_list/check_op_sequence_instance_0_input_white_list.py
  tools/parallel_UT_rule.py
  tools/static_mode_white_list.py
Labels: PaddlePaddle Hackathon, contributor

#63399 【Hackathon 6th Fundable Projects 3 No.1、3、26、57、66、72、105、115-117、173-174、188、215、228-229、244、253、272、303、309、317、325、329、355、357-358、365、367、369、373、386、390】Remove fluid prim_ops
  paddle/fluid/operators/CMakeLists.txt
  paddle/fluid/operators/prim_ops/CMakeLists.txt
  paddle/fluid/operators/prim_ops/abs_p_op.cc
  paddle/fluid/operators/prim_ops/add_p_op.cc
  paddle/fluid/operators/prim_ops/broadcast_p_op.cc
  paddle/fluid/operators/prim_ops/cast_p_op.cc
  paddle/fluid/operators/prim_ops/concat_p_op.cc
  paddle/fluid/operators/prim_ops/cos_p_op.cc
  paddle/fluid/operators/prim_ops/div_p_op.cc
  paddle/fluid/operators/prim_ops/eq_p_op.cc
  paddle/fluid/operators/prim_ops/erf_p_op.cc
  paddle/fluid/operators/prim_ops/exp_p_op.cc
  paddle/fluid/operators/prim_ops/fill_constant_p_op.cc
  paddle/fluid/operators/prim_ops/gather_p_op.cc
  paddle/fluid/operators/prim_ops/ge_p_op.cc
  paddle/fluid/operators/prim_ops/gt_p_op.cc
  paddle/fluid/operators/prim_ops/log_p_op.cc
  paddle/fluid/operators/prim_ops/matmul_p_op.cc
  paddle/fluid/operators/prim_ops/max_p_op.cc
  paddle/fluid/operators/prim_ops/mul_p_op.cc
  paddle/fluid/operators/prim_ops/ne_p_op.cc
  paddle/fluid/operators/prim_ops/pow_p_op.cc
  paddle/fluid/operators/prim_ops/reduce_sum_p_op.cc
  paddle/fluid/operators/prim_ops/reshape_p_op.cc
  paddle/fluid/operators/prim_ops/rsqrt_p_op.cc
  paddle/fluid/operators/prim_ops/scatter_add_p_op.cc
  paddle/fluid/operators/prim_ops/select_p_op.cc
  paddle/fluid/operators/prim_ops/sin_p_op.cc
  paddle/fluid/operators/prim_ops/slice_assign_p_op.cc
  paddle/fluid/operators/prim_ops/slice_select_p_op.cc
  paddle/fluid/operators/prim_ops/split_p_op.cc
  paddle/fluid/operators/prim_ops/sqrt_p_op.cc
  paddle/fluid/operators/prim_ops/sub_p_op.cc
  paddle/fluid/operators/prim_ops/tanh_p_op.cc
  paddle/fluid/operators/prim_ops/transpose_p_op.cc
  paddle/fluid/operators/prim_ops/uniform_random_p_op.cc
  paddle/fluid/operators/prim_ops/unity_build_rule.cmake
  python/paddle/incubate/autograd/primops.py
  python/paddle/incubate/autograd/primrules.py
  python/paddle/incubate/autograd/primx.py
  test/auto_parallel/CMakeLists.txt
  test/auto_parallel/test_prim_dist_op.py
  test/autograd/CMakeLists.txt
  test/autograd/test_jvp_and_transpose.py
  test/autograd/test_orig2prim.py
  test/autograd/test_prim2orig.py
  test/autograd/test_primapi.py
  test/autograd/test_primops.py
  test/autograd/test_transform.py
Labels: PaddlePaddle Hackathon, contributor

#63468 【Hackathon 6th Fundable Projects 3 No.205】Remove fluid operator lite_engine
  paddle/fluid/framework/naive_executor.cc
  paddle/fluid/operators/CMakeLists.txt
  paddle/fluid/operators/lite/CMakeLists.txt
  paddle/fluid/operators/lite/lite_engine_op.cc
  paddle/fluid/operators/lite/lite_engine_op.h
  test/cpp/fluid/CMakeLists.txt
  test/cpp/fluid/lite/CMakeLists.txt
  test/cpp/fluid/lite/lite_engine_op_test.cc
Labels: PaddlePaddle Hackathon, contributor

#63538 Fix unittest of fused_rope
  python/paddle/incubate/nn/functional/fused_rotary_position_embedding.py
  test/legacy_test/test_fused_rotary_position_embedding.py
Labels: contributor

#63488 【Hackathon 6th Fundable Projects 3 No.366】Remove fluid operator spp
  paddle/fluid/operators/spp_op.cc
  paddle/fluid/operators/spp_op.cu.cc
  paddle/fluid/operators/spp_op.h
  test/legacy_test/test_spp_op.py
Labels: PaddlePaddle Hackathon, contributor

#63487 【Hackathon 6th Fundable Projects 3 No.354、376】Remove fluid operator similarity_focus
  paddle/fluid/operators/similarity_focus_op.cc
  paddle/fluid/operators/similarity_focus_op.h
  paddle/fluid/operators/teacher_student_sigmoid_loss_op.cc
  paddle/fluid/operators/teacher_student_sigmoid_loss_op.h
  test/legacy_test/test_similarity_focus_op.py
  test/legacy_test/test_teacher_student_sigmoid_loss_op.py
Labels: PaddlePaddle Hackathon, contributor

#63466 【Hackathon 6th Fundable Projects 3 No.237】Remove fluid operator minus
  paddle/fluid/operators/minus_op.cc
  paddle/fluid/operators/minus_op.h
  test/legacy_test/test_minus_op.py
Labels: PaddlePaddle Hackathon, contributor

#63464 【Hackathon 6th Fundable Projects 3 No.391-392】Remove fluid operators unique_with_counts etc
  paddle/fluid/operators/unique_with_counts_op.cc
  paddle/fluid/operators/unique_with_counts_op.h
  paddle/fluid/operators/unzip_op.cc
  paddle/fluid/operators/unzip_op.cu
  paddle/fluid/operators/unzip_op.h
  test/legacy_test/test_unique_with_counts.py
  test/legacy_test/test_unzip_op.py
Labels: PaddlePaddle Hackathon, contributor

#63483 【Hackathon 6th Fundable Projects 3 No.273】Remove fluid operator precision_recall
  paddle/fluid/operators/CMakeLists.txt
  paddle/fluid/operators/metrics/CMakeLists.txt
  paddle/fluid/operators/metrics/precision_recall_op.cc
  paddle/fluid/operators/metrics/precision_recall_op.h
  paddle/fluid/operators/metrics/unity_build_rule.cmake
  test/legacy_test/test_precision_recall_op.py
Labels: PaddlePaddle Hackathon, contributor

#63486 【Hackathon 6th Fundable Projects 3 No.312-313、315】Remove fluid operator retinanet_detection_output etc
  paddle/fluid/operators/detection/CMakeLists.txt
  paddle/fluid/operators/detection/retinanet_detection_output_op.cc
  paddle/fluid/operators/detection/rpn_target_assign_op.cc
  test/legacy_test/test_retinanet_detection_output.py
  test/legacy_test/test_rpn_target_assign_op.py
Labels: PaddlePaddle Hackathon, contributor

#63492 【Hackathon 6th Fundable Projects 3 No.319】Remove fluid operator sampling_id
  paddle/fluid/operators/sampling_id_op.cc
  paddle/fluid/operators/sampling_id_op.cu
  paddle/fluid/operators/sampling_id_op.h
  paddle/fluid/operators/sampling_id_op_xpu.cc
  paddle/phi/backends/xpu/xpu2_op_list.cc
  paddle/phi/backends/xpu/xpu3_op_list.cc
  python/paddle/distribution/distribution.py
Labels: PaddlePaddle Hackathon, contributor

#63475 【Hackathon 6th Fundable Projects 3 No.60】Remove fluid operator chunk_eval
  paddle/fluid/operators/chunk_eval_op.cc
  paddle/fluid/operators/chunk_eval_op.h
  test/cpp/inference/api/CMakeLists.txt
  test/legacy_test/test_chunk_eval_op.py
Labels: PaddlePaddle Hackathon, contributor

#63566 【Hackathon 6th Fundable Projects 3 No.336】fluid operator sequence_enumerate
  paddle/fluid/operators/sequence_ops/sequence_enumerate_op.cc
  paddle/fluid/operators/sequence_ops/sequence_enumerate_op.cu
  paddle/fluid/operators/sequence_ops/sequence_enumerate_op.h
Labels: PaddlePaddle Hackathon, contributor

#63489 【Hackathon 6th Fundable Projects 3 No.351】Remove fluid operator shrink_rnn_memory
  paddle/fluid/operators/shrink_rnn_memory_op.cc
  test/cpp/inference/api/CMakeLists.txt
Labels: PaddlePaddle Hackathon, contributor

#63470 【Hackathon 6th Fundable Projects 3 No.61-62】Remove fluid operator cinn_instruction_run
  paddle/fluid/framework/details/build_strategy.cc
  paddle/fluid/framework/ir/memory_optimize_pass/eager_deletion_pass.cc
  paddle/fluid/framework/ir/memory_optimize_pass/share_varinfo_into_cinn_pass.cc
  paddle/fluid/framework/paddle2cinn/build_cinn_pass.cc
  paddle/fluid/inference/api/paddle_pass_builder.cc
  paddle/fluid/operators/cinn/cinn_instruction_run_op.cc
  paddle/fluid/operators/cinn/cinn_instruction_run_op.cu.cc
  paddle/fluid/operators/cinn/cinn_instruction_run_op.h
  paddle/fluid/operators/cinn/cinn_launch_op.cc
  paddle/fluid/operators/cinn/cinn_launch_op.cu.cc
  paddle/fluid/operators/cinn/cinn_launch_op.h
  test/cpp/fluid/cinn/CMakeLists.txt
  test/cpp/fluid/cinn/cinn_instruction_run_op_test.cc
  test/cpp/fluid/cinn/cinn_launch_context_test.cc
  test/cpp/fluid/cinn/cinn_launch_op_test.cc
  test/cpp/fluid/framework/ir/memory_optimize_pass/CMakeLists.txt
  test/cpp/fluid/framework/ir/memory_optimize_pass/share_varinfo_into_cinn_pass_test.cc
  test/cpp/fluid/framework/paddle2cinn/build_cinn_pass_test.cc
  test/cpp/fluid/framework/paddle2cinn/cinn_compiler_test.cc
  test/distributed_passes/test_build_cinn_pass_simple_net.py
Labels: PaddlePaddle Hackathon, contributor

#63457 【Hackathon 6th Fundable Projects 3 No.81】Remove fluid operators ctc_align
  paddle/fluid/operators/ctc_align_op.cc
  paddle/fluid/operators/ctc_align_op.cu
  paddle/fluid/operators/ctc_align_op.h
  test/legacy_test/test_ctc_align.py
Labels: PaddlePaddle Hackathon, contributor

#63493 【Hackathon 6th Fundable Projects 3 No.271】Remove fluid operator pow2_decay_with_linear_warmup
  paddle/fluid/operators/ops_signature/pow2_decay_with_linear_warmup_sig.cc
  paddle/fluid/operators/optimizers/pow2_decay_with_linear_warmup_op.cc
  test/legacy_test/test_pow2_decay_with_linear_warmup_op.py
  test/xpu/test_pow2_decay_with_linear_warmup_op_xpu.py
Labels: PaddlePaddle Hackathon, contributor

#63561 【Hackathon 6th Fundable Projects 3 No.345】fluid operator sequence_scatter
  paddle/fluid/operators/sequence_ops/sequence_scatter_op.cc
  paddle/fluid/operators/sequence_ops/sequence_scatter_op.h
  test/sequence/test_sequence_scatter_op.py
Labels: PaddlePaddle Hackathon, contributor

#63584 【Hackathon 6th Fundable Projects 3 No.95、114】fluid operator dequeue etc
  paddle/fluid/operators/dequeue_op.cc
  paddle/fluid/operators/enqueue_op.cc
  test/legacy_test/test_queue.py
Labels: PaddlePaddle Hackathon, contributor

#63587 【Hackathon 6th Fundable Projects 3 No.25】fluid operator brp_loss
  paddle/fluid/operators/bpr_loss_op.cc
  paddle/fluid/operators/bpr_loss_op.h
  test/legacy_test/test_bpr_loss_op.py
Labels: PaddlePaddle Hackathon, contributor

#62710 Add InferSymbolicShape for pd_op.meshgrid
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/multiary_infer_sym.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/multiary_infer_sym.h
  paddle/phi/api/yaml/ops.yaml
  test/ir/pir/cinn/symbolic/test_infer_sym_shape_multinary_op.py
Labels: contributor

#63569 【Hackathon 6th Fundable Projects 3 No.339】fluid operator sequence_expand_as
  paddle/fluid/operators/sequence_ops/sequence_expand_as_op.cc
  paddle/fluid/operators/sequence_ops/sequence_expand_as_op.cu
  paddle/fluid/operators/sequence_ops/sequence_expand_as_op.h
  test/sequence/test_sequence_expand_as.py
Labels: PaddlePaddle Hackathon, contributor

#63559 【Hackathon 6th Fundable Projects 3 No.346】fluid operator sequence_slice
  paddle/fluid/operators/sequence_ops/sequence_slice_op.cc
  paddle/fluid/operators/sequence_ops/sequence_slice_op.cu
  paddle/fluid/operators/sequence_ops/sequence_slice_op.h
  test/sequence/test_sequence_slice_op.py
Labels: PaddlePaddle Hackathon, contributor

#63558 【Hackathon 6th Fundable Projects 3 No.341、348】fluid operator sequence_unpad
  paddle/fluid/operators/sequence_ops/sequence_pad_op.cc
  paddle/fluid/operators/sequence_ops/sequence_pad_op.cu
  paddle/fluid/operators/sequence_ops/sequence_pad_op.h
  paddle/fluid/operators/sequence_ops/sequence_unpad_op.cc
  paddle/fluid/operators/sequence_ops/sequence_unpad_op.cu
  paddle/fluid/operators/sequence_ops/sequence_unpad_op.h
  paddle/fluid/operators/sequence_ops/sequence_unpad_op_xpu.cc
  test/cpp/fluid/framework/op_compatible_info_test.cc
  test/legacy_test/test_zero_dim_sundry_static_api_part3.py
  test/sequence/test_sequence_pad_op.py
  test/sequence/test_sequence_unpad_op.py
  test/xpu/test_sequence_unpad_op_xpu.py
Labels: PaddlePaddle Hackathon, contributor

#63555 【Hackathon 6th Fundable Projects 3 No.202】Remove fluid operator linear_chain_crf
  paddle/fluid/operators/linear_chain_crf_op.cc
  paddle/fluid/operators/linear_chain_crf_op.h
  test/legacy_test/CMakeLists.txt
  test/legacy_test/test_linear_chain_crf_op.py
Labels: PaddlePaddle Hackathon, contributor

#63589 【Hackathon 6th Fundable Projects 3 No.87】fluid operator deformable_psroi_pooling
  paddle/fluid/operators/deformable_psroi_pooling_op.cc
  paddle/fluid/operators/deformable_psroi_pooling_op.cu
  paddle/fluid/operators/deformable_psroi_pooling_op.h
Labels: PaddlePaddle Hackathon, contributor

#63583 【Hackathon 6th Fundable Projects 3 No.141】fluid operator fsp
  paddle/fluid/operators/fsp_op.cc
  paddle/fluid/operators/fsp_op.cu
  paddle/fluid/operators/fsp_op.h
  test/legacy_test/test_fsp_op.py
Labels: PaddlePaddle Hackathon, contributor

#63565 【Hackathon 6th Fundable Projects 3 No.337】fluid operator sequence_erase
  paddle/fluid/operators/sequence_ops/sequence_erase_op.cc
  paddle/fluid/operators/sequence_ops/sequence_erase_op.cu
  paddle/fluid/operators/sequence_ops/sequence_erase_op.h
  test/sequence/test_sequence_erase_op.py
Labels: PaddlePaddle Hackathon, contributor

#63564 【Hackathon 6th Fundable Projects 3 No.343】fluid operator sequence_reshape
  paddle/fluid/operators/sequence_ops/sequence_reshape_op.cc
  paddle/fluid/operators/sequence_ops/sequence_reshape_op.cu
  paddle/fluid/operators/sequence_ops/sequence_reshape_op.h
  test/sequence/test_sequence_reshape.py
Labels: PaddlePaddle Hackathon, contributor

#63459 【Hackathon 6th Fundable Projects 3 No.166】Remove fluid operators fused_softplus
  paddle/fluid/operators/compat/fused_softplus.pbtxt
  paddle/fluid/operators/fused/fused_softplus_op.cc
  paddle/fluid/operators/ops_signature/fused_softplus_sig.cc
  test/cpp/inference/infer_ut/test_ppyolov2_r50vd.cc
  test/ir/inference/test_onednn_softplus_activation_fuse_pass.py
Labels: PaddlePaddle Hackathon, contributor

#63265 【Hackathon 6th Fundable Projects 3 No.269、270、275】Remove fluid operator polygon_box_transform etc
  paddle/fluid/operators/detection/CMakeLists.txt
  paddle/fluid/operators/detection/polygon_box_transform_op.cc
  paddle/fluid/operators/detection/polygon_box_transform_op.cu
  paddle/fluid/operators/optimizers/proximal_gd_op.cc
  paddle/fluid/operators/optimizers/proximal_gd_op.cu
  paddle/fluid/operators/optimizers/proximal_gd_op.h
  paddle/fluid/operators/positive_negative_pair_op.cc
  paddle/fluid/operators/positive_negative_pair_op.h
  test/legacy_test/test_polygon_box_transform.py
  test/legacy_test/test_positive_negative_pair_op.py
  test/legacy_test/test_proximal_gd_op.py
Labels: PaddlePaddle Hackathon, contributor

#63243 【Hackathon 6th Fundable Projects 3 No.393】Remove fluid operator var_conv_2d
  paddle/fluid/framework/op_compatible_info.cc
  paddle/fluid/operators/CMakeLists.txt
  paddle/fluid/operators/var_conv_2d_op.cc
  paddle/fluid/operators/var_conv_2d_op.h
  test/legacy_test/CMakeLists.txt
  test/legacy_test/test_var_conv_2d.py
Labels: PaddlePaddle Hackathon, contributor

#63473 【Hackathon 6th Fundable Projects 4 No.4】 clean parallel executor in cinn
  paddle/common/flags.cc
  paddle/fluid/framework/ir/memory_optimize_pass/CMakeLists.txt
  paddle/fluid/framework/ir/memory_optimize_pass/eager_deletion_pass.cc
  paddle/fluid/framework/paddle2cinn/CMakeLists.txt
  paddle/fluid/framework/paddle2cinn/cinn_compiler.cc
  paddle/fluid/operators/cinn/CMakeLists.txt
  paddle/fluid/operators/cinn/cinn_launch_context.cc
  paddle/fluid/operators/cinn/cinn_launch_context.h
  test/cpp/fluid/cinn/cinn_launch_context_test.cc
Labels: PaddlePaddle Hackathon, contributor

#63590 【Hackathon 6th Fundable Projects 3 No.74】fluid operator create_custom_reader
  paddle/fluid/operators/reader/create_custom_reader_op.cc
Labels: PaddlePaddle Hackathon, contributor

#63588 【Hackathon 6th Fundable Projects 3 No.59】fluid operator check_memory_continue
  paddle/fluid/operators/check_memory_continue_op.cc
Labels: PaddlePaddle Hackathon, contributor

#63491 【Hackathon 6th Fundable Projects 3 No.293】Remove fluid operator queue_generator
  paddle/fluid/operators/queue_generator_op.cc
Labels: PaddlePaddle Hackathon, contributor

#63472 [PIR-3][36] Adapt apply_per_channel_scale api
  python/paddle/nn/quant/quantized_linear.py
  test/quantization/test_apply_per_channel_scale.py
Labels: contributor

#63595 Resolved a conflict between import torch and paddle
  paddle/fluid/pybind/pybind.cc
Labels: contributor, HappyOpenSource

#63562 【Hackathon 6th Fundable Projects 3 No.344】fluid operator sequence_reverse
  paddle/fluid/operators/sequence_ops/sequence_reverse_op.cc
  paddle/fluid/operators/sequence_ops/sequence_reverse_op.cu
  paddle/fluid/operators/sequence_ops/sequence_reverse_op.h
  python/paddle/static/nn/__init__.py
  python/paddle/static/nn/sequence_lod.py
  test/sequence/test_sequence_reverse.py
Labels: PaddlePaddle Hackathon, contributor

#63640 xpu supports pp as gpu
  paddle/fluid/operators/collective/c_sync_calc_stream_op_xpu.cc
  paddle/fluid/operators/collective/c_sync_comm_stream_op_xpu.cc
  paddle/phi/backends/xpu/xpu3_op_list.cc
  python/paddle/distributed/communication/batch_isend_irecv.py
  python/paddle/distributed/fleet/meta_parallel/pipeline_parallel.py
Labels: contributor

#62612 [CINN] Removed 0d-to-1d pass
  paddle/cinn/hlir/dialect/operator/transforms/add_cinn_pass.cc
  paddle/cinn/hlir/dialect/operator/transforms/group_merge/convert_0d_to_1d_pass.cc
  paddle/cinn/hlir/dialect/operator/transforms/group_merge/convert_0d_to_1d_pass.h
  paddle/cinn/operator_fusion/policy/relative_judge_policy.h
  paddle/cinn/operator_fusion/policy/shardable_axes_base.cc
  paddle/cinn/operator_fusion/utils.h
  test/ir/pir/cinn/symbolic/test_cinn_0d_tensor.py
Labels: contributor

#63626 Clean paddle/fluid/operators/kernel_primitives
  paddle/fluid/operators/fused/attn_bias_add.cu.h
  paddle/fluid/operators/kernel_primitives/functor_primitives.h
  paddle/fluid/operators/kernel_primitives/kernel_primitives.h
Labels: contributor, HappyOpenSource

#63591 【Hackathon 6th Fundable Projects 3 No.205】Clean WITH_LITE option
  CMakeLists.txt
  cmake/external/lite.cmake
  cmake/third_party.cmake
  cmake/version.cmake
  paddle/fluid/framework/naive_executor.cc
  paddle/fluid/framework/naive_executor.h
  paddle/fluid/inference/CMakeLists.txt
  paddle/fluid/inference/analysis/argument.h
  paddle/fluid/inference/analysis/ir_pass_manager.cc
  paddle/fluid/inference/analysis/ir_passes/CMakeLists.txt
  paddle/fluid/inference/analysis/ir_passes/lite_subgraph_pass.cc
  paddle/fluid/inference/analysis/ir_passes/lite_subgraph_pass.h
  paddle/fluid/inference/analysis/ir_passes/lite_subgraph_pass_tester.cc
  paddle/fluid/inference/api/analysis_config.cc
  paddle/fluid/inference/api/analysis_predictor.cc
  paddle/fluid/inference/api/paddle_analysis_config.h
  paddle/fluid/inference/api/paddle_pass_builder.cc
  paddle/fluid/inference/api/paddle_pass_builder.h
  paddle/fluid/inference/capi_exp/pd_config.cc
  paddle/fluid/inference/capi_exp/pd_config.h
  paddle/fluid/inference/goapi/config.go
  paddle/fluid/inference/goapi/config_test.go
  paddle/fluid/inference/lite/CMakeLists.txt
  paddle/fluid/inference/lite/engine.cc
  paddle/fluid/inference/lite/engine.h
  paddle/fluid/inference/lite/op_teller.cc
  paddle/fluid/inference/lite/op_teller.h
  paddle/fluid/inference/lite/tensor_utils.cc
  paddle/fluid/inference/lite/tensor_utils.h
  paddle/fluid/inference/lite/test_engine_lite.cc
  paddle/fluid/inference/lite/test_tensor_utils.cc
  paddle/fluid/inference/paddle_inference.map
  paddle/fluid/operators/lite/ut_helper.h
  paddle/fluid/pybind/inference_api.cc
  paddle/scripts/paddle_build.sh
  python/env_dict.py.in
  python/setup.py.in
  setup.py
  test/cpp/inference/api/CMakeLists.txt
  test/cpp/inference/api/analysis_predictor_tester.cc
  test/cpp/inference/api/analyzer_capi_exp_pd_config_tester.cc
  test/cpp/inference/api/lite_mul_model_test.cc
  test/cpp/inference/api/lite_resnet50_test.cc
  test/cpp/inference/api/xpu_config_resnet50_test.cc
  tools/parallel_UT_rule.py
Labels: PaddlePaddle Hackathon, contributor

#63603 [CINN]Open test_sub_graph_test unittest
  test/ir/pir/cinn/sub_graphs/test_sub_graph_66.py
Labels: contributor

#63281 Replace MKLDNN_ ONEDNN_
  cmake/cinn.cmake
  cmake/external/onednn.cmake
  cmake/inference_lib.cmake
  cmake/operators.cmake
  paddle/fluid/eager/auto_code_generator/CMakeLists.txt
  paddle/fluid/inference/api/demo_ci/CMakeLists.txt
  paddle/fluid/pybind/CMakeLists.txt
  python/env_dict.py.in
  python/setup.py.in
  python/setup_cinn.py.in
  setup.py
  test/auto_parallel/custom_op/CMakeLists.txt
  test/auto_parallel/custom_op/utils.py
  test/cpp/inference/infer_ut/CMakeLists.txt
  test/ir/inference/auto_scan_test.py
Labels: contributor, HappyOpenSource

#63284 【Hackathon 6th No.24 】 为 paddle.nn.LSTM/RNNBase 功能增强
  python/paddle/nn/layer/rnn.py
  test/deprecated/rnn/test_rnn_nets.py
  test/deprecated/rnn/test_rnn_nets_static.py
  test/dygraph_to_static/test_lstm.py
  test/rnn/rnn_numpy.py
Labels: PaddlePaddle Hackathon, contributor

#63516 [OneDNN][PIR] Add elementwise_act_onednn_fuse_pass
  paddle/fluid/inference/api/paddle_pass_builder.cc
  paddle/fluid/pir/transforms/onednn/elementwise_act_onednn_fuse_pass.cc
  paddle/fluid/pir/transforms/onednn/elementwise_act_onednn_fuse_pass.h
  paddle/fluid/pir/transforms/passes.h
  test/ir/pir/fused_pass/onednn/test_elementwise_act_fuse_pass.py
Labels: Intel, contributor

#63592 [OneDNN][PIR] Add operator_unsqueeze_onednn_fuse_pass
  paddle/fluid/inference/api/paddle_pass_builder.cc
  paddle/fluid/pir/transforms/onednn/operator_unsqueeze_onednn_fuse_pass.cc
  paddle/fluid/pir/transforms/onednn/operator_unsqueeze_onednn_fuse_pass.h
  paddle/fluid/pir/transforms/passes.h
  test/ir/pir/fused_pass/onednn/test_operator_unsqueeze_onednn_fuse_pass.py
Labels: Intel, contributor

#63617 [PIR][oneDNN] Add softplus_activation_fuse_pass
  paddle/fluid/inference/api/paddle_pass_builder.cc
  paddle/fluid/pir/transforms/onednn/softplus_activation_fuse_pass.cc
  paddle/fluid/pir/transforms/onednn/softplus_activation_fuse_pass.h
  paddle/fluid/pir/transforms/passes.h
  test/ir/pir/fused_pass/onednn/test_softplus_activation_fuse_pass.py
Labels: Intel, contributor

#63576 support ExpandAsOpInferSymbolicShape
  paddle/cinn/hlir/dialect/operator/transforms/add_broadcast_to_elementwise_pass.cc
  paddle/cinn/hlir/pe/transform.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/binary_infer_sym.cc
Labels: contributor

#62987 Add InferSymbolicShape for pd_op.nonzero
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/unary_infer_sym.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/unary_infer_sym.h
  paddle/phi/api/yaml/ops.yaml
  test/ir/pir/cinn/symbolic/test_infer_sym_shape_unary_op.py
Labels: contributor

#63460 【Hackathon 6th Fundable Projects 3 No.24、89、177、178】Remove fluid operators generate_mask_labels
  paddle/fluid/operators/detection/CMakeLists.txt
  paddle/fluid/operators/detection/box_decoder_and_assign_op.cc
  paddle/fluid/operators/detection/box_decoder_and_assign_op.cu
  paddle/fluid/operators/detection/box_decoder_and_assign_op.h
  paddle/fluid/operators/detection/density_prior_box_op.cc
  paddle/fluid/operators/detection/density_prior_box_op.cu
  paddle/fluid/operators/detection/density_prior_box_op.h
  paddle/fluid/operators/detection/generate_mask_labels_op.cc
  paddle/fluid/operators/detection/generate_proposal_labels_op.cc
  paddle/fluid/operators/detection/mask_util.cc
  paddle/fluid/operators/detection/mask_util.h
  test/cpp/fluid/CMakeLists.txt
  test/cpp/fluid/detection/CMakeLists.txt
  test/cpp/fluid/detection/mask_util_test.cc
  test/legacy_test/test_box_decoder_and_assign_op.py
  test/legacy_test/test_density_prior_box_op.py
  test/legacy_test/test_generate_mask_labels_op.py
  test/legacy_test/test_generate_proposal_labels_op.py
Labels: PaddlePaddle Hackathon, contributor

#63238 【Hackathon 6th Fundable Projects 3 No.138、139】Remove fluid operator fill_zeros_like
  paddle/fluid/operators/fill_zeros_like_op.cc
  paddle/fluid/operators/fill_zeros_like_op.cu.cc
  paddle/fluid/operators/fill_zeros_like_op.h
  test/deprecated/legacy_test/CMakeLists.txt
  test/deprecated/legacy_test/test_fill_zeros_like2_op.py
  test/legacy_test/test_fill_zeros_like_op.py
Labels: PaddlePaddle Hackathon, contributor

#63580 【Error Message No. 19】paddle/cinn/frontend/paddle/*
  paddle/cinn/frontend/paddle/cpp/block_desc.cc
  paddle/cinn/frontend/paddle/cpp/program_desc.cc
  paddle/cinn/frontend/paddle/model_parser.cc
  paddle/cinn/frontend/paddle/pb/block_desc.cc
  paddle/cinn/frontend/paddle/pb/program_desc.cc
Labels: contributor, HappyOpenSource

#63708 fix int32 overflow in rope rotate_half
  paddle/phi/kernels/fusion/gpu/fused_rope_utils.h
Labels: contributor

#63610 【Hackathon 6th No.54】move fake_quantize_abs_max op to phi - part
  paddle/fluid/operators/fake_quantize_op.cc
  paddle/fluid/operators/fake_quantize_op.cu
  paddle/fluid/operators/fake_quantize_op.cu.h
  paddle/fluid/operators/fake_quantize_op.h
  paddle/fluid/operators/fused/quant_dequant_kernel.h
  paddle/fluid/operators/quantize_linear_op.h
  paddle/phi/api/yaml/op_compat.yaml
  paddle/phi/api/yaml/ops.yaml
  paddle/phi/infermeta/unary.cc
  paddle/phi/infermeta/unary.h
  paddle/phi/kernels/cpu/fake_quantize_kernel.cc
  paddle/phi/kernels/fake_quantize_kernel.h
  paddle/phi/kernels/funcs/fake_quantize_functor.cc
  paddle/phi/kernels/funcs/fake_quantize_functor.cu
  paddle/phi/kernels/funcs/fake_quantize_functor.h
  paddle/phi/kernels/funcs/layer_norm_impl.cu.h
  paddle/phi/kernels/gpu/fake_quantize_kernel.cu
  paddle/phi/kernels/impl/fake_quantize_kernel_impl.h
Labels: PaddlePaddle Hackathon, contributor

#63638 【Hackathon 6th No.55】move dequantize_log to phi - part
  paddle/fluid/operators/dequantize_log_op.cc
  paddle/fluid/operators/dequantize_log_op.cu
  paddle/fluid/operators/dequantize_log_op.h
  paddle/fluid/operators/ops_signature/dequantize_log_sig.cc
  paddle/fluid/pir/dialect/operator/ir/ops.yaml
  paddle/phi/api/yaml/legacy_ops.yaml
  paddle/phi/infermeta/binary.cc
  paddle/phi/infermeta/binary.h
  paddle/phi/kernels/cpu/dequantize_log_kernel.cc
  paddle/phi/kernels/dequantize_log_kernel.h
  paddle/phi/kernels/gpu/dequantize_log_kernel.cu
  test/legacy_test/test_dequantize_log_op.py
Labels: PaddlePaddle Hackathon, contributor

#63648 【Hackathon 6th No.29】为 paddle.nn.functional.max_unpool1d / max_unpool2d / max_unpool3d/paddle.nn.functional.kl_div 进行功能增强 -part
  paddle/phi/kernels/cpu/unpool_grad_kernel.cc
  paddle/phi/kernels/cpu/unpool_kernel.cc
  paddle/phi/kernels/gpu/unpool_grad_kernel.cu
  paddle/phi/kernels/gpu/unpool_kernel.cu
  python/paddle/nn/functional/pooling.py
  test/deprecated/legacy_test/test_unpool3d_op.py
  test/deprecated/legacy_test/test_unpool_op.py
  test/legacy_test/test_unpool1d_op.py
Labels: PaddlePaddle Hackathon, contributor

#62747 [Sparse conv] Implement implicit gemm algo for SubmConv3D
  paddle/fluid/operators/controlflow/feed_op.cc
  paddle/fluid/operators/sync_batch_norm_op.cu
  paddle/phi/api/yaml/sparse_ops.yaml
  paddle/phi/core/kmap_cache.h
  paddle/phi/core/sparse_coo_tensor.h
  paddle/phi/infermeta/sparse/binary.cc
  paddle/phi/infermeta/sparse/binary.h
  paddle/phi/kernels/CMakeLists.txt
  paddle/phi/kernels/funcs/sparse/convolution.h
  paddle/phi/kernels/sparse/batch_norm_kernel.cc
  paddle/phi/kernels/sparse/elementwise_kernel.h
  paddle/phi/kernels/sparse/gpu/coalesce_kernel.cu
  paddle/phi/kernels/sparse/gpu/conv_kernel_igemm.cu
  paddle/phi/kernels/sparse/gpu/conv_kernel_impl.cuh
  paddle/phi/kernels/sparse/gpu/conv_memory_utils.cuh
  paddle/phi/kernels/sparse/gpu/elementwise_kernel.cu
  paddle/phi/kernels/sparse/gpu/sparse_conv_hashmap.cuh
  paddle/phi/kernels/sparse/impl/unary_kernel_impl.h
  python/paddle/sparse/nn/functional/__init__.py
  python/paddle/sparse/nn/functional/conv.py
  python/paddle/sparse/nn/layer/conv.py
  test/legacy_test/CMakeLists.txt
  test/legacy_test/test_sparse_conv_igemm_op.py
Labels: NVIDIA, contributor

#63690 【Hackathon 6th Fundable Projects 1 】Add typing_extensions to requirements
  python/requirements.txt
Labels: PaddlePaddle Hackathon, contributor

#63674 【Hackathon 6th Fundable Projects 3 No.304】fluid operator reorder_lod_tensor_by_rank
  paddle/fluid/operators/reorder_lod_tensor_by_rank_op.cc
Labels: PaddlePaddle Hackathon, contributor

#63771 [CodeStyle][ruff] clean some I001 step: 14
  pyproject.toml
  python/paddle/distributed/auto_parallel/static/dist_context.py
  python/paddle/distributed/auto_parallel/static/parallelizer_v2.py
  python/paddle/distributed/passes/__init__.py
Labels: contributor

#63688 【Hackathon 6th Fundable Projects 3 No.374】fluid operator tdm_child
  paddle/fluid/operators/tdm_child_op.cc
  paddle/fluid/operators/tdm_child_op.h
  paddle/phi/api/yaml/op_compat.yaml
  paddle/phi/kernels/cpu/tdm_child_kernel.cc
  test/deprecated/legacy_test/test_tdm_child_op.py
Labels: PaddlePaddle Hackathon, contributor

#63513 API improvement for paddle.argsort and paddle.sort 易用性提升
  paddle/phi/api/yaml/backward.yaml
  paddle/phi/api/yaml/op_version.yaml
  paddle/phi/api/yaml/ops.yaml
  paddle/phi/infermeta/unary.cc
  paddle/phi/infermeta/unary.h
  paddle/phi/kernels/argsort_grad_kernel.h
  paddle/phi/kernels/argsort_kernel.h
  paddle/phi/kernels/cpu/argsort_grad_kernel.cc
  paddle/phi/kernels/cpu/argsort_kernel.cc
  paddle/phi/kernels/gpu/argsort_grad_kernel.cu
  paddle/phi/kernels/gpu/argsort_kernel.cu
  paddle/phi/kernels/xpu/argsort_grad_kernel.cc
  paddle/phi/kernels/xpu/argsort_kernel.cc
  python/paddle/tensor/search.py
  test/deprecated/legacy_test/test_argsort_op.py
  test/legacy_test/test_sort_op.py
  test/xpu/test_argsort_op_xpu.py
Labels: contributor

#63769 remove templatedoc decorator
  python/paddle/base/layers/layer_function_generator.py
  python/paddle/base/layers/math_op_patch.py
  python/paddle/common_ops_import.py
  python/paddle/tensor/layer_function_generator.py
Labels: contributor, HappyOpenSource

#63796 Fix argsort kernel annotation
  paddle/phi/kernels/argsort_kernel.h
Labels: contributor

#63702 add PD_ConfigEnableCustomDevice new param
  paddle/fluid/inference/capi_exp/pd_config.cc
  paddle/fluid/inference/capi_exp/pd_config.h
Labels: contributor

#63793 remove op_proto in func generate_activation_fn
  python/paddle/tensor/layer_function_generator.py
  python/paddle/tensor/ops.py
Labels: contributor, HappyOpenSource

#63805 [pybind] update `py::exception<>::operator()` to `py::set_error`
  paddle/fluid/pybind/exception.cc
Labels: contributor

#62935 【PIR Dist Op Reg No.10】 reg pull_gpups_sparse
  paddle/fluid/ir_adaptor/translator/op_compat_gen.py
  paddle/fluid/pir/dialect/op_generator/ops_api_gen.py
  paddle/fluid/pir/dialect/operator/interface/parse_kernel_key.cc
  paddle/fluid/pir/dialect/operator/interface/parse_kernel_key.h
  paddle/fluid/pir/dialect/operator/ir/ops.yaml
  paddle/phi/api/yaml/backward.yaml
  paddle/phi/api/yaml/op_compat.yaml
  paddle/phi/infermeta/binary.cc
  paddle/phi/infermeta/binary.h
  paddle/phi/infermeta/ternary.cc
  paddle/phi/infermeta/ternary.h
  test/ir/pir/translator/CMakeLists.txt
  test/ir/pir/translator/test_op_translator.py
  test/ir/pir/translator/test_pull_gpups_sparse_translator.py
Labels: contributor, HappyOpenSource

#63799 [Prim][PIR] support bmm op forward in prim pir
  paddle/fluid/pir/dialect/op_generator/decomp_interface_gen_op_list.py
  paddle/fluid/primitive/composite/composite.h
  test/deprecated/legacy_test/test_bmm_op.py
Labels: contributor

#63726 [PIR][oneDNN] Add self_attention_fuse_pass
  cmake/simd.cmake
  paddle/fluid/inference/api/paddle_pass_builder.cc
  paddle/fluid/pir/transforms/onednn/scale_matmul_fuse_pass.cc
  paddle/fluid/pir/transforms/onednn/self_attention_fuse_pass.cc
  paddle/fluid/pir/transforms/onednn/self_attention_fuse_pass.h
  paddle/fluid/pir/transforms/passes.h
  test/ir/pir/fused_pass/onednn/CMakeLists.txt
  test/ir/pir/fused_pass/onednn/test_self_attention_fuse_pass.py
Labels: Intel, contributor

#63354 [xpu]:fuse unsqueeze2 pad3d squeeze2 as a pass,skip slice,fix nearest_interp bug;
  paddle/fluid/framework/ir/CMakeLists.txt
  paddle/fluid/framework/ir/xpu/conv2d_transpose_xpu_fuse_pass.cc
  paddle/fluid/framework/ir/xpu/conv2d_xpu_fuse_pass.cc
  paddle/fluid/framework/ir/xpu/pad2d_xpu_fuse_pass.cc
  paddle/fluid/inference/api/paddle_pass_builder.cc
  paddle/phi/api/yaml/fused_ops.yaml
  paddle/phi/backends/xpu/xpu2_op_list.cc
  paddle/phi/infermeta/fusion.cc
  paddle/phi/infermeta/fusion.h
  paddle/phi/kernels/fusion/xpu/pad2d_xpu_kernel.cc
  paddle/phi/kernels/xpu/interpolate_kernel.cc
  paddle/phi/kernels/xpu/pad3d_kernel.cc
  paddle/phi/kernels/xpu/slice_kernel.cc
  test/ir/inference/test_xpu_pad2d_fuse.py
Labels: contributor
