Repository PaddlePaddle/Paddle, pull requests merged in 2024-07, with the labels that each got.

#65545 [Typing] 修改一些示例代码中的类型错误 part 3
  python/paddle/base/framework.py
  python/paddle/onnx/export.py
  python/paddle/static/nn/common.py
  python/paddle/vision/models/vgg.py
  python/paddle/vision/transforms/transforms.py
  test/dygraph_to_static/simnet_dygraph_model.py
Labels: PaddlePaddle Hackathon, contributor

#65252 [Prim][PIR] add the test case for concat_grad backward decomposite
  paddle/fluid/primitive/composite/composite.h
  paddle/fluid/primitive/rule/vjp/details.h
  paddle/fluid/primitive/utils/utils.h
  test/prim/pir_prim/test_prim_sub_graph_backward_dynamic_shape.py
Labels: contributor

#65466 【Hackathon 6th Fundable Projects 3 No.245】multi_gru
  paddle/fluid/operators/fused/multi_gru_op.cc
  paddle/fluid/operators/fused/multi_gru_op.h
  paddle/fluid/operators/ops_signature/multi_gru_sig.cc
  paddle/fluid/pir/dialect/operator/utils/utils.cc
  paddle/phi/kernels/onednn/multi_gru_kernel.cc
  paddle/phi/ops/yaml/inconsistent/onednn_static.yaml
  paddle/phi/ops/yaml/op_compat.yaml
Labels: PaddlePaddle Hackathon, contributor

#65420 【Hackathon 6th Fundable Projects 3 No.171】fusion_seqpool_concat
  paddle/fluid/operators/fused/fusion_seqpool_concat_op.cc
  paddle/fluid/operators/fused/fusion_seqpool_concat_op.h
  paddle/phi/infermeta/fusion.cc
  paddle/phi/infermeta/fusion.h
  paddle/phi/kernels/cpu/fusion_seqpool_concat_kernel.cc
  paddle/phi/ops/yaml/fused_ops.yaml
  paddle/phi/ops/yaml/op_compat.yaml
  test/legacy_test/test_fusion_seqpool_concat_op.py
  test/white_list/compile_vs_runtime_white_list.py
Labels: PaddlePaddle Hackathon, contributor

#63028 Update cudnn flash attention
  cmake/external/cudnn-frontend.cmake
  paddle/fluid/framework/ir/fuse_dot_product_attention_pass.cc
  paddle/fluid/framework/ir/graph_pattern_detector.cc
  paddle/fluid/framework/ir/graph_pattern_detector.h
  paddle/fluid/pir/transforms/gpu/fused_dot_product_attention_pass.cc
  paddle/phi/backends/dynload/cudnn_frontend.h
  paddle/phi/infermeta/fusion.cc
  paddle/phi/infermeta/fusion.h
  paddle/phi/kernels/fusion/gpu/fused_dot_product_attention_op.cu
  paddle/phi/kernels/fusion/gpu/max_pool2d_v2_grad_kernel.cu
  paddle/phi/kernels/fusion/gpu/max_pool2d_v2_kernel.cu
  paddle/phi/kernels/gpudnn/mha_cudnn_frontend.cu
  paddle/phi/kernels/gpudnn/mha_cudnn_frontend.h
  paddle/phi/ops/yaml/fused_backward.yaml
  paddle/phi/ops/yaml/fused_ops.yaml
  python/paddle/incubate/nn/functional/__init__.py
  python/paddle/incubate/nn/functional/fused_dot_product_attention.py
  test/deprecated/legacy_test/CMakeLists.txt
  test/legacy_test/CMakeLists.txt
  test/legacy_test/test_fused_dot_product_attention_op.py
  test/legacy_test/test_fused_dot_product_attention_op_static.py
  tools/gpups_test.sh
Labels: NVIDIA

#65006 [Prim][PIR] Support dynamic shape for divide_grad
  paddle/fluid/primitive/rule/vjp/details.h
  python/paddle/autograd/backward_utils.py
  test/prim/pir_prim/test_prim_skip_dynamic.py
  test/prim/pir_prim/test_prim_sub_graph_backward_dynamic_shape.py
Labels: contributor

#65585 [CodeStyle][UP031] fix `/{python, test, tools}/*` - part 19
  paddle/fluid/operators/generator/templates/operator_utils.c.j2
  paddle/phi/api/generator/tensor_operants_gen.py
  python/paddle/autograd/backward_utils.py
  python/paddle/autograd/ir_backward.py
  python/paddle/base/backward.py
  python/paddle/base/compiler.py
  python/paddle/base/framework.py
  python/paddle/distributed/fleet/launch.py
  python/paddle/framework/io.py
  python/paddle/incubate/layers/nn.py
  python/paddle/io/multiprocess_utils.py
  python/paddle/static/io.py
  python/paddle/static/nn/common.py
  python/paddle/tensor/layer_function_generator.py
  setup.py
  test/auto_parallel/test_static_gradient_sync.py
  test/cpp/inference/api/full_pascalvoc_test_preprocess.py
  tools/handle_h_cu_file.py
Labels: contributor

#65609 [Typing] 修理部分示例中的类型缺失 `var-annotated`
  python/paddle/base/executor.py
  python/paddle/distributed/communication/stream/all_to_all.py
  python/paddle/incubate/optimizer/lbfgs.py
  python/paddle/static/input.py
  python/paddle/static/io.py
  python/paddle/static/nn/common.py
  python/paddle/static/nn/static_pylayer.py
  python/paddle/static/pir_io.py
Labels: contributor

#62975 【Hackathon 6th No.30】为 paddle.nn.functional.max_pool1d/max_pool2d /max_pool3d/paddle.signal.stft 进行功能增强
  paddle/phi/infermeta/backward.cc
  paddle/phi/infermeta/backward.h
  paddle/phi/infermeta/unary.cc
  paddle/phi/infermeta/unary.h
  paddle/phi/kernels/funcs/pooling.h
  paddle/phi/kernels/impl/pool_grad_kernel_impl.h
  paddle/phi/kernels/impl/pool_kernel_impl.h
  paddle/phi/kernels/pool_grad_kernel.h
  paddle/phi/kernels/pool_kernel.h
  paddle/phi/kernels/xpu/pool_grad_kernel.cc
  paddle/phi/kernels/xpu/pool_kernel.cc
  paddle/phi/ops/yaml/backward.yaml
  paddle/phi/ops/yaml/op_version.yaml
  paddle/phi/ops/yaml/ops.yaml
  python/paddle/nn/functional/pooling.py
  test/legacy_test/test_pool1d_api.py
  test/legacy_test/test_pool2d_api.py
  test/legacy_test/test_pool3d_api.py
  test/legacy_test/test_pool_max_op.py
  test/legacy_test/test_stft_op.py
Labels: PaddlePaddle Hackathon, contributor, API

#64829 【Hackathon 6th Fundable Projects 2 No.44】 performance-move-const-arg-part
  paddle/fluid/pir/dialect/operator/ir/ir_selected_rows.cc
  paddle/phi/infermeta/spmd_rules/rms_norm.cc
Labels: PaddlePaddle Hackathon, contributor

#65174 【Hackathon 6th Fundable Projects 3 No.350】share_data
  paddle/fluid/operators/share_data_op.cc
  paddle/fluid/operators/share_data_op.cu
  paddle/fluid/operators/share_data_op.h
  paddle/fluid/pir/dialect/operator/utils/utils.cc
  paddle/phi/infermeta/unary.cc
  paddle/phi/infermeta/unary.h
  paddle/phi/kernels/cpu/share_data_kernel.cc
  paddle/phi/kernels/gpu/share_data_kernel.cu
  paddle/phi/kernels/impl/share_data_kernel_impl.h
  paddle/phi/kernels/selected_rows/cpu/share_data_kernel.cc
  paddle/phi/kernels/selected_rows/gpu/share_data_kernel.cu
  paddle/phi/kernels/selected_rows/impl/share_data_kernel_impl.h
  paddle/phi/ops/yaml/op_compat.yaml
  paddle/phi/ops/yaml/ops.yaml
  test/legacy_test/test_share_data_op.py
Labels: PaddlePaddle Hackathon, contributor

#65207 【Hackathon 6th Fundable Projects 3 No.17】beam_search_decode
  paddle/fluid/operators/beam_search_decode_op.cc
  paddle/fluid/operators/beam_search_decode_op.cu.cc
  paddle/fluid/operators/beam_search_decode_op.h
  paddle/fluid/operators/beam_search_decode_op_xpu.cc
  paddle/fluid/pir/dialect/op_generator/ops_api_gen.py
  paddle/phi/infermeta/binary.cc
  paddle/phi/infermeta/binary.h
  paddle/phi/kernels/cpu/beam_search_decode_kernel.cc
  paddle/phi/kernels/funcs/beam_search_decode.h
  paddle/phi/kernels/funcs/beam_search_decode_xpu.h
  paddle/phi/kernels/gpu/beam_search_decode_kernel.cu
  paddle/phi/kernels/impl/beam_search_decode_kernel_impl.h
  paddle/phi/kernels/xpu/beam_search_decode_kernel.cc
  paddle/phi/ops/yaml/inconsistent/static_ops.yaml
  paddle/phi/ops/yaml/legacy/static_ops.yaml
  paddle/phi/ops/yaml/op_compat.yaml
Labels: PaddlePaddle Hackathon, contributor

#65385 【Hackathon 6th Fundable Projects 3 No.118】expand
  paddle/fluid/operators/expand_op.cc
  paddle/fluid/operators/expand_op.h
  paddle/fluid/operators/ops_signature/legacy_expand_sig.cc
  paddle/phi/core/compat/op_utils.h
  paddle/phi/kernels/impl/legacy_expand_kernel_impl.h
  paddle/phi/kernels/legacy/cpu/legacy_expand_grad_kernel.cc
  paddle/phi/kernels/legacy/cpu/legacy_expand_kernel.cc
  paddle/phi/kernels/legacy/gpu/legacy_expand_grad_kernel.cu
  paddle/phi/kernels/legacy/gpu/legacy_expand_kernel.cu
  paddle/phi/ops/yaml/legacy/static_backward.yaml
  paddle/phi/ops/yaml/legacy/static_ops.yaml
  paddle/phi/ops/yaml/op_compat.yaml
  test/legacy_test/test_expand_op.py
  test/legacy_test/test_infer_shape.py
Labels: PaddlePaddle Hackathon, contributor

#65598 【Hackathon 6th Fundable Projects 3 No.106】dlnne_engine 2
  paddle/fluid/inference/analysis/argument.h
  paddle/fluid/inference/api/analysis_config.cc
  paddle/fluid/inference/api/analysis_predictor.cc
  paddle/fluid/inference/api/paddle_analysis_config.h
  paddle/fluid/inference/api/paddle_pass_builder.cc
  paddle/fluid/inference/api/paddle_pass_builder.h
  paddle/fluid/inference/capi/pd_config.cc
  paddle/fluid/pybind/inference_api.cc
Labels: PaddlePaddle Hackathon, contributor

#65489 update static list and open train for some subgraphs
  test/ir/pir/cinn/sub_graphs/CMakeLists.txt
  test/ir/pir/cinn/sub_graphs/base.py
  test/ir/pir/cinn/sub_graphs/test_sub_graph_0.py
  test/ir/pir/cinn/sub_graphs/test_sub_graph_14.py
  test/ir/pir/cinn/sub_graphs/test_sub_graph_16.py
  test/ir/pir/cinn/sub_graphs/test_sub_graph_18.py
  test/ir/pir/cinn/sub_graphs/test_sub_graph_20.py
  test/ir/pir/cinn/sub_graphs/test_sub_graph_25.py
  test/ir/pir/cinn/sub_graphs/test_sub_graph_26.py
  test/ir/pir/cinn/sub_graphs/test_sub_graph_27.py
  test/ir/pir/cinn/sub_graphs/test_sub_graph_28.py
  test/ir/pir/cinn/sub_graphs/test_sub_graph_29.py
  test/ir/pir/cinn/sub_graphs/test_sub_graph_30.py
  test/ir/pir/cinn/sub_graphs/test_sub_graph_31.py
  test/ir/pir/cinn/sub_graphs/test_sub_graph_33.py
  test/ir/pir/cinn/sub_graphs/test_sub_graph_34.py
  test/ir/pir/cinn/sub_graphs/test_sub_graph_43.py
  test/ir/pir/cinn/sub_graphs/test_sub_graph_44.py
  test/ir/pir/cinn/sub_graphs/test_sub_graph_48.py
  test/ir/pir/cinn/sub_graphs/test_sub_graph_49.py
  test/ir/pir/cinn/sub_graphs/test_sub_graph_54.py
  test/ir/pir/cinn/sub_graphs/test_sub_graph_56.py
  test/ir/pir/cinn/sub_graphs/test_sub_graph_57.py
  test/ir/pir/cinn/sub_graphs/test_sub_graph_61.py
  test/ir/pir/cinn/sub_graphs/test_sub_graph_62.py
  test/ir/pir/cinn/sub_graphs/test_sub_graph_65.py
  test/ir/pir/cinn/sub_graphs/test_sub_graph_66.py
  test/ir/pir/cinn/sub_graphs/test_sub_graph_67.py
  test/ir/pir/cinn/sub_graphs/test_sub_graph_69.py
  test/ir/pir/cinn/sub_graphs/test_sub_graph_7.py
  test/ir/pir/cinn/sub_graphs/test_sub_graph_72.py
  test/ir/pir/cinn/sub_graphs/test_sub_graph_73.py
  test/ir/pir/cinn/sub_graphs/test_sub_graph_74.py
  test/ir/pir/cinn/sub_graphs/test_sub_graph_77.py
  test/ir/pir/cinn/sub_graphs/test_sub_graph_80.py
  test/ir/pir/cinn/sub_graphs/test_sub_graph_82.py
  test/ir/pir/cinn/sub_graphs/test_sub_graph_83.py
  test/ir/pir/cinn/sub_graphs/test_sub_graph_86.py
  test/ir/pir/cinn/sub_graphs/test_sub_graph_87.py
  test/ir/pir/cinn/sub_graphs/test_sub_graph_89.py
  test/ir/pir/cinn/sub_graphs/test_sub_graph_9.py
  test/ir/pir/cinn/sub_graphs/test_sub_graph_adaptive_avg_pool2d.py
  test/ir/pir/cinn/sub_graphs/test_sub_graph_add.py
  test/ir/pir/cinn/sub_graphs/test_sub_graph_add_n.py
  test/ir/pir/cinn/sub_graphs/test_sub_graph_avg_pool2d.py
  test/ir/pir/cinn/sub_graphs/test_sub_graph_concat.py
  test/ir/pir/cinn/sub_graphs/test_sub_graph_conv_nd.py
  test/ir/pir/cinn/sub_graphs/test_sub_graph_linear.py
  test/ir/pir/cinn/sub_graphs/test_sub_graph_max_pool2d.py
  test/ir/pir/cinn/sub_graphs/test_sub_graph_mul_method.py
  test/ir/pir/cinn/sub_graphs/test_sub_graph_relu6.py
  test/ir/pir/cinn/sub_graphs/test_sub_graph_sigmoid.py
  test/ir/pir/cinn/sub_graphs/test_sub_graph_split.py
  test/ir/pir/cinn/sub_graphs/test_sub_graph_squeeze_unsqueeze.py
  test/ir/pir/cinn/sub_graphs/test_sub_graph_swish.py
  test/ir/pir/cinn/sub_graphs/test_sub_graph_transpose.py
Labels: contributor

#65566 [Typing][A-91] Add type annotations for `paddle/metric/metrics.py`
  python/paddle/metric/metrics.py
Labels: contributor, HappyOpenSource

#65517 [SOT][dynamic shape] Adapt some InferMeta for dynamic shape
  paddle/phi/infermeta/binary.cc
  paddle/phi/infermeta/fusion.cc
  paddle/phi/infermeta/multiary.cc
  paddle/phi/infermeta/ternary.cc
  test/dygraph_to_static/test_dynamic_shape_infermeta.py
Labels: contributor

#65620 [Typing][B-29] Add type annotations for `python/paddle/distribution/variable.py`
  python/paddle/distribution/constraint.py
  python/paddle/distribution/variable.py
Labels: contributor, HappyOpenSource

#65568 [Typing][A-93] Add type annotations for `paddle/vision/ops.py`
  python/paddle/vision/ops.py
Labels: contributor, HappyOpenSource

#65567 [Typing][A-90] Add type annotations for `paddle/vision/datasets/voc2012.py`
  python/paddle/vision/datasets/voc2012.py
Labels: contributor, HappyOpenSource

#65628 [CINN] dump FeedOp tensor meta
  paddle/cinn/hlir/dialect/operator/transforms/pir_to_py_code_converter.cc
  paddle/fluid/inference/api/analysis_predictor.cc
Labels: contributor

#65588 【Hackathon 6th Fundable Projects 3 No.347、338】sequence_softmax
  paddle/fluid/operators/sequence_ops/sequence_expand_op.cc
  paddle/fluid/operators/sequence_ops/sequence_expand_op.cu
  paddle/fluid/operators/sequence_ops/sequence_expand_op.h
  paddle/fluid/operators/sequence_ops/sequence_softmax_op.cc
  paddle/fluid/operators/sequence_ops/sequence_softmax_op.cu
  paddle/fluid/operators/sequence_ops/sequence_softmax_op.h
  paddle/fluid/pir/dialect/op_generator/ops_api_gen.py
  paddle/phi/infermeta/binary.cc
  paddle/phi/infermeta/binary.h
  paddle/phi/infermeta/unary.cc
  paddle/phi/infermeta/unary.h
  paddle/phi/kernels/cpu/sequence_expand_grad_kernel.cc
  paddle/phi/kernels/cpu/sequence_expand_kernel.cc
  paddle/phi/kernels/cpu/sequence_softmax_grad_kernel.cc
  paddle/phi/kernels/cpu/sequence_softmax_kernel.cc
  paddle/phi/kernels/gpu/sequence_expand_grad_kernel.cu
  paddle/phi/kernels/gpu/sequence_expand_kernel.cu
  paddle/phi/kernels/gpu/sequence_softmax_grad_kernel.cu
  paddle/phi/kernels/gpu/sequence_softmax_kernel.cu
  paddle/phi/kernels/impl/sequence_expand_kernel_impl.h
  paddle/phi/kernels/impl/sequence_softmax_kernel_impl.h
  paddle/phi/ops/yaml/inconsistent/static_backward.yaml
  paddle/phi/ops/yaml/inconsistent/static_ops.yaml
  paddle/phi/ops/yaml/legacy/static_backward.yaml
  paddle/phi/ops/yaml/legacy/static_ops.yaml
  paddle/phi/ops/yaml/op_compat.yaml
  test/sequence/test_sequence_softmax_op.py
Labels: PaddlePaddle Hackathon, contributor

#65647 Open train subgraph
  test/ir/pir/cinn/sub_graphs/test_sub_graph_31.py
  test/ir/pir/cinn/sub_graphs/test_sub_graph_36.py
  test/ir/pir/cinn/sub_graphs/test_sub_graph_48.py
  test/ir/pir/cinn/sub_graphs/test_sub_graph_59.py
  test/ir/pir/cinn/sub_graphs/test_sub_graph_78.py
  test/ir/pir/cinn/sub_graphs/test_sub_graph_chunk.py
Labels: contributor

#65638 [Strided Kernel]fix bug when fallback inplace and not strided kernel
  paddle/phi/api/generator/api_base.py
Labels: contributor, HappyOpenSource

#65643 [Prim][PIR] fix the multiply_grad bug in dynamic shape case
  paddle/fluid/primitive/rule/vjp/details.h
  test/prim/pir_prim/test_prim_sub_graph_backward_dynamic_shape.py
Labels: contributor

#65441 Fp8 ptq kernel function
  paddle/fluid/ir_adaptor/translator/op_translator.cc
  paddle/fluid/operators/fake_quantize_op.cu.h
  paddle/fluid/operators/ops_signature/quantize_linear_sig.cc
  paddle/fluid/operators/quantize_linear_op.cc
  paddle/phi/kernels/funcs/fake_quantize_functor.cc
  paddle/phi/kernels/funcs/fake_quantize_functor.cu
  paddle/phi/kernels/funcs/fake_quantize_functor.h
  paddle/phi/kernels/impl/quantize_linear_impl.h
  paddle/phi/kernels/quantize_linear_kernel.h
  paddle/phi/ops/yaml/inconsistent/static_ops.yaml
  python/paddle/nn/quant/format.py
  python/paddle/static/quantization/quantization_pass.py
  test/deprecated/quantization/test_ptq.py
  test/legacy_test/test_fake_dequantize_op.py
Labels: contributor

#65681 [CINN] Dump pir program only once
  paddle/cinn/hlir/dialect/operator/transforms/pir_to_py_code_converter.cc
Labels: contributor

#65024 Multiple Invocations of AllocAndCopy in ArraySetterBase
  paddle/phi/kernels/funcs/segmented_array.h
Labels: NVIDIA, contributor

#65094 Disabling Unrelated Tests When Enabling CUDA Async Allocator in CI
  paddle/fluid/framework/new_executor/garbage_collector/garbage_collector.h
  paddle/fluid/memory/allocation/allocator_facade.cc
  test/cpp/fluid/memory/CMakeLists.txt
  test/cpp/fluid/memory/stream_safe_cuda_alloc_test.cu
  test/legacy_test/test_auto_growth_allocator_gpu.py
Labels: NVIDIA, contributor

#64436 【Hackathon 6th No.28】为 paddle.round 进行功能增强 -part
  paddle/phi/kernels/activation_kernel.h
  paddle/phi/kernels/cpu/activation_kernel.cc
  paddle/phi/kernels/funcs/activation_functor.h
  paddle/phi/kernels/gpu/activation_kernel.cu
  paddle/phi/kernels/onednn/activation_kernel.cc
  paddle/phi/ops/yaml/backward.yaml
  paddle/phi/ops/yaml/op_version.yaml
  paddle/phi/ops/yaml/ops.yaml
  python/paddle/tensor/ops.py
  test/legacy_test/test_activation_op.py
Labels: PaddlePaddle Hackathon, contributor, API

#65663 Clean some tests
  test/deprecated/legacy_test/test_crop_op.py
  test/legacy_test/CMakeLists.txt
  test/legacy_test/test_bicubic_interp_op.py
  test/legacy_test/test_bilinear_interp_op.py
  test/legacy_test/test_generate_proposals_op.py
  test/legacy_test/test_generate_proposals_v2_op.py
  test/legacy_test/test_linear_interp_op.py
  test/legacy_test/test_lookup_table_op.py
  test/legacy_test/test_matmul_op.py
  test/legacy_test/test_nearest_interp_op.py
  test/legacy_test/test_trilinear_interp_op.py
  test/mkldnn/test_bilinear_interp_mkldnn_op.py
  test/mkldnn/test_matmul_mkldnn_op.py
  test/mkldnn/test_nearest_interp_mkldnn_op.py
  test/xpu/CMakeLists.txt
  test/xpu/test_bilinear_interp_op_xpu.py
  test/xpu/test_matmul_op_xpu.py
  test/xpu/test_nearest_interp_op_xpu.py
Labels: contributor, HappyOpenSource

#65660 [Typing][B-28] Add type annotations for `python/paddle/distribution/uniform.py`
  python/paddle/distribution/uniform.py
Labels: contributor, HappyOpenSource

#65645 [Typing][A-100] Add type annotations for `python/paddle/io/dataloader/worker.py`
  python/paddle/io/dataloader/worker.py
Labels: contributor, HappyOpenSource

#65644 [Typing] 修理部分示例中的类型缺失 `var-annotated` 以及添加具体 ignore 类型
  python/paddle/amp/debugging.py
  python/paddle/base/layers/math_op_patch.py
  python/paddle/distributed/communication/stream/gather.py
  python/paddle/distributed/parallel.py
  python/paddle/optimizer/lbfgs.py
  python/paddle/tensor/attribute.py
  python/paddle/tensor/creation.py
  python/paddle/vision/transforms/transforms.py
Labels: PaddlePaddle Hackathon, contributor

#65700 [Typing] 使用 `Callable` 代替 `type[xxx]`
  python/paddle/vision/models/mobilenetv2.py
  python/paddle/vision/models/mobilenetv3.py
  python/paddle/vision/models/resnet.py
  python/paddle/vision/models/shufflenetv2.py
  python/paddle/vision/ops.py
Labels: PaddlePaddle Hackathon, contributor

#65600 [Typing][B-03] Add type annotations for `python/paddle/distribution/beta.py`
  python/paddle/distribution/beta.py
Labels: contributor, HappyOpenSource

#65697 [Typing] 修改 `tensor.prototype.pyi` 不再使用 Protocol 以及缺失的参数类型
  python/paddle/tensor/manipulation.py
  python/paddle/tensor/stat.py
  python/paddle/tensor/tensor.prototype.pyi
Labels: PaddlePaddle Hackathon, contributor

#65706 Set timeout for test_flash_attention.
  test/legacy_test/CMakeLists.txt
Labels: contributor

#65661 【Hackathon 6th Fundable Projects 3 No.246、247】multiclass_nms
  paddle/fluid/operators/detection/CMakeLists.txt
  paddle/fluid/operators/detection/multiclass_nms_op.cc
  paddle/fluid/operators/generator/get_expected_kernel_func.cc
  paddle/fluid/operators/generator/get_expected_kernel_func.h
  paddle/phi/infermeta/binary.cc
  paddle/phi/infermeta/binary.h
  paddle/phi/kernels/legacy/cpu/multiclass_nms_kernel.cc
  paddle/phi/ops/yaml/legacy/static_ops.yaml
  paddle/phi/ops/yaml/op_compat.yaml
  test/deprecated/legacy_test/test_detection.py
  test/legacy_test/test_multiclass_nms_op.py
Labels: PaddlePaddle Hackathon, contributor

#65629 Clean paddle/fluid/operators/index_select_op.h
  paddle/fluid/operators/index_impl.cu.h
  paddle/fluid/operators/index_select_op.h
  paddle/fluid/operators/repeat_interleave_op.cc
Labels: contributor, HappyOpenSource

#63346 【Hackathon 6th No.25】[Typing] 为 paddle.histogram 进行功能对齐与功能增强 -part
  paddle/phi/infermeta/binary.cc
  paddle/phi/infermeta/binary.h
  paddle/phi/infermeta/unary.cc
  paddle/phi/infermeta/unary.h
  paddle/phi/kernels/cpu/histogram_kernel.cc
  paddle/phi/kernels/gpu/histogram_kernel.cu
  paddle/phi/kernels/histogram_kernel.h
  paddle/phi/ops/yaml/op_compat.yaml
  paddle/phi/ops/yaml/op_version.yaml
  paddle/phi/ops/yaml/ops.yaml
  python/paddle/__init__.py
  python/paddle/tensor/__init__.py
  python/paddle/tensor/linalg.py
  test/legacy_test/test_histogram_bin_edges_op.py
  test/legacy_test/test_histogram_op.py
Labels: PaddlePaddle Hackathon, contributor, API

#65657 [Typing] 设置环境变量 `SKIP_STUB_GEN` 阻止 `gen_tensor_stub.py` 生成 stub 文件
  python/setup.py.in
  setup.py
  tools/gen_tensor_stub.py
Labels: PaddlePaddle Hackathon, contributor

#65712 [PIR][oneDNN] Revise foperator_reshape_onednn_fuse_pass
  paddle/fluid/inference/api/paddle_pass_builder.cc
  paddle/fluid/pir/transforms/onednn/operator_reshape_onednn_fuse_pass.cc
  paddle/fluid/pir/transforms/passes.h
  test/ir/pir/fused_pass/onednn/test_operator_reshape_onednn_fuse_pass.py
Labels: Intel, contributor

#65339 Add cmake argument to set ninja compilation job pools for flash attention.
  cmake/external/flashattn.cmake
Labels: contributor

#65639 【Hackathon 6th No.9】fix reshape op with zero-size tensor input in static mode -part
  paddle/fluid/operators/reshape_op.cc
  paddle/phi/kernels/reshape_kernel.cc
  python/paddle/tensor/manipulation.py
  test/legacy_test/test_zero_size_tensor.py
Labels: PaddlePaddle Hackathon, contributor, API

#65742 [Typing] 修改 `uniform.py` 中输入参数的类型
  python/paddle/distribution/uniform.py
Labels: PaddlePaddle Hackathon, contributor

#65765 [Typing][B-06] Add type annotations for `python/paddle/distribution/cauchy.py`
  python/paddle/distribution/cauchy.py
Labels: contributor

#65767 [Typing][B-08] Add type annotations for `python/paddle/distribution/continuous_bernoulli.py`
  python/paddle/distribution/continuous_bernoulli.py
Labels: contributor

#65692 [Prim][PIR] Support dynamic shape for elementwise_pow_grad
  paddle/fluid/primitive/rule/vjp/details.h
  python/paddle/autograd/backward_utils.py
  test/prim/pir_prim/test_prim_sub_graph_backward_dynamic_shape.py
Labels: contributor

#65770 [Typing][B-11] Add type annotations for `python/paddle/distribution/exponential.py`
  python/paddle/distribution/exponential.py
Labels: contributor

#65768 [Typing][B-09] Add type annotations for `python/paddle/distribution/dirichlet.py`
  python/paddle/distribution/dirichlet.py
Labels: contributor

#65772 [Typing][B-13] Add type annotations for `python/paddle/distribution/gamma.py`
  python/paddle/distribution/gamma.py
Labels: contributor

#65774 [Typing][B-15] Add type annotations for `python/paddle/distribution/gumbel.py`
  python/paddle/distribution/gumbel.py
Labels: contributor

#65769 [Typing][B-10] Add type annotations for `python/paddle/distribution/distribution.py`
  python/paddle/distribution/distribution.py
Labels: contributor

#65773 [Typing][B-14] Add type annotations for `python/paddle/distribution/geometric.py`
  python/paddle/distribution/geometric.py
Labels: contributor

#65766 [Typing][B-07] Add type annotations for `python/paddle/distribution/chi2.py`
  python/paddle/distribution/chi2.py
Labels: contributor

#65776 [Typing][B-17] Add type annotations for `python/paddle/distribution/kl.py`
  python/paddle/distribution/kl.py
Labels: contributor

#65775 [Typing][B-16] Add type annotations for `python/paddle/distribution/independent.py`
  python/paddle/distribution/independent.py
Labels: contributor

#65755 [Typing][A-52] Add type annotations for `python/paddle/hapi/model.py`
  python/paddle/hapi/model.py
Labels: contributor, HappyOpenSource

#65745 [CINN] Dump input meta of builtin parameter and builtin constant
  paddle/cinn/hlir/dialect/operator/transforms/pir_to_py_code_converter.cc
Labels: contributor

#65731 Replace platform::errors phi::errors in paddle/fluid/distributed/collective
  paddle/fluid/distributed/collective/async_load.cc
  paddle/fluid/distributed/collective/bkcl_tools.cc
  paddle/fluid/distributed/collective/bkcl_tools.h
  paddle/fluid/distributed/collective/common.cc
  paddle/fluid/distributed/collective/common.h
  paddle/fluid/distributed/collective/custom_ccl_tools.cc
  paddle/fluid/distributed/collective/mpi_tools.cc
  paddle/fluid/distributed/collective/process_group_bkcl.cc
  paddle/fluid/distributed/collective/process_group_custom.cc
  paddle/fluid/distributed/collective/process_group_gloo.cc
  paddle/fluid/distributed/collective/process_group_gloo.h
  paddle/fluid/distributed/collective/process_group_mpi.cc
  paddle/fluid/distributed/collective/process_group_mpi.h
  paddle/fluid/distributed/collective/process_group_nccl.cc
  paddle/fluid/distributed/collective/reducer.cc
  paddle/fluid/distributed/collective/reducer.h
  paddle/fluid/platform/lodtensor_printer.cc
  paddle/fluid/platform/place.cc
  paddle/phi/common/place.cc
  paddle/phi/common/place.h
Labels: contributor, HappyOpenSource

#65733 Add tile config performance
  test/cpp/pir/cinn/CMakeLists.txt
  test/cpp/pir/cinn/tile_config_performance_test.cc
Labels: contributor

#65715 Add SstaticRdynamic.json for V100
  paddle/cinn/ir/group_schedule/config/tile_config/NVGPU_Tesla_V100_SXM2_32GB/S_R/Sstatic_Rdynamic.json
Labels: contributor

#65666 [Prim][PIR] Modify the function get_reduce_dims_from_out
  paddle/fluid/primitive/base/decomp_trans.cc
  paddle/fluid/primitive/utils/utils.h
Labels: contributor

#65783 Fix a typo `ir_backwardappend_backward` to `ir_backward.append_backward`
  python/paddle/autograd/ir_backward.py
Labels: contributor, HappyOpenSource

#65782 Replace platform::errors:: in distributed/ps
  paddle/fluid/distributed/ps/service/brpc_ps_client.cc
  paddle/fluid/distributed/ps/service/brpc_utils.cc
  paddle/fluid/distributed/ps/service/communicator/communicator.cc
  paddle/fluid/distributed/ps/service/communicator/communicator.h
  paddle/fluid/distributed/ps/service/heter_client.cc
  paddle/fluid/distributed/ps/service/heter_server.h
  paddle/fluid/distributed/ps/service/ps_local_client.cc
  paddle/fluid/distributed/ps/service/server.h
  paddle/fluid/distributed/ps/table/common_graph_table.cc
  paddle/fluid/distributed/ps/table/graph/graph_node.h
  paddle/fluid/distributed/ps/table/memory_dense_table.cc
  paddle/fluid/distributed/ps/table/table.h
  paddle/fluid/distributed/ps/table/tensor_table.h
  paddle/fluid/distributed/ps/wrapper/fleet.cc
  paddle/fluid/distributed/ps/wrapper/fleet.h
Labels: contributor, HappyOpenSource

#65462 【Hackathon 6th Fundable Projects 4 No.5】remove rpc_op_handle/fetch_barrier_op_handle/gather_op_handle -part
  paddle/fluid/framework/compiled_program.cc
  paddle/fluid/framework/details/CMakeLists.txt
  paddle/fluid/framework/details/build_strategy.cc
  paddle/fluid/framework/details/build_strategy.h
  paddle/fluid/framework/details/fetch_barrier_op_handle.cc
  paddle/fluid/framework/details/fetch_barrier_op_handle.h
  paddle/fluid/framework/details/gather_op_handle.cc
  paddle/fluid/framework/details/gather_op_handle.h
  paddle/fluid/framework/details/multi_devices_helper.cc
  paddle/fluid/framework/details/multi_devices_helper.h
  paddle/fluid/framework/details/rpc_op_handle.cc
  paddle/fluid/framework/details/rpc_op_handle.h
  paddle/fluid/framework/distributed_strategy.proto
  paddle/fluid/framework/ir/graph_test.cc
  paddle/fluid/framework/ir/memory_optimize_pass/share_varinfo_into_cinn_pass.cc
  paddle/fluid/framework/ir/multi_devices_graph_pass/CMakeLists.txt
  paddle/fluid/framework/ir/multi_devices_graph_pass/fix_op_run_order_pass.cc
  paddle/fluid/framework/ir/multi_devices_graph_pass/multi_devices_graph_pass.cc
  paddle/fluid/framework/ir/multi_devices_graph_pass/multi_devices_graph_pass.h
  paddle/fluid/framework/ir/multi_devices_graph_pass/sequential_execution_pass.cc
  paddle/fluid/pybind/compiled_program.cc
  paddle/fluid/pybind/pybind.cc
  python/paddle/base/compiler.py
  python/paddle/distributed/fleet/base/distributed_strategy.py
  test/collective/fleet/test_fleet_distributed_strategy.py
  test/cpp/fluid/framework/details/CMakeLists.txt
  test/cpp/fluid/framework/details/gather_op_handle_test.cc
  test/legacy_test/test_cuda_graph_static_mode.py
Labels: PaddlePaddle Hackathon, contributor

#65698 [XPU] Unittest for fill_constant_batch_size_like
  test/xpu/test_fill_constant_batch_size_like_xpu.py
Labels: contributor

#65777 [Typing][A-96, B-43] Add type annotations for `python/paddle/hapi/callbacks.py`, `python/paddle/framework/framework.py`
  python/paddle/base/layer_helper_base.py
  python/paddle/framework/framework.py
  python/paddle/hapi/callbacks.py
Labels: contributor

#65823 [Typing][B-57] Add type annotations for `python/paddle/utils/dlpack.py`
  python/paddle/utils/dlpack.py
Labels: contributor

#65807 [Typing][B-84] Add type annotations for `python/paddle/nn/quant/stub.py`
  python/paddle/nn/quant/stub.py
Labels: PaddlePaddle Hackathon, contributor

#65821 [Typing][B-55] Add type annotations for `python/paddle/utils/install_check.py`
  python/paddle/utils/install_check.py
Labels: contributor

#65819 [Typing][B-54] Add type annotations for `python/paddle/utils/cpp_extension/extension_utils.py`
  python/paddle/utils/cpp_extension/extension_utils.py
Labels: contributor

#65479 【Hackathon 6th Fundable Projects 3 No.19、21、203、254、387】 interpolate
  paddle/fluid/operators/interpolate_op.cc
  paddle/fluid/operators/interpolate_op.cu
  paddle/fluid/operators/interpolate_op.h
  paddle/fluid/operators/onednn/interpolate_onednn_op.cc
  paddle/phi/core/compat/op_utils.h
  paddle/phi/infermeta/multiary.cc
  paddle/phi/infermeta/multiary.h
  paddle/phi/kernels/cpu/interpolate_grad_kernel.cc
  paddle/phi/kernels/cpu/interpolate_kernel.cc
  paddle/phi/kernels/gpu/interpolate_grad_kernel.cu
  paddle/phi/kernels/gpu/interpolate_kernel.cu
  paddle/phi/kernels/onednn/interpolate_kernel.cc
  paddle/phi/ops/yaml/legacy/static_backward.yaml
  paddle/phi/ops/yaml/legacy/static_ops.yaml
  paddle/phi/ops/yaml/op_compat.yaml
Labels: PaddlePaddle Hackathon, contributor

#65830 Replace platform::CPUPlace in test/cpp/eager
  test/cpp/eager/data_structure_tests/accumulation_node_test.cc
  test/cpp/eager/data_structure_tests/autograd_meta_test.cc
  test/cpp/eager/data_structure_tests/eager_tensor_test.cc
  test/cpp/eager/data_structure_tests/grad_node_info_test.cc
  test/cpp/eager/data_structure_tests/grad_node_test.h
  test/cpp/eager/data_structure_tests/grad_tensor_holder_test.cc
  test/cpp/eager/data_structure_tests/tensor_wrapper_test.cc
  test/cpp/eager/performance_tests/benchmark_eager_cpu.cc
  test/cpp/eager/performance_tests/benchmark_eager_cuda.cc
  test/cpp/eager/performance_tests/benchmark_fluid_cpu.cc
  test/cpp/eager/performance_tests/benchmark_fluid_cuda.cc
  test/cpp/eager/performance_tests/benchmark_utils.cc
  test/cpp/eager/performance_tests/benchmark_utils.h
  test/cpp/eager/task_tests/backward_test.cc
  test/cpp/eager/task_tests/cross_batch_accumulation_test.cc
  test/cpp/eager/task_tests/eager_utils_test.cc
  test/cpp/eager/task_tests/forward_autograd_test.cc
  test/cpp/eager/task_tests/fwd_bwd_joint_test.cc
  test/cpp/eager/task_tests/generated_test.cc
  test/cpp/eager/task_tests/grad_test.cc
  test/cpp/eager/task_tests/hook_test.cc
  test/cpp/eager/task_tests/hook_test_intermidiate.cc
  test/cpp/eager/task_tests/tensor_utils_test.cc
  test/cpp/eager/test_utils.h
Labels: contributor, HappyOpenSource

#65826 Replace platform::CPUPlace in paddle/fluid/imperative
  paddle/fluid/imperative/all_reduce.cc
  paddle/fluid/imperative/gloo_context.cc
  paddle/fluid/imperative/gradient_accumulator.cc
  paddle/fluid/imperative/heter_ccl_context.cc
  paddle/fluid/imperative/heter_ccl_context.h
  paddle/fluid/imperative/layer.cc
  paddle/fluid/imperative/layer.h
  paddle/fluid/imperative/op_base.h
  paddle/fluid/imperative/parallel_context.h
  paddle/fluid/imperative/partial_grad_engine.cc
  paddle/fluid/imperative/partial_grad_engine.h
  paddle/fluid/imperative/prepared_operator.cc
  paddle/fluid/imperative/reducer.h
  paddle/fluid/imperative/tracer.cc
  paddle/fluid/imperative/tracer.h
  paddle/fluid/imperative/var_helper.cc
  paddle/fluid/imperative/var_helper.h
  paddle/fluid/imperative/variable_wrapper.h
Labels: contributor, HappyOpenSource

#65825 Replace platform::CPUPlace in paddle/fluid/inference
  paddle/fluid/inference/analysis/passes/convert_to_mixed_precision.cc
  paddle/fluid/inference/analysis/passes/ir_graph_build_pass.cc
  paddle/fluid/inference/analysis/passes/ir_graph_build_pass.h
  paddle/fluid/inference/analysis/passes/ir_params_sync_among_devices_pass.cc
  paddle/fluid/inference/analysis/passes/save_optimized_model_pass.cc
  paddle/fluid/inference/api/analysis_predictor.cc
  paddle/fluid/inference/api/analysis_predictor.h
  paddle/fluid/inference/api/api_impl.cc
  paddle/fluid/inference/api/api_impl.h
  paddle/fluid/inference/api/details/zero_copy_tensor.cc
  paddle/fluid/inference/api/helper.h
  paddle/fluid/inference/api/onnxruntime_predictor.cc
  paddle/fluid/inference/api/onnxruntime_predictor.h
  paddle/fluid/inference/api/paddle_infer_contrib.cc
  paddle/fluid/inference/io.cc
  paddle/fluid/inference/tensorrt/convert/batch_norm_op.cc
  paddle/fluid/inference/tensorrt/convert/dropout_op.cc
  paddle/fluid/inference/tensorrt/convert/fill_constant_op.cc
  paddle/fluid/inference/tensorrt/convert/gelu_op.cc
  paddle/fluid/inference/tensorrt/convert/leaky_relu_op.cc
  paddle/fluid/inference/tensorrt/convert/op_converter.h
  paddle/fluid/inference/tensorrt/convert/scale_op.cc
  paddle/fluid/inference/tensorrt/convert/test_io_converter.cc
  paddle/fluid/inference/tensorrt/convert/test_op_converter.cc
  paddle/fluid/inference/tensorrt/convert/ut_helper.h
  paddle/fluid/inference/tensorrt/engine.cc
  paddle/fluid/inference/tensorrt/plugin/custom_generic_plugin.cu
  paddle/fluid/inference/tensorrt/plugin/deformable_conv_op_plugin.cu
  paddle/fluid/inference/tensorrt/plugin/elementwiseadd_transpose_op_plugin.cu
  paddle/fluid/inference/tensorrt/plugin/fused_token_prune_op_plugin.cu
  paddle/fluid/inference/tensorrt/plugin/generic_plugin.cu
  paddle/fluid/inference/tensorrt/plugin/instance_norm_op_plugin.cu
  paddle/fluid/inference/tensorrt/plugin/layer_norm_op_plugin.cu
  paddle/fluid/inference/tensorrt/plugin/multihead_matmul_roformer_plugin.cu
  paddle/fluid/inference/tensorrt/plugin/qkv_to_context_plugin.cu
  paddle/fluid/inference/tensorrt/plugin/trans_layernorm_op_plugin.cu
  paddle/fluid/inference/tensorrt/plugin/transformer_input_output_convert_plugin.cu
  paddle/fluid/inference/tensorrt/test_dynamic_engine.cc
  paddle/fluid/inference/tensorrt/test_engine.cc
  paddle/fluid/inference/tensorrt/trt_int8_calibrator.cc
  paddle/fluid/inference/tensorrt/trt_int8_calibrator.h
Labels: contributor, HappyOpenSource

#65761 Add label for fluid ops to skip coverage
  tools/get_pr_title.py
Labels: contributor, HappyOpenSource

#65810 [Typing][B-87] Add type annotations for `python/paddle/nn/utils/spectral_norm_hook.py`
  python/paddle/nn/utils/spectral_norm_hook.py
Labels: PaddlePaddle Hackathon, contributor

#65808 [Typing][B-85] Add type annotations for `python/paddle/nn/utils/clip_grad_norm_.py`
  python/paddle/nn/utils/clip_grad_norm_.py
Labels: PaddlePaddle Hackathon, contributor

#65824 [Typing][B-58] Add type annotations for `python/paddle/utils/download.py`
  python/paddle/utils/download.py
Labels: PaddlePaddle Hackathon, contributor

#65553 [Typing][A-89] Add type annotations for `python/paddle/vision/datasets/mnist.py`
  python/paddle/vision/datasets/mnist.py
Labels: contributor, HappyOpenSource

#65827 Replace platform::CPUPlace in paddle/fluid/memory
  paddle/fluid/memory/allocation/allocator.h
  paddle/fluid/memory/allocation/allocator_facade.cc
  paddle/fluid/memory/allocation/allocator_facade.h
  paddle/fluid/memory/allocation/auto_growth_best_fit_allocator.h
  paddle/fluid/memory/allocation/auto_growth_best_fit_allocator_v2.cc
  paddle/fluid/memory/allocation/auto_growth_best_fit_allocator_v2.h
  paddle/fluid/memory/allocation/cpu_allocator.cc
  paddle/fluid/memory/allocation/cuda_allocator.h
  paddle/fluid/memory/allocation/cuda_device_context_allocator.h
  paddle/fluid/memory/allocation/cuda_ipc_allocator.h
  paddle/fluid/memory/allocation/cuda_malloc_async_allocator.cc
  paddle/fluid/memory/allocation/cuda_malloc_async_allocator.h
  paddle/fluid/memory/allocation/cuda_managed_allocator.h
  paddle/fluid/memory/allocation/cuda_virtual_mem_allocator.cc
  paddle/fluid/memory/allocation/cuda_virtual_mem_allocator.h
  paddle/fluid/memory/allocation/custom_allocator.h
  paddle/fluid/memory/allocation/mmap_allocator.h
  paddle/fluid/memory/allocation/naive_best_fit_allocator.cc
  paddle/fluid/memory/allocation/naive_best_fit_allocator.h
  paddle/fluid/memory/allocation/pinned_allocator.cc
  paddle/fluid/memory/allocation/stream_safe_cuda_allocator.cc
  paddle/fluid/memory/allocation/stream_safe_cuda_allocator.h
  paddle/fluid/memory/allocation/stream_safe_custom_device_allocator.cc
  paddle/fluid/memory/allocation/stream_safe_custom_device_allocator.h
  paddle/fluid/memory/allocation/stream_safe_xpu_allocator.cc
  paddle/fluid/memory/allocation/stream_safe_xpu_allocator.h
  paddle/fluid/memory/allocation/system_allocator.cc
  paddle/fluid/memory/allocation/thread_local_allocator.cc
  paddle/fluid/memory/allocation/thread_local_allocator.h
  paddle/fluid/memory/allocation/virtual_memory_auto_growth_best_fit_allocator.cc
  paddle/fluid/memory/allocation/virtual_memory_auto_growth_best_fit_allocator.h
  paddle/fluid/memory/allocation/xpu_allocator.h
  paddle/fluid/memory/malloc.cc
  paddle/fluid/memory/malloc.h
  paddle/fluid/memory/memcpy.cc
Labels: contributor, HappyOpenSource

#65829 Replace platform::CPUPlace in paddle/fluid/pybind
  paddle/fluid/pybind/cuda_streams_py.cc
  paddle/fluid/pybind/custom_device_py.cc
  paddle/fluid/pybind/data_set_py.cc
  paddle/fluid/pybind/distributed_py.cc
  paddle/fluid/pybind/eager.cc
  paddle/fluid/pybind/eager_functions.cc
  paddle/fluid/pybind/eager_math_op_patch.cc
  paddle/fluid/pybind/eager_method.cc
  paddle/fluid/pybind/eager_utils.cc
  paddle/fluid/pybind/eager_utils.h
  paddle/fluid/pybind/imperative.cc
  paddle/fluid/pybind/io.cc
  paddle/fluid/pybind/jit.cc
  paddle/fluid/pybind/place.cc
  paddle/fluid/pybind/pybind.cc
  paddle/fluid/pybind/tensor.cc
  paddle/fluid/pybind/tensor_py.h
  paddle/fluid/pybind/uva_utils.h
Labels: contributor, HappyOpenSource

#65668 [OneDNN][PIR] Add conv2d_transpose_bn_fuse_pass
  paddle/fluid/inference/api/paddle_pass_builder.cc
  paddle/fluid/pir/transforms/onednn/conv2d_transpose_bn_fuse_pass.cc
  paddle/fluid/pir/transforms/onednn/conv2d_transpose_bn_fuse_pass.h
  paddle/fluid/pir/transforms/passes.h
  test/ir/pir/fused_pass/onednn/test_conv_transpose_bn_onednn_fuse_pass.py
Labels: Intel, contributor

#65818 [Typing][B-53] Add type annotations for `python/paddle/utils/cpp_extension/cpp_extension.py`
  python/paddle/utils/cpp_extension/cpp_extension.py
Labels: PaddlePaddle Hackathon, contributor

#65812 [Typing][B-89] Add type annotations for `python/paddle/nn/utils/weight_norm_hook.py`
  python/paddle/nn/utils/weight_norm_hook.py
Labels: PaddlePaddle Hackathon, contributor

#65803 [Typing][B-82] Add type annotations for `python/paddle/nn/quant/quant_layers.py`
  python/paddle/nn/quant/quant_layers.py
Labels: PaddlePaddle Hackathon, contributor

#65816 [CINN] dump DenseTensorArrayType for pir pycode
  paddle/cinn/hlir/dialect/operator/transforms/pir_to_py_code_converter.cc
  paddle/cinn/hlir/dialect/operator/transforms/type_adt_type_id.cc
  paddle/cinn/hlir/dialect/operator/transforms/type_adt_type_id.h
  paddle/fluid/pir/dialect/operator/ir/op_type.h
Labels: contributor

#65862 [fluid_ops]Replace platform::is_gpu_place in fluid/imperative
  paddle/fluid/imperative/all_reduce.cc
  paddle/fluid/imperative/amp_auto_cast.cc
  paddle/fluid/imperative/amp_utils.h
  paddle/fluid/imperative/bkcl_context.cc
  paddle/fluid/imperative/gradient_accumulator.cc
  paddle/fluid/imperative/nccl_context.cc
  paddle/fluid/imperative/prepared_operator.cc
  paddle/fluid/imperative/reducer.cc
  paddle/fluid/imperative/tracer.cc
  paddle/fluid/imperative/xccl_context.cc
Labels: contributor

#65836 Replace paddle::platform::DeviceContextPool in fluid/pybind
  paddle/fluid/pybind/custom_device_py.cc
  paddle/fluid/pybind/eager_method.cc
  paddle/fluid/pybind/imperative.cc
  paddle/fluid/pybind/pybind.cc
  paddle/fluid/pybind/slice_utils.h
  paddle/fluid/pybind/tensor_py.h
  paddle/fluid/pybind/uva_utils.h
  paddle/fluid/pybind/xpu_streams_py.cc
Labels: contributor, HappyOpenSource

#65865 [Typing][B-67] Add type annotations for `python/paddle/sparse/binary.py`
  python/paddle/sparse/binary.py
Labels: contributor

#65870 [Typing][B-72] Add type annotations for `python/paddle/sparse/nn/layer/conv.py`
  python/paddle/sparse/nn/layer/conv.py
Labels: contributor

#65866 [Typing][B-68] Add type annotations for `python/paddle/sparse/creation.py`
  python/paddle/sparse/creation.py
Labels: contributor

#65890 [CINN] Fix bug of ArgsortOp infer symbolic shape
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/same_operands_result.cc
Labels: contributor

#65750 [PIR][oneDNN] Add conv2d_bias_bn_onednn_fuse_pass
  paddle/fluid/inference/api/paddle_pass_builder.cc
  paddle/fluid/pir/transforms/onednn/conv2d_bn_onednn_fuse_pass.cc
  paddle/fluid/pir/transforms/onednn/conv2d_bn_onednn_fuse_pass.h
  paddle/fluid/pir/transforms/passes.h
  test/ir/pir/fused_pass/onednn/test_conv2d_bn_onednn_fuse_pass.py
Labels: Intel, contributor

#65886 [PIR] Fix 4 unittests in pir mode
  python/paddle/utils/install_check.py
  test/deprecated/legacy_test/CMakeLists.txt
  test/legacy_test/CMakeLists.txt
  test/legacy_test/test_imperative_ptb_rnn.py
  test/legacy_test/test_imperative_ptb_rnn_sorted_gradient.py
  test/legacy_test/test_imperative_recurrent_usage.py
  test/legacy_test/test_install_check.py
Labels: contributor

#65844 [Typing][B-21] Add type annotations for `python/paddle/distribution/multinomial.py`
  python/paddle/distribution/multinomial.py
Labels: contributor, HappyOpenSource

#65605 【Hackathon 6th No.9】Add cartesian_prod API to Paddle
  python/paddle/__init__.py
  python/paddle/tensor/__init__.py
  python/paddle/tensor/math.py
  test/legacy_test/test_cartesian_prod.py
Labels: PaddlePaddle Hackathon, contributor, API

#65798 Replace platform::errors in fluid/platform
  paddle/fluid/platform/bfloat16_test.cc
  paddle/fluid/platform/collective_helper.cc
  paddle/fluid/platform/collective_helper.h
  paddle/fluid/platform/cpu_helper.cc
  paddle/fluid/platform/cuda_graph_with_memory_pool.cc
  paddle/fluid/platform/device/custom/custom_device_resource_pool.cc
  paddle/fluid/platform/device/gpu/cuda/cuda_profiler.cc
  paddle/fluid/platform/device/gpu/gpu_info.cc
  paddle/fluid/platform/device/gpu/gpu_launch_config.h
  paddle/fluid/platform/device/gpu/gpu_resource_pool.cc
  paddle/fluid/platform/device/gpu/nccl_helper.h
  paddle/fluid/platform/device/ipu/ipu_compiler.cc
  paddle/fluid/platform/device/ipu/ipu_device.cc
  paddle/fluid/platform/device/ipu/ipu_executor.cc
  paddle/fluid/platform/device/ipu/ipu_strategy.cc
  paddle/fluid/platform/device/ipu/ipu_strategy.h
  paddle/fluid/platform/device/ipu/ipu_utils.cc
  paddle/fluid/platform/device/ipu/popart_canonicalization/activation_ops.cc
  paddle/fluid/platform/device/ipu/popart_canonicalization/canonicalization_utils.cc
  paddle/fluid/platform/device/ipu/popart_canonicalization/loss_ops.cc
  paddle/fluid/platform/device/ipu/popart_canonicalization/math_ops.cc
  paddle/fluid/platform/device/ipu/popart_canonicalization/nn_ops.cc
  paddle/fluid/platform/device/ipu/popart_canonicalization/op_builder.cc
  paddle/fluid/platform/device/ipu/popart_canonicalization/search_ops.cc
  paddle/fluid/platform/device/ipu/popart_canonicalization/tensor_ops.cc
  paddle/fluid/platform/device/xpu/bkcl_helper.h
  paddle/fluid/platform/device/xpu/xpu_info.cc
  paddle/fluid/platform/device/xpu/xpu_resource_pool.cc
  paddle/fluid/platform/device_context.cc
  paddle/fluid/platform/device_context.h
  paddle/fluid/platform/device_event_base.cc
  paddle/fluid/platform/device_event_base.h
  paddle/fluid/platform/device_event_cpu.h
  paddle/fluid/platform/device_event_custom_device.cc
  paddle/fluid/platform/device_event_gpu.cc
  paddle/fluid/platform/dynload/tensorrt.cc
  paddle/fluid/platform/dynload/tensorrt.h
  paddle/fluid/platform/enforce_test.cc
  paddle/fluid/platform/float16_test.cc
  paddle/fluid/platform/float16_test.cu
  paddle/fluid/platform/gen_comm_id_helper.cc
  paddle/fluid/platform/gloo_context.cc
  paddle/fluid/platform/init.cc
  paddle/fluid/platform/lodtensor_printer.cc
  paddle/fluid/platform/onednn_helper.h
  paddle/fluid/platform/place.h
  paddle/fluid/platform/place_test.cc
  paddle/fluid/platform/profiler.cc
  paddle/fluid/platform/profiler/cuda_tracer.cc
  paddle/fluid/platform/profiler/custom_device/custom_tracer.cc
  paddle/fluid/platform/profiler/event_node.cc
  paddle/fluid/platform/profiler/event_node.h
  paddle/fluid/platform/profiler/host_tracer.cc
  paddle/fluid/platform/profiler/utils.h
  paddle/fluid/platform/profiler/xpu_tracer.cc
  paddle/fluid/platform/profiler_helper.h
  paddle/fluid/platform/resource_pool.h
Labels: contributor, HappyOpenSource

#65616 【Hackathon 6th Fundable Projects 3 No.311】[fluid_ops]resnet_unit
  paddle/fluid/operators/fused/CMakeLists.txt
  paddle/fluid/operators/fused/resnet_unit_op.cc
  paddle/fluid/operators/fused/resnet_unit_op.cu
  paddle/fluid/operators/fused/resnet_unit_op_xpu.cc
  paddle/phi/infermeta/fusion.cc
  paddle/phi/infermeta/fusion.h
  paddle/phi/kernels/fusion/gpu/resnet_unit_grad_kernel.cu
  paddle/phi/kernels/fusion/gpu/resnet_unit_kernel.cu
  paddle/phi/kernels/fusion/xpu/resnet_unit_grad_kernel.cc
  paddle/phi/kernels/fusion/xpu/resnet_unit_kernel.cc
  paddle/phi/ops/yaml/fused_backward.yaml
  paddle/phi/ops/yaml/fused_ops.yaml
  paddle/phi/ops/yaml/op_compat.yaml
Labels: PaddlePaddle Hackathon, contributor

#64953 【Hackathon 6th Fundable Projects 3 No.77】[fluid_ops]crop
  paddle/fluid/operators/crop_op.cc
  paddle/fluid/operators/crop_op.h
  paddle/phi/core/compat/op_utils.h
  paddle/phi/infermeta/binary.cc
  paddle/phi/infermeta/binary.h
  paddle/phi/kernels/impl/legacy_crop_kernel_impl.h
  paddle/phi/kernels/legacy/cpu/legacy_crop_grad_kernel.cc
  paddle/phi/kernels/legacy/cpu/legacy_crop_kernel.cc
  paddle/phi/kernels/legacy/gpu/legacy_crop_grad_kernel.cu
  paddle/phi/kernels/legacy/gpu/legacy_crop_kernel.cu
  paddle/phi/ops/yaml/legacy/static_backward.yaml
  paddle/phi/ops/yaml/legacy/static_ops.yaml
  paddle/phi/ops/yaml/op_compat.yaml
  test/cpp/fluid/mkldnn/test_onednn_op_nhwc.cc
Labels: PaddlePaddle Hackathon, contributor

#65853 [Typing][B-25] Add type annotations for `python/paddle/distribution/student_t.py`
  python/paddle/distribution/student_t.py
Labels: contributor, HappyOpenSource

#65874 [Typing][B-76] Add type annotations for `python/paddle/sparse/nn/functional/conv.py`
  python/paddle/sparse/nn/functional/conv.py
Labels: PaddlePaddle Hackathon, contributor

#65871 [Typing][B-73] Add type annotations for `python/paddle/sparse/nn/layer/norm.py`
  python/paddle/nn/layer/norm.py
  python/paddle/sparse/nn/layer/norm.py
Labels: PaddlePaddle Hackathon, contributor

#65891 [Typing] 修复`Model` 中 `callbacks` 的参数类型
  python/paddle/hapi/model.py
Labels: PaddlePaddle Hackathon, contributor

#65809 [Typing][B-86] Add type annotations for `python/paddle/nn/utils/clip_grad_value_.py`
  python/paddle/nn/utils/clip_grad_value_.py
Labels: PaddlePaddle Hackathon, contributor

#65863 [fluid_ops]Replace platform::is_gpu_place in fluid/inference
  paddle/fluid/inference/api/analysis_predictor.cc
  paddle/fluid/inference/api/api_impl.cc
  paddle/fluid/inference/api/details/zero_copy_tensor.cc
  paddle/fluid/inference/api/onnxruntime_predictor.cc
  paddle/fluid/inference/tensorrt/convert/io_converter.cc
Labels: contributor, HappyOpenSource

#65840 [fluid_ops]Replace framework::DDim in paddle/fluid/pybind
  paddle/fluid/pybind/eager_method.cc
  paddle/fluid/pybind/reader_py.cc
  paddle/fluid/pybind/tensor_py.h
Labels: contributor, HappyOpenSource

#65867 [Typing][B-69] Add type annotations for `python/paddle/sparse/multiary.py`
  python/paddle/sparse/multiary.py
Labels: PaddlePaddle Hackathon, contributor

#65855 [CINN] Fix infer_symbol_shape of test_tile_op
  test/legacy_test/test_tile_op.py
Labels: contributor

#65781 [fluid_ops]Migrate distributed/collective/process_group.h
  paddle/fluid/distributed/collective/process_group.cc
  paddle/fluid/distributed/collective/process_group.h
  paddle/fluid/operators/class_center_sample_op.cu
  paddle/fluid/operators/collective/c_allreduce_op.h
  paddle/fluid/operators/sync_batch_norm_utils.h
  paddle/phi/core/distributed/CMakeLists.txt
  paddle/phi/core/distributed/collective/CMakeLists.txt
  paddle/phi/core/distributed/collective/process_group.cc
  paddle/phi/core/distributed/collective/process_group.h
Labels: contributor, HappyOpenSource

#65898 Revert "【Hackathon 6th Fundable Projects 3 No.158】fused_gate_attention"[fluid_ops]
  paddle/fluid/eager/api/manual/fluid_manual/forwards/CMakeLists.txt
  paddle/fluid/eager/api/manual/fluid_manual/forwards/fused_gate_attention_fwd_func.cc
  paddle/fluid/eager/api/manual/fluid_manual/nodes/CMakeLists.txt
  paddle/fluid/eager/api/manual/fluid_manual/nodes/fused_gate_attention_node.cc
  paddle/fluid/operators/fused/CMakeLists.txt
  paddle/fluid/operators/fused/fused_gate_attention.h
  paddle/fluid/operators/fused/fused_gate_attention_op.cc
  paddle/fluid/operators/fused/fused_gate_attention_op.cu
  paddle/fluid/pybind/eager_generator.h
  test/deprecated/legacy_test/CMakeLists.txt
  test/legacy_test/CMakeLists.txt
  test/legacy_test/test_fused_gate_attention_op.py
Labels: PaddlePaddle Hackathon, contributor

#65904 【Hackathon 6th No.9】Fix cartesian_prod API docs -part
  python/paddle/tensor/math.py
Labels: PaddlePaddle Hackathon, contributor

#65822 [Typing][B-56] Add type annotations for `python/paddle/utils/lazy_import.py`
  python/paddle/utils/lazy_import.py
Labels: PaddlePaddle Hackathon, contributor

#65872 [Typing][B-74] Add type annotations for `python/paddle/sparse/nn/layer/pooling.py`
  python/paddle/nn/layer/pooling.py
  python/paddle/sparse/nn/layer/pooling.py
Labels: PaddlePaddle Hackathon, contributor

#65873 [Typing][B-75] Add type annotations for `python/paddle/sparse/nn/functional/activation.py`
  python/paddle/sparse/nn/functional/activation.py
Labels: PaddlePaddle Hackathon, contributor

#65837 [fluid_ops]Replace paddle::platform::DeviceContextPool in fluid/imperative
  paddle/fluid/imperative/all_reduce.cc
  paddle/fluid/imperative/basic_engine.cc
  paddle/fluid/imperative/bkcl_context.cc
  paddle/fluid/imperative/gradient_accumulator.cc
  paddle/fluid/imperative/layer.cc
  paddle/fluid/imperative/nccl_context.cc
  paddle/fluid/imperative/partial_grad_engine.cc
  paddle/fluid/imperative/prepared_operator.cc
  paddle/fluid/imperative/reducer.cc
  paddle/fluid/imperative/tracer.cc
  paddle/fluid/imperative/xccl_context.cc
  paddle/fluid/inference/api/analysis_predictor.cc
  paddle/fluid/inference/api/api_impl.cc
  paddle/fluid/inference/api/details/zero_copy_tensor.cc
  paddle/fluid/inference/api/details/zero_copy_tensor_test.cc
  paddle/fluid/inference/api/onednn_quantizer.cc
  paddle/fluid/inference/api/onnxruntime_predictor.cc
  paddle/fluid/inference/api/paddle_infer_contrib.cc
  paddle/fluid/inference/tensorrt/plugin/deformable_conv_op_plugin.cu
  paddle/fluid/inference/tensorrt/plugin/elementwiseadd_transpose_op_plugin.cu
  paddle/fluid/inference/tensorrt/plugin/generic_plugin.cu
  paddle/fluid/inference/tensorrt/plugin/multihead_matmul_roformer_plugin.cu
  paddle/fluid/inference/tensorrt/plugin/qkv_to_context_plugin.cu
  paddle/fluid/inference/tensorrt/plugin/trans_layernorm_op_plugin.cu
Labels: contributor, HappyOpenSource

#65796 Clean paddle/fluid/platform/device/xpu/xpu_header.h
  paddle/fluid/distributed/collective/process_group_bkcl.h
  paddle/fluid/framework/fleet/heter_ps/heter_comm.h
  paddle/fluid/framework/fleet/heter_ps/heter_resource.cc
  paddle/fluid/framework/fleet/ps_gpu_wrapper.h
  paddle/fluid/imperative/reducer.cc
  paddle/fluid/memory/allocation/stream_safe_xpu_allocator.cc
  paddle/fluid/memory/memcpy.cc
  paddle/fluid/platform/device/device_wrapper.h
  paddle/fluid/platform/device/xpu/bkcl_helper.h
  paddle/fluid/platform/device/xpu/enforce_xpu.h
  paddle/fluid/platform/device/xpu/xpu_header.h
  paddle/fluid/platform/device/xpu/xpu_info.cc
  paddle/fluid/platform/device_context.h
  paddle/fluid/platform/init.cc
  test/xpu/cpp/enforce_xpu_test.cc
Labels: contributor, HappyOpenSource

#65909 fix auto_parallel CI exit -6
  tools/auto_parallel/ci_auto_parallel.sh
Labels: contributor

#65878 [CINN] Fix infer_symbol_shape of test_concat_op
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/multiary_infer_sym.cc
  test/legacy_test/test_concat_op.py
Labels: contributor

#65869 [Typing][B-71] Add type annotations for `python/paddle/sparse/nn/layer/activation.py`
  python/paddle/sparse/nn/layer/activation.py
Labels: PaddlePaddle Hackathon, contributor

#65868 [Typing][B-70] Add type annotations for `python/paddle/sparse/unary.py`
  python/paddle/sparse/unary.py
Labels: PaddlePaddle Hackathon, contributor

#65849 [Typing][B-23] Add type annotations for `python/paddle/distribution/normal.py`
  python/paddle/distribution/normal.py
Labels: contributor, HappyOpenSource

#65875 [Typing][B-77] Add type annotations for `python/paddle/sparse/nn/functional/pooling.py`
  python/paddle/sparse/nn/functional/pooling.py
Labels: PaddlePaddle Hackathon, contributor

#65876 [Typing][B-78] Add type annotations for `python/paddle/sparse/nn/functional/transformer.py`
  python/paddle/sparse/nn/functional/transformer.py
Labels: PaddlePaddle Hackathon, contributor

#65864 [fluid_ops]Replace platform::is_gpu_place in test/ - part1
  test/cpp/eager/data_structure_tests/eager_tensor_test.cc
  test/cpp/eager/performance_tests/benchmark_eager_cpu.cc
  test/cpp/eager/performance_tests/benchmark_eager_cuda.cc
  test/cpp/eager/performance_tests/benchmark_fluid_cpu.cc
  test/cpp/eager/performance_tests/benchmark_fluid_cuda.cc
  test/cpp/eager/performance_tests/benchmark_utils.cc
  test/cpp/eager/task_tests/backward_test.cc
  test/cpp/eager/task_tests/cross_batch_accumulation_test.cc
  test/cpp/eager/task_tests/eager_utils_test.cc
  test/cpp/eager/task_tests/forward_autograd_test.cc
  test/cpp/eager/task_tests/fwd_bwd_joint_test.cc
  test/cpp/eager/task_tests/generated_test.cc
  test/cpp/eager/task_tests/grad_test.cc
  test/cpp/eager/task_tests/hook_test.cc
  test/cpp/eager/task_tests/hook_test_intermidiate.cc
  test/cpp/eager/task_tests/tensor_utils_test.cc
  test/cpp/eager/test_utils.h
  test/cpp/imperative/test_eager.cc
  test/cpp/imperative/test_gradient_accmulator.cc
  test/cpp/imperative/test_group.cc
  test/cpp/imperative/test_layer.cc
  test/cpp/imperative/test_prepare_op.cc
  test/cpp/imperative/test_tracer.cc
  test/cpp/inference/api/analyzer_capi_pd_tensor_tester.cc
  test/cpp/inference/api/analyzer_detect_functional_mkldnn_tester.cc
  test/cpp/inference/api/analyzer_int8_object_detection_tester.cc
  test/cpp/inference/api/analyzer_lexical_analysis_gru_tester.cc
  test/cpp/inference/api/analyzer_pyramid_dnn_tester.cc
  test/cpp/inference/api/analyzer_seq_pool1_tester_helper.h
  test/cpp/inference/api/ipu_multi_model_profile.cc
  test/cpp/inference/api/mkldnn_quantizer_config_tester.cc
  test/cpp/inference/api/paddle_infer_api_copy_tensor_tester.cc
  test/cpp/inference/api/paddle_infer_api_errors_tester.cc
  test/cpp/inference/api/tester_helper.h
  test/cpp/inference/test_helper.h
  test/cpp/jit/layer_test.cc
  test/cpp/new_executor/standalone_executor_pir_test.cc
  test/cpp/pir/core/ir_program_test.cc
  test/cpp/pir/pass/pass_manager_test.cc
  test/cpp/pir/pattern_rewrite/pattern_rewrite_test.cc
  test/cpp/pir/tools/test_op.cc
  test/cpp/prim/test_eager_prim.cc
  test/deprecated/cpp/inference/analysis/analyzer_tester.cc
  test/deprecated/cpp/inference/api/analyzer_bert_tester.cc
  test/deprecated/cpp/inference/api/analyzer_dam_tester.cc
  test/deprecated/cpp/inference/api/analyzer_lac_tester.cc
  test/deprecated/cpp/inference/api/analyzer_mmp_tester.cc
  test/deprecated/cpp/inference/api/analyzer_ner_tester.cc
  test/deprecated/cpp/inference/api/analyzer_rnn2_tester.cc
  test/deprecated/cpp/inference/api/analyzer_seq_conv1_tester.cc
  test/deprecated/cpp/inference/api/analyzer_text_classification_tester.cc
  test/deprecated/cpp/inference/api/analyzer_vis_tester.cc
  test/deprecated/cpp/inference/api/api_impl_tester.cc
  test/deprecated/custom_op/custom_raw_op_kernel_op.cc
  test/deprecated/custom_op/custom_raw_op_kernel_op.h
  test/xpu/cpp/beam_search_decode_op_xpu_test.cc
Labels: contributor, HappyOpenSource

#65954 Replace paddle::platform::Place [fluid_ops] - part4
  paddle/fluid/framework/new_executor/garbage_collector/garbage_collector.cc
  paddle/fluid/framework/new_executor/garbage_collector/garbage_collector.h
  paddle/fluid/framework/new_executor/instruction/builtin_combine_instruction.cc
  paddle/fluid/framework/new_executor/instruction/builtin_combine_instruction.h
  paddle/fluid/framework/new_executor/instruction/cinn_jit_instruction.cc
  paddle/fluid/framework/new_executor/instruction/cinn_jit_instruction.h
  paddle/fluid/framework/new_executor/instruction/control_flow/assert_instruction.cc
  paddle/fluid/framework/new_executor/instruction/control_flow/assert_instruction.h
  paddle/fluid/framework/new_executor/instruction/control_flow/has_elements_instruction.cc
  paddle/fluid/framework/new_executor/instruction/control_flow/has_elements_instruction.h
  paddle/fluid/framework/new_executor/instruction/control_flow/if_instruction.cc
  paddle/fluid/framework/new_executor/instruction/control_flow/if_instruction.h
  paddle/fluid/framework/new_executor/instruction/control_flow/pylayer_instruction.cc
  paddle/fluid/framework/new_executor/instruction/control_flow/pylayer_instruction.h
  paddle/fluid/framework/new_executor/instruction/control_flow/select_input_instruction.h
  paddle/fluid/framework/new_executor/instruction/control_flow/select_output_instruction.h
  paddle/fluid/framework/new_executor/instruction/control_flow/tuple_pop_instruction.cc
  paddle/fluid/framework/new_executor/instruction/control_flow/tuple_pop_instruction.h
  paddle/fluid/framework/new_executor/instruction/control_flow/tuple_push_instruction.cc
  paddle/fluid/framework/new_executor/instruction/control_flow/tuple_push_instruction.h
  paddle/fluid/framework/new_executor/instruction/control_flow/while_instruction.cc
  paddle/fluid/framework/new_executor/instruction/control_flow/while_instruction.h
  paddle/fluid/framework/new_executor/instruction/control_flow/yield_instruction.h
  paddle/fluid/framework/new_executor/instruction/custom_kernel_instruction.cc
  paddle/fluid/framework/new_executor/instruction/custom_kernel_instruction.h
  paddle/fluid/framework/new_executor/instruction/instruction_base.cc
  paddle/fluid/framework/new_executor/instruction/instruction_base.h
  paddle/fluid/framework/new_executor/instruction/instruction_util.cc
  paddle/fluid/framework/new_executor/instruction/instruction_util.h
  paddle/fluid/framework/new_executor/instruction/legacy_kernel_instruction.cc
  paddle/fluid/framework/new_executor/instruction/legacy_kernel_instruction.h
  paddle/fluid/framework/new_executor/instruction/onednn/onednn_instruction.cc
  paddle/fluid/framework/new_executor/instruction/onednn/onednn_instruction.h
  paddle/fluid/framework/new_executor/instruction/onednn/onednn_legacy_instruction.cc
  paddle/fluid/framework/new_executor/instruction/onednn/onednn_legacy_instruction.h
  paddle/fluid/framework/new_executor/instruction/onednn/onednn_mixed_instruction.cc
  paddle/fluid/framework/new_executor/instruction/onednn/onednn_mixed_instruction.h
  paddle/fluid/framework/new_executor/instruction/phi_kernel_instruction.cc
  paddle/fluid/framework/new_executor/instruction/phi_kernel_instruction.h
  paddle/fluid/framework/new_executor/interpreter/data_transfer.cc
  paddle/fluid/framework/new_executor/interpreter/data_transfer.h
  paddle/fluid/framework/new_executor/interpreter/interpreter_util.cc
  paddle/fluid/framework/new_executor/interpreter/interpreter_util.h
  paddle/fluid/framework/new_executor/interpreter/static_build.cc
  paddle/fluid/framework/new_executor/interpreter/static_build.h
  paddle/fluid/framework/new_executor/interpreter/stream_analyzer.h
  paddle/fluid/framework/new_executor/interpreter_base_impl.h
  paddle/fluid/framework/new_executor/interpretercore.cc
  paddle/fluid/framework/new_executor/interpretercore.h
  paddle/fluid/framework/new_executor/pir_interpreter.cc
  paddle/fluid/framework/new_executor/pir_interpreter.h
  paddle/fluid/framework/new_executor/profiler.h
  paddle/fluid/framework/new_executor/program_interpreter.cc
  paddle/fluid/framework/new_executor/program_interpreter.h
  paddle/fluid/framework/new_executor/standalone_executor.cc
  paddle/fluid/framework/new_executor/standalone_executor.h
Labels: contributor, HappyOpenSource

#65959 [fluid_ops]Replace platform::is_gpu_place in test/ - part2
  test/cpp/fluid/assign_op_test.cc
  test/cpp/fluid/beam_search_decode_op_test.cc
  test/cpp/fluid/benchmark/op_tester.cc
  test/cpp/fluid/benchmark/op_tester_config.h
  test/cpp/fluid/controlflow/conditional_block_op_test.cc
  test/cpp/fluid/elementwise/test_elementwise_add_grad_grad.cc
  test/cpp/fluid/elementwise/test_elementwise_add_op_inplace.cc
  test/cpp/fluid/elementwise/test_elementwise_div_grad_grad.cc
  test/cpp/fluid/elementwise/test_elementwise_op_grad_grad.h
  test/cpp/fluid/framework/copy_same_tensor_test.cc
  test/cpp/fluid/framework/data_device_transform_test.cu
  test/cpp/fluid/framework/data_feed_test.cc
  test/cpp/fluid/framework/details/broadcast_op_handle_test.h
  test/cpp/fluid/framework/details/fused_broadcast_op_handle_test.cc
  test/cpp/fluid/framework/details/reduce_op_handle_test.cc
  test/cpp/fluid/framework/dlpack_tensor_test.cc
  test/cpp/fluid/framework/op_call_stack_test.cc
  test/cpp/fluid/framework/op_registry_test.cc
  test/cpp/fluid/framework/operator_test.cc
  test/cpp/fluid/framework/phi_utils_test.cc
  test/cpp/fluid/framework/reader_test.cc
  test/cpp/fluid/framework/tensor_util_test.cc
  test/cpp/fluid/framework/tensor_util_test.cu
  test/cpp/fluid/fused/cudnn_bn_add_relu_test.cc
  test/cpp/fluid/fused/cudnn_norm_conv_test.cc
  test/cpp/fluid/fused/fused_dropout_act_bias_test.cu
  test/cpp/fluid/fused/fused_dropout_test.h
  test/cpp/fluid/fused/fused_layernorm_residual_dropout_bias_test.cu
  test/cpp/fluid/fused/fused_residual_dropout_bias_test.cu
  test/cpp/fluid/fused/fusion_group_op_test.cc
  test/cpp/fluid/math/beam_search_test.cc
  test/cpp/fluid/math/concat_test.cc
  test/cpp/fluid/math/im2col_test.cc
  test/cpp/fluid/math/vol2col_test.cc
  test/cpp/fluid/memory/buffered_allocator_test.cc
  test/cpp/fluid/memory/cuda_malloc_async_allocator_test.cu
  test/cpp/fluid/memory/retry_allocator_test.cc
  test/cpp/fluid/memory/stream_safe_cuda_alloc_test.cu
  test/cpp/fluid/mkldnn/test_conv_onednn_nhwc.cc
  test/cpp/fluid/mkldnn/test_onednn_caching.cc
  test/cpp/fluid/mkldnn/test_onednn_conv2d_transpose_bias.cc
  test/cpp/fluid/mkldnn/test_onednn_op_inplace.cc
  test/cpp/fluid/mkldnn/test_onednn_op_nhwc.cc
  test/cpp/fluid/mkldnn/test_onednn_pool_adaptive_op.cc
  test/cpp/fluid/mkldnn/test_onednn_squeeze.cc
  test/cpp/fluid/nccl/nccl_op_test.cu.cc
  test/cpp/fluid/op_debug_string_test.cc
  test/cpp/fluid/platform/device/custom/custom_device_test.cc
  test/cpp/fluid/pscore/heter_cloud_comm_cpu_test.cc
  test/cpp/fluid/pscore/heter_listen_and_server_test.cc
  test/cpp/fluid/pscore/heter_server_test.cc
  test/cpp/fluid/pscore/send_and_recv_op_cpu_test.cc
  test/cpp/fluid/pscore/send_and_recv_op_gpu_test.cc
  test/cpp/fluid/reduce_ops/check_reduce_rank_test.cu
  test/cpp/fluid/share_buffer_op_test.cc
  test/cpp/fluid/test_leaky_relu_grad_grad_functor.h
Labels: contributor, HappyOpenSource

#65907 Replace paddle::platform::Place [fluid_ops] - part1
  paddle/cinn/ir/group_schedule/search/measurer.h
  paddle/fluid/framework/compiled_program.cc
  paddle/fluid/framework/compiled_program.h
  paddle/fluid/framework/custom_operator.cc
  paddle/fluid/framework/data_device_transform.h
  paddle/fluid/framework/device_worker.h
  paddle/fluid/framework/downpour_lite_worker.cc
  paddle/fluid/framework/downpour_worker.cc
  paddle/fluid/framework/executor.cc
  paddle/fluid/framework/executor.h
  paddle/fluid/framework/executor_cache.h
  paddle/fluid/framework/heter_pipeline_trainer.cc
  paddle/fluid/framework/heter_section_worker.cc
  paddle/fluid/framework/heterxpu_trainer.cc
  paddle/fluid/framework/ir/memory_optimize_pass/eager_deletion_pass.cc
  paddle/fluid/framework/ir/memory_optimize_pass/reference_count_pass_helper.h
  paddle/fluid/framework/ir/multi_devices_graph_pass/multi_devices_graph_pass.cc
  paddle/fluid/framework/ir/multi_devices_graph_pass/multi_devices_graph_pass.h
  paddle/fluid/framework/lod_tensor.cc
  paddle/fluid/framework/lod_tensor.h
  paddle/fluid/framework/multi_trainer.cc
  paddle/fluid/framework/naive_executor.h
  paddle/fluid/framework/operator.cc
  paddle/fluid/framework/operator.h
  paddle/fluid/framework/phi_utils.cc
  paddle/fluid/framework/pipeline_trainer.cc
  paddle/fluid/framework/ps_gpu_trainer.cc
  paddle/fluid/framework/ps_gpu_worker.cc
  paddle/fluid/framework/tensor_util.cc
  paddle/fluid/framework/tensor_util.h
  paddle/fluid/framework/trainer.h
  paddle/fluid/framework/var_type_traits.h
  paddle/fluid/framework/variable_helper.cc
  paddle/fluid/inference/tensorrt/convert/ut_helper.h
  paddle/fluid/pir/dialect/operator/transforms/param_to_variable.cc
  paddle/fluid/pir/transforms/general/params_sync_among_devices_pass.cc
  paddle/fluid/pir/transforms/pd_op_to_kernel_pass.cc
  paddle/phi/kernels/gpu/batch_norm_kernel.cu
Labels: contributor, HappyOpenSource

#65935 Sync batch norm adapt new comm
  paddle/fluid/operators/sync_batch_norm_op.cu
  paddle/fluid/operators/sync_batch_norm_utils.h
  tools/test_runner.py
Labels: contributor

#65950 Replace paddle::platform::Place [fluid_ops] - part3
  paddle/fluid/distributed/collective/process_group_bkcl.cc
  paddle/fluid/distributed/collective/reducer.h
  paddle/fluid/distributed/fleet_executor/carrier.cc
  paddle/fluid/distributed/fleet_executor/carrier.h
  paddle/fluid/distributed/fleet_executor/cond_interceptor.cc
  paddle/fluid/distributed/fleet_executor/dist_model.cc
  paddle/fluid/distributed/fleet_executor/dist_model.h
  paddle/fluid/distributed/fleet_executor/fleet_executor.cc
  paddle/fluid/distributed/fleet_executor/fleet_executor.h
  paddle/fluid/distributed/fleet_executor/interceptor.h
  paddle/fluid/distributed/fleet_executor/test/compute_interceptor_run_op_test.cc
  paddle/fluid/distributed/ps/service/brpc_ps_client.cc
  paddle/fluid/distributed/ps/service/brpc_utils.cc
  paddle/fluid/distributed/ps/service/communicator/communicator.cc
  paddle/fluid/distributed/ps/service/communicator/communicator.h
  paddle/fluid/distributed/ps/service/heter_client.cc
  paddle/fluid/distributed/ps/service/heter_server.cc
  paddle/fluid/distributed/ps/service/heter_server.h
  paddle/fluid/distributed/ps/service/server.h
  paddle/fluid/distributed/ps/table/tensor_table.h
  paddle/fluid/distributed/ps/wrapper/fleet.cc
  paddle/fluid/distributed/test/brpc_service_dense_sgd_test.cc
  paddle/fluid/distributed/test/brpc_service_sparse_sgd_test.cc
  paddle/fluid/distributed/test/brpc_utils_test.cc
  paddle/fluid/eager/api/generated/eager_generated/backwards/scale_node.cc
  paddle/fluid/eager/api/utils/global_utils.cc
  paddle/fluid/eager/api/utils/global_utils.h
  paddle/fluid/eager/pylayer/py_layer_node.h
  paddle/fluid/framework/details/all_reduce_op_handle.cc
  paddle/fluid/framework/details/all_reduce_op_handle.h
  paddle/fluid/framework/details/bkcl_op_handle.h
  paddle/fluid/framework/details/broadcast_op_handle.h
  paddle/fluid/framework/details/build_strategy.cc
  paddle/fluid/framework/details/build_strategy.h
  paddle/fluid/framework/details/fused_all_reduce_op_handle.cc
  paddle/fluid/framework/details/fused_all_reduce_op_handle.h
  paddle/fluid/framework/details/fused_broadcast_op_handle.h
  paddle/fluid/framework/details/graph_test_base.h
  paddle/fluid/framework/details/nan_inf_utils.h
  paddle/fluid/framework/details/nan_inf_utils_detail.cc
  paddle/fluid/framework/details/nan_inf_utils_detail.h
  paddle/fluid/framework/details/nccl_op_handle.h
  paddle/fluid/framework/details/op_handle_base.h
  paddle/fluid/framework/details/reduce_and_gather.h
  paddle/fluid/framework/details/reduce_op_handle.cc
  paddle/fluid/framework/details/reduce_op_handle.h
  paddle/fluid/framework/details/sparse_all_reduce_op_handle.cc
  paddle/fluid/framework/details/sparse_all_reduce_op_handle.h
  paddle/fluid/framework/details/var_handle.h
  paddle/fluid/operators/collective/c_comm_init_all_op.h
  paddle/fluid/operators/memcpy_d2h_op.h
  paddle/fluid/operators/memcpy_op.h
  paddle/fluid/operators/reader/buffered_reader.cc
Labels: contributor, HappyOpenSource

#65802 Replace platform::XPUDeviceGuard phi::backends::xpu::XPUDeviceGuard
  paddle/fluid/distributed/collective/bkcl_tools.h
  paddle/fluid/distributed/collective/process_group_bkcl.cc
  paddle/fluid/framework/fleet/heter_ps/heter_comm_inl.h
  paddle/fluid/framework/fleet/heter_ps/heter_resource.cc
  paddle/fluid/framework/fleet/heter_ps/heter_resource.h
  paddle/fluid/framework/heterxpu_trainer.cc
  paddle/fluid/memory/allocation/naive_best_fit_allocator.cc
  paddle/fluid/operators/reader/buffered_reader.cc
  paddle/fluid/platform/device/xpu/xpu_resource_pool.cc
  paddle/fluid/pybind/tensor_py.h
Labels: contributor, HappyOpenSource

#65843 [Typing][B-20] Add type annotations for `python/paddle/distribution/lognormal.py`
  python/paddle/distribution/lognormal.py
Labels: contributor, HappyOpenSource

#65727 [Typing][B-02,B-04] Add type annotations for `python/paddle/distribution/{bernoulli, binomial}.py`
  python/paddle/distribution/bernoulli.py
  python/paddle/distribution/beta.py
  python/paddle/distribution/binomial.py
  python/paddle/distribution/transformed_distribution.py
Labels: contributor, HappyOpenSource

#65895 [Typing] 修复示例中使用 `Dataset` 的 `type-arg` 类型检查错误
  python/paddle/distributed/auto_parallel/api.py
  python/paddle/incubate/optimizer/lookahead.py
  python/paddle/incubate/optimizer/modelaverage.py
  python/paddle/io/dataloader/batch_sampler.py
  python/paddle/io/dataloader/sampler.py
  python/paddle/jit/api.py
  python/paddle/jit/pir_translated_layer.py
  python/paddle/jit/translated_layer.py
  python/paddle/metric/metrics.py
Labels: PaddlePaddle Hackathon, contributor

#65587 [Typing][B-01] Add type annotations for `python/paddle/io/reader.py`
  python/paddle/io/reader.py
Labels: contributor, HappyOpenSource

#65785 [Typing][B-19] Add type annotations for `python/paddle/distribution/lkj_cholesky.py`
  python/paddle/distribution/beta.py
  python/paddle/distribution/lkj_cholesky.py
Labels: contributor, HappyOpenSource

#65784 [Typing][B-18] Add type annotations for `python/paddle/distribution/laplace.py`
  python/paddle/distribution/laplace.py
Labels: contributor, HappyOpenSource

#65811 [Typing][B-88] Add type annotations for `python/paddle/nn/utils/transform_parameters.py`
  python/paddle/nn/utils/transform_parameters.py
Labels: PaddlePaddle Hackathon, contributor

#65919 [Typing][B-59] Add type annotations for `python/paddle/text/viterbi_decode.py`
  python/paddle/text/viterbi_decode.py
Labels: contributor, HappyOpenSource

#65838 [Typing][B-05] Add type annotations for `python/paddle/distribution/categorical.py`
  python/paddle/distribution/categorical.py
Labels: contributor, HappyOpenSource

#65852 [Typing][B-24] Add type annotations for `python/paddle/distribution/poisson.py`
  python/paddle/distribution/poisson.py
Labels: contributor, HappyOpenSource

#65847 [Typing][B-22] Add type annotations for `python/paddle/distribution/multivariate_normal.py`
  python/paddle/distribution/multivariate_normal.py
Labels: contributor, HappyOpenSource

#66014 [Typing][C-62] Add type annotations for `python/paddle/incubate/autograd/utils.py`
  python/paddle/incubate/autograd/utils.py
Labels: contributor

#65805 [Typing][B-83] Add type annotations for `python/paddle/nn/quant/quantized_linear.py`
  python/paddle/nn/quant/quantized_linear.py
Labels: PaddlePaddle Hackathon, contributor

#66009 [Typing][C-55] Add type annotations for `python/paddle/incubate/autotune.py`
  python/paddle/incubate/autotune.py
Labels: contributor

#66012 [Typing][C-58] Add type annotations for `python/paddle/incubate/asp/utils.py`
  python/paddle/incubate/asp/utils.py
Labels: contributor

#65633 [Typing][B-33,B-37] Add type annotations for `python/paddle/amp/{amp_lists,__init__}.py`
  python/paddle/amp/__init__.py
  python/paddle/amp/amp_lists.py
Labels: contributor, HappyOpenSource

#66011 [Typing][C-57] Add type annotations for `python/paddle/incubate/asp/supported_layer_list.py`
  python/paddle/incubate/asp/supported_layer_list.py
Labels: contributor
