Repository PaddlePaddle/Paddle, pull requests merged in 2024-11, with the labels that each got.

#68950 remove use_calc_stream param [fluid_ops] partial_send
  paddle/fluid/operators/collective/partial_send_op.cc
  paddle/fluid/operators/ops_signature/partial_send_sig.cc
  paddle/phi/infermeta/unary.cc
  paddle/phi/infermeta/unary.h
  paddle/phi/kernels/cpu/partial_send_kernel.cc
  paddle/phi/kernels/gpu/partial_send_kernel.cu
  paddle/phi/ops/yaml/inconsistent/static_ops.yaml
  paddle/phi/ops/yaml/op_version.yaml
Labels: PaddlePaddle Hackathon, contributor

#69042 [XPU] refine adamw ut
  paddle/scripts/paddle_build.sh
  test/legacy_test/test_adamw_op.py
  tools/get_quick_disable_lt.py
Labels: XPU

#68781 set sharding degree and sharding mesh axis in auto parallel fix shard_optimizer bug
  python/paddle/distributed/auto_parallel/api.py
Labels: contributor

#69126 [SOT][3.13] `eval_frame` support python 3.13
  paddle/fluid/pybind/sot/cpython_internals.c
  paddle/fluid/pybind/sot/cpython_internals.h
  paddle/fluid/pybind/sot/eval_frame.c
  paddle/fluid/pybind/sot/eval_frame_tools.cc
  paddle/fluid/pybind/sot/eval_frame_tools.h
  paddle/fluid/pybind/sot/macros.h
  test/dygraph_to_static/test_eval_frame.py
Labels: contributor

#68964 [Infer Symbolic Shape No.151] Add symbol_infer_interface for instance_norm
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/multiary_infer_sym.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/multiary_infer_sym.h
  paddle/phi/ops/yaml/ops.yaml
Labels: contributor

#68929 [Infer Symbolic Shape No.152] Add symbol_infer_interface for llm_int8_linear
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/multiary_infer_sym.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/multiary_infer_sym.h
  paddle/phi/ops/yaml/ops.yaml
Labels: contributor

#68907 【Infer Symbolic Shape No.153】add symbol_infer_interface for lstm
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/multiary_infer_sym.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/multiary_infer_sym.h
  paddle/phi/ops/yaml/ops.yaml
Labels: contributor

#68967 【Infer Symbolic Shape No.217】Add infer_symbol_shape for rank_attention
  paddle/fluid/pir/dialect/op_generator/ops_api_gen.py
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/multiary_infer_sym.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/multiary_infer_sym.h
  paddle/phi/ops/yaml/ops.yaml
  test/legacy_test/test_rank_attention_op.py
Labels: contributor

#69148 Fix Numberic Numeric
  python/paddle/_typing/__init__.py
  python/paddle/_typing/basic.py
  python/paddle/distributed/auto_parallel/api.py
  python/paddle/distributed/auto_parallel/process_mesh.py
  python/paddle/distributed/fleet/base/util_factory.py
  python/paddle/distribution/distribution.py
  python/paddle/nn/functional/pooling.py
  python/paddle/nn/layer/activation.py
  python/paddle/sparse/binary.py
  python/paddle/sparse/creation.py
  python/paddle/tensor/creation.py
  python/paddle/tensor/manipulation.py
Labels: contributor, HappyOpenSource

#69145 Fix opitimize optimize
  paddle/fluid/pybind/compiled_program.cc
  paddle/fluid/pybind/eager.cc
  paddle/fluid/pybind/eager_generator.cc
  paddle/fluid/pybind/eager_method.cc
  paddle/fluid/pybind/pybind.cc
  paddle/fluid/pybind/tensor.cc
  python/paddle/tensor/linalg.py
Labels: contributor, HappyOpenSource

#68768 [Docathon][Add API Legend No.42] Add legend for as_complex API
  python/paddle/tensor/manipulation.py
Labels: contributor, HappyOpenSource

#68917 [Infer Symbolic Shape No.154] Add symbol_infer_interface for lstsq
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/binary_infer_sym.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/binary_infer_sym.h
  paddle/phi/ops/yaml/ops.yaml
Labels: contributor

#69133 【Infer Symbolic Shape No.77&No.197】Add infer_symbol_shape for DepthwiseConv2dTranspose and LogSoftmax
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/binary_infer_sym.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/binary_infer_sym.h
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/same_operands_result.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/same_operands_result.h
  paddle/phi/ops/yaml/ops.yaml
Labels: contributor

#68996 Fix `paddle.distribution.constraint` 易用性提升
  python/paddle/distribution/constraint.py
  python/paddle/distribution/variable.py
  test/distribution/test_distribution_constraint.py
Labels: contributor

#68984 [Infer Symbolic Shape No.199] Add symbol_infer_interface for flash_attn_qkvpacked
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/multiary_infer_sym.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/multiary_infer_sym.h
  paddle/phi/ops/yaml/ops.yaml
Labels: contributor

#69168 Fix compuatation computation [fluid_ops]
  test/cpp/eager/task_tests/eager_utils_test.cc
  test/deprecated/auto_parallel/test_dist_embedding_deprecated.py
  test/deprecated/cpp/inference/api/analysis_predictor_tester.cc
  test/deprecated/legacy_test/auto_parallel_data_unshard_deprecated.py
  test/deprecated/legacy_test/test_desc_clone_deprecated.py
  test/deprecated/legacy_test/test_save_load_deprecated.py
  test/legacy_test/test_sigmoid_cross_entropy_with_logits_grad_with_auto_grad.py
  test/prim/model/bert.py
  test/prim/pir_prim/test_prim_jit.py
  test/xpu/test_collective_allgather_xpu.py
Labels: contributor, HappyOpenSource

#68550 [CINN] Add RepeatInterleaveWithTensorIndex && Solve
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/binary_infer_sym.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/binary_infer_sym.h
  paddle/phi/ops/yaml/ops.yaml
  paddle/pir/include/dialect/shape/utils/shape_analysis.h
  paddle/pir/src/dialect/shape/utils/shape_analysis.cc
  test/legacy_test/test_repeat_interleave_op.py
Labels: contributor

#69056 [XPU] support argmax bf16 & update xhpc date
  cmake/external/xpu.cmake
  paddle/phi/backends/xpu/xpu3_op_list.cc
  paddle/phi/kernels/xpu/arg_min_max_kernel.cc
  test/xpu/test_arg_max_op_xpu.py
Labels: XPU

#68644 [CINN] Add InferSymbolicShapeInterface for (`frame, prune_gate_by_capacity`) op
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/binary_infer_sym.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/binary_infer_sym.h
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/unary_infer_sym.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/unary_infer_sym.h
  paddle/phi/ops/yaml/ops.yaml
  test/legacy_test/test_frame_op.py
  test/legacy_test/test_prune_gate_by_capacity_op.py
Labels: contributor

#68841 [CINN] Disable some op symbol_infer check in `same_operand_with_result.cc`
  test/legacy_test/test_activation_op.py
  test/legacy_test/test_angle_op.py
  test/legacy_test/test_bitwise_op.py
  test/legacy_test/test_clip_op.py
  test/legacy_test/test_conj_op.py
  test/legacy_test/test_digamma_op.py
  test/legacy_test/test_erf_op.py
  test/legacy_test/test_erfinv_op.py
  test/legacy_test/test_flip.py
  test/legacy_test/test_i0_op.py
  test/legacy_test/test_i0e_op.py
  test/legacy_test/test_i1_op.py
  test/legacy_test/test_i1e_op.py
  test/legacy_test/test_label_smooth_op.py
  test/legacy_test/test_lgamma_op.py
  test/legacy_test/test_logit_op.py
  test/legacy_test/test_pow_op.py
  test/legacy_test/test_prelu_op.py
  test/legacy_test/test_put_along_axis_op.py
  test/legacy_test/test_real_imag_op.py
  test/legacy_test/test_roll_op.py
  test/legacy_test/test_scatter_nd_op.py
  test/legacy_test/test_scatter_op.py
Labels: contributor

#68681 【Hackathon 7th No.20】为 Paddle 新增 Tensor.set_ -part
  paddle/phi/infermeta/unary.cc
  paddle/phi/infermeta/unary.h
  paddle/phi/kernels/set_kernel.cc
  paddle/phi/kernels/set_kernel.h
  paddle/phi/ops/yaml/ops.yaml
  python/paddle/tensor/__init__.py
  python/paddle/tensor/creation.py
  test/legacy_test/test_inplace.py
Labels: PaddlePaddle Hackathon, contributor, API

#69090 Fix distribution API with 0-D input parameters 易用性提升 -part1
  python/paddle/distribution/bernoulli.py
  python/paddle/distribution/binomial.py
  python/paddle/distribution/categorical.py
  python/paddle/distribution/cauchy.py
  python/paddle/distribution/continuous_bernoulli.py
  test/distribution/test_distribution_binomial.py
  test/distribution/test_distribution_binomial_static.py
  test/distribution/test_distribution_continuous_bernoulli.py
  test/distribution/test_distribution_continuous_bernoulli_static.py
Labels: contributor

#68748 【Paddle Toolkit Development Competition No.2】[Custom OP] Add contiguous api support to paddle::Tensor -part
  paddle/phi/api/include/tensor.h
  paddle/phi/api/lib/tensor.cc
  test/custom_op/CMakeLists.txt
  test/custom_op/custom_contiguous.cc
  test/custom_op/test_custom_contiguous.py
Labels: contributor, HappyOpenSource Pro

#69196 [SOT][3.13]add `LOAD_FAST_LOAD_FAST`、 `STORE_FAST_STORE_FAST`、 `STORE_FAST_LOAD_FAST` and add skip tests files
  python/paddle/jit/sot/opcode_translator/instruction_utils/instruction_utils.py
  test/sot/skip_files_py313
Labels: contributor

#69229 [XPU] fix c_concat op
  paddle/fluid/distributed/collective/process_group_bkcl.cc
  paddle/fluid/distributed/collective/process_group_bkcl.h
  paddle/fluid/imperative/CMakeLists.txt
  paddle/fluid/imperative/prepared_operator.cc
Labels: XPU

#69167 [CINN] Refine sym infer for FloorDivide
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/element_wise_binary.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/element_wise_binary.h
  paddle/phi/ops/yaml/inconsistent/static_ops.yaml
  paddle/phi/ops/yaml/legacy/static_ops.yaml
  test/legacy_test/test_elementwise_floordiv_op.py
Labels: contributor

#69197 【Paddle Tensor No.21】：新增 bitwise_invert，复用已有接口 Tenosr.__invert__
  python/paddle/__init__.py
  python/paddle/jit/sot/utils/magic_methods.py
  python/paddle/tensor/__init__.py
  python/paddle/tensor/logic.py
  test/legacy_test/test_bitwise_op.py
  test/legacy_test/test_inplace.py
  test/legacy_test/test_math_op_patch_pir.py
Labels: contributor, HappyOpenSource

#69159 [CINN][New Hardware]Fix dcu compile
  paddle/cinn/backends/codegen_device_util.cc
  paddle/cinn/common/dev_info_manager.h
  paddle/cinn/common/target.cc
  paddle/cinn/hlir/framework/pir/op_lowering_impl.cc
  paddle/fluid/framework/new_executor/instruction/cinn_jit_instruction.cc
Labels: contributor

#68882 【Infer Symbolic Shape No.220】Add infer_symbol_shape for rnn
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/multiary_infer_sym.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/multiary_infer_sym.h
  paddle/phi/ops/yaml/ops.yaml
  test/legacy_test/test_rnn_op.py
Labels: contributor

#69268 [Lod] [fluid_ops] LoDTensorArray
  paddle/fluid/pybind/pybind.cc
  python/paddle/base/__init__.py
  python/paddle/base/executor.py
  python/paddle/base/layers/math_op_patch.py
  python/paddle/base/reader.py
  python/paddle/io/dataloader/dataloader_iter.py
  python/paddle/jit/dy2static/convert_operators.py
  python/paddle/jit/dy2static/partial_program.py
  python/paddle/static/nn/control_flow.py
  python/paddle/tensor/manipulation.py
  test/cpp/fluid/assign_op_test.cc
  test/cpp/fluid/beam_search_decode_op_test.cc
  test/cpp/fluid/controlflow/conditional_block_op_test.cc
  test/deprecated/legacy_test/test_tensor_array_to_tensor_deprecated.py
  test/dygraph_to_static/test_list.py
  test/legacy_test/op_test.py
  test/legacy_test/test_concat_op.py
  test/legacy_test/test_fetch_lod_tensor_array.py
  test/legacy_test/test_lod_tensor_array.py
  test/legacy_test/test_slice_op.py
  test/legacy_test/test_stack_op.py
  test/legacy_test/test_tensor_array_to_tensor.py
  test/legacy_test/test_while_loop_op.py
  test/xpu/cpp/beam_search_decode_op_xpu_test.cc
Labels: PaddlePaddle Hackathon, contributor

#69271 [Lod] [fluid_ops] paddle LodTensor
  paddle/fluid/distributed/collective/reducer.cc
  paddle/fluid/distributed/ps/service/brpc_utils.cc
  paddle/fluid/distributed/ps/service/brpc_utils.h
  paddle/fluid/distributed/ps/service/heter_client.cc
  paddle/fluid/distributed/ps/service/heter_server.cc
  paddle/fluid/distributed/ps/service/ps_client.h
  paddle/fluid/distributed/ps/service/ps_local_client.h
  paddle/fluid/distributed/ps/wrapper/fleet.h
  paddle/fluid/framework/device_worker.cc
  paddle/fluid/framework/device_worker.h
  paddle/fluid/framework/downpour_lite_worker.cc
  paddle/fluid/framework/downpour_worker.cc
  paddle/fluid/framework/hetercpu_worker.cc
  paddle/fluid/framework/operator.cc
  paddle/fluid/imperative/reducer.cc
  paddle/fluid/inference/tensorrt/convert/io_converter.cc
  paddle/fluid/ir_adaptor/translator/op_translator.cc
  paddle/fluid/operators/beam_search_decode_op_def.h
  paddle/fluid/operators/collective/recv_v2_op.cu.cc
  paddle/fluid/operators/collective/send_v2_op.cu.cc
  paddle/fluid/operators/fused/multi_gru_op.cc
  paddle/fluid/operators/load_combine_op.cc
  paddle/fluid/operators/sum_op.cc
  paddle/fluid/operators/tensor_array_to_tensor_op.cc
  paddle/fluid/pybind/eager.cc
  paddle/phi/core/tensor_array.h
  paddle/phi/kernels/cpu/detection_map_kernel.cc
  paddle/phi/kernels/funcs/beam_search_decode.h
  paddle/phi/kernels/funcs/sequence2batch.h
  paddle/phi/kernels/gpu/p_recv_kernel.cu
  paddle/phi/kernels/gpu/p_send_kernel.cu
  test/cpp/fluid/framework/device_worker_test.cc
  test/cpp/fluid/framework/operator_test.cc
  test/cpp/fluid/platform/lodtensor_printer_test.cc
Labels: PaddlePaddle Hackathon, contributor

#69215 [SCU][Docathon][Add API Legend No.52] Add legend for masked_fill API
  python/paddle/tensor/manipulation.py
Labels: contributor, HappyOpenSource Pro

#69231 【SCU】【Paddle Tensor No.3】新增 Tensor.__rmod__，复用已有接口 Tensor.__mod__
  paddle/fluid/pybind/eager_math_op_patch.cc
  python/paddle/base/dygraph/math_op_patch.py
  python/paddle/base/layers/math_op_patch.py
  python/paddle/pir/math_op_patch.py
  python/paddle/tensor/tensor.prototype.pyi
  test/legacy_test/test_math_op_patch.py
  test/legacy_test/test_math_op_patch_pir.py
Labels: contributor, HappyOpenSource Pro

#69222 【Paddle Tensor No.2】新增 Tensor.__rfloordiv__ 复用已有接口 Tensor.__floordiv__
  paddle/fluid/pybind/eager_math_op_patch.cc
  python/paddle/base/dygraph/math_op_patch.py
  python/paddle/base/layers/math_op_patch.py
  python/paddle/pir/math_op_patch.py
  python/paddle/tensor/tensor.prototype.pyi
  test/legacy_test/test_math_op_patch.py
  test/legacy_test/test_math_op_patch_pir.py
Labels: contributor, HappyOpenSource

#69270 【Paddle Tensor No.22】: 新增 paddle.less Tensor.less
  python/paddle/__init__.py
  python/paddle/tensor/__init__.py
  test/legacy_test/test_inplace.py
  test/legacy_test/test_layers.py
  test/legacy_test/test_math_op_patch_pir.py
  test/legacy_test/test_math_op_patch_var_base.py
Labels: contributor

#68975 [Infer Symbolic Shape No.157] Add symbol_infer_interface for matrix_rank_tol
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/binary_infer_sym.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/binary_infer_sym.h
  paddle/phi/ops/yaml/ops.yaml
Labels: contributor

#68922 Fix `paddle.distribution.LKJCholesky.sample()` when concentration is 1-D 易用性提升
  python/paddle/distribution/lkj_cholesky.py
  test/distribution/test_distribution_lkj_cholesky.py
  test/distribution/test_distribution_lkj_cholesky_static.py
Labels: contributor

#68947 [Infer Symbolic Shape No.126] Add symbol_infer_interface for assign_ops
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/multiary_infer_sym.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/multiary_infer_sym.h
  paddle/phi/ops/yaml/ops.yaml
  test/legacy_test/test_assign_pos_op.py
Labels: contributor

#68978 [Infer Symbolic Shape No.225] Add symbol_infer_interface for shuffle_batch
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/binary_infer_sym.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/binary_infer_sym.h
  paddle/phi/ops/yaml/ops.yaml
Labels: contributor

#68980 [Infer Symbolic Shape No.240] Add symbol_infer_interface for uniform_random_batch_size_like
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/unary_infer_sym.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/unary_infer_sym.h
  paddle/phi/ops/yaml/ops.yaml
Labels: contributor

#69256 【Paddle Tensor No.13】: 新增paddle.positive,新增Tensor.__pos__
  python/paddle/__init__.py
  python/paddle/tensor/__init__.py
  python/paddle/tensor/logic.py
  python/paddle/tensor/tensor.prototype.pyi
  test/legacy_test/test_math_op_patch_pir.py
  test/legacy_test/test_positive.py
Labels: contributor

#69306 Update paddle/fluid/pybind/eager.cc
  paddle/fluid/pybind/eager.cc
Labels: PaddlePaddle Hackathon, contributor

#69302 [Lod][fluid_ops] LOD_TENSOR_ARRAY
  paddle/fluid/distributed/auto_parallel/dist_attr.cc
  paddle/fluid/framework/executor_gc_helper.cc
  paddle/fluid/framework/framework.proto
  paddle/fluid/framework/infershape_utils.cc
  paddle/fluid/framework/ir/auto_mixed_precision_pass.cc
  paddle/fluid/framework/new_executor/interpreter/interpreter_util.cc
  paddle/fluid/framework/op_desc.cc
  paddle/fluid/framework/var_desc.cc
  paddle/fluid/framework/var_type.h
  paddle/fluid/framework/var_type_traits.h
  paddle/fluid/framework/variable_helper.cc
  paddle/fluid/imperative/var_helper.cc
  paddle/fluid/inference/utils/model_utils.cc
  paddle/fluid/ir_adaptor/translator/op_translator.cc
  paddle/fluid/ir_adaptor/translator/program_translator.cc
  paddle/fluid/ir_adaptor/translator/type_translator.cc
  paddle/fluid/operators/controlflow/tensor_array_read_write_op.cc
  paddle/fluid/operators/slice_op.cc
  paddle/fluid/operators/sum_op.cc
  paddle/fluid/operators/tensor_array_to_tensor_op.cc
  paddle/fluid/pybind/protobuf.cc
  paddle/phi/core/framework/framework.proto
  python/paddle/base/framework.py
  python/paddle/base/layers/math_op_patch.py
  python/paddle/base/variable_index.py
  python/paddle/distributed/auto_parallel/static/auto_align_tool.py
  python/paddle/distributed/auto_parallel/static/utils.py
  python/paddle/distributed/passes/auto_parallel_fp16.py
  python/paddle/distributed/passes/auto_parallel_pipeline.py
  python/paddle/distributed/passes/pass_utils.py
  python/paddle/jit/dy2static/convert_operators.py
  python/paddle/jit/translated_layer.py
  python/paddle/static/amp/bf16/amp_utils.py
  python/paddle/static/amp/fp16_utils.py
  python/paddle/static/nn/control_flow.py
  python/paddle/static/nn/static_pylayer.py
  python/paddle/tensor/array.py
  python/paddle/tensor/manipulation.py
  test/cpp/fluid/framework/var_type_traits_test.cc
  test/cpp/imperative/test_eager.cc
  test/cpp/imperative/test_layer.cc
  test/deprecated/ir/inference/program_config.py
  test/deprecated/legacy_test/test_tensor_array_to_tensor_deprecated.py
  test/ir/inference/program_config.py
  test/legacy_test/test_debugger.py
  test/legacy_test/test_slice_op.py
Labels: PaddlePaddle Hackathon, contributor

#69183 [AutoParallel][PIR] support using custom spec for dist.to_static()
  python/paddle/distributed/auto_parallel/api.py
  test/auto_parallel/pir/CMakeLists.txt
  test/auto_parallel/pir/custom_spec_pir.py
  test/auto_parallel/pir/test_custom_spec_pir.py
Labels: contributor

#69313 [SOT][Faster Guard] add some basic guard
  paddle/fluid/pybind/CMakeLists.txt
  paddle/fluid/pybind/jit.cc
  paddle/fluid/pybind/sot/guards.cc
  paddle/fluid/pybind/sot/guards.h
  test/sot/test_faster_guard.py
Labels: contributor

#69208 [Paddle Tensorrt] add tensorrt converter and marker
  paddle/fluid/pir/transforms/tensorrt/trt_op_marker_pass.cc
  python/paddle/tensorrt/impls/activation.py
  python/paddle/tensorrt/impls/creation.py
  python/paddle/tensorrt/impls/linalg.py
  python/paddle/tensorrt/impls/logic.py
  python/paddle/tensorrt/impls/math.py
  python/paddle/tensorrt/impls/ops.py
  test/tensorrt/CMakeLists.txt
  test/tensorrt/test_converter_activation.py
  test/tensorrt/test_converter_creation.py
  test/tensorrt/test_converter_linalg.py
  test/tensorrt/test_converter_logic.py
  test/tensorrt/test_converter_math.py
  test/tensorrt/test_converter_ops.py
Labels: contributor

#69257 【Paddle Tensor No.10】新增 `Tensor.__complex__`
  python/paddle/base/dygraph/math_op_patch.py
  python/paddle/base/layers/math_op_patch.py
  python/paddle/jit/dy2static/convert_operators.py
  python/paddle/jit/dy2static/transformers/cast_transformer.py
  python/paddle/jit/sot/opcode_translator/executor/variables/basic.py
  python/paddle/jit/sot/utils/magic_methods.py
  python/paddle/pir/math_op_patch.py
  python/paddle/tensor/tensor.prototype.pyi
  test/dygraph_to_static/test_cast.py
  test/legacy_test/test_math_op_patch.py
  test/legacy_test/test_math_op_patch_pir.py
  test/legacy_test/test_math_op_patch_var_base.py
Labels: contributor, HappyOpenSource

#68979 [Infer Symbolic Shape No.245,247] Add symbol_infer_interface for weight_{dequantize.quantize}
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/binary_infer_sym.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/binary_infer_sym.h
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/unary_infer_sym.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/unary_infer_sym.h
  paddle/phi/infermeta/unary.cc
  paddle/phi/ops/yaml/ops.yaml
Labels: contributor

#68817 [Prim][PIR] Add backward_decomp and support dynamic shape for argsort_grad
  paddle/fluid/primitive/codegen/decomp_vjp_gen.py
  paddle/fluid/primitive/decomp_rule/decomp_vjp/details.h
  python/paddle/autograd/backward_utils.py
  test/legacy_test/test_argsort_op.py
  test/prim/pir_prim/test_prim_sub_graph_abcde_backward_dynamic_shape.py
Labels: contributor

#69214 [AutoParallel] fix error when using pure sharding
  python/paddle/distributed/auto_parallel/api.py
  test/auto_parallel/semi_auto_parallel_sharding_stage_1.py
Labels: contributor

#69353 [SOT][Faster Guard] add FasterStringifiedExpression
  paddle/fluid/pybind/jit.cc
  paddle/fluid/pybind/sot/guards.cc
  paddle/fluid/pybind/sot/guards.h
  python/paddle/jit/sot/opcode_translator/executor/guard.py
  python/paddle/jit/sot/opcode_translator/executor/variables/basic.py
  test/sot/test_case_base.py
  test/sot/test_dtype.py
  test/sot/test_faster_guard.py
  test/sot/test_guard_outputs.py
  test/sot/test_guard_user_defined_fn.py
Labels: contributor

#69346 [SOT][3.13] support `FORMAT_SIMPLE` opcode in python3.13
  python/paddle/jit/sot/opcode_translator/executor/opcode_executor.py
  test/sot/skip_files_py313
Labels: contributor

#69364 [Lod][fluid_ops] libpaddle LoDTensor
  paddle/fluid/pybind/tensor.cc
  python/paddle/base/core.py
Labels: contributor

#69343 [Lod] [fluid_ops] test_layer.cc LoDTensor
  paddle/fluid/imperative/layer.cc
  test/cpp/imperative/test_layer.cc
Labels: contributor

#69374 [xpu] fixbug for use of xpu::sigmoid and change xpu::clip_v2 to xpu::clamp
  paddle/phi/kernels/fusion/xpu/fused_multi_transformer_int8_xpu_kernel.cc
  paddle/phi/kernels/fusion/xpu/fused_multi_transformer_xpu_kernel.cc
  paddle/phi/kernels/fusion/xpu/fused_rope_utils.h
  paddle/phi/kernels/xpu/activation_grad_kernel.cc
  paddle/phi/kernels/xpu/c_embedding_kernel.cc
  paddle/phi/kernels/xpu/clip_kernel.cc
  paddle/phi/kernels/xpu/distribute_fpn_proposals_kernel.cc
  paddle/phi/kernels/xpu/embedding_kernel.cc
  paddle/phi/kernels/xpu/gather_kernel.cc
  paddle/phi/kernels/xpu/generate_proposals_kernel.cc
  paddle/phi/kernels/xpu/index_sample_kernel.cc
  paddle/phi/kernels/xpu/index_select_kernel.cc
  paddle/phi/kernels/xpu/repeat_interleave_kernel.cc
  paddle/phi/kernels/xpu/softmax_kernel.cc
  paddle/phi/kernels/xpu/take_along_axis_kernel.cc
  paddle/phi/kernels/xpu/unique_kernel.cc
Labels: XPU

#69383 [Lod][fluid_ops] tools LOD_TENSOR
  tools/test_check_api_compatible.py
Labels: contributor

#69360 Revert "【Hackathon 7th Fundable Projects 1 No.9-12】 [fluid_ops] data_norm"
  paddle/fluid/operators/data_norm_op.cc
  paddle/fluid/operators/data_norm_op.cu
  paddle/fluid/operators/data_norm_op.h
  test/deprecated/legacy_test/test_data_norm_op_deprecated.py
  test/deprecated/legacy_test/test_dist_fleet_ps2_deprecated.py
  test/deprecated/legacy_test/test_fleet_deprecated.py
  test/ipu/test_data_norm_op_ipu.py
  test/legacy_test/test_data_norm_op.py
Labels: PaddlePaddle Hackathon, contributor

#69378 [Lod][fluid_ops] set
  paddle/fluid/pybind/tensor.cc
Labels: contributor

#69301 【SCU】【Paddle Tensor No.24】新增 `paddle.matrix_transpose`, `paddle.linalg.matrix_transpose`，复用已有接口 `paddle.transpose`
  python/paddle/__init__.py
  python/paddle/linalg.py
  python/paddle/tensor/linalg.py
  test/legacy_test/test_transpose_op.py
Labels: contributor, HappyOpenSource Pro

#69361 【SCU】【Paddle Tensor No.28-29】新增 `paddle.from_dlpack` , `paddle.to_dlpack`，复用已有同名函数 `paddle.utils.dlpack`
  python/paddle/__init__.py
  test/legacy_test/test_dlpack.py
Labels: contributor, HappyOpenSource Pro

#69345 [Lod][fluid_ops] Replace LoDTensor in comment
  python/paddle/base/executor.py
  python/paddle/base/lod_tensor.py
  python/paddle/base/multiprocess_utils.py
  python/paddle/framework/io.py
  python/paddle/hapi/model.py
  python/paddle/incubate/layers/nn.py
  python/paddle/io/dataloader/dataloader_iter.py
  python/paddle/io/multiprocess_utils.py
  python/paddle/jit/dy2static/partial_program.py
  python/paddle/jit/dy2static/pir_partial_program.py
  python/paddle/jit/pir_translated_layer.py
  python/paddle/jit/translated_layer.py
  python/paddle/nn/clip.py
  python/paddle/static/nn/common.py
  python/paddle/static/nn/metric.py
  python/paddle/tensor/creation.py
  python/paddle/tensor/manipulation.py
  python/paddle/vision/ops.py
  test/book/notest_understand_sentiment.py
  test/cpp/fluid/platform/bfloat16_test.cu
  test/cpp/fluid/platform/float16_test.cu
  test/deprecated/ir/inference/test_trt_multiclass_nms3_op_deprecated.py
  test/deprecated/legacy_test/dist_fleet_ctr.py
  test/deprecated/legacy_test/test_eager_run_program_deprecated.py
  test/legacy_test/dist_fleet_ctr.py
  test/legacy_test/dist_fleet_heter_pipeline_ctr.py
  test/legacy_test/dist_fleet_sparse_embedding_ctr.py
  test/legacy_test/fleet_heter_ps_training.py
  test/legacy_test/test_add_position_encoding_op.py
  test/legacy_test/test_dist_fleet_sparse_embedding_ctr.py
  test/legacy_test/test_lod_tensor.py
Labels: PaddlePaddle Hackathon, contributor

#69382 [Lod][fluid_ops] replace LoDTensor to DenseTensor in paddle directory
  paddle/fluid/distributed/ps/service/communicator/communicator.h
  paddle/fluid/distributed/ps/service/heter_client.cc
  paddle/fluid/eager/eager_tensor.h
  paddle/fluid/framework/data_feed.h
  paddle/fluid/framework/ir/memory_optimize_pass/eager_deletion_pass.cc
  paddle/fluid/framework/phi_utils.cc
  paddle/fluid/imperative/gradient_accumulator.cc
  paddle/fluid/imperative/gradient_accumulator.h
  paddle/fluid/imperative/infer_shape_context.h
  paddle/fluid/imperative/layer.cc
  paddle/fluid/imperative/reducer.cc
  paddle/fluid/imperative/var_helper.cc
  paddle/fluid/imperative/variable_wrapper.h
  paddle/fluid/inference/api/analysis_predictor.cc
  paddle/fluid/inference/api/analysis_predictor.h
  paddle/fluid/inference/api/api_impl.cc
  paddle/fluid/inference/api/api_impl.h
  paddle/fluid/inference/api/details/reset_tensor_array.h
  paddle/fluid/inference/api/paddle_api.h
  paddle/fluid/inference/tensorrt/convert/op_converter.h
  paddle/fluid/operators/collective/recv_v2_op.cu.cc
  paddle/fluid/operators/controlflow/conditional_block_op.cc
  paddle/fluid/operators/load_combine_op.cc
  paddle/fluid/operators/lod_reset_op.cc
  paddle/fluid/operators/save_combine_op.cc
  paddle/fluid/operators/select_input_op.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/multiary_infer_sym.cc
  paddle/fluid/pybind/eager_method.cc
  paddle/fluid/pybind/eager_utils.cc
  paddle/fluid/pybind/imperative.cc
  paddle/phi/core/enforce.h
  paddle/phi/core/lod_utils.h
  paddle/phi/infermeta/multiary.cc
  paddle/phi/infermeta/ternary.cc
  paddle/phi/kernels/coalesce_tensor_kernel.cc
  paddle/phi/kernels/cpu/concat_kernel.cc
  paddle/phi/kernels/funcs/math/beam_search.h
  paddle/phi/kernels/funcs/selected_rows_functor.h
  paddle/phi/kernels/funcs/sequence2batch.h
  paddle/phi/kernels/gpu/concat_kernel.cu
  paddle/phi/kernels/xpu/full_kernel.cc
Labels: PaddlePaddle Hackathon, contributor

#69272 [Lod] [fluid_ops] python LoDTensor
  python/paddle/base/__init__.py
  python/paddle/base/data_feeder.py
  python/paddle/base/executor.py
  python/paddle/base/lod_tensor.py
  python/paddle/base/reader.py
  python/paddle/distributed/auto_parallel/api.py
  python/paddle/distributed/auto_parallel/static/utils.py
  python/paddle/framework/io.py
  python/paddle/framework/io_utils.py
  python/paddle/hapi/model.py
  python/paddle/incubate/multiprocessing/reductions.py
  python/paddle/inference/wrapper.py
  python/paddle/io/dataloader/dataloader_iter.py
  python/paddle/io/dataloader/sampler.py
  python/paddle/io/dataloader/worker.py
  python/paddle/nn/layer/layers.py
  python/paddle/pir/core.py
  python/paddle/static/nn/common.py
  python/paddle/static/quantization/quant2_int8_onednn_pass.py
  python/paddle/tensor/creation.py
  python/paddle/utils/dlpack.py
  test/cpp/fluid/assign_op_test.cc
  test/deprecated/ir/inference/inference_pass_test.py
  test/deprecated/ir/inference/quant_dequant_test.py
  test/deprecated/legacy_test/test_argsort_op_deprecated.py
  test/deprecated/legacy_test/test_feed_data_check_shape_type_deprecated.py
  test/deprecated/legacy_test/test_memory_reuse_exclude_feed_var_deprecated.py
  test/deprecated/legacy_test/test_tensor_array_to_tensor_deprecated.py
  test/dygraph_to_static/predictor_utils.py
  test/ir/inference/inference_pass_test.py
  test/ir/inference/quant_dequant_test.py
  test/legacy_test/op_test.py
  test/legacy_test/test_argsort_op.py
  test/legacy_test/test_auto_growth_allocator_gpu.py
  test/legacy_test/test_beam_search_decode_op.py
  test/legacy_test/test_dlpack.py
  test/legacy_test/test_eager_tensor.py
  test/legacy_test/test_feed_fetch_method.py
  test/legacy_test/test_fused_dconv_drelu_dbn_op.py
  test/legacy_test/test_lod_tensor.py
  test/legacy_test/test_lod_tensor_array.py
  test/legacy_test/test_naive_best_fit_gpu_memory_limit.py
  test/legacy_test/test_paddle_save_load.py
  test/legacy_test/test_paddle_save_load_binary.py
  test/legacy_test/test_print_op.py
  test/legacy_test/test_tensor.py
  test/legacy_test/test_tensor_copy_from.py
  test/legacy_test/test_tensor_to_numpy.py
Labels: PaddlePaddle Hackathon, contributor

#69412 [SOT][3.13] Prohibit treating instances of `BooleanEnvironmentVariable` directly as boolean values
  python/paddle/jit/sot/opcode_translator/executor/guard.py
  python/paddle/utils/environments.py
Labels: contributor

#69261 [Paddle TensorRT No.9-10] Add `pd_op.(argmin,argsort)` converter
  paddle/fluid/pir/transforms/tensorrt/trt_op_marker_pass.cc
  python/paddle/tensorrt/impls/search.py
  test/tensorrt/test_converter_search.py
Labels: contributor, HappyOpenSource

#69406 [Paddle Tensor No.4] 新增 `Tensor.__rmatmul__`
  paddle/fluid/pybind/eager_math_op_patch.cc
  python/paddle/base/dygraph/math_op_patch.py
  python/paddle/base/layers/math_op_patch.py
  python/paddle/pir/math_op_patch.py
  python/paddle/tensor/tensor.prototype.pyi
  test/legacy_test/test_math_op_patch.py
  test/legacy_test/test_math_op_patch_pir.py
Labels: contributor, HappyOpenSource

#69368 [XPU] update bkcl to round mode
  cmake/external/xpu.cmake
Labels: XPU

#69434 [Typos] Add `Typos` to pre-commit
  .pre-commit-config.yaml
  _typos.toml
  paddle/fluid/framework/details/build_strategy.h
Labels: contributor

#69381 [Lod][fluid_ops] Remove recursive_sequence_lengths in tests
  test/book/notest_understand_sentiment.py
  test/deprecated/legacy_test/test_weight_normalization_deprecated.py
  test/legacy_test/test_batch_norm_op.py
  test/legacy_test/test_data_feeder.py
  test/legacy_test/test_feed_fetch_method.py
  test/legacy_test/test_lod_tensor.py
  test/legacy_test/test_lod_tensor_array.py
  test/legacy_test/test_print_op.py
  test/legacy_test/test_tensor.py
Labels: PaddlePaddle Hackathon, contributor

#69424 [XPU] fix xpu compile dependency
  paddle/fluid/imperative/CMakeLists.txt
Labels: XPU

#69415 [Lod][fluid_ops] Change DenseTensor in paddle directory
  paddle/fluid/distributed/fleet_executor/dist_model.cc
  paddle/fluid/framework/fleet/ps_gpu_wrapper.h
  paddle/fluid/framework/infershape_utils.cc
  paddle/fluid/framework/var_desc.h
  paddle/fluid/imperative/all_reduce.cc
  paddle/fluid/imperative/bkcl_context.cc
  paddle/fluid/imperative/gloo_context.cc
  paddle/fluid/imperative/layer.cc
  paddle/fluid/imperative/xccl_context.cc
  paddle/fluid/inference/tensorrt/convert/generic_and_custom_plugin_creater.cc
  paddle/fluid/inference/tensorrt/convert/op_converter.h
  paddle/fluid/operators/controlflow/control_flow_op_helper.h
  paddle/fluid/operators/controlflow/while_op.cc
  paddle/fluid/pybind/eager.cc
  paddle/fluid/pybind/eager_utils.cc
  paddle/fluid/pybind/pybind.cc
  paddle/fluid/pybind/tensor.cc
  paddle/phi/core/enforce.h
  paddle/phi/kernels/cpu/distribute_fpn_proposals_kernel.cc
  paddle/phi/kernels/full_kernel.cc
  paddle/phi/kernels/xpu/concat_kernel.cc
Labels: PaddlePaddle Hackathon, contributor

#69425 move `paddle.tensor.logic.positive` to `paddle.tensor.math.positive`
  python/paddle/__init__.py
  python/paddle/tensor/__init__.py
  python/paddle/tensor/logic.py
  python/paddle/tensor/math.py
Labels: contributor, HappyOpenSource

#69141 Fix distribution API with 0-D input parameters 易用性提升 -part2
  python/paddle/distribution/bernoulli.py
  python/paddle/distribution/beta.py
  python/paddle/distribution/binomial.py
  python/paddle/distribution/categorical.py
  python/paddle/distribution/cauchy.py
  python/paddle/distribution/continuous_bernoulli.py
  python/paddle/distribution/dirichlet.py
  python/paddle/distribution/distribution.py
  python/paddle/distribution/exponential.py
  python/paddle/distribution/gamma.py
  python/paddle/distribution/geometric.py
  python/paddle/distribution/gumbel.py
  python/paddle/distribution/independent.py
  python/paddle/distribution/laplace.py
  python/paddle/distribution/lkj_cholesky.py
  python/paddle/distribution/multinomial.py
  python/paddle/distribution/multivariate_normal.py
  python/paddle/distribution/normal.py
  python/paddle/distribution/poisson.py
  python/paddle/distribution/student_t.py
  python/paddle/distribution/transformed_distribution.py
  python/paddle/distribution/uniform.py
  test/distribution/test_distribution_poisson.py
  test/distribution/test_distribution_poisson_static.py
Labels: contributor

#69440 [XPU] update xhpc to 1118
  cmake/external/xpu.cmake
  paddle/phi/kernels/xpu/logical_kernel.cc
Labels: XPU

#69401 [SOT][3.13] support `CONVERT_VALUE` and `FORMAT_WITH_SPEC` opcode in python3.13
  python/paddle/jit/sot/opcode_translator/executor/instr_flag.py
  python/paddle/jit/sot/opcode_translator/executor/opcode_executor.py
  test/sot/test_09_f_string.py
Labels: contributor

#69321 [Lod][fluid_ops] libpaddle LoDTensor
  python/paddle/base/core.py
Labels: contributor

#69380 [Lod][fluid_ops]recursive_sequence_lengths
  paddle/fluid/pybind/tensor.cc
  python/paddle/base/lod_tensor.py
  test/legacy_test/op_test.py
Labels: PaddlePaddle Hackathon, contributor

#69393 [AutoParallel] Reconstruct sharding mesh dimension inference logic - Part1 rename func parameter
  python/paddle/distributed/auto_parallel/api.py
  python/paddle/distributed/auto_parallel/sharding.py
  test/auto_parallel/semi_auto_parallel_sharding_stage_1.py
Labels: contributor

#69451 Fix `Tensor.square_` not available 易用性提升
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/same_operands_result.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/same_operands_result.h
  paddle/phi/ops/yaml/ops.yaml
  python/paddle/tensor/__init__.py
  test/legacy_test/test_inplace.py
Labels: contributor

#69457 [DCU] dcu fastgelu support fp16
  paddle/phi/kernels/gpu/gelu_grad_kernel.cu
  paddle/phi/kernels/gpu/gelu_kernel.cu
Labels: contributor

#69449 refact: 复用 `less_than` 实现 `less`,而不是直接 `import less_than as less`
  python/paddle/__init__.py
  python/paddle/tensor/__init__.py
  python/paddle/tensor/logic.py
Labels: contributor, HappyOpenSource

#69396 [Docathon][Add API Legend No.47] Add the legend of unflatten
  python/paddle/tensor/manipulation.py
Labels: contributor, HappyOpenSource

#69329 [CINN] Add array_pop InferSymbolicShape
  paddle/fluid/pir/dialect/operator/ir/manual_op.cc
  paddle/fluid/pir/dialect/operator/ir/manual_op.h
Labels: contributor

#69055 [CINN] Add symbol_infer_interface for create_array_like && has_elements
  paddle/fluid/pir/dialect/operator/ir/control_flow_op.cc
  paddle/fluid/pir/dialect/operator/ir/control_flow_op.h
  paddle/fluid/pir/dialect/operator/ir/manual_op.cc
  paddle/fluid/pir/dialect/operator/ir/manual_op.h
Labels: contributor

#69331 [CINN] add assign_array && assign_array_ InferSymbolicShape
  paddle/fluid/pir/dialect/operator/ir/manual_op.cc
  paddle/fluid/pir/dialect/operator/ir/manual_op.h
Labels: contributor

#69472 [CodeStyle][Typos][A-[11-19]] Fix typo(`addtional`、`addess`、`adjancent`、`admissable`、`afer`、`Ags`、`aggragate`、`alis`、`algorithem`、`alogrithm`)
  _typos.toml
  paddle/cinn/backends/codegen_gpu_dev.cc
  paddle/cinn/poly/stage.cc
  paddle/fluid/framework/fleet/heter_ps/graph_gpu_ps_table_inl.cu
  paddle/fluid/framework/ir/graph_helper.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/unary_infer_sym.cc
  paddle/fluid/pir/transforms/general/transfer_layout_pass.cc
  paddle/phi/backends/onednn/onednn_context.cc
  paddle/phi/kernels/gpu/rms_norm_kernel.cu
  paddle/phi/kernels/gpudnn/conv_cudnn_v7.h
  python/paddle/audio/datasets/dataset.py
Labels: contributor, HappyOpenSource

#69437 [Lod] [fluid_ops] LodTensor test
  test/cpp/fluid/platform/bfloat16_test.cu
  test/cpp/fluid/platform/float16_test.cu
  test/cpp/fluid/save_load_combine_op_test.cc
  test/deprecated/book/test_word2vec_book_deprecated.py
  test/deprecated/ir/inference/test_trt_multiclass_nms3_op_deprecated.py
  test/deprecated/legacy_test/test_eager_run_program_deprecated.py
  test/deprecated/legacy_test/test_run_program_op_deprecated.py
  test/ir/test_ir_fusion_group_pass.py
  test/legacy_test/nets.py
  test/legacy_test/test_paddle_save_load.py
Labels: contributor

#69335 [CINN] Add `slice_array && slice_array_dense` InferSymbolicShape
  paddle/fluid/pir/dialect/operator/ir/manual_op.cc
  paddle/fluid/pir/dialect/operator/ir/manual_op.h
Labels: contributor

#69017 [CINN] Add InferSymbolicShape for array_read ops
  paddle/fluid/pir/dialect/operator/ir/manual_op.cc
  paddle/fluid/pir/dialect/operator/ir/manual_op.h
Labels: contributor

#69505 [CodeStyle][Typos][A-[31-35]] Fix typo(`argumnets`、`argmuments`、`argumet`、`arised`、`aranged`、`arrray`)
  _typos.toml
  paddle/fluid/framework/new_executor/instruction/cinn_jit_instruction.cc
  paddle/fluid/inference/tensorrt/op_teller.cc
  paddle/phi/infermeta/spmd_rules/replicated.h
  paddle/phi/kernels/impl/kron_grad_kernel_impl.h
  python/paddle/incubate/asp/utils.py
  python/paddle/jit/dy2static/convert_operators.py
Labels: contributor, HappyOpenSource

#69484 [Lod] [fluid_ops] LodTensor python
  python/paddle/autograd/saved_tensors_hooks.py
  python/paddle/base/data_feed_desc.py
  python/paddle/base/executor.py
  python/paddle/base/framework.py
  python/paddle/base/lod_tensor.py
  python/paddle/base/reader.py
  python/paddle/framework/io.py
  python/paddle/incubate/layers/nn.py
  python/paddle/jit/api.py
  python/paddle/jit/dy2static/partial_program.py
  python/paddle/jit/dy2static/pir_partial_program.py
  python/paddle/jit/dy2static/utils.py
  python/paddle/jit/translated_layer.py
  python/paddle/nn/clip.py
  python/paddle/nn/functional/extension.py
  python/paddle/static/input.py
  python/paddle/static/nn/common.py
  python/paddle/tensor/array.py
  python/paddle/tensor/linalg.py
  python/paddle/tensor/manipulation.py
  python/paddle/tensor/tensor.prototype.pyi
Labels: PaddlePaddle Hackathon, contributor

#69448 [Lod][fluid_ops] IsValidLoDTensor
  paddle/fluid/pybind/data_set_py.cc
Labels: PaddlePaddle Hackathon, contributor

#69464 【SCU】【Paddle Tensor No.17、20】新增 paddle.inf, paddle.newaxis, 复用math.inf、None
  python/paddle/__init__.py
  test/legacy_test/test_constant.py
Labels: contributor, HappyOpenSource Pro

#68669 [PIR] refine `check_view_op_used_by_inplace` logic
  python/paddle/jit/dy2static/program_translator.py
  test/legacy_test/test_stride.py
Labels: contributor

#69525 [CodeStyle][Typos][A-[41-44]] Fix typo (`attritube`、`atrribute`、`attribtue`、`automatical`、`automaticly`、`Auxillary`)
  _typos.toml
  paddle/fluid/framework/ir/pass.cc
  paddle/fluid/framework/ir/pass.h
  paddle/fluid/framework/ir/pass_test.cc
  paddle/fluid/pybind/eager_legacy_op_function_generator.cc
  paddle/phi/backends/onednn/onednn_context.h
  python/paddle/distributed/auto_parallel/static/reshard_funcs/s_to_r_reshard_func.py
  python/paddle/incubate/autotune.py
  python/paddle/nn/initializer/kaiming.py
Labels: contributor, HappyOpenSource

#69480 [Paddle Tensor No.23] 新增`TensorA[mask] = TensorB`
  paddle/fluid/pybind/eager_method.cc
  test/indexing/test_setitem.py
Labels: contributor, HappyOpenSource

#69372 [Prim][PIR] Add back_decomp and support dynamic shape for take_along_axis_grad
  paddle/fluid/primitive/codegen/decomp_vjp_gen.py
  paddle/fluid/primitive/decomp_rule/decomp_vjp/details.h
  python/paddle/autograd/backward_utils.py
  test/legacy_test/test_take_along_axis_op.py
  test/prim/pir_prim/test_prim_sub_graph_pqrst_backward_dynamic_shape.py
Labels: contributor

#69520 [CINN] Clean some code
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/binary_infer_sym.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/multiary_infer_sym.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/unary_infer_sym.cc
  test/legacy_test/test_fused_attention_op_api.py
Labels: contributor

#69532 [CodeStyle][Typos][A-20] Fix typo(`Oll`)
  _typos.toml
  paddle/fluid/inference/tensorrt/convert/reverse_roll_op.cc
Labels: contributor, HappyOpenSource

#69494 [Lod][fluid_ops] paddle lodtensor
  paddle/phi/README.md
  python/paddle/base/executor.py
  python/paddle/base/framework.py
  python/paddle/base/lod_tensor.py
  python/paddle/base/trainer_factory.py
  python/paddle/distributed/auto_parallel/static/utils.py
  python/paddle/framework/io_utils.py
  python/paddle/inference/wrapper.py
  python/paddle/jit/dy2static/convert_operators.py
Labels: contributor

#69541 [Lod][fluid_ops] reader_py.cc
  paddle/fluid/pybind/reader_py.cc
Labels: contributor

#69551 [Lod][fluid_ops] revert recursive_sequence_lengths
  paddle/fluid/pybind/tensor.cc
Labels: PaddlePaddle Hackathon, contributor

#69252 math API support int tensor autocast to float32 易用性提升
  paddle/fluid/eager/auto_code_generator/generator/eager_gen.py
  paddle/fluid/pir/dialect/op_generator/api_gen.py
  paddle/phi/common/type_promotion.h
  python/paddle/tensor/math.py
  python/paddle/tensor/ops.py
  test/legacy_test/test_digamma_op.py
  test/legacy_test/test_logit_op.py
  test/legacy_test/test_logsumexp.py
  test/legacy_test/test_tensor_type_autocast.py
Labels: contributor

#69534 [Paddle Tensor No.23] 为`TensorA[mask] = TensorB`补充单测
  test/indexing/test_setitem.py
Labels: contributor, HappyOpenSource

#69573 Fix random failure in test_trt_convert_strided_slice
  paddle/fluid/inference/tensorrt/convert/slice_op.cc
  paddle/fluid/inference/tensorrt/convert/strided_slice_op.cc
Labels: NVIDIA, contributor

#69542 【SCU】【Paddle Tensor No.18】新增 paddle.nan, 复用math.nan
  python/paddle/__init__.py
  test/legacy_test/test_constant.py
Labels: contributor, HappyOpenSource Pro

#69562 [CodeStyle][Typos][C-[10-15]] Fix typo(`CACH(4)`, `catched(2)`, `cuase(2)`, `channles(1)`, `channnel(2)`, `cahr(1)`)
  _typos.toml
  paddle/fluid/framework/data_feed.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/unary_infer_sym.cc
  paddle/fluid/pybind/sot/cpython_internals.c
  security/advisory/pdsa-2023-013.md
  security/advisory/pdsa-2023-016.md
  test/dygraph_to_static/transformer_util.py
  tools/gen_ut_cmakelists.py
Labels: contributor, HappyOpenSource

#69540 [Lod][fluid_ops] save_lod_tensor
  paddle/fluid/pybind/io.cc
  python/paddle/framework/io.py
  test/legacy_test/test_paddle_save_load_binary.py
Labels: PaddlePaddle Hackathon, contributor

#69606 [CodeStyle][Typos][B-1] Fix typo (beed)
  _typos.toml
  paddle/fluid/inference/utils/singleton.h
  paddle/phi/kernels/funcs/jit/refer/refer.h
Labels: contributor, HappyOpenSource

#69605 [CodeStyle][Typos][B-13,B-15,B-16]] Fix typos (`brach`, `buffert`, `builer`)
  _typos.toml
  paddle/fluid/operators/tensorrt/tensorrt_engine_op.h
  test/legacy_test/test_egr_python_api.py
Labels: contributor, HappyOpenSource

#69569 [Lod][fluid_ops] lodtensor_printer
  paddle/fluid/framework/CMakeLists.txt
  paddle/fluid/framework/heter_section_worker.cc
  paddle/fluid/framework/hogwild_worker.cc
  paddle/fluid/framework/multi_trainer.cc
  paddle/fluid/framework/ps_gpu_worker.cc
  paddle/fluid/platform/CMakeLists.txt
  paddle/fluid/platform/densetensor_printer.cc
  paddle/fluid/platform/densetensor_printer.h
  test/cpp/fluid/platform/CMakeLists.txt
  test/cpp/fluid/platform/lodtensor_printer_test.cc
Labels: PaddlePaddle Hackathon, contributor

#69568 [Lod][fluid_ops] lod_tensor_array
  paddle/fluid/framework/dense_tensor_array.h
  paddle/fluid/framework/var_type.h
  paddle/fluid/framework/var_type_traits.h
  paddle/fluid/framework/variable_helper.cc
  paddle/fluid/imperative/var_helper.cc
  paddle/fluid/inference/api/api_impl.h
  paddle/fluid/inference/api/details/reset_tensor_array.h
  paddle/fluid/operators/array_operator.h
  paddle/fluid/operators/beam_search_decode_op_def.h
  paddle/fluid/operators/load_op.cc
  paddle/fluid/operators/tensor_array_to_tensor_op.cc
  paddle/fluid/pybind/compiled_program.cc
  paddle/fluid/pybind/eager_utils.h
  paddle/fluid/pybind/place.cc
  paddle/fluid/pybind/pybind.cc
  paddle/fluid/pybind/tensor.cc
  paddle/phi/core/framework/dense_tensor_serialize.cc
  paddle/phi/core/framework/dense_tensor_serialize.h
  paddle/phi/kernels/impl/load_combine_kernel_impl.h
  paddle/phi/kernels/impl/load_kernel_impl.h
  paddle/phi/kernels/impl/save_combine_kernel_impl.h
  paddle/phi/kernels/impl/save_kernel_impl.h
  paddle/phi/kernels/selected_rows/impl/save_kernel_impl.h
Labels: PaddlePaddle Hackathon, contributor

#69558 [CodeStyle][Typos][A-[38-40]] Fix typo (astroid，attemps，attribtes)
  _typos.toml
  paddle/phi/core/string_tensor.cc
  test/legacy_test/test_eager_tensor.py
Labels: contributor, HappyOpenSource

#69609 [CodeStyle][Typos][A-45] Fix typo('available')
  _typos.toml
  paddle/fluid/distributed/ps/thirdparty/round_robin.h
Labels: contributor, HappyOpenSource

#69613 【SCU】【Paddle Tensor No.19】新增paddle.pi，复用math.pi
  python/paddle/__init__.py
  test/legacy_test/test_constant.py
Labels: contributor, HappyOpenSource Pro

#69473 【SCU】【Paddle Tensor No.5】新增 Tensor.__rand__，复用已有接口Tensor.__and__
  python/paddle/tensor/__init__.py
  python/paddle/tensor/logic.py
  python/paddle/tensor/tensor.prototype.pyi
  test/legacy_test/test_math_op_patch.py
  test/legacy_test/test_math_op_patch_pir.py
Labels: contributor, HappyOpenSource Pro

#69615 [PIR] Fix `check_view_api_used_by_inplace`
  python/paddle/jit/dy2static/program_translator.py
Labels: contributor

#69567 [SOT][3.13] Complete simulation for bytecode `TO_BOOL` `MAKE_FUNCTION` and `SET_FUNCTION_ATTRIBUTE`
  python/paddle/jit/sot/opcode_translator/executor/opcode_executor.py
  test/sot/skip_files_py313
  test/sot/test_13_make_function.py
Labels: contributor

#69644 [CodeStyle][Typos][A-[21-30]] Fix typos (`allctor`,`almostly`,`alog`,`Aread`,`Allways`,`alway`,`ane`,`adn`,`expaned`,`annotaions`,`annotaion`,`architecure`,`architecuture`,`aer`)
  _typos.toml
  paddle/cinn/operator_fusion/graph_transformer/search_algorithm.h
  paddle/fluid/operators/fused/fused_attention_op.cc
  paddle/fluid/platform/init.cc
  paddle/fluid/pybind/pybind.cc
  paddle/phi/infermeta/spmd_rules/cross_entropy_with_softmax.cc
  python/paddle/distributed/passes/auto_parallel_fp16.py
  python/paddle/incubate/asp/supported_layer_list.py
  python/paddle/nn/utils/transform_parameters.py
  python/paddle/optimizer/optimizer.py
  python/paddle/static/quantization/post_training_quantization.py
  python/paddle/tensor/tensor.prototype.pyi
  test/cpp/fluid/platform/errors_test.cc
  test/cpp/phi/kernels/test_gpu_timer.cu
Labels: contributor

#69650 [CodeStyle][Typos] Sort the `_typos.toml` file in the same order as the task list.
  _typos.toml
  test/distribution/test_distribution_lkj_cholesky_static.py
Labels: contributor

#69652 [CodeStyle][Typos][A-45] Fix typo (`AVALIABLE`)
  _typos.toml
  cmake/cuda.cmake
  paddle/fluid/inference/tensorrt/plugin/deformable_conv_op_plugin.cu
  paddle/fluid/inference/tensorrt/plugin/multihead_matmul_roformer_plugin.cu
  paddle/fluid/inference/tensorrt/plugin/preln_residual_bias_plugin.cu
  paddle/fluid/inference/tensorrt/plugin/qkv_to_context_plugin.cu
  paddle/fluid/inference/tensorrt/plugin/trans_layernorm_op_plugin.cu
  paddle/phi/kernels/fusion/gpu/block_multi_head_attention_kernel.cu
  paddle/phi/kernels/gpu/top_p_sampling_kernel.cu
  test/cpp/inference/api/trt_dynamic_shape_ernie_test.cc
Labels: contributor

#69664 [CodeStyle][Typos][A-28,C-[18-21]] Fix typos (`annotaion`,`choses`,`choos`,`choosed`,`choosen`)
  _typos.toml
  paddle/fluid/distributed/fleet_executor/dist_model.cc
  paddle/fluid/distributed/ps/thirdparty/round_robin.h
  paddle/phi/kernels/gpu/yolo_box_post_kernel.cu
  paddle/phi/kernels/onednn/stack_kernel.cc
  test/dygraph_to_static/test_convert_operators.py
  tools/gen_pybind11_stub.py
Labels: contributor

#69621 [Lod][fluid_ops] get_dense_tensor_array
  paddle/fluid/pybind/pybind.cc
  python/paddle/base/executor.py
  test/deprecated/legacy_test/test_tensor_array_to_tensor_deprecated.py
  test/legacy_test/test_beam_search_decode_op.py
  test/legacy_test/test_lod_tensor_array.py
  test/legacy_test/test_tensor_array_to_tensor.py
Labels: contributor

#69622 [Lod] [fluid_ops] modify lod_tensor in test directory
  test/cpp/fluid/assign_op_test.cc
  test/cpp/fluid/platform/bfloat16_test.cc
  test/cpp/fluid/platform/bfloat16_test.cu
  test/cpp/fluid/platform/float16_test.cu
  test/cpp/imperative/test_layer.cc
  test/dygraph_to_static/test_len.py
  test/legacy_test/test_eager_tensor.py
  test/legacy_test/test_fetch_lod_tensor_array.py
Labels: contributor

#69529 `paddle.bernoulli` add parameter `p` 易用性提升
  python/paddle/tensor/random.py
  test/legacy_test/test_bernoulli_op.py
Labels: contributor

#69498 [SCU][Docathon][Add API Legend No.24] Update annotations of `matrix_transpose`
  python/paddle/tensor/linalg.py
Labels: contributor, HappyOpenSource Pro

#69614 [xpu] fix pir:fc_xpu_fuse_pass && add bfloat16 for op :abs
  paddle/fluid/pir/transforms/xpu/fc_xpu_fuse_pass.cc
  paddle/phi/backends/xpu/xpu3_op_list.cc
  paddle/phi/kernels/fusion/xpu/fc_xpu_kernel.cc
  paddle/phi/kernels/xpu/abs_kernel.cc
  paddle/phi/ops/yaml/fused_ops.yaml
Labels: XPU

#69395 [AutoParallel] Reconstruct sharding mesh dimension inference logic - Part3 reconstruct
  python/paddle/distributed/auto_parallel/api.py
  python/paddle/distributed/auto_parallel/intermediate/parallel_base.py
  test/auto_parallel/hybrid_strategy/semi_auto_parallel_sharding_stage_1.py
  test/auto_parallel/hybrid_strategy/semi_auto_parallel_sharding_stage_2.py
  test/auto_parallel/hybrid_strategy/semi_auto_parallel_sharding_stage_3.py
  test/auto_parallel/semi_auto_parallel_sharding_stage_1.py
  test/auto_parallel/semi_auto_parallel_sharding_stage_2.py
  test/auto_parallel/semi_auto_parallel_sharding_stage_3.py
Labels: contributor

#69005 【Infer Symbolic Shape No.131】Add infer_symbol_shape for cholesky_solve_op
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/binary_infer_sym.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/binary_infer_sym.h
  paddle/phi/ops/yaml/ops.yaml
  test/legacy_test/test_cholesky_solve_op.py
Labels: contributor

#69617 [DCU] dcu topk warpsize bugfix
  paddle/phi/kernels/funcs/top_k_function_cuda.h
Labels: contributor

#69579 [Custom Device] fix c_comm_init_op and c_gen_xccl_id_op
  paddle/common/flags.cc
  paddle/fluid/operators/collective/c_comm_init_op.cc
  paddle/fluid/operators/collective/c_gen_xccl_id_op.cc
Labels: contributor

#69640 [CodeStyle][Typos][B-[3-7]] Fix typo(`befor`, `befores`, `begining`,`benfit`,`Betweent`,`betweeen`,`bindins`)
  _typos.toml
  paddle/cinn/hlir/dialect/operator/ir/generate_shape_util.cc
  paddle/cinn/optim/lower_function_call_bind_vars.cc
  paddle/fluid/eager/general_grad.h
  paddle/fluid/framework/data_feed.cu
  paddle/fluid/framework/fleet/ps_gpu_wrapper.cc
  paddle/fluid/framework/new_executor/interpreter/dependency_builder.cc
  paddle/fluid/inference/tensorrt/convert/tile_op.cc
  paddle/fluid/pir/transforms/onednn/cpu_bfloat16_squash_pass.cc
  python/paddle/distributed/auto_parallel/static/completion.py
  test/legacy_test/test_array_read_write_op.py
  tools/check_file_diff_approvals.sh
Labels: contributor, HappyOpenSource

#68829 [Prim][PIR] Add backward_decomp and support dynamic shape for ceil_grad
  paddle/fluid/primitive/codegen/decomp_vjp_gen.py
  paddle/fluid/primitive/decomp_rule/decomp_vjp/details.h
  python/paddle/autograd/backward_utils.py
  test/legacy_test/test_activation_op.py
  test/prim/pir_prim/test_prim_sub_graph_abcde_backward_dynamic_shape.py
Labels: contributor

#69463 [Paddle Tensor No.6][BUPT] 新增 `Tensor.__ror__`
  python/paddle/tensor/__init__.py
  python/paddle/tensor/logic.py
  python/paddle/tensor/tensor.prototype.pyi
  test/legacy_test/test_math_op_patch.py
  test/legacy_test/test_math_op_patch_pir.py
Labels: contributor, HappyOpenSource Pro

#69667 【SCU】【Paddle Tensor No.16】新增 paddle.e, 复用math.e
  python/paddle/__init__.py
  test/legacy_test/test_constant.py
Labels: contributor, HappyOpenSource Pro

#69413 [SCU][Docathon][Add API Legend No.34]Add legend for transpose API
  python/paddle/tensor/manipulation.py
Labels: contributor, HappyOpenSource Pro

#69404 [SCU][Docathon][Add API Legend No.31] Add legend for stack API
  python/paddle/tensor/manipulation.py
Labels: contributor, HappyOpenSource Pro

#69563 【SCU】【Paddle TensorRT No.5】Add `pd_op.thresholded_relu` converter
  paddle/fluid/pir/transforms/tensorrt/trt_op_marker_pass.cc
  python/paddle/tensorrt/impls/activation.py
  test/tensorrt/test_converter_activation.py
Labels: contributor, HappyOpenSource Pro

#69702 [Lod][fluid_ops] data_transform.cc
  paddle/fluid/framework/data_transform.cc
  paddle/fluid/framework/executor_gc_helper.cc
  paddle/fluid/framework/new_executor/instruction/control_flow/select_input_instruction.cc
  paddle/fluid/framework/new_executor/instruction/control_flow/select_output_instruction.cc
  paddle/fluid/framework/new_executor/pir_interpreter.cc
  paddle/fluid/framework/new_executor/program_interpreter.cc
Labels: PaddlePaddle Hackathon, contributor

#69344 [CINN] Add `cinn_op.split` infersymbolicshape
  paddle/cinn/hlir/dialect/operator/ir/manual_op.cc
  paddle/cinn/hlir/dialect/operator/ir/manual_op.h
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/cinn_op_infer_sym.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/cinn_op_infer_sym.h
Labels: contributor

#69738 [SOT][3.13] fix get `frame.f_locals` segmentation fault
  paddle/fluid/pybind/sot/cpython_internals.c
  paddle/fluid/pybind/sot/cpython_internals.h
  paddle/fluid/pybind/sot/eval_frame.c
Labels: contributor

#69704 [Lod][fluid_ops] tdm_sampler
  paddle/phi/infermeta/ternary.cc
  paddle/phi/infermeta/ternary.h
  paddle/phi/kernels/cpu/tdm_sampler_kernel.cc
  paddle/phi/ops/yaml/ops.yaml
  python/paddle/incubate/layers/nn.py
  test/legacy_test/test_tdm_sampler_op.py
Labels: PaddlePaddle Hackathon, contributor

#69069 [CINN]Add InferSymbolicShape for tensor_to_array
  paddle/fluid/pir/dialect/operator/ir/manual_op.cc
  paddle/fluid/pir/dialect/operator/ir/manual_op.h
Labels: contributor

#69684 [Prim][PIR] Support dynamic shape for tile_grad
  paddle/fluid/primitive/decomp_rule/decomp_vjp/details.h
  python/paddle/autograd/backward_utils.py
  test/prim/pir_prim/test_prim_sub_graph_pqrst_backward_dynamic_shape.py
Labels: contributor

#69359 [Paddle TensorRT No.17] Add pd_op.celu converter
  paddle/fluid/pir/transforms/tensorrt/trt_op_marker_pass.cc
  python/paddle/tensorrt/converter_utils.py
  python/paddle/tensorrt/impls/activation.py
  test/tensorrt/test_converter_activation.py
Labels: contributor, HappyOpenSource

#69632 [Paddle Tensor No.12][BUPT] 新增 Tensor.__dlpack_device__
  python/paddle/base/dygraph/tensor_patch_methods.py
  test/dygraph_to_static/test_tensor_attr_consistency.py
  test/legacy_test/test_dlpack.py
  test/legacy_test/test_eager_tensor.py
Labels: contributor, HappyOpenSource Pro

#69741 [CodeStyle][Typos][A-36] Fix typos (`assigend`, `assined`)
  _typos.toml
  paddle/phi/infermeta/spmd_rules/utils.h
  tools/gen_ut_cmakelists.py
Labels: contributor, HappyOpenSource

#69477 【SCU】【Paddle Tensor No.25】新增`paddle.vecdot` , `paddle.linalg.vecdot`
  python/paddle/__init__.py
  python/paddle/linalg.py
  python/paddle/tensor/__init__.py
  python/paddle/tensor/linalg.py
  test/legacy_test/test_linalg_vecdot.py
Labels: contributor, HappyOpenSource Pro

#69747 refact: remove duplicate op.
  paddle/fluid/primitive/base/primitive_ops.h
Labels: contributor, HappyOpenSource

#69729 [Docathon][Add API Legend No.1] Add the picture of broadcast_to
  python/paddle/tensor/manipulation.py
Labels: contributor, HappyOpenSource
