Repository PaddlePaddle/Paddle, pull requests merged in 2024-09, with the labels that each got.

#67854 remove some static manual uts
  test/deprecated/legacy_test/CMakeLists.txt
  test/legacy_test/CMakeLists.txt
  test/legacy_test/dist_fleet_sync_batch_norm.py
  test/legacy_test/static_model_parallel_fused_attention.py
  test/legacy_test/static_model_parallel_fused_feedforward.py
  test/legacy_test/test_c_comm_init_all_op.py
  test/legacy_test/test_fleet_executor.py
  test/legacy_test/test_fleet_executor_with_task_nodes.py
  test/legacy_test/test_fleet_gradient_scale.py
  test/legacy_test/test_static_model_parallel_fused_attention.py
  test/legacy_test/test_static_model_parallel_fused_feedforward.py
  test/legacy_test/test_sync_batch_norm_op.py
  tools/jetson_infer_op.py
  tools/parallel_UT_rule.py
  tools/static_mode_white_list.py
  tools/windows/run_unittests.sh
Labels: contributor

#67788 [CINN][BUAA][Infer Symbolic Shape BUAA No.4,109]Add stanh and floor_divide op
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/element_wise_binary.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/element_wise_binary.h
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/same_operands_result.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/same_operands_result.h
  paddle/phi/ops/yaml/legacy/static_ops.yaml
  paddle/phi/ops/yaml/ops.yaml
Labels: contributor, HappyOpenSource Pro

#67705 【BUAA】【Infer Symbolic Shape No.211,214】Add prior_box and qr
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/binary_infer_sym.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/binary_infer_sym.h
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/unary_infer_sym.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/unary_infer_sym.h
  paddle/phi/ops/yaml/ops.yaml
Labels: contributor, HappyOpenSource Pro

#67387 【Infer Symbolic Shape No.86, 89】[buaa]Add multiplex number_count op
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/multiary_infer_sym.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/multiary_infer_sym.h
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/same_operands_result.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/same_operands_result.h
  paddle/phi/ops/yaml/ops.yaml
Labels: contributor, HappyOpenSource Pro

#67881 Replace phi::errors to common::errors [fluid_ops]
  paddle/cinn/hlir/dialect/operator/ir/generate_shape_util.cc
  paddle/cinn/hlir/dialect/operator/transforms/dynamic_reshape_pass.cc
  paddle/cinn/hlir/dialect/operator/transforms/fuse_shape_ops_into_generate_shape_op_pass.cc
  paddle/cinn/hlir/dialect/operator/transforms/group_merge/convert_dynamic_to_static_dim_pass.cc
  paddle/cinn/hlir/dialect/operator/transforms/group_merge/convert_static_dim_to_dynamic_pass.cc
  paddle/cinn/hlir/dialect/operator/transforms/group_merge/generate_shape_util.cc
  paddle/cinn/hlir/dialect/operator/transforms/group_merge/move_generate_shape_ops_to_prologue_pass.cc
  paddle/cinn/hlir/dialect/operator/transforms/pd_to_cinn_pass.cc
  paddle/cinn/hlir/dialect/operator/transforms/split_generate_shape_into_shape_ops_pass.cc
  paddle/cinn/hlir/framework/op.h
  paddle/cinn/hlir/framework/op_strategy.cc
  paddle/cinn/hlir/framework/pir/op_lowering_impl.cc
  paddle/cinn/hlir/framework/pir/op_mapper.h
  paddle/cinn/hlir/framework/pir/utils.cc
  paddle/cinn/hlir/framework/schedule.h
  paddle/cinn/hlir/framework/visualize_helper.h
  paddle/cinn/hlir/op/contrib/bitcast_convert.cc
  paddle/cinn/hlir/op/contrib/cholesky.cc
  paddle/cinn/hlir/op/op_util.cc
  paddle/cinn/hlir/op/op_util.h
  paddle/cinn/hlir/op/reduction.cc
  paddle/cinn/hlir/pe/broadcast.cc
  paddle/cinn/hlir/pe/ir_schedule_pe.cc
  paddle/cinn/hlir/pe/load_x86_params.cc
  paddle/cinn/operator_fusion/pattern_fuser.h
  paddle/cinn/runtime/hip/hip_module.cc
  paddle/fluid/distributed/ps/table/ssd_sparse_table.cc
  paddle/phi/backends/gpu/gpu_context.cc
  paddle/phi/infermeta/multiary.cc
  paddle/phi/kernels/gpu/flash_attn_grad_kernel.cu
  paddle/phi/kernels/gpu/flash_attn_kernel.cu
  paddle/phi/kernels/xpu/rms_norm_grad_kernel.cc
  paddle/phi/kernels/xpu/rms_norm_kernel.cc
Labels: contributor, HappyOpenSource

#67775 [Prim][PIR] Support the dynamic shape for prod_grad
  paddle/fluid/primitive/rule/vjp/details.h
  python/paddle/autograd/backward_utils.py
  test/prim/pir_prim/test_prim_sub_graph_pqrst_backward_dynamic_shape.py
Labels: contributor

#67814 【BUAA】【Infer Symbolic Shape】Add depthwise_conv for CINN
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/binary_infer_sym.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/binary_infer_sym.h
  paddle/phi/ops/yaml/ops.yaml
Labels: contributor, HappyOpenSource Pro

#67830 [OneDNN][PIR] Fix bf16 pass data type replacement error
  paddle/fluid/pir/transforms/onednn/cpu_bfloat16_pass.cc
  paddle/fluid/pir/transforms/onednn/cpu_bfloat16_placement_pass.cc
  paddle/fluid/pir/transforms/onednn/cpu_bfloat16_type_placement_pass.cc
Labels: Intel, contributor

#67894 【Hackathon 6th Fundable Projects 3 No.359】[fluid_ops] soft_relu
  paddle/fluid/operators/CMakeLists.txt
  paddle/fluid/operators/activation_op.cc
  paddle/fluid/operators/soft_relu_op.cu
  paddle/phi/kernels/cpu/soft_relu_grad_kernel.cc
  paddle/phi/kernels/cpu/soft_relu_kernel.cc
  paddle/phi/kernels/gpu/soft_relu_grad_kernel.cu
  paddle/phi/kernels/gpu/soft_relu_kernel.cu
  paddle/phi/ops/yaml/inconsistent/onednn_ops_extra.yaml
  paddle/phi/ops/yaml/inconsistent/static_backward.yaml
  paddle/phi/ops/yaml/inconsistent/static_ops.yaml
Labels: PaddlePaddle Hackathon, contributor

#67851 【Infer Symbolic Shape No.78, 79】[buaa]Add log2 log10 op
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/same_operands_result.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/same_operands_result.h
  paddle/phi/ops/yaml/ops.yaml
Labels: contributor, HappyOpenSource Pro

#67858 【BUAA】【Infer Symbolic Shape】Add weighted_sample_neighbors for CINN
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/multiary_infer_sym.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/multiary_infer_sym.h
  paddle/phi/ops/yaml/ops.yaml
Labels: contributor, HappyOpenSource Pro

#67189 Replace framework::ThreadPool to phi::ThreadPool [fluid_ops]
  paddle/fluid/distributed/ps/service/ps_graph_client.cc
  paddle/fluid/distributed/ps/service/ps_graph_client.h
  paddle/fluid/framework/data_set.cc
  paddle/fluid/framework/dist_multi_trainer.cc
  paddle/fluid/framework/multi_trainer.cc
  test/cpp/fluid/framework/threadpool_test.cc
Labels: contributor, HappyOpenSource

#67899 Replace platform::ToNCCLDataType [fluid_ops]
  paddle/fluid/framework/compiled_program.cc
  paddle/fluid/imperative/all_reduce.cc
  paddle/fluid/imperative/bkcl_context.cc
  paddle/fluid/imperative/nccl_context.cc
Labels: contributor, HappyOpenSource

#67695 【Error Message No. 389-397】replace CHECK macro
  paddle/fluid/pir/transforms/build_cinn_pass.cc
  paddle/phi/core/tensor_utils.cc
Labels: contributor, HappyOpenSource

#67885 【complex op No.50】tan_coo/tan_csr(sparse）
  paddle/phi/kernels/sparse/cpu/unary_grad_kernel.cc
  paddle/phi/kernels/sparse/cpu/unary_kernel.cc
  paddle/phi/kernels/sparse/gpu/unary_grad_kernel.cu
  paddle/phi/kernels/sparse/gpu/unary_kernel.cu
  paddle/phi/kernels/sparse/impl/unary_kernel_impl.h
  python/paddle/sparse/unary.py
  test/legacy_test/test_sparse_unary_op.py
Labels: contributor, HappyOpenSource

#67800 Fix `paddle.diff` when `n!=1` and has `prepend` or `append` 易用性提升
  python/paddle/tensor/math.py
  test/legacy_test/test_diff_op.py
Labels: contributor

#67891 【Hackathon 7th No.13】 Backward decomp for put_along_axis_grad op
  paddle/fluid/primitive/codegen/gen.py
  paddle/fluid/primitive/rule/vjp/details.h
  test/legacy_test/test_put_along_axis_op.py
Labels: PaddlePaddle Hackathon, contributor

#66929 paddle.linalg.matrix_rank add attributes `atol` and `rtol` 易用性提升
  paddle/phi/infermeta/ternary.cc
  paddle/phi/infermeta/ternary.h
  paddle/phi/kernels/cpu/matrix_rank_tol_kernel.cc
  paddle/phi/kernels/gpu/matrix_rank_tol_kernel.cu
  paddle/phi/kernels/matrix_rank_tol_kernel.h
  paddle/phi/ops/yaml/ops.yaml
  python/paddle/tensor/linalg.py
  test/legacy_test/test_matrix_rank_atol_rtol_op.py
Labels: contributor

#67823 [SOT] Dispatcher support `ListVariable` extend `DictVariable` and `DictVariable`
  python/paddle/jit/sot/opcode_translator/executor/opcode_executor.py
  python/paddle/jit/sot/opcode_translator/executor/variable_dispatch.py
  python/paddle/jit/sot/opcode_translator/executor/variables/container.py
  test/dygraph_to_static/seq2seq_dygraph_model.py
  test/sot/test_04_list.py
Labels: contributor

#67933 [Fix] 修复 CI 中抓取类型检查标题的 `grep` 问题
  paddle/scripts/paddle_build.sh
Labels: contributor

#67893 [Dy2St] Fix jupyter error message display errors
  python/paddle/jit/dy2static/error.py
Labels: contributor

#67882 【Infer Symbolic Shape No.25】【BUAA】 Add dist op
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/binary_infer_sym.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/binary_infer_sym.h
  paddle/phi/ops/yaml/ops.yaml
Labels: contributor, HappyOpenSource Pro

#67857 make some auto parallel uts in distributed_passes deprecated
  test/deprecated/CMakeLists.txt
  test/deprecated/distributed_passes/CMakeLists.txt
  test/deprecated/distributed_passes/auto_parallel_pass_test_base_deprecated.py
  test/deprecated/distributed_passes/test_auto_parallel_amp_pass_deprecated.py
  test/deprecated/distributed_passes/test_auto_parallel_data_parallel_optimization_pass_deprecated.py
  test/deprecated/distributed_passes/test_auto_parallel_fp16_pass_deprecated.py
  test/deprecated/distributed_passes/test_auto_parallel_fused_linear_promotion_pass_deprecated.py
  test/deprecated/distributed_passes/test_auto_parallel_gradient_merge_pass_deprecated.py
  test/deprecated/distributed_passes/test_auto_parallel_recompute_pass_deprecated.py
  test/deprecated/distributed_passes/test_auto_parallel_sharding_pass_deprecated.py
  test/distributed_passes/CMakeLists.txt
  test/distributed_passes/ps_pass_test_base.py
  test/distributed_passes/test_dist_fuse_adam_pass.py
  test/distributed_passes/test_dist_fuse_bn_act_pass.py
  test/distributed_passes/test_dist_fuse_bn_add_act_pass.py
  test/distributed_passes/test_dist_fuse_momentum_pass.py
  test/distributed_passes/test_dist_fuse_relu_depthwise_conv_pass.py
  test/distributed_passes/test_dist_fuse_sgd_pass.py
  test/distributed_passes/test_dist_inplace_addto_pass.py
  test/distributed_passes/test_ps_trainer_pass.py
  tools/test_run_by_protobuf_3.py
Labels: contributor

#67451 [buaa]【Infer Symbolic Shape BUAA No.193】Add detection_map op
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/multiary_infer_sym.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/multiary_infer_sym.h
  paddle/phi/ops/yaml/ops.yaml
Labels: contributor, HappyOpenSource Pro

#65969 【Hackathon 6th Fundable Projects 3 No.158】[fluid_ops] fused_gate_attention
  paddle/fluid/operators/fused/fused_gate_attention_op.cu
  paddle/fluid/operators/ops_signature/fused_gate_attention_sig.cc
  paddle/fluid/pir/dialect/op_generator/ops_api_gen.py
  paddle/phi/infermeta/fusion.cc
  paddle/phi/infermeta/fusion.h
  paddle/phi/kernels/funcs/fused_gate_attention.h
  paddle/phi/kernels/fusion/gpu/fused_gate_attention_grad_kernel.cu
  paddle/phi/kernels/fusion/gpu/fused_gate_attention_kernel.cu
  paddle/phi/ops/yaml/inconsistent/static_backward.yaml
  paddle/phi/ops/yaml/inconsistent/static_ops.yaml
  paddle/phi/ops/yaml/op_compat.yaml
Labels: PaddlePaddle Hackathon, contributor

#67836 [PIR][oneDNN] Fix data type in cpu_bfloat16_squash_pass
  paddle/fluid/pir/transforms/onednn/cpu_bfloat16_squash_pass.cc
  test/ir/pir/fused_pass/onednn/test_cpu_bfloat16_squash_pass.py
Labels: Intel, contributor

#67955 [XPU] support index_add and index_add_grad in xpu, support bf16 and fp16 for index_select
  paddle/phi/backends/xpu/xpu3_op_list.cc
  paddle/phi/kernels/xpu/index_add_grad_kernel.cc
  paddle/phi/kernels/xpu/index_add_kernel.cc
  paddle/phi/kernels/xpu/index_select_kernel.cc
  test/xpu/test_index_add_op_xpu.py
Labels: contributor

#67915 CI测试不review [fluid_ops] partial_send process_group
  paddle/phi/kernels/gpu/partial_send_kernel.cu
Labels: contributor

#67959 [XPU] refine test
  test/xpu/test_eye_op_xpu.py
Labels: XPU

#67751 【Infer Symbolic Shape No.175】【BUAA】Add unfold ops
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/unary_infer_sym.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/unary_infer_sym.h
  paddle/phi/ops/yaml/ops.yaml
Labels: contributor, HappyOpenSource Pro

#67864 【Infer Symbolic Shape No.11】【BUAA】 Add box_coder op
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/multiary_infer_sym.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/multiary_infer_sym.h
  paddle/phi/ops/yaml/ops.yaml
Labels: contributor, HappyOpenSource Pro

#67902 fix some static manual dist uts
  test/deprecated/asp/CMakeLists.txt
  test/deprecated/asp/test_fleet_with_asp_static_deprecated.py
  test/deprecated/legacy_test/CMakeLists.txt
  test/deprecated/legacy_test/test_communicator_async.py
  test/legacy_test/test_dist_base.py
  test/legacy_test/test_dist_fleet_base.py
  test/legacy_test/test_fleet_base_single.py
  tools/parallel_UT_rule.py
  tools/test_run_by_protobuf_3.py
Labels: contributor

#67876 [SOT][dynamic shape] support fallback to static shape
  python/paddle/jit/sot/opcode_translator/executor/executor_cache.py
  python/paddle/jit/sot/opcode_translator/executor/function_graph.py
  python/paddle/jit/sot/opcode_translator/executor/variables/base.py
  python/paddle/jit/sot/opcode_translator/executor/variables/basic.py
  python/paddle/jit/sot/opcode_translator/executor/variables/callable.py
  python/paddle/jit/sot/utils/__init__.py
  python/paddle/jit/sot/utils/exceptions.py
  python/paddle/utils/layers_utils.py
  test/sot/test_sot_dynamic_shape.py
  test/sot/test_trace_list_arg.py
Labels: contributor

#67917 [fluid_ops] partial_allgather process_group
  paddle/phi/kernels/gpu/partial_allgather_kernel.cu
Labels: contributor

#67976 【complex op No.47】sinh_coo/sinh_csr(sparse)
  paddle/phi/kernels/sparse/cpu/unary_grad_kernel.cc
  paddle/phi/kernels/sparse/cpu/unary_kernel.cc
  paddle/phi/kernels/sparse/gpu/unary_grad_kernel.cu
  paddle/phi/kernels/sparse/gpu/unary_kernel.cu
  paddle/phi/kernels/sparse/impl/unary_kernel_impl.h
  python/paddle/sparse/unary.py
  test/legacy_test/test_sparse_unary_op.py
Labels: contributor, HappyOpenSource

#67994 易用性提升已修改的58个API核对 - part2
  python/paddle/__init__.py
  python/paddle/tensor/linalg.py
Labels: contributor

#67995 [auto parallel] make some auto_parallel uts deprecated
  test/collective/fleet/CMakeLists.txt
  test/collective/fleet/testslist.csv
  test/deprecated/collective/fleet/CMakeLists.txt
  test/deprecated/collective/fleet/auto_parallel_parallelizer_deprecated.py
  test/deprecated/collective/fleet/test_auto_parallel_parallelizer_deprecated.py
  test/deprecated/standalone_executor/CMakeLists.txt
  test/deprecated/standalone_executor/test_standalone_cuda_graph_multi_stream_deprecated.py
  test/deprecated/standalone_executor/test_standalone_measure_real_op_cost_deprecated.py
  test/standalone_executor/CMakeLists.txt
  tools/parallel_UT_rule.py
  tools/windows/run_unittests.sh
Labels: contributor

#67503 [BUAA][Infer Symbolic Shape]add full_batch_size_like&temporal_shift&squared_l2_norm
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/unary_infer_sym.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/unary_infer_sym.h
  paddle/phi/ops/yaml/ops.yaml
Labels: contributor, HappyOpenSource Pro

#68012 make some auto_parallel uts deprecated
  test/auto_parallel/CMakeLists.txt
  test/deprecated/auto_parallel/CMakeLists.txt
  test/deprecated/auto_parallel/test_fp16_assign_deprecated.py
  test/deprecated/auto_parallel/test_fuse_adamw_pass_deprecated.py
  test/deprecated/auto_parallel/test_fused_linear_pass_deprecated.py
  test/deprecated/auto_parallel/test_group_operators_deprecated.py
  test/deprecated/auto_parallel/test_interface_deprecated.py
  test/deprecated/auto_parallel/test_lr_grad_clip_deprecated.py
  test/deprecated/auto_parallel/test_new_cost_model_deprecated.py
  test/deprecated/auto_parallel/test_parallel_tuner_deprecated.py
  test/deprecated/auto_parallel/test_parallel_tuner_full_deprecated.py
  test/deprecated/auto_parallel/test_parallel_tuner_predict_deprecated.py
  test/deprecated/auto_parallel/test_process_mesh_deprecated.py
  test/deprecated/auto_parallel/test_serialization_deprecated.py
  tools/gpups_test.sh
Labels: contributor

#68010 [XPU] fix unbind op ut
  test/xpu/test_unbind_op_xpu.py
Labels: XPU

#67861 【Infer Symbolic Shape No.208】[BUAA] Add masked_multihead_attention_ op
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/multiary_infer_sym.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/multiary_infer_sym.h
  paddle/phi/ops/yaml/ops.yaml
Labels: contributor, HappyOpenSource Pro

#67950 【Error Message】update error message in `paddle/cinn/ir/schedule/impl/{base.cc, storage.cc}`
  paddle/cinn/ir/schedule/impl/base.cc
  paddle/cinn/ir/schedule/impl/storage.cc
Labels: contributor, HappyOpenSource Pro

#67888 【Infer Symbolic Shape No.168】【BUAA】 Add partial sum op
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/unary_infer_sym.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/unary_infer_sym.h
  paddle/phi/ops/yaml/ops.yaml
Labels: contributor, HappyOpenSource Pro

#67884 【Infer Symbolic Shape No.92】【BUAA】 Add nll_loss op
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/multiary_infer_sym.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/multiary_infer_sym.h
  paddle/phi/ops/yaml/ops.yaml
Labels: contributor, HappyOpenSource Pro

#67875 【BUAA】【Infer Symbolic Shape】添加 weight_only_linear op的符号推导接口
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/multiary_infer_sym.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/multiary_infer_sym.h
  paddle/phi/ops/yaml/ops.yaml
Labels: contributor, HappyOpenSource Pro

#67826 [CINN] add `pool2d` op in `cinn_op_infer`
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/cinn_op_infer_sym.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/cinn_op_infer_sym.h
Labels: contributor

#68013 make some auto_parallel uts deprecated
  test/auto_parallel/CMakeLists.txt
  test/deprecated/auto_parallel/CMakeLists.txt
  test/deprecated/auto_parallel/recompute_pass_unittest_deprecated.py
  test/deprecated/auto_parallel/sharding_pass_unittest_deprecated.py
  test/deprecated/auto_parallel/test_align_tool_deprecated.py
  test/deprecated/auto_parallel/test_auto_conditional_block_deprecated.py
  test/deprecated/auto_parallel/test_base_cost_deprecated.py
  test/deprecated/auto_parallel/test_conditional_block_reshard_deprecated.py
  test/deprecated/auto_parallel/test_cost_interface_deprecated.py
  test/deprecated/auto_parallel/test_dist_embedding_deprecated.py
  test/deprecated/auto_parallel/test_dist_op_cost_deprecated.py
  test/deprecated/auto_parallel/test_dist_pnorm_deprecated.py
  test/deprecated/auto_parallel/test_dist_reshape_deprecated.py
  test/deprecated/auto_parallel/test_dist_saver_deprecated.py
  test/deprecated/auto_parallel/test_dist_shape_deprecated.py
  test/deprecated/auto_parallel/test_dist_slice_deprecated.py
  test/deprecated/auto_parallel/test_dist_split_deprecated.py
  test/deprecated/auto_parallel/test_engine_api_error_deprecated.py
  test/deprecated/auto_parallel/test_engine_callbacks_deprecated.py
  test/deprecated/auto_parallel/test_engine_save_load_deprecated.py
  test/deprecated/auto_parallel/test_pass_recompute_deprecated.py
  test/deprecated/auto_parallel/test_pass_sharding_deprecated.py
Labels: contributor

#68005 [Error Message No. 4][BUAA] update 7 error message in paddle/cinn/ir/schedule/impl/for_type.cc
  paddle/cinn/ir/schedule/impl/for_type.cc
Labels: contributor, HappyOpenSource Pro

#67956 [Paddle TensorRT] add pd_op.max converter
  paddle/fluid/pir/transforms/tensorrt/trt_op_marker_pass.cc
  python/paddle/tensorrt/impls/math.py
  test/tensorrt/CMakeLists.txt
  test/tensorrt/test_converter_math.py
Labels: contributor

#65939 【Hackathon 6th Fundable Projects 3 No.227】 [fluid_ops] matmul
  paddle/fluid/operators/matmul_op.cc
  paddle/fluid/operators/matmul_op_xpu.cc
  paddle/fluid/operators/onednn/matmul_onednn_op.cc
  paddle/fluid/operators/ops_signature/legacy_matmul_sig.cc
  paddle/fluid/pir/dialect/op_generator/ops_api_gen.py
  paddle/phi/core/compat/op_utils.h
  paddle/phi/kernels/cpu/matmul_grad_kernel.cc
  paddle/phi/kernels/cpu/matmul_kernel.cc
  paddle/phi/kernels/gpu/matmul_grad_kernel.cu
  paddle/phi/kernels/gpu/matmul_kernel.cu
  paddle/phi/kernels/impl/matmul_grad_kernel_impl.h
  paddle/phi/kernels/impl/matmul_kernel_impl.h
  paddle/phi/kernels/onednn/matmul_grad_kernel.cc
  paddle/phi/kernels/onednn/matmul_kernel.cc
  paddle/phi/kernels/onednn/scale_kernel.cc
  paddle/phi/kernels/xpu/matmul_grad_kernel.cc
  paddle/phi/kernels/xpu/matmul_kernel.cc
  paddle/phi/ops/yaml/inconsistent/onednn_ops_extra.yaml
  paddle/phi/ops/yaml/inconsistent/static_backward.yaml
  paddle/phi/ops/yaml/inconsistent/static_ops.yaml
  paddle/phi/ops/yaml/op_compat.yaml
  test/legacy_test/test_matmul_op_with_head.py
Labels: PaddlePaddle Hackathon, contributor

#67911 Clean phi::ErrorSummary [fluid_ops]
  paddle/common/errors.h
Labels: contributor, HappyOpenSource

#67900 Modify include in platform/tensorrt/ [fluid_ops]
  paddle/fluid/platform/tensorrt/trt_plugin.h
  paddle/fluid/platform/tensorrt/trt_plugin_utils.h
Labels: contributor

#68015 【Infer Symbolic Shape No.177】Add TraceOpInferSymbolicShape implementation
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/unary_infer_sym.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/unary_infer_sym.h
  paddle/phi/ops/yaml/ops.yaml
Labels: contributor, HappyOpenSource

#67790 [Prim][PIR] Support the dynamic shape for batch_norm_grad
  paddle/fluid/primitive/rule/vjp/details.h
  python/paddle/autograd/backward_utils.py
  test/prim/pir_prim/test_prim_sub_graph_abcde_backward_dynamic_shape.py
  test/prim/pir_prim/test_prim_sub_graph_backward_dynamic_shape.py
Labels: contributor

#67965 [Prim][PIR] Support the dynamic shape for cumprod_grad op
  paddle/fluid/primitive/rule/vjp/details.h
  python/paddle/autograd/backward_utils.py
  test/prim/pir_prim/test_prim_sub_graph_abcde_backward_dynamic_shape.py
Labels: contributor

#67953 [fluid_ops] class_center_sample process_group
  paddle/phi/kernels/gpu/class_center_sample_kernel.cu
Labels: PaddlePaddle Hackathon, contributor

#67948 [fluid_ops] process_group revert
  paddle/fluid/distributed/collective/CMakeLists.txt
  paddle/fluid/distributed/collective/async_load.cc
  paddle/fluid/distributed/collective/async_load.h
  paddle/fluid/distributed/collective/bkcl_tools.cc
  paddle/fluid/distributed/collective/bkcl_tools.h
  paddle/fluid/distributed/collective/common.cc
  paddle/fluid/distributed/collective/common.h
  paddle/fluid/distributed/collective/custom_ccl_tools.cc
  paddle/fluid/distributed/collective/custom_ccl_tools.h
  paddle/fluid/distributed/collective/gloo_send_recv.cc
  paddle/fluid/distributed/collective/gloo_send_recv.h
  paddle/fluid/distributed/collective/mpi_tools.cc
  paddle/fluid/distributed/collective/mpi_tools.h
  paddle/fluid/distributed/collective/process_group.cc
  paddle/fluid/distributed/collective/process_group.h
  paddle/fluid/distributed/collective/process_group_bkcl.cc
  paddle/fluid/distributed/collective/process_group_bkcl.h
  paddle/fluid/distributed/collective/process_group_custom.cc
  paddle/fluid/distributed/collective/process_group_custom.h
  paddle/fluid/distributed/collective/process_group_gloo.cc
  paddle/fluid/distributed/collective/process_group_gloo.h
  paddle/fluid/distributed/collective/process_group_mpi.cc
  paddle/fluid/distributed/collective/process_group_mpi.h
  paddle/fluid/distributed/collective/process_group_nccl.cc
  paddle/fluid/distributed/collective/process_group_nccl.h
  paddle/fluid/distributed/collective/process_group_with_stream.h
  paddle/fluid/distributed/collective/process_group_without_stream.h
  paddle/fluid/distributed/collective/processgroup_comm_utils.cc
  paddle/fluid/distributed/collective/reducer.h
  paddle/fluid/operators/CMakeLists.txt
  paddle/fluid/pybind/CMakeLists.txt
  paddle/fluid/pybind/distributed_py.cc
  paddle/phi/core/distributed/collective/CMakeLists.txt
  paddle/phi/core/distributed/collective/process_group.h
  paddle/phi/core/distributed/collective/process_group_nccl.h
Labels: PaddlePaddle Hackathon, contributor

#68003 [Error Message No. 5][BUAA]update 25 error message in `paddle/cinn/ir/schedule/impl/loop_transformation.cc`
  paddle/cinn/ir/schedule/impl/loop_transformation.cc
Labels: contributor, HappyOpenSource Pro

#67916 [CINN] fix `axis` bug in `unsqueeze` op
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/unary_infer_sym.cc
Labels: contributor

#67841 add illustration for expand_as API
  python/paddle/tensor/manipulation.py
Labels: contributor, HappyOpenSource

#68044 [BUAA][Infer Symbolic Shape]Add Seed
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/nullary_infer_sym.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/nullary_infer_sym.h
  paddle/phi/ops/yaml/inconsistent/static_ops.yaml
Labels: contributor, HappyOpenSource Pro

#67687 Replace mkldnn_white_list to onednn_white_list [fluid_ops]
  paddle/fluid/framework/operator.cc
  paddle/fluid/imperative/prepared_operator.cc
  paddle/fluid/platform/onednn_op_list.h
Labels: contributor, HappyOpenSource

#68017 【Infer Symbolic Shape BUAA No.221】Add sequence_pool op
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/unary_infer_sym.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/unary_infer_sym.h
  paddle/phi/ops/yaml/ops.yaml
Labels: contributor, HappyOpenSource Pro

#67968 [Prim][PIR] Support the dynamic shape for gather_grad op and gather_nd_grad op
  paddle/fluid/primitive/rule/vjp/details.h
  python/paddle/autograd/backward_utils.py
  test/prim/pir_prim/test_prim_sub_graph_fghij_backward_dynamic_shape.py
Labels: contributor

#67947 Optimizer API's attr `weight_decay` support int 易用性提升
  python/paddle/optimizer/adadelta.py
  python/paddle/optimizer/adagrad.py
  python/paddle/optimizer/adam.py
  python/paddle/optimizer/adamax.py
  python/paddle/optimizer/adamw.py
  python/paddle/optimizer/asgd.py
  python/paddle/optimizer/optimizer.py
  test/legacy_test/test_adadelta_op.py
  test/legacy_test/test_adagrad_op_v2.py
  test/legacy_test/test_adam_op.py
  test/legacy_test/test_adamax_api.py
  test/legacy_test/test_adamw_op.py
  test/legacy_test/test_asgd_op.py
Labels: contributor

#68069 【Infer Symbolic Shape BUAA No.155】Add matrix_rank op
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/unary_infer_sym.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/unary_infer_sym.h
  paddle/phi/ops/yaml/ops.yaml
Labels: contributor, HappyOpenSource Pro

#68157 [XPU] use non fusion logsumexp impl to normalize input for numeric st…
  paddle/phi/backends/xpu/xpu3_op_list.cc
  paddle/phi/kernels/xpu/activation_kernel.cc
  paddle/phi/kernels/xpu/logsumexp_kernel.cc
  test/xpu/test_activation_op_xpu.py
Labels: XPU

#68078 [Dy2St] Optimize `bool(Value)` error messages
  python/paddle/pir/math_op_patch.py
Labels: contributor

#68168 [Prim][PIR] Support dynamic shape for scatter_grad and add the comp detection for all the backward dynamic shape test case
  paddle/fluid/primitive/codegen/gen.py
  paddle/fluid/primitive/rule/vjp/details.h
  python/paddle/autograd/backward_utils.py
  test/prim/pir_prim/CMakeLists.txt
  test/prim/pir_prim/test_prim_sub_graph_abcde_backward_dynamic_shape.py
  test/prim/pir_prim/test_prim_sub_graph_backward_dynamic_shape.py
  test/prim/pir_prim/test_prim_sub_graph_dynamic_shape.py
  test/prim/pir_prim/test_prim_sub_graph_fghij_backward_dynamic_shape.py
  test/prim/pir_prim/test_prim_sub_graph_klmno_backward_dynamic_shape.py
  test/prim/pir_prim/test_prim_sub_graph_pqrst_backward_dynamic_shape.py
  test/prim/pir_prim/test_prim_sub_graph_uvwxyz_backward_dynamic_shape.py
Labels: contributor

#68108 Fix matrix_rank_atol_rtol kernel when `rtol = None` 易用性提升
  paddle/phi/kernels/cpu/matrix_rank_tol_kernel.cc
  paddle/phi/kernels/gpu/matrix_rank_tol_kernel.cu
  test/legacy_test/test_matrix_rank_atol_rtol_op.py
Labels: contributor

#68098 [CINN] 【Infer Symbolic Shape BUAA 】Add Frobenius_norm op
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/unary_infer_sym.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/unary_infer_sym.h
  paddle/phi/ops/yaml/ops.yaml
Labels: contributor, HappyOpenSource Pro

#68033 Optimizer API's attr `weight_decay` support int 易用性提升 - part2
  python/paddle/optimizer/lbfgs.py
  python/paddle/optimizer/momentum.py
  python/paddle/optimizer/nadam.py
  python/paddle/optimizer/radam.py
  python/paddle/optimizer/rmsprop.py
  python/paddle/optimizer/sgd.py
  test/legacy_test/test_momentum_op.py
  test/legacy_test/test_nadam_op.py
  test/legacy_test/test_radam_op.py
  test/legacy_test/test_rmsprop_op.py
  test/legacy_test/test_sgd_op.py
Labels: contributor

#68057 [PIR][oneDNN] Fix bf16 quantization for cast
  paddle/fluid/pir/transforms/onednn/cpu_bfloat16_pass.cc
  paddle/fluid/pir/transforms/onednn/cpu_bfloat16_placement_pass.cc
  paddle/fluid/pir/transforms/onednn/cpu_bfloat16_type_placement_pass.cc
  paddle/fluid/pir/transforms/onednn/onednn_placement_pass.cc
  paddle/fluid/pir/transforms/onednn/shuffle_channel_detect_pass.cc
  paddle/phi/ops/yaml/inconsistent/onednn_ops_extra.yaml
  test/ir/pir/fused_pass/onednn/test_cpu_bfloat16_pir_pass.py
Labels: Intel, contributor

#68021 [PIR][OneDNN] Add cpu bf16 placement pass check data type
  paddle/fluid/pir/transforms/onednn/cpu_bfloat16_placement_pass.cc
Labels: Intel, contributor

#67872 [AutoParallel] Distributed Unit Test Handling - Part 3
  test/auto_parallel/CMakeLists.txt
  test/deprecated/auto_parallel/CMakeLists.txt
  test/deprecated/auto_parallel/auto_parallel_relaunch_model.py
  test/deprecated/auto_parallel/engine_api_deprecated.py
  test/deprecated/auto_parallel/engine_api_dp_deprecated.py
  test/deprecated/auto_parallel/launch.py
  test/deprecated/auto_parallel/optimization_tuner_api_deprecated.py
  test/deprecated/auto_parallel/pipeline_scheduler_zb_unittest_deprecated.py
  test/deprecated/auto_parallel/recompute_pass_unittest_deprecated.py
  test/deprecated/auto_parallel/test_auto_parallel_relaunch_deprecated.py
  test/deprecated/auto_parallel/test_auto_tuner_compare_deprecated.py
  test/deprecated/auto_parallel/test_auto_tuner_deprecated.py
  test/deprecated/auto_parallel/test_engine_api_deprecated.py
  test/deprecated/auto_parallel/test_engine_api_dp_deprecated.py
  test/deprecated/auto_parallel/test_mp_allreduce_matmul_grad_overlapping_deprecated.py
  test/deprecated/auto_parallel/test_optimization_tuner_api_deprecated.py
  test/deprecated/auto_parallel/test_relaunch_with_planner_deprecated.py
Labels: contributor

#68076 [Prim][PIR] Add the dynamic shape test case for unsqueeze_grad ans squeeze_grad
  python/paddle/autograd/backward_utils.py
  test/prim/pir_prim/test_prim_sub_graph_abcde_backward_dynamic_shape.py
  test/prim/pir_prim/test_prim_sub_graph_pqrst_backward_dynamic_shape.py
  test/prim/pir_prim/test_prim_sub_graph_uvwxyz_backward_dynamic_shape.py
Labels: contributor

#68093 Clean memcpy_h2d kernel [fluid_ops]
  paddle/fluid/operators/memcpy_h2d_op.cc
Labels: contributor

#68092 Clean memcpy_d2h kernel [fluid_ops]
  paddle/fluid/operators/memcpy_d2h_op.cc
Labels: contributor

#68058 Clean feed_sparse_coo_tensor kernel [fluid_ops]
  paddle/fluid/operators/controlflow/feed_op.cc
Labels: contributor

#67564 Move test in platform/device/gpu to test/cpp [fluid_ops]
  paddle/fluid/platform/device/gpu/CMakeLists.txt
  paddle/fluid/platform/device/gpu/cuda/CMakeLists.txt
  test/cpp/fluid/platform/device/CMakeLists.txt
  test/cpp/fluid/platform/device/gpu/CMakeLists.txt
  test/cpp/fluid/platform/device/gpu/cuda/CMakeLists.txt
  test/cpp/fluid/platform/device/gpu/cuda/cudnn_helper_test.cc
  test/cpp/fluid/platform/device/gpu/cuda_helper_test.cu
  test/cpp/fluid/platform/device/gpu/cudnn_desc_test.cc
  test/cpp/fluid/platform/device/gpu/rocm/CMakeLists.txt
  test/cpp/fluid/platform/device/gpu/rocm/miopen_helper_test.cc
Labels: contributor

#66558 remove memory optimize pass
  paddle/fluid/framework/CMakeLists.txt
  paddle/fluid/framework/compiled_program.cc
  paddle/fluid/framework/details/CMakeLists.txt
  paddle/fluid/framework/details/share_tensor_buffer_functor.cc
  paddle/fluid/framework/details/share_tensor_buffer_functor.h
  paddle/fluid/framework/details/share_tensor_buffer_op_handle.cc
  paddle/fluid/framework/details/share_tensor_buffer_op_handle.h
  paddle/fluid/framework/ir/memory_optimize_pass/CMakeLists.txt
  paddle/fluid/framework/ir/memory_optimize_pass/buffer_shared_cross_op_memory_reuse_pass.cc
  paddle/fluid/framework/ir/memory_optimize_pass/buffer_shared_inplace_op_pass.cc
  paddle/fluid/framework/ir/memory_optimize_pass/inplace_addto_op_pass.cc
  paddle/fluid/framework/ir/memory_optimize_pass/memory_reuse_pass.cc
  paddle/fluid/framework/ir/memory_optimize_pass/memory_reuse_pass.h
  paddle/fluid/framework/ir/memory_optimize_pass/op_graph_view.cc
  paddle/fluid/framework/ir/memory_optimize_pass/op_graph_view.h
  paddle/fluid/framework/ir/memory_optimize_pass/reference_count_pass.cc
  paddle/fluid/framework/new_executor/pir_interpreter.cc
  paddle/fluid/framework/new_executor/program_interpreter.cc
  paddle/fluid/framework/new_executor/program_interpreter.h
  python/paddle/base/executor.py
  python/paddle/distributed/passes/__init__.py
  python/paddle/distributed/passes/cpp_pass.py
  python/paddle/framework/ir.py
  python/paddle/jit/dy2static/partial_program.py
  test/cpp/fluid/framework/CMakeLists.txt
  test/cpp/fluid/framework/ir/CMakeLists.txt
  test/cpp/fluid/framework/ir/memory_optimize_pass/CMakeLists.txt
  test/cpp/fluid/framework/ir/memory_optimize_pass/test_reference_count_pass_last_lived_ops.cc
  test/deprecated/legacy_test/test_apply_pass_to_program_deprecated.py
Labels: PaddlePaddle Hackathon, contributor

#68177 [CINN] 【Infer Symbolic Shape BUAA 】Add match_matrix_tensor op
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/multiary_infer_sym.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/multiary_infer_sym.h
  paddle/phi/ops/yaml/ops.yaml
Labels: contributor, HappyOpenSource Pro

#67663 【Infer Symbolic Shape No.230】【BUAA】Add stft, changed 3 files
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/binary_infer_sym.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/binary_infer_sym.h
  paddle/phi/ops/yaml/ops.yaml
Labels: contributor, HappyOpenSource Pro

#67664 【Infer Symbolic Shape No.232】【BUAA】Add svd, changed 3 files
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/unary_infer_sym.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/unary_infer_sym.h
  paddle/phi/ops/yaml/ops.yaml
Labels: contributor, HappyOpenSource Pro

#67434 【Infer Symbolic Shape No.17】【BUAA】Add ClassCenterSample, changed 4 files
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/unary_infer_sym.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/unary_infer_sym.h
  paddle/phi/infermeta/unary.cc
  paddle/phi/ops/yaml/ops.yaml
  test/legacy_test/test_class_center_sample_op.py
Labels: contributor, HappyOpenSource Pro

#68096 【Infer Symbolic Shape No.15】Add LruOpInferSymbolicShape implementation
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/unary_infer_sym.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/unary_infer_sym.h
  paddle/phi/ops/yaml/inconsistent/static_ops.yaml
Labels: contributor, HappyOpenSource

#68102 [CINN] 【Infer Symbolic Shape】Add cinn_op.uniform_random op
  paddle/cinn/hlir/dialect/operator/ir/ops.yaml
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/cinn_op_infer_sym.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/cinn_op_infer_sym.h
Labels: contributor, HappyOpenSource Pro

#67951 [CINN]【Infer Symbolic Shape 】Add pyramid_hash op
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/multiary_infer_sym.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/multiary_infer_sym.h
  paddle/phi/ops/yaml/ops.yaml
Labels: contributor

#67910 【pir_save_load】support pir for jit_layer
  paddle/fluid/jit/engine/pir_interpreter_engine.cc
  paddle/fluid/jit/engine/pir_interpreter_engine.h
  paddle/fluid/jit/function_schema.cc
  paddle/fluid/jit/function_schema.h
  paddle/fluid/jit/function_utils.cc
  paddle/fluid/jit/function_utils.h
  paddle/fluid/jit/layer.cc
  paddle/fluid/jit/layer.h
  paddle/fluid/jit/serializer.cc
  paddle/fluid/jit/serializer.h
  paddle/fluid/pybind/jit.cc
  test/legacy_test/test_jit_layer.py
Labels: contributor

#68228 [Prim][PIR] Support the dynamic shape for topk_grad
  paddle/fluid/primitive/rule/vjp/details.h
  python/paddle/autograd/backward_utils.py
  test/prim/pir_prim/test_prim_sub_graph_pqrst_backward_dynamic_shape.py
Labels: contributor

#68193 [PIR][oneDNN] Optimize Fc InferMeta
  paddle/phi/infermeta/fusion.cc
  paddle/phi/infermeta/fusion.h
  paddle/phi/ops/yaml/inconsistent/onednn_ops_extra.yaml
  paddle/phi/ops/yaml/inconsistent/onednn_static.yaml
Labels: Intel, contributor

#68272 [Prim][PIR] Add the dynamic shape test case for roll_grad
  python/paddle/autograd/backward_utils.py
  test/prim/pir_prim/test_prim_sub_graph_pqrst_backward_dynamic_shape.py
Labels: contributor

#68132 [OneDNN][PIR] Fix vit model fail for matmul op
  paddle/fluid/pir/transforms/onednn/cpu_bfloat16_pass.cc
  test/ir/pir/fused_pass/onednn/test_cpu_bfloat16_pir_pass.py
Labels: Intel, contributor

#67818 【Infer Symbolic Shape No.176】【BUAA】Add unpool op
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/binary_infer_sym.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/binary_infer_sym.h
  paddle/phi/ops/yaml/ops.yaml
Labels: contributor, HappyOpenSource Pro

#68261 【complex op No.39】atanh_coo/atanh_csr(sparse)
  paddle/phi/kernels/sparse/cpu/unary_grad_kernel.cc
  paddle/phi/kernels/sparse/cpu/unary_kernel.cc
  paddle/phi/kernels/sparse/gpu/unary_grad_kernel.cu
  paddle/phi/kernels/sparse/gpu/unary_kernel.cu
  paddle/phi/kernels/sparse/impl/unary_kernel_impl.h
  python/paddle/sparse/unary.py
  test/legacy_test/test_sparse_unary_op.py
Labels: contributor, HappyOpenSource

#68046 Unpool/Unpool3d kernel support input of int64 `indices` 易用性提升
  paddle/phi/kernels/cpu/unpool_grad_kernel.cc
  paddle/phi/kernels/cpu/unpool_kernel.cc
  paddle/phi/kernels/gpu/unpool_grad_kernel.cu
  paddle/phi/kernels/gpu/unpool_kernel.cu
  python/paddle/nn/functional/pooling.py
  test/legacy_test/test_unpool_indices.py
Labels: contributor

#68266 Move test in fluid/platform to test/cpp [fluid_ops]
  paddle/fluid/platform/CMakeLists.txt
  test/cpp/fluid/platform/CMakeLists.txt
  test/cpp/fluid/platform/bfloat16_test.cc
  test/cpp/fluid/platform/bfloat16_test.cu
  test/cpp/fluid/platform/complex_test.cc
  test/cpp/fluid/platform/complex_test.cu
  test/cpp/fluid/platform/cpu_helper_test.cc
  test/cpp/fluid/platform/cpu_info_test.cc
  test/cpp/fluid/platform/device_code_test.cc
  test/cpp/fluid/platform/device_context_test.cu
  test/cpp/fluid/platform/device_context_test_cuda_graph.cu
  test/cpp/fluid/platform/device_context_xpu_test.cc
  test/cpp/fluid/platform/device_event_test.cc
  test/cpp/fluid/platform/enforce_test.cc
  test/cpp/fluid/platform/errors_test.cc
  test/cpp/fluid/platform/float16_test.cc
  test/cpp/fluid/platform/float16_test.cu
  test/cpp/fluid/platform/init_phi_test.cc
  test/cpp/fluid/platform/init_test.cc
  test/cpp/fluid/platform/lodtensor_printer_test.cc
  test/cpp/fluid/platform/os_info_test.cc
  test/cpp/fluid/platform/place_test.cc
  test/cpp/fluid/platform/profiler_test.cc
  test/cpp/fluid/platform/test_limit_gpu_memory.cu
  test/cpp/fluid/platform/timer_test.cc
Labels: contributor, HappyOpenSource

#67957 [CINN] 【Infer Symbolic Shape BUAA 】Add crop op
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/unary_infer_sym.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/unary_infer_sym.h
  paddle/phi/ops/yaml/ops.yaml
  test/legacy_test/test_crop_tensor_op.py
Labels: contributor

#68208 【Infer Symbolic Shape No.105】Add Slogdet implementation
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/same_operands_result.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/same_operands_result.h
  paddle/phi/ops/yaml/ops.yaml
Labels: contributor, HappyOpenSource

#68095 [PIR][oneDNN] Optimize onednn_placement_pass
  paddle/fluid/pir/transforms/onednn/onednn_placement_pass.cc
  test/ir/pir/fused_pass/onednn/test_onednn_placement.py
Labels: Intel, contributor

#68295 [Prim][PIR] Support the dynamic shape for one_hot op
  paddle/fluid/primitive/base/decomp_trans.cc
  paddle/fluid/primitive/composite/composite.h
  test/prim/pir_prim/test_prim_sub_graph_dynamic_shape.py
Labels: contributor

#68326 【complex op No.36-38,41,42,49,51】asin_coo/asin_csr(sparse),asinh_coo/asinh_csr(sparse),atan_coo/atan_csr(sparse),expm1_coo/expm1_csr(sparse),log1p_coo/log1p_csr(sparse),square_coo/square_csr(sparse),tanh_coo/tanh_csr(sparse)
  paddle/phi/kernels/sparse/cpu/unary_grad_kernel.cc
  paddle/phi/kernels/sparse/cpu/unary_kernel.cc
  paddle/phi/kernels/sparse/gpu/unary_grad_kernel.cu
  paddle/phi/kernels/sparse/gpu/unary_kernel.cu
  paddle/phi/kernels/sparse/impl/unary_kernel_impl.h
  python/paddle/sparse/unary.py
  test/legacy_test/test_sparse_unary_op.py
Labels: contributor

#64999 【Hackathon 6th Fundable Projects 3 No.221】[fluid_ops] lookup_table
  paddle/fluid/operators/lookup_table_op.cc
  paddle/fluid/operators/lookup_table_op.cu
  paddle/fluid/operators/lookup_table_op.h
  paddle/fluid/operators/ops_signature/lookup_table_sig.cc
  paddle/fluid/pir/dialect/op_generator/ops_api_gen.py
  paddle/phi/infermeta/binary.cc
  paddle/phi/infermeta/binary.h
  paddle/phi/kernels/cpu/lookup_table_grad_kernel.cc
  paddle/phi/kernels/cpu/lookup_table_kernel.cc
  paddle/phi/kernels/gpu/lookup_table_grad_kernel.cu
  paddle/phi/kernels/gpu/lookup_table_kernel.cu
  paddle/phi/kernels/selected_rows/cpu/lookup_table_grad_kernel.cc
  paddle/phi/kernels/selected_rows/cpu/lookup_table_kernel.cc
  paddle/phi/kernels/selected_rows/gpu/lookup_table_grad_kernel.cu
  paddle/phi/kernels/selected_rows/gpu/lookup_table_kernel.cu
  paddle/phi/ops/yaml/inconsistent/static_backward.yaml
  paddle/phi/ops/yaml/inconsistent/static_ops.yaml
  paddle/phi/ops/yaml/op_compat.yaml
  test/cpp/new_executor/standalone_executor_test.cc
Labels: PaddlePaddle Hackathon, contributor

#67928 【Hackathon 6th Fundable Projects 3 No.163】 [fluid_ops] fused_seqpool_cvm
  paddle/fluid/operators/fused/fused_seqpool_cvm_op.cc
  paddle/fluid/operators/fused/fused_seqpool_cvm_op.cu
  paddle/fluid/operators/fused/fused_seqpool_cvm_op.h
  paddle/fluid/pir/dialect/op_generator/ops_api_gen.py
  paddle/phi/infermeta/fusion.cc
  paddle/phi/infermeta/fusion.h
  paddle/phi/kernels/fusion/cpu/fused_seqpool_cvm_grad_kernel.cc
  paddle/phi/kernels/fusion/cpu/fused_seqpool_cvm_kernel.cc
  paddle/phi/kernels/fusion/gpu/fused_seqpool_cvm_grad_kernel.cu
  paddle/phi/kernels/fusion/gpu/fused_seqpool_cvm_kernel.cu
  paddle/phi/ops/yaml/fused_backward.yaml
  paddle/phi/ops/yaml/fused_ops.yaml
  paddle/phi/ops/yaml/op_compat.yaml
Labels: PaddlePaddle Hackathon, contributor

#66673 Fix pipileInfo pipeLineInfo
  tools/CrossStackProfiler/CspReporter.py
  tools/CrossStackProfiler/NetFileReader.py
  tools/get_pr_ut.py
  tools/get_single_test_cov.py
  tools/get_ut_file_map.py
Labels: contributor, HappyOpenSource

#67889 【Infer Symbolic Shape No.170】【BUAA】 Add read_file op
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/nullary_infer_sym.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/nullary_infer_sym.h
  paddle/phi/ops/yaml/ops.yaml
Labels: contributor, HappyOpenSource Pro

#68311 Clean pull_box_sparse_op.kps [fluid_ops]
  paddle/fluid/operators/pull_box_sparse_op.kps
Labels: contributor, HappyOpenSource

#68353 [Prim][PIR] Support dynamic shape for batch_norm and batch_norm_ op
  paddle/fluid/primitive/base/decomp_trans.cc
  paddle/fluid/primitive/composite/composite.h
  test/prim/pir_prim/test_prim_sub_graph_dynamic_shape.py
Labels: contributor

#68294 【Hackathon 7th No.18】为稀疏计算添加复数支持 -part
  paddle/phi/kernels/cpu/activation_kernel.cc
  paddle/phi/kernels/sparse/cpu/elementwise_grad_kernel.cc
  paddle/phi/kernels/sparse/cpu/elementwise_kernel.cc
  paddle/phi/kernels/sparse/gpu/elementwise_grad_kernel.cu
  paddle/phi/kernels/sparse/gpu/elementwise_kernel.cu
  test/legacy_test/test_sparse_elementwise_op.py
Labels: PaddlePaddle Hackathon, contributor

#68320 【Error Message No. 3】update 8 error message in paddle\cinn\ir\schedule\impl\compute_location.cc
  paddle/cinn/ir/schedule/impl/compute_location.cc
Labels: contributor, HappyOpenSource

#68358 Clean beam_search_decode_op_xpu.h [fluid_ops]
  paddle/fluid/operators/beam_search_decode_op_xpu.h
  test/xpu/cpp/beam_search_decode_op_xpu_test.cc
Labels: contributor, HappyOpenSource

#68312 Clean mp_allreduce_sum_op_xpu [fluid_ops]
  paddle/fluid/operators/collective/c_allgather_op_xpu.cc
  paddle/fluid/operators/collective/c_embedding_op_xpu.cc
  paddle/fluid/operators/collective/mp_allreduce_sum_op.kps
  paddle/fluid/operators/collective/mp_allreduce_sum_op_xpu.cc
Labels: contributor, HappyOpenSource

#68206 Uniformly use Inplace to link Outplace documents
  python/paddle/tensor/manipulation.py
Labels: contributor, HappyOpenSource

#68166 [CINN] Add infer_symbol_shape for some ops
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/binary_infer_sym.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/binary_infer_sym.h
  paddle/phi/ops/yaml/ops.yaml
Labels: contributor, HappyOpenSource

#68158 REGISTER_IR_PASS for common_subexpression_elimination_pass.cc
  paddle/fluid/pir/transforms/general/common_subexpression_elimination_pass.cc
  paddle/fluid/pir/transforms/passes.h
Labels: contributor

#68169 [XPU] support several bf16 ops
  paddle/phi/backends/xpu/xpu3_op_list.cc
  paddle/phi/kernels/fusion/xpu/fused_gemm_epilogue_kernel.cc
  paddle/phi/kernels/legacy/xpu/elementwise_kernel.cc
  paddle/phi/kernels/xpu/add_n_kernel.cc
  paddle/phi/kernels/xpu/elementwise_kernel.cc
  paddle/phi/kernels/xpu/expand_as_kernel.cc
  test/xpu/test_elementwise_max_op_xpu.py
  test/xpu/test_elementwise_min_op_xpu.py
Labels: XPU

#68097 【Hackathon 6th Fundable Projects 3 No.212、307】 [fluid_ops] lod_reset、reshape
  paddle/fluid/operators/lod_reset_op.cc
  paddle/fluid/operators/lod_reset_op.cu
  paddle/fluid/operators/ops_signature/lod_reset_sig.cc
  paddle/fluid/operators/ops_signature/reshape_sig.cc
  paddle/fluid/operators/reshape_op.cc
  paddle/fluid/pir/dialect/op_generator/ops_api_gen.py
  paddle/phi/core/compat/op_utils.h
  paddle/phi/infermeta/backward.cc
  paddle/phi/infermeta/backward.h
  paddle/phi/infermeta/binary.cc
  paddle/phi/infermeta/binary.h
  paddle/phi/kernels/cpu/lod_reset_grad_kernel.cc
  paddle/phi/kernels/cpu/lod_reset_kernel.cc
  paddle/phi/kernels/gpu/lod_reset_grad_kernel.cu
  paddle/phi/kernels/gpu/lod_reset_kernel.cu
  paddle/phi/kernels/impl/lod_reset_kernel_impl.h
  paddle/phi/ops/yaml/inconsistent/static_backward.yaml
  paddle/phi/ops/yaml/inconsistent/static_ops.yaml
  paddle/phi/ops/yaml/op_compat.yaml
  test/legacy_test/test_get_all_op_or_kernel_names.py
  test/legacy_test/test_lod_reset_op.py
Labels: PaddlePaddle Hackathon, contributor

#68035 Simplify "phi::errors" to "errors" [fluid_ops]
  paddle/phi/infermeta/spmd_rules/moe_combine.cc
  paddle/phi/infermeta/spmd_rules/moe_gate_dispatch.cc
  paddle/phi/kernels/fusion/gpu/fused_gate_attention_kernel.cu
  paddle/phi/kernels/fusion/gpu/fused_multi_transformer_op.cu.h
  paddle/phi/kernels/gpu/matrix_rank_tol_kernel.cu
Labels: contributor, HappyOpenSource

#68214 F.pad `data_format` support automatic default format 易用性提升
  python/paddle/nn/functional/common.py
  test/legacy_test/test_pad3d_op.py
Labels: contributor

#67528 Clean operators/activation_op.h [fluid_ops]
  paddle/fluid/framework/op_compatible_info.cc
  paddle/fluid/operators/activation_op.cc
  paddle/fluid/operators/activation_op.cu.h
  paddle/fluid/operators/activation_op.h
  paddle/fluid/operators/fake_quantize_op.cc
  paddle/fluid/operators/fake_quantize_op.h
  paddle/fluid/operators/memcpy_d2h_op.cc
  paddle/fluid/operators/memcpy_d2h_op.h
  paddle/fluid/operators/memcpy_h2d_op.cc
  paddle/fluid/operators/memcpy_h2d_op.h
  python/paddle/incubate/layers/__init__.py
  python/paddle/incubate/layers/nn.py
Labels: contributor, HappyOpenSource

#68316 Clean deprecated_op_names [fluid_ops]
  paddle/phi/core/compat/op_utils.h
  paddle/phi/core/kernel_factory.cc
Labels: contributor

#68356 Clean sequence_enumerate sequence_erase [fluid_ops]
  python/paddle/nn/functional/loss.py
  python/paddle/static/nn/__init__.py
  python/paddle/static/nn/sequence_lod.py
  test/white_list/check_op_sequence_batch_1_input_white_list.py
  test/white_list/check_op_sequence_instance_0_input_white_list.py
  test/white_list/no_grad_set_white_list.py
  tools/parallel_UT_rule.py
  tools/static_mode_white_list.py
Labels: contributor, HappyOpenSource

#68328 [Dy2St] Optimize `int(Value)` and `float(Value)` error messages
  python/paddle/pir/math_op_patch.py
Labels: contributor

#68415 Fix `paddle.cast_` dtype convertion 易用性提升
  python/paddle/tensor/manipulation.py
  test/legacy_test/test_cast_op.py
Labels: contributor

#68427 【Error Message No. 6】update 2 error messages in paddle/cinn/ir/schedule/impl/reduction.cc
  paddle/cinn/ir/schedule/impl/reduction.cc
Labels: contributor, HappyOpenSource

#68419 【Error Message No. 284】 replace CHECK macros in paddle\cinn\adt\equation_solver.cc
  paddle/cinn/adt/equation_solver.cc
Labels: contributor, HappyOpenSource

#68418 [XPU] bind bf16 flatten and uint8 stack
  paddle/phi/backends/xpu/xpu3_op_list.cc
  paddle/phi/kernels/cpu/flatten2_grad_kernel.cc
  paddle/phi/kernels/cpu/flatten2_kernel.cc
  paddle/phi/kernels/flatten_grad_kernel.cc
  paddle/phi/kernels/flatten_kernel.cc
  paddle/phi/kernels/xpu/flatten2_grad_kernel.cc
  paddle/phi/kernels/xpu/flatten2_kernel.cc
  paddle/phi/kernels/xpu/stack_grad_kernel.cc
  paddle/phi/kernels/xpu/stack_kernel.cc
  test/xpu/test_flatten2_op_xpu.py
  test/xpu/test_flatten_contiguous_range_op_xpu.py
  test/xpu/test_stack_op_xpu.py
Labels: XPU

#68426 【Error Message No. 2】update 27 error messages in paddle\cinn\ir\schedule\impl\base.cc
  paddle/cinn/ir/schedule/impl/base.cc
Labels: contributor, HappyOpenSource

#68388 [XPU] Fix depthwise conv2d unit test
  test/xpu/test_depthwise_conv2d_op_xpu.py
Labels: XPU

#68019 [CINN] Add interface for check if block can merge
  paddle/cinn/optim/CMakeLists.txt
  paddle/cinn/optim/merge_block_utils.cc
  paddle/cinn/optim/merge_block_utils.h
  test/cpp/pir/cinn/adt/CMakeLists.txt
  test/cpp/pir/cinn/adt/merge_block_utils_test.cc
Labels: contributor

#68372 [Typing] bump `mypy` version to `1.11.2` and fix many typing errors in cinn binding
  paddle/scripts/paddle_build.sh
  python/paddle/base/backward.py
  python/paddle/base/framework.py
  python/paddle/static/io.py
  python/paddle/utils/dlpack.py
  python/setup.py.in
  python/unittest_py/requirements.txt
  setup.py
  tools/gen_pybind11_stub.py
Labels: contributor, HappyOpenSource

#68449 [OneDNN] Fix compiler error in clang build
  paddle/fluid/pir/transforms/onednn/cpu_bfloat16_pass.cc
Labels: Intel, contributor

#68152 Fix incorrect parameter replacing of PIR constant_folding_pass caused by stack op
  paddle/fluid/pir/transforms/general/constant_folding_pass.cc
Labels: contributor

#68403 Update tools/parallel_UT_rule.py [fluid_ops]
  test/white_list/op_accuracy_white_list.py
  test/white_list/op_threshold_white_list.py
  tools/final_ut_parallel_rule.py
  tools/parallel_UT_rule.py
  tools/static_mode_white_list.py
Labels: contributor

#68397 Clean LoDTensorArray [fluid_ops]
  paddle/fluid/framework/lod_tensor_array.h
Labels: contributor

#67972 添加vstack英文文档
  python/paddle/tensor/manipulation.py
Labels: contributor, HappyOpenSource

#68452 【Error Message No. 7】update 9 error messages in paddle/cinn/ir/schedule/impl/storage.cc
  paddle/cinn/ir/schedule/impl/storage.cc
Labels: contributor, HappyOpenSource

#67703 Fix test_trt_convert_layer_norm failure on TensorRT 10.3.0
  paddle/fluid/inference/tensorrt/engine.cc
  test/ir/inference/auto_scan_test.py
Labels: NVIDIA, contributor

#67973 添加flip英文文档
  python/paddle/tensor/manipulation.py
Labels: contributor, HappyOpenSource

#68213 [XPU] fix bf16 tensor print caused by new round mode
  python/paddle/tensor/to_string.py
Labels: XPU

#68458 【Error Message No. 10】update 3 error messages in paddle/cinn/ir/schedule/ir_schedule_util.cc
  paddle/cinn/ir/schedule/ir_schedule_util.cc
Labels: contributor, HappyOpenSource

#68433 [XPU], add bf16 unittest for rms_norm
  paddle/phi/backends/xpu/xpu2_op_list.cc
  paddle/phi/backends/xpu/xpu3_op_list.cc
  paddle/phi/infermeta/backward.cc
  paddle/phi/kernels/rms_norm_kernel.h
  test/xpu/test_rms_norm_op_xpu.py
Labels: XPU

#68454 [XPU], update bkcl to update tracehang
  cmake/external/xpu.cmake
Labels: XPU

#67897 [Docathon][Add API Legend No.23]Add legend for slice API
  python/paddle/tensor/manipulation.py
Labels: contributor, HappyOpenSource

#68404 【Hackathon 6th Fundable Projects 3 No.84】 [fluid_ops] data_norm
  paddle/fluid/operators/data_norm_op.cc
  paddle/fluid/operators/data_norm_op.cu
  paddle/fluid/operators/data_norm_op.h
  test/deprecated/collective/fleet/test_fleet_utils_deprecated.py
  test/deprecated/legacy_test/test_data_norm_op_deprecated.py
  test/deprecated/legacy_test/test_dist_fleet_ps2_deprecated.py
  test/deprecated/legacy_test/test_fleet_deprecated.py
  test/ipu/test_data_norm_op_ipu.py
  test/legacy_test/test_data_norm_op.py
Labels: PaddlePaddle Hackathon, contributor

#68441 Clean tensor_util.cu [fluid_ops]
  paddle/fluid/framework/tensor_util.cu
Labels: contributor, HappyOpenSource

#68464 Migrate timer.cc to phi [fluid_ops]
  paddle/fluid/distributed/ps/service/ps_client.h
  paddle/fluid/distributed/ps/table/common_graph_table.cc
  paddle/fluid/framework/CMakeLists.txt
  paddle/fluid/framework/data_feed.cc
  paddle/fluid/framework/data_feed.h
  paddle/fluid/framework/data_set.cc
  paddle/fluid/framework/device_worker.h
  paddle/fluid/framework/downpour_lite_worker.cc
  paddle/fluid/framework/downpour_worker.cc
  paddle/fluid/framework/downpour_worker_opt.cc
  paddle/fluid/framework/fleet/box_wrapper.h
  paddle/fluid/framework/fleet/heter_ps/heter_comm.h
  paddle/fluid/framework/fleet/metrics.h
  paddle/fluid/framework/fleet/ps_gpu_wrapper.cc
  paddle/fluid/framework/heter_section_worker.cc
  paddle/fluid/framework/heter_service.h
  paddle/fluid/framework/heter_util.h
  paddle/fluid/framework/hetercpu_worker.cc
  paddle/fluid/framework/hogwild_worker.cc
  paddle/fluid/framework/io/CMakeLists.txt
  paddle/fluid/framework/io/shell.cc
  paddle/fluid/framework/naive_executor.cc
  paddle/fluid/framework/new_executor/profiler.h
  paddle/fluid/framework/ps_gpu_worker.cc
  paddle/fluid/imperative/CMakeLists.txt
  paddle/fluid/imperative/tracer.cc
  paddle/fluid/inference/api/analysis_predictor.cc
  paddle/fluid/inference/api/api_impl.cc
  paddle/fluid/inference/api/onnxruntime_predictor.cc
  paddle/fluid/inference/io.cc
  paddle/fluid/platform/CMakeLists.txt
  paddle/fluid/platform/device/ipu/ipu_backend.h
  paddle/fluid/platform/init.cc
  paddle/fluid/pybind/compiled_program.cc
  paddle/fluid/pybind/place.cc
  paddle/fluid/pybind/pybind.cc
  paddle/fluid/pybind/tensor.cc
  paddle/phi/core/platform/CMakeLists.txt
  paddle/phi/core/platform/cpu_helper.cc
  paddle/phi/core/platform/cpu_helper.h
  paddle/phi/core/platform/denormal.cc
  paddle/phi/core/platform/denormal.h
  paddle/phi/core/platform/monitor.cc
  paddle/phi/core/platform/monitor.h
  paddle/phi/core/platform/timer.cc
  paddle/phi/core/platform/timer.h
  test/cpp/fluid/benchmark/op_tester.cc
  test/cpp/fluid/platform/CMakeLists.txt
  test/cpp/fluid/platform/cpu_helper_test.cc
  test/cpp/fluid/platform/timer_test.cc
  test/cpp/jit/layer_test.cc
Labels: contributor, HappyOpenSource

#68113 [SOT][dynamic shape] Fallback static shape all symvar
  python/paddle/jit/sot/opcode_translator/executor/function_graph.py
Labels: contributor

#68469 Migrate gpu_launch_config.h [fluid_ops]
  paddle/fluid/inference/tensorrt/plugin/deformable_conv_op_plugin.cu
  paddle/fluid/platform/device/gpu/cuda/cuda_profiler.h
  paddle/phi/core/platform/device/gpu/cuda/cuda_helper.h
  paddle/phi/core/platform/device/gpu/cuda/cusparse_helper.h
  paddle/phi/core/platform/device/gpu/gpu_helper.h
  paddle/phi/core/platform/device/gpu/gpu_launch_config.h
  paddle/phi/core/platform/device/gpu/rocm/rocm_helper.h
  test/cpp/fluid/platform/device/gpu/cuda_helper_test.cu
Labels: contributor

#68417 Clean feed_strings kernel [fluid_ops]
  paddle/fluid/operators/controlflow/feed_op.cc
  test/deprecated/tokenizer/test_faster_tokenizer_op_deprecated.py
Labels: contributor
