Repository PaddlePaddle/Paddle, pull requests merged in 2024-06, with the labels that each got.

#64817 [PIR] Split pd_op.cc and pd_op_bwd.cc
  paddle/fluid/pir/dialect/CMakeLists.txt
  paddle/fluid/pir/dialect/op_generator/op_gen.py
Labels: contributor

#63229 【complex op No.26】add complex support for inv
  paddle/fluid/platform/dynload/cublas.h
  paddle/phi/backends/dynload/cublas.h
  paddle/phi/kernels/cpu/inverse_grad_kernel.cc
  paddle/phi/kernels/cpu/inverse_kernel.cc
  paddle/phi/kernels/funcs/blas/blas_impl.cu.h
  paddle/phi/kernels/funcs/matrix_inverse.cc
  paddle/phi/kernels/funcs/matrix_inverse.cu
  paddle/phi/kernels/funcs/matrix_inverse.h
  paddle/phi/kernels/gpu/inverse_grad_kernel.cu
  paddle/phi/kernels/gpu/inverse_kernel.cu
  paddle/phi/kernels/impl/inverse_grad_kernel_impl.h
  python/paddle/tensor/math.py
  test/deprecated/legacy_test/test_inverse_op.py
Labels: contributor

#64240 [CINN] New tiling method optimized for warp-level continuous read
  paddle/cinn/ir/group_schedule/tactic/tile_first_general_tactic.cc
  paddle/cinn/optim/resize_buffer.cc
Labels: contributor

#64820 [Prim][PIR] fix slice op backward in prim pir
  paddle/fluid/prim/api/composite_backward/composite_backward_api.h
  paddle/fluid/primitive/rule/vjp/details.h
Labels: contributor

#64699 【Hackathon 6th Fundable Projects 3 No.85】decayed_adagrad
  paddle/fluid/operators/ops_signature/decayed_adagrad_sig.cc
  paddle/fluid/operators/optimizers/decayed_adagrad_op.cc
  paddle/phi/ops/yaml/inconsistent/static_ops.yaml
  paddle/phi/ops/yaml/ops.yaml
Labels: PaddlePaddle Hackathon, contributor

#64693 【Hackathon 6th Fundable Projects 3 No.58】channel_shuffle
  paddle/fluid/operators/channel_shuffle_op.cc
  paddle/fluid/operators/ops_signature/channel_shuffle_sig.cc
  paddle/phi/ops/yaml/legacy/backward_exclude.yaml
  paddle/phi/ops/yaml/legacy/ops_exclude.yaml
Labels: PaddlePaddle Hackathon, contributor

#64752 【Error Message No.14】Replace paddle/cinn/backends/*
  paddle/cinn/backends/codegen_c.cc
  paddle/cinn/backends/codegen_c_x86.cc
  paddle/cinn/backends/codegen_c_x86.h
  paddle/cinn/backends/codegen_cuda_dev.cc
  paddle/cinn/backends/codegen_cuda_host.cc
  paddle/cinn/backends/codegen_device_util.h
  paddle/cinn/backends/function_prototype.cc
  paddle/cinn/backends/ir_schedule_test.cc
  paddle/cinn/backends/llvm/codegen_llvm.cc
  paddle/cinn/backends/llvm/codegen_llvm_test.cc
  paddle/cinn/backends/llvm/codegen_x86.cc
  paddle/cinn/backends/llvm/execution_engine_test.cc
  paddle/cinn/backends/llvm/llvm_intrin_rule.h
  paddle/cinn/backends/llvm/runtime_symbol_registry.cc
  paddle/cinn/backends/modular.cc
  paddle/cinn/backends/nvrtc/header_generator.cc
  paddle/cinn/backends/nvrtc/nvrtc_util.cc
Labels: contributor, HappyOpenSource

#64733 【Error Message No.13】Replace paddle/cinn/auto_schedule/*
  paddle/cinn/auto_schedule/analysis/analyze_ir.cc
  paddle/cinn/auto_schedule/auto_tuner.cc
  paddle/cinn/auto_schedule/cost_model/expr_cost_model.cc
  paddle/cinn/auto_schedule/database/database.cc
  paddle/cinn/auto_schedule/measure/simple_builder.cc
  paddle/cinn/auto_schedule/measure/simple_runner.cc
  paddle/cinn/auto_schedule/post_schedule_rule/cooperative_process.cc
  paddle/cinn/auto_schedule/search_space/auto_gen_rule/auto_bind.cc
  paddle/cinn/auto_schedule/search_space/auto_gen_rule/auto_gen_rule.cc
  paddle/cinn/auto_schedule/search_space/auto_gen_rule/auto_unroll.cc
  paddle/cinn/auto_schedule/search_space/auto_gen_rule/multi_level_tiling.h
  paddle/cinn/auto_schedule/search_space/auto_gen_rule/reduction_factoring.cc
  paddle/cinn/auto_schedule/search_space/auto_gen_rule/reduction_factoring_test.cc
  paddle/cinn/auto_schedule/search_space/auto_gen_rule/test_helper.cc
  paddle/cinn/auto_schedule/search_space/block_sampler.cc
  paddle/cinn/auto_schedule/search_space/rule_sampler.cc
  paddle/cinn/auto_schedule/search_space/search_space.cc
  paddle/cinn/auto_schedule/search_strategy/evolutionary_search.cc
  paddle/cinn/auto_schedule/search_strategy/evolutionary_search_test.cc
  paddle/cinn/auto_schedule/task/task_optimizer.cc
  paddle/cinn/auto_schedule/task_scheduler/task_scheduler.cc
  paddle/cinn/auto_schedule/tests/performance_comparison_test.cc
Labels: contributor, HappyOpenSource

#64753 Clean paddle/fluid/operators/reduce_ops/reduce_op.h
  paddle/fluid/operators/reduce_ops/logsumexp_op.cc
  paddle/fluid/operators/reduce_ops/logsumexp_op_xpu.cc
  paddle/fluid/operators/reduce_ops/reduce_mean_op.cc
  paddle/fluid/operators/reduce_ops/reduce_mean_op.h
  paddle/fluid/operators/reduce_ops/reduce_op.h
  paddle/fluid/operators/reduce_ops/reduce_op_function.h
Labels: contributor, HappyOpenSource

#64681 【Hackathon 6th Fundable Projects 3 No.374-375】tdm_child
  paddle/fluid/operators/tdm_child_op.cc
  paddle/fluid/operators/tdm_child_op.h
  paddle/fluid/operators/tdm_sampler_op.cc
  paddle/phi/infermeta/binary.cc
  paddle/phi/infermeta/binary.h
  paddle/phi/kernels/cpu/tdm_child_kernel.cc
  paddle/phi/ops/yaml/inconsistent/static_ops.yaml
  paddle/phi/ops/yaml/ops.yaml
Labels: PaddlePaddle Hackathon, contributor

#64684 【Hackathon 6th No.9】Update meshgrid to support complex dtype -part
  paddle/phi/kernels/cpu/meshgrid_grad_kernel.cc
  paddle/phi/kernels/cpu/meshgrid_kernel.cc
  paddle/phi/kernels/gpu/meshgrid_grad_kernel.cu.cc
  paddle/phi/kernels/gpu/meshgrid_kernel.cu.cc
  python/paddle/tensor/creation.py
  python/paddle/tensor/manipulation.py
  test/deprecated/legacy_test/test_meshgrid_op.py
Labels: PaddlePaddle Hackathon, contributor, API

#63728 【Hackathon 6th No.3】为 Paddle 新增 ZeroPad1D / ZeroPad3D / block_diag API -part
  python/paddle/__init__.py
  python/paddle/nn/__init__.py
  python/paddle/nn/layer/common.py
  python/paddle/tensor/__init__.py
  python/paddle/tensor/manipulation.py
  test/legacy_test/test_ZeroPad1d.py
  test/legacy_test/test_ZeroPad3d.py
  test/legacy_test/test_block_diag.py
Labels: PaddlePaddle Hackathon, contributor, API

#64688 【Hackathon 6th Fundable Projects 3 No.383】transfer_layout
  paddle/fluid/operators/transfer_layout_op.cc
  paddle/fluid/operators/transfer_layout_op.h
  paddle/phi/ops/yaml/legacy/static_ops.yaml
  paddle/phi/ops/yaml/op_compat.yaml
Labels: PaddlePaddle Hackathon, contributor

#64701 【Hackathon 6th Fundable Projects 3 No.11】assign_pos
  paddle/fluid/operators/assign_pos_op.cc
  paddle/fluid/operators/ops_signature/assign_pos_sig.cc
  paddle/phi/ops/yaml/inconsistent/static_ops.yaml
  paddle/phi/ops/yaml/ops.yaml
Labels: PaddlePaddle Hackathon, contributor

#64727 【Hackathon 6th Fundable Projects 3 No.256】 number_count
  paddle/fluid/operators/number_count_op.cc
  paddle/fluid/operators/number_count_op.h
  paddle/fluid/operators/ops_signature/number_count_sig.cc
  paddle/phi/ops/yaml/inconsistent/static_ops.yaml
  paddle/phi/ops/yaml/ops.yaml
Labels: PaddlePaddle Hackathon, contributor

#64001 【Hackathon 6th No.10】Add isin API to Paddle -part
  python/paddle/__init__.py
  python/paddle/tensor/__init__.py
  python/paddle/tensor/math.py
  python/paddle/tensor/search.py
  test/legacy_test/CMakeLists.txt
  test/legacy_test/test_isin.py
Labels: PaddlePaddle Hackathon, contributor, API

#64822 【Hackathon 6th Fundable Projects 4 No.5】remove parallel executor pybind code -part
  .github/CODEOWNERS
  paddle/fluid/pybind/CMakeLists.txt
  paddle/fluid/pybind/parallel_executor.cc
  paddle/fluid/pybind/parallel_executor.h
  paddle/fluid/pybind/pybind.cc
  test/legacy_test/CMakeLists.txt
Labels: PaddlePaddle Hackathon, contributor

#64689 [CINN] Dump example input tensor meta
  paddle/cinn/hlir/dialect/operator/transforms/pir_to_py_code_converter.cc
  paddle/fluid/eager/to_static/run_program_op_node.h
  paddle/fluid/framework/CMakeLists.txt
  paddle/fluid/framework/feed_hook.cc
  paddle/fluid/framework/feed_hook.h
  paddle/fluid/framework/new_executor/standalone_executor.cc
  paddle/fluid/inference/api/analysis_predictor.cc
  paddle/pir/include/core/program.h
  paddle/pir/src/core/program.cc
Labels: contributor

#63786 [SOT][dynamic shape] Support dynamic Tensor shape
  python/paddle/jit/sot/infer_meta.py
  python/paddle/jit/sot/opcode_translator/executor/executor_cache.py
  python/paddle/jit/sot/opcode_translator/executor/function_graph.py
  python/paddle/jit/sot/opcode_translator/executor/opcode_executor.py
  python/paddle/jit/sot/opcode_translator/executor/tracker.py
  python/paddle/jit/sot/opcode_translator/executor/variables/basic.py
  python/paddle/jit/sot/symbolic/compile_cache.py
  python/paddle/jit/sot/symbolic/symbolic_context.py
  test/sot/test_sot_dynamic_shape.py
Labels: contributor

#64294 【Hackathon 6th No.6】为 Paddle 新增 StudentT API
  python/paddle/distribution/__init__.py
  python/paddle/distribution/student_t.py
  test/distribution/test_distribution_student_t.py
Labels: PaddlePaddle Hackathon, contributor, API

#64575 [Typing] Ensure packaging `tensor.pyi` into wheel
  python/CMakeLists.txt
  python/paddle/__init__.py
  python/paddle/base/framework.py
  python/paddle/nn/quant/quantized_linear.py
  python/paddle/tensor/tensor.prototype.pyi
  python/setup.py.in
  setup.py
  tools/gen_tensor_stub.py
Labels: PaddlePaddle Hackathon, contributor

#64390 【Hackathon 6th Fundable Projects 3 No.224】lstm
  paddle/fluid/operators/CMakeLists.txt
  paddle/fluid/operators/lstm_op.cc
  paddle/fluid/operators/lstm_op.cu.cc
  paddle/fluid/operators/lstm_op.h
  paddle/phi/infermeta/backward.cc
  paddle/phi/infermeta/backward.h
  paddle/phi/infermeta/multiary.cc
  paddle/phi/infermeta/multiary.h
  paddle/phi/kernels/cpu/lstm_grad_kernel.cc
  paddle/phi/kernels/cpu/lstm_kernel.cc
  paddle/phi/kernels/funcs/lstm_utils.h
  paddle/phi/kernels/gpu/lstm_grad_kernel.cu
  paddle/phi/kernels/gpu/lstm_kernel.cu
  paddle/phi/kernels/impl/lstm_kernel_impl.h
  paddle/phi/kernels/lstm_kernel.h
  paddle/phi/ops/yaml/backward.yaml
  paddle/phi/ops/yaml/op_compat.yaml
  paddle/phi/ops/yaml/ops.yaml
Labels: PaddlePaddle Hackathon, contributor

#64741 【Hackathon 6th Fundable Projects 3 No.169】fusion_group
  paddle/fluid/operators/fused/CMakeLists.txt
  paddle/fluid/operators/fused/fusion_group_op.cc
  paddle/fluid/operators/ops_signature/fusion_group_sig.cc
  paddle/fluid/pir/dialect/op_generator/ops_api_gen.py
  paddle/phi/ops/yaml/fused_ops.yaml
  paddle/phi/ops/yaml/op_compat.yaml
Labels: PaddlePaddle Hackathon, contributor

#64799 【Hackathon 6th Fundable Projects 3 No.316】rrelu
  paddle/fluid/operators/ops_signature/rrelu_sig.cc
  paddle/fluid/operators/rrelu_op.cc
  paddle/phi/ops/yaml/legacy/backward_exclude.yaml
  paddle/phi/ops/yaml/legacy/ops_exclude.yaml
  paddle/phi/ops/yaml/op_compat.yaml
  paddle/phi/ops/yaml/ops.yaml
Labels: PaddlePaddle Hackathon, contributor

#64778 【Hackathon 6th Fundable Projects 2 No.29】 Fix modernize-concat-nested-namespaces-part-24
  paddle/fluid/distributed/fleet_executor/task_loop.cc
  paddle/fluid/distributed/ps/table/graph/graph_node.cc
  paddle/fluid/framework/details/all_reduce_op_handle.cc
  paddle/fluid/framework/details/eager_deletion_op_handle.cc
  paddle/fluid/framework/details/reduce_op_handle.cc
  paddle/fluid/framework/ir/delete_cast_op_pass_test.cc
  paddle/fluid/framework/ir/fusion_group/code_generator.cc
  paddle/fluid/framework/ir/merge_layernorm_fuse_pass.cc
  paddle/fluid/framework/ir/multi_devices_graph_pass/add_reader_dependency_pass.cc
  paddle/fluid/framework/ir/multi_devices_graph_pass/set_reader_device_info_utils.cc
  paddle/fluid/framework/ir/onednn/compute_propagate_scales_onednn_pass.cc
  paddle/fluid/framework/ir/onednn/conv_elementwise_add_onednn_fuse_pass.cc
  paddle/fluid/framework/ir/onednn/operator_reshape2_onednn_fuse_pass.cc
  paddle/fluid/framework/ir/onednn/squeeze2_transpose2_onednn_fuse_pass.cc
  paddle/fluid/framework/ir/placement_pass_base.cc
  paddle/fluid/framework/ir/preln_elementwise_groupnorm_act_pass.cc
  paddle/fluid/framework/ir/trt_qk_multihead_matmul_fuse_pass.cc
  paddle/fluid/framework/ir/trt_skip_layernorm_fuse_pass.cc
  paddle/fluid/framework/ir/trt_support_nhwc_pass.cc
  paddle/fluid/framework/new_executor/instruction/instruction_util.cc
  paddle/fluid/framework/new_executor/interpretercore.cc
  paddle/fluid/imperative/prepared_operator.cc
  paddle/fluid/inference/analysis/passes/save_optimized_model_pass.cc
  paddle/fluid/inference/tensorrt/convert/conv3d_op.cc
  paddle/fluid/inference/tensorrt/convert/leaky_relu_op.cc
  paddle/fluid/inference/tensorrt/convert/matrix_multiply_op.cc
  paddle/fluid/inference/tensorrt/convert/multiclass_nms3_op.cc
  paddle/fluid/inference/tensorrt/convert/transformer_input_convert_op.cc
  paddle/fluid/inference/tensorrt/test_dynamic_engine.cc
  paddle/fluid/memory/allocation/cpu_allocator.cc
  paddle/fluid/memory/allocation/memory_block_desc.cc
  paddle/fluid/operators/collective/c_allreduce_avg_op.cc
  paddle/fluid/operators/collective/partial_send_op.cc
  paddle/fluid/pir/dialect/distributed/ir/dist_tools.cc
  paddle/fluid/pir/dialect/operator/ir/op_attribute.cc
  paddle/fluid/pir/dialect/operator/transforms/param_to_variable.cc
  paddle/fluid/platform/device/gpu/gpu_info.cc
  paddle/fluid/platform/dynload/nccl.cc
  paddle/fluid/prim/api/manual_prim/utils/static_utils.cc
  paddle/fluid/prim/utils/static/static_global_utils.cc
  paddle/fluid/pybind/graph.cc
  paddle/phi/api/lib/context_pool.cc
  paddle/phi/backends/dynload/cublas.cc
  paddle/phi/backends/dynload/cusparse.cc
  paddle/phi/core/distributed/auto_parallel/dist_attr.cc
  paddle/phi/core/distributed/auto_parallel/reshard/x_to_r_reshard_function.cc
  paddle/phi/kernels/funcs/concat_and_split_functor.cc
  paddle/phi/kernels/funcs/matrix_inverse.cc
  paddle/phi/kernels/funcs/sequence_pooling.cc
  paddle/phi/kernels/fusion/cpu/fusion_seqconv_eltadd_relu_kernel.cc
Labels: PaddlePaddle Hackathon, contributor

#64041 【Hackathon 6th Fundable Projects 2 No.47】 performance-unnecessary-copy-initialization_3-part
  paddle/fluid/ir_adaptor/translator/op_translator.cc
  paddle/phi/api/lib/tensor_utils.cc
  paddle/phi/infermeta/backward.cc
  paddle/phi/infermeta/spmd_rules/expand_as.cc
  paddle/phi/infermeta/spmd_rules/triu.cc
  paddle/phi/kernels/cpu/fill_diagonal_tensor_kernel.cc
  paddle/phi/kernels/sparse/cpu/sparse_utils_kernel.cc
  paddle/phi/kernels/stride/slice_kernel.cc
Labels: PaddlePaddle Hackathon, contributor

#64781 【Hackathon 6th Fundable Projects 2 No.29】 Fix modernize-concat-nested-namespaces-part-21
  paddle/fluid/distributed/collective/common.cc
  paddle/fluid/distributed/fleet_executor/runtime_graph.cc
  paddle/fluid/distributed/fleet_executor/task_loop_thread.cc
  paddle/fluid/distributed/ps/service/ps_service/graph_py_service.cc
  paddle/fluid/framework/details/broadcast_op_handle.cc
  paddle/fluid/framework/details/computation_op_handle.cc
  paddle/fluid/framework/executor.cc
  paddle/fluid/framework/ir/adaptive_pool2d_convert_global_pass.cc
  paddle/fluid/framework/ir/fuse_relu_depthwise_conv_pass.cc
  paddle/fluid/framework/ir/graph_helper.cc
  paddle/fluid/framework/ir/graph_to_program_pass.cc
  paddle/fluid/framework/ir/memory_optimize_pass/conditional_block_op_eager_deletion_pass.cc
  paddle/fluid/framework/ir/onednn/conv_activation_onednn_fuse_pass.cc
  paddle/fluid/framework/ir/onednn/cpu_bfloat16_pass_tester.cc
  paddle/fluid/framework/ir/preln_skip_layernorm_fuse_pass.cc
  paddle/fluid/framework/ir/vit_attention_fuse_pass.cc
  paddle/fluid/framework/new_executor/interpreter/stream_analyzer.cc
  paddle/fluid/framework/shape_inference.cc
  paddle/fluid/inference/analysis/ir_pass_manager.cc
  paddle/fluid/inference/api/paddle_infer_contrib.cc
  paddle/fluid/inference/tensorrt/convert/flip_op.cc
  paddle/fluid/inference/tensorrt/convert/quantize_linear_op.cc
  paddle/fluid/inference/tensorrt/convert/share_data_op.cc
  paddle/fluid/inference/tensorrt/convert/unsqueeze2_op.cc
  paddle/fluid/jit/serializer_utils.cc
  paddle/fluid/operators/collective/global_scatter_op.cc
  paddle/fluid/operators/collective/mp_allreduce_sum_op.cc
  paddle/fluid/operators/collective/send_v2_op.cc
  paddle/fluid/operators/optimizers/sparse_momentum_op.cc
  paddle/fluid/operators/reader/create_double_buffer_reader_op.cc
  paddle/fluid/operators/share_data_op.cc
  paddle/fluid/pir/dialect/distributed/ir/dist_type.cc
  paddle/fluid/pir/dialect/operator/ir/ir_selected_rows.cc
  paddle/fluid/pir/drr/src/pattern_graph.cc
  paddle/fluid/prim/api/manual_prim/static_prim_api.cc
  paddle/fluid/pybind/inference_api.cc
  paddle/fluid/pybind/place.cc
  paddle/phi/api/lib/scalar.cc
  paddle/phi/backends/gpu/cuda/cudnn_workspace_helper.cc
  paddle/phi/core/distributed/auto_parallel/reshard/reshard_function.cc
  paddle/phi/infermeta/spmd_rules/utils.cc
  paddle/phi/kernels/funcs/eigen/pad.cc
  paddle/phi/kernels/funcs/eigen/reverse.cc
  paddle/phi/kernels/funcs/gpc.cc
  paddle/phi/kernels/funcs/jit/more/mix/mix.cc
  paddle/phi/kernels/funcs/math/sampler.cc
  paddle/phi/kernels/sparse/cpu/fused_attention_grad_kernel.cc
  paddle/phi/kernels/sparse/cpu/matmul_kernel.cc
  paddle/phi/kernels/sparse/sparse_utils_grad_kernel.cc
  paddle/phi/kernels/strings/cpu/strings_copy_kernel.cc
Labels: PaddlePaddle Hackathon, contributor

#64769 【Hackathon 6th Fundable Projects 2 No.29】 Fix modernize-concat-nested-namespaces-part-14
  paddle/common/flags_native.cc
  paddle/fluid/distributed/collective/process_group_gloo.cc
  paddle/fluid/distributed/fleet_executor/amplifier_interceptor.cc
  paddle/fluid/distributed/ps/table/graph/graph_weighted_sampler.cc
  paddle/fluid/distributed/test/ctr_dymf_accessor_test.cc
  paddle/fluid/framework/details/fused_broadcast_op_handle.cc
  paddle/fluid/framework/executor_cache.cc
  paddle/fluid/framework/io/save_load_tensor.cc
  paddle/fluid/framework/ir/delete_quant_dequant_op_pass.cc
  paddle/fluid/framework/ir/dense_multihead_matmul_to_sparse_pass.cc
  paddle/fluid/framework/ir/embedding_eltwise_layernorm_fuse_pass.cc
  paddle/fluid/framework/ir/fc_lstm_fuse_pass_tester.cc
  paddle/fluid/framework/ir/onednn/conv_affine_channel_onednn_fuse_pass.cc
  paddle/fluid/framework/ir/onednn/params_quantization_onednn_pass_tester.cc
  paddle/fluid/framework/ir/quantize_helper.cc
  paddle/fluid/framework/ir/skip_layernorm_fuse_pass.cc
  paddle/fluid/framework/ir/subgraph_detector.cc
  paddle/fluid/framework/ir/trt_map_ops_to_matrix_multiply_pass.cc
  paddle/fluid/framework/lod_tensor.cc
  paddle/fluid/framework/new_executor/new_executor_defs.cc
  paddle/fluid/framework/new_executor/workqueue/workqueue_utils.cc
  paddle/fluid/imperative/partial_grad_engine.cc
  paddle/fluid/inference/tensorrt/convert/bitwise_not_op.cc
  paddle/fluid/inference/tensorrt/convert/bitwise_or_op.cc
  paddle/fluid/inference/tensorrt/convert/preln_residual_bias.cc
  paddle/fluid/inference/tensorrt/convert/sum_op.cc
  paddle/fluid/inference/tensorrt/dynamic_shape_infermeta.cc
  paddle/fluid/inference/tensorrt/test_arg_mapping_context.cc
  paddle/fluid/memory/allocation/system_allocator.cc
  paddle/fluid/operators/nop_op.cc
  paddle/fluid/operators/pscore/send_op.cc
  paddle/fluid/pir/dialect/distributed/ir/dist_api.cc
  paddle/fluid/pir/dialect/operator/ir/op_dialect.cc
  paddle/fluid/platform/dynload/cusolver.cc
  paddle/fluid/platform/monitor.cc
  paddle/fluid/platform/profiler/event_python.cc
  paddle/fluid/pybind/eager_utils.cc
  paddle/fluid/pybind/generator_py.cc
  paddle/phi/backends/dynload/cusolver.cc
  paddle/phi/backends/dynload/cutlass_conv2d.cc
  paddle/phi/backends/dynload/lapack.cc
  paddle/phi/core/distributed/check/nccl_dynamic_check.cc
  paddle/phi/core/distributed/comm_context_manager.cc
  paddle/phi/infermeta/spmd_rules/full_like.cc
  paddle/phi/infermeta/spmd_rules/gather.cc
  paddle/phi/kernels/funcs/gather_scatter_functor.cc
  paddle/phi/kernels/funcs/jit/gen/blas.cc
  paddle/phi/kernels/funcs/jit/more/intrinsic/crf_decoding.cc
  paddle/phi/kernels/sparse/empty_kernel.cc
  paddle/phi/kernels/strings/cpu/strings_lower_upper_kernel.cc
Labels: PaddlePaddle Hackathon, contributor

#64768 【Hackathon 6th Fundable Projects 2 No.29】 Fix modernize-concat-nested-namespaces-part-13
  paddle/fluid/distributed/collective/process_group.cc
  paddle/fluid/distributed/collective/process_group_nccl.cc
  paddle/fluid/distributed/ps/service/ps_local_client.cc
  paddle/fluid/distributed/ps/table/barrier_table.cc
  paddle/fluid/distributed/test/feature_value_test.cc
  paddle/fluid/distributed/test/table_test.cc
  paddle/fluid/framework/details/fetch_async_op_handle.cc
  paddle/fluid/framework/io/crypto/cipher.cc
  paddle/fluid/framework/io/save_paddle2cinn_varmap.cc
  paddle/fluid/framework/ir/coalesce_grad_tensor_pass.cc
  paddle/fluid/framework/ir/conv_elementwise_add2_act_fuse_pass.cc
  paddle/fluid/framework/ir/fuse_optimizer_ops_pass/fuse_adam_op_pass.cc
  paddle/fluid/framework/ir/fused_multi_transformer_decoder_pass.cc
  paddle/fluid/framework/ir/multi_devices_graph_pass/fix_op_run_order_pass.cc
  paddle/fluid/framework/ir/multi_devices_graph_pass/multi_devices_graph_pass.cc
  paddle/fluid/framework/ir/onednn/compute_propagate_scales_onednn_pass_tester.cc
  paddle/fluid/framework/ir/onednn/conv_bias_onednn_fuse_pass.cc
  paddle/fluid/framework/ir/onednn/softplus_activation_onednn_fuse_pass.cc
  paddle/fluid/framework/ir/seqpool_concat_fuse_pass_tester.cc
  paddle/fluid/framework/ir/shuffle_channel_detect_pass.cc
  paddle/fluid/framework/new_executor/executor_statistics.cc
  paddle/fluid/framework/new_executor/feed_fetch_utils.cc
  paddle/fluid/framework/new_executor/interpreter/dependency_builder.cc
  paddle/fluid/framework/program_desc.cc
  paddle/fluid/framework/string_array.cc
  paddle/fluid/framework/variable_helper.cc
  paddle/fluid/inference/tensorrt/convert/instance_norm_op.cc
  paddle/fluid/inference/tensorrt/convert/lookup_table_op.cc
  paddle/fluid/inference/tensorrt/convert/multihead_matmul_op.cc
  paddle/fluid/inference/tensorrt/convert/prompt_tuning_emb_eltwise_layernorm.cc
  paddle/fluid/inference/tensorrt/convert/test_op_converter.cc
  paddle/fluid/inference/utils/model_utils.cc
  paddle/fluid/operators/collective/c_allreduce_prod_op.cc
  paddle/fluid/operators/fused/fused_conv2d_op.cc
  paddle/fluid/operators/fused/fused_gate_attention_op.cc
  paddle/fluid/operators/pscore/fetch_barrier_op.cc
  paddle/fluid/pir/dialect/operator/utils/op_yaml_info_parser.cc
  paddle/fluid/platform/dynload/cudnn.cc
  paddle/fluid/platform/profiler/cuda_tracer.cc
  paddle/fluid/primitive/rule/vjp/manual/manual_vjp.cc
  paddle/fluid/pybind/eager_method.cc
  paddle/fluid/pybind/exception.cc
  paddle/fluid/pybind/global_value_getter_setter.cc
  paddle/phi/core/distributed/auto_parallel/reshard/nd_mesh_reshard_function.cc
  paddle/phi/core/distributed/auto_parallel/reshard/s_to_r_reshard_function.cc
  paddle/phi/core/distributed/check/static_check.cc
  paddle/phi/infermeta/spmd_rules/where.cc
  paddle/phi/kernels/funcs/jit/gen/adamw.cc
  paddle/phi/kernels/selected_rows/merge_selected_rows_kernel.cc
  paddle/phi/kernels/sparse/cpu/transpose_kernel.cc
Labels: PaddlePaddle Hackathon, contributor

#64766 【Hackathon 6th Fundable Projects 2 No.29】 Fix modernize-concat-nested-namespaces-part-11
  paddle/fluid/distributed/ps/service/graph_brpc_server.cc
  paddle/fluid/framework/details/grad_merge_all_reduce_op_handle.cc
  paddle/fluid/framework/details/scope_buffered_monitor.cc
  paddle/fluid/framework/details/share_tensor_buffer_op_handle.cc
  paddle/fluid/framework/garbage_collector.cc
  paddle/fluid/framework/ir/auto_mixed_precision_pass.cc
  paddle/fluid/framework/ir/delete_cast_op_pass.cc
  paddle/fluid/framework/ir/fc_fuse_pass.cc
  paddle/fluid/framework/ir/fuse_optimizer_ops_pass/fuse_optimizer_op_pass.cc
  paddle/fluid/framework/ir/fuse_optimizer_ops_pass/fuse_sgd_op_pass.cc
  paddle/fluid/framework/ir/fused_multi_transformer_decoder_pass_tester.cc
  paddle/fluid/framework/ir/multi_devices_graph_pass/backward_optimizer_op_deps_pass.cc
  paddle/fluid/framework/ir/onednn/reshape_transpose_matmul_onednn_fuse_pass.cc
  paddle/fluid/framework/ir/onednn/shuffle_channel_onednn_detect_pass.cc
  paddle/fluid/framework/ir/pass_test_util.cc
  paddle/fluid/framework/ir/seqpool_cvm_concat_fuse_pass.cc
  paddle/fluid/framework/ir/trt_delete_weight_dequant_linear_op_pass.cc
  paddle/fluid/framework/transfer_scope_cache.cc
  paddle/fluid/imperative/nccl_context.cc
  paddle/fluid/inference/tensorrt/convert/fused_token_prune_op.cc
  paddle/fluid/inference/tensorrt/convert/index_select_op.cc
  paddle/fluid/inference/tensorrt/convert/pool3d_op.cc
  paddle/fluid/inference/tensorrt/convert/roll_op.cc
  paddle/fluid/inference/tensorrt/convert/skip_merge_layernorm_op.cc
  paddle/fluid/inference/tensorrt/plugin/test_split_plugin.cc
  paddle/fluid/inference/tensorrt/test_engine.cc
  paddle/fluid/jit/layer.cc
  paddle/fluid/memory/allocation/auto_growth_best_fit_allocator.cc
  paddle/fluid/operators/collective/c_comm_init_all_op.cc
  paddle/fluid/operators/collective/c_gen_xccl_id_op.cc
  paddle/fluid/operators/collective/c_reducescatter_op.cc
  paddle/fluid/operators/controlflow/pylayer_op.cc
  paddle/fluid/operators/controlflow/pylayer_op_helper.cc
  paddle/fluid/operators/sync_batch_norm_op.cc
  paddle/fluid/pir/transforms/pd_op_to_kernel_pass.cc
  paddle/fluid/platform/denormal.cc
  paddle/fluid/pybind/op_function_common.cc
  paddle/fluid/pybind/protobuf.cc
  paddle/phi/backends/dynload/cuda_driver.cc
  paddle/phi/core/distributed/auto_parallel/proto_helper.cc
  paddle/phi/core/distributed/auto_parallel/reshard/p_to_s_reshard_function.cc
  paddle/phi/infermeta/sparse/unary.cc
  paddle/phi/infermeta/spmd_rules/elementwise.cc
  paddle/phi/infermeta/spmd_rules/unsqueeze.cc
  paddle/phi/kernels/funcs/gru_compute.cc
  paddle/phi/kernels/fusion/onednn/fused_elementwise_kernel.cc
  paddle/phi/kernels/sparse/cpu/mask_kernel.cc
  paddle/phi/kernels/sparse/cpu/matmul_grad_kernel.cc
  paddle/phi/kernels/sparse/cpu/mv_kernel.cc
Labels: PaddlePaddle Hackathon, contributor

#64764 【Hackathon 6th Fundable Projects 2 No.29】 Fix modernize-concat-nested-namespaces-part-9
  paddle/fluid/distributed/collective/gloo_send_recv.cc
  paddle/fluid/distributed/common/afs_warpper.cc
  paddle/fluid/distributed/ps/service/server.cc
  paddle/fluid/distributed/ps/table/ctr_accessor.cc
  paddle/fluid/distributed/ps/table/memory_dense_table.cc
  paddle/fluid/distributed/rpc/python_rpc_handler.cc
  paddle/fluid/distributed/test/brpc_utils_test.cc
  paddle/fluid/framework/details/fused_all_reduce_op_handle.cc
  paddle/fluid/framework/ir/delete_assign_op_pass_test.cc
  paddle/fluid/framework/ir/delete_op_device_pass.cc
  paddle/fluid/framework/ir/fc_elementwise_layernorm_fuse_pass_tester.cc
  paddle/fluid/framework/ir/matmul_scale_fuse_pass.cc
  paddle/fluid/framework/ir/multihead_matmul_roformer_fuse_pass.cc
  paddle/fluid/framework/ir/node_test.cc
  paddle/fluid/framework/ir/onednn/multi_gru_seq_fuse_pass.cc
  paddle/fluid/framework/ir/squared_mat_sub_fuse_pass.cc
  paddle/fluid/framework/ir/trt_multihead_matmul_fuse_pass.cc
  paddle/fluid/framework/new_executor/instruction/custom_kernel_instruction.cc
  paddle/fluid/framework/op_def_api.cc
  paddle/fluid/framework/program_utils.cc
  paddle/fluid/imperative/layer.cc
  paddle/fluid/inference/tensorrt/convert/roi_align_op.cc
  paddle/fluid/inference/tensorrt/convert/yolo_box_head_op.cc
  paddle/fluid/ir_adaptor/translator/program_translator.cc
  paddle/fluid/jit/property.cc
  paddle/fluid/memory/allocation/allocator_facade.cc
  paddle/fluid/memory/allocation/cuda_virtual_mem_allocator.cc
  paddle/fluid/operators/fused_softmax_mask_upper_triangle_op.cc
  paddle/fluid/operators/reader/py_reader.cc
  paddle/fluid/operators/repeat_interleave_op.cc
  paddle/fluid/pir/dialect/distributed/ir/dist_op.cc
  paddle/fluid/pir/dialect/operator/interface/layout_transformation.cc
  paddle/fluid/pir/dialect/operator/ir/control_flow_op.cc
  paddle/fluid/pir/dialect/operator/ir/ir_tensor.cc
  paddle/fluid/platform/cuda_graph_with_memory_pool.cc
  paddle/fluid/platform/timer.cc
  paddle/fluid/prim/api/all.cc
  paddle/fluid/pybind/data_set_py.cc
  paddle/fluid/pybind/xpu_streams_py.cc
  paddle/phi/backends/dynload/cupti.cc
  paddle/phi/backends/gpu/cuda/cuda_graph.cc
  paddle/phi/core/distributed/auto_parallel/reshard/p_to_r_reshard_function.cc
  paddle/phi/infermeta/spmd_rules/pow.cc
  paddle/phi/kernels/funcs/fft.cc
  paddle/phi/kernels/funcs/lapack/lapack_function.cc
  paddle/phi/kernels/funcs/softmax.cc
  paddle/phi/kernels/fusion/cpu/fused_softmax_mask_kernel.cc
  paddle/phi/kernels/sparse/cpu/slice_kernel.cc
Labels: PaddlePaddle Hackathon, contributor

#64763 【Hackathon 6th Fundable Projects 2 No.29】 Fix modernize-concat-nested-namespaces-part-8
  paddle/fluid/distributed/ps/service/ps_service/service.cc
  paddle/fluid/framework/details/build_strategy.cc
  paddle/fluid/framework/details/fast_threaded_ssa_graph_executor.cc
  paddle/fluid/framework/device_worker_factory.cc
  paddle/fluid/framework/ir/delete_op_device_pass_test.cc
  paddle/fluid/framework/ir/graph.cc
  paddle/fluid/framework/ir/is_test_pass.cc
  paddle/fluid/framework/ir/multihead_matmul_fuse_pass.cc
  paddle/fluid/framework/ir/onednn/cpu_quantize_pass.cc
  paddle/fluid/framework/ir/onednn/interpolate_onednn_pass.cc
  paddle/fluid/framework/ir/quant_conv2d_dequant_fuse_pass.cc
  paddle/fluid/framework/ir/simplify_with_basic_ops_pass.cc
  paddle/fluid/framework/ir/split_layernorm_to_math_ops_pass.cc
  paddle/fluid/framework/ir/sync_batch_norm_pass_tester.cc
  paddle/fluid/framework/ir/transpose_flatten_concat_fuse_pass.cc
  paddle/fluid/framework/ir/trt_prompt_tuning_embedding_eltwise_layernorm_fuse_pass.cc
  paddle/fluid/framework/new_executor/garbage_collector/event_garbage_collector.cc
  paddle/fluid/imperative/data_loader.cc
  paddle/fluid/inference/api/helper.cc
  paddle/fluid/inference/tensorrt/convert/celu_op.cc
  paddle/fluid/inference/tensorrt/convert/fill_constant_op.cc
  paddle/fluid/inference/tensorrt/convert/gather_nd_op.cc
  paddle/fluid/inference/tensorrt/convert/grid_sampler_op.cc
  paddle/fluid/inference/tensorrt/convert/preln_emb_eltwise_layernorm.cc
  paddle/fluid/inference/tensorrt/plugin/trt_plugin.cc
  paddle/fluid/inference/tensorrt/plugin_arg_mapping_context.cc
  paddle/fluid/inference/utils/table_printer.cc
  paddle/fluid/memory/allocation/cuda_allocator.cc
  paddle/fluid/operators/fused/fused_feedforward_op.cc
  paddle/fluid/operators/fused/resnet_unit_op.cc
  paddle/fluid/pir/dialect/operator/ir/manual_op.cc
  paddle/fluid/platform/dynload/curand.cc
  paddle/fluid/pybind/control_flow_api.cc
  paddle/fluid/pybind/dist_api.cc
  paddle/phi/api/lib/kernel_dispatch.cc
  paddle/phi/backends/dynload/nvjpeg.cc
  paddle/phi/core/distributed/auto_parallel/reshard/r_to_s_reshard_function.cc
  paddle/phi/core/distributed/auto_parallel/reshard/reshard_utils.cc
  paddle/phi/core/distributed/nccl_comm_context.cc
  paddle/phi/infermeta/spmd_rules/flash_attention.cc
  paddle/phi/infermeta/spmd_rules/one_hot.cc
  paddle/phi/kernels/funcs/jit/gen/gru.cc
  paddle/phi/kernels/funcs/jit/gen/vbroadcast.cc
  paddle/phi/kernels/funcs/segment_pooling.cc
  paddle/phi/kernels/funcs/sequence2batch.cc
  paddle/phi/kernels/fusion/onednn/fused_softplus_kernel.cc
  paddle/phi/kernels/selected_rows/hsigmoid_loss_grad_kernel.cc
  paddle/phi/kernels/selected_rows/shape_kernel.cc
  paddle/phi/kernels/sparse/batch_norm_grad_kernel.cc
  paddle/phi/kernels/sparse/cpu/fused_attention_kernel.cc
Labels: PaddlePaddle Hackathon, contributor

#64760 【Hackathon 6th Fundable Projects 2 No.29】 Fix modernize-concat-nested-namespaces-part-5
  paddle/fluid/distributed/fleet_executor/task_loop_thread_pool.cc
  paddle/fluid/distributed/ps/service/coordinator_client.cc
  paddle/fluid/distributed/ps/table/memory_sparse_geo_table.cc
  paddle/fluid/distributed/ps/table/sparse_accessor.cc
  paddle/fluid/distributed/test/ctr_accessor_test.cc
  paddle/fluid/framework/data_feed.cc
  paddle/fluid/framework/data_type.cc
  paddle/fluid/framework/details/fetch_op_handle.cc
  paddle/fluid/framework/details/parallel_ssa_graph_executor.cc
  paddle/fluid/framework/details/scale_loss_grad_op_handle.cc
  paddle/fluid/framework/ir/delete_dropout_op_pass_test.cc
  paddle/fluid/framework/ir/dense_fc_to_sparse_pass_tester.cc
  paddle/fluid/framework/ir/fused_multi_transformer_encoder_pass_tester.cc
  paddle/fluid/framework/ir/graph_helper_test.cc
  paddle/fluid/framework/ir/onednn/int8_scale_calculation_onednn_pass.cc
  paddle/fluid/framework/ir/preln_embedding_eltwise_layernorm_fuse_pass.cc
  paddle/fluid/framework/ir/preln_residual_bias_fuse_pass.cc
  paddle/fluid/framework/naive_executor.cc
  paddle/fluid/framework/new_executor/instruction/legacy_kernel_instruction.cc
  paddle/fluid/framework/new_executor/interpreter/execution_config.cc
  paddle/fluid/framework/new_executor/interpreter/interpreter_util.cc
  paddle/fluid/framework/new_executor/pir_interpreter.cc
  paddle/fluid/framework/scope.cc
  paddle/fluid/framework/selected_rows_utils.cc
  paddle/fluid/inference/analysis/passes/ir_graph_to_program_pass.cc
  paddle/fluid/inference/tensorrt/convert/qk_multihead_matmul_op.cc
  paddle/fluid/inference/tensorrt/convert/transpose_op.cc
  paddle/fluid/inference/tensorrt/convert/unary_op.cc
  paddle/fluid/jit/function_schema.cc
  paddle/fluid/memory/allocation/memory_block.cc
  paddle/fluid/memory/allocation/meta_cache.cc
  paddle/fluid/memory/allocation/pinned_allocator.cc
  paddle/fluid/operators/collective/c_allreduce_max_op.cc
  paddle/fluid/operators/collective/c_comm_init_op.cc
  paddle/fluid/pir/dialect/kernel/ir/kernel_op.cc
  paddle/fluid/pybind/gloo_context_py.cc
  paddle/phi/backends/dynload/tensorrt.cc
  paddle/phi/common/scalar.cc
  paddle/phi/core/distributed/nccl_comm_task.cc
  paddle/phi/infermeta/spmd_rules/slice.cc
  paddle/phi/infermeta/spmd_rules/unbind.cc
  paddle/phi/infermeta/strings/nullary.cc
  paddle/phi/kernels/cpu/random_routing_kernel.cc
  paddle/phi/kernels/funcs/jit/gen/seqpool.cc
  paddle/phi/kernels/funcs/jit/kernel_pool.cc
  paddle/phi/kernels/sparse/cpu/addmm_kernel.cc
  paddle/phi/kernels/sparse/cpu/conv_grad_kernel.cc
  paddle/phi/kernels/sparse/cpu/transpose_grad_kernel.cc
  paddle/pir/src/core/op_result_impl.cc
  test/deprecated/cpp/prim/test_static_prim.cc
Labels: PaddlePaddle Hackathon, contributor

#64870 update block_diag
  python/paddle/tensor/manipulation.py
Labels: PaddlePaddle Hackathon, contributor, API

#64883 Fix equels equals
  paddle/phi/kernels/cpu/fill_diagonal_grad_kernel.cc
  paddle/phi/kernels/cpu/fill_diagonal_kernel.cc
  paddle/phi/kernels/gpu/fill_diagonal_grad_kernel.cu
  paddle/phi/kernels/gpu/fill_diagonal_kernel.cu
  paddle/pir/include/core/block.h
  paddle/pir/include/core/block_argument.h
  paddle/pir/include/core/builtin_op.h
  paddle/pir/include/core/builtin_type_storage.h
  paddle/pir/src/dialect/shape/interface/infer_symbolic_shape/infer_symbolic_shape.cc
  paddle/pir/src/dialect/shape/utils/constraints_manager.cc
  paddle/pir/src/dialect/shape/utils/dim_expr_util.cc
Labels: contributor, HappyOpenSource

#64617 【Hackathon 6th Fundable Projects 2 No.25】Fix misc-redundant-expression-final
  paddle/fluid/pybind/auto_parallel_py.cc
  paddle/fluid/pybind/eager.cc
  paddle/fluid/pybind/eager_py_layer.cc
  paddle/phi/infermeta/ternary.cc
Labels: PaddlePaddle Hackathon, contributor

#64427 【Hackathon 6th Fundable Projects 2 No.43】Fix inefficient-vector-operation final
  paddle/fluid/distributed/ps/table/graph/graph_weighted_sampler.cc
  paddle/fluid/inference/tensorrt/dynamic_shape_infermeta.cc
  paddle/fluid/pir/dialect/distributed/ir/dist_tools.cc
  paddle/phi/api/lib/data_transform.cc
  paddle/phi/infermeta/spmd_rules/fused_rope.cc
  paddle/phi/infermeta/spmd_rules/split.cc
  paddle/phi/infermeta/spmd_rules/unbind.cc
Labels: PaddlePaddle Hackathon, contributor

#64739 【Hackathon 6th Fundable Projects 2 No.26】Fix misc-unused-alias-decls-final
  paddle/fluid/operators/load_combine_op.cc
  paddle/fluid/pybind/pir.cc
Labels: PaddlePaddle Hackathon, contributor

#64795 【Error Message No.15】Replace paddle/cinn/common/*
  paddle/cinn/common/arithmetic.cc
  paddle/cinn/common/broadcast_tree.cc
  paddle/cinn/common/cas.cc
  paddle/cinn/common/cas.h
  paddle/cinn/common/cinn_value.cc
  paddle/cinn/common/cinn_value.h
  paddle/cinn/common/float16_bfloat16_cuda_test.cu
  paddle/cinn/common/graph_utils.cc
  paddle/cinn/common/graph_utils.h
  paddle/cinn/common/ir_util.cc
  paddle/cinn/common/type.cc
  paddle/cinn/common/union_find.h
Labels: contributor, HappyOpenSource

#64740 【Hackathon 6th Fundable Projects 2 No.27】Fix misc-unused-using-decls-final
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/same_operands_result.cc
  paddle/fluid/pybind/control_flow_api.cc
  paddle/fluid/pybind/rpc.cc
  paddle/phi/infermeta/spmd_rules/numel.cc
Labels: PaddlePaddle Hackathon, contributor

#64772 【Hackathon 6th Fundable Projects 2 No.29】 Fix modernize-concat-nested-namespaces-part-18
  paddle/fluid/distributed/fleet_executor/message_bus.cc
  paddle/fluid/distributed/ps/service/brpc_utils.cc
  paddle/fluid/distributed/ps/table/graph/graph_edge.cc
  paddle/fluid/distributed/ps/table/sparse_sgd_rule.cc
  paddle/fluid/distributed/test/barrier_table_test.cc
  paddle/fluid/framework/feed_fetch_method.cc
  paddle/fluid/framework/ir/fuse_optimizer_ops_pass/fuse_momentum_op_pass.cc
  paddle/fluid/framework/ir/groupnorm_act_pass.cc
  paddle/fluid/framework/ir/memory_optimize_pass/op_graph_view.cc
  paddle/fluid/framework/ir/multi_batch_merge_pass.cc
  paddle/fluid/framework/ir/onednn/elementwise_act_onednn_fuse_pass.cc
  paddle/fluid/framework/ir/onednn/scale_matmul_fuse_pass.cc
  paddle/fluid/framework/ir/onednn/shuffle_channel_onednn_detect_pass_tester.cc
  paddle/fluid/framework/ir/yolo_box_fuse_pass.cc
  paddle/fluid/framework/new_executor/standalone_executor.cc
  paddle/fluid/framework/section_worker.cc
  paddle/fluid/inference/analysis/passes/ir_graph_build_pass.cc
  paddle/fluid/inference/analysis/passes/ir_params_sync_among_devices_pass.cc
  paddle/fluid/inference/tensorrt/convert/c_allreduce_op.cc
  paddle/fluid/inference/tensorrt/convert/concat_op.cc
  paddle/fluid/inference/tensorrt/convert/skip_layernorm.cc
  paddle/fluid/inference/tensorrt/convert/stack_op.cc
  paddle/fluid/inference/tensorrt/convert/trans_layernorm_op.cc
  paddle/fluid/jit/function_utils.cc
  paddle/fluid/memory/stats.cc
  paddle/fluid/operators/collective/c_reduce_max_op.cc
  paddle/fluid/operators/common_infer_shape_functions.cc
  paddle/fluid/operators/controlflow/conditional_block_op.cc
  paddle/fluid/operators/detection/bipartite_match_op.cc
  paddle/fluid/operators/fused/fusion_lstm_op.cc
  paddle/fluid/operators/logspace_op.cc
  paddle/fluid/operators/memcpy_h2d_op.cc
  paddle/fluid/operators/read_file_op.cc
  paddle/fluid/operators/reader/reader_op_registry.cc
  paddle/fluid/pir/dialect/distributed/transforms/dist_to_dense_pass.cc
  paddle/fluid/platform/dynload/nvrtc.cc
  paddle/fluid/platform/dynload/warpctc.cc
  paddle/fluid/prim/api/manual_prim/eager_prim_api.cc
  paddle/phi/backends/dynload/nvtx.cc
  paddle/phi/backends/gpu/gpu_info.cc
  paddle/phi/core/distributed/auto_parallel/reshard/r_to_x_reshard_function.cc
  paddle/phi/core/distributed/gloo_utils.cc
  paddle/phi/infermeta/spmd_rules/fused_linear_param_grad_add.cc
  paddle/phi/infermeta/spmd_rules/softmax.cc
  paddle/phi/infermeta/spmd_rules/swiglu.cc
  paddle/phi/infermeta/strings/unary.cc
  paddle/phi/kernels/funcs/data_layout_transform.cc
  paddle/phi/kernels/funcs/eigen/erf.cc
  paddle/phi/kernels/sparse/cpu/elementwise_grad_kernel.cc
Labels: PaddlePaddle Hackathon, contributor

#64440 【Hackathon 6th Fundable Projects 3 No.153】fluid operator fused_elemwise_activation
  paddle/fluid/framework/ir/fuse_elewise_add_act_pass.cc
  paddle/fluid/operators/fused/fused_elemwise_activation_op.cc
  paddle/fluid/operators/fused/fused_elemwise_activation_op.cu
  paddle/fluid/pir/dialect/op_generator/ops_api_gen.py
  paddle/fluid/pir/dialect/operator/utils/utils.cc
  paddle/phi/infermeta/fusion.cc
  paddle/phi/infermeta/fusion.h
  paddle/phi/kernels/funcs/elementwise/elementwise_op_function.h
  paddle/phi/kernels/funcs/fused_elemwise_activation_functor.h
  paddle/phi/kernels/fusion/cpu/fused_elemwise_activation_grad_kernel.cc
  paddle/phi/kernels/fusion/cpu/fused_elemwise_activation_kernel.cc
  paddle/phi/kernels/fusion/gpu/fused_elemwise_activation_grad_kernel.cu
  paddle/phi/kernels/fusion/gpu/fused_elemwise_activation_kernel.cu
  paddle/phi/kernels/impl/fused_elemwise_activation_kernel_impl.h
  paddle/phi/ops/yaml/fused_backward.yaml
  paddle/phi/ops/yaml/fused_ops.yaml
  paddle/phi/ops/yaml/inconsistent/static_backward.yaml
  paddle/phi/ops/yaml/inconsistent/static_ops.yaml
  paddle/phi/ops/yaml/op_compat.yaml
  test/legacy_test/test_fused_elemwise_activation_op.py
Labels: PaddlePaddle Hackathon, contributor

#64700 【Hackathon 6th Fundable Projects 3 No.276】prune_gate_by_capacity
  paddle/fluid/operators/ops_signature/prune_gate_by_capacity_sig.cc
  paddle/fluid/operators/prune_gate_by_capacity_op.cc
  paddle/phi/ops/yaml/inconsistent/static_ops.yaml
  paddle/phi/ops/yaml/op_compat.yaml
  paddle/phi/ops/yaml/ops.yaml
Labels: PaddlePaddle Hackathon, contributor

#64737 【Hackathon 6th Fundable Projects 3 No.352】shuffle_batch
  paddle/fluid/operators/ops_signature/shuffle_batch_sig.cc
  paddle/fluid/operators/shuffle_batch_op.cc
  paddle/phi/ops/yaml/backward.yaml
  paddle/phi/ops/yaml/inconsistent/static_backward.yaml
  paddle/phi/ops/yaml/inconsistent/static_ops.yaml
  paddle/phi/ops/yaml/ops.yaml
Labels: PaddlePaddle Hackathon, contributor

#63137 improve the performence of fftc2rgrad
  paddle/phi/kernels/funcs/fft_fill_conj.h
  paddle/phi/kernels/impl/fft_grad_kernel_impl.h
Labels: contributor

#64147 Out of bound access on `test_sparse_sum_op`
  paddle/phi/kernels/sparse/gpu/sum_grad_kernel.cu
  paddle/phi/kernels/sparse/gpu/sum_kernel.cu
Labels: NVIDIA, contributor, HappyOpenSource

#64145 Fixes about `unique_ptr` in `malloc_test`
  test/cpp/fluid/memory/malloc_test.cu
Labels: NVIDIA, contributor, HappyOpenSource

#64871 【Hackathon 6th Fundable Projects 3 No.170】fusion_lstm
  paddle/fluid/operators/fused/CMakeLists.txt
  paddle/fluid/operators/fused/fusion_lstm_op.cc
  paddle/fluid/operators/fused/fusion_lstm_op.h
  paddle/fluid/operators/fused/onednn/fusion_lstm_onednn_op.cc
  paddle/fluid/pir/dialect/op_generator/ops_api_gen.py
  paddle/fluid/pir/dialect/operator/utils/utils.cc
  paddle/phi/kernels/fusion/cpu/fusion_lstm_kernel.cc
  paddle/phi/kernels/fusion/onednn/fusion_lstm_kernel.cc
  paddle/phi/kernels/fusion/onednn/fusion_rnn_onednn.h
  paddle/phi/ops/yaml/fused_ops.yaml
  paddle/phi/ops/yaml/inconsistent/onednn_static.yaml
Labels: PaddlePaddle Hackathon, contributor

#64911 [CINN] dump pir origin programs
  paddle/cinn/hlir/dialect/operator/transforms/add_cinn_pass.cc
  paddle/cinn/hlir/dialect/operator/transforms/pir_to_py_code_converter.cc
  paddle/common/flags.cc
  paddle/fluid/framework/feed_hook.cc
  paddle/fluid/pybind/pir.cc
  python/paddle/base/executor.py
Labels: contributor

#64942 Fix ToCDatatType ToCDataType
  paddle/phi/api/include/tensor_utils.h
  paddle/phi/api/lib/data_transform.h
  paddle/phi/api/profiler/trace_event.h
  paddle/phi/backends/custom/custom_device.cc
  paddle/phi/backends/gpu/cuda/cuda_helper.h
Labels: contributor, HappyOpenSource

#63453 【Hackathon 6th No.25】为 paddle.nn.functional.threshold 进行功能对齐与功能增强 -part
  paddle/phi/kernels/activation_grad_kernel.h
  paddle/phi/kernels/activation_kernel.h
  paddle/phi/kernels/cpu/activation_grad_kernel.cc
  paddle/phi/kernels/cpu/activation_kernel.cc
  paddle/phi/kernels/funcs/activation_functor.h
  paddle/phi/kernels/gpu/activation_grad_kernel.cu
  paddle/phi/kernels/gpu/activation_kernel.cu
  paddle/phi/ops/yaml/backward.yaml
  paddle/phi/ops/yaml/op_version.yaml
  paddle/phi/ops/yaml/ops.yaml
  python/paddle/nn/functional/activation.py
  python/paddle/nn/layer/activation.py
  test/legacy_test/test_activation_op.py
  test/legacy_test/test_imperative_layers.py
Labels: PaddlePaddle Hackathon, contributor, API

#64912 [OneDNN][PIR] Fix OneDNN concat kernel bug
  paddle/phi/kernels/onednn/concat_kernel.cc
Labels: Intel, contributor

#64925 [PIR][oneDNN] set is_test attribute for onednn ops
  paddle/fluid/pir/transforms/onednn/onednn_placement_pass.cc
Labels: Intel, contributor

#64789 [Prim][PIR] Support dynamic shape for sum_grad and mean_grad
  paddle/fluid/primitive/rule/vjp/details.h
  python/paddle/autograd/backward_utils.py
  test/prim/pir_prim/CMakeLists.txt
  test/prim/pir_prim/test_prim_sub_graph_backward_dynamic_shape.py
Labels: contributor

#64933 [Prim][PIR] fix one_hot op forward in prim pir
  paddle/fluid/primitive/composite/composite.h
  test/deprecated/legacy_test/test_one_hot_v2_op.py
Labels: contributor

#64934 [CINN] Pir py code fix free vars
  paddle/cinn/hlir/dialect/operator/transforms/pir_to_py_code_converter.cc
Labels: contributor

#64981 Rename device_memory_aligment device_memory_alignment
  paddle/fluid/framework/details/fused_all_reduce_op_handle.cc
  paddle/phi/backends/device_memory_alignment.h
  paddle/phi/infermeta/multiary.cc
  paddle/phi/kernels/check_memory_continue_kernel.cc
  paddle/phi/kernels/coalesce_tensor_kernel.cc
Labels: contributor, HappyOpenSource

#63544 【Hackathon 6th No.16】为 Paddle 新增 LPPool1D / LPPool2D API
  paddle/phi/kernels/cpu/pool_grad_kernel.cc
  paddle/phi/kernels/cpu/pool_kernel.cc
  paddle/phi/kernels/funcs/pooling.cc
  paddle/phi/kernels/funcs/pooling.cu
  paddle/phi/kernels/funcs/pooling.h
  paddle/phi/kernels/gpu/pool_grad_kernel.cu
  paddle/phi/kernels/gpu/pool_kernel.cu
  paddle/phi/kernels/gpudnn/pool_grad_kernel.cu
  paddle/phi/kernels/impl/pool_grad_kernel_impl.h
  paddle/phi/kernels/impl/pool_kernel_impl.h
  paddle/phi/kernels/pool_grad_kernel.h
  paddle/phi/kernels/pool_kernel.h
  paddle/phi/ops/yaml/backward.yaml
  paddle/phi/ops/yaml/ops.yaml
  python/paddle/nn/__init__.py
  python/paddle/nn/functional/__init__.py
  python/paddle/nn/functional/pooling.py
  python/paddle/nn/layer/__init__.py
  python/paddle/nn/layer/pooling.py
  test/legacy_test/test_pool1d_api.py
  test/legacy_test/test_pool2d_api.py
  test/legacy_test/test_pool2d_op.py
  test/white_list/op_threshold_white_list.py
Labels: PaddlePaddle Hackathon, contributor, API

#64988 [Mthreads] support/fix operators for Bert/DBNet
  cmake/external/gloo.cmake
  paddle/fluid/platform/device/gpu/nccl_helper.h
  paddle/phi/backends/context_pool.cc
  paddle/phi/backends/gpu/musa/mudnn_desc.h
  paddle/phi/backends/gpu/musa/mudnn_helper.h
  paddle/phi/kernels/CMakeLists.txt
  paddle/phi/kernels/funcs/CMakeLists.txt
  paddle/phi/kernels/funcs/softmax.cu
  paddle/phi/kernels/gpu/activation_kernel.cu
  paddle/phi/kernels/gpu/cross_entropy_kernel.cu
  paddle/phi/kernels/gpu/embedding_kernel.cu
  paddle/phi/kernels/gpu/gelu_grad_kernel.cu
  paddle/phi/kernels/gpu/gelu_kernel.cu
  paddle/phi/kernels/gpu/numel_kernel.cu
  paddle/phi/kernels/gpudnn/affine_grid_grad_kernel.cu
  paddle/phi/kernels/gpudnn/affine_grid_kernel.cu
  paddle/phi/kernels/gpudnn/conv_gpudnn_info.h
  paddle/phi/kernels/gpudnn/conv_grad_kernel.cu
  paddle/phi/kernels/gpudnn/conv_kernel.cu
  paddle/phi/kernels/gpudnn/conv_mudnn_helper.h
  paddle/phi/kernels/gpudnn/conv_transpose_grad_kernel.cu
  paddle/phi/kernels/gpudnn/conv_transpose_kernel.cu
  paddle/phi/kernels/gpudnn/pool_grad_kernel.cu
  paddle/phi/kernels/gpudnn/pool_kernel.cu
  paddle/phi/kernels/gpudnn/softmax_gpudnn.h
  paddle/phi/kernels/impl/conv_cudnn_impl.h
  patches/gloo/device.cc.patch
  patches/gloo/error.h.patch
  python/paddle/distributed/launch/utils/nvsmi.py
  test/collective/fleet/test_dygraph_sharding_stage2.py
  test/collective/fleet/test_dygraph_sharding_stage3_for_eager.py
  test/collective/fleet/test_parallel_dygraph_mp_layers.py
  test/collective/fleet/test_parallel_dygraph_sharding_parallel.py
  test/legacy_test/test_softmax_with_cross_entropy_op.py
Labels: contributor

#64947 [CINN][ROCM] fix compilation error when -DWITH_ROCM=ON -DWITH_CINN=ON
  cmake/cinn/external/absl.cmake
  cmake/hip.cmake
Labels: contributor

#64997 [oneDNN] Fix oneDNN kernel of fusion_lstm
  paddle/phi/kernels/fusion/onednn/fusion_lstm_kernel.cc
Labels: Intel, contributor

#64519 【Hackathon 6th No.2】【Typing】为 Paddle 新增 cholesky_inverse API -part
  python/paddle/linalg.py
  python/paddle/tensor/__init__.py
  python/paddle/tensor/linalg.py
  test/legacy_test/CMakeLists.txt
  test/legacy_test/test_linalg_cholesky_inverse.py
Labels: PaddlePaddle Hackathon, contributor, API

#64793 【Hackathon 6th No.31】gaussian kernel and normal api support complex -part
  paddle/phi/kernels/cpu/gaussian_inplace_grad_kernel.cc
  paddle/phi/kernels/cpu/gaussian_kernel.cc
  paddle/phi/kernels/funcs/norm_distribution.h
  paddle/phi/kernels/gpu/gaussian_inplace_grad_kernel.cu
  paddle/phi/kernels/gpu/gaussian_kernel.cu
  python/paddle/tensor/random.py
  test/legacy_test/test_normal.py
  test/legacy_test/test_normal_inplace.py
Labels: PaddlePaddle Hackathon, contributor, API

#65002 [Prim] Modify the reduce_as op
  paddle/fluid/primitive/rule/vjp/details.h
  paddle/phi/kernels/cpu/reduce_as_grad_kernel.cc
  paddle/phi/kernels/cpu/reduce_as_kernel.cc
  paddle/phi/kernels/gpu/reduce_as_grad_kernel.cu
  paddle/phi/kernels/gpu/reduce_as_kernel.cu
  test/deprecated/legacy_test/test_reduce_as_op.py
Labels: contributor

#64552 【Hackathon 6th No.11】Add log_normal and log_normal_ API to Paddle
  python/paddle/__init__.py
  python/paddle/tensor/__init__.py
  python/paddle/tensor/random.py
  test/legacy_test/test_log_normal.py
  test/legacy_test/test_log_normal_inplace.py
Labels: PaddlePaddle Hackathon, contributor, API

#64909 【Error Message No.25】Replace paddle/cinn/hlir/pe/*
  paddle/cinn/hlir/framework/pir/compilation_task.cc
  paddle/cinn/hlir/pe/broadcast.cc
  paddle/cinn/hlir/pe/elementwise.cc
  paddle/cinn/hlir/pe/ir_schedule_pe.cc
  paddle/cinn/hlir/pe/map_expr_to_ir.cc
  paddle/cinn/hlir/pe/nn.cc
  paddle/cinn/hlir/pe/nn_util.cc
  paddle/cinn/hlir/pe/reduction.cc
  paddle/cinn/hlir/pe/schedule.cc
  paddle/cinn/hlir/pe/transform.cc
Labels: contributor, HappyOpenSource

#64987 【Error Message No.26】Replace paddle/cinn/ir/*
  paddle/cinn/ir/group_schedule/st_shape_group_scheduler.cc
  paddle/cinn/ir/group_schedule/tactic/arrange_storage_tactic.cc
  paddle/cinn/ir/group_schedule/tactic/optimize_reduction_tactic.cc
  paddle/cinn/ir/intrinsic_ops.cc
  paddle/cinn/ir/ir.cc
  paddle/cinn/ir/ir.h
  paddle/cinn/ir/ir_analyzer/ir_analyzer.cc
  paddle/cinn/ir/ir_base.cc
  paddle/cinn/ir/ir_base.h
  paddle/cinn/ir/ir_printer.cc
  paddle/cinn/ir/layout.cc
  paddle/cinn/ir/lowered_func.cc
  paddle/cinn/ir/schedule/factorize_reduction.h
  paddle/cinn/ir/schedule/impl/base.cc
  paddle/cinn/ir/schedule/impl/compute_location.cc
  paddle/cinn/ir/schedule/impl/for_type.cc
  paddle/cinn/ir/schedule/impl/loop_transformation.cc
  paddle/cinn/ir/schedule/impl/reduction.cc
  paddle/cinn/ir/schedule/impl/storage.cc
  paddle/cinn/ir/schedule/ir_schedule.cc
  paddle/cinn/ir/schedule/ir_schedule_util.cc
  paddle/cinn/ir/schedule/ir_schedule_util.h
  paddle/cinn/ir/schedule/schedule_desc.cc
  paddle/cinn/ir/schedule_block_graph.cc
  paddle/cinn/ir/test/schedule_block_graph_test.cc
  paddle/cinn/ir/test/schedule_desc_test.cc
  paddle/cinn/ir/test/st_shape_group_scheduler_test.cc
Labels: contributor, HappyOpenSource

#64019 【Hackathon 6th Fundable Projects 3 No.381】fluid operator top_k
  paddle/fluid/operators/top_k_op.cc
  paddle/fluid/operators/top_k_op.cu
  paddle/fluid/operators/top_k_op.h
  paddle/fluid/operators/top_k_op_xpu.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/unary_infer_sym.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/unary_infer_sym.h
  paddle/phi/core/compat/op_utils.h
  paddle/phi/infermeta/unary.cc
  paddle/phi/infermeta/unary.h
  paddle/phi/kernels/cpu/top_k_grad_kernel.cc
  paddle/phi/kernels/cpu/top_k_kernel.cc
  paddle/phi/kernels/gpu/top_k_grad_kernel.cu
  paddle/phi/kernels/gpu/top_k_kernel.cu
  paddle/phi/kernels/xpu/top_k_kernel.cc
  paddle/phi/ops/yaml/legacy/static_backward.yaml
  paddle/phi/ops/yaml/legacy/static_ops.yaml
  paddle/phi/ops/yaml/op_compat.yaml
  test/legacy_test/test_top_k_op.py
  test/xpu/test_top_k_op_xpu.py
Labels: PaddlePaddle Hackathon, contributor

#64818 【Hackathon 6th Fundable Projects 4 No.5】remove parallel executor in run_program op -part
  paddle/fluid/framework/CMakeLists.txt
  paddle/fluid/framework/details/CMakeLists.txt
  paddle/fluid/framework/details/async_ssa_graph_executor.cc
  paddle/fluid/framework/details/async_ssa_graph_executor.h
  paddle/fluid/framework/details/bind_threaded_ssa_graph_executor.cc
  paddle/fluid/framework/details/bind_threaded_ssa_graph_executor.h
  paddle/fluid/framework/details/fast_threaded_ssa_graph_executor.cc
  paddle/fluid/framework/details/fast_threaded_ssa_graph_executor.h
  paddle/fluid/framework/details/multi_devices_helper.h
  paddle/fluid/framework/details/parallel_ssa_graph_executor.cc
  paddle/fluid/framework/details/parallel_ssa_graph_executor.h
  paddle/fluid/framework/details/scope_buffered_monitor.cc
  paddle/fluid/framework/details/scope_buffered_monitor.h
  paddle/fluid/framework/details/scope_buffered_ssa_graph_executor.cc
  paddle/fluid/framework/details/scope_buffered_ssa_graph_executor.h
  paddle/fluid/framework/details/ssa_graph_executor.cc
  paddle/fluid/framework/details/ssa_graph_executor.h
  paddle/fluid/framework/details/threaded_ssa_graph_executor.cc
  paddle/fluid/framework/details/threaded_ssa_graph_executor.h
  paddle/fluid/framework/executor_cache.cc
  paddle/fluid/framework/executor_cache.h
  paddle/fluid/framework/new_executor/executor_statistics.cc
  paddle/fluid/framework/parallel_executor.cc
  paddle/fluid/framework/parallel_executor.h
  paddle/fluid/jit/CMakeLists.txt
  paddle/fluid/operators/run_program_op.h
  paddle/fluid/pybind/compiled_program.cc
  paddle/fluid/pybind/place.cc
  paddle/fluid/pybind/pybind.cc
  paddle/fluid/pybind/tensor.cc
  python/paddle/base/core.py
  python/paddle/jit/dy2static/partial_program.py
  python/paddle/jit/dy2static/pir_partial_program.py
  test/deprecated/legacy_test/CMakeLists.txt
  test/legacy_test/CMakeLists.txt
  tools/windows/run_unittests.sh
Labels: PaddlePaddle Hackathon, contributor

#64608 【Hackathon 6th Fundable Projects 2 No.31】Fix modernize-loop-convert-final
  paddle/fluid/distributed/ps/table/common_graph_table.cc
  paddle/fluid/framework/ir/delete_remove_padding_recover_padding_pass.cc
  paddle/fluid/inference/tensorrt/dynamic_shape_infermeta.cc
  paddle/fluid/pir/dialect/distributed/transforms/dist_to_dense_pass.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/multiary_infer_sym.cc
  paddle/fluid/pir/dialect/operator/ir/op_dialect.cc
  paddle/fluid/pir/drr/src/rewrite_pattern.cc
  paddle/fluid/pir/serialize_deserialize/src/ir_serialize.cc
  paddle/fluid/pir/transforms/pd_op_to_kernel_pass.cc
  paddle/fluid/primitive/base/decomp_trans.cc
  paddle/phi/core/distributed/auto_parallel/reshard/r_to_x_reshard_function.cc
  paddle/phi/core/distributed/auto_parallel/reshard/x_to_r_reshard_function.cc
  paddle/phi/infermeta/spmd_rules/slice.cc
  paddle/phi/infermeta/spmd_rules/squeeze.cc
  paddle/phi/kernels/reduce_kernel_impl.cc
  paddle/phi/kernels/stride/as_real_kernel.cc
  paddle/pir/src/core/region.cc
  paddle/pir/src/dialect/shape/utils/shape_analysis.cc
Labels: PaddlePaddle Hackathon, contributor

#64915 【Hackathon 6th Fundable Projects 3 No.342】sequence_pool
  paddle/fluid/operators/ops_signature/sequence_pool_sig.cc
  paddle/fluid/operators/sequence_ops/sequence_pool_op.cc
  paddle/phi/infermeta/unary.cc
  paddle/phi/infermeta/unary.h
  paddle/phi/ops/yaml/backward.yaml
  paddle/phi/ops/yaml/op_compat.yaml
  paddle/phi/ops/yaml/ops.yaml
Labels: PaddlePaddle Hackathon, contributor

#65012 Fix calsses classes
  python/paddle/amp/auto_cast.py
  python/paddle/base/dataset.py
  python/paddle/decomposition/recompute.py
  python/paddle/device/cuda/cuda_graphed_layer.py
  python/paddle/pir_utils.py
Labels: contributor, HappyOpenSource

#65046 【Hackathon 6th Fundable Projects 3 No.377】 temporal_shift
  paddle/fluid/operators/temporal_shift_op.cu
  paddle/fluid/operators/temporal_shift_op.h
Labels: PaddlePaddle Hackathon, contributor

#64773 【Hackathon 6th Fundable Projects 2 No.29】 Fix modernize-concat-nested-namespaces-part-19
  paddle/fluid/distributed/fleet_executor/cond_interceptor.cc
  paddle/fluid/distributed/fleet_executor/interceptor.cc
  paddle/fluid/distributed/ps/service/brpc_ps_server.cc
  paddle/fluid/distributed/ps/table/ctr_dymf_accessor.cc
  paddle/fluid/distributed/ps/table/tensor_accessor.cc
  paddle/fluid/eager/auto_code_generator/eager_generator.cc
  paddle/fluid/framework/io/crypto/aes_cipher.cc
  paddle/fluid/framework/ir/conv2d_trans_filter_dilations_nxn_to_1x1_pass.cc
  paddle/fluid/framework/ir/elementwiseadd_transpose_pass.cc
  paddle/fluid/framework/ir/fused_attention_pass.cc
  paddle/fluid/framework/ir/graph_pattern_detector.cc
  paddle/fluid/framework/ir/onednn/onednn_placement_pass.cc
  paddle/fluid/framework/new_executor/instruction/control_flow/tuple_push_instruction.cc
  paddle/fluid/framework/op_info.cc
  paddle/fluid/framework/op_kernel_type.cc
  paddle/fluid/imperative/amp_auto_cast.cc
  paddle/fluid/imperative/gradient_accumulator.cc
  paddle/fluid/imperative/layout_autotune.cc
  paddle/fluid/imperative/profiler.cc
  paddle/fluid/inference/analysis/helper.cc
  paddle/fluid/inference/tensorrt/convert/bilinear_interp_v2_op.cc
  paddle/fluid/inference/tensorrt/convert/cast_op.cc
  paddle/fluid/inference/tensorrt/convert/expand_v2_op.cc
  paddle/fluid/inference/tensorrt/convert/flash_multihead_matmul_op.cc
  paddle/fluid/inference/tensorrt/convert/flatten_contiguous_range_op.cc
  paddle/fluid/inference/tensorrt/convert/preln_skip_layernorm.cc
  paddle/fluid/inference/tensorrt/convert/recover_padding_op.cc
  paddle/fluid/inference/tensorrt/convert/silu_op.cc
  paddle/fluid/inference/tensorrt/convert/swish_op.cc
  paddle/fluid/inference/tensorrt/convert/tanhshrink_op.cc
  paddle/fluid/inference/tensorrt/convert/test_custom_plugin_creater.cc
  paddle/fluid/inference/tensorrt/engine.cc
  paddle/fluid/memory/allocation/auto_growth_best_fit_allocator_v2.cc
  paddle/fluid/memory/allocation/cuda_ipc_allocator.cc
  paddle/fluid/operators/collective/barrier_op.cc
  paddle/fluid/operators/collective/c_sync_calc_stream_op.cc
  paddle/fluid/operators/pscore/send_barrier_op.cc
  paddle/fluid/operators/reduce_ops/logsumexp_op.cc
  paddle/fluid/platform/device/gpu/cuda/cuda_profiler.cc
  paddle/fluid/platform/profiler/dump/serialization_logger.cc
  paddle/fluid/platform/profiler/xpu_tracer.cc
  paddle/phi/api/lib/data_transform.cc
  paddle/phi/infermeta/sparse/backward.cc
  paddle/phi/infermeta/spmd_rules/flatten.cc
  paddle/phi/kernels/autotune/cache.cc
  paddle/phi/kernels/funcs/deformable_conv_functor.cc
  paddle/phi/kernels/funcs/jit/gen/matmul.cc
  paddle/pir/src/core/value_impl.cc
  paddle/utils/string/pretty_log.cc
Labels: PaddlePaddle Hackathon, contributor

#65042 [Typing][A-13] Add type annotations for `paddle/tensor/to_string.py`
  python/paddle/tensor/to_string.py
Labels: PaddlePaddle Hackathon, contributor

#64967 fix ci train grad
  test/ir/pir/cinn/sub_graphs/base.py
Labels: contributor

#64991 [Typing] type checking with apis
  python/paddle/tensor/math.py
  tools/sampcd_processor_utils.py
  tools/type_checking.py
Labels: PaddlePaddle Hackathon, contributor

#63883 【Hackathon 6th No.5】Add chi2/LKJCholesky API to Paddle -part
  python/paddle/distribution/__init__.py
  python/paddle/distribution/chi2.py
  python/paddle/distribution/lkj_cholesky.py
  test/deprecated/distribution/CMakeLists.txt
  test/deprecated/distribution/test_distribution_chi2_static.py
  test/deprecated/distribution/test_distribution_lkj_cholesky_static.py
  test/distribution/test_distribution_chi2.py
  test/distribution/test_distribution_lkj_cholesky.py
Labels: PaddlePaddle Hackathon, contributor, API

#65064 [Typing][A-64] Add type annotations for `paddle/nn/functional/sparse_attention.py`
  python/paddle/nn/functional/sparse_attention.py
Labels: contributor

#65071 [Typing][A-57] Add type annotations for `paddle/nn/functional/distance.py`
  python/paddle/nn/functional/distance.py
Labels: contributor

#65047 【Hackathon 6th Fundable Projects 3 No.389】 uniform_random_inplace
  paddle/fluid/operators/uniform_random_inplace_op_xpu.cc
  paddle/phi/kernels/xpu/uniform_inplace_grad_kernel.cc
  paddle/phi/kernels/xpu/uniform_inplace_kernel.cc
Labels: contributor

#65009 [Typing][A-1] Add type annotations for `paddle/tensor/array.py`
  python/paddle/jit/sot/translate.py
  python/paddle/tensor/array.py
Labels: PaddlePaddle Hackathon, contributor

#65066 [CINN] Bind ShapeConstraintIRAnalysis and ShapeOrDataDimExprs to python level
  paddle/fluid/pybind/pir.cc
Labels: contributor

#64993 【Hackathon 6th Fundable Projects 3 No.220】logsumexp int
  paddle/fluid/operators/ops_signature/logsumexp_sig.cc
  paddle/fluid/operators/reduce_ops/logsumexp_op.cc
  paddle/fluid/operators/reduce_ops/logsumexp_op_xpu.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/unary_infer_sym.cc
  paddle/phi/infermeta/unary.cc
  paddle/phi/infermeta/unary.h
  paddle/phi/kernels/gpu/logsumexp_kernel.cu
  paddle/phi/kernels/impl/logsumexp_grad_kernel_impl.h
  paddle/phi/kernels/impl/logsumexp_kernel_impl.h
  paddle/phi/kernels/logsumexp_grad_kernel.h
  paddle/phi/kernels/logsumexp_kernel.h
  paddle/phi/kernels/xpu/logsumexp_kernel.cc
  paddle/phi/ops/yaml/backward.yaml
  paddle/phi/ops/yaml/legacy/backward_exclude.yaml
  paddle/phi/ops/yaml/legacy/ops_exclude.yaml
  paddle/phi/ops/yaml/ops.yaml
Labels: PaddlePaddle Hackathon, contributor

#64990 【Hackathon 6th Fundable Projects 3 No.243】mul static
  paddle/fluid/operators/mul_op.cc
  paddle/fluid/operators/ops_signature/mul_sig.cc
  paddle/phi/ops/yaml/legacy/static_backward.yaml
  paddle/phi/ops/yaml/legacy/static_ops.yaml
  test/cpp/imperative/CMakeLists.txt
Labels: PaddlePaddle Hackathon, contributor

#65090 [Typing] Fix type checking duplicate and speedup tensor stub generation
  tools/gen_tensor_stub.py
  tools/type_checking.py
Labels: PaddlePaddle Hackathon, contributor

#65087 [Typing][A-30,A-31] Add typing annotations for `paddle/nn/initializer/dirac.py`
  python/paddle/nn/initializer/dirac.py
  python/paddle/nn/initializer/initializer.py
Labels: contributor, HappyOpenSource

#65065 [CINN] Add fusion fallback pass
  paddle/cinn/hlir/dialect/operator/transforms/add_cinn_pass.cc
  paddle/cinn/hlir/dialect/operator/transforms/fusion_fallback_pass.cc
  paddle/cinn/hlir/dialect/operator/transforms/fusion_fallback_pass.h
  paddle/common/flags.cc
  test/cinn/CMakeLists.txt
  test/cinn/passes/test_fusion_fallback_pass.py
Labels: contributor

#65095 [Typing][A-29] Add type annotations for `paddle/nn/initializer/constant.py`
  python/paddle/nn/initializer/constant.py
Labels: contributor, HappyOpenSource

#63721 [DCU] new features
  cmake/external/flashattn.cmake
  cmake/hip.cmake
  cmake/third_party.cmake
  paddle/fluid/operators/matmul_op.cc
  paddle/phi/backends/dynload/flashattn.h
  paddle/phi/common/float16.h
  paddle/phi/infermeta/ternary.cc
  paddle/phi/infermeta/unary.cc
  paddle/phi/kernels/CMakeLists.txt
  paddle/phi/kernels/cpu/weight_quantize_kernel.cc
  paddle/phi/kernels/funcs/blas/blas_impl.hip.h
  paddle/phi/kernels/funcs/fc_functor.cu
  paddle/phi/kernels/funcs/load_store_util.h
  paddle/phi/kernels/funcs/quant_dequant.h
  paddle/phi/kernels/fusion/gpu/block_attn.h
  paddle/phi/kernels/fusion/gpu/block_multi_head_attention_kernel.cu
  paddle/phi/kernels/fusion/gpu/fused_bias_act_kernel.cu
  paddle/phi/kernels/fusion/gpu/fused_bias_act_utils.h
  paddle/phi/kernels/fusion/gpu/mmha_util.cu.h
  paddle/phi/kernels/fusion/gpu/quant_dequant_kernel.h
  paddle/phi/kernels/gpu/batch_norm_grad_kernel.cu
  paddle/phi/kernels/gpu/batch_norm_kernel.cu
  paddle/phi/kernels/gpu/flash_attn_grad_kernel.cu
  paddle/phi/kernels/gpu/flash_attn_kernel.cu
  paddle/phi/kernels/gpu/flash_attn_utils.h
  paddle/phi/kernels/gpu/gelu_funcs.h
  paddle/phi/kernels/gpu/matmul_kernel.cu
  paddle/phi/kernels/gpu/multiclass_nms3_kernel.cu
  paddle/phi/kernels/gpu/weight_dequantize_kernel.cu
  paddle/phi/kernels/gpu/weight_quantize_kernel.cu
  paddle/phi/kernels/impl/matmul_kernel_impl.h
  paddle/phi/kernels/impl/quant_linear_kernel_impl.h
  paddle/phi/kernels/impl/weight_quantize_kernel_impl.h
  python/paddle/nn/quant/quantized_linear.py
  python/paddle/utils/cpp_extension/cpp_extension.py
  python/paddle/utils/cpp_extension/extension_utils.py
  test/legacy_test/test_fused_bias_act_op.py
  test/legacy_test/test_fused_layernorm_op.py
  test/legacy_test/test_fused_rotary_position_embedding.py
  test/legacy_test/test_multiclass_nms_op.py
  test/legacy_test/test_quant_linear_op.py
  test/legacy_test/test_rms_norm_op.py
Labels: contributor

#65097 【Hackathon 6th Fundable Projects 3 No.22】bipartite_match
  paddle/fluid/operators/detection/CMakeLists.txt
  paddle/fluid/operators/detection/bipartite_match_op.cc
  paddle/phi/infermeta/unary.cc
  paddle/phi/infermeta/unary.h
  paddle/phi/kernels/cpu/bipartite_match_kernel.cc
  paddle/phi/ops/yaml/op_compat.yaml
  paddle/phi/ops/yaml/ops.yaml
Labels: PaddlePaddle Hackathon, contributor

#65005 [Prim][PIR] Support dynamic shape for subtract_grad
  paddle/fluid/primitive/rule/vjp/details.h
  python/paddle/autograd/backward_utils.py
  test/prim/pir_prim/test_prim_sub_graph_backward_dynamic_shape.py
Labels: contributor

#65127 [Typing][A-18] Add type annotations for `paddle/nn/layer/distance.py`
  python/paddle/nn/layer/distance.py
Labels: contributor, HappyOpenSource

#65119 [Typing] Tensor stub property setter and stub add comment twice
  python/paddle/tensor/tensor.prototype.pyi
  tools/gen_tensor_stub.py
Labels: PaddlePaddle Hackathon, contributor

#65125 [Typing][A-34] Add typing annotations for `paddle/nn/initializer/orthogonal.py `
  python/paddle/nn/initializer/orthogonal.py
Labels: contributor, HappyOpenSource

#65107 [PIR] Add non-existent attribute handler for several ops
  paddle/fluid/ir_adaptor/translator/op_translator.cc
Labels: Intel, contributor

#65130 [CINN][New Hardware Update] replace arch.visit with arch.Match
  paddle/cinn/backends/compiler.cc
  paddle/cinn/backends/extern_func_jit_register.h
  paddle/cinn/frontend/computation.cc
  paddle/cinn/frontend/paddle/model_parser.cc
  paddle/cinn/hlir/framework/instruction.cc
  paddle/cinn/hlir/op/contrib/gather_nd.cc
  paddle/cinn/hlir/op/contrib/repeat.cc
  paddle/cinn/hlir/op/contrib/resize.cc
  paddle/cinn/hlir/op/contrib/sort.cc
  paddle/cinn/hlir/op/nn.cc
  paddle/cinn/hlir/op/reduction.cc
  paddle/cinn/hlir/op/transform.cc
  paddle/cinn/hlir/pe/schedule.cc
  paddle/cinn/hlir/pe/transform.cc
  paddle/cinn/pybind/framework.cc
  paddle/cinn/pybind/frontend.cc
Labels: contributor

#65086 [Typing][A-53] Add type annotations for `paddle/hapi/model_summary.py`
  python/paddle/hapi/model_summary.py
Labels: contributor, HappyOpenSource

#65199 [Typing][Fix] Ensure all workers are running complete before pool terminate
  tools/type_checking.py
Labels: contributor

#65206 [Typing][A-27,A-28,A-32,A-33,A-35,A-36] Add type annotations for `paddle/nn/initializer/*`
  python/paddle/nn/initializer/assign.py
  python/paddle/nn/initializer/bilinear.py
  python/paddle/nn/initializer/constant.py
  python/paddle/nn/initializer/initializer.py
  python/paddle/nn/initializer/kaiming.py
  python/paddle/nn/initializer/normal.py
  python/paddle/nn/initializer/uniform.py
  python/paddle/nn/initializer/xavier.py
Labels: contributor

#65170 Rmsnorm Migration
  paddle/phi/kernels/fusion/gpu/fused_multi_transformer_helper.cu.h
  paddle/phi/kernels/gpu/rms_norm_kernel.cu
  paddle/phi/kernels/rms_norm_kernel.h
  test/legacy_test/test_fused_multi_transformer_op.py
Labels: contributor

#65082 [Typing][A-3] Add type annotations for `paddle/tensor/creation.py`
  python/paddle/base/data_feeder.py
  python/paddle/tensor/creation.py
Labels: contributor, HappyOpenSource

#65205 【Hackathon 6th No.5】Add chi2/LKJCholesky API to Paddle
  python/paddle/distribution/chi2.py
Labels: contributor

#65210 [CINN] add group_schedule SstaticRdynamic_best_config
  paddle/cinn/ir/group_schedule/config/SstaticRdynamic.json
Labels: contributor

#65226 [Typing][A-68] Add type annotations for `paddle/regularizer.py`
  python/paddle/regularizer.py
Labels: contributor

#65076 [Typing][A-39,A-47,A-51] Add type annotations for `paddle/optimizer/optimizer.py`
  python/paddle/_typing/shape.py
  python/paddle/base/dygraph/base.py
  python/paddle/nn/layer/layers.py
  python/paddle/optimizer/adam.py
  python/paddle/optimizer/optimizer.py
  python/paddle/optimizer/sgd.py
  python/paddle/static/input.py
Labels: contributor, HappyOpenSource

#65148 [Prim][PIR] Support dynamic shape for concat_grad
  paddle/fluid/primitive/rule/vjp/details.h
  python/paddle/autograd/backward_utils.py
  test/prim/pir_prim/test_prim_sub_graph_backward_dynamic_shape.py
Labels: contributor

#65139 [CINN] Add symbol check logic to OpTest
  paddle/fluid/pybind/pir.cc
  paddle/pir/src/dialect/shape/transforms/shape_optimization_pass.cc
  test/deprecated/legacy_test/test_slice_op.py
  test/legacy_test/__init__.py
  test/legacy_test/op_test.py
  test/legacy_test/test_gather_op.py
  test/legacy_test/test_reshape_op.py
Labels: contributor

#65112 [PIR] Add attribute for several ops for some failed model
  paddle/fluid/ir_adaptor/translator/op_translator.cc
Labels: Intel, contributor

#64430 [Prim][PIR] support unbind op forward in prim pir
  paddle/fluid/pir/dialect/op_generator/decomp_interface_gen_op_list.py
  paddle/fluid/primitive/composite/composite.h
  test/deprecated/legacy_test/test_unbind_op.py
  test/ir/pir/cinn/symbolic/test_infer_sym_shape_unary_op.py
  test/prim/pir_prim/test_prim_sub_graph_dynamic_shape.py
Labels: contributor

#65236 [Typing][A-40,A-41,A-42] Add type annotations for some optimizers (adamax, adamw, asgd)
  python/paddle/optimizer/adam.py
  python/paddle/optimizer/adamax.py
  python/paddle/optimizer/adamw.py
  python/paddle/optimizer/asgd.py
  python/paddle/optimizer/sgd.py
Labels: contributor

#65059 [CINN]add best config search pipeline
  test/cpp/pir/cinn/tile_config_searcher_test.cc
Labels: contributor

#65224 [CINN] Normalize cinn reduce ops attribute names
  paddle/cinn/hlir/dialect/operator/ir/ops.yaml
  paddle/cinn/hlir/dialect/operator/transforms/cinn_to_pd_util.cc
  paddle/cinn/hlir/dialect/operator/transforms/group_merge/group_with_group_merge_pass_utils.h
  paddle/cinn/hlir/dialect/operator/transforms/group_merge/group_with_group_merge_util.h
  paddle/cinn/hlir/dialect/operator/transforms/group_merge/op_with_group_merge_util.h
  paddle/cinn/hlir/dialect/operator/transforms/pd_to_cinn_pass.cc
  paddle/cinn/hlir/framework/op_lowering_util.cc
  paddle/cinn/hlir/framework/pir/op_lowering_util.cc
  paddle/cinn/hlir/framework/pir/op_mapper.cc
  paddle/cinn/hlir/op/op_broadcast_test.cc
  paddle/cinn/hlir/op/reduction.cc
  paddle/cinn/hlir/op/reduction_test.cc
  paddle/cinn/hlir/pass/check_fusion_accuracy_pass.cc
  paddle/cinn/hlir/pass/fusion_helper_base.h
  paddle/cinn/hlir/pass/fusion_merge_pass_util.h
  paddle/cinn/hlir/pass/general_fusion_merge_pass_utils.h
  paddle/cinn/hlir/pass/op_fusion_pass_util.h
  paddle/cinn/hlir/pass/reduce_split_pass.cc
  paddle/cinn/operator_fusion/utils.h
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/cinn_op_infer_sym.cc
Labels: contributor

#65166 fix test_sub_graph_7 and test_sub_graph_9
  test/ir/pir/cinn/sub_graphs/CMakeLists.txt
  test/ir/pir/cinn/sub_graphs/test_sub_graph_7.py
  test/ir/pir/cinn/sub_graphs/test_sub_graph_9.py
Labels: contributor

#65247 [Typing][A-43] Add type annotations for `paddle/optimizer/lamb.py`
  python/paddle/optimizer/lamb.py
Labels: contributor

#65249 [Typing][A-9] Add type annotations for `paddle/tensor/ops.py`
  python/paddle/tensor/layer_function_generator.py
  python/paddle/tensor/ops.py
Labels: contributor

#65269 [CINN] Unify pd_op.prod attributes with cinn_op.reduce_prod
  paddle/cinn/hlir/dialect/operator/transforms/cinn_to_pd_util.cc
  paddle/phi/ops/yaml/backward.yaml
  paddle/phi/ops/yaml/legacy/static_backward.yaml
  paddle/phi/ops/yaml/legacy/static_ops.yaml
  paddle/phi/ops/yaml/op_compat.yaml
  paddle/phi/ops/yaml/ops.yaml
Labels: contributor

#65272 [Typing][A-10] Add type annotations for `paddle/tensor/random.py`
  python/paddle/tensor/random.py
Labels: contributor

#65191 [Typing][A-54,A-55,A-56] Add type annotations for `paddle/nn/functional/{activation.py, common.py, conv.py}`
  python/paddle/_typing/basic.py
  python/paddle/_typing/layout.py
  python/paddle/nn/functional/activation.py
  python/paddle/nn/functional/common.py
  python/paddle/nn/functional/conv.py
  python/paddle/tensor/creation.py
Labels: contributor, HappyOpenSource

#65277 [Typing] Update `_ParameterConfig` in Optimizer
  python/paddle/optimizer/adam.py
  python/paddle/optimizer/adamax.py
  python/paddle/optimizer/adamw.py
  python/paddle/optimizer/lamb.py
  python/paddle/optimizer/optimizer.py
  python/paddle/optimizer/sgd.py
Labels: contributor

#65290 [Typing][A-75] Add type annotations for `python/paddle/vision/models/googlenet.py`
  python/paddle/vision/models/googlenet.py
Labels: contributor

#65255 [Typing][A-2,A-4] Add type annotations for `paddle/tensor/attribute.py` and `paddle/tensor/einsum.py`
  python/paddle/base/layer_helper_base.py
  python/paddle/tensor/attribute.py
  python/paddle/tensor/einsum.py
  python/paddle/tensor/manipulation.py
  test/legacy_test/test_einsum_v2.py
Labels: contributor

#65173 Clean paddle/fluid/operators/set_value_op.h
  paddle/fluid/operators/set_value_op.cc
  paddle/fluid/operators/set_value_op.h
Labels: contributor

#65198 Clean paddle/fluid/operators/sequence_ops/sequence_softmax_cudnn_op.cu.cc
  paddle/fluid/operators/sequence_ops/sequence_softmax_cudnn_op.cu.cc
Labels: contributor

#65248 Clean paddle/fluid/operators/one_hot_op_xpu.cc
  paddle/fluid/operators/one_hot_op_xpu.cc
Labels: contributor

#65256 【Hackathon 6th Fundable Projects 3 No.214】log_loss
  paddle/fluid/operators/log_loss_op_xpu.cc
  paddle/phi/kernels/xpu/log_loss_grad_kernel.cc
  paddle/phi/kernels/xpu/log_loss_kernel.cc
Labels: contributor

#65189 【Hackathon 6th Fundable Projects 4 No.5】remove run_program_op.h
  paddle/fluid/operators/custom_device_common_op_registry.cc
  paddle/fluid/operators/run_program_op.cc
  paddle/fluid/operators/run_program_op.cu
  paddle/fluid/operators/run_program_op.h
Labels: contributor

#65292 [Typing][A-76] Add type annotations for `python/paddle/vision/models/inceptionv3.py`
  python/paddle/vision/models/inceptionv3.py
Labels: contributor

#65270 [pybind11] fix deprecated `T(handle, bool)`
  paddle/fluid/pybind/eager.cc
  paddle/fluid/pybind/eager_math_op_patch.cc
  paddle/fluid/pybind/pir.cc
  paddle/fluid/pybind/slice_utils.h
Labels: contributor

#65153 【Hackathon 6th Fundable Projects 3 No.155】fused_embedding_fc_lstm
  paddle/fluid/operators/fused/fused_embedding_fc_lstm_op.cc
  paddle/fluid/operators/fused/fused_embedding_fc_lstm_op.h
  paddle/fluid/pir/dialect/op_generator/ops_api_gen.py
  paddle/phi/infermeta/fusion.cc
  paddle/phi/infermeta/fusion.h
  paddle/phi/kernels/fusion/cpu/fused_embedding_fc_lstm_kernel.cc
  paddle/phi/ops/yaml/fused_ops.yaml
  paddle/phi/ops/yaml/op_compat.yaml
Labels: contributor

#65154 【Hackathon 6th Fundable Projects 3 No.4】add_position_encoding
  paddle/fluid/operators/add_position_encoding_op.cc
  paddle/fluid/operators/add_position_encoding_op.h
  paddle/phi/infermeta/unary.cc
  paddle/phi/infermeta/unary.h
  paddle/phi/kernels/cpu/add_position_encoding_grad_kernel.cc
  paddle/phi/kernels/cpu/add_position_encoding_kernel.cc
  paddle/phi/ops/yaml/backward.yaml
  paddle/phi/ops/yaml/op_compat.yaml
  paddle/phi/ops/yaml/ops.yaml
Labels: contributor

#65151 【Hackathon 6th Fundable Projects 3 No.5】affine_channel
  paddle/fluid/operators/affine_channel_op.cc
  paddle/fluid/operators/affine_channel_op.cu
  paddle/fluid/operators/affine_channel_op_xpu.cc
  paddle/phi/infermeta/ternary.cc
  paddle/phi/infermeta/ternary.h
  paddle/phi/kernels/cpu/affine_channel_grad_kernel.cc
  paddle/phi/kernels/cpu/affine_channel_kernel.cc
  paddle/phi/kernels/gpu/affine_channel_grad_kernel.cu
  paddle/phi/kernels/gpu/affine_channel_kernel.cu
  paddle/phi/kernels/xpu/affine_channel_grad_kernel.cc
  paddle/phi/kernels/xpu/affine_channel_kernel.cc
  paddle/phi/ops/yaml/backward.yaml
  paddle/phi/ops/yaml/op_compat.yaml
  paddle/phi/ops/yaml/ops.yaml
Labels: contributor

#65122 【Hackathon 6th Fundable Projects 3 No.83】cvm
  paddle/fluid/operators/cvm_op.cc
  paddle/fluid/operators/cvm_op.cu
  paddle/fluid/operators/cvm_op.h
  paddle/phi/infermeta/binary.cc
  paddle/phi/infermeta/binary.h
  paddle/phi/kernels/cpu/cvm_grad_kernel.cc
  paddle/phi/kernels/cpu/cvm_kernel.cc
  paddle/phi/kernels/gpu/cvm_grad_kernel.cu
  paddle/phi/kernels/gpu/cvm_kernel.cu
  paddle/phi/kernels/impl/cvm_kernel_impl.h
  paddle/phi/ops/yaml/backward.yaml
  paddle/phi/ops/yaml/op_compat.yaml
  paddle/phi/ops/yaml/ops.yaml
Labels: PaddlePaddle Hackathon, contributor

#65164 【Hackathon 6th Fundable Projects 3 No.226】match_matrix_tensor
  paddle/fluid/operators/match_matrix_tensor_op.cc
  paddle/fluid/operators/match_matrix_tensor_op.h
  paddle/fluid/pir/dialect/operator/utils/utils.cc
  paddle/phi/kernels/cpu/match_matrix_tensor_kernel.cc
  paddle/phi/ops/yaml/backward.yaml
  paddle/phi/ops/yaml/inconsistent/static_backward.yaml
  paddle/phi/ops/yaml/inconsistent/static_ops.yaml
  paddle/phi/ops/yaml/op_compat.yaml
  paddle/phi/ops/yaml/ops.yaml
Labels: contributor

#65192 【Hackathon 6th Fundable Projects 3 No.12】attention_lstm
  paddle/fluid/operators/attention_lstm_op.cc
  paddle/fluid/operators/attention_lstm_op.h
  paddle/phi/infermeta/multiary.cc
  paddle/phi/infermeta/multiary.h
  paddle/phi/kernels/cpu/attention_lstm_kernel.cc
  paddle/phi/ops/yaml/op_compat.yaml
  paddle/phi/ops/yaml/ops.yaml
Labels: contributor

#65300 [Typing][A-6] Add type annotations for `paddle/tensor/logic.py`
  python/paddle/distributed/fleet/meta_parallel/pipeline_parallel.py
  python/paddle/distributed/fleet/meta_parallel/pp_utils/four_directions_p2p_communication.py
  python/paddle/distributed/fleet/meta_parallel/pp_utils/p2p_communication.py
  python/paddle/tensor/logic.py
  test/legacy_test/test_Tensor_type.py
Labels: contributor

#65193 【Hackathon 6th Fundable Projects 3 No.222】lookup_table_dequant
  paddle/fluid/operators/lookup_table_dequant_op.cc
  paddle/fluid/operators/lookup_table_dequant_op.h
  paddle/phi/infermeta/binary.cc
  paddle/phi/infermeta/binary.h
  paddle/phi/kernels/cpu/lookup_table_dequant_kernel.cc
  paddle/phi/ops/yaml/op_compat.yaml
  paddle/phi/ops/yaml/ops.yaml
  test/legacy_test/test_lookup_table_dequant_op.py
Labels: contributor

#65160 【Hackathon 6th Fundable Projects 3 No.192】hinge_loss
  paddle/fluid/operators/hinge_loss_op.cc
  paddle/fluid/operators/hinge_loss_op.h
  paddle/phi/infermeta/binary.cc
  paddle/phi/infermeta/binary.h
  paddle/phi/kernels/cpu/hinge_loss_grad_kernel.cc
  paddle/phi/kernels/cpu/hinge_loss_kernel.cc
  paddle/phi/kernels/gpu/hinge_loss_grad_kernel.cu
  paddle/phi/kernels/gpu/hinge_loss_kernel.cu
  paddle/phi/kernels/impl/hinge_loss_kernel_impl.h
  paddle/phi/ops/yaml/backward.yaml
  paddle/phi/ops/yaml/op_compat.yaml
  paddle/phi/ops/yaml/ops.yaml
  test/legacy_test/test_hinge_loss_op.py
Labels: contributor

#65077 【Hackathon 6th Fundable Projects 4 No.3】remove `ExecutionStrategy`
  paddle/fluid/framework/details/execution_strategy.h
  paddle/fluid/framework/details/op_handle_base.h
  paddle/fluid/framework/distributed_strategy.proto
  paddle/fluid/framework/ir/memory_optimize_pass/memory_reuse_pass.cc
  python/paddle/distributed/fleet/base/distributed_strategy.py
Labels: PaddlePaddle Hackathon, contributor

#65328 Complementary implementation of rmsnorm
  paddle/phi/kernels/fusion/gpu/fused_multi_transformer_helper.cu.h
  paddle/phi/kernels/gpu/rms_norm_kernel.cu
  paddle/phi/kernels/rms_norm_kernel.h
Labels: contributor

#65332 [Typing][A-84] Add type annotations for `python/paddle/vision/models/squeezenet.py`
  python/paddle/vision/models/squeezenet.py
Labels: contributor

#65323 [Typing][A-78] Add type annotations for ` python/paddle/vision/models/mobilenetv1.py`
  python/paddle/vision/models/mobilenetv1.py
Labels: contributor

#65326 [Typing][A-79] Add type annotations for `python/paddle/vision/models/mobilenetv2.py`
  python/paddle/vision/models/mobilenetv2.py
Labels: contributor

#65280 [CINN]Add tensor buffer map checker
  paddle/cinn/hlir/framework/pir/op_lowering_impl.cc
  paddle/cinn/optim/CMakeLists.txt
  paddle/cinn/optim/check_tensor_buffer_map.cc
  paddle/cinn/optim/check_tensor_buffer_map.h
  paddle/cinn/runtime/flags.cc
Labels: contributor

#65319 [Typing] 识别标题中的 debug 关键字进行类型检查
  paddle/scripts/paddle_build.sh
  python/paddle/_typing/__init__.py
  python/paddle/nn/functional/pooling.py
  tools/type_checking.py
Labels: contributor

#65311 [CINN] Normalize cinn to pd operator transformation
  paddle/cinn/hlir/dialect/operator/transforms/cinn_to_pd_util.cc
Labels: contributor

#64381 [Prim][PIR] support square op backward in prim pir
  paddle/fluid/primitive/codegen/gen.py
  paddle/fluid/primitive/rule/vjp/details.h
  test/legacy_test/test_activation_op.py
Labels: contributor

#65266 [CINN] Fix bug of SplitWithNumOpInferSymbolicShape And Add unit test
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/unary_infer_sym.cc
  test/ir/pir/cinn/symbolic/CMakeLists.txt
  test/ir/pir/cinn/symbolic/test_dyshape_split_with_num.py
Labels: contributor

#65329 [CINN][new hardware] HIP second: op register
  paddle/cinn/hlir/op/broadcast.cc
  paddle/cinn/hlir/op/elementwise.cc
  paddle/cinn/hlir/op/nn.cc
  paddle/cinn/hlir/op/transform.cc
Labels: contributor

#65273 [Typing][A-46] Add type annotations for `paddle/optimizer/nadam.py`
  python/paddle/optimizer/nadam.py
Labels: contributor
