Repository PaddlePaddle/Paddle, pull requests merged in 2024-01, with the labels that each got.

#60458 open warning with `paddle.utils.deprecated`
  python/paddle/utils/deprecated.py
  test/legacy_test/CMakeLists.txt
  test/legacy_test/test_deprecated_decorator.py
Labels: contributor, HappyOpenSource

#60335 【PIR OpTest Fix No.23】 fix test_distribute_fpn_proposals_op
  paddle/fluid/pir/dialect/operator/ir/ops.yaml
  test/white_list/pir_op_test_white_list
Labels: contributor

#60332 【PIR OpTest Fix No.16】 fix test_lookup_table_v2_bf16_op
  test/legacy_test/test_lookup_table_v2_bf16_op.py
  test/white_list/pir_op_test_white_list
Labels: contributor

#60355 [pir]Supporting constant_folding_pass for train
  paddle/fluid/pir/transforms/constant_folding_pass.cc
  test/cpp/pir/pattern_rewrite/pattern_rewrite_test.cc
Labels: contributor

#60485 Fix _hiden_size to _hidden_size
  test/dygraph_to_static/seq2seq_dygraph_model.py
  test/dygraph_to_static/test_fallback.py
Labels: contributor, HappyOpenSource

#60025 [xpu]add sine_pos fuse pass and sine_pos xpu kernel
  cmake/external/xpu.cmake
  paddle/fluid/framework/ir/CMakeLists.txt
  paddle/fluid/framework/ir/xpu/sine_pos_fuse_pass.cc
  paddle/fluid/inference/api/paddle_pass_builder.cc
  paddle/phi/api/yaml/fused_ops.yaml
  paddle/phi/backends/xpu/xpu2_op_list.cc
  paddle/phi/infermeta/fusion.cc
  paddle/phi/infermeta/fusion.h
  paddle/phi/kernels/fusion/xpu/sine_pos_xpu_kernel.cc
  paddle/phi/kernels/legacy/xpu/reduce_max_kernel.cc
  paddle/phi/kernels/xpu/activation_kernel.cc
  paddle/phi/kernels/xpu/reduce_max_kernel.cc
  test/ir/inference/test_xpu_sine_pos_pass.py
Labels: contributor

#60517 【CMake opt No.13】Remove CINN DEPS in test/cpp/pir/shape_dialect/CMakeLists.txt
  test/cpp/pir/shape_dialect/CMakeLists.txt
Labels: contributor, HappyOpenSource

#60527 update 2023 security advisory, test=document_fix
  security/README.md
  security/README_cn.md
  security/README_ja.md
  security/advisory/pdsa-2023-004_cn.md
  security/advisory/pdsa-2023-006.md
  security/advisory/pdsa-2023-006_cn.md
  security/advisory/pdsa-2023-007.md
  security/advisory/pdsa-2023-007_cn.md
  security/advisory/pdsa-2023-008.md
  security/advisory/pdsa-2023-008_cn.md
  security/advisory/pdsa-2023-009.md
  security/advisory/pdsa-2023-009_cn.md
  security/advisory/pdsa-2023-010.md
  security/advisory/pdsa-2023-010_cn.md
  security/advisory/pdsa-2023-011.md
  security/advisory/pdsa-2023-011_cn.md
  security/advisory/pdsa-2023-012.md
  security/advisory/pdsa-2023-012_cn.md
  security/advisory/pdsa-2023-013.md
  security/advisory/pdsa-2023-013_cn.md
  security/advisory/pdsa-2023-014.md
  security/advisory/pdsa-2023-014_cn.md
  security/advisory/pdsa-2023-015.md
  security/advisory/pdsa-2023-015_cn.md
  security/advisory/pdsa-2023-016.md
  security/advisory/pdsa-2023-016_cn.md
  security/advisory/pdsa-2023-017.md
  security/advisory/pdsa-2023-017_cn.md
  security/advisory/pdsa-2023-018.md
  security/advisory/pdsa-2023-018_cn.md
  security/advisory/pdsa-2023-019.md
  security/advisory/pdsa-2023-019_cn.md
  security/advisory/pdsa-2023-020.md
  security/advisory/pdsa-2023-020_cn.md
  security/advisory/pdsa-2023-021.md
  security/advisory/pdsa-2023-021_cn.md
  security/advisory/pdsa-2023-022.md
  security/advisory/pdsa-2023-022_cn.md
  security/advisory/pdsa-2023-023.md
  security/advisory/pdsa-2023-023_cn.md
Labels: contributor

#59529 【complex op】No.19 add complex support for triangular_solve
  paddle/phi/kernels/cpu/triangular_solve_grad_kernel.cc
  paddle/phi/kernels/cpu/triangular_solve_kernel.cc
  paddle/phi/kernels/funcs/blas/blas_impl.h
  paddle/phi/kernels/funcs/matrix_reduce.cc
  paddle/phi/kernels/funcs/matrix_reduce.cu
  paddle/phi/kernels/gpu/triangular_solve_grad_kernel.cu
  paddle/phi/kernels/gpu/triangular_solve_kernel.cu
  python/paddle/tensor/linalg.py
  test/legacy_test/test_triangular_solve_op.py
Labels: contributor, HappyOpenSource

#60532 update 2023 security advisory, test=document_fix
  security/README.md
  security/README_cn.md
  security/README_ja.md
  security/advisory/pdsa-2023-004_cn.md
  security/advisory/pdsa-2023-006.md
  security/advisory/pdsa-2023-006_cn.md
  security/advisory/pdsa-2023-007.md
  security/advisory/pdsa-2023-007_cn.md
  security/advisory/pdsa-2023-008.md
  security/advisory/pdsa-2023-008_cn.md
  security/advisory/pdsa-2023-009.md
  security/advisory/pdsa-2023-009_cn.md
  security/advisory/pdsa-2023-010.md
  security/advisory/pdsa-2023-010_cn.md
  security/advisory/pdsa-2023-011.md
  security/advisory/pdsa-2023-011_cn.md
  security/advisory/pdsa-2023-012.md
  security/advisory/pdsa-2023-012_cn.md
  security/advisory/pdsa-2023-013.md
  security/advisory/pdsa-2023-013_cn.md
  security/advisory/pdsa-2023-014.md
  security/advisory/pdsa-2023-014_cn.md
  security/advisory/pdsa-2023-015.md
  security/advisory/pdsa-2023-015_cn.md
  security/advisory/pdsa-2023-016.md
  security/advisory/pdsa-2023-016_cn.md
  security/advisory/pdsa-2023-017.md
  security/advisory/pdsa-2023-017_cn.md
  security/advisory/pdsa-2023-018.md
  security/advisory/pdsa-2023-018_cn.md
  security/advisory/pdsa-2023-019.md
  security/advisory/pdsa-2023-019_cn.md
  security/advisory/pdsa-2023-020.md
  security/advisory/pdsa-2023-020_cn.md
  security/advisory/pdsa-2023-021.md
  security/advisory/pdsa-2023-021_cn.md
  security/advisory/pdsa-2023-022.md
  security/advisory/pdsa-2023-022_cn.md
  security/advisory/pdsa-2023-023.md
  security/advisory/pdsa-2023-023_cn.md
Labels: contributor

#60518 Fix OpTranslatorTest name
  test/ir/pir/translator/CMakeLists.txt
  test/ir/pir/translator/test_c_reduce_min_translator.py
  test/ir/pir/translator/test_op_translator.py
Labels: contributor

#59801 【PIR API adaptor No.90,92】Migrate some ops into pir
  python/paddle/incubate/operators/graph_reindex.py
  python/paddle/vision/ops.py
  test/legacy_test/test_generate_proposals_v2_op.py
  test/legacy_test/test_graph_reindex.py
Labels: contributor, HappyOpenSource

#60551 fix bug of put_along_axis when the input size is very large
  paddle/phi/kernels/funcs/gather_scatter_functor.cu
  test/legacy_test/test_put_along_axis_op.py
Labels: contributor, HappyOpenSource

#60541 [Custom Device]Remove ClearPass to allow Custom Device use fusion under fp16
  paddle/fluid/inference/api/analysis_predictor.cc
Labels: contributor

#60361 [xpu]Add vis_decoder_attention_xpu_pass && modify qkv_attention_xpu_kernel
  paddle/fluid/framework/ir/CMakeLists.txt
  paddle/fluid/framework/ir/xpu/decoder_attention_xpu_fuse_pass.cc
  paddle/fluid/framework/ir/xpu/decoder_attention_xpu_fuse_pass.h
  paddle/fluid/framework/ir/xpu/qk_qkv_attention_xpu_fuse_pass.cc
  paddle/fluid/inference/api/paddle_pass_builder.cc
  paddle/phi/api/yaml/fused_ops.yaml
  paddle/phi/infermeta/fusion.cc
  paddle/phi/infermeta/fusion.h
  paddle/phi/kernels/fusion/xpu/qkv_attention_xpu_kernel.cc
  test/ir/inference/test_xpu_decoder_attention_xpu_fuse_pass.py
Labels: contributor

#60444 [Prim][PIR] support abs, instance_norm op backward in prim pir
  paddle/fluid/primitive/codegen/gen.py
  paddle/fluid/primitive/rule/vjp/details.h
  test/legacy_test/test_activation_op.py
  test/legacy_test/test_instance_norm_op.py
  test/legacy_test/test_instance_norm_op_v2.py
Labels: contributor

#60553 【Hackathon 5th No.25】add gammaln api
  paddle/phi/api/yaml/backward.yaml
  paddle/phi/api/yaml/ops.yaml
  paddle/phi/kernels/cpu/gammaln_grad_kernel.cc
  paddle/phi/kernels/cpu/gammaln_kernel.cc
  paddle/phi/kernels/gammaln_grad_kernel.h
  paddle/phi/kernels/gammaln_kernel.h
  paddle/phi/kernels/gpu/gammaln_grad_kernel.cu
  paddle/phi/kernels/gpu/gammaln_kernel.cu
  paddle/phi/kernels/impl/gammaln_grad_kernel_impl.h
  paddle/phi/kernels/impl/gammaln_kernel_impl.h
  python/paddle/__init__.py
  python/paddle/tensor/__init__.py
  python/paddle/tensor/math.py
  test/legacy_test/test_gammaln_op.py
  test/legacy_test/test_inplace.py
Labels: PaddlePaddle Hackathon, contributor

#59631 【PIR OpTest Fix No.8】 fix test_shuffle_batch_op
  paddle/fluid/pir/dialect/op_generator/ops_api_gen.py
  paddle/fluid/pir/dialect/operator/ir/ops.yaml
  paddle/fluid/pir/dialect/operator/ir/ops_backward.yaml
  paddle/phi/api/yaml/op_compat.yaml
  paddle/phi/infermeta/backward.cc
  paddle/phi/infermeta/backward.h
  paddle/phi/infermeta/binary.cc
  paddle/phi/infermeta/binary.h
  test/white_list/pir_op_test_no_check_list
  test/white_list/pir_op_test_white_list
Labels: contributor

#60255 【PIR OpTest Fix No.14】 fix test_nce
  paddle/fluid/pir/dialect/op_generator/ops_api_gen.py
  paddle/fluid/pir/dialect/operator/ir/ops.yaml
  paddle/fluid/pir/dialect/operator/ir/ops_backward.yaml
  paddle/fluid/pir/dialect/operator/utils/utils.cc
  paddle/phi/api/yaml/op_compat.yaml
  paddle/phi/infermeta/backward.cc
  paddle/phi/infermeta/backward.h
  paddle/phi/infermeta/multiary.cc
  paddle/phi/infermeta/multiary.h
  test/white_list/pir_op_test_white_list
Labels: contributor

#60329 【PIR OpTest Fix No.19】 fix test_ftrl_op
  paddle/fluid/pir/dialect/op_generator/ops_api_gen.py
  paddle/fluid/pir/dialect/operator/ir/ops.yaml
  paddle/fluid/pir/dialect/operator/utils/utils.cc
  paddle/phi/api/yaml/op_compat.yaml
  paddle/phi/infermeta/multiary.cc
  paddle/phi/infermeta/multiary.h
  test/white_list/pir_op_test_white_list
Labels: contributor

#60310 Resubmit PR-58859
  paddle/fluid/pybind/generator_py.cc
  paddle/phi/core/generator.cc
  paddle/phi/core/generator.h
  paddle/phi/kernels/funcs/dropout_impl.cu.h
  paddle/phi/kernels/fusion/gpu/fused_dropout_add_grad_kernel.cu
  paddle/phi/kernels/fusion/gpu/fused_dropout_add_kernel.cu
  python/paddle/device/cuda/cuda_graphed_layer.py
  python/paddle/distributed/fleet/layers/mpu/random.py
  python/paddle/incubate/__init__.py
  python/paddle/incubate/framework/__init__.py
  python/paddle/incubate/framework/random.py
  python/setup.py.in
  setup.py
  test/legacy_test/test_cuda_graphed_layer.py
  test/legacy_test/test_random_generator_set_get_state.py
Labels: NVIDIA, contributor

#60603 Fix words
  test/ir/inference/auto_scan_test.py
  test/ir/inference/program_config.py
  test/ir/inference/test_conv_elementwise_add2_act_fuse_pass.py
  test/ir/inference/test_trt_convert_pad.py
  test/ir/inference/test_trt_convert_reshape.py
  test/ir/inference/test_trt_convert_rnn.py
  test/ir/pass_test.py
  test/ir/pir/test_if_api.py
  test/ir/pir/test_while_api.py
  test/ir/test_fuse_resnet_unit.py
Labels: contributor

#59413 Add CUDNNv8 max pooling
  paddle/fluid/pir/dialect/op_generator/ops_api_gen.py
  paddle/fluid/pir/dialect/op_generator/vjp_interface_black_list.py
  paddle/fluid/pybind/pybind.cc
  paddle/phi/api/yaml/fused_backward.yaml
  paddle/phi/api/yaml/fused_ops.yaml
  paddle/phi/infermeta/unary.cc
  paddle/phi/infermeta/unary.h
  paddle/phi/kernels/CMakeLists.txt
  paddle/phi/kernels/autotune/cache.h
  paddle/phi/kernels/fusion/gpu/max_pool2d_v2_grad_kernel.cu
  paddle/phi/kernels/fusion/gpu/max_pool2d_v2_kernel.cu
  paddle/phi/kernels/gpudnn/pool_gpudnn.h
  test/legacy_test/CMakeLists.txt
  test/legacy_test/test_pool_max_op.py
  test/white_list/no_check_set_white_list.py
  test/white_list/op_accuracy_white_list.py
  tools/gpups_test.sh
Labels: NVIDIA, contributor

#60401 set_pir_tests_properties for some tests
  test/auto_parallel/CMakeLists.txt
  test/mkldnn/CMakeLists.txt
  test/white_list/pir_op_test_white_list
Labels: contributor

#60522 Add tests to whitelist
  test/white_list/pir_op_test_white_list
Labels: contributor

#60590 [PIR] Support Region Clone in Operation::Clone
  paddle/fluid/pybind/pir.cc
  paddle/pir/core/block.h
  paddle/pir/core/ir_mapping.h
  paddle/pir/core/operation.cc
  paddle/pir/core/program.cc
  paddle/pir/core/program.h
  paddle/pir/core/region.cc
  paddle/pir/core/region.h
  test/cpp/pir/core/ir_region_test.cc
Labels: contributor

#60445 PIR API adaptor No.35、40】 Migrate paddle.nn.ChannelShuffle/ClipGradByNorm into pir
  python/paddle/nn/clip.py
  python/paddle/nn/functional/vision.py
  python/paddle/pir/core.py
  test/legacy_test/test_channel_shuffle.py
  test/legacy_test/test_clip_by_norm_op.py
  test/legacy_test/test_gradient_clip.py
Labels: contributor, HappyOpenSource

#60631 Fix words
  test/ir/pir/cinn/symbolic/test_cinn_sub_graph_symbolic.py
  test/ir/pir/fused_pass/pass_test.py
  test/ir/pir/fused_pass/test_conv2d_add_act_fuse_pass.py
  test/ir/pir/fused_pass/test_conv2d_add_fuse_pass.py
  test/ir/pir/fused_pass/test_conv2d_bn_fuse_pass.py
  test/ir/pir/fused_pass/test_fused_weight_only_linear_pass.py
  test/ir/pir/fused_pass/test_pir_fc_elementwise_layernorm_fuse_pass.py
Labels: contributor, HappyOpenSource

#60646 update pdsa-2023-019, test=document_fix
  security/README.md
  security/README_cn.md
  security/README_ja.md
  security/advisory/pdsa-2023-019.md
  security/advisory/pdsa-2023-019_cn.md
Labels: contributor

#60618 Improve the performence of put_along_axis
  paddle/phi/kernels/funcs/gather_scatter_functor.cu
Labels: contributor, HappyOpenSource

#60560 [AutoParallel] Fit vpp for gradient_merge pass
  python/paddle/distributed/passes/auto_parallel_gradient_merge.py
Labels: contributor

#60537 [CI]add test_semi_auto_parallel_hybrid_strategy case
  tools/auto_parallel/ci_auto_parallel.sh
  tools/auto_parallel/ci_case_unit.sh
Labels: contributor

#60649 [cherry-pick]update pdsa-2023-019
  security/README.md
  security/README_cn.md
  security/README_ja.md
  security/advisory/pdsa-2023-019.md
  security/advisory/pdsa-2023-019_cn.md
Labels: contributor

#60595 [Custom Device]enable custom device to use silu_fuse_pass
  paddle/fluid/framework/ir/silu_fuse_pass.cc
  paddle/fluid/inference/analysis/ir_pass_manager.cc
  paddle/fluid/inference/api/analysis_predictor.cc
Labels: contributor

#60565 [XPU]correct adamw bf16 unit test and the way to get data type
  test/xpu/op_test_xpu.py
  test/xpu/test_adamw_op_xpu.py
  test/xpu/test_elementwise_sub_op_xpu.py
Labels: contributor

#60487 Fix some PADDLE_THROW error type and change test cases
  paddle/common/errors.h
  paddle/fluid/pybind/eager_utils.cc
  paddle/fluid/pybind/op_function_common.cc
  python/paddle/nn/functional/vision.py
  test/dygraph_to_static/test_set_static_op_arg_pre_cast_hook.py
  test/legacy_test/test_affine_grid_function.py
  test/legacy_test/test_deformable_conv_op.py
  test/legacy_test/test_fill_constant_op.py
  test/legacy_test/test_gumbel_softmax_op.py
  test/legacy_test/test_layer_norm_op.py
  test/legacy_test/test_mean_op.py
  test/legacy_test/test_numel_op.py
  test/legacy_test/test_randint_op.py
  test/legacy_test/test_reduce_op.py
  test/legacy_test/test_squeeze2_op.py
  test/legacy_test/test_unsqueeze2_op.py
  test/legacy_test/test_where_op.py
Labels: contributor

#58092 【Hackathon 5th No.34】为 Paddle 新增 bitwise_right_shift / bitwise_right_shift_ / bitwise_left_shift / bitwise_left_shift_ API
  paddle/phi/api/yaml/ops.yaml
  paddle/phi/infermeta/binary.cc
  paddle/phi/infermeta/binary.h
  paddle/phi/kernels/bitwise_kernel.h
  paddle/phi/kernels/cpu/bitwise_kernel.cc
  paddle/phi/kernels/funcs/bitwise_functors.h
  paddle/phi/kernels/kps/bitwise_kernel.cu
  python/paddle/__init__.py
  python/paddle/tensor/__init__.py
  python/paddle/tensor/math.py
  test/legacy_test/test_bitwise_shift_op.py
  test/legacy_test/test_inplace.py
Labels: PaddlePaddle Hackathon, contributor

#60616 Enable offset of generator for custom device.
  paddle/phi/core/generator.cc
Labels: contributor

#60656 [xpu]: check op is null
  paddle/fluid/framework/ir/graph_pattern_detector.cc
  paddle/fluid/framework/ir/xpu/link_xpu_op_max_pass.cc
Labels: contributor

#60314 [xpu] fc pass and delete pass nodes check
  paddle/fluid/framework/ir/xpu/delete_isolated_node_pass.cc
  paddle/fluid/framework/ir/xpu/pass_utils.cc
Labels: contributor

#60679 Fix defition definition
  python/paddle/device/cuda/cuda_graphed_layer.py
  python/paddle/distributed/auto_parallel/interface.py
  python/paddle/distributed/auto_parallel/random.py
  python/paddle/distributed/auto_parallel/static/cost/estimate_cost.py
  python/paddle/distributed/auto_parallel/static/cost/op_runtime_cost.py
  python/paddle/distributed/auto_parallel/static/operators/dist_assign.py
  python/paddle/distributed/auto_parallel/static/operators/dist_concat.py
  python/paddle/distributed/auto_parallel/static/operators/dist_cross_entropy.py
  python/paddle/distributed/auto_parallel/static/operators/dist_default.py
  python/paddle/distributed/auto_parallel/static/operators/dist_dropout.py
  python/paddle/distributed/auto_parallel/static/operators/dist_eltwise.py
  python/paddle/distributed/auto_parallel/static/operators/dist_embedding.py
  python/paddle/distributed/auto_parallel/static/operators/dist_fused_rope.py
  python/paddle/distributed/auto_parallel/static/operators/dist_layer_norm.py
  python/paddle/distributed/auto_parallel/static/operators/dist_matmul.py
  python/paddle/distributed/auto_parallel/static/operators/dist_reduce_sum_p.py
  python/paddle/distributed/auto_parallel/static/operators/dist_reshape.py
  python/paddle/distributed/auto_parallel/static/operators/dist_split.py
  python/paddle/distributed/auto_parallel/static/operators/dist_transpose.py
  python/paddle/distributed/auto_parallel/static/operators/dist_unsqueeze2.py
Labels: contributor, HappyOpenSource

#60741 Fix Throughtput Throughput
  python/paddle/decomposition/decomp.py
  python/paddle/distributed/auto_parallel/static/tuner/optimization_tuner.py
  python/paddle/distributed/auto_parallel/static/tuner/profiler.py
Labels: contributor, HappyOpenSource

#60473 【PIR Dist Op Reg No.1】 reg push_sparse_v2
  paddle/fluid/ir_adaptor/translator/op_compat_gen.py
  paddle/fluid/pir/dialect/op_generator/ops_api_gen.py
  paddle/fluid/pir/dialect/operator/ir/ops.yaml
  paddle/fluid/pir/dialect/operator/utils/utils.cc
  paddle/phi/api/yaml/op_compat.yaml
Labels: contributor, HappyOpenSource

#60752 [PIR] change IR clone to const and support clone operation successors
  paddle/cinn/hlir/framework/pir/group.h
  paddle/fluid/pybind/pir.cc
  paddle/pir/core/ir_mapping.h
  paddle/pir/core/operation.cc
  paddle/pir/core/operation.h
  paddle/pir/core/program.cc
  paddle/pir/core/program.h
  paddle/pir/core/region.cc
  paddle/pir/core/region.h
  test/cpp/pir/core/ir_region_test.cc
Labels: contributor

#59890 【Hackathon 5th No.110】为 Paddle 增强 sparse.matmul API
  paddle/fluid/platform/dynload/cusparse.h
  paddle/phi/backends/dynload/cusparse.h
  paddle/phi/kernels/funcs/sparse/sparse_blas.h
  paddle/phi/kernels/funcs/sparse/sparse_blas_impl.cu.h
  paddle/phi/kernels/sparse/gpu/matmul_grad_kernel.cu
  paddle/phi/kernels/sparse/gpu/matmul_kernel.cu
  paddle/phi/kernels/sparse/gpu/transpose_kernel.cu
  paddle/phi/kernels/sparse/impl/unary_kernel_impl.h
  paddle/phi/kernels/sparse/matmul_kernel.h
  test/legacy_test/test_sparse_matmul_op.py
Labels: PaddlePaddle Hackathon, contributor

#60770 Fix rank_relatvie rank_relative
  python/paddle/distributed/auto_parallel/static/cluster.py
  python/paddle/distributed/auto_parallel/static/completion.py
  python/paddle/distributed/auto_parallel/static/dist_tensor.py
  python/paddle/distributed/auto_parallel/static/helper.py
  python/paddle/distributed/auto_parallel/static/utils.py
Labels: contributor, HappyOpenSource

#59847 【Hackathon 5th No.38】为 Paddle 新增 FractionalMaxPool2d / FractionalMaxPool3d API -kernel
  paddle/phi/api/yaml/backward.yaml
  paddle/phi/api/yaml/ops.yaml
  paddle/phi/infermeta/unary.cc
  paddle/phi/infermeta/unary.h
  paddle/phi/kernels/cpu/pool_grad_kernel.cc
  paddle/phi/kernels/cpu/pool_kernel.cc
  paddle/phi/kernels/funcs/pooling.cc
  paddle/phi/kernels/funcs/pooling.cu
  paddle/phi/kernels/funcs/pooling.h
  paddle/phi/kernels/gpu/pool_grad_kernel.cu
  paddle/phi/kernels/gpu/pool_kernel.cu
  paddle/phi/kernels/impl/pool_grad_kernel_impl.h
  paddle/phi/kernels/impl/pool_kernel_impl.h
  paddle/phi/kernels/pool_grad_kernel.h
  paddle/phi/kernels/pool_kernel.h
  python/paddle/nn/__init__.py
  python/paddle/nn/functional/__init__.py
  python/paddle/nn/functional/pooling.py
  python/paddle/nn/layer/__init__.py
  python/paddle/nn/layer/pooling.py
  test/legacy_test/CMakeLists.txt
  test/legacy_test/test_fractional_max_pool2d_api.py
  test/legacy_test/test_fractional_max_pool2d_op.py
  test/legacy_test/test_fractional_max_pool3d_api.py
  test/legacy_test/test_fractional_max_pool3d_op.py
  test/white_list/op_accuracy_white_list.py
  test/white_list/op_threshold_white_list.py
Labels: PaddlePaddle Hackathon, contributor

#60719 Add TestOpWithBackWardTranslator
  test/ir/pir/translator/test_op_translator.py
Labels: contributor

#60281 【Hackathon 5th No.124】Support r to x on 1D one-device-to-multiple mesh
  paddle/phi/core/distributed/auto_parallel/reshard/CMakeLists.txt
  paddle/phi/core/distributed/auto_parallel/reshard/r_to_x_reshard_function.cc
  paddle/phi/core/distributed/auto_parallel/reshard/r_to_x_reshard_function.h
  paddle/phi/core/distributed/auto_parallel/reshard/reshard_function_registry.cc
  paddle/phi/core/distributed/auto_parallel/reshard/reshard_utils.cc
  paddle/phi/core/distributed/auto_parallel/reshard/reshard_utils.h
  paddle/phi/core/distributed/auto_parallel/reshard/same_status_reshard_function.cc
  paddle/phi/core/distributed/auto_parallel/reshard/x_to_r_reshard_function.cc
  test/auto_parallel/CMakeLists.txt
  test/auto_parallel/reshard_r_to_x.py
  test/auto_parallel/test_reshard_r_to_x.py
Labels: PaddlePaddle Hackathon, contributor

#60746 [Code Governance][phi] clean cycle in include-mapping
  paddle/phi/kernels/sparse/elementwise_kernel.h
Labels: contributor, HappyOpenSource

#60750 [Cleanup] clean `random_seed` for test path - Part 1
  python/paddle/framework/random.py
  test/collective/fleet/dist_mnist_gradient_merge.py
  test/collective/fleet/parallel_dygraph_no_sync.py
  test/collective/fleet/pipeline_mnist.py
  test/collective/fleet/pipeline_mnist_multi_device.py
  test/collective/fleet/pipeline_mnist_one_device.py
  test/collective/fleet/static_model_parallel_by_col.py
  test/collective/fleet/static_model_parallel_by_row.py
  test/collective/fleet/static_model_parallel_embedding.py
  test/contrib/test_image_classification_fp16.py
  test/contrib/test_multi_precision_fp16_train.py
  test/dygraph_to_static/test_basic_api_transformation.py
  test/dygraph_to_static/test_bert.py
  test/dygraph_to_static/test_cycle_gan.py
  test/dygraph_to_static/test_mnist.py
Labels: contributor, HappyOpenSource

#60737 [cmake] clean findnumpy
  cmake/FindNumPy.cmake
Labels: contributor, HappyOpenSource

#60747 [CodeStyle][ruff] fix some `RUF100`
  python/paddle/__init__.py
  python/paddle/distributed/__init__.py
  python/paddle/distributed/auto_parallel/static/helper.py
  python/paddle/distributed/auto_parallel/static/operators/__init__.py
  python/paddle/jit/sot/opcode_translator/executor/variables/container.py
  python/paddle/jit/sot/symbolic/interpreter.py
  python/paddle/utils/__init__.py
  python/paddle/vision/__init__.py
  test/auto_parallel/custom_op/semi_auto_parallel_for_custom_op.py
  test/dygraph_to_static/test_legacy_error.py
  test/legacy_test/test_fuse_relu_depthwise_conv_pass.py
  tools/sampcd_processor_utils.py
Labels: contributor, HappyOpenSource

#60766 【Hackathon 5th No.115】为 paddle.linalg.norm 进行功能对齐与功能增强-增加nuclear_norm
  python/paddle/tensor/linalg.py
  test/legacy_test/test_norm_all.py
Labels: contributor, HappyOpenSource

#60792 fix test_op_translator.py
  test/ir/pir/translator/test_op_translator.py
Labels: contributor

#60353 【PIR API adaptor No.171】Migrate paddle.vision.ops.PSRoIPool into pir
  python/paddle/vision/ops.py
  test/legacy_test/test_psroi_pool_op.py
Labels: contributor, HappyOpenSource

#59910 【PIR API adaptor No.31】Migrate `paddle.distribution.Normal` into pir
  python/paddle/distribution/distribution.py
  test/distribution/test_distribution_normal.py
Labels: contributor, HappyOpenSource

#60825 Fix ouputs outputs
  python/paddle/distributed/fleet/meta_optimizers/raw_program_optimizer.py
  test/ir/pir/fused_pass/test_fused_dropout_add_pass.py
  test/ir/pir/fused_pass/test_fused_gemm_epilogue_pass.py
  test/ir/pir/fused_pass/test_pir_fc_elementwise_layernorm_fuse_pass.py
  test/ir/pir/test_pass_manager.py
  test/ir/pir/test_pir_identity_op_clean_pass.py
  test/ir/pir/test_pir_to_static.py
  test/ir/pir/test_standalone_pir.py
  test/ir/pir/test_stop_gradient.py
  test/ir/pir/test_while_api.py
Labels: contributor, HappyOpenSource

#60790 【PIR Dist Op Reg No.21】 reg c_allreduce_prod
  paddle/fluid/pir/dialect/op_generator/ops_api_gen.py
  paddle/fluid/pir/dialect/operator/ir/ops.yaml
  paddle/fluid/pir/dialect/operator/utils/utils.cc
  paddle/phi/api/yaml/legacy_ops.yaml
  paddle/phi/api/yaml/op_compat.yaml
  test/ir/pir/translator/CMakeLists.txt
  test/ir/pir/translator/test_c_allreduce_prod_translator.py
Labels: contributor, HappyOpenSource

#59617 【PIR OpTest Fix No.6】 fix test_tdm_sampler_op
  paddle/fluid/pir/dialect/op_generator/ops_api_gen.py
  paddle/fluid/pir/dialect/operator/ir/ops.yaml
  paddle/fluid/pir/dialect/operator/utils/utils.cc
  paddle/phi/api/yaml/op_compat.yaml
  paddle/phi/infermeta/ternary.cc
  paddle/phi/infermeta/ternary.h
  test/white_list/pir_op_test_no_check_list
  test/white_list/pir_op_test_white_list
Labels: contributor

#60629 [fix bug]fix bug for program_converter
  paddle/fluid/framework/program_converter.cc
Labels: contributor

#60835 fix masked_scatter
  python/paddle/tensor/manipulation.py
Labels: PaddlePaddle Hackathon, contributor

#60845 [PIR] rm @test_sot_only in TestTransformForLoop
  test/dygraph_to_static/test_loop.py
Labels: contributor

#60821 【complex op】No.12、14 add complex support for square & reciprocal
  paddle/phi/common/complex.h
  paddle/phi/kernels/cpu/activation_grad_kernel.cc
  paddle/phi/kernels/cpu/activation_kernel.cc
  paddle/phi/kernels/funcs/activation_functor.h
  paddle/phi/kernels/gpu/activation_grad_kernel.cu
  paddle/phi/kernels/gpu/activation_kernel.cu
  test/legacy_test/test_activation_op.py
Labels: contributor, HappyOpenSource

#60853 [XPU]replace count_nan_or_inf with check
  paddle/phi/kernels/xpu/amp_kernel.cc
Labels: contributor

#60857 Fix _is_list_or_turple_ _is_list_or_tuple_
  python/paddle/hapi/dynamic_flops.py
  python/paddle/jit/dy2static/export_subgraph.py
  python/paddle/nn/functional/common.py
  python/paddle/nn/layer/common.py
  python/paddle/static/nn/common.py
Labels: contributor, HappyOpenSource

#60423 [phi] fix sequence_mask dtype
  paddle/fluid/pir/dialect/operator/ir/update_ops.yaml
  paddle/phi/api/yaml/legacy_ops.yaml
  paddle/phi/infermeta/binary.cc
  paddle/phi/infermeta/binary.h
  paddle/phi/infermeta/unary.cc
  paddle/phi/infermeta/unary.h
  paddle/phi/kernels/impl/sequence_mask_kernel_impl.h
  paddle/phi/kernels/sequence_mask_kernel.h
  python/paddle/base/framework.py
  python/paddle/nn/functional/extension.py
  python/paddle/pir/core.py
  test/legacy_test/prim_op_test.py
  test/sequence/test_sequence_mask.py
Labels: contributor

#60897 【complex op】No.12、14 add complex support for square & reciprocal-英文文档修改
  python/paddle/tensor/ops.py
Labels: contributor, HappyOpenSource

#60905 [PIR] fix some control flow test in pir mode
  python/paddle/base/variable_index.py
  test/legacy_test/test_layers.py
  test/legacy_test/test_set_value_op.py
  test/legacy_test/test_tensor_array_to_tensor.py
Labels: contributor

#60891 Fix words
  python/paddle/audio/backends/init_backend.py
  python/paddle/audio/backends/wave_backend.py
  python/paddle/audio/features/layers.py
  python/paddle/nn/functional/conv.py
  python/paddle/nn/functional/distance.py
  python/paddle/nn/functional/extension.py
  python/paddle/nn/functional/loss.py
  python/paddle/nn/functional/norm.py
  python/paddle/nn/functional/pooling.py
  python/paddle/nn/functional/vision.py
  python/paddle/nn/initializer/initializer.py
  python/paddle/tensor/einsum.py
Labels: contributor, HappyOpenSource

#60921 Fix Normalizaiton Normalization
  python/paddle/audio/functional/functional.py
  python/paddle/utils/cpp_extension/cpp_extension.py
  python/paddle/utils/cpp_extension/extension_utils.py
  python/paddle/utils/inplace_utils.py
  python/paddle/vision/datasets/folder.py
  python/paddle/vision/models/shufflenetv2.py
  python/paddle/vision/ops.py
  python/paddle/vision/transforms/functional.py
  python/paddle/vision/transforms/functional_cv2.py
  python/paddle/vision/transforms/functional_pil.py
  python/paddle/vision/transforms/functional_tensor.py
  python/paddle/vision/transforms/transforms.py
Labels: contributor, HappyOpenSource

#60912 Fix paddle.static.ctr_metric_bundle en doc
  python/paddle/static/nn/metric.py
Labels: contributor, HappyOpenSource

#60923 Fix Simbolic Symbolic
  paddle/cinn/adt/equation_solver.cc
  paddle/cinn/adt/graph_symbolic_dim_infer_ctx.cc
  paddle/cinn/adt/print_utils/print_schedule_mesh.cc
  paddle/cinn/adt/print_utils/print_schedule_mesh.h
  paddle/cinn/api/op_group.h
  paddle/cinn/auto_schedule/search_space/auto_gen_rule/test_helper.cc
  paddle/cinn/auto_schedule/search_space/auto_gen_rule/test_helper.h
  paddle/cinn/auto_schedule/search_space/search_space.h
Labels: contributor, HappyOpenSource

#60928 Fix enfoce enforce
  paddle/common/enforce.h
  paddle/fluid/distributed/auto_parallel/spmd_rules/common.cc
  paddle/fluid/distributed/auto_parallel/spmd_rules/common.h
  paddle/fluid/distributed/auto_parallel/spmd_rules/replicated_spmd_rule.cc
  paddle/fluid/distributed/collective/process_group_with_stream.h
  paddle/fluid/distributed/collective/reducer.cc
  paddle/fluid/distributed/fleet_executor/compute_interceptor.cc
  paddle/fluid/distributed/fleet_executor/cond_interceptor.cc
  paddle/fluid/distributed/ps/service/brpc_ps_client.cc
  paddle/fluid/distributed/ps/service/graph_brpc_server.cc
Labels: contributor, HappyOpenSource

#60940 Fix precison precision
  paddle/fluid/inference/analysis/analyzer.cc
  paddle/fluid/inference/analysis/ir_passes/dlnne_subgraph_pass.cc
  paddle/fluid/inference/analysis/ir_passes/tensorrt_subgraph_pass.cc
  paddle/fluid/inference/analysis/passes/inference_op_replace_pass.h
  paddle/fluid/inference/analysis/passes/memory_optimize_pass.cc
  paddle/fluid/inference/analysis/passes/passes.h
  paddle/fluid/inference/api/analysis_config.cc
  paddle/fluid/inference/api/analysis_predictor.cc
  paddle/fluid/inference/api/analysis_predictor.h
  paddle/fluid/inference/api/helper.h
Labels: contributor, HappyOpenSource

#60936 Fix Optimze Optimize
  paddle/fluid/imperative/amp_auto_cast.cc
  paddle/fluid/imperative/amp_auto_cast.h
  paddle/fluid/imperative/basic_engine.cc
  paddle/fluid/imperative/data_loader.cc
  paddle/fluid/imperative/gradient_accumulator.cc
  paddle/fluid/imperative/gradient_accumulator.h
  paddle/fluid/imperative/infer_shape_context.h
  paddle/fluid/imperative/layout_autotune.cc
  paddle/fluid/imperative/layout_transformer.h
  paddle/fluid/imperative/partial_grad_engine.cc
Labels: contributor, HappyOpenSource

#60932 Fix protmotion promotion
  paddle/fluid/distributed/ps/service/ps_client.h
  paddle/fluid/distributed/ps/wrapper/fleet.cc
  paddle/fluid/distributed/rpc/rpc_agent.cc
  paddle/fluid/distributed/test/brpc_service_dense_sgd_test.cc
  paddle/fluid/distributed/test/brpc_service_sparse_sgd_test.cc
  paddle/fluid/eager/api/manual/eager_manual/forwards/multiply_fwd_func.cc
  paddle/fluid/eager/api/manual/eager_manual/forwards/reshard_fwd_func.cc
  paddle/fluid/eager/api/manual/eager_manual/nodes/reshard_node.cc
  paddle/fluid/eager/auto_code_generator/eager_generator.cc
  paddle/fluid/eager/custom_operator/custom_operator_utils.cc
Labels: contributor, HappyOpenSource

#60935 Fix cahce cache
  paddle/fluid/eager/amp_auto_cast.h
  paddle/fluid/eager/autograd_meta.h
  paddle/fluid/eager/backward.cc
  paddle/fluid/eager/eager_amp_auto_cast.h
  paddle/fluid/eager/eager_layout_auto_tune.h
  paddle/fluid/eager/eager_layout_transformer.h
  paddle/fluid/eager/eager_tensor.h
  paddle/fluid/eager/grad_node_info.h
  paddle/fluid/eager/to_static/run_program_op_node.h
  paddle/fluid/eager/utils.cc
Labels: contributor, HappyOpenSource

#60931 Fix coverter converter
  paddle/fluid/distributed/ps/table/accessor.h
  paddle/fluid/distributed/ps/table/common_graph_table.cc
  paddle/fluid/distributed/ps/table/common_graph_table.h
  paddle/fluid/distributed/ps/table/ctr_dymf_accessor.h
  paddle/fluid/distributed/ps/table/memory_dense_table.cc
  paddle/fluid/distributed/ps/table/memory_sparse_table.cc
  paddle/fluid/distributed/ps/table/ssd_sparse_table.cc
  paddle/fluid/distributed/ps/table/table.cc
Labels: contributor, HappyOpenSource

#60763 bug fix for xpu constant
  paddle/phi/kernels/funcs/math_function.cc
  paddle/phi/kernels/funcs/math_function.h
Labels: contributor

#60769 [pir]Adding FusionOp and CinnFusionLoweringPass
  paddle/cinn/hlir/dialect/operator/ir/manual_op.cc
  paddle/cinn/hlir/dialect/operator/ir/manual_op.h
  paddle/cinn/hlir/dialect/operator/ir/op_dialect.cc
  paddle/cinn/hlir/dialect/operator/transforms/group_merge/divide_group_op_to_fusion_op_pass.cc
  paddle/cinn/hlir/dialect/operator/transforms/group_merge/divide_group_op_to_fusion_op_pass.h
  paddle/cinn/hlir/dialect/operator/transforms/group_merge/lower_cinn_fusion_op_pass.cc
  paddle/cinn/hlir/dialect/operator/transforms/group_merge/lower_cinn_fusion_op_pass.h
  paddle/fluid/pybind/pir.cc
  paddle/fluid/sub_graph/sub_graph_checker.cc
  test/cpp/pir/cinn/group_op_test.cc
  test/cpp/pir/cinn/pir_all_path_test.cc
  test/cpp/pir/cinn/symbolic_lower_test.cc
Labels: contributor

#60945 [PIR] Fix some control flow tests in pir mode
  test/legacy_test/test_device_guard.py
  test/legacy_test/test_zero_dim_tensor.py
Labels: contributor

#60708 [Custom Device] Add Conv2d Fuse more act support for Custom Device
  paddle/fluid/framework/ir/conv_elementwise_add_act_fuse_pass.cc
Labels: contributor

#60898 fix core dump when fallback gather_nd_grad and MemoryAllocateHost condition
  paddle/phi/api/yaml/backward.yaml
  paddle/phi/backends/custom/custom_device.cc
Labels: contributor

#60922 [OneDNN] Add cache in Deconvolution kernel
  paddle/phi/kernels/onednn/conv_transpose_kernel.cc
Labels: Intel, contributor

#60798 [PIR] Replace OpResult with Value in python
  python/paddle/autograd/backward_utils.py
  python/paddle/autograd/ir_backward.py
  python/paddle/base/backward.py
  python/paddle/base/layer_helper_base.py
  python/paddle/base/variable_index.py
  python/paddle/decomposition/decomp.py
  python/paddle/jit/pir_dy2static/parameter_recorder.py
  python/paddle/optimizer/adamw.py
  python/paddle/optimizer/momentum.py
  python/paddle/optimizer/optimizer.py
  python/paddle/pir/__init__.py
  python/paddle/pir/core.py
  python/paddle/regularizer.py
  python/paddle/tensor/attribute.py
  python/paddle/tensor/creation.py
  python/paddle/tensor/linalg.py
  python/paddle/tensor/manipulation.py
  python/paddle/tensor/math.py
  python/paddle/tensor/random.py
  python/paddle/tensor/search.py
  python/paddle/utils/layers_utils.py
  test/ir/pir/test_ir_pybind.py
  test/ir/pir/test_pir_to_static.py
  test/legacy_test/gradient_checker.py
  test/legacy_test/op_test.py
  test/legacy_test/test_math_op_patch_pir.py
Labels: contributor

#60951 Fix lable label
  test/amp/test_amp_api.py
  test/amp/test_amp_master_grad_static.py
  test/amp/test_compare_accuracy_api.py
  test/amp/test_model_cast_to_bf16.py
  test/asp/test_asp_customized_pruning.py
  test/auto_parallel/custom_op/semi_auto_parallel_for_custom_op.py
  test/auto_parallel/custom_op/test_semi_auto_parallel_custom_op.py
  test/auto_parallel/hybrid_strategy/semi_auto_parallel_llama_model.py
  test/auto_parallel/hybrid_strategy/semi_auto_parallel_simple_net_dp_mp_pp.py
  test/auto_parallel/hybrid_strategy/test_cross_mesh_reshard.py
  test/auto_parallel/spmd_rules/test_cross_entropy_with_softmax_rule.py
  test/auto_parallel/spmd_rules/test_embedding_rule.py
Labels: contributor, HappyOpenSource

#60964 Fix loacl local
  test/auto_parallel/1F1B_pass_unittest.py
  test/auto_parallel/converter.py
  test/auto_parallel/gpt_with_pir.py
  test/auto_parallel/quantization_pass_unittest.py
  test/auto_parallel/random_control_unittest.py
  test/auto_parallel/semi_auto_parallel_checkpoint_dedup_tensor.py
  test/auto_parallel/semi_auto_parallel_for_fused_rope.py
  test/auto_parallel/semi_auto_parallel_simple_net.py
  test/auto_parallel/sharding_pass_unittest.py
  test/auto_parallel/static_completion_convergence.py
  test/auto_parallel/static_reshard_api_cross_mesh.py
  test/auto_parallel/static_reshard_api_same_mesh.py
  test/auto_parallel/test_auto_parallel_relaunch.py
  test/auto_parallel/test_relaunch_with_gpt_planner.py
  test/auto_parallel/test_relaunch_with_planner.py
Labels: contributor, HappyOpenSource

#60965 Fix input_sepc input_spec
  test/auto_parallel/test_conditional_block_reshard.py
  test/auto_parallel/test_new_cost_model.py
  test/auto_parallel/test_serialization.py
  test/auto_parallel/test_static_gradient_sync.py
  test/auto_parallel/test_static_sequence_parallel_pass.py
  test/auto_parallel/test_to_static.py
  test/auto_parallel/test_trial.py
  test/auto_parallel/test_tunable_space.py
  test/autograd/test_orig2prim.py
  test/autograd/utils.py
Labels: contributor, HappyOpenSource

#60967 Fix Desceding Descending
  test/cinn/op_mappers/test_layer_norm_op.py
  test/cinn/ops/test_argsort_op.py
  test/cinn/ops/test_zero_dim_tensor.py
  test/cinn/test_paddle_model_convertor.py
  test/collective/fleet/parallel_dygraph_transformer.py
  test/collective/fleet/test_dgc_optimizer.py
  test/collective/fleet/test_fleet_rolemaker_new.py
  test/collective/fleet/test_fleet_sharding_meta_optimizer.py
  test/collective/fleet/test_fleet_tensor_parallel_extra_sync.py
  test/collective/fleet/test_parallel_dygraph_no_sync.py
Labels: contributor, HappyOpenSource

#60972 Fix foward forward
  paddle/fluid/jit/compilation_unit.cc
  paddle/fluid/jit/layer.cc
  paddle/fluid/operators/generator/parse_utils.py
  paddle/fluid/pir/dialect/op_generator/op_gen.py
  paddle/fluid/pir/dialect/op_generator/op_infermeta_gen.py
  paddle/fluid/pir/dialect/op_generator/op_interface_gen.py
  paddle/fluid/pir/dialect/operator/ir/control_flow_op.cc
  paddle/phi/api/yaml/generator/api_gen.py
  paddle/phi/api/yaml/generator/dist_api_gen.py
  paddle/phi/api/yaml/generator/intermediate_api_gen.py
Labels: contributor, HappyOpenSource

#60968 [Fix] refactor copysign
  paddle/phi/kernels/copysign_grad_kernel.h
  paddle/phi/kernels/copysign_kernel.h
  paddle/phi/kernels/cpu/copysign_grad_kernel.cc
  paddle/phi/kernels/cpu/copysign_kernel.cc
  paddle/phi/kernels/cpu/elementwise_grad_kernel.cc
  paddle/phi/kernels/cpu/elementwise_kernel.cc
  paddle/phi/kernels/elementwise_grad_kernel.h
  paddle/phi/kernels/elementwise_kernel.h
  paddle/phi/kernels/funcs/elementwise_functor.h
  paddle/phi/kernels/gpu/copysign_grad_kernel.cu
  paddle/phi/kernels/gpu/copysign_kernel.cu
  paddle/phi/kernels/gpu/elementwise_grad_kernel.cu
  paddle/phi/kernels/impl/elementwise_grad_kernel_impl.h
  paddle/phi/kernels/kps/elementwise_kernel.cu
Labels: PaddlePaddle Hackathon, contributor

#60960 【paddle_test No.33】replace cc_test with paddle_test
  paddle/phi/core/distributed/store/CMakeLists.txt
  test/cpp/phi/core/CMakeLists.txt
  test/cpp/phi/core/test_tcp_store.cc
Labels: contributor, HappyOpenSource

#60971 Fix GetInstantcePtr GetInstancePtr
  paddle/fluid/distributed/ps/service/communicator/communicator.h
  paddle/fluid/distributed/ps/service/graph_brpc_server.cc
  paddle/fluid/pybind/auto_parallel_py.cc
  paddle/fluid/pybind/communicator_py.cc
  paddle/fluid/pybind/complex.h
  paddle/fluid/pybind/control_flow_api.cc
  paddle/fluid/pybind/cuda_streams_py.cc
  paddle/fluid/pybind/eager_functions.cc
  paddle/fluid/pybind/eager_utils.cc
  paddle/fluid/pybind/eager_utils.h
  paddle/fluid/pybind/fleet_py.cc
  paddle/fluid/sub_graph/sub_graph_checker.cc
Labels: contributor, HappyOpenSource

#60980 Fix temp_dense_tensots temp_dense_tensors
  paddle/phi/api/lib/api_custom_impl.cc
  paddle/phi/api/lib/kernel_dispatch.h
  paddle/phi/api/lib/op_meta_info.cc
  paddle/phi/api/lib/tensor_method.cc
  paddle/phi/api/lib/tensor_utils.cc
Labels: contributor, HappyOpenSource

#60984 Fix Unsuppored Unsupported
  paddle/phi/backends/c_comm_lib.h
  paddle/phi/backends/device_code.cc
  paddle/phi/backends/gpu/cuda/cuda_graph.cc
  paddle/phi/backends/gpu/cuda/cuda_graph.h
  paddle/phi/backends/gpu/gpu_context.cc
  paddle/phi/backends/gpu/gpu_decls.h
  paddle/phi/backends/gpu/gpu_launch_config.h
  paddle/phi/backends/gpu/gpu_types.h
  paddle/phi/backends/stream.cc
  paddle/phi/backends/xpu/xpu_info.cc
Labels: contributor, HappyOpenSource

#60985 Fix larget larger
  paddle/phi/infermeta/binary.cc
  paddle/phi/infermeta/fusion.cc
  paddle/phi/kernels/cpu/arg_min_max_kernel.cc
  paddle/phi/kernels/cpu/batch_norm_grad_kernel.cc
  paddle/phi/kernels/cpu/batch_norm_kernel.cc
  paddle/phi/kernels/cpu/class_center_sample_kernel.cc
  paddle/phi/kernels/cpu/conv_util.h
  paddle/phi/kernels/cpu/cross_entropy_grad_kernel.cc
  paddle/phi/kernels/cpu/cross_entropy_kernel.cc
  paddle/phi/kernels/cpu/eig.h
  paddle/phi/kernels/cpu/masked_select_kernel.cc
  paddle/phi/kernels/cpu/mode_kernel.cc
  paddle/phi/kernels/cpu/top_k_kernel.cc
  paddle/phi/kernels/gpu/unique_consecutive_functor.h
  paddle/phi/kernels/gpu/unique_kernel.cu
Labels: contributor, HappyOpenSource

#60989 Fix tranposed_input transposed_input
  paddle/phi/kernels/cpu/eig.h
  paddle/phi/kernels/cpu/embedding_grad_kernel.cc
  paddle/phi/kernels/cpu/matrix_nms_kernel.cc
  paddle/phi/kernels/cpu/mode_grad_kernel.cc
  paddle/phi/kernels/cpu/mode_kernel.cc
  paddle/phi/kernels/cpu/svd_kernel.cc
  paddle/phi/kernels/cpu/top_k_grad_kernel.cc
  paddle/phi/kernels/cpu/top_k_kernel.cc
  paddle/phi/kernels/gpu/mode_kernel.cu
  paddle/phi/kernels/gpu/top_k_kernel.cu
Labels: contributor, HappyOpenSource

#60990 Fix Upate Update
  paddle/phi/kernels/funcs/lamb_functors.h
  paddle/phi/kernels/impl/adagrad_kernel_impl.h
  paddle/phi/kernels/impl/bilinear_grad_kernel_impl.h
  paddle/phi/kernels/impl/dot_grad_kernel_impl.h
  paddle/phi/kernels/impl/einsum_grad_impl.h
  paddle/phi/kernels/impl/einsum_impl.h
  paddle/phi/kernels/impl/kron_grad_kernel_impl.h
  paddle/phi/kernels/impl/lamb_kernel_impl.h
  paddle/phi/kernels/impl/matmul_kernel_impl.h
  paddle/phi/kernels/selected_rows/impl/lamb_kernel_impl.h
Labels: contributor, HappyOpenSource

#60991 Fix velocitys velocities
  paddle/phi/kernels/impl/merged_momentum_impl.h
  paddle/phi/kernels/impl/multi_dot_kernel_impl.h
  paddle/phi/kernels/impl/set_value_grad_kernel_impl.h
  paddle/phi/kernels/impl/set_value_kernel_impl.h
  paddle/phi/kernels/impl/slice_grad_kernel_impl.h
Labels: contributor, HappyOpenSource

#60992 Fix DECALRE DECLARE
  paddle/phi/kernels/compare_kernel.h
  paddle/phi/kernels/impl/slogdeterminant_grad_kernel_impl.h
  paddle/phi/kernels/impl/solve_grad_kernel_impl.h
  paddle/phi/kernels/impl/triangular_solve_grad_kernel_impl.h
  paddle/phi/kernels/impl/warprnnt_kernel_impl.h
  paddle/phi/kernels/onednn/conv_grad_kernel.cc
  paddle/phi/kernels/primitive/functor_primitives_xpu2.h
  paddle/phi/kernels/sparse/cpu/conv_kernel.cc
  paddle/phi/kernels/sparse/cpu/softmax_kernel.cc
  paddle/phi/kernels/stride/slice_kernel.cc
Labels: contributor, HappyOpenSource

#60994 Fix Destoryed Destroyed
  paddle/pir/core/block.cc
  paddle/pir/core/block_argument.cc
  paddle/pir/core/ir_mapping.h
  paddle/pir/core/ir_printer.cc
  paddle/pir/core/iterator.h
  paddle/pir/core/op_base.h
  paddle/pir/core/op_info_impl.cc
  paddle/pir/core/op_result.h
  paddle/pir/core/op_result_impl.cc
  paddle/pir/core/operation.cc
  paddle/pir/core/parser/ir_parser.cc
  paddle/pir/core/parser/lexer.cc
  paddle/pir/core/parser/lexer.h
  paddle/pir/core/parser/token.h
  paddle/pir/core/region.cc
Labels: contributor, HappyOpenSource

#60995 Fix communicatoin communication
  paddle/fluid/operators/cinn/cinn_instruction_run_op.cc
  paddle/fluid/operators/cinn/cinn_launch_context.cc
  paddle/fluid/operators/cinn/cinn_launch_context.h
  paddle/fluid/operators/cinn/cinn_launch_op.cc
  paddle/fluid/operators/collective/c_comm_init_multitrainer_op.cc
  paddle/fluid/operators/collective/c_gen_xccl_id_op.cc
  paddle/fluid/operators/collective/global_gather_op.cu.cc
  paddle/fluid/operators/controlflow/depend_op.cc
  paddle/fluid/operators/controlflow/feed_op.cc
  paddle/fluid/operators/detection/bipartite_match_op.cc
  paddle/fluid/operators/detection/collect_fpn_proposals_op.cc
  paddle/fluid/operators/detection/density_prior_box_op.cc
Labels: contributor, HappyOpenSource

#60996 Fix Minmum Minimum
  paddle/fluid/operators/elementwise/elementwise_add_op.cc
  paddle/fluid/operators/elementwise/elementwise_div_op.cc
  paddle/fluid/operators/elementwise/elementwise_functor.h
  paddle/fluid/operators/elementwise/elementwise_mul_op.cc
  paddle/fluid/operators/elementwise/elementwise_op_function.h
  paddle/fluid/operators/elementwise/elementwise_sub_op.cc
Labels: contributor, HappyOpenSource

#61001 Fix reprensent represent
  paddle/pir/dialect/control_flow/ir/cf_op.cc
  paddle/pir/dialect/shape/utils/dim_expr.h
  paddle/pir/dialect/shape/utils/dim_expr_builder.cc
  paddle/pir/dialect/shape/utils/dim_expr_builder.h
  paddle/pir/pass/analysis_manager.h
  paddle/pir/pass/pass.h
  paddle/pir/pass/pass_instrumentation.h
  paddle/pir/pattern_rewrite/frozen_rewrite_pattern_set.h
  paddle/pir/pattern_rewrite/pattern_applicator.h
  paddle/pir/pattern_rewrite/pattern_match.cc
  paddle/pir/pattern_rewrite/pattern_match.h
  paddle/pir/pattern_rewrite/pattern_rewrite_driver.cc
Labels: contributor, HappyOpenSource

#61000 Fix sentece sentence
  paddle/fluid/operators/beam_search_decode_op_def.h
  paddle/fluid/operators/beam_search_op.cc
  paddle/fluid/operators/cast_op.cc
  paddle/fluid/operators/correlation_op.cc
  paddle/fluid/operators/crf_decoding_op.cc
  paddle/fluid/operators/crop_op.cc
  paddle/fluid/operators/pscore/distributed_lookup_table_op.cc
  paddle/fluid/operators/pscore/listen_and_serv_op.cc
  paddle/fluid/operators/pscore/send_and_recv_op.cc
  paddle/fluid/operators/reader/blocking_queue.h
  paddle/fluid/operators/reader/create_py_reader_op.cc
  paddle/fluid/operators/reduce_ops/logsumexp_op.cc
Labels: contributor, HappyOpenSource

#60999 Fix excuted executed
  paddle/fluid/operators/fused/multi_gru_op.cc
  paddle/fluid/operators/generator/filters.py
  paddle/fluid/operators/generator/generate_op.py
  paddle/fluid/operators/generator/generate_sparse_op.py
  paddle/fluid/operators/generator/get_expected_kernel_func.cc
  paddle/fluid/operators/generator/templates/operator_utils.c.j2
  paddle/fluid/operators/ops_signature/matrix_rank_sig.cc
  paddle/fluid/operators/optimizers/proximal_gd_op.cc
  paddle/fluid/operators/prim_ops/abs_p_op.cc
  paddle/fluid/operators/prim_ops/add_p_op.cc
  paddle/fluid/operators/prim_ops/bernoulli_p_op.cc
  paddle/fluid/operators/prim_ops/broadcast_p_op.cc
  paddle/fluid/operators/prim_ops/cast_p_op.cc
  paddle/fluid/operators/prim_ops/concat_p_op.cc
  paddle/fluid/operators/prim_ops/cos_p_op.cc
  paddle/fluid/operators/prim_ops/div_p_op.cc
  paddle/fluid/operators/prim_ops/eq_p_op.cc
  paddle/fluid/operators/prim_ops/erf_p_op.cc
  paddle/fluid/operators/prim_ops/exp_p_op.cc
  paddle/fluid/operators/prim_ops/fill_constant_p_op.cc
  paddle/fluid/operators/prim_ops/gather_p_op.cc
  paddle/fluid/operators/prim_ops/ge_p_op.cc
  paddle/fluid/operators/prim_ops/gt_p_op.cc
  paddle/fluid/operators/prim_ops/log_p_op.cc
  paddle/fluid/operators/prim_ops/matmul_p_op.cc
  paddle/fluid/operators/prim_ops/max_p_op.cc
  paddle/fluid/operators/prim_ops/mul_p_op.cc
  paddle/fluid/operators/prim_ops/ne_p_op.cc
  paddle/fluid/operators/prim_ops/pow_p_op.cc
  paddle/fluid/operators/prim_ops/reduce_sum_p_op.cc
  paddle/fluid/operators/prim_ops/reshape_p_op.cc
  paddle/fluid/operators/prim_ops/rsqrt_p_op.cc
  paddle/fluid/operators/prim_ops/scatter_add_p_op.cc
  paddle/fluid/operators/prim_ops/select_p_op.cc
  paddle/fluid/operators/prim_ops/sin_p_op.cc
  paddle/fluid/operators/prim_ops/slice_assign_p_op.cc
  paddle/fluid/operators/prim_ops/slice_select_p_op.cc
  paddle/fluid/operators/prim_ops/split_p_op.cc
  paddle/fluid/operators/prim_ops/sqrt_p_op.cc
  paddle/fluid/operators/prim_ops/sub_p_op.cc
  paddle/fluid/operators/prim_ops/tanh_p_op.cc
  paddle/fluid/operators/prim_ops/transpose_p_op.cc
  paddle/fluid/operators/prim_ops/uniform_random_p_op.cc
Labels: contributor, HappyOpenSource

#60998 Fix architecure architecture
  paddle/fluid/operators/fused/fused_gate_attention_op.cc
  paddle/fluid/operators/fused/fused_gemm_epilogue_op.cc
  paddle/fluid/operators/fused/fused_multi_transformer_int8_op.cc
  paddle/fluid/operators/fused/fused_multi_transformer_op.cc
  paddle/fluid/operators/fused/fused_transformer_op.cc
  paddle/fluid/operators/fused/fused_transformer_op.cu
  paddle/fluid/operators/fused/fused_transformer_op.h
  paddle/fluid/operators/fused/fusion_conv_inception_op.cc
  paddle/fluid/operators/fused/fusion_lstm_op.cc
  paddle/fluid/operators/fused/fusion_seqpool_concat_op.cc
Labels: contributor, HappyOpenSource

#60961 【paddle_test No.34】replace cc_test with paddle_test
  paddle/phi/backends/CMakeLists.txt
  test/cpp/phi/backends/CMakeLists.txt
  test/cpp/phi/backends/custom/capi_test.cc
Labels: contributor, HappyOpenSource

#60962 fix: fix docstring issue
  python/paddle/tensor/linalg.py
Labels: contributor, HappyOpenSource

#60942 [Docs] Fix delimiter of argument in docstring
  python/paddle/base/framework.py
  python/paddle/nn/functional/vision.py
  python/paddle/nn/quant/stub.py
  python/paddle/quantization/factory.py
  python/paddle/quantization/ptq.py
  python/paddle/quantization/qat.py
  python/paddle/quantization/quantize.py
  python/paddle/quantization/wrapper.py
Labels: contributor, HappyOpenSource

#60693 Add test_with_pir_api in error test
  test/legacy_test/test_arange.py
  test/legacy_test/test_assign_op.py
  test/legacy_test/test_cast_op.py
  test/legacy_test/test_compare_op.py
  test/legacy_test/test_numel_op.py
  test/legacy_test/test_reshape_op.py
  test/legacy_test/test_scale_op.py
  test/legacy_test/test_sum_op.py
  test/legacy_test/test_uniform_random_op.py
  test/legacy_test/test_unsqueeze2_op.py
  test/legacy_test/test_where_op.py
Labels: contributor

#61005 [xpu]: delete squeeze_excitation_fuse_pass out_max
  paddle/fluid/framework/ir/xpu/squeeze_excitation_fuse_pass.cc
Labels: contributor

#61026 Fix reproducability reproducibility
  test/collective/fleet/hybrid_parallel_mp_layers.py
  test/collective/fleet/hybrid_parallel_mp_model.py
  test/collective/fleet/hybrid_parallel_mp_model_with_sequence_parallel.py
  test/collective/fleet/hybrid_parallel_pp_amp.py
  test/collective/fleet/hybrid_parallel_pp_bf16.py
  test/collective/fleet/hybrid_parallel_pp_embedding.py
  test/collective/fleet/hybrid_parallel_pp_fp16.py
  test/collective/fleet/hybrid_parallel_pp_recompute.py
  test/collective/fleet/hybrid_parallel_pp_transformer.py
  test/collective/fleet/hybrid_parallel_pp_transformer_with_virtual_stage.py
  test/collective/fleet/hybrid_parallel_qat.py
  test/collective/fleet/hybrid_parallel_shared_weight.py
  test/collective/fleet/parallel_class_center_sample.py
  test/collective/fleet/parallel_margin_cross_entropy.py
  test/legacy_test/hybrid_parallel_perf_test.py
  test/legacy_test/hybrid_parallel_pp_alexnet.py
Labels: contributor, HappyOpenSource

#61009 Fix euqal equal
  paddle/cinn/ir/schedule/schedule_desc.h
  paddle/cinn/ir/test/ir_compare_test.cc
  paddle/cinn/ir/test/schedule_desc_test.cc
  paddle/cinn/ir/utils/ir_compare.cc
  paddle/cinn/ir/utils/ir_compare.h
  paddle/fluid/framework/fleet/ps_gpu_wrapper.cc
  paddle/fluid/pir/transforms/inplace_pass.cc
  paddle/fluid/pir/transforms/pd_op_to_kernel_pass.cc
  paddle/fluid/pir/transforms/transform_general_functions.h
  paddle/phi/infermeta/binary.cc
  paddle/phi/infermeta/fusion.cc
  paddle/phi/infermeta/multiary.cc
  paddle/phi/infermeta/unary.cc
  paddle/phi/kernels/cpu/conv_util.h
  paddle/phi/kernels/fusion/cutlass/memory_efficient_attention_grad_kernel.cu
Labels: contributor, HappyOpenSource

#61032 Fix CVE-2024-0521
  python/paddle/utils/download.py
Labels: contributor, HappyOpenSource

#60772 [cherry-pick] This PR enable offset of generator for custom device. (#60616)
  paddle/phi/core/generator.cc
Labels: contributor

#58738 [PIR] Add auto mixed precision pass in pir
  paddle/fluid/pir/transforms/auto_mixed_precision_pass.cc
  paddle/fluid/pir/transforms/auto_mixed_precision_pass.h
Labels: contributor

#61012 [PR] remove BindOpResult
  paddle/fluid/ir_adaptor/translator/program_translator.cc
  paddle/fluid/ir_adaptor/translator/program_translator.h
  paddle/fluid/pir/dialect/op_generator/op_gen.py
  paddle/fluid/pir/dialect/op_generator/op_interface_gen.py
  paddle/fluid/pir/dialect/op_generator/python_c_gen.py
  paddle/fluid/pir/dialect/operator/interface/decomp.h
  paddle/fluid/pir/dialect/operator/interface/vjp.h
  paddle/fluid/pir/dialect/operator/ir/control_flow_op.cc
  paddle/fluid/pir/dialect/operator/ir/control_flow_op.h
  paddle/fluid/pir/dialect/operator/ir/manual_op.h
  paddle/fluid/pir/dialect/operator/ir/manual_op_decomp.cc
  paddle/fluid/pir/dialect/operator/ir/manual_op_vjp.cc
  paddle/fluid/primitive/base/decomp_trans.cc
  paddle/fluid/primitive/base/decomp_trans.h
  paddle/fluid/primitive/codegen/templates/decomp/generated_decomp.j2
  paddle/fluid/pybind/control_flow_api.cc
  paddle/fluid/pybind/eager_utils.cc
  paddle/fluid/pybind/eager_utils.h
  paddle/fluid/pybind/manual_static_op_function.h
  paddle/fluid/pybind/pir.cc
  paddle/fluid/pybind/pybind.cc
  test/dygraph_to_static/test_set_static_op_arg_pre_cast_hook.py
Labels: contributor

#61034 Fix paralel parallel
  paddle/phi/api/yaml/generator/dist_api_gen.py
  paddle/phi/api/yaml/generator/dist_bw_api_gen.py
  python/paddle/distributed/auto_parallel/static/operators/common.py
  python/paddle/distributed/auto_tuner/prune.py
  python/paddle/distributed/auto_tuner/utils.py
  python/paddle/distributed/fleet/base/topology.py
  test/legacy_test/test_directory_migration.py
Labels: contributor, HappyOpenSource

#61033 Fix precison precision
  paddle/fluid/platform/device/ipu/popart_canonicalization/tensor_ops.cc
  paddle/phi/kernels/funcs/cufft_util.h
  paddle/scripts/paddle_build.sh
  python/paddle/amp/auto_cast.py
  python/paddle/nn/layer/layers.py
  python/paddle/static/amp/fp16_utils.py
Labels: contributor, HappyOpenSource

#61020 Fix optinal optional
  paddle/cinn/auto_schedule/measure/measure.h
  paddle/cinn/frontend/decomposer_registry.h
  paddle/cinn/ir/schedule/impl/loop_transformation.cc
  paddle/cinn/ir/schedule/ir_schedule_util.cc
  paddle/fluid/framework/ir/fused_multi_transformer_decoder_pass.cc
  paddle/fluid/framework/ir/fused_multi_transformer_encoder_pass.cc
  paddle/fluid/framework/ir/multihead_matmul_fuse_pass.cc
  paddle/fluid/framework/new_executor/feed_fetch_utils.cc
  paddle/fluid/framework/parallel_executor.cc
  paddle/fluid/inference/tensorrt/convert/io_converter.cc
  paddle/fluid/inference/tensorrt/op_teller.cc
  paddle/fluid/inference/tensorrt/plugin/gather_nd_op_plugin.cu
  paddle/phi/core/generator.cc
  paddle/phi/infermeta/fusion.cc
  paddle/phi/kernels/cpu/send_uv_grad_kernel.cc
  paddle/phi/kernels/cpu/send_uv_kernel.cc
  paddle/phi/kernels/funcs/common_shape.h
  paddle/phi/kernels/fusion/onednn/fc_kernel.cc
  paddle/phi/kernels/gpu/send_uv_grad_kernel.cu
  paddle/phi/kernels/gpu/send_uv_kernel.cu
  python/paddle/amp/auto_cast.py
  python/paddle/amp/debugging.py
  python/paddle/autograd/autograd.py
  python/paddle/base/framework.py
  python/paddle/base/multiprocess_utils.py
  python/paddle/base/param_attr.py
  python/paddle/base/reader.py
  python/paddle/distributed/auto_parallel/static/dist_context.py
  python/paddle/distributed/auto_parallel/static/engine.py
  python/paddle/distributed/auto_tuner/prune.py
  python/paddle/distributed/fleet/elastic/collective.py
  python/paddle/distributed/fleet/meta_optimizers/dygraph_optimizer/dygraph_sharding_optimizer.py
  python/paddle/distributed/fleet/meta_optimizers/sharding_optimizer.py
  python/paddle/distributed/fleet/meta_parallel/parallel_layers/pp_layers.py
  python/paddle/distributed/passes/auto_parallel_sharding.py
  python/paddle/distribution/transform.py
  python/paddle/fft.py
  python/paddle/framework/random.py
  python/paddle/hapi/hub.py
  python/paddle/hapi/model.py
  python/paddle/hapi/static_flops.py
  python/paddle/incubate/autograd/functional.py
  python/paddle/incubate/autograd/primx.py
  python/paddle/incubate/framework/random.py
  python/paddle/jit/dy2static/partial_program.py
  python/paddle/jit/sot/opcode_translator/executor/opcode_executor.py
  python/paddle/tensor/creation.py
  test/legacy_test/test_prod_op.py
  test/xpu/test_prod_op_xpu.py
Labels: contributor, HappyOpenSource

#60350 【PIR API adaptor No.182】Migrate paddle.optimizer.RMSProp into pir
  python/paddle/optimizer/rmsprop.py
  test/legacy_test/test_rmsprop_op.py
Labels: contributor, HappyOpenSource

#60336 [AutoParallel] add _check_dist_attr
  python/paddle/distributed/auto_parallel/static/parallelizer_v2.py
  python/paddle/distributed/passes/auto_parallel_sharding.py
Labels: contributor

#61053 [PIR] Replace OpResult usage in Operation::result(s)
  paddle/cinn/hlir/dialect/operator/ir/manual_op.h
  paddle/fluid/ir_adaptor/translator/op_translator.cc
  paddle/fluid/ir_adaptor/translator/op_translator.h
  paddle/fluid/ir_adaptor/translator/utils.cc
  paddle/fluid/pir/dialect/op_generator/api_gen.py
  paddle/fluid/pir/dialect/op_generator/op_build_gen.py
  paddle/fluid/pir/dialect/op_generator/op_member_func_gen.py
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape.cc
  paddle/fluid/pir/dialect/operator/ir/control_flow_op.h
  paddle/fluid/pir/dialect/operator/ir/manual_api.cc
  paddle/fluid/pir/dialect/operator/ir/manual_api.h
  paddle/fluid/pir/dialect/operator/ir/manual_op.cc
  paddle/fluid/pir/dialect/operator/ir/manual_op.h
  paddle/fluid/pir/dialect/operator/ir/op_dialect.cc
  paddle/fluid/pir/transforms/fusion/conv2d_add_act_fuse_pass.cc
  paddle/fluid/pir/transforms/fusion/conv2d_bn_fuse_pass.cc
  paddle/fluid/pir/transforms/pd_op_to_kernel_pass.cc
  paddle/fluid/pir/transforms/shape_optimization_pass.cc
  paddle/fluid/pir/transforms/sub_graph_detector.cc
  paddle/fluid/primitive/backend/manual/manual_static_backend.cc
  paddle/fluid/primitive/base/decomp_trans.cc
  paddle/fluid/primitive/base/decomp_trans.h
  paddle/fluid/primitive/codegen/templates/backend/generated/generated_static_backend.cc.j2
  paddle/fluid/pybind/eager_utils.cc
  paddle/fluid/pybind/eager_utils.h
  paddle/pir/core/builtin_op.h
  paddle/pir/core/ir_printer.cc
  paddle/pir/core/op_base.h
  paddle/pir/core/op_trait.cc
  paddle/pir/core/operation.cc
  paddle/pir/core/operation.h
  paddle/pir/dialect/shape/ir/shape_op.h
  test/cpp/pir/cinn/adt/map_expr_test.cc
  test/cpp/pir/cinn/ir_op_fusion_test.cc
  test/cpp/pir/cinn/pir_compiler_test.cc
  test/cpp/pir/core/ir_region_test.cc
  test/cpp/pir/core/ir_value_test.cc
  test/cpp/pir/pass/pass_manager_test.cc
Labels: contributor

#61092 Fix specificing specifying, test=document_fix
  python/paddle/jit/dy2static/function_spec.py
Labels: contributor, HappyOpenSource

#61066 Fix cantains contains
  paddle/cinn/backends/codegen_cuda_util.h
  paddle/cinn/hlir/dialect/operator/transforms/group_merge/op_with_group_merge_util.h
  paddle/cinn/hlir/pass/op_fusion_pass_util.h
  paddle/cinn/ir/group_schedule/tactic/optimize_reduction_tactic.cc
  paddle/cinn/lang/README.md
  paddle/fluid/distributed/ps/table/depends/dense.h
  paddle/fluid/framework/fleet/box_wrapper.h
  paddle/fluid/framework/fleet/ps_gpu_wrapper.h
  paddle/fluid/framework/new_executor/executor_statistics.cc
  paddle/fluid/framework/ps_gpu_worker.cc
Labels: contributor, HappyOpenSource

#61063 Fix invovled involved
  python/paddle/incubate/autograd/functional.py
  python/paddle/incubate/distributed/fleet/parameter_server/ir/pserver_pass.py
  python/paddle/incubate/distributed/utils/io/save_for_auto.py
  python/paddle/incubate/nn/functional/fused_gate_attention.py
  python/paddle/incubate/operators/unzip.py
  python/paddle/incubate/optimizer/functional/line_search.py
  python/paddle/incubate/optimizer/line_search_dygraph.py
  python/paddle/incubate/optimizer/lookahead.py
  python/paddle/incubate/tensor/manipulation.py
  python/paddle/io/dataloader/dataloader_iter.py
Labels: contributor, HappyOpenSource

#59357 【Hackathon 5th No.11】add `gammaincc` and `gammainc` API
  paddle/phi/api/yaml/backward.yaml
  paddle/phi/api/yaml/ops.yaml
  paddle/phi/kernels/cpu/gammaincc_grad_kernel.cc
  paddle/phi/kernels/cpu/gammaincc_kernel.cc
  paddle/phi/kernels/gammaincc_grad_kernel.h
  paddle/phi/kernels/gammaincc_kernel.h
  paddle/phi/kernels/gpu/gammaincc_grad_kernel.cu
  paddle/phi/kernels/gpu/gammaincc_kernel.cu
  paddle/phi/kernels/impl/gammaincc_grad_kernel_impl.h
  paddle/phi/kernels/impl/gammaincc_kernel_impl.h
  python/paddle/__init__.py
  python/paddle/tensor/__init__.py
  python/paddle/tensor/math.py
  test/legacy_test/test_gammainc.py
  test/legacy_test/test_gammaincc_op.py
  test/legacy_test/test_inplace.py
Labels: PaddlePaddle Hackathon, contributor

#61089 Fix fileds fields
  python/paddle/io/dataloader/collate.py
  python/paddle/io/dataloader/dataloader_iter.py
  python/paddle/io/dataloader/dataset.py
  python/paddle/io/dataloader/flat.py
  python/paddle/io/dataloader/sampler.py
  python/paddle/io/dataloader/worker.py
  python/paddle/quantization/imperative/ptq_quantizer.py
Labels: contributor, HappyOpenSource

#61065 【Cleanup random_seed No.1】clean `test_varname_inplace_ipu.py`
  test/ipu/test_varname_inplace_ipu.py
Labels: contributor

#61087 [pir] fix frexp datatype
  python/paddle/tensor/math.py
  test/legacy_test/test_frexp_api.py
  test/legacy_test/test_smooth_l1_loss.py
Labels: contributor

#61111 [PIR] Remove most usage of OpResult [Part 2]
  paddle/fluid/pir/dialect/op_generator/api_gen.py
  paddle/fluid/pir/drr/ir_operation_factory.cc
  paddle/fluid/pir/transforms/constant_folding_pass.cc
  paddle/fluid/pir/transforms/replace_fetch_with_shadow_output_pass.cc
  paddle/fluid/pir/transforms/transform_general_functions.cc
  paddle/fluid/pybind/manual_static_op_function.h
  paddle/fluid/pybind/op_function_common.cc
  paddle/pir/core/builtin_op.cc
  paddle/pir/core/ir_context.h
  paddle/pir/core/op_info.h
  test/cpp/pir/core/block_operand_test.cc
  test/cpp/pir/tools/test_op.cc
  test/cpp/pir/tools/test_op.h
  test/ir/pir/test_symbol_overload.py
  test/legacy_test/test_expand_v2_op.py
  test/legacy_test/test_reshape_op.py
  test/legacy_test/test_where_op.py
Labels: contributor

#61122 fix test_gammaincc_op fail
  python/paddle/tensor/math.py
  test/legacy_test/test_gammaincc_op.py
Labels: PaddlePaddle Hackathon, contributor

#60911 【PIR Dist Op Reg No.24】 reg distributed_lookup_table
  paddle/fluid/pir/dialect/op_generator/ops_api_gen.py
  paddle/fluid/pir/dialect/operator/ir/ops.yaml
  paddle/phi/api/yaml/op_compat.yaml
  paddle/phi/infermeta/binary.cc
  paddle/phi/infermeta/binary.h
  test/ir/pir/translator/CMakeLists.txt
  test/ir/pir/translator/test_distributed_lookup_table_translate.py
Labels: contributor, HappyOpenSource

#61051 【fix bug】fix bug for program_converter
  paddle/fluid/framework/program_converter.cc
Labels: contributor

#61074 【Cleanup random_seed No.3、12-13】clean some `random_seed`
  test/ipu/test_weight_decay_ipu.py
  test/legacy_test/dist_fleet_raw_program_optimizer_fuse_allreduce.py
Labels: contributor

#58834 【Hackathon No.40】为 Paddle 新增 ASGD API
  paddle/phi/api/yaml/ops.yaml
  paddle/phi/infermeta/multiary.cc
  paddle/phi/infermeta/multiary.h
  paddle/phi/kernels/asgd_kernel.h
  paddle/phi/kernels/cpu/asgd_kernel.cc
  paddle/phi/kernels/gpu/asgd_kernel.cu
  python/paddle/optimizer/__init__.py
  python/paddle/optimizer/asgd.py
  test/legacy_test/test_asgd_op.py
Labels: PaddlePaddle Hackathon, contributor

#61129 Fix tenosr tensor
  paddle/fluid/operators/detection/locality_aware_nms_op.cc
  paddle/fluid/operators/detection/multiclass_nms_op.cc
  paddle/fluid/operators/detection/retinanet_detection_output_op.cc
  paddle/phi/infermeta/binary.cc
  paddle/phi/infermeta/spmd_rules/utils.cc
  paddle/phi/infermeta/spmd_rules/utils.h
  python/paddle/static/nn/sequence_lod.py
  python/paddle/tensor/creation.py
Labels: contributor, HappyOpenSource

#61128 Fix recevied received
  paddle/fluid/operators/math/sampler.h
  paddle/fluid/operators/optimizers/sgd_op.h
  paddle/fluid/operators/partial_concat_op.cc
  paddle/fluid/operators/partial_sum_op.cc
  paddle/phi/infermeta/binary.cc
  paddle/phi/infermeta/unary.cc
  paddle/phi/kernels/cpu/sgd_kernel.cc
  python/paddle/jit/dy2static/convert_call_func.py
Labels: contributor, HappyOpenSource

#61126 Fix attrbute attribute
  paddle/cinn/frontend/op_mappers/science/transform.cc
  paddle/cinn/frontend/paddle/cpp/op_desc.cc
  paddle/cinn/hlir/op/transform.cc
  paddle/fluid/operators/sequence_ops/sequence_expand_op.cc
Labels: contributor, HappyOpenSource

#61123 Fix finded_ops found_ops
  python/paddle/jit/dy2static/partial_program.py
  python/paddle/jit/dy2static/pir_partial_program.py
Labels: contributor, HappyOpenSource

#61113 Fix recyle_ops recycle_ops
  paddle/fluid/framework/hogwild_worker.cc
Labels: contributor, HappyOpenSource

#61189 Fix initilizer initializer
  test/legacy_test/auto_parallel_gpt_model.py
  test/legacy_test/test_auto_parallel_completion_gpt.py
  test/legacy_test/test_auto_parallel_partitioner_gpt.py
  test/legacy_test/test_dropout_op.py
  test/legacy_test/test_elementwise_max_op.py
  test/legacy_test/test_elementwise_min_op.py
  test/legacy_test/test_imperative_mnist.py
  test/legacy_test/test_imperative_optimizer.py
  test/legacy_test/test_imperative_optimizer_v2.py
  test/legacy_test/test_imperative_resnet.py
  test/legacy_test/test_imperative_se_resnext.py
  test/legacy_test/test_imperative_transformer_sorted_gradient.py
  test/legacy_test/test_initializer.py
  test/legacy_test/test_initializer_nn.py
  test/legacy_test/test_launch_coverage.py
  test/legacy_test/test_layout_autotune.py
  test/legacy_test/test_modelaverage.py
  test/legacy_test/test_optimizer_in_control_flow.py
  test/legacy_test/test_parallel_executor_transformer.py
  test/legacy_test/test_transforms.py
Labels: contributor, HappyOpenSource

#61175 Fix shoudl should
  paddle/phi/kernels/funcs/jit/helper.h
  paddle/phi/kernels/funcs/jit/more/mkl/mkl.h
  paddle/phi/kernels/funcs/jit/refer/refer.h
  python/paddle/metric/metrics.py
  python/paddle/nn/clip.py
  python/paddle/quantization/ptq.py
  python/paddle/quantization/qat.py
  python/paddle/vision/ops.py
Labels: contributor, HappyOpenSource

#59601 【Hackathon 5th No.105】 fix the bug in moving fusion_gru_mkldnn to phi -part
  paddle/fluid/framework/ir/mkldnn/multi_gru_seq_fuse_pass.cc
  paddle/fluid/operators/ops_extra_info.h
  paddle/phi/api/yaml/fused_ops.yaml
  paddle/phi/api/yaml/op_compat.yaml
  paddle/phi/infermeta/fusion.cc
  paddle/phi/infermeta/fusion.h
  paddle/phi/kernels/fusion/cpu/fusion_gru_kernel.cc
  paddle/phi/kernels/fusion/onednn/fusion_gru_kernel.cc
Labels: PaddlePaddle Hackathon, contributor

#61153 Fix excuted executed
  python/paddle/static/nn/static_pylayer.py
  python/paddle/static/quantization/post_training_quantization.py
  python/paddle/static/quantization/quant2_int8_mkldnn_pass.py
  python/paddle/static/quantization/quantization_pass.py
  python/paddle/tensor/attribute.py
  python/paddle/tensor/einsum.py
  python/paddle/tensor/math.py
  python/paddle/tensor/random.py
  python/paddle/tensor/search.py
  python/paddle/utils/cpp_extension/extension_utils.py
Labels: contributor, HappyOpenSource

#61191 clean eval_frame.c
  paddle/fluid/pybind/eval_frame.c
Labels: contributor

#61199 [XPU] update xpu.cmake xhpc date
  cmake/external/xpu.cmake
Labels: contributor

#61038 [PIR] A-14 Adapt matmul test_errors
  test/legacy_test/test_matmul_op.py
Labels: contributor, HappyOpenSource
