Repository PaddlePaddle/Paddle, pull requests merged in 2024-02, with the labels that each got.

#61412 [SOT][3.12] open some test
  test/sot/skip_files_py312
Labels: contributor

#61392 Fix eaqual equal
  paddle/fluid/framework/lod_tensor.cc
  paddle/phi/kernels/funcs/sparse/sparse_blas_impl.cu.h
  paddle/phi/kernels/funcs/sparse/sparse_blas_impl.hip.h
  paddle/phi/kernels/gpu/multinomial_kernel.cu
  paddle/phi/kernels/sparse/gpu/addmm_kernel.cu
  paddle/phi/kernels/sparse/gpu/matmul_kernel.cu
  paddle/phi/kernels/sparse/gpu/mv_kernel.cu
Labels: contributor, HappyOpenSource

#61404 Fix ohther other
  paddle/fluid/framework/data_feed.h
  paddle/fluid/framework/data_set.cc
  paddle/fluid/framework/data_transform.cc
  paddle/fluid/framework/data_type_transform.cc
  paddle/fluid/framework/paddle2cinn/cinn_graph_symbolization.cc
Labels: contributor, HappyOpenSource

#61318 Fix BindVarDsec BindVarDesc
  paddle/fluid/pybind/protobuf.cc
  paddle/fluid/pybind/protobuf.h
  paddle/fluid/pybind/pybind.cc
Labels: contributor, HappyOpenSource

#61148 [XPU] bind mean_all_grad xpu kernel
  cmake/external/xpu.cmake
  paddle/phi/kernels/xpu/mean_all_grad_kernel.cc
Labels: contributor

#61383 Fix pruns prunes
  paddle/CMakeLists.txt
  paddle/fluid/framework/ir/conv_bn_fuse_pass_tester.cc
  paddle/fluid/framework/ir/cudnn_placement_pass_tester.cc
  paddle/fluid/framework/ir/cutlass_teller.h
  paddle/fluid/framework/ir/gpu_cpu_map_matmul_to_mul_pass.h
  paddle/fluid/framework/ir/graph_pattern_detector.h
  paddle/fluid/framework/ir/layernorm_shift_partition_fuse_pass.h
  paddle/fluid/framework/ir/lock_free_optimize_pass.cc
  paddle/fluid/framework/ir/trt_flash_multihead_matmul_fuse_pass.cc
  paddle/fluid/framework/ir/trt_qk_multihead_matmul_fuse_pass.cc
  paddle/fluid/framework/ir/xpu/multi_encoder_xpu_fuse_pass.cc
  paddle/fluid/framework/ir/yolo_box_fuse_pass.h
  paddle/fluid/operators/array_to_lod_tensor_op.cc
  paddle/fluid/operators/detection/locality_aware_nms_op.cc
  paddle/fluid/operators/detection/multiclass_nms_op.cc
  paddle/fluid/operators/detection/prior_box_op.h
  paddle/fluid/operators/dlnne/dlnne_engine_op.cc
  paddle/fluid/operators/fake_dequantize_op.cc
  paddle/fluid/operators/fake_quantize_op.cc
  paddle/fluid/operators/fused/fused_transformer_op.h
  paddle/fluid/operators/fused_token_prune_op.cc
  paddle/fluid/operators/gru_op.cc
  paddle/fluid/operators/im2sequence_op.cc
  paddle/fluid/operators/interpolate_op.cc
  paddle/fluid/operators/partial_sum_op.cc
  paddle/fluid/operators/reduce_ops/reduce_op.h
  paddle/fluid/operators/reshape_op.cc
  paddle/fluid/operators/sequence_ops/sequence_expand_op.cc
  paddle/fluid/operators/sequence_ops/sequence_pad_op.cc
Labels: contributor, HappyOpenSource

#61372 【paddle_test No.23】replace cc_test with paddle_test
  test/cpp/fluid/dlnne/CMakeLists.txt
Labels: contributor, HappyOpenSource

#60838 【PIR Dist Op Reg No.18】 reg lars_momentum
  paddle/fluid/operators/optimizers/lars_momentum_op.cc
  paddle/fluid/pir/dialect/op_generator/ops_api_gen.py
  paddle/fluid/pir/dialect/operator/ir/ops.yaml
Labels: contributor, HappyOpenSource

#61222 Write a pass to check infer symbolic.
  paddle/cinn/hlir/dialect/operator/transforms/group_merge/check_infer_symbolic_pass.cc
  paddle/cinn/hlir/dialect/operator/transforms/group_merge/check_infer_symbolic_pass.h
  paddle/fluid/pybind/pir.cc
  paddle/phi/core/flags.cc
  test/ir/pir/cinn/symbolic/CMakeLists.txt
  test/ir/pir/cinn/symbolic/test_check_infer_symbolic.py
Labels: contributor

#60834 【paddle_test No.5】replace cc_test with paddle_test
  paddle/cinn/frontend/interpreter.h
  paddle/fluid/framework/new_executor/interpretercore.h
  paddle/fluid/pir/dialect/op_generator/op_gen.py
  paddle/fluid/pir/dialect/operator/ir/control_flow_op.h
  paddle/fluid/pir/dialect/operator/ir/manual_op.h
  test/cpp/pir/control_flow_dialect/CMakeLists.txt
Labels: contributor, HappyOpenSource

#61306 Fix Retrive Retrieve, CI 错误修改 PaddleTest
  paddle/fluid/inference/api/analysis_predictor.cc
  paddle/fluid/inference/api/paddle_inference_api.h
  paddle/fluid/pybind/inference_api.cc
  test/cpp/inference/api/paddle_infer_api_test.cc
  test/cpp/inference/api/trt_mobilenet_test.cc
  test/cpp/inference/infer_ut/test_LeViT.cc
  test/cpp/inference/infer_ut/test_det_mv3_db.cc
  test/cpp/inference/infer_ut/test_ernie_text_cls.cc
  test/cpp/inference/infer_ut/test_mobilnetv1.cc
  test/cpp/inference/infer_ut/test_ppyolo_mbv3.cc
  test/cpp/inference/infer_ut/test_ppyolov2_r50vd.cc
  test/cpp/inference/infer_ut/test_resnet50.cc
  test/cpp/inference/infer_ut/test_resnet50_quant.cc
  test/cpp/inference/infer_ut/test_yolov3.cc
Labels: contributor

#61382 [Security] fix security problem for prune_by_memory_estimation
  python/paddle/distributed/auto_tuner/prune.py
Labels: contributor

#60602 【PIR OpTest Fix No.2】 fix test_empty_op
  test/white_list/pir_op_test_no_check_list
  test/white_list/pir_op_test_white_list
Labels: contributor, HappyOpenSource

#61324 Fix feasgin_to_box feasign_to_box
  paddle/fluid/framework/fleet/box_wrapper.cc
  paddle/fluid/framework/fleet/box_wrapper.h
Labels: contributor, HappyOpenSource

#61414 [SOT][3.12] Don't fallback to AST mode in Python 3.12
  python/paddle/jit/api.py
  test/sot/skip_files_py312
Labels: contributor

#60070 为 paddle.linalg.norm 进行功能升级与对齐
  python/paddle/linalg.py
  python/paddle/tensor/linalg.py
  test/legacy_test/test_norm_all.py
Labels: PaddlePaddle Hackathon, contributor

#61045 [cherry-pick] adapt c_embedding to phi namespace for custom devices
  paddle/phi/kernels/CMakeLists.txt
  paddle/phi/kernels/custom/c_embedding_grad_kernel.cc
  paddle/phi/kernels/custom/c_embedding_kernel.cc
  test/legacy_test/c_embedding_op_base.py
Labels: contributor, heco

#61374 【paddle_test No.25】replace cc_test with paddle_test
  paddle/phi/core/tensor_array.h
  test/cpp/fluid/controlflow/CMakeLists.txt
  test/cpp/fluid/controlflow/conditional_block_op_test.cc
Labels: contributor, HappyOpenSource

#61484 [Cleanup][C-18] clean some Program.random_seed for test
  test/dygraph_to_static/test_word2vec.py
  test/dygraph_to_static/test_yolov3.py
  test/legacy_test/test_weight_decay.py
  test/quantization/test_user_defined_quantization.py
  test/quantization/test_weight_only_linear.py
Labels: contributor, HappyOpenSource

#61273 Update global_value_getter_setter.cc
  paddle/fluid/pybind/global_value_getter_setter.cc
Labels: contributor, HappyOpenSource

#61426 Fix SetFininshed SetFinished
  paddle/fluid/framework/new_executor/garbage_collector/event_garbage_collector.cc
  paddle/fluid/platform/device_event_base.h
  paddle/fluid/platform/device_event_test.cc
Labels: contributor, HappyOpenSource

#61390 Fix GetGradientHookFuntions GetGradientHookFunctions
  paddle/fluid/eager/general_grad.h
  paddle/fluid/eager/grad_node_info.h
Labels: contributor, HappyOpenSource

#61419 Fix maseked_select masked_select
  test/legacy_test/test_zero_dim_tensor.py
  test/xpu/test_reduce_amin_op_xpu.py
  test/xpu/test_set_value_op_xpu.py
  test/xpu/test_sum_op_xpu.py
  test/xpu/test_zero_dim_tensor_xpu.py
Labels: contributor, HappyOpenSource

#61420 Update fs.py
  python/paddle/distributed/fleet/utils/fs.py
Labels: contributor, HappyOpenSource

#60295 Enable workspace optimization for cudnn flash attention
  paddle/phi/kernels/fusion/gpu/fused_dot_product_attention_op.cu
  python/paddle/incubate/nn/functional/fused_dot_product_attention.py
  test/legacy_test/test_fuse_dot_product_attention_pass.py
  test/legacy_test/test_fused_dot_product_attention_op.py
Labels: NVIDIA, contributor

#61513 [Cleanup][C-11]Replace Program.random_seed
  test/quantization/test_imperative_qat.py
  test/quantization/test_imperative_qat_amp.py
  test/quantization/test_imperative_qat_lsq.py
  test/quantization/test_imperative_qat_matmul.py
  test/quantization/test_imperative_qat_user_defined.py
Labels: HappyOpenSource

#61476 [Cleanup][B-6] clean some `to_variable` for test
  test/legacy_test/test_dot_op.py
  test/legacy_test/test_dropout_op.py
  test/legacy_test/test_dygraph_mnist_fp16.py
  test/legacy_test/test_dygraph_multi_forward.py
  test/legacy_test/test_dygraph_weight_norm.py
  test/legacy_test/test_egr_python_api.py
  test/legacy_test/test_eig_op.py
  test/legacy_test/test_elementwise_add_op.py
  test/xpu/test_dropout_op_xpu.py
  test/xpu/test_elementwise_add_op_xpu.py
Labels: contributor, HappyOpenSource

#61510 [Cleanup][C-16] clean some random_seed for test
  test/dygraph_to_static/test_save_inference_model.py
  test/dygraph_to_static/test_seq2seq.py
  test/legacy_test/test_rnn_decode_api.py
  test/legacy_test/test_static_save_load.py
  test/quantization/test_quantization_scale_pass.py
Labels: HappyOpenSource

#61511 [Cleanup][B-7] clean some to_variable for test
  test/dygraph_to_static/test_for_enumerate.py
  test/legacy_test/test_elementwise_pow_op.py
  test/legacy_test/test_elementwise_sub_op.py
  test/legacy_test/test_erf_op.py
  test/legacy_test/test_exception.py
  test/legacy_test/test_fill_constant_op.py
  test/legacy_test/test_fleet_base.py
  test/legacy_test/test_flip.py
  test/legacy_test/test_functional_conv1d.py
  test/xpu/test_elementwise_add_op_xpu_kp.py
Labels: HappyOpenSource

#61377 Fix Paddle-TRT UT fails
  test/ir/inference/program_config.py
  test/ir/inference/test_trt_convert_assign.py
  test/ir/inference/test_trt_convert_cast.py
Labels: NVIDIA

#61526 [Cleanup][C-14]Replace Program.random_seed
  test/legacy_test/test_multiprocess_dataloader_dataset.py
  test/legacy_test/test_multiprocess_dataloader_dynamic.py
  test/legacy_test/test_multiprocess_dataloader_iterable_dataset_dynamic.py
  test/legacy_test/test_multiprocess_dataloader_iterable_dataset_static.py
  test/legacy_test/test_multiprocess_dataloader_static.py
Labels: HappyOpenSource

#61524 [Cleanup][C-3]Replace Program.random_seed
  test/legacy_test/dist_mnist_fp16_allreduce.py
  test/legacy_test/dist_mnist_lars.py
  test/legacy_test/dist_se_resnext.py
  test/legacy_test/dist_sharding_save.py
  test/legacy_test/dist_word2vec.py
Labels: HappyOpenSource

#61525 [Cleanup][C-13]Replace Program.random_seed
  test/ipu/test_model_parallel_ipu.py
  test/ipu/test_modelruntime_ipu.py
  test/legacy_test/test_layers.py
  test/legacy_test/test_metrics.py
  test/quantization/test_llm_int8_linear.py
Labels: HappyOpenSource

#61466 [Cleanup][A-1,A-2,A-3,A-4] clean some `VarType` for test
  test/auto_parallel/amp_o2_pass.py
  test/auto_parallel/test_pass_bf16.py
  test/collective/fleet/test_imperative_auto_mixed_precision_for_eager.py
  test/custom_op/test_custom_conj.py
  test/dygraph_to_static/test_to_tensor.py
  test/ir/test_ir_fusion_group_pass.py
  test/legacy_test/gradient_checker.py
  test/legacy_test/op_test.py
  test/legacy_test/test_batch_norm_op.py
  test/legacy_test/test_cummax_op.py
  test/legacy_test/test_cummin_op.py
  test/legacy_test/test_cumsum_op.py
  test/legacy_test/test_elementwise_add_op.py
  test/legacy_test/test_gather_op.py
  test/legacy_test/test_logcumsumexp_op.py
Labels: contributor, HappyOpenSource

#61497 [Cleanup][C-12]Replace Program.random_seed
  test/ipu/test_inference_model_io_ipu.py
  test/legacy_test/test_imperative_recurrent_usage.py
  test/legacy_test/test_lambv2_op.py
Labels: contributor, HappyOpenSource

#61538 [Cleanup][B-16]Replace to_variable
  test/dygraph_to_static/test_reinforcement_learning.py
  test/dygraph_to_static/test_save_load.py
  test/dygraph_to_static/test_se_resnet.py
  test/dygraph_to_static/test_sentiment.py
  test/legacy_test/test_repeat_interleave_op.py
  test/legacy_test/test_roll_op.py
  test/legacy_test/test_rot90_op.py
  test/legacy_test/test_scatter_nd_op.py
  test/legacy_test/test_scatter_op.py
  test/legacy_test/test_slice_op.py
Labels: HappyOpenSource

#61533 [Cleanup][B-12]Replace to_variable
  test/legacy_test/test_imperative_trace_non_persistable_inputs.py
  test/legacy_test/test_imperative_transformer_sorted_gradient.py
  test/legacy_test/test_imperative_triple_grad.py
  test/legacy_test/test_imperative_using_non_zero_gpu.py
  test/legacy_test/test_index_select_op.py
  test/legacy_test/test_instance_norm_op.py
  test/legacy_test/test_instance_norm_op_v2.py
  test/legacy_test/test_inverse_op.py
  test/xpu/test_index_select_op_xpu.py
  test/xpu/test_inverse_op_xpu.py
Labels: HappyOpenSource

#61530 [Cleanup][B-5] clean some `to_variable` for test
  test/contrib/test_correlation.py
  test/dygraph_to_static/test_cycle_gan.py
  test/dygraph_to_static/test_dict.py
  test/legacy_test/test_conv2d_transpose_layer.py
  test/legacy_test/test_conv3d_transpose_layer.py
  test/legacy_test/test_cross_op.py
  test/legacy_test/test_detach.py
  test/legacy_test/test_detection.py
Labels: HappyOpenSource

#61468 [Cleanup][B-1] clean some `paddle.base.dygraph.to_variable` for test
  test/collective/fleet/parallel_dygraph_control_flow_same.py
  test/collective/fleet/parallel_dygraph_se_resnext.py
  test/collective/fleet/parallel_dygraph_sync_batch_norm.py
  test/collective/fleet/parallel_dygraph_transformer.py
  test/legacy_test/op_test.py
  test/legacy_test/parallel_dygraph_mnist.py
  test/legacy_test/parallel_dygraph_shared_unused_var.py
  test/legacy_test/parallel_dygraph_sparse_embedding.py
  test/mkldnn/check_flags_mkldnn_ops_on_off.py
  test/mkldnn/check_flags_use_mkldnn.py
Labels: contributor, HappyOpenSource

#61527 [Cleanup][C-15]Replace Program.random_seed
  test/ipu/test_optimizer_ipu.py
  test/legacy_test/test_optimizer_in_control_flow.py
  test/quantization/test_quantization_mkldnn_pass.py
  test/quantization/test_quantization_pass.py
Labels: HappyOpenSource

#61535 [Cleanup][B-15]Replace to_variable
  test/dygraph_to_static/test_partial_program.py
  test/dygraph_to_static/test_pylayer.py
  test/legacy_test/test_one_hot_v2_op.py
  test/legacy_test/test_op_function_generator.py
  test/legacy_test/test_optimizer_in_control_flow.py
  test/legacy_test/test_paddle_imperative_double_grad.py
  test/legacy_test/test_reduce_op.py
  test/legacy_test/test_regularizer.py
  test/legacy_test/test_regularizer_api.py
  test/xpu/test_one_hot_v2_op_xpu.py
Labels: HappyOpenSource

#61512 [Cleanup][C-10]Replace Program.random_seed
  test/legacy_test/test_imperative_hook_for_layer.py
  test/legacy_test/test_imperative_mnist.py
  test/legacy_test/test_imperative_mnist_sorted_gradient.py
  test/quantization/test_imperative_out_scale.py
  test/quantization/test_imperative_ptq.py
Labels: HappyOpenSource

#61531 [Cleanup][B-10]Replace to_variable
  test/legacy_test/test_imperative_hook_for_layer.py
  test/legacy_test/test_imperative_layer_trainable.py
  test/legacy_test/test_imperative_lod_tensor_to_selected_rows.py
  test/legacy_test/test_imperative_mnist_sorted_gradient.py
  test/legacy_test/test_imperative_named_members.py
  test/legacy_test/test_imperative_ocr_attention_model.py
  test/legacy_test/test_imperative_optimizer.py
  test/legacy_test/test_imperative_optimizer_v2.py
  test/legacy_test/test_imperative_parallel_coalesce_split.py
  test/legacy_test/test_imperative_partitial_backward.py
Labels: HappyOpenSource

#61539 [Cleanup][B-17]Replace to_variable
  test/legacy_test/test_smooth_l1_loss.py
  test/legacy_test/test_softmax_mask_fuse_op.py
  test/legacy_test/test_softmax_mask_fuse_upper_triangle_op.py
  test/legacy_test/test_solve_op.py
  test/legacy_test/test_stack_op.py
  test/legacy_test/test_traced_layer_err_msg.py
  test/legacy_test/test_transpose_op.py
  test/legacy_test/test_tril_triu_op.py
  test/legacy_test/test_unfold_op.py
  test/xpu/test_unfold_op_xpu.py
Labels: contributor, HappyOpenSource

#61434 [Prim][PIR] square forward decomp
  paddle/fluid/pir/dialect/op_generator/decomp_interface_gen_op_list.py
  paddle/fluid/primitive/composite/composite.h
  test/legacy_test/test_activation_op.py
Labels: contributor

#61309 [Fix][AutoParallel] Fix Visualize Tool for vpp mode
  python/paddle/distributed/auto_parallel/static/profiler_helper_static.py
Labels: contributor

#61532 [Cleanup][B-11]Replace to_variable
  test/legacy_test/test_imperative_ptb_rnn.py
  test/legacy_test/test_imperative_ptb_rnn_sorted_gradient.py
  test/legacy_test/test_imperative_recurrent_usage.py
  test/legacy_test/test_imperative_reinforcement.py
  test/legacy_test/test_imperative_resnet.py
  test/legacy_test/test_imperative_resnet_sorted_gradient.py
  test/legacy_test/test_imperative_save_load_v2.py
  test/legacy_test/test_imperative_selected_rows.py
  test/legacy_test/test_imperative_selected_rows_to_lod_tensor.py
  test/legacy_test/test_imperative_star_gan_with_gradient_penalty.py
Labels: contributor, HappyOpenSource

#61521 [Cleanup][C-5]Replace Program.random_seed
  test/ipu/distributed/test_dist_data_parallel_ipu.py
  test/ipu/distributed/test_dist_pod128_sample.py
  test/legacy_test/test_desc_clone.py
  test/legacy_test/test_detection.py
  test/legacy_test/test_dist_base.py
Labels: contributor, HappyOpenSource

#61517 [Cleanup][C-9]Replace Program.random_seed
  test/ipu/test_identity_loss_ipu.py
  test/legacy_test/test_fused_multi_transformer_op.py
  test/legacy_test/test_fused_transformer_encoder_layer.py
  test/legacy_test/test_imperative_deepcf.py
Labels: contributor, HappyOpenSource

#61518 [Cleanup][C-8]Replace Program.random_seed
  test/legacy_test/test_fused_ec_moe_op.py
  test/legacy_test/test_fused_feedforward_op.py
  test/legacy_test/test_fused_feedforward_pass.py
  test/legacy_test/test_fused_multi_transformer_int8_op.py
  test/xpu/test_fused_feedforward_op_xpu.py
Labels: contributor, HappyOpenSource

#61550 [Cleanup][A-6] clean some `VarType` for test
  test/legacy_test/test_gaussian_random_op.py
  test/legacy_test/test_lod_tensor.py
  test/legacy_test/test_math_op_patch.py
  test/legacy_test/test_math_op_patch_var_base.py
  test/legacy_test/test_parameter.py
Labels: HappyOpenSource

#61408 Fix decotate decorate
  python/paddle/amp/auto_cast.py
  python/paddle/base/executor.py
  python/paddle/distributed/fleet/meta_optimizers/sharding/utils.py
  python/paddle/distributed/fleet/meta_optimizers/sharding_optimizer.py
  python/paddle/distributed/fleet/meta_parallel/pp_utils/four_directions_p2p_communication.py
  python/paddle/distributed/fleet/meta_parallel/pp_utils/p2p_communication.py
  python/paddle/distributed/fleet/recompute/recompute_hybrid.py
  python/paddle/distributed/fleet/utils/fs.py
  python/paddle/distributed/fleet/utils/hybrid_parallel_inference.py
  python/paddle/distributed/fleet/utils/pp_parallel_adaptor.py
  python/paddle/distributed/transpiler/distribute_transpiler.py
  python/paddle/hapi/model.py
  python/paddle/incubate/distributed/models/moe/moe_layer.py
  python/paddle/incubate/nn/functional/masked_multihead_attention.py
  python/paddle/incubate/nn/layer/fused_ec_moe.py
  python/paddle/incubate/nn/layer/fused_linear.py
  python/paddle/incubate/nn/layer/fused_transformer.py
  python/paddle/incubate/operators/resnet_unit.py
  python/paddle/incubate/optimizer/modelaverage.py
  python/paddle/incubate/optimizer/pipeline.py
  python/paddle/incubate/xpu/resnet_block.py
  python/paddle/io/dataloader/batch_sampler.py
  python/paddle/io/dataloader/worker.py
  python/paddle/io/multiprocess_utils.py
  python/paddle/io/reader.py
  python/paddle/jit/api.py
  python/paddle/jit/dy2static/partial_program.py
  python/paddle/jit/translated_layer.py
  python/paddle/nn/functional/activation.py
  python/paddle/nn/layer/common.py
  python/paddle/nn/layer/layers.py
  python/paddle/nn/layer/transformer.py
  python/paddle/static/amp/decorator.py
  python/paddle/static/amp/fp16_lists.py
  python/paddle/tensor/manipulation.py
Labels: contributor, HappyOpenSource

#61520 [Cleanup][C-6]Replace Program.random_seed
  test/ipu/distributed/test_dist_sample.py
  test/legacy_test/test_dist_transpiler.py
  test/legacy_test/test_eager_deletion_dynamic_rnn_base.py
Labels: contributor, HappyOpenSource

#61545 [Cleanup][B-19]Replace to_variable
  python/paddle/amp/grad_scaler.py
  python/paddle/base/dygraph/tensor_patch_methods.py
  python/paddle/base/framework.py
  python/paddle/base/layers/math_op_patch.py
  python/paddle/distributed/fleet/meta_parallel/sharding/group_sharded_utils.py
  python/paddle/distributed/fleet/utils/mix_precision_utils.py
Labels: HappyOpenSource

#61425 Fix manully manually
  paddle/cinn/api/README.md
  paddle/fluid/eager/auto_code_generator/eager_generator.cc
  paddle/fluid/eager/custom_operator/custom_operator_utils.cc
  paddle/fluid/eager/eager_layout_auto_tune.h
  paddle/fluid/eager/eager_tensor.h
  paddle/fluid/eager/pylayer/py_layer_node.cc
  paddle/fluid/eager/to_static/run_program_op_node.h
  paddle/fluid/eager/utils.h
  paddle/fluid/framework/details/broadcast_op_handle.cc
  paddle/fluid/framework/executor_cache.cc
  paddle/fluid/framework/executor_cache.h
  paddle/fluid/inference/api/paddle_inference_api.h
  paddle/fluid/inference/tensorrt/convert/multihead_matmul_op.cc
  paddle/fluid/inference/tensorrt/convert/multihead_matmul_roformer_op.cc
  paddle/fluid/inference/tensorrt/convert/sparse_fc_op.cc
  paddle/fluid/inference/tensorrt/convert/sparse_multihead_matmul_op.cc
  paddle/fluid/platform/device/ipu/ipu_compiler.cc
  paddle/fluid/platform/device/ipu/popart_canonicalization/tensor_ops.cc
  paddle/fluid/platform/init.cc
  paddle/fluid/platform/mkldnn_helper.h
  paddle/fluid/platform/profiler_helper.h
  paddle/fluid/prim/api/auto_code_generated/eager_gen.py
  paddle/fluid/prim/api/auto_code_generated/tensor_operants_gen.py
  paddle/fluid/prim/api/composite_backward/composite_backward_api.h
  paddle/fluid/prim/utils/static/desc_tensor.h
  paddle/fluid/primitive/codegen/gen.py
  paddle/fluid/primitive/composite/composite.h
  paddle/fluid/primitive/rule/vjp/details.h
  paddle/fluid/pybind/place.cc
  paddle/fluid/pybind/tensor_py.h
  paddle/phi/api/profiler/device_tracer.cc
  paddle/phi/api/profiler/event_tracing.h
  paddle/phi/common/transform.h
  paddle/phi/kernels/cpu/top_k_kernel.cc
Labels: contributor, HappyOpenSource

#61463 【paddle_test No.20】replace cc_test with paddle_test
  paddle/fluid/platform/device/gpu/gpu_info.h
  test/cpp/fluid/framework/details/CMakeLists.txt
Labels: contributor, HappyOpenSource

#61548 [Cleanup][A-7] Replace `VarType`
  test/legacy_test/test_rand_op.py
  test/legacy_test/test_tensor.py
  test/legacy_test/test_uniform_random_op.py
  test/legacy_test/test_var_base.py
Labels: HappyOpenSource

#61519 [Cleanup][C-7]Replace Program.random_seed
  test/ipu/test_eval_model_ipu.py
  test/legacy_test/test_fused_attention_op.py
  test/legacy_test/test_fused_bias_dropout_residual_layer_norm_op.py
Labels: contributor, HappyOpenSource

#61549 [Cleanup][A-5] clean some `VarType` for test
  test/collective/fleet/test_fleet_amp_meta_optimizer.py
  test/collective/fleet/test_fleet_gradient_merge_meta_optimizer.py
  test/legacy_test/test_data.py
  test/legacy_test/test_egr_python_api.py
  test/legacy_test/test_executor_feed_non_tensor.py
Labels: HappyOpenSource

#61574 [Cleanup][B-14] Replace to_variable
  test/dygraph_to_static/test_mnist.py
  test/dygraph_to_static/test_mobile_net.py
  test/legacy_test/test_mean_op.py
  test/legacy_test/test_merged_adam_op.py
  test/legacy_test/test_meshgrid_op.py
  test/legacy_test/test_mse_loss.py
  test/legacy_test/test_nansum_api.py
  test/legacy_test/test_nn_functional_hot_op.py
  test/legacy_test/test_nonzero_api.py
  test/xpu/test_merged_adam_op_xpu.py
Labels: contributor

#61585 [Cleanup][B-9] Replace to_variable
  test/collective/fleet/test_imperative_auto_mixed_precision_for_eager.py
  test/legacy_test/test_histogram_op.py
  test/legacy_test/test_imperative_container_layerlist.py
  test/legacy_test/test_imperative_container_parameterlist.py
  test/legacy_test/test_imperative_container_sequential.py
  test/legacy_test/test_imperative_deepcf.py
  test/legacy_test/test_imperative_double_grad.py
  test/legacy_test/test_imperative_framework.py
  test/legacy_test/test_imperative_gan.py
  test/legacy_test/test_imperative_gnn.py
Labels: contributor

#61581 [Cleanup][B-8] Replace to_variable
  test/legacy_test/test_functional_conv1d_transpose.py
  test/legacy_test/test_functional_conv2d.py
  test/legacy_test/test_functional_conv2d_transpose.py
  test/legacy_test/test_functional_conv3d.py
  test/legacy_test/test_functional_conv3d_transpose.py
  test/legacy_test/test_gather_nd_op.py
  test/legacy_test/test_gelu_op.py
  test/legacy_test/test_grad_clip_minimize.py
  test/legacy_test/test_gradient_clip.py
  test/legacy_test/test_group_norm_op.py
Labels: contributor

#61541 [AutoParallel] Fit send_recv overlap for vpp
  python/paddle/distributed/passes/pass_utils.py
  python/paddle/distributed/passes/pipeline_scheduler_pass.py
  test/auto_parallel/pipeline_scheduler_vpp_unittest.py
Labels: contributor

#61029 [XPU] bind dropout_v2
  paddle/phi/kernels/xpu/dropout_grad_kernel.cc
  paddle/phi/kernels/xpu/dropout_kernel.cc
Labels: contributor

#61553 [Cleanup][A-8] clean some `VarType` for test
  test/legacy_test/test_variable.py
  test/sequence/test_sequence_pad_op.py
  test/xpu/test_gaussian_random_op_xpu.py
Labels: contributor, HappyOpenSource

#61504 [Cleanup][C-17] clean some `random_seed` for test
  test/ir/inference/test_trt_conv_quant_dequant_pass.py
  test/ir/inference/test_trt_fc_fuse_quant_dequant_pass.py
  test/ir/inference/test_trt_matmul_quant_dequant.py
  test/legacy_test/test_static_save_load_bf16.py
Labels: contributor, HappyOpenSource

#61603 [Cleanup][B-13]Replace to_variable part2
  test/dygraph_to_static/test_lac.py
  test/legacy_test/test_jit_save_load.py
Labels: contributor

#61534 [Cleanup][B-13]Replace to_variable
  test/legacy_test/test_kron_op.py
  test/legacy_test/test_label_smooth_functional.py
  test/legacy_test/test_learning_rate_scheduler.py
  test/legacy_test/test_linear_interp_op.py
  test/legacy_test/test_linear_interp_v2_op.py
  test/legacy_test/test_matmul_op.py
  test/legacy_test/test_matrix_power_op.py
  test/xpu/test_matmul_op_xpu.py
Labels: contributor, HappyOpenSource

#61599 [PIR] fix_test_conv_pir
  python/paddle/tensor/linalg.py
  test/legacy_test/test_zero_dim_tensor.py
Labels: contributor

#61601 [CustomDevice] remove restrain of device of group_sharded_parallel api
  python/paddle/distributed/sharding/group_sharded.py
Labels: contributor

#61567 [Cleanup][A-14] clean some VarType for test
  python/paddle/tensor/creation.py
  python/paddle/tensor/to_string.py
Labels: contributor, HappyOpenSource

#61523 [Cleanup][C-4]Replace Program.random_seed
  test/ipu/custom_ops/test_custom_leaky_relu_ipu.py
  test/ipu/op_test_ipu.py
  test/legacy_test/ir_memory_optimize_net_base.py
Labels: contributor, HappyOpenSource

#61565 [Cleanup][A-12] clean some VarType for test
  python/paddle/jit/translated_layer.py
  python/paddle/static/amp/amp_nn.py
  python/paddle/static/amp/bf16/amp_utils.py
  python/paddle/static/amp/debugging.py
Labels: contributor, HappyOpenSource

#61666 [PIR] fix test_eager_deletion_while_op in pir mode
  test/legacy_test/test_eager_deletion_while_op.py
Labels: contributor

#61376 【paddle_test No.22】replace cc_test with paddle_test
  test/cpp/fluid/elementwise/CMakeLists.txt
Labels: contributor, HappyOpenSource

#61557 Fix _remove_not_supported_itmes
  python/paddle/incubate/distributed/utils/io/dist_load.py
Labels: contributor, HappyOpenSource

#61628 Fix _check_vaild_topo _check_valid_topo
  python/paddle/distributed/fleet/base/topology.py
  python/paddle/distributed/fleet/meta_parallel/pipeline_parallel.py
  python/paddle/distributed/fleet/recompute/recompute.py
  python/paddle/optimizer/adam.py
  python/paddle/optimizer/adamax.py
  python/paddle/optimizer/adamw.py
Labels: contributor, HappyOpenSource

#61564 [Cleanup][A-11] clean some VarType for test
  python/paddle/distributed/passes/auto_parallel_fp16.py
  python/paddle/distributed/passes/auto_parallel_master_grad.py
  python/paddle/hapi/model.py
  python/paddle/incubate/distributed/models/moe/grad_clip.py
  python/paddle/incubate/optimizer/distributed_fused_lamb.py
Labels: contributor, HappyOpenSource

#60830 【paddle_test No.1】replace cc_test with paddle_test
  paddle/fluid/pir/dialect/op_generator/op_gen.py
  paddle/fluid/pir/dialect/operator/ir/manual_op.h
  paddle/fluid/pir/drr/include/drr_match_context.h
  paddle/fluid/pir/drr/include/drr_pattern_base.h
  paddle/fluid/pir/drr/include/drr_pattern_context.h
  paddle/fluid/pir/transforms/transform_general_functions.h
  test/cpp/pir/pattern_rewrite/CMakeLists.txt
Labels: contributor, HappyOpenSource

#61373 【paddle_test No.24】replace cc_test with paddle_test
  paddle/fluid/memory/malloc.h
  paddle/fluid/operators/detection/mask_util.h
  test/cpp/fluid/detection/CMakeLists.txt
Labels: contributor, HappyOpenSource

#61692 [PIR] fix test_write_python_container in pir mode
  paddle/fluid/framework/new_executor/instruction/control_flow/while_instruction.cc
  test/dygraph_to_static/test_write_python_container.py
Labels: contributor

#61703 [SOT][3.12] Fix that `frame` in eval custom code was not released in `tstate`
  paddle/fluid/pybind/cpython_internals.c
  paddle/fluid/pybind/cpython_internals.h
  paddle/fluid/pybind/eval_frame.c
Labels: contributor

#61707 Fix some typos (seq_espand_functor, accorindg, etc.)
  paddle/fluid/operators/attention_lstm_op.cc
  paddle/fluid/operators/sequence_ops/sequence_expand_as_op.h
  paddle/fluid/operators/sequence_ops/sequence_pad_op.cc
  paddle/fluid/operators/sequence_ops/sequence_unpad_op.cc
  paddle/fluid/operators/string/faster_tokenizer_op.cc
  paddle/fluid/operators/tensorrt/tensorrt_engine_op.cc
  paddle/fluid/operators/tensorrt/tensorrt_engine_op.h
Labels: contributor, HappyOpenSource

#61560 Fix some typos (CommConetxt, yeild_op, etc.)
  test/auto_parallel/pipeline_scheduler_unittest.py
  test/auto_parallel/semi_auto_parallel_simple_net_fill_zero_for_emtpy_grad.py
  test/auto_parallel/test_comm_cost.py
  test/autograd/test_prim2orig.py
  test/cpp/inference/infer_ut/test_LeViT.cc
  test/cpp/inference/infer_ut/test_det_mv3_db.cc
  test/cpp/inference/infer_ut/test_ernie_text_cls.cc
  test/cpp/inference/infer_ut/test_mobilnetv1.cc
  test/cpp/inference/infer_ut/test_ppyolo_mbv3.cc
  test/cpp/inference/infer_ut/test_ppyolov2_r50vd.cc
  test/cpp/inference/infer_ut/test_resnet50.cc
  test/cpp/inference/infer_ut/test_resnet50_quant.cc
  test/cpp/inference/infer_ut/test_yolov3.cc
  test/cpp/phi/api/test_phi_tensor.cc
  test/cpp/phi/common/test_scalar.cc
  test/cpp/phi/kernels/test_math_function.cc
  test/cpp/pir/cinn/group_op_test.cc
  test/cpp/pir/pattern_rewrite/pattern_rewrite_test.cc
Labels: contributor, HappyOpenSource

#61684 Fix typo (`bolck` -> `block`)
  test/legacy_test/test_conv2d_op.py
  test/legacy_test/test_conv2d_transpose_op.py
  test/legacy_test/test_conv3d_op.py
  test/legacy_test/test_conv3d_transpose_op.py
  test/xpu/test_conv2d_op_xpu.py
  test/xpu/test_conv2d_transpose_op_xpu.py
  test/xpu/test_conv3d_op_xpu.py
  test/xpu/test_depthwise_conv2d_transpose_op_xpu.py
Labels: contributor, HappyOpenSource

#61710 [CodeStyle][ruff] clean some I001 step: 12
  pyproject.toml
  python/paddle/distributed/rpc/__init__.py
  python/paddle/incubate/distributed/fleet/__init__.py
  python/paddle/incubate/distributed/fleet/parameter_server/pslib/__init__.py
Labels: contributor

#61470 [Cleanup][C-2] clean some `Program.random_seed` for test
  test/legacy_test/dist_fleet_raw_program_optimizer.py
  test/legacy_test/dist_fleet_simnet_bow.py
  test/legacy_test/dist_mnist_dgc.py
Labels: contributor, HappyOpenSource

#61722 [CodeStyle][ruff] clean some I001 step: 13
  pyproject.toml
  python/paddle/amp/__init__.py
  python/paddle/distributed/communication/stream/__init__.py
  python/paddle/distributed/launch/context/__init__.py
  python/paddle/distributed/launch/controllers/__init__.py
Labels: contributor

#61305 [SOT][3.12] Support `LOAD_ATTR` opcode and skip `PRECALL_CALL` check in Python 3.12
  python/paddle/jit/sot/opcode_translator/executor/opcode_executor.py
  python/paddle/jit/sot/opcode_translator/executor/pycode_generator.py
  python/paddle/jit/sot/opcode_translator/instruction_utils/opcode_info.py
  test/sot/skip_files_py312
Labels: contributor

#61706 [Pybind] upgrade Pybind init usage
  paddle/fluid/pybind/generator_py.cc
  paddle/fluid/pybind/imperative.cc
  paddle/fluid/pybind/pir.cc
  paddle/fluid/pybind/place.cc
  paddle/fluid/pybind/protobuf.cc
  paddle/fluid/pybind/pybind.cc
  paddle/fluid/pybind/tensor.cc
Labels: contributor

#61724 Fix some typos (p_nrom, inferece, etc.)
  test/legacy_test/test_zero_dim_tensor.py
  test/legacy_test/testsuite.py
  test/legacy_test/transformer_model.py
  test/mkldnn/test_elementwise_add_bf16_mkldnn_op.py
  test/mkldnn/test_elementwise_add_onednn_op_rare_shape.py
  test/mkldnn/test_elementwise_mul_onednn_op.py
  test/mkldnn/test_fusion_lstm_bf16_mkldnn_op.py
  test/prim/prim/vjp/eager/test_comp_eager_matmul_double_grad.py
  test/rnn/rnn_numpy.py
  test/xpu/test_zero_dim_tensor_xpu.py
Labels: contributor, HappyOpenSource

#61719 Fix typo (`inlcude` -> `include`)
  paddle/phi/kernels/funcs/jit/README.en.md
  paddle/phi/kernels/funcs/sequence2batch.h
  test/legacy_test/test_assign_op.py
  test/legacy_test/test_cast_op.py
  test/legacy_test/test_concat_op.py
  test/legacy_test/test_elementwise_nn_grad.py
  test/legacy_test/test_expand_v2_op.py
  test/legacy_test/test_flip.py
  test/legacy_test/test_mean_op.py
  test/legacy_test/test_scale_op.py
  test/legacy_test/test_slice_op.py
  test/legacy_test/test_sum_op.py
  test/legacy_test/test_tile_op.py
  test/legacy_test/test_transpose_op.py
Labels: contributor

#61729 Fix typo (`TopologyVarientSort` -> `TopologyVariantSort`)
  paddle/fluid/framework/ir/constant_folding_pass.cc
  paddle/fluid/framework/ir/graph_helper.cc
  paddle/fluid/framework/ir/graph_helper.h
  paddle/fluid/framework/ir/mkldnn/compute_propagate_scales_mkldnn_pass.cc
  paddle/fluid/framework/ir/mkldnn/mkldnn_pass_util.h
  paddle/fluid/framework/ir/mkldnn/quant_dequant_mkldnn_pass.cc
  paddle/fluid/framework/ir/transfer_layout_elim_pass.cc
  paddle/fluid/framework/ir/xpu/quant_dequant_xpu_pass.cc
  paddle/fluid/inference/analysis/ir_passes/tensorrt_subgraph_pass.cc
  paddle/fluid/inference/analysis/passes/memory_optimize_pass.cc
Labels: contributor

#61763 Fix typo (`DistrubutedInputSpec` -> `DistributedInputSpec`)
  python/paddle/distributed/auto_parallel/static/dist_input_spec.py
  python/paddle/distributed/auto_parallel/static/engine.py
Labels: contributor

#61755 Fix some typos (sketchs, tunner, etc.)
  paddle/cinn/ast_gen_ius/tensor_group.cc
  paddle/cinn/auto_schedule/analysis/analyze_ir.h
  paddle/cinn/auto_schedule/cost_model/feature_extractor.h
  paddle/cinn/auto_schedule/search_space/auto_gen_rule/multi_level_tiling_test.cc
  paddle/cinn/auto_schedule/search_space/auto_gen_rule/reduction_factoring_test.cc
  paddle/cinn/auto_schedule/search_space/search_space.cc
  paddle/cinn/auto_schedule/tuning.h
  paddle/cinn/backends/_x86_builtin_source.cc
  paddle/cinn/backends/codegen_debug_test.cc
  paddle/cinn/frontend/op_mappers/paddle/constant.cc
Labels: contributor

#61737 Fix docstring in `moe_utils.py`
  python/paddle/distributed/utils/moe_utils.py
Labels: contributor

#61750 Fix typo (`starup_prog` -> `startup_prog`)
  test/dygraph_to_static/test_to_tensor.py
  test/legacy_test/test_activation_nn_grad.py
  test/legacy_test/test_adaptive_avg_pool2d.py
  test/legacy_test/test_arg_min_max_op.py
  test/legacy_test/test_attribute_var.py
  test/legacy_test/test_bincount_op.py
  test/legacy_test/test_conv2d_transpose_op.py
  test/legacy_test/test_cumsum_op.py
  test/legacy_test/test_eye_op.py
  test/legacy_test/test_multinomial_op.py
  test/legacy_test/test_pad_op.py
  test/legacy_test/test_squeeze2_op.py
  test/legacy_test/test_sum_op.py
  test/legacy_test/test_uniform_random_op.py
  test/legacy_test/test_unpool_op.py
  test/xpu/test_pad_op_xpu.py
Labels: contributor

#61753 Fix typo (`tesnor` -> `tensor`)
  paddle/fluid/jit/serializer.cc
  paddle/phi/kernels/memcpy_kernel.cc
  python/paddle/distributed/passes/auto_parallel_sharding.py
  test/cpp/phi/api/test_from_blob.cc
  test/legacy_test/test_cosine_similarity_api.py
Labels: contributor

#61756 Update add_broadcast_to_elementwise_pass.cc
  paddle/cinn/hlir/dialect/operator/transforms/add_broadcast_to_elementwise_pass.cc
Labels: contributor

#61758 Fix some typos (`accesor` -> `accessor`)
  paddle/fluid/distributed/ps/service/brpc_ps_server.cc
  paddle/fluid/distributed/ps/table/memory_dense_table.cc
  paddle/fluid/distributed/ps/table/memory_sparse_table.cc
  paddle/fluid/distributed/ps/table/ssd_sparse_table.cc
  paddle/fluid/distributed/ps/table/table.cc
  paddle/fluid/distributed/ps/table/table.h
  paddle/fluid/distributed/ps/wrapper/fleet.cc
  paddle/fluid/distributed/ps/wrapper/fleet.h
  paddle/fluid/framework/fleet/fleet_wrapper.cc
  paddle/fluid/framework/fleet/fleet_wrapper.h
  paddle/fluid/operators/pull_sparse_op.h
Labels: contributor

#61731 Fix typo (`pd_onfig` -> `pd_config`)
  paddle/fluid/inference/capi_exp/pd_config.h
Labels: contributor

#61711 [SOT][3.12] add `_PyEvalFrameClearAndPop` interpretative statement for `eval_frame`
  paddle/fluid/pybind/eval_frame.c
Labels: contributor

#61739 Fix typo (`EVENT_NOT_SWTICH` -> `EVENT_NOT_SWITCH`)
  paddle/fluid/framework/data_feed.cu
  paddle/fluid/framework/data_feed.h
Labels: contributor

#61559 Fix some typos (`tranpose`, `wamup`, etc.)
  test/cinn/passes/test_transpose_floding_output_pass.py
  test/dygraph_to_static/test_pylayer.py
  test/ir/inference/test_mkldnn_reshape_transpose_matmul_v2_fuse_pass.py
  test/ir/inference/test_trt_multiclass_nms3_op.py
  test/legacy_test/test_model.py
  test/legacy_test/test_sparse_model.py
  test/mkldnn/test_requantize_mkldnn_op.py
  test/prim/model/bert.py
  test/tokenizer/bert_tokenizer.py
Labels: contributor, HappyOpenSource

#61617 [xpu] multi_encoder_xpu supoort smooth quant, skip quant and local quant
  paddle/fluid/framework/ir/xpu/multi_encoder_xpu_fuse_pass.cc
  paddle/fluid/framework/ir/xpu/multi_encoder_xpu_fuse_pass.h
  paddle/fluid/framework/ir/xpu/pass_utils.cc
  paddle/fluid/framework/ir/xpu/pass_utils.h
  paddle/fluid/framework/ir/xpu/quant_dequant_xpu_pass.cc
  paddle/fluid/framework/ir/xpu/quant_utils.cc
  paddle/fluid/framework/ir/xpu/quant_utils.h
  paddle/fluid/inference/api/paddle_pass_builder.cc
  paddle/phi/api/yaml/fused_ops.yaml
  paddle/phi/infermeta/fusion.cc
  paddle/phi/infermeta/fusion.h
  paddle/phi/kernels/fusion/xpu/multi_encoder_xpu_kernel.cc
Labels: contributor

#60959 【paddle_test No.31, No.32】replace cc_test with paddle_test
  paddle/common/flags_native.cc
  paddle/utils/CMakeLists.txt
  paddle/utils/string/CMakeLists.txt
  test/cpp/CMakeLists.txt
  test/cpp/utils/CMakeLists.txt
  test/cpp/utils/array_ref_test.cc
  test/cpp/utils/flags_native_test.cc
  test/cpp/utils/small_vector_test.cc
  test/cpp/utils/span_test.cc
  test/cpp/utils/string/CMakeLists.txt
  test/cpp/utils/string/printf_test.cc
  test/cpp/utils/string/split_test.cc
  test/cpp/utils/string/string_helper_test.cc
  test/cpp/utils/string/to_string_test.cc
  test/cpp/utils/variant_test.cc
Labels: contributor, HappyOpenSource

#61652 Fix some typos (adapot, swith, etc.)
  python/paddle/distributed/passes/auto_parallel_fp16.py
  python/paddle/distributed/passes/auto_parallel_fused_linear_promotion.py
  python/paddle/distributed/passes/auto_parallel_grad_clip.py
  python/paddle/distributed/passes/auto_parallel_pipeline.py
  python/paddle/distributed/passes/auto_parallel_quantization.py
  python/paddle/distributed/passes/auto_parallel_sequence_parallel_optimization.py
  python/paddle/distributed/passes/auto_parallel_sharding.py
  python/paddle/distributed/passes/auto_parallel_supplement_explicit_dependencies.py
  python/paddle/distributed/passes/pass_utils.py
  python/paddle/distributed/ps/utils/public.py
Labels: contributor, HappyOpenSource

#61602 Fix some typos (maxmum, minimun_out, etc.)
  paddle/fluid/primitive/composite/composite.h
  python/paddle/incubate/autograd/composite_rules.py
  python/paddle/incubate/optimizer/functional/line_search.py
Labels: contributor, HappyOpenSource

#61558 Fix some typos (maitained, var_topoloy, etc.)
  python/paddle/distributed/auto_parallel/static/operators/common.py
  python/paddle/distributed/fleet/utils/fs.py
  python/paddle/distributed/fleet/utils/pp_parallel_adaptor.py
  python/paddle/static/amp/function_overload.py
  python/paddle/static/nn/sequence_lod.py
  python/paddle/tensor/creation.py
  python/paddle/tensor/einsum.py
  python/paddle/tensor/linalg.py
  python/paddle/tensor/random.py
  python/paddle/tensor/search.py
  python/paddle/tensor/to_string.py
Labels: contributor, HappyOpenSource

#61563 [Cleanup][A-10] clean some VarType for test
  python/paddle/distributed/auto_parallel/static/engine.py
  python/paddle/distributed/fleet/dataset/dataset.py
  python/paddle/distributed/fleet/meta_optimizers/sharding/offload_helper.py
  python/paddle/distributed/fleet/utils/mix_precision_utils.py
  python/paddle/distributed/passes/auto_parallel_amp.py
Labels: contributor, HappyOpenSource

#61546 [Cleanup][B-20] Replace `to_variable` with `to_tensor`
  python/paddle/distributed/fleet/scaler.py
  python/paddle/hapi/model.py
  python/paddle/nn/functional/loss.py
  python/paddle/nn/layer/norm.py
  python/paddle/pir/math_op_patch.py
Labels: contributor, HappyOpenSource

#61688 fix doc style
  python/paddle/quantization/quantize.py
Labels: contributor, HappyOpenSource

#61119 [PIR] A-17 Adapt transpose test_errors
  python/paddle/tensor/linalg.py
  test/legacy_test/test_transpose_op.py
Labels: contributor, HappyOpenSource

#61660 Fix some typos (default_deveice, Andorid, etc.)
  python/paddle/distributed/passes/ps_trainer_pass.py
  python/paddle/distributed/ps/coordinator.py
  python/paddle/distributed/ps/the_one_ps.py
  python/paddle/distributed/ps/utils/public.py
  python/paddle/distributed/transpiler/details/ufind.py
  python/paddle/distributed/transpiler/details/vars_distributed.py
  python/paddle/distributed/transpiler/distribute_transpiler.py
  python/paddle/distributed/utils/launch_utils.py
  python/paddle/distribution/bernoulli.py
  python/paddle/distribution/beta.py
  python/paddle/distribution/cauchy.py
  python/paddle/distribution/dirichlet.py
  python/paddle/incubate/distributed/fleet/parameter_server/ir/heter_trainer_pass.py
  python/paddle/incubate/distributed/fleet/parameter_server/ir/ufind.py
  python/paddle/incubate/distributed/fleet/parameter_server/ir/vars_metatools.py
Labels: contributor, HappyOpenSource

#61423 Update save_for_auto.py
  python/paddle/incubate/distributed/utils/io/save_for_auto.py
Labels: contributor

#61627 Update ci_dockerfile.sh
  tools/dockerfile/ci_dockerfile.sh
Labels: contributor, HappyOpenSource

#61685 Fix typo (`ingore` -> `ignore`)
  test/legacy_test/test_dot_op.py
  test/legacy_test/test_elementwise_add_op.py
  test/legacy_test/test_elementwise_div_op.py
  test/legacy_test/test_elementwise_heaviside_op.py
  test/legacy_test/test_elementwise_max_op.py
  test/legacy_test/test_elementwise_min_op.py
  test/legacy_test/test_elementwise_mul_op.py
  test/legacy_test/test_elementwise_sub_op.py
  test/legacy_test/test_fmax_op.py
  test/legacy_test/test_fmin_op.py
  test/legacy_test/test_fused_elemwise_activation_op.py
  test/legacy_test/test_gru_unit_op.py
  test/legacy_test/test_huber_loss_op.py
  test/legacy_test/test_kron_op.py
  test/legacy_test/test_lstm_op.py
  test/legacy_test/test_matmul_v2_op.py
  test/legacy_test/test_mul_op.py
  test/mkldnn/test_elementwise_add_bf16_mkldnn_op.py
  test/mkldnn/test_elementwise_add_mkldnn_op.py
  test/mkldnn/test_elementwise_mul_bf16_mkldnn_op.py
  test/mkldnn/test_elementwise_mul_onednn_op.py
  test/mkldnn/test_mul_mkldnn_op.py
  test/xpu/test_elementwise_add_op_xpu.py
  test/xpu/test_elementwise_add_op_xpu_kp.py
  test/xpu/test_elementwise_div_op_xpu.py
  test/xpu/test_elementwise_max_op_xpu.py
  test/xpu/test_elementwise_min_op_xpu.py
  test/xpu/test_elementwise_mul_op_xpu.py
  test/xpu/test_elementwise_sub_op_xpu.py
  test/xpu/test_huber_loss_op_xpu.py
  test/xpu/test_mul_op_xpu.py
  test/xpu/test_refactor_op_xpu.py
Labels: contributor, HappyOpenSource

#61690 Fix some typos (force_persisable, SolvePersisableVarNames, etc.)
  paddle/fluid/framework/new_executor/pir_adaptor/pir_adaptor_util.cc
  paddle/fluid/framework/new_executor/pir_adaptor/pir_adaptor_util.h
  paddle/fluid/framework/new_executor/pir_interpreter.cc
  paddle/fluid/framework/new_executor/pir_interpreter.h
  paddle/fluid/ir_adaptor/translator/program_translator.cc
  paddle/fluid/ir_adaptor/translator/program_translator.h
  paddle/fluid/pir/transforms/constant_folding_pass.cc
  paddle/fluid/pir/transforms/inplace_pass.cc
  paddle/fluid/pir/transforms/pd_op_to_kernel_pass.cc
  paddle/fluid/pybind/pir.cc
  paddle/pir/include/core/attribute.h
  python/paddle/autograd/backward_mode.py
  python/paddle/autograd/backward_utils.py
  python/paddle/autograd/ir_backward.py
  test/cpp/pir/core/TestParserText.txt
Labels: contributor, HappyOpenSource

#61727 Fix typo (`DataTranferHelper` -> `DataTransferHelper`)
  paddle/fluid/framework/new_executor/interpreter/data_transfer.cc
  paddle/fluid/framework/new_executor/interpreter/data_transfer.h
Labels: contributor, HappyOpenSource

#61738 Fix some typos (estabulished, desciriptor, etc.)
  paddle/phi/kernels/autotune/auto_tune_base.h
  paddle/phi/kernels/funcs/blas/blaslt_impl.cu.h
  python/paddle/base/compiler.py
  python/paddle/base/core.py
  python/paddle/base/data_feeder.py
  python/paddle/base/framework.py
  python/paddle/decomposition/rules.py
  python/paddle/device/__init__.py
  python/paddle/distributed/auto_parallel/static/cost/op_runtime_cost.py
  python/paddle/distributed/auto_parallel/static/operators/dist_eltwise.py
Labels: contributor, HappyOpenSource

#61740 Fix some typos (manully, scpoe_feed_vec_, etc.)
  paddle/fluid/framework/custom_operator.cc
  paddle/fluid/framework/data_feed.cc
  paddle/fluid/framework/data_feed.h
  paddle/fluid/framework/data_set.cc
  paddle/fluid/framework/data_set.h
  python/paddle/distributed/auto_parallel/static/operators/dist_dropout.py
  python/paddle/distributed/auto_parallel/static/operators/dist_eltwise.py
  python/paddle/distributed/auto_parallel/static/operators/dist_embedding.py
  python/paddle/distributed/auto_parallel/static/operators/dist_fused_dropout_add.py
  python/paddle/distributed/fleet/dataset/dataset.py
  python/paddle/distributed/fleet/elastic/manager.py
  python/paddle/distributed/fleet/layers/mpu/mp_layers.py
  python/paddle/distributed/fleet/layers/mpu/mp_ops.py
  python/paddle/distributed/fleet/meta_optimizers/sharding/gradient_clip_helper.py
  python/paddle/distributed/fleet/meta_optimizers/sharding/utils.py
Labels: contributor, HappyOpenSource

#61741 Fix some typos (distributd, _valide_env, etc.)
  python/paddle/distributed/launch/controllers/ipu_controller.py
  python/paddle/distributed/launch/job/container.py
  python/paddle/distributed/launch/job/pod.py
  python/paddle/distributed/launch/main.py
  python/paddle/distributed/passes/allreduce_matmul_grad_overlapping.py
  python/paddle/distributed/passes/auto_parallel_amp.py
  python/paddle/distributed/passes/auto_parallel_data_parallel_optimization.py
  python/paddle/distributed/passes/auto_parallel_grad_clip.py
  python/paddle/distributed/passes/auto_parallel_quantization.py
  python/paddle/distributed/passes/auto_parallel_recompute.py
  python/paddle/distributed/passes/pipeline_scheduler_pass.py
  python/paddle/distributed/passes/ps_server_pass.py
Labels: contributor, HappyOpenSource

#61743 Fix some typos (tanspose, vlaue, etc.)
  python/paddle/distribution/categorical.py
  python/paddle/distribution/multinomial.py
  python/paddle/distribution/multivariate_normal.py
  python/paddle/distribution/uniform.py
  python/paddle/framework/io.py
  python/paddle/hapi/model.py
  python/paddle/incubate/autograd/composite_rules.py
  python/paddle/incubate/autograd/functional.py
  python/paddle/incubate/autograd/generate_op_map.py
  python/paddle/incubate/autograd/primapi.py
  python/paddle/incubate/autograd/primops.py
  python/paddle/incubate/autograd/utils.py
  python/paddle/incubate/distributed/fleet/parameter_server/distribute_transpiler/distributed_strategy.py
  python/paddle/incubate/distributed/fleet/parameter_server/ir/public.py
  python/paddle/incubate/distributed/fleet/parameter_server/ir/trainer_pass.py
Labels: contributor, HappyOpenSource

#61566 [Cleanup][A-13] clean some VarType for test
  python/paddle/static/amp/decorator.py
  python/paddle/static/amp/fp16_lists.py
  python/paddle/static/amp/fp16_utils.py
  python/paddle/static/nn/common.py
  python/paddle/static/quantization/quantization_pass.py
Labels: contributor, HappyOpenSource

#61562 [Cleanup][A-9] clean some VarType for test
  python/paddle/amp/grad_scaler.py
  python/paddle/base/dataset.py
  python/paddle/base/framework.py
  python/paddle/distributed/auto_parallel/static/cost/base_cost.py
Labels: contributor, HappyOpenSource

#61744 Fix some typos (persistbale, Retruns, etc.)
  python/paddle/distributed/io.py
  python/paddle/distributed/parallel.py
  python/paddle/distributed/parallel_with_gloo.py
  python/paddle/distributed/spawn.py
  python/paddle/distributed/transpiler/collective.py
  python/paddle/distributed/utils/moe_utils.py
Labels: contributor, HappyOpenSource

#61745 Fix some typos (colective, fuctools, etc.)
  python/paddle/incubate/distributed/fleet/parameter_server/pslib/__init__.py
  python/paddle/incubate/distributed/fleet/parameter_server/pslib/node.py
  python/paddle/incubate/distributed/fleet/parameter_server/pslib/optimizer_factory.py
  python/paddle/incubate/distributed/fleet/role_maker.py
  python/paddle/incubate/distributed/utils/io/dist_save.py
  python/paddle/incubate/distributed/utils/io/save_for_auto.py
  python/paddle/incubate/multiprocessing/reductions.py
  python/paddle/incubate/nn/functional/fused_transformer.py
  python/paddle/incubate/nn/layer/fused_transformer.py
  python/paddle/incubate/optimizer/functional/bfgs.py
  python/paddle/incubate/optimizer/functional/lbfgs.py
  python/paddle/incubate/optimizer/functional/line_search.py
  python/paddle/incubate/optimizer/recompute.py
  python/paddle/incubate/xpu/resnet_block.py
  python/paddle/inference/wrapper.py
  python/paddle/io/dataloader/dataset.py
  python/paddle/io/dataloader/fetcher.py
  python/paddle/io/dataloader/sampler.py
  python/paddle/jit/dy2static/transformers/base.py
  python/paddle/jit/dy2static/transformers/basic_api_transformer.py
Labels: contributor, HappyOpenSource

#61762 Fix some typos (RebuildGruops, primtive, etc.)
  paddle/fluid/imperative/reducer.cc
  paddle/fluid/imperative/reducer.h
  python/paddle/distributed/auto_parallel/static/completion.py
  python/paddle/distributed/auto_parallel/static/engine.py
  python/paddle/distributed/auto_parallel/static/operators/dist_default.py
  python/paddle/distributed/auto_parallel/static/reshard.py
  python/paddle/distributed/auto_parallel/static/tuner/algorithms.py
  python/paddle/distributed/auto_parallel/static/tuner/rule_based_tuner.py
  python/paddle/distributed/auto_parallel/static/utils.py
  python/paddle/distributed/checkpoint/load_state_dict.py
  python/paddle/distributed/checkpoint/save_state_dict.py
Labels: contributor, HappyOpenSource

#61767 Fix some typos (outpus, componnets, etc.)
  python/paddle/nn/layer/pooling.py
  python/paddle/nn/layer/rnn.py
  python/paddle/nn/layer/vision.py
  python/paddle/nn/quant/lsq.py
  python/paddle/nn/quant/quant_layers.py
  python/paddle/nn/utils/weight_norm_hook.py
  python/paddle/optimizer/adagrad.py
  python/paddle/optimizer/adam.py
  python/paddle/optimizer/adamw.py
  python/paddle/optimizer/lbfgs.py
  python/paddle/optimizer/lr.py
  python/paddle/pir/math_op_patch.py
  python/paddle/profiler/profiler.py
  python/paddle/profiler/profiler_statistic.py
  python/paddle/profiler/timer.py
  python/paddle/profiler/utils.py
  python/paddle/quantization/base_quanter.py
  python/paddle/quantization/config.py
  python/paddle/quantization/imperative/ptq_registry.py
  python/paddle/quantization/imperative/qat.py
  python/paddle/static/amp/bf16/amp_utils.py
  python/paddle/static/amp/decorator.py
  python/paddle/static/amp/fp16_lists.py
  python/paddle/static/amp/fp16_utils.py
  python/paddle/static/nn/common.py
Labels: contributor, HappyOpenSource

#61768 Fix some typos (posision, DYgraph, etc.)
  python/paddle/static/nn/metric.py
  test/auto_parallel/semi_auto_parallel_simple_net_fill_zero_for_empty_grad.py
  test/auto_parallel/test_semi_auto_parallel_in_framework.py
  test/auto_parallel/test_static_gradient_sync.py
  test/collective/multinode/dygraph_hybrid_recompute.py
  test/collective/multinode/test_multinode_dygraph_hybrid_dp.py
  test/collective/multinode/test_multinode_dygraph_hybrid_dpppmp.py
  test/collective/multinode/test_multinode_dygraph_sharding.py
  test/collective/process_group_mpi.py
  test/collective/test_collective_alltoall_single_api.py
Labels: contributor, HappyOpenSource

#61774 Fix some typos (SetOverridedStopGradient, overrided_stop_gradient_, etc.)
  paddle/fluid/eager/auto_code_generator/eager_generator.cc
  paddle/fluid/eager/autograd_meta.h
  paddle/fluid/imperative/basic_engine.cc
  paddle/fluid/imperative/dygraph_grad_maker.h
  paddle/fluid/imperative/gradient_accumulator.cc
  paddle/fluid/imperative/gradient_accumulator.h
  paddle/fluid/imperative/layer.cc
  paddle/fluid/imperative/layer.h
  paddle/fluid/imperative/partial_grad_engine.cc
  paddle/fluid/imperative/reducer.cc
  paddle/fluid/imperative/tracer.cc
  paddle/fluid/imperative/variable_wrapper.h
  paddle/fluid/pybind/imperative.cc
  test/cpp/eager/performance_tests/benchmark_fluid_cpu.cc
  test/cpp/eager/performance_tests/benchmark_fluid_cuda.cc
  test/cpp/imperative/test_gradient_accmulator.cc
  test/cpp/imperative/test_hooks.cc
  test/cpp/imperative/test_layer.cc
  test/cpp/imperative/test_tracer.cc
Labels: contributor, HappyOpenSource

#61781 Fix some typos (approch, decrator, etc.)
  test/ipu/CMakeLists.txt
  test/ipu/op_test_ipu.py
  test/ipu/test_elementwise_x_op_ipu.py
  test/ipu/test_matmul_serialize_ipu.py
  test/ipu/test_mixed_precision_inference_ipu.py
  test/ipu/test_mixed_precision_training_ipu.py
  test/ipu/test_optimizer_ipu.py
Labels: contributor, HappyOpenSource

#61783 Update test_conv3d_op_xpu.py
  test/xpu/test_conv2d_op_xpu.py
  test/xpu/test_conv3d_op_xpu.py
Labels: contributor, HappyOpenSource

#61757 Fix some typos (connot, transpsoe, etc.)
  paddle/cinn/frontend/pass/transpose_collapsing.cc
  paddle/cinn/frontend/syntax.cc
  paddle/cinn/frontend/syntax.h
  paddle/cinn/hlir/dialect/operator/transforms/group_merge/generate_shape_util.cc
  paddle/cinn/hlir/dialect/operator/transforms/group_merge/generate_shape_util.h
  paddle/cinn/hlir/dialect/operator/transforms/group_merge/group_with_group_merge_pass.cc
  paddle/cinn/hlir/dialect/operator/transforms/group_merge/group_with_group_merge_util.h
  paddle/cinn/hlir/dialect/operator/transforms/group_merge/special_ops_fusion_rule.cc
  paddle/cinn/hlir/framework/buffer.h
  paddle/cinn/hlir/framework/graph_compiler_test.cc
  paddle/cinn/hlir/framework/pir/op_lowering_impl.h
  paddle/cinn/hlir/framework/pir/op_lowering_util.cc
  paddle/cinn/hlir/framework/pir/op_mapper.cc
  paddle/cinn/hlir/framework/pir/op_mapper.h
  paddle/cinn/hlir/framework/pir/utils.cc
Labels: contributor, HappyOpenSource

#61732 Fix typo (`LoopkUpOpInfo` -> `LookUpOpInfo`)
  paddle/fluid/ir_adaptor/translator/op_translator.cc
  paddle/fluid/ir_adaptor/translator/op_translator.h
  paddle/fluid/ir_adaptor/translator/utils.cc
Labels: contributor, HappyOpenSource

#61705 [clang] fix `-Wunused-comparison` warning
  paddle/fluid/framework/new_executor/instruction/control_flow/tuple_push_instruction.cc
  paddle/phi/core/tensor_meta.cc
Labels: contributor, HappyOpenSource

#61580 [clang-tidy] NO.35-37 enable `modernize-use-bool-literals`, `clang-analyzer-core.DivideZero`, `bugprone-integer-division`
  paddle/fluid/distributed/test/graph_node_test.cc
  paddle/fluid/inference/utils/table_printer.cc
  paddle/fluid/memory/allocation/allocator.h
  paddle/phi/kernels/stride/view_kernel.cc
  test/cpp/fluid/pscore/heter_cloud_comm_cpu_test.cc
  test/cpp/fluid/pscore/heter_server_test.cc
  test/cpp/fluid/pscore/send_and_recv_op_cpu_test.cc
  test/cpp/fluid/pscore/send_and_recv_op_gpu_test.cc
Labels: contributor, HappyOpenSource

#61589 [clang-tidy] NO.33 enable bugprone-inaccurate-erase
  .clang-tidy
  paddle/phi/kernels/funcs/jit/test.cc
Labels: contributor, HappyOpenSource

#61609 [clang-tidy] NO.29 enable bugprone-exception-escape
  paddle/fluid/framework/details/eager_deletion_op_handle.cc
  paddle/fluid/framework/details/fused_all_reduce_op_handle.cc
  paddle/fluid/inference/api/resource_manager.cc
  paddle/phi/backends/onednn/onednn_context.cc
  paddle/phi/core/sparse_coo_tensor.cc
  paddle/phi/core/string_tensor.cc
Labels: contributor, HappyOpenSource

#61817 [AutoParallel] Optimize all_reduce_matmul_grad_overlapping
  python/paddle/distributed/passes/allreduce_matmul_grad_overlapping.py
Labels: contributor

#61616 [clang-tidy] NO.26 enable misc-unused-using-decls
  paddle/fluid/platform/profiler/dump/test_serialization_logger.cc
  paddle/phi/infermeta/spmd_rules/concat.cc
  paddle/phi/kernels/cpu/multiclass_nms3_kernel.cc
  paddle/phi/kernels/onednn/matmul_kernel.cc
  test/cpp/auto_parallel/dist_attr_test.cc
Labels: contributor, HappyOpenSource

#61715 [clang-tidy] NO.15 enable performance-inefficient-vector-operation
  paddle/fluid/framework/new_executor/interpreter/plan.cc
  paddle/fluid/jit/function_schema.cc
  paddle/fluid/pir/dialect/operator/utils/utils.cc
  paddle/fluid/pir/drr/src/rewrite_pattern.cc
  paddle/phi/backends/device_manager.cc
  paddle/phi/core/distributed/auto_parallel/dist_mapper.cc
  paddle/phi/core/distributed/auto_parallel/reshard/s_to_r_reshard_function.cc
  paddle/phi/infermeta/spmd_rules/utils.cc
  paddle/phi/kernels/cpu/overlap_add_grad_kernel.cc
  paddle/phi/kernels/cpu/overlap_add_kernel.cc
  paddle/phi/kernels/funcs/jit/benchmark.cc
  paddle/phi/kernels/sparse/cpu/sum_grad_kernel.cc
  paddle/phi/kernels/stride/split_kernel.cc
  paddle/testing/paddle_gtest_main.cc
  test/cpp/fluid/framework/attribute_test.cc
  test/cpp/fluid/framework/op_desc_test.cc
  test/cpp/phi/kernels/test_fused_adam_kernel.cc
Labels: contributor, HappyOpenSource

#61716 [clang-tidy] NO.14 enable misc-unused-alias-decls
  paddle/fluid/distributed/test/brpc_service_dense_sgd_test.cc
  paddle/fluid/distributed/test/brpc_service_sparse_sgd_test.cc
  paddle/fluid/distributed/test/brpc_utils_test.cc
  paddle/fluid/distributed/test/graph_node_split_test.cc
  paddle/fluid/distributed/test/graph_node_test.cc
  paddle/fluid/distributed/test/graph_table_sample_test.cc
  paddle/fluid/pybind/auto_parallel_py.cc
  paddle/fluid/pybind/inference_api.cc
  test/cpp/fluid/framework/details/exception_holder_test.cc
  test/cpp/fluid/framework/op_registry_test.cc
  test/cpp/fluid/framework/tensor_test.cc
  test/cpp/imperative/test_gradient_accmulator.cc
  test/cpp/imperative/test_hooks.cc
  test/cpp/imperative/test_layer.cc
  test/cpp/imperative/test_prepare_op.cc
  test/cpp/imperative/test_tracer.cc
  test/cpp/phi/api/test_to_api.cc
  test/cpp/phi/kernels/test_memcpy_dev_api.cc
  test/cpp/phi/kernels/test_strings_lower_upper_dev_api.cc
Labels: contributor, HappyOpenSource

#61759 [clang-tidy] NO.3 bugprone-narrowing-conversions,cppcoreguidelines-narrowing-conversions PART 1
  paddle/fluid/distributed/test/brpc_service_dense_sgd_test.cc
  paddle/fluid/distributed/test/ctr_dymf_accessor_test.cc
  paddle/fluid/distributed/test/sparse_sgd_rule_test.cc
  paddle/fluid/framework/data_feed.cc
  paddle/fluid/framework/heter_section_worker.cc
  paddle/fluid/framework/io/shell.cc
  paddle/fluid/framework/ir/fusion_group/code_generator_helper.cc
  paddle/fluid/framework/ir/fusion_group/code_generator_tester.cc
  paddle/fluid/framework/ir/mkldnn/compute_propagate_scales_mkldnn_pass.cc
  paddle/fluid/framework/ir/mkldnn/cpu_quantize_squash_pass.cc
  paddle/fluid/framework/ir/mkldnn/int8_scale_calculation_mkldnn_pass_tester.cc
  paddle/fluid/framework/ir/mkldnn/quant_dequant_mkldnn_pass.cc
  paddle/fluid/framework/tensor_util.cc
  paddle/fluid/inference/api/mkldnn_quantizer.cc
  paddle/fluid/pir/transforms/pd_op_to_kernel_pass.cc
  paddle/fluid/platform/device/gpu/gpu_info.cc
  paddle/fluid/platform/profiler/cpu_utilization.cc
  paddle/fluid/platform/profiler/cupti_data_process.cc
  paddle/fluid/platform/profiler/dump/deserialization_reader.cc
  paddle/fluid/pybind/eager_functions.cc
  paddle/fluid/pybind/eager_method.cc
  paddle/fluid/pybind/op_function_common.cc
  paddle/phi/backends/onednn/onednn_context.cc
  paddle/phi/common/place.cc
  paddle/phi/core/distributed/auto_parallel/placement_types.cc
  paddle/phi/core/distributed/auto_parallel/reshard/reshard_utils.cc
  paddle/phi/infermeta/spmd_rules/default_data_parallel.cc
  paddle/phi/infermeta/spmd_rules/flatten.cc
  paddle/phi/infermeta/spmd_rules/layer_norm.cc
  paddle/phi/infermeta/spmd_rules/matmul.cc
  paddle/phi/infermeta/spmd_rules/reshape.cc
  paddle/phi/infermeta/spmd_rules/slice.cc
  paddle/phi/infermeta/spmd_rules/split.cc
  paddle/phi/infermeta/spmd_rules/transpose.cc
  paddle/phi/kernels/funcs/jit/gen/act.cc
  paddle/phi/kernels/funcs/jit/gen/adam.cc
  paddle/phi/kernels/funcs/jit/gen/adamw.cc
  paddle/phi/kernels/funcs/jit/gen/matmul.cc
  paddle/phi/kernels/funcs/jit/gen/seqpool.cc
  paddle/phi/kernels/fusion/cpu/self_dp_attention_kernel.cc
  paddle/phi/kernels/fusion/onednn/fused_matmul_kernel.cc
  paddle/phi/kernels/fusion/onednn/fusion_gru_kernel.cc
  paddle/phi/kernels/onednn/expand_kernel.cc
  paddle/phi/kernels/onednn/reduce_mean_grad_kernel.cc
  paddle/phi/kernels/onednn/reshape_kernel.cc
  paddle/phi/kernels/onednn/stack_kernel.cc
  paddle/phi/kernels/onednn/transpose_kernel.cc
  test/cpp/fluid/fused/cudnn_norm_conv_test.cc
  test/cpp/inference/api/analyzer_detect_functional_mkldnn_tester.cc
  test/cpp/inference/api/analyzer_ner_tester.cc
  test/cpp/inference/api/analyzer_rnn1_tester.cc
  test/cpp/inference/api/analyzer_rnn2_tester.cc
  test/cpp/inference/api/analyzer_seq_conv1_tester.cc
  test/cpp/new_executor/standalone_executor_test.cc
Labels: contributor, HappyOpenSource

#61555 [clang-tidy] NO.42-44 enable `noexcept-move-constructor`,`unused-but-set-variable`,`security.FloatLoopCounter`
  .clang-tidy
  paddle/fluid/inference/utils/table_printer.cc
  paddle/fluid/platform/profiler/event_node.cc
  test/cpp/fluid/reader/reader_blocking_queue_test.cc
Labels: contributor, HappyOpenSource

#61672 【paddle_test No.16】replace parts of cc_test with paddle_test
  paddle/fluid/framework/ir/graph.h
  paddle/fluid/framework/ir/pass.h
  paddle/phi/backends/onednn/onednn_context.h
  test/cpp/fluid/mkldnn/CMakeLists.txt
  test/cpp/fluid/mkldnn/test_conv_mkldnn_nhwc.cc
  test/cpp/fluid/mkldnn/test_mkldnn_caching.cc
  test/cpp/fluid/mkldnn/test_mkldnn_cpu_quantize_pass.cc
  test/cpp/fluid/mkldnn/test_mkldnn_op_inplace.cc
  test/cpp/fluid/mkldnn/test_mkldnn_pool_adaptive_op.cc
  test/cpp/fluid/mkldnn/test_mkldnn_squeeze.cc
Labels: contributor, HappyOpenSource

#61730 Fix some typos (shink, tured, etc.)
  paddle/fluid/inference/api/analysis_predictor.cc
  paddle/fluid/inference/api/analysis_predictor.h
  paddle/fluid/inference/api/api.cc
  paddle/fluid/inference/api/api_impl.cc
  paddle/fluid/inference/api/details/zero_copy_tensor.cc
  paddle/fluid/inference/api/mkldnn_quantizer_config.cc
  paddle/fluid/inference/api/onnxruntime_predictor.h
  paddle/fluid/inference/api/paddle_analysis_config.h
  paddle/fluid/inference/api/paddle_api.h
  paddle/fluid/inference/api/paddle_tensor.h
Labels: contributor, HappyOpenSource

#61728 Fix typo (`kNotAllowInferShapeCahce` -> `kNotAllowInferShapeCache`)
  paddle/fluid/framework/ir/runtime_context_cache_pass.cc
  paddle/fluid/framework/operator.cc
Labels: contributor, HappyOpenSource

#61633 Fix some typos (eqaution_graph_view, GetValueOfRewritedOps, etc.)
  paddle/cinn/adt/generate_map_expr.cc
  paddle/cinn/adt/write_broadcast_disabled_bidirection_equation_generator.cc
  paddle/cinn/hlir/dialect/operator/transforms/fuse_shape_ops_into_generate_shape_op_pass.cc
  paddle/cinn/hlir/dialect/operator/transforms/split_generate_shape_into_shape_ops_pass.cc
  python/paddle/distributed/fleet/launch.py
  python/paddle/distributed/fleet/launch_utils.py
  python/paddle/distributed/fleet/meta_parallel/pipeline_parallel.py
  python/paddle/distributed/fleet/meta_parallel/sharding/group_sharded_optimizer_stage2.py
  python/paddle/distributed/fleet/meta_parallel/sharding/group_sharded_stage2.py
  python/paddle/distributed/fleet/meta_parallel/sharding/group_sharded_stage3.py
  python/paddle/distributed/fleet/meta_parallel/sharding/group_sharded_storage.py
  python/paddle/distributed/fleet/model.py
  python/paddle/distributed/sharding/group_sharded.py
  python/paddle/distributed/utils/launch_utils.py
Labels: contributor, HappyOpenSource

#61720 Fix some typos (Intermedaite, deperecated, etc.)
  paddle/fluid/operators/fused/fused_elemwise_activation_op.h
  paddle/phi/kernels/funcs/compound_functors.h
  paddle/phi/kernels/funcs/elementwise_base.h
  paddle/phi/kernels/funcs/elementwise_functor.h
  paddle/phi/kernels/funcs/fft.cc
  paddle/phi/kernels/funcs/jit/README.en.md
  paddle/phi/kernels/funcs/jit/README.md
  paddle/phi/kernels/funcs/jit/helper.cc
  paddle/phi/kernels/funcs/jit/helper.h
  paddle/phi/kernels/funcs/jit/more/intrinsic/crf_decoding.cc
  paddle/phi/kernels/funcs/matrix_bit_code.h
  paddle/phi/kernels/funcs/matrix_solve.h
  paddle/phi/kernels/funcs/selected_rows_functor.cc
  paddle/phi/kernels/funcs/selected_rows_functor.h
  paddle/phi/kernels/funcs/seq2col.h
  paddle/phi/kernels/funcs/sparse/convolution.h
  paddle/phi/kernels/funcs/unsqueeze.h
  paddle/phi/kernels/funcs/values_vectors_functor.h
  paddle/phi/kernels/funcs/vol2col.cc
  paddle/phi/kernels/funcs/vol2col.cu
  paddle/phi/kernels/fusion/cutlass/conv2d/conv2d_depthwise_bias_act.py
  paddle/phi/kernels/fusion/cutlass/cutlass_extensions/epilogue/threadblock/epilogue_tensor_op_int32.h
  paddle/phi/kernels/fusion/cutlass/cutlass_kernels/fpA_intB_gemm/fpA_intB_gemm_template.h
  paddle/phi/kernels/fusion/cutlass/memory_efficient_attention/transform/tile_smem_loader.h
  paddle/phi/kernels/fusion/gpu/fused_bias_dropout_residual_layer_norm_kernel.cu
  paddle/phi/kernels/fusion/onednn/fused_elementwise_kernel.cc
  paddle/phi/kernels/fusion/xpu/bn_act_xpu_kernel.cc
Labels: contributor, HappyOpenSource
