Repository PaddlePaddle/Paddle, pull requests merged in 2025-02, with the labels that each got.

#71008 [CodeStyle][Typos][S-[34-35]]Fix typos(`splitting`,`Splitting`,`splitted`,`Splited`,`splited`)
  _typos.toml
  paddle/cinn/backends/codegen_device_util.h
  paddle/cinn/operator_fusion/graph_transformer/operation.h
  paddle/phi/infermeta/unary.cc
  python/paddle/distributed/passes/pass_utils.py
Labels: contributor

#70995 更正svd、svdvals、svd_lowrank文档公式错误
  python/paddle/tensor/linalg.py
Labels: contributor, HappyOpenSource

#70670 Fix typos insrance instance
  paddle/common/flags.cc
  paddle/common/flags_native.cc
Labels: contributor, HappyOpenSource

#70241 Fix typos combile_ combine_
  paddle/fluid/inference/tensorrt/convert/batch_norm_op.cc
  python/paddle/distributed/passes/auto_parallel_gradient_merge.py
  python/paddle/distributed/passes/pass_utils.py
Labels: contributor

#70051 Fix typos simplely simply
  python/paddle/distributed/passes/pass_utils.py
  python/paddle/distributed/rpc/rpc.py
  python/paddle/distributed/transpiler/details/vars_distributed.py
Labels: contributor, HappyOpenSource

#70991 [CodeStyle][Typos][P-[42-48]] Fix typo (`producted`,`progam`,`progrss`,`propogated`,`Propogation`,`protocal`,`PROTOCAL`,`pthon`,`pyrhon`)
  CMakeLists.txt
  _typos.toml
  paddle/fluid/inference/tensorrt/convert/matrix_multiply_op.cc
  paddle/phi/infermeta/spmd_rules/dim_trans.cc
  paddle/phi/infermeta/spmd_rules/gather.cc
  paddle/phi/infermeta/spmd_rules/nonzero.cc
  paddle/phi/infermeta/spmd_rules/scatter.cc
  paddle/scripts/fast_install.sh
  python/paddle/distributed/launch/controllers/master.py
  python/paddle/jit/dy2static/convert_operators.py
  python/paddle/tensor/linalg.py
  test/deprecated/legacy_test/auto_parallel_op_test.py
  test/legacy_test/auto_parallel_op_test.py
Labels: contributor, HappyOpenSource

#71000 [CodeStyle][Typos][S-[51-59]] Fix typo (substract, successed...)
  CMakeLists.txt
  _typos.toml
  paddle/fluid/distributed/ps/table/ssd_sparse_table.cc
  paddle/fluid/framework/data_feed.cu
  paddle/fluid/framework/data_feed.h
  paddle/fluid/platform/init.cc
  paddle/phi/api/generator/api_gen.py
  paddle/phi/kernels/funcs/blas/blas_impl.hip.h
  paddle/phi/kernels/funcs/detail/avx_mathfun.h
  paddle/phi/kernels/funcs/emb_eltwise_layer_norm_functor.cu
  paddle/phi/kernels/funcs/jit/gen/act.h
  paddle/phi/kernels/funcs/math/bert_encoder_functor.cu
  paddle/phi/kernels/funcs/multihead_matmul_functor.cu
  paddle/phi/kernels/funcs/skip_layernorm_functor.cu
  paddle/phi/kernels/gpu/check_numerics_kernel.cu
  paddle/phi/kernels/gpudnn/conv_grad_kernel.cu
  paddle/phi/kernels/gpudnn/conv_kernel.cu
  python/paddle/incubate/jit/inference_decorator.py
  python/paddle/tensorrt/impls/math.py
  python/paddle/utils/download.py
  test/dygraph_to_static/dygraph_to_static_utils.py
  test/legacy_test/hygon_dcu/test_hygon_llama_op.sh
  test/legacy_test/test_dygraph_mnist_fp16.py
  test/tensorrt/test_converter_math.py
Labels: contributor, HappyOpenSource

#71004 [CodeStyle][Typos][S-42] Fix typo (stop)
  _typos.toml
  paddle/fluid/distributed/ps/service/brpc_ps_server.cc
  paddle/fluid/distributed/ps/service/brpc_ps_server.h
  paddle/fluid/distributed/ps/service/graph_brpc_server.cc
  paddle/fluid/distributed/ps/service/graph_brpc_server.h
  paddle/fluid/distributed/ps/service/heter_server.cc
  paddle/fluid/distributed/ps/service/heter_server.h
  paddle/fluid/distributed/ps/service/ps_service/graph_py_service.cc
  paddle/fluid/distributed/ps/service/ps_service/graph_py_service.h
  paddle/fluid/platform/profiler/cuda_tracer.cc
  paddle/fluid/platform/profiler/custom_device/custom_tracer.cc
  paddle/fluid/platform/profiler/host_tracer.cc
  paddle/fluid/platform/profiler/tracer_base.h
  paddle/fluid/platform/profiler/xpu_tracer.cc
  paddle/phi/api/profiler/tracer_base.h
  python/paddle/distributed/auto_parallel/static/cluster.py
Labels: contributor, HappyOpenSource

#70973 [XPU] fix serveral xpu ut
  paddle/phi/backends/xpu/xpu3_op_list.cc
  paddle/phi/kernels/array_kernel.cc
  test/dygraph_to_static/test_list.py
  test/legacy_test/test_index_sample_op.py
  test/legacy_test/test_manual_seed.py
  test/legacy_test/test_scatter_op.py
  tools/xpu/disable_ut_xpu_kl3.local
Labels: XPU

#70988 [CodeStyle][Typos][S-[26-33]] Fix typos(`Skiped`,`skiped`,`smll`,`samll`,`somme`,`Patial`,`patial`,`specificed`,`splite`,`spliter`)
  _typos.toml
  paddle/fluid/framework/new_executor/interpreter/static_build.cc
  paddle/phi/common/cpstring_impl.h
  paddle/phi/kernels/funcs/reduce_function.h
  paddle/phi/kernels/fusion/cutlass/memory_efficient_attention/gemm/attention_scaling_coefs_updater.h
  paddle/phi/kernels/fusion/cutlass/memory_efficient_attention/gemm/mma_accum_lambda_iterator.h
  paddle/phi/kernels/fusion/cutlass/memory_efficient_attention/gemm/mma_from_smem.h
  paddle/phi/kernels/impl/lstm_kernel_impl.h
  python/paddle/distributed/auto_parallel/static/reshard_funcs/s_to_r_reshard_func.py
  python/paddle/distributed/fleet/utils/tensor_fusion_helper.py
  python/paddle/nn/initializer/initializer.py
  test/cpp/utils/small_vector_test.cc
  test/legacy_test/test_multiprocess_dataloader_iterable_dataset_split.py
  tools/gen_pybind11_stub.py
Labels: contributor, HappyOpenSource

#71012 [XPU] Update xccl
  cmake/external/xpu.cmake
Labels: XPU

#71023 [CodeStyle][Typos][U-9] Fix typo (`Unsupport`) (part2)
  paddle/cinn/ir/group_schedule/config/group_tile_util.cc
  paddle/cinn/optim/vectorize_for_trans.cc
  paddle/fluid/imperative/prepared_operator.cc
  paddle/fluid/imperative/reducer.cc
  paddle/fluid/imperative/reducer.cu
  paddle/fluid/inference/capi/c_api.cc
  paddle/fluid/inference/capi_exp/pd_config.cc
  paddle/fluid/inference/capi_exp/pd_utils.cc
  paddle/fluid/inference/tensorrt/plugin/spmm_plugin.cu
  paddle/fluid/operators/pscore/distributed_lookup_table_op.h
  paddle/fluid/operators/sum_op.cc
  paddle/phi/core/distributed/gloo_utils.h
  paddle/phi/core/kernel_factory.cc
Labels: contributor, HappyOpenSource

#71006 [CodeStyle][Typos][S-50] Fix typo (subsituted)
  _typos.toml
  paddle/cinn/hlir/framework/pir/trivial_op_impl.cc
  paddle/cinn/hlir/framework/pir/trivial_op_util.cc
  paddle/cinn/hlir/framework/pir/trivial_op_util.h
  paddle/fluid/framework/pass_desc.proto
  paddle/phi/core/framework/pass_desc.proto
Labels: contributor, HappyOpenSource

#70326 [CINN][dynamic rank] optimize log and IsDeniedInCinn logic
  paddle/cinn/hlir/framework/pir/utils.cc
  paddle/pir/src/dialect/shape/transforms/shape_optimization_pass.cc
Labels: contributor

#67764 Fix typos tanspose transpose
  paddle/fluid/inference/tensorrt/convert/c_allreduce_op.cc
  paddle/fluid/inference/tensorrt/convert/temporal_shift_op.cc
  paddle/fluid/inference/tensorrt/plugin/fused_token_prune_op_plugin.cu
  paddle/fluid/inference/tensorrt/plugin/generic_plugin.cu
  paddle/fluid/inference/tensorrt/plugin/spmm_plugin.cu
Labels: contributor, HappyOpenSource

#68846 Fix typos IsDivisiblieBySymbol IsDivisibleBySymbol
  paddle/cinn/common/ir_util.cc
  paddle/cinn/common/ir_util.h
Labels: contributor, HappyOpenSource

#71027 [XPU] fix bug in addmm
  paddle/phi/kernels/xpu/addmm_kernel.cc
  tools/xpu/disable_ut_xpu_kl3.local
Labels: XPU

#70999 [CodeStyle][Typos][R-15] Fix typo (REGIST, Regiter, Regist, Registe, regist, registe)
  _typos.toml
  paddle/cinn/auto_schedule/auto_tuner.cc
  paddle/fluid/distributed/ps/service/brpc_ps_client.cc
  paddle/fluid/distributed/ps/service/brpc_ps_server.cc
  paddle/fluid/distributed/ps/service/coordinator_client.cc
  paddle/fluid/distributed/ps/service/env.h
  paddle/fluid/distributed/ps/service/graph_brpc_server.cc
  paddle/fluid/distributed/ps/service/server.h
  paddle/fluid/framework/fleet/fleet_wrapper.cc
  paddle/fluid/inference/tensorrt/convert/conv2d_op.cc
  paddle/fluid/inference/tensorrt/convert/conv3d_op.cc
  paddle/fluid/inference/tensorrt/convert/sparse_fc_op.cc
  paddle/fluid/inference/tensorrt/convert/test_custom_plugin_creater.cc
  paddle/fluid/inference/tensorrt/engine.h
  paddle/fluid/platform/tensorrt/engine.h
  paddle/fluid/platform/tensorrt/trt_plugin.h
  paddle/fluid/pybind/pybind.cc
  test/legacy_test/test_attribute_var.py
  tools/get_single_test_cov.py
Labels: contributor, HappyOpenSource

#71002 [CodeStyle][Typos][S-[36-41]] Fix typo (sqaure, sequeze...)
  _typos.toml
  paddle/cinn/optim/replace_cross_block_reduction.cc
  paddle/cinn/poly/schedule.cc
  paddle/phi/kernels/fusion/cutlass/cutlass_extensions/gemm/threadblock/dq_mma_pipelined.h
  paddle/phi/kernels/fusion/cutlass/memory_efficient_attention/gemm/custom_mma_pipelined.h
  paddle/phi/kernels/fusion/cutlass/memory_efficient_attention/gemm/mma_from_smem.h
  python/paddle/distributed/auto_parallel/static/pir_pass.py
  test/dygraph_to_static/test_tensor_shape.py
Labels: contributor, HappyOpenSource

#71035 [CodeStyle][Typos][U-9] Fix typo (`Unsupport`) (part3)
  paddle/phi/infermeta/spmd_rules/embedding.cc
  paddle/phi/infermeta/spmd_rules/embedding.h
  paddle/phi/kernels/funcs/blas/blaslt_impl.hip.h
  paddle/phi/kernels/funcs/uniform_random_functor.h
  paddle/phi/kernels/fusion/gpu/block_attn.h
  paddle/phi/kernels/fusion/gpu/fused_multi_transformer_op.cu.h
  paddle/phi/kernels/fusion/gpu/masked_multihead_attention_kernel.cu
  paddle/phi/kernels/fusion/gpu/qkv_unpack_mha_kernel.cu
  paddle/phi/kernels/kps/elementwise_kernel.cu
  paddle/phi/ops/yaml/inconsistent/dygraph_ops.yaml
  paddle/phi/ops/yaml/inconsistent/static_ops.yaml
  python/paddle/base/framework.py
  python/paddle/cinn/compiler/compute_code_generator.py
  python/paddle/distributed/auto_parallel/static/pir_pass.py
  python/paddle/distributed/fleet/layers/mpu/random.py
  python/paddle/distributed/fleet/meta_optimizers/sharding/offload_helper.py
  python/paddle/jit/sot/opcode_translator/executor/executor_cache.py
  python/paddle/jit/sot/opcode_translator/executor/variables/callable.py
  python/paddle/static/amp/fp16_utils.py
Labels: contributor, HappyOpenSource

#70993 [CodeStyle][Typos][O-22] Fix typo (`outout`,`ouput`,`ouptut`,`outpout`,`Ouput`)
  _typos.toml
  paddle/cinn/hlir/pe/nn.h
  paddle/cinn/hlir/pe/reduction.cc
  paddle/cinn/operator_fusion/utils.cc
  paddle/fluid/framework/ir/graph_helper.cc
  paddle/fluid/framework/ir/graph_pattern_detector.cc
  paddle/fluid/inference/openvino/engine.cc
  paddle/fluid/inference/openvino/engine.h
  paddle/fluid/operators/openvino/openvino_engine_op.h
  paddle/phi/infermeta/spmd_rules/default_data_parallel.h
  paddle/phi/kernels/funcs/interpolate_function.h
  paddle/phi/kernels/funcs/pooling.cu
  paddle/phi/kernels/impl/bessel_grad_kernel_cuda_impl.h
  paddle/pir/include/core/operation.h
  python/paddle/distributed/auto_parallel/static/engine.py
  python/paddle/jit/dy2static/program_translator.py
  test/ir/inference/test_mkldnn_conv_affine_channel_fuse_pass.py
Labels: contributor, HappyOpenSource

#68872 Fix typos dockcerfile dockerfile
  tools/ci_op_benchmark.sh
  tools/dockerfile/centos7_manylinux.sh
  tools/dockerfile/ci_dockerfile.sh
  tools/type_checking.py
Labels: contributor, HappyOpenSource

#70055 Fix typos confrom conform
  python/paddle/_typing/layout.py
  python/paddle/autograd/backward_utils.py
Labels: contributor

#71001 [CodeStyle][Typos][S-[43-49]] Fix typo (storage, sotring...)
  _typos.toml
  paddle/fluid/framework/new_executor/interpreter/interpreter_util.cc
  paddle/phi/kernels/gpu/batch_norm_grad_kernel.cu
  paddle/phi/kernels/gpu/batch_norm_kernel.cu
  python/paddle/distributed/auto_parallel/static/helper.py
  python/paddle/nn/functional/loss.py
  test/ir/pir/cinn/test_anchor_fusion.py
  test/legacy_test/test_hsigmoid_op.py
Labels: contributor, HappyOpenSource

#71038 [xpu] add controls for fc patterns
  paddle/fluid/pir/transforms/xpu/fc_xpu_fuse_pass.cc
Labels: XPU

#71047 xpu set_value_grad support
  paddle/phi/backends/xpu/xpu3_op_list.cc
  paddle/phi/kernels/xpu/set_value_grad_kernel.cc
Labels: XPU

#71062 [XPU] zero size support for gaussian op
  paddle/phi/kernels/xpu/gaussian_kernel.cc
  test/xpu/test_gaussian_random_op_xpu.py
  tools/xpu/disable_ut_xpu_kl3.local
Labels: XPU

#71053 [XPU] support flash_attn when head_dim of v not equal to that of q, k
  paddle/phi/kernels/xpu/flash_attn_grad_kernel.cc
  paddle/phi/kernels/xpu/flash_attn_kernel.cc
  test/xpu/test_flash_attention_op_xpu.py
Labels: XPU

#67404 Fix typos epislon epsilon
  cmake/generic.cmake
  test/cpp/inference/api/CMakeLists.txt
  test/cpp/inference/api/tester_helper.h
  test/cpp/inference/infer_ut/test_ernie_xnli_int8.cc
  test/cpp/inference/infer_ut/test_suite.h
  test/deprecated/legacy_test/test_lbfgs_deprecated.py
  test/prim/prim/vjp/eager/test_comp_eager_index_add_double_grad.py
Labels: contributor, HappyOpenSource

#71073 Update variable name in install_cuda.sh
  tools/dockerfile/manylinux/common/install_cuda.sh
Labels: contributor, HappyOpenSource

#70757 【Hackathon 8th No.2】为 Paddle 新增 baddbmm API
  paddle/fluid/pir/dialect/op_generator/decomp_interface_gen_op_list.py
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/multiary_infer_sym.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/multiary_infer_sym.h
  paddle/fluid/primitive/decomp_rule/decomp_rule/composite.h
  paddle/phi/infermeta/ternary.cc
  paddle/phi/infermeta/ternary.h
  paddle/phi/kernels/baddbmm_grad_kernel.h
  paddle/phi/kernels/baddbmm_kernel.h
  paddle/phi/kernels/cpu/baddbmm_grad_kernel.cc
  paddle/phi/kernels/cpu/baddbmm_kernel.cc
  paddle/phi/kernels/funcs/blas/blas.h
  paddle/phi/kernels/funcs/blas/blas_impl.cu.h
  paddle/phi/kernels/funcs/blas/blas_impl.h
  paddle/phi/kernels/funcs/blas/blas_impl.hip.h
  paddle/phi/kernels/gpu/baddbmm_grad_kernel.cu
  paddle/phi/kernels/gpu/baddbmm_kernel.cu
  paddle/phi/kernels/impl/baddbmm_grad_kernel_impl.h
  paddle/phi/kernels/impl/baddbmm_kernel_impl.h
  paddle/phi/ops/yaml/backward.yaml
  paddle/phi/ops/yaml/op_compat.yaml
  paddle/phi/ops/yaml/ops.yaml
  python/paddle/__init__.py
  python/paddle/tensor/__init__.py
  python/paddle/tensor/math.py
  test/legacy_test/CMakeLists.txt
  test/legacy_test/test_baddbmm_op.py
Labels: PaddlePaddle Hackathon, contributor, API

#71077 [CodeStyle][Typos][S-19] Fix typo (`setted`,`ser`)
  _typos.toml
  paddle/fluid/framework/op_desc.h
  paddle/fluid/framework/operator.h
  paddle/fluid/inference/tensorrt/convert/emb_eltwise_layernorm.cc
  paddle/fluid/inference/tensorrt/convert/preln_emb_eltwise_layernorm.cc
  paddle/fluid/inference/tensorrt/convert/prompt_tuning_emb_eltwise_layernorm.cc
  paddle/fluid/operators/fill_constant_op.cc
  paddle/phi/api/lib/api_gen_utils.h
  paddle/phi/api/lib/data_transform.h
  python/paddle/base/core.py
  python/paddle/nn/layer/container.py
  test/deprecated/tokenizer/test_faster_tokenizer_op_deprecated.py
  tools/document_preview.sh
Labels: contributor, HappyOpenSource

#71080 Fix typos colaescing coalescing
  paddle/fluid/distributed/collective/process_group_bkcl.cc
  paddle/fluid/distributed/collective/process_group_bkcl.h
  paddle/fluid/distributed/collective/process_group_nccl.cc
  paddle/fluid/distributed/collective/process_group_nccl.h
Labels: contributor, HappyOpenSource

#71084 Fix typos SyncCalcuStream SyncCalcStream
  paddle/fluid/distributed/collective/async_load.cc
  paddle/fluid/distributed/collective/async_load.h
Labels: contributor, HappyOpenSource

#71096 [SOT] Move Internal Function to External Scope
  python/paddle/jit/sot/symbolic/interpreter.py
  python/paddle/jit/sot/symbolic/statement_ir.py
Labels: contributor

#67954 Fix typos mutilple multiple
  python/paddle/distributed/auto_parallel/static/pir_pass.py
  python/paddle/distributed/auto_parallel/static/tuner/rule_based_tuner.py
Labels: contributor, HappyOpenSource

#71115 [XPU] fix test_autograd_functional_dynamic ut
  test/autograd/test_autograd_functional_dynamic.py
  tools/xpu/disable_ut_xpu_kl3.local
Labels: XPU

#71100 [XPU] update xpti interface
  cmake/external/xpu.cmake
  paddle/fluid/platform/profiler/xpu_tracer.cc
  paddle/phi/backends/dynload/xpti.h
  tools/xpu/get_xpti_dependence.sh
Labels: XPU

#68540 【Hackathon 7th Fundable Projects 2 No.89】 [fluid_ops] custom operator
  paddle/fluid/operators/custom_device_common_op_registry.cc
  paddle/phi/kernels/custom/c_concat_kernel.cc
  paddle/phi/kernels/custom/c_softmax_with_entropy_grad_kernel.cc
  paddle/phi/kernels/custom/c_softmax_with_entropy_kernel.cc
Labels: PaddlePaddle Hackathon, contributor

#70211 Modify _legacy_C_ops.c_softmax_with_cross_entropy
  paddle/fluid/pir/dialect/op_generator/ops_api_gen.py
  paddle/phi/ops/yaml/backward.yaml
  paddle/phi/ops/yaml/inconsistent/static_backward.yaml
  paddle/phi/ops/yaml/inconsistent/static_ops.yaml
  paddle/phi/ops/yaml/legacy/backward_exclude.yaml
  paddle/phi/ops/yaml/legacy/ops_exclude.yaml
  paddle/phi/ops/yaml/ops.yaml
  python/paddle/distributed/fleet/layers/mpu/mp_ops.py
Labels: PaddlePaddle Hackathon, contributor

#71110 [XPU] Update xccl
  cmake/external/xpu.cmake
Labels: XPU

#71132 [XPU] bfloat16 support for gather/gather_grad/scatter/scatter_grad
  cmake/external/xpu.cmake
  paddle/phi/backends/xpu/xpu3_op_list.cc
  paddle/phi/kernels/cpu/gather_grad_kernel.cc
  paddle/phi/kernels/cpu/gather_kernel.cc
  paddle/phi/kernels/fusion/xpu/fused_rope_utils.h
  paddle/phi/kernels/xpu/gather_grad_kernel.cc
  paddle/phi/kernels/xpu/gather_kernel.cc
  paddle/phi/kernels/xpu/scatter_grad_kernel.cc
  paddle/phi/kernels/xpu/scatter_kernel.cc
  test/xpu/test_gather_op_xpu.py
  test/xpu/test_scatter_op_xpu.py
Labels: XPU

#71113 Fix typos symbole symbol
  paddle/cinn/adt/get_sub_reshape_dim_ranges.cc
  paddle/cinn/common/iter_simplify.cc
  paddle/cinn/ir/schedule/schedule_desc.cc
  paddle/cinn/operator_fusion/pattern_fuser.h
  paddle/cinn/poly/stage.h
  paddle/phi/common/memory_utils.h
  paddle/pir/include/pattern_rewrite/pattern_match.h
Labels: contributor

#70883 [CINN][Backend Pass Update No.12] Update transform_gpu_forloop pass
  paddle/cinn/hlir/framework/pir/op_lowering_impl.cc
  paddle/cinn/optim/optimize.cc
  paddle/cinn/optim/replace_var_with_expr.cc
  paddle/cinn/optim/transform_gpu_forloop.cc
  paddle/cinn/optim/transform_gpu_forloop.h
  paddle/cinn/pybind/lang.cc
Labels: contributor, HappyOpenSource

#71171 [XPU] fix clip grad ut
  paddle/phi/kernels/impl/clip_kernel_impl.h
  paddle/phi/kernels/xpu/clip_kernel.cc
  tools/xpu/disable_ut_xpu_kl3.local
Labels: XPU

#71087 [CINN][new hardware] SYCL second PR: add SYCL backend
  paddle/cinn/backends/CMakeLists.txt
  paddle/cinn/backends/codegen_gpu_dev.cc
  paddle/cinn/backends/codegen_gpu_dev.h
  paddle/cinn/backends/sycl/CMakeLists.txt
  paddle/cinn/backends/sycl/codegen_sycl_dev.cc
  paddle/cinn/backends/sycl/codegen_sycl_dev.h
  paddle/cinn/backends/sycl/compiler_sycl.cc
  paddle/cinn/backends/sycl/compiler_sycl.h
Labels: contributor

#70556 【SCU】【Paddle TensorRT No.49】Add pd_op.pad3d converter
  paddle/fluid/pir/transforms/tensorrt/trt_op_marker_pass.cc
  python/paddle/tensorrt/impls/manipulation.py
  test/tensorrt/test_converter_manipulation.py
Labels: contributor, HappyOpenSource Pro

#71193 [Dy2St] mark `pd_op.memcpy` as forward only
  paddle/phi/ops/yaml/inconsistent/static_ops.yaml
  test/dygraph_to_static/test_tensor_memcpy_on_gpu.py
Labels: contributor

#71144 [SOT] Move Internal Function to External Scope
  python/paddle/jit/api.py
  python/paddle/jit/sot/opcode_translator/executor/function_graph.py
  python/paddle/jit/sot/utils/utils.py
Labels: contributor

#70591 【SCU】【Paddle TensorRT No.43】Add `pd_op.leaky_relu` 、`pd_op.prelu` converter
  paddle/fluid/pir/transforms/tensorrt/trt_op_marker_pass.cc
  python/paddle/tensorrt/impls/activation.py
  python/paddle/tensorrt/util.py
  test/tensorrt/test_converter_activation.py
Labels: contributor, HappyOpenSource Pro

#71216 [SOT] Split NumpyVariable for separate array/number handling
  python/paddle/jit/sot/opcode_translator/executor/variable_dispatch.py
  python/paddle/jit/sot/opcode_translator/executor/variables/__init__.py
  python/paddle/jit/sot/opcode_translator/executor/variables/basic.py
Labels: contributor

#67456 Fix typos maually manually
  paddle/cinn/hlir/dialect/operator/transforms/pd_to_cinn_pass.cc
  paddle/cinn/utils/multi_threading.cc
  paddle/fluid/framework/ir/onednn/cpu_bfloat16_pass.cc
  paddle/phi/api/profiler/device_tracer.cc
  paddle/phi/infermeta/multiary.cc
Labels: contributor

#69273 Fix typos repicated replicated
  paddle/phi/infermeta/spmd_rules/utils.cc
  paddle/phi/kernels/funcs/blas/blaslt_impl.cu.h
Labels: contributor, HappyOpenSource

#69673 【SCU】【Paddle TensorRT No.48】Add `pd_op.pad` converter
  paddle/fluid/pir/transforms/tensorrt/trt_op_marker_pass.cc
  python/paddle/tensorrt/impls/manipulation.py
  test/tensorrt/test_converter_manipulation.py
Labels: contributor, HappyOpenSource Pro

#70647 【SCU】【Paddle TensorRT No.18】Add `pd_op.conv3d` and `pd_op.conv3d_transpose` converter
  paddle/fluid/pir/transforms/tensorrt/trt_op_marker_pass.cc
  python/paddle/tensorrt/converter_utils.py
  python/paddle/tensorrt/impls/conv.py
  python/paddle/tensorrt/util.py
  test/tensorrt/test_converter_conv.py
Labels: contributor, HappyOpenSource Pro

#71228 [XPU] bfloat16 support for round op
  cmake/external/xpu.cmake
  paddle/phi/backends/xpu/xpu3_op_list.cc
  paddle/phi/kernels/xpu/activation_kernel.cc
  test/xpu/test_activation_op_xpu.py
Labels: XPU

#66981 Fix typos in test directory
  test/collective/README.md
  test/deprecated/legacy_test/test_group_norm_op_deprecated.py
  test/deprecated/legacy_test/test_instance_norm_op_deprecated.py
  test/deprecated/prim/composite_ops/test_composite_batch_norm_deprecated.py
  test/deprecated/prim/composite_ops/test_composite_gelu_deprecated.py
  test/deprecated/prim/composite_ops/test_composite_gelu_grad_deprecated.py
  test/deprecated/prim/composite_ops/test_composite_layer_norm_deprecated.py
  test/deprecated/prim/composite_ops/test_composite_layer_norm_grad_deprecated.py
  test/deprecated/prim/composite_ops/test_composite_mean_deprecated.py
  test/deprecated/prim/composite_ops/test_composite_mean_grad_deprecated.py
  test/deprecated/prim/composite_ops/test_composite_softmax_custom_vjp_deprecated.py
  test/deprecated/prim/composite_ops/test_composite_softmax_deprecated.py
  test/deprecated/prim/composite_ops/test_composite_softmax_grad_deprecated.py
  test/deprecated/prim/prim/flags/test_prim_flags_deprecated.py
  test/deprecated/prim/process/test_copy_op_deprecated.py
  test/prim/pir_prim/test_pir_prim_flags.py
Labels: contributor

#71191 [cherry-pick]Remove storage when recompute using saved_tensor_hooks (#70455)
  python/paddle/distributed/fleet/recompute/recompute.py
Labels: contributor

#71122 Fix typos patter pattern
  paddle/cinn/ir/ir_printer.h
  paddle/cinn/ir/schedule/impl/compute_location.cc
  paddle/cinn/ir/schedule/ir_schedule.h
  paddle/cinn/ir/schedule/ir_schedule_util.h
  paddle/cinn/lang/lower_impl.cc
  python/paddle/distributed/fleet/meta_optimizers/dygraph_optimizer/dygraph_sharding_optimizer.py
  python/paddle/distributed/fleet/meta_parallel/sharding/group_sharded_optimizer_stage2.py
Labels: contributor, HappyOpenSource

#71274 [XPU] Add fp16 support for index_select_grad
  paddle/phi/backends/xpu/xpu2_op_list.cc
  paddle/phi/backends/xpu/xpu3_op_list.cc
  paddle/phi/kernels/xpu/index_select_grad_kernel.cc
Labels: XPU

#71268 [SOT] Collect BreakGraph Reason
  python/paddle/jit/sot/infer_meta.py
  python/paddle/jit/sot/opcode_translator/executor/dispatch_functions.py
  python/paddle/jit/sot/opcode_translator/executor/function_graph.py
  python/paddle/jit/sot/opcode_translator/executor/opcode_executor.py
  python/paddle/jit/sot/opcode_translator/executor/opcode_inline_executor.py
  python/paddle/jit/sot/opcode_translator/executor/variable_dispatch.py
  python/paddle/jit/sot/opcode_translator/executor/variables/basic.py
  python/paddle/jit/sot/opcode_translator/executor/variables/callable.py
  python/paddle/jit/sot/opcode_translator/executor/variables/iter.py
  python/paddle/jit/sot/utils/__init__.py
  python/paddle/jit/sot/utils/exceptions.py
  python/paddle/jit/sot/utils/info_collector.py
Labels: contributor

#71280 Fix typos runnng running
  python/paddle/base/executor.py
  test/collective/fleet/test_auto_checkpoint.py
  test/deprecated/book/test_recognize_digits_deprecated.py
  test/deprecated/cpp/inference/api/CMakeLists.txt
  test/deprecated/legacy_test/dist_fleet_ctr.py
  test/deprecated/legacy_test/test_bfgs_deprecated.py
  test/legacy_test/dist_fleet_ctr.py
  test/legacy_test/dist_fleet_heter_pipeline_ctr.py
  test/legacy_test/dist_fleet_simnet_bow.py
  test/legacy_test/dist_fleet_sparse_embedding_ctr.py
  test/legacy_test/fleet_heter_ps_training.py
  test/legacy_test/test_atleast_xd.py
Labels: contributor, HappyOpenSource

#71263 [CINN]Softmax optimization based on bucket splitting strategy
  paddle/cinn/ir/group_schedule/config/group_tile_config.cc
  paddle/cinn/ir/group_schedule/config/group_tile_config.h
  paddle/cinn/ir/group_schedule/tactic/tile_first_general_tactic.cc
  paddle/cinn/ir/schedule/impl/loop_transformation.cc
Labels: contributor

#71325 [CI] override
  .github/workflows/_SOT.yml
Labels: skip-ci: sot
