Repository PaddlePaddle/Paddle, pull requests merged in 2025-04, with the labels that each got.

#71968 [fluid_ops] Change LoDTensor to DenseTensor
  python/paddle/optimizer/fusion_utils.py
  test/legacy_test/test_paddle_multiprocessing.py
  test/xpu/test_xpu_share_memory.py
Labels: PaddlePaddle Hackathon, contributor

#71992 [CI] Fix clone base branch
  .github/workflows/_Clone-linux.yml
  .github/workflows/re-run.yml
Labels: skip-ci: sot

#72005 [XPU] fix all_to_all with unequal splits when input/output is empty
  paddle/fluid/distributed/collective/process_group_bkcl.cc
  paddle/fluid/distributed/collective/process_group_kernel_utils.h
  paddle/phi/core/distributed/check/bkcl_dynamic_check.cc
  test/xpu/collective_alltoall_api_unequal_split_empty_dygraph.py
  test/xpu/collective_alltoall_single_api_unequal_split_empty_dygraph.py
  test/xpu/test_collective_alltoall_api_unequal_split.py
  test/xpu/test_collective_alltoall_single_api_unequal_split.py
  test/xpu/test_collective_api_base.py
Labels: XPU

#72009 add more tests
  test/collective/CMakeLists.txt
  test/collective/test_collective_barrier_api.py
  test/collective/test_collective_gather_api.py
  test/collective/test_collective_isend_irecv_api.py
  test/collective/test_collective_sendrecv_api.py
  test/collective/test_communication_stream_reduce_api.py
  test/collective/test_communication_stream_reduce_scatter_api.py
  test/collective/test_communication_stream_scatter_api.py
  test/collective/test_communication_stream_sendrecv_api.py
Labels: contributor

#71963 [Fix] remove the found_one = false to adapt sm=86
  paddle/phi/kernels/fusion/cutlass/cutlass_kernels/fpA_intB_gemm/fpA_intB_gemm_template.cu
Labels: contributor

#72017 [0-Size Tensor问题修复] `paddle.broadcast_tensors`
  paddle/phi/kernels/impl/broadcast_tensors_kernel_impl.h
  test/legacy_test/test_broadcast_tensors_op.py
Labels: contributor, HappyOpenSource Pro

#71814 【Hackathon 8th No.3】 clean oldIR for pass_util -part
  python/paddle/distributed/passes/pass_utils.py
  python/paddle/distributed/passes/pipeline_scheduler_pass/pipeline_1f1b.py
  python/paddle/distributed/passes/pipeline_scheduler_pass/pipeline_eager_1f1b.py
  python/paddle/distributed/passes/pipeline_scheduler_pass/pipeline_pass_base.py
  python/paddle/distributed/passes/pipeline_scheduler_pass/pipeline_vpp.py
  python/paddle/distributed/passes/pipeline_scheduler_pass/pipeline_zero_bubble.py
  test/deprecated/auto_parallel/CMakeLists.txt
  test/deprecated/auto_parallel/mp_allreduce_matmul_grad_overlapping_unittest.py
  test/deprecated/auto_parallel/pipeline_scheduler_unittest.py
  test/deprecated/auto_parallel/pipeline_scheduler_vpp_unittest_deprecated.py
  test/deprecated/auto_parallel/pipeline_scheduler_zb_unittest_deprecated.py
  test/deprecated/auto_parallel/pipeline_scheduler_zb_vpp_unittest.py
  test/deprecated/auto_parallel/test_mp_allreduce_matmul_grad_overlapping_deprecated.py
  test/deprecated/auto_parallel/test_pipeline_scheduler_deprecated.py
  test/deprecated/auto_parallel/test_pipeline_scheduler_vpp_deprecated.py
  test/deprecated/auto_parallel/test_pipeline_scheduler_zb_deprecated.py
  test/deprecated/auto_parallel/test_pipeline_scheduler_zb_vpp_deprecated.py
  tools/count_api_without_core_ops.py
Labels: PaddlePaddle Hackathon, contributor

#71931 add fc te
  paddle/fluid/pir/transforms/xpu/fc_xpu_fuse_pass.cc
  paddle/phi/kernels/xpu/xpu_api_wrapper.h
Labels: XPU

#72011 [fluid_ops]clean send_v2 TensorArray
  paddle/fluid/operators/collective/recv_v2_op.cu.cc
  paddle/fluid/operators/collective/send_v2_op.cu.cc
Labels: PaddlePaddle Hackathon, contributor

#72043 [fluid_ops] clean c_reduce* config
  paddle/fluid/framework/new_executor/pir_interpreter.cc
  paddle/fluid/pybind/eager_generator.cc
Labels: PaddlePaddle Hackathon, contributor

#72034 [fluid_ops]clean c_allreduce_max config
  paddle/fluid/framework/new_executor/pir_interpreter.cc
  paddle/fluid/inference/tensorrt/convert/c_allreduce_op.cc
  paddle/fluid/inference/tensorrt/op_teller.cc
  python/paddle/distributed/auto_parallel/static/mapper.py
  python/paddle/distributed/auto_parallel/static/operators/common.py
  python/paddle/distributed/auto_parallel/static/operators/dist_check_finite_and_unscale.py
  python/paddle/distributed/fleet/meta_optimizers/sharding/fp16_helper.py
  python/paddle/distributed/fleet/meta_optimizers/sharding/utils.py
  python/paddle/distributed/passes/fuse_all_reduce.py
Labels: PaddlePaddle Hackathon, contributor

#72047 [fluid_ops] clean config in operator/utils/utils.cc
  paddle/fluid/pir/dialect/operator/utils/utils.cc
Labels: PaddlePaddle Hackathon, contributor

#72013 [CI] Fix approval
  .github/actions/check-bypass/action.yml
  .github/workflows/Approval.yml
Labels: skip-ci: sot, skip-ci: approval

#72003 fix nonzero
  python/paddle/tensor/search.py
  test/legacy_test/test_nonzero_api.py
  test/legacy_test/test_where_op.py
  test/xpu/test_where_index_xpu.py
Labels: contributor

#72025 [CINN] Fix kernel type errors (atan, pow, exp, bitwise_xxx)
  paddle/cinn/backends/llvm/llvm_intrin_rule.h
  paddle/cinn/ir/op/ir_operators.cc
  paddle/cinn/optim/map_extern_call.cc
  paddle/cinn/runtime/cpu/host_intrinsics.cc
  paddle/cinn/runtime/cuda/cinn_cuda_runtime_source.cuh
  paddle/cinn/runtime/cuda/cuda_intrinsics.cc
Labels: contributor

#72060 [fluid_ops] update IsCommunicationOp
  paddle/fluid/framework/new_executor/interpreter/interpreter_util.cc
Labels: PaddlePaddle Hackathon, contributor

#72056 [fluid_ops] clean push_dense yaml config
  paddle/fluid/ir_adaptor/translator/op_compat_gen.py
  paddle/fluid/pir/dialect/op_generator/ops_api_gen.py
  paddle/phi/api/generator/api_gen.py
  paddle/phi/ops/yaml/backward.yaml
  paddle/phi/ops/yaml/inconsistent/static_backward.yaml
  paddle/phi/ops/yaml/inconsistent/static_ops.yaml
  paddle/phi/ops/yaml/op_compat.yaml
Labels: PaddlePaddle Hackathon, contributor

#72087 [fluid_ops] dist_reduce_sum_p.py modify c_allreduce_sum
  python/paddle/distributed/auto_parallel/static/operators/dist_reduce_sum_p.py
Labels: PaddlePaddle Hackathon, contributor

#72086 [fluid_ops] hogwild_worker.cc add all_reduce
  paddle/fluid/framework/hogwild_worker.cc
Labels: PaddlePaddle Hackathon, contributor

#72093 Fix typos Pleas Please
  paddle/fluid/eager/api/generated/eager_generated/backwards/scale_node.cc
  paddle/fluid/eager/to_static/run_program_op_func.h
  python/paddle/distributed/checkpoint/load_state_dict.py
  python/paddle/distributed/checkpoint/save_state_dict.py
  python/paddle/distributed/fleet/launch_utils.py
  python/paddle/metric/metrics.py
  python/paddle/optimizer/lr.py
Labels: contributor, HappyOpenSource

#72083 [fluid_ops] collective_allreduce_op.py modify c_allreduce_sum
  test/collective/collective_allreduce_op.py
Labels: PaddlePaddle Hackathon, contributor

#72082 [fluid_ops] auto_parallel_grad_clip.py modify c_allreduce_sum
  python/paddle/distributed/passes/auto_parallel_grad_clip.py
Labels: PaddlePaddle Hackathon

#72079 [fluid_ops] graph_helper c_allreduce_sum
  paddle/fluid/framework/ir/graph_helper.cc
Labels: PaddlePaddle Hackathon, contributor

#72078 [fluid_ops] transpiler/collective.py modify c_allreduce_sum
  python/paddle/distributed/transpiler/collective.py
Labels: PaddlePaddle Hackathon, contributor

#72073 [fluid_ops] c_allreduce_sum strings
  paddle/fluid/framework/ir/fused_multi_transformer_decoder_pass.cc
  paddle/fluid/framework/ir/fused_multi_transformer_decoder_pass_tester.cc
  paddle/fluid/framework/ir/fused_multi_transformer_encoder_pass.cc
  paddle/fluid/framework/ir/graph_helper.cc
  paddle/phi/kernels/check_memory_continue_kernel.h
  python/paddle/distributed/passes/allreduce_matmul_grad_overlapping.py
  python/paddle/distributed/passes/auto_parallel_fused_linear_promotion.py
Labels: PaddlePaddle Hackathon, contributor

#72057 [fluid_ops] clean c_allreduce_prod
  paddle/fluid/framework/new_executor/pir_interpreter.cc
  paddle/fluid/inference/tensorrt/convert/c_allreduce_op.cc
  paddle/fluid/inference/tensorrt/op_teller.cc
  paddle/phi/backends/xpu/xpu2_op_list.cc
  paddle/phi/backends/xpu/xpu3_op_list.cc
  python/paddle/distributed/auto_parallel/static/mapper.py
  python/paddle/distributed/auto_parallel/static/operators/common.py
  python/paddle/distributed/passes/auto_parallel_data_parallel_optimization.py
  python/paddle/distributed/passes/auto_parallel_sharding.py
  python/paddle/distributed/passes/fuse_all_reduce.py
  test/ir/inference/test_trt_convert_c_allreduce.py
Labels: PaddlePaddle Hackathon, contributor

#72077 [fluid_ops] base_cost.py modify c_allreduce_sum
  python/paddle/distributed/auto_parallel/static/cost/__init__.py
  python/paddle/distributed/auto_parallel/static/cost/base_cost.py
  python/paddle/distributed/auto_parallel/static/cost/comm_op_cost.py
  python/paddle/distributed/auto_parallel/static/mapper.py
  python/paddle/distributed/auto_parallel/static/operators/dist_embedding.py
  test/deprecated/auto_parallel/test_base_cost_deprecated.py
  test/deprecated/auto_parallel/test_dist_embedding_deprecated.py
  test/deprecated/auto_parallel/test_new_cost_model_deprecated.py
  test/deprecated/legacy_test/test_auto_parallel_partitioner_deprecated.py
Labels: PaddlePaddle Hackathon, contributor

#72081 [SOT][Faster Guard] support `object_equal_stringified_guard`
  paddle/fluid/pybind/jit.cc
  paddle/fluid/pybind/sot/guards.cc
  paddle/fluid/pybind/sot/guards.h
  python/paddle/jit/sot/opcode_translator/executor/guard.py
  python/paddle/jit/sot/opcode_translator/executor/variables/basic.py
  test/sot/test_faster_guard.py
Labels: contributor

#72096 [fluid_ops] test_trt_convert_c_allreduce.py modify c_allreduce_sum
  test/ir/inference/test_trt_c_allreduce_infer_script.py
  test/ir/inference/test_trt_convert_c_allreduce.py
Labels: PaddlePaddle Hackathon, contributor

#72085 [fluid_ops] dist_mnist_gradient_merge_raw_optimizer.py add all_reduce
  test/collective/fleet/dist_mnist_gradient_merge_raw_optimizer.py
Labels: PaddlePaddle Hackathon, contributor

#72092 [fluid_ops] fleet modify c_allreduce_sum
  python/paddle/distributed/fleet/meta_optimizers/common.py
  python/paddle/distributed/fleet/meta_optimizers/localsgd_optimizer.py
  python/paddle/distributed/fleet/meta_optimizers/pipeline_optimizer.py
  python/paddle/distributed/fleet/meta_optimizers/raw_program_optimizer.py
  python/paddle/distributed/fleet/meta_optimizers/sharding/gradient_clip_helper.py
  python/paddle/distributed/fleet/meta_optimizers/sharding/utils.py
  python/paddle/distributed/fleet/meta_optimizers/sharding_optimizer.py
  python/paddle/distributed/fleet/meta_optimizers/tensor_parallel_optimizer.py
  python/paddle/incubate/distributed/fleet/parameter_server/pslib/__init__.py
  python/paddle/static/amp/fp16_lists.py
Labels: PaddlePaddle Hackathon, contributor

#71999 [CINN]Change To The cooperative_groups syncthread
  paddle/cinn/backends/codegen_cuda_dev.cc
  paddle/cinn/backends/codegen_device_util.cc
  paddle/cinn/common/target.cc
  paddle/cinn/common/target.h
  paddle/cinn/hlir/framework/pir/op_lowering_impl.cc
  paddle/cinn/hlir/framework/pir/trivial_op_impl.cc
  paddle/cinn/ir/group_schedule/config/group_tile_util.cc
  paddle/cinn/ir/group_schedule/config/group_tile_util.h
  paddle/cinn/optim/replace_cross_block_reduction.cc
  paddle/cinn/optim/replace_cross_block_reduction.h
  paddle/cinn/runtime/cuda/cinn_cuda_runtime_source.cuh
  paddle/cinn/runtime/cuda/cuda_intrinsics_reduce.cc
  test/cpp/pir/cinn/replace_cross_block_reduction_test.cc
Labels: contributor

#72110 [fluid_ops] remove use_calc_stream check
  python/paddle/distributed/passes/auto_parallel_data_parallel_optimization.py
  test/deprecated/auto_parallel/test_auto_parallel_data_parallel_optimization_pass_deprecated.py
Labels: PaddlePaddle Hackathon, contributor

#72127 [fluid_ops] auto_parallel_sharding.py modify c_allreduce_sum
  python/paddle/distributed/passes/auto_parallel_sharding.py
Labels: PaddlePaddle Hackathon, contributor

#72111 [fluid_ops]dist_default modify c_allreduce_sum
  python/paddle/distributed/auto_parallel/static/operators/common.py
  python/paddle/distributed/auto_parallel/static/operators/dist_default.py
  test/deprecated/auto_parallel/test_while_op_partition_deprecated.py
  test/deprecated/legacy_test/test_auto_parallel_partitioner_gpt_deprecated.py
Labels: PaddlePaddle Hackathon, contributor

#71985 [CINN] [New Hardware Update]Fix hip optimize bugs
  paddle/cinn/optim/optimize.cc
Labels: contributor

#72153 [CI] Set wheel version 0.45
  paddle/scripts/compile_requirements.txt
Labels: skip-ci: approval

#72126 [fluid_ops] dist_matmul modify c_allreduce_sum
  python/paddle/distributed/auto_parallel/static/operators/dist_matmul.py
  python/paddle/distributed/passes/auto_parallel_fused_linear_promotion.py
  test/deprecated/auto_parallel/test_dist_matmul_deprecated.py
  test/deprecated/legacy_test/test_auto_parallel_partitioner_deprecated.py
Labels: PaddlePaddle Hackathon, contributor

#72135 [fluid_ops] auto_parallel_fused_linear_promotion.py backward modify c_allreduce_sum
  python/paddle/distributed/passes/auto_parallel_fused_linear_promotion.py
Labels: PaddlePaddle Hackathon, contributor

#72131 [fluid_ops] random_control_unittest_deprecated.py modify c_sync_calc_stream
  test/deprecated/auto_parallel/random_control_unittest_deprecated.py
Labels: PaddlePaddle Hackathon, contributor

#72152 [fluid_ops] test_variable_deprecated.py remove lod_level
  test/deprecated/legacy_test/test_variable_deprecated.py
  test/deprecated/legacy_test/utils.py
Labels: PaddlePaddle Hackathon, contributor

#72145 [fluid_ops] modify FP32_LODTensor to FP32_DenseTensor
  python/paddle/optimizer/adam.py
  python/paddle/optimizer/momentum.py
  python/paddle/optimizer/optimizer.py
Labels: PaddlePaddle Hackathon, contributor

#72136 [XPU] avoid using xpu-smi to query device info
  paddle/fluid/pybind/pybind.cc
  paddle/phi/backends/xpu/enforce_xpu.h
  paddle/phi/backends/xpu/xpu_info.cc
  paddle/phi/backends/xpu/xpu_info.h
  paddle/phi/core/platform/device/xpu/xpu_info.cc
  paddle/phi/core/platform/device/xpu/xpu_info.h
  python/paddle/distributed/launch/utils/nvsmi.py
  test/xpu/test_query_xpu_device_info.py
Labels: XPU

#72031 [CI] Add Coverage
  .github/codecov.yml
  .github/workflows/CI.yml
  .github/workflows/_Clone-linux.yml
  .github/workflows/_Coverage.yml
  ci/check_added_ut.sh
  ci/coverage_build.sh
  ci/coverage_build_size_approval.sh
  ci/coverage_diff.py
  ci/coverage_gcda_clean.py
  ci/coverage_info.sh
  ci/coverage_pull_request.py
  ci/coverage_python_coverage.py
  ci/coverage_test.sh
  ci/run_linux_cpu_test.sh
  ci/run_setup.sh
  ci/utils.sh
  tools/get_pr_ut.py
Labels: skip-ci: sot, skip-ci: approval

#72141 [CI] disable verbose log in check approval workflow
  .github/workflows/Approval.yml
Labels: skip-ci: approval

#71948 [fluid_ops] test_auto_parallel_partitioner_deprecated.py modify c_allreduce_sum
  paddle/fluid/operators/collective/c_allreduce_sum_op.cc
  paddle/fluid/operators/collective/c_allreduce_sum_op.cu.cc
  paddle/fluid/operators/collective/c_allreduce_sum_op.kps
  python/paddle/distributed/auto_parallel/static/operators/common.py
  python/paddle/distributed/passes/auto_parallel_data_parallel_optimization.py
  test/deprecated/auto_parallel/test_dist_embedding_deprecated.py
  test/deprecated/auto_parallel/test_dist_matmul_deprecated.py
Labels: PaddlePaddle Hackathon, contributor

#70358 [fluid_ops] clean data_norm in python
  python/paddle/static/nn/__init__.py
  python/paddle/static/nn/common.py
  test/legacy_test/test_directory_migration.py
Labels: PaddlePaddle Hackathon, contributor

#71994 [SOT][Faster Guard][3.13] implement faster lookup
  paddle/fluid/pybind/jit.cc
  paddle/fluid/pybind/sot/guards.cc
  paddle/fluid/pybind/sot/guards.h
  python/paddle/jit/sot/opcode_translator/executor/executor_cache.py
  python/paddle/jit/sot/opcode_translator/executor/function_graph.py
  python/paddle/jit/sot/opcode_translator/executor/guard.py
  python/paddle/jit/sot/opcode_translator/executor/opcode_executor.py
  python/paddle/jit/sot/opcode_translator/executor/tracker.py
  python/paddle/jit/sot/opcode_translator/executor/variables/base.py
  python/paddle/jit/sot/opcode_translator/executor/variables/basic.py
  python/paddle/jit/sot/opcode_translator/executor/variables/callable.py
  python/paddle/jit/sot/opcode_translator/executor/variables/container.py
  python/paddle/jit/sot/opcode_translator/executor/variables/iter.py
  test/sot/test_guard_tree.py
  test/sot/test_instruction_translator_cache.py
Labels: contributor

#72125 [fluid_ops] clean c_broadcast config
  paddle/fluid/framework/new_executor/pir_interpreter.cc
  paddle/fluid/framework/op_compatible_info.cc
  paddle/fluid/framework/op_version_proto.cc
  paddle/fluid/framework/unused_var_check.cc
Labels: PaddlePaddle Hackathon, contributor

#72195 [fluid_ops] Fix typos allotor allocator
  paddle/fluid/inference/api/analysis_predictor.cc
  paddle/fluid/inference/api/demo_ci/run_windows_demo.bat
Labels: contributor, HappyOpenSource

#72171 [fluid_ops] communication/group.py modify c_sync_calc_stream
  python/paddle/distributed/communication/group.py
Labels: PaddlePaddle Hackathon, contributor

#72142 [CINN] [New Hardware Update]Clean obsolete HIP Reduce templates
  paddle/cinn/backends/codegen_device_util.cc
  paddle/cinn/backends/codegen_invoke_module.h
  paddle/cinn/runtime/hip/cinn_hip_runtime_source.h
  paddle/cinn/runtime/hip/hip_intrinsics.cc
  paddle/cinn/runtime/hip/hip_intrinsics_reduce.cc
  paddle/cinn/runtime/hip/hip_util.cc
  paddle/cinn/runtime/hip/hip_util.h
  paddle/cinn/runtime/intrinsic.h
Labels: contributor

#72188 [fluid_ops] sum modify _legacy_C_ops
  test/legacy_test/test_tdm_child_op.py
  test/xpu/test_sum_op_xpu.py
Labels: PaddlePaddle Hackathon, contributor

#72197 [fluid_ops]adam modify _legacy_C_ops
  test/legacy_test/test_merged_adam_op.py
Labels: PaddlePaddle Hackathon, contributor

#72241 fix typos
  python/paddle/nn/layer/conv.py
  python/paddle/nn/layer/loss.py
  python/paddle/nn/layer/pooling.py
Labels: contributor, HappyOpenSource

#72237 fix typos
  python/paddle/jit/dy2static/program_translator.py
  python/paddle/nn/layer/layers.py
Labels: contributor, HappyOpenSource

#72212 [fluid_ops] matmul_v2 modify _legacy_C_ops
  test/legacy_test/test_function_hook.py
  test/legacy_test/test_reset_grad_inplace_version.py
Labels: PaddlePaddle Hackathon, contributor

#72211 [fluid_ops] squared_l2_norm modify _legacy_C_ops
  test/legacy_test/test_squared_l2_norm_op.py
Labels: PaddlePaddle Hackathon, contributor

#72184 [fluid_ops] clean soft_relu in fluid/operators
  paddle/fluid/operators/activation_op.cc
  paddle/fluid/operators/activation_op.h
Labels: PaddlePaddle Hackathon, contributor

#72177 [Auto-parallel] add unary ops which have spmd_rule but not add in yaml file.
  paddle/phi/ops/yaml/ops.yaml
Labels: contributor

#72162 [fluid_ops] _get_reduce_op remove func_name parameter
  python/paddle/distributed/communication/reduce.py
  python/paddle/distributed/communication/stream/all_reduce.py
  python/paddle/distributed/communication/stream/reduce.py
  python/paddle/distributed/communication/stream/reduce_scatter.py
  python/paddle/distributed/fleet/layers/mpu/mp_layers.py
  python/paddle/distributed/fleet/layers/mpu/mp_ops.py
Labels: PaddlePaddle Hackathon, contributor

#71897 [fluid_ops] clean c_allreduce_sum config
  paddle/fluid/operators/collective/c_allreduce_sum_op.cc
  paddle/fluid/pir/dialect/operator/utils/utils.cc
  test/collective/fleet/dist_mnist_gradient_merge_raw_optimizer.py
  test/deprecated/auto_parallel/test_while_op_partition_deprecated.py
  test/deprecated/legacy_test/test_auto_parallel_partitioner_gpt_deprecated.py
Labels: PaddlePaddle Hackathon, contributor

#72229 refine IsCommunicationOp
  paddle/fluid/framework/new_executor/interpreter/interpreter_util.cc
Labels: contributor, HappyOpenSource

#72208 Fix bool_attrs to double_attrs
  paddle/fluid/inference/tensorrt/convert/generic_and_custom_plugin_creater.cc
Labels: contributor, HappyOpenSource

#72218 [fluid_ops] all_gather modify _legacy_C_ops
  python/paddle/distributed/fleet/meta_parallel/pp_utils/utils.py
  python/paddle/incubate/distributed/models/moe/moe_layer.py
Labels: PaddlePaddle Hackathon, contributor

#72064 [fluid_ops] remove fake_init
  paddle/fluid/operators/pscore/fake_init_op.cc
  test/legacy_test/test_fake_init_op.py
Labels: contributor

#72074 [fluid_ops]remove fluid send_op
  paddle/fluid/operators/pscore/send_op.cc
  test/deprecated/legacy_test/test_dist_fleet_a_sync_optimizer_auto_deprecated.py
  test/deprecated/legacy_test/test_dist_fleet_a_sync_optimizer_auto_geo_deprecated.py
Labels: PaddlePaddle Hackathon, contributor

#70330 [fluid_ops] clean distributed_push_sparse config
  paddle/fluid/pir/dialect/op_generator/ops_api_gen.py
  paddle/fluid/pir/dialect/operator/utils/utils.cc
  paddle/phi/ops/yaml/inconsistent/static_ops.yaml
  paddle/phi/ops/yaml/op_compat.yaml
Labels: PaddlePaddle Hackathon, contributor

#72285 [SOT][Faster Guard] support stringify for guard tree
  paddle/fluid/pybind/jit.cc
  paddle/fluid/pybind/sot/guards.cc
  paddle/fluid/pybind/sot/guards.h
  python/paddle/jit/sot/opcode_translator/executor/executor_cache.py
Labels: contributor

#72041 [XPU] adapt new interface for uniform kernel
  paddle/phi/kernels/xpu/uniform_kernel.cc
  test/legacy_test/test_adamw_op.py
  test/xpu/parallel_api_xpu.py
Labels: XPU

#72260 [Auto Parallel] add unary backward ops which have spmd_rule but not add in yaml file.
  paddle/phi/ops/yaml/backward.yaml
Labels: contributor

#70274 Fix typos rshard reshard
  python/paddle/distributed/auto_parallel/intermediate/pipeline_parallel.py
  python/paddle/distributed/auto_parallel/intermediate/tensor_parallel.py
  python/paddle/distributed/auto_parallel/static/partitioner.py
  python/paddle/distributed/auto_parallel/static/process_mesh_v2.py
Labels: contributor, HappyOpenSource

#72265 [fluid_ops] clean c_allreduce_sum if statement
  python/paddle/distributed/auto_parallel/static/mapper.py
  python/paddle/distributed/auto_parallel/static/operators/common.py
  python/paddle/distributed/fleet/meta_optimizers/sharding/prune.py
  python/paddle/distributed/fleet/meta_optimizers/sharding/utils.py
  python/paddle/distributed/fleet/meta_optimizers/sharding_optimizer.py
  python/paddle/distributed/passes/allreduce_matmul_grad_overlapping.py
  python/paddle/distributed/passes/auto_parallel_data_parallel_optimization.py
  python/paddle/distributed/passes/auto_parallel_fused_linear_promotion.py
  python/paddle/distributed/passes/auto_parallel_gradient_merge.py
  python/paddle/distributed/passes/auto_parallel_sequence_parallel_optimization.py
  python/paddle/distributed/passes/auto_parallel_sharding.py
  python/paddle/distributed/passes/fuse_all_reduce.py
  python/paddle/distributed/passes/pipeline_scheduler_pass/pipeline_1f1b.py
  python/paddle/distributed/transpiler/collective.py
  python/paddle/static/amp/fp16_lists.py
Labels: PaddlePaddle Hackathon, contributor

#72295 remove paddle/fluid/operators/pscore/
  paddle/fluid/operators/CMakeLists.txt
  paddle/fluid/operators/pscore/CMakeLists.txt
Labels: PaddlePaddle Hackathon, contributor

#72139 fix tensordot
  python/paddle/tensor/manipulation.py
  python/paddle/tensor/math.py
  test/legacy_test/test_sum_op.py
Labels: contributor

#72138 fix sumraw
  paddle/phi/kernels/cpu/reduce_sum_kernel.cc
  paddle/phi/kernels/kps/reduce_kernel.cu
  test/legacy_test/test_sum_op.py
Labels: contributor

#72262 Inv support 0-size
  paddle/phi/infermeta/unary.cc
  paddle/phi/kernels/impl/inverse_grad_kernel_impl.h
  paddle/phi/kernels/impl/inverse_kernel_impl.h
  test/legacy_test/test_inverse_op.py
Labels: contributor

#72247 paddle.where support complex64 and complex128
  paddle/phi/kernels/cpu/where_grad_kernel.cc
  paddle/phi/kernels/cpu/where_kernel.cc
  paddle/phi/kernels/gpu/where_grad_kernel.cu
  paddle/phi/kernels/gpu/where_kernel.cu
  test/legacy_test/test_where_op.py
Labels: contributor

#72220 [fluid_ops] dropout add default value
  paddle/phi/ops/yaml/ops.yaml
Labels: contributor, HappyOpenSource

#72304 all_reduce modify _get_reduce_op
  python/paddle/distributed/communication/reduce.py
  python/paddle/distributed/communication/stream/all_reduce.py
Labels: PaddlePaddle Hackathon, contributor

#72277 [CINN]optimize CUDA launch bounds calculation and usage
  paddle/cinn/backends/codegen_gpu_dev.cc
  paddle/cinn/ir/lowered_func.h
  paddle/cinn/ir/schedule/ir_schedule_util.cc
Labels: contributor

#72245 [CINN]Add remove_redundant_full_int_array_pass
  paddle/cinn/hlir/dialect/operator/transforms/add_cinn_pass.cc
  paddle/cinn/hlir/dialect/operator/transforms/remove_redundant_full_int_array_pass.cc
  paddle/cinn/hlir/dialect/operator/transforms/remove_redundant_full_int_array_pass.h
Labels: contributor

#72256 Avoid NPU context null error by setting device when constructing Standalone Executor
  paddle/fluid/framework/new_executor/standalone_executor.cc
Labels: contributor

#72272 [SOT][Faster Guard] Implement more `make_faster_guard`
  paddle/fluid/pybind/jit.cc
  paddle/fluid/pybind/sot/guards.cc
  paddle/fluid/pybind/sot/guards.h
  python/paddle/jit/sot/opcode_translator/executor/executor_cache.py
  python/paddle/jit/sot/opcode_translator/executor/guard.py
  python/paddle/jit/sot/opcode_translator/executor/variables/base.py
  python/paddle/jit/sot/opcode_translator/executor/variables/basic.py
  python/paddle/jit/sot/opcode_translator/executor/variables/callable.py
  python/paddle/jit/sot/opcode_translator/executor/variables/container.py
  test/sot/test_15_slice.py
  test/sot/test_instruction_translator_cache.py
Labels: contributor

#72182 [CI] Modify PADDLE_ROOT
  .github/workflows/_Coverage.yml
  .github/workflows/_SOT.yml
  ci/coverage_build.sh
  ci/coverage_build_size_approval.sh
  ci/coverage_test.sh
  ci/run_setup.sh
  ci/utils.sh
Labels: skip-ci: approval, skip-ci: inference

#72342 [CI] Fix rerun and add inference rerun
  .github/actions/rerun-workflow/rerun.sh
  .github/workflows/re-run.yml
Labels: skip-ci: sot, skip-ci: approval, skip-ci: coverage, skip-ci: inference

#72343 clean c_allreduce_op.h
  paddle/fluid/operators/collective/c_allreduce_op.h
  paddle/fluid/operators/collective/mp_allreduce_sum_op.cc
Labels: PaddlePaddle Hackathon, contributor

#72303 clean send_and_recv config
  paddle/fluid/framework/op_version_proto.cc
  paddle/fluid/pir/dialect/op_generator/ops_api_gen.py
  paddle/phi/ops/yaml/inconsistent/static_ops.yaml
  paddle/phi/ops/yaml/op_compat.yaml
Labels: PaddlePaddle Hackathon, contributor

#72296 remove c_allgather_op.cc
  paddle/fluid/operators/collective/c_allgather_op.cc
  paddle/fluid/operators/collective/c_allgather_op.h
  paddle/fluid/operators/collective/c_split_op.cc
Labels: PaddlePaddle Hackathon, contributor

#72280 [XPU] support multi card profiling
  cmake/external/xpu.cmake
Labels: XPU

#72336 remove include operators/activation_op.h
  paddle/fluid/pybind/compiled_program.cc
  paddle/fluid/pybind/place.cc
  paddle/fluid/pybind/pybind.cc
  paddle/fluid/pybind/tensor.cc
Labels: PaddlePaddle Hackathon, contributor

#72338 clean custom_device_common_op_registry
  paddle/fluid/eager/auto_code_generator/CMakeLists.txt
  paddle/fluid/operators/CMakeLists.txt
  paddle/fluid/operators/custom_device_common_op_registry.cc
  paddle/fluid/operators/custom_device_common_op_registry.h
  paddle/fluid/pybind/CMakeLists.txt
  paddle/fluid/pybind/eager_generator.cc
  paddle/fluid/pybind/eager_legacy_op_function_generator.cc
  paddle/fluid/pybind/pybind.cc
Labels: PaddlePaddle Hackathon, contributor

#72328 instruction_util.cc remove duplicate config
  paddle/fluid/framework/new_executor/instruction/instruction_util.cc
Labels: PaddlePaddle Hackathon, contributor

#72282 [BIT] fix unexpected inplace squeeze_ in paddle.signal.istft
  python/paddle/signal.py
Labels: contributor, HappyOpenSource Pro

#72361 [XPU update xhpc date to 20250417
  cmake/external/xpu.cmake
Labels: XPU

#72263 【BIT】isclose Tensor.isclose support 0-size
  paddle/phi/kernels/impl/isclose_kernel_impl.h
  test/legacy_test/test_isclose_op.py
Labels: contributor, HappyOpenSource Pro

#72307 [CINN]Add Type Support for Sigmoid and LogicalNot
  paddle/cinn/hlir/dialect/operator/transforms/pd_to_cinn_pass.cc
  paddle/cinn/lang/builtin.h
Labels: contributor

#72232 [CINN] [New Hardware Update]:SYCL PR5: Release SYCL's dependence on CINN_WITH_HIP
  cmake/cinn.cmake
  paddle/cinn/backends/CMakeLists.txt
  paddle/cinn/optim/optimize.cc
  paddle/cinn/runtime/CMakeLists.txt
  paddle/cinn/runtime/sycl/sycl_intrinsics.cc
  paddle/cinn/runtime/sycl/sycl_util.cc
  paddle/cinn/runtime/sycl/sycl_util.h
Labels: contributor

#72279 paddle.nonzero support complex
  paddle/phi/kernels/cpu/nonzero_kernel.cc
  paddle/phi/kernels/gpu/nonzero_kernel.cu
  test/legacy_test/test_nonzero_api.py
Labels: contributor

#72249 [CI] Add CPU and NPU workflow
  .github/workflows/CI.yml
  .github/workflows/_CPU.yml
  .github/workflows/_NPU.yml
  .github/workflows/re-run.yml
  ci/utils.sh
Labels: skip-ci: sot, skip-ci: approval, skip-ci: coverage, skip-ci: xpu, skip-ci: inference

#72068 [CI] Add kunlun and change name with XPU
  .github/workflows/CI.yml
  .github/workflows/_Linux-XPU.yml
  .github/workflows/re-run.yml
  ci/kunlun_test.sh
  ci/run_setup.sh
  ci/utils.sh
Labels: skip-ci: approval, skip-ci: inference

#72380 Support FakeTensorArray for Backend Inference
  paddle/fluid/pir/dialect/operator/ir/manual_op.cc
  paddle/fluid/pir/transforms/pd_op_to_kernel_pass.cc
  paddle/phi/api/lib/kernel_dispatch.cc
Labels: contributor

#72308 matrix_power support complex
  paddle/phi/kernels/cpu/matrix_power_grad_kernel.cc
  paddle/phi/kernels/cpu/matrix_power_kernel.cc
  paddle/phi/kernels/gpu/matrix_power_grad_kernel.cu
  paddle/phi/kernels/gpu/matrix_power_kernel.cu
  test/legacy_test/test_matrix_power_op.py
Labels: contributor

#71997 在Upsample和interpolate函数中加入recompute_scale_factor参数
  python/paddle/nn/functional/common.py
  python/paddle/nn/layer/common.py
  test/legacy_test/CMakeLists.txt
  test/legacy_test/test_interp_recompute_scale_factor.py
Labels: contributor

#72341 modify logging.warn
  python/paddle/base/reader.py
  python/paddle/distributed/fleet/meta_optimizers/dgc_optimizer.py
  python/paddle/distributed/fleet/meta_optimizers/lamb_optimizer.py
  python/paddle/distributed/fleet/meta_optimizers/lars_optimizer.py
  python/paddle/distributed/fleet/runtime/collective_runtime.py
  python/paddle/distributed/transpiler/distribute_transpiler.py
  python/paddle/distributed/transpiler/memory_optimization_transpiler.py
  python/paddle/incubate/distributed/fleet/collective.py
Labels: contributor, HappyOpenSource

#72204 [CINN]Add iter_vals type cast logic
  paddle/cinn/ast_gen_ius/ast_gen.cc
  paddle/cinn/hlir/pe/elementwise.cc
Labels: contributor

#72406 [XPU] sigmoid and sigmoid_grad support type of bfloat16
  paddle/phi/backends/xpu/xpu3_op_list.cc
  paddle/phi/kernels/xpu/activation_grad_kernel.cc
  paddle/phi/kernels/xpu/activation_kernel.cc
  test/xpu/test_activation_op_xpu.py
Labels: XPU

#72269 [Auto Parallel]Add spmd_rule for min and min_grad ops.
  paddle/phi/infermeta/spmd_rules/reduction.cc
  paddle/phi/infermeta/spmd_rules/reduction.h
  paddle/phi/ops/yaml/inconsistent/dygraph_backward.yaml
  paddle/phi/ops/yaml/inconsistent/dygraph_ops.yaml
  paddle/phi/ops/yaml/inconsistent/static_backward.yaml
  paddle/phi/ops/yaml/inconsistent/static_ops.yaml
  test/cpp/auto_parallel/spmd_rule_test.cc
Labels: contributor

#72310 [Auto Parallel]Add spmd rule for five ops(bitwise_or,atan2,fmax,fmin,reciprocal).
  paddle/phi/ops/yaml/backward.yaml
  paddle/phi/ops/yaml/ops.yaml
Labels: contributor

#71804 新增API local_map
  python/paddle/distributed/__init__.py
  python/paddle/distributed/auto_parallel/api.py
  python/paddle/distributed/auto_parallel/local_map.py
  test/auto_parallel/hybrid_strategy/single_llama_model.py
  test/auto_parallel/local_view_compute.py
  test/auto_parallel/pir/CMakeLists.txt
  test/auto_parallel/pir/local_map_demo.py
  test/auto_parallel/pir/test_local_map.py
  test/auto_parallel/pir/vpp_pass_unittest_local_view_pir.py
Labels: contributor

#70001 Fix typos in external/pslib_brpc.cmake
  cmake/cinn/core.cmake
  cmake/external/pslib_brpc.cmake
  cmake/simd.cmake
Labels: contributor, HappyOpenSource

#72435 [CI] Update CPU workflow log
  .github/workflows/CI.yml
  .github/workflows/_Linux-CPU.yml
  .github/workflows/_Linux-NPU.yml
  ci/run_linux_cpu_test.sh
  ci/utils.sh
Labels: skip-ci: sot, skip-ci: approval, skip-ci: coverage, skip-ci: mac, skip-ci: xpu, skip-ci: inference

#72438 [SOT][Faster Guard] Implement `SymbolicVariable.make_faster_guard`
  paddle/fluid/pybind/jit.cc
  paddle/fluid/pybind/sot/guards.cc
  paddle/fluid/pybind/sot/guards.h
  python/paddle/jit/sot/opcode_translator/executor/executor_cache.py
  python/paddle/jit/sot/opcode_translator/executor/function_graph.py
  python/paddle/jit/sot/opcode_translator/executor/guard.py
  python/paddle/jit/sot/opcode_translator/executor/variables/base.py
  python/paddle/jit/sot/opcode_translator/executor/variables/basic.py
  python/paddle/jit/sot/opcode_translator/executor/variables/callable.py
  python/paddle/jit/sot/opcode_translator/executor/variables/container.py
  python/paddle/jit/sot/opcode_translator/executor/variables/iter.py
  python/paddle/jit/sot/symbolic_shape/constraints.py
Labels: contributor

#70348 Fix typos euqal equal
  python/paddle/distributed/checkpoint/load_state_dict.py
  python/paddle/distributed/fleet/base/distributed_strategy.py
  python/paddle/nn/layer/rnn.py
  python/paddle/quantization/config.py
  test/cpp/phi/core/test_intrusive_ptr.cc
Labels: contributor, HappyOpenSource

#70329 Fix typos oepn open
  tools/check_api_approvals.sh
  tools/get_single_test_cov.py
Labels: contributor, HappyOpenSource

#72463 [SOT][Faster Guard] Implement more`guard_tree_expr_node` and `TensorDtypeVariable.make_faster_guard`
  paddle/fluid/pybind/sot/guards.cc
  python/paddle/jit/sot/opcode_translator/executor/executor_cache.py
  python/paddle/jit/sot/opcode_translator/executor/function_graph.py
  python/paddle/jit/sot/opcode_translator/executor/opcode_inline_executor.py
  python/paddle/jit/sot/opcode_translator/executor/tracker.py
  python/paddle/jit/sot/opcode_translator/executor/variables/basic.py
  python/paddle/jit/sot/opcode_translator/executor/virtual_frame.py
Labels: contributor

#72327 [SOT][Faster Guard] support `TensorVariable` Dist check
  paddle/fluid/pybind/jit.cc
  paddle/fluid/pybind/sot/guards.cc
  paddle/fluid/pybind/sot/guards.h
  python/paddle/jit/sot/opcode_translator/executor/variables/basic.py
  test/sot/test_faster_guard.py
Labels: contributor, skip-ci: approval

#72503 [SOT][Faster Guard] Implement DummyGuardNode
  paddle/fluid/pybind/jit.cc
  paddle/fluid/pybind/sot/guards.cc
  paddle/fluid/pybind/sot/guards.h
  python/paddle/jit/sot/opcode_translator/executor/executor_cache.py
  python/paddle/jit/sot/opcode_translator/executor/tracker.py
  test/sot/test_instruction_translator_cache.py
Labels: contributor

#72501 [SOT][Faster Guard] Move all trackers implements to `tracker.py`
  paddle/fluid/pybind/sot/guards.cc
  python/paddle/jit/sot/opcode_translator/executor/opcode_inline_executor.py
  python/paddle/jit/sot/opcode_translator/executor/tracker.py
  python/paddle/jit/sot/opcode_translator/executor/variables/basic.py
  python/paddle/jit/sot/opcode_translator/executor/virtual_frame.py
Labels: contributor

#72482 [Update] test matrix exp tol for mac m4
  test/legacy_test/test_linalg_matrix_exp.py
Labels: contributor, HappyOpenSource

#72474 [SOT][3.13] Add `BlockStackItem`
  python/paddle/jit/sot/opcode_translator/executor/virtual_frame.py
Labels: contributor

#72515 [CI] Add cpu workflow bypass if
  .github/workflows/_Linux-CPU.yml
Labels: skip-ci: all

#72514 [CI] Add no_proxy for all yaml
  .github/workflows/_Coverage.yml
  .github/workflows/_Inference.yml
  .github/workflows/_Linux-CPU.yml
  .github/workflows/_Linux-XPU.yml
  .github/workflows/_SOT.yml
  ci/run_setup.sh
Labels: skip-ci: all

#72433 3.0.1 Windows cuda128
  cmake/tensorrt.cmake
  python/setup.py.in
  setup.py
Labels: skip-ci: approval, skip-ci: coverage

#72428 [CI]Add timeout exception prompt for auto_parallel ci
  tools/auto_parallel/ci_auto_parallel.sh
Labels: contributor

#72465 [CINN]Change flat_hash_map of absl to the flat_hash_map of paddle
  cmake/cinn/external/absl.cmake
  paddle/cinn/ast_gen_ius/tensor_group.cc
  paddle/cinn/ast_gen_ius/tensor_group.h
  paddle/cinn/backends/codegen_device_util.h
  paddle/cinn/backends/extern_func_emitter.h
  paddle/cinn/backends/function_prototype.cc
  paddle/cinn/backends/function_prototype.h
  paddle/cinn/backends/llvm/codegen_llvm.h
  paddle/cinn/backends/llvm/codegen_x86.cc
  paddle/cinn/backends/llvm/codegen_x86.h
  paddle/cinn/backends/llvm/llvm_intrin_rule.h
  paddle/cinn/common/context.h
  paddle/cinn/common/graph_utils.cc
  paddle/cinn/common/graph_utils.h
  paddle/cinn/common/info_registry.h
  paddle/cinn/common/integer_set.cc
  paddle/cinn/common/integer_set.h
  paddle/cinn/common/ir_util.cc
  paddle/cinn/common/ir_util.h
  paddle/cinn/hlir/framework/op.h
  paddle/cinn/hlir/framework/op_strategy.h
  paddle/cinn/hlir/framework/visualize_helper.cc
  paddle/cinn/hlir/framework/visualize_helper.h
  paddle/cinn/hlir/op/op_util.h
  paddle/cinn/hlir/op/transform.cc
  paddle/cinn/hlir/pe/ir_schedule_pe.cc
  paddle/cinn/hlir/pe/ir_schedule_pe.h
  paddle/cinn/hlir/pe/load_x86_params.cc
  paddle/cinn/hlir/pe/load_x86_params.h
  paddle/cinn/hlir/pe/nn.cc
  paddle/cinn/hlir/pe/schedule.cc
  paddle/cinn/hlir/pe/schedule.h
  paddle/cinn/hlir/pe/transform.cc
  paddle/cinn/hlir/pe/transform.h
  paddle/cinn/ir/group_schedule/config/group_tile_util.h
  paddle/cinn/ir/schedule/schedule_desc.cc
  paddle/cinn/ir/schedule/schedule_desc.h
  paddle/cinn/ir/tensor.h
  paddle/cinn/lang/lower_impl.cc
  paddle/cinn/lang/lower_impl.h
  paddle/cinn/lang/lower_tensor_group.h
  paddle/cinn/operator_fusion/pir_graph_analyzing/loop_axis_mapping.cc
  paddle/cinn/operator_fusion/pir_graph_analyzing/loop_transform_analysis.cc
  paddle/cinn/optim/ir_simplify.cc
  paddle/cinn/optim/longlong2int_pass.h
  paddle/cinn/optim/vectorize_for_trans.cc
  paddle/cinn/poly/poly_scheduler.cc
  paddle/cinn/poly/poly_scheduler.h
  paddle/cinn/poly/schedule.h
  paddle/cinn/poly/stage.h
  paddle/cinn/pybind/bind.h
  paddle/cinn/runtime/cuda/cuda_util.cc
  paddle/cinn/runtime/cuda/cuda_util.h
  paddle/cinn/utils/type_defs.h
  test/cpp/cinn/ast_gen_ius/tensor_group_test.cc
  test/cpp/cinn/hlir/pe/load_params_test.cc
Labels: contributor

#72509 [SOT][FasterGuard] refactor GuardNode
  paddle/fluid/pybind/jit.cc
  paddle/fluid/pybind/sot/guards.cc
  paddle/fluid/pybind/sot/guards.h
  python/paddle/jit/sot/opcode_translator/executor/variables/basic.py
  test/sot/test_faster_guard.py
Labels: contributor

#72528 [XPU] tanh support type of bfloat16
  paddle/phi/backends/xpu/xpu3_op_list.cc
  paddle/phi/kernels/xpu/activation_kernel.cc
Labels: XPU

#72547 [CI] XPU tar zstd
  .github/workflows/_Linux-XPU.yml
Labels: skip-ci: sot, skip-ci: approval, skip-ci: coverage, skip-ci: mac, skip-ci: inference

#72538 【Hackathon 8th No.3】del oldIR in auto_parallel_gradient_merge -part
  python/paddle/distributed/passes/__init__.py
  python/paddle/distributed/passes/auto_parallel_gradient_merge.py
Labels: PaddlePaddle Hackathon, contributor
