Repository PaddlePaddle/Paddle, pull requests merged in 2025-09, with the labels that each got.

#74994 [CppExtension] Extract get paddle include dirs logic to a common method
  python/paddle/base/core.py
  python/paddle/utils/cpp_extension/extension_utils.py
  test/auto_parallel/custom_op/utils.py
  test/auto_parallel/semi_auto_parallel_for_custom_relu.py
  test/auto_parallel/semi_auto_parallel_simple_net_custom_relu.py
  test/cpp_extension/cpp_extension_setup.py
  test/cpp_extension/test_cpp_extension_jit.py
  test/cpp_extension/utils.py
  test/custom_kernel/test_custom_kernel_load.py
  test/custom_op/utils.py
  test/custom_runtime/test_custom_op_setup.py
  test/deprecated/custom_op/utils.py
Labels: skip-ci: coverage

#75003 Fix eager python c code gen when sink api into c++
  paddle/fluid/eager/auto_code_generator/generator/python_c_gen.py
  paddle/fluid/pir/dialect/op_generator/python_c_gen.py
  paddle/phi/ops/yaml/ops.yaml
  paddle/phi/ops/yaml/python_api_info.yaml
  python/paddle/_paddle_docs.py
  python/paddle/tensor/linalg.py
  python/paddle/tensor/search.py
  test/legacy_test/test_arg_min_max_v2_op.py
Labels: skip-ci: coverage, skip-ci: static-check, skip-ci: api-benchmark

#75001 Fix eager python c code gen when sink api into c++
  paddle/fluid/eager/auto_code_generator/generator/python_c_gen.py
  paddle/fluid/pir/dialect/op_generator/python_c_gen.py
  paddle/phi/ops/yaml/ops.yaml
  paddle/phi/ops/yaml/python_api_info.yaml
  python/paddle/_paddle_docs.py
  python/paddle/tensor/linalg.py
  python/paddle/tensor/search.py
  test/legacy_test/test_arg_min_max_v2_op.py
Labels: skip-ci: coverage, skip-ci: static-check

#74850 【Hackathon 9th No.1】Add running_mean running_var check for batch_norm cpu kernel when needed
  paddle/phi/kernels/cpu/batch_norm_kernel.cc
  test/legacy_test/test_batch_norm_op.py
Labels: PaddlePaddle Hackathon, contributor

#74992 rename test_transpose_mkldnn_op test_transpose_onednn_op [fluid_ops]
  test/mkldnn/test_fill_constant_onednn_op.py
  test/mkldnn/test_fusion_lstm_bf16_onednn_op.py
  test/mkldnn/test_fusion_lstm_int8_onednn_op.py
  test/mkldnn/test_fusion_lstm_onednn_op.py
  test/mkldnn/test_pool2d_bf16_onednn_op.py
  test/mkldnn/test_pool2d_int8_onednn_op.py
  test/mkldnn/test_pool2d_onednn_op.py
  test/mkldnn/test_transpose_bf16_onednn_op.py
  test/mkldnn/test_transpose_int8_onednn_op.py
  test/mkldnn/test_transpose_onednn_op.py
  tools/parallel_UT_rule.py
  tools/static_mode_white_list.py
Labels: contributor, HappyOpenSource

#74863 【Hackathon 9th No.5】fix index_sample 0-size
  paddle/phi/kernels/gpu/index_sample_grad_kernel.cu
  paddle/phi/kernels/gpu/index_sample_kernel.cu
Labels: PaddlePaddle Hackathon, contributor

#75013 [API Compatibility][Doc] Add docstring for `Tensor.new_xxx`
  python/paddle/base/dygraph/math_op_patch.py
Labels: API Compatibility

#75034 remove INSTANTIATE_ISFINITE_KERNEL_Isnan NOLINT
  paddle/phi/kernels/cpu/isfinite_kernel.cc
  paddle/phi/kernels/gpu/isfinite_kernel.cu
  paddle/phi/kernels/isfinite_kernel.h
Labels: contributor, HappyOpenSource

#74924 rename test_fc_mkldnn_op test_fc_onednn_op [fluid_ops]
  test/mkldnn/CMakeLists.txt
  test/mkldnn/check_flags_onednn_ops_on_off.py
  test/mkldnn/test_elementwise_add_bf16_onednn_op.py
  test/mkldnn/test_elementwise_add_onednn_op.py
  test/mkldnn/test_elementwise_div_onednn_op.py
  test/mkldnn/test_elementwise_mul_bf16_onednn_op.py
  test/mkldnn/test_fc_bf16_onednn_op.py
  test/mkldnn/test_fc_int8_onednn_op.py
  test/mkldnn/test_fc_onednn_op.py
  test/mkldnn/test_flags_onednn_ops_on_off.py
  test/mkldnn/test_softplus_onednn_op.py
  tools/parallel_UT_rule.py
  tools/static_mode_white_list.py
  tools/windows/run_unittests.sh
Labels: contributor, HappyOpenSource

#75048 add safetensors Version dispatch
  python/paddle/framework/io.py
Labels: skip-ci: coverage

#75024 [CherryPick] Support customizable dataloader reader‘s buffersize #75023
  paddle/fluid/pybind/reader_py.cc
  python/paddle/io/dataloader/dataloader_iter.py
  python/paddle/io/reader.py
Labels: skip-ci: coverage

#75029 [XPU] update XPHC to 20250901
  cmake/external/xpu.cmake
Labels: XPU

#75021 Change VLOG level to 1 when missing kernel in static graph mode
  paddle/fluid/framework/operator.cc
Labels: skip-ci: coverage

#75008 Fix args mapper mechanism for sinking Python API into C++
  paddle/fluid/eager/auto_code_generator/generator/python_c_gen.py
  paddle/fluid/pybind/args_mapper.cc
  paddle/fluid/pybind/args_mapper.h
  paddle/phi/ops/yaml/python_api_info.yaml
  python/paddle/_paddle_docs.py
  python/paddle/tensor/search.py
  test/ir/pir/test_ir_pybind.py
  test/legacy_test/test_arg_min_max_v2_op.py
Labels: skip-ci: approval

#75039 [PHI] PyTorch aligned scatter reduce kernels for integer mean
  paddle/phi/kernels/funcs/gather_scatter_functor.cc
  paddle/phi/kernels/funcs/gather_scatter_functor.cu
  test/legacy_test/test_higher_dim_scatter.py
Labels: skip-ci: coverage

#75027 add paddle.Tensor.clamp and paddle.Tensor.itemsize
  python/paddle/base/dygraph/math_op_patch.py
  python/paddle/base/dygraph/tensor_patch_methods.py
  python/paddle/pir/math_op_patch.py
  python/paddle/tensor/__init__.py
  test/legacy_test/test_clip_op.py
  test/legacy_test/test_eager_tensor.py
  test/legacy_test/test_pir_tensor.py
Labels: API Compatibility

#74826 [Auto Parallel] Add co_shard spmd_rule for transpose
  paddle/phi/infermeta/spmd_rules/transpose.cc
  test/auto_parallel/end_to_end/test_e2e_co_shard.py
  test/auto_parallel/end_to_end/transpose_co_shard.py
  test/cpp/auto_parallel/CMakeLists.txt
  test/cpp/auto_parallel/transpose_co_shard_spmd_rule_test.cc
Labels: contributor

#75053 replace mkldnn_data_type in test_conv_onednn_nhwc
  test/cpp/fluid/mkldnn/test_conv_onednn_nhwc.cc
Labels: contributor, HappyOpenSource

#75033 [Cherry-Pick] [Bug fixes] fix _offload_tensors for RL Training
  python/paddle/distributed/fleet/meta_parallel/pipeline_parallel.py
Labels: skip-ci: coverage

#75066 replace mkldnn_data_type in test_reshape_bf16_op [fluid_ops]
  test/legacy_test/op_test.py
  test/mkldnn/test_reshape_bf16_op.py
Labels: contributor, HappyOpenSource

#75072 rename test_clip_mkldnn_op_deprecated [fluid_ops]
  test/deprecated/mkldnn/test_clip_onednn_op_deprecated.py
  test/deprecated/mkldnn/test_concat_onednn_op_deprecated.py
  test/deprecated/mkldnn/test_layer_norm_bf16_onednn_op_deprecated.py
  test/deprecated/mkldnn/test_layer_norm_onednn_op_deprecated.py
  test/deprecated/mkldnn/test_onednn_cpu_bfloat16_pass_deprecated.py
Labels: contributor, HappyOpenSource

#75043 [API compatibility] Add Tensor.is_cuda and paddle.Size
  python/paddle/__init__.py
  python/paddle/base/dygraph/tensor_patch_methods.py
  python/paddle/pir/math_op_patch.py
  python/paddle/tensor/size.py
  test/legacy_test/test_eager_tensor.py
  test/legacy_test/test_size.py
Labels: API Compatibility

#75037 [API Compatibility] add `stride` tensor method
  paddle/fluid/pybind/eager_method.cc
  paddle/fluid/pybind/pir.cc
  test/dygraph_to_static/test_tensor_methods.py
  test/legacy_test/test_eager_tensor.py
Labels: API Compatibility

#75112 replace mkldnn_data_type in test_onednn_quant_transpose_dequant_fuse_pass [fluid_ops]
  test/ir/inference/test_onednn_quant_transpose_dequant_fuse_pass.py
Labels: contributor, HappyOpenSource

#75113 replace mkldnn_data_type in test_mkldnn_int8_scale_calculation_pass [fluid_ops]
  test/ir/inference/test_mkldnn_int8_scale_calculation_pass.py
Labels: contributor, HappyOpenSource

#74611 [API Compatibility] Add prepend/with_kwargs/always_call for register_forward_pre_hook
  python/paddle/nn/layer/layers.py
  test/legacy_test/test_imperative_hook_for_layer.py
Labels: contributor, API Compatibility

#75135 use onednn_data_type in cpu_bfloat16_placement_pass_tester
  paddle/fluid/framework/ir/onednn/cpu_bfloat16_placement_pass.cc
  paddle/fluid/framework/ir/onednn/cpu_bfloat16_placement_pass.h
  paddle/fluid/framework/ir/onednn/cpu_bfloat16_placement_pass_tester.cc
Labels: contributor, HappyOpenSource

#75134 use onednn_data_type in cpu_quantize_placement_pass_tester
  paddle/fluid/framework/ir/onednn/cpu_quantize_placement_pass.cc
  paddle/fluid/framework/ir/onednn/cpu_quantize_placement_pass_tester.cc
Labels: contributor, HappyOpenSource

#75124 replace mkldnn_data_type in test/deprecated/mkldnn
  test/deprecated/mkldnn/test_clip_onednn_op_deprecated.py
  test/deprecated/mkldnn/test_concat_onednn_op_deprecated.py
  test/deprecated/mkldnn/test_prelu_onednn_op_deprecated.py
  test/deprecated/mkldnn/test_sum_onednn_op_deprecated.py
Labels: contributor, HappyOpenSource

#75130 [Infra] Refine some log message in distributed ci
  ci/auto_parallel/ci_case_unit.sh
  tools/auto_parallel/ci_case_unit.sh
Labels: contributor, HappyOpenSource

#74532 [Warning fix] fix warning for async_fast_garbage_collector.cc
  paddle/fluid/framework/new_executor/garbage_collector/async_fast_garbage_collector.cc
Labels: contributor, HappyOpenSource, skip-ci: approval, skip-ci: coverage

#74697 [API Compatiblity] Add `paddle.compat.slogdet`
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/unary_infer_sym.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/unary_infer_sym.h
  paddle/phi/infermeta/unary.cc
  paddle/phi/infermeta/unary.h
  paddle/phi/kernels/cpu/slogdeterminant_grad_kernel.cc
  paddle/phi/kernels/cpu/slogdeterminant_kernel.cc
  paddle/phi/kernels/elementwise_multiply_kernel.h
  paddle/phi/kernels/gpu/slogdeterminant_grad_kernel.cu
  paddle/phi/kernels/gpu/slogdeterminant_kernel.cu
  paddle/phi/kernels/impl/slogdeterminant_grad_kernel_impl.h
  paddle/phi/kernels/impl/slogdeterminant_kernel_impl.h
  paddle/phi/kernels/slogdeterminant_grad_kernel.h
  paddle/phi/kernels/slogdeterminant_kernel.h
  paddle/phi/ops/yaml/backward.yaml
  paddle/phi/ops/yaml/ops.yaml
  python/paddle/compat.py
  python/paddle/tensor/__init__.py
  python/paddle/tensor/compat.py
  test/compat/test_compat_warn.py
  test/legacy_test/test_compat_slogdet.py
  test/legacy_test/test_decorator.py
  test/legacy_test/test_zero_dim_sundry_dygraph_api.py
  test/legacy_test/test_zero_dim_sundry_static_api_part4.py
  test/xpu/test_zero_dim_tensor_xpu.py
Labels: skip-ci: coverage

#74812 【Hackathon 9th No.2】fix expand 0-size
  paddle/phi/kernels/gpu/expand_grad_kernel.cu
  paddle/phi/kernels/gpu/expand_kernel.cu
  python/paddle/tensor/manipulation.py
  test/legacy_test/test_expand_v2_op.py
Labels: PaddlePaddle Hackathon, contributor

#74890 remove include bfloat16.h in paddle/phi/kernels/cpu [fluid_ops]
  paddle/phi/kernels/cpu/activation_grad_kernel.cc
  paddle/phi/kernels/cpu/adamw_kernel.cc
  paddle/phi/kernels/cpu/broadcast_tensors_grad_kernel.cc
  paddle/phi/kernels/cpu/broadcast_tensors_kernel.cc
  paddle/phi/kernels/cpu/c_concat_kernel.cc
  paddle/phi/kernels/cpu/concat_grad_kernel.cc
  paddle/phi/kernels/cpu/concat_kernel.cc
  paddle/phi/kernels/cpu/contiguous_kernel.cc
  paddle/phi/kernels/cpu/debug_tools_kernel.cc
  paddle/phi/kernels/cpu/elementwise_add_kernel.cc
  paddle/phi/kernels/cpu/elementwise_divide_kernel.cc
  paddle/phi/kernels/cpu/elementwise_multiply_kernel.cc
  paddle/phi/kernels/cpu/elementwise_subtract_kernel.cc
  paddle/phi/kernels/cpu/erf_grad_kernel.cc
  paddle/phi/kernels/cpu/erf_kernel.cc
  paddle/phi/kernels/cpu/gather_grad_kernel.cc
  paddle/phi/kernels/cpu/gather_kernel.cc
  paddle/phi/kernels/cpu/index_elementwise_get_grad_kernel.cc
  paddle/phi/kernels/cpu/index_elementwise_get_kernel.cc
  paddle/phi/kernels/cpu/index_elementwise_put_grad_kernel.cc
  paddle/phi/kernels/cpu/index_elementwise_put_kernel.cc
  paddle/phi/kernels/cpu/lookup_table_grad_kernel.cc
  paddle/phi/kernels/cpu/lookup_table_kernel.cc
  paddle/phi/kernels/cpu/save_combine_kernel.cc
  paddle/phi/kernels/cpu/scale_kernel.cc
  paddle/phi/kernels/cpu/sign_kernel.cc
  paddle/phi/kernels/cpu/soft_relu_grad_kernel.cc
  paddle/phi/kernels/cpu/soft_relu_kernel.cc
  paddle/phi/kernels/cpu/split_kernel.cc
  paddle/phi/kernels/cpu/strided_copy_kernel.cc
  paddle/phi/kernels/cpu/transpose_grad_kernel.cc
  paddle/phi/kernels/cpu/transpose_kernel.cc
Labels: contributor, HappyOpenSource, skip-ci: approval

#75088 [API-Compat] paddle.gather inplace compatible upgrade
  python/paddle/tensor/manipulation.py
  test/legacy_test/test_gather_compatible.py
Labels: skip-ci: coverage

#74941 rename test_bilinear_interp_v2_mkldnn_op [fluid_ops]
  test/mkldnn/CMakeLists.txt
  test/mkldnn/test_activation_bf16_onednn_op.py
  test/mkldnn/test_bilinear_interp_v2_onednn_op.py
  test/mkldnn/test_cast_onednn_op.py
  test/mkldnn/test_dequantize_onednn_op.py
  test/mkldnn/test_flatten_onednn_op.py
  test/mkldnn/test_fusion_gru_bf16_onednn_op.py
  test/mkldnn/test_fusion_gru_int8_onednn_op.py
  test/mkldnn/test_fusion_gru_onednn_op.py
  test/mkldnn/test_gaussian_random_onednn_op.py
  test/mkldnn/test_quantize_onednn_op.py
  test/mkldnn/test_reduce_bf16_onednn_op.py
  test/mkldnn/test_scale_bf16_onednn_op.py
  test/mkldnn/test_shape_onednn_op.py
  test/mkldnn/test_slice_onednn_op.py
  test/mkldnn/test_squeeze2_onednn_op.py
  test/mkldnn/test_sum_bf16_onednn_op.py
  tools/parallel_UT_rule.py
  tools/static_mode_white_list.py
Labels: contributor, HappyOpenSource

#75141 【Hackathon 9th No.17、18】 Fix accuracy diff for conv2d_transpose API with NHWC format
  paddle/phi/kernels/funcs/im2col_cfo_cpu.h
  test/legacy_test/test_conv2d_transpose_op.py
Labels: PaddlePaddle Hackathon, contributor

#75136 [Auto Parallel] Refine co_shard e2e tests
  ci/auto_parallel/ci_case_unit.sh
  test/auto_parallel/end_to_end/CMakeLists.txt
  test/auto_parallel/end_to_end/reshape_co_shard.py
  test/auto_parallel/end_to_end/softmax_co_shard.py
  test/auto_parallel/end_to_end/test_e2e_co_shard_8cards.py
  test/auto_parallel/end_to_end/testslist.csv
  test/auto_parallel/end_to_end/transpose_co_shard.py
Labels: contributor

#75028 [API compatibility] Compatible with size properties and methods
  python/paddle/base/dygraph/math_op_patch.py
  test/legacy_test/test_size.py
  test/sot/test_18_tensor_method.py
Labels: API Compatibility

#75183 [API Compatibility] add `paddle.random.initial_seed`
  python/paddle/__init__.py
  python/paddle/random.py
  test/legacy_test/test_initial_seed.py
Labels: API Compatibility

#75249 [XPU] support bool datatype for fill_any op
  paddle/phi/backends/xpu/xpu2_op_list.cc
  paddle/phi/backends/xpu/xpu3_op_list.cc
Labels: XPU

#75277 [CodeStyle][Ruff] Bump ruff to v0.13.0, fix some `B017` - part 3
  .pre-commit-config.yaml
  pyproject.toml
  test/collective/fleet/test_distributed_strategy.py
  test/deprecated/legacy_test/test_fleet_base.py
  test/deprecated/legacy_test/test_fleet_util.py
  test/deprecated/legacy_test/test_prune_deprecated.py
  test/legacy_test/test_activation_op.py
  test/legacy_test/test_dot_op.py
  test/legacy_test/test_dot_op_0d.py
  test/legacy_test/test_identity_loss_op.py
  test/legacy_test/test_incubate_cross_entropy_with_softmax_bwd_w_downcast.py
  test/legacy_test/test_inner.py
  test/legacy_test/test_lu_unpack_op.py
  test/legacy_test/test_normalize.py
  test/legacy_test/test_outer.py
  test/legacy_test/test_pad3d_op.py
  test/legacy_test/test_sum_op.py
  test/xpu/test_pad3d_op_xpu.py
Labels: contributor, HappyOpenSource

#74860 【Hackathon 9th No.8】Fix 0-size for as_strided grad and add bound check for as_strided
  paddle/phi/kernels/stride/as_strided_grad_kernel.cc
  paddle/phi/kernels/stride/as_strided_kernel.cc
  test/legacy_test/test_as_strided.py
  test/legacy_test/test_narrow.py
Labels: PaddlePaddle Hackathon, contributor

#75188 [XPU] update xhpc to 20250909
  cmake/external/xpu.cmake
Labels: XPU, skip-ci: win-inference

#75171 rename test_mkldnn_conv_hard_sigmoid_fuse_pass [fluid_ops]
  test/ir/inference/CMakeLists.txt
  test/ir/inference/test_onednn_conv_hard_sigmoid_fuse_pass.py
  test/ir/inference/test_onednn_conv_hard_swish_fuse_pass.py
  tools/windows/run_unittests.sh
Labels: contributor, HappyOpenSource

#75275 【UnitTestFix No.11】fix test_stack_op
  test/legacy_test/test_stack_op.py
Labels: contributor, HappyOpenSource

#75075 Add 6 api to support flashinfer
  paddle/fluid/pybind/pybind.cc
  python/paddle/_C.py
  python/paddle/utils/cpp_extension/__init__.py
  python/paddle/utils/cpp_extension/cpp_extension.py
  test/compat/test__C_api.py
  test/compat/test_cpp_extension_api.py
Labels: skip-ci: coverage

#75215 add scatter commOp wwhen compiled with FlagCX
  cmake/third_party.cmake
  paddle/fluid/distributed/collective/process_group_bkcl.cc
  paddle/fluid/distributed/collective/process_group_bkcl.h
  paddle/phi/backends/dynload/flagcx.h
  paddle/phi/core/distributed/bkcl_comm_context.cc
  paddle/phi/core/distributed/bkcl_comm_context.h
  tools/flagcx/build_flagcx_xpu.sh
Labels: contributor

#75261 优化im2col_common索引计算
  paddle/phi/kernels/funcs/im2col_cfo_cpu.h
Labels: contributor, HappyOpenSource

#75179 [API Compatiblity] Sink sum to c
  paddle/fluid/pir/dialect/op_generator/python_c_gen.py
  paddle/fluid/pybind/arg_pre_process.cc
  paddle/fluid/pybind/arg_pre_process.h
  paddle/fluid/pybind/args_mapper.cc
  paddle/fluid/pybind/args_mapper.h
  paddle/phi/ops/yaml/python_api_info.yaml
  python/paddle/_paddle_docs.py
  python/paddle/tensor/math.py
  test/auto_parallel/hybrid_strategy/semi_auto_parallel_global_input.py
  test/auto_parallel/hybrid_strategy/semi_auto_parallel_multi_inputs.py
  test/auto_parallel/hybrid_strategy/test_semi_auto_parallel_global_input.py
  test/auto_parallel/hybrid_strategy/test_semi_auto_parallel_multi_inputs.py
  test/collective/fleet/static_model_parallel_by_col.py
  test/collective/fleet/static_model_parallel_by_row.py
  test/deprecated/legacy_test/CMakeLists.txt
  test/deprecated/legacy_test/test_inplace_addto_strategy_deprecated.py
  test/deprecated/legacy_test/test_instance_norm_op_deprecated.py
  test/deprecated/legacy_test/test_lookup_table_v2_op_deprecated.py
  test/deprecated/legacy_test/test_regularizer_api_deprecated.py
  test/deprecated/legacy_test/test_regularizer_deprecated.py
  test/deprecated/legacy_test/test_run_program_op_deprecated.py
  test/deprecated/legacy_test/test_set_value_op_deprecated.py
  test/deprecated/legacy_test/test_weight_normalization_deprecated.py
  test/deprecated/legacy_test/test_zero_dim_sundry_static_api_deprecated.py
  test/deprecated/mkldnn/test_softmax_onednn_op_deprecated.py
  test/deprecated/prim/composite_ops/CMakeLists.txt
  test/deprecated/prim/composite_ops/test_composite_batch_norm_grad_deprecated.py
  test/deprecated/prim/composite_ops/test_composite_mean_deprecated.py
  test/deprecated/prim/composite_ops/test_composite_mean_grad_deprecated.py
  test/deprecated/prim/composite_ops/test_composite_softmax_custom_vjp_deprecated.py
  test/deprecated/prim/composite_ops/test_composite_softmax_deprecated.py
  test/deprecated/prim/composite_ops/test_composite_softmax_grad_deprecated.py
  test/deprecated/prim/prim/flags/CMakeLists.txt
  test/deprecated/prim/prim/flags/test_prim_flags_case_deprecated.py
  test/deprecated/prim/prim/vjp/static/CMakeLists.txt
  test/deprecated/prim/prim/vjp/static/test_comp_sum_grad_deprecated.py
  test/ir/pir/test_ir_backward.py
  test/ir/pir/test_special_op_translator.py
  test/legacy_test/test_instance_norm_op.py
  test/legacy_test/test_instance_norm_op_v2.py
  test/legacy_test/test_reduce_op.py
  test/legacy_test/test_softmax_op.py
  test/legacy_test/test_sum_op.py
  test/prim/pir_prim/test_vjp_prim.py
  test/xpu/test_set_value_op_xpu.py
  tools/gen_pybind11_stub.py
  tools/xpu/disable_ut_xpu_kl3.local
Labels: skip-ci: distribute

#75330 Revert "update tensor_copy.cc"
  paddle/phi/api/lib/tensor_copy.cc
Labels: contributor

#75240 GLOG info management and support for exporting backward graphs of dynamic graph and call stack of GradNode
  paddle/common/flags.cc
  paddle/fluid/eager/accumulation/accumulation_node.cc
  paddle/fluid/eager/api/manual/eager_manual/forwards/add_n_fwd_func.cc
  paddle/fluid/eager/api/manual/eager_manual/forwards/conv2d_fwd_function.cc
  paddle/fluid/eager/api/manual/eager_manual/forwards/multiply_fwd_func.cc
  paddle/fluid/eager/api/manual/eager_manual/forwards/sync_batch_norm_fwd_func.cc
  paddle/fluid/eager/api/manual/eager_manual/nodes/add_n_node.cc
  paddle/fluid/eager/api/manual/eager_manual/nodes/conv2d_nodes.cc
  paddle/fluid/eager/api/manual/eager_manual/nodes/multiply_node.cc
  paddle/fluid/eager/api/manual/eager_manual/nodes/sync_batch_norm_node.cc
  paddle/fluid/eager/auto_code_generator/generator/eager_gen.py
  paddle/fluid/eager/backward.cc
  paddle/fluid/eager/backward.h
  paddle/fluid/eager/grad_node_info.cc
  paddle/fluid/eager/grad_node_info.h
  paddle/fluid/eager/grad_tensor_holder.cc
  paddle/fluid/eager/utils.cc
  paddle/fluid/eager/utils.h
  paddle/fluid/imperative/amp_auto_cast.cc
  paddle/fluid/imperative/layout_autotune.cc
  paddle/fluid/inference/analysis/dot.h
  paddle/fluid/platform/init.cc
  paddle/fluid/pybind/eager_functions.cc
  paddle/fluid/pybind/eager_utils.cc
  paddle/fluid/pybind/global_value_getter_setter.cc
  paddle/fluid/pybind/imperative.cc
  paddle/fluid/pybind/pybind.cc
  paddle/phi/api/generator/api_base.py
  paddle/phi/api/generator/api_gen.py
  paddle/phi/api/generator/dist_api_gen.py
  paddle/phi/backends/dynload/dynamic_loader.cc
  paddle/phi/backends/gpu/gpu_launch_config.h
  paddle/phi/core/generator.cc
  paddle/phi/core/kernel_factory.cc
  paddle/phi/core/memory/allocation/allocator_facade.cc
  paddle/phi/core/memory/allocation/auto_growth_best_fit_allocator.cc
  paddle/phi/core/memory/allocation/mmap_allocator.cc
  paddle/phi/core/memory/memcpy.cc
  paddle/phi/core/tensor_utils.cc
  paddle/phi/kernels/funcs/dims_simplifier.h
  python/paddle/autograd/backward_mode.py
  python/paddle/base/dygraph/base.py
  python/paddle/base/dygraph/tensor_patch_methods.py
  python/paddle/utils/download.py
  test/legacy_test/test_backward_dump_debug_info.py
Labels: skip-ci: coverage, skip-ci: distribute

#75030 [API compatibility] Added trunc_divide kernel
  paddle/fluid/eager/auto_code_generator/generator/eager_gen.py
  paddle/fluid/pir/dialect/op_generator/api_gen.py
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/element_wise_binary.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/element_wise_binary.h
  paddle/phi/common/type_promotion.h
  paddle/phi/infermeta/spmd_rules/rules.cc
  paddle/phi/kernels/cpu/elementwise_kernel.cc
  paddle/phi/kernels/elementwise_kernel.h
  paddle/phi/kernels/funcs/elementwise_functor.h
  paddle/phi/kernels/kps/elementwise_kernel.cu
  paddle/phi/ops/yaml/ops.yaml
  python/paddle/tensor/math.py
  test/legacy_test/test_div_op.py
Labels: API Compatibility

#75352 Disable XPU PaddleX test
  .github/workflows/_Linux-XPU.yml
Labels: skip-ci: all

#75173 [Distributed] Refine pipeline detail messages
  python/paddle/distributed/fleet/meta_parallel/pipeline_parallel.py
Labels: skip-ci: coverage

#75345 fix unused ElementType
  paddle/phi/infermeta/nullary.cc
Labels: contributor, HappyOpenSource

#75303 format test_index_sample_op.py
  test/legacy_test/test_index_sample_op.py
Labels: contributor, HappyOpenSource

#75231 clean CUDA version 11.0 notes
  python/paddle/sparse/binary.py
  python/paddle/sparse/multiary.py
Labels: contributor, HappyOpenSource

#75050 [Auto Parallel] Add co_shard spmd_rule for index_select
  paddle/phi/infermeta/spmd_rules/index_select.cc
  paddle/phi/infermeta/spmd_rules/spmd_rule_macro_define.h
  test/auto_parallel/end_to_end/index_select_co_shard.py
  test/auto_parallel/end_to_end/test_e2e_co_shard_8cards.py
  test/cpp/auto_parallel/CMakeLists.txt
  test/cpp/auto_parallel/index_select_co_shard_spmd_rule_test.cc
Labels: contributor

#75289 【UnitTestFix No.20】fix test_pyramid_hash_op.py
  test/legacy_test/test_pyramid_hash_op.py
Labels: contributor, HappyOpenSource, skip-ci: slice

#75332 2nd-batch-03-函数原型与定义返回类型不匹配
  paddle/fluid/inference/capi/pd_config.cc
Labels: contributor, Beijing Innovation Consortium

#75339 2nd-batch-11-未使用的局部变量
  test/auto_parallel/reshard_p_to_r_cross_mesh.py
Labels: contributor, Beijing Innovation Consortium

#75327 fix typos
  paddle/common/performance_statistician.cc
  python/paddle/profiler/profiler_statistic.py
  python/paddle/sparse/nn/functional/conv.py
  test/legacy_test/test_multi_dot_op.py
Labels: contributor, HappyOpenSource

#75375 add bypass
  .github/workflows/Warning.yml
Labels: skip-ci: warning

#75340 2nd-batch-12-越界访问和资源泄漏
  paddle/utils/small_vector.h
Labels: contributor, Beijing Innovation Consortium

#75310 [CMake4] Set cmake_policy CMP0026 to New
  CMakeLists.txt
  cmake/generic.cmake
Labels: contributor, HappyOpenSource

#75305 [CMake4] fix cmake CMP0153 warning when with_cpu in windows
  cmake/FindNumPy.cmake
  cmake/cinn/system.cmake
  cmake/external/protobuf.cmake
  cmake/system.cmake
Labels: contributor, HappyOpenSource

#75346 [CMake4] Add `CMAKE_POLICY_VERSION_MINIMUM=3.5` to some third_party (linux cpu)
  CMakeLists.txt
  cmake/external/cryptopp.cmake
  cmake/external/gflags.cmake
  cmake/external/glog.cmake
  cmake/external/gloo.cmake
  cmake/external/onednn.cmake
  cmake/external/utf8proc.cmake
  cmake/external/warpctc.cmake
  cmake/external/warprnnt.cmake
  cmake/external/xbyak.cmake
Labels: contributor, HappyOpenSource

#75301 [CodeStyle][Ruff] fix some `noqa: B017`
  test/deprecated/legacy_test/test_fleet_base.py
  test/deprecated/legacy_test/test_fleet_util.py
  test/deprecated/legacy_test/test_prune_deprecated.py
Labels: contributor, HappyOpenSource

#75282 【FlexCheckpoint】Upgrade some macros and optimize load_state_dict communication
  python/paddle/distributed/fleet/meta_optimizers/dygraph_optimizer/dygraph_sharding_optimizer.py
  python/paddle/distributed/flex_checkpoint/aoa/aoa_engine.py
  python/paddle/distributed/flex_checkpoint/aoa/macros.py
  python/paddle/distributed/flex_checkpoint/dcp/load_state_dict.py
  python/paddle/distributed/flex_checkpoint/dcp/save_state_dict.py
  python/paddle/optimizer/adamw.py
  test/auto_parallel/hybrid_strategy/semi_auto_load_state_dict.py
  test/flex_checkpoint/test_macros.py
Labels: skip-ci: distribute

#75236 fix comparison warning in add_norm_fuse_pass.cc
  paddle/fluid/pir/transforms/gpu/add_norm_fuse_pass.cc
Labels: contributor, HappyOpenSource

#75274 【UnitTestFix No.10】fix test_normal.py
  test/legacy_test/test_normal.py
Labels: contributor, HappyOpenSource

#75428 [CMake4] Adapt some inference demos and tests
  cmake/coverallsGcovJsons.cmake
  paddle/fluid/inference/api/demo_ci/CMakeLists.txt
  test/cpp/inference/infer_ut/CMakeLists.txt
  test/cpp/inference/infer_ut/external-cmake/gtest-cpp.cmake
Labels: contributor, HappyOpenSource

#75263 remove check cuda >= 10.0
  paddle/phi/kernels/funcs/multihead_matmul_functor.cu
  paddle/phi/kernels/fusion/gpu/multihead_matmul_kernel.cu
  paddle/phi/kernels/fusion/gpu/skip_layernorm_kernel.cu
Labels: contributor, HappyOpenSource

#75439 2nd-batch-24-修复函数命名和预期语义
  paddle/cinn/ir/intrinsic_ops.h
Labels: contributor, Beijing Innovation Consortium

#75453 2nd-batch-42to43-代码执行流逻辑错误
  paddle/phi/api/lib/api_gen_utils.cc
  paddle/phi/api/lib/kernel_dispatch.h
Labels: contributor, Beijing Innovation Consortium

#75479 add include nvtx3/nvToolxExt.h
  paddle/phi/backends/dynload/nvtx.h
Labels: contributor, HappyOpenSource

#75233 Update README_cn.md
  README_cn.md
Labels: contributor, skip-ci: all

#75232 Update README.md
  README.md
Labels: contributor, skip-ci: all

#75438 修复fix_any.h在cpplint上的报错
  paddle/utils/any.h
Labels: contributor, Beijing Innovation Consortium

#75395 【UnitTestFix No.9】: Fix test_memcpy_op unittest error and support PIR API compatibility
  test/legacy_test/test_memcpy_op.py
Labels: contributor, HappyOpenSource

#75342 Add 7 api under paddle.cuda
  python/paddle/cuda/__init__.py
  test/compat/test_paddle_cuda_apis.py
Labels: skip-ci: coverage

#74603 Fix dtype api en doc
  python/paddle/base/executor.py
  python/paddle/distributed/auto_parallel/api.py
  python/paddle/framework/dtype.py
  python/paddle/sparse/creation.py
  python/paddle/tensor/creation.py
  python/paddle/tensor/manipulation.py
  python/paddle/tensor/random.py
Labels: skip-ci: coverage, skip-ci: win-inference, API Compatibility

#75455 [Compat] Unified some cuda/device apis
  python/paddle/cuda/__init__.py
  python/paddle/device/__init__.py
  python/paddle/device/cpu_device.py
  python/paddle/device/cuda/__init__.py
  python/paddle/device/custom_device.py
  python/paddle/device/xpu/__init__.py
  test/compat/test_device_apis.py
  test/compat/test_get_device_module.py
  test/legacy_test/test_cuda_unittest.py
Labels: skip-ci: coverage

#75487 Replace deprecated `paddle.dataset.uci_housing` with `paddle.text.datasets.UCIHousing` in unittests
  test/legacy_test/test_adadelta_op.py
  test/legacy_test/test_adam_optimizer_fp32_fp64.py
  test/legacy_test/test_momentum_op.py
  test/legacy_test/test_network_with_dtype.py
  test/legacy_test/test_rmsprop_op.py
Labels: contributor, HappyOpenSource

#75348 Add nigth coverage
  .github/workflows/Night_ALL_Coverage.yml
  ci/coverage_all_info.sh
  ci/utils.sh
Labels: skip-ci: all

#75490 update disable_ut_xpu_kl3.local
  tools/xpu/disable_ut_xpu_kl3.local
Labels: contributor, HappyOpenSource

#75334 2nd-batch-04\05\06\07-去除无用死代码
  python/paddle/distributed/launch/utils/etcd_client.py
  test/ir/inference/test_map_matmul_v2_to_mul_pass.py
  test/legacy_test/test_lr_scheduler.py
  test/ps/static_gpubox_trainer.py
Labels: contributor, Beijing Innovation Consortium

#75378 [SOT] Avoid skip adding shape alias caused by #73509
  python/paddle/jit/dy2static/utils.py
  python/paddle/jit/sot/opcode_translator/executor/variables/basic.py
Labels: skip-ci: win-inference

#75498 3rd-batch-01-未显式检查是否包含有效张量
  paddle/phi/kernels/xpu/deformable_conv_kernel.cc
Labels: contributor, Beijing Innovation Consortium

#75500 [API compatibility] add _cur_sdpa_kernel_backends for testing
  python/paddle/nn/attention/__init__.py
  test/legacy_test/test_sdpa_kernel.py
Labels: API Compatibility

#75450 2nd-batch-37-修复报错信息问题
  paddle/ap/include/axpr/string_method_class.h
  paddle/ap/include/code_module/api_wrapper_project_maker.h
Labels: contributor, Beijing Innovation Consortium

#75510 rename mkldnn in test/cpp/inference/infer_ut
  test/cpp/inference/infer_ut/README.md
  test/cpp/inference/infer_ut/run.sh
  test/cpp/inference/infer_ut/test_ernie_text_cls.cc
  test/cpp/inference/infer_ut/test_ppyolo_mbv3.cc
  test/cpp/inference/infer_ut/test_ppyolov2_r50vd.cc
Labels: contributor, HappyOpenSource

#75445 2nd-batch-34-满足哈希函数的一致性要求
  paddle/ap/include/axpr/data_value.h
Labels: contributor, Beijing Innovation Consortium

#75532 【CUDA Kernel No.6】fused_layernorm_kernel修复 -part
  paddle/phi/kernels/fused_layernorm_kernel.h
  paddle/phi/kernels/fusion/gpu/fused_layernorm_kernel.cu
  paddle/phi/kernels/fusion/xpu/fused_layernorm_kernel.cc
Labels: contributor, HappyOpenSource

#75538 【CUDA Kernel No.9】fused_softmax_mask_grad算子Kernel修复 -part
  paddle/phi/kernels/fused_softmax_mask_grad_kernel.h
  paddle/phi/kernels/fusion/cpu/fused_softmax_mask_grad_kernel.cc
  paddle/phi/kernels/fusion/gpu/fused_softmax_mask_grad_kernel.cu
  paddle/phi/kernels/fusion/xpu/fused_softmax_mask_grad_kernel.cc
Labels: contributor, HappyOpenSource

#75542 【CUDA Kernel No.18】skip_layernorm算子Kernel修复 -part
  paddle/phi/kernels/fusion/gpu/skip_layernorm_kernel.cu
  paddle/phi/kernels/fusion/gpu/skip_layernorm_kernel.h
Labels: contributor, HappyOpenSource

#75545 【CUDA Kernel No.20】affine_channel算子Kernel修复 -part
  paddle/phi/kernels/affine_channel_kernel.h
  paddle/phi/kernels/cpu/affine_channel_kernel.cc
  paddle/phi/kernels/gpu/affine_channel_kernel.cu
  paddle/phi/kernels/xpu/affine_channel_kernel.cc
Labels: contributor, HappyOpenSource

#75541 【CUDA Kernel No.15】fusion_group算子Kernel修复 -part
  paddle/phi/kernels/fusion/gpu/fusion_group_kernel.cu
  paddle/phi/kernels/fusion/gpu/fusion_group_kernel.h
Labels: contributor, HappyOpenSource

#75539 【CUDA Kernel No.13】fused_transpose_split_quant算子Kernel修复 -part
  paddle/phi/kernels/fusion/gpu/fused_transpose_split_quant_kernel.cu
  paddle/phi/kernels/fusion/gpu/fused_transpose_split_quant_kernel.h
Labels: contributor, HappyOpenSource

#75477 Modified allocation type in kernels to support custom device
  paddle/phi/kernels/cpu/batch_fc_kernel.cc
  paddle/phi/kernels/cpu/correlation_kernel.cc
  paddle/phi/kernels/cpu/soft_relu_grad_kernel.cc
  paddle/phi/kernels/cpu/soft_relu_kernel.cc
  paddle/phi/kernels/fusion/gpu/distributed_fused_lamb_init_kernel.cu
  paddle/phi/kernels/gpu/correlation_kernel.cu
  paddle/phi/kernels/gpu/dgc_kernel.cu
  paddle/phi/kernels/gpu/shuffle_batch_kernel.cu
  paddle/phi/kernels/impl/merged_momentum_impl.h
  paddle/phi/kernels/impl/momentum_kernel_impl.h
Labels: skip-ci: coverage

#75501 [Metax] fix 'python/paddle/base/framework.py/_get_paddle_place' api bug
  paddle/phi/kernels/funcs/multi_tensor_apply.h
  python/paddle/base/framework.py
Labels: contributor, skip-ci: coverage

#75521 fix typo WARPCTC_PATHCH_ROCM_COMMAND WARPCTC_PATCH_ROCM_COMMAND
  cmake/external/warpctc.cmake
Labels: contributor, HappyOpenSource

#75413 handle_missing_edge_cases_in_fc
  python/paddle/distributed/flex_checkpoint/dcp/load_state_dict.py
Labels: contributor, skip-ci: win-inference

#75527 [Docathon][Fix Doc Format No.5、6] Fix example code format in `paddle.linalg.lu_solve` and `paddle.tensor_split`
  python/paddle/tensor/linalg.py
  python/paddle/tensor/manipulation.py
Labels: contributor, HappyOpenSource, skip-ci: all

#75440 2nd-batch-25-修复条件判断的语法错误
  paddle/cinn/ir/ir_analyzer/data_dependency_graph.cc
Labels: contributor, Beijing Innovation Consortium

#75513 update check_py_version
  CMakeLists.txt
  cmake/python_module.cmake
Labels: contributor, HappyOpenSource

#75519 3rd-batch-08-函数语义错误导致提前结束
  paddle/fluid/pir/dialect/distributed/ir/dist_tools.cc
Labels: contributor, Beijing Innovation Consortium

#75575 rename mkldnn to onednn in test/cpp/inference/
  test/cpp/inference/api/analyzer_bfloat16_image_classification_tester.cc
  test/cpp/inference/api/analyzer_quant_image_classification_tester.cc
Labels: contributor, HappyOpenSource

#75586 replace paddle.incubate.optimizer.lbfgs
  test/legacy_test/test_lbfgs_class.py
Labels: contributor, HappyOpenSource

#75595 rename mkldnn to onednn in tools directory
  tools/final_ut_parallel_rule.py
  tools/parallel_UT_rule.py
  tools/static_mode_white_list.py
Labels: contributor, HappyOpenSource

#75581 【CUDA Kernel No.108】soft_relu_grad算子Kernel修复 -part
  paddle/phi/kernels/cpu/soft_relu_grad_kernel.cc
  paddle/phi/kernels/gpu/soft_relu_grad_kernel.cu
  paddle/phi/kernels/soft_relu_grad_kernel.h
Labels: contributor, HappyOpenSource

#75494 【UnitTestFix No.2】test_adam_op 单测 优化
  test/legacy_test/test_adam_op.py
Labels: contributor, HappyOpenSource

#75599 rename mkldnn to onednn in test/quantization
  test/quantization/quant2_int8_image_classification_comparison.py
  test/quantization/quant2_int8_lstm_model.py
  test/quantization/quant2_int8_nlp_comparison.py
  test/quantization/quant_int8_image_classification_comparison.py
Labels: contributor, HappyOpenSource

#75578 【CUDA Kernel No.104】sequence_expand算子Kernel修复 -part
  paddle/phi/kernels/cpu/sequence_expand_kernel.cc
  paddle/phi/kernels/gpu/sequence_expand_kernel.cu
  paddle/phi/kernels/sequence_expand_kernel.h
Labels: contributor, HappyOpenSource

#75607 Fix moe_permute and moe_unpermute INT32 overflow error
  paddle/phi/kernels/gpu/moe_permute_kernel.cu
  paddle/phi/kernels/gpu/moe_unpermute_kernel.cu
Labels: skip-ci: template

#75554 【CUDA Kernel No.101】row_conv_grad算子Kernel修复 -part
  paddle/phi/kernels/cpu/row_conv_grad_kernel.cc
  paddle/phi/kernels/gpu/row_conv_grad_kernel.cu
  paddle/phi/kernels/row_conv_grad_kernel.h
Labels: contributor, HappyOpenSource

#75601 【CUDA Kernel No.3 】fused_bias_dropout_residual_layer_norm_grad_kernel算子Kernel修复 -part
  paddle/phi/kernels/fusion/gpu/fused_bias_dropout_residual_layer_norm_grad_kernel.cu
  paddle/phi/kernels/fusion/gpu/fused_bias_dropout_residual_layer_norm_grad_kernel.h
Labels: contributor, HappyOpenSource

#75562 【CUDA Kernel No.102】row_conv算子Kernel修复 -part
  paddle/phi/kernels/cpu/row_conv_kernel.cc
  paddle/phi/kernels/gpu/row_conv_kernel.cu
  paddle/phi/kernels/row_conv_kernel.h
Labels: contributor, HappyOpenSource
