Repository PaddlePaddle/Paddle, pull requests merged in 2025-07, with the labels that each got.

#73570 [0-size Tensor No.43、131] Add 0-size Tensor support for paddle.diag/masked_fill
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/unary_infer_sym.cc
  paddle/phi/infermeta/unary.cc
  paddle/phi/kernels/cpu/diag_grad_kernel.cc
  paddle/phi/kernels/cpu/diag_kernel.cc
  paddle/phi/kernels/cpu/masked_fill_grad_kernel.cc
  paddle/phi/kernels/cpu/masked_fill_kernel.cc
  paddle/phi/kernels/gpu/diag_grad_kernel.cu
  paddle/phi/kernels/gpu/diag_kernel.cu
  paddle/phi/kernels/gpu/masked_fill_grad_kernel.cu
  paddle/phi/kernels/gpu/masked_fill_kernel.cu
  paddle/phi/kernels/xpu/diag_kernel.cc
  test/legacy_test/test_diag_v2.py
  test/legacy_test/test_masked_fill.py
Labels: contributor, HappyOpenSource Pro

#73488 paddle_new_group2ncclCommInitRankConfigMemOpt
  paddle/fluid/distributed/collective/process_group_nccl.cc
  paddle/fluid/distributed/collective/process_group_nccl.h
  paddle/fluid/framework/distributed_strategy.proto
  paddle/fluid/pybind/communication.cc
  paddle/fluid/pybind/communication.h
  paddle/fluid/pybind/distributed_py.cc
  paddle/fluid/pybind/pybind.cc
  paddle/phi/backends/dynload/nccl.h
  paddle/phi/backends/dynload/rccl.h
  paddle/phi/core/distributed/CMakeLists.txt
  paddle/phi/core/distributed/comm_context_manager.cc
  paddle/phi/core/distributed/comm_context_manager.h
  paddle/phi/core/distributed/nccl_comm_context.cc
  paddle/phi/core/distributed/nccl_comm_context.h
  paddle/phi/core/distributed/nccl_config.cc
  paddle/phi/core/distributed/nccl_config.h
  python/paddle/distributed/__init__.py
  python/paddle/distributed/collective.py
  python/paddle/distributed/fleet/base/topology.py
  python/paddle/distributed/fleet/fleet.py
  python/paddle/distributed/fleet/meta_parallel/parallel_layers/pp_layers.py
  python/paddle/distributed/parallel.py
  test/collective/CMakeLists.txt
  test/collective/new_api_per_op_and_group_intranode.py
  test/collective/test_new_api_per_op_and_group_intranode.sh
  test/collective/testslist.csv
Labels: skip-ci: coverage

#73752 fix compile failed with WITH_NV_JETSON Flag
  paddle/phi/kernels/funcs/pooling.cu
Labels: contributor, HappyOpenSource

#73486 [Auto Parallel] Add spmd rule No.15 for index_put and index_put_grad ops.
  paddle/phi/infermeta/spmd_rules/index_put.cc
  paddle/phi/infermeta/spmd_rules/index_put.h
  paddle/phi/infermeta/spmd_rules/rules.cc
  paddle/phi/infermeta/spmd_rules/rules.h
  paddle/phi/ops/yaml/backward.yaml
  paddle/phi/ops/yaml/ops.yaml
  test/cpp/auto_parallel/spmd_rule_test.cc
Labels: contributor, HappyOpenSource Pro, skip-ci: approval

#73739 [Accuracy diff No.125] Fix accuracy diff for paddle.nn.functional.multi_margin_loss API
  python/paddle/nn/functional/loss.py
  test/legacy_test/test_multimarginloss.py
Labels: contributor, HappyOpenSource Pro

#73715 [0-size Tensor No.12、71] Add 0-size Tensor support for paddle.frac
  test/legacy_test/test_complex_view_op.py
  test/legacy_test/test_frac_api.py
Labels: contributor, HappyOpenSource Pro

#73723 get_places adds string_format parameter
  test/legacy_test/op_test.py
  test/legacy_test/test_adadelta_op.py
Labels: contributor, HappyOpenSource

#73728 Replace some op_test.get_places() - part5
  test/legacy_test/test_activation_nn_grad.py
  test/legacy_test/test_batch_norm_op_v2.py
  test/legacy_test/test_nn_matmul_v2_grad.py
  test/legacy_test/test_sum_op.py
  test/legacy_test/test_unfold_op.py
Labels: contributor, HappyOpenSource

#73631 修复macOS-x64在使用-DONNXRUNTIME=ON时编译失败的问题
  cmake/flags.cmake
Labels: contributor, HappyOpenSource

#73726 Replace some op_test.get_places() - part3
  test/legacy_test/test_batch_norm_op.py
  test/legacy_test/test_complex_reshape.py
  test/legacy_test/test_complex_trace_layer.py
  test/legacy_test/test_i0_op.py
  test/legacy_test/test_imperative_hook_for_layer.py
  test/legacy_test/test_lu_solve_op.py
  test/legacy_test/test_max_op.py
  test/legacy_test/test_nn_sigmoid_op.py
  test/legacy_test/test_slice_scatter.py
  test/legacy_test/test_top_k_v2_op.py
Labels: contributor, HappyOpenSource

#73738 Fix argsort bug to solve Big Tensor Problem: paddle.nanquantile
  paddle/phi/kernels/gpu/argsort_kernel.cu
Labels: contributor

#73594 [0-size Tensor Job2 No.75] Add 0-size Tensor support for paddle.shard_index
  paddle/phi/kernels/cpu/shard_index_kernel.cc
  paddle/phi/kernels/gpu/shard_index_kernel.cu
  test/legacy_test/test_shard_index_op.py
Labels: contributor, HappyOpenSource Pro

#73783 [LOG] Print watcher exception info
  python/paddle/distributed/launch/controllers/watcher.py
Labels: skip-ci: coverage

#73776 [0-size Tensor No.117] Add 0-size Tensor support for paddle.linalg.svd_lowrank
  python/paddle/tensor/linalg.py
  test/legacy_test/test_svd_lowrank.py
Labels: contributor

#73724 Fix typos infermation information[fluid_ops]
  paddle/fluid/pybind/manual_static_op_function.h
  paddle/fluid/pybind/pir.cc
  paddle/fluid/pybind/pybind.cc
Labels: contributor, HappyOpenSource

#73727 Replace some op_test.get_places() - part4
  test/legacy_test/test_alpha_dropout.py
  test/legacy_test/test_atan2_op.py
  test/legacy_test/test_dropout_op.py
  test/legacy_test/test_linalg_pinv_op.py
  test/legacy_test/test_lrn_op.py
  test/legacy_test/test_momentum_op.py
  test/legacy_test/test_sigmoid_focal_loss.py
  test/legacy_test/test_sign_op.py
  test/legacy_test/test_triangular_solve_op.py
Labels: contributor, HappyOpenSource

#73721 Replace some op_test.get_places() - part1
  test/legacy_test/test_fill_constant_op.py
  test/legacy_test/test_lamb_op.py
  test/legacy_test/test_uniform_random_op.py
Labels: contributor, HappyOpenSource

#72882 [Auto Parallel] Add spmd rule No.18 for conv3d and conv3d_grad ops.
  paddle/phi/infermeta/spmd_rules/conv3d.cc
  paddle/phi/infermeta/spmd_rules/conv3d.h
  paddle/phi/infermeta/spmd_rules/rules.cc
  paddle/phi/infermeta/spmd_rules/rules.h
  paddle/phi/ops/yaml/backward.yaml
  paddle/phi/ops/yaml/ops.yaml
  test/auto_parallel/spmd_rules/CMakeLists.txt
  test/auto_parallel/spmd_rules/test_conv3d_rule.py
Labels: contributor, HappyOpenSource Pro

#73690 support fp8 quant in sharding optimizer
  paddle/fluid/pybind/eager_method.cc
  python/paddle/distributed/fleet/meta_optimizers/dygraph_optimizer/dygraph_sharding_optimizer.py
  python/paddle/distributed/fleet/utils/tensor_fusion_helper.py
Labels: skip-ci: coverage

#73735 【auto parallel】fix cp ut
  python/paddle/distributed/auto_parallel/intermediate/tensor_parallel.py
  python/paddle/distributed/auto_parallel/ring_attention.py
  test/auto_parallel/hybrid_strategy/CMakeLists.txt
  test/auto_parallel/hybrid_strategy/test_parallel_api_with_llama_2d_sep.py
  test/auto_parallel/hybrid_strategy/testslist.csv
Labels: skip-ci: coverage

#73788 Replace some op_test.get_places() - part9
  test/legacy_test/test_group_norm_op_v2.py
  test/legacy_test/test_instance_norm_op.py
  test/legacy_test/test_instance_norm_op_v2.py
  test/legacy_test/test_layer_norm_op_v2.py
Labels: contributor, HappyOpenSource

#73794 update test_solve_op.py
  test/legacy_test/test_solve_op.py
Labels: contributor, HappyOpenSource

#73808 [XPU] support zero dim tensor in concat_grad.
  paddle/phi/kernels/xpu/concat_grad_kernel.cc
  test/xpu/test_concat_op_xpu.py
Labels: XPU

#73803 Optimize fused_act_dequant op by remove redundant memset
  paddle/phi/kernels/fusion/gpu/fused_act_dequant_kernel.cu
Labels: skip-ci: coverage

#73757 [Dy2St] Move output creation behind of kernel launch and skip allocation creation
  paddle/cinn/hlir/dialect/operator/transforms/lowering_pass/lower_cinn_fusion_op_pass.cc
  paddle/fluid/eager/to_static/run_program_func.cc
  paddle/fluid/eager/to_static/run_program_func.h
  paddle/fluid/eager/to_static/run_program_impl.cc
  paddle/fluid/eager/to_static/run_program_impl.h
  paddle/fluid/eager/to_static/run_program_node.cc
  paddle/fluid/framework/executor_cache.h
  paddle/fluid/pybind/eager_custom_python_api.h
  paddle/fluid/pybind/eager_utils.cc
  paddle/fluid/pybind/op_function_common.cc
  python/paddle/jit/dy2static/pir_partial_program.py
Labels: skip-ci: coverage

#72986 [0-size Tensor No.302] Add 0-size Tensor support for expand_as [fluid_ops]
  paddle/phi/kernels/gpu/expand_as_grad_kernel.cu
  paddle/phi/kernels/gpu/expand_as_kernel.cu
  paddle/phi/kernels/impl/expand_as_grad_kernel_impl.h
  paddle/phi/kernels/impl/expand_as_kernel_impl.h
  paddle/phi/kernels/xpu/expand_as_kernel.cc
  test/legacy_test/test_expand_as_v2_op.py
  test/legacy_test/test_solve_op.py
Labels: contributor

#73812 Rename ctx to dev_ctx in elementwise_grad_base.h [fluid_ops]
  paddle/phi/kernels/funcs/elementwise_grad_base.h
Labels: contributor, HappyOpenSource

#73827 Rename ctx to dev_ctx in elementwise_base.h
  paddle/phi/kernels/funcs/elementwise_base.h
Labels: contributor, HappyOpenSource

#73839 Replace some op_test.get_places() - part10
  test/legacy_test/test_adagrad_op.py
  test/legacy_test/test_adam_op.py
  test/legacy_test/test_adaptive_avg_pool1d.py
  test/legacy_test/test_as_strided.py
  test/legacy_test/test_index_select_strided.py
  test/legacy_test/test_momentum_op.py
  test/legacy_test/test_rmsprop_op.py
  test/legacy_test/test_tensor_fill_.py
  test/legacy_test/test_tensor_to_list.py
  test/legacy_test/test_tensor_to_numpy.py
  test/legacy_test/test_tensor_unfold.py
  test/legacy_test/test_tensor_zero_.py
Labels: contributor, HappyOpenSource

#73841 Rename ctx to dev_ctx in paddle/phi/kernels/funcs/blas/
  paddle/phi/kernels/funcs/blas/blas.h
  paddle/phi/kernels/funcs/blas/blas_impl.cu.h
  paddle/phi/kernels/funcs/blas/blas_impl.hip.h
  paddle/phi/kernels/funcs/blas/blaslt_impl.cu.h
  paddle/phi/kernels/funcs/blas/blaslt_impl.hip.h
Labels: contributor, HappyOpenSource, skip-ci: approval

#73857 Add value check for chunk
  python/paddle/tensor/manipulation.py
  test/legacy_test/test_chunk_op.py
Labels: contributor, HappyOpenSource

#73762 [ILUVATAR_GPU] Update for compiling CUDAExtension for iluvatar
  paddle/common/backend_header.h
  paddle/utils/flat_hash_map.h
  python/paddle/utils/cpp_extension/cpp_extension.py
  python/paddle/utils/cpp_extension/extension_utils.py
Labels: contributor, skip-ci: coverage

#73717 [Auto-parallel] Fix sharding all_gather overlap in auto_dy
  python/paddle/distributed/auto_parallel/api.py
  test/auto_parallel/semi_auto_parallel_sharding_stage_1.py
Labels: skip-ci: approval, skip-ci: coverage

#73297 remove extra comm context after init
  paddle/phi/api/generator/dist_api_gen.py
  test/collective/CMakeLists.txt
  test/collective/test_comm_group_num.py
  test/collective/test_comm_group_num.sh
  test/collective/testslist.csv
Labels: contributor

#73855 [0-size Tensor Job2 No.56] Add 0-size Tensor support for paddle.nn.functional.dice_loss[fluid_ops]
  python/paddle/nn/functional/loss.py
  test/legacy_test/test_nn_dice_loss.py
Labels: contributor, HappyOpenSource Pro

#73884 add ut for paddle.view api in low dtype to high dtype
  test/legacy_test/test_stride.py
Labels: contributor

#73790 Fix op_test.py to support use_onednn config [fluid_ops]
  test/legacy_test/op_test.py
  test/mkldnn/test_conv3d_mkldnn_op.py
Labels: contributor, HappyOpenSource

#73763 Aff Fp8 moe fusion ops
  paddle/phi/infermeta/ternary.cc
  paddle/phi/infermeta/ternary.h
  paddle/phi/kernels/CMakeLists.txt
  paddle/phi/kernels/legacy/gpu/moe_gate_dispatch_and_quant_kernel.cu
  paddle/phi/kernels/legacy/gpu/moe_gate_dispatch_kernel.cu
  paddle/phi/kernels/legacy/gpu/moe_gate_dispatch_permute_kernel.cu
  paddle/phi/kernels/legacy/gpu/moe_ops_utils.h
  paddle/phi/ops/yaml/ops.yaml
  python/paddle/incubate/nn/functional/__init__.py
  python/paddle/incubate/nn/functional/moe_gate_dispatch_and_quant.py
  test/legacy_test/CMakeLists.txt
  test/legacy_test/test_incubate_moe_gate_dispatch_and_quant.py
Labels: skip-ci: coverage

#73873 Revert "add FLAGS_paddle_grad_inputs_zero_copy, support paddle.grad zero copy…"
  paddle/common/flags.cc
  paddle/fluid/eager/backward.cc
Labels: skip-ci: approval

#73744 [AutoParallel] remove sharding fuse flags
  python/paddle/distributed/auto_parallel/api.py
  test/auto_parallel/semi_auto_parallel_sharding_stage_1.py
Labels: skip-ci: coverage

#73897 【dygraph】add pylayer forward call_stack
  paddle/fluid/eager/auto_code_generator/generator/eager_gen.py
  paddle/fluid/eager/pylayer/py_layer_node.cc
  paddle/fluid/pybind/eager_py_layer.cc
Labels: skip-ci: coverage

#73899 [Phi] Fix einsum kernel for big tensor
  paddle/phi/infermeta/unary.cc
  paddle/phi/kernels/impl/einsum_grad_kernel_impl.h
  paddle/phi/kernels/impl/einsum_kernel_impl.h
  paddle/phi/kernels/impl/tile_grad_kernel_impl.h
Labels: contributor

#73896 [SOT] Update plain dataclass
  python/paddle/jit/dy2static/utils.py
  test/sot/test_dataclass.py
Labels: skip-ci: coverage

#73821 [0-size Tensor No.205] Add 0-size Tensor support for pad [fluid_ops]
  paddle/phi/kernels/cpu/pad3d_grad_kernel.cc
  paddle/phi/kernels/cpu/pad3d_kernel.cc
  paddle/phi/kernels/gpu/pad3d_grad_kernel.cu
  paddle/phi/kernels/gpu/pad3d_kernel.cu
  paddle/phi/kernels/impl/pad_grad_kernel_impl.h
  paddle/phi/kernels/impl/pad_kernel_impl.h
  paddle/phi/kernels/xpu/pad3d_grad_kernel.cc
  paddle/phi/kernels/xpu/pad3d_kernel.cc
  paddle/phi/kernels/xpu/pad_grad_kernel.cc
  paddle/phi/kernels/xpu/pad_kernel.cc
  python/paddle/nn/functional/common.py
  test/legacy_test/test_pad3d_op.py
  test/legacy_test/test_pad_op.py
  test/xpu/test_pad3d_op_xpu.py
Labels: contributor, HappyOpenSource Pro

#73820 [Inference] use MmapStorage to speedup the model file load in safetensors
  paddle/fluid/pybind/pybind.cc
  python/paddle/__init__.py
  python/paddle/tensor/__init__.py
  python/paddle/tensor/creation.py
  test/legacy_test/test_mmap_storage.py
Labels: contributor

#73538 新增MultiLabelMarginLoss
  python/paddle/nn/__init__.py
  python/paddle/nn/functional/__init__.py
  python/paddle/nn/functional/loss.py
  python/paddle/nn/layer/__init__.py
  python/paddle/nn/layer/loss.py
  test/legacy_test/test_multilabelmarginloss.py
Labels: contributor

#73905 Rename use_mkldnn to use_onednn in test cases - part5
  test/mkldnn/test_gaussian_random_mkldnn_op.py
  test/mkldnn/test_matmul_v2_mkldnn_op.py
  test/mkldnn/test_mul_int8_mkldnn_op.py
  test/mkldnn/test_nearest_interp_v2_mkldnn_op.py
  test/mkldnn/test_pool2d_bf16_mkldnn_op.py
  test/mkldnn/test_pool2d_mkldnn_op.py
Labels: contributor, HappyOpenSource

#73903 Rename use_mkldnn to use_onednn in test cases - part3
  test/mkldnn/test_softmax_bf16_mkldnn_op.py
Labels: contributor, HappyOpenSource

#73902 Rename use_mkldnn to use_onednn in test cases - part2
  test/mkldnn/test_sum_bf16_mkldnn_op.py
Labels: contributor, HappyOpenSource

#73900 Rename use_mkldnn to use_onednn in test cases - part1
  test/mkldnn/test_transpose_bf16_mkldnn_op.py
  test/mkldnn/test_transpose_int8_mkldnn_op.py
  test/mkldnn/test_transpose_mkldnn_op.py
Labels: contributor, HappyOpenSource

#73840 Rename ctx to dev_ctx in paddle/phi/kernels/funcs/detection/
  paddle/phi/kernels/funcs/detection/bbox_util.cu.h
  paddle/phi/kernels/funcs/detection/bbox_util.h
  paddle/phi/kernels/funcs/detection/nms_util.h
Labels: contributor, HappyOpenSource

#73826 Rename ctx to dev_ctx in gather.cu.h
  paddle/phi/kernels/funcs/gather.cu.h
  paddle/phi/kernels/funcs/scatter.cu.h
  paddle/phi/kernels/funcs/search_compute.h
Labels: contributor, HappyOpenSource

#73825 Rename context to dev_ctx in paddle/phi/kernels/gpu
  paddle/phi/kernels/gpu/adagrad_kernel.cu
  paddle/phi/kernels/gpu/depthwise_conv.h
  paddle/phi/kernels/gpu/expand_as_grad_kernel.cu
  paddle/phi/kernels/gpu/sequence_expand_grad_kernel.cu
  paddle/phi/kernels/gpu/sequence_expand_kernel.cu
  paddle/phi/kernels/gpu/sequence_softmax_grad_kernel.cu
  paddle/phi/kernels/gpu/sequence_softmax_kernel.cu
  paddle/phi/kernels/gpu/unique_consecutive_functor.h
  paddle/phi/kernels/gpu/unique_kernel.cu
Labels: contributor, HappyOpenSource

#73889 [0-size Tensor Job2 No.76] Add 0-size Tensor support for paddle.slice_scatter [fluid_ops]
  paddle/phi/kernels/gpu/set_value_kernel.cu
  paddle/phi/kernels/impl/set_value_grad_kernel_impl.h
  paddle/phi/kernels/impl/set_value_kernel_impl.h
  paddle/phi/kernels/xpu/set_value_grad_kernel.cc
  paddle/phi/kernels/xpu/set_value_kernel.cc
  test/legacy_test/test_slice_scatter.py
Labels: contributor, HappyOpenSource Pro

#73898 [0-size Tensor Job2 No.57] Add 0-size Tensor support for paddle.nn.functional.embedding
  python/paddle/nn/functional/input.py
  test/legacy_test/test_lookup_table_v2_op.py
Labels: contributor, HappyOpenSource Pro

#73733 [AutoParallel] addd sync param dynamic
  python/paddle/distributed/auto_parallel/pipelining/schedules.py
  python/paddle/distributed/auto_parallel/pipelining/stage.py
  test/auto_parallel/CMakeLists.txt
  test/auto_parallel/pipeline_sync_shared_parameters_unittest.py
  test/auto_parallel/test_pipeline_sync_shared_parameters.py
Labels: skip-ci: coverage

#73616 [0-size Tensor No.31、293] Add 0-size Tensor support for chunk
  test/legacy_test/test_chunk_op.py
Labels: contributor

#73931 [Dataloader] Fix _DataLoaderIterMultiProcess/_DataLoaderIterSingleProcess has no attribute 'shudown'
  python/paddle/io/dataloader/dataloader_iter.py
Labels: skip-ci: coverage

#73977 [CI] ce whl to self-hosted
  .github/workflows/_CE-Framework.yml
Labels: skip-ci: sot, skip-ci: approval, skip-ci: coverage, skip-ci: mac, skip-ci: xpu, skip-ci: inference, skip-ci: distribute, skip-ci: static-check, skip-ci: cpu, skip-ci: npu, skip-ci: ce-cinn-framework, skip-ci: api-benchmark, skip-ci: ce-infer, skip-ci: ce-test, skip-ci: auto-parallel, skip: dcu

#74001 [CodeStyle][yamlfmt] Bump `google-yamlfmt` to version 0.17.2
  .github/workflows/check-bypass.yml
  .pre-commit-config.yaml
Labels: contributor, skip-ci: all

#73934 [SOT] Add env for specialized dim numbers
  paddle/fluid/pybind/jit.cc
  paddle/fluid/pybind/sot/guards.cc
  paddle/fluid/pybind/sot/guards.h
  python/paddle/jit/sot/infer_meta.py
  python/paddle/jit/sot/opcode_translator/executor/variables/basic.py
  python/paddle/jit/sot/opcode_translator/executor/variables/callable.py
  python/paddle/jit/sot/utils/__init__.py
  python/paddle/jit/sot/utils/envs.py
  python/paddle/jit/sot/utils/utils.py
  test/sot/test_faster_guard.py
  test/sot/test_sot_dynamic_shape.py
Labels: skip-ci: xpu, skip-ci: dcu

#73947 Rename MKLDNN to ONEDNN in test/deprecated/mkldnn
  test/deprecated/mkldnn/test_activation_mkldnn_op_deprecated.py
  test/deprecated/mkldnn/test_layer_norm_bf16_mkldnn_op_deprecated.py
  test/deprecated/mkldnn/test_layer_norm_mkldnn_op_deprecated.py
  test/deprecated/mkldnn/test_mkldnn_cpu_bfloat16_pass_deprecated.py
  test/deprecated/mkldnn/test_mkldnn_matmul_op_output_fuse_pass_deprecated.py
  test/deprecated/mkldnn/test_softmax_mkldnn_op_deprecated.py
  test/deprecated/mkldnn/test_sum_mkldnn_op_deprecated.py
Labels: contributor, HappyOpenSource

#73920 【slice】remove eigen for Set value grad
  paddle/phi/kernels/gpu/set_value_grad_kernel.cu
  paddle/phi/kernels/impl/set_value_grad_kernel_impl.h
  paddle/phi/kernels/impl/set_value_kernel_impl.h
Labels: skip-ci: dcu

#74031 [CI] windows inference onnxruntime
  .github/workflows/_Windows-Inference.yml
Labels: skip-ci: all

#73971 [slice]support different shape case for GPUScatterAdd op
  paddle/fluid/pybind/eager_method.cc
  paddle/phi/backends/gpu/gpu_primitives.h
  paddle/phi/kernels/funcs/scatter.cu.h
  paddle/phi/kernels/funcs/stride_utils.h
  paddle/phi/kernels/gpu/gather_grad_kernel.cu
Labels: skip-ci: win-openblas

#73918 Bind get stream method to python for deep_ep
  paddle/fluid/distributed/collective/deep_ep/event.hpp
  paddle/fluid/distributed/collective/deep_ep/src/event.cc
  paddle/fluid/pybind/deep_ep_api.cc
  python/paddle/distributed/communication/deep_ep/__init__.py
  python/paddle/distributed/communication/deep_ep/utils.py
  python/paddle/distributed/fleet/meta_parallel/dualpipev.py
Labels: skip-ci: coverage

#73882 [0-size Tensor No.156] Add 0-size Tensor support for paddle.nn.functional. binary_cross_entropy_with_logits [fluid_ops]
  paddle/phi/kernels/xpu/sigmoid_cross_entropy_with_logits_grad_kernel.cc
  paddle/phi/kernels/xpu/sigmoid_cross_entropy_with_logits_kernel.cc
  test/legacy_test/test_binary_cross_entropy_with_logits_op.py
Labels: contributor, HappyOpenSource Pro

#73962 [0-size Tensor No.18、42、51、83] Add 0-size Tensor support for hessian、cumulative_trapezoid、einsum、fused_feedforward API.
  paddle/phi/infermeta/unary.cc
  paddle/phi/kernels/fusion/gpu/fused_feedforward_grad_kernel.cu
  paddle/phi/kernels/fusion/gpu/fused_feedforward_kernel.cu
  paddle/phi/kernels/impl/einsum_grad_kernel_impl.h
  paddle/phi/kernels/impl/einsum_kernel_impl.h
  test/legacy_test/test_cumulative_trapezoid.py
  test/legacy_test/test_einsum.py
  test/legacy_test/test_fused_feedforward_op.py
Labels: skip-ci: coverage

#73998 [0-size Tensor No.188、231] Add 0-size Tensor support for paddle.nn.functional.local_response_norm
  python/paddle/nn/functional/loss.py
  test/legacy_test/test_lrn_op.py
  test/legacy_test/test_triplet_margin_with_distance_loss.py
Labels: contributor, HappyOpenSource Pro

#73830 Fix FusedLayerNormInferMeta different signedness warning
  paddle/phi/infermeta/multiary.cc
Labels: contributor, HappyOpenSource

#73944 Rename use_mkldnn to use_onednn in test cases - part11
  test/mkldnn/test_concat_bf16_mkldnn_op.py
  test/mkldnn/test_concat_int8_mkldnn_op.py
  test/mkldnn/test_conv2d_bf16_mkldnn_op.py
  test/mkldnn/test_conv2d_int8_mkldnn_op.py
Labels: contributor, HappyOpenSource

#73949 Rename context to dev_ctx in paddle/phi/kernels/funcs [fluid_ops]
  paddle/phi/kernels/funcs/batch_norm_utils.h
  paddle/phi/kernels/funcs/detail/gru_cpu_kernel.h
  paddle/phi/kernels/funcs/detail/lstm_cpu_kernel.h
  paddle/phi/kernels/funcs/detail/lstm_gpu_kernel.h
  paddle/phi/kernels/funcs/diagonal.h
  paddle/phi/kernels/funcs/gru_compute.cc
  paddle/phi/kernels/funcs/gru_compute.cu
  paddle/phi/kernels/funcs/gru_compute.h
  paddle/phi/kernels/funcs/im2col.cc
  paddle/phi/kernels/funcs/im2col.cu
  paddle/phi/kernels/funcs/im2col.h
  paddle/phi/kernels/funcs/layer_norm_util.h
  paddle/phi/kernels/funcs/lstm_compute.cc
  paddle/phi/kernels/funcs/lstm_compute.cu
  paddle/phi/kernels/funcs/lstm_compute.h
  paddle/phi/kernels/funcs/math/beam_search.cc
  paddle/phi/kernels/funcs/math/beam_search.cu
  paddle/phi/kernels/funcs/math/beam_search.h
  paddle/phi/kernels/funcs/math/beam_search_xpu.cc
  paddle/phi/kernels/funcs/matrix_solve.cu
  paddle/phi/kernels/funcs/matrix_solve.h
  paddle/phi/kernels/funcs/multihead_matmul_functor.cu
  paddle/phi/kernels/funcs/padding.h
  paddle/phi/kernels/funcs/selected_rows_functor.cc
  paddle/phi/kernels/funcs/selected_rows_functor.cu
  paddle/phi/kernels/funcs/selected_rows_functor.h
  paddle/phi/kernels/funcs/sequence2batch.cc
  paddle/phi/kernels/funcs/sequence2batch.cu
  paddle/phi/kernels/funcs/sequence2batch.h
  paddle/phi/kernels/funcs/sequence_padding.cc
  paddle/phi/kernels/funcs/sequence_padding.cu
  paddle/phi/kernels/funcs/sequence_padding.h
  paddle/phi/kernels/funcs/sequence_pooling.cc
  paddle/phi/kernels/funcs/sequence_pooling.cu
  paddle/phi/kernels/funcs/sequence_pooling.h
  paddle/phi/kernels/funcs/sequence_scale.cc
  paddle/phi/kernels/funcs/sequence_scale.cu
  paddle/phi/kernels/funcs/sequence_scale.h
  paddle/phi/kernels/funcs/softmax.cu
  paddle/phi/kernels/funcs/softmax.h
  paddle/phi/kernels/funcs/softmax_impl.h
  paddle/phi/kernels/funcs/vol2col.cu
Labels: contributor, HappyOpenSource, skip-ci: approval

#73945 Rename use_mkldnn to use_onednn in test cases - part12
  test/legacy_test/test_elementwise_mul_op.py
  test/mkldnn/test_elementwise_mul_onednn_op.py
Labels: contributor, HappyOpenSource, skip-ci: approval

#74009 [Accuracy diff No.153] Fix accuracy diff for paddle.vision.ops.deform_conv2d API
  python/paddle/vision/ops.py
  test/legacy_test/test_deformable_conv_op.py
Labels: contributor, HappyOpenSource Pro

#73961 Enable bf16 cast for iluvatar_gpu and metax_gpu
  python/paddle/distributed/fleet/meta_optimizers/dygraph_optimizer/hybrid_parallel_optimizer.py
Labels: skip-ci: coverage

#73885 [PHI] Support complex for `paddle.linalg.lu`
  paddle/phi/backends/dynload/lapack.h
  paddle/phi/kernels/cpu/lu_grad_kernel.cc
  paddle/phi/kernels/cpu/lu_kernel.cc
  paddle/phi/kernels/funcs/lapack/lapack_function.cc
  paddle/phi/kernels/gpu/lu_grad_kernel.cu
  paddle/phi/kernels/gpu/lu_kernel.cu
  python/paddle/tensor/linalg.py
  test/legacy_test/test_lu_op.py
Labels: skip-ci: coverage

#73349 Fix eigh UPLO parameter
  python/paddle/tensor/linalg.py
Labels: contributor, HappyOpenSource

#73969 Rename use_mkldnn to use_onednn in test cases - part14
  test/deprecated/mkldnn/test_activation_mkldnn_op_deprecated.py
  test/deprecated/mkldnn/test_layer_norm_mkldnn_op_deprecated.py
  test/deprecated/mkldnn/test_reduce_mkldnn_op_deprecated.py
  test/deprecated/mkldnn/test_requantize_mkldnn_op_deprecated.py
  test/deprecated/mkldnn/test_scale_mkldnn_op_deprecated.py
  test/deprecated/mkldnn/test_softmax_mkldnn_op_deprecated.py
  test/deprecated/mkldnn/test_sum_mkldnn_op_deprecated.py
  test/mkldnn/onednn_op_test.py
  test/mkldnn/test_batch_norm_mkldnn_op.py
  test/mkldnn/test_conv2d_mkldnn_op.py
  test/mkldnn/test_conv2d_transpose_bf16_mkldnn_op.py
  test/mkldnn/test_fusion_gru_bf16_mkldnn_op.py
  test/mkldnn/test_matmul_bf16_mkldnn_op.py
  test/mkldnn/test_transpose_int8_mkldnn_op.py
Labels: contributor, HappyOpenSource

#74006 [0-size Tensor Job2 No.29、28] Add 0-size Tensor support for paddle.incubate.nn.functional.fused_multi_head_attention [fluid_ops]
  paddle/phi/kernels/fusion/gpu/fused_attention_grad_kernel.cu
  paddle/phi/kernels/fusion/gpu/fused_attention_kernel.cu
  paddle/phi/kernels/fusion/gpu/fused_gemm_epilogue_grad_kernel.cu
  test/legacy_test/test_fused_attention_op.py
  test/legacy_test/test_fused_gemm_epilogue_op.py
Labels: contributor, HappyOpenSource Pro, skip-ci: approval

#74069 [CodeStyle] Revert yamlfmt to `v0.16.0`
  .pre-commit-config.yaml
Labels: skip-ci: all

#73948 Rename context to dev_ctx in expand_as_grad_kernel_impl.h [fluid_ops]
  paddle/phi/backends/gpu/gpu_launch_config.h
  paddle/phi/kernels/impl/expand_as_grad_kernel_impl.h
  paddle/phi/kernels/impl/expand_as_kernel_impl.h
  paddle/phi/kernels/xpu/expand_as_kernel.cc
Labels: contributor, HappyOpenSource

#74064 Replace 25 with phi::DDim::kMaxRank
  paddle/phi/kernels/cpu/index_elementwise_get_grad_kernel.cc
  paddle/phi/kernels/cpu/index_elementwise_put_grad_kernel.cc
  paddle/phi/kernels/cpu/index_elementwise_put_kernel.cc
  paddle/phi/kernels/gpu/index_elementwise_get_grad_kernel.cu
  paddle/phi/kernels/gpu/index_elementwise_put_grad_kernel.cu
  paddle/phi/kernels/gpu/index_elementwise_put_kernel.cu
Labels: skip-ci: coverage

#74025 [PHI] remove rint op_compat
  paddle/phi/ops/yaml/op_compat.yaml
  test/ir/pir/cinn/test_cinn_fused_rms_norm.py
Labels: skip-ci: approval, skip-ci: static-check

#73753 [AutoParallel] Add einsum spmd rules
  paddle/phi/infermeta/spmd_rules/einsum.cc
  paddle/phi/infermeta/spmd_rules/einsum.h
  paddle/phi/infermeta/spmd_rules/rules.cc
  paddle/phi/infermeta/spmd_rules/rules.h
  paddle/phi/ops/yaml/inconsistent/dygraph_backward.yaml
  paddle/phi/ops/yaml/inconsistent/dygraph_ops.yaml
  test/auto_parallel/spmd_rules/CMakeLists.txt
  test/auto_parallel/spmd_rules/test_einsum_rule.py
Labels: contributor

#74072 [0-size Tensor No.165、218] Add 0-size Tensor support for paddle.nn.functional.cosine_similarity [fluid_ops]
  python/paddle/nn/functional/common.py
  test/legacy_test/test_cosine_similarity_api.py
  test/legacy_test/test_sigmoid_focal_loss.py
Labels: contributor, HappyOpenSource Pro

#74022 [0-size Tensor No.89、86] Add 0-size Tensor support for paddle.incubate.softmax_mask_fuse [fluid_ops]
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/multiary_infer_sym.cc
  paddle/phi/infermeta/multiary.cc
  paddle/phi/kernels/fusion/gpu/fused_softmax_mask_grad_kernel.cu
  paddle/phi/kernels/fusion/gpu/fused_softmax_mask_kernel.cu
  paddle/phi/kernels/gpu/rms_norm_grad_kernel.cu
  paddle/phi/kernels/gpu/rms_norm_kernel.cu
  paddle/phi/kernels/xpu/rms_norm_grad_kernel.cc
  paddle/phi/kernels/xpu/rms_norm_kernel.cc
  python/paddle/incubate/operators/softmax_mask_fuse.py
  test/legacy_test/test_rms_norm_op.py
  test/legacy_test/test_softmax_mask_fuse_op.py
Labels: contributor, HappyOpenSource Pro, skip-ci: approval

#74062 [API]Fix histogramdd accuracy for big tensor
  python/paddle/tensor/linalg.py
Labels: skip-ci: coverage

#73673 [ILUVATAR_GPU] Support iluvatar device.
  paddle/phi/infermeta/unary.cc
  python/paddle/nn/functional/flash_attention.py
Labels: contributor, skip-ci: coverage

#73936 [PHI] Optimize List/Combined Slice Performance
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/same_operands_result.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/same_operands_result.h
  paddle/fluid/pybind/eager_method.cc
  paddle/fluid/pybind/slice_utils.h
  paddle/phi/infermeta/backward.cc
  paddle/phi/infermeta/backward.h
  paddle/phi/infermeta/binary.cc
  paddle/phi/infermeta/binary.h
  paddle/phi/kernels/cpu/index_elementwise_get_grad_kernel.cc
  paddle/phi/kernels/cpu/index_elementwise_get_kernel.cc
  paddle/phi/kernels/cpu/index_elementwise_put_grad_kernel.cc
  paddle/phi/kernels/cpu/index_elementwise_put_kernel.cc
  paddle/phi/kernels/funcs/index_elementwise.cu.h
  paddle/phi/kernels/funcs/stride_utils.h
  paddle/phi/kernels/gpu/index_elementwise_get_grad_kernel.cu
  paddle/phi/kernels/gpu/index_elementwise_get_kernel.cu
  paddle/phi/kernels/gpu/index_elementwise_put_grad_kernel.cu
  paddle/phi/kernels/gpu/index_elementwise_put_kernel.cu
  paddle/phi/kernels/index_elementwise_put_grad_kernel.h
  paddle/phi/kernels/index_elementwise_put_kernel.h
  paddle/phi/ops/yaml/backward.yaml
  paddle/phi/ops/yaml/ops.yaml
  python/paddle/base/dygraph/tensor_patch_methods.py
Labels: contributor, skip-ci: coverage

#73933 [0-size Tensor Job2 No.72-74] Add 0-size Tensor support for paddle.scatter [fluid_ops]
  paddle/phi/infermeta/ternary.cc
  paddle/phi/kernels/cpu/scatter_grad_kernel.cc
  paddle/phi/kernels/cpu/scatter_kernel.cc
  paddle/phi/kernels/cpu/scatter_nd_add_grad_kernel.cc
  paddle/phi/kernels/cpu/scatter_nd_add_kernel.cc
  paddle/phi/kernels/gpu/scatter_grad_kernel.cu
  paddle/phi/kernels/gpu/scatter_kernel.cu
  paddle/phi/kernels/gpu/scatter_nd_add_grad_kernel.cu
  paddle/phi/kernels/gpu/scatter_nd_add_kernel.cu
  paddle/phi/kernels/xpu/scatter_grad_kernel.cc
  paddle/phi/kernels/xpu/scatter_kernel.cc
  paddle/phi/kernels/xpu/scatter_nd_add_grad_kernel.cc
  paddle/phi/kernels/xpu/scatter_nd_add_kernel.cc
  python/paddle/tensor/manipulation.py
  test/legacy_test/test_scatter_nd_op.py
  test/legacy_test/test_scatter_op.py
Labels: contributor, HappyOpenSource Pro, skip-ci: approval

#73218 Rename ctx to dev_ctx in paddle/phi/kernels/ - part [fluid_ops]
  paddle/phi/kernels/cpu/index_elementwise_get_grad_kernel.cc
  paddle/phi/kernels/cpu/index_elementwise_get_kernel.cc
  paddle/phi/kernels/fusion/gpu/fused_dropout_common.h
  paddle/phi/kernels/gpu/elementwise_grad.h
  paddle/phi/kernels/gpu/flash_attn_utils.h
  paddle/phi/kernels/gpu/index_elementwise_get_grad_kernel.cu
  paddle/phi/kernels/gpu/index_elementwise_get_kernel.cu
  paddle/phi/kernels/kps/compare_kernel.cu
  paddle/phi/kernels/onednn/add_n_kernel.cc
  paddle/phi/kernels/onednn/cast_kernel.cc
  paddle/phi/kernels/onednn/concat_kernel.cc
  paddle/phi/kernels/onednn/interpolate_kernel.cc
  paddle/phi/kernels/onednn/pad3d_kernel.cc
  paddle/phi/kernels/onednn/pool_grad_kernel.cc
  paddle/phi/kernels/onednn/pool_kernel.cc
  paddle/phi/kernels/onednn/sgd_kernel.cc
  paddle/phi/kernels/onednn/slice_grad_kernel.cc
  paddle/phi/kernels/onednn/split_kernel.cc
  paddle/phi/kernels/reduce_kernel_impl.cc
  paddle/phi/kernels/xpu/as_complex_kernel.cc
  paddle/phi/kernels/xpu/as_real_kernel.cc
  paddle/phi/kernels/xpu/fft_grad_kernel.cc
  paddle/phi/kernels/xpu/fft_kernel.cc
  paddle/phi/kernels/xpu/flash_attn_kernel.cc
Labels: contributor, HappyOpenSource, skip-ci: approval

#74042 [0-size Tensor No.166、257] Add 0-size Tensor support for paddle.nn.functional.ctc_loss [fluid_ops]
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/multiary_infer_sym.cc
  paddle/phi/infermeta/multiary.cc
  python/paddle/signal.py
  test/legacy_test/test_signal.py
  test/legacy_test/test_warpctc_op.py
Labels: contributor, HappyOpenSource Pro

#73688 [0-size Tensor No.204] Add 0-size Tensor support for paddle.nn.functional.normalize
  test/legacy_test/test_norm_op.py
Labels: contributor, HappyOpenSource Pro

#73997 [AutoParallel]fix fuse flag bug
  python/paddle/distributed/auto_parallel/api.py
  test/auto_parallel/semi_auto_parallel_sharding_stage_1.py
Labels: skip-ci: coverage, skip-ci: distribute

#73844 [0-size Tensor Job2 No.96] Add 0-size Tensor support for reshape
  paddle/phi/kernels/onednn/reshape_grad_kernel.cc
  paddle/phi/kernels/onednn/reshape_kernel.cc
  paddle/phi/kernels/reshape_grad_kernel.cc
  test/legacy_test/test_reshape_op.py
Labels: skip-ci: coverage

#74107 Custom Device Memory Status Api Support
  python/paddle/device/cuda/__init__.py
Labels: skip-ci: coverage

#74132 Replace context to dev_ctx in paddle/phi/kernels/funcs/pooling.cu
  paddle/phi/kernels/funcs/pooling.cu
  paddle/phi/kernels/xpu/concat_and_split_functor.cc
Labels: contributor, HappyOpenSource

#73189 [XPU] support python memory api in XPU
  paddle/fluid/pybind/pybind.cc
  paddle/phi/backends/xpu/xpu_info.cc
  paddle/phi/backends/xpu/xpu_info.h
  paddle/phi/core/platform/device/xpu/xpu_info.cc
  paddle/phi/core/platform/device/xpu/xpu_info.h
  python/paddle/device/xpu/__init__.py
  python/paddle/distributed/launch/utils/nvsmi.py
  test/xpu/test_xpu_device_count.py
  test/xpu/test_xpu_max_memory_allocated.py
  test/xpu/test_xpu_max_memory_reserved.py
  test/xpu/test_xpu_memory_allocated.py
  test/xpu/test_xpu_memory_reserved.py
  test/xpu/test_xpu_memory_total.py
  test/xpu/test_xpu_memory_used.py
  test/xpu/test_xpu_reset_max_memory_allocated.py
  test/xpu/test_xpu_reset_max_memory_reserved.py
  test/xpu/test_xpu_set_debug_level.py
Labels: XPU, skip-ci: coverage

#74106 support cumprod's dim with None
  python/paddle/tensor/math.py
  test/legacy_test/test_cumprod_op.py
  test/legacy_test/test_inplace.py
Labels: contributor, HappyOpenSource

#74123 [PHI] Unify expand_grad kernel behavior between cpu and gpu
  paddle/phi/kernels/impl/expand_grad_kernel_impl.h
Labels: contributor, HappyOpenSource

#74033 dual pp support overlap
  paddle/fluid/distributed/collective/process_group_nccl.cc
  python/paddle/distributed/communication/deep_ep/__init__.py
  python/paddle/distributed/fleet/meta_parallel/dualpipev.py
  python/paddle/distributed/fleet/meta_parallel/pp_utils/batch_comm_helper.py
Labels: skip-ci: coverage

#74145 [Typing] support Numeric with bool in type hints
  paddle/fluid/pybind/eager_utils.cc
  python/paddle/_typing/basic.py
  python/paddle/tensor/manipulation.py
Labels: contributor, HappyOpenSource

#74116 [Slice]Dispatch bool-only combined case to elementwise
  paddle/fluid/pybind/eager_method.cc
  paddle/fluid/pybind/slice_utils.h
  paddle/phi/kernels/cpu/index_elementwise_put_grad_kernel.cc
  paddle/phi/kernels/cpu/index_elementwise_put_kernel.cc
  paddle/phi/kernels/gpu/index_elementwise_put_grad_kernel.cu
  paddle/phi/kernels/gpu/index_elementwise_put_kernel.cu
Labels: skip-ci: coverage

#73854 [0-size Tensor Job2 No.60] Add 0-size Tensor support for paddle.nn.functional.instance_norm [fluid_ops]
  paddle/fluid/prim/api/composite_backward/composite_backward_api.h
  paddle/fluid/primitive/decomp_rule/decomp_vjp/details.h
  paddle/phi/infermeta/backward.cc
  paddle/phi/infermeta/backward.h
  paddle/phi/infermeta/spmd_rules/instance_norm.cc
  paddle/phi/infermeta/spmd_rules/instance_norm.h
  paddle/phi/infermeta/ternary.cc
  paddle/phi/kernels/cpu/instance_norm_grad_kernel.cc
  paddle/phi/kernels/cpu/instance_norm_kernel.cc
  paddle/phi/kernels/gpu/instance_norm_grad_kernel.cu
  paddle/phi/kernels/gpu/instance_norm_kernel.cu
  paddle/phi/kernels/instance_norm_grad_kernel.h
  paddle/phi/kernels/xpu/instance_norm_grad_kernel.cc
  paddle/phi/kernels/xpu/instance_norm_kernel.cc
  paddle/phi/ops/yaml/backward.yaml
  test/cpp/auto_parallel/spmd_rule_test.cc
  test/legacy_test/test_instance_norm_op_v2.py
Labels: contributor, HappyOpenSource Pro, skip-ci: approval

#74134 [Phi]Fix multi_margin_loss for big tensor
  paddle/phi/infermeta/binary.cc
  python/paddle/nn/functional/loss.py
Labels: skip-ci: coverage

#74129 [0-size Tensor No.185、151] Add 0-size Tensor support for paddle.nn.functional.layer_norm [fluid_ops]
  paddle/phi/kernels/cpu/layer_norm_grad_kernel.cc
  paddle/phi/kernels/cpu/layer_norm_kernel.cc
  paddle/phi/kernels/gpu/layer_norm_grad_kernel.cu
  paddle/phi/kernels/gpu/layer_norm_kernel.cu
  paddle/phi/kernels/xpu/layer_norm_grad_kernel.cc
  paddle/phi/kernels/xpu/layer_norm_kernel.cc
  python/paddle/nn/functional/vision.py
  test/legacy_test/test_affine_grid_op.py
  test/legacy_test/test_layer_norm_op.py
Labels: contributor, HappyOpenSource Pro, skip-ci: approval

#74104 Fix cmake check tensorrt with TensorRT 10.12.0.36
  cmake/tensorrt.cmake
Labels: contributor, HappyOpenSource

#74098 [0-size Tensor No.181] Add 0-size Tensor support for paddle.nn.functional.interpolate [fluid_ops]
  paddle/phi/infermeta/multiary.cc
  paddle/phi/kernels/cpu/interpolate_grad_kernel.cc
  paddle/phi/kernels/cpu/interpolate_kernel.cc
  paddle/phi/kernels/gpu/interpolate_grad_kernel.cu
  paddle/phi/kernels/gpu/interpolate_kernel.cu
  paddle/phi/kernels/xpu/interpolate_grad_kernel.cc
  paddle/phi/kernels/xpu/interpolate_kernel.cc
  python/paddle/nn/functional/common.py
  test/legacy_test/test_adaptive_avg_pool2d.py
  test/legacy_test/test_bicubic_interp_v2_op.py
Labels: contributor, HappyOpenSource Pro

#74130 [PHI] Support complex for `paddle.linalg.lu_unpack` , `paddle.linalg.lu_solve`
  paddle/phi/backends/dynload/cusolver.h
  paddle/phi/backends/dynload/lapack.h
  paddle/phi/backends/dynload/rocsolver.h
  paddle/phi/kernels/cpu/lu_solve_grad_kernel.cc
  paddle/phi/kernels/cpu/lu_solve_kernel.cc
  paddle/phi/kernels/cpu/lu_unpack_grad_kernel.cc
  paddle/phi/kernels/cpu/lu_unpack_kernel.cc
  paddle/phi/kernels/funcs/lapack/lapack_function.cc
  paddle/phi/kernels/gpu/lu_grad_kernel.cu
  paddle/phi/kernels/gpu/lu_solve_grad_kernel.cu
  paddle/phi/kernels/gpu/lu_solve_kernle.cu
  paddle/phi/kernels/gpu/lu_unpack_grad_kernel.cu
  paddle/phi/kernels/gpu/lu_unpack_kernel.cu
  python/paddle/tensor/linalg.py
  test/legacy_test/test_lu_solve_op.py
  test/legacy_test/test_lu_unpack_op.py
Labels: skip-ci: coverage

#74119 [0-size Tensor No.221、155、187] Add 0-size Tensor support for paddle.nn.functional.softmax [fluid_ops]
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/multiary_infer_sym.cc
  paddle/phi/infermeta/multiary.cc
  paddle/phi/kernels/cpu/batch_norm_grad_kernel.cc
  paddle/phi/kernels/cpu/batch_norm_kernel.cc
  paddle/phi/kernels/gpu/batch_norm_grad_kernel.cu
  paddle/phi/kernels/gpu/batch_norm_kernel.cu
  paddle/phi/kernels/gpudnn/softmax_grad_kernel.cu
  paddle/phi/kernels/gpudnn/softmax_kernel.cu
  paddle/phi/kernels/xpu/batch_norm_grad_kernel.cc
  paddle/phi/kernels/xpu/batch_norm_kernel.cc
  paddle/phi/kernels/xpu/matmul_grad_kernel.cc
  paddle/phi/kernels/xpu/matmul_kernel.cc
  test/legacy_test/test_batch_norm_op.py
  test/legacy_test/test_linear.py
  test/legacy_test/test_softmax_op.py
Labels: contributor, HappyOpenSource Pro

#74121 Support use default stream for GPU
  paddle/common/flags.cc
  paddle/phi/backends/context_pool.cc
  paddle/phi/backends/gpu/gpu_context.cc
  paddle/phi/backends/gpu/gpu_context.h
  paddle/phi/common/memory_utils.cc
  paddle/phi/common/memory_utils.h
  paddle/phi/core/cuda_stream.h
  paddle/phi/core/memory/memcpy.cc
  paddle/phi/core/platform/device_context.cc
  paddle/phi/core/platform/device_context.h
  python/paddle/distributed/fleet/meta_parallel/pp_utils/forward_backward_overlap_utils.py
Labels: skip-ci: coverage

#74070 [Big tensor] fix nan in cross_entropy
  python/paddle/nn/functional/loss.py
Labels: skip-ci: coverage

#74166 Replace FUSE_MKLDNN FUSE_ONEDNN [fluid_ops]
  paddle/fluid/framework/ir/conv_bn_fuse_pass.cc
  paddle/fluid/framework/ir/fuse_pass_base.cc
  paddle/fluid/framework/ir/fuse_pass_base.h
  paddle/fluid/framework/ir/onednn/conv_elementwise_add_onednn_fuse_pass.cc
  paddle/fluid/framework/ir/onednn/matmul_elementwise_add_onednn_fuse_pass.cc
Labels: contributor, HappyOpenSource

#74142 Replace use_mkldnn to use_onednn in paddle/fluid/framework/ir/onednn tests
  paddle/fluid/framework/ir/onednn/cpu_bfloat16_pass_tester.cc
  paddle/fluid/framework/ir/onednn/cpu_quantize_pass_tester.cc
  paddle/fluid/framework/ir/onednn/cpu_quantize_squash_pass_tester.cc
  paddle/fluid/framework/ir/onednn/depthwise_conv_onednn_pass_tester.cc
  paddle/fluid/framework/ir/onednn/onednn_placement_pass_tester.cc
Labels: contributor, HappyOpenSource

#74143 [0-size Tensor Job2 No.53] Add 0-size Tensor support for paddle.nn.functional.adaptive_log_softmax_with_loss [fluid_ops]
  python/paddle/nn/functional/loss.py
  test/legacy_test/test_adaptive_log_softmax_with_loss.py
Labels: contributor, HappyOpenSource Pro

#74151 Add DefaultCustomPlace to GetDefaultPlace() method
  paddle/phi/common/place.cc
  paddle/phi/common/place.h
  paddle/phi/core/distributed/auto_parallel/reshard/reshard_utils.cc
Labels: contributor, skip-ci: coverage

#74160 [Accuracy diff No.102] Fix accuracy diff for paddle.lstsq API
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/binary_infer_sym.cc
  paddle/phi/infermeta/binary.cc
  paddle/phi/kernels/cpu/lstsq_kernel.cc
  paddle/phi/kernels/gpu/lstsq_kernel.cu
  paddle/phi/kernels/impl/lstsq_kernel_impl.h
  test/legacy_test/test_linalg_lstsq_op.py
Labels: contributor, HappyOpenSource Pro, skip-ci: coverage

#74152 [0-size Tensor Job2 No.27] Add 0-size Tensor support for paddle.incubate.nn.functional.fused_linear
  test/legacy_test/test_fused_matmul_bias.py
Labels: contributor, HappyOpenSource Pro, skip-ci: approval

#74175 [0-size Tensor Retest]Fix bincount、 chunk、gather_nd、einsum to support 0-size Tensor
  paddle/phi/infermeta/unary.cc
  paddle/phi/kernels/cpu/bincount_kernel.cc
  paddle/phi/kernels/gpu/bincount_kernel.cu
  paddle/phi/kernels/impl/einsum_grad_kernel_impl.h
  paddle/phi/kernels/impl/tile_grad_kernel_impl.h
  paddle/phi/kernels/impl/tile_kernel_impl.h
  paddle/phi/kernels/tile_grad_kernel.h
  paddle/phi/kernels/tile_kernel.h
  python/paddle/tensor/manipulation.py
  test/legacy_test/test_gather_nd_op.py
  test/legacy_test/test_tile_op.py
Labels: skip-ci: coverage

#74187 mark the last forward chunk in balanced vpp
  python/paddle/distributed/fleet/meta_parallel/pipeline_parallel.py
Labels: skip-ci: coverage

#74147 [slice] fix index_elemwentwise_get_gard bug slice-check
  paddle/fluid/pybind/slice_utils.h
  paddle/phi/kernels/cpu/index_elementwise_get_grad_kernel.cc
  paddle/phi/kernels/gpu/index_elementwise_get_grad_kernel.cu
Labels: skip-ci: coverage

#74159 [Fix Issue] fix issue 73668
  paddle/phi/kernels/cpu/arange_kernel.cc
  paddle/phi/kernels/gpu/arange_kernel.cu
  paddle/phi/kernels/xpu/arange_kernel.cc
Labels: contributor, HappyOpenSource, skip-ci: coverage

#74180 Replace EnableMKLDNN EnableONEDNN [fluid_ops]
  paddle/fluid/framework/executor.cc
  paddle/fluid/framework/executor.h
  paddle/fluid/inference/api/analysis_config.cc
  paddle/fluid/inference/api/paddle_analysis_config.h
  paddle/fluid/inference/api/paddle_pass_builder.cc
  paddle/fluid/inference/api/paddle_pass_builder.h
  paddle/fluid/inference/capi/paddle_c_api.h
  paddle/fluid/inference/capi/pd_config.cc
  paddle/fluid/inference/capi_exp/pd_config.cc
  paddle/fluid/inference/capi_exp/pd_config.h
  paddle/fluid/inference/experimental/javaapi/native/com_baidu_paddle_inference_Config.cpp
  paddle/fluid/inference/goapi/config.go
  paddle/fluid/inference/goapi/config_test.go
  paddle/fluid/jit/engine/predictor_engine.cc
  paddle/fluid/operators/controlflow/conditional_block_infer_op.cc
  paddle/fluid/pybind/inference_api.cc
  test/cpp/fluid/mkldnn/test_onednn_cpu_quantize_pass.cc
  test/cpp/inference/api/analyzer_bfloat16_image_classification_tester.cc
  test/cpp/inference/api/analyzer_capi_exp_pd_config_tester.cc
  test/cpp/inference/api/analyzer_capi_exp_tester.cc
  test/cpp/inference/api/analyzer_capi_tester.cc
  test/cpp/inference/api/analyzer_dam_tester.cc
  test/cpp/inference/api/analyzer_detect_tester.cc
  test/cpp/inference/api/analyzer_image_classification_tester.cc
  test/cpp/inference/api/analyzer_mmp_tester.cc
  test/cpp/inference/api/analyzer_quant_image_classification_tester.cc
  test/cpp/inference/api/analyzer_seq_pool1_tester_helper.h
  test/cpp/inference/api/analyzer_vis_tester.cc
  test/cpp/inference/api/analyzer_vit_ocr_tester.cc
  test/cpp/inference/infer_ut/test_det_mv3_db.cc
  test/cpp/inference/infer_ut/test_ernie_text_cls.cc
  test/cpp/inference/infer_ut/test_ppyolo_mbv3.cc
  test/cpp/inference/infer_ut/test_ppyolov2_r50vd.cc
  test/cpp/inference/infer_ut/test_yolov3.cc
  test/cpp/inference/test_helper.h
  test/deprecated/cpp/inference/api/analysis_predictor_tester.cc
  test/deprecated/cpp/inference/api/analyzer_bert_tester_deprecated.cc
  test/deprecated/cpp/inference/api/analyzer_detect_functional_mkldnn_tester_deprecated.cc
  test/deprecated/cpp/inference/api/analyzer_image_classification_tester.cc
  test/deprecated/cpp/inference/api/analyzer_transformer_profile_tester.cc
Labels: contributor, HappyOpenSource, skip-ci: approval

#74205 Replace mkldnn_enabled_op_types_ onednn_enabled_op_types_ [fluid_ops]
  paddle/fluid/framework/details/build_strategy.cc
  paddle/fluid/framework/details/build_strategy.h
  paddle/fluid/inference/api/analysis_config.cc
  paddle/fluid/inference/api/analysis_predictor.cc
  paddle/fluid/inference/api/paddle_analysis_config.h
  paddle/fluid/inference/api/paddle_pass_builder.cc
  paddle/fluid/inference/api/paddle_pass_builder.h
  paddle/fluid/inference/capi/paddle_c_api.h
  paddle/fluid/inference/capi/pd_config.cc
  paddle/fluid/inference/capi_exp/pd_config.cc
  paddle/fluid/inference/capi_exp/pd_config.h
  paddle/fluid/inference/goapi/config.go
  paddle/fluid/inference/goapi/config_test.go
  paddle/fluid/jit/engine/predictor_engine.cc
  paddle/fluid/pybind/compiled_program.cc
  paddle/fluid/pybind/inference_api.cc
  test/cpp/inference/api/CMakeLists.txt
  test/cpp/inference/api/analyzer_bfloat16_image_classification_tester.cc
  test/cpp/inference/api/analyzer_capi_exp_pd_config_tester.cc
  test/cpp/inference/api/analyzer_capi_exp_tester.cc
  test/cpp/inference/api/analyzer_capi_tester.cc
  test/cpp/inference/api/analyzer_dam_tester.cc
  test/cpp/inference/api/analyzer_detect_tester.cc
  test/cpp/inference/api/analyzer_image_classification_tester.cc
  test/cpp/inference/api/analyzer_mmp_tester.cc
  test/cpp/inference/api/analyzer_seq_pool1_profile_tester.cc
  test/cpp/inference/api/analyzer_seq_pool1_tester_helper.h
  test/cpp/inference/api/analyzer_vis_tester.cc
  test/cpp/inference/api/analyzer_vit_ocr_tester.cc
  test/cpp/inference/infer_ut/test_det_mv3_db.cc
  test/cpp/inference/infer_ut/test_ernie_text_cls.cc
  test/cpp/inference/infer_ut/test_ppyolo_mbv3.cc
  test/cpp/inference/infer_ut/test_ppyolov2_r50vd.cc
  test/cpp/inference/infer_ut/test_yolov3.cc
  test/deprecated/cpp/inference/api/CMakeLists.txt
  test/deprecated/cpp/inference/api/analysis_predictor_tester.cc
  test/deprecated/cpp/inference/api/analyzer_detect_functional_mkldnn_tester_deprecated.cc
  test/deprecated/cpp/inference/api/analyzer_image_classification_tester.cc
  test/deprecated/cpp/inference/api/analyzer_transformer_compare_tester.cc
Labels: contributor, HappyOpenSource, skip-ci: approval

#74225 [XPU] fix strided_copy data_size param
  paddle/phi/kernels/xpu/strided_copy_kernel.cc
Labels: XPU

#74237 fix
  .github/workflows/CI.yml
Labels: skip-ci: all

#74212 [0-size Tensor Job2 No.51] Add 0-size Tensor support for paddle.multiplex [fluid_ops]
  paddle/phi/kernels/cpu/multiplex_kernel.cc
  paddle/phi/kernels/gpu/multiplex_kernel.cu
  test/legacy_test/test_multiplex_op.py
Labels: contributor, HappyOpenSource Pro

#74157 [0-size Tensor No.88] Add 0-size Tensor support for paddle.incubate.nn.functional.variable_length_memory_efficient_attention [fluid_ops]
  paddle/phi/infermeta/fusion.cc
  paddle/phi/kernels/fusion/cutlass/variable_length_memory_efficient_attention_kernel.cu
  test/legacy_test/test_variable_length_memory_efficient_attention.py
Labels: contributor, HappyOpenSource Pro, skip-ci: approval

#74223 [Big-Tensor Fix] Add error throwing check of ctc_loss
  paddle/phi/kernels/impl/warpctc_kernel_impl.h
Labels: contributor

#74264 [PHI] Add missing `const` qualifier for `Tensor.contiguous`
  paddle/phi/api/include/tensor.h
  paddle/phi/api/lib/tensor.cc
Labels: skip-ci: coverage

#74245 Fix elemenewist_add_op elementwise_add_op [fluid_ops]
  paddle/fluid/pybind/compiled_program.cc
  paddle/phi/backends/device_ext.h
  paddle/phi/backends/onednn/axpy_handler.h
  paddle/phi/backends/onednn/matmul_utils.h
  paddle/phi/core/dense_tensor.cc
  paddle/phi/core/framework/var_type_helper.h
  paddle/phi/kernels/funcs/fft_fill_conj.h
  paddle/phi/kernels/funcs/sequence_padding.cu
  paddle/phi/kernels/funcs/strided_slice.h
  test/legacy_test/test_fold_op.py
Labels: contributor, HappyOpenSource

#74233 Rename context to dev_ctx in paddle/phi/kernels/funcs [fluid_ops]
  paddle/phi/kernels/funcs/cross_entropy.h
  paddle/phi/kernels/funcs/fc_functor.h
  paddle/phi/kernels/funcs/math/unpooling.h
  paddle/phi/kernels/funcs/math_function.h
  paddle/phi/kernels/funcs/math_function_impl.h
  paddle/phi/kernels/funcs/maxouting.cc
  paddle/phi/kernels/funcs/maxouting.cu
  paddle/phi/kernels/funcs/maxouting.h
  paddle/phi/kernels/funcs/vol2col.h
Labels: contributor, HappyOpenSource

#74232 update block_radix_topk.cuh namespace
  paddle/phi/kernels/funcs/block_radix_topk.cuh
  paddle/phi/kernels/gpu/weighted_sample_neighbors_kernel.cu
  tools/enforce/count_enforce_by_dir.sh
Labels: contributor, HappyOpenSource

#74257 [Accuracy diff No.84-85] Fix accuracy diff for `paddle.einsum` API
  paddle/phi/kernels/impl/einsum_grad_kernel_impl.h
  paddle/phi/kernels/impl/einsum_kernel_impl.h
  test/legacy_test/test_einsum.py
Labels: contributor, HappyOpenSource Pro

#74182 [Accuracy diff No.132] Fix accuracy diff for paddle.outer API
  python/paddle/tensor/math.py
  test/legacy_test/test_outer.py
Labels: contributor, HappyOpenSource Pro

#74261 [0-size Tensor No.358] Add 0-size Tensor support for paddle.vision.ops.generate_proposals [fluid_ops]
  paddle/phi/kernels/cpu/generate_proposals_kernel.cc
  paddle/phi/kernels/gpu/generate_proposals_kernel.cu
  paddle/phi/kernels/xpu/generate_proposals_kernel.cc
  test/legacy_test/test_generate_proposals_v2_op.py
Labels: contributor, HappyOpenSource Pro

#74259 [0-size Tensor No.82] Add 0-size Tensor support for paddle.incubate.nn.functional.fused_bias_act [fluid_ops]
  paddle/phi/infermeta/multiary.cc
  paddle/phi/kernels/fusion/gpu/fused_bias_act_kernel.cu
  paddle/phi/kernels/fusion/xpu/fused_bias_act_kernel.cc
  test/legacy_test/test_fused_bias_act_op.py
Labels: contributor, HappyOpenSource Pro, skip-ci: approval

#74268 [distributed] fix bug when ep_degree == sharding_degree
  python/paddle/distributed/fleet/utils/tensor_fusion_helper.py
Labels: skip-ci: coverage

#74242 [big tensor] upsample 支持大tensor
  paddle/phi/kernels/cpu/interpolate_grad_kernel.cc
  paddle/phi/kernels/cpu/interpolate_kernel.cc
  paddle/phi/kernels/funcs/interpolate_function.h
  paddle/phi/kernels/gpu/interpolate_grad_kernel.cu
  paddle/phi/kernels/gpu/interpolate_kernel.cu
  paddle/phi/kernels/xpu/interpolate_grad_kernel.cc
  paddle/phi/kernels/xpu/interpolate_kernel.cc
Labels: skip-ci: coverage

#74263 [PHI]Fix nanmedian
  paddle/phi/kernels/gpu/nanmedian_kernel.cu
  test/legacy_test/test_nanmedian.py
Labels: contributor, HappyOpenSource

#74299 add is_compiled_with_onednn [fluid_ops]
  paddle/fluid/pybind/pybind.cc
  test/deprecated/book/test_fit_a_line_deprecated.py
  test/deprecated/book/test_word2vec_book_deprecated.py
  test/deprecated/custom_op/custom_raw_op_kernel_op_setup.py
Labels: contributor, HappyOpenSource

#74304 Revert "Fix paddle.vision.ops.deform_conv2d API big Tensor"
  paddle/fluid/inference/tensorrt/plugin/deformable_conv_op_plugin.cu
  paddle/phi/kernels/cpu/deformable_conv_grad_kernel.cc
  paddle/phi/kernels/funcs/deformable_conv_functor.cc
  paddle/phi/kernels/funcs/deformable_conv_functor.cu
  paddle/phi/kernels/gpu/deformable_conv_grad_kernel.cu
  paddle/phi/kernels/impl/deformable_conv_grad_kernel_impl.h
  paddle/phi/kernels/impl/deformable_conv_kernel_impl.h
Labels: skip-ci: coverage

#74244 Replace cur_mkldnn_session_id cur_onednn_session_id [fluid_ops]
  paddle/fluid/inference/api/analysis_predictor.cc
  paddle/phi/backends/onednn/onednn_context.cc
  paddle/phi/backends/onednn/onednn_context.h
Labels: contributor, HappyOpenSource

#73831 support fa3 varlen bwd and modify fa3 varlen fwd api
  paddle/phi/infermeta/backward.cc
  paddle/phi/infermeta/backward.h
  paddle/phi/infermeta/ternary.cc
  paddle/phi/infermeta/ternary.h
  paddle/phi/kernels/gpu/flash_attn_v3_grad_kernel.cu
  paddle/phi/kernels/gpu/flash_attn_v3_kernel.cu
  paddle/phi/kernels/gpu/flash_attn_v3_kernel.h
  paddle/phi/ops/yaml/backward.yaml
  paddle/phi/ops/yaml/ops.yaml
  python/paddle/nn/functional/flash_attention.py
Labels: skip-ci: coverage

#74308 Add paddle.device.memory and paddle.device.device_count API
  python/paddle/device/__init__.py
Labels: skip-ci: coverage

#74158 fix dual pp bug
  python/paddle/distributed/fleet/meta_parallel/dualpipev.py
Labels: skip-ci: coverage

#74298 fix cuda error 700 for softmax
  paddle/phi/kernels/gpudnn/softmax_gpudnn.h
Labels: contributor

#74044 Implement IEEE 754 rounding conditions for fp32 to fp16 conversion in host
  paddle/phi/common/float16.h
Labels: contributor

#73941 [AutoParallel] pp dataloader align mode
  python/paddle/distributed/auto_parallel/pipelining/microbatch.py
  test/auto_parallel/PP_Schedules_demo.py
Labels: contributor, skip-ci: coverage

#74290 [Complex] Fix wrong reciprocal result when meets complex dtype
  paddle/phi/kernels/funcs/activation_functor.h
  test/legacy_test/test_activation_op.py
Labels: contributor, HappyOpenSource
