Repository PaddlePaddle/Paddle, pull requests merged in 2025-06, with the labels that each got.

#73045 Fix typos euqal equal
  paddle/fluid/pir/dialect/operator/ir/control_flow_op.cc
  paddle/phi/infermeta/unary.cc
  pyproject.toml
Labels: contributor, HappyOpenSource

#73038 [SOT][Exception] breakgraph when using `random.*`
  python/paddle/jit/sot/opcode_translator/executor/variables/callable.py
  python/paddle/jit/sot/utils/exceptions.py
  test/sot/test_force_breakgraph_api.py
Labels: contributor

#73005 Fix cudnn.make include path
  cmake/cudnn.cmake
Labels: contributor, HappyOpenSource

#72952 Fix out resize out dims
  paddle/phi/kernels/cpu/elementwise_add_kernel.cc
  paddle/phi/kernels/cpu/elementwise_divide_kernel.cc
  paddle/phi/kernels/cpu/elementwise_multiply_kernel.cc
  paddle/phi/kernels/cpu/roll_kernel.cc
  paddle/phi/kernels/gpu/roll_kernel.cu
  paddle/phi/kernels/kps/elementwise_kernel.cu
Labels: contributor, HappyOpenSource, skip-ci: xpu

#73060 [CodeStyle][Ruff] rename pre-commit id `ruff` -> `ruff-check`
  .pre-commit-config.yaml
Labels: contributor

#72937 [0-size Tensor No.81、138、141] Add 0-size Tensor support for blha_get_max_len
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/unary_infer_sym.cc
  paddle/phi/infermeta/unary.cc
  paddle/phi/kernels/cpu/mv_grad_kernel.cc
  paddle/phi/kernels/cpu/nanmedian_grad_kernel.cc
  paddle/phi/kernels/cpu/nanmedian_kernel.cc
  paddle/phi/kernels/fusion/gpu/blha_get_max_len.cu
  paddle/phi/kernels/fusion/xpu/blha_get_max_len_kernel.cc
  paddle/phi/kernels/gpu/mv_grad_kernel.cu
  paddle/phi/kernels/gpu/nanmedian_grad_kernel.cu
  paddle/phi/kernels/gpu/nanmedian_kernel.cu
  paddle/phi/kernels/impl/mv_kernel_impl.h
  test/legacy_test/test_blha_get_max_len_op.py
  test/legacy_test/test_mv_op.py
  test/legacy_test/test_nanmedian.py
Labels: contributor, HappyOpenSource Pro

#73030 [SOT][Exception] Fix zerodiv not raising
  python/paddle/jit/sot/opcode_translator/executor/variable_dispatch.py
  python/paddle/jit/sot/symbolic_shape/operators.py
  python/paddle/jit/sot/utils/magic_methods.py
  test/sot/test_24_exceptions.py
Labels: contributor

#72954 [0-size Tensor No.145-150、152-154、170-171、194-199] Add 0-size Tensor support for pool
  paddle/phi/kernels/cpu/unpool_grad_kernel.cc
  paddle/phi/kernels/cpu/unpool_kernel.cc
  paddle/phi/kernels/funcs/pooling.h
  paddle/phi/kernels/funcs/reduce_function.h
  paddle/phi/kernels/gpu/unpool_grad_kernel.cu
  paddle/phi/kernels/gpu/unpool_kernel.cu
  paddle/phi/kernels/gpudnn/pool_grad_kernel.cu
  paddle/phi/kernels/gpudnn/pool_kernel.cu
  paddle/phi/kernels/impl/pool_grad_kernel_impl.h
  paddle/phi/kernels/impl/pool_kernel_impl.h
  paddle/phi/kernels/xpu/pool_grad_kernel.cc
  paddle/phi/kernels/xpu/pool_kernel.cc
  test/legacy_test/test_adaptive_avg_pool1d.py
  test/legacy_test/test_adaptive_avg_pool2d.py
  test/legacy_test/test_adaptive_avg_pool3d.py
  test/legacy_test/test_adaptive_max_pool1d.py
  test/legacy_test/test_adaptive_max_pool2d.py
  test/legacy_test/test_adaptive_max_pool3d.py
  test/legacy_test/test_fractional_max_pool2d_api.py
  test/legacy_test/test_fractional_max_pool3d_api.py
  test/legacy_test/test_pool1d_api.py
  test/legacy_test/test_pool2d_api.py
  test/legacy_test/test_pool3d_api.py
  test/legacy_test/test_unpool1d_op.py
  test/legacy_test/test_unpool3d_op.py
  test/legacy_test/test_unpool_op.py
Labels: contributor, HappyOpenSource Pro, skip-ci: approval

#72513 [XPU] update xhpc to impove performance of strided_copy, update prelu interface and update rsqrt interface
  cmake/external/xpu.cmake
  paddle/phi/kernels/xpu/activation_grad_kernel.cc
  paddle/phi/kernels/xpu/flash_attn_utils.h
  paddle/phi/kernels/xpu/p_recv_kernel.cc
  paddle/phi/kernels/xpu/p_send_kernel.cc
  paddle/phi/kernels/xpu/prelu_grad_kernel.cc
  paddle/phi/kernels/xpu/prelu_kernel.cc
  paddle/phi/kernels/xpu/strided_copy_kernel.cc
Labels: XPU

#72965 [Accuracy diff No.38-39] Fix accuracy diff for nextafter API
  paddle/phi/kernels/cpu/elementwise_kernel.cc
  paddle/phi/kernels/cpu/nextafter_kernel.cc
  paddle/phi/kernels/elementwise_kernel.h
  paddle/phi/kernels/funcs/elementwise_functor.h
  paddle/phi/kernels/gpu/nextafter_kernel.cu
  paddle/phi/kernels/impl/nextafter_kernel_impl.h
  paddle/phi/kernels/kps/elementwise_kernel.cu
  paddle/phi/kernels/nextafter_kernel.h
  test/legacy_test/test_nextafter_op.py
Labels: contributor, HappyOpenSource Pro

#73092 [fp8]Support fp8 deep gemm in paddle
  .gitignore
  cmake/cuda.cmake
  cmake/generic.cmake
  paddle/fluid/CMakeLists.txt
  paddle/fluid/distributed/collective/CMakeLists.txt
  paddle/fluid/distributed/collective/deep_ep/kernels/buffer.cuh
  paddle/fluid/distributed/collective/deep_ep/kernels/utils.cuh
  paddle/fluid/fp8/CMakeLists.txt
  paddle/fluid/fp8/deep_gemm/include/deep_gemm/fp8_gemm.cuh
  paddle/fluid/fp8/deep_gemm/include/deep_gemm/mma_utils.cuh
  paddle/fluid/fp8/deep_gemm/include/deep_gemm/scheduler.cuh
  paddle/fluid/fp8/deep_gemm/include/deep_gemm/tma_utils.cuh
  paddle/fluid/fp8/deep_gemm/include/deep_gemm/utils.cuh
  python/env_dict.py.in
  python/paddle/incubate/fp8/__init__.py
  python/paddle/incubate/fp8/deep_gemm/__init__.py
  python/paddle/incubate/fp8/deep_gemm/jit/__init__.py
  python/paddle/incubate/fp8/deep_gemm/jit/compiler.py
  python/paddle/incubate/fp8/deep_gemm/jit/interleave_ffma.py
  python/paddle/incubate/fp8/deep_gemm/jit/runtime.py
  python/paddle/incubate/fp8/deep_gemm/jit/template.py
  python/paddle/incubate/fp8/deep_gemm/jit_kernels/__init__.py
  python/paddle/incubate/fp8/deep_gemm/jit_kernels/gemm.py
  python/paddle/incubate/fp8/deep_gemm/jit_kernels/m_grouped_gemm.py
  python/paddle/incubate/fp8/deep_gemm/jit_kernels/tuner.py
  python/paddle/incubate/fp8/deep_gemm/jit_kernels/utils.py
  python/paddle/incubate/fp8/deep_gemm/utils.py
  python/setup.py.in
  setup.py
  test/fp8/CMakeLists.txt
  test/fp8/test_fp8_deep_gemm.py
Labels: skip-ci: approval

#73104 Fix nvtx.h deprecation warning
  paddle/phi/backends/dynload/nvtx.h
Labels: contributor, HappyOpenSource

#72927 在scaled_dot_product_attention函数中加入bool mask
  python/paddle/nn/functional/flash_attention.py
  test/legacy_test/test_scaled_dot_product_attention.py
Labels: contributor

#73044 [0-size Tensor No.200、210、345、356、267、338] Add 0-size Tensor support for prelu/maxout/var
  paddle/phi/kernels/cpu/prelu_grad_kernel.cc
  paddle/phi/kernels/cpu/prelu_kernel.cc
  paddle/phi/kernels/gpu/prelu_grad_kernel.cu
  paddle/phi/kernels/gpu/prelu_kernel.cu
  paddle/phi/kernels/impl/maxout_grad_kernel_impl.h
  paddle/phi/kernels/impl/maxout_kernel_impl.h
  paddle/phi/kernels/onednn/prelu_grad_kernel.cc
  paddle/phi/kernels/onednn/prelu_kernel.cc
  paddle/phi/kernels/xpu/prelu_grad_kernel.cc
  paddle/phi/kernels/xpu/prelu_kernel.cc
  python/paddle/tensor/stat.py
  test/legacy_test/test_maxout_op.py
  test/legacy_test/test_prelu_op.py
  test/legacy_test/test_variance_layer.py
Labels: contributor, HappyOpenSource Pro

#73014 [Accuracy diff No.40-41] [BIT] fix cosine_similarity accuracy error when x1, x2 need to broadcast
  python/paddle/nn/functional/common.py
  test/legacy_test/test_cosine_similarity_api.py
Labels: contributor

#72727 [Auto Parallel] Add spmd rule No.10 for index_select and index_select_grad ops.
  paddle/phi/infermeta/spmd_rules/index_select.cc
  paddle/phi/infermeta/spmd_rules/index_select.h
  paddle/phi/infermeta/spmd_rules/rules.cc
  paddle/phi/infermeta/spmd_rules/rules.h
  paddle/phi/ops/yaml/backward.yaml
  paddle/phi/ops/yaml/ops.yaml
  test/auto_parallel/spmd_rules/CMakeLists.txt
  test/auto_parallel/spmd_rules/test_index_select_rule.py
  test/cpp/auto_parallel/spmd_rule_test.cc
Labels: contributor, HappyOpenSource Pro, skip-ci: approval

#73108 [0-size Tensor No.26、289] Add 0-size Tensor support for bmm
  paddle/phi/kernels/impl/bmm_grad_kernel_impl.h
  paddle/phi/kernels/xpu/bmm_grad_kernel.cc
  test/legacy_test/test_bmm_op.py
Labels: contributor, HappyOpenSource Pro

#72970 [0-size Tensor No.172] Add 0-size Tensor support for gelu
  paddle/phi/kernels/cpu/gelu_grad_kernel.cc
  paddle/phi/kernels/cpu/gelu_kernel.cc
  paddle/phi/kernels/gpu/gelu_grad_kernel.cu
  paddle/phi/kernels/gpu/gelu_kernel.cu
  paddle/phi/kernels/xpu/gelu_grad_kernel.cc
  paddle/phi/kernels/xpu/gelu_kernel.cc
  test/legacy_test/test_gelu_op.py
Labels: contributor, HappyOpenSource Pro

#73179 [CodeStyle] Format all `.cuh` files
  .pre-commit-config.yaml
  paddle/cinn/runtime/cuda/cinn_cuda_runtime_source.cuh
  paddle/fluid/distributed/collective/deep_ep/kernels/buffer.cuh
  paddle/fluid/distributed/collective/deep_ep/kernels/configs.cuh
  paddle/fluid/distributed/collective/deep_ep/kernels/exception.cuh
  paddle/fluid/distributed/collective/deep_ep/kernels/ibgda_device.cuh
  paddle/fluid/distributed/collective/deep_ep/kernels/launch.cuh
  paddle/fluid/distributed/collective/deep_ep/kernels/utils.cuh
  paddle/fluid/fp8/deep_gemm/include/deep_gemm/fp8_gemm.cuh
  paddle/fluid/fp8/deep_gemm/include/deep_gemm/mma_utils.cuh
  paddle/fluid/fp8/deep_gemm/include/deep_gemm/scheduler.cuh
  paddle/fluid/fp8/deep_gemm/include/deep_gemm/tma_utils.cuh
  paddle/fluid/fp8/deep_gemm/include/deep_gemm/utils.cuh
  paddle/fluid/inference/tensorrt/plugin/common/common.cuh
  paddle/phi/kernels/funcs/block_radix_topk.cuh
  paddle/phi/kernels/funcs/random.cuh
  paddle/phi/kernels/sparse/gpu/conv_kernel_impl.cuh
  paddle/phi/kernels/sparse/gpu/conv_memory_utils.cuh
  paddle/phi/kernels/sparse/gpu/sparse_conv_hashmap.cuh
  python/paddle/apy/matmul_pass/matmul/cutlass_matmul.cuh
Labels: skip-ci: approval

#72825 Rename ctx to dev_ctx in paddle/phi/kernels/xpu/ directory
  paddle/phi/kernels/xpu/abs_grad_kernel.cc
  paddle/phi/kernels/xpu/abs_kernel.cc
  paddle/phi/kernels/xpu/adagrad_kernel.cc
  paddle/phi/kernels/xpu/bitwise.cc
  paddle/phi/kernels/xpu/cast_kernel.cc
  paddle/phi/kernels/xpu/clip_grad_kernel.cc
  paddle/phi/kernels/xpu/complex_grad_kernel.cc
  paddle/phi/kernels/xpu/conv_transpose_grad_kernel.cc
  paddle/phi/kernels/xpu/conv_transpose_kernel.cc
  paddle/phi/kernels/xpu/dequantization_kernel.cc
  paddle/phi/kernels/xpu/embedding_grad_kernel.cc
  paddle/phi/kernels/xpu/embedding_kernel.cc
  paddle/phi/kernels/xpu/expand_as_kernel.cc
  paddle/phi/kernels/xpu/expand_grad_kernel.cc
  paddle/phi/kernels/xpu/expand_kernel.cc
  paddle/phi/kernels/xpu/eye.cc
  paddle/phi/kernels/xpu/fill_diagonal_tensor_kernel.cc
  paddle/phi/kernels/xpu/flash_attn_grad_kernel.cc
  paddle/phi/kernels/xpu/flash_attn_utils.h
  paddle/phi/kernels/xpu/gather_nd_grad_kernel.cc
  paddle/phi/kernels/xpu/gaussian_kernel.cc
  paddle/phi/kernels/xpu/increment_kernel.cc
  paddle/phi/kernels/xpu/index_add_grad_kernel.cc
  paddle/phi/kernels/xpu/index_add_kernel.cc
  paddle/phi/kernels/xpu/index_sample_grad_kernel.cc
  paddle/phi/kernels/xpu/index_sample_kernel.cc
  paddle/phi/kernels/xpu/index_select_grad_kernel.cc
  paddle/phi/kernels/xpu/index_select_kernel.cc
  paddle/phi/kernels/xpu/interpolate_kernel.cc
  paddle/phi/kernels/xpu/isfinite_kernel.cc
  paddle/phi/kernels/xpu/label_smooth_kernel.cc
  paddle/phi/kernels/xpu/layer_norm_grad_kernel.cc
  paddle/phi/kernels/xpu/layer_norm_kernel.cc
  paddle/phi/kernels/xpu/linspace_kernel.cc
  paddle/phi/kernels/xpu/meshgrid_kernel.cc
  paddle/phi/kernels/xpu/multiclass_nms3_kernel.cc
  paddle/phi/kernels/xpu/norm_kernel.cc
  paddle/phi/kernels/xpu/pixel_shuffle_grad_kernel.cc
  paddle/phi/kernels/xpu/pixel_shuffle_kernel.cc
  paddle/phi/kernels/xpu/pool_grad_kernel.cc
  paddle/phi/kernels/xpu/pool_kernel.cc
  paddle/phi/kernels/xpu/prior_box_kernel.cc
  paddle/phi/kernels/xpu/quantization_kernel.cc
  paddle/phi/kernels/xpu/repeat_interleave_kernel.cc
  paddle/phi/kernels/xpu/scatter_grad_kernel.cc
  paddle/phi/kernels/xpu/scatter_kernel.cc
  paddle/phi/kernels/xpu/scatter_nd_add_grad_kernel.cc
  paddle/phi/kernels/xpu/slice_grad_kernel.cc
  paddle/phi/kernels/xpu/slice_kernel.cc
  paddle/phi/kernels/xpu/swiglu_kernel.cc
  paddle/phi/kernels/xpu/swiglu_kernel_grad.cc
  paddle/phi/kernels/xpu/tril_triu_grad_kernel.cc
  paddle/phi/kernels/xpu/tril_triu_kernel.cc
  paddle/phi/kernels/xpu/unfold_grad_kernel.cc
  paddle/phi/kernels/xpu/unfold_kernel.cc
  paddle/phi/kernels/xpu/uniform_inplace_grad_kernel.cc
  paddle/phi/kernels/xpu/uniform_inplace_kernel.cc
  paddle/phi/kernels/xpu/where_grad_kernel.cc
  paddle/phi/kernels/xpu/where_kernel.cc
Labels: contributor, HappyOpenSource, skip-ci: approval

#73167 Clean "Why still include the fluid headers"
  paddle/phi/kernels/cpu/bitwise_kernel.cc
  paddle/phi/kernels/cpu/cast_impl.h
  paddle/phi/kernels/cpu/complex_kernel.cc
  paddle/phi/kernels/cpu/dot_kernel.cc
  paddle/phi/kernels/cpu/logical_kernel.cc
  paddle/phi/kernels/cpu/scale_kernel.cc
  paddle/phi/kernels/cpu/sign_kernel.cc
  paddle/phi/kernels/gpu/complex_kernel.cu
  paddle/phi/kernels/gpu/dot_kernel.cu
  paddle/phi/kernels/gpu/sign_kernel.cu.cc
  paddle/phi/kernels/gpudnn/softmax_gpudnn.h
  paddle/phi/kernels/impl/complex_kernel_impl.h
  paddle/phi/kernels/impl/sign_kernel_impl.h
  paddle/phi/kernels/selected_rows/xpu/adam_kernel.cc
Labels: contributor, HappyOpenSource

#72577 `frobenius_norm` support complex input
  paddle/phi/kernels/cpu/frobenius_norm_grad_kernel.cc
  paddle/phi/kernels/cpu/frobenius_norm_kernel.cc
  paddle/phi/kernels/gpu/frobenius_norm_grad_kernel.cu
  paddle/phi/kernels/gpu/frobenius_norm_kernel.cu
  python/paddle/tensor/linalg.py
  test/legacy_test/test_norm_all.py
Labels: contributor

#73151 Rename ctx to dev_ctx in paddle/phi/kernels/impl/ directory - part2
  paddle/phi/kernels/impl/pixel_shuffle_grad_kernel_impl.h
  paddle/phi/kernels/impl/pixel_shuffle_kernel_impl.h
  paddle/phi/kernels/impl/poisson_grad_kernel_impl.h
  paddle/phi/kernels/impl/pool_grad_kernel_impl.h
  paddle/phi/kernels/impl/pool_kernel_impl.h
  paddle/phi/kernels/impl/qr_grad_kernel_impl.h
  paddle/phi/kernels/impl/renorm_impl.h
  paddle/phi/kernels/impl/repeat_interleave_grad_kernel_impl.h
  paddle/phi/kernels/impl/repeat_interleave_kernel_impl.h
  paddle/phi/kernels/impl/rmsprop_kernel_impl.h
  paddle/phi/kernels/impl/searchsorted_kernel_impl.h
  paddle/phi/kernels/impl/sequence_expand_kernel_impl.h
  paddle/phi/kernels/impl/sequence_mask_kernel_impl.h
  paddle/phi/kernels/impl/sequence_pool_kernel_impl.h
  paddle/phi/kernels/impl/sequence_softmax_kernel_impl.h
  paddle/phi/kernels/impl/slice_grad_kernel_impl.h
  paddle/phi/kernels/impl/slice_kernel_impl.h
  paddle/phi/kernels/impl/stft_kernel_impl.h
  paddle/phi/kernels/impl/svd_grad_kernel_impl.h
  paddle/phi/kernels/impl/trace_grad_kernel_impl.h
  paddle/phi/kernels/impl/tril_triu_grad_kernel_impl.h
  paddle/phi/kernels/impl/tril_triu_kernel_impl.h
  paddle/phi/kernels/impl/unfold_grad_kernel_impl.h
  paddle/phi/kernels/impl/unfold_kernel_impl.h
  paddle/phi/kernels/impl/warpctc_kernel_impl.h
  paddle/phi/kernels/impl/warprnnt_kernel_impl.h
Labels: contributor, HappyOpenSource, skip-ci: approval

#73119 [Feat] Support custom __radd__ and __rmul__
  paddle/fluid/pybind/eager_math_op_patch.cc
  paddle/fluid/pybind/exception.h
  test/legacy_test/test_math_op_patch.py
Labels: contributor

#73008 [0-size Tensor No.144] Add 0-size Tensor support for paddle.nextafter API.
  paddle/phi/kernels/cpu/elementwise_kernel.cc
  paddle/phi/kernels/kps/elementwise_kernel.cu
  test/legacy_test/test_nextafter_op.py
Labels: contributor, HappyOpenSource Pro

#72996 [0-size Tensor No.75] Add 0-size Tensor support for hstack
  test/legacy_test/test_stack_extension_api.py
Labels: contributor, HappyOpenSource Pro

#73169 [Auto Parallel] add spmd rule for pd_op.empty_like
  paddle/phi/infermeta/spmd_rules/full_like.cc
  paddle/phi/infermeta/spmd_rules/full_like.h
  paddle/phi/ops/yaml/ops.yaml
  test/cpp/auto_parallel/spmd_rule_test.cc
Labels: contributor, HappyOpenSource

#73175 [AutoParallel] Add reduce_any spmd rule
  paddle/phi/core/distributed/gloo_utils.h
  paddle/phi/infermeta/spmd_rules/reduction.cc
  paddle/phi/infermeta/spmd_rules/reduction.h
  paddle/phi/kernels/gpu/all_reduce_kernel.cu
  paddle/phi/ops/yaml/ops.yaml
  test/auto_parallel/semi_auto_parallel_for_reduction.py
  test/cpp/auto_parallel/spmd_rule_test.cc
Labels: contributor, HappyOpenSource

#73165 [0-size Tensor No.248] Add 0-size Tensor support for reshape
  paddle/phi/kernels/reshape_grad_kernel.cc
  paddle/phi/kernels/reshape_kernel.cc
  test/legacy_test/test_reshape_op.py
Labels: contributor, HappyOpenSource Pro

#73166 [0-size Tensor No.252] Add 0-size Tensor support for round
  test/legacy_test/test_activation_op_zero_size.py
  test/white_list/op_accuracy_white_list.py
Labels: contributor, HappyOpenSource Pro

#73170 [0-size Tensor No.4] Add 0-size Tensor support for addmm
  paddle/phi/infermeta/ternary.cc
  paddle/phi/kernels/impl/addmm_grad_kernel_impl.h
  paddle/phi/kernels/impl/addmm_kernel_impl.h
  paddle/phi/kernels/xpu/addmm_grad_kernel.cc
  paddle/phi/kernels/xpu/addmm_kernel.cc
  test/legacy_test/test_addmm_op.py
Labels: contributor, HappyOpenSource Pro

#73164 Replace strtobool from distutils
  python/paddle/distributed/fleet/utils/tensor_fusion_helper.py
Labels: contributor, HappyOpenSource

#73204 [0-size Tensor Job2 No.68、92] Add 0-size Tensor support for pow
  test/legacy_test/test_pow.py
Labels: contributor, HappyOpenSource Pro

#73174 [BIT] mode support big tensor
  paddle/phi/kernels/funcs/mode.h
  paddle/phi/kernels/gpu/mode_grad_kernel.cu
Labels: contributor

#73197 [0-size Tensor No.321] Add 0-size Tensor support for mode
  paddle/phi/kernels/cpu/mode_grad_kernel.cc
  paddle/phi/kernels/cpu/mode_kernel.cc
  paddle/phi/kernels/gpu/mode_grad_kernel.cu
  paddle/phi/kernels/gpu/mode_kernel.cu
  test/legacy_test/test_mode_op.py
Labels: contributor, HappyOpenSource Pro

#73168 [0-size Tensor No.261] Add 0-size Tensor support for slice
  test/legacy_test/test_slice_op.py
Labels: contributor, HappyOpenSource Pro

#73198 [PHI] Fix paddle.trunc for big tensor
  paddle/phi/kernels/gpu/trunc_grad_kernel.cu
Labels: contributor

#72925 [Auto Parallel] Add spmd rule No.19 for roi_align and roi_align_grad ops.
  paddle/phi/infermeta/spmd_rules/roi_align.cc
  paddle/phi/infermeta/spmd_rules/roi_align.h
  paddle/phi/infermeta/spmd_rules/rules.cc
  paddle/phi/infermeta/spmd_rules/rules.h
  paddle/phi/ops/yaml/backward.yaml
  paddle/phi/ops/yaml/ops.yaml
  test/auto_parallel/spmd_rules/CMakeLists.txt
  test/auto_parallel/spmd_rules/test_roi_align_rule.py
  test/cpp/auto_parallel/spmd_rule_test.cc
  test/cpp/auto_parallel/spmd_rule_test_util.cc
  test/cpp/auto_parallel/spmd_rule_test_util.h
Labels: contributor, HappyOpenSource Pro, skip-ci: approval, skip-ci: all

#73211 Fix openfile_check bug
  paddle/fluid/inference/utils/io_utils.cc
Labels: contributor, HappyOpenSource Pro

#73050 优化to_tensor函数中的bf16转换
  python/paddle/tensor/creation.py
Labels: contributor

#73181 [0-size Tensor No.303] Add 0-size Tensor support for fill_diagonal_
  paddle/phi/kernels/cpu/fill_diagonal_grad_kernel.cc
  paddle/phi/kernels/cpu/fill_diagonal_kernel.cc
  paddle/phi/kernels/gpu/fill_diagonal_grad_kernel.cu
  paddle/phi/kernels/gpu/fill_diagonal_kernel.cu
  test/legacy_test/test_tensor_fill_diagonal_.py
Labels: contributor, HappyOpenSource Pro

#73154 [Auto Parallel] add more tests for expand spmd
  paddle/phi/infermeta/spmd_rules/expand.cc
  test/cpp/auto_parallel/expand_spmd_rule_test.cc
Labels: contributor, HappyOpenSource, skip-ci: xpu

#73107 [Auto Parallel] Add spmd rule No.7 for expand_as and expand_as_grad ops.
  paddle/phi/api/generator/dist_api_gen.py
  paddle/phi/infermeta/spmd_rules/expand_as.cc
  paddle/phi/infermeta/spmd_rules/rules.cc
  paddle/phi/ops/yaml/backward.yaml
  paddle/phi/ops/yaml/ops.yaml
  test/auto_parallel/spmd_rules/CMakeLists.txt
  test/auto_parallel/spmd_rules/test_expand_as_rule.py
  test/cpp/auto_parallel/expand_as_spmd_rule_test.cc
Labels: contributor, HappyOpenSource Pro, skip-ci: approval

#73210 Fix opendir_check bug
  test/cpp/inference/api/trt_test_helper.h
Labels: contributor, HappyOpenSource Pro

#73191 [0-size Tensor No.193] Add 0-size Tensor support for mode margin_ranking_loss
  test/legacy_test/test_nn_margin_rank_loss.py
Labels: contributor, HappyOpenSource Pro

#73201 [PHI] Fix paddle.trapezoid for big tensor
  paddle/phi/kernels/funcs/gather.cu.h
  paddle/phi/kernels/gpu/elementwise_grad.h
Labels: contributor

#73274 [Accuracy diff No.133] Fix accuracy diff for pow API
  paddle/phi/kernels/funcs/elementwise_functor.h
  paddle/phi/kernels/gpu/activation_kernel.cu
  test/legacy_test/test_elementwise_pow_op.py
Labels: contributor

#73123 在fused_rms_norm函数中加入begin_norm_axis的默认值和维度检查
  python/paddle/incubate/nn/functional/fused_rms_norm.py
  test/legacy_test/test_rms_norm_op.py
Labels: contributor

#73228 【Operator Mechanism】add fused_stack_transpose_quant api
  paddle/phi/infermeta/fusion.cc
  paddle/phi/infermeta/fusion.h
  paddle/phi/kernels/CMakeLists.txt
  paddle/phi/kernels/fusion/gpu/fused_stack_quant_kernel.cu
  paddle/phi/kernels/fusion/gpu/fused_stack_transpose_quant.h
  paddle/phi/kernels/fusion/gpu/fused_stack_transpose_quant_kernel.cu
  paddle/phi/kernels/fusion/gpu/quant_utils.h
  paddle/phi/ops/yaml/fused_ops.yaml
  python/paddle/incubate/nn/functional/__init__.py
  python/paddle/incubate/nn/functional/fp8.py
  test/legacy_test/CMakeLists.txt
  test/legacy_test/test_fused_stack_transpose_quant_op.py
Labels: contributor, skip-ci: approval

#73282 [SOT][3.13] Mark more APIs as unified (`all_reduce`, `top_p_sampling`, etc.)
  python/paddle/distributed/fleet/layers/mpu/mp_ops.py
  python/paddle/jit/sot/opcode_translator/executor/pycode_generator.py
  python/paddle/jit/sot/utils/paddle_api_config.py
Labels: contributor

#73285 Add fused_transpose_split_quant Operator
  paddle/phi/infermeta/fusion.cc
  paddle/phi/infermeta/fusion.h
  paddle/phi/kernels/CMakeLists.txt
  paddle/phi/kernels/fusion/gpu/fused_transpose_split_quant_kernel.cu
  paddle/phi/ops/yaml/fused_ops.yaml
  python/paddle/incubate/nn/functional/__init__.py
  python/paddle/incubate/nn/functional/fp8.py
  test/legacy_test/CMakeLists.txt
  test/legacy_test/test_fused_transpose_split_quant_op.py
Labels: contributor

#72938 [Auto Parallel] Add spmd rule No.11 for instance_norm and instance_norm_grad ops.
  paddle/phi/infermeta/spmd_rules/instance_norm.cc
  paddle/phi/infermeta/spmd_rules/instance_norm.h
  paddle/phi/infermeta/spmd_rules/rules.cc
  paddle/phi/infermeta/spmd_rules/rules.h
  paddle/phi/ops/yaml/backward.yaml
  paddle/phi/ops/yaml/ops.yaml
  test/cpp/auto_parallel/spmd_rule_test.cc
Labels: contributor, HappyOpenSource Pro, skip-ci: approval

#73240 优化scaled_dot_product_attention的head_size检查
  python/paddle/nn/functional/flash_attention.py
Labels: contributor

#73114 [Auto Parallel] Try to refine dist_api_gen
  paddle/phi/api/generator/dist_api_gen.py
  paddle/phi/api/generator/dist_bw_api_gen.py
Labels: contributor, HappyOpenSource Pro

#73180 [0-size Tensor No.132、236、240、241、259] Add 0-size Tensor support for masked_select
  paddle/phi/kernels/gpu/masked_select_grad_kernel.cu
  test/legacy_test/test_masked_select_op.py
  test/legacy_test/test_parameter.py
  test/legacy_test/test_pdist.py
  test/legacy_test/test_polar.py
  test/legacy_test/test_sinc.py
Labels: contributor, HappyOpenSource Pro

#73359 Improvements in fused_swiglu_weighted_bwd operator
  paddle/phi/kernels/fusion/gpu/fused_swiglu_weighted_bwd_kernel.cu
Labels: contributor, skip-ci: distribute

#73357 [XPU] support moe_combine on XPU
  paddle/phi/backends/xpu/xpu3_op_list.cc
  paddle/phi/kernels/xpu/moe_combine_grad_kernel.cc
  paddle/phi/kernels/xpu/moe_combine_kernel.cc
  test/xpu/test_moe_combine.py
Labels: XPU

#73276 [0-size Tensor Job2 No.38] Add 0-size Tensor support for index_sample
  paddle/phi/infermeta/binary.cc
  paddle/phi/kernels/cpu/index_sample_kernel.cc
  paddle/phi/kernels/gpu/index_sample_grad_kernel.cu
  paddle/phi/kernels/gpu/index_sample_kernel.cu
  paddle/phi/kernels/xpu/index_sample_kernel.cc
  test/legacy_test/test_index_sample_op.py
Labels: contributor, HappyOpenSource Pro

#73161 Rename ctx to dev_ctx in paddle/phi/kernels/fusion/xpu/ directory
  paddle/phi/kernels/fusion/xpu/add_act_xpu_kernel.cc
  paddle/phi/kernels/fusion/xpu/add_layernorm_xpu_kernel.cc
  paddle/phi/kernels/fusion/xpu/addcmul_xpu_kernel.cc
  paddle/phi/kernels/fusion/xpu/conv1d_xpu_kernel.cc
  paddle/phi/kernels/fusion/xpu/conv2d_xpu_kernel.cc
  paddle/phi/kernels/fusion/xpu/conv_transpose_xpu_kernel.cc
  paddle/phi/kernels/fusion/xpu/cross_attention_xpu_kernel.cc
  paddle/phi/kernels/fusion/xpu/embedding_with_eltwise_add_xpu_kernel.cc
  paddle/phi/kernels/fusion/xpu/fast_layernorm_xpu_kernel.cc
  paddle/phi/kernels/fusion/xpu/fast_where_xpu_kernel.cc
  paddle/phi/kernels/fusion/xpu/fc_xpu_kernel.cc
  paddle/phi/kernels/fusion/xpu/fused_linear_param_grad_add_kernel.cc
  paddle/phi/kernels/fusion/xpu/generate_sequence_xpu_kernel.cc
  paddle/phi/kernels/fusion/xpu/group_norm_silu_xpu_kernel.cc
  paddle/phi/kernels/fusion/xpu/layer_norm_act_xpu_kernel.cc
  paddle/phi/kernels/fusion/xpu/layer_norm_relu_xpu_kernel.cc
  paddle/phi/kernels/fusion/xpu/mask_adaptive_xpu_kernel.cc
  paddle/phi/kernels/fusion/xpu/multi_encoder_xpu_kernel.cc
  paddle/phi/kernels/fusion/xpu/qkv_attention_xpu_kernel.cc
  paddle/phi/kernels/fusion/xpu/roformer_relative_embedding_kernel.cc
  paddle/phi/kernels/fusion/xpu/sequance_unpad_xpu_kernel.cc
  paddle/phi/kernels/fusion/xpu/sine_pos_xpu_kernel.cc
  paddle/phi/kernels/fusion/xpu/spatial_transformer_resblock_xpu_kernel.cc
  paddle/phi/kernels/fusion/xpu/squeeze_excitation_block_xpu_kernel.cc
  paddle/phi/kernels/fusion/xpu/variable_length_memory_efficient_attention_kernel.cc
  paddle/phi/kernels/fusion/xpu/yolo_box_xpu_kernel.cc
Labels: contributor, HappyOpenSource, skip-ci: approval

#73326 Rename dev_ctx.x_context() ctx
  paddle/phi/kernels/xpu/activation_kernel.cc
  paddle/phi/kernels/xpu/adamw_kernel.cc
  paddle/phi/kernels/xpu/add_n_kernel.cc
  paddle/phi/kernels/xpu/argsort_kernel.cc
  paddle/phi/kernels/xpu/batch_norm_grad_kernel.cc
  paddle/phi/kernels/xpu/c_softmax_with_cross_entropy_kernel.cc
  paddle/phi/kernels/xpu/compare_kernel.cc
  paddle/phi/kernels/xpu/concat_and_split_functor.cc
  paddle/phi/kernels/xpu/cum_kernel.cc
  paddle/phi/kernels/xpu/dropout_kernel.cc
  paddle/phi/kernels/xpu/elementwise_add_kernel.cc
  paddle/phi/kernels/xpu/elementwise_divide_grad_kernel.cc
  paddle/phi/kernels/xpu/elementwise_divide_kernel.cc
  paddle/phi/kernels/xpu/elementwise_grad_kernel.cc
  paddle/phi/kernels/xpu/elementwise_kernel.cc
  paddle/phi/kernels/xpu/elementwise_multiply_grad_kernel.cc
  paddle/phi/kernels/xpu/elementwise_multiply_kernel.cc
  paddle/phi/kernels/xpu/elementwise_subtract_grad_kernel.cc
  paddle/phi/kernels/xpu/elementwise_subtract_kernel.cc
  paddle/phi/kernels/xpu/flash_attn_grad_kernel.cc
  paddle/phi/kernels/xpu/flip_kernel.cc
  paddle/phi/kernels/xpu/gather_nd_grad_kernel.cc
  paddle/phi/kernels/xpu/gaussian_kernel.cc
  paddle/phi/kernels/xpu/increment_kernel.cc
  paddle/phi/kernels/xpu/index_sample_kernel.cc
  paddle/phi/kernels/xpu/logical_kernel.cc
  paddle/phi/kernels/xpu/momentum_kernel.cc
  paddle/phi/kernels/xpu/multinomial_kernel.cc
  paddle/phi/kernels/xpu/prod_kernel.cc
  paddle/phi/kernels/xpu/quantize_linear_kernel.cc
  paddle/phi/kernels/xpu/reduce_all_kernel.cc
  paddle/phi/kernels/xpu/reduce_any_kernel.cc
  paddle/phi/kernels/xpu/reduce_max_kernel.cc
  paddle/phi/kernels/xpu/reduce_mean_kernel.cc
  paddle/phi/kernels/xpu/reduce_min_kernel.cc
  paddle/phi/kernels/xpu/reduce_util.h
  paddle/phi/kernels/xpu/set_value_kernel.cc
  paddle/phi/kernels/xpu/sigmoid_cross_entropy_with_logits_grad_kernel.cc
  paddle/phi/kernels/xpu/sigmoid_cross_entropy_with_logits_kernel.cc
  paddle/phi/kernels/xpu/squared_l2_norm_grad_kernel.cc
  paddle/phi/kernels/xpu/squared_l2_norm_kernel.cc
  paddle/phi/kernels/xpu/stride_slice_grad_kernel.cc
  paddle/phi/kernels/xpu/stride_slice_kernel.cc
  paddle/phi/kernels/xpu/tile_grad_kernel.cc
  paddle/phi/kernels/xpu/xpu_api_wrapper.h
Labels: contributor, HappyOpenSource, skip-ci: approval

#73374 Rename flatten_kernel_grad.cc to flatten_grad_kernel.cc
  paddle/phi/kernels/onednn/flatten_grad_kernel.cc
  paddle/phi/kernels/xpu/c_embedding_grad_kernel.cc
Labels: contributor, HappyOpenSource

#73255 Update row_conv_grad_kernel.cu
  paddle/phi/kernels/gpu/row_conv_grad_kernel.cu
Labels: contributor, HappyOpenSource

#73173 [0-size Tensor No.180、182-183] Add 0-size Tensor support for hinge_embedding_loss
  paddle/phi/kernels/impl/kldiv_loss_grad_kernel_impl.h
  paddle/phi/kernels/impl/kldiv_loss_kernel_impl.h
  paddle/phi/kernels/xpu/kldiv_loss_kernel.cc
  test/legacy_test/test_hinge_embedding_loss.py
  test/legacy_test/test_kldiv_loss_op.py
  test/legacy_test/test_l1_loss.py
Labels: contributor, HappyOpenSource Pro

#73341 [0-size Tensor Job2 No.17-20、31-34] Add 0-size Tensor support for segment_max
  paddle/phi/kernels/impl/segment_pool_grad_kernel_impl.h
  paddle/phi/kernels/impl/segment_pool_kernel_impl.h
  test/legacy_test/test_segment_ops.py
Labels: contributor, HappyOpenSource Pro

#73346 [0-size Tensor Job2 No.30] Add 0-size Tensor support for swiglu
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/binary_infer_sym.cc
  paddle/phi/infermeta/binary.cc
  paddle/phi/kernels/swiglu_grad_kernel.h
  paddle/phi/kernels/swiglu_kernel.h
  paddle/phi/kernels/xpu/swiglu_kernel.cc
  paddle/phi/kernels/xpu/swiglu_kernel_grad.cc
  test/legacy_test/test_swiglu.py
Labels: contributor, HappyOpenSource Pro

#73361 [0-size Tensor Job2 No.105] Add 0-size Tensor support for roi_align
  paddle/phi/kernels/cpu/roi_align_grad_kernel.cc
  paddle/phi/kernels/cpu/roi_align_kernel.cc
  paddle/phi/kernels/gpu/roi_align_kernel.cu
  paddle/phi/kernels/xpu/roi_align_grad_kernel.cc
  paddle/phi/kernels/xpu/roi_align_kernel.cc
  test/legacy_test/test_roi_align_op.py
Labels: contributor, HappyOpenSource Pro

#73375 [0-size Tensor Job2 No.24] Add 0-size Tensor support for histogram
  paddle/phi/kernels/cpu/histogram_kernel.cc
  paddle/phi/kernels/gpu/histogram_kernel.cu
  test/legacy_test/test_histogram_op.py
Labels: contributor, HappyOpenSource Pro

#73293 [Accuracy diff No.79] Fix accuracy diff for paddle.combinations API
  python/paddle/tensor/math.py
  test/legacy_test/test_combinations.py
Labels: contributor, HappyOpenSource Pro

#73365 standardize moe permute unpermute
  paddle/phi/infermeta/multiary.cc
  paddle/phi/infermeta/multiary.h
  paddle/phi/kernels/CMakeLists.txt
  paddle/phi/kernels/gpu/moe_permute_kernel.cu
  paddle/phi/kernels/moe_permute.h
  paddle/phi/ops/yaml/ops.yaml
  python/paddle/nn/functional/moe_permute.py
  python/paddle/nn/functional/moe_unpermute.py
  test/legacy_test/CMakeLists.txt
  test/legacy_test/test_moe_permute_unpermute.py
Labels: contributor

#73418 Fix transfer_layout_pass bug
  paddle/fluid/pir/transforms/general/transfer_layout_pass.cc
Labels: contributor

#73239 propagates NaNs for paddle.angle
  paddle/phi/kernels/funcs/complex_functors.h
  python/paddle/tensor/math.py
  test/legacy_test/test_angle_op.py
Labels: contributor, HappyOpenSource

#73355 [0-size Tensor Job2 No.78、98] Add 0-size Tensor support for sum
  paddle/phi/kernels/cpu/reduce_sum_kernel.cc
  paddle/phi/kernels/kps/reduce_kernel.cu
  paddle/phi/kernels/xpu/reduce_sum_kernel.cc
  test/legacy_test/test_sum_op.py
Labels: contributor, HappyOpenSource Pro

#73409 [Auto Parallel] add FLAGS_enable_main_grad
  python/paddle/amp/auto_cast.py
  python/paddle/optimizer/optimizer.py
Labels: contributor

#73411 fix deepep compile error
  cmake/external/nvshmem.cmake
  setup.py
Labels: contributor

#73420 将signal.stft的onsided的默认参数值从True改为None
  python/paddle/signal.py
Labels: contributor

#73352 [0-size Tensor Job2 No.100] Add 0-size Tensor support for topk
  paddle/phi/kernels/cpu/top_k_grad_kernel.cc
  paddle/phi/kernels/cpu/top_k_kernel.cc
  paddle/phi/kernels/gpu/top_k_grad_kernel.cu
  paddle/phi/kernels/gpu/top_k_kernel.cu
  paddle/phi/kernels/xpu/top_k_grad_kernel.cc
  paddle/phi/kernels/xpu/top_k_kernel.cc
  test/legacy_test/test_top_k_v2_op.py
Labels: contributor, HappyOpenSource Pro

#73387 [0-size Tensor Job2 No.58] Add 0-size Tensor support for gather_tree
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/binary_infer_sym.cc
  paddle/phi/infermeta/binary.cc
  paddle/phi/kernels/cpu/gather_tree_kernel.cc
  paddle/phi/kernels/gpu/gather_tree_kernel.cu
  test/legacy_test/test_gather_tree_op.py
Labels: contributor, HappyOpenSource Pro

#73456 [CI] clone fix
  .github/workflows/_Clone-linux.yml
Labels: skip-ci: all

#73464 [XPU] support moe_gate_dispatch
  paddle/phi/backends/xpu/xpu3_op_list.cc
  paddle/phi/kernels/xpu/moe_gate_dispatch_grad_kernel.cc
  paddle/phi/kernels/xpu/moe_gate_dispatch_kernel.cc
  test/xpu/test_moe_gate_dispatch.py
Labels: XPU

#73416 在smooth_l1_loss函数中加入is_huber参数
  python/paddle/nn/functional/loss.py
  python/paddle/nn/layer/loss.py
  test/legacy_test/test_smooth_l1_loss.py
Labels: contributor

#73392 Update repeat_tensor2index_tensor.cc
  paddle/phi/kernels/funcs/repeat_tensor2index_tensor.cc
Labels: contributor, HappyOpenSource

#73438 Add a call method for .cuda_steam
  paddle/fluid/pybind/custom_device_py.cc
Labels: contributor

#73384 [0-size Tensor Job2 No.46] Add 0-size Tensor support for masked_scatter
  paddle/phi/kernels/xpu/clip_grad_kernel.cc
  paddle/phi/kernels/xpu/clip_kernel.cc
  paddle/phi/kernels/xpu/logical_kernel.cc
  python/paddle/tensor/manipulation.py
  test/legacy_test/test_masked_scatter.py
Labels: contributor, HappyOpenSource Pro

#73442 Refine permute: reduce size of cudaMemset
  paddle/phi/kernels/gpu/moe_permute_kernel.cu
Labels: contributor

#73408 [Auto Parallel] add ElementwiseBinaryWithPartialInferSpmd for multiply
  paddle/phi/infermeta/spmd_rules/elementwise.cc
  paddle/phi/infermeta/spmd_rules/elementwise.h
  paddle/phi/infermeta/spmd_rules/rules.cc
  paddle/phi/infermeta/spmd_rules/utils.cc
  paddle/phi/infermeta/spmd_rules/utils.h
  paddle/phi/ops/yaml/inconsistent/dygraph_ops.yaml
  test/auto_parallel/spmd_rules/test_elementwise_rule.py
Labels: contributor

#73481 [CI] coverage disable ut
  .github/workflows/Coverage.yml
  test/ir/inference/CMakeLists.txt
Labels: skip-ci: all

#73512 Fix fp8 gemm interface performance issue
  python/paddle/incubate/nn/functional/fp8.py
Labels: skip-ci: cpu, skip-ci: npu

#73417 [Dy2St][3.13] Support pass cuda graph state and dispatch key in run program op and move get value name to python side
  paddle/fluid/eager/to_static/run_program_op_func.h
  paddle/fluid/eager/to_static/run_program_op_node.h
  paddle/fluid/framework/executor_cache.cc
  paddle/fluid/framework/executor_cache.h
  paddle/fluid/framework/new_executor/interpreter_base_impl.h
  paddle/fluid/framework/new_executor/interpretercore.cc
  paddle/fluid/framework/new_executor/interpretercore.h
  paddle/fluid/framework/new_executor/pir_interpreter.h
  paddle/fluid/framework/new_executor/program_interpreter.h
  paddle/fluid/pir/utils/name_analysis.cc
  paddle/fluid/pir/utils/name_analysis.h
  paddle/fluid/pybind/op_function_common.cc
  paddle/fluid/pybind/pir.cc
  python/paddle/jit/dy2static/pir_partial_program.py
  python/paddle/jit/dy2static/utils.py
  python/paddle/pir/__init__.py
  test/dygraph_to_static/test_no_need_buffer.py
  test/ir/pir/cinn/sub_graphs/test_sub_graph_82.py
Labels: skip-ci: approval

#73234 [XPU] support moe_gate_dispatch_partial_nosoftmaxtopk, expand_modality_expert_id and build_src_rank_and_local_expert_id
  paddle/phi/backends/xpu/xpu3_op_list.cc
  paddle/phi/kernels/xpu/expand_modality_expert_id_kernel.cc
  paddle/phi/kernels/xpu/ext_build_src_rank_and_local_expert_id_kernel.cc
  paddle/phi/kernels/xpu/moe_gate_dispatch_grad_kernel.cc
  paddle/phi/kernels/xpu/moe_gate_dispatch_kernel.cc
  paddle/phi/kernels/xpu/moe_ops_partial_nosoftmaxtopk_grad_kernel.cc
  paddle/phi/kernels/xpu/moe_ops_partial_nosoftmaxtopk_kernel.cc
  test/xpu/test_incubate_build_src_rank_and_local_expert_id_xpu.py
  test/xpu/test_incubate_expand_modality_expert_id_xpu.py
  test/xpu/test_incubate_moe_gate_dispatch_partial_nosoftmaxtopk_xpu.py
  test/xpu/test_moe_combine_xpu.py
  test/xpu/test_moe_gate_dispatch_xpu.py
Labels: XPU

#73516 Fix dynamic 0size nan complex problem in moe_permute
  paddle/phi/kernels/gpu/moe_permute_kernel.cu
Labels: skip-ci: xpu

#73393 Add cuda_graph op and pass
  paddle/common/flags.cc
  paddle/fluid/eager/to_static/run_program_op_node.h
  paddle/fluid/framework/new_executor/instruction/cuda_graph_instruction.cc
  paddle/fluid/framework/new_executor/instruction/cuda_graph_instruction.h
  paddle/fluid/framework/new_executor/pir_adaptor/pir_adaptor_util.cc
  paddle/fluid/framework/new_executor/pir_adaptor/pir_adaptor_util.h
  paddle/fluid/framework/new_executor/pir_interpreter.cc
  paddle/fluid/framework/new_executor/pir_interpreter.h
  paddle/fluid/pir/dialect/operator/ir/manual_op.cc
  paddle/fluid/pir/dialect/operator/ir/manual_op.h
  paddle/fluid/pir/transforms/cuda_graph_extract_pass.cc
  paddle/fluid/pir/transforms/cuda_graph_extract_pass.h
  paddle/fluid/pir/transforms/pd_op_to_kernel_pass.cc
  paddle/fluid/pir/transforms/sub_graph_detector.h
  python/paddle/jit/dy2static/pir_partial_program.py
Labels: skip-ci: approval, skip-ci: distribute

#73454 [Accuracy diff No.148] Fix accuracy diff for paddle.Tensor.tile API
  paddle/phi/kernels/impl/tile_grad_kernel_impl.h
Labels: contributor, HappyOpenSource Pro

#73102 修复atleast函数中，”输入为tensor的list，输出不是tensor的list“的bug
  python/paddle/tensor/manipulation.py
  test/legacy_test/test_atleast_xd.py
Labels: contributor

#73437 [0-size Tensor Job2 No.13、54] Add 0-size Tensor support for gammainc
  test/legacy_test/test_bce_loss.py
  test/legacy_test/test_gammainc.py
Labels: contributor, HappyOpenSource Pro

#73546 revert 73508
  python/paddle/distributed/fleet/meta_parallel/pipeline_parallel.py
Labels: skip-ci: all

#73507 [0-size Tensor No.130] Add 0-size Tensor support for logsumexp
  paddle/phi/kernels/gpu/logsumexp_kernel.cu
  paddle/phi/kernels/impl/logsumexp_grad_kernel_impl.h
  paddle/phi/kernels/impl/logsumexp_kernel_impl.h
  paddle/phi/kernels/xpu/logsumexp_grad_kernel.cc
  paddle/phi/kernels/xpu/logsumexp_kernel.cc
  test/legacy_test/test_logsumexp.py
Labels: contributor, HappyOpenSource Pro

#73477 [0-size Tensor Job2 No.48] Add 0-size Tensor support for paddle.median
  paddle/phi/kernels/cpu/top_k_kernel.cc
  paddle/phi/kernels/gpu/top_k_kernel.cu
  paddle/phi/kernels/xpu/top_k_kernel.cc
  python/paddle/tensor/stat.py
  test/legacy_test/test_median.py
Labels: contributor, HappyOpenSource Pro

#73513 [0-size Tensor Job2 No.37] Add 0-size Tensor support for index_put
  paddle/phi/kernels/cpu/index_put_grad_kernel.cc
  paddle/phi/kernels/cpu/index_put_kernel.cc
  paddle/phi/kernels/gpu/index_put_grad_kernel.cu
  paddle/phi/kernels/gpu/index_put_kernel.cu
  paddle/phi/kernels/xpu/index_put_grad_kernel.cc
  paddle/phi/kernels/xpu/index_put_kernel.cc
  test/legacy_test/test_index_put_op.py
Labels: contributor, HappyOpenSource Pro

#73525 [0-size Tensor Job2 No.69、93] Add 0-size Tensor support for prod
  paddle/phi/kernels/cpu/prod_kernel.cc
  paddle/phi/kernels/impl/prod_grad_kernel_impl.h
  paddle/phi/kernels/kps/reduce_kernel.cu
  paddle/phi/kernels/xpu/prod_kernel.cc
  python/paddle/tensor/math.py
  test/legacy_test/test_prod_op.py
Labels: contributor, HappyOpenSource Pro

#73528 [0-size Tensor No.213] Add 0-size Tensor support for paddle.nn.functional.rrelu
  paddle/phi/kernels/gpu/rrelu_grad_kernel.cu
  test/legacy_test/test_rrelu_op.py
Labels: contributor, HappyOpenSource Pro

#73369 phi not include fluid
  paddle/fluid/distributed/collective/process_group_custom.cc
  paddle/fluid/distributed/collective/process_group_flagcx.cc
  paddle/fluid/distributed/collective/process_group_nccl.cc
  paddle/fluid/framework/CMakeLists.txt
  paddle/fluid/framework/new_executor/CMakeLists.txt
  paddle/fluid/framework/new_executor/instruction/control_flow/select_input_instruction.cc
  paddle/fluid/framework/new_executor/instruction/control_flow/select_output_instruction.cc
  paddle/fluid/platform/profiler/CMakeLists.txt
  paddle/fluid/platform/profiler/supplement_tracing.cc
  paddle/phi/api/profiler/profiler_helper.h
  paddle/phi/common/thread_data_registry.h
  paddle/phi/common/type_promotion.h
  paddle/phi/core/enforce.h
  paddle/phi/core/framework/convert_utils.h
  paddle/phi/core/framework/var_type_helper.cc
  paddle/phi/core/framework/var_type_helper.h
  paddle/phi/core/memory/allocation/allocator.h
  paddle/phi/core/memory/allocation/custom_allocator.cc
  paddle/phi/core/memory/allocation/inlined_vector.h
  paddle/phi/core/operators/reader/buffered_reader.cc
  paddle/phi/core/platform/device_context.cc
  paddle/phi/core/platform/device_context.h
  paddle/phi/core/platform/device_event_base.h
  paddle/phi/core/platform/profiler.cc
  paddle/phi/core/platform/profiler.h
  paddle/phi/core/platform/resource_pool.h
  test/cpp/fluid/platform/profiler_test.cc
Labels: skip-ci: approval

#73563 [BIT] Optimize print speed
  python/paddle/tensor/to_string.py
Labels: contributor

#73593 [XPU] bugfix: release/3.1 skip async_offload for eb45
  python/paddle/incubate/tensor/manipulation.py
Labels: XPU

#73573 [XPU][cherry-pick] support math_cal_aux_loss and math_int_bincount
  python/paddle/incubate/nn/functional/cal_aux_loss.py
  python/paddle/incubate/nn/functional/int_bincount.py
  test/legacy_test/CMakeLists.txt
  test/legacy_test/test_incubate_cal_aux_loss.py
  test/xpu/test_incubate_int_bincount_xpu.py
Labels: XPU

#73617 Update nvshmem link
  cmake/external/nvshmem.cmake
Labels: skip-ci: all

#73524 [0-size Tensor No.9、10、286] Add 0-size Tensor support for argmin/argmax
  paddle/phi/kernels/cpu/arg_min_max_kernel.cc
  paddle/phi/kernels/gpu/arg_min_max_kernel.cu
  paddle/phi/kernels/xpu/arg_min_max_kernel.cc
  test/legacy_test/test_arg_min_max_op.py
Labels: contributor, HappyOpenSource Pro

#73556 [XPU] bugfix: skip async_offload for eb45 since cudaHostAllocPortable issue
  python/paddle/incubate/tensor/manipulation.py
  test/xpu/test_xpu_async_offload_reload_loadtest.py
Labels: XPU

#73589 [CI] fix cmake predownload
  .github/workflows/Coverage.yml
  ci/cmake-predownload.sh
Labels: skip-ci: sot, skip-ci: approval, skip-ci: coverage, skip-ci: mac, skip-ci: xpu, skip-ci: distribute, skip-ci: build, skip-ci: cpu, skip-ci: npu

#73537 [BIT] mv support big tensor
  paddle/phi/kernels/gpu/mv_grad_kernel.cu
Labels: contributor

#73370 Add fused_act_quant etc. API docs
  python/paddle/incubate/nn/functional/fp8.py
Labels: contributor

#73553 Dygraph PIR check cuda error
  paddle/common/flags.cc
  paddle/fluid/eager/api/manual/eager_manual/forwards/add_n_fwd_func.cc
  paddle/fluid/eager/api/manual/eager_manual/forwards/conv2d_fwd_function.cc
  paddle/fluid/eager/api/manual/eager_manual/forwards/dtensor_from_local_fwd_func.cc
  paddle/fluid/eager/api/manual/eager_manual/forwards/dtensor_to_local_fwd_func.cc
  paddle/fluid/eager/api/manual/eager_manual/forwards/multiply_fwd_func.cc
  paddle/fluid/eager/api/manual/eager_manual/forwards/reshard_fwd_func.cc
  paddle/fluid/eager/api/manual/eager_manual/forwards/sync_batch_norm_fwd_func.cc
  paddle/fluid/eager/api/manual/eager_manual/nodes/add_n_node.cc
  paddle/fluid/eager/api/manual/eager_manual/nodes/conv2d_nodes.cc
  paddle/fluid/eager/api/manual/eager_manual/nodes/dtensor_from_local_node.cc
  paddle/fluid/eager/api/manual/eager_manual/nodes/dtensor_to_local_node.cc
  paddle/fluid/eager/api/manual/eager_manual/nodes/multiply_node.cc
  paddle/fluid/eager/api/manual/eager_manual/nodes/reshard_node.cc
  paddle/fluid/eager/api/manual/eager_manual/nodes/sync_batch_norm_node.cc
  paddle/fluid/eager/auto_code_generator/generator/eager_gen.py
  paddle/fluid/eager/custom_operator/custom_operator_node.cc
  paddle/fluid/eager/pylayer/py_layer_node.cc
  paddle/fluid/eager/utils.h
  paddle/fluid/framework/new_executor/instruction/builtin_combine_instruction.cc
  paddle/fluid/framework/new_executor/instruction/cinn_jit_instruction.cc
  paddle/fluid/framework/new_executor/instruction/control_flow/assert_instruction.cc
  paddle/fluid/framework/new_executor/instruction/control_flow/has_elements_instruction.cc
  paddle/fluid/framework/new_executor/instruction/control_flow/if_instruction.cc
  paddle/fluid/framework/new_executor/instruction/control_flow/pylayer_instruction.cc
  paddle/fluid/framework/new_executor/instruction/control_flow/select_input_instruction.cc
  paddle/fluid/framework/new_executor/instruction/control_flow/select_output_instruction.cc
  paddle/fluid/framework/new_executor/instruction/control_flow/tuple_pop_instruction.cc
  paddle/fluid/framework/new_executor/instruction/control_flow/tuple_push_instruction.cc
  paddle/fluid/framework/new_executor/instruction/control_flow/while_instruction.cc
  paddle/fluid/framework/new_executor/instruction/control_flow/yield_instruction.cc
  paddle/fluid/framework/new_executor/instruction/cuda_graph_instruction.cc
  paddle/fluid/framework/new_executor/instruction/custom_engine_instruction.cc
  paddle/fluid/framework/new_executor/instruction/custom_kernel_instruction.cc
  paddle/fluid/framework/new_executor/instruction/instruction_util.h
  paddle/fluid/framework/new_executor/instruction/legacy_kernel_instruction.cc
  paddle/fluid/framework/new_executor/instruction/onednn/onednn_instruction.cc
  paddle/fluid/framework/new_executor/instruction/onednn/onednn_legacy_instruction.cc
  paddle/fluid/framework/new_executor/instruction/onednn/onednn_mixed_instruction.cc
  paddle/fluid/framework/new_executor/instruction/phi_kernel_instruction.cc
  paddle/fluid/framework/new_executor/instruction/tensorrt_engine_instruction.cc
  paddle/fluid/pybind/eager_functions.cc
  paddle/fluid/pybind/eager_py_layer.cc
Labels: skip-ci: approval, skip-ci: distribute

#73581 Update fp8_gemm_blockwise_kernel.cu check cuda version
  paddle/phi/kernels/legacy/gpu/fp8_gemm_blockwise_kernel.cu
Labels: contributor, HappyOpenSource

#73632 [0-size Tensor No.216] Add 0-size Tensor support for paddle.nn.functional.sequence_mask
  paddle/phi/kernels/impl/sequence_mask_kernel_impl.h
  test/sequence/test_sequence_mask.py
Labels: contributor, HappyOpenSource Pro

#73602 add math_moe_gate_dispatch operator
  python/paddle/incubate/nn/functional/moe_gate_dispatch.py
Labels: contributor

#73603 add math_moe_gate_dispatch operator
  python/paddle/incubate/nn/functional/moe_gate_dispatch.py
Labels: contributor

#73657 [BIT] Add not support enforce for lu big tensor
  paddle/phi/kernels/gpu/lu_kernel.cu
Labels: contributor

#73675 [ILUVATAR_GPU] Support iluvatar device.
  paddle/phi/infermeta/unary.cc
  python/paddle/nn/functional/flash_attention.py
Labels: contributor

#73667 [Infra] Update codeowners
  .github/CODEOWNERS
  ci/check_approval.sh
  tools/check_api_approvals.sh
Labels: skip-ci: approval

#73655 Fix supplement_tracing.cc
  paddle/fluid/platform/profiler/supplement_tracing.cc
Labels: contributor, HappyOpenSource

#73569 [Accuracy diff No.104] Fix accuracy diff for paddle.matmul API
  paddle/phi/kernels/impl/matmul_grad_kernel_impl.h
  paddle/phi/kernels/xpu/matmul_grad_kernel.cc
  test/legacy_test/test_matmul_v2_op.py
Labels: contributor, HappyOpenSource Pro

#73669 [XPU] update kunlun Dockerfile.develop.xre
  tools/dockerfile/Dockerfile.develop.xre
Labels: XPU, skip-ci: all

#73696 Update distribute CI
  .github/workflows/_Distribute-stable.yml
Labels: skip-ci: all

#73554 fix bug for adaptive_log_softmax_with_loss
  python/paddle/nn/functional/loss.py
Labels: contributor

#72063 [AutoParallel] Add take_along_axis spmd rules
  paddle/phi/infermeta/spmd_rules/rules.cc
  paddle/phi/infermeta/spmd_rules/rules.h
  paddle/phi/infermeta/spmd_rules/take_along_axis.cc
  paddle/phi/infermeta/spmd_rules/take_along_axis.h
  paddle/phi/ops/yaml/backward.yaml
  paddle/phi/ops/yaml/ops.yaml
  test/auto_parallel/spmd_rules/CMakeLists.txt
  test/auto_parallel/spmd_rules/test_take_along_axis_rule.py
Labels: contributor

#73582 [0-size Tensor Job2 No.12、77] Add 0-size Tensor support for paddle.squeeze/full
  python/paddle/tensor/manipulation.py
  python/paddle/utils/layers_utils.py
  test/legacy_test/test_fill_constant_op.py
  test/legacy_test/test_squeeze2_op.py
Labels: contributor, HappyOpenSource Pro

#73666 [0-size Tensor No.109、105、107] Add 0-size Tensor support for paddle.linalg.matrix_norm
  test/legacy_test/test_cov.py
  test/legacy_test/test_inverse_op.py
  test/legacy_test/test_norm_all.py
Labels: contributor, HappyOpenSource Pro

#73521 [Accuracy diff No.22] Fix accuracy diff for paddle.kron API
  paddle/phi/kernels/impl/kron_grad_kernel_impl.h
Labels: contributor, HappyOpenSource Pro

#73640 Fix typo hean_num_k head_num_k
  python/paddle/nn/functional/conv.py
  python/paddle/nn/functional/flash_attention.py
Labels: contributor, HappyOpenSource

#73609 [0-size Tensor No.90] Add 0-size Tensor support for paddle.index_fill
  python/paddle/tensor/manipulation.py
  test/legacy_test/test_index_fill.py
Labels: contributor, HappyOpenSource Pro

#73608 [0-size Tensor No.243、326] Add 0-size Tensor support for quantile
  test/legacy_test/test_quantile_and_nanquantile.py
Labels: contributor
