Repository PaddlePaddle/Paddle, pull requests merged in 2025-05, with the labels that each got.

#72154 [SOT][NumPy] Complete the basic procedure
  paddle/fluid/pybind/jit.cc
  paddle/fluid/pybind/sot/guards.cc
  paddle/fluid/pybind/sot/guards.h
  python/paddle/jit/sot/infer_meta.py
  python/paddle/jit/sot/opcode_translator/executor/function_graph.py
  python/paddle/jit/sot/opcode_translator/executor/opcode_executor.py
  python/paddle/jit/sot/opcode_translator/executor/variable_dispatch.py
  python/paddle/jit/sot/opcode_translator/executor/variables/__init__.py
  python/paddle/jit/sot/opcode_translator/executor/variables/basic.py
  python/paddle/jit/sot/opcode_translator/executor/variables/callable.py
  python/paddle/jit/sot/utils/__init__.py
  python/paddle/jit/sot/utils/envs.py
  python/paddle/jit/sot/utils/exceptions.py
  python/paddle/jit/sot/utils/numpy_utils.py
  test/sot/test_faster_guard.py
  test/sot/test_numpy_array.py
  test/sot/test_numpy_var_if.py
Labels: skip-ci: approval

#72478 [XPU] improve performance of layernorm, support scale and bias cast in xdnn
  paddle/phi/kernels/xpu/layer_norm_grad_kernel.cc
  paddle/phi/kernels/xpu/layer_norm_kernel.cc
Labels: XPU

#72546 Change the dependency of absl
  cmake/cinn/external/absl.cmake
  paddle/cinn/adt/op_equation_context.h
  paddle/cinn/backends/compiler.cc
  paddle/cinn/backends/compiler.h
  paddle/cinn/backends/extern_func_emitter.cc
  paddle/cinn/backends/function_prototype.h
  paddle/cinn/backends/llvm/codegen_llvm.cc
  paddle/cinn/backends/llvm/codegen_llvm.h
  paddle/cinn/backends/llvm/execution_engine.cc
  paddle/cinn/backends/llvm/execution_engine.h
  paddle/cinn/backends/llvm/generate_runtime_llvm_ir.py
  paddle/cinn/backends/llvm/llvm_util.h
  paddle/cinn/backends/llvm/runtime_symbol_registry.cc
  paddle/cinn/backends/llvm/runtime_symbol_registry.h
  paddle/cinn/backends/llvm/simple_jit.h
  paddle/cinn/common/cinn_value.cc
  paddle/cinn/common/cinn_value.h
  paddle/cinn/common/common.h
  paddle/cinn/common/context.h
  paddle/cinn/common/debug_manager.cc
  paddle/cinn/common/debug_manager.h
  paddle/cinn/common/info_registry.h
  paddle/cinn/hlir/framework/op.h
  paddle/cinn/hlir/framework/op_strategy.cc
  paddle/cinn/hlir/op/broadcast.cc
  paddle/cinn/hlir/op/contrib/cholesky.cc
  paddle/cinn/hlir/op/contrib/gaussian_random.cc
  paddle/cinn/hlir/op/contrib/lookup_table.cc
  paddle/cinn/hlir/op/contrib/one_hot.cc
  paddle/cinn/hlir/op/contrib/randint.cc
  paddle/cinn/hlir/op/contrib/repeat.cc
  paddle/cinn/hlir/op/contrib/sort.cc
  paddle/cinn/hlir/op/contrib/uniform_random.cc
  paddle/cinn/hlir/op/custom_call.cc
  paddle/cinn/hlir/op/elementwise.cc
  paddle/cinn/hlir/op/nn.cc
  paddle/cinn/hlir/op/op_util.h
  paddle/cinn/hlir/op/reduction.cc
  paddle/cinn/hlir/op/transform.cc
  paddle/cinn/ir/ir.cc
  paddle/cinn/ir/ir.h
  paddle/cinn/ir/ir_printer.cc
  paddle/cinn/ir/op/ir_operators.cc
  paddle/cinn/ir/registry.h
  paddle/cinn/ir/schedule/ir_schedule.cc
  paddle/cinn/ir/schedule/schedule_desc.cc
  paddle/cinn/ir/tensor.cc
  paddle/cinn/ir/tensor.h
  paddle/cinn/lang/compute.h
  paddle/cinn/optim/unroll_loops.cc
  paddle/cinn/pybind/backends.cc
  paddle/cinn/pybind/bind.h
  paddle/cinn/pybind/bind_utils.h
  paddle/cinn/pybind/common.cc
  paddle/cinn/pybind/lang.cc
  paddle/cinn/utils/functional.h
  paddle/cinn/utils/string.cc
  paddle/cinn/utils/type_defs.h
Labels: contributor

#72264 [Auto Parallel] Add there ops spmd_rule(argmin, abs, cosh)
  paddle/phi/infermeta/spmd_rules/argmin.cc
  paddle/phi/infermeta/spmd_rules/argmin.h
  paddle/phi/infermeta/spmd_rules/rules.cc
  paddle/phi/infermeta/spmd_rules/rules.h
  paddle/phi/ops/yaml/backward.yaml
  paddle/phi/ops/yaml/ops.yaml
  test/auto_parallel/spmd_rules/CMakeLists.txt
  test/auto_parallel/spmd_rules/test_argmin_rule.py
  test/cpp/auto_parallel/spmd_rule_test.cc
Labels: contributor

#72561 [NPU] release GIL in constant folding pass
  paddle/fluid/pybind/inference_api.cc
Labels: contributor

#72590 Fix typos <=
  python/paddle/nn/functional/input.py
  python/paddle/nn/layer/common.py
Labels: contributor, HappyOpenSource

#72611 fix result shape of `__ne__` and `__eq__` when comparing with complex scalar
  paddle/fluid/pybind/eager_math_op_patch.cc
  test/legacy_test/test_math_op_patch_pir.py
Labels: contributor

#72591 Fix typos 4-d
  python/paddle/nn/functional/vision.py
Labels: contributor, HappyOpenSource

#72618 [XPU] UpdatePadding has already modified the value of pad
  paddle/phi/kernels/xpu/pool_kernel.cc
Labels: XPU

#72627 Fix typo FlashAttention
  paddle/phi/kernels/gpu/flash_attn_utils.h
Labels: contributor, HappyOpenSource

#72619 为paddle.less_than、paddle.less_equal、paddle.greater_than、paddle.greater_equal添加复数类型支持
  paddle/phi/kernels/cpu/compare_kernel.cc
  paddle/phi/kernels/funcs/compare_functors.h
  paddle/phi/kernels/kps/compare_kernel.cu
  paddle/phi/kernels/legacy/cpu/compare_kernel.cc
  paddle/phi/kernels/legacy/kps/compare_kernel.cu
  python/paddle/tensor/logic.py
  test/legacy_test/test_compare_complex_op.py
Labels: contributor

#72632 [CI] coverage download
  .github/actions/rerun-workflow/rerun.sh
  .github/workflows/Coverage.yml
  .github/workflows/_Clone-linux.yml
  .github/workflows/_Inference.yml
  .github/workflows/_Linux-XPU.yml
  .github/workflows/re-run.yml
Labels: skip-ci: all

#72657 Fix typo in grad_scaler.py
  python/paddle/amp/grad_scaler.py
Labels: contributor, HappyOpenSource

#72659 Update tensor_patch_methods.py
  python/paddle/base/dygraph/tensor_patch_methods.py
  python/paddle/pir/math_op_patch.py
Labels: contributor, HappyOpenSource

#72658 Fix parameter name in dygraph/base.py
  python/paddle/base/dygraph/base.py
Labels: contributor, HappyOpenSource

#72660 Update python/paddle/base/backward.py
  python/paddle/base/backward.py
  python/paddle/base/compiler.py
Labels: contributor, HappyOpenSource

#72661 Update base/framework.py
  python/paddle/base/framework.py
Labels: contributor, HappyOpenSource

#72656 Fix example output in amp/debugging.py
  python/paddle/amp/debugging.py
Labels: contributor, HappyOpenSource

#72499 [Auto Parallel] Add spmd rule No.1 for topk and topk_grad ops
  paddle/phi/infermeta/spmd_rules/rules.cc
  paddle/phi/infermeta/spmd_rules/rules.h
  paddle/phi/infermeta/spmd_rules/topk.cc
  paddle/phi/infermeta/spmd_rules/topk.h
  paddle/phi/ops/yaml/backward.yaml
  paddle/phi/ops/yaml/ops.yaml
  test/auto_parallel/spmd_rules/CMakeLists.txt
  test/auto_parallel/spmd_rules/test_topk_rule.py
  test/cpp/auto_parallel/spmd_rule_test.cc
Labels: contributor, HappyOpenSource

#72673 [CI] docker first
  .github/workflows/Build-develop.yml
  .github/workflows/CI.yml
  .github/workflows/Coverage.yml
  .github/workflows/_Distribute-stable.yml
  .github/workflows/_Inference.yml
  .github/workflows/_Linux-CPU.yml
  .github/workflows/_Linux-build.yml
  .github/workflows/_SOT.yml
  .github/workflows/_Static-Check.yml
  .github/workflows/docker.yml
Labels: skip-ci: sot, skip-ci: coverage, skip-ci: mac, skip-ci: xpu, skip-ci: inference, skip-ci: build

#72647 [CI] Add Api-Benchmark
  .github/workflows/CI.yml
  .github/workflows/_Api-Benchmark.yml
Labels: skip-ci: sot, skip-ci: approval, skip-ci: coverage, skip-ci: xpu, skip-ci: inference, skip-ci: distribute, skip-ci: static-check

#72570 【Paddle Tensor 第二期 API支持 0-size Tensor】Fix frobenius_norm to support 0-size tensor
  paddle/phi/kernels/gpu/frobenius_norm_kernel.cu
  paddle/phi/kernels/impl/frobenius_norm_kernel_impl.h
  test/legacy_test/test_norm_all.py
Labels: contributor, HappyOpenSource

#72696 [CI] Add CE-CINN-Framework
  .github/workflows/Build-develop.yml
  .github/workflows/CI.yml
  .github/workflows/_CE-CINN-Framework.yml
  .github/workflows/docker.yml
  .github/workflows/re-run.yml
  ci/ce_cinn_diff.sh
Labels: skip-ci: sot, skip-ci: coverage, skip-ci: mac, skip-ci: xpu, skip-ci: inference, skip-ci: distribute, skip-ci: static-check

#72631 [SOT][PIR] Mark `item` to breakgraph && add unittest of tensor array related APIs
  python/paddle/jit/sot/utils/paddle_api_config.py
  python/paddle/pir/math_op_patch.py
  test/dygraph_to_static/test_item.py
  test/legacy_test/test_math_op_patch_pir.py
  test/sot/test_sot_tensor_array.py
Labels: contributor

#72388 [spmd_rules] Add SPMD rules for ArgSort operator
  paddle/phi/infermeta/spmd_rules/argsort.cc
  paddle/phi/infermeta/spmd_rules/argsort.h
  paddle/phi/infermeta/spmd_rules/rules.cc
  paddle/phi/infermeta/spmd_rules/rules.h
  paddle/phi/ops/yaml/backward.yaml
  paddle/phi/ops/yaml/ops.yaml
  test/auto_parallel/spmd_rules/CMakeLists.txt
  test/auto_parallel/spmd_rules/test_argsort_rule.py
  test/cpp/auto_parallel/spmd_rule_test.cc
Labels: contributor

#72564 [SOT][FasterGuard] `ShapeMatchGuard` support dynamic shape
  paddle/fluid/pybind/sot/guards.cc
  paddle/fluid/pybind/sot/guards.h
Labels: contributor

#72771 test=document_fix
  .github/workflows/re-run.yml
Labels: skip-ci: sot, skip-ci: inference

#72757 [API] Fix the out of bounds issue with paddle.take_along_axis
  paddle/phi/kernels/funcs/gather_scatter_functor.cu
Labels: contributor

#72769 Fix typos UNKNOW UNKNOWN
  paddle/fluid/pybind/sot/eval_frame_tools.cc
  paddle/phi/core/framework/dense_tensor_serialize.cc
  paddle/phi/core/framework/selected_rows_serialize.cc
Labels: contributor, HappyOpenSource

#72723 [Distributed] resolve Python Logger warnings
  python/paddle/distributed/utils/process_utils.py
  test/ps/ps_dnn_trainer.py
Labels: contributor, HappyOpenSource

#72762 [XPU] fix int64 index bug of masked_select
  paddle/phi/kernels/xpu/masked_select_kernel.cc
  paddle/phi/kernels/xpu/warpctc_kernel.cc
Labels: XPU

#72559 [SOT][Exception][3.10-] Add exception handler for Py3.10-
  python/paddle/jit/sot/opcode_translator/executor/exception_stack.py
  python/paddle/jit/sot/opcode_translator/executor/opcode_executor.py
  python/paddle/jit/sot/opcode_translator/executor/variable_dispatch.py
  python/paddle/jit/sot/opcode_translator/executor/variables/__init__.py
  python/paddle/jit/sot/opcode_translator/executor/variables/basic.py
  python/paddle/jit/sot/opcode_translator/executor/variables/callable.py
  test/sot/test_23_super.py
  test/sot/test_24_exceptions.py
  test/sot/test_sot_exception.py
Labels: contributor

#72634 [PHI] Fix shape int overflow for flatten and split
  paddle/fluid/primitive/decomp_rule/decomp_rule/composite.h
  paddle/phi/infermeta/unary.cc
Labels: contributor

#72706 [Phi]Fix bincount kernel for big tensor
  paddle/phi/kernels/cpu/bincount_kernel.cc
  paddle/phi/kernels/gpu/bincount_kernel.cu
  test/legacy_test/test_bincount_op.py
Labels: contributor

#72721 [0-size Tensor No.27、290] Add 0-size Tensor support for broadcast_to API.
  paddle/phi/kernels/gpu/expand_grad_kernel.cu
  paddle/phi/kernels/impl/expand_grad_kernel_impl.h
  paddle/phi/kernels/onednn/expand_grad_kernel.cc
  paddle/phi/kernels/onednn/expand_kernel.cc
  test/legacy_test/test_expand_v2_op.py
  test/mkldnn/test_expand_v2_mkldnn_op.py
Labels: skip-ci: approval

#72778 Update 12.9 setup.py
  python/setup.py.in
  setup.py
Labels: skip-ci: approval

#72677 [Auto Parallel] Add spmd_rule for five backward ops(round_grad, trunc_grad, ceil_grad, floor_grad, poisson_grad).
  paddle/phi/infermeta/spmd_rules/elementwise.cc
  paddle/phi/infermeta/spmd_rules/elementwise.h
  paddle/phi/ops/yaml/backward.yaml
  test/cpp/auto_parallel/spmd_rule_test.cc
Labels: contributor

#72787 [XPU] improve error print format for some kernels
  paddle/phi/backends/gpu/cuda/gpu_event_timer.cc
  paddle/phi/infermeta/multiary.cc
  paddle/phi/infermeta/spmd_rules/argsort.cc
  paddle/phi/infermeta/spmd_rules/topk.cc
  paddle/phi/kernels/cpu/lu_solve_kernel.cc
  paddle/phi/kernels/cpu/svdvals_kernel.cc
  paddle/phi/kernels/funcs/index_put_utils.h
  paddle/phi/kernels/gpu/ap_variadic_kernel.cu
  paddle/phi/kernels/gpu/lu_solve_kernle.cu
  paddle/phi/kernels/selected_rows/xpu/adam_kernel.cc
  paddle/phi/kernels/xpu/adam_kernel.cc
  paddle/phi/kernels/xpu/adamw_kernel.cc
  paddle/phi/kernels/xpu/gather_grad_kernel.cc
  paddle/phi/kernels/xpu/gather_kernel.cc
  paddle/phi/kernels/xpu/p_recv_kernel.cc
  paddle/phi/kernels/xpu/p_send_kernel.cc
  paddle/phi/kernels/xpu/pool_kernel.cc
  paddle/phi/kernels/xpu/stack_grad_kernel.cc
Labels: XPU

#72815 [API]Fix the out of bounds issue and the missing of float16 with padd…
  paddle/phi/kernels/gpu/trunc_kernel.cu
  python/paddle/tensor/math.py
Labels: contributor

#72807 [0-size Tensor No.92、94-97] Add 0-size Tensor support for isfinite/isinf/isnan
  paddle/phi/kernels/impl/isfinite_kernel_impl.h
  paddle/phi/kernels/selected_rows/impl/isfinite_kernel_impl.h
  paddle/phi/kernels/xpu/isfinite_kernel.cc
  test/legacy_test/test_isfinite_v2_op.py
Labels: contributor, HappyOpenSource Pro

#72799 [0-size Tensor No.41、125] Add 0-size Tensor support for cumsum
  paddle/phi/kernels/cpu/cum_kernel.cc
  paddle/phi/kernels/gpu/cum_kernel.cu
  paddle/phi/kernels/impl/logcumsumexp_grad_impl.h
  paddle/phi/kernels/xpu/cum_kernel.cc
  test/legacy_test/test_cumsum_op.py
  test/legacy_test/test_logcumsumexp_op.py
Labels: contributor, HappyOpenSource Pro

#72813 add workflow to compare DEVELOP_VERSION and RELEASE_VERSION in PIR CM…
  .github/workflows/validate-pir-versions.yml
Labels: contributor

#72823 [SOT][FasterGuard] add `IsDenseTensorHoldAllocationMatchGuard`
  paddle/fluid/pybind/jit.cc
  paddle/fluid/pybind/sot/guards.cc
  paddle/fluid/pybind/sot/guards.h
  python/paddle/jit/sot/opcode_translator/executor/variables/basic.py
  test/sot/test_faster_guard.py
Labels: contributor

#72788 [PHI] implement masked_fill_op and optimize bool setitem indexing
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/same_operands_result.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/same_operands_result.h
  paddle/fluid/pybind/eager_method.cc
  paddle/fluid/pybind/slice_utils.h
  paddle/phi/infermeta/binary.cc
  paddle/phi/infermeta/binary.h
  paddle/phi/kernels/cpu/masked_fill_grad_kernel.cc
  paddle/phi/kernels/cpu/masked_fill_kernel.cc
  paddle/phi/kernels/funcs/masked_fill_utils.h
  paddle/phi/kernels/gpu/masked_fill_grad_kernel.cu
  paddle/phi/kernels/gpu/masked_fill_kernel.cu
  paddle/phi/kernels/masked_fill_grad_kernel.h
  paddle/phi/kernels/masked_fill_kernel.h
  paddle/phi/ops/yaml/backward.yaml
  paddle/phi/ops/yaml/ops.yaml
  python/paddle/tensor/manipulation.py
Labels: contributor

#72837 [0-size Tensor No.8] Add 0-size Tensor support for angle
  paddle/phi/kernels/impl/angle_grad_kernel_impl.h
  paddle/phi/kernels/impl/angle_kernel_impl.h
  test/legacy_test/test_angle_op.py
Labels: contributor, HappyOpenSource Pro

#72852 [XPU] support top_k_grad
  paddle/phi/backends/xpu/xpu3_op_list.cc
  paddle/phi/kernels/xpu/top_k_grad_kernel.cc
  test/xpu/test_top_k_op_xpu.py
Labels: XPU

#72856 [3.8] Remove `undef copysign` macros
  paddle/fluid/eager/auto_code_generator/generator/python_c_gen.py
  paddle/fluid/eager/pylayer/py_layer_node.h
  paddle/fluid/framework/io/shell.h
  paddle/fluid/pir/dialect/op_generator/python_c_gen.py
  paddle/fluid/pybind/communication.cc
  paddle/fluid/pybind/communication.h
  paddle/fluid/pybind/communicator_py.cc
  paddle/fluid/pybind/communicator_py.h
  paddle/fluid/pybind/compiled_program.cc
  paddle/fluid/pybind/const_value.h
  paddle/fluid/pybind/eager.cc
  paddle/fluid/pybind/eager.h
  paddle/fluid/pybind/eager_functions.cc
  paddle/fluid/pybind/eager_math_op_patch.cc
  paddle/fluid/pybind/eager_method.cc
  paddle/fluid/pybind/eager_properties.cc
  paddle/fluid/pybind/eager_py_layer.cc
  paddle/fluid/pybind/eager_utils.cc
  paddle/fluid/pybind/eager_utils.h
  paddle/fluid/pybind/exception.h
  paddle/fluid/pybind/gloo_context_py.cc
  paddle/fluid/pybind/gloo_context_py.h
  paddle/fluid/pybind/imperative.cc
  paddle/fluid/pybind/imperative.h
  paddle/fluid/pybind/io.h
  paddle/fluid/pybind/jit.h
  paddle/fluid/pybind/place.cc
  paddle/fluid/pybind/protobuf.h
  paddle/fluid/pybind/pybind.cc
  paddle/fluid/pybind/pybind_variant_caster.h
  paddle/fluid/pybind/slice_utils.h
  paddle/fluid/pybind/tensor.cc
  paddle/fluid/pybind/tensor_py.h
  paddle/fluid/pybind/uva_utils.h
Labels: contributor, skip-ci: approval

#72854 [3.8] Remove Python 3.8 support speification in `setup.py`
  python/setup.py.in
  setup.py
Labels: skip-ci: approval

#72858 Fix typos eaqul equal
  paddle/phi/kernels/sparse/gpu/addmm_kernel.cu
  paddle/phi/kernels/sparse/gpu/conv_kernel.cu
  paddle/phi/kernels/sparse/gpu/conv_kernel_igemm.cu
  paddle/phi/kernels/sparse/gpu/convolution.cu.h
  paddle/phi/kernels/sparse/gpu/matmul_kernel.cu
  paddle/phi/kernels/sparse/gpu/mv_kernel.cu
  paddle/phi/kernels/sparse/gpu/slice_grad_kernel.cu
  paddle/phi/kernels/stride/strided_slice_kernel.cc
Labels: contributor, HappyOpenSource

#72873 [Typing][3.8] Remove `Literal` conversion in stubgen for python 3.8
  tools/gen_tensor_stub.py
Labels: contributor

#72870 [3.8] Remove unused dependency `astor`
  paddle/scripts/conda_build.py
  pyproject.toml
  python/paddle/jit/api.py
  python/paddle/jit/dy2static/ast_utils.py
  python/requirements.txt
  test/dygraph_to_static/test_program_translator.py
  tools/cinn/docker/requirements.txt
Labels: contributor

#72868 [SOT][3.8] Cleanup `eval_frame` python3.9- code
  paddle/fluid/pybind/sot/eval_frame.c
  paddle/fluid/pybind/sot/guards.cc
  paddle/fluid/pybind/sot/macros.h
  test/dygraph_to_static/test_eval_frame.py
Labels: contributor

#72896 [CodeStyle][Ruff] Introduce rule `B005` and fix discovered bugs
  ci/coverage_diff.py
  paddle/fluid/eager/auto_code_generator/generator/python_c_gen.py
  pyproject.toml
  python/paddle/distributed/fleet/meta_optimizers/sharding/fp16_helper.py
  python/paddle/distributed/fleet/meta_optimizers/sharding/gradient_clip_helper.py
  python/paddle/distributed/launch/controllers/master.py
  python/paddle/distributed/launch/main.py
  tools/check_api_yaml_same.py
  tools/coverage/coverage_diff.py
Labels: contributor, skip-ci: approval

#72826 [0-size Tensor No.76-79] Add 0-size Tensor support for i0
  paddle/phi/kernels/cpu/i0_grad_kernel.cc
  paddle/phi/kernels/cpu/i0_kernel.cc
  paddle/phi/kernels/cpu/i0e_grad_kernel.cc
  paddle/phi/kernels/cpu/i0e_kernel.cc
  paddle/phi/kernels/cpu/i1_grad_kernel.cc
  paddle/phi/kernels/cpu/i1_kernel.cc
  paddle/phi/kernels/cpu/i1e_grad_kernel.cc
  paddle/phi/kernels/cpu/i1e_kernel.cc
  test/legacy_test/test_i0_op.py
  test/legacy_test/test_i0e_op.py
  test/legacy_test/test_i1_op.py
  test/legacy_test/test_i1e_op.py
  test/white_list/op_accuracy_white_list.py
Labels: contributor, HappyOpenSource Pro

#72866 [0-size Tensor No.32、294] Add 0-size Tensor support for clip
  test/legacy_test/test_clip_op.py
Labels: contributor, HappyOpenSource Pro

#72903 [CI] api-bm fix
  .github/workflows/_Api-Benchmark.yml
Labels: skip-ci: sot, skip-ci: coverage, skip-ci: all, skip-ci: xpu, skip-ci: inference, skip-ci: distribute, skip-ci: static-check

#72900 fix slice
  .github/workflows/_Slice.yml
Labels: skip-ci: sot, skip-ci: approval, skip-ci: coverage, skip-ci: xpu, skip-ci: inference, skip-ci: distribute, skip-ci: static-check, skip-ci: api-benchmark

#72784 [SOT][Exception] Add exception test && fix some param annotation
  python/paddle/jit/sot/opcode_translator/executor/exception_stack.py
  python/paddle/jit/sot/opcode_translator/executor/opcode_executor.py
  python/paddle/jit/sot/opcode_translator/executor/variable_dispatch.py
  python/paddle/jit/sot/opcode_translator/executor/variables/basic.py
  python/paddle/jit/sot/opcode_translator/executor/variables/callable.py
  python/paddle/jit/sot/opcode_translator/instruction_utils/opcode_info.py
  python/paddle/jit/sot/opcode_translator/skip_files.py
  python/paddle/jit/sot/utils/exceptions.py
  test/sot/test_24_exceptions.py
Labels: contributor

#72819 [Prim][Decomp] masked_fill bug fix
  paddle/fluid/prim/api/composite_backward/composite_backward_api.h
  paddle/fluid/pybind/eager_method.cc
  paddle/fluid/pybind/slice_utils.h
  paddle/phi/infermeta/binary.cc
  paddle/phi/kernels/gpu/masked_fill_kernel.cu
  paddle/phi/ops/yaml/backward.yaml
  python/paddle/tensor/manipulation.py
  test/legacy_test/test_masked_fill.py
Labels: contributor

#72935 [CodeStyle][Ruff] Update target version to py39
  paddle/fluid/eager/auto_code_generator/generator/codegen_utils.py
  paddle/fluid/eager/auto_code_generator/generator/eager_gen.py
  paddle/fluid/eager/auto_code_generator/generator/python_c_gen.py
  pyproject.toml
  python/paddle/__init__.py
  python/paddle/_typing/basic.py
  python/paddle/_typing/dtype_like.py
  python/paddle/_typing/shape.py
  python/paddle/amp/auto_cast.py
  python/paddle/base/core.py
  python/paddle/base/data_feeder.py
  python/paddle/distributed/communication/batch_isend_irecv.py
  python/paddle/hapi/model.py
  python/paddle/incubate/autograd/functional.py
  python/paddle/io/dataloader/batch_sampler.py
  python/paddle/io/dataloader/dataset.py
  python/paddle/jit/sot/opcode_translator/executor/dispatcher.py
  python/paddle/jit/sot/opcode_translator/executor/executor_cache.py
  python/paddle/jit/sot/opcode_translator/executor/function_graph.py
  python/paddle/jit/sot/utils/envs.py
  python/paddle/nn/layer/layers.py
  python/paddle/reader/decorator.py
  python/paddle/utils/environments.py
  python/paddle/vision/datasets/cifar.py
  python/paddle/vision/datasets/flowers.py
  python/paddle/vision/datasets/folder.py
  python/paddle/vision/datasets/mnist.py
  python/paddle/vision/datasets/voc2012.py
  test/dygraph_to_static/check_approval.py
  test/dygraph_to_static/dygraph_to_static_utils.py
  tools/coverage/coverage_diff.py
  tools/coverage/coverage_diff_list.py
Labels: contributor, skip-ci: approval

#72894 [Accuracy diff No.21] Fix accuracy diff for heaviside API
  paddle/phi/kernels/cpu/elementwise_kernel.cc
  paddle/phi/kernels/funcs/elementwise_functor.h
  test/legacy_test/test_elementwise_heaviside_op.py
Labels: contributor, HappyOpenSource Pro

#72889 [0-size Tensor No.129、316] Add 0-size Tensor support for logit
  test/legacy_test/test_logit_op.py
Labels: contributor, HappyOpenSource Pro, skip-ci: api-benchmark

#72800 [0-size Tensor No.39、40] Add 0-size Tensor support for cummin/cummax
  paddle/phi/kernels/cpu/cum_maxmin_kernel.cc
  paddle/phi/kernels/gpu/cum_maxmin_grad_kernel.cu
  paddle/phi/kernels/gpu/cum_maxmin_kernel.cu
  test/legacy_test/test_cummax_op.py
  test/legacy_test/test_cummin_op.py
Labels: contributor, HappyOpenSource Pro, skip-ci: all

#72920 [0-size Tensor No.93] Add 0-size Tensor support for isin
  test/legacy_test/test_isin.py
Labels: contributor, HappyOpenSource Pro

#72836 Fix xpu paddlex
  .github/workflows/_Linux-XPU.yml
  paddle/scripts/paddle_build.sh
Labels: skip-ci: approval

#72944 [PHI]Add non-bool mask cast
  paddle/phi/kernels/gpu/masked_fill_grad_kernel.cu
  python/paddle/tensor/manipulation.py
Labels: contributor

#72921 [0-size Tensor No.121-123、314、315] Add 0-size Tensor support for log10
  test/legacy_test/test_activation_op.py
Labels: contributor, HappyOpenSource Pro

#72898 [0-size Tensor No.44、297] Add 0-size Tensor support for diag_embed
  paddle/phi/kernels/impl/diag_embed_impl.h
  test/legacy_test/test_diag_embed.py
Labels: contributor, HappyOpenSource Pro, skip-ci: xpu

#72967 [CI] xpu env
  .github/workflows/Build-develop.yml
  .github/workflows/_Linux-XPU.yml
  ci/kunlun_test.sh
  ci/run_setup.sh
  ci/utils.sh
Labels: skip-ci: sot, skip-ci: approval, skip-ci: coverage, skip-ci: mac, skip-ci: inference, skip-ci: distribute, skip-ci: static-check, skip-ci: build, skip-ci: cpu, skip-ci: npu, skip-ci: ce-cinn-framework, skip-ci: ce-framework, skip-ci: api-benchmark

#72814 [0-size Tensor No.343, 350, 351] Add 0-size Tensor support for paddle.tril paddle.Tensor.tril paddle.triu API.
  paddle/phi/kernels/impl/tril_triu_grad_kernel_impl.h
  paddle/phi/kernels/impl/tril_triu_kernel_impl.h
  paddle/phi/kernels/xpu/tril_triu_grad_kernel.cc
  paddle/phi/kernels/xpu/tril_triu_kernel.cc
  test/legacy_test/test_tril_triu_op.py
Labels: contributor, HappyOpenSource Pro

#72816 refine eager backward
  paddle/fluid/eager/backward.cc
Labels: skip-ci: all, skip-ci: distribute, skip-ci: api-benchmark

#72978 Fix compilation bug on CUDA 12.9
  cmake/cinn/core.cmake
  cmake/generic.cmake
Labels: skip-ci: xpu

#72995 disable xpu paddlex
  .github/workflows/_Linux-XPU.yml
Labels: skip-ci: all

#72842 [weight_only_linear]decrease code
  paddle/phi/kernels/fusion/cutlass/cutlass_extensions/gemm/kernel/mixed_gemm_B_layout.h
Labels: skip-ci: xpu

#72753 Fix expand_as and expand_as_grad kernel for big tensor
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/binary_infer_sym.cc
  paddle/fluid/pir/serialize_deserialize/patch/0.yaml
  paddle/phi/api/generator/dist_api_gen.py
  paddle/phi/infermeta/binary.cc
  paddle/phi/infermeta/binary.h
  paddle/phi/kernels/expand_as_grad_kernel.h
  paddle/phi/kernels/expand_as_kernel.h
  paddle/phi/kernels/gpu/expand_as_grad_kernel.cu
  paddle/phi/kernels/gpu/expand_as_kernel.cu
  paddle/phi/kernels/impl/expand_as_grad_kernel_impl.h
  paddle/phi/kernels/impl/expand_as_kernel_impl.h
  paddle/phi/kernels/impl/solve_kernel_impl.h
  paddle/phi/kernels/xpu/expand_as_kernel.cc
  paddle/phi/ops/yaml/backward.yaml
  paddle/phi/ops/yaml/legacy/backward_exclude.yaml
  paddle/phi/ops/yaml/legacy/ops_exclude.yaml
  paddle/phi/ops/yaml/legacy/static_backward.yaml
  paddle/phi/ops/yaml/legacy/static_ops.yaml
  paddle/phi/ops/yaml/ops.yaml
  test/ir/pir/cinn/symbolic/test_infer_sym_shape_binary_op.py
Labels: contributor

#72919 [0-size Tensor No.29] Add 0-size Tensor support for cartesian_prod
  test/legacy_test/test_cartesian_prod.py
Labels: contributor, HappyOpenSource Pro

#72820 [0-size Tensor No.5] Add 0-size Tensor support for allclose
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/binary_infer_sym.cc
  paddle/phi/infermeta/binary.cc
  paddle/phi/kernels/cpu/allclose_kernel.cc
  paddle/phi/kernels/gpu/allclose_kernel.cu
  test/legacy_test/test_allclose_op.py
Labels: contributor, HappyOpenSource Pro

#72824 [Auto Parallel] Add spmd rule No.6 for unique ops.
  paddle/fluid/pybind/auto_parallel_py.cc
  paddle/phi/core/distributed/auto_parallel/inferspmd_utils.cc
  paddle/phi/infermeta/spmd_rules/rules.cc
  paddle/phi/infermeta/spmd_rules/rules.h
  paddle/phi/infermeta/spmd_rules/unique.cc
  paddle/phi/infermeta/spmd_rules/unique.h
  paddle/phi/ops/yaml/inconsistent/dygraph_ops.yaml
  paddle/phi/ops/yaml/inconsistent/static_ops.yaml
  test/auto_parallel/spmd_rules/CMakeLists.txt
  test/auto_parallel/spmd_rules/test_unique_rule.py
  test/cpp/auto_parallel/spmd_rule_test.cc
Labels: contributor, HappyOpenSource Pro, skip-ci: xpu

#72931 [BIT] Fix paddle.unstack api for big tensor
  paddle/phi/infermeta/backward.cc
  paddle/phi/infermeta/unary.cc
  paddle/phi/kernels/funcs/stack_and_unstack.h
  paddle/phi/kernels/impl/unstack_grad_kernel_impl.h
Labels: contributor, skip-ci: xpu

#72975 [0-size Tensor No.229] Add 0-size Tensor support for temporal_shift
  paddle/phi/kernels/cpu/temporal_shift_grad_kernel.cc
  paddle/phi/kernels/cpu/temporal_shift_kernel.cc
  paddle/phi/kernels/gpu/temporal_shift_grad_kernel.cu
  paddle/phi/kernels/gpu/temporal_shift_kernel.cu
  paddle/phi/kernels/xpu/temporal_shift_grad_kernel.cc
  paddle/phi/kernels/xpu/temporal_shift_kernel.cc
  test/legacy_test/test_temporal_shift_op.py
Labels: contributor, HappyOpenSource Pro

#72805 supports fa3_varlen api
  paddle/phi/kernels/gpu/flash_attn_v3_kernel.cu
  paddle/phi/kernels/gpu/flash_attn_v3_kernel.h
  paddle/phi/ops/yaml/ops.yaml
  python/paddle/nn/functional/__init__.py
  python/paddle/nn/functional/flash_attention.py
  test/legacy_test/test_flash_attention.py
Labels: skip-ci: approval, skip-ci: api-benchmark

#72872 [0-size Tensor No.11、262、287] Add 0-size Tensor support for argsort/sort API.
  paddle/phi/kernels/xpu/argsort_kernel.cc
  test/xpu/test_argsort_op_xpu.py
Labels: contributor, HappyOpenSource Pro

#73012 [Accuracy diff No.57、69] Fix accuracy diff for sum API
  paddle/phi/kernels/cpu/reduce_sum_kernel.cc
  test/legacy_test/test_reduce_op.py
Labels: contributor, HappyOpenSource Pro

#72993 [0-size Tensor No.184] Add 0-size Tensor support for label_smooth
  test/legacy_test/test_label_smooth_op.py
Labels: contributor, HappyOpenSource Pro

#72972 [0-size Tensor No.174] Add 0-size Tensor support for grid_sample
  paddle/phi/kernels/cpu/grid_sample_grad_kernel.cc
  paddle/phi/kernels/cpu/grid_sample_kernel.cc
  paddle/phi/kernels/gpu/grid_sample_grad_kernel.cu
  paddle/phi/kernels/gpu/grid_sample_kernel.cu
  paddle/phi/kernels/xpu/grid_sample_grad_kernel.cc
  paddle/phi/kernels/xpu/grid_sample_kernel.cc
  test/legacy_test/test_grid_sampler_op.py
Labels: contributor, HappyOpenSource Pro, skip-ci: xpu
