Repository PaddlePaddle/Paddle, pull requests merged in 2025-03, with the labels that each got.

#71337 【dcu】dcu cutlass fa
  cmake/external/flashattn.cmake
  paddle/phi/kernels/gpu/flash_attn_grad_kernel.cu
  paddle/phi/kernels/gpu/flash_attn_kernel.cu
Labels: contributor

#71350 Fix typos shoulde should
  paddle/cinn/hlir/framework/pir/trivial_op_util.cc
  paddle/phi/core/distributed/auto_parallel/placement_types.cc
  paddle/phi/kernels/funcs/blas/blaslt_gemm_search.h
  paddle/phi/kernels/funcs/distribution_helper.h
  paddle/phi/kernels/funcs/jit/gen/seqpool.h
  paddle/phi/kernels/funcs/stack_and_unstack.h
  paddle/phi/kernels/fusion/cutlass/memory_efficient_attention/iterators/epilogue_predicated_tile_iterator.h
  paddle/phi/kernels/fusion/gpu/masked_multihead_attention_kernel.cu
  paddle/phi/kernels/gpu/lars_momentum_kernel.cu
  paddle/phi/kernels/gpu/multinomial_kernel.cu
  paddle/phi/kernels/gpu/qr_kernel.cu
Labels: contributor, HappyOpenSource

#71212 [xpu] support: each parameter has different lr in merged_momentum
  paddle/phi/kernels/xpu/merged_momentum_kernel.cc
  test/xpu/test_merged_momentum_op_xpu.py
  test/xpu/test_merged_momentum_op_xpu_base.py
Labels: contributor

#71412 [SOT] `GraphLogger`->`SubGraphInfo` to collect graph info
  python/paddle/jit/sot/symbolic/compile_cache.py
  python/paddle/jit/sot/translate.py
  python/paddle/jit/sot/utils/__init__.py
  python/paddle/jit/sot/utils/info_collector.py
  python/paddle/jit/sot/utils/utils.py
Labels: contributor

#71361 [XPU] reduce_xxx and broadcast_xxx use int64_t shape
  paddle/phi/kernels/funcs/fused_gemm_epilogue_xpu.h
  paddle/phi/kernels/fusion/xpu/fused_feedforward_grad_kernel.cc
  paddle/phi/kernels/legacy/xpu/compare_kernel.cc
  paddle/phi/kernels/legacy/xpu/elementwise_add_kernel.cc
  paddle/phi/kernels/legacy/xpu/elementwise_divide_kernel.cc
  paddle/phi/kernels/legacy/xpu/elementwise_kernel.cc
  paddle/phi/kernels/legacy/xpu/elementwise_multiply_kernel.cc
  paddle/phi/kernels/legacy/xpu/elementwise_subtract_kernel.cc
  paddle/phi/kernels/legacy/xpu/reduce_max_kernel.cc
  paddle/phi/kernels/xpu/activation_grad_kernel.cc
  paddle/phi/kernels/xpu/addmm_grad_kernel.cc
  paddle/phi/kernels/xpu/affine_channel_grad_kernel.cc
  paddle/phi/kernels/xpu/affine_channel_kernel.cc
  paddle/phi/kernels/xpu/batch_norm_grad_kernel.cc
  paddle/phi/kernels/xpu/c_softmax_with_cross_entropy_kernel.cc
  paddle/phi/kernels/xpu/compare_kernel.cc
  paddle/phi/kernels/xpu/elementwise.h
  paddle/phi/kernels/xpu/elementwise_add_grad_kernel.cc
  paddle/phi/kernels/xpu/elementwise_add_kernel.cc
  paddle/phi/kernels/xpu/elementwise_divide_grad_kernel.cc
  paddle/phi/kernels/xpu/elementwise_divide_kernel.cc
  paddle/phi/kernels/xpu/elementwise_grad_kernel.cc
  paddle/phi/kernels/xpu/elementwise_kernel.cc
  paddle/phi/kernels/xpu/elementwise_multiply_grad_kernel.cc
  paddle/phi/kernels/xpu/elementwise_multiply_kernel.cc
  paddle/phi/kernels/xpu/elementwise_subtract_grad_kernel.cc
  paddle/phi/kernels/xpu/elementwise_subtract_kernel.cc
  paddle/phi/kernels/xpu/fused_attention_grad_kernel.cc
  paddle/phi/kernels/xpu/fused_attention_kernel.cc
  paddle/phi/kernels/xpu/gather_nd_grad_kernel.cc
  paddle/phi/kernels/xpu/gather_nd_kernel.cc
  paddle/phi/kernels/xpu/matmul_grad_kernel.cc
  paddle/phi/kernels/xpu/mean_all_kernel.cc
  paddle/phi/kernels/xpu/p_norm_grad_kernel.cc
  paddle/phi/kernels/xpu/p_norm_kernel.cc
  paddle/phi/kernels/xpu/pool_grad_kernel.cc
  paddle/phi/kernels/xpu/prod_kernel.cc
  paddle/phi/kernels/xpu/reduce.h
  paddle/phi/kernels/xpu/reduce_all_kernel.cc
  paddle/phi/kernels/xpu/reduce_any_kernel.cc
  paddle/phi/kernels/xpu/reduce_max_grad_kernel.cc
  paddle/phi/kernels/xpu/reduce_max_kernel.cc
  paddle/phi/kernels/xpu/reduce_mean_grad_kernel.cc
  paddle/phi/kernels/xpu/reduce_mean_kernel.cc
  paddle/phi/kernels/xpu/reduce_min_grad_kernel.cc
  paddle/phi/kernels/xpu/reduce_min_kernel.cc
  paddle/phi/kernels/xpu/reduce_sum_grad_kernel.cc
  paddle/phi/kernels/xpu/reduce_util.h
  paddle/phi/kernels/xpu/rms_norm_kernel.cc
  paddle/phi/kernels/xpu/set_value_kernel.cc
  paddle/phi/kernels/xpu/tile_grad_kernel.cc
  paddle/phi/kernels/xpu/tile_kernel.cc
  paddle/phi/kernels/xpu/xpu_api_wrapper.h
Labels: XPU

#71383 Fix typos simplied simplified
  paddle/cinn/common/simplify_special_pattern.cc
  paddle/cinn/runtime/cuda/cuda_util.cc
  paddle/fluid/framework/ir/auto_mixed_precision_pass.cc
  paddle/fluid/framework/new_executor/instruction/cinn_jit_instruction.cc
  paddle/fluid/inference/tensorrt/engine.h
  paddle/fluid/pir/transforms/onednn/cpu_bfloat16_placement_pass.cc
  paddle/phi/kernels/gpu/edit_distance_kernel.cu
  python/paddle/jit/pir_dy2static/parameter_recorder.py
  python/paddle/jit/sot/opcode_translator/executor/opcode_executor.py
Labels: contributor, HappyOpenSource

#71364 [XPU] add isfinite/isinf support
  paddle/phi/backends/xpu/xpu3_op_list.cc
  paddle/phi/kernels/xpu/isfinite_kernel.cc
  test/xpu/test_isfinite_op_xpu.py
Labels: XPU

#71426 [PIR] Fix issue of no op_info when enabling oneDNN
  paddle/fluid/inference/api/analysis_predictor.cc
Labels: Intel, contributor

#71204 [CINN][new hardware] SYCL third PR: complete the SYCL logic
  paddle/cinn/backends/codegen_device_util.h
  paddle/cinn/backends/compiler.cc
  paddle/cinn/backends/compiler.h
  paddle/cinn/common/target.cc
  paddle/cinn/optim/optimize.cc
  paddle/cinn/optim/trans_buffer_with_dynamic_shape.cc
  paddle/cinn/runtime/sycl/sycl_backend_api.cc
  paddle/cinn/runtime/use_extern_funcs.h
Labels: contributor

#71430 [SOT] Add `PEP508LikeEnvironmentVariable`
  python/paddle/jit/sot/symbolic/compile_cache.py
  python/paddle/jit/sot/utils/__init__.py
  python/paddle/jit/sot/utils/envs.py
  python/paddle/jit/sot/utils/info_collector.py
  test/sot/test_envs.py
Labels: contributor

#71428 Fix typos divisble divisible
  paddle/cinn/optim/entail_loop_condition_pass.h
  paddle/fluid/eager/api/generated/eager_generated/backwards/scale_node.cc
  paddle/fluid/eager/custom_operator/custom_operator_node.cc
  paddle/fluid/operators/deformable_conv_v1_op.cc
  paddle/phi/core/distributed/auto_parallel/process_mesh.h
  paddle/phi/core/distributed/auto_parallel/reshard/global_and_sub_mesh_reshard_function.cc
  paddle/phi/kernels/gpu/grid_sample_grad_kernel.cu
  paddle/phi/kernels/gpu/grid_sample_kernel.cu
  python/paddle/base/framework.py
  test/cpp/inference/api/analyzer_transformer_tester_helper.h
  test/cpp/inference/api/api_tester.cc
  test/ir/inference/test_quant_linear_fuse_pass.py
  test/legacy_test/test_imperative_auto_prune.py
  test/legacy_test/test_index_put_op.py
Labels: contributor, HappyOpenSource

#71396 [Inference] MoE Use macro to compress code impl
  paddle/phi/kernels/fusion/cutlass/moe/fused_moe_op.h
Labels: contributor

#71375 [XPU] add quantize_linear and dequantize_linear op
  cmake/external/xpu.cmake
  paddle/phi/backends/xpu/xpu3_op_list.cc
  paddle/phi/kernels/xpu/quantize_linear_kernel.cc
  test/xpu/test_quantize_linear_xpu.py
Labels: XPU

#71394 【快乐开源】Paddle Tensor 规范化二期：array_api_tests/test_creation_functions.py::test_arange鲁棒性增强
  paddle/phi/kernels/funcs/range_function.h
  test/legacy_test/test_arange.py
Labels: contributor, HappyOpenSource Pro

#71449 Refine license of adapted DeepEP files
  paddle/fluid/distributed/collective/deep_ep/config.hpp
  paddle/fluid/distributed/collective/deep_ep/deep_ep.cpp
  paddle/fluid/distributed/collective/deep_ep/deep_ep.hpp
  paddle/fluid/distributed/collective/deep_ep/event.hpp
  paddle/fluid/distributed/collective/deep_ep/kernels/api.cuh
  paddle/fluid/distributed/collective/deep_ep/kernels/buffer.cuh
  paddle/fluid/distributed/collective/deep_ep/kernels/configs.cuh
  paddle/fluid/distributed/collective/deep_ep/kernels/exception.cuh
  paddle/fluid/distributed/collective/deep_ep/kernels/internode.cu
  paddle/fluid/distributed/collective/deep_ep/kernels/internode_ll.cu
  paddle/fluid/distributed/collective/deep_ep/kernels/intranode.cu
  paddle/fluid/distributed/collective/deep_ep/kernels/launch.cuh
  paddle/fluid/distributed/collective/deep_ep/kernels/runtime.cu
  paddle/fluid/distributed/collective/deep_ep/kernels/utils.cuh
  python/paddle/distributed/communication/deep_ep/buffer.py
  python/paddle/distributed/communication/deep_ep/utils.py
Labels: skip-ci: sot

#71446 Fix typos sptial spatial
  paddle/cinn/ir/group_schedule/config/group_tile_config.cc
  paddle/cinn/ir/group_schedule/config/group_tile_config.h
  paddle/cinn/ir/group_schedule/tactic/align_iter_space_tactic.cc
  paddle/cinn/ir/group_schedule/tactic/compute_at_reduction_tactic.cc
  paddle/cinn/optim/rearrange_load_instruction_pass.cc
  paddle/cinn/optim/rearrange_load_instruction_pass.h
  paddle/cinn/optim/vectorize_for_trans.cc
  paddle/cinn/optim/vectorize_for_trans.h
  paddle/cinn/poly/compute_at_transform.cc
  paddle/cinn/poly/stage.cc
  paddle/cinn/pybind/ir/ir_context.h
  paddle/cinn/runtime/sycl/sycl_module.cc
  paddle/fluid/framework/ir/graph.h
  paddle/fluid/framework/ir/multihead_matmul_fuse_pass_tester.cc
Labels: contributor, HappyOpenSource

#71423 [XPU] fix batch_norm_grad when use global status
  paddle/phi/kernels/xpu/batch_norm_grad_kernel.cc
  test/xpu/test_batch_norm_op_xpu.py
Labels: contributor

#71431 [XPU] Support print runtime error log for xdnn/xfa/xpudnn error
  paddle/fluid/framework/fleet/heter_ps/heter_comm_inl.h
  paddle/phi/backends/xpu/enforce_xpu.h
  paddle/phi/backends/xpu/xpu_header.h
  paddle/phi/kernels/xpu/addmm_kernel.cc
  paddle/phi/kernels/xpu/affine_channel_grad_kernel.cc
  paddle/phi/kernels/xpu/affine_channel_kernel.cc
  paddle/phi/kernels/xpu/amp_kernel.cc
  paddle/phi/kernels/xpu/contiguous_kernel.cc
  paddle/phi/kernels/xpu/expand_as_kernel.cc
  paddle/phi/kernels/xpu/expand_kernel.cc
  paddle/phi/kernels/xpu/flash_attn_kernel.cc
  paddle/phi/kernels/xpu/label_smooth_kernel.cc
  paddle/phi/kernels/xpu/prior_box_kernel.cc
  paddle/phi/kernels/xpu/rnn_grad_kernel.cc
  paddle/phi/kernels/xpu/strided_copy_kernel.cc
  paddle/phi/kernels/xpu/top_k_kernel.cc
  test/xpu/cpp/enforce_xpu_test.cc
Labels: XPU

#71447 Modify Hook_intermidiate to Hook_intermediate
  test/cpp/eager/task_tests/hook_test_intermidiate.cc
Labels: contributor, HappyOpenSource

#71458 [SOT][3.13] Split `InlineCallBreak`
  python/paddle/jit/sot/opcode_translator/executor/opcode_executor.py
  python/paddle/jit/sot/opcode_translator/executor/variables/callable.py
  python/paddle/jit/sot/utils/exceptions.py
Labels: contributor

#71451 [XPU] add conv3d_transpose
  cmake/external/xpu.cmake
  paddle/phi/backends/xpu/xpu3_op_list.cc
  paddle/phi/kernels/xpu/conv_kernel.cc
  paddle/phi/kernels/xpu/conv_transpose_kernel.cc
  test/xpu/test_conv3d_transpose_op_xpu.py
  test/xpu/test_conv3d_transpose_part2_op_xpu.py
Labels: XPU

#71178 [XPU] feat: support xpu ipc and stream to enable zero cost checkpoint
  paddle/fluid/platform/init.cc
  paddle/fluid/pybind/tensor.cc
  paddle/fluid/pybind/xpu_streams_py.cc
  paddle/fluid/pybind/xpu_streams_py.h
  paddle/phi/backends/xpu/enforce_xpu.h
  paddle/phi/backends/xpu/xpu_context.cc
  paddle/phi/backends/xpu/xpu_context.h
  paddle/phi/backends/xpu/xpu_info.cc
  paddle/phi/backends/xpu/xpu_info.h
  paddle/phi/core/memory/allocation/CMakeLists.txt
  paddle/phi/core/memory/allocation/xpu_ipc_allocator.cc
  paddle/phi/core/memory/allocation/xpu_ipc_allocator.h
  paddle/phi/core/memory/memcpy.cc
  paddle/phi/core/xpu_cuda_stream.h
  python/paddle/incubate/multiprocessing/reductions.py
  test/xpu/test_paddle_share_xpu.py
Labels: XPU

#71492 [XPU] fix error in conv3d_transpose test
  test/xpu/test_conv3d_transpose_op_xpu.py
Labels: XPU

#71460 [SOT] Optimize env and subgraph information printing
  python/paddle/jit/sot/profiler/profiler.py
  python/paddle/jit/sot/symbolic/compile_cache.py
  python/paddle/jit/sot/utils/envs.py
  python/paddle/jit/sot/utils/info_collector.py
  python/paddle/jit/sot/utils/utils.py
  python/paddle/utils/environments.py
  test/sot/test_binary_operator_tracker.py
Labels: contributor

#71503 [Dy2St] Clear `InplaceMap` after program is completed
  python/paddle/jit/dy2static/program_translator.py
  python/paddle/jit/pir_dy2static/parameter_recorder.py
Labels: contributor

#71030 【Hackathon 8th No.1】add `lu_solve` api for paddle
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/multiary_infer_sym.cc
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/multiary_infer_sym.h
  paddle/phi/backends/dynload/cusolver.h
  paddle/phi/backends/dynload/lapack.h
  paddle/phi/backends/dynload/rocsolver.h
  paddle/phi/kernels/cpu/lu_solve_grad_kernel.cc
  paddle/phi/kernels/cpu/lu_solve_kernel.cc
  paddle/phi/kernels/funcs/lapack/lapack_function.cc
  paddle/phi/kernels/funcs/lapack/lapack_function.h
  paddle/phi/kernels/gpu/lu_solve_grad_kernel.cu
  paddle/phi/kernels/gpu/lu_solve_kernle.cu
  paddle/phi/kernels/impl/lu_solve_grad_kernel_impl.h
  paddle/phi/kernels/lu_solve_grad_kernel.h
  paddle/phi/kernels/lu_solve_kernel.h
  paddle/phi/ops/yaml/backward.yaml
  paddle/phi/ops/yaml/ops.yaml
  python/paddle/linalg.py
  python/paddle/tensor/__init__.py
  python/paddle/tensor/linalg.py
  test/legacy_test/CMakeLists.txt
  test/legacy_test/test_lu_solve_op.py
  test/white_list/no_grad_set_white_list.py
Labels: PaddlePaddle Hackathon, contributor

#71478 Modify hook_test_intermidiate to hook_test_intermediate
  test/cpp/eager/task_tests/CMakeLists.txt
  test/cpp/eager/task_tests/hook_test_intermediate.cc
Labels: contributor, HappyOpenSource

#71514 [XPU] update xhpc lib to 20250306
  cmake/external/xpu.cmake
Labels: XPU

#71546 [SOT] Remove `COST_MODEL` flag
  ci/run_sot_test.sh
  paddle/scripts/paddle_build.sh
  test/dygraph_to_static/CMakeLists.txt
  test/sot/CMakeLists.txt
Labels: contributor

#71525 [SOT] Add JSON dumping and Base64 encoding for log output
  python/paddle/jit/sot/symbolic/compile_cache.py
  python/paddle/jit/sot/utils/envs.py
  python/paddle/jit/sot/utils/info_collector.py
  test/sot/test_info_collect.py
Labels: contributor

#71568 Revert "[PHI]fix 0 size error"
  paddle/phi/infermeta/binary.cc
  paddle/phi/kernels/gpu/concat_kernel.cu
  paddle/phi/kernels/gpu/masked_select_kernel.cu
  paddle/phi/kernels/impl/repeat_interleave_kernel_impl.h
  paddle/phi/kernels/kps/reduce_kernel.cu
  python/paddle/tensor/manipulation.py
Labels: skip-ci: sot

#71557 Fix typos in quotes
  paddle/cinn/optim/replace_cross_block_reduction.h
  paddle/fluid/framework/ir/fuse_optimizer_ops_pass/fuse_optimizer_op_pass.cc
  paddle/fluid/inference/tensorrt/convert/arg_max_op.cc
  paddle/fluid/inference/tensorrt/convert/generic_and_custom_plugin_creater.cc
  paddle/fluid/inference/tensorrt/convert/set_value_op.cc
  paddle/fluid/inference/tensorrt/plugin/layernorm_shift_partition_op.cu
  paddle/fluid/operators/elementwise/elementwise_div_op.h
  paddle/fluid/operators/elementwise/elementwise_mul_op.h
  paddle/fluid/operators/elementwise/elementwise_op.h
  paddle/fluid/operators/fused/fused_matmul_op.cc
  paddle/fluid/operators/generator/templates/operator_utils.c.j2
  paddle/fluid/operators/matmul_op.cc
  paddle/fluid/pir/dialect/op_generator/op_kerneltype_gen.py
  paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/multiary_infer_sym.cc
  paddle/fluid/pir/serialize_deserialize/include/ir_serialize.h
  paddle/phi/api/include/tensor_utils.h
  paddle/phi/common/place.h
  paddle/phi/core/distributed/auto_parallel/dist_tensor.cc
  paddle/phi/core/kernel_factory.h
  paddle/phi/core/memory/allocation/system_allocator.cc
  paddle/phi/kernels/gpu/argsort_grad_kernel.cu
  paddle/phi/kernels/gpu/argsort_kernel.cu
  paddle/phi/kernels/gpu/cum_kernel.cu
  paddle/phi/kernels/onednn/elementwise_kernel.cc
  paddle/phi/kernels/onednn/matmul_kernel.cc
Labels: contributor, HappyOpenSource

#71239 [SOT][Faster Guard] add `ENV_SOT_ENABLE_STRICT_GUARD_CHECK`
  ci/run_sot_test.sh
  paddle/fluid/pybind/sot/guards.h
  paddle/scripts/paddle_build.sh
  python/paddle/jit/sot/opcode_translator/executor/executor_cache.py
  python/paddle/jit/sot/opcode_translator/executor/guard.py
  python/paddle/jit/sot/opcode_translator/executor/variables/callable.py
  python/paddle/jit/sot/opcode_translator/executor/variables/container.py
  python/paddle/jit/sot/utils/__init__.py
  python/paddle/jit/sot/utils/envs.py
  test/sot/CMakeLists.txt
  test/sot/test_case_base.py
  test/sot/test_instruction_translator_cache.py
Labels: contributor

#71243 【Hackathon 8th No.3】clean oldIR in api.py -part
  python/paddle/distributed/auto_parallel/api.py
  test/auto_parallel/hybrid_strategy/CMakeLists.txt
  test/auto_parallel/hybrid_strategy/test_semi_auto_parallel_llama_model.py
  test/auto_parallel/hybrid_strategy/testslist.csv
Labels: PaddlePaddle Hackathon, contributor

#71609 Fix typos nume num
  paddle/common/flags.cc
  paddle/fluid/eager/utils.cc
  test/ir/pir/fused_pass/onednn/test_reshape_transpose_matmul_fuse_pass.py
  test/ir/pir/fused_pass/onednn/test_scale_matmul_fuse_pass.py
  test/ir/pir/fused_pass/onednn/test_shuffle_channel_detect_onednn_pass.py
  test/ir/pir/fused_pass/python/test_py_add_norm_fuse_pass.py
  test/legacy_test/prim_op_test.py
  test/legacy_test/test_adam_op.py
  test/legacy_test/test_momentum_op.py
Labels: contributor, HappyOpenSource

#71596 [XPU] bump XCCL to 3.0.2.5
  cmake/external/xpu.cmake
Labels: XPU

#71569 [XPU] support fp16 for group_norm_grad
  paddle/phi/backends/xpu/xpu3_op_list.cc
  paddle/phi/kernels/xpu/group_norm_grad_kernel.cc
  test/xpu/test_group_norm_op_xpu.py
Labels: XPU

#71246 【Hackathon 8th No.3】 clean oldIR for pipeline scheduler -part
  python/paddle/distributed/passes/pipeline_scheduler_pass/pipeline_1f1b.py
  python/paddle/distributed/passes/pipeline_scheduler_pass/pipeline_fthenb.py
  test/standalone_executor/test_standalone_executor_1f1b_plan.py
Labels: PaddlePaddle Hackathon, contributor

#71526 [XPU] support print runtime error log for xblas and bkcl
  paddle/phi/backends/CMakeLists.txt
  paddle/phi/backends/xpu/enforce_xpu.cc
  paddle/phi/backends/xpu/enforce_xpu.h
  paddle/phi/kernels/fusion/xpu/fc_xpu_kernel.cc
  paddle/phi/kernels/xpu/addmm_kernel.cc
  paddle/phi/kernels/xpu/xpu_api_wrapper.h
Labels: XPU

#71638 Rename prelnlayernorm_shift_partition_op to preln_layernorm_shift_partition_op
  paddle/fluid/inference/tensorrt/convert/preln_layernorm_shift_partition_op.cc
  paddle/fluid/inference/tensorrt/plugin/CMakeLists.txt
  paddle/fluid/inference/tensorrt/plugin/preln_layernorm_shift_partition_op.cu
  paddle/fluid/inference/tensorrt/plugin/preln_layernorm_shift_partition_op.h
Labels: contributor, HappyOpenSource

#71637 Fix typos silce slice
  paddle/fluid/framework/ir/auto_mixed_precision_pass.cc
  paddle/fluid/framework/ir/auto_mixed_precision_pass.h
  paddle/fluid/framework/ir/conv_bn_fuse_pass.cc
  paddle/fluid/framework/ir/conv_elementwise_add_act_fuse_pass.cc
  paddle/fluid/framework/ir/conv_elementwise_add_fuse_pass.cc
  paddle/fluid/framework/ir/cutlass_teller.h
  paddle/fluid/framework/ir/fc_gru_fuse_pass.cc
  paddle/fluid/framework/ir/graph_pattern_detector.cc
  paddle/fluid/framework/ir/graph_pattern_detector.h
  paddle/fluid/framework/ir/xpu/yolo_box_xpu_fuse_pass.cc
Labels: contributor, HappyOpenSource

#71641 [SOT] add Env Variable `SOT_CE_DEBUG_MODE`
  python/paddle/jit/sot/utils/__init__.py
  python/paddle/jit/sot/utils/envs.py
Labels: contributor

#71635 [XPU] replace xpu::where with xpu::nonzero_compute for nonzero kernel
  paddle/phi/kernels/xpu/nonzero_kernel.cc
Labels: XPU

#71642 c_split custom kernel remove ring_id
  paddle/phi/kernels/custom/c_split_kernel.cc
Labels: PaddlePaddle Hackathon, contributor

#71629 [Test] Add main block for unittest
  test/rnn/test_rnn_cells.py
Labels: contributor

#71467 【DCU】support dtk25 and put_along_axis
  paddle/phi/backends/gpu/rocm/rocm_helper.h
  paddle/phi/kernels/CMakeLists.txt
  paddle/phi/kernels/gpu/gelu_funcs.h
  paddle/phi/kernels/gpu/put_along_axis_grad_kernel.cu
  paddle/phi/kernels/gpu/weight_quantize_kernel.cu
  paddle/phi/kernels/impl/weight_quantize_kernel_gpu_impl.h
Labels: contributor

#71671 [SOT] Re-format `ObjectVariable` in builtin dispatch pattern
  python/paddle/jit/sot/opcode_translator/executor/variables/callable.py
  python/paddle/jit/sot/utils/__init__.py
  python/paddle/jit/sot/utils/utils.py
Labels: contributor

#71662 [Pybind] add `__eq__`、`__hash__` for `Place`
  paddle/fluid/pybind/place.cc
  test/legacy_test/test_tensor_place.py
Labels: contributor

#71686 [CodeStyle][Typos] fix `uncode`
  paddle/scripts/fast_install.sh
Labels: HappyOpenSource

#71691 [SOT][Guard] `np.bool` conversion error in `NumpyVariable.format_dtype` in numpy `1.20.0+`
  python/paddle/jit/sot/opcode_translator/executor/variables/basic.py
Labels: contributor

#71692 [SOT] Enable strict guard check in dy2st uts
  test/dygraph_to_static/CMakeLists.txt
Labels: contributor

#71432 [XPU] add grid sampler support.
  paddle/phi/backends/xpu/xpu3_op_list.cc
  test/xpu/test_grid_sampler_op_xpu.py
Labels: XPU

#71555 [Paddle Tensor 第二期 API支持 0-size Tensor] paddle.mean 支持 0-size tensor
  paddle/phi/kernels/funcs/reduce_function.h
  test/legacy_test/test_mean_op.py
Labels: contributor, HappyOpenSource Pro

#71480 Fix typo in python/paddle/base/unique_name.py
  python/paddle/base/unique_name.py
Labels: contributor, HappyOpenSource

#71680 Fix typos splitted split
  python/paddle/distributed/auto_parallel/static/operators/dist_embedding.py
  python/paddle/distributed/auto_parallel/static/operators/dist_pnorm.py
  python/paddle/distributed/auto_parallel/static/reshard_funcs/sub_to_global_mesh_func.py
  python/paddle/distributed/auto_parallel/static/utils.py
  python/paddle/distributed/communication/stream/all_to_all.py
  python/paddle/distributed/fleet/base/strategy_compiler.py
  python/paddle/distributed/passes/pass_utils.py
  python/paddle/distributed/passes/pipeline_scheduler_pass/pipeline_1f1b.py
  test/auto_parallel/semi_auto_parallel_moe_utils.py
Labels: contributor, HappyOpenSource

#71627 [XPU] feat: implement xpu pinned memory and sync load with pinned memory, split commit 1
  paddle/phi/api/include/tensor.h
  paddle/phi/api/lib/tensor.cc
  paddle/phi/common/memory_utils.cc
  paddle/phi/common/memory_utils.h
  paddle/phi/common/place.cc
  paddle/phi/common/place.h
  paddle/phi/core/memory/allocation/CMakeLists.txt
  paddle/phi/core/memory/allocation/allocator_facade.cc
  paddle/phi/core/memory/allocation/naive_best_fit_allocator.cc
  paddle/phi/core/memory/allocation/system_allocator.cc
  paddle/phi/core/memory/allocation/system_allocator.h
  paddle/phi/core/memory/allocation/xpu_ipc_allocator.cc
  paddle/phi/core/memory/allocation/xpu_pinned_allocator.cc
  paddle/phi/core/memory/allocation/xpu_pinned_allocator.h
  paddle/phi/kernels/memcpy_kernel.cc
Labels: XPU

#71726 [XPU] nonzero kernel use int64
  paddle/phi/kernels/xpu/nonzero_kernel.cc
Labels: XPU

#71729 [SOT][Faster Guard] `LengthMatchGuard` support dict
  paddle/fluid/pybind/sot/guards.cc
  python/paddle/jit/sot/opcode_translator/executor/variables/container.py
  test/sot/test_faster_guard.py
Labels: contributor

#71721 [XPU] feat: implement xpu pinned memory and sync load with pinned memory, split commit 2
  paddle/fluid/distributed/collective/xpu_async_load.cc
  paddle/fluid/distributed/collective/xpu_async_load.h
  paddle/fluid/framework/dlpack_tensor.cc
  paddle/fluid/framework/garbage_collector.cc
  paddle/fluid/framework/garbage_collector.h
  paddle/fluid/inference/api/analysis_predictor.cc
  paddle/fluid/pir/dialect/operator/utils/utils.cc
  paddle/fluid/pir/transforms/pd_op_to_kernel_pass.cc
  paddle/fluid/platform/init.cc
  paddle/phi/backends/xpu/xpu_context.cc
  paddle/phi/backends/xpu/xpu_context.h
  paddle/phi/core/memory/memcpy.cc
  paddle/phi/core/platform/device_context.cc
  paddle/phi/core/platform/device_context.h
  paddle/phi/core/utils/type_info.cc
  paddle/phi/core/utils/visit_place.h
  test/cpp/fluid/platform/init_test.cc
  test/xpu/test_xpu_async_offload_reload.py
  test/xpu/test_xpu_async_offload_reload_performance.py
Labels: XPU

#71757 [SOT][Faster Guard] clean `test_with_faster_guard`
  test/sot/test_01_basic.py
  test/sot/test_04_list.py
  test/sot/test_05_dict.py
  test/sot/test_07_unpack.py
  test/sot/test_12_for_loop.py
  test/sot/test_14_operators.py
  test/sot/test_15_slice.py
  test/sot/test_17_paddle_layer.py
  test/sot/test_18_tensor_method.py
  test/sot/test_builtin_bool.py
  test/sot/test_builtin_dispatch.py
  test/sot/test_builtin_map.py
  test/sot/test_builtin_zip.py
  test/sot/test_case_base.py
  test/sot/test_dtype.py
  test/sot/test_guard_outputs.py
  test/sot/test_guard_user_defined_fn.py
  test/sot/test_side_effects.py
Labels: contributor

#71762 [CINN] [New Hardware Update]:fix hip bugs
  cmake/cinn.cmake
  cmake/hip.cmake
  paddle/cinn/backends/codegen_device_util.cc
  paddle/cinn/backends/codegen_invoke_module.h
  paddle/cinn/hlir/dialect/operator/transforms/add_cinn_pass.cc
  paddle/cinn/runtime/hip/cinn_hip_runtime_source.h
  paddle/cinn/runtime/hip/hip_intrinsics.cc
  paddle/cinn/runtime/hip/hip_intrinsics_reduce.cc
  paddle/cinn/runtime/hip/hip_util.cc
  paddle/cinn/runtime/hip/hip_util.h
  paddle/cinn/runtime/intrinsic.h
Labels: contributor

#71661 custom kernel modify ring_id
  paddle/phi/kernels/custom/barrier_kernel.cc
  paddle/phi/kernels/custom/c_allreduce_kernel_impl.h
  paddle/phi/kernels/custom/c_broadcast_kernel.cc
  paddle/phi/kernels/custom/c_softmax_with_entropy_grad_kernel.cc
  paddle/phi/kernels/custom/global_gather_kernel.cc
  paddle/phi/kernels/custom/global_scatter_kernel.cc
  paddle/phi/kernels/custom/mp_allreduce_sum_kernel.cc
Labels: contributor

#71734 fix avx512 error
  cmake/simd.cmake
Labels: contributor

#71759 fix avx512 error
  cmake/simd.cmake
Labels: contributor

#71714 Fix typos in mp_layers.py
  python/paddle/distributed/fleet/layers/mpu/mp_layers.py
  python/paddle/distributed/fleet/layers/mpu/mp_ops.py
Labels: contributor, HappyOpenSource

#71713 Fix is_dataset_splitted is_dataset_split
  python/paddle/distributed/auto_parallel/api.py
  test/auto_parallel/pir/while_unittest_pir.py
Labels: contributor, HappyOpenSource

#71732 cherry-pick PR 71507 to release/3.0
  CMakeLists.txt
  cmake/flagcx.cmake
  paddle/common/flags.cc
  paddle/fluid/distributed/collective/CMakeLists.txt
  paddle/fluid/distributed/collective/process_group_flagcx.cc
  paddle/fluid/distributed/collective/process_group_flagcx.h
  paddle/fluid/pybind/CMakeLists.txt
  paddle/fluid/pybind/distributed_py.cc
  paddle/fluid/pybind/pybind.cc
  paddle/phi/CMakeLists.txt
  paddle/phi/backends/dynload/CMakeLists.txt
  paddle/phi/backends/dynload/dynamic_loader.cc
  paddle/phi/backends/dynload/dynamic_loader.h
  paddle/phi/backends/dynload/flagcx.cc
  paddle/phi/backends/dynload/flagcx.h
  paddle/phi/core/distributed/CMakeLists.txt
  paddle/phi/core/distributed/comm_context_manager.cc
  paddle/phi/core/distributed/comm_context_manager.h
  paddle/phi/core/distributed/flagcx_comm_context.cc
  paddle/phi/core/distributed/flagcx_comm_context.h
  paddle/phi/core/distributed/flagcx_tools.cc
  paddle/phi/core/distributed/flagcx_tools.h
  paddle/phi/core/enforce.h
  paddle/phi/core/utils/data_type.h
  python/paddle/__init__.py
  python/paddle/distributed/collective.py
  python/paddle/distributed/fleet/launch_utils.py
  python/paddle/distributed/parallel.py
Labels: contributor

#71540 优化LayerList类的insert函数
  python/paddle/nn/layer/container.py
  test/legacy_test/test_layerlist.py
Labels: contributor

#71448 paddle.distributed.all_to_all supports unequal split(#71429)
  paddle/fluid/distributed/collective/CMakeLists.txt
  paddle/fluid/distributed/collective/process_group.h
  paddle/fluid/distributed/collective/process_group_bkcl.cc
  paddle/fluid/distributed/collective/process_group_bkcl.h
  paddle/fluid/distributed/collective/process_group_custom.cc
  paddle/fluid/distributed/collective/process_group_custom.h
  paddle/fluid/distributed/collective/process_group_kernel_utils.cc
  paddle/fluid/distributed/collective/process_group_kernel_utils.h
  paddle/fluid/distributed/collective/process_group_nccl.cc
  paddle/fluid/distributed/collective/process_group_nccl.h
  paddle/fluid/distributed/collective/process_group_with_stream.h
  paddle/fluid/pybind/distributed_py.cc
  paddle/fluid/pybind/process_group_utils.h
  paddle/phi/core/distributed/check/CMakeLists.txt
  paddle/phi/core/distributed/check/bkcl_dynamic_check.cc
  paddle/phi/core/distributed/check/bkcl_dynamic_check.h
  paddle/phi/core/distributed/check/nccl_dynamic_check.cc
  paddle/phi/core/distributed/check/nccl_dynamic_check.h
  paddle/phi/core/distributed/check/static_check.cc
  paddle/phi/core/distributed/check/static_check.h
  paddle/phi/core/distributed/collective/process_group.h
  python/paddle/distributed/communication/all_to_all.py
  python/paddle/distributed/communication/stream/all_to_all.py
  test/collective/collective_alltoall_api_unequal_split_dygraph.py
  test/collective/test_collective_alltoall_api.py
  test/legacy_test/test_collective_api_base.py
  test/xpu/collective_alltoall_api_unequal_split_dygraph.py
  test/xpu/collective_alltoall_single_api_unequal_split_dygraph.py
  test/xpu/test_collective_alltoall_api_unequal_split.py
  test/xpu/test_collective_alltoall_single_api_unequal_split.py
  test/xpu/test_collective_api_base.py
  test/xpu/test_collective_base_xpu.py
Labels: XPU

#71763 [SOT] Optimize reason string
  python/paddle/jit/sot/opcode_translator/executor/variables/callable.py
Labels: contributor

#71424 [XPU] support set numa affinity
  python/paddle/distributed/utils/process_utils.py
Labels: XPU

#71780 Fix typos splitted split
  paddle/fluid/pir/transforms/gpu/horizontal_fuse_pass.cc
  paddle/phi/infermeta/spmd_rules/dim_trans.cc
  paddle/phi/infermeta/spmd_rules/dim_trans.h
  paddle/phi/infermeta/spmd_rules/flatten.cc
  paddle/phi/infermeta/spmd_rules/reshape.cc
  paddle/phi/infermeta/spmd_rules/split.cc
  paddle/phi/infermeta/spmd_rules/unbind.cc
  paddle/phi/kernels/onednn/split_kernel.cc
Labels: contributor, HappyOpenSource

#71791 [clean old comm]Revert "Revert old comm"
  paddle/fluid/operators/collective/c_allreduce_op.h
  paddle/fluid/operators/collective/c_gen_bkcl_id_op.cc
  paddle/fluid/operators/collective/c_gen_nccl_id_op.cc
  paddle/fluid/operators/collective/c_wait_comm_op.cc
  paddle/fluid/operators/collective/c_wait_compute_op.cc
  paddle/fluid/operators/collective/recv_v2_op.cu.cc
  paddle/fluid/operators/collective/send_v2_op.cu.cc
Labels: PaddlePaddle Hackathon, contributor

#71809 [XPU] gelu and gelu_grad support bfloat16 type
  paddle/phi/backends/xpu/xpu3_op_list.cc
  paddle/phi/kernels/xpu/gelu_grad_kernel.cc
  paddle/phi/kernels/xpu/gelu_kernel.cc
Labels: XPU

#70362 [SOT][Faster Guard] remove `RangeMatchGuard`
  paddle/fluid/pybind/jit.cc
  paddle/fluid/pybind/sot/guards.h
  python/paddle/jit/sot/opcode_translator/executor/guard.py
  python/paddle/jit/sot/opcode_translator/executor/variables/container.py
  test/sot/test_faster_guard.py
Labels: contributor

#71779 [XPU] support take_along_axis_grad in XPU
  paddle/phi/backends/xpu/xpu3_op_list.cc
  paddle/phi/kernels/xpu/take_along_axis_grad_kernel.cc
  test/xpu/test_take_along_axis_op_xpu.py
Labels: contributor

#71776 [XPU] fix integral type of scale and update flash_attn_grad
  cmake/external/xpu.cmake
  paddle/phi/backends/xpu/xpu3_op_list.cc
  paddle/phi/kernels/xpu/amp_kernel.cc
  paddle/phi/kernels/xpu/flash_attn_grad_kernel.cc
  paddle/phi/kernels/xpu/pool_grad_kernel.cc
  paddle/phi/kernels/xpu/scale_kernel.cc
  paddle/phi/kernels/xpu/squared_l2_norm_grad_kernel.cc
Labels: XPU

#71842 [Custom Device] Add PIR support for _npu_identity
  python/paddle/incubate/tensor/manipulation.py
Labels: contributor

#71810 forward compability for checkpoint
  paddle/fluid/pybind/generator_py.cc
Labels: XPU

#71795 [fluid_ops] clean push_dense
  paddle/fluid/operators/push_dense_op.cc
  paddle/fluid/operators/push_dense_op.h
  test/ir/pir/translator/CMakeLists.txt
  test/ir/pir/translator/test_push_dense_translator.py
Labels: PaddlePaddle Hackathon, contributor

#71792 [fluid_ops] clean pull_box_sparse
  paddle/fluid/operators/pull_box_sparse_op.cc
  paddle/fluid/operators/pull_box_sparse_op.h
  test/deprecated/legacy_test/CMakeLists.txt
  test/ir/pir/translator/test_pull_box_sparse_translator.py
  test/legacy_test/CMakeLists.txt
  test/legacy_test/test_boxps.py
Labels: PaddlePaddle Hackathon, contributor

#71756 [XPU] feat: implement xpu pinned memory and sync load with pinned memory, split commit 3
  paddle/fluid/pybind/eager.cc
  paddle/fluid/pybind/eager_math_op_patch.cc
  paddle/fluid/pybind/eager_method.cc
  paddle/fluid/pybind/eager_utils.cc
  paddle/fluid/pybind/imperative.cc
  paddle/fluid/pybind/io.cc
  paddle/fluid/pybind/place.cc
  paddle/fluid/pybind/pybind.cc
  paddle/fluid/pybind/tensor.cc
  paddle/fluid/pybind/tensor_py.h
  paddle/phi/core/memory/memcpy.cc
  python/paddle/__init__.py
  python/paddle/_typing/device_like.py
  python/paddle/base/__init__.py
  python/paddle/base/framework.py
  python/paddle/framework/__init__.py
  test/xpu/test_xpu_async_offload_reload.py
  test/xpu/test_xpu_pinned_memory.py
  test/xpu/test_xpu_share_memory.py
Labels: XPU

#71853 Revert Fix is_dataset_splitted is_dataset_split
  python/paddle/distributed/auto_parallel/api.py
  test/auto_parallel/pir/while_unittest_pir.py
Labels: contributor

#71794 [fluid_ops] clean pull_sparse_v2
  paddle/fluid/operators/pull_sparse_v2_op.cc
  paddle/fluid/operators/pull_sparse_v2_op.h
  test/ir/pir/translator/CMakeLists.txt
  test/ir/pir/translator/test_pull_sparse_v2_translator.py
Labels: PaddlePaddle Hackathon, contributor

#71846 [fluid_ops] clean test_fleet_base
  test/deprecated/legacy_test/CMakeLists.txt
  test/deprecated/legacy_test/test_fleet_base_2_deprecated.py
  test/deprecated/legacy_test/test_fleet_base_3_deprecated.py
  test/legacy_test/test_fleet_base_4.py
Labels: PaddlePaddle Hackathon, contributor

#71808 [fluid_ops] clean heter_listen_and_serv
  paddle/fluid/operators/pscore/heter_listen_and_serv_op.cc
  paddle/fluid/operators/pscore/heter_listen_and_serv_op.h
  test/cpp/fluid/framework/CMakeLists.txt
  test/cpp/fluid/framework/heter_pipeline_trainer_test.cc
  test/cpp/fluid/pscore/CMakeLists.txt
  test/cpp/fluid/pscore/heter_listen_and_server_test.cc
  test/deprecated/legacy_test/test_dist_fleet_heter_program_deprecated.py
Labels: PaddlePaddle Hackathon, contributor

#71852 [XPU] fix XPU linking error on Clang
  paddle/phi/kernels/custom/c_embedding_grad_kernel.cc
  paddle/phi/kernels/xpu/c_concat_kernel.cc
  paddle/phi/kernels/xpu/c_embedding_kernel_grad.cc
  paddle/phi/kernels/xpu/c_softmax_with_cross_entropy_kernel.cc
  paddle/phi/kernels/xpu/c_split_kernel.cc
  paddle/phi/kernels/xpu/embedding_grad_kernel.cc
  paddle/phi/kernels/xpu/reduce_sum_grad_kernel.cc
Labels: XPU

#71831 [clean old comm] clean dynamic_static_unified_comm part
  paddle/fluid/framework/new_executor/instruction/instruction_util.cc
  paddle/fluid/framework/new_executor/interpreter/stream_analyzer.cc
  paddle/fluid/framework/new_executor/new_executor_defs.cc
  paddle/fluid/framework/new_executor/new_executor_defs.h
  paddle/fluid/framework/new_executor/pir_interpreter.cc
  paddle/fluid/framework/new_executor/program_interpreter.cc
  paddle/fluid/inference/tensorrt/plugin/c_allreduce_op_plugin.cu
Labels: PaddlePaddle Hackathon, contributor

#71869 [XPU] test: add performance and load test for xpu async load
  test/xpu/test_xpu_async_offload_reload_loadtest.py
  test/xpu/test_xpu_async_offload_reload_performance.py
Labels: XPU

#71573 [XPU] support flashmask_attention
  paddle/phi/backends/xpu/xpu3_op_list.cc
  paddle/phi/kernels/xpu/flash_attn_grad_kernel.cc
  paddle/phi/kernels/xpu/flash_attn_kernel.cc
  test/xpu/test_flashmask_attention_op_xpu.py
Labels: XPU

#71872 [Fix] use `py_compile` for pyi file syntax check
  tools/gen_pybind11_stub.py
Labels: contributor, HappyOpenSource

#71860 [fluid_ops] clean send_and_recv
  paddle/fluid/operators/pscore/send_and_recv_op.cc
  test/cpp/fluid/pscore/CMakeLists.txt
  test/cpp/fluid/pscore/send_and_recv_op_cpu_test.cc
  test/cpp/fluid/pscore/send_and_recv_op_gpu_test.cc
  test/ir/pir/translator/CMakeLists.txt
  test/ir/pir/translator/test_send_and_recv_translator.py
Labels: PaddlePaddle Hackathon, contributor

#71886 Revert "[CINN] [New Hardware Update]:fix hip bugs #71762"
  cmake/cinn.cmake
Labels: contributor

#71883 [XPU] Support print runtime error log for bkcl
  paddle/fluid/distributed/collective/process_group_bkcl.cc
  paddle/fluid/platform/device/xpu/bkcl_helper.h
  paddle/phi/backends/xpu/enforce_xpu.cc
  paddle/phi/backends/xpu/enforce_xpu.h
  paddle/phi/core/distributed/bkcl_comm_context.cc
  paddle/phi/core/distributed/check/bkcl_dynamic_check.cc
  paddle/phi/core/distributed/comm_context_manager.cc
  paddle/phi/core/platform/collective_helper.cc
  paddle/phi/core/platform/device/xpu/bkcl_helper.h
  test/xpu/cpp/enforce_xpu_test.cc
Labels: XPU

#71564 [XPU] enable ut for 2 cards
  paddle/scripts/paddle_build.sh
  test/collective/fleet/dygraph_group_sharded_stage1_bf16.py
  test/legacy_test/test_run.py
  tools/xpu/disable_ut_xpu_kl3.local
  tools/xpu/multi_card_ut_xpu_kl3.local
Labels: XPU

#71879 [clean old comm]Remove dynamic_static_unified_comm
  paddle/common/flags.cc
  paddle/scripts/paddle_build.sh
Labels: PaddlePaddle Hackathon, contributor

#71921 add enable_nccl_dynamic_check/enable_bkcl_dynamic_check gflags
  paddle/common/flags.cc
  paddle/fluid/distributed/collective/process_group_bkcl.cc
  paddle/fluid/distributed/collective/process_group_nccl.cc
Labels: XPU

#71914 [fluid_ops] collective_transpiler.py
  python/paddle/distributed/ps/utils/collective_transpiler.py
Labels: contributor

#71918 [fluid_ops] Modify c_allreduce_sum in clip.py
  python/paddle/nn/clip.py
Labels: PaddlePaddle Hackathon, contributor

#71906 [fluid_ops] auto_parallel_sequence_parallel_optimization.py add all_reduce
  python/paddle/distributed/passes/auto_parallel_sequence_parallel_optimization.py
  python/paddle/distributed/passes/fuse_all_reduce.py
Labels: PaddlePaddle Hackathon, contributor

#71905 [fluid_ops] auto_parallel_grad_clip.py add all_reduce
  python/paddle/distributed/passes/allreduce_matmul_grad_overlapping.py
  python/paddle/distributed/passes/auto_parallel_grad_clip.py
Labels: PaddlePaddle Hackathon, contributor

#71904 [fluid_ops] pipeline_1f1b.py add all_reduce
  python/paddle/distributed/passes/pipeline_scheduler_pass/pipeline_1f1b.py
  python/paddle/distributed/passes/pipeline_scheduler_pass/pipeline_vpp.py
Labels: PaddlePaddle Hackathon, contributor

#71793 [fluid_ops] clean pull_gpups_sparse
  paddle/fluid/operators/pull_gpups_sparse_op.cc
  paddle/fluid/operators/pull_gpups_sparse_op.cu
  paddle/fluid/operators/pull_gpups_sparse_op.h
  test/ir/pir/translator/CMakeLists.txt
  test/ir/pir/translator/test_pull_gpups_sparse_translator.py
  test/legacy_test/test_pull_gpups_sparse_op.py
Labels: PaddlePaddle Hackathon, contributor

#71910 [fluid_ops]clean test_communicator_half_async
  test/collective/fleet/CMakeLists.txt
  test/collective/fleet/run_server_for_communicator_half_async.py
  test/collective/fleet/test_communicator_half_async.py
  test/legacy_test/CMakeLists.txt
  test/legacy_test/test_dist_fleet_minimize.py
Labels: PaddlePaddle Hackathon, contributor

#71738 [CI] Add approval
  .github/actions/check-bypass/action.yml
  .github/workflows/Approval.yml
  ci/check_approval.sh
Labels: skip-ci: sot

#70602 [CI] Add rerun
  .github/actions/rerun-workflow/action.yml
  .github/actions/rerun-workflow/rerun.sh
  .github/workflows/re-run.yml
Labels: skip-ci: sot

#71900 [SOT][Faster Guard] support `NumpyDtypeMatchGuard`
  paddle/fluid/pybind/jit.cc
  paddle/fluid/pybind/sot/guards.cc
  paddle/fluid/pybind/sot/guards.h
  python/paddle/jit/sot/opcode_translator/executor/variables/basic.py
  test/sot/test_faster_guard.py
Labels: contributor

#71946 Fix register_operators DEPS executor
  paddle/fluid/operators/CMakeLists.txt
Labels: contributor

#71954 [XPU] bfloat16 for fused_gemm_epilogue_grad
  paddle/phi/backends/xpu/xpu3_op_list.cc
  paddle/phi/kernels/funcs/fused_gemm_epilogue_xpu.h
  paddle/phi/kernels/fusion/xpu/fused_gemm_epilogue_grad_kernel.cc
  test/xpu/test_fused_gemm_epilogue_grad_op_xpu.py
Labels: XPU

#71820 [CINN][New Hardware Update] SYCL PR4: Add sycl runtime path
  cmake/cinn.cmake
  python/setup.py.in
  python/setup_cinn.py.in
  setup.py
Labels: contributor

#71806 [fluid_ops] clean distributed_push_sparse
  paddle/fluid/operators/pscore/distributed_push_sparse_op.cc
  paddle/fluid/operators/pscore/distributed_push_sparse_op.cu.cc
  paddle/fluid/operators/pscore/distributed_push_sparse_op.h
  test/deprecated/legacy_test/test_dist_fleet_a_sync_optimizer_auto_async_deprecated.py
  test/deprecated/legacy_test/test_dist_fleet_decay_deprecated.py
  test/distributed_passes/test_ps_trainer_pass.py
  test/ir/pir/translator/CMakeLists.txt
  test/ir/pir/translator/test_distributed_push_sparse_translator.py
Labels: PaddlePaddle Hackathon, contributor

#71903 [fluid_ops] clean send_barrier
  paddle/fluid/operators/pscore/send_barrier_op.cc
  test/deprecated/collective/fleet/test_communicator_sync_deprecated.py
  test/deprecated/legacy_test/test_dist_fleet_a_sync_optimizer_async.py
  test/deprecated/legacy_test/test_dist_fleet_a_sync_optimizer_sync.py
  test/legacy_test/test_dist_transpiler.py
Labels: PaddlePaddle Hackathon, contributor

#71104 【Auto-Parallel | Comm】fix communication hang issue on GPU-H(VPP)
  python/paddle/distributed/passes/pass_utils.py
  python/paddle/distributed/passes/pipeline_scheduler_pass/pipeline_1f1b.py
  python/paddle/distributed/passes/pipeline_scheduler_pass/pipeline_eager_1f1b.py
  python/paddle/distributed/passes/pipeline_scheduler_pass/pipeline_fthenb.py
  python/paddle/distributed/passes/pipeline_scheduler_pass/pipeline_pass_base.py
  python/paddle/distributed/passes/pipeline_scheduler_pass/pipeline_vpp.py
  python/paddle/distributed/passes/pipeline_scheduler_pass/pipeline_zero_bubble.py
Labels: contributor

#71865 [SOT] Support builtin function `super`
  python/paddle/jit/sot/opcode_translator/executor/opcode_executor.py
  python/paddle/jit/sot/opcode_translator/executor/variable_dispatch.py
  python/paddle/jit/sot/opcode_translator/executor/variables/__init__.py
  python/paddle/jit/sot/opcode_translator/executor/variables/basic.py
  python/paddle/jit/sot/opcode_translator/executor/variables/callable.py
  python/paddle/jit/sot/opcode_translator/executor/variables/container.py
  python/paddle/jit/sot/opcode_translator/executor/variables/iter.py
  test/sot/test_23_super.py
Labels: contributor

#71958 [CI] Fix approval bypass
  .github/workflows/Approval.yml
Labels: skip-ci: approval

#71966 [XPU] fix several unit tests
  paddle/phi/kernels/xpu/compare_kernel.cc
  paddle/phi/kernels/xpu/set_value_kernel.cc
  paddle/phi/kernels/xpu/stack_kernel.cc
  test/collective/fleet/dygraph_group_sharded_stage1_fp16.py
  test/collective/fleet/dygraph_group_sharded_stage2_bf16.py
  test/collective/fleet/dygraph_group_sharded_stage3_bf16.py
  test/indexing/test_getitem_appendix.py
  test/indexing/test_setitem_appendix.py
  tools/xpu/disable_ut_xpu_kl3.local
  tools/xpu/multi_card_ut_xpu_kl3.local
Labels: XPU

#71981 pack flagcx library into paddle whl
  paddle/fluid/pybind/pybind.cc
  python/env_dict.py.in
  python/paddle/distributed/fleet/launch_utils.py
  python/paddle/distributed/parallel.py
  python/paddle/jit/sot/utils/paddle_api_config.py
  python/setup.py.in
  setup.py
Labels: contributor

#71922 [fluid_ops] clean distributed_lookup_table
  paddle/fluid/operators/pscore/distributed_lookup_table_op.cc
  paddle/fluid/operators/pscore/distributed_lookup_table_op.cu.cc
  paddle/fluid/operators/pscore/distributed_lookup_table_op.h
  test/ir/pir/translator/test_distributed_lookup_table_translate.py
Labels: PaddlePaddle Hackathon, contributor

#71980 Add flagcx process group
  paddle/common/flags.cc
  paddle/fluid/distributed/collective/CMakeLists.txt
  paddle/fluid/distributed/collective/process_group_flagcx.cc
  paddle/fluid/distributed/collective/process_group_flagcx.h
Labels: contributor

#71984 [SOT] Use relative imports instead of absolute imports for some files
  python/paddle/jit/sot/opcode_translator/executor/variables/callable.py
  python/paddle/jit/sot/opcode_translator/executor/variables/container.py
  python/paddle/jit/sot/opcode_translator/executor/variables/iter.py
Labels: contributor

#70154 [SOT][Faster Guard] implement basic guard tree mechanism
  paddle/fluid/pybind/jit.cc
  paddle/fluid/pybind/sot/frame_proxy.h
  paddle/fluid/pybind/sot/guards.cc
  paddle/fluid/pybind/sot/guards.h
  python/paddle/jit/sot/opcode_translator/executor/executor_cache.py
  python/paddle/jit/sot/opcode_translator/executor/function_graph.py
  python/paddle/jit/sot/opcode_translator/executor/guard.py
  python/paddle/jit/sot/opcode_translator/executor/opcode_inline_executor.py
  python/paddle/jit/sot/opcode_translator/executor/tracker.py
  python/paddle/jit/sot/opcode_translator/executor/variables/base.py
  python/paddle/jit/sot/opcode_translator/executor/variables/basic.py
  test/sot/test_guard_tree.py
Labels: contributor
